### ISSUE TITLE
DRM Error, Amazon Kindle for PC Book.

### ISSUE THREAD

**Issue by bobloadmire** [apprenticeharper/DeDRM_tools#1]
Here is the error I'm seeing. http://puu.sh/gDCod/8226f3107f.png
Processing: B00I8XF5ME_EBOK.azw4...Failed
Complete:  Successes: 0, Failures: 1

Here is a box link to the book i'm trying to deDRM. https://www.dropbox.com/s/kw2ymt579m6yuz4/B00I8XF5ME_EBOK.azw4?dl=0

What am I doing wrong?

**Comment by apprenticeharper** [comment]
Impossible to say. The Windows tools probably produce a log somewhere which will give a clue, but Paul and Laura at Apprentice Alf's blog are more experienced at troubleshooting than I am.

**Comment by ElleKayEm** [comment]
Over on the blog, it was revealed this was a rented textbook.  The tools purposely do not work on these (or library books).

**Comment by bobloadmire** [comment]
They should probably make the error a little more verbose, because it was
not obvious that the refusal to decrypt rented books was an artificial
limitation.

IMO this is pretty lame because I have a rented book I can't view on touch
based Kindle, and if it was decrypted i could view it in touch based Adobe
PDF.

On Mon, Mar 23, 2015 at 12:48 PM, ElleKayEm <notifications@github.com>
wrote:

> Over on the blog, it was revealed this was a rented textbook. The tools
> purposely do not work on these (or library books).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apprenticeharper/DeDRM_tools/issues/1#issuecomment-85166032>
> .
>



-- 
- Brad Stewart

**Comment by ElleKayEm** [comment]
I agree that it would be nice to have a clear error message.  I know that it is mentioned on the blog's FAQs page that the tools don't work on rented books or library books.

As for it being lame, we'll have to disagree.  The DRM is what makes it a rental.  If you could remove the DRM, the rental would never end.  You can't use it exactly how you'd like, but you saved money renting instead of buying (similar to physical books).

**Comment by bobloadmire** [comment]
I see exactly what you are saying but that argument doesn't make sense in
it's current context. When you bought a book, you agreed to only be able to
view it on Amazon's platform and you are circumventing that as well, so you
are violating ToS either way.

On Mon, Mar 23, 2015 at 2:03 PM, ElleKayEm <notifications@github.com> wrote:

> I agree that it would be nice to have a clear error message. I know that
> it is mentioned on the blog's FAQs page that the tools don't work on rented
> books or library books.
>
> As for it being lame, we'll have to disagree. The DRM is what makes it a
> rental. If you could remove the DRM, the rental would never end. You can't
> use it exactly how you'd like, but you saved money renting instead of
> buying (similar to physical books).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apprenticeharper/DeDRM_tools/issues/1#issuecomment-85196215>
> .
>



-- 
- Brad Stewart

**Comment by SchnWalter** [comment]
This tool is about the freedom to read the books you bought on any device you feel like. And by bought I mean clicking on a button labeled "buy this book" and not "rent this book". And if it happens that by clicking a "buy this book" button you actually rent the book - like in some cases - then... this is a whole different issue and it is not about freedom...

It never was and never will be about intentionally violating the ToS. It just happens that by exercising your freedom rights you might be violating parts of the ToS (_in some situations_), but this is not the intent.

**Comment by bobloadmire** [comment]
Well then I'm curious why this tool is about reading the books you bought
it n any device but those who rent should be denied that same luxury? Why
can't I read the books I rented on any device?

It doesn't make any sense, and in the eyes if the law you violate the ToS
in the same way whether you buy or rent.

**Comment by hendersj** [comment]
If you borrow/rent something, it isn't yours.  If you buy it, it is.  It's that simple.

**Comment by bobloadmire** [comment]
Well this is getting philosophical now. The only difference between owning
and renting is a time duration which isn't related in anyway to how someone
should be able to view a document.

If you want to go further, you don't ever own a book unless you wrote it
your self, you merely have a hard copy of some one else's IP.

**Comment by hendersj** [comment]
It's not philosophical, it's practical - and a bug here isn't the right place to have that debate. In some jurisdictions, the buyer has a right to make a backup and stripping the DRM for that purpose isn't against the law - but only on the condition that the item was purchased, not borrowed.

In the end, the decision on what to implement is the decision of the software author. The author of this code has done us a service, and has assumed some risk, and they are fully justified in deciding how much risk they're willing to take.

**Comment by bobloadmire** [comment]
The author of this program is free to do what ever he/she wants.

I just irked me to find out this was an artificial limitation because it
doesn't protect the author legally or morally.

But it is what it is. I still have to use a fucking mouse with my tablet to
read this thing lol.

On Tue, Mar 24, 2015 at 10:06 AM, hendersj <notifications@github.com> wrote:

> It's not philosophical, it's practical - and a bug here isn't the right
> place to have that debate. In some jurisdictions, the buyer has a right to
> make a backup and stripping the DRM for that purpose isn't against the law
> - but only on the condition that the item was purchased, not borrowed.
>
> In the end, the decision on what to implement is the decision of the
> software author. The author of this code has done us a service, and has
> assumed some risk, and they are fully justified in deciding how much risk
> they're willing to take.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apprenticeharper/DeDRM_tools/issues/1#issuecomment-85600274>
> .
>



-- 
- Brad Stewart

**Comment by hendersj** [comment]
The author of the code has apparently judged differently than you have, and from their standpoint, that's the only opinion that matters.

**Comment by ElleKayEm** [comment]
Wow, I just wanted to let Harper know that this isn't an issue, that it is a case of things working as designed.
----------------------
bobloadmire,
I understand that you rented the book, you're willing to lose access to it after a certain time period to save some money, and you just want to use it better during the time you need it.  You should be irked at Amazon for this.  They should make their reading software work better on more devices.

If this tool removed DRM from rental books, then anyone could buy the book for the price of the rental.  In the case of library books, get them for free.  This tool is for your personal use on books you OWN.  This does not violate copyright.  Allowing people to keep books they've only rented or borrowed would.

**Comment by apprenticeharper** [comment]
Closed. Not a bug.
