### ISSUE TITLE
DeDRM Tools inconsistent

### ISSUE THREAD

**Issue by PapaQuebec** [apprenticeharper/DeDRM_tools#100]
Hi.
Firstly thanks for such a fabulous piece of software. I purchase dozens of books from Amazon but hate reading in the Kindle app because of it's limited choice of fonts/text sizes/margin options etc etc etc.

I cant utilise my favourite reader app (FB Reader) without first removing DRM. Up till now I'd been using a proprietary DRM removal tool but that stopped working a few weeks ago, so DeDRM is a real boon.

My issue is that while it works perfectly on my system (Win7 Ultimate SP1 x64) it wont work on any of my friends systems - I've only tried three and they are using Win 10 x64. Books are imported but retain DRM (as you're informed when you attempt conversion in Calibre)

Are there issues with Windows 10? Or is there anything you can recommend to solve the issue

Many thanks

PapaQuebec

**Comment by ElleKayEm** [comment]
No issues with Windows 10 and the DeDRM tools or calibre.  But they do need to use Kindle for PC downloaded from the Amazon site, not the Windows store Kindle app.  Have them post an import log.

**Comment by PapaQuebec** [comment]
I'm not sure where they obtained their version of Kindle for PC.
I'll ask them to uninstall and then source from Amazon and then reinstall and try.

I'll get back to you with the result

Thanks for your input - appreciated

**Comment by apprenticeharper** [comment]
Closed. If your friends are still having a problem, please open a new issue with an import log.
