### ISSUE TITLE
DeDRM could not be removed.

### ISSUE THREAD

**Issue by fbafbafba** [apprenticeharper/DeDRM_tools#1000]
Hey everyone. I've failed to decrypt an ebook I've just bought for my studies. Maybe someone could help - I would appreciate it a lot. Thanks in advance!

Below you can find the debug log. I'm using Calibre on a Surface Pro 7 and downloaded the eBook from the usb download section from the amazon webpage.

calibre Debug log
calibre 4.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.643076923 x 133.900578035
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.56] splash screen shown
[0.56] Initializing db...
[0.56] db initialized
[0.56] Constructing main UI...
[2.25] main UI initialized...
[2.25] Hiding splash screen
[8.45] splash screen hidden
[8.45] Started up in 8.45 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xe3\x8a\x9d\xa2A\xa4\xd1.~\x1d,\x15S\x0c+\xdf\xde\xe6pZ\xfb\xc1>)m\xba\x11a8\x9c\xb2\xcf', 'C:\\Users\\user_\\Downloads\\Corporate Social Responsibility.azw3']
DeDRM v6.6.3: Trying to decrypt Corporate Social Responsibility.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Corporate Social Responsibility
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\user_\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\user_\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '486395291' and UserName '757365725f'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Corporate Social Responsibility
Got DSN key from database default_key_1
Found 3 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Corporate Social Responsibility to db in: 0.3
Added 1 books in 1.7 seconds

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) and enter its serial number into the DeDRM plugin customization.

**Comment by fbafbafba** [comment]
Hey, thank you for your fast reply. All options beside "readme" are greyed out in the navigation menu of the download section. How can I download the book as an E-ink kindle? 

Thank you in advance :)

**Comment by ElleKayEm** [comment]
If you don't have an E-ink Kindle on your account, then you can download the book via Kindle for PC version 1.24 or earlier.  You'll also need to prevent KFX downloads.  Or you can add the KFX Input plugin and downgrade calibre to version 4.5.  Method 1, 2, or 4 here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by fbafbafba** [comment]
Thank you very much! Method 1 worked perfect for me! I had to check some SHA-1 hashs but finally found the right version.

I really appreciate your fast and detailed help! Have a nice weekend :)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
