### ISSUE TITLE
Cannot remove Kindle DRM

### ISSUE THREAD

**Issue by Kindle-Perplexed** [apprenticeharper/DeDRM_tools#1014]
[tmpo2iq45.txt](https://github.com/apprenticeharper/DeDRM_tools/files/4238807/tmpo2iq45.txt)

Windows 10 Home
Kindle book downloaded via "Download and transfer via USB" for reading on PC
FYI: there is no option to download eink.

**Comment by ElleKayEm** [comment]
If you don't have an E-ink Kindle on your Amazon account, then you will need to download the book with Kindle for PC 1.24 or earlier.  See this post for details:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Kindle-Perplexed** [comment]
That works wonders! Many thanks @ElleKayEm !!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
