### ISSUE TITLE
Remove DRM with Kobo Plus

### ISSUE THREAD

**Issue by winterhard** [apprenticeharper/DeDRM_tools#1018]
Is there a way to remove DRM from Kobo Plus subscription books? Would love to read them on Kindle instead of phone.

**Comment by ElleKayEm** [comment]
These tools are intended for purchased books.

**Comment by winterhard** [comment]
Thanks. I didn't realize Kobo Plus is a subscription service so you don't actually own a book. I canceled my subscription and will stick with Kindel for a while.
