### ISSUE TITLE
DeDRM is not working properly

### ISSUE THREAD

**Issue by xyzmary2001** [apprenticeharper/DeDRM_tools#102]
I installed it and I tried to remove DRM from a book bought an Amazon. I've got an error - this book cannot be converted - DRM Locked (or something similar). What should I do?

**Comment by ElleKayEm** [comment]
Post an import log.  See the FAQs page at the blog for instructions:

https://apprenticealf.wordpress.com/2011/01/17/frequently-asked-questions-about-the-drm-removal-tools/

**Comment by apprenticeharper** [comment]
Closed. Please open a new issue with an import log if you're still having problems.
