### ISSUE TITLE
Could not decrypt book

### ISSUE THREAD

**Issue by skipmeister123** [apprenticeharper/DeDRM_tools#1023]
calibre 4.12 [64bit] embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && Goodreads (1, 4, 0) && Goodreads Sync (1, 14, 2) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
...
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing book.kfx
Gather KFX-ZIP (from KFX Input): Gathered 9 file(s) as C:\Users\user\AppData\Local\Temp\calibre_gdi5ap\kp pdfg.kfx-zip
DeDRM v6.7.0: Trying to decrypt kppdfg.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: kppdfg
Found 2 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.7.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\user\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\user\AppData\Local\Amazon\Kindle\storage\ .kinf2018
Decrypted key file using IDString 'xxxxx' and UserName 'xxxxx'
DeDRM v6.7.0: Found 1 new key
Decrypting KFX-ZIP ebook: kppdfg
Got DSN key from database default_key_1
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/...master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
File "calibre_plugins.dedrm.__init__", line 625, in run
File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/...master/FAQs.md
Package KFX (from KFX Input) 1.31.0: Packaging C:\Users\user\AppData\Local\Temp\calibre_gdi5ap\kp pdfg.kfx-zip
Processing container: CR!14R399BYDX1R950HXBRCXX5TS2ZQ.kfx
Processing container: CR!2TFQNVWDV93R95XGAKN0EXQMBHVV.kfx
Processing container: CR!43S9K29DQ96G99Q3R04WHNKMCXJ9.kfx
Processing container: CR!4C9E9K6VNH0NQCNQB4B3V95Y4137.kfx
Processing container: CR!DGSJ3VMYHS4QV86XXHM36T7Q6RJX.kfx
Processing container: CR!TGHP5TD6Z944D8N41HDMHSC56E17.kfx
Processing container: book.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
File "calibre_plugins.kfx_input.package_filetype", line 21, in run
File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container book.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\user\AppData\Local\Temp\calibre_gdi5ap\yp f9sm_add_books\0\book.kfx-zip
Added book to db in: 6.0
Added 1 books in 7.7 seconds

**Comment by ElleKayEm** [comment]
Go back to Kindle for PC 1.24 or earlier.

**Comment by skipmeister123** [comment]
I just pulled this right off an actual Kindle.

**Comment by ElleKayEm** [comment]
That won't work for KFX format books.  If it's an E-ink Kindle, you could get the book from the website for "download & transfer for USB."  Put the Kindle's serial number into the DeDRM plugin's customization if you haven't already.

**Comment by skipmeister123** [comment]
Got it. Thanks.

**Comment by ElleKayEm** [comment]
You can close the issue if you're all set.
