### ISSUE TITLE
DRM Removal not working.

### ISSUE THREAD

**Issue by safdagwe** [apprenticeharper/DeDRM_tools#1029]
Linux Mint 19.3
Calibre  4.12.0
DeDRM_tools_6.7.0.zip

Hello 

I am a newbie and maybe I have done something wrong? This is the first time I bought a book on amazon and I download it with an old version 1.16 kindle for pc https://kindle-for-pc.en.uptodown.com/windows/versions on my laptop. I do not own a kindle device and want to read to book on my pocketbook device. After I downloaded the ebook in azw format, I loaded it into Calibre but the conversion is not working. The DeDRM tools are installed. 

here ist the output:

Buch 1 von 1 (Divine Or Demoniac?: Spiritual Movements and the Enemies Within) konvertieren
Conversion options changed from defaults:
  output_profile: u'cybook_opus'
  verbose: 2
  read_metadata_from_opf: u'/tmp/calibre_4.12.0_tmp_AxWlEO/50RxT3.opf'
  cover: u'/tmp/calibre_4.12.0_tmp_AxWlEO/TDZZ0Q.jpeg'
Resolved conversion options
calibre version: 4.12.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/tmp/calibre_4.12.0_tmp_AxWlEO/TDZZ0Q.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f42a9b5ec90>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.CybookOpusOutput object at 0x7f42a9a28050>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/tmp/calibre_4.12.0_tmp_AxWlEO/50RxT3.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on /tmp/calibre_4.12.0_tmp_AxWlEO/qAEaJ2.azw
Found KF8 MOBI of type u'standalone'
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
DRMError: Divine Or Demoniac?: Spiritual Movements and the Enemies Within

How can this be solved??

Thank you

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre, not during conversion.  Post a log from adding a book:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by safdagwe** [comment]
Thanks for the answer. Meanwhile I found what went wrong. The key was missing because I downloaded the book on another laptop with OS Windows and copied it to this laptop with OS Linux. After installing Calibre on the windows laptop the key was automatically transferred to calibre. Is there a known way to read the key from kindle for pc software? 
Best regards

**Comment by ElleKayEm** [comment]
Each installation of K4PC has its own unique key stored in an encrypted file.
