### ISSUE TITLE
AZW books fail to remove DRM for Kobo

### ISSUE THREAD

**Issue by RichyH67** [apprenticeharper/DeDRM_tools#103]
Just bought a series of books from Amazon (Kindle books) and wanted to put them on my Kobo touch device. The Calibre plugin installed fine (using 64-bit Calibre) but Calibre won't convert and send to the Kobo because it says the book has DRM, meaning the plugin hasn't worked?

calibre Debug log
calibre 2.56 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 5.42 seconds with 11 books
Storage number map:
{(7L, 0L): [(3L, 'C')],
 (7L, 1L): [(1L, 'D')],
 (7L, 2L): [(1L, 'H')],
 (7L, 3L): [(1L, 'M')],
 (7L, 4L): [(1L, 'I')],
 (7L, 5L): [(1L, 'J')],
 (7L, 6L): [(1L, 'K')]}
Storage number for USBSTOR\DISK&VEN_KOBO&PROD_EREADER-3.19.576&REV_0110\N905J35204800&0: StorageDeviceNumber(type=7L, number=3L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x2237 product_id=0x4163 bcd=0x110 devid=usb\vid_2237&pid_4163&rev_0110 devinst=21)
{u'drive_letters': ['M'],
 u'pnp_id_map': {'M': u'\\\\?\\usbstor#disk&ven_kobo&prod_ereader-3.19.576&rev_0110#n905j35204800&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'M': (3L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 KoboTouch:books - oncard='None'
DEBUG:    0.0 KoboTouch:books - oncard='None', prefix='M:\'
DEBUG:    0.0 Kobo device: Kobo Touch
DEBUG:    0.0 Version of driver: (2, 1, 11) Has kepubs: True
DEBUG:    0.0 Version of firmware: (3, 19, 5761) Has kepubs: True
DEBUG:    0.0 Firmware supports cover image tree: True
DEBUG:    0.0 KoboTouch:books - opts.extra_customization= [u'', False, False, False, False, False, False, False, False, False, False, True, u'']
DEBUG:    0.0 KoboTouch:books - prefs['manage_device_metadata']= manual
DEBUG:    0.0 KoboTouch:books - set_debugging_title to ''
DEBUG:    0.0 KoboTouch:books - length bl=0
DEBUG:    0.2 KoboTouch:books - length bl after sync=57
DEBUG:    0.2 KoboTouch:books - reading device database
DEBUG:    0.2 Database Version=125
DEBUG:    0.2 KoboTouch:books - shelf list: {REMOVED BY ME - irrelivant and intrusive info!}
DEBUG:    0.2 KoboTouch:books - query= SELECT Title, Attribution, DateCreated, ContentID, MimeType, ContentType, ImageID, ReadStatus, ___ExpirationStatus, FavouritesIndex, Accessibility, IsDownloaded, Series, SeriesNumber, ___UserID, ExternalId FROM content  where BookID is Null  and ((Accessibility = -1 and IsDownloaded in ('true', 1 )) or (Accessibility in (1,2) and IsDownloaded in ('true', 1))       ) and not ((___ExpirationStatus=3 or ___ExpirationStatus is Null) and ContentType = 6) AND (externalId IS NULL OR externalId = '') AND contentId NOT LIKE 'file:///mnt/sd/%'
Job: 2 Set library information finished
No details available.
Job: 1 Get device information finished
No details available.
DEBUG:    0.6 KoboTouch:books - about to sync_booklists
DEBUG:    0.6 USBMS: starting sync_booklists
DEBUG:    0.7 USBMS: finished sync_booklists
DEBUG:    0.7 KoboTouch:books - have done sync_booklists
DEBUG:    0.7 KoboTouch:books - end - oncard='None'
DEBUG:    0.7 KoboTouch:books - oncard='carda'
DEBUG:    0.7 KoboTouch:books - Asked to process 'carda', but do not have one!
DEBUG:    0.7 KoboTouch:books - oncard='cardb'
DEBUG:    0.7 KoboTouch:books - Asked to process 'cardb', but do not have one!
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 57
DeviceJob: set_books_in_library finished: time= 0.00800013542175
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Job: 4 Upload 0 books to device started
DEBUG:    8.8 KoboTouch:upload_books - 0 books
DEBUG:    8.8 KoboTouch:upload_books - files= []
DEBUG:    8.8 USBMS: uploading 0 books
DEBUG:    8.8 USBMS: finished uploading 0 books
DeviceJob: 4 Upload 0 books to device done, calling callback
DeviceJob: set_books_in_library: books to process= 57
DeviceJob: set_books_in_library finished: time= 0.00300002098083
DeviceJob: 4 Upload 0 books to device callback returned
Job: 5 Send metadata to device started
DEBUG:    8.9 KOBO:sync_booklists - start
DEBUG:    8.9 KoboTouch:update_device_database_collections - oncard='main'
DEBUG:    8.9 KoboTouch:update_device_database_collections - set_debugging_title to ''
DEBUG:    8.9 KoboTouch:update_device_database_collections - Finished 
DEBUG:    8.9 USBMS: starting sync_booklists
Job: 4 Upload 0 books to device finished
No details available.
Worker Launch took: 0.167000055313
Job: 6 Convert book 1 of 1 (Percy Jackson and the Lightning Thief (Book 1) (Percy Jackson And The Olympians)) finished
Convert book 1 of 1 (Percy Jackson and the Lightning Thief (Book 1) (Percy Jackson And The Olympians))
	Resolved conversion options
	calibre version: 2.56.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Richard\\AppData\\Local\\Temp\\calibre_jih8ox\\9a7jot.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000000014A1E80>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x00000000051A05F8>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Richard\\AppData\\Local\\Temp\\calibre_jih8ox\\cjvivj.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Richard\AppData\Local\Temp\calibre_jih8ox\op4zjf.azw
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Percy Jackson and the Lightning Thief (Book 1) (Percy Jackson And The Olympians) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 190, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 31, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1057, in run
	  File "site-packages\calibre\customize\conversion.py", line 241, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 43, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 81, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 144, in check_for_drm
	calibre.ebooks.DRMError: Percy Jackson and the Lightning Thief (Book 1) (Percy Jackson And The Olympians)

DEBUG:   30.8 USBMS: finished sync_booklists
DEBUG:   30.8 KOBO:sync_booklists - end
DeviceJob: 5 Send metadata to device done, calling callback
DeviceJob: 5 Send metadata to device callback returned
Job: 7 Upload 0 books to device started
DEBUG:   30.8 KoboTouch:upload_books - 0 books
DEBUG:   30.8 KoboTouch:upload_books - files= []
DEBUG:   30.8 USBMS: uploading 0 books
DEBUG:   30.8 USBMS: finished uploading 0 books
DeviceJob: 7 Upload 0 books to device done, calling callback
DeviceJob: set_books_in_library: books to process= 57
DeviceJob: set_books_in_library finished: time= 0.00399994850159
DeviceJob: 7 Upload 0 books to device callback returned
Job: 9 Send metadata to device started
DEBUG:   30.9 KOBO:sync_booklists - start
DEBUG:   30.9 KoboTouch:update_device_database_collections - oncard='main'
DEBUG:   31.0 KoboTouch:update_device_database_collections - set_debugging_title to ''
DEBUG:   31.0 KoboTouch:update_device_database_collections - Finished 
DEBUG:   31.0 USBMS: starting sync_booklists
DEBUG:   31.0 USBMS: finished sync_booklists
DEBUG:   31.0 KOBO:sync_booklists - end
DeviceJob: 9 Send metadata to device done, calling callback
DeviceJob: 9 Send metadata to device callback returned
Job: 8 Upload 0 books to device started
DEBUG:   31.0 KoboTouch:upload_books - 0 books
DEBUG:   31.0 KoboTouch:upload_books - files= []
DEBUG:   31.0 USBMS: uploading 0 books
DEBUG:   31.0 USBMS: finished uploading 0 books
DeviceJob: 8 Upload 0 books to device done, calling callback
DeviceJob: set_books_in_library: books to process= 57
DeviceJob: set_books_in_library finished: time= 0.00500011444092
DeviceJob: 8 Upload 0 books to device callback returned
Job: 10 Send metadata to device started
DEBUG:   31.1 KOBO:sync_booklists - start
DEBUG:   31.1 KoboTouch:update_device_database_collections - oncard='main'
DEBUG:   31.1 KoboTouch:update_device_database_collections - set_debugging_title to ''
DEBUG:   31.1 KoboTouch:update_device_database_collections - Finished 
DEBUG:   31.1 USBMS: starting sync_booklists
DEBUG:   31.2 USBMS: finished sync_booklists
DEBUG:   31.2 KOBO:sync_booklists - end
DeviceJob: 10 Send metadata to device done, calling callback
DeviceJob: 10 Send metadata to device callback returned
Job: 5 Send metadata to device finished
No details available.
Job: 7 Upload 0 books to device finished
No details available.
Job: 10 Send metadata to device finished
No details available.
Job: 8 Upload 0 books to device finished
No details available.
Job: 9 Send metadata to device finished
No details available.
Job: 11 Upload 0 books to device started
DEBUG:   45.3 KoboTouch:upload_books - 0 books
DEBUG:   45.3 KoboTouch:upload_books - files= []
DEBUG:   45.3 USBMS: uploading 0 books
DEBUG:   45.3 USBMS: finished uploading 0 books
DeviceJob: 11 Upload 0 books to device done, calling callback
DeviceJob: set_books_in_library: books to process= 57
DeviceJob: set_books_in_library finished: time= 0.00399994850159
DeviceJob: 11 Upload 0 books to device callback returned
Job: 12 Send metadata to device started
DEBUG:   45.3 KOBO:sync_booklists - start
DEBUG:   45.4 KoboTouch:update_device_database_collections - oncard='main'
DEBUG:   45.4 KoboTouch:update_device_database_collections - set_debugging_title to ''
DEBUG:   45.4 KoboTouch:update_device_database_collections - Finished 
DEBUG:   45.4 USBMS: starting sync_booklists
DEBUG:   45.4 USBMS: finished sync_booklists
DEBUG:   45.4 KOBO:sync_booklists - end
DeviceJob: 12 Send metadata to device done, calling callback
DeviceJob: 12 Send metadata to device callback returned
Job: 12 Send metadata to device finished
No details available.
Job: 11 Upload 0 books to device finished
No details available.
Worker Launch took: 0.160000085831
Job: 13 Convert book 1 of 1 (Percy Jackson and the Lightning Thief (Book 1) (Percy Jackson And The Olympians)) finished
Convert book 1 of 1 (Percy Jackson and the Lightning Thief (Book 1) (Percy Jackson And The Olympians))
	Resolved conversion options
	calibre version: 2.56.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Richard\\AppData\\Local\\Temp\\calibre_jih8ox\\qdhdfg.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000000001491E80>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x00000000051A05F8>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Richard\\AppData\\Local\\Temp\\calibre_jih8ox\\wfiu6f.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Richard\AppData\Local\Temp\calibre_jih8ox\juk7yt.azw
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Percy Jackson and the Lightning Thief (Book 1) (Percy Jackson And The Olympians) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 190, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 31, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1057, in run
	  File "site-packages\calibre\customize\conversion.py", line 241, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 43, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 81, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 144, in check_for_drm
	calibre.ebooks.DRMError: Percy Jackson and the Lightning Thief (Book 1) (Percy Jackson And The Olympians)

Job: 14 Upload 0 books to device started
DEBUG:   49.4 KoboTouch:upload_books - 0 books
DEBUG:   49.4 KoboTouch:upload_books - files= []
DEBUG:   49.4 USBMS: uploading 0 books
DEBUG:   49.4 USBMS: finished uploading 0 books
DeviceJob: 14 Upload 0 books to device done, calling callback
DeviceJob: set_books_in_library: books to process= 57
DeviceJob: set_books_in_library finished: time= 0.00300002098083
DeviceJob: 14 Upload 0 books to device callback returned
Job: 15 Send metadata to device started
DEBUG:   49.5 KOBO:sync_booklists - start
DEBUG:   49.5 KoboTouch:update_device_database_collections - oncard='main'
DEBUG:   49.5 KoboTouch:update_device_database_collections - set_debugging_title to ''
DEBUG:   49.5 KoboTouch:update_device_database_collections - Finished 
DEBUG:   49.5 USBMS: starting sync_booklists
Job: 14 Upload 0 books to device finished
No details available.
DEBUG:   49.6 USBMS: finished sync_booklists
DEBUG:   49.6 KOBO:sync_booklists - end
DeviceJob: 15 Send metadata to device done, calling callback
DeviceJob: 15 Send metadata to device callback returned
Job: 15 Send metadata to device finished
No details available.

**Comment by ElleKayEm** [comment]
DRM removal happens when you first import the book, not during conversion.  You'll need to post an import log.

**Comment by RichyH67** [comment]
Apologies. Anyway, issue resolved. For some reason, the plugin had become disabled. I wonder if Windows 10 did that?
