### ISSUE TITLE
Unable to DeDRM epub from ADE

### ISSUE THREAD

**Issue by nicolaslecle40** [apprenticeharper/DeDRM_tools#1032]
Hello,

I bought 2 books on a local digital library instead of amazon kindle bookstore. The books are on epub format and I needed to open them with ADE (acsm file initialy dowloaded).

I tried to DeDRM them with Calibre and DeDRM 6.7.0 plugin but it fails.

I tried again in debug mode and the log file is attached.

I'm using Windows 10, Calibre 4.12 and DeDRM 6.7.0.

Has anyone a solution ?

Thanks

[tmpqqljac.txt](https://github.com/apprenticeharper/DeDRM_tools/files/4365068/tmpqqljac.txt)

**Comment by ElleKayEm** [comment]
Looks like the book is successfully DeDRMed but calibre cannot save it.  Normally the book would still be saved to calibre's library even if the DRM wasn't removed.

According to calibre's creator, this is typically from an antivirus program blocking calibre from accessing its database. Either disable it or exclude the calibre library folder from its scans.

**Comment by nicolaslecle40** [comment]
Hello,

Thanks for your answer. 

I run calibre (portable version) from my Synology NAS, so we can access it from various computer in the family.

It appears that windows block any modification from a program running from a mapped network.

I simply copy past my calibre on my C drive and everything worked fine directly. I didn't need to deactivate my antivirus.

Thanks for your help 👍

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
