### ISSUE TITLE
DRM not removed

### ISSUE THREAD

**Issue by Essi67** [apprenticeharper/DeDRM_tools#1033]
Hi

I tried to remove the drm on a book from google play. I can read the book in Adope Digital Edition. I have previously removed drm on Calibre using the dedrm plugin.

Here is my log. It seems like its not trying to dedrm.

Any help is very much appreciated.

C:\Users\kjeld>calibre-debug -g
calibre 4.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 111.923870968 x 112.110344828
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
[2.03] main UI initialized...
[2.03] Hiding splash screen
[2.55] splash screen hidden
[2.55] Started up in 2.55 seconds with 25 books
Added Sword of Destiny-epub to db in: 0.2
Added 1 books in 0.6 seconds

/Kjeld

**Comment by ElleKayEm** [comment]
Is the file you imported into calibre the actual epub?  Or just the acsm file?

**Comment by Essi67** [comment]
Hi ElleKayEm

You are totally right about the file type. It works fine now when I use the ePub file from Adope. 

Thanks a lot :-)

/Kjeld
