### ISSUE TITLE
FileOpen Plugin: Plan for support?

### ISSUE THREAD

**Issue by the-researcher** [apprenticeharper/DeDRM_tools#104]
Hi!

I'm wondering if there is any plan on supporting the FileOpen Plugin through DeDRM_tools. I've been looking for a solution after reviewing I[heart]cabbages' work on De-DRM solutions, but they don't seem to work for my problem.

Specifically, I have some documents that I'd like to view on my phone and tablet, but the **FileOpen plugin** is being unhelpful. I don't see any reference to FileOpen in your documentation, but I may have  missed something.

Link for those interested: http://plugin.fileopen.com/faq.aspx

Here's hoping Christmas comes early!

the-researcher

**Comment by apprenticeharper** [comment]
There is a Windows-only version of the ineptepub.py script that was supposed to work with FileOpen PDFs that was created and maintained by Tetrachroma back in 2010. See https://tetrachroma.wordpress.com/tag/fileopen/

The latest version of the Tetrachroma's script, 8.4.51,  is included in the Other Tools folder. Because it's Windows only it hasn't been included in the main DeDRM plugin/apps.

**Comment by the-researcher** [comment]
Thanks for the feedback!

The script ended up working, albeit in a half-baked manner. I've included my experience in case anyone stumbles upon this topic for FileOpen plugin references.

apprenticeharper, you are indeed correct that Tetrachroma's script can be used. However, you may be met with an interesting error.

When parsing a document through Tetrachroma's script, I tried to open the document in Acrobat DC. Upon opening, I was greeted with the error that the "root object" was missing.

If you get this error, try these steps:

1) Open the PDF file in another reader (e.g. Foxit). The file opened successfully, but your experience may be different.

2) After opening the file, save it as a new file.

3) The newly-saved file created in step 2 should now open without issue in Acrobat DC.

Cheers, and thanks for maintaining such an amazing software suite! You're the person that people look up to when they are looked down upon by DRM. :)

**Comment by ElleKayEm** [comment]
Had a comment over at the blog about a solution here:

https://github.com/alaingilbert/ineptpdf/issues/1#issuecomment-641300318

**Comment by RichMar** [comment]
Hello,
I found out that FileOpen has apparently changed its encryption. I use ineptpdf 8.4.51, but now, apparently since October 2025, it has stopped working for newly downloaded files. It still works for previously downloaded PDF files, but it no longer unlocks new ones.

**Comment by freyta** [comment]
> Hello,
> I found out that FileOpen has apparently changed its encryption. I use ineptpdf 8.4.51, but now, apparently since October 2025, it has stopped working for newly downloaded files. It still works for previously downloaded PDF files, but it no longer unlocks new ones.

Do you have a sample of a PDF? I can decrypt ones downloaded February this year.
