### ISSUE TITLE
Missing .zip file

### ISSUE THREAD

**Issue by Bones8264** [apprenticeharper/DeDRM_tools#1040]
HI,

I hope i am not missing something really silly, but i can't see the zip file required for installing the plugin into Calibre.

I get an error message that the zip file does not contain the top level "init.py" file.

Having read back on some of the issues regarding this, i unzipped the main DeDRM_tools-master.zip

In the folder it created i looked for a DeDRM tools.zip but the only other zip file i found was "alfcrypto_src.zip"

I have tried using that as the plugin file, but still get the error message above.

Is there a file missing? or am i not up to the task??

Regards

Mark

**Comment by ElleKayEm** [comment]
Download DeDRM_tools_6.7.0.zip from here:

https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.7.0

Unzip that to find DeDRM_plugin.zip which is what you load into calibre.

**Comment by Bones8264** [comment]
Thank you so much for such a quick response :-)

**Comment by ElleKayEm** [comment]
If or when you're all set, you can close the issue.
