### ISSUE TITLE
The default encryption key kindle for pc/mac could not be found

### ISSUE THREAD

**Issue by dhaoxi** [apprenticeharper/DeDRM_tools#1042]
Of course it can't be found, I want to add it. I press the + as in the instructions and this error comes up. How to remove this error and add the sn?

**Comment by dhaoxi** [comment]
nevermind, going to use another thing
maybe make the instructions clearer next time
the DRM was not removed even after inputing the sn, restarting; even uninstalling and restarting and re-adding the book

**Comment by ElleKayEm** [comment]
Happy to help get things working for you.  This post may help:

https://www.mobileread.com/forums/showthread.php?t=283371

If not, post a log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
