### ISSUE TITLE
unable to install on calibre 

### ISSUE THREAD

**Issue by faridcher** [apprenticeharper/DeDRM_tools#1043]
I get this error while trying to install:

```
calibre, version 4.99.4
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 4.99.4  embedded-python: False is64bit: True
Linux-5.4.0-4-amd64-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
('Linux', '5.4.0-4-amd64', '#1 SMP Debian 5.4.19-1 (2020-02-13)')
Python 3.8.2
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib/calibre/polyglot/builtins.py", line 123, in reload
    return importlib.reload(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
```

**Comment by ElleKayEm** [comment]
Not compatible with Python 3 yet.

**Comment by green-ctrl** [comment]
Hey sorry im new to this stuff so i dont really know anything about it. Is Python 3 the programming language of my software, so thats why it doesnt work? And what can i do to make it work, because i have the same problem as @faridcher

**Comment by ElleKayEm** [comment]
You should be able to install DeDRM with this version of calibre:

https://calibre-ebook.com/download_linux

**Comment by green-ctrl** [comment]
Thankyou! ill try that:)

**Comment by faridcher** [comment]
@ElleKayEm thanks

**Comment by kocoten1992** [comment]
@faridcher , please open it, it's is not done yet

**Comment by ElleKayEm** [comment]
There are a few other issues open with this problem.

**Comment by kocoten1992** [comment]
But this is the first result return on google when I copy the exact error message.

**Comment by ElleKayEm** [comment]
You could always open a new issue yourself.

**Comment by faridcher** [comment]
I can confirm there is problem with the Debian unstable package. The official standalone build (package) is fine. In fact I could not install any plugin witg Debian package. I will report this bug!

**Comment by jansloopes** [comment]
Same issue on windows 10.
Try to install DeDRM_tools_6.8.0.zip. 
-------------------error log------------------------------------------------
calibre, version 5.0.0
FOUT: Niet afgehandelde fout: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.0  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', 'SP0', 'Multiprocessor Free')
Interface language: nl
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 200, in load
  File "site-packages\polyglot\builtins.py", line 123, in reload
  File "importlib\__init__.py", line 169, in reload
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
For now, you will need to stay with [calibre 4.23](https://download.calibre-ebook.com/4.23.0/) until DeDRM is updated to be compatible with Python 3.  Discussion of the progress on that in issue #979 .

**Comment by mohuddle** [comment]
> For now, you will need to stay with [calibre 4.23](https://download.calibre-ebook.com/4.23.0/) until DeDRM is updated to be compatible with Python 3. Discussion of the progress on that in issue #979 .

I'm in the same boat, but it seems that 4.23 does not support my current Kobo Aura One firmware version. Any attempt to push a book to 'main memory on device' and I get an incompatible firmware version from Calibre.

**Comment by ElleKayEm** [comment]
Yeah, it prevents calibre from messing with anything else on your Kobo besides just copying the book over.  There is an option under Device > Configure this device > Advanced (bottom of last tab) to "attempt to support newer firmware".

**Comment by mohuddle** [comment]
> Yeah, it prevents calibre from messing with anything else on your Kobo besides just copying the book over. There is an option under Device > Configure this device > Advanced (bottom of last tab) to "attempt to support newer firmware".

Thanks LKM, did not know that was there. I'll get it set.

**Comment by ElleKayEm** [comment]
There is a "here be dragons!" warning about the potential of corrupting the Kobo's database, but in the last Kobo firmware thread at MobileRead it said it was safe.
