### ISSUE TITLE
Comment on issue #95 (closed)

### ISSUE THREAD

**Issue by urcminister** [apprenticeharper/DeDRM_tools#105]
I'm away from home at the moment, so can't get to my archives.  Somewhere, I have an old version of the Calbre plugin that includes the epub python script.  Meanwhile, see this:
"This plugin will remove the DRM from Amazon Kindle ebooks (Mobi, KF8, Topaz and Print Replica), Mobipocket, Adobe Digital Edition ePubs (including Sony and Kobo ePubs), Barnes and Noble ePubs, Adobe Digital Edition PDFs, and Fictionwise eReader ebooks".

And I remember for certain that I used it with the plugin a year ago.

**Comment by ElleKayEm** [comment]
The DeDRM calibre plugin works on Kobo epubs downloaded with Adobe Digital Editions.  The Obok calibre plugin works on kepubs downloaded with the Kobo Desktop program or from an attached Kobo device.  In the screenshot you provided in the previous issue, there is a button for Adobe Digital Editions ebooks.  That includes Kobo, Google, and many other stores' ebooks.  I don't understand what you seem to think has gone missing.

**Comment by apprenticeharper** [comment]
Not an issue. Closed.
