### ISSUE TITLE
DeDRM 6.7.0 with calibre 4.13 64bit not working

### ISSUE THREAD

**Issue by liamsmith9** [apprenticeharper/DeDRM_tools#1061]
Downloaded new version and followed installation instructions ...add-in installed and shows enabled.
Restarted Calibre program and added kindle azw3 books.
When run conversion, message still comes back "locked with DRM"
???

**Comment by ElleKayEm** [comment]
How did you download them?  If they were from the website for "download & transfer via USB, you need to choose an E-ink Kindle (not a Fire) and enter its serial number into the DeDRM plugin customization.

**Comment by liamsmith9** [comment]
I don't own a kindle anymore, it died ...use kindle app on tablet that downloads directly fine.
But I used the "download & transfer" option from Amazon for the copy that am trying to convert in calibre.  Are you saying that if I use the kindle app copy, it should work?

**Comment by ElleKayEm** [comment]
If you still have an E-ink Kindle on your account regardless of whether it is working, you can use the copy from "download & transfer".  Copy and paste the Kindle's serial number from the website into the plugin's customization.

If you don't have an E-ink Kindle on your account, then you will need to use Kindle for PC/Mac.

**Comment by liamsmith9** [comment]
Amazing!!  That worked.  Thank you.
I actually found the devices and s/n on website and where to put it in the plugin.
...added books and converted, and am done!!
Thanks again

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
