### ISSUE TITLE
DeDrm fails with very a large book 700MB fails but 50MB-book with success

### ISSUE THREAD

**Issue by lawipac** [apprenticeharper/DeDRM_tools#1063]
Hi

I tested DeDRM with 'picture intensive' books, 700MB per book.  and it fails. I tried with smaller ones, such as 50MB, and it succeeds. 

Do you know where to adjust the memory limit if any?

Kind Regards

**Comment by ElleKayEm** [comment]
Are you using 64-bit calibre?

**Comment by lawipac** [comment]
Thank you for your pointer.  After replacing it with 64-bit, it works like a charm.
