### ISSUE TITLE
Unable to convert a Kindle book to PDF (is it a DRM issue?)

### ISSUE THREAD

**Issue by RisoGalloExpresso** [apprenticeharper/DeDRM_tools#1064]
Hi guys,

I just bought a comic on Amazon (it's an .azw file protected by DRM) and I would very like to convert it in a pdf file without any kind of protection. to do that I tried to use Calibre with DeDRM extension but, during the conversion process, accured an error. below you can see the logs:

> calibre, version 4.13.0 (win32, embedded-python: True)
> Conversion error: Failed: Convert book 1 of 1 (La malinconia di Haruhi Suzumiya: 17 (Italian Edition))
> 
> Convert book 1 of 1 (La malinconia di Haruhi Suzumiya: 17 (Italian Edition))
> Conversion options changed from defaults:
>   cover: u'C:\\Users\\QUERCI~1\\AppData\\Local\\Temp\\calibre_2iv8rw\\n3immd.jpeg'
>   read_metadata_from_opf: u'C:\\Users\\QUERCI~1\\AppData\\Local\\Temp\\calibre_2iv8rw\\nxhszc.opf'
>   output_profile: u'generic_eink'
>   pdf_serif_family: u'MS Shell Dlg 2'
>   verbose: 2
>   pdf_sans_family: u'MS Shell Dlg 2'
> Resolved conversion options
> calibre version: 4.13.0
> {'asciiize': False,
>  'author_sort': None,
>  'authors': None,
>  'base_font_size': 0.0,
>  'book_producer': None,
>  'change_justification': u'original',
>  'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
>  'chapter_mark': u'pagebreak',
>  'comments': None,
>  'cover': u'C:\\Users\\QUERCI~1\\AppData\\Local\\Temp\\calibre_2iv8rw\\n3immd.jpeg',
>  'custom_size': None,
>  'debug_pipeline': None,
>  'dehyphenate': True,
>  'delete_blank_paragraphs': True,
>  'disable_font_rescaling': False,
>  'duplicate_links_in_toc': False,
>  'embed_all_fonts': False,
>  'embed_font_family': None,
>  'enable_heuristics': False,
>  'expand_css': False,
>  'extra_css': None,
>  'filter_css': u'',
>  'fix_indents': True,
>  'font_size_mapping': None,
>  'format_scene_breaks': True,
>  'html_unwrap_factor': 0.4,
>  'input_encoding': None,
>  'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001E8E4840848>,
>  'insert_blank_line': False,
>  'insert_blank_line_size': 0.5,
>  'insert_metadata': False,
>  'isbn': None,
>  'italicize_common_cases': True,
>  'keep_ligatures': False,
>  'language': None,
>  'level1_toc': None,
>  'level2_toc': None,
>  'level3_toc': None,
>  'line_height': 0.0,
>  'linearize_tables': False,
>  'margin_bottom': 5.0,
>  'margin_left': 5.0,
>  'margin_right': 5.0,
>  'margin_top': 5.0,
>  'markup_chapter_headings': True,
>  'max_toc_links': 50,
>  'minimum_line_height': 120.0,
>  'no_chapters_in_toc': False,
>  'no_inline_navbars': False,
>  'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001E8E4845488>,
>  'page_breaks_before': u"//*[name()='h1' or name()='h2']",
>  'paper_size': u'letter',
>  'pdf_add_toc': False,
>  'pdf_default_font_size': 20,
>  'pdf_footer_template': None,
>  'pdf_header_template': None,
>  'pdf_hyphenate': False,
>  'pdf_mark_links': False,
>  'pdf_mono_family': u'Courier',
>  'pdf_mono_font_size': 16,
>  'pdf_odd_even_offset': 0.0,
>  'pdf_page_margin_bottom': 72.0,
>  'pdf_page_margin_left': 72.0,
>  'pdf_page_margin_right': 72.0,
>  'pdf_page_margin_top': 72.0,
>  'pdf_page_number_map': None,
>  'pdf_page_numbers': False,
>  'pdf_sans_family': u'MS Shell Dlg 2',
>  'pdf_serif_family': u'MS Shell Dlg 2',
>  'pdf_standard_font': u'serif',
>  'pdf_use_document_margins': False,
>  'prefer_metadata_cover': False,
>  'preserve_cover_aspect_ratio': False,
>  'pretty_print': False,
>  'pubdate': None,
>  'publisher': None,
>  'rating': None,
>  'read_metadata_from_opf': u'C:\\Users\\QUERCI~1\\AppData\\Local\\Temp\\calibre_2iv8rw\\nxhszc.opf',
>  'remove_fake_margins': True,
>  'remove_first_image': False,
>  'remove_paragraph_spacing': False,
>  'remove_paragraph_spacing_indent_size': 1.5,
>  'renumber_headings': True,
>  'replace_scene_breaks': u'',
>  'search_replace': '[]',
>  'series': None,
>  'series_index': None,
>  'smarten_punctuation': False,
>  'sr1_replace': None,
>  'sr1_search': None,
>  'sr2_replace': None,
>  'sr2_search': None,
>  'sr3_replace': None,
>  'sr3_search': None,
>  'start_reading_at': None,
>  'subset_embedded_fonts': False,
>  'tags': None,
>  'timestamp': None,
>  'title': None,
>  'title_sort': None,
>  'toc_filter': None,
>  'toc_threshold': 6,
>  'toc_title': None,
>  'transform_css_rules': '[]',
>  'uncompressed_pdf': False,
>  'unit': u'inch',
>  'unsmarten_punctuation': False,
>  'unwrap_lines': True,
>  'use_auto_toc': False,
>  'use_profile_size': False,
>  'verbose': 2}
> InputFormatPlugin: MOBI Input running
> on C:\Users\QUERCI~1\AppData\Local\Temp\calibre_2iv8rw\waiuoj.azw
> Found KF8 MOBI of type u'standalone'
> Python function terminated unexpectedly
>   La malinconia di Haruhi Suzumiya: 17 (Italian Edition) (Error Code: 1)
>  Traceback (most recent call last):
>   File "site.py", line 114, in main
>   File "site.py", line 88, in run_entry_point
>   File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
>   File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
>   File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
>   File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
>   File "site-packages\calibre\customize\conversion.py", line 246, in __call__
>   File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
>   File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
>   File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
> DRMError: La malinconia di Haruhi Suzumiya: 17 (Italian Edition)

Can someone help me to understand how to fix the issue? With others books and comics (always bought from amazon) the conversion process works. Only with this comic it doesn't work.

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre, not during conversion.  So we'll need to see an import log to see what went wrong:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by RisoGalloExpresso** [comment]
Below the logs from Calibre in debug mode. In this mode I added the problem ebook:

> calibre Debug log
> calibre 4.13 [64bit]  embedded-python: True is64bit: True
> Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
> ('Windows', '10', '10.0.18362')
> Python 2.7.16+
> Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
> Interface language: en_GB
> Successfully initialized third party plugins: DeDRM (6, 6, 3)
> calibre 4.13 [64bit]  embedded-python: True is64bit: True
> Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
> ('Windows', '10', '10.0.18362')
> Python 2.7.16+
> Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
> Interface language: en_GB
> Successfully initialized third party plugins: DeDRM (6, 6, 3)
> Turning on automatic hidpi scaling
> devicePixelRatio: 1.0
> logicalDpi: 96.0 x 96.0
> physicalDpi: 96.1893491124 x 96.3318518519
> Using calibre Qt style: True
> [0.00] Starting up...
> [0.00] Showing splash screen...
> [0.58] splash screen shown
> [0.58] Initializing db...
> [0.58] db initialized
> [0.58] Constructing main UI...
> [2.08] main UI initialized...
> [2.08] Hiding splash screen
> [27.73] splash screen hidden
> [27.73] Started up in 27.73 seconds with 3 books
> DeDRM v6.6.3: Trying to decrypt B01AG29RGO_EBOK.azw
> Using Library AlfCrypto DLL/DYLIB/SO
> MobiDeDrm v0.42.
> Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
> Decrypting Kindle Format 8 ebook: La malinconia di Haruhi Suzumiya: 17 (Italian Edition)
> Got DSN key from database default_key_2
> Got DSN key from database default_key
> Found 7 keys to try after 0.4 seconds
> Crypto Type is: 2
> File is encoded with PID wQj6Gqa/S5.
> Decrypting. Please wait . . . done
> Decryption succeeded after 0.6 seconds
> DeDRM v6.6.3: Finished after 0.8 seconds
> Added La malinconia di Haruhi Suzumiya: 17 (Italian Edition) to db in: 0.4
> Added 1 books in 3.0 seconds

from this output I didn't see any error messages, so that I tried to convert it again and it worked! probably deleting the comic and importing it again have soved the issue.

Thanks for your support ElleKayEm

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
