### ISSUE TITLE
Conversion fail log MacOs

### ISSUE THREAD

**Issue by clombion** [apprenticeharper/DeDRM_tools#1068]
Here is my log with a purchased epub download from Google Play Books.

qt.qpa.fonts: Populating font family aliases took 759 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost. 
calibre Journal de débogage
calibre 4.13  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: fr
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.13  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: fr
Successfully initialized third party plugins: DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: False
[0.00] Starting up...
[0.02] Showing splash screen...
[0.37] splash screen shown
[0.37] Initializing db...
[0.37] db initialized
[0.37] Constructing main UI...
[1.94] main UI initialized...
[1.94] Hiding splash screen
[13.42] splash screen hidden
[13.42] Started up in 13.42 seconds with 1 books
Added La pensée éthique contemporaine-epub to db in: 0.0
Added 1 books in 0.3 seconds

**Comment by ElleKayEm** [comment]
Did you add the acsm file to calibre instead of the epub?

**Comment by clombion** [comment]
I added the only file that I get when downloading from Google Play Books which is an indeed an acsm file (regardless of if I choose "Download PDF" or "Download Epub"). Is there something I should be doing to the file before putting it in Calibre?

**Comment by ElleKayEm** [comment]
Yes.  To get the epub file, install Adobe Digital Editions 2.0.1 on the same machine and user as calibre with DeDRM.  Authorize ADE with an Adobe ID.  Then open the acsm file with ADE.  You will find the epub file in Documents/Digital Editions folder.  Be sure to authorize ADE with an Adobe ID BEFORE opening the acsm file.

**Comment by clombion** [comment]
Didn't know about the additional steps, thanks!
