### ISSUE TITLE
KFX Conversion failed (but only for some books?)

### ISSUE THREAD

**Issue by AmaranthWolf** [apprenticeharper/DeDRM_tools#1069]
I'm on a Surface Pro 4 with Windows 10 attempting to convert KFX files from a Kindle/Amazon purchase to EPUB files to bring into a Kobo account (both on desktop). I have 40 books and 38 worked fine. 2 are failing. I am using the latest version of DRM (6.7.0), 64bit version of Calibre (downloaded today) and version 1.24.3 of Kindle. Both books were legally purchased and downloaded via Amazon. I tried the troubleshooting tips on the ReadMe file but didn't work. I have also tried converting these books to other files but it doesn't work. Both books open fine in Kindle. I do not have a Kobo e-reader and my sisters Kindle e-reader is broken, so all of this is being done on desktop apps. 

Error message: 'ERROR:  KFX Conversion failed'

calibre, version 4.13.0
ERROR: KFX conversion failed: <p><b>Cannot convert Crooked Kingdom (Six of Crows Book 2)</b><br><br>Exception(u'Unexpected Ion symbols used: $131, $132, $785\nstory lD content type $270 has extra data: ($785: ($131: 1, $132: 1))\nstory lD content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory lU content

(LITERALLY HUNDREDS of lines like this. I deleted 99% of them because you get the idea)

($785: ($131: 1, $132: 1))\nstory l61R content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory l61R content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory l61R content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory l61R content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory l61R content type $269 has extra data: ($785: ($131: 1, $132: 1))\nstory l62P content type $270 has extra data: ($785: ($131: 1, $132: 1))\nstory l62P content type $269 has extra data: ($785: ($131: 1, $132: 1))',)</p>

Any thoughts?

**Comment by j-howell** [comment]
The most likely cause of those errors is using an outdated version of the KFX Input plugin.

**Comment by ElleKayEm** [comment]
If 38 of 40 were successful, then DeDRM (probably) isn't the issue.  Are you using 64-bit calibre?

**Comment by AmaranthWolf** [comment]
> If 38 of 40 were successful, then DeDRM (probably) isn't the issue. Are you using 64-bit calibre?

Yep I am, probably should have mentioned that

**Comment by AmaranthWolf** [comment]
> The most likely cause of those errors is using an outdated version of the KFX Input plugin.

Is there a way to update that?

**Comment by j-howell** [comment]
> Is there a way to update that?

The latest version is 1.41.1. Calibre should offer the update to you at the bottom of the window.

**Comment by AmaranthWolf** [comment]
> The latest version is 1.31.0. Calibre should offer the update to you at the bottom of the window. (Fixed wrong version.)

Okay, thank you! Good catch, the update wasn't installed. And it worked!! Thanks for that
