### ISSUE TITLE
License

### ISSUE THREAD

**Issue by HugoForrat** [apprenticeharper/DeDRM_tools#1070]
Hello,

Thanks a lot for your work on this. However, could youo please put this project under the license of your choice so that we can legally use it in other projects ?

Thank you.

**Comment by ElleKayEm** [comment]
See the discussion here:
issue #244

**Comment by HugoForrat** [comment]
I see, I tried to search the past issues to see if someone else had asked but I must have missed this thread.
Thank youf for the quick answer.

**Comment by enforcing** [comment]
melonbooks.zip
<https://drive.google.com/file/d/1r-MsAv8x5W_JS3Pi_Nsls4G94wvgZyII/view?usp=drive_web>

HugoForrat <notifications@github.com> 於 2020年4月23日 週四 下午7:30寫道：

**Comment by ElleKayEm** [comment]
@enforcing 
Is this in the wrong issue?
