### ISSUE TITLE
make_release.py: No such file or directory: 'DeDRM_Plugin'

### ISSUE THREAD

**Issue by a-vrma** [apprenticeharper/DeDRM_tools#1071]
Linux's main filesystems are all case-sensitive so your `make_release.py` won't work on those. You can fix this by changing the variables at the start of the script to match the case of the files on disk or vice versa.

**Comment by ElleKayEm** [comment]
Since make_release.py is only for putting together the release and not actually part of the releases, I don't imagine it matters too much. ::shrug::

**Comment by a-vrma** [comment]
Who knows, maybe he has to make a release on a \*nix computer in the future? Anyway I have attached a patch and it is up to him whether he wants to merge or not.

[0001-Fix-making-release-on-case-sensitive-filesystems.txt](https://github.com/apprenticeharper/DeDRM_tools/files/4526322/0001-Fix-making-release-on-case-sensitive-filesystems.txt)
