### ISSUE TITLE
DRM removal failure

### ISSUE THREAD

**Issue by LaPointe2000** [apprenticeharper/DeDRM_tools#108]
Hi,

I'm under Windows 10, I cannot remove the DRM from my Amazon ebooks. I've tried with the current Calibre version 2.57.1 and an older one I previously used with success (but that was under Win7), the 2.20.0.

Here is the log:

calibre Journal de débogage
calibre 2.20 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 11.07 seconds with 4 books
DeDRM v6.4.3: Trying to decrypt B00AAL6288_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Justinguitar.com Beginner's Songbook (Beginners Songbook)
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.4.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.4.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Herv\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Herv\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '5269999' and UserName '48657276e9'
DeDRM v6.4.3: Found 1 new key
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Justinguitar.com Beginner's Songbook (Beginners Songbook)
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.4.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 604, in run
  File "calibre_plugins.dedrm.__init__", line 554, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.3: Ultimately failed to decrypt after 0.3 seconds
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Justinguitar.com Beginner's Songbook (Beginners Songbook) to db in: 4.3
Added 1 books in 5.0 seconds
Worker Launch took: 0.18799996376

Kindle for PC has been installed from the Amazon website (KindleForPC-installer-1.16.44025) and the ebook has been freshly downloaded.

**Comment by ElleKayEm** [comment]
Was the book downloaded with the installation of Kindle for PC that's currently on the same machine (and the same Windows user) as calibre?

**Comment by LaPointe2000** [comment]
Yes it was.

**Comment by ElleKayEm** [comment]
I suggest seeing the info on completely removing and reinstalling Kindle for PC over on the blog FAQs page (about halfway down the page):

https://apprenticealf.wordpress.com/2011/01/17/frequently-asked-questions-about-the-drm-removal-tools/

**Comment by LaPointe2000** [comment]
Already done 2 times without any result.
BTW, I managed to remove the DRM on another computer (under Win7), so the issue does not come from the ebook.

**Comment by ElleKayEm** [comment]
Well, I'm stumped.  I know that others have had success with Windows 10, but maybe there is some new issue.

**Comment by apprenticeharper** [comment]
I haven't had any problems under Windows 10, so it must be something else. But nothing springs to mind. If it really is a new problem I would have expected to see more reports, but perhaps it's a new installation only problem. We'll see over the next week or two.

**Comment by apprenticeharper** [comment]
Another report prompted a thought. Are you using Kindle for PC from the WIndows app store? If so, that's the problem. Download Windows for PC directly from the Amazon web site instead.

**Comment by LaPointe2000** [comment]
I've carefully followed the instructions on the website and I'm using Kindle for PC from the Amazon web site.

**Comment by apprenticeharper** [comment]
Thanks. Could you post (or send by email) the keyfile generated by the tools. You may need to either run the keyfile script manually, or generate it in the plugin preferences dialog using the green + button in the Kindle for PC prefs dialog. (The plugin only saves the key file if it works to decrypt a file.)

**Comment by LaPointe2000** [comment]
I'm sorry but since I've managed to do it on another PC I've uninstalled everything. If I have some time, I will reinstall it.

**Comment by apprenticeharper** [comment]
I think in that case I'll close this issue. If you come across the same problem and want to pursue it, either ask for this to be re-opened, or start another issue.
