### ISSUE TITLE
Unable to remove DRM from rental Amazon AZW3 e-ink textbook file

### ISSUE THREAD

**Issue by brak265** [apprenticeharper/DeDRM_tools#1083]
Hello, I am having difficultly removing the DRM on a 30-day rented textbook for my Kindle Voyage e-ink reader.  I have the latest version of Calibre, DeDRM, and I am on MacOS.  The format of the book is .azw3

I have read online that there are difficulties in some cases for rental books in removing DRM, but I decided to try anyways to see if it would work, and I am receiving an error in Calibre when I try to convert the book from AZW3 to EPUB.  I've checked my serial number both on-device and on Amazon's site, and it is entered into the customization prompt. The error just tells me that the book can't be converted because it is locked by the DRM.  

I don't think it is relevant, but it will not convert both when I download the AZW3 from Amazon directly on their site, and also when I try to convert the file which was directly sent to my Kindle after I rented the book.  Both result in an error.  But I would assume it is the same file both ways.

Here is the error code from when I try to convert:

> Convert book 1 of 1 (Macroeconomics)
Conversion options changed from defaults:
  output_profile: u'kindle_voyage'
  verbose: 2
  read_metadata_from_opf: u'/var/folders/3f/y45gdpjj3bbb_v9nz24k3jrc0000gn/C/calibre_4.14.0_tmp_h3Onb4/Ijk3dj.opf'
  cover: u'/var/folders/3f/y45gdpjj3bbb_v9nz24k3jrc0000gn/C/calibre_4.14.0_tmp_h3Onb4/nqxdlT.jpeg'
Resolved conversion options
calibre version: 4.14.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/3f/y45gdpjj3bbb_v9nz24k3jrc0000gn/C/calibre_4.14.0_tmp_h3Onb4/nqxdlT.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10d91bad0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.KindleVoyageOutput object at 0x10d928350>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/3f/y45gdpjj3bbb_v9nz24k3jrc0000gn/C/calibre_4.14.0_tmp_h3Onb4/Ijk3dj.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on /var/folders/3f/y45gdpjj3bbb_v9nz24k3jrc0000gn/C/calibre_4.14.0_tmp_h3Onb4/NcRc88.azw3
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly: Macroeconomics
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 187, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
calibre.ebooks.DRMError: Macroeconomics

**Comment by ElleKayEm** [comment]
Yeah, these tools are intended for purchased books.
