### ISSUE TITLE
Key file location

### ISSUE THREAD

**Issue by ktk** [apprenticeharper/DeDRM_tools#1088]
I can't decrypt latest stuff from Kindle as I had a fresh install on MacOS Catalina. However, I found an old backup (a few years back) with the whole Calibre install as well.

I tried to figure out where the keys were stored in the Calibre config folder on MacOS but no luck so far. Anyone knows where the keys are stored so I can move them to my new Calibre configuration?

I will definitely export them as k4i file but first I need to know where to find them.

**Comment by ElleKayEm** [comment]
Each installation of Kindle for Mac has a unique key.  So a key from an old setup won't work with a completely fresh install of Kindle for Mac.  Not sure how you could work around this.

**Comment by ktk** [comment]
Ah too bad, thanks for the hint!

**Comment by Geremia** [comment]
@ElleKayEm Is that what he's asking? I thought he was asking where DeDRM stores its imported keys.

**Comment by ElleKayEm** [comment]
He was, but as I said, a key for the Kindle app extracted from an old calibre/DeDRM setup won't work on books downloaded with a different installation of Kindle for Mac.
