### ISSUE TITLE
Nook epub file only has cover?

### ISSUE THREAD

**Issue by oncpnda** [apprenticeharper/DeDRM_tools#1089]
I was able to download a Nook epub off of the Android simulator and used DeDRM to upload it to Calibre, but the book (manga) itself is empty. The only thing that shows up is the cover. I know the DRM was removed because it loaded in Calibre and on my Kindle, but the only content was the cover. Did I do something wrong??

**Comment by ElleKayEm** [comment]
Maybe some non-standard epub structure that works in Nook apps only.  If it's all images of page scans, you could unzip it, take just the images, and zip them back up to make a CBZ file.

**Comment by oncpnda** [comment]
So, I unzipped the epub file that was uploaded to Calibre and it worked. Thanks!
