### ISSUE TITLE
After Ubuntu 20.04 upgrade and new Calibre install unable to install DeDRM plugin

### ISSUE THREAD

**Issue by ub2004** [apprenticeharper/DeDRM_tools#1090]
After Ubuntu 20.04 upgrade from 19.10 (working DeDRM) and new Calibre install unable to install DeDRM plugin error message details below:

calibre, version 4.99.4
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 163)

calibre 4.99.4  embedded-python: False is64bit: True
Linux-5.4.0-29-generic-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
('Linux', '5.4.0-29-generic', '#33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020')
Python 3.8.2
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib/calibre/polyglot/builtins.py", line 123, in reload
    return importlib.reload(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 163
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
Not compatible with Python 3 yet.

**Comment by ub2004** [comment]
> Not compatible with Python 3 yet.

Ok, thanks. Is there a Dev version that is compatible that I can try? or a way of setting calibre to use Python 2.7 any workaround that has been found would help. I am currently looking into old calibre  versions etc and will update if I find anything.

**Comment by ElleKayEm** [comment]
The regular release of calibre is still Python 2.

**Comment by ub2004** [comment]
Both the Ubuntu 20.04 S/W updater and Synaptic package manager have dependency problems moving back to a previous version from the distributed release. 
My working solution was to download/install - "wine msiexec /i calibre-2-80-0.msi" add the .4ki file from pycrypto and use this version for .azw to .epub conversion.
The distributed version will still work under 20.04 for the database if you use new functions etc.

**Comment by ub2004** [comment]
> The regular release of calibre is still Python 2.

ElleKayEm, thank you for your clarification and assistance it is appreciated.
