### ISSUE TITLE
DeDRM Calibre plugin failled 

### ISSUE THREAD

**Issue by Otroyo8** [apprenticeharper/DeDRM_tools#1099]
Calibre Registro de depuración
calibre 4.16  embedded-python: True is64bit: True
Darwin-19.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.4.0', 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.4', ('', '', ''), 'x86_64')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.16  embedded-python: True is64bit: True
Darwin-19.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.4.0', 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.4', ('', '', ''), 'x86_64')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 7, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 103.000001547 x 103.000001547
Using calibre Qt style: True
[0.00] Starting up...
[0.10] Showing splash screen...
[0.49] splash screen shown
[0.49] Initializing db...
[0.52] db initialized
[0.52] Constructing main UI...
[1.51] main UI initialized...
[1.51] Hiding splash screen
[13.08] splash screen hidden
[13.08] Started up in 13.08 seconds with 53 books
DeDRM v6.7.0: Trying to decrypt Colombia 5. 19602010. La búsqueda de la democracia.epub
DeDRM v6.7.0: Verifying zip archive integrity
DeDRM v6.7.0: Colombia 5. 19602010. La búsqueda de la democracia.epub is a secure Adobe Adept ePub
DeDRM v6.7.0: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v6.7.0: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 350, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 447, in adeptkeys
ADEPTError: Could not find ADE activation.dat file.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
Do you have Adobe Digital Editions authorized with your Adobe ID on the same machine and user as calibre with DeDRM?

**Comment by Otroyo8** [comment]
No. I don’t.

**Comment by ElleKayEm** [comment]
That's what DeDRM needs to retrieve the key to unlock the book.

**Comment by Otroyo8** [comment]
I have installed and authorized Adobe Digital Editions and all works well. Thanks.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
