### ISSUE TITLE
DeDRM corrupts images on certain eBooks [Calibre Plugin] [Kindle AZW3]

### ISSUE THREAD

**Issue by GhostSquad57** [apprenticeharper/DeDRM_tools#11]
Hello! I noticed that when I DeDRM certain eBooks, (The Witcher series by Andrzej Sapkowski as an example), the images become corrupt; the corrupted images are renamed "0000N.unknown".

![Here's a screenshot of the corrupted image](https://cloud.githubusercontent.com/assets/1379876/7710659/558fbd0e-fe33-11e4-8684-794ee420376f.png)

Viewing the eBook via Amazon's Cloud Viewer, I was able to see how the eBook looks proper. From there I was able to find the missing image on Google images and import it.

![Here's how  it's supposed to look](https://cloud.githubusercontent.com/assets/1379876/7710765/f90b1c12-fe33-11e4-97a3-f268117ff64a.png)

**Comment by GhostSquad57** [comment]
I should mention that all the books in the Witcher series corrupt the same images in the same way; so it's definitely a reproducible pattern. Also, I'm using Arch Linux.

**Comment by ElleKayEm** [comment]
Were the books imported from a Kindle?  In some cases (books with large images?), the images are stored separately from the main epub file when you download them directly to a device .  Try going to the Manage Your Content and Devices page at Amazon.  Then choose the Download & Transfer via USB option for one of those books.  That copy should have the images intact and should work properly with the tools.

**Comment by GhostSquad57** [comment]
@ElleKayEm Yep! That's it! Images are showing up. Thanks!
