### ISSUE TITLE
Large batches added to calibre fail

### ISSUE THREAD

**Issue by apprenticeharper** [apprenticeharper/DeDRM_tools#110]
If a large (>20 or so) number of books are imported into calibre at once, only some of them get their DRM removed, although they all work if added in smaller batches,

The problem goes away in debug mode.

**Comment by apprenticeharper** [comment]
I'm still interested in hearing from anyone who currently has this problem.

**Comment by kwhaley7** [comment]
I have had the problems periodically in the past and smaller batches work. Then I update (or have to reinstall calibre, helper apps, etc) and I don't have the problem for awhile. I actually have an issue where Kindle for PC stopped converting today (as best as I can tell other types are working but I haven't checked: ADE worked a couple of days ago.) I've updated to 6.5.0 of the tool (6.4.4 in calibre) and still have the problem. I don't remember what I had to do fix this (I've had this particular issue before). It's AZW that's the problem too.

**Comment by apprenticeharper** [comment]
Please start a new issue with a log of an import that doesn't work.

**Comment by kwhaley7** [comment]
Will do.

**Comment by apprenticeharper** [comment]
Has anyone encountered this problem recently?

**Comment by apprenticeharper** [comment]
I'm closing this, on the assumption that the logging changes have fixed it.
