### ISSUE TITLE
Dedrm isn't working with kindle 1.17

### ISSUE THREAD

**Issue by hari866** [apprenticeharper/DeDRM_tools#1102]
I get the following error when I attempt to convert a .azw4 file

Error:
```
Conversion options changed from defaults:
  read_metadata_from_opf: u'C:\\Users\\Sairam\\AppData\\Local\\Temp\\calibre_iwwwg8\\czm3pw.opf'
  cover: u'C:\\Users\\Sairam\\AppData\\Local\\Temp\\calibre_iwwwg8\\rv_vvf.jpeg'
  verbose: 2
  output_profile: u'generic_eink'
Resolved conversion options
calibre version: 4.16.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\Sairam\\AppData\\Local\\Temp\\calibre_iwwwg8\\rv_vvf.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002378148AB08>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000023781527748>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Sairam\\AppData\\Local\\Temp\\calibre_iwwwg8\\czm3pw.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: AZW4 Input running
on C:\Users\Sairam\AppData\Local\Temp\calibre_iwwwg8\fidtyy.azw4
Extracting PDF from AZW4 Container...
Converting file to html...
Python function terminated unexpectedly
  pdftohtml failed with return code: 1
Syntax Error: Document stream is empty (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\azw4_input.py", line 27, in convert
  File "site-packages\calibre\ebooks\azw4\reader.py", line 59, in extract_content
  File "site-packages\calibre\ebooks\conversion\plugins\pdf_input.py", line 54, in convert
  File "site-packages\calibre\ebooks\pdf\pdftohtml.py", line 90, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Document stream is empty
```

**Comment by ElleKayEm** [comment]
Can't tell if DRM is the issue from this log.  DRM removal happens when you first add a book, not during conversion.  AZW4 files are PDFs in a Kindle wrapper.  Try using the KindleUnpack plugin to extract the PDF, instead of calibre's conversion.  I'd also suggest calibre 64-bit if that's not already what you have.

**Comment by hari866** [comment]
DRM removal doesn't happen when I drag and drop a file. It was working fine when I used it last month. Calibre reads metadata & gives the details of the book, when I double click to open it throws "This book is locked by DRM" error. I use the latest calibre 4.16 (64 bit stable).

**Comment by ElleKayEm** [comment]
Let's take a look at an import log to see what's wrong:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by hari866** [comment]
calibre Debug log
calibre 4.16 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KePub Output (3, 2, 7) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && KindleUnpack - The Plugin (0, 82, 1)
calibre 4.16 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KePub Output (3, 2, 7) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && KindleUnpack - The Plugin (0, 82, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.59] splash screen shown
[0.59] Initializing db...
[0.61] db initialized
[0.62] Constructing main UI...
[2.27] main UI initialized...
[2.27] Hiding splash screen
[72.84] splash screen hidden
[72.84] Started up in 72.84 seconds with 2 books
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing C:/Users/Guest1/B087JRKJ7P_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.7.0: Trying to decrypt B087JRKJ7P_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Reviving Jobs
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 7 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 7 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Sairam\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Sairam\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '380980277' and UserName '53616972616d'
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Reviving Jobs to db in: 1.4
Added 1 books in 2.4 seconds

**Comment by ElleKayEm** [comment]
Use Kindle for PC version 1.24 or earlier.

**Comment by hari866** [comment]
I use Kindle 1.17, should i change the version?

**Comment by hari866** [comment]
I used Kindle 1.24, still facing the same error

**Comment by hari866** [comment]
calibre Debug log
calibre 4.16 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && KePub Output (3, 2, 7) && KindleUnpack - The Plugin (0, 82, 1)
calibre 4.16 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && KePub Output (3, 2, 7) && KindleUnpack - The Plugin (0, 82, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.56] splash screen shown
[0.56] Initializing db...
[0.56] db initialized
[0.56] Constructing main UI...
[2.11] main UI initialized...
[2.11] Hiding splash screen
[6.25] splash screen hidden
[6.25] Started up in 6.25 seconds with 2 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xf9\xaa\xffj\xa2x\xf4\xc4jw*\xbb\xcb\x0ec\x13\xbfR\x88D\x15\xdd1L\xad\x0c\x90\xe7`\x85\xdb\x8f', 'C:\\Users\\Guest1\\Documents\\My Kindle Content\\B087JRKJ7P_EBOK\\B087JRKJ7P_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing C:\Users\Guest1\Documents\My Kindle Content\B087JRKJ7P_EBOK\B087JRKJ7P_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Sairam\AppData\Local\Temp\calibre_lnxbwg\9o4b2r.kfx-zip
DeDRM v6.7.0: Trying to decrypt 9o4b2r.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 9o4b2r
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 2 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.4c977f3e-a6f5-4946-88c6-f5fa5fb9326b.voucher
DeDRM v6.7.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Sairam\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Sairam\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '380980277' and UserName '53616972616d'
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.31.0: Packaging C:\Users\Sairam\AppData\Local\Temp\calibre_lnxbwg\9o4b2r.kfx-zip
Processing container: B087JRKJ7P_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B087JRKJ7P_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Sairam\AppData\Local\Temp\calibre_lnxbwg\5_3amm_add_books\0\B087JRKJ7P_EBOK.kfx-zip
Added Reviving Jobs to db in: 1.6
Added 1 books in 2.8 seconds

**Comment by ElleKayEm** [comment]
Log is still showing a more recent version of Kindle for PC.  See the bottom of the first post here for info on getting it to stay on an earlier version:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by tenxt** [comment]
This is how I solved my issue. I had replied to a post last year about how to do it. Maybe this can help! This is a repost of the solution.

Here are instructions in the most paraphrased form. At least how it would of helped me anyways..

**Steps for DeDRM and KFX plugins with  Kindle Book for Windows 10 PC:**
1. Download Kindle version 1.24.3 or less.
- Link here: [https://medium.com/@angeldan1989/the-latest-solution-to-remove-drm-from-kindle-kfx-books-2018-e27d6f71df4f](url)
2. Register/Login to your Amazon account.
3. Buy the Kindle book you want on Amazon. Do not buy the rented version because it won't work.
4. Wait for book to download on Kindle Window PC Program
5. Download calibre
- Link here: [https://calibre-ebook.com/download_windows](url)
6. Download DeDRM from apprenticeharper
- Link here: v6.6.3 [https://github.com/apprenticeharper/DeDRM_tools/releases](url)
7. Unzip file
8. Go in to calibre to add plugins under "Preferences". Click the unzipped DeDRM folder. Choose folder "DeDRM_calibre_plugin" and then click the zip file name "DeDRM_plugin" to add the plugin.
9. Click ok on all and then "apply"
10. Exit calibre and open again.
11. Download the KFX plugin
- Link here: [https://www.mobileread.com/forums/showthread.php?t=291290](url)
12. Go in to calibre to add plugins under "Preferences". Click the zip file "KFX Input" to add the plugin.
13. Click ok on all and then "apply"
14. Exit calibre and open again.
15. Now click add books. Click folder "My Kindle Content." Then click the book you want to add.
16. After the book is added, check the side of calibre to see if there was any change to "Format: azw." If the format changed anything like "Format: azw4" etc. then you have been successful.
17. Now you can convert the book in to any other format you wish.
18. Happy reading.

**Comment by ElleKayEm** [comment]
The problem in this issue is that they haven't prevented K4PC from auto-updating past version 1.24.

**Comment by hari866** [comment]
Thanks for the replies, the issue got resolved. Actually, I created a guest account to install old versions of kindle to use with calibre & had new version of kindle in the admin account. Only when I uninstalled the newer version, the process worked as intended.

**Comment by ElleKayEm** [comment]
Thanks for reporting back!
