### ISSUE TITLE
DeDRM not working in Calibre 4.16

### ISSUE THREAD

**Issue by kuiperfun** [apprenticeharper/DeDRM_tools#1103]
Hi, trying to remove DRM from Amazon books. I am using the Kindle for PC 1.24 as specified; have gone through the deleting and reinstalling as laid out in the FAQs. Can anyone help?

Here is the Calibre log

calibre Debug log
calibre 4.16  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
calibre 4.16  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.238993711 x 102.358208955
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[1.53] main UI initialized...
[1.53] Hiding splash screen
[3.94] splash screen hidden
[3.94] Started up in 3.94 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xfd\xfc".\x1a\x99d\xcc\xa5-<$\x95\x973"\xf11\x81dq\xb5\xae\xb5\x0c/\xcb\xd2\x17\x8b7\xfd', 'C:\\Users\\morrissey\\Documents\\My Kindle Content\\B006MD58Z6_EBOK\\B006MD58Z6_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing C:\Users\morrissey\Documents\My Kindle Content\B006MD58Z6_EBOK\B006MD58Z6_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 6 file(s) as C:\Users\MORRIS~1\AppData\Local\Temp\calibre_ea5nen\5tuvqw.kfx-zip
DeDRM v6.6.3: Trying to decrypt 5tuvqw.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 5tuvqw
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.bfe28e30-f25e-49c0-9bfe-414528d7e3d0.voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\morrissey\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\morrissey\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '81790422' and UserName '6d6f72726973736579'
DeDRM v6.6.3: Found 1 new key
Decrypting KFX-ZIP ebook: 5tuvqw
Got DSN key from database default_key_1
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.bfe28e30-f25e-49c0-9bfe-414528d7e3d0.voucher
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.31.0: Packaging C:\Users\MORRIS~1\AppData\Local\Temp\calibre_ea5nen\5tuvqw.kfx-zip
Processing container: B006MD58Z6_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B006MD58Z6_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\MORRIS~1\AppData\Local\Temp\calibre_ea5nen\afwcht_add_books\0\B006MD58Z6_EBOK.kfx-zip
Added Winning Chess Tactics to db in: 1.4
Added 1 books in 2.3 seconds

**Comment by ElleKayEm** [comment]
Hmm...I'm not seeing what could be wrong.  This book was downloaded with the current installation of Kindle for PC on the same machine and user as calibre with DeDRM?

I'd also suggest updating to the current 6.7.0 version of DeDRM.  It couldn't hurt to try calibre 64-bit as well.

**Comment by kuiperfun** [comment]
yes the book was downloaded with the current installation of Kindle for PC and there is only me using this machine.

I get this error when I try to update to 6.7.0 of DeDRM

InvalidPlugin: 

DeDRM_tools_6.7.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by kuiperfun** [comment]
Calibre 64-bit has the same problem

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_6.7.0.zip and load DeDRM_plugin.zip.

**Comment by kuiperfun** [comment]
You know what, that worked! Now I can enjoy my books. Thank you Elle :)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
