### ISSUE TITLE
Unable to De-DRM .azw4 using Calibre

### ISSUE THREAD

**Issue by rancidturtle** [apprenticeharper/DeDRM_tools#1105]
Hello,

I have been able to de-drm books using Calibre. I have recently bought a new laptop and have installed the same version of Kindle for PC (1.17) and Calibre (2.21) as I have on my old laptop. However, the Kindle Unpack plugin keeps showing the red lock instead of a green open lock. I have tried several different version of the DeDRM plug in including the latest (6.7.0) but had no luck. I have done the steps exactly how I would do on my old laptop but it does not work.

I have copied the debug log for the import of a purchased book on Amazon below, any help will be greatly appreciated! Thanks in advance!

calibre Debug log
calibre 2.21  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) && DeDRM && Package KFX (from KFX Input) && KFX metadata reader (from KFX Input) && KFX Input && KindleUnpack - The Plugin
Starting up...
Problem creating accessible interface for:  CalibreSplashScreen(0x2c30a70) 
Make sure to deploy Qt with accessibility plugins.
Problem creating accessible interface for:  Main(0x5884aa0, name = "MainWindow") 
Make sure to deploy Qt with accessibility plugins.
QTextCursor::setPosition: Position '1' out of range
QTextCursor::setPosition: Position '198' out of range
QTextCursor::setPosition: Position '21' out of range
Started up in 11.64 seconds with 2 books
DeDRM v6.4.0: Trying to decrypt B078SPWB1Y_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 264
Decrypting Mobipocket 4 ebook: Microbiology Fundamentals: A Clinical Approach
Found 0 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.4.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.4.0: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\phuon\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\phuon\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1413484075' and UserName '7068756f6e'
DeDRM v6.4.0: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
DeDRM v6.4.0: Ultimately failed to decrypt after 0.8 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 598, in run
  File "calibre_plugins.dedrm.__init__", line 548, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.0: Ultimately failed to decrypt after 0.8 seconds
Added Microbiology Fundamentals: A Clinical Approach to db in: 1.8
Added 1 books in 4.3 seconds
isEncrypted = True

**Comment by ElleKayEm** [comment]
Did you mean to close this?

I'd update to the current 64-bit calibre and the current DeDRM.  You downloaded the book with Kindle for PC 1.17 that's installed on the new laptop?
