### ISSUE TITLE
Log shows success, but the file retains DRM anyway.

### ISSUE THREAD

**Issue by LordHelmchen** [apprenticeharper/DeDRM_tools#1108]
Hi,
I have trouble with some books, that I downloaded with Kindle for PC 1.17. They are azw files.
The log shows successful decryption, but the file in calibre cannot be opened or converted, because it says it has DRM. The Kindle Reader 1.17 displays them without problems.

`calibre Fehlerdiagnoseprotokoll
calibre 2.51 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) && DeDRM && Package KFX (from KFX Input) && KFX metadata reader (from KFX Input) && KFX Input && Obok DeDRM
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 46.46 seconds with 226 books
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing C:/Users/jonas/Documents/My Kindle Content/B07GCT4BBK_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.7.0: Trying to decrypt B07GCT4BBK_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Der Videospieltester (KrÃ¤utersammler der Finsternis Buch 1) LitRPG-Serie (German Edition)
Got DSN key from database default_key
Found 6 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID UU5HFJVoHJ.
Decrypting. Please wait . . . . . . . . done
Decryption succeeded after 0.1 seconds
DeDRM v6.7.0: Finished after 0.1 seconds
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Der Videospieltester (Kräutersammler der Finsternis Buch 1) LitRPG-Serie (German Edition) to db in: 0.3
Added 1 books in 1.2 seconds
Worker Launch took: 0.161999940872`

**Comment by ElleKayEm** [comment]
Try updating to the current version of calibre.

**Comment by LordHelmchen** [comment]
Thank you, sometimes it is that simple.
