### ISSUE TITLE
DeDRM not working

### ISSUE THREAD

**Issue by mimirak** [apprenticeharper/DeDRM_tools#1109]
Hi,
I am no programmer, but I am trying to make DeDRM work on my PC. So I launched calibre-debug. I understand the issues has something to do with a key. Any help would be greatly appreciated. 

Here is what I get:

Firefox rurl: None None
URLS: XXXXX
Paths: XXXXX
Extensions: frozenset([u'epub'])
DeDRM v6.7.0: Trying to decrypt XXXXXX.epub
DeDRM v6.7.0: Verifying zip archive integrity
DeDRM v6.7.0: XXXXXXXX.epub is a secure Adobe Adept ePub
DeDRM v6.7.0: Trying Encryption key default_key
**Could not decrypt x3hc85.epub. Wrong key**
DeDRM v6.7.0: Failed to decrypt with key default_key after 0.3 seconds
DeDRM v6.7.0: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v6.7.0: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 350, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 379, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 359, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files (x86)\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added XXXXX to db in: 0.1
Added 1 books in 0.6 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x05B4B750>> ignored

**Comment by ElleKayEm** [comment]
Beginning of log seems to be missing which would show calibre version, plugins installed, and OS info.  
Do you have Adobe Digital Editions 2.0.1 authorized with your Adobe ID installed on the same machine as calibre with DeDRM?  And you can read the book in ADE?

**Comment by mimirak** [comment]
Hi ElleKayEm,
Thanks for your prompt response. I am running a w10 machine along with ADE 4.5.10.186048 (windows version authorized with my adobe ID) and the latest version of calibre and DeDRM. I can read the book in ADE. He is the full log:

calibre 4.17  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Hyphenate This! (0, 0, 9)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 54.5503355705 x 54.5910447761
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Initializing db...
[0.03] db initialized
[0.03] Constructing main UI...
[1.61] main UI initialized...
[1.61] Started up in 1.61 seconds with 999 books

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 356 '\x01\x00\x00\x00\x0c\x00\x00\x00\xcc\x00\x00\x00\x14\x00\x1fP\xe0O\xd0 \xea:i\x10\xa2\xd8\x08\x00+00\x9d:\x00.\x80\x92+\x16\xd3e\x93zF\x95k\x92p:\xca\x08\xaf&\x00\x01\x00&\x00\xef\xbe\x11\x00\x00\x00j\x85e\xf6\xb5\x80\xd5\x01\xb4\x8f\xf5{\xbd6\xd6\x01\xb4\x8f\xf5{\xbd6\xd6\x01\x14\x00p\x001\x00\x00\x00\x00\x00\xbeP{\x9d\x10\x00MYDIGI~1\x00\x00X\x00\t\x00\x04\x00\xef\xbeWO\x16n\xbeP{\x9d.\x00\x00\x00^\x97\x03\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xcd\xba\x03\x00M\x00y\x00 \x00D\x00i\x00g\x00i\x00t\x00a\x00l\x00 \x00E\x00d\x00i\x00t\x00i\x00o\x00n\x00s\x00\x00\x00\x18\x00\x00\x00\x96\x002\x00H\xac6\x00\xbeP\x99\x98 \x00POURUN~1.PDF\x00\x00z\x00\t\x00\x04\x00\xef\xbe\xbeP\x99\x98\xbeP\x99\x98.\x00\x00\x00\x00s\x05\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\xebp\x00P\x00o\x00u\x00r\x00 \x00u\x00n\x00e\x00 \x00c\x00r\x00'

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 '\x01\x00\x00\x00'

application/x-qt-windows-mime;value="DragImageBits" 82968 '\x90\x00\x00\x00\x90\x00\x00\x00H\x00\x00\x00\x85\x00\x00\x00|\x11\x05\x93\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

application/x-qt-windows-mime;value="DragContext" 16 '\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 '\x01\x00\x00\x00'

application/x-qt-windows-mime;value="InShellDragLoop" 4 '\x01\x00\x00\x00'

text/uri-list 105 'file:///C:/Users/Karim/Documents/My%20Digital%20Editions/Pour%20une%20critique%20de%20la%20violence.pdf\r\n'

application/x-qt-windows-mime;value="FileName" 46 'C:\\Users\\Karim\\DOCUME~1\\MYDIGI~1\\POURUN~1.PDF\x00'

application/x-qt-windows-mime;value="FileContents" 0 ''

application/x-qt-windows-mime;value="FileNameW" 164 'C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00K\x00a\x00r\x00i\x00m\x00\\\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00s\x00\\\x00M\x00y\x00 \x00D\x00i\x00g\x00i\x00t\x00a\x00l\x00 \x00E\x00d\x00i\x00t\x00i\x00o\x00n\x00s\x00\\\x00P\x00o\x00u\x00r\x00 \x00u\x00n\x00e\x00 \x00c\x00r\x00i\x00t\x00i\x00q\x00u\x00e\x00 \x00d\x00e\x00 \x00l\x00a\x00 \x00v\x00i\x00o\x00l\x00e\x00n\x00c\x00e\x00.\x00p\x00d\x00f\x00\x00\x00'

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 '\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\xb5i1\xb56\xd6\x01\x00\x00\x00\x00\x00\x00\x00\x00\x84\xc9\xf80\xb56\xd6\x01\x00\x00\x00\x00H\xac6\x00P\x00o\x00u\x00r\x00 \x00u\x00n\x00e\x00 \x00c\x00r\x00i\x00t\x00i\x00q\x00u\x00e\x00 \x00d\x00e\x00 \x00l\x00a\x00 \x00v\x00i\x00o\x00l\x00e\x00n\x00c\x00e\x00.\x00p\x00d\x00f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'


Firefox rurl: None None
URLS: [u'file:///C:/Users/Karim/Documents/My%20Digital%20Editions/Pour%20une%20critique%20de%20la%20violence.pdf']
Paths: [u'C:/Users/Karim/Documents/My Digital Editions/Pour une critique de la violence.pdf']
Extensions: frozenset([u'pdf'])
DeDRM v6.7.0: Trying to decrypt Pour une critique de la violence.pdf
DeDRM v6.7.0: Pour une critique de la violence.pdf is a PDF ebook
DeDRM v6.7.0: Trying Encryption key default_key
DeDRM v6.7.0: Exception when decrypting after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 428, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2193, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1999, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1484, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1616, in initialize_ebx
ADEPTError: error decrypting book session key
DeDRM v6.7.0: Failed to decrypt with key default_key after 0.3 seconds
DeDRM v6.7.0: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v6.7.0: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 453, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 379, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 359, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 507, in PDFDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 343, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 129, in get_metadata
ValueError: Could not read info dict from PDF
Added Pour une critique de la violence to db in: 0.0
Added 1 books in 0.7 seconds


Thanks for your help!

**Comment by ElleKayEm** [comment]
For whatever reason, the key it's finding isn't working on this book.  Try de-authorizing and re-authorizing ADE.  Scroll down here for Windows instructions:

https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html

Be aware that with ADE 4.5 it's possible to get DRM that can't be removed.  (Depends on whether the ebookstore is using the newer hardened DRM or not.)  If it can be opened in ADE 2.0.1 (authorized with your Adobe ID), then DeDRM should work.

You might also want to try calibre 64-bit.  Since PDF files tend to be larger, it can't hurt.

**Comment by mimirak** [comment]
So I DE-authorized and uninstalled ADE 4.5, then installed ADE 2.0.1 and authorized it with the same credentials. I downloaded another book from the same place (epub this time). I can read it fine in ADE, but DeDRM still can't open it. If I understand you correctly, since I can read it in ADE 2.0.1, it is not a hardened DRM. Any other ideas? Thanks!

**Comment by ElleKayEm** [comment]
Yes, definitely not hardened DRM if you can read it in 2.0.1.  I'd try what it says under "TROUBLESHOOTING REAUTHORIZATION AND DEAUTHORIZATION ISSUES ON WINDOWS" at the previous link if you haven't already.  (As it says there, be careful when editing the registry.)
