### ISSUE TITLE
Can't remove DRM from Kindle Ebook

### ISSUE THREAD

**Issue by jappjunior** [apprenticeharper/DeDRM_tools#111]
I did as tutorial but can't remove DRM from my Kindle Ebook, follow the debug information:

Thanks for helping.

C:\Users\JoséAp>calibre-debug -g
calibre 2.59 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Qt: Untested Windows version 10.0 detected!
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 2.26 seconds with 0 books
DeDRM v6.4.3: Trying to decrypt B00QMIYWQM_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Exploring BeagleBone: Tools and Techniques for Building with Embedded Linux
Found 0 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.4.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.4.3: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\JosAp\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\JosAp\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '347743771' and UserName '4a6f73e94170'
DeDRM v6.4.3: Found 1 new key
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Exploring BeagleBone: Tools and Techniques for Building with Embedded Linux
Found 4 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.4.3: Ultimately failed to decrypt after 0.6 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 604, in run
  File "calibre_plugins.dedrm.__init__", line 554, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.3: Ultimately failed to decrypt after 0.6 seconds
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Exploring BeagleBone: Tools and Techniques for Building with Embedded Linux to db in: 2.0
Added 1 books in 3.6 seconds

**Comment by ElleKayEm** [comment]
Was that book downloaded with the current installation of Kindle for PC on the same machine and user as calibre?  If so, then try unregistering and uninstalling Kindle for PC.  Then delete the Kindle folders.  Finally reinstall, register, and redownload your book.

**Comment by jappjunior** [comment]
Actually I downloaded it with Kindle for WindowsStore, but I deleted the e-book, installed Kindle for PC and downloaded and registered the book again.

But now, I've just done as you said EllenKayEm, uninstall Kindle for WindowsStore, after uninstall Kindle for PC, deleted the folders and files, unregistered at Amazon website and install Kindle for PC, download the book and register again, but I had the following message again and it doesn't work.

I really love drafting/doodling the book and not being able to print the book I bought to work the way I want is really frustrating.

Thanks again!

C:\Users\JoséAp>calibre-debug -g
calibre 2.59 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Qt: Untested Windows version 10.0 detected!
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 2.19 seconds with 0 books
DeDRM v6.4.3: Trying to decrypt B00QMIYWQM_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Exploring BeagleBone: Tools and Techniques for Building with Embedded Linux
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.4.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.4.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\JosAp\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\JosAp\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '347743771' and UserName '4a6f73e94170'
DeDRM v6.4.3: Found 1 new key
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Exploring BeagleBone: Tools and Techniques for Building with Embedded Linux
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.4.3: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 604, in run
  File "calibre_plugins.dedrm.__init__", line 554, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.3: Ultimately failed to decrypt after 0.4 seconds
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Exploring BeagleBone: Tools and Techniques for Building with Embedded Linux to db in: 1.5
Added 1 books in 2.6 seconds
Worker Launch took: 0.22000002861

**Comment by ElleKayEm** [comment]
Did you delete both the "My Kindle Content" folder and the following hidden folder?

C:\Users\JosAp\AppData\Local\Amazon

**Comment by jappjunior** [comment]
Same problem, I did that three times. :(

C:\Users\JoséAp>calibre-debug -g
calibre 2.59 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Qt: Untested Windows version 10.0 detected!
Successfully initialized third party plugins: DeDRM
Starting up...
Failed to check for calibre update: [Errno 11001] getaddrinfo failed
Failed to check for plugin update: [Errno 11001] getaddrinfo failed
Started up in 2.53 seconds with 0 books
DeDRM v6.4.3: Trying to decrypt B00QMIYWQM_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Exploring BeagleBone: Tools and Techniques for Building with Embedded Linux
Found 0 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.4.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.4.3: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\JosAp\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\JosAp\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '347743771' and UserName '4a6f73e94170'
DeDRM v6.4.3: Found 1 new key
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Exploring BeagleBone: Tools and Techniques for Building with Embedded Linux
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.4.3: Ultimately failed to decrypt after 0.5 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 604, in run
  File "calibre_plugins.dedrm.__init__", line 554, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.3: Ultimately failed to decrypt after 0.5 seconds
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Exploring BeagleBone: Tools and Techniques for Building with Embedded Linux to db in: 1.6
Added 1 books in 3.0 seconds
Worker Launch took: 0.203000068665

**Comment by jappjunior** [comment]
And I deleted both folders.

**Comment by jappjunior** [comment]
I did it all again in another computer, with Windows 7, and it worked.

I guess it's some problem with Windows 10.

Thanks anyway.

**Comment by ElleKayEm** [comment]
I know some people have been able to use it on Windows 10.  Glad you got it working with Windows 7.
