### ISSUE TITLE
DeDRM cannot work on extremely large azw3 file.

### ISSUE THREAD

**Issue by helei0147** [apprenticeharper/DeDRM_tools#1111]
I followed the guide and successfully removed the drm of an about 2.7MB azw3 file.
But I have no idea why I failed on a 710MB comic collection file. These two files were downloaded in the same way.
The log is as below, including a success and a failure.

calibre 调试日志
calibre 4.16  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Obok DeDRM (6, 7, 0) && EpubSplit (2, 9, 0)
calibre 4.16  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Obok DeDRM (6, 7, 0) && EpubSplit (2, 9, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 78.9126213592 x 79.2832369942
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.44] db initialized
[0.44] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.14] main UI initialized...
[2.14] Hiding splash screen
[8.14] splash screen hidden
[8.14] Started up in 8.14 seconds with 34 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xab\xbc<p\xb1\xa5;O\xce\xdfl\xd6X\xfa\x19\x0e\xde\xce\x0c_\x7f\xed\x91\xdc?\xb7\xc3\x0e%h\xf8\xaf', 'C:\\Users\\helei\\Downloads\\\xe7\x8b\x84\xe9\x87\x91\xe6\xa3\xae\xe5\x85\xa8\xe9\x9b\x86.azw3']
DeDRM v6.7.0: Trying to decrypt 鐙勯噾妫叏闆?azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 鐙勯噾妫叏闆?
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
File is encoded with PID V5XajztJNI.
Decrypting. Please wait . . . . . . . . . done
Decryption succeeded after 0.1 seconds
DeDRM v6.7.0: Finished after 0.1 seconds
C:\Program Files (x86)\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added 狄金森全集 to db in: 0.1
Added 1 books in 0.6 seconds
Worker Launch took: 0.181999921799
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x92t\xd2\xac\xa6Wn\x98\x17\x92c [>\xbem\x08e\x88\xb4\xc6\xc7%\xbe\x87=w\x06\x03oz\xbf', 'C:\\Users\\helei\\Downloads\\\xe8\x94\xa1\xe5\xbf\x97\xe5\xbf\xa0\xe5\x85\xb8\xe8\x97\x8f\xe5\x9b\xbd\xe5\xad\xa6\xe6\xbc\xab\xe7\x94\xbb\xe7\xb3\xbb\xe5\x88\x97\xe5\xa4\xa7\xe5\x85\xa8\xe9\x9b\x86(\xe5\xa5\x97\xe8\xa3\x85\xe5\x85\xb118\xe5\x86\x8c).azw3']
DeDRM v6.7.0: Trying to decrypt 钄″織蹇犲吀钘忓浗瀛︽极鐢荤郴鍒楀ぇ鍏ㄩ泦(濂楄鍏?8鍐?.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 钄″織蹇犲吀钘忓浗瀛︽极鐢荤郴鍒楀ぇ鍏ㄩ泦(濂楄鍏?8鍐?
Found 2 keys to try after 1.2 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 1.2 seconds
searching for kinfoFiles in C:\Users\helei\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 蔡志忠典藏国学漫画系列大全集(套装共18册) to db in: 1.0
Added 1 books in 2.9 seconds
Worker Launch took: 0.18700003624

It seems that the key works on the first file, but it failed on the second large file.

**Comment by ElleKayEm** [comment]
Use calibre 64-bit.
