### ISSUE TITLE
Unable to convert KFX files using method 1 KindleForPC version 1.17

### ISSUE THREAD

**Issue by ZipperDipper** [apprenticeharper/DeDRM_tools#1113]
The First Method by which one could de-DRM KFX files appears to no longer work. I downloaded and installed Kindle-for-PC 1.17 which does not use KFX files (or so the instructions state) https://www.mobileread.com/forums/showthread.php?t=283371 But when Kindle 1.17 downloaded the book, it downloaded several types of files none of which were of familiar form - Calibre tries to import an MD file from the My Kindle Content directory and could not convert it to any recognizable format.

**Comment by ElleKayEm** [comment]
As I said in the other issue, Kindle for PC must have auto-updated if you're seeing an MD file.  See the info at the link about preventing unwanted updates.

**Comment by ZipperDipper** [comment]
I uninstalled KindleForPC, turned off internet connection, re-installed it. It found the book I had downloaded already on my Kindle Content Folder and was able to read it. I checked version and it said 1.17. The file had an azw extension. I tried to import this into kindle. This time it converted giving me a title and author (unlike previous) BUT when I tried to read it, it said this book is protected by DRM and cannot be read. I checked that the De-DRM package is installed. So there is something else that is wrong here.

**Comment by ElleKayEm** [comment]
Post a log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by ZipperDipper** [comment]
[0.38] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[2.19] main UI initialized...
[2.19] Hiding splash screen
[14.59] splash screen hidden
[14.59] Started up in 14.59 seconds with 58 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xd2\t\xbb\xb2\x8b\x96\xe1\xe8p\xdf\x9e\xb5\x07\xcd\xe7\xd6O\x88\x93\xad\x9f\x82H\x0c^

\xd6X6\x0c\xf2\xf3\x06', 'C:\\Users\\asad\\Documents\\My Kindle Content\\B07TJ1YW3Q_EBOK.azw']
DeDRM v6.7.0: Trying to decrypt B07TJ1YW3Q_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Radical Uncertainty: Decision-Making Beyond the Numbers
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\asad\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\asad\AppData\Local\Amazon\Kindle\storage\.kinf2011
Couldn't decrypt file.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: 

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: 

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Radical Uncertainty: Decision-Making Beyond the Numbers to db in: 0.4
Added 1 books in 1.9 seconds
Worker Launch took: 0.172999858856

**Comment by ElleKayEm** [comment]
Redownload the book with the current installation of Kindle for PC.  Each installation of K4PC has a unique key.

**Comment by ZipperDipper** [comment]
THanks. That WORKED -- !! great
