### ISSUE TITLE
KFX decrypt failed. Download & Xfer via USB works.

### ISSUE THREAD

**Issue by hehaden511** [apprenticeharper/DeDRM_tools#1114]
I have a Kindle Basic eInk reader.  
The DeDRM and KFX Input plugins are installed and serial number entered and verified to be correct.  
  
I followed the guide and dragged and drop the .kfx file into Calibre. Tried to decrypt and encountered the error saying the book is DRM protected.   
However, if I go to Amazon and download the eBooks and convert them, I have no issues.   
Is KFX decrypt not working if I drag and drop from Kindle or did I get the steps wrong?  

___  

calibre Debug log
calibre 4.17 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && Obok DeDRM (6, 7, 0)
calibre 4.17 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.5518394649 x 81.6428571429
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.44] db initialized
[0.44] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.66] main UI initialized...
[1.66] Hiding splash screen
Storage number map:
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&XXX\XXX: StorageDeviceNumber(type=XXX, number=XXX, partition_number=XXX)
Drive letters for USBDevice(vendor_id=XXX product_id=XXX bcd=XXX devid=usb\XXX devinst=XXX)
{u'drive_letters': ['G'],
 u'pnp_id_map': {'G': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rXXX#XXX#XXX'},
 u'readonly_drives': set([]),
 u'sort_map': {'XXX': (XXX, XXX)}}
Syncing cover thumbnails to workaround amazon cover bug
Restored 0 cover thumbnails that were destroyed by Amazon
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: G:\ documents
DEBUG:    0.1 USBMS: scan from root False G:\documents
DEBUG:    0.1 USBMS: count found in cache: 67, count of files in metadata: 67, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 67
DeviceJob: set_books_in_library finished: time= 0.00399994850159
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
[9.69] splash screen hidden
[9.70] Started up in 9.70 seconds with 0 books
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing G:/documents/Downloads/Items01/XXX.kfx
Gather KFX-ZIP (from KFX Input): Gathered 5 file(s) as C:\Users\XXX\AppData\Local\Temp\XXX\XXX.kfx-zip
DeDRM v6.7.0: Trying to decrypt XXX.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: XXX
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.7.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.7.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\XXX\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.31.0: Packaging C:\Users\XXX\AppData\Local\Temp\XXX\XXX.kfx-zip
Processing container: XXX.kfx
Processing container: XXX.kfx
Processing container: XXX.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container XXX.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\XXX\AppData\Local\Temp\XXX\XXX\0\XXX.kfx-zip
Added From XXX to db in: 0.1
Added 1 books in 1.1 seconds

**Comment by ElleKayEm** [comment]
Trying to decrypt KFX files directly from Kindles with firmware 5.10.2 or newer (or from Kindle for PC/Mac 1.25 or newer) will not work.  When you download a file from the website, it will be in one of the older formats.

**Comment by hehaden511** [comment]
Thanks. I'll close this issue.
