### ISSUE TITLE
BN DRM Removal Not Working

### ISSUE THREAD

**Issue by FernandezR** [apprenticeharper/DeDRM_tools#1121]
It looks like BN may have changed the encryption method. The decryption method in ignobleepub.py no longer works.

My key file is current and generates the correct key which can find the bookkey in 'META-INF/rights.xml'.

The bookkey variable ends up as the empty string after line 268 `bookkey = bookkey[:-ord(bookkey[-1])]` executes.

Does anyone have any idea how to update the decryption of BN epubs?

Thanks

**Comment by ElleKayEm** [comment]
I don't have an answer.  But out of curiosity, did you get your current key from a nook, android app, or android emulator?  Book from the same?  Have you been able to decrypt BN books in the past?

**Comment by FernandezR** [comment]
It's been a while since I bought a nook book usually I buy from other sites. I generated the key with the scripts provided. 

I tried using epubor but that wasn't able to decrypt it either.

**Comment by ElleKayEm** [comment]
Ok, the tools haven't been able to generate a BN key since the desktop Nook apps got cut off.  The only workaround I know of now is to manually extract it from a device or Android app.  Then it can be imported into DeDRM.

Are the books new downloads of old purchases?  Or old downloads?

**Comment by FernandezR** [comment]
The book is a new purchase

**Comment by ElleKayEm** [comment]
Take a look at this blog post:

https://www.aricrenzo.com/2019-12-13-Liberate-Your-Nook-Ebooks/

**Comment by FernandezR** [comment]
Thanks @ElleKayEm, I take a look at the method described in that post.
