### ISSUE TITLE
Version 6.8 still doesn't de-DRM KFX format

### ISSUE THREAD

**Issue by slyvella** [apprenticeharper/DeDRM_tools#1127]
I have been successfully working with Kindle books by using an older version of Kindle for PC that downloaded MOBI and AZW books.  I thought I'd try the new version with the latest Kindle for PC I just downloaded, but it didn't de-DRM the KFX.  It does still work with EPUB.  

I can go back to the old Kindle for PC, but thought I'd let you know.  If would be nice not to be fighting with Amazon all the time about upgrading the Kindle software since it sometimes seems not to respect the choice to not upgrade!

calibre, version 3.48.0
ERROR: Could not open e-book: Failed to read book, C:\Users\silvi\Documents\Books\Calibre Laptop Library\Unknown\B089WH7DCT EBOK (697)\B089WH7DCT EBOK - Unknown.azw click "Show Details" for more information

Traceback (most recent call last):
  File "site-packages\calibre\utils\ipc\simple_worker.py", line 290, in main
  File "site-packages\calibre\ebooks\oeb\iterator\book.py", line 64, in extract_book
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 37, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

**Comment by ElleKayEm** [comment]
Do you have the KFX Input plugin installed as well?  Also, the calibre ebook viewer cannot read this format.

**Comment by slyvella** [comment]
Hi, I didn't have the KFX Input plugin installed, I think I read instructions too fast!  But I missed that the calibre viewer cannot read the format, and that's how I verify a successful DRM removal.  

Since this is just for archiving my purchased Kindle content, I decided instead to to upgrade the Kindle app and disable the renderer check.  The instructions at the link below didn't exactly work (access denied for renaming) so I took ownership of the Kindle program directory and was able to do it with a rename in File Manager.

https://www.mobileread.com/forums/showthread.php?t=283371

Book was now saved as AZW3 instead of KFX and I'll just deal with the upgrade issue.  Thanks.

**Comment by ElleKayEm** [comment]
To keep from getting KFX format, you'll need to stick to Kindle for PC 1.24 or earlier.  For later versions, disabling renderer-test doesn't seem to stop KFX downloads.  I'm personally sticking with 1.17 for as long as possible.  That version is unable to download KFX at all.

**Comment by slyvella** [comment]
I've been using 1.17 up to now with updating issues once in a while (especially after it's reinstalled), but just tried 1.24.  I have both installers, so can always go back and forth if I need to.  The interface on the newer version is a little nicer, but if it gives me any problems, it's out of there.  Thanks.

**Comment by ElleKayEm** [comment]
Just wanted to say that I was wrong about the calibre ebook viewer not being able to read KFX format.  I discovered it can (DRM-free, of course), but I just didn't have the internal viewer set up to open them (under Preferences > Behavior).
