### ISSUE TITLE
Failed DRM removal (Failed to decrypt with error: string index out of range)

### ISSUE THREAD

**Issue by UmiChahan** [apprenticeharper/DeDRM_tools#1131]
Good evening and sorry to bother, 
I attempted to remove the DRM from files I extracted from an e-ink kindle, and after inputing the serial number the program still fails to operate. I tried several options, such as running a 64 bits Calibre, but an error still shows :
calibre 4.19 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.19 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.44] db initialized
[0.44] Constructing main UI...
[1.56] main UI initialized...
[1.56] Hiding splash screen
[18.34] splash screen hidden
[18.34] Started up in 18.34 seconds with 2 books
DeDRM v6.8.0: Trying to decrypt ä¸ƒã¤ã®é­”å‰£ãŒæ”¯é…ã™ã‚‹ (é›»æ’ƒæ–‡åº«)_B07GZCDZ45.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: ä¸ƒã¤ã®é­”å‰£ãŒæ”¯é…ã™ã‚‹ (é›»æ’ƒæ–‡åº«)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
File is encoded with PID y41+ufmyR4.
Decrypting. Please wait . . . DeDRM v6.8.0: Failed to decrypt with error: string index out of range
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Kylian\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added ä¸ƒã¤ã®é­”å‰£ãŒæ”¯é…ã™ã‚‹ (é›»æ’ƒæ–‡åº«) to db in: 0.1
Added 1 books in 0.5 seconds
Worker Launch took: 0.15399980545
Thank you very much for your hard work, it is very much appreciated !

**Comment by ElleKayEm** [comment]
It doesn't like that key.  If you downloaded the book from the website, make sure you chose the correct E-ink Kindle (not a Fire).  Make sure you entered the serial number correctly into the eink Kindle section of the DeDRM plugin customization.  Try copy and pasting the serial number from the website.

**Comment by UmiChahan** [comment]
Ok in fact I could not download it from the store for a while because my account had been locked, but now I can and it worked just fine ! Thanks and sorry for the incovenience
