### ISSUE TITLE
The plugin in u'\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by chapmjs** [apprenticeharper/DeDRM_tools#1133]
calibre, version 4.19.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.19 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && Package KFX (from KFX Input) (1, 32, 0) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 319, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You’re trying to load the whole archive. Unzip DeDRM_tools_6.8.0.zip and load DeDRM_Plugin.zip.

**Comment by chapmjs** [comment]
Found it.  I was confused by the two different zip files (one has a hyphen, the other an underscore):
DeDRM_tools-6.8.0.zip
DeDRM_tools_6.8.0.zip

I found the DeDRM_Plugin.zip in the underscore zip file. 
Thank you!

**Comment by ElleKayEm** [comment]
Yeah, the hyphen one is the source code, not the release.  You want the first link under assets on the release page.  The one in your error message is the underscore one, but that's not the plugin.
