### ISSUE TITLE
New DL from amazon unable to add to Calibre

### ISSUE THREAD

**Issue by bean901** [apprenticeharper/DeDRM_tools#1134]
calibre Debug log
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 81.5518394649 x 81.6428571429
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.72] splash screen shown
[0.72] Initializing db...
[0.73] db initialized
[0.73] Constructing main UI...
[2.62] main UI initialized...
[2.62] Hiding splash screen
[5.36] splash screen hidden
[5.36] Started up in 5.36 seconds with 85 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xf3\x17Y\xa0u\xf9\x86U;\r\xb5\xd2 \xc3\xa5\x8aQ\xba=\xdc\xb3\xbe\xef\x12\xa9,\x11V\xed\xc7z>', 'C:\\Users\\Fred_2.homeserver\\Documents\\My Kindle Content\\B01J0F0CAS_EBOK\\B01J0F0CAS_EBOK.azw']
DeDRM v6.8.0: Trying to decrypt B01J0F0CAS_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.8.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Fred_2.homeserver\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Fred_2.homeserver\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2727136058' and UserName '467265645f32'
DeDRM v6.8.0: Found 1 new key
DeDRM v6.8.0: Ultimately failed to decrypt after 13.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 13.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 285, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
Added B01J0F0CAS EBOK to db in: 1.0
Added 1 books in 15.5 seconds
Worker Launch took: 0.147000074387

Windows 10

Purchased from Amazon

**Comment by bean901** [comment]
After Dl an older version of Kindle for PC and then registering the older program and then dl the purchase I was able to add it to Calibre with DRM removed

**Comment by ElleKayEm** [comment]
The problem was the KFX format.  See this post for all the ways to avoid or deal with it:

https://www.mobileread.com/forums/showthread.php?t=283371

If you're all set, you can close the issue.

**Comment by bean901** [comment]
Issued resolved with an older version of Kindle.  Ensure that the option to update is unchecked
