### ISSUE TITLE
cannot remove drm 

### ISSUE THREAD

**Issue by Luciaven** [apprenticeharper/DeDRM_tools#1137]
calibre Debug log
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.53] splash screen shown
[0.53] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
[2.02] main UI initialized...
[2.02] Hiding splash screen
[6.77] splash screen hidden
[6.77] Started up in 6.77 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x89\x9c\x13\xc0h\x04\xfc\xc08o\xe7k\xef\xcd@\x93\x08#\x03\xbc\xb6UC\x92\xd3\x14}\xb0\xf4\xe4\xefr', 'C:\\Users\\Lucia\\Desktop\\This Perfect Day.epub']
Added This Perfect Day to db in: 0.6
Added 1 books in 0.9 seconds

**Comment by Luciaven** [comment]
Can you please help? I bought an epub book from a dealer online, and cannot convert it to read it on my kindle.

**Comment by ElleKayEm** [comment]
Did you mean to close this issue?  In any case, I don't see the DeDRM plugin loading at all here.

**Comment by Luciaven** [comment]
No, I am unable to convert the epub to kindle in whichever form, (mobi or other) due to DRM. 

I followed myriad instructions, one of which eventually was to paste the result to this  webpage, which I did.

I am totally clueless as to what to do next.

I bought the epub from a legitimate online dealer, and Calibre allows me to read it on the laptop, but I want it on my kindle.

I would appreciate any help, thanks

 

Lucia

**Comment by ElleKayEm** [comment]
It doesn't look like you have the DeDRM plugin installed.

**Comment by Luciaven** [comment]
It seems to install it, not sure why it does not work

**Comment by ElleKayEm** [comment]
Check to see if it was somehow disabled.

**Comment by Luciaven** [comment]
Thank you so much! I finally managed to convert the book and send to the kindle!

I appreciate your help

 

Regards,

Lucia
