### ISSUE TITLE
SOME AZW De-DRM and other not- and not the case in any of FAQ neither here + OASIS

### ISSUE THREAD

**Issue by Giacom77** [apprenticeharper/DeDRM_tools#114]
hello

new here. and new in many things. Just aquired a Kindle Oasis. Bought a few books last week in amazon. some paid some free (Price 0) In total 11. I use calibre + the pluggin. Only able to de-DRM 2 books. but not the others. Most of them appear AZW and some AZW3. I Also did everything what is suggested and finaly debug mode and got the file tmpumdoew.txt . Before that i dis 2 clean instalations of Kindle for PC and also Calibre. I dis addition 1 by 1

Is it posible to have some help ?

Thank you.

**Comment by ElleKayEm** [comment]
If the books are from your Kindle Oasis, then you need to add its serial number to the plugin customization.  Otherwise, import books from Kindle for PC installed on the same machine and user as calibre.

If you're still having trouble, post the log you get from debug mode when adding a book.

**Comment by Giacom77** [comment]
Hello

I did exactly what you sugest. Bith tried to do it first from JKindle for PC, and later tried from the Oasis this the serieal number. The problema happens in both cases. I would prefer if posible to send the log in private. Can I send it to any email. ?

thank you and best regards

**Comment by ElleKayEm** [comment]
Just post it here.  You can put XXXX in place of the book title and/or your user name if you like.

**Comment by Giacom77** [comment]
Ok. I do it in a while
Thanks

**Comment by Giacom77** [comment]
HERE I ATTACH THE FIRST DEBUG TXT:

[tmpumdoewCLEAN.txt](https://github.com/apprenticeharper/DeDRM_tools/files/364328/tmpumdoewCLEAN.txt)

**Comment by Giacom77** [comment]
I ALSO ATTACH HEREAFTER ONE DEBUG FILE WITH ONE BOOK THAT IS WELL de-DRM AND ANOTHER NOT
[tmp26vc0f ONE-OK and ONE-NOT CLEAN.txt](https://github.com/apprenticeharper/DeDRM_tools/files/364334/tmp26vc0f.ONE-OK.and.ONE-NOT.CLEAN.txt)

**Comment by Giacom77** [comment]
Hope this info will help t understand what happens. thank you.

**Comment by apprenticeharper** [comment]
The ones that 'work' don't have encryption to start with: "This book is not encrypted."

For the Kindle for PC files, I suspect that your user name has a non-ASCII character in it, and that's messing things up (I thought I had fixed that, but obviously not). 

Either use the files from your Oasis (and double-check that you've got the serial number right), or create a new user account with a user name that only has ASCII characters, and install Kindle for PC in that, which should allow the DRM removal to work.
