### ISSUE TITLE
DeDRM won't auto convert when adding new book

### ISSUE THREAD

**Issue by lostinagoodbook** [apprenticeharper/DeDRM_tools#1140]
Hi, 

I never had a problem before, but then the IT guy made some changes to our server and I had to re-download Calibre and the plugin. Now when I add a new book it won't automatically convert to Mobi.  
I get books sent to me through my kindle email, but they are not books bought from Amazon.  They are ARC copies from Netgalley.  Please let me know what i can do to fix this problem.

Here is the log file:

calibre Debug log
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 32, 0) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0) && Goodreads Sync (1, 14, 3) && Set KFX metadata (from KFX Output) (1, 42, 0) && KFX Output (1, 42, 0) && Obok DeDRM (6, 7, 0)
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 32, 0) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0) && Goodreads Sync (1, 14, 3) && Set KFX metadata (from KFX Output) (1, 42, 0) && KFX Output (1, 42, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.8113948919 x 95.9160839161
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.72] splash screen shown
[0.72] Initializing db...
[0.77] db initialized
[0.77] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    2.1 HttpHelper::__init__: proxy=None
[3.06] main UI initialized...
[3.06] Hiding splash screen
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'D')],
 (7L, 1L): [(1L, 'F')],
 (7L, 2L): [(1L, 'G')],
 (7L, 3L): [(1L, 'H')],
 (7L, 4L): [(1L, 'I')],
 (7L, 5L): [(1L, 'J')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\G090G10553430054&0: StorageDeviceNumber(type=7L, number=5L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=15)
{u'drive_letters': ['J'],
 u'pnp_id_map': {'J': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#g090g10553430054&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'J': (5L, 1L)}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device informationJob:  0callback returned 
Get device information finishedJob:
 1 No details available.
Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: J:\ documents
[8.81] splash screen hidden
[8.81] Started up in 8.81 seconds with 601 books
DEBUG:    0.8 USBMS: scan from root False J:\documents
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
DEBUG:    1.7 USBMS: count found in cache: 715, count of files in metadata: 715, need_sync: False
DEBUG:    1.7 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    1.7 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    1.7 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 715
DeviceJob: set_books_in_library finished: time= 0.0279998779297
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['B\x0e\xf8\xf5%\x90\xdew\x8a\x07\x8bX}\xc4\xdcr@!\xf3J\xd0\x12j\xb8[\xf1r\xeea\xf0\x06\xfa', 'J:\\documents\\The Conductors_XVC53VFOSPTOD4T5KQM2SKPBYGIDN3QB.azw3']
DeDRM v6.8.0: Trying to decrypt The Conductors_XVC53VFOSPTOD4T5KQM2SKPBYGIDN3QB.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Conductors
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\CServ1.CALPAC\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Conductors to db in: 2.2
Added 1 books in 3.3 seconds

**Comment by ElleKayEm** [comment]
Looks like you probably forgot to add your E-ink Kindle's serial number to the DeDRM plugin customization.

**Comment by lostinagoodbook** [comment]
That did it!! Thank you so much for your help.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
