### ISSUE TITLE
Can't DeDRM Adobe Didital Edition Books

### ISSUE THREAD

**Issue by TnT420** [apprenticeharper/DeDRM_tools#1144]
calibre Debug log
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.110344828
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.66] splash screen shown
[0.66] Initializing db...
[0.67] db initialized
[0.67] Constructing main UI...
[2.70] main UI initialized...
[2.70] Hiding splash screen
[11.95] splash screen hidden
[11.95] Started up in 11.95 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xf8\xf9\xd9[ffF\x99\xf7\x89W\x01\xf4\xb2\\\xec0K\r\xfe\xba\x8f\x9a$\xc7E\xcc$\x1b\n\xbb5', 'C:\\Users\\mohams\\Documents\\My Digital Editions\\Bon appe\xcc\x81tit.epub']
DeDRM v6.8.0: Trying to decrypt Bon appétit.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: Bon appétit.epub is a secure Adobe Adept ePub
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v6.8.0: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 350, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 379, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 359, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Bon appétit to db in: 0.1
Added 1 books in 1.8 seconds
--------------------------------------------------------------------------
Yes, I'm on the same pc I've downloaded this encrypted book from.
Even Same IDs are connected on ADE's and book source.
ADE's version is 2.0 (the one mentioned on blog)

Note: It can dedrm all kind of books If I set it up on on a different local account on same PC.

**Comment by ElleKayEm** [comment]
You can DeDRM this and other books on a different setup?  Just not this one?  Try de-authorizing and re-authorizing ADE with your Adobe ID.  Look at the section here on TROUBLESHOOTING REAUTHORIZATION AND DEAUTHORIZATION ISSUES ON WINDOWS:

https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html

Be very careful when editing the Windows registry.
