### ISSUE TITLE
Didn't remove DRM

### ISSUE THREAD

**Issue by beenha** [apprenticeharper/DeDRM_tools#1146]
Calibre 4.20.0 on a Windows 8.1 Single Language x64
Dell Vostro 5470
Purchased the eBook on Amazon

After installing the plugin and when opening the book, it says "This book is protected by DRM"

calibre Log de Debug
calibre 4.20 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 2.7.16+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.20 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 2.7.16+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
[1.52] main UI initialized...
[1.52] Hiding splash screen
[6.88] splash screen hidden
[6.88] Started up in 6.88 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['a\xc4\xbd\xfd\x143\x8c\xab \xb6sN \xfbPO\xd4\x7f\xa0\xcb/\xed\t}\xac\x05\xfe9*1\x124', 'C:\\Users\\B\\Downloads\\The Fabliaux.azw3']
DeDRM v6.8.0: Trying to decrypt The Fabliaux.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Fabliaux
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\B\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added The Fabliaux to db in: 2.2
Added 1 books in 3.2 seconds

**Comment by ElleKayEm** [comment]
Is the book from the website for "download & transfer via USB"?  You need to chose an E-ink Kindle (not a Fire) and enter its serial number into the DeDRM plugin's customization.

**Comment by beenha** [comment]
> 
> 
> Is the book from the website for "download & transfer via USB"? You need to chose an E-ink Kindle (not a Fire) and enter its serial number into the DeDRM plugin's customization.

It worked! Thanks a lot!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
