### ISSUE TITLE
Won't install in calibre

### ISSUE THREAD

**Issue by Brak87** [apprenticeharper/DeDRM_tools#1151]
I've tried installing this plugin a few times, and I keep getting an error message:

calibre, version 4.20.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/Users/Brak87/Downloads/DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.20  embedded-python: True is64bit: True
Darwin-19.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.5.0', 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 194, in load
  File "site-packages/calibre/customize/zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'/Users/Brak87/Downloads/DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ZolaLa9** [comment]
You are trying to add the whole tools archive (DeDRM_tools_6.8.0.zip) instead of the plugin. Unzip the archive, and look for **DeDRM_plugin.zip** inside the folder called DeDRM_calibre_plugin. 

**DeDRM_plugin.zip** is the actual plugin you need to install.

**Comment by ElleKayEm** [comment]
With the last couple releases, there is no longer a DeDRM_calibre_plugin folder.  DeDRM_plugin.zip is now in the main folder after unzipping DeDRM_tools_6.8.0.zip.

**Comment by Brak87** [comment]
Thanks so much, it's so obvious now, lol. This is a new process for me. However, now that I've installed it successfully, I'm having the same problem as other users ... it's just not working. I know the easiest fix (for the time being) is to downgrade to Kindle to 1.26, but I'm unable to find this anywhere. Do you have a source? Thanks again!

**Comment by ElleKayEm** [comment]
Look at the section on "obtaining and verifying Kindle for PC/Mac software" here:

https://www.mobileread.com/forums/showthread.php?t=283371

It gives you the specific file name to search for and how to check if it it's an unmodified copy.

**Comment by Brak87** [comment]
Many thanks for your help, I was able to find and verify a copy, and I'm now using your plugin with ease :)!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
