### ISSUE TITLE
Where can I find the ADE key on windows to use on linux?

### ISSUE THREAD

**Issue by gambr** [apprenticeharper/DeDRM_tools#1153]
I installed ADE on windows and imported an ebook. Now I want to use calibre and DeDRM on linux to read the ebook (epub copied from windows ADE dir). DeDRM is not able to remove the DRM protection. I think the key is missing. Is there a file on windows where I can get it?

Regards

**Comment by ElleKayEm** [comment]
Set up calibre and DeDRM on Windows.  Add a book to calibre.  If the book is successfully decrypted, you'll be able to save the key from the Windows DeDRM plugin customization and import it into your Linux setup.  You'll be able to decrypt books downloaded with any app authorized with that same Adobe ID.  After you've gotten things working on Linux, you can uninstall the Windows calibre if you want.
