### ISSUE TITLE
Imported ACSM book file into Calibre but it's not being DeDRMed. Did this 3-4 times.

### ISSUE THREAD

**Issue by tonitii24** [apprenticeharper/DeDRM_tools#1155]
Just updated my Calibre to latest version.
Mac OS Catalina, 10.15.4
Downloaded DeDRM plugin and loaded it. Closed Calibre and reopened it before importing book again. But the book stays an ACSM file and when I "open containing folder" it stays the same.

calibre Debug log
calibre 4.20  embedded-python: True is64bit: True
Darwin-19.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.4.0', 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.20  embedded-python: True is64bit: True
Darwin-19.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.4.0', 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.29] db initialized
[0.29] Constructing main UI...
[1.09] main UI initialized...
[1.09] Hiding splash screen
[9.92] splash screen hidden
[9.92] Started up in 9.92 seconds with 30 books
Added URLLink to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by ElleKayEm** [comment]
Install Adobe Digital Editions on the same machine and user as calibre with DeDRM.  Authorize it an Adobe ID.  Open the ACSM file with Adobe Digital Editions to download the EPUB or PDF.  Add that file to calibre.

**Comment by tonitii24** [comment]
What do you mean by "user as calibre with DeDRM" and "authorize it an Adobe ID". I have Adobe Digital Editions on my laptop already and used it to the open the ACSM file. But how do I download the EPUB or PDF after opening it in ADE?

**Comment by tonitii24** [comment]
Never mind--I think I got it. I clicked on "Show in Finder" to find the EPUB file and then I put that in Calibre, and now it can be viewed in Calibre. Thank you!
