### ISSUE TITLE
Calibre does not recognised source kpf

### ISSUE THREAD

**Issue by continentaldrift** [apprenticeharper/DeDRM_tools#1165]
Hi, many thanks for creating the DeDrm plugin.  I found it via William Thompson on https://www.kdpcommunity.com/
I'm using a macbook pro retina, OS Mojave 10.14.6.
I generated a kpf file from a pdf of my comic, using Kindle Create. I want to publish the epub on other platforms. 

The debug log is below. It seems short and I can't see that it contains any useful info. But I'm not a coder. Then again, it's possible that I didn't generate the file properly. If so, my apologies. TIA!

EpubMerge: DEBUG: 2020-07-16 13:28:43,635: calibre_plugins.epubmerge.epubmerge_plugin(152): macmenuhack file_path:/Users/lisamills/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
calibre Debug log
calibre 4.20  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0) && EpubMerge (2, 2, 0)
calibre 4.20  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0) && EpubMerge (2, 2, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.71] splash screen shown
[0.71] Initializing db...
[0.73] db initialized
[0.73] Constructing main UI...
[2.42] main UI initialized...
[2.42] Hiding splash screen
[9.85] splash screen hidden
[9.86] Started up in 9.86 seconds with 8 books
Added spacewarp 16 july 1256 to db in: 3.8
Added 1 books in 4.7 seconds

**Comment by j-howell** [comment]
KPF files produced using Kindle Create are not encrypted and the DeDRM plugin has nothing to do with them.

The optional KFX Input plugin for calibre is able to handle KPF files, but it will not be of much use for your purpose. Comics on Kindle use proprietary fixed-layout markup that will not be usable on other platforms.

**Comment by continentaldrift** [comment]
Sorry, I was led to believe that the drm plugin somehow also enable Calibre to handle KPF files.
Just to clarify: the optional KFX input plugin you mention can handle KPF files, but will not be able to convert KPF to epub?

**Comment by j-howell** [comment]
>the optional KFX input plugin you mention can handle KPF files, but will not be able to convert KPF to epub?

The KFX Input plugin is able to convert books that use reflowable layout to EPUB.

Books that use Amazon's comic or textbook fixed-layout formats can also be converted to EPUB, but the result will not be usable for other purposes because it will contain coding that is proprietary to Amazon. Each bookstore ecosystem has their own variant of fixed-layout that is not compatible between them.

**Comment by continentaldrift** [comment]
OK, thank you for explaining :)

**Comment by ElleKayEm** [comment]
It looks like there is an option to enable the calibre ebook viewer to open KPF files under Preferences > Behavior.  No idea how well it actually handles this.

**Comment by ElleKayEm** [comment]
@continentaldrift 
Since this isn't actually a DeDRM issue, would you mind closing the issue?  You can still comment after it's closed if needed.
