### ISSUE TITLE
Kindle for android keys from backup

### ISSUE THREAD

**Issue by sorcierlegrand** [apprenticeharper/DeDRM_tools#1166]
I tried using the method for generating keys from a android device here https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_plugin/DeDRM_Kindle%20for%20Android%20Key_Help.htm

and it does not work, and doesn't even gives me an error on the console, is this method not working?
I generated the ab file using the adb tools on linux (ubuntu 18.04, if it makes any difference), exactly like the manual said (adb backup com.amazon.kindle) and using the plugin (6.8) clicking on the "choose the backup file" while importing the backup doesn't load the file, clicking on the ok always gives me a "Please choose a Kindle for android backup file", with or without a "Unique key name". 

What am I doing wrong?

**Comment by ElleKayEm** [comment]
The method doesn't work anymore.  I believe Amazon changed things so that backup doesn't actually produce anything useful anymore.

**Comment by sorcierlegrand** [comment]
ok, thank you, gonna check another method.
