### ISSUE TITLE
DeDRM works fine, my books are readable but without images

### ISSUE THREAD

**Issue by ramast** [apprenticeharper/DeDRM_tools#1174]
The title says it all.

I've used the command line directly 

./lib/k4mobidedrm.py -k <my serial> input_file.azw3 output_foler/

A mobi file is successfully produced but all images inside the book can not be displayed.
Clicking "view image" shows an error like this

> calibre, version 4.9.1
> ERROR: Invalid image: Failed to load the image images/00201.unknown

**Comment by ElleKayEm** [comment]
Is this possible a multi-file book with the images stored separately?

**Comment by ramast** [comment]
How do I validate that? There is only one azw3 file for that book and a directory with same name that ends with ".sdr" extension. This directory only contains one file with some json data in it.

Also why would an image have an ".unknown" extension, I don't think this is normal.

**Comment by ElleKayEm** [comment]
There's an AZW6 format and the KFX format which have images stored in a separate file.  I don't think I've seen anyone report anything like this before.  How was the book downloaded?

**Comment by ramast** [comment]
It was purchased from amazon store using amazon kindle paperwhite device and was auto-downloaded.
I can send it if that helps.

**Comment by ElleKayEm** [comment]
Try downloading it from the website and see how that copy is.

**Comment by ramast** [comment]
I don't see any option from Amazon website to download the books. I presume you mean use Windows version of Amazon reader? 
I only have Linux  PC and that's the reason I want to use decryption tool in the first place.

I could start virtual machine, installed windows, installed amazon app and give it a try but I was hoping I could get the script work directly from my Linux machine without having to rely on virtual machines.

I am a python developer myself so maybe you can guide me to the part of the code that extract images and I can do some debugging?

**Comment by ElleKayEm** [comment]
No, not Kindle for PC.  Go here:

amazon.com/myk

Choose the "download & transfer via USB" option and select your Paperwhite as the device.

**Comment by ramast** [comment]
Thank you, That's solved my problem
