### ISSUE TITLE
DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by jayantanth** [apprenticeharper/DeDRM_tools#1175]
![Capture](https://user-images.githubusercontent.com/1370149/88258206-3e1abd80-ccdd-11ea-8c0c-6dfeef9a1940.PNG)

calibre, version 4.21.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Program Files (x86)\\Calibre2\\Plugin\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.21  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Set KFX metadata (from KFX Output) (1, 43, 0) && KFX Output (1, 43, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'C:\\Program Files (x86)\\Calibre2\\Plugin\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're trying to install the whole archive.  Unzip that file and load DeDRM_plugin.zip into calibre.

**Comment by jayantanth** [comment]
Thanks, its, work. That my mistake.
