### ISSUE TITLE
most books convert except those with b0 in the file title

### ISSUE THREAD

**Issue by johnledezma34** [apprenticeharper/DeDRM_tools#1176]
It's as simple as that, I have absolutely no trouble decrypting most of my books, those with the b0 then some letters give me trouble. I just dragged all my books from my Kindle oasis, they're all kfx from the same source.

**Comment by ElleKayEm** [comment]
KFX format directly from a Kindle Oasis won't be able to be decrypted.  You can either use "download & transfer via USB" from the website or Kindle for PC/Mac.  See this post for details:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by gitmeupbaby** [comment]
same issue here. file starts with b0...
this was not from an Oasis, but from the Kindle app for Windows.  Any suggestions?

**Comment by ElleKayEm** [comment]
See the link in my previous reply.  If one of those methods doesn't work, post a log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by gitmeupbaby** [comment]
Forgive me, I misunderstood your reply to be Oasis-specific, so I didn't follow that link at first.
Thank you, @ElleKayEm  -This should fix me up 👍
