### ISSUE TITLE
Foreign language kindle -- cannot be dedrm -- title cannot be downloaded to kindle for PC OR Kindlefor Mac 

### ISSUE THREAD

**Issue by helphelpplease** [apprenticeharper/DeDRM_tools#1178]
Hello: i wrote this on mobile read forum and thought maybe I be better to write here.i do not know, sorry.  I purchased a kindle title that amazon says only able to download title to subset devices -- bunch of kindle devices, plus (kindle for android, and kindle for iPad ) allowed but **_**does not list** either kindle for Mac or kindle for PC.

 I am hoping others know about this delimma as it appears relevant for certain type of kindles eg foreign languages like **traditional Chinese, Arabic or Italian**. (Kindle for PC supports Hindi from 1.21is my understanding).

This title is kindle Arabic, with drm.

Attempted to download to the android, and received amazon message "must upgrade to receive this title".
Upgraded kindle for android to 8.11, and title downloaded to android. File format the resulted is this **KFX**.

It seems it is not possible to dedrm my title as this title cannot be downloaded to kindle for PC or kindle for Mac (and I do not own a physical kindle device).( The dedrm tools no longer have anything for kindle android later than 4.8). Is this correct?

Or is there another kindle for android version that works, or some other new method -- I ask as j Howell says in the KFX input plugin thread the kfx input plugin only works on kindle for android 8.11 and earlier. Implies some hope... maybe..

  _**Calibre - KFX Conversion Input Plugin** (thread at mobile read), jhowell, says:

Import cannot currently be performed on KFX books downloaded using Kindle for Android version 8.12 or greater and Kindle for Fire 14.12 or greater due to new DRM.
No workable import method is available for the Kindle for iOS app._

I found 2018 post and did as jhowell guided (below)
1 from the android, grabbed the entire directory of the KFX plus another file just outside the book title directory.
2 loaded the entire kfx directory into calibre, dedrm plugin 6.8 loaded
3 log files says cannot find key

Of course it cannot I thought -- , as key is on the kindle for android. Bad news for me.

Jhowell says in post 2018:

In order to make that work you will need to 
1 add a .kfx file from the book to calibre in its original directory structure, either by accessing the Android device using MTP or by copying the files to your PC. 
2 If you copy you must include the folder that contains the KFX files or it will not work. Or as an alternative you can zip all of the files in the folder that holds the book, rename the extension from .zip to .kfx-zip and import that.
3 That should work as long as the book was set by the publisher to be **sold without DRM.** 

If instead the book is protected, you have the problem of obtaining the DRM key associated with your Kindle for Android installation.--- **this is my situation**

Thankyou for any assistance.

**Comment by ElleKayEm** [comment]
No, it isn't possible to DeDRM Kindle for Android books any longer.  The old method involved making a backup file of the app from which the key could be extracted.  But Amazon changed things so its app backup doesn't contain anything useful.

Would you be willing to share a link to one of the books which doesn't have the option to download to Kindle for PC/Mac?

**Comment by helphelpplease** [comment]
Thankyou ElleKayEm.

There are many. Commonality is they are foreign language. 
One example:
https://www.amazon.com/%E2%80%ABيوميّات-هرّ-Arabic-املي-نصرالله-ebook/dp/B07BSG3113

On Amazon webpage under linek "Available on These Devices", I have checked the same list of limited device on all these type of foreign language kindles:


![Available on These Devices](https://user-images.githubusercontent.com/68757906/88441203-7e587800-ce64-11ea-8002-a0a50aba2997.jpeg)

**Comment by ElleKayEm** [comment]
Thanks.  I got the sample for this book to see what I could find out.  There doesn't appear to be any way to DeDRM books like these at this time -- even if you had an E-ink Kindle.

**Comment by helphelpplease** [comment]
Thankyou ElleKayEm.  Are you saying not possible on elink kindle reader, as the device will force you to update firmware?  I was asking around if a friend had one.

**Comment by ElleKayEm** [comment]
This will only download in the KFX format to E-ink Kindles on the current firmware (which DeDRM cannot handle yet).  And there is no option to download in the older format from the website.
