### ISSUE TITLE
DRM free perhaps?

### ISSUE THREAD

**Issue by achandra03** [apprenticeharper/DeDRM_tools#1183]
Tried with an EPUB file. Here's the log:

calibre Debug log
calibre 4.4  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.4  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 3.0
logicalDpi: 80.0 x 80.0
physicalDpi: 93.9653179191 x 94.2680412371
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.23] splash screen shown
[1.23] Initializing db...
[1.23] db initialized
[1.23] Constructing main UI...
[3.00] main UI initialized...
[3.00] Hiding splash screen
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information Job: 0started 
Get device information finished
DeviceJob: 1 No details available.Set library information
 done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
MTP: Loading filesystem metadata...
MTP: Ignored object: Music
MTP: Ignored object: Ringtones
MTP: Ignored object: Alarms
MTP: Ignored object: Notifications
MTP: Ignored object: Pictures
MTP: Ignored object: Movies
MTP: Ignored object: DCIM
MTP: Ignored object: Android/media
MTP: Ignored object: Android/data/com.amazon.mp3
MTP: Ignored object: Android/data/com.amazon.ags.app
MTP: Ignored object: Android/data/com.amazon.venezia
MTP: Ignored object: Android/data/com.amazon.avod
MTP: Ignored object: Android/data/com.amazon.photos
MTP: Ignored object: Android/data/com.amazon.device.backup
MTP: Ignored object: Android/data/com.here.odnp.service
MTP: Ignored object: Android/data/com.amazon.securitysyncclient
MTP: Ignored object: Android/data/com.amazon.kindle.otter.oobe
MTP: Ignored object: Android/data/com.amazon.zico
MTP: Ignored object: Android/data/com.amazon.readynowcore
MTP: Ignored object: Android/data/com.amazon.firelauncher
MTP: Ignored object: Android/data/com.amazon.csapp
Job: 1 Set library information finished
No details available.
MTP: Filesystem metadata loaded in 1.012 seconds (643 objects)
MTP: Using cached metadata for Internal storage/Download/Then She Was Gone - Lisa Jewell.mobi
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 1
DeviceJob: set_books_in_library finished: time= 0.00300002098083
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
[11.56] splash screen hidden
[11.56] Started up in 11.56 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x16\x17\xdcv\xc6\x8eGL\x17\x0e\xd2\x0cI&\x9a\x85\xb2Hg\x8d9Z\xdaQ\xaa\x17.\n\x14t\x7fB', 'C:\\Users\\arnav\\Downloads\\Lisa Jewell - Then She Was Gone_ A Novel-Atria Books (2018).epub']
DeDRM v6.8.0: Trying to decrypt Lisa Jewell - Then She Was Gone_ A Novel-Atria Books (2018).epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: “Lisa Jewell - Then She Was Gone_ A Novel-Atria Books (2018).epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
**Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 412, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Couldn't decrypt after 0.3 seconds. DRM free perhaps?**
Added Then She Was Gone to db in: 0.3
Added 1 books in 1.7 seconds

EDIT: Just tried with different files - same issue with all of them, so it isn't a problem with the file.

**Comment by ElleKayEm** [comment]
For epub files, DeDRM works on Adobe DRM and Barnes and Noble books.  How did you download this?

**Comment by fedinskiy** [comment]
Interesting, I have the same issue with the book from Google Play. It was downloaded through copying link from the acsm file, so I assume, it it locked with Adobe DRM.


`calibre Debug log
calibre 3.48  embedded-python: False is64bit: True
Linux-5.3.18-lp152.33-default-x86_64-with-glibc2.2.5 Linux ('64bit', '')
('Linux', '5.3.18-lp152.33-default', '#1 SMP Wed Jul 22 06:32:33 UTC 2020 (e5a8383)')
Python 2.7.17
Linux: ('', '', '')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 3.48  embedded-python: False is64bit: True
Linux-5.3.18-lp152.33-default-x86_64-with-glibc2.2.5 Linux ('64bit', '')
('Linux', '5.3.18-lp152.33-default', '#1 SMP Wed Jul 22 06:32:33 UTC 2020 (e5a8383)')
Python 2.7.17
Linux: ('', '', '')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.6235294118 x 95.5818815331
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.21] splash screen shown
[0.21] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[1.21] main UI initialized...
[1.21] Hiding splash screen
DeDRM v6.8.0: Trying to decrypt Peace_Talks.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: “Peace_Talks.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 412, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
[13.93] splash screen hidden
[13.94] Started up in 13.94 seconds with 2 books
Added Peace Talks to db in: 2.7
Added 1 books in 3.4 seconds
`

**Comment by ElleKayEm** [comment]
You will need to open the acsm file with Adobe Digital Editions 2.0.1 authorized with an Adobe ID and on the same machine and user as calibre with DeDRM.  Then you will have an epub file that DeDRM can decrypt.

**Comment by achandra03** [comment]
> For epub files, DeDRM works on Adobe DRM and Barnes and Noble books. How did you download this?

Got it from Library Genesis. Is there any way I can convert this file into a format that's compatible?

**Comment by ElleKayEm** [comment]
@achandra03 
Then isn't it already DRM-free?

**Comment by achandra03** [comment]
@ElleKayEm 
Nope, tried transferring it onto my Kindle Fire and it said it couldn't open because it was protected by DRM

**Comment by ElleKayEm** [comment]
Can you read it in the calibre ebook viewer?

**Comment by achandra03** [comment]
Yep, it reads fine in calibre

**Comment by ElleKayEm** [comment]
Then it's DRM-free.  Convert it to AZW3 and you should be able to read it on your Kindle Fire.

**Comment by achandra03** [comment]
Oh, didn't know you had to convert to AZW3. It worked, thanks for the solution.
