### ISSUE TITLE
DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by mnanda** [apprenticeharper/DeDRM_tools#1184]
I'm on Mac OSX 10.14.6
Calibre 4.22.0  (but was having same problem on earlier version, V 3. Something)

I also tried to load the earlier Tools 6.7.0.zip and got the same error message.

Below is what I copied from full error message inf.  Any help much appreciated.  Thank you!

Amanda

* * * * * * * 
calibre, version 4.22.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/Users/amandamarks/Downloads/DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.22  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && Modify ePub (1, 4, 1) && LanguageTool (0, 1, 1) && EpubSplit (2, 9, 0)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 194, in load
  File "site-packages/calibre/customize/zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'/Users/amandamarks/Downloads/DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're trying to load the whole archive.  Unzip DeDRM_tools_6.8.0.zip.  Load DeDRM_Plugin.zip.

**Comment by mnanda** [comment]
I had unzipped DeDRM_Plugin.zip ALSO, thanks for the help!
