### ISSUE TITLE
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

### ISSUE THREAD

**Issue by racer213** [apprenticeharper/DeDRM_tools#1185]
Thus far I've had no luck while DRM'ing a book (it stays in an AZW3 format) in this case I've tried using the latest versions of both plugins needed for KFX files from Amazon Kindle for PC (version 1.17). I've even deregistered myself from Amazon in order to make a clean install of this outdated version of such reader.

I do include the entire log but I do think that the issue is from the line I do post in the title:

`calibre 4.22 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.22 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
[1.50] main UI initialized...
[1.50] Hiding splash screen
[5.02] splash screen hidden
[5.02] Started up in 5.02 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['hPH8x\xd6 \rN\xebe\xbe\xfb\xcf\xa0\xa4/\xea?N\x12\x90\x03\xb2\xdab\xcb"b\x0c\xcb3', 'C:\\Users\\lol\\Documents\\My Kindle Content\\B07ZCSR5MJ_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing C:\Users\lol\Documents\My Kindle Content\B07ZCSR5MJ_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.8.0: Trying to decrypt B07ZCSR5MJ_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: æœˆåˆŠã‚¢ã‚¯ã‚·ãƒ§ãƒ³2020å¹´9æœˆå·ï¼»é›‘èªŒï¼½
Got DSN key from database default_key
Found 4 keys to try after 0.8 seconds
Crypto Type is: 2
File is encoded with PID 5DrL5IHyXC.
Decrypting. Please wait . . . . done
Decryption succeeded after 2.0 seconds
DeDRM v6.8.0: Finished after 2.8 seconds
D:\Programs\Calibre\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added æœˆåˆŠã‚¢ã‚¯ã‚·ãƒ§ãƒ³2020å¹´9æœˆå·ï¼»é›‘èªŒï¼½ to db in: 1.2
Added 1 books in 4.5 seconds`

**Comment by racer213** [comment]
I do reinclude the log since github is being github, and it's impossible to understand the log.

calibre 4.22 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.22 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
[1.50] main UI initialized...
[1.50] Hiding splash screen
[5.02] splash screen hidden
[5.02] Started up in 5.02 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['hPH8x\xd6 \rN\xebe\xbe\xfb\xcf\xa0\xa4/\xea?N\x12\x90\x03\xb2\xdab\xcb"b\x0c\xcb3', 'C:\\Users\\lol\\Documents\\My Kindle Content\\B07ZCSR5MJ_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing C:\Users\lol\Documents\My Kindle Content\B07ZCSR5MJ_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.8.0: Trying to decrypt B07ZCSR5MJ_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: æœˆåˆŠã‚¢ã‚¯ã‚·ãƒ§ãƒ³2020å¹´9æœˆå·ï¼»é›‘èªŒï¼½
Got DSN key from database default_key
Found 4 keys to try after 0.8 seconds
Crypto Type is: 2
File is encoded with PID 5DrL5IHyXC.
Decrypting. Please wait . . . . done
Decryption succeeded after 2.0 seconds
DeDRM v6.8.0: Finished after 2.8 seconds
D:\Programs\Calibre\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added æœˆåˆŠã‚¢ã‚¯ã‚·ãƒ§ãƒ³2020å¹´9æœˆå·ï¼»é›‘èªŒï¼½ to db in: 1.2
Added 1 books in 4.5 seconds

**Comment by ElleKayEm** [comment]
This log shows that the DRM has been successfully removed.  The book starts out with the generic AZW extension.  Then has the AWZ3 extension once it has been unlocked.

**Comment by racer213** [comment]
For no reason at all, I've redownloaded the same file again, and now it works. The file extension before it also showed as being AWZ3, but while trying to export the file it said that the file was still encrypted. Thanks though.

**Comment by ElleKayEm** [comment]
Maybe the first file was from the previous installation?  If you deregistered and had to log in again, the key would change.
