### ISSUE TITLE
No decryption possible

### ISSUE THREAD

**Issue by derritter88** [apprenticeharper/DeDRM_tools#1186]
I had to use the current Amazon Kindle for PC application as 1.17 (or any other below it) does no longer work with my credentials.

I installed the KFX and DeDRM plugin at Calibre but the import process does not work with following log:

Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: of956o
Got DSN key from database default_key
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.8186cbe5-4b21-4f88-8541-51f664f974ef.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\xxx\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\xxx\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\xxx\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString 'xxx' and UserName 'xxx'
Couldn't decrypt file.
DeDRM v6.8.0: Ultimately failed to decrypt after 6.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 6.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
You'll need Kindle for PC 1.26 or earlier.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by derritter88** [comment]
Thanks @ElleKayEm! This worked
