### ISSUE TITLE
failed to remove DRM

### ISSUE THREAD

**Issue by tujiaki** [apprenticeharper/DeDRM_tools#1187]
calibre デバッグログ
calibre 4.22  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: ja
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.22  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: ja
Successfully initialized third party plugins: DeDRM (6, 8, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 147.500002215 x 147.000002208
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.36] splash screen shown
[0.36] Initializing db...
[0.37] db initialized
[0.37] Constructing main UI...
[1.24] main UI initialized...
[1.24] Hiding splash screen
DeDRM v6.8.0: Trying to decrypt B06Y5TC24Y_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: ＮＨＫ趣味の園芸　やさいの時間　初めてでも大成功！無農薬でかんたん野菜づくり
Got DSN key from database default_key
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kinf2018 file: /Users/Aki2/Library/Application Support/Kindle/storage/.kinf2018
[13.93] splash screen hidden
[13.93] Started up in 13.93 seconds with 266 books
Decrypted key file using IDString '2543f5bdb3cf' and UserName 'Aki2'
DeDRM v6.8.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: ＮＨＫ趣味の園芸　やさいの時間　初めてでも大成功！無農薬でかんたん野菜づくり
Got DSN key from database default_key_1
Found 4 keys to try after 0.9 seconds
Crypto Type is: 2
DeDRM v6.8.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
Was this downloaded with the same installation of Kindle for Mac which is currently on the same machine and user as calibre with DeDRM?

**Comment by tujiaki** [comment]
It was downloaded using Kindle for Windows (Parallels Desktop), because I use macOS Catalina.

**Comment by ElleKayEm** [comment]
See this post about getting books you can DeDRM with versions of Kindle for Mac that run on Catalina:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by tujiaki** [comment]
Thank you very much! It works. I understand that DeDRM must use same computer.
