### ISSUE TITLE
Trying to Remove DRM from Kindle eBook

### ISSUE THREAD

**Issue by CrossReach** [apprenticeharper/DeDRM_tools#119]
Okay, so it's an eBook my friend bought for me in Canada and emailed to me, I can't get it here in Ireland. It's mine and it was bought legally. I want to back it up. It was downloaded onto a Mac. I have Windows.

I used the Kindle DRM Reomver which seems to use Apprentice Alfie's DeDRM tool. I'm showng this because I was able to find the log info easily. Here's the log:

K4MobiDeDrm v5.3.
.
MobiDeDrm v0.41.

MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Complete Works of C. S. Lewis: 
Fantasy Classics, Science Fiction Novels, Religious Studies, Poetry, Speeches & Autobiography: 
The Chronicles of Narnia, ... Letters, Mere Christianity, Miraclesâ€¦
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 4 keys tried.
Traceback (most recent call last):
  File "C:\Program Files (x86)\eBook Converter\Kindle DRM Removal\lib\k4mobidedrm.py", line 249, in 
decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "C:\Program Files (x86)\eBook Converter\Kindle DRM Removal\lib\k4mobidedrm.py", line 223, in 
GetDecryptedBook
    mb.processBook(totalpids)
  File "C:\Program Files (x86)\eBook Converter\Kindle DRM Removal\lib\mobidedrm.py", line 471, in 
processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 4 keys tried.

This may or may not help, but I tried to convert the file to DOCX in calibre just to get log info for it  Here it is:
Convert book 1 of 1 (The Complete Works of C. S. Lewis: Fantasy Classics, Science Fiction Novels, Religious Studies, Poetry, Speeches & Autobiography: The Chronicles of Narnia, ... Letters, Mere Christianity, Miracles…)
Resolved conversion options
calibre version: 2.63.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\Dani\\AppData\\Local\\Temp\\calibre_5hnxwb\\uwkzor.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'docx_custom_page_size': None,
 'docx_no_cover': False,
 'docx_no_toc': False,
 'docx_page_size': u'letter',
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000000004C617B8>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 72.0,
 'margin_left': 72.0,
 'margin_right': 72.0,
 'margin_top': 72.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000000004C61B38>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Dani\\AppData\\Local\\Temp\\calibre_5hnxwb\\97f0hr.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\Dani\AppData\Local\Temp\calibre_5hnxwb\jxgxas.azw
Found KF8 MOBI of type 'standalone'
Python function terminated unexpectedly
  The Complete Works of C. S. Lewis: Fantasy Classics, Science Fiction Novels, Religious Studies, Poetry, Speeches & Autobiography: The Chronicles of Narnia, ... Letters, Mere Christianity, Miracles… (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 132, in main
  File "site.py", line 109, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 190, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 31, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1060, in run
  File "site-packages\calibre\customize\conversion.py", line 241, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 43, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 81, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 144, in check_for_drm
calibre.ebooks.DRMError: The Complete Works of C. S. Lewis: Fantasy Classics, Science Fiction Novels, Religious Studies, Poetry, Speeches & Autobiography: The Chronicles of Narnia, ... Letters, Mere Christianity, Miracles…

**Comment by ElleKayEm** [comment]
These tools work with Kindle books downloaded with Kindle for PC/Mac on the same machine as calibre.  Or if you have an E-ink Kindle, you can enter its serial number into the customization dialog and decrypt the ebooks downloaded to it or for it via the website.  If you can't do either, then you're out of luck.
