### ISSUE TITLE
failed to remove DRM from AZW file

### ISSUE THREAD

**Issue by tcrombez** [apprenticeharper/DeDRM_tools#1191]
I'm trying to remove the DRM from a book in the AZW file format, downloaded (on an older Mac) with Kindle for Mac 1.17. I have installed the latest versions of the plugins. Attached is the log from Calibre.

[tmp1N8Zkz.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5026226/tmp1N8Zkz.txt)

**Comment by ElleKayEm** [comment]
Was that downloaded with the current installation of Kindle for Mac that's on the same machine and user as calibre with DeDRM?

**Comment by tcrombez** [comment]
No, calibre was running on a different machine. I have now tried running calibre on the same (old) machine where the files were downloaded, and it works. Many thanks for the tip.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
