### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by Jaquemart** [apprenticeharper/DeDRM_tools#1195]
Hi, I tried to install the plugin on Calibre 4.22 64 bit on windows 10. Error message states the plugin is invalid.

calibre 4.22 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && Package KFX (from KFX Input) (1, 33, 0) && EpubMerge (2, 10, 0) && Generate Cover (1, 5, 25) && Modify ePub (1, 4, 1) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'C:\\Program Files\\Calibre2\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
That's not the plugin.  Unzip DeDRM_tools_6.8.0.zip.  Install DeDRM_Plugin.zip.

**Comment by FNSga8Qab** [comment]
ElleKayEm, When I unzip DeDRM_tools_6.8.0.zip, I cannot find DeDRM_Plugin.zip in that folder.

**Comment by ElleKayEm** [comment]
You got it from the first link here?

https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.0

Once you unzip DeDRM_tools_6.8.0.zip, you should find 5 files.  DeDRM_Plugin.zip, Obok_plugin.zip, and 3 readme txt files.

**Comment by FNSga8Qab** [comment]
> You got it from the first link here?
> 
> https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.0
> 
> Once you unzip DeDRM_tools_6.8.0.zip, you should find 5 files. DeDRM_Plugin.zip, Obok_plugin.zip, and 3 readme txt files.

Got it! Thank you.
