### ISSUE TITLE
DRM not removed 

### ISSUE THREAD

**Issue by hight996** [apprenticeharper/DeDRM_tools#1198]
It seems as though it depends on the book. I imported two books today. One of them did not have any problem with the DRM Plugin. The other just cannot be converted. here is the import log: 

calibre Debug log
calibre 4.17  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0) && Set KFX metadata (from KFX Output) (1, 43, 0) && KFX Output (1, 43, 0)
calibre 4.17  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0) && Set KFX metadata (from KFX Output) (1, 43, 0) && KFX Output (1, 43, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 78.9126213592 x 78.8275862069
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
[2.19] main UI initialized...
[2.19] Hiding splash screen
[13.66] splash screen hidden
[13.66] Started up in 13.66 seconds with 104 books
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing C:/Users/PC/Documents/My Kindle Content/B004XFYR98_EBOK/B004XFYR98_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\PC\AppData\Local\Temp\calibre_9bdnk4\_w5k_p.kfx-zip
Package KFX (from KFX Input) 1.33.0: Packaging C:\Users\PC\AppData\Local\Temp\calibre_9bdnk4\_w5k_p.kfx-zip
Processing container: B004XFYR98_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
KFXDRMError: Book container B004XFYR98_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\PC\AppData\Local\Temp\calibre_9bdnk4\othdot_add_books\0\B004XFYR98_EBOK.kfx-zip
C:\Program Files (x86)\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added The Kybalion to db in: 0.2
Added 1 books in 0.7 seconds

I have then tried on the latest version of calibre, same problem. I Had tried on the latest version of DeDRM, did not work either.
Thank you for your work.

**Comment by ElleKayEm** [comment]
For KFX format, you need Kindle for PC 1.26 or earlier.  Alternatively, you could disable KFX downloads.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by hight996** [comment]
I use Kindle for PC 1.17 and I cannot disable KFX downloads. Any idea what I could do?
Thank you for the answer.

**Comment by ElleKayEm** [comment]
Yeah, Kindle for PC/Mac can be pretty aggressive about updating.  Be sure to look at the note at that link about preventing unwanted updates.  As long as you can stick with 1.17, you won't get any KFX format because that was the last version that didn't support it.
