### ISSUE TITLE
Opening Patched App crashes

### ISSUE THREAD

**Issue by toxiclabs** [apprenticeharper/DeDRM_tools#12]
Hello

I saw your post and decided to patch the kindle apk 4.8.1.10 and finished patching and install successfully on my nexus 5. However when I open the app it crashes, tried clearing out the cache and stuff and it keeps happening. I was wondering if your apk is working and wondering if you can attached your working version so I can use it. I already spend 4 hrs trying to figure it out with no success. The newest version of Kindle is 4.12, maybe you can rework the patch to work with it. I tried the 4.8.1.10 to patch 4.12 however there is a small error when patching but with the same crash when I tried to open it.

Also what version of Javasdk are you using and the apktools 2.0? to decompile and recompile with signing.

PS I sent a email containing the apk to your apprenticealf@gmail.com
Please let me know if you can take a look into it

thank you

**Comment by toxiclabs** [comment]
I attached the adb logcat for this error
----------------------------------------------------------------------------------------------------------------------------------------

W/BroadcastQueue(  754): Skipping deliver [foreground] BroadcastRecord{b8bc835 u
-1 android.intent.action.SCREEN_OFF} to ReceiverList{11d3456d 15152 com.amazon.k
indle/10210/u0 remote:37521984}: process crashing
I/DisplayManagerService(  754): Display device changed: DisplayDeviceInfo{"Built
-in Screen": uniqueId="local:0", 1080 x 1920, 60.0 fps, supportedRefreshRates [6
0.0], density 480, 442.451 x 443.345 dpi, appVsyncOff 7500000, presDeadline 1266
6667, touch INTERNAL, rotation 0, type BUILT_IN, state OFF, FLAG_DEFAULT_DISPLAY
, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
V/ActivityManager(  754): Display changed displayId=0
D/SurfaceFlinger(  180): Set power mode=0, type=0 flinger=0xb6082000
D/qdhwcomposer(  180): hwc_blank: Blanking display: 0
D/qdhwcomposer(  180): hwc_blank: Done blanking display: 0
D/SurfaceControl(  754): Excessive delay in setPowerMode(): 274ms
E/ANDR-PERF-LOCK( 1826): Failed to apply optimization for resource: 4 level: 0
E/WifiStateMachine(  754): WifiStateMachine CMD_START_SCAN source -2 txSuccessRa
te=0.00 rxSuccessRate=0.00 targetRoamBSSID=00:8e:f2:5b:dc:c6 RSSI=-70
E/WifiStateMachine(  754): WifiStateMachine L2Connected CMD_START_SCAN source -2
 82, 83 -> obsolete
I/PowerManagerService(  754): Waking up from sleep (uid 1000)...
I/DisplayPowerController(  754): Blocking screen on until initial contents have
been drawn.
E/ANDR-PERF-LOCK( 1826): Failed to reset optimization for resource: 4 level: 0
D/SurfaceFlinger(  180): Set power mode=2, type=0 flinger=0xb6082000
D/qdhwcomposer(  180): hwc_blank: Unblanking display: 0
I/DisplayManagerService(  754): Display device changed: DisplayDeviceInfo{"Built
-in Screen": uniqueId="local:0", 1080 x 1920, 60.0 fps, supportedRefreshRates [6
0.0], density 480, 442.451 x 443.345 dpi, appVsyncOff 7500000, presDeadline 1266
6667, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY,
 FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
V/KeyguardServiceDelegate(  754): onScreenTurnedOn(showListener = com.android.in
ternal.policy.impl.PhoneWindowManager$2@2c2e32c)
V/ActivityManager(  754): Display changed displayId=0
V/ActivityManager(  754): Display changed displayId=0
V/UserPresentBroadcastReceiver( 1640): Received Intent { act=android.intent.acti
on.USER_PRESENT flg=0x24000010 cmp=com.google.android.gms/.auth.trustagent.UserP
resentBroadcastReceiver }.
V/KeyguardServiceDelegate(  754): **** SHOWN CALLED ****
I/DisplayPowerController(  754): Unblocked screen on after 126 ms
E/BrcmNfcJni( 1172): nfaConnectionCallback: unknown event ????
D/BrcmNfcJni( 1172): RoutingManager::nfaEeCallback: NFA_EE_SET_TECH_CFG_EVT; sta
tus=0x0
D/BrcmNfcJni( 1172): RoutingManager::nfaEeCallback: NFA_EE_SET_PROTO_CFG_EVT; st
atus=0x0
D/BrcmNfcJni( 1172): RoutingManager::commitRouting
D/BrcmNfcJni( 1172): RoutingManager::nfaEeCallback: NFA_EE_UPDATED_EVT
D/audio_hw_primary(  188): adev_set_parameters: enter: screen_state=on
D/NfcService( 1172): Discovery configuration equal, not updating.
E/WifiStateMachine(  754): cancelDelayedScan -> 84
E/native  (  754): do suspend false
W/BroadcastQueue(  754): Skipping deliver [foreground] BroadcastRecord{11cf1f6e
u-1 android.intent.action.SCREEN_ON} to ReceiverList{2d530e16 15152 com.amazon.k
indle/10210/u0 remote:3e106731}: process crashing
D/qdhwcomposer(  180): hwc_blank: Done unblanking display: 0
D/SurfaceControl(  754): Excessive delay in setPowerMode(): 232ms
E/WifiStateMachine(  754): WifiStateMachine CMD_START_SCAN source -2 txSuccessRa
te=0.00 rxSuccessRate=0.00 targetRoamBSSID=00:8e:f2:5b:dc:c6 RSSI=-69
E/WifiStateMachine(  754): WifiStateMachine starting scan for "CEROwrt"WPA_PSK w
ith 2462
I/Process (15152): Sending signal. PID: 15152 SIG: 9
I/HotwordRecognitionRnr( 1412): Starting hotword detection.
I/MicrophoneInputStream( 1412): mic_starting com.google.android.apps.gsa.speech.
audio.w@238c3b91
I/AudioFlinger(  188): AudioFlinger's thread 0xb448a000 ready to run
I/MicrophoneInputStream( 1412): mic_started com.google.android.apps.gsa.speech.a
udio.w@238c3b91
D/audio_hw_primary(  188): select_devices: out_snd_device(0: none) in_snd_device
(55: voice-rec-mic)
D/msm8974_platform(  188): platform_send_audio_calibration: sending audio calibr
ation for snd_device(55) acdb_id(62)
D/        (  188): Failed to fetch the lookup information of the device 0000003E

E/ACDB-LOADER(  188): Error: ACDB AudProc vol returned = -19
D/audio_hw_primary(  188): enable_snd_device: snd_device(55: voice-rec-mic)
D/audio_hw_primary(  188): enable_audio_route: apply and update mixer path: audi
o-record
I/Icing   ( 1657): Usage reports 1 indexed 0 rejected 0 imm upload true
I/HotwordWorker( 1412): onReady
I/ActivityManager(  754): Process com.amazon.kindle (pid 15152) has died
D/ConnectivityService(  754): updateNetworkScore for NetworkAgentInfo [WIFI () -
 100] to 56
D/ConnectivityService(  754): rematching NetworkAgentInfo [WIFI () - 100]
D/ConnectivityService(  754): Network NetworkAgentInfo [WIFI () - 100] was alrea
dy satisfying request 1. No change.
D/ConnectivityService(  754): notifyType AVAILABLE for NetworkAgentInfo [WIFI ()
 - 100]
D/ConnectivityManager.CallbackHandler(  924): CM callback handler got msg 524290

I/MicrophoneInputStream( 1412): mic_close com.google.android.apps.gsa.speech.aud
io.w@238c3b91
D/audio_hw_primary(  188): disable_audio_route: reset and update mixer path: aud
io-record
D/audio_hw_primary(  188): disable_snd_device: snd_device(55: voice-rec-mic)
I/HotwordRecognitionRnr( 1412): Stopping hotword detection.
I/HotwordRecognitionRnr( 1412): Hotword detection finished
I/ActivityManager(  754): START u0 {act=android.intent.action.MAIN cat=[android.
intent.category.LAUNCHER] flg=0x10200000 cmp=com.amazon.kindle/.UpgradePage (has
 extras)} from uid 10019 on display 0
V/WindowManager(  754): addAppToken: AppWindowToken{149e2dc9 token=Token{72839d0
 ActivityRecord{23b86593 u0 com.amazon.kindle/.UpgradePage t286}}} to stack=1 ta
sk=286 at 0
V/WindowManager(  754): Adding window Window{3b79c7ef u0 Starting com.amazon.kin
dle} at 9 of 15 (after Window{1d237d32 u0 com.android.settings/com.android.setti
ngs.SubSettings})
I/ActivityManager(  754): Start proc 15461:com.amazon.kindle/u0a210 for activity
 com.amazon.kindle/.UpgradePage
V/ActivityManager(  754): Display changed displayId=0
V/DexElementCompatibility(15461): ElementObjectFileFileDexFile is not the right
one for this platform
V/DexElementCompatibility(15461): ElementObjectFileZipFileDexFile is not the rig
ht one for this platform
W/System.err(15461): SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBin
der".
W/System.err(15461): SLF4J: Defaulting to no-operation (NOP) logger implementati
on
W/System.err(15461): SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBind
er for further details.
I/com.amazon.kindle/com.amazon.identity.auth.device.api.MAPInit(15461): Initiali
zing MAP (130050001 / MAPAndroidLib-1.0.753.0) for app com.amazon.kindle
I/AmazonKindle.com.amazon.kcp.application.ReddingApplication(15461): [main]: Pro
cess started: com.amazon.kindle
W/com.amazon.dcp.settings.SettingsCache(15461): Permission to read device settin
gs doesn't exist. This is normal on third-party devices.
I/com.amazon.dcp.settings.SettingsCache(15461): Always use default values for se
ttings
W/com.amazon.kindle/com.amazon.identity.auth.device.utils.ReflectionHelper(15461
): Failed to locate class named com.amazon.acos.util.AmazonBuild. If this is not
 a Kindle device, you can ignore this warning.
I/com.amazon.kindle/com.amazon.identity.auth.device.utils.CentralApkUtils(15461)
: Cannot find amazon authenticator. returning null
I/com.amazon.kindle/com.amazon.identity.auth.device.utils.CentralApkUtils(15461)
: No central apk detected. This should be a 3P device.
I/com.amazon.kindle/com.amazon.identity.auth.device.attribute.DeviceAttributeCac
he(15461): Setting device attribute CentralAPK to false
I/com.amazon.kindle/com.amazon.identity.auth.device.utils.CentralApkUtils(15461)
: Cannot find amazon authenticator. If this is 1P device, this is a bug!
V/WindowManager(  754): Adding window Window{3d2a257e u0 com.amazon.kindle/com.a
mazon.kindle.UpgradePage} at 9 of 16 (before Window{3b79c7ef u0 Starting com.ama
zon.kindle})
I/ActivityManager(  754): Displayed com.amazon.kindle/.UpgradePage: +352ms (tota
l +1m4s161ms)
I/com.amazon.kindle/com.amazon.identity.auth.device.storage.DistributedDataStora
ge(15461): Am the latest application. Setting up alarm to clean database
W/TRThreadPoolExecutor( 1412): Task "NotifyOnDoneFutureTask[log_attempted_search
es_to_kansas]" is a x. Failures of FutureTask can not be detected and exceptions
 will not be propagated by the executor
W/com.amazon.dcp.settings.SettingsCache(15461): Permission to read device settin
gs doesn't exist. This is normal on third-party devices.
I/com.amazon.dcp.settings.SettingsCache(15461): Always use default values for se
ttings
I/com.amazon.kindle/com.amazon.identity.auth.accounts.MultipleAccountPluginHolde
r(15461): Returning Default multiple profile settings
I/com.amazon.kindle/com.amazon.identity.auth.device.utils.CentralApkUtils(15461)
: Cannot find amazon authenticator. If this is 1P device, this is a bug!
I/com.amazon.kindle/com.amazon.identity.auth.device.utils.CentralApkUtils(15461)
: Cannot find amazon authenticator. If this is 1P device, this is a bug!
E/AmazonKindle.com.amazon.kindle.services.authentication.AuthenticationService(1
5461): [AsyncTask #1]: fetchTokens(): not registered; current account ID: MASTER

W/AmazonKindle.com.amazon.system.io.PersistentSetting(15461): [AsyncTask #1]: Pe
rsistentSetting.load: Failed loading parameter file. Is it the first application
 launch ?
I/com.amazon.kindle/com.amazon.identity.auth.device.utils.CentralApkUtils(15461)
: Cannot find amazon authenticator. If this is 1P device, this is a bug!
I/com.amazon.kindle/com.amazon.identity.auth.device.utils.CentralApkUtils(15461)
: Cannot find amazon authenticator. If this is 1P device, this is a bug!
I/com.amazon.kindle/com.amazon.identity.auth.device.utils.CentralApkUtils(15461)
: Cannot find amazon authenticator. If this is 1P device, this is a bug!
I/AmazonKindle.com.amazon.kcp.application.ReddingApplication(15461): [AsyncTask
#1]: Kindle Application started
I/com.amazon.kindle/com.amazon.identity.auth.device.utils.CentralApkUtils(15461)
: Cannot find amazon authenticator. If this is 1P device, this is a bug!
I/AmazonKindle.com.amazon.kcp.application.ReddingApplication(15461): [AsyncTask
#1]: Starting Kindle application
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461): [AsyncTa
sk #1]: App initialization failed!
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461): android.
content.res.Resources$NotFoundException: File res/raw/modules from drawable reso
urce ID #0x7f070012
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at android.content.res.Resources.openRawResource(Resources.java:1187)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at android.content.res.Resources.openRawResource(Resources.java:1158)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at com.amazon.kcp.application.ReddingApplication.initializeModules(ReddingApplic
ation.java:363)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at com.amazon.kcp.application.ReddingApplication.initializeAppState(ReddingAppli
cation.java:319)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at com.amazon.kcp.application.StandaloneApplication.initializeAppState(Standalon
eApplication.java:118)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at com.amazon.kcp.application.ReddingApplication$2.call(ReddingApplication.java:
216)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at com.amazon.kcp.application.ReddingApplication$2.call(ReddingApplication.java:
178)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at com.amazon.kcp.application.StandaloneApplication$1.doInBackground(StandaloneA
pplication.java:98)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at com.amazon.kcp.application.StandaloneApplication$1.doInBackground(StandaloneA
pplication.java:89)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:111
2)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:58
7)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at java.lang.Thread.run(Thread.java:818)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461): Caused b
y: java.io.FileNotFoundException: res/raw/modules
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at android.content.res.AssetManager.openNonAssetNative(Native Method)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at android.content.res.AssetManager.openNonAsset(AssetManager.java:405)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
at android.content.res.Resources.openRawResource(Resources.java:1184)
E/AmazonKindle.com.amazon.kcp.application.StandaloneApplication(15461):
... 14 more
I/AmazonKindle.com.amazon.kindle.UpgradePage(15461): [AsyncTask #2]: KindleBookO
pen start
I/ActivityManager(  754): START u0 {flg=0x14010000 cmp=com.amazon.kindle/com.ama
zon.kcp.library.LibraryFragmentActivity} from uid 10210 on display 0
V/WindowManager(  754): addAppToken: AppWindowToken{251d7b3a token=Token{2a21826
5 ActivityRecord{3f5fcf5c u0 com.amazon.kindle/com.amazon.kcp.library.LibraryFra
gmentActivity t286}}} to stack=1 task=286 at 1
I/com.amazon.kindle/com.amazon.identity.auth.device.utils.CentralApkUtils(15461)
: Cannot find amazon authenticator. If this is 1P device, this is a bug!
D/AndroidRuntime(15461): Shutting down VM
E/AndroidRuntime(15461): FATAL EXCEPTION: main
E/AndroidRuntime(15461): Process: com.amazon.kindle, PID: 15461
E/AndroidRuntime(15461): java.lang.RuntimeException: Unable to start activity Co
mponentInfo{com.amazon.kindle/com.amazon.kcp.library.LibraryFragmentActivity}: j
ava.lang.NullPointerException: Attempt to invoke interface method 'com.amazon.ki
ndle.krx.readingstreams.IReadingStreamsEncoder com.amazon.kindle.krx.IKindleRead
erSDK.getReadingStreamsEncoder()' on a null object reference
E/AndroidRuntime(15461):        at android.app.ActivityThread.performLaunchActiv
ity(ActivityThread.java:2325)
E/AndroidRuntime(15461):        at android.app.ActivityThread.handleLaunchActivi
ty(ActivityThread.java:2387)
E/AndroidRuntime(15461):        at android.app.ActivityThread.access$800(Activit
yThread.java:151)
E/AndroidRuntime(15461):        at android.app.ActivityThread$H.handleMessage(Ac
tivityThread.java:1303)
E/AndroidRuntime(15461):        at android.os.Handler.dispatchMessage(Handler.ja
va:102)
E/AndroidRuntime(15461):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(15461):        at android.app.ActivityThread.main(ActivityThrea
d.java:5254)
E/AndroidRuntime(15461):        at java.lang.reflect.Method.invoke(Native Method
)
E/AndroidRuntime(15461):        at java.lang.reflect.Method.invoke(Method.java:3
72)
E/AndroidRuntime(15461):        at com.android.internal.os.ZygoteInit$MethodAndA
rgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(15461):        at com.android.internal.os.ZygoteInit.main(Zygot
eInit.java:698)
E/AndroidRuntime(15461): Caused by: java.lang.NullPointerException: Attempt to i
nvoke interface method 'com.amazon.kindle.krx.readingstreams.IReadingStreamsEnco
der com.amazon.kindle.krx.IKindleReaderSDK.getReadingStreamsEncoder()' on a null
 object reference
E/AndroidRuntime(15461):        at com.amazon.kcp.redding.ReddingActivity.onCrea
te(ReddingActivity.java:167)
E/AndroidRuntime(15461):        at com.amazon.kcp.library.LibraryFragmentActivit
y.onCreate(LibraryFragmentActivity.java:170)
E/AndroidRuntime(15461):        at android.app.Activity.performCreate(Activity.j
ava:5990)
E/AndroidRuntime(15461):        at android.app.Instrumentation.callActivityOnCre
ate(Instrumentation.java:1106)
E/AndroidRuntime(15461):        at android.app.ActivityThread.performLaunchActiv
ity(ActivityThread.java:2278)
E/AndroidRuntime(15461):        ... 10 more
W/ActivityManager(  754):   Force finishing activity 1 com.amazon.kindle/com.ama
zon.kcp.library.LibraryFragmentActivity
I/OpenGLRenderer(  754): Initialized EGL, version 1.4
W/ActivityManager(  754): Activity pause timeout for ActivityRecord{3f5fcf5c u0
com.amazon.kindle/com.amazon.kcp.library.LibraryFragmentActivity t286 f}
W/ResourceType(  924): No package identifier when getting value for resource num
ber 0x00000000
W/PackageManager(  924): Failure retrieving resources for com.amazon.kindle: Res
ource ID #0x0
D/TaskPersister(  754): removeObsoleteFile: deleting file=285_task.xml
D/ConnectivityService(  754): updateNetworkScore for NetworkAgentInfo [WIFI () -
 100] to 60
D/ConnectivityService(  754): rematching NetworkAgentInfo [WIFI () - 100]
D/ConnectivityService(  754): Network NetworkAgentInfo [WIFI () - 100] was alrea
dy satisfying request 1. No change.
D/ConnectivityService(  754): notifyType AVAILABLE for NetworkAgentInfo [WIFI ()
 - 100]
D/ConnectivityManager.CallbackHandler(  924): CM callback handler got msg 524290

**Comment by apprenticeharper** [comment]
In what time I have I'm concentrating on Android support through extracting keys from a backup file, not by using a patched APK.

**Comment by apprenticeharper** [comment]
Support for Kindle on Android is now in the current release, through a backup file. What little support there was for modifying the APK has now gone.
