### ISSUE TITLE
Importing DRM Free PDF into Calibre with the plugin turned on sometimes corrupts the file

### ISSUE THREAD

**Issue by leavion** [apprenticeharper/DeDRM_tools#120]
Importing DRM Free PDF files into Calibre with the plugin active sometimes corrupts the file. When this happens Adobe Reader shows error 110 however FoxIt reader has no problem with the file nor does Document Viewer. If I deactivate the DeDRM plugin the document is imported fine and there are no errors even with Adobe Reader.

Environment: Ubuntu Linux 14.04.5 LTS
DeDRM 6.4.3
Calibre 2.63
Adobe Reader 9 version 9.5.5 4/26/2013

I attached two files:
Original.pdf is the original file
Bad.pdf is the file after it was imported into Calibre with the DeDRM plugin active. This files causes Adobe Reader to display the error.

[Bad.pdf](https://github.com/apprenticeharper/DeDRM_tools/files/408005/Bad.pdf)
[Original.pdf](https://github.com/apprenticeharper/DeDRM_tools/files/408006/Original.pdf)

**Comment by apprenticeharper** [comment]
Thank you for the report. I shall see if I can reproduce the problem.

**Comment by apprenticeharper** [comment]
OK, I can reproduce the problem. I don't know whether the PDF produced is a valid PDF or has some errors. The ineptpdf script doesn't check whether the PDF is encrypted or not, it just parses the PDF, decrypting any encrypted objects, and then writes it out again.

It would be nicer to just return the original file if there's no encryption. But that will required some delving into PDF internals and so significant changes to the script. I'll see what I can do.

**Comment by apprenticeharper** [comment]
This error should be fixed with DeDRM 6.5.1. Could you check that it's fixed, please?

**Comment by leavion** [comment]
Yes, it seems to be fixed. I tried with the same file and I was able to read it file with Adobe Reader. Then compared the md5sum of the two files and they matched.

Thank you very much for the QUICK fix!

**Comment by apprenticeharper** [comment]
Thanks for the confirmation
