### ISSUE TITLE
DeDRM Failure Log for Calibre

### ISSUE THREAD

**Issue by quilty71** [apprenticeharper/DeDRM_tools#1202]
calibre Debug log
calibre 1.25  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.5
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Starting up...
Started up in 9.57 seconds with 54 books
Worker Launch took: 0.151999950409
Job: 1 Read metadata (0 of 1) finished
Read metadata (0 of 1)
	DeDRM v6.8.0: Trying to decrypt Too-Much-and-Never-Enough.pdf
	DeDRM v6.8.0: Too-Much-and-Never-Enough.pdf is a PDF ebook
	DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.4 seconds
	DeDRM v6.8.0: Exception when getting default Adobe Key after 0.4 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 453, in PDFDecrypt
	  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
	ADEPTError: Adobe Digital Editions not activated
	DeDRM v6.8.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 632, in run
	  File "calibre_plugins.dedrm.__init__", line 507, in PDFDecrypt
	DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Syntax Error: Couldn't find trailer dictionary
	Syntax Error: Couldn't read xref table
	pdfinfo errored out with return code: 1
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 347, in get_file_type_metadata
	  File "site-packages\calibre\customize\builtins.py", line 326, in get_metadata
	  File "site-packages\calibre\ebooks\metadata\pdf.py", line 101, in get_metadata
	ValueError: Could not read info dict from PDF

Added Too-Much-and-Never-Enough to db in: 1.14599990845 seconds
Worker Launch took: 0.144999980927
Job: 2 Convert book 1 of 1 (Too-Much-and-Never-Enough) finished
Convert book 1 of 1 (Too-Much-and-Never-Enough)
	Resolved conversion options
	calibre version: 1.25.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0400F370>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'new_pdf_engine': False,
	 'no_chapters_in_toc': False,
	 'no_images': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleDXOutput object at 0x0400F6D0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Scott\\AppData\\Local\\Temp\\calibre_m07d4o\\fz7uf7.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'unsmarten_punctuation': False,
	 'unwrap_factor': 0.45,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: PDF Input running
	on C:\Users\Scott\AppData\Local\Temp\calibre_m07d4o\wmiwy2.pdf
	Converting file to html...
	Python function terminated unexpectedly
	   (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 192, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 31, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1035, in run
	  File "site-packages\calibre\customize\conversion.py", line 241, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\pdf_input.py", line 50, in convert
	  File "site-packages\calibre\ebooks\pdf\pdftohtml.py", line 97, in pdftohtml
	calibre.ebooks.DRMError

Windows 8
Source of PDF was from an e-mail not sure of original source
[tmplqea_t.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5080095/tmplqea_t.txt)
[tmplqea_t.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5080097/tmplqea_t.txt)

**Comment by ElleKayEm** [comment]
>Source of PDF was from an e-mail not sure of original source

That won't work.  DeDRM unlocks the book with your own account info -- i.e. an Adobe ID.

**Comment by tartley** [comment]
Closing this issue for now. Shout if that isn't right.
