### ISSUE TITLE
DeDRM plug-in not working in Calibre

### ISSUE THREAD

**Issue by lano800** [apprenticeharper/DeDRM_tools#1209]
Using Windows 7, Adobe Digital Editions 2.0.1

calibre Debug log
calibre 1.1  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.4
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::utilities.py - exception when loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::dialogs.py - exception when loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::config.py - exception when loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    0.0 obok::action_err.py - exception when loading translations
Loaded cached store plugin for: ManyBooks at version: 2
Loaded cached store plugin for: Ebookpoint at version: 4
Loaded cached store plugin for: Project Gutenberg at version: 6
Loaded cached store plugin for: XinXii at version: 2
Started up in 10.59 seconds with 1004 books
Worker Launch took: 0.40499997139
Job: 1 Read metadata (0 of 1) finished
Read metadata (0 of 1)
	DeDRM v6.8.0: Trying to decrypt This Is Your Brain on Music.epub
	DeDRM v6.8.0: Verifying zip archive integrity
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 636, in run
	  File "calibre_plugins.dedrm.__init__", line 308, in ePubDecrypt
	  File "site-packages\calibre\customize\zipplugin.py", line 150, in load_module
	  File "calibre_plugins.dedrm.ineptepub", line 48, in <module>
	ImportError: No module named six

Added This Is Your Brain on Music to db in: 0.344000101089 seconds
Worker Launch took: 0.406000137329
Job: 2 Convert book 1 of 1 (This Is Your Brain on Music) finished
Convert book 1 of 1 (This Is Your Brain on Music)
	Resolved conversion options
	calibre version: 1.1.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x040AE1B0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x040AE570>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Diane\\AppData\\Local\\Temp\\calibre_tbedcy\\sm4bvx.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\Diane\AppData\Local\Temp\calibre_tbedcy\mr5dhw.epub
	Python function terminated unexpectedly
	  mr5dhw.epub (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 189, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 31, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1027, in run
	  File "site-packages\calibre\customize\conversion.py", line 241, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 209, in convert
	calibre.ebooks.DRMError: mr5dhw.epub

**Comment by ElleKayEm** [comment]
I'm thinking that version of calibre is way too ancient.

**Comment by lano800** [comment]
Thanks
