### ISSUE TITLE
Amazon for PC importing stop working

### ISSUE THREAD

**Issue by kwhaley7** [apprenticeharper/DeDRM_tools#121]
Latest verions 6.5.0 tools. AZW is still locked when dragging and dropping into calibre 2.63 64-bit. Started over the last weekend. They had been converting fine previously. Well, one of them converted to mobi. The rest stayed AZW. Made sure the plugin had a default option with Amazon for PC installed. Having a bit of trouble getting the log for the adding the books.

**Comment by apprenticeharper** [comment]
From the FAQs.md file:

I cannot solve my problem with the DeDRM plugin, and now I need to ‘post a log’. How do I do that?

Remove the DRMed book from calibre. Click the Preferences drop-down menu and choose 'Restart in debug mode'. Once calibre has re-started, import the problem ebook. Now close calibre. A log will appear that you can copy and paste into a comment at Apprentice Alf's blog, or into a new issue at Apprentice Harper's github repository.

**Comment by FlyingDutchman12** [comment]
Sorry for hijacking, but as a) I have go the same problem and b) I have got a log at hand maybe this helps (both kwhaley7 and myself). I am running Windows 10 with the latest calibre and DeDRM as of today, plus I reinstalled the Amazon for PC reader again today as well.

Not sure whether it makes a difference, but it may be that my trouble started when updating my Amazon for PC to version 1.16 - could be a red herring, though.

```
calibre 2.64 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 1)
Starting up...
Started up in 1.99 seconds with 430 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x9e\rW\xdb \x0b\xa3=\xf0\x8b\xc8v\xbc\xcf\xf4\xfd\xf1\xe4\xb5\xa2R\xb01x\x8e\xc1\xca\xfdi\xc9\xdb\x1a', 'D:\\Benutzer\\Dutchman\\Documents\\My Kindle Content\\B01D1XO06M_EBOK.azw']
DeDRM v6.5.1: Trying to decrypt B01D1XO06M_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: Solarian. Tage der Stille (Solarian-Saga 3) (German Edition)
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.1: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in D:\Benutzer\Dutchman\AppData\Local
Found K4PC 1.9+ kinf2011 file: D:\Benutzer\Dutchman\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3871328959' and UserName '4b72f662656c'
DeDRM v6.5.1: Found 1 new key
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: Solarian. Tage der Stille (Solarian-Saga 3) (German Edition)
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.1: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Added Solarian. Tage der Stille (Solarian-Saga 3) (German Edition) to db in: 1.4
Added 1 books in 2.3 seconds
```
For the records, decrypting e.g. Adobe Digital Editions works fine.

**Comment by FlyingDutchman12** [comment]
Actually for me it might be due to issue #118, as my real user name contains an "umlaut character", and so does the path name. So instead of "Dutchman" it is something with a "ö". And now that I think of it the trouble really started when upgrading Windows from 7 to 10, and before my user name didn't have this umlaut ...

**Comment by kwhaley7** [comment]
I couldn't figure out how to reply to comment on website so went to the
location mentioned and posted my log there. I was able to concert AZW3
yesterday just fine fine.

**Comment by FlyingDutchman12** [comment]
... and I could just confirm with a quick test that with another user with no special characters the decryption works just fine.

Sorry for the confusion ;-)

**Comment by apprenticeharper** [comment]
I'm not quite sure whether kwhaley7's problem is sorted, but it sounds like it is.

**Comment by kwhaley7** [comment]
Mine is not sorted. FlyingDutchman12 was. Let me get that log again and
paste it here.

Kim

**Comment by kwhaley7** [comment]
Here is the log below. I'm able to convert AZW3 but 3 of the 4 AZW files
did not. This is a new log as I couldn't find the old log again. It might
be limited to these particular books since other mobi/azw3 work. epubs work
too from Adobe Digital Editions.

calibre Debug log
calibre 2.63 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 4, 4) && Manage
Series (1, 2, 8) && Read MP3 AudioBook metadata (1, 0, 79) && Find
Duplicates (1, 6, 2)
Starting up...
SMART_DEV (   0.00:  0.003) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.04:  0.865) startup_on_demand listening on port 9090
SMART_DEV (   1.13:  0.013) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.22:  0.000) startup_on_demand broadcast socket listening on
port 54982
SMART_DEV (   2.32:  1.015) run All IP addresses
{'{28BA09CC-3D35-11E6-A914-806E6F6E6963}': [{'broadcast':
'127.255.255.255', 'addr': '127.0.0.1', 'netmask': '255.0.0.0'}],
'{E71847B7-558D-45BD-B314-94A73D64172D}': [{'broadcast': '192.168.1.255',
'addr': '192.168.1.124', 'netmask': '255.255.255.0'}]}
Started up in 19.07 seconds with 28971 books
DeDRM v6.4.4: Trying to decrypt B013MA1SIC_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Conviction: A Dominion Novel
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.4.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.4.4: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\kimwh\AppData\Local
Found K4PC 1.9+ kinf2011 file:
C:\Users\kimwh\AppData\Local\Amazon\Kindle\storage\.kinf2011
DeDRM v6.4.4: Trying to decrypt B00YFZOV06_EBOK.azw
Decrypted key file using IDString '2655246174' and UserName '6b696d7768'
DeDRM v6.4.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Conviction: A Dominion Novel
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.4.4: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in
_run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 606, in run
  File "calibre_plugins.dedrm.__init__", line 556, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.4: Ultimately failed to decrypt after 0.3 seconds
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 3
Decrypting Mobipocket 6 ebook: Reclamation: A Dominion Novel
Found 4 keys to try after 0.1 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.1 seconds
DeDRM v6.4.4: Finished after 0.1 seconds
DeDRM v6.4.4: Trying to decrypt B01B6YBLN8_EBOK.azw
DeDRM v6.4.4: Trying to decrypt B00TA6BN9C_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Ascendance: A Dominion Novel
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.4.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.4.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\kimwh\AppData\Local
Found K4PC 1.9+ kinf2011 file:
C:\Users\kimwh\AppData\Local\Amazon\Kindle\storage\.kinf2011
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Inheritance: A Dominion Novel
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.4.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.4.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\kimwh\AppData\Local
Found K4PC 1.9+ kinf2011 file:
C:\Users\kimwh\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2655246174' and UserName '6b696d7768'
DeDRM v6.4.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Ascendance: A Dominion Novel
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.4.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in
_run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 606, in run
  File "calibre_plugins.dedrm.__init__", line 556, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.4: Ultimately failed to decrypt after 0.2 seconds
Decrypted key file using IDString '2655246174' and UserName '6b696d7768'
DeDRM v6.4.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Inheritance: A Dominion Novel
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.4.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in
_run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 606, in run
  File "calibre_plugins.dedrm.__init__", line 556, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.4: Ultimately failed to decrypt after 0.2 seconds
Added Conviction: A Dominion Novel to db in: 1.9
Added Reclamation: A Dominion Novel to db in: 1.9
Added Ascendance: A Dominion Novel to db in: 1.7
Added Inheritance: A Dominion Novel to db in: 1.9
Added 4 books in 8.5 seconds

**Comment by ElleKayEm** [comment]
The log shows that the one that worked here was already DRM-free.  If the ones that didn't are from a previous installation or from another computer, then that would be the issue.  For Amazon, each app installation and each device has its own unique key.  Try downloading fresh copies on the same computer and user where calibre is installed.

**Comment by kwhaley7** [comment]
They are not from a different machine or installation. They were downloaded
8/7 with earlier ones working find since June when I reinstalled. I will
see about downloading them again and see what happens. As I said, 3 of the
four didn't work. And the fourth did. Later ones did show as AZW3 and were
unlocked.

**Comment by kwhaley7** [comment]
I re-downloaded the two i'm missing (one I already had previously and the
other converted fine) and the log is below. I am testing on another
computer with Kindle for PC installed, recently upgraded to Win 10, and
have calibre installed as well (2.60 64 bit version). It opened them as
AZW3 and converted to mobi/epub just fine. I'm updating both machines to
calibre 2.64 and see what happens.

calibre Debug log
calibre 2.63 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 4, 4) && Manage
Series (1, 2, 8) && Find Duplicates (1, 6, 2) && Read MP3 AudioBook
metadata (1, 0, 79)
Starting up...
SMART_DEV (   0.00:  0.004) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.07:  0.893) startup_on_demand listening on port 9090
SMART_DEV (   1.16:  0.014) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.24:  0.000) startup_on_demand broadcast socket listening on
port 54982
SMART_DEV (   2.33:  1.014) run All IP addresses
{'{28BA09CC-3D35-11E6-A914-806E6F6E6963}': [{'addr': '127.0.0.1',
'broadcast': '127.255.255.255', 'netmask': '255.0.0.0'}],
'{E71847B7-558D-45BD-B314-94A73D64172D}': [{'addr': '192.168.1.124',
'broadcast': '192.168.1.255', 'netmask': '255.255.255.0'}]}
Started up in 14.49 seconds with 28971 books
DeDRM v6.4.4: Trying to decrypt B01B6YBLN8_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Ascendance: A Dominion Novel
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.4.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.4.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\kimwh\AppData\Local
Found K4PC 1.9+ kinf2011 file:
C:\Users\kimwh\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2655246174' and UserName '6b696d7768'
DeDRM v6.4.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Ascendance: A Dominion Novel
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.4.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in
_run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 606, in run
  File "calibre_plugins.dedrm.__init__", line 556, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.4: Ultimately failed to decrypt after 0.2 seconds
DeDRM v6.4.4: Trying to decrypt B013MA1SIC_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Conviction: A Dominion Novel
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.4.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.4.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\kimwh\AppData\Local
Found K4PC 1.9+ kinf2011 file:
C:\Users\kimwh\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2655246174' and UserName '6b696d7768'
DeDRM v6.4.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Conviction: A Dominion Novel
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.4.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in
_run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 606, in run
  File "calibre_plugins.dedrm.__init__", line 556, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.4: Ultimately failed to decrypt after 0.2 seconds
Added Ascendance: A Dominion Novel to db in: 1.7
Added Conviction: A Dominion Novel to db in: 1.7
Added 2 books in 4.4 seconds

**Comment by kwhaley7** [comment]
And the original machine still won't convert those two but the backup
machine will on 2.64.

So, at this point, I've managed to convert them, but the issue is limited
to the particular machine I tried it on. I guess this can be closed and if
I run into it again later, I can post then.

Thanks for the help.

Kim

**Comment by ElleKayEm** [comment]
For the machine not working, see the FAQs about deregistering, uninstalling, deleting all folders, then reinstalling, etc.
