### ISSUE TITLE
Unable to remove Kindle DRM downloaded from Am@zon

### ISSUE THREAD

**Issue by Fenway68** [apprenticeharper/DeDRM_tools#1213]
Last Successful removal with 6.8 and Calibre 4.22 was on August 3; first fail was August 11; tried removing, then updating to 4.23 without luck.  Here is the log from this morning.

thank you in advance.
F68

calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[3.71] main UI initialized...
[3.71] Hiding splash screen
[11.54] splash screen hidden
[11.54] Started up in 11.54 seconds with 371 books
DeDRM v6.8.0: Trying to decrypt Aristotle and Dante Discover the Secrets of the Universe.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Aristotle and Dante Discover the Secrets of the Universe
Found 6 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kindle-info file: /Users/Brown/Library/Application Support/Amazon/Kindle for Mac/storage/.kindle-info
Couldn't decrypt file.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Aristotle and Dante Discover the Secrets of the Universe to db in: 0.1
Added 1 books in 4.0 seconds

**Comment by Fenway68** [comment]
yes, filename before uploading to calibre.

I haven't made any changes to the serial numbers since the last successful conversion on August 3.  
I didn't change any of the order of operations in how I add a new book to Calibre.

Any other thoughts? I will try to remove and re-add the serials.

is the old standalone version still available or only the integrated plug-in?

**Comment by Fenway68** [comment]
removing and re-adding the serials did nothing

**Comment by Fenway68** [comment]
found the issue....wife added a kindle fire, didn't realize i was downloading for transfer to that device rather than the kindle ereader

**Comment by ElleKayEm** [comment]
Glad you figured it out.  FYI, the last version with stand-alone apps is 6.6.3.  So no updates to them since then.  If you're all set, you can close the issue.

**Comment by Fenway68** [comment]
thanks for the help...

**Comment by tejakilaru89** [comment]
calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259 x 93.6245733788
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.53] splash screen shown
[0.53] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
[1.70] main UI initialized...
[1.70] Hiding splash screen
[24.08] splash screen hidden
[24.08] Started up in 24.08 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["9\xa2\xe7X\xd8.\xb2\t\xc3H\xcck\x95\x88\x927`\xd0\xac:O\xc8\x8f\x04\xf1(\xfaW\x01\xa8\x83'", 'C:\\Users\\tejak\\Downloads\\Option Volatility and Pricing.azw3']
DeDRM v6.8.0: Trying to decrypt Option Volatility and Pricing.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Option Volatility and Pricing: Advanced Trading Strategies and Techniques, 2nd Edition
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\tejak\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Option Volatility and Pricing: Advanced Trading Strategies and Techniques, 2nd Edition to db in: 1.7
Added 1 books in 2.8 seconds
Worker Launch took: 0.261000156403
Job: 0 Convert book 1 of 1 (Option Volatility and Pricing: Advanced Trading Strategies and Techniques, 2nd Edition) finished
Convert book 1 of 1 (Option Volatility and Pricing: Advanced Trading Strategies and Techniques, 2nd Edition)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\tejak\\AppData\\Local\\Temp\\calibre_8cuxox\\edmevx.opf'
	  verbose: 2
	  output_profile: u'kindle'
	  cover: u'C:\\Users\\tejak\\AppData\\Local\\Temp\\calibre_8cuxox\\9gmbey.jpeg'
	Resolved conversion options
	calibre version: 4.23.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\tejak\\AppData\\Local\\Temp\\calibre_8cuxox\\9gmbey.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x05CAE350>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x05CAE6B0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\tejak\\AppData\\Local\\Temp\\calibre_8cuxox\\edmevx.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\tejak\AppData\Local\Temp\calibre_8cuxox\j_rhoc.azw3
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  Option Volatility and Pricing: Advanced Trading Strategies and Techniques, 2nd Edition (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Option Volatility and Pricing: Advanced Trading Strategies and Techniques, 2nd Edition

stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xa3\x03\xcan\xdc\x8aP\xfe\x95\xd7\x92,]\x14<Fb\xe5C-G\x90\xf0\x1a\xfd$\x82\x1b\x1a"\x8fN', 'C:\\Users\\tejak\\Downloads\\Option Volatility and Pricing.azw3']
DeDRM v6.8.0: Trying to decrypt Option Volatility and Pricing.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Option Volatility and Pricing: Advanced Trading Strategies and Techniques, 2nd Edition
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\tejak\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Option Volatility and Pricing: Advanced Trading Strategies and Techniques, 2nd Edition to db in: 2.3
Added 1 books in 3.6 seconds

**Comment by ElleKayEm** [comment]
DeDRM works with your own account info.
