### ISSUE TITLE
DeDRM not working

### ISSUE THREAD

**Issue by pso020204** [apprenticeharper/DeDRM_tools#1214]
calibre 偵錯記錄
calibre 4.22  embedded-python: True is64bit: True
Darwin-19.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.5.0', 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.5', ('', '', ''), 'x86_64')
Interface language: zh_TW
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.22  embedded-python: True is64bit: True
Darwin-19.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.5.0', 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.5', ('', '', ''), 'x86_64')
Interface language: zh_TW
Successfully initialized third party plugins: DeDRM (6, 8, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.32] splash screen shown
[0.32] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
[1.28] main UI initialized...
[1.28] Hiding splash screen
[5.46] splash screen hidden
[5.46] Started up in 5.46 seconds with 38 books
Added The Importance of Living-epub to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by pso020204** [comment]
I obtained the book from google play books

**Comment by pso020204** [comment]
My MacBook is at Mac OS ver 10.15.5

**Comment by pso020204** [comment]
Thanks so much

**Comment by ElleKayEm** [comment]
Looks like you have not imported the actual EPUB file into calibre.

**Comment by pso020204** [comment]
Hi. The book is in ACSM format, is that correct?

**Comment by ElleKayEm** [comment]
You will need to install Adobe Digital Editions (on the same machine and user as calibre with DeDRM) and authorize it with an Adobe ID.  Then open the ACSM file in ADE.  An EPUB file will download.  Import that into calibre.

**Comment by pso020204** [comment]
I see! Problem solved now. Thank you so much from Hong Kong ;)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
