### ISSUE TITLE
DeDRM not working- MacOS/Kindle paperwhite

### ISSUE THREAD

**Issue by StewartSpeer1** [apprenticeharper/DeDRM_tools#1215]
DE DRM not working to remove DRM.

Setup
MacAir 3.2
MacOs 10.13.6

Calibre 3.48.0 ( Install notes say that ver 4.23.0 requires higher that MacOs 10.13)
DeDRM plugin 6.8.0

Kindle Paperwhite 
Kindle firmware 5.12.4

Symptoms:
1. Setup appears OK as per inserts
2. DeDRM plugin configured in Calibre with correct Kindle ser no
3, Import of books from Kindle do not appear to DeDRM, even though I set up in Calibre prefs to do it
4. Check of all files in Calibre reader show DRM active on the books
5. Attempt to convert book in Calibre library  results in an error saying that not all pieces are in the dfx-zip file
6. Cleaned out my Calibre library, restarted in debug mode
7. Imported library from Kindle again.
8.  Attempted to convert to Mobi again- same result.
9.  The Calibre debug dumpfile is attached here.  

I attempted to try every setting possible to be found in Calibre, Attempts to import from Kindle/MacOs library as well, with similar error message

[full import and conversion trials- tmpqGrjtZ.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5119910/full.import.and.conversion.trials-.tmpqGrjtZ.txt)
[single file export attempt- tmpZ7r1xu.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5119911/single.file.export.attempt-.tmpZ7r1xu.txt)

Ideas?

**Comment by ElleKayEm** [comment]
You won't be able to DeDRM the file directly from the Paperwhite.  Download from the website choosing that Paperwhite for "download & transfer via USB".  Or I see you have Kindle for Mac.  You can disable KFX downloads and use the files from there.  Or you can use Kindle for Mac 1.26 or earlier.  See this post for all your options:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by tartley** [comment]
I think this issue can be closed.
