### ISSUE TITLE
DeDRM 6.8.0 plugin not working

### ISSUE THREAD

**Issue by jeky91** [apprenticeharper/DeDRM_tools#1217]
Hi everyone,
I'm using Calibre v 4.23 (21st August 2020) on W10 64bit and trying to convert a .prc file that I received from NetGalley (from NetGalley I sent it to my Kindle app, then I downloaded the .prc file on my device and tried to convert it) to read and review the book, but it keeps telling me that the file is protected.

Here's the log.

Thank you.

calibre Log di debug
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Annotations (1, 12, 0) && Kobo Utilities (2, 11, 4) && Obok DeDRM (6, 7, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Annotations (1, 12, 0) && Kobo Utilities (2, 11, 4) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[1.75] splash screen shown
[1.75] Initializing db...
[1.75] db initialized
[1.75] Constructing main UI...
DEBUG:    0.0 Annotations plugin: Error loading libiMobileDevice. This hasn't worked for a while, and is blacklisted in calibre v3.
DEBUG:    0.0 Annotations plugin: Error is:  No module named idevice.libimobiledevice
DEBUG:    0.0 Annotations::reader_app_support.py - loading translations
DEBUG:    0.0 Annotations::common_utils.py - loading translations
DEBUG:    0.0 Annotations::appearance.py - loading translations
DEBUG:    0.0 Annotations::config.py - loading translations
DEBUG:    0.0 Annotations::annotated_books.py - loading translations
DEBUG:    0.3 Annotations::action.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
DEBUG:    2.1 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    2.1 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    2.1 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    2.1 device_driver_name - could not load extended driver. Exception= No module named kobotouch_extended.device.driver
DEBUG:    2.1 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouch'
DEBUG:    2.1 device_driver_name - could not load extended driver. Exception= No module named kobotouch_extended.device.driver
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
[4.45] main UI initialized...
[4.45] Hiding splash screen
[95.23] splash screen hidden
[95.23] Started up in 95.23 seconds with 0 books
DeDRM v6.8.0: Trying to decrypt KNZGOXDAPU2JFB5CMXZOJZEQ4TOE4YH7_PDOC.prc
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Wreckage of Us(Uncorrected Proof)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\jessi\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\jessi\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3668408367' and UserName '6a65737369'
DeDRM v6.8.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Wreckage of Us(Uncorrected Proof)
Got DSN key from database default_key_1
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.8.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Wreckage of Us(Uncorrected Proof) to db in: 1.9
Added 1 books in 3.7 seconds
Worker Launch took: 0.262000083923
Job: 0 Converti libro 1 di 1 (The Wreckage of Us(Uncorrected Proof)) finished
Converti libro 1 di 1 (The Wreckage of Us(Uncorrected Proof))
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\jessi\\AppData\\Local\\Temp\\calibre_gugdcl\\e20atr.opf'
	  cover: u'C:\\Users\\jessi\\AppData\\Local\\Temp\\calibre_gugdcl\\wnt4if.jpeg'
	  output_profile: u'kobo'
	  verbose: 2
	Resolved conversion options
	calibre version: 4.23.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\jessi\\AppData\\Local\\Temp\\calibre_gugdcl\\wnt4if.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000019AF654E288>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x0000019AF6679C48>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\jessi\\AppData\\Local\\Temp\\calibre_gugdcl\\e20atr.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\jessi\AppData\Local\Temp\calibre_gugdcl\isqcfx.prc
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  The Wreckage of Us(Uncorrected Proof) (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: The Wreckage of Us(Uncorrected Proof)

**Comment by ElleKayEm** [comment]
There isn't currently a way to decrypt Kindle books from Android or iOS.  If you have an E-ink Kindle (not a Fire), you could decrypt the book from there.  Or NetGalley books usually also have an Adobe DRM EPUB or PDF option.  You'd need to install Adobe Digital Editions on the same machine and user as calibre with DeDRM.  Then authorize it with an Adobe ID.  Open the ACSM file downloaded from NetGalley in ADE, then add the EPUB to calibre and DeDRM will work on that.

**Comment by tartley** [comment]
I think this issue can be closed now.
