### ISSUE TITLE
Calibre De_DRM Plug-in for Amazon Kindle Fire Not Working

### ISSUE THREAD

**Issue by Colormelala** [apprenticeharper/DeDRM_tools#1219]
I downloaded Calibre and I downloaded the De_DRM Plug-in. I followed the Read Me text and I installed the De_DRM Plug-in. I customized the Plug-in via the eLink Kindle eBooks by putting in my Kindle serial number (copied and pasted). However, I am still having trouble with opening my book to read and I definitely cannot convert it. 

calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 109.837837838 x 109.837837838
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.53] splash screen shown
[0.53] Initializing db...
[0.55] db initialized
[0.55] Constructing main UI...
[1.30] main UI initialized...
[1.30] Hiding splash screen
[12.39] splash screen hidden
[12.39] Started up in 12.39 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['0\x84P\x90\x97\x13:\xf6\x80 \x16\xc0\xa7l\xe3^j\xed8\xcd\x89\xcdE\x7f\x8a\xdd\xa4@\xe6G\xbf\x06', 'C:\\Users\\color\\Downloads\\DeDRM_tools_6.8.0\\DeDRM_Plugin.zip']
Downloading plugin ZIP attachment:  https://code.calibre-ebook.com/plugins/244202.zip
Installing plugin:  C:\Users\color\AppData\Local\Temp\calibre_wb3_vt\5oburd.zip
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["o\x85Q\xb0\xbd:r\x9b\xb6\xe3}\xdem1\xac\xa5\xce'9\x86E\xec\x10~\x94r\x11\xba\x03T\xf7\xf4", 'C:\\Users\\color\\Downloads\\Generation to Generation (The Guilford Family Therapy Series).azw3']
DeDRM v6.8.0: Trying to decrypt Generation to Generation (The Guilford Family Therapy Series).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Generation to Generation (The Guilford Family Therapy Series)
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\color\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Generation to Generation (The Guilford Family Therapy Series) to db in: 0.1
Added 1 books in 1.4 seconds
Worker Launch took: 0.46799993515
Worker Launch took: 0.792000055313
Worker Launch took: 0.960000038147
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xec\x9c\xff\xea\xf3\xe0\xcb=\xab\xec\x80O\xc3M\x1d=\xf9\xbc_\xcf\x19\x13\x97\xffO\x96\xa5\x1e\x96\xc1@\xfc', 'C:\\Users\\color\\Downloads\\DeDRM_tools_6.8.0\\DeDRM_Plugin.zip']

**Comment by ElleKayEm** [comment]
Books from or for a Kindle Fire cannot be decrypted.  Other options are E-ink Kindle or Kindle for PC.  See this post for details:  
https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Colormelala** [comment]
OMG! Thank you so much. I downloaded the older version of Kindle for PC. 

Here is the link for others if they are having the same troubles. 
https://www.epubsoft.com/soft/kindle-for-pc.html#:~:text=Read%20more%20than%201%20million,and%20highlights%20across%20various%20devices.
