### ISSUE TITLE
Thank You apprenticeharper. I am finally able to take print out of  DRM azw converted into pdf

### ISSUE THREAD

**Issue by onlinehippy** [apprenticeharper/DeDRM_tools#122]
I was not able to take print out of my book which i bought from amazon for examination purpose.After surfing  a lot i found out about your DeDRM_tools and it's the best tool  amongst lot of crap.It helped me to make my ebook DRM free
Thanks.

I have small query my generated pdf has 60% free space and very less text .How to merge all text so that i am able to reduce the number of pages required for printing?

**Comment by rahulludhani** [comment]
I was not able to take print out of my book which i bought from amazon for examination purpose.After surfing  a lot i found out about your DeDRM_tools and it's the best tool  amongst lot of crap.
Thanks

**Comment by ElleKayEm** [comment]
For ebook questions that are not about removing DRM, I suggest checking out the forums at MoileRead.com.
