### ISSUE TITLE
DeDRM Worked Once, Doesn't work anymore

### ISSUE THREAD

**Issue by Vorox3** [apprenticeharper/DeDRM_tools#1220]
I used this once on a kindle book I purchased and it worked the first time. I then tried other kindle books without changing anything and they would no longer deDRM.

I have attached the log.
[calibrelog_8_28_2020.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5142688/calibrelog_8_28_2020.txt)

**Comment by Vorox3** [comment]
I am using Kindle for PC 1.28, but I followed the instructions in the FAQ to disable KFX

**Comment by ElleKayEm** [comment]
The method described in the FAQs for disabling KFX only works up to Kindle for PC 1.24.3 (51068).  And sure enough, that log shows a KFX format book.  See this post for your options:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Vorox3** [comment]
Yeah, I was just running into the issue where I couldn't register the app. Still can't, even with the guides help.

**Comment by ElleKayEm** [comment]
Someone over at the blog on a Mac had that issue.  They solved the problem by uninstalling and removing all Kindle related folders/files.  Then reinstalling.  Someone on a PC had tried that to no avail as far as they ever said.  Have a look at this page to see if you can deregister from the website, then try registering:

amazon.com/mycd

**Comment by Vorox3** [comment]
This wasn't the issue. The issue was left over keys in the registry from the previous install. Deleted those and it allowed me to log in.

**Comment by ElleKayEm** [comment]
Thanks for letting us know.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
