### ISSUE TITLE
Will the deDRM plugin work with Calibre 5 (which will use Python 3)?

### ISSUE THREAD

**Issue by SuffolkPunch** [apprenticeharper/DeDRM_tools#1221]
Hello,

Calibre 5 is switching to use Python 3. Calibre plugins which use Python 2 may not continue to work - please see  [https://www.mobileread.com/forums/showthread.php?t=331543](url)

Is the deDRM Calibre plugin (and the deDRM code) going to be updated to run with Calibre 5?

Hope the answer is "Yes"!

**Comment by ElleKayEm** [comment]
Not yet, but it is being worked on.  There's a pull request and also some discussion in issue #979.

**Comment by chrisisbd** [comment]
I have hit this problem by simply keeping my system up to date!  I.e. I have xubuntu 20.04 which has a version of calibre that requires Python 3 so dedrm has simply stopped working.  Help!

**Comment by ElleKayEm** [comment]
The current release of calibre (4.23) still has embedded Python 2.  So you can use that for now.

**Comment by mu22le** [comment]
Isn't this a duplicate of #979?

**Comment by ElleKayEm** [comment]
Yes.  It's not the first, and I'm sure it won't be the last.

**Comment by tartley** [comment]
Duplicate of #1253
