### ISSUE TITLE
problem with ADE ebooks

### ISSUE THREAD

**Issue by fedormyskin** [apprenticeharper/DeDRM_tools#1224]
I can't remove the DRM for these 2 books:

calibre Debug log
calibre 4.11.2  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.11.2  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[1.31] main UI initialized...
[1.31] Hiding splash screen
[31.85] splash screen hidden
[31.85] Started up in 31.85 seconds with 22 books
DeDRM v6.8.0: Trying to decrypt Ultimo viene il corvo.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: Ultimo viene il corvo.epub is a secure Adobe Adept ePub
DeDRM v6.8.0: Trying Encryption key default_key
Could not decrypt zkcqlc.epub. Wrong key
DeDRM v6.8.0: Failed to decrypt with key default_key after 0.0 seconds
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v6.8.0: Trying to decrypt Prima che tu dica «Pronto».epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: Prima che tu dica «Pronto».epub is a secure Adobe Adept ePub
DeDRM v6.8.0: Trying Encryption key default_key
Could not decrypt Qj9Nmq.epub. Wrong key
DeDRM v6.8.0: Failed to decrypt with key default_key after 0.0 seconds
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Ultimo viene il corvo to db in: 0.0
Added Prima che tu dica «Pronto» to db in: 0.0
Added 2 books in 0.9 seconds

**Comment by ElleKayEm** [comment]
The default key that DeDRM tried was the wrong key for these books.  Were these books downloaded with Adobe Digital Editions authorized with your Adobe ID on the same machine and user as calibre with DeDRM?

**Comment by fedormyskin** [comment]
No, they were downloaded on a different computer? Is it still possible to
remove the DRM?

**Comment by ElleKayEm** [comment]
Since that computer must be authorized with a different Adobe ID than this one, you'll need to install calibre with DeDRM on that computer to retrieve the key associated with that Adobe ID.

**Comment by fedormyskin** [comment]
Ok, thanks

**Comment by tartley** [comment]
I think this issue can be closed now.
