### ISSUE TITLE
unable to convert azw3 with v6.80

### ISSUE THREAD

**Issue by williemctell** [apprenticeharper/DeDRM_tools#1228]
I just downloaded a Kindle book and was unable to remove the DRM with v6.80.  Here's the debug log:

calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 101.6 x 101.6
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
[1.75] main UI initialized...
[1.75] Hiding splash screen
[6.20] splash screen hidden
[6.20] Started up in 6.20 seconds with 1839 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\n\xbb\xf2\x0e\xf2\x1b\x82\xaf\xe2A\xb6j\xe0\x05\xaa\x92\x11\xfe\x01\x1c\xdbD+\x8f\xf0\xf3 <T\x10g\xb7', 'P:\\Squeeze Me.azw3']
DeDRM v6.8.0: Trying to decrypt Squeeze Me.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Squeeze Me
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\willi\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\willi\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '451177122' and UserName '77696c6c69'
DeDRM v6.8.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Squeeze Me
Got DSN key from database default_key_1
Found 4 keys to try after 4.8 seconds
Crypto Type is: 2
DeDRM v6.8.0: Ultimately failed to decrypt after 4.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 4.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Squeeze Me to db in: 1.6
Added 1 books in 6.7 seconds
Worker Launch took: 0.0659999847412

**Comment by ElleKayEm** [comment]
If that's for an E-ink Kindle (not a Fire), you need to enter its serial number into DeDRM's customization.

**Comment by williemctell** [comment]
From look at another user's post I realized that I didn't have the Kindle software installed on my new desktop machine.  I installed Kindle for PC, downloaded the book,  removed the book from Calibre,  and tried the import again from the Kindle directory in appdata/local/  Here's the latest debug log:

calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 101.6 x 101.6
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.36] splash screen shown
[0.36] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
[1.80] main UI initialized...
[1.80] Hiding splash screen
[4.19] splash screen hidden
[4.19] Started up in 4.19 seconds with 1839 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['1+B\x8c\xe2\xfbT\n\t\xc3>\x85\xb5\xa7\x10\xce-\xb1\x0eB\xba\\4"x551(\xb8\x0cQ', 'C:\\Users\\willi\\Documents\\My Kindle Content\\B0841NPVX5_EBOK\\B0841NPVX5_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing C:\Users\willi\Documents\My Kindle Content\B0841NPVX5_EBOK\B0841NPVX5_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\willi\AppData\Local\Temp\calibre_mftxfx\m_u7zv.kfx-zip
DeDRM v6.8.0: Trying to decrypt m_u7zv.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: m_u7zv
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.11cbe169-ff5e-4f4b-95a4-362842dc4ef9.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\willi\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\willi\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '451177122' and UserName '77696c6c69'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: m_u7zv
Got DSN key from database default_key_1
Found 1 keys to try after 4.7 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.11cbe169-ff5e-4f4b-95a4-362842dc4ef9.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 4.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 4.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.33.0: Packaging C:\Users\willi\AppData\Local\Temp\calibre_mftxfx\m_u7zv.kfx-zip
Processing container: B0841NPVX5_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
KFXDRMError: Book container B0841NPVX5_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\willi\AppData\Local\Temp\calibre_mftxfx\agh6ac_add_books\0\B0841NPVX5_EBOK.kfx-zip
Import symbol table YJ_symbols version 10 max_id 778 exceeds known table size 777
Added Squeeze Me to db in: 2.0
Added 1 books in 7.1 seconds
Worker Launch took: 0.0830001831055

**Comment by ElleKayEm** [comment]
A Kindle for PC key was found in the first log, but of course that didn't work for that copy.   For KFX format, you'll need Kindle for PC version 1.26 or earlier.  Or you can disable KFX downloads.  See this post for details:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by williemctell** [comment]
Thanks for your help.  I realized that the simplest thing would be to use my 2010 Kindle Keyboard.  I registered the S/N on the Amazon site and will use it in the future.  I was able to process my download without a hitch.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by williemctell** [comment]
It's fixed.  Close the ticket, please.
