### ISSUE TITLE
XML with BOM erroneously fails Obok decryption

### ISSUE THREAD

**Issue by stormborn2** [apprenticeharper/DeDRM_tools#123]
The EPUB standard requires that XML documents have UTF-8 or UTF-16 encoding, in both cases an XML file may start with a BOM. XML decryption verification code in obok.py doesn't account for the possibility of a BOM, thus correctly decrypted XML can get flagged as a failure and the entire book will erroneously fail to decrypt. See the discussion under https://apprenticealf.wordpress.com/2012/09/10/drm-removal-tools-for-ebooks/#comment-55726 for an example of this.

**Comment by tobybryans** [comment]
Thank you for opening this bug! Let me know if I can help at all with the file that caused me that problem or anything else.

**Comment by apprenticeharper** [comment]
Thank you for this report. Yes, that looks like a bug.

**Comment by tobybryans** [comment]
I can confirm that works with the epub that I had the problem with, thank you!

Also, it works with the latest version of the Kobo Windows application.

**Comment by apprenticeharper** [comment]
Released in v6.5.2
