### ISSUE TITLE
Can't DeDRM

### ISSUE THREAD

**Issue by ItsTiage** [apprenticeharper/DeDRM_tools#1231]
Hello,
I've installed this DeDRM plugin for calibre togheter with the KMZ Input plugin and tried to import on my calibre library a book downloaded with the 1.29 PC Kindel app. But the imported ebook   was still protected by DRM. Here's the copy of the log file:

calibre Log di debug
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.31] splash screen shown
[0.31] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
Loaded cached store plugin for: ebook.de at version: 6
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
[1.36] main UI initialized...
[1.36] Hiding splash screen
[5.09] splash screen hidden
[5.09] Started up in 5.09 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xfd*@\xbdO,\x0f\x13\x86\xca\x1d\x9d0\xbcL\x11f\x8c\x93\x12)\x11\x02-\xef\xec*\xdb\x8dd '", 'C:\\Users\\tiago\\Documents\\My Kindle Content\\B0899RKNTM_EBOK\\B0899RKNTM_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing C:\Users\tiago\Documents\My Kindle Content\B0899RKNTM_EBOK\B0899RKNTM_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\tiago\AppData\Local\Temp\calibre_e5gap7\y6dndl.kfx-zip
DeDRM v6.8.0: Trying to decrypt y6dndl.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: y6dndl
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.e31a0f85-6f8d-4a33-88be-d7d8e0dafe85.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\tiago\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\tiago\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3833541472' and UserName '746961676f'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: y6dndl
Got DSN key from database default_key_1
Found 1 keys to try after 8.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.e31a0f85-6f8d-4a33-88be-d7d8e0dafe85.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 8.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 8.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.33.0: Packaging C:\Users\tiago\AppData\Local\Temp\calibre_e5gap7\y6dndl.kfx-zip
Processing container: B0899RKNTM_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
KFXDRMError: Book container B0899RKNTM_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\tiago\AppData\Local\Temp\calibre_e5gap7\0sej7g_add_books\0\B0899RKNTM_EBOK.kfx-zip
Added Bomba atomica (Italian Edition) to db in: 1.3
Added 1 books in 9.9 seconds

Thank you in advance!

**Comment by ElleKayEm** [comment]
Use Kindle for PC 1.26 or earlier.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by tartley** [comment]
I think this issue can be closed for now.
