### ISSUE TITLE
dedrm failure on epub copied from ADE 3.0

### ISSUE THREAD

**Issue by chrisisbd** [apprenticeharper/DeDRM_tools#1234]
I have a DRM'ed book that I have successfully downloaded into ADE 3.0 on my (virtual) XP system.

I copied the file into Calibre 4.23 (which has dedrm installed) on my Linux system but the DRM removal failed.

The log from the import is:-

Traceback (most recent call last):
  File "site-packages/calibre/gui2/viewer/ui.py", line 468, in _load_ebook_worker
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 234, in prepare_book
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 191, in do_convert
ConversionFailure: Failed to convert book: /home/chris/dld/books/Unknown/PCC Accountability (62)/PCC Accountability - Unknown.epub with error:
InputFormatPlugin: EPUB Input running
on /home/chris/dld/books/Unknown/PCC Accountability (62)/PCC Accountability - Unknown.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 189, in main
  File "<string>", line 1, in <module>
  File "site-packages/calibre/srv/render_book.py", line 862, in viewer_main
  File "site-packages/calibre/srv/render_book.py", line 855, in render_for_viewer
  File "site-packages/calibre/srv/render_book.py", line 830, in render
  File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 64, in extract_book
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 290, in convert
DRMError: PCC Accountability - Unknown.epub

Any ideas what might be wrong?

**Comment by ElleKayEm** [comment]
Since DRM removal happens on import (not conversion), we need the log of adding the book to calibre.  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by chrisisbd** [comment]
Oops, sorry, that was what I had intended to provide.

Here it is:-

calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Linux-5.4.0-47-generic-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-47-generic', '#51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020')
Python 2.7.16
Linux: ('debian', 'bullseye/sid', '')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: True
Linux-5.4.0-47-generic-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-47-generic', '#51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020')
Python 2.7.16
Linux: ('debian', 'bullseye/sid', '')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 157.825242718 x 158.566473988
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[0.63] main UI initialized...
[0.63] Hiding splash screen
[7.38] splash screen hidden
[7.40] Started up in 7.40 seconds with 55 books
['zenity', '--modal', '--file-selection', '--title=Select books', '--separator=\n', '--attach=96469015', '--filename=/tmp/.fgdfg.gdfhjdhf*&^839', '--file-filter=Books | *.lrf *.rar *.zip *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf', '--file-filter=EPUB books | *.epub *.kepub', '--file-filter=Kindle books | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=PDF books | *.pdf *.azw4', '--file-filter=HTML books | *.htm *.html *.xhtm *.xhtml', '--file-filter=LIT books | *.lit', '--file-filter=Text books | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Comics | *.cbz *.cbr *.cbc', '--file-filter=Archives | *.zip *.rar', '--file-filter=Wordprocessor files | *.odt *.doc *.docx', '--file-filter=All files | *', '--multiple']
DeDRM v6.8.0: Trying to decrypt PCC Accountability.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: PCC Accountability.epub is a secure Adobe Adept ePub
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v6.8.0: Running adobekey.py under Wine
DeDRM v6.8.0: Command line: 'wine python.exe "/home/chris/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/chris/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
/bin/sh: 1: wine: not found
DeDRM v6.8.0: Found and decrypted 0 key files
DeDRM v6.8.0: Exception when getting default Adobe Key after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 357, in ePubDecrypt
IndexError: list index out of range
DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added PCC Accountability to db in: 0.1
Added 1 books in 0.4 seconds

**Comment by chrisisbd** [comment]
Oh, by the way, dedrm is working well for me with kindle azw3 books.  Maybe it needs some more configuration of the plugin to work with epub from ADE.

**Comment by ElleKayEm** [comment]
DeDRM is unable to retrieve the Adobe key on this setup.  

> DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v6.8.0: Running adobekey.py under Wine
DeDRM v6.8.0: Command line: 'wine python.exe "/home/chris/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/chris/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
/bin/sh: 1: wine: not found

A workaround might be running adobekey.py where you have ADE and importing the key into the DeDRM customization.

**Comment by chrisisbd** [comment]
But I'm not running Wine, this is just Calibre running directly on Linux.  So "...running adobekey.py where you have ADE..." isn't possible as it's not a Windows PC and so can't run ADE.

Is it possible to manually get the key from ADE and then put it into Calibre's DeDRM?

**Comment by ajshell1** [comment]
You said you had a virtual XP system where you had ADE installed. Run  adobekey.pyw inside that virtual machine after installing python2.7 and pycrypto. Then transfer the file produced by that script to your Linux machine and add the key to the plugin using the plugin's configuration menu.

I'm on Linux as well, and I've done this successfully more than once.

Also, the FAQ recommends using Adobe Digital Editions version 2.01.

**Comment by chrisisbd** [comment]
Yes, OK, that has all worked thank you!  I can now read the book in 'native' Linux as well as in a rather creaky old Windows XP running in VirtualBox.

**Comment by ElleKayEm** [comment]
@ajshell1 

Thanks for explaining it better than I did!
