### ISSUE TITLE
Trying to remove from book from BAM

### ISSUE THREAD

**Issue by tacocatwizard** [apprenticeharper/DeDRM_tools#1236]
Trying to remove from a book bought from Books a Million. Registered it to my computer only and I want it on my iPad. 

calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 166.443686007 x 166.254545455
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.25] splash screen shown
[1.25] Initializing db...
[1.31] db initialized
[1.31] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[3.47] main UI initialized...
[3.47] Hiding splash screen
[8.25] splash screen hidden
[8.25] Started up in 8.25 seconds with 2 books
DeDRM v6.8.0: Trying to decrypt Co-12.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: Co-12.epub is a secure Adobe Adept ePub
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v6.8.0: Trying a new default key
Could not decrypt 5yx0ci.epub. Wrong key
DeDRM v6.8.0: Failed to decrypt with new default key after 0.5 seconds
DeDRM v6.8.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Co to db in: 0.1
Added 1 books in 1.3 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x05E74B50>> ignored
Worker Launch took: 0.132000207901

**Comment by tacocatwizard** [comment]
Figured it out--I can't currently open it on this computer so this didn't work

**Comment by ElleKayEm** [comment]
Just for anyone with the same issue:  Adobe Digital Editions 2.0.1 authorized with your Adobe ID needs to be on the same machine and user as calibre with DeDRM to retrieve the key.
