### ISSUE TITLE
Can't convert DRM file to mobi or epub

### ISSUE THREAD

**Issue by Tarz-an** [apprenticeharper/DeDRM_tools#1238]
I have purchased a book from Amazon UK and can read the book in Calibre as is but won't let me convert to .mobi or .epub to upload to kindle Aus or iPad.
Here is the log for you - appreciate any help you can give - thanks.
calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && Goodreads (1, 4, 0) && Count Pages (1, 10, 0) && MondoUrania (0, 2, 3) && Find Duplicates (1, 7, 2) && Kindle Collections (1, 7, 26) && KindleUnpack - The Plugin (0, 82, 1) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && FanFicFare (3, 23, 0) && CalibreSpy (1, 0, 82) && Obok DeDRM (6, 7, 0) && Kindle hi-res covers (0, 4, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && Goodreads (1, 4, 0) && Count Pages (1, 10, 0) && MondoUrania (0, 2, 3) && Find Duplicates (1, 7, 2) && Kindle Collections (1, 7, 26) && KindleUnpack - The Plugin (0, 82, 1) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && FanFicFare (3, 23, 0) && CalibreSpy (1, 0, 82) && Obok DeDRM (6, 7, 0) && Kindle hi-res covers (0, 4, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 80.2105263158 x 79.5130434783
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.59] db initialized
[0.59] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
FFF: INFO: 2020-09-18 11:55:24,414: calibre_plugins.fanficfare_plugin.prefs(215): Attempting to read settings from predecessor--FFDL
FFF: INFO: 2020-09-18 11:55:24,414: calibre_plugins.fanficfare_plugin.prefs(220): Using default settings
FFF: DEBUG: 2020-09-18 11:55:24,417: calibre_plugins.fanficfare_plugin.fff_plugin(210): Plugin FanFicFare macmenuhack file_path:C:\Users\Roanta\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
CalibreSpy: initialization_complete
[3.30] main UI initialized...
[3.30] Hiding splash screen
[1161.67] splash screen hidden
[1161.67] Started up in 1161.67 seconds with 4584 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x97\x9a\x0e\x08w\x92M\xfa\xfa\xd4tm\x90\x83\xe2\x14\x80\xf8\xa2P\x9b\xacn\xdeV~\x9bL\xbe\xbc?\x99', 'C:\\Users\\Roanta\\Documents\\My Kindle Content\\B07BBVRR8C_EBOK\\B07BBVRR8C_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing C:\Users\Roanta\Documents\My Kindle Content\B07BBVRR8C_EBOK\B07BBVRR8C_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Roanta\AppData\Local\Temp\calibre_9psft2\itumxp.kfx-zip
DeDRM v6.8.0: Trying to decrypt itumxp.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: itumxp
Got DSN key from database default_key_3
Found 3 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.6e87cd5a-5153-4c35-a00a-be9c9494dad2.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Roanta\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Roanta\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '77879533' and UserName '526f616e7461'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: itumxp
Got DSN key from database default_key_1
Found 1 keys to try after 7.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.6e87cd5a-5153-4c35-a00a-be9c9494dad2.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 7.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 7.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\Roanta\AppData\Local\Temp\calibre_9psft2\itumxp.kfx-zip
Processing container: B07BBVRR8C_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container B07BBVRR8C_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Roanta\AppData\Local\Temp\calibre_9psft2\jk8huk_add_books\0\B07BBVRR8C_EBOK.kfx-zip
Added The Lighthouse Keeper’s Daughter: A gripping, unforgettable page-turner to db in: 0.1
Added 1 books in 8.9 seconds
Worker Launch took: 0.123000144958
Job: 0 Convert book 1 of 1 (The Lighthouse Keeper’s Daughter: A gripping, unforgettable page-turner) finished
Convert book 1 of 1 (The Lighthouse Keeper’s Daughter: A gripping, unforgettable page-turner)
	Conversion options changed from defaults:
	  allow_conversion_with_errors: True
	  cover: u'C:\\Users\\Roanta\\AppData\\Local\\Temp\\calibre_9psft2\\7f2ogg.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\Roanta\\AppData\\Local\\Temp\\calibre_9psft2\\pu3i4e.opf'
	  output_profile: u'kindle_pw3'
	  verbose: 2
	  input_profile: u'kindle'
	Resolved conversion options
	calibre version: 4.23.0
	{'allow_conversion_with_errors': True,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Roanta\\AppData\\Local\\Temp\\calibre_9psft2\\7f2ogg.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.KindleInput object at 0x060116D0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x06011A10>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Roanta\\AppData\\Local\\Temp\\calibre_9psft2\\pu3i4e.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\Roanta\AppData\Local\Temp\calibre_9psft2\uxkgsj.kfx-zip
	Software versions: KFX Input 1.34.0, calibre 4.23, Windows-10-10.0.18362-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\Roanta\AppData\Local\Temp\calibre_9psft2\uxkgsj.kfx-zip
	Processing container: B07BBVRR8C_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
	KFXDRMError: Book container B07BBVRR8C_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 123, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
Use Kindle for PC version 1.26 or earlier.  Or disable KFX downloads.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Tarz-an** [comment]
Thank you :)
