### ISSUE TITLE
DeDRM 6.8.0

### ISSUE THREAD

**Issue by MacAodhain** [apprenticeharper/DeDRM_tools#1240]
Hardware: IMac
OS: Catalina V10.5.6
Calibre: V 4.23.0

Installed Calibre with DeDrm today.  Can add newly purchased AZW (Kindle for Mac) file to Calibre library which loads as KFX-ZIP file.  When I try to open or convert to EPUB it fails with message "This Book is locked by DRM".  I've used the latest version of Calibre and DeDRM and followed the recommended installation instructions but can't get this to work.  Would appreciate any help.

I've attached the Calibre debug file.
[tmpaj_Nf2.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5249583/tmpaj_Nf2.txt)

**Comment by ElleKayEm** [comment]
With KFX files, you will need to use Kindle for Mac version 1.26.  Or you can disable KFX downloads up to the current version of Kindle for Mac.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by MacAodhain** [comment]
Thanks so much for your prompt and helpful response.

Disabling KFX downloads did the trick.

Much appreciated.


Regards

Brian

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
