### ISSUE TITLE
Cannot DeDRM (debug log supplied) - Need help

### ISSUE THREAD

**Issue by fcayre** [apprenticeharper/DeDRM_tools#1249]
Hi,

there is the debug log file:
[calibre_debug_log.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5288379/calibre_debug_log.txt)

The ebook is a school book that I cannot read offline on my linux laptop as the editor does not supply a linux version of its app. I installed the Android app (https://play.google.com/store/apps/details?id=ean3133091123925.com.bordasnathan.bibliomanuels), opened the book in it (from an indivudual link supplied by the school). Then I transferred the android app's data to my laptop, found a sqlite db storing the epub file URL (which I downloaded), as well as a username and password, that I do not know how to use (data to decode the DRM?).

How can I go ahead and figure out the DRM type and decoding algorithm? Any help welcome. Is it even the right place to ask?

**Comment by ElleKayEm** [comment]
Looks like a proprietary DRM scheme that DeDRM doesn't recognize.  Figuring out the DRM essentially involves reverse engineering the way a native app unlocks the book.

**Comment by fcayre** [comment]
OK thanks for the reply, so there is no such thing like a standard DRM catalog where book editors choose an algorithm from. Well, this is annoying as reverse engineering is feasible but such an effort for one book...
