### ISSUE TITLE
v6.8.0 plugin not working in Calibre 4.23.0

### ISSUE THREAD

**Issue by caelestiie** [apprenticeharper/DeDRM_tools#1261]
ElleKayEm suggested making a new issue for v6.8.0 in Calibre 4.23.0 problems, so here it is. I have Windows 10 and was trying to strip a Barnes and Noble EPUB

> calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Goodreads (1, 5, 1) && Read MP3 AudioBook metadata (1, 0, 79) && Obok DeDRM (6, 5, 4) && Resize Cover (1, 1, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Goodreads (1, 5, 1) && Read MP3 AudioBook metadata (1, 0, 79) && Obok DeDRM (6, 5, 4) && Resize Cover (1, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.62] splash screen shown
[0.62] Initializing db...
[0.66] db initialized
[0.66] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
{u'height': 680, u'default': True, u'width': 450}
Resize Covers::rebuild_menus - size_data={u'height': 680, u'default': True, u'width': 450}
[2.77] main UI initialized...
[2.77] Hiding splash screen
SMART_DEV (   0.00:  0.002) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.00:  0.806) _startup_on_demand listening on port 9090
SMART_DEV (   1.15:  0.002) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.30:  0.000) _startup_on_demand broadcast socket listening on port 54982
[4.36] splash screen hidden
[4.36] Started up in 4.36 seconds with 321 books
SMART_DEV (   2.39:  1.041) run All IP addresses {u'{A71C8BCB-29F1-4108-A246-1FAC206347F4}': [{'addr': u'192.168.1.185', 'broadcast': u'192.168.1.255', 'netmask': u'255.255.255.0'}], u'{8A05ED06-ECF3-11E7-9A7A-806E6F6E6963}': [{'addr': u'127.0.0.1', 'broadcast': u'127.255.255.255', 'netmask': u'255.0.0.0'}]}
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x1bFYD\xab(PW\x03\xa43y\xcbII\x89\xbc\xaa<\xdd\xe8;\xed\x0e;\xec\xfd,\xa0"\xe6\xfa', 'C:\\Users\\gcalv\\AppData\\Local\\Packages\\BarnesNoble.Nook_ahnzqzva31enc\\LocalState\\9780062931788.epub']
DeDRM v6.8.0: Trying to decrypt 9780062931788.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: “9780062931788.epub” is a secure Barnes & Noble ePub
DeDRM v6.8.0: Looking for new NOOK Study Keys after 0.1 seconds
No nook Study log files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 305, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Lady's Guide to Celestial Mechanics to db in: 1.5
Added 1 books in 3.5 seconds

**Comment by ElleKayEm** [comment]
Unfortunately the methods for retrieving Nook keys included in DeDRM stopped working when B&N cut off their old desktop programs.  And a way to extract the key from the current Windows app has not been figured out.  It is possible to extract your key from the Android Nook app (or at least it still was last I heard), but requires some work.  Here is a write-up on it:  https://www.aricrenzo.com/2019-12-13-Liberate-Your-Nook-Ebooks/
