### ISSUE TITLE
DeDRM 6.7 on calibre 4.18 not working to convert my kindle ebook to pdf

### ISSUE THREAD

**Issue by chandrap0072** [apprenticeharper/DeDRM_tools#1263]
calibre Debug log
calibre 4.18  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: KindleUnpack - The Plugin (0, 82, 3) && Kobo Books (1, 8, 0) && Obok DeDRM (6, 5, 4)
calibre 4.18  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: KindleUnpack - The Plugin (0, 82, 3) && Kobo Books (1, 8, 0) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.84] splash screen shown
[0.84] Initializing db...
[0.84] db initialized
[0.86] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Loaded cached store plugin for: Amazon Kindle at version: 19
Loaded cached store plugin for: ebook.de at version: 6
[3.06] main UI initialized...
[3.06] Hiding splash screen
[16.55] splash screen hidden
[16.55] Started up in 16.55 seconds with 5 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xc4\r\xfc"\xe2r\xf0W\xecnhCOY\x96\x0c\x0cx\x8b^\xb0\x04I\x99gY\xd0a\xdd!\x0bC', 'C:\\Users\\Chandra\\Documents\\My Kindle Content\\B07T9MFFF7_EBOK.azw']
Added An Introduction to Composite Materials to db in: 2.9
Added 1 books in 3.5 seconds

**Comment by chandrap0072** [comment]
calibre, version 4.18.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (An Introduction to Composite Materials)

Convert book 1 of 1 (An Introduction to Composite Materials)
Conversion options changed from defaults:
  cover: u'C:\\Users\\Chandra\\AppData\\Local\\Temp\\calibre_gglwin\\xb_lxh.jpeg'
  read_metadata_from_opf: u'C:\\Users\\Chandra\\AppData\\Local\\Temp\\calibre_gglwin\\mw8jjh.opf'
  output_profile: u'tablet'
  verbose: 2
  pdf_serif_family: u'MS Shell Dlg 2'
  pdf_sans_family: u'MS Shell Dlg 2'
Resolved conversion options
calibre version: 4.18.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\Chandra\\AppData\\Local\\Temp\\calibre_gglwin\\xb_lxh.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x051DA070>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x051DA670>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Chandra\\AppData\\Local\\Temp\\calibre_gglwin\\mw8jjh.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\Chandra\AppData\Local\Temp\calibre_gglwin\elnbjj.azw
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly
  An Introduction to Composite Materials (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
DRMError: An Introduction to Composite Materials

**Comment by ElleKayEm** [comment]
Install DeDRM 6.8.  I only see Obok installed which is for Kobo books.

**Comment by tartley** [comment]
Closing this issue for now. Shout if that seems wrong.
