### ISSUE TITLE
Imported Kindle's book still has DRM: Windows 7 OS, Calibre v3.48, Kindle for PC 1.26.55076.

### ISSUE THREAD

**Issue by Raven4iK** [apprenticeharper/DeDRM_tools#1276]
Hello!

I'm on Windows 7 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr_escrow.200102-1707) with Kindle for PC 1.26.55076.
And I'm using Calibre v3.48 with the latest DeDRM_tools - 6.8.0 + KFX Input Plugin.

Also I have tried to download Amazon's book with enabled and disabled KFX format. That's why two logs attached.

Could you, please, take a look and give some idea how to fix it? Thank you!

Ebook like KFX-ZIP:

calibre Журнал ошибок
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Obok DeDRM (6, 7, 0)
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.06] db initialized
[0.06] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.34] main UI initialized...
[1.34] Hiding splash screen
[8.10] splash screen hidden
[8.10] Started up in 8.10 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['g\xb1\xeb\x83&\x8a?\xe4mH\xf1\xfaKKL\x98\x95\xc52Yz\xe9\xb8\x84\xcc\xa1\xd4ZC\xb1\xc0\xe5', 'C:\\Users\\\xd0\x9c\xd1\x83\xd1\x80\xd1\x87\xd0\xb8\xd0\xba\\Documents\\My Kindle Content\\B07HNBW6YW_EBOK\\B07HNBW6YW_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing C:\Users\РњСѓСЂС‡РёРє\Documents\My Kindle Content\B07HNBW6YW_EBOK\B07HNBW6YW_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\210D~1\AppData\Local\Temp\calibre_evf_bi\la8scc.kfx-zip
DeDRM v6.8.0: Trying to decrypt la8scc.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: la8scc
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.4b66d591-fb01-4354-a4d0-a63e0a9f7a80.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\\AppData\Local\Amazon\Kindle\storage\.kinf2018
Couldn't decrypt file.
DeDRM v6.8.0: Ultimately failed to decrypt after 6.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 6.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\210D~1\AppData\Local\Temp\calibre_evf_bi\la8scc.kfx-zip
Processing container: B07HNBW6YW_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container B07HNBW6YW_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\210D~1\AppData\Local\Temp\calibre_evf_bi\8btqs0_add_books\0\B07HNBW6YW_EBOK.kfx-zip
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Golden Child: Winner of the Desmond Elliot Prize 2019 to db in: 2.0
Added 1 books in 9.4 seconds
Worker Launch took: 0.125
Job: 0 Конвертировать книгу 1 из 1 (Golden Child: Winner of the Desmond Elliot Prize 2019) finished
Конвертировать книгу 1 из 1 (Golden Child: Winner of the Desmond Elliot Prize 2019)
	C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  output_profile: u'generic_eink'
	  cover: u'C:\\Users\\210D~1\\AppData\\Local\\Temp\\calibre_evf_bi\\xsuq_3.jpeg'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\210D~1\\AppData\\Local\\Temp\\calibre_evf_bi\\aqrdsr.opf'
	Resolved conversion options
	calibre version: 3.48.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\210D~1\\AppData\\Local\\Temp\\calibre_evf_bi\\xsuq_3.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'fb2_genre': u'antique',
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000000003E359E8>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000000003E35D68>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\210D~1\\AppData\\Local\\Temp\\calibre_evf_bi\\aqrdsr.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'sectionize': u'files',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\210D~1\AppData\Local\Temp\calibre_evf_bi\mlre3t.kfx-zip
	Software versions: KFX Input 1.34.0, calibre 3.48 [64bit], Windows-7-6.1.7601-SP1
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\210D~1\AppData\Local\Temp\calibre_evf_bi\mlre3t.kfx-zip
	Processing container: B07HNBW6YW_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
	KFXDRMError: Book container B07HNBW6YW_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 123, in convert
	calibre.ebooks.DRMError: This book has DRM!

Ebook like AZW:

calibre Журнал ошибок
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && Obok DeDRM (6, 7, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && Obok DeDRM (6, 7, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.22] main UI initialized...
[1.22] Hiding splash screen
[5.09] splash screen hidden
[5.09] Started up in 5.09 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xf0\x01\x9b\xab\x809\xe1\xf7}\x81ZUU\xbc5\xe4\xd3\xf5\xaa[\xebj\x8f\x0e\xa1\r\xd3\xc7\xdd\xb0\x0f\xce', 'C:\\Users\\\xd0\x9c\xd1\x83\xd1\x80\xd1\x87\xd0\xb8\xd0\xba\\Desktop\\B07HNBW6YW_EBOK\\B07HNBW6YW_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing C:\Users\РњСѓСЂС‡РёРє\Desktop\B07HNBW6YW_EBOK\B07HNBW6YW_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.8.0: Trying to decrypt B07HNBW6YW_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright В© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Golden Child: Winner of the Desmond Elliot Prize 2019
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\\AppData\Local\Amazon\Kindle\storage\.kinf2018
Couldn't decrypt file.
DeDRM v6.8.0: Ultimately failed to decrypt after 6.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 6.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Golden Child: Winner of the Desmond Elliot Prize 2019 to db in: 1.9
Added 1 books in 9.2 seconds
Worker Launch took: 0.118000030518
Job: 0 Конвертировать книгу 1 из 1 (Golden Child: Winner of the Desmond Elliot Prize 2019) finished
Конвертировать книгу 1 из 1 (Golden Child: Winner of the Desmond Elliot Prize 2019)
	C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  output_profile: u'generic_eink'
	  cover: u'C:\\Users\\210D~1\\AppData\\Local\\Temp\\calibre_mw5nor\\mknbs3.jpeg'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\210D~1\\AppData\\Local\\Temp\\calibre_mw5nor\\zeqpop.opf'
	Resolved conversion options
	calibre version: 3.48.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\210D~1\\AppData\\Local\\Temp\\calibre_mw5nor\\mknbs3.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'fb2_genre': u'antique',
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000000003F8AA90>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000000003F8AE10>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\210D~1\\AppData\\Local\\Temp\\calibre_mw5nor\\zeqpop.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'sectionize': u'files',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\210D~1\AppData\Local\Temp\calibre_mw5nor\6aok89.azw
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  Golden Child: Winner of the Desmond Elliot Prize 2019 (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Golden Child: Winner of the Desmond Elliot Prize 2019

**Comment by ElleKayEm** [comment]
Were both formats downloaded with the current installation of Kindle for PC which is installed on the same machine and user as calibre with DeDRM?

**Comment by Raven4iK** [comment]
Yes, with current installation of 1.26.55076 version. And all the same: machine \ user with admin rights and etc.

**Comment by ElleKayEm** [comment]
The .kinf2018 key file that is found in "C:\Users\AppData\Local\Amazon\Kindle\storage" doesn't seem to be the right one for these books.  Possibly it is something left behind by a previous installation of Kindle for PC?  I would expect the key file to be in "C:\Users\[User Name]\AppData\Local\Amazon\Kindle\storage".  Is there actually an AppData folder directly inside the Users folder?  (Make sure you can view hidden folders to check.)  Perhaps it's just not showing correctly in the log here because of the characters in your user name.  I know there used to be issues for DeDRM with non-ASCII characters in the Windows user name, but I thought that had been resolved a while ago.

**Comment by Raven4iK** [comment]
You are right in both cases. Actual version 1.29.58059 of Kindle for PC was installed first. And current Windows username consists of only cyrillic characters. Should I try to create a new local user or administrator account with standard latin symbols?
AppData inside the Users folder presents like hidden and view option for hidden folders is enabled.

**Comment by ElleKayEm** [comment]
So you have two Amazon folders?  One in "C:\Users\AppData\Local\" and another in "C:\Users\YOUR_USER_NAME\AppData\Local\"?  If so, I'd try deleting the .kinf2018 key file from "C:\Users\AppData\Local\Amazon\Kindle\storage".  That way maybe DeDRM can find what should be the correct key file in "C:\Users\YOUR_USER_NAME\AppData\Local\Amazon\Kindle\storage".

If that doesn't do it, then, yes, I'd try a completely fresh setup in a new user with standard Latin characters.

**Comment by Raven4iK** [comment]
So, I created new administrator account with standard latin characters on the same Windows OS and made fresh install of all software (Calibre v3.48, DeDRM_tools - 6.8.0 + KFX Input Plugin Kindle for PC 1.26.55076)...
.... And everyting is OK now!
Thanks for your attention and sorry for disturbing :)

**Comment by ElleKayEm** [comment]
No problem.  Perhaps a fix can eventually be made to allow for non-Latin characters in the user name.

**Comment by tartley** [comment]
Closing this issue for now. Shout if that's not right.
