### ISSUE TITLE
DRM not working on Linux with Calibre 4.23

### ISSUE THREAD

**Issue by mariocioni** [apprenticeharper/DeDRM_tools#1277]
Here is the output I receive as I try to read the book:
`calibre, version 4.23.0
ERRORE: Caricamento libro fallito: Failed to open the book at /home/wolinski/Biblioteca di calibre/Stephen King/Il Talismano (Italian Edition) (9)/Il Talismano (Italian Edition) - Stephen King.azw. Click "Show details" for more info.

Traceback (most recent call last):
  File "site-packages/calibre/gui2/viewer/ui.py", line 468, in _load_ebook_worker
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 234, in prepare_book
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 191, in do_convert
ConversionFailure: Failed to convert book: /home/wolinski/Biblioteca di calibre/Stephen King/Il Talismano (Italian Edition) (9)/Il Talismano (Italian Edition) - Stephen King.azw with error:
InputFormatPlugin: MOBI Input running
on /home/wolinski/Biblioteca di calibre/Stephen King/Il Talismano (Italian Edition) (9)/Il Talismano (Italian Edition) - Stephen King.azw
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 189, in main
  File "<string>", line 1, in <module>
  File "site-packages/calibre/srv/render_book.py", line 862, in viewer_main
  File "site-packages/calibre/srv/render_book.py", line 855, in render_for_viewer
  File "site-packages/calibre/srv/render_book.py", line 830, in render
  File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 64, in extract_book
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 39, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 162, in extract_content
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
DRMError: Il Talismano (Italian Edition)`

I also tried with Calibre 3.48 as well as Calibre 5.1.0 (where plugin does not install) to no avail.
Thank you for any help

**Comment by PiperKev** [comment]
Which version of DeDRM are you using?  6.8.0 is the version that works with calibre 4.23.  The newest "master" version is being reworked with Python 3 and is not compatible with earlier releases of calibre.

**Comment by mariocioni** [comment]
It is indeed the 6.8.0 version of the plugin that I am using

**Comment by ElleKayEm** [comment]
Stick with calibre 4.23 and DeDRM 6.8.  For Amazon books, see this post:  https://www.mobileread.com/forums/showthread.php?t=283371

If you still need help, we need an import log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by mariocioni** [comment]
Thanks for the reply. I have looked at https://www.mobileread.com/forums/showthread.php?t=283371 : however it does not work for me. Let me give more details. I have a kindle paperwhite (2012) which I never registered with Amazon (and registration does not seem possible any more), plus a registered older one and a newer one (both registered). I am trying to copy kindle books I have purchased on Amazon on this unregistered device. I used to remove drm with calibre and the plugin under Ubuntu and used to succed. Now it's not working any more.

**Comment by ElleKayEm** [comment]
If the Kindles which are registered to your account are E-ink Kindles (not Fires), you should be able to download your books from the website and choose one of them for the device.  Enter the Kindle's serial number into the DeDRM customization.  Again, if you can't get it to work, we'll need an import log to troubleshoot what's wrong.

**Comment by mariocioni** [comment]
Actually one of the kindles is a Kindle 2 the other is a 2020 8GB Kindle. 
Here is the import log. Seems perhaps to suggest I should install win?

`calibre Log di debug
calibre 4.23  embedded-python: True is64bit: True
Linux-5.4.0-48-generic-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-48-generic', '#52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020')
Python 2.7.16
Linux: ('debian', 'bullseye/sid', '')
Interface language: it
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: True
Linux-5.4.0-48-generic-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-48-generic', '#52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020')
Python 2.7.16
Linux: ('debian', 'bullseye/sid', '')
Interface language: it
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 117.584086799 x 117.607717042
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.07] splash screen shown
[0.07] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
[0.69] main UI initialized...
[0.69] Hiding splash screen
[12.93] splash screen hidden
[12.93] Started up in 12.93 seconds with 1 books
['zenity', '--modal', '--file-selection', '--title=Seleziona libro', '--separator=\n', '--attach=79691796', '--filename=/home/wolinski/Scaricati/.fgdfg.gdfhjdhf*&^839', '--file-filter=Libri | *.lrf *.rar *.zip *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf', '--file-filter=Libri EPUB | *.epub *.kepub', '--file-filter=Libri Kindle | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=Libri PDF | *.pdf *.azw4', '--file-filter=Libri HTML | *.htm *.html *.xhtm *.xhtml', '--file-filter=Libri LIT | *.lit', '--file-filter=Libri TXT | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Fumetti | *.cbz *.cbr *.cbc', '--file-filter=Archivi | *.zip *.rar', '--file-filter=File elaboratore di testi | *.odt *.doc *.docx', '--file-filter=Tutti i file | *', '--multiple']
DeDRM v6.8.0: Trying to decrypt Il Talismano (Italian Edition).azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Il Talismano (Italian Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.8.0: Running kindlekey.py under Wine
DeDRM v6.8.0: Command line: 'wine python.exe "/home/wolinski/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/wolinski/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
/bin/sh: 1: wine: not found
DeDRM v6.8.0: Found and decrypted 0 key files
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Il Talismano (Italian Edition) to db in: 0.1
Added 1 books in 0.5 seconds`

**Comment by ElleKayEm** [comment]
If those are Kindles with greyscale e-ink screens and not Fire tablets, then they will work.

If this book was downloaded with the Kindle app, you could run kindlekey.pyw where you have it installed and then import the key into the DeDRM plugin customization.

**Comment by mariocioni** [comment]
It worked! I somehow had overlooked the importance of entering the Kindle's serial number into the DeDRM customization (perhaps this used to be unnecessary in the past).
Thank you so much

**Comment by ElleKayEm** [comment]
Glad you got it working.  If the book is from or for an E-ink Kindle, then the serial number is needed to derive the key.  If you're importing from the Kindle app, DeDRM can automatically retrieve the key.  Each device and app installation has a unique key even if they are attached to the same account.
