### ISSUE TITLE
Cannot remove DRM from two books purchased from google play

### ISSUE THREAD

**Issue by kunalamin3** [apprenticeharper/DeDRM_tools#1285]
1) Log below
2) Running calibre version 4.23 on windows 10

calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 83.2218430034 x 83.1272727273
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
[1.58] main UI initialized...
[1.58] Hiding splash screen
[9.59] splash screen hidden
[9.61] Started up in 9.61 seconds with 2 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x95\xb2\xbfm\xad\x19j\x92\x06dF\x8eyO_\x80?/\x8e\x97\xc8\xa8\x15\xc5\x86xDFI\xa1Va', 'C:\\Users\\kunal\\Desktop\\Plague of Corruption.epub']
DeDRM v6.8.0: Trying to decrypt Plague of Corruption.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: Plague of Corruption.epub is a secure Adobe Adept ePub
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.8.0: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 350, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
ADEPTError: Adobe Digital Editions not activated
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Plague of Corruption to db in: 0.4
Added 1 books in 0.9 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x05BB4330>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x05BA4FD0>> ignored

**Comment by ElleKayEm** [comment]
The log says:

> Adobe Digital Editions not activated

You need to authorize ADE with an Adobe ID before opening the acsm file.

**Comment by tartley** [comment]
Closing this issue for now. Shout if that's not right.
