### ISSUE TITLE
KFX Converting Error - DeDRM v6.6.2

### ISSUE THREAD

**Issue by splant135** [apprenticeharper/DeDRM_tools#1286]
Was able to load the book into Calibre, unable to convert:
Running Windows 10
Calibre 5.1

calibre Debug log
calibre 4.21  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 6, 2) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Goodreads_Rating (3, 1, 0) && KindleUnpack - The Plugin (0, 82, 3) && Goodreads Sync (1, 14, 3) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0) && Goodreads (1, 5, 1)
calibre 4.21  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 6, 2) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Goodreads_Rating (3, 1, 0) && KindleUnpack - The Plugin (0, 82, 3) && Goodreads Sync (1, 14, 3) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0) && Goodreads (1, 5, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.31] splash screen shown
[0.31] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
DEBUG:    1.5 HttpHelper::__init__: proxy=None
[2.02] main UI initialized...
[2.02] Hiding splash screen
[11.74] splash screen hidden
[11.74] Started up in 11.74 seconds with 930 books
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing D:/Documents/My Kindle Content/B076FLFDCN_EBOK/B076FLFDCN_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\FROOTF~1\AppData\Local\Temp\calibre_etoerp\8mb2ei.kfx-zip
DeDRM v6.6.2: Trying to decrypt 8mb2ei.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 8mb2ei
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.03bbb4c0-fe7f-444b-a8c5-5acc29c1748f.voucher
DeDRM v6.6.2: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.2: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Froot Froot\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Froot Froot\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '576726625' and UserName '46726f6f742046726f6f74'
DeDRM v6.6.2: Found 1 new key
Decrypting KFX-ZIP ebook: 8mb2ei
Got DSN key from database default_key_1
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.03bbb4c0-fe7f-444b-a8c5-5acc29c1748f.voucher
DeDRM v6.6.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 572, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\FROOTF~1\AppData\Local\Temp\calibre_etoerp\8mb2ei.kfx-zip
Processing container: B076FLFDCN_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container B076FLFDCN_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\FROOTF~1\AppData\Local\Temp\calibre_etoerp\m7cq43_add_books\0\B076FLFDCN_EBOK.kfx-zip
Added Dragon Night: A Dark Kings Novella to db in: 0.3
Added 1 books in 2.1 seconds

**Comment by ElleKayEm** [comment]
Use calibre 4.23, DeDRM 6.8, and Kindle for PC 1.26 or earlier.

**Comment by tartley** [comment]
Closing this issue for now. Shout if that's not right.

The required versions should be made clearer soon with the proposed README update: https://github.com/apprenticeharper/DeDRM_tools/wiki/Exactly-how-to-remove-DRM
