### ISSUE TITLE
Amazon eBook DRM NOT being stripped on calibre

### ISSUE THREAD

**Issue by Rimidalv1** [apprenticeharper/DeDRM_tools#129]
As the title suggests, I have an eBook from Amazon that I've rented and I'll need it for much longer than the rent option so I'm trying to strip the DRM via calibre and the de-DRM plugin

This is what I've tried:
Updated the de-DRM plugin to most recent (DeDRM_tools_6.5.1)
Uninstalled previous de-DRM plugin, re-installed most recent (closed and re-opened calibre)
Ran in debug mode, attempted to import then and still DRM was on.
Attached is the log file for the DRM attempted stripping.

Can anyone help? Greatly appreciate it if anyone knows how to work this problem, thanks!
[tmp8y7b7g.txt](https://github.com/apprenticeharper/DeDRM_tools/files/458631/tmp8y7b7g.txt)

**Comment by ElleKayEm** [comment]
The tools do not work on rentals.  The solution is to buy the book.

**Comment by Rimidalv1** [comment]
Oh darn! What would you suggest I do if I need like the last half of the book after the 90 day rental? I was thinking of screen-capturing each individual page and saving it like that but that's so much work. I can't afford to buy the entire book so that's not a solution for me.

**Comment by ElleKayEm** [comment]
The tools here are for books you own.  You're not going to receive help with DRM removal from rental or library books.
