### ISSUE TITLE
I volunteer to help clean up duplicate issues

### ISSUE THREAD

**Issue by tartley** [apprenticeharper/DeDRM_tools#1293]
I'd like to volunteer to tidy up the proliferation of issues, e.g. by combining duplicates, to make them more readable.

I'd preserve information. For example, I'd copy any extra relevant extra info from an issue before closing it as a dupe.

Is it possible for the esteemed @apprenticeharper to grant me the ability to edit / label / delete issues, to help out? Or is that only possible for repos which are owned by an organization ?

**Comment by tartley** [comment]
Ah,  I *think* it could be done, under settings / Manage access.

I understand if you are uncomfortable granting access though. Just wanted to have the conversation. Thoughts welcome.

**Comment by ismail** [comment]
I don't know to whom but someone needs access to clean up invalid issues indeed and since @tartley seems to be a well-known company he'd be a good choice IMHO.

**Comment by apprenticeharper** [comment]
I'm delighted to accept your offer. You should have an invite.

I'm only doing this because no-one else is doing it. :)

**Comment by tartley** [comment]
I made a start. Closing this issue...
