### ISSUE TITLE
The outcome .pdf file got messed up

### ISSUE THREAD

**Issue by trambui** [apprenticeharper/DeDRM_tools#130]
I tried to convert one of my Kindle books from .azw to .pdf file but the book got messed up. A few pages' font went unreadable and the size of letters were also much bigger than the original version in kindle :(.

![screen shot 2016-09-08 at 3 02 06 pm](https://cloud.githubusercontent.com/assets/19370462/18364796/5125fcfe-75d5-11e6-8cb7-1989423bf493.png)

**Comment by ElleKayEm** [comment]
If it's not an issue caused by the tools here, then I suggest asking in the calibre forum at MobileRead.com.
