### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by AboShayeb** [apprenticeharper/DeDRM_tools#1301]
When is Python 3 supported release? Calibre 5 doesn't support this version of the tool.

**Comment by tartley** [comment]
Hey. There are about 50 issues already reported to this effect.

A number of people are committing Python3 fixes. You can see them in the commit log:
https://github.com/apprenticeharper/DeDRM_tools/commits/master

It's hard to know when all the required changes will be made. I'm not very familiar with the project but at a speculative guess it will take a small number of weeks.

**Comment by AboShayeb** [comment]
All fixes suggested do not work. Downgrading isn't an option for me. And using the master 7.0 didn't work as well.

**Comment by apprenticeharper** [comment]
There are approx. 22,000 lines of code to be fixed. This isn't a commercial product. If you can't stick with calibre 4.23, you'll just have to wait, or if you're lucky, drop back to a version that has the stand-alone tools, if you don't required the latest kindle changes.

Or take the 6.8 code, extract the scripts, and run them by hand, having first installed appropriate versions of python.
