### ISSUE TITLE
Please help for ADE

### ISSUE THREAD

**Issue by gelinstar** [apprenticeharper/DeDRM_tools#1308]
Book can only be opened using Adobe 4.5, used calibre 4.3 with the plug in for 6.8.  unable to remove DRM.

**Comment by tartley** [comment]
Closing as dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1323

**Comment by ElleKayEm** [comment]
@gelinstar 
Can you open it in ADE 2.0.1 authorized with the same Adobe ID?

**Comment by gelinstar** [comment]
no, i can't
