### ISSUE TITLE
AZW not working. Claiming no voucher but it is in the same directory.

### ISSUE THREAD

**Issue by drmoisan** [apprenticeharper/DeDRM_tools#1309]
AZW file not working. Exception says there is no voucher, but voucher is in the same directory
amzn1.drm-voucher.v1.8ae1335b-2cc8-4d04-a37f-b38242835934.voucher

Thank you for the help!

Microsoft Windows [Version 10.0.19041.508]
(c) 2020 Microsoft Corporation. All rights reserved.

calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.643076923 x 133.900578035
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.62] splash screen shown
[0.62] Initializing db...
[0.62] db initialized
[0.64] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.55] main UI initialized...
[2.55] Hiding splash screen
[2.75] splash screen hidden
[2.75] Started up in 2.75 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xfc\xc4\x971^\xb5\xdf|\xad{\xe5\x03"\x1f)\xb2\xb6\xfaI\xab\xf7)$\xce\xd6\xd5\x01\x8e\xebY\xb2N', 'C:\\Users\\***filtered***\\Documents\\My Kindle Content\\B07BN5HWWX_EBOK\\B07BN5HWWX_EBOK.azw']
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
GetPointerType() failed: "The operation completed successfully."
DeDRM v6.8.0: Trying to decrypt B07BN5HWWX_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.8.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\***filtered***\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\03311352\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3659576242' and UserName '***filtered***'
DeDRM v6.8.0: Found 1 new key
DeDRM v6.8.0: Ultimately failed to decrypt after 10.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 10.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 285, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 0: invalid start byte

**Comment by ElleKayEm** [comment]
You'll need to install the KFX Input plugin and download the book with Kindle for PC 1.26 (or earlier).  Alternatively, you could disable KFX downloads.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371
