### ISSUE TITLE
dedrm not working on kindle after latest calibre release

### ISSUE THREAD

**Issue by gizmotherat** [apprenticeharper/DeDRM_tools#131]
Hi, the dedrm was working fine for me previously, but when I logged in today I updated calibre to the latest release (and reinstalled the plugin with apparently no issue) and now I'm trying to upload a kindle book into calibre and it isn't stripping it. It's a purchased kindle book registered to the same (my only) amazon account...?

**Comment by gizmotherat** [comment]
not sure now if this was the problem -- it looks like perhaps i was importing the kindle books from the wrong source, but i also reverted to an older version of calibre, so.

**Comment by ElleKayEm** [comment]
Just so you know, there is no need to reinstall plugins when you update calibre.
