### ISSUE TITLE
Topaz book issue

### ISSUE THREAD

**Issue by k00kbzon** [apprenticeharper/DeDRM_tools#132]
I tried to convert a book but its i cant because its topaz

this my log:

calibre Registro de depuración
calibre 2.67  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 1) && KindleUnpack - The Plugin (0, 81, 2)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.664921466 x 127.590697674
Starting up...
Started up in 4.42 seconds with 290 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['9qh\x81E\x9c\xb4N\x1d\xae.\x7f\x81^\x1a\x13\x1b\xd6\x8a\xa1\xc2P$k\x07\x1d\x1f\x10\\^&\\', 'C:\\Users\\k00kb\\Documents\\My Kindle Content\\Libros de sangre - IV_ 4 (Eclip - Clive Barker.azw']
DeDRM v6.5.1: Trying to decrypt Libros de sangre - IV_ 4 (Eclip - Clive Barker.azw
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting Topaz ebook: Libros de sangre - IV: 4 (Eclipse) (Spanish Edition)
Found 8 keys to try after 0.3 seconds
Trying: LLRD4M5X
Trying: wTemcirC
Trying: 5Agl2LoI
Trying: BGKsZ937
Trying: LLRD4M5X
Trying: aI81rHYz
Book Key Found! (2393640b993e2941)
Processing Section: dict
. . . .  
Processing Section: metadata
. . . .  
Processing Section: color
. . . . . . . .  
Processing Section: img
. . . . . . . .  
Processing Section: page
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  
Processing Section: other
. . . .  
Processing Section: glyphs
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  
Successfully Extracted Topaz contents
Updating to color images if available
Creating cover.jpg
Processing Dictionary
Processing Meta Data and creating OPF
Processing StyleSheet
           Using font size: 111
           Using page height: 13334
           Using page width: 8928
Processing Glyphs
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  
Processing Pages
. . . Unknown Token: src
DeDRM v6.5.1: Failed to decrypt with error: %d format: a number is required, not NoneType
DeDRM v6.5.1: Looking for new default Kindle Key after 3.2 seconds
searching for kinfoFiles in C:\Users\k00kb\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\k00kb\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3337999492' and UserName '6b30306b62'
DeDRM v6.5.1: Found 1 new key
Decrypting Topaz ebook: Libros de sangre - IV: 4 (Eclipse) (Spanish Edition)
Found 4 keys to try after 3.3 seconds
Trying: LLRD4M5X
Trying: aI81rHYz
Book Key Found! (2393640b993e2941)
Processing Section: dict
. . . .  
Processing Section: metadata
. . . .  
Processing Section: color
. . . . . . . .  
Processing Section: img
. . . . . . . .  
Processing Section: page
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  
Processing Section: other
. . . .  
Processing Section: glyphs
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  
Successfully Extracted Topaz contents
Updating to color images if available
Creating cover.jpg
Processing Dictionary
Processing Meta Data and creating OPF
Processing StyleSheet
           Using font size: 111
           Using page height: 13334
           Using page width: 8928
Processing Glyphs
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  
Processing Pages
. . . Unknown Token: src
DeDRM v6.5.1: Ultimately failed to decrypt after 6.2 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 608, in run
  File "calibre_plugins.dedrm.__init__", line 558, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.1: Ultimately failed to decrypt after 6.2 seconds
Added Libros de sangre - IV: 4 (Eclipse) (Spanish Edition) to db in: 2.2
Added 1 books in 9.1 seconds

i think the error is this part :  . . . Unknown Token: src

**Comment by apprenticeharper** [comment]
Please attach that book file. I'll see what can be done.

**Comment by k00kbzon** [comment]
[Libros de sangre - IV_ 4 (Eclip - Clive Barker.zip](https://github.com/apprenticeharper/DeDRM_tools/files/470492/Libros.de.sangre.-.IV_.4.Eclip.-.Clive.Barker.zip)

here it is , just in a zip file.

**Comment by apprenticeharper** [comment]
Thanks, I'll take a look as soon as I can, but that might not be until early next week.

**Comment by apprenticeharper** [comment]
I was overly optimistic. I've got your file now, and I'm working on it.

**Comment by apprenticeharper** [comment]
Please try the new version of the plugin just uploaded to the repository: https://github.com/apprenticeharper/DeDRM_tools/tree/master/DeDRM_calibre_plugin

**Comment by k00kbzon** [comment]
I tried it and it worked!!!! ,i even tried with another book with the same error and it worked ! ,now it its fixed thank you very much. (-:

**Comment by apprenticeharper** [comment]
Released in v6.5.2
