### ISSUE TITLE
Book opens in Calibre, but not on Kindle

### ISSUE THREAD

**Issue by shorinjin** [apprenticeharper/DeDRM_tools#1320]
I have a book that I converted to Mobi after using DeDRM.  It opens fine in Calibre, but after I transfer it to my Kindle, it says "Unable to Open Item" when I try to open it.

Any suggestions?

**Comment by diazbastian** [comment]
Works fine here on a Kindle Voyage. Look at the firmware of your model and see if you can update it, however, regarding to Calibre, look at the mobi format output options and try setting the options to default. Also try formats like AZW or AZW3.

**Comment by ElleKayEm** [comment]
If you can convert it to MOBI, then the DRM is removed.  That being said, I'd second the suggestion to try converting to AZW3 instead.

**Comment by tartley** [comment]
I don't believe this project has any actions resulting from this issue, so I'm tempted to close it. Thoughts?

Could we integrate the advice to update firmware, etc, into the docs? In a 'troubleshooting' section?

**Comment by tartley** [comment]
I incorporated the above advice into the Troubleshooting section here: https://github.com/apprenticeharper/DeDRM_tools/wiki/How-to-exact-remove-DRM

There is an issue to merge that wiki page into the DeDRM_plugin_README.md: https://github.com/apprenticeharper/DeDRM_tools/issues/1328

**Comment by tartley** [comment]
Hi there @diazbastian. Your guidance is much appreciated. I don't yet fully understand what you've said. I'm going to try and break it down, not to nitpick or argue, just to check that I understand and can comply.

>  you don't generalize a issue that other users cannot replicate.

I think you are saying that, just because it was good advice for THIS user to try updating Kindle device firmware, etc, that might not be good advice for other users. Is that what you are saying? Would you prefer I entirely removed the updates I made to the Troubleshooting section as a result of this Issue? I think your next comments imply you'd prefer I modify them, as I describe below. Let me know. Thanks.

> it is nonsense to speak of the ePub format when talking about a Kindle

Thanks! I'll remove that.

> the MOBI format is friendly and native to any Kindle

So are you saying that the advice to try converting to AZW or AZW3 is not useful in the troubleshooting? Or just that I shouldn't describe them as "more kindle friendly" ?

> The other formats are more modern.
> Lastly, nothing that is related to removing DRM from a e-book.

I don't know what to do in response to these comments. Help me understand, and I'll do it. Thanks.

**Comment by tartley** [comment]
I made the following tweaks:

```
-  1. If a book that has been converted by DeDRM into Mobi/Epub will not load again in a Kindle device:
+  1. If a book that has been converted by DeDRM into Mobi will not load again in a Kindle device:
     1. Consider updating the Kindle firmware
-     1. Reset the Calibre Mobi/Epub output format options to defaults
+     1. Reset the Calibre Mobi output format options to defaults
-    1. Try converting to more Kindle-friendly formats like AZW or AZW3, instead of Mobi.
+     1. Try converting to other formats like AZW or AZW3, instead of Mobi.
```

**Comment by diazbastian** [comment]
> I think you are saying that, just because it was good advice for THIS user to try updating Kindle device firmware, etc, that might not be good advice for other users. Is that what you are saying? Would you prefer I entirely removed the updates I made to the proposed Troubleshooting section as a result of this Issue? I think your next comments imply you'd prefer I modify them, as I describe below. Let me know. Thanks.

Yes

> So are you saying that the advice to try converting to AZW or AZW3 is not useful in the troubleshooting? Or just that I shouldn't describe them as "more kindle friendly" ?

Both, however using a more modern file format can have certain advantages depending on the case or not always (like new and modern KFX Kindle format). There is no point talking about format friendliness, all those listed on Kindle are well supported formats.

> I don't know what to do in response to these comments. Help me understand, and I'll do it. Thanks.

It's simple, **all** of the above doesn't make sense to discuss here. DeDRM is a plugin to remove DRM from e-books using Calibre and all troubleshooting has to be focused on that functionality. Converting between e-book formats is a Calibre feature, and if there is a problem or troubleshooting tip you should go into that project help page.

What I did above was give a "friendly" advice to a community member who had a problem, but as someone else pointed out, that issue has nothing to do with DeDRM itself.

**Comment by tartley** [comment]
Alright. Thanks for expanding, that helps me understand your goals, so that I can do the right thing, not just here, but in future as well.

**Comment by ElleKayEm** [comment]
@tartley 
The OP is clearly not having any issue with DeDRM.  You cannot convert to another format if you haven't already successfully removed the DRM.  A couple of us offered our thoughts, but this question and possible solutions really belong elsewhere -- like the MobileRead Kindle or calibre forums.

**Comment by tartley** [comment]
@ElleKayEm Thanks for the guidance.
