### ISSUE TITLE
Overdrive downloads worked until last week, now no DRM removal

### ISSUE THREAD

**Issue by gcallero** [apprenticeharper/DeDRM_tools#1325]
I have been using Calibre and Oveerdrive from the Seattle Public library for the last few years successfully until my last successful download/conversion into Calibre on Sept 24, 2020,  when DrDrm stopped working.
I have re-installed Calibre 5.3 and re-tried, with no success.  
[tmpiai1op7y.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5398263/tmpiai1op7y.txt)
What am I doing wrong?

**Comment by ElleKayEm** [comment]
DeDRM is not compatible with calibre 5.x yet.  For now, stick with calibre 4.23.

**Comment by gcallero** [comment]
Got it, did it. Works fine, Thanx

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by gcallero** [comment]
Thank you for the quick response.
