### ISSUE TITLE
De DRM did not remove DRM

### ISSUE THREAD

**Issue by FlamingoStorm** [apprenticeharper/DeDRM_tools#1327]
I imported kfx files from my kindle e-reader after I added the Serial Number to the configuration. It failed to remove the DRM however. I am on a windows 10 computer running calibre 4.23 and have installed kfx input from the forum. The deubg log is as follows: calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.20236-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.20236')
Python 2.7.16+
Windows: ('10', '10.0.20236', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && Obok DeDRM (6, 7, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.20236-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.20236')
Python 2.7.16+
Windows: ('10', '10.0.20236', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && Obok DeDRM (6, 7, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.0 x 95.9160839161
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.36] splash screen shown
[0.36] Initializing db...
[0.36] db initialized
[0.36] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.89] main UI initialized...
[0.89] Hiding splash screen
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'D')], (7L, 2L): [(1L, 'E')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0401\G090VB06038600UX&0: StorageDeviceNumber(type=7L, number=2L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=7)
{u'drive_letters': ['E'],
 u'pnp_id_map': {'E': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0401#g090vb06038600ux&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'E': (2L, 1L)}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: E:\ documents
DEBUG:    0.0 USBMS: scan from root False E:\documents
DEBUG:    0.0 USBMS: count found in cache: 11, count of files in metadata: 11, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 11
DeviceJob: set_books_in_library finished: time= 0.00100016593933
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 1 Set library information finished
No details available.
Job: 0 Get device information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
[6.91] splash screen hidden
[6.91] Started up in 6.91 seconds with 1 books
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing E:/documents/Downloads/Items01/Rebirth of the Undead King_ Book 1_B07PZ2NGJ1.kfx
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\maqhcf.kfx-zip
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing E:/documents/Downloads/Items01/Reincarnated as a Familiar Volume 1 (Light Novel)_B0863DT67F.kfx
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing E:/documents/Downloads/Items01/Reincarnated as a Familiar Volume 2 (Light Novel)_B08DQWJTGN.kfx
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\cnqkhm.kfx-zip
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\ejdjxt.kfx-zip
DeDRM v6.8.0: Trying to decrypt maqhcf.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: maqhcf
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\elicu\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\maqhcf.kfx-zip
Processing container: CR!26WNMKE9MH1P93ATGX96A5AT701Q.kfx
Processing container: Rebirth of the Undead King_ Book 1_B07PZ2NGJ1.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container Rebirth of the Undead King_ Book 1_B07PZ2NGJ1.kfx has DRM and cannot be converted
DeDRM v6.8.0: Trying to decrypt cnqkhm.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
KFX metadata reader (from KFX Input) activated for C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\ehvjga_add_books\0\Rebirth of the Undead King_ Book 1_B07PZ2NGJ1.kfx-zip
Decrypting KFX-ZIP ebook: cnqkhm
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing E:/documents/Downloads/Items01/My Best Friend is Dense Harem Main Character-kun, But Why am I the Heroine_! Volume 1 (Best Friend and_B07FHZ2CQY.kfx
searching for kinfoFiles in C:\Users\elicu\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\cnqkhm.kfx-zip
DeDRM v6.8.0: Trying to decrypt ejdjxt.kfx-zip
Processing container: CR!M8WCM0K8P91QK5QR2W1YHPCZNZNG.kfx
Processing container: Reincarnated as a Familiar Volume 1 (Light Novel)_B0863DT67F.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container Reincarnated as a Familiar Volume 1 (Light Novel)_B0863DT67F.kfx has DRM and cannot be converted
Using Library AlfCrypto DLL/DYLIB/SO
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\jbtxdy.kfx-zip
KFX metadata reader (from KFX Input) activated for C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\ehvjga_add_books\1\Reincarnated as a Familiar Volume 1 (Light Novel)_B0863DT67F.kfx-zip
Decrypting KFX-ZIP ebook: ejdjxt
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\elicu\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing E:/documents/Downloads/Items01/1984_B003JTHWKU.kfx
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\ejdjxt.kfx-zip
Added Rebirth of the Undead King: Book 1 to db in: 0.1Processing container: CR!W09JCSWK3964V3F36B94EBFW3DVB.kf
x
Processing container: Reincarnated as a Familiar Volume 2 (Light Novel)_B08DQWJTGN.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container Reincarnated as a Familiar Volume 2 (Light Novel)_B08DQWJTGN.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\ehvjga_add_books\2\Reincarnated as a Familiar Volume 2 (Light Novel)_B08DQWJTGN.kfx-zip
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing E:/documents/Downloads/Items01/The Thran (Magic_ The Gathering_ The Thran)_B07BNVL4RV.kfx
Added Reincarnated as a Familiar Volume 1 (Light Novel) to db in: 0.1
Gather KFX-ZIP (from KFX Input): Gathered 9 file(s) as C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\wxmblp.kfx-zip
Added Reincarnated as a Familiar Volume 2 (Light Novel) to db in: 0.1
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\ellvqy.kfx-zip
DeDRM v6.8.0: Trying to decrypt jbtxdy.kfx-zip
Decrypting KFX-ZIP ebook: jbtxdy
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\elicu\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\jbtxdy.kfx-zip
Processing container: My Best Friend is Dense Harem Main Character-kun, But Why am I the Heroine_! Volume 1 (Best Friend and_B07FHZ2CQY.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container My Best Friend is Dense Harem Main Character-kun, But Why am I the Heroine_! Volume 1 (Best Friend and_B07FHZ2CQY.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\ehvjga_add_books\6\My Best Friend is Dense Harem Main Character-kun, But Why am I the Heroine_! Volume 1 (Best Friend and_B07FHZ2CQY.kfx-zip
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing E:/documents/Downloads/Items01/So I'm a Spider, So What_, Vol. 1 (light novel) (So I'm a Spider, So What_ (light novel))_B0723G97LX.kfx
Added My Best Friend is Dense Harem Main Character-kun, But Why am I the Heroine?! Volume 1 (Best Friend and Dense MC-kun) to db in: 0.1
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\zdeytb.kfx-zip
DeDRM v6.8.0: Trying to decrypt wxmblp.kfx-zip
Decrypting KFX-ZIP ebook: wxmblp
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\elicu\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\wxmblp.kfx-zip
Processing container: 1984_B003JTHWKU.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container 1984_B003JTHWKU.kfx has DRM and cannot be converted
DeDRM v6.8.0: Trying to decrypt ellvqy.kfx-zip
KFX metadata reader (from KFX Input) activated for C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\ehvjga_add_books\5\1984_B003JTHWKU.kfx-zip
Decrypting KFX-ZIP ebook: ellvqy
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\elicu\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\ellvqy.kfx-zip
Processing container: CR!D0MC74HQ6N5XB7VW3B888XGJ7Q2Q.kfx
Processing container: The Thran (Magic_ The Gathering_ The Thran)_B07BNVL4RV.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container The Thran (Magic_ The Gathering_ The Thran)_B07BNVL4RV.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\ehvjga_add_books\4\The Thran (Magic_ The Gathering_ The Thran)_B07BNVL4RV.kfx-zip
Added 1984 to db in: 0.1
Added The Thran (Magic: The Gathering: The Thran) to db in: 0.1
DeDRM v6.8.0: Trying to decrypt zdeytb.kfx-zip
Decrypting KFX-ZIP ebook: zdeytb
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\elicu\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\zdeytb.kfx-zip
Processing container: CR!WMH1DQM2494ED48T9PMH3RW9K7MK.kfx
Processing container: So I'm a Spider, So What_, Vol. 1 (light novel) (So I'm a Spider, So What_ (light novel))_B0723G97LX.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container So I'm a Spider, So What_, Vol. 1 (light novel) (So I'm a Spider, So What_ (light novel))_B0723G97LX.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\elicu\AppData\Local\Temp\calibre_ulqh9d\ehvjga_add_books\3\So I'm a Spider, So What_, Vol. 1 (light novel) (So I'm a Spider, So What_ (light novel))_B0723G97LX.kfx-zip
Added So I'm a Spider, So What?, Vol. 1 (light novel) (So I'm a Spider, So What? (light novel)) to db in: 0.1
Added 7 books in 2.6 seconds
Worker Launch took: 0.0940001010895

**Comment by ElleKayEm** [comment]
You cannot decrypt books directly from the newer Kindles.  Download from the website choosing your E-ink Kindle for the device.

**Comment by tartley** [comment]
I'm going to close this as user error.

Users would understand better (in particular, supported kindle versions) when we improve the docs, for which a ticket exists: https://github.com/apprenticeharper/DeDRM_tools/issues/1327
