### ISSUE TITLE
DRM Not Being Removed on Kindle Ebook with Calibre

### ISSUE THREAD

**Issue by bchtown** [apprenticeharper/DeDRM_tools#133]
I'm using the latest version of DeDRM with the latest version of Calibre on OS 10.8.5 for a Kindle ebook and getting the message "Failed: Convert book 1 of 1 (the book name)". I changed the location of my Kindle Content to an easily accessible location on my Mac so I'm able to access the ebook directly. I have already deregistered and re-downloaded the book so the azw4 file I'm uploading to Calibre is the latest, clean copy. Attached is the conversion error detail.
[Conversion error in Calibre - Becoming Influential.docx](https://github.com/apprenticeharper/DeDRM_tools/files/471062/Conversion.error.in.Calibre.-.Becoming.Influential.docx)

I've also tried using the app with my Mac by dragging and dropping to the DeDRM icon in my applications folder and get this error message "B00EIR8M6U_EBOK.azw4 couldn't be decrypted. "doesn't understand the <<event sysonotf>> message". This is the AppleScript log.

[Apple Script Log - Becoming Influential Kindle ebook.docx](https://github.com/apprenticeharper/DeDRM_tools/files/471073/Apple.Script.Log.-.Becoming.Influential.Kindle.ebook.docx)

Thanks!

**Comment by ElleKayEm** [comment]
In order to see what is happening with DRM removal, we'll need to see the debug log from adding the book to calibre.

**Comment by bchtown** [comment]
Here you go.

Thanks



On Sep 13, 2016, at 6:20 PM, ElleKayEm <notifications@github.com> wrote:

In order to see what is happening with DRM removal, we'll need to see the debug log from adding the book to calibre.

**Comment by ElleKayEm** [comment]
You haven't included the log.

**Comment by bchtown** [comment]
It was attached as a word document. I copied and pasted the log into a word document. is there another format you want it in? I've attached it again below.




On Sep 14, 2016, at 4:02 AM, ElleKayEm <notifications@github.com> wrote:

You haven't included the log.

**Comment by ElleKayEm** [comment]
Log still didn't get attached.  Reply on the Github site, instead of via email.

**Comment by bchtown** [comment]
ok.


On Sep 14, 2016, at 3:20 PM, ElleKayEm <notifications@github.com> wrote:

Log still didn't get attached. Reply on the Github site, instead of via email.

**Comment by bchtown** [comment]
[Calibre Debug log - Becoming Influential.docx](https://github.com/apprenticeharper/DeDRM_tools/files/473699/Calibre.Debug.log.-.Becoming.Influential.docx)

**Comment by ElleKayEm** [comment]
Cannot decode library or rented ebooks

**Comment by bchtown** [comment]
Is there anything that can?

**Comment by ElleKayEm** [comment]
You're not going to get any help for that here.
