### ISSUE TITLE
Amazon PC 1.26 .azw file not having drm removed

### ISSUE THREAD

**Issue by FlamingoStorm** [apprenticeharper/DeDRM_tools#1330]
I try downloading books on amazon for pc and even did the trick to get the program to use .azw instead of .kfx but it is not working. I am using a windows 10 x64 pc. The debug log is as follows:
calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.20236-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.20236')
Python 2.7.16+
Windows: ('10', '10.0.20236', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.20236-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.20236')
Python 2.7.16+
Windows: ('10', '10.0.20236', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.0 x 95.9160839161
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.36] splash screen shown
[0.36] Initializing db...
[0.36] db initialized
[0.36] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Loaded cached store plugin for: Amazon Kindle at version: 19
Loaded cached store plugin for: ebook.de at version: 6
[1.44] main UI initialized...
[1.44] Hiding splash screen
[3.88] splash screen hidden
[3.88] Started up in 3.88 seconds with 1 books
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing C:/Users/elicu/OneDrive/School Work/My Kindle Content/B07BNVL4RV_EBOK/B07BNVL4RV_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\elicu\AppData\Local\Temp\calibre_ms0rea\ncx32y.kfx-zip
DeDRM v6.8.0: Trying to decrypt ncx32y.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: ncx32y
Got DSN key from database Windows 10 x64
Found 2 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.9d11d019-eccc-4a22-867d-3c6a91de81e5.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\elicu\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\elicu\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '4105890013' and UserName '656c696375'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: ncx32y
Got DSN key from database default_key_1
Found 1 keys to try after 5.6 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.9d11d019-eccc-4a22-867d-3c6a91de81e5.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 5.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 5.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\elicu\AppData\Local\Temp\calibre_ms0rea\ncx32y.kfx-zip
Processing container: B07BNVL4RV_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container B07BNVL4RV_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\elicu\AppData\Local\Temp\calibre_ms0rea\8fi9bn_add_books\0\B07BNVL4RV_EBOK.kfx-zip
Added The Thran (Magic: The Gathering: The Thran) to db in: 0.2
Added 1 books in 6.8 seconds

**Comment by tartley** [comment]
Hi. Is the '1.30' in your title the version of Kindle for PC? You must use Kindle for PC 1.26 or earlier.

**Comment by FlamingoStorm** [comment]
yes it is the version of  kindle pc I am using and the FAQ doesn't say anything other than "it (the trick to get .azw) may not work in versions past 1.25"

**Comment by tartley** [comment]
Thanks for filing the report.

Yes, you have to use Kindle for PC <= 1.26

We get a lot of reports like this, it's clear we have to make the documentation clearer. There is an issue for improving the documentation: https://github.com/apprenticeharper/DeDRM_tools/issues/1328

**Comment by FlamingoStorm** [comment]
I installed kindle for pc 1.26 and it is still not working:
calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.20236-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.20236')
Python 2.7.16+
Windows: ('10', '10.0.20236', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.20236-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.20236')
Python 2.7.16+
Windows: ('10', '10.0.20236', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.0 x 95.9160839161
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Loaded cached store plugin for: Amazon Kindle at version: 19
Loaded cached store plugin for: ebook.de at version: 6
[0.86] main UI initialized...
[0.86] Hiding splash screen
[3.27] splash screen hidden
[3.27] Started up in 3.27 seconds with 1 books
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing C:/Users/elicu/OneDrive/School Work/My Kindle Content/B07PZ2NGJ1_EBOK/B07PZ2NGJ1_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\elicu\AppData\Local\Temp\calibre_9ebci_\_hvfcs.kfx-zip
DeDRM v6.8.0: Trying to decrypt _hvfcs.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: _hvfcs
Got DSN key from database Windows 10 x64
Found 2 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.8ba26f2e-e64c-4a96-85ee-7958dd1269e4.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.8.0: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\elicu\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\elicu\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '4105890013' and UserName '656c696375'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: _hvfcs
Got DSN key from database default_key_1
Found 1 keys to try after 5.7 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.8ba26f2e-e64c-4a96-85ee-7958dd1269e4.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.8.0: Ultimately failed to decrypt after 5.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 5.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\elicu\AppData\Local\Temp\calibre_9ebci_\_hvfcs.kfx-zip
Processing container: B07PZ2NGJ1_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container B07PZ2NGJ1_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\elicu\AppData\Local\Temp\calibre_9ebci_\2dnlin_add_books\0\B07PZ2NGJ1_EBOK.kfx-zip
Added Rebirth of the Undead King: Book 1 to db in: 0.1
Added 1 books in 6.8 seconds

**Comment by tartley** [comment]
You have reached the limits of my knowledge. Hopefully someone else can add some useful information...

**Comment by tartley** [comment]
I'm chaning the title of this issue to say "1.26"

**Comment by FlamingoStorm** [comment]
don't I found the issue

**Comment by FlamingoStorm** [comment]
in 1.26 it did not work because I accidentally tested with a kindle unlimited book

**Comment by tartley** [comment]
Ah, thanks for reporting back. So does that mean it is working now?

**Comment by koumaza** [comment]
> in 1.26 it did not work because I accidentally tested with a kindle unlimited book

##### <= 1.2.4
In my case it worked before 1.2.4.

**Comment by ElleKayEm** [comment]
@FlamingoStorm 
Just FYI, you say that you tried disabling KFX format downloads, but that log shows a KFX format book.  The method of renaming renderer-test only works for Kindle for PC 1.19 through 1.24.  Or you can use 1.17 which is the last version which doesn't download KFX format at all.  As mentioned above, (purchased) books in KFX format downloaded with K4PC 1.26 and earlier can be DeDRMed.
