### ISSUE TITLE
syntax

### ISSUE THREAD

**Issue by SpiderJonny** [apprenticeharper/DeDRM_tools#1336]
Trying to install DeDRM_Plugin 6.8.0 in Calibre 5.3.0, but get the following error:

ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.3 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 3.8.5
Windows: ('8.1', '6.3.9600', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 285, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 177, in exec_module
  File "calibre\customize\zipplugin.py", line 173, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by dqwfgzs** [comment]
> Trying to install DeDRM_Plugin 6.8.0 in Calibre 5.3.0, but get the following error:
> 
> ERROR: Unhandled exception: SyntaxError:invalid syntax (calibre_plugins.dedrm.**init**, line 168)
> 
> calibre 5.3 [64bit] embedded-python: True is64bit: True
> Windows-8.1-6.3.9600-SP0 Windows ('64bit', 'WindowsPE')
> ('Windows', '8.1', '6.3.9600')
> Python 3.8.5
> Windows: ('8.1', '6.3.9600', 'SP0', 'Multiprocessor Free')
> Interface language: en_GB
> Successfully initialized third party plugins:
> Traceback (most recent call last):
> File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
> File "calibre\customize\ui.py", line 472, in add_plugin
> File "calibre\customize\ui.py", line 61, in load_plugin
> File "calibre\customize\zipplugin.py", line 285, in load
> File "importlib__init__.py", line 127, in import_module
> File "", line 1014, in _gcd_import
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 671, in _load_unlocked
> File "calibre\customize\zipplugin.py", line 177, in exec_module
> File "calibre\customize\zipplugin.py", line 173, in get_code
> File "calibre_plugins.dedrm.**init**", line 168
> print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
> ^
> SyntaxError: invalid syntax

You need to downgrade to 4.x. It seems that you cannot upgrade to 5.x unless the author updates the plugin.

**Comment by SpiderJonny** [comment]
> You need to downgrade to 4.x. It seems that you cannot upgrade to 5.x unless the author updates the plugin.

Thanks!

**Comment by UnKnoWn-Consortium** [comment]
5.x has moved to Python 3 as Python 2 is going to meet its EOL this year. So there are plenty of breaking changes.

**Comment by ElleKayEm** [comment]
Update to Python 3 is being worked on.
