### ISSUE TITLE
DRM Being removed from one eBook, but not another.

### ISSUE THREAD

**Issue by itsaferbie** [apprenticeharper/DeDRM_tools#134]
Hello,

I am having an issue with a eBook not having its drm being removed, but it will remove the drm from a different eBook.

With the eBook not having its drm removed the file size is 859 MB, while the other is only 30 MB.

I have deactivated and reinstalled Kindle for PC and even reinstalled calibre, but the issue still happens.

Here is the log of the eBook not having its drm being removed.

calibre Debug log
calibre 2.67  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 1) && KindleUnpack - The Plugin (0, 81, 2)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.735785953 x 108.857142857
Starting up...
Started up in 4.13 seconds with 2 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['2%S\x05H\xd1\xca \xcf@\xdb\xd7\x8d?lB=\xbfqAF\xfa[G\xec\x06Hq\xcd\x84\x83\x0e', 'C:\\Users\\Donald\\Documents\\My Kindle Content\\B018SAIJBA_EBOK.azw4']
DeDRM v6.5.1: Trying to decrypt B018SAIJBA_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 608, in run
  File "calibre_plugins.dedrm.__init__", line 520, in KindleMobiDecrypt
IndexError: tuple index out of range
Added Living with Art to db in: 1.2
Added 1 books in 2.0 seconds

I even have a log of me adding both books and it showing the smaller book succeeding, if you'd like to see that.

Thank you.

**Comment by ElleKayEm** [comment]
Sounds like it is just specific to that book then.  The large size may indeed be the problem.  @apprenticeharper will probably need to answer this.

**Comment by apprenticeharper** [comment]
It's probably a memory error. Try running the 64-bit version of calibre.

**Comment by itsaferbie** [comment]
That fixed the issue. Using the 64-bit version solved my issue. Thanks @apprenticeharper
