### ISSUE TITLE
Calibre 4.23 Unable to Remove DRM from Overdrive Book

### ISSUE THREAD

**Issue by Geektasticdad** [apprenticeharper/DeDRM_tools#1343]
calibre Debug log
calibre 4.23 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 94.2376811594 x 94.2680412371
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.61] splash screen shown
[0.61] Initializing db...
[0.61] db initialized
[0.61] Constructing main UI...
[2.25] main UI initialized...
[2.25] Hiding splash screen
[27.62] splash screen hidden
[27.62] Started up in 27.62 seconds with 1 books
DeDRM v6.8.0: Trying to decrypt The Golden Compass-Part01.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: “The Golden Compass-Part01.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 412, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Couldn't decrypt after 0.2 seconds. DRM free perhaps?
Added The Golden Compass to db in: 0.2
Added 1 books in 1.3 seconds
Worker Launch took: 0.151999950409

**Comment by apprenticeharper** [comment]
"The Golden Compass-Part01.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub"

So DeDRM can't help
