### ISSUE TITLE
Logging in with Kindle for PC 1.17 stopped working as of today (2020-11-01)

### ISSUE THREAD

**Issue by PyroDevil** [apprenticeharper/DeDRM_tools#1345]
The 1.17 version of Kindle for PC has stopped working, because it can no longer log into Amazon (amazon.de).

It complains about wrong E-Mail or phone number when entered the correct on. Hopefully this is a temporary issue.

Here is what I tried so far:
- Logging in with Kindle 1.17.0 (44170) does not work
- Logging in with Kindle 1.17.1 (44183) does not work
- Logging in with Kindle 1.25 works

When logging in via Kindle 1.25 I get asked to enter a captcha and click on a link I get via email. So I guess the login process has changed with newer versions of Kindle? I also disable 2FA for my account, but that also did not help.

It seems an existing registered kindle for pc 1.17.0 still works, only new registration fails.

**Comment by PyroDevil** [comment]
@SvenErik1968: Interesting. I use 1.17.0 (44170). Do you have a link for your version?

**Comment by PyroDevil** [comment]
@SvenErik1968: Nevermind I found a 1.17.1 download, however logging in still doesn't work. I login to amazon.de. Maybe that is a reason?

**Comment by PyroDevil** [comment]
Just to clarify logging in with 1.25 worked

**Comment by SvenErik1968** [comment]
If this is a change from Amazon, maybe they are rolling it out regionwise or over time. I log into amazon.com from Norway.

**Comment by SvenErik1968** [comment]
@PyroDevil, I am running v1 1.17.1 (44183) on Windows 10, and I just tested it, and I could log in and download purchased books...

**Comment by ElleKayEm** [comment]
Someone over at MobileRead reported this.  They were able to resolve it though.  They installed and registered the latest version of Kindle for PC.  Then installed version 1.17 and were able to register it with the extra step of approving the sign-in attempt on their phone.  (Always making sure the automatic update box was unchecked.)

**Comment by sean-perryman** [comment]
Just wanted to pop in and say the fix that @ElleKayEm mentioned does not work for me. I was able to log into the newest version of Kindle for PC, then I installed 1.17.1 over the top and it still tells me to enter a valid email address.

**Comment by sean-perryman** [comment]
Ok, I think I have it sorted. Had to install a 1.24 version (https://www.epubor.com/how-to-downgrade-kindle-for-pcmac.html), then register/login/whatever, then install 1.17 over the top. That gets past that hurdle at least, haven't tried running  a book through yet.

**Comment by PyroDevil** [comment]
@sean-perryman: That worked for me as well. Thanks! I think it was cause by a forced update for me. So I also followed [a post on mobile read](https://www.mobileread.com/forums/showpost.php?p=4052995&postcount=59) to disable the force update permanently.

**Comment by zenon49** [comment]
I also couldn't login any more. 
@sean-perryman your method worked for me as well, tanks!

**Comment by sulazix** [comment]
I had this issue too tanks @sean-perryman  your fix worked for me.

**Comment by bhillyer** [comment]
Mine just stopped working completely the Week of 02/14/2021. Just stopped opening. I tried uninstalling, then uninstalling with Revo Uninstaller, turning off AV for a moment, and installing while unplugged from the internet to see if it would launch at least.
I've tried all of my saved install files that used to work, 1.17 44170, 1.24 51068, and 1.26 55076 All will install but none will launch at all. They icon just blinks once and don't even show up in task manager.

**Comment by ElleKayEm** [comment]
What about installing the current version?

**Comment by bhillyer** [comment]
An update. I went to other computers I had Kindle for PC 1.17 installed and even though updates were turned off on both, one automatically updated anyway. I verified it updated, and that the option to Auto Update was still unchecked. The other computer I turned off wifi before launching, then connected and downloaded, and even though all books were downloaded with KfPC 1.17 only one was able to convert in Calibre 4.23 with DeDRM 6.63. I got the protected by DRM pop-up on 5 books purchased. 
Something is definitely up.

**Comment by bhillyer** [comment]
> What about installing the current version?

New version is not opening either. Maybe a Windows 10 20H2 update borked it. I have installed and updated other software, but only Kindle is refusing to open so far, but now other issues with Kindle have happened on 2 other Win10 PCs today.

**Comment by ElleKayEm** [comment]
K4PC 1.17 still working on Windows 10 for me.  This is the first I've heard about not being able to install the current version.  Maybe try deregistering from the website, then reinstalling?

**Comment by PyroDevil** [comment]
Kindle for PC 1.17.1 (44183) also works for me on Win10. I recently have issues with the my Kindle setup on Wine/Linux, but I guess that is probably in issue with my wine setup.

I can only repeat my hint: Kindle apparently still updates even if those are disabled in the options, you have to disable them by creating a file where Kindle would place its update directory to prevent that. See [this](https://www.mobileread.com/forums/showpost.php?p=4051217&postcount=14) or take permissions away to write to this directory.

**Comment by agaring** [comment]
For those that encounter this issue, there may be an even simple solution, read this reddit thread: https://www.reddit.com/r/Calibre/comments/hlj4z5/registering_kindle_for_pc_117/

In summary:

- Uninstall Kindle for PC
- Go and delete the registry key folder "HKEY_CURRENT_USER\SOFTWARE\Amazon"
- Install Kindle for PC
- Login

Worked perfectly for me

**Comment by DavidGretzschel** [comment]
Couldn't log in with 1.24 anymore. The Amazon-form kept insta-reload-looping itself.
![AmazonInstaFormReload](https://user-images.githubusercontent.com/23729465/146756584-3a22770a-7e91-4bdb-a6d9-cc1854864490.gif)

But thankfully the registry trick allowed me to just log in with 1.17 again. Many thanks for figuring that out.

**Comment by viet4777** [comment]
> For those that encounter this issue, there may be an even simpler solution, read this reddit thread: https://www.reddit.com/r/Calibre/comments/hlj4z5/registering_kindle_for_pc_117/
> 
> In summary:
> 
> 1. Uninstall Kindle for PC
> 2. Go and delete the registry key folder "HKEY_CURRENT_USER\SOFTWARE\Amazon"
> 3. Install Kindle for PC
> 4. Login
> 
> Worked perfectly for me

Worked perfectly for me, tooo.

**Comment by jameshounshell** [comment]
I know I'm bumping a dead thread but I wanted to say registry key delete worked for me as of 2022/06/11.

**Comment by london36** [comment]
> For those that encounter this issue, there may be an even simpler solution, read this reddit thread: https://www.reddit.com/r/Calibre/comments/hlj4z5/registering_kindle_for_pc_117/
> 
> In summary:
> 
>     1. Uninstall Kindle for PC
> 
>     2. Go and delete the registry key folder "HKEY_CURRENT_USER\SOFTWARE\Amazon"
> 
>     3. Install Kindle for PC
> 
>     4. Login
> 
> 
> Worked perfectly for me

As per January 2023 this worked perfectly ! after trying to upgrade and downgrade several times

**Comment by ybymentario** [comment]
> For those that encounter this issue, there may be an even simpler solution, read this reddit thread: https://www.reddit.com/r/Calibre/comments/hlj4z5/registering_kindle_for_pc_117/
> 
> In summary:
> 
> 1. Uninstall Kindle for PC
> 2. Go and delete the registry key folder "HKEY_CURRENT_USER\SOFTWARE\Amazon"
> 3. Install Kindle for PC
> 4. Login
> 
> Worked perfectly for me

Not working anymore as of October 2023. Cannot log in as the captcha doesn't load.

**Comment by transitionsystem** [comment]
Dec 2023. Having the same problem as Narnarar1. Captcha doesn't load. Any solutions?

**Comment by ElleKayEm** [comment]
You know that you can only download books published before 2023 with older versions of Kindle for PC.  You can decrypt most books downloaded with the current Kindle for PC 2.2 with DeDRM 10.0.9 and KFX Input plugins.

**Comment by transitionsystem** [comment]
No I did not know this! Hadn't actually discovered Calibre yet either. Cheers. 

Previously used anyebookconverter. 

Edit: Worked Perfectly.

**Comment by alexwu-github** [comment]
> You know that you can only download books published before 2023 with older versions of Kindle for PC. You can decrypt most books downloaded with the current Kindle for PC 2.2 with DeDRM 10.0.9 and KFX Input plugins.

old thread but, I'm getting a Kobo and looking if possible for me to buy kindle books if kobo doesn't have it. So if I don't own a kindle I can't remove  DRM from kindle e-books? I need to use old kindle pc and only buy books that is pubished before 2023 or get a new kindle?

**Comment by ElleKayEm** [comment]
Books from the current Kindle for PC 2.4.1 cannot be decrypted.  But most books from recent Kindle for PC 2.3.5 and 2.4.0 can be.  And those versions will download newly published books.

See more details and other methods here: https://www.mobileread.com/forums/showthread.php?t=361503
