### ISSUE TITLE
Importing ADE keys exported from 6.8.0 fails in Python 3 version

### ISSUE THREAD

**Issue by Forger125** [apprenticeharper/DeDRM_tools#1347]
First and foremost, a huge thank you to all the awesome developers pouring in the herculean effort to port DeDRM to Python 3. You all are incredible!

When testing if it was time to migrate to Calibre 5 with the DeDRM plugin, I tested exporting keys from my main (Calibre 4, DeDRM 6.x) computer to my testing (Calibre 5, DeDRM 7.0 from GitHub) computer using the Import Existing Keyfiles function. The Kindle for PC encryption keys imported without issue, but when trying to import Adobe Digital Editions keys exported as .der files, I received the following unhandled exception error:

```
calibre 5.4.2  embedded-python: True is64bit: True
Linux-5.4.0-52-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-52-generic', '#57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 35, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 35, 0) && Audit Log (1, 0, 15) && CalibreSpy (1, 0, 82) && Job Spy (1, 0, 187) && KFX metadata reader (from KFX Input) (1, 35, 0) && KFX Input (1, 35, 0)
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 417, in migrate_wrapper
    if self.migrate_files():
  File "calibre_plugins.dedrm.config", line 381, in migrate_files
    new_key_value = new_key_value.encode('hex')
AttributeError: 'bytes' object has no attribute 'encode'
```

This appears to be a Python 3-related error, and I know the work of porting is ongoing - just wanted to bring it to the attention of the developers. Thank you all again!

**Comment by apprenticeharper** [comment]
Try with 7.0.0b2
