### ISSUE TITLE
Failure with Obok and Kobo Desktop 4.0.5579

### ISSUE THREAD

**Issue by Robnina** [apprenticeharper/DeDRM_tools#135]
This is probably a known fault, but after a forced "upgrading" to the latest Kobo Desktop version Obok appears to be broken... Debug below:

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.
C:\Users\robni>calibre-debug -g
calibre 2.68 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Qt: Untested Windows version 10.0 detected!
Successfully initialized third party plugins: DeDRM (6, 5, 1) && Kobo Utilities (2, 4, 1) && KoboTouchExtended (2, 8, 0) && Obok DeDRM (6, 3, 6)
devicePixelRatio: 1.0
logicalDpi: 144.0 x 144.0
physicalDpi: 207.523404255 x 207.818181818
Starting up...
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    2.8 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    2.8 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    2.8 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    2.8 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
Started up in 3.98 seconds with 5584 books
Running Obok DeDRM v6.3.6
DEBUG:   36.2 didn't find device
Obok v3.1.9
Copyright © 2012-2015 Physisticated et al.
DEBUG:   36.2 got kobodir C:\Users\robni\AppData\Local\Kobo\Kobo Desktop Edition
calibre 2.68 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 1) && Kobo Utilities (2, 4, 1) && KoboTouchExtended (2, 8, 0) && Obok DeDRM (6, 3, 6)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 107, in launchObok
  File "calibre_plugins.obok_dedrm.action", line 210, in build_book_list
  File "calibre_plugins.obok_dedrm.obok.obok", line 387, in books
DatabaseError: file is encrypted or is not a database

Any help greatly appreciated!
Rob.

**Comment by ElleKayEm** [comment]
The following comment was left over at Alf's blog:

> KoboK says:
September 10, 2016 at 6:15 pm
Just as an FYI to Obok users:

>The changes to book encryption in Kobo Desktop version 4.0.x appear to be somewhat more involved than the last few times when they just changed the key derivation salt – there’s a separate wholly encrypted database for books now. So, it may take a bit longer than what we’ve recently gotten used to until Obok can support these latest app changes, but I’m sure we’ll get there eventually.

So it does seem that people are aware and working on it.  Thanks for adding the issue here so others can see what's happening.

In the meantime, you can still get your Kobo books from the website via Adobe Digital Editions 2.0.1 (authorized with an Adobe ID) and then use the DeDRM tools instead of Obok.

**Comment by carolineplourde** [comment]
Thanks for posting this, I have the same issue

**Comment by apprenticeharper** [comment]
Please try the obok plugin just uploaded to the repository here: https://github.com/apprenticeharper/DeDRM_tools/tree/master/Obok_calibre_plugin

**Comment by ElleKayEm** [comment]
Works for me with the latest Kobo Desktop on Windows 8.

**Comment by stormborn2** [comment]
@apprenticeharper
So importing *apsw* instead of *sqlite3* takes care of the BS "encrypted or is not a database" error message even without updating Python's sqlite3.dll to a newer version?

**Comment by Robnina** [comment]
Looks to be working on Win10, Calibre 2.68.0 and Kobo Desktop 4.0.5579. Absolutely awesome work!
Thanx!

**Comment by apprenticeharper** [comment]
Not my fix. Work by others who wish to remain anonymous.

I'm not 100% happy because it seems that ActiveState Python (at least under Windows) doesn't include apsw support, which means that the obok.py script won't run on its own. I'm still looking into other options.

**Comment by stormborn2** [comment]
@apprenticeharper
If you make a temp copy of Kobo.sqlite and change file offsets 18-19 from 0x0202 to 0x0101 (https://www.sqlite.org/fileformat2.html) then that database seems to work OK with Python 2.7 *sqlite3*. Unfortunately the WAL mode was added in SQLite 3.7 and Python 2.7 appears to only know about 3.6. I don't believe any regular distribution has *apsw*.

**Comment by stormborn2** [comment]
I suggested a temp file because simply setting *PRAGMA journal_mode = DELETE;* before doing anything else doesn't seem to help. It gets set OK but rest of the statements still fail after that. I don't think we want to be messing with the original db anyway, so trying to do it the API way doesn't really matter then.

**Comment by apprenticeharper** [comment]
Thank you for the suggestion. That might be a better way to go. Does anyone else have any comments about this possible solution?

**Comment by fhdeutschmann** [comment]
Another approach: install the sqlite3 tools, and run the attached 
[kobo-compat.txt](https://github.com/apprenticeharper/DeDRM_tools/files/514525/kobo-compat.txt)
 script using the sqlite3 tool - results in writing a minimal Kobo database (just content, content_keys, user, all with only the columns needed) which can be opened by Python with the sqlite3 module.  

Also note, I had to add a check for mimetype==xhtml+xml to accept "<!DOCTYPE html"

And if a Win10 user is running with a profile coming from a UNC path, the popen to ipconfig needs to be modified.

**Comment by apprenticeharper** [comment]
I've changed to use a tweaked temporary file. This seems to work for the stand-alone script as well as the plugin, and should work on non-Windows systems.

Please try this revised obok plugin just uploaded to the repository here: https://github.com/apprenticeharper/DeDRM_tools/tree/master/Obok_calibre_plugin

**Comment by ElleKayEm** [comment]
Maybe not terribly helpful, but just so you know someone else tried it:  the revised plugin works for me on Windows.

**Comment by apprenticeharper** [comment]
All reports are useful.

**Comment by stormborn2** [comment]
Coolio, it seems to work great. I think now it'd also make sense to turn command-line book selection into a loop, because then, if people want to do several books, the temp file can be reused and the general overhead of loading Python and running db prep every time can be avoided.

**Comment by apprenticeharper** [comment]
Released in v6.5.2

**Comment by apprenticeharper** [comment]
@stormborn2: If you'd like to contribute a pull request that allows the command line option to do an efficient loop without breaking the plugin, I'd probably include it in the next big release.

I don't think that command line use of the script is a big enough 'market' to spend the time on it myself. But I appreciate the interest.

**Comment by apprenticeharper** [comment]
6.5.2 seems to have fixed this.
