### ISSUE TITLE
Rolled Back to Calibre 4.23 - Now DeDRM Isn't Working

### ISSUE THREAD

**Issue by acherates** [apprenticeharper/DeDRM_tools#1356]
Hi,

Uninstalled latest Calibre. Rolled back to 4.23.

Downloaded Apprentice Alf's DeDRM.

Always worked before. Not working now.

Attached are images of the files, and what I've done in Calibre.

What do you think is happening?

Sincerely,

Blaine
![calib-ddrm-err](https://user-images.githubusercontent.com/65814934/98450966-71923280-217c-11eb-8d34-65a46324b77f.jpg)
[Calibre Errs.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5505392/Calibre.Errs.txt)

**Comment by ElleKayEm** [comment]
Did you remove and re-add the book before trying to convert?

**Comment by acherates** [comment]
Ah!  Let me try that... :)

**Comment by acherates** [comment]
Hip, hip...HOORAY!!!  That was it.

T H A N K  Y O U  !  !  ! **:D**

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by acherates** [comment]
Hi ElleKayEm,

Ah!  Yep.  All set.  Will do.  Thank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! **:D :D**
