### ISSUE TITLE
[QUESTION] Calibre 5 Python 3 PyCrypto Wine

### ISSUE THREAD

**Issue by riker513** [apprenticeharper/DeDRM_tools#1360]
Hi there,
thanks for all the work on the nice tools.
I used them for years via Wine and KindleForPC, but now I got stuck. I've already wasted half a day on this, so I'd like to ask if there is a chance it will be possible in reasonable time to use Calibre >5 with DeDRM7, Kindle for PC 1.7 under PlayOnLinux/Wine?

I got Calibre 5, KindleForPC, DeDRM 7 master branch plugin set up, but then I was stuck and couldnt solve the problem from Calibre debug log:
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v7.0.0: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v7.0.0: Looking for new default Kindle Key after 0.0 seconds
DeDRM v7.0.0: Running kindlekey.py under Wine
DeDRM v7.0.0: Command line: 'PYTHONPATH="" WINEPREFIX="/home/user/.PlayOnLinux/wineprefix/amazon_kindle" wine python.exe "/home/user/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/user/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
Added 0 books in 4.9 seconds

This is because there is no python.exe - but I couldn't manage to install Python 3 and a suitable version of PyCrypto under Wine, mainly because I did not find a suitable installer for the latter.
Does anybody have any ideas on this?
By the way, I don't own a Kindle, I solely run KindleForPC conntected to my Amazon account.

Kind regards
riheki

**Comment by ElleKayEm** [comment]
Maybe run kindlekey.pyw from DeDRM 6.8 under Wine with your previous Python 2 and PyCrypto setup.  Then manually import the retrieved key into DeDRM 7 in calibre 5.

**Comment by riker513** [comment]
That's it, guys. Trust this man.

**Comment by riker513** [comment]
Thanks!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
