### ISSUE TITLE
[QUESTION] Cannot remove DRM from 'The Rocket Mass Heater Builder's Guide' .azw3 file

### ISSUE THREAD

**Issue by humblepi-ipelbmuh** [apprenticeharper/DeDRM_tools#1361]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Cannot remove DRM from 'The Rocket Mass Heater Builder's Guide' .azw3 file
<calibre Debug log
calibre 2.85.1  embedded-python: True is64bit: True
Darwin-14.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.5.0', 'Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.10.5', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM (6, 8, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Starting up...
Started up in 2.97 seconds with 4 books
2020-11-11 13:20:24.251 calibre-debug[1653:59273] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fea5c6be640 h=-&- v=-&- V:|-(0)-[NSClipView:0x7fea5c6c73b0]   (Names: '|':FI_TListScrollView:0x7fea5c6afb70 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fea5c6b9660 h=-&- v=-&- V:[NSClipView:0x7fea5c6c73b0]-(15)-|   (Names: '|':FI_TListScrollView:0x7fea5c6afb70 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fea5c638bc0 h=--& v=--& V:[FI_TBrowserBackgroundView:0x7fea5c615e20(0)]>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fea5c6a7360 h=-&- v=-&- V:|-(0)-[FI_TListScrollView:0x7fea5c6afb70]   (Names: '|':FI_TBrowserBackgroundView:0x7fea5c615e20 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fea5c6ac760 h=-&- v=-&- V:[FI_TListScrollView:0x7fea5c6afb70]-(0)-|   (Names: '|':FI_TBrowserBackgroundView:0x7fea5c615e20 )>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x7fea5c6b9660 h=-&- v=-&- V:[NSClipView:0x7fea5c6c73b0]-(15)-|   (Names: '|':FI_TListScrollView:0x7fea5c6afb70 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
DeDRM v6.8.0: Trying to decrypt The Rocket Mass Heater Builder's Guide.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Rocket Mass Heater Builder's Guide
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.2 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Rocket Mass Heater Builder's Guide to db in: 0.6
Added 1 books in 1.7 seconds
>

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

**Comment by humblepi-ipelbmuh** [comment]
Hi ApprenticeAlf,

I'm having some trouble please help?

J

**Comment by ElleKayEm** [comment]
Enter your Kindle's serial number into the DeDRM customization.  After restarting calibre, remove and re-add your book.

**Comment by humblepi-ipelbmuh** [comment]
Thank you @ElleKayEm Unfortunately this didn't work.

I entered my serial into the only option availble (eINK Kindle ebooks), restarted Calibre and got the same error message:

"Cannot convert The Rocket Mass Heater Builder's Guide - This book is locked by DRM. To learn more..."

**Comment by humblepi-ipelbmuh** [comment]
YES!!! Thank you @ElleKayEm
