### ISSUE TITLE
[QUESTION] Can't unlock DRM for Adobe Digital

### ISSUE THREAD

**Issue by ToReadManyBooks** [apprenticeharper/DeDRM_tools#1364]
Calibre: 4.23
DeDRM: 6.8
Adoble Digital: 4.5

Imported books to Calibre and can't unlock the DRMs.

Thanks.

**Comment by ElleKayEm** [comment]
Can you read the book with Adobe Digital Editions 2.0.1 authorized with the same Adobe ID?

**Comment by ToReadManyBooks** [comment]
I installed Adobe Digital Editions 2.0.1 and, with this combination, the DRM is successfully unlocked. Thanks for the tip.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by ToReadManyBooks** [comment]
Problem resolved!
