### ISSUE TITLE
Issue with Obok DeDRM

### ISSUE THREAD

**Issue by Pandalff** [apprenticeharper/DeDRM_tools#1365]
Hi,

I have some issue when I want to use the Obok DeDRM plugin, I have the message "Unable to open database file" who appears.

As requested, I have launch Calibre in debug mode via the command prompt and thi is the lines about the execution of the Obok plugin : 

Running Obok DeDRM v6.7.0
DEBUG:   16.6 get_device_settings - device_path= F:\
Obok v3.2.4
Copyright © 2012-2016 Physisticated et al.
c:\users\nom of user\appdata\local\temp\tmpv6whq6
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 96, in launchObok
  File "calibre_plugins.obok_dedrm.obok.obok", line 389, in __init__
OperationalError: unable to open database file

Thanks in advance for your time and your work.

I hope you may help me.

Best regards

Pandalf

**Comment by ElleKayEm** [comment]
You have Kobo Desktop on the same machine and user as calibre with Obok DeDRM?  Or you have a Kobo device connect via USB?

**Comment by Pandalff** [comment]
I only have a kobo device connected via USB

**Comment by ElleKayEm** [comment]
You've clicked connect on the Kobo screen and calibre shows the device button on the main menu?  Click the drop down arrow next to that button and choose "Configure this device".  On the right-most tab under Advanced options, check "Attempt to support newer firmware".  Click ok and then restart calibre.  Obok is working for me with my Kobo Forma.

**Comment by Pandalff** [comment]
Yes Calibre see my Kobo :)

I just tried your tips but the result is same.

My Kobo is an Aura ONE

**Comment by ElleKayEm** [comment]
I don't know why it's not working.  You could try installing the Kobo Desktop program.  Or downloading the Adobe Epub via Adobe Digital Editions 2.0.1 and using DeDRM.

**Comment by Pandalff** [comment]
Okay, 

I found where my problem was, my user folder has an accented letter. 

I created a new local account with no accent and everything works.

Thanks for the help :)

**Comment by ElleKayEm** [comment]
Thanks for reporting back about the workaround.  I remember there was previously a similar issue with DeDRM and Kindle for PC books.  Hopefully this bug can be squashed too.

**Comment by Pandalff** [comment]
Okay, 

I found where my problem was, my user folder has an accented letter. 

I created a new local account with no accent and everything works.

Thanks for the help :)
