### ISSUE TITLE
[Solved, Changed to Suggestion] (Calibre Plugin) DRM Not Removed From Amazon Kindle Ebook

### ISSUE THREAD

**Issue by zaptrem** [apprenticeharper/DeDRM_tools#137]
The EBook is successfully imported, but retains its DRM. I tried with two different computers, and both had this problem. Here is the log, with user ID and book name details redacted:

calibre Debug log
calibre 2.68  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 1) && KindleUnpack - The Plugin (0, 81, 2)
devicePixelRatio: 1.0
logicalDpi: 192.0 x 192.0
physicalDpi: 267.368421053 x 267.368421053
Starting up...
Started up in 11.05 seconds with 1 books
DeDRM v6.5.1: Trying to decrypt B00QXKGJ10_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 248
Decrypting Mobipocket 4 ebook: REDACTEDBOOKNAME
Found 0 keys to try after 0.8 seconds
Crypto Type is: 2
DeDRM v6.5.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.1: Looking for new default Kindle Key after 0.8 seconds
searching for kinfoFiles in C:\Users\zaptr\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\zaptr\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString 'REDACTED' and UserName 'REDACTED'
DeDRM v6.5.1: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
DeDRM v6.5.1: Ultimately failed to decrypt after 1.0 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 608, in run
  File "calibre_plugins.dedrm.__init__", line 558, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.1: Ultimately failed to decrypt after 1.0 seconds
Added REDACTEDBOOKNAME to db in: 7.0
Added 1 books in 9.3 seconds
isEncrypted = True

Any idea what went wrong? This was a vanilla unmodified Kindle book I upgraded from a rental to a purchase to deDRM it. It was downloaded using the Kindle for PC application.

**Comment by zaptrem** [comment]
Hm. Turns out the solution was to use the 64 bit version. Maybe it would be useful to display an error message when you try to DeDRM files over a certain number of megabytes suggesting the 64 bit edition.

**Comment by apprenticeharper** [comment]
Too tricky to get right for a minor problem.
