### ISSUE TITLE
Ipublishreader

### ISSUE THREAD

**Issue by cndesu** [apprenticeharper/DeDRM_tools#1370]
DeDRM plug-in could not remove the DRM from the ebook. Ipublishreader is the ebook reader used to decrypt the ebook which is downloaded and stored on my hard drive. Ebook is not in compressed format. Let me know if this is possible. I tried with Calibre 4.23.

**Comment by ElleKayEm** [comment]
Not at this time.  DeDRM handles Amazon, Adobe, and B&N DRM.  Obok deals with Kobo's DRM.
