### ISSUE TITLE
DeDRM isn't working for Azw3 files on Calibre 3.21.0 intalled on Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by verori** [apprenticeharper/DeDRM_tools#1371]
Hello! I rented some books for school for Amazon and need to open them on a different platform than the Kindle Cloud Reader. I downloaded the files from Amazon using the "download and transfer via USB" method. However, I don't own a Kindle device, so I wan to read them using Calibre, but the DRM will not let me open the files. PLEASE HELP! I have exams coming up after Turkey day that I need to study for. Thanks in advance! 
Here is the entire log I got when attempting to add and view the books while Calibre is running on debugging mode:

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 3.21  embedded-python: False is64bit: True
Linux-4.15.0-124-generic-x86_64-with-Ubuntu-18.04-bionic Linux ('64bit', '')
('Linux', '4.15.0-124-generic', '#127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020')
Python 2.7.17
Linux: ('Ubuntu', '18.04', 'bionic')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 3.21  embedded-python: False is64bit: True
Linux-4.15.0-124-generic-x86_64-with-Ubuntu-18.04-bionic Linux ('64bit', '')
('Linux', '4.15.0-124-generic', '#127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020')
Python 2.7.17
Linux: ('Ubuntu', '18.04', 'bionic')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.10] db initialized
[0.10] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[0.58] main UI initialized...
[0.58] Hiding splash screen
Gtk-Message: 21:55:20.056: GtkDialog mapped without a transient parent. This is discouraged.
DeDRM v6.8.0: Trying to decrypt Theory and Practice of Addiction Counseling.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Theory and Practice of Addiction Counseling
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.8.0: Running kindlekey.py under Wine
DeDRM v6.8.0: Command line: 'wine python.exe "/home/verori/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/verori/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
/bin/sh: 1: wine: not found
DeDRM v6.8.0: Found and decrypted 0 key files
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 171, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[15.51] splash screen hidden
[15.51] Started up in 15.51 seconds with 1 books
Added Theory and Practice of Addiction Counseling to db in: 7.6
Added 1 books in 8.1 seconds
Gtk-Message: 21:57:21.755: GtkDialog mapped without a transient parent. This is discouraged.
DeDRM v6.8.0: Trying to decrypt The Essential Counselor.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Essential Counselor
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.8.0: Running kindlekey.py under Wine
DeDRM v6.8.0: Command line: 'wine python.exe "/home/verori/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/verori/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
/bin/sh: 1: wine: not found
DeDRM v6.8.0: Found and decrypted 0 key files
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 171, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Essential Counselor to db in: 4.3
Added 1 books in 4.8 seconds
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Worker Launch took: 0.0452160835266

-------------

Found these instructions on "Removing DRM from rented Amazon azw4 eBook" by ballju	here: https://somethingdifferent.wordpress.com/2016/12/27/removing-drm-from-rented-amazon-azw4-ebook-2/ 
But I have no clue how to implement them:

To make deDRM work with rented Kindle books, you have to open mobidedrm.py and find the lines:

    if val406 != 0:

    raise DrmException(u”Cannot decode library or rented ebooks.”)

Then either comment them out (using #) or remove these two lines. Then deDRM works perfectly with rented eBooks.

**Comment by ElleKayEm** [comment]
From the log:

> DeDRM v6.8.0: Failed to decrypt with error: Cannot decode library or rented ebooks.

These tools are intended for purchased books.  Not gonna help with this.
