### ISSUE TITLE
DeDRM giving error for kindle azw3 drm files on Calibre 4.23 and DeDRM 6.8.0

### ISSUE THREAD

**Issue by BaronOfNothing** [apprenticeharper/DeDRM_tools#1373]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [x ] Code block is used for `the log`.

---

## Title
 Can't convert azw3 files from kindle. 

### DeDRM: `6.8.0`

I downloaded a bunch of books that i got from amazon via the download and transfer via usb and most of them could be imported and converted to epub. But for 2 of the books, i can import them fine but converting gives me the error that its locked by drm. I dont know much about coding but at the bottom of the log i see it say that it says a python function unexpectedly terminated. Ive tried uninstalling and reinstalling both calibre and the plugins but it still throws the same error. Strange thing is when removing and re-adding the other kindle books via a new copy of the azw3 file from the amazon website, they work fine. I can convert those to epub like normal.

## Log

```log
Convert book 1 of 1 (Sherlock Holmes : Complete Collection)
Conversion options changed from defaults:
  output_profile: u'kindle_pw3'
  cover: u'C:\\Users\\rohaa\\AppData\\Local\\Temp\\calibre_0aykck\\yqwbg2.jpeg'
  verbose: 2
  read_metadata_from_opf: u'C:\\Users\\rohaa\\AppData\\Local\\Temp\\calibre_0aykck\\c12h4i.opf'
Resolved conversion options
calibre version: 4.23.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\rohaa\\AppData\\Local\\Temp\\calibre_0aykck\\yqwbg2.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000029C1DA1B248>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x0000029C1DA21A88>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\rohaa\\AppData\\Local\\Temp\\calibre_0aykck\\c12h4i.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\rohaa\AppData\Local\Temp\calibre_0aykck\ricwzn.azw3
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly
  Sherlock Holmes : Complete Collection (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
calibre.ebooks.DRMError: Sherlock Holmes : Complete Collection

```
</details>

**Comment by ElleKayEm** [comment]
Since DRM removal happens when you first add a book to calibre, I can't tell anything from the conversion log.  Let's see an import log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by BaronOfNothing** [comment]
calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && Find Duplicates (1, 8, 3) && Set KFX metadata (from KFX Output) (1, 46, 0) && KFX Output (1, 46, 0) && Quality Check (1, 10, 1) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && Find Duplicates (1, 8, 3) && Set KFX metadata (from KFX Output) (1, 46, 0) && KFX Output (1, 46, 0) && Quality Check (1, 10, 1) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.5518394649 x 81.6428571429
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.45] db initialized
[0.45] Constructing main UI...
[2.25] main UI initialized...
[2.25] Hiding splash screen
[14.01] splash screen hidden
[14.01] Started up in 14.01 seconds with 190 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['Z\xcf\xbdH\xfb\x1b\x13_\xe8\xb0\xb6E5\x97\xc7\x0b\r\n\xe2<\xc9\xd2\\\xb1@\xb9\xed%\xc5&\x14A', 'D:\\Downloads\\Sherlock Holmes _ Complete Collection.azw3']
DeDRM v6.8.0: Trying to decrypt Sherlock Holmes _ Complete Collection.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Sherlock Holmes : Complete Collection
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\rohaa\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Sherlock Holmes : Complete Collection to db in: 1.5
Added 1 books in 2.5 seconds

**Comment by ElleKayEm** [comment]
When you were downloading from the website, did you choose an E-ink Kindle (not a Fire) for the device? And do you have the Kindle's serial number entered into the DeDRM customization?

**Comment by BaronOfNothing** [comment]
yea i only have a kindle paperwhite and i put the serial number into the customization

**Comment by BaronOfNothing** [comment]
well would you look at that, i deleted the serial number and reentered it and it worked. dont know why i didnt try that before :/.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
