### ISSUE TITLE
Commit #1362 breaks ePub decryption when used in Calibre 5

### ISSUE THREAD

**Issue by ableeker** [apprenticeharper/DeDRM_tools#1377]
Commit #1362 changes the last line of function bytesToNumber from 'return total' to 'return long(total)'. This change breaks the decryption of ePubs, because it isn't valid for Python 3, it's only valid for Python 2. According to the documentation, in Python 3 the equivalent of long is int, but you don't have to use that explicitly, as int is default anyway. So this change is probably a good fox for Python 2, but in Python 3 we should use the original code. To make ePub decryption work, this commit could be used for DeDRM 6.8.0, but for the new Python 3 version it should be reverted.

**Comment by fireattack** [comment]
So what's the current state of this project (`master`), in term of Python versions? Hybrid Python 2+3 or just 3? I'm asking because this determines do we want to fix it by using `long` conditionally or simply revert it since we no longer want to support Py2.

**Comment by ElleKayEm** [comment]
From what I understand, the master should concentrate on supporting Python 3 because that is what is required for calibre 5.x.  If you want to use calibre 4.23 or earlier, you can stick with DeDRM 6.8.

**Comment by ableeker** [comment]
I've also read somewhere that apprentice Harper didn't want to try to stay compatible with Python 2.

The commit has been reverted.
