### ISSUE TITLE
DRM removal failure

### ISSUE THREAD

**Issue by infotronico** [apprenticeharper/DeDRM_tools#138]
I'm under Windows 7 64bit, I cannot remove the DRM from my Amazon ebooks. I'm using Calibre version 2.69.
My device is a Kindle Paperwhite 

Thi is my debug content:

calibre Log di debug
calibre 2.69  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 1)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.0 x 71.8867924528
Starting up...
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
Storage number map:
{(7L, 0L): [(3L, 'C')], (7L, 1L): [(2L, 'D')], (7L, 2L): [(1L, 'G')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\90D42201407408C5&0: StorageDeviceNumber(type=7L, number=2L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=2304)
{u'drive_letters': ['G'],
 u'pnp_id_map': {'G': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#90d42201407408c5&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'G': (2L, 1L)}}
Job: 1 Recupera informazioni sul dispositivo started
DeviceJob: 1 Recupera informazioni sul dispositivo done, calling callback
DeviceJob: 1 Recupera informazioni sul dispositivo callback returned
Job: 2 Imposta informazioni sulla biblioteca started
DeviceJob: 2 Imposta informazioni sulla biblioteca done, calling callback
DeviceJob: 2 Imposta informazioni sulla biblioteca callback returned
Job: 3 Recupera la lista dei libri del dispositivo started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: G:\ documents
DEBUG:    0.1 USBMS: scan from root False G:\documents
Job: 2 Imposta informazioni sulla biblioteca finished
Nessun dettaglio disponibile.
Job: 1 Recupera informazioni sul dispositivo finished
Nessun dettaglio disponibile.
DEBUG:    0.4 USBMS: count found in cache: 45, count of files in metadata: 45, need_sync: False
DEBUG:    0.4 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.4 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.4 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Recupera la lista dei libri del dispositivo done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 45
DeviceJob: set_books_in_library finished: time= 0.00699996948242
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Recupera la lista dei libri del dispositivo callback returned
Started up in 7.25 seconds with 192 books
Job: 3 Recupera la lista dei libri del dispositivo finished
Nessun dettaglio disponibile.
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['p\xa0\xd3|\xeey\xaf?6\x12\x16\xd5\x8d\xbaS\xb3dWP\xf9Dy\x1f\x86A\x18\xa9)\xd1\xc4\xab\xee', 'C:\\Users\\scheggia\\Downloads\\Medos (Italian Edition) - Tironi Conchita.azw3']
DeDRM v6.5.1: Trying to decrypt Medos (Italian Edition) - Tironi Conchita.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: MÃ¨dos (Italian Edition)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\scheggia\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.1: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 608, in run
  File "calibre_plugins.dedrm.__init__", line 558, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.1: Ultimately failed to decrypt after 0.1 seconds
Added Mèdos (Italian Edition) to db in: 1.0
Added 1 books in 1.5 seconds
Worker Launch took: 0.19000005722

Thanks

**Comment by ElleKayEm** [comment]
For books from your Paperwhite, you need to enter its serial number into the plugin customization.  You could also install Kindle for PC and import your books from there.

**Comment by infotronico** [comment]
Perfect, so it works !!!
Thanks a lot
