### ISSUE TITLE
Download & transfer via USB

### ISSUE THREAD

**Issue by happyinaz00** [apprenticeharper/DeDRM_tools#139]
Download & transfer via USB has been working in Calibre for as long as I can remember. It recently stopped working for all books using this process. I verified Serial Number entered. Removed serial number and readded. Entered a second Kindle serial number and tried using it unsuccessfully. Verified Kindle for PC works successfully. I updated Calibre 2.69 (64bit), DeDRM (6.5.1). 

Note: downloaded file to Kindle folder and was not downloaded nor available using Kindle for PC.

Thank you

calibre Debug log
calibre 2.69 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 1)
devicePixelRatio: 1.0
logicalDpi: 144.0 x 144.0
physicalDpi: 71.9595278246 x 72.0810810811
Starting up...
Started up in 4.78 seconds with 122 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x8d\x86LM?\xa4\x81\x1bq\xeb\xb0s"\xa3\xf6\xd4\xad\xb7>\xae\xc9\x13\xca\xf5\xec\xa366\xc1\x03\xb4`', 'C:\\Users\\xxx\\Documents\\My Kindle Content']
DeDRM v6.5.1: Trying to decrypt xxx.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: xxx
Found 8 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.1: Failed to decrypt with error: No key found in 8 keys tried.
DeDRM v6.5.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\xxx\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\xxx\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '371662124' and UserName '706c6163686e6f'
DeDRM v6.5.1: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: xxx
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.1: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 608, in run
  File "calibre_plugins.dedrm.__init__", line 558, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.1: Ultimately failed to decrypt after 0.1 seconds
Added xxx to db in: 0.2
Added 1 books in 1.7 seconds
Worker Launch took: 0.113999843597

**Comment by ElleKayEm** [comment]
Still working for me, and I haven't heard any other reports.  The best way to make absolutely sure you have the serial number entered correctly is to copy and paste it from the "Manage your content and devices" page.  Also, it only works for E-ink Kindles.

**Comment by happyinaz00** [comment]
This has worked for me for as long as I have owned my Kindle until just recently. The serial number is definitely correct. Yes, I did a copy from my online account. I saw other posts stating it only works for E-ink Kindles, which shocks me because it has worked for me using Download & transfer via USB as long as I have owned my Fire until recently.

**Comment by apprenticeharper** [comment]
As far as I know, DRM removal for Kindle Fires has never worked. Perhaps you never happened to buy a DRMed book before.
