### ISSUE TITLE
DeDRM Failures in Calibre

### ISSUE THREAD

**Issue by NeilS007** [apprenticeharper/DeDRM_tools#1391]
I hesitate to leave anything here as I am not very technically knowledgeable. But I very much need to appeal here for some help. I have been using Calibre and the DeDRM plugin for years and years and years. But I went and I downloaded and installed the new Plugin in to the new Calibre and now nothing works for me. I have looked over the issues here now and only wish I had thought to do that before "upgrading." But this is the very first time I have had a failure. What is happening is I have Mac Calibre 5.6 and I get the DRM Locked error message now whenever I add a downloaded book which I have purchased on opening the ebook viewer. If I go to Calibre Plugins I see in the File Type area that I have the DeDRM 7.0.0 plugin installed. I understand, now, that is an unfinished beta? I am, btw, running Mac Calibre on my iMac with Big Sur 11.0.1 System. What might I try to recover from this error of mine? I really appreciate any help and thank you.

**Comment by ElleKayEm** [comment]
What type of book and how are you getting it?

**Comment by NeilS007** [comment]
Hi-  It is an azw3 book from Amazon. I go into my manage content area and I download it for use in my Paperwhite 2 the serial number of which is in the plugin. It reads into Calibre in that the book cover appears but the DRM Lock is left intact. Thanks!

**Comment by ElleKayEm** [comment]
If you have the serial number entered correctly into the eInk Kindle ebook section of DeDRM's customization and the Paperwhite 2 is the device you chose when downloading from the website, it should work when adding the book to calibre.  If not, then it may be something still needs work in the beta DeDRM.  In that case, uninstall calibre 5.6 and install [calibre 4.23](https://download.calibre-ebook.com/4.23.0/).  Install [DeDRM 6.8.1](https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.1).  Remember to unzip DeDRM_tools_6.8.1.zip
and load DeDRM_Plugin.zip.  Restart calibre.  Re-add your book.

**Comment by NeilS007** [comment]
Still failed. I also tried an older Kindle and that failed as well. I installed Calibre 4.23. Then I downloaded DeDRM 6.8.1 from your link. That will not load and returns a "py" tytpe error code thus;

calibre, version 4.23.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/Users/neilshapiro/Downloads/DeDRM_tools_6.8.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.23  embedded-python: True is64bit: True
Darwin-20.1.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.1.0', 'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 194, in load
  File "site-packages/calibre/customize/zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'/Users/neilshapiro/Downloads/DeDRM_tools_6.8.1.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
As I said, unzip DeDRM_tools_6.8.1.zip and load DeDRM_Plugin.zip.

**Comment by NeilS007** [comment]
Yep, sorry about that. It now has Calibre 4.23 working fine for me. Thanks for the help! So I guess I should wait until the reports come in of a totally working Calibre/PLug-in combo? I don't think I am using any of the new things anyway.

**Comment by ElleKayEm** [comment]
Yes, that's what I plan on doing.  If you're all set, you can close the issue.

**Comment by NeilS007** [comment]
Closing and thanks again!
