### ISSUE TITLE
Calibre 5.6.0 epub with not working with DeDRM_plugin_7.0.0b3 in Windows 10

### ISSUE THREAD

**Issue by DanRinkevich** [apprenticeharper/DeDRM_tools#1395]
Title
Calibre 5.6.0 epub with not working with DeDRM_plugin_7.0.0b3 in Windows 10

## Log
Here is the calibre debug file:
C:\WINDOWS\system32>calibre-debug -g
calibre 5.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.36866359447005 x 112.88888888888889
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.70] splash screen shown
[0.70] Initializing db...
[0.73] db initialized
[0.73] Constructing main UI...
[2.92] main UI initialized...
[2.92] Hiding splash screen
Starting QuickView
[3.55] splash screen hidden
[3.55] Started up in 3.55 seconds with 9 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xcf\xd8\x1dt\xd0R\xd3I\x8f[\xb3\x8d[M\xd1\n\x8d9\xbf\xca\\\xae^4\x8bs\xd2\x12A\xc9\x06:', b'C:\\Users\\n\\Documents\\My Digital Editions\\Camino Winds.epub']
DeDRM v7.0.0: Trying to decrypt Camino Winds.epub
DeDRM v7.0.0: Verifying zip archive integrity
DeDRM v7.0.0: Camino Winds.epub is a secure Adobe Adept ePub
DeDRM v7.0.0: Trying Encryption key default_key
Could not decrypt il1mhod8.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 414, in decryptBook
TypeError: object of type 'int' has no len()

DeDRM v7.0.0: Failed to decrypt with key default_key after 0.7 seconds
DeDRM v7.0.0: Looking for new default Adobe Digital Editions Keys after 0.7 seconds
DeDRM v7.0.0: Exception when getting default Adobe Key after 0.7 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 352, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 360, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 340, in CryptUnprotectData
calibre_plugins.dedrm.adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v7.0.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Camino Winds to db in: 0.2
Added 1 books in 2.4 seconds

**Comment by ElleKayEm** [comment]
I would guess this is because retrieval of Adobe keys still needs work in DeDRM 7.  Was this downloaded with ADE authorized with your Adobe ID on the same machine and user as calibre with DeDRM?  Another thing to check is if it can be opened with ADE 2.0.1 authorized to the same Adobe ID.  If so, then you should be able to decrypt it with DeDRM 6.8.x and calibre 4.23.

**Comment by DanRinkevich** [comment]
Yes, ADE was installed on the same machine and authorized, then the book was downloaded.  I will install ADE 2.0.1 and try.

**Comment by DanRinkevich** [comment]
ADE 2.0.1 would not open it.  I got an error check activation message.  I tried a to download and open fresh downloaded book.  ADE 2.0.1 is showing that it is using the same authorization.

**Comment by ElleKayEm** [comment]
Well, that could be a problem with Adobe authorization or it could be hardened Adobe DRM that DeDRM can't remove.  I'd give DeDRM 6.8.x installed in calibre 4.23 a try anyway.

**Comment by ableeker** [comment]
That error is a bit odd, something seems to be not quite right with the book key. An epub is actually a zip archive. If you open it, ther should be a file /META-INF/right.xml. Is it there? And, if it does exist, it should contain a tag encryptedKey. This is the base64 encoded book key. Does it exist, and if so, what is it?

**Comment by DanRinkevich** [comment]
Thank you so much for your suggestions.  I removed everything including unauthorizing the computer.  I even ran CCleaner to remove any extra junk left behind and even deleted the Digital Editions directory in Documents.   I now have:ADE: 2.0.6Calibre: 4.23 (32bit)DeDRM: 6.8.1 The book opens in ADE.  On Calibre it is still failing to decrypt.  Here is the log: C:\WINDOWS\system32>calibre-debug -gcalibre 4.23  embedded-python: True is64bit: FalseWindows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')32bit process running on 64bit windows('Windows', '10', '10.0.18362')Python 2.7.16+Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')Interface language: NoneSuccessfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)Turning on automatic hidpi scalingdevicePixelRatio: 2.0logicalDpi: 96.0 x 96.0physicalDpi: 112.368663594 x 112.888888889Using calibre Qt style: True[0.00] Starting up...[0.00] Showing splash screen...[0.61] splash screen shown[0.61] Initializing db...[0.62] db initialized[0.62] Constructing main UI...DEBUG:    0.0 obok::utilities.py - loading translationsDEBUG:    0.0 obok::dialogs.py - loading translationsDEBUG:    0.0 obok::config.py - loading translationsDEBUG:    0.0 obok::action_err.py - loading translations[2.88] main UI initialized...[2.88] Hiding splash screen[3.56] splash screen hidden[3.56] Started up in 3.56 seconds with 8 booksstdout+stderr from file dialog helper: ['', '']piped data from file dialog helper: ['Ez\xbd9ES\xeap\x99\x87\xbb\x90J\xf9\xd3\xc0\xb8rJ\xac\x87\xbb\x80\xecw\x17\x13\xfc\xd4\x11\xe5\xb7', 'C:\\Users\\n\\Documents\\My Digital Editions\\Camino Winds.epub']DeDRM v6.8.0: Trying to decrypt Camino Winds.epubDeDRM v6.8.0: Verifying zip archive integrityDeDRM v6.8.0: Camino Winds.epub is a secure Adobe Adept ePubDeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.1 secondsDeDRM v6.8.0: Exception when getting default Adobe Key after 0.1 secondsTraceback (most recent call last):  File "calibre_plugins.dedrm.__init__", line 351, in ePubDecrypt  File "calibre_plugins.dedrm.adobekey", line 379, in adeptkeys  File "calibre_plugins.dedrm.adobekey", line 359, in CryptUnprotectDataADEPTError: Failed to decrypt user key key (sic)DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.mdRunning file type plugin DeDRM failed with traceback:Traceback (most recent call last):  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins  File "calibre_plugins.dedrm.__init__", line 637, in run  File "calibre_plugins.dedrm.__init__", line 408, in ePubDecryptDeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.mdAdded Camino Winds to db in: 0.2Added 1 books in 2.0 seconds Any suggestions?      Dan RinkevichFrom: ElleKayEmSent: Wednesday, December 2, 2020 11:18 AMTo: apprenticeharper/DeDRM_toolsCc: DanRinkevich; AuthorSubject: Re: [apprenticeharper/DeDRM_tools] Calibre 5.6.0 epub with not working with DeDRM_plugin_7.0.0b3 in Windows 10 (#1395) Well, that could be a problem with Adobe authorization or it could be hardened Adobe DRM that DeDRM can't remove. I'd give DeDRM 6.8.x installed in calibre 4.23 a try anyway.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DanRinkevich** [comment]
Ableeker,
I think I destroyed the evidence on the epub.  It wouldn't open in ADE so I freshened it up, and deleted the old one.  The new file opens in ADE 2.0.6.   

The tag in the new epub file is:
<encryptedKey keyInfo="user">dZq/0OcoCBHEiRr1t27Q3y9FLfw40Z/SUU9jD66k9TMI+Svf4TUAYPEFPn16iY6VJfZVFHsVTBxXLDvMZqghYDdjwXMFJAuhw9cnaBD9u1ohgrswN7MAecCIVef7PaYwQW3i065NyrbPh13qq4UjIXW16tRdm+/NH350aQ9H6V0=</encryptedKey>

Unfortunately I have no idea what it was in the previous file at this point.

**Comment by ableeker** [comment]
That new key looks fine, it's base 64 encoded, it's the right length, and it's recognised by DeDRM. But DeDRM 4.8.0 is unable to decrypt the user key that should be available on the computer. The error in adobekey.py points to code that deals with ADE activation. In fact that very line 359 should have raised the error "Adobe Digital Editions not activated", because it's unable to read the Registry key HKEY_CURRENT_USER\SOFTWARE\Adobe\Adept\Device\key. That's the user key.

It looks to me something went wrong activating the computer. When it's activated properly, DeDRM 6.8.0 should decrypt the book just fine. There's even a good chance that 7.0.0 would work as well.

**Comment by DanRinkevich** [comment]
ableeker,
Thank you.  The registry shows for \HKEY_CURRENT_USER\Software\Adobe\Adept\Device:
  (Default) - REG_SZ - not set
  key - REG_BINARY - 01 00 00 00 d0 8c 9d 9f 01 15 d1 11 8c 7a 00 c0 4f...
  username - REG_SZ - n

Is there a way that I could know that they are correct?

**Comment by ableeker** [comment]
Hm, so that key exists... It looks fine as well. Actually, my key is 264 bytes long, but it starts exactly the same way:

01 00 00 00 d0 8c 9d df 01 15 d1 11 8c 7a 00 c0 ...

Odd...

Hehe, I just found on the Adobe forum some topic with the advice to do exactly what you've just done.

**Comment by ElleKayEm** [comment]
Ah, I was just coming to give you the link to [this page](https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html) with instructions on de-authorizing, deleting the registry key, and re-authorizing.  Glad you got it sorted.  If you're all set, you can close the issue.

**Comment by DanRinkevich** [comment]
Thanks for your help.  I upgraded back up to:
  Calibre: 5.6.0
  DeDRM: 7.0.0b3
  ADE: '4.5.11.187303'
And it's working great!

**Comment by ElleKayEm** [comment]
Just be aware that it's possible to get Adobe DRM that can't be removed when using ADE 3 and up.  Glad to hear DeDRM 7 is working for Adobe epubs.
