### ISSUE TITLE
Only one key retrieved

### ISSUE THREAD

**Issue by skandragon** [apprenticeharper/DeDRM_tools#14]
When fetching the key from the B&N site, only one key is retrieved, even if multiple keys are used for different books.

I know of no work-around; I just edited the JSON config to add the additional keys, retrieved from a nook via the cchashdata.db file.

**Comment by ElleKayEm** [comment]
There is only one key to retrieve for new downloads.  Any additional keys saved on the nook are for books opened before your key changed to the current one.

**Comment by skandragon** [comment]
Gotcha.  I did find a way to retrieve the older keys from the rooted nook, so this isn't a serious problem.
