### ISSUE TITLE
b4 no decrypt from Windows Kindle v1.17

### ISSUE THREAD

**Issue by truthsword** [apprenticeharper/DeDRM_tools#1404]
Running Linux Calibre 5.6, with beta 4 plugin. Imported azw from Kindle for Windows 1.17; book will not open due to DRM.

![](https://i.imgur.com/4sh4pwH.png)

**Comment by ElleKayEm** [comment]
Let's see an import log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by truthsword** [comment]
That's hard to do running from Docker.

**Comment by ElleKayEm** [comment]
If DeDRM can't retrieve the key automatically, then you could try running kindlekey.py where you have Kindle for PC installed and importing the key manually into calibre.

**Comment by truthsword** [comment]
I didn't realize that a key was required from the app itself. I thought the azw file coming from the proper Kindle of PC version was all that was necessary. 

As it happens, I have Calibre 4.2.3 installed on a PC with a working decrypt plugin, and so I exported the k4i key from the PC Calibre, and then imported it into the v5 Docker plugin, and tested a few imports successfully. Now I can remove the PC version.

Thank you!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
