### ISSUE TITLE
7.0.0b4 works calibre port 5.3 not calibre 64bit 5.6

### ISSUE THREAD

**Issue by ebethn** [apprenticeharper/DeDRM_tools#1409]
No coding experience but I did run debug logs to see why same book dedrm'd in calibre portable 5.3 but not calibre 64bit 5.6. Both on windows 10. Updated both calibre versions to have same plugin in case part of problem.  Downloading as USB for eInk kindle, double checked eInk id numbers in both calibre. 

This appears to be the pertinent line from the failed debug log, but I've attached both logs just in case. If the logs didn't attach let me know and I'll redo. Thanks, Beth

DeDRM v7.0.0: Failed to decrypt with error: a bytes-like object is required, not 'str'

[cal port 5 3 debug.docx](https://github.com/apprenticeharper/DeDRM_tools/files/5660722/cal.port.5.3.debug.docx)
[fail cal 5 6 64bit 1 plug debug.docx](https://github.com/apprenticeharper/DeDRM_tools/files/5660724/fail.cal.5.6.64bit.1.plug.debug.docx)

In case it's easier to see: 
THIS IS THE FAILED DECRYPT
calibre Debug log
calibre 5.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Failed to initialize plugin: 'C:\\Users\\ebeth\\AppData\\Roaming\\calibre\\plugins\\Goodreads.zip'
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Count Pages (1, 11, 0) && Obok DeDRM (6, 7, 0)
calibre 5.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Count Pages (1, 11, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.81139489194499 x 95.9160839160839
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.70] splash screen shown
[0.70] Initializing db...
[0.72] db initialized
[0.72] Constructing main UI...
[1.74] main UI initialized...
[1.74] Hiding splash screen
Starting QuickView
SMART_DEV (   0.00:  0.002) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.35:  0.838) _startup_on_demand listening on port 9090
SMART_DEV (   1.40:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.44:  0.000) _startup_on_demand broadcast socket listening on port 54982
[3.42] splash screen hidden
[3.42] Started up in 3.42 seconds with 3 books
SMART_DEV (   2.49:  1.009) run All IP addresses {'{C1340DE0-F48D-42F6-8443-287E1B8C94C5}': [{'addr': '192.168.1.6', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}], '{79E74102-D16F-11E7-B022-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xfd\x88Gh\x86\xcbr\x18E!\xe6\xb6[\xc2\x07,\xf1ob\x92\x04h\xf2\xe0\xf8\x8e\xb57\xac3h\xb4', b'C:\\Users\\ebeth\\Downloads\\Discordia (The Elementals Book 0).azw3']
DeDRM v7.0.0: Trying to decrypt Discordia (The Elementals Book 0).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Discordia (The Elementals Book 0)
Found 18 keys to try after 1.5 seconds
Crypto Type is: 2
DeDRM v7.0.0: Failed to decrypt with error: a bytes-like object is required, not 'str'
DeDRM v7.0.0: Looking for new default Kindle Key after 1.5 seconds
searching for kinfoFiles in C:\Users\ebeth\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.0.0: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 449, in processBook
  File "calibre_plugins.dedrm.mobidedrm", line 196, in checksumPid
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 627, in run
  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Failed to initialize plugin: 'C:\\Users\\ebeth\\AppData\\Roaming\\calibre\\plugins\\Goodreads.zip'

THIS IS THE SUCCESSFUL DECRYPT
calibre Debug log
calibre 5.3 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Count Pages (1, 11, 0)
calibre 5.3 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Count Pages (1, 11, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.81139489194499 x 95.9160839160839
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.72] splash screen shown
[0.72] Initializing db...
[3.25] db initialized
[3.25] Constructing main UI...
[5.61] main UI initialized...
[5.61] Hiding splash screen
Starting QuickView
[8.31] splash screen hidden
[8.31] Started up in 8.31 seconds with 22971 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xd1\xe1\x11\x84\xa6j\x1f\xc5\x1d\xdc5\xa6\xee-\x93\xa98\xe4\xb3x\x8b1\x98~\n2\xd8\x1d;\xcb\x8a.', b'C:\\Users\\ebeth\\Downloads\\Discordia (The Elementals Book 0).azw3']
DeDRM v7.0.0: Trying to decrypt Discordia (The Elementals Book 0).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Discordia (The Elementals Book 0)
Found 4 keys to try after 2.6 seconds
Crypto Type is: 2
File is encoded with PID b'RZYhRX4zPH'.
Decrypting. Please wait . . . done
Decryption succeeded after 2.6 seconds
DeDRM v7.0.0: Finished after 2Added Discordia (The Elementals Book 0) to db in: 0.6
Added 1 books in 10.1 seconds
toolbar_triggered - mode= Estimate
toolbar_triggered - mode= Estimate
toolbar_triggered - download_source= None
get_library_config - start
get_library_config - start
QueueProgressDialog - self.input_order= ['epub', 'azw3', 'mobi', 'lit', 'prc', 'fb2', 'html', 'htm', 'xhtm', 'shtml', 'xhtml', 'zip', 'docx', 'odt', 'rtf', 'pdf', 'txt']
For book 'Discordia (The Elementals Book 0)', using format azw3
Worker Launch took: 0.1562187671661377
Job: 0 Count Page/Word Statistics finished
Count Page/Word Statistics	do_count_statistics - book_path=C:\Users\ebeth\AppData\Local\Temp\calibre_6mhnfart\y12vj5qv_count_pages\39264.azw3, pages_algorithm=0, page_count_mode=Estimate, statistics_to_run=['PageCount', 'WordCount'], custom_chars_per_page=1500, icu_wordcount=True	do_count_statistics - job started for file book_path=C:\Users\ebeth\AppData\Local\Temp\calibre_6mhnfart\y12vj5qv_count_pages\39264.azw3	-------------------------------	Logfile for book ID 39264 (Discordia (The Elementals Book 0))		Method of counting _page_count_mode=Estimate _download_sources=[]		results= {'PageCount': 49, 'WordCount': 11988}		Found 49 pages		Found 11988 words	39264
		do_statistics_for_book:  C:\Users\ebeth\AppData\Local\Temp\calibre_6mhnfart\y12vj5qv_count_pages\39264.azw3 0 Estimate [] ['PageCount', 'WordCount'] 1500 True
			Estimated accurate page count
			  Lines: 1400  Divs: 201  Paras: 451
			  Accurate count: 45  Fast count: 49
			Page count: 49
			Word count using icu_wordcount - trying to count_words
			Word count - used count_words: 11988
			Word count: 11988
		
About to refresh GUI - book_ids_to_update= [39264, 39264]

**Comment by apprenticeharper** [comment]
There seems to be some error in reading the existing preferences. Probably an encoding issue again, and may be tricky to find. And once found, may be tricky to reproduce. 

But thanks for the report. It's useful to know that there's a problem there. Perhaps someone will have a go at finding and fixing it.

**Comment by camhorn** [comment]
Similar issue, Mac Big Sur, DeDrm 7.0.0b4, calibre 5.7.2:

> DeDRM v7.0.0: Failed to decrypt with error: a bytes-like object is required, not 'str'
> DeDRM v7.0.0: Looking for new default Kindle Key after 0.1 seconds
> Found k4Mac kinf2018 file: /Users/camhorn/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
> trying username  b'camhorn'  on file  /Users/camhorn/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
> trying IDString: b'092206b493ce'
> trying IDString: b'1dac2fb4730e'
> trying IDString: b'1dac2fb47309'
> trying IDString: b'27b4a47b45e5'
> trying IDString: b'27b4a47b45e4'
> trying IDString: b'27b4a47b45e5'
> trying IDString: b'S1FWNYAG400786'
> Decrypted key file using IDString 'S1FWNYAG400786' and UserName 'camhorn'
> DeDRM v7.0.0: Found 1 new key
> MobiDeDrm v1.0.
> Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
> Decrypting Kindle Format 8 ebook: Choices of One: Star Wars Legends (Star Wars - Legends)
> Got SerialNumber from database default_key_1
> Got UsernameHash from database default_key_1
> Found 4 keys to try after 3.0 seconds
> Crypto Type is: 2
> DeDRM v7.0.0: Ultimately failed to decrypt after 3.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
> Running file type plugin DeDRM failed with traceback:
> Traceback (most recent call last):
>   File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt
>     book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
>   File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
>     mb.processBook(totalpids)
>   File "calibre_plugins.dedrm.mobidedrm", line 449, in processBook
>     if checksumPid(pid[0:-2]) != pid:
>   File "calibre_plugins.dedrm.mobidedrm", line 196, in checksumPid
>     crc = (~binascii.crc32(s,-1))&0xFFFFFFFF
> TypeError: a bytes-like object is required, not 'str'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
>   File "calibre_plugins.dedrm.__init__", line 627, in run
>     decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
>   File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt
>     raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
> calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 3.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
> Added Choices of One: Star Wars Legends (Star Wars - Legends) to db in: 0.0
> Added 1 books in 3.6 seconds

**Comment by ElleKayEm** [comment]
@camhorn 
How was your book downloaded?

**Comment by camhorn** [comment]
Downloaded via Amazon Contents & Devices | Download & transfer via USB targeted to a registered Kindle Keyboard. The file downloaded as "FSDownloadContent" which I manually gave an ".azw3" extension.

**Comment by ElleKayEm** [comment]
Google tells me that "FSDownloadContent" thing may be a Safari bug.  Have you added your Kindle's serial number to DeDRM's customization?

**Comment by camhorn** [comment]
Serial numbers are in and working with Calibre 4 / DeDRM 6.

**Comment by ElleKayEm** [comment]
Ok, thanks, definitely seems like a bug in the beta then.

**Comment by ebethn** [comment]
Working for me now - on windows 10 64bit updated to calibre 5.8.1 and tools 7.0.1, successful with usb downloads for eink kindle books. Continuing to have no problems on calibre portable 5.3 with tools 7.0.0. Thanks. Will close issue if camhorn also resolved.
