### ISSUE TITLE
DeDRM is not working with azw3 files on Calibre 4.23 installed on mac OS 11.0.1

### ISSUE THREAD

**Issue by tos070** [apprenticeharper/DeDRM_tools#1410]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

## Log
<details><summary>Removing DRM from The trainable cat</summary>

```log
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.1.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.1.0', 'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5)
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.1.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.1.0', 'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 125.500001885 x 125.500001885
Using calibre Qt style: True
[0.00] Starting up...
[0.12] Showing splash screen...
[0.84] splash screen shown
[0.84] Initializing db...
[0.94] db initialized
[0.94] Constructing main UI...
[16.70] main UI initialized...
[16.70] Hiding splash screen
[16.70] splash screen hidden
[16.71] Started up in 16.71 seconds with 152 books
DeDRM v6.8.0: Trying to decrypt The Trainable Cat.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Trainable Cat
Found 4 keys to try after 1.1 seconds
Crypto Type is: 2
File is encoded with PID R7GDrdZECG.
Decrypting. Please wait . . . . done
Decryption succeeded after 2.1 seconds
DeDRM v6.8.0: Finished after 2.1 seconds
```
</details>

**Comment by ElleKayEm** [comment]
This log shows a successful decryption.

**Comment by tos070** [comment]
I bought the ebook from Amazon. I downloaded the azw3 file from the "Manage Devices and Content" page of my Amazon account. I can read the book on my kindle and on the Kindle for Mac app. But I cannot remove the DMR and cannot read it in the Calibre Viewer. Although I downloaded and installed 6.8.1 of DeDRM, when I look in Calibre it still displays 6.8.0. I removed and re-installed, but still it shows 6.8.0. I customised the plugin and added under eInk Kindle ebooks, two serial numbers of my two Kindles (one being the 1.30.0 where I have the book

**Comment by tos070** [comment]
I removed and re-added the book and somehow now it works!
But why do I see the 6.8.0 plugin while I just installed the 6.8.1?

**Comment by tos070** [comment]
Thank you, I repeated the whole process and now I can see the MOBI version and I can read it in the Calbre viewer.
But why does Calibre show me that I have the 6.8.0 version of DeDRM? I downloaded and installed version 6.8.1

**Comment by ElleKayEm** [comment]
Harper forgot to update the version number that gets displayed there.  They are aware, and it will probably be corrected at some point.  The only difference between 6.8.0 and 6.8.1 is a fix for Kindle for Mac on Big Sur.

**Comment by tos070** [comment]
Oh, I see thanks.
I also have Kindle for Mac on Big Sur. 
I saw in the customisation of the plugin that the last option is "Kindle for Mac and PC keys” and mine is empty (no key). Should I add a key there? Where can I find it?
(Please excuse my ignorance: why is the plugin needed for Kindle for Mac?
I use the plugin when I buy books with DMR, not necessarily from the Kindle store, so that I can then read them on my e-ink Kindle. When I buy them from the Kindle store, they are of course downloaded to the Kindle and I do not need Calibre. However, I do add the book in Calibre so that I have all the books I bought in one place (Calibre). I hope it makes sense what I am trying to explain..)

**Comment by ElleKayEm** [comment]
DeDRM will automatically retrieve the key if you add a DRM book to calibre which was downloaded from the current installation of Kindle for Mac on the same machine and user.  Each installation of the app has a unique key.

**Comment by tos070** [comment]
> DeDRM will automatically retrieve the key if you add a DRM book to calibre which was downloaded from the current installation of Kindle for Mac on the same machine and user. Each installation of the app has a unique key.

I download the azw3 file from the Amazon site (Devices and Content) and then I manually add it to Calibre. Then I convert it to mobi (I think that in the past DRM was automatically removed by the plug-in when the book was added in Calibre). Is there a more efficient way to do things? How is the Kindle for Mac involved? (I understand that one may want to read a book with this app on the mac, but other than this, how is this app involved in the deDRM process?)

**Comment by ElleKayEm** [comment]
Kindle for Mac is just another way to download Kindle ebooks.  If someone doesn't have an E-ink Kindle, they can can get them that way instead.

If you're all set, you can close the issue.
