### ISSUE TITLE
Unable to remove DRM from Hitchcock/Truffaut

### ISSUE THREAD

**Issue by koberulz** [apprenticeharper/DeDRM_tools#1412]
It's the only AZW4 in my collection and for some reason comes in at over 300MB.

calibre Debug log
calibre 3.36  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && KindleUnpack - The Plugin (0, 82, 3)
calibre 3.36  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && KindleUnpack - The Plugin (0, 82, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[1.87] main UI initialized...
[1.87] Hiding splash screen
[58.86] splash screen hidden
[58.86] Started up in 58.86 seconds with 203 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['8\xc9\x08\xb00^\xb8\xba\xed\xaf\x87\x98\n\xa5Xp\xd16m\xd8\xb3N\xa0\xcb\x17\xb8>K\x97`A\x8d', '[redacted]\\Kindle Content\\B01N52HCQE_EBOK.azw4']
DeDRM v6.8.0: Trying to decrypt B01N52HCQE_EBOK.azw4
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Hitchcock
Got DSN key from database default_key_2
Got DSN key from database default_key
Found 5 keys to try after 3.5 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 5 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 3.5 seconds
searching for kinfoFiles in C:\Users\[redacted]\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\[redacted]\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '539389151' and UserName '6d796e616d65'
DeDRM v6.8.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Hitchcock
Got DSN key from database default_key_1
Found 4 keys to try after 3.8 seconds
Crypto Type is: 2
DeDRM v6.8.0: Ultimately failed to decrypt after 3.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 3.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Hitchcock to db in: 1.7
Added 1 books in 6.0 seconds
isEncrypted = True
Worker Launch took: 0.0899999141693

**Comment by ElleKayEm** [comment]
AZW4 format is a PDF in an Amazon wrapper, and they can be really large files.  I think you'd need to set things up on a system where you can run 64-bit calibre for this one.  You're able to remove DRM from other Amazon books?

**Comment by koberulz** [comment]
I've never had an issue before, across dozens of books.

Why am I not running 64-bit calibre now? I have a 64-bit system.

**Comment by ElleKayEm** [comment]
Then definitely try 64-bit calibre.

**Comment by koberulz** [comment]
How? I would've assumed 64-bit would've been what it installed given I installed it on a 64-bit machine. I'm only on Win7, which limits things, but other than that...and what would be involved in shifting over? Retaining the DeDRM and KindleUnpack plugins, retaining my library, etc?

**Comment by ElleKayEm** [comment]
Two different installers.  You can actually run both on the same machine.  (Although I don't know why you would, but somebody probably has some reason.)

Here's the version recommended to use for Windows 7:  https://download.calibre-ebook.com/3.48.0/

Just install it, and it will use the same library, plugins, etc.

**Comment by koberulz** [comment]
That works.
