### ISSUE TITLE
Can't decrypt anything (Win10/64, Calibre 4.23 , DeDRM v6.8.0)

### ISSUE THREAD

**Issue by Profc13** [apprenticeharper/DeDRM_tools#1416]
Tried to import from kindle-Lib some bookds, no one could be de-crypted...
here are the logs:

C:\WINDOWS\system32>calibre-debug -g
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 118.946341463 x 112.888888889
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.53] splash screen shown
[0.53] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.00] main UI initialized...
[2.00] Hiding splash screen
[2.39] splash screen hidden
[2.39] Started up in 2.39 seconds with 19 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xc2\xf4a\xbfF\xcfP~\xec\xdd\xac\xc5'\xca\x7f%\xcdk\xed\x9e\x9a\xd5\x97\xba\xe4w\xa6\xdf\x8f\x0e\xe4\xdb", 'C:\\Users\\XXX\\Documents\\My Kindle Content\\B0138ZCUWO_EBOK\\B0138ZCUWO_EBOK.azw']
DeDRM v6.8.0: Trying to decrypt B0138ZCUWO_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.8.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\XXX\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\XXX\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '437556393' and UserName '72616c6663'
DeDRM v6.8.0: Found 1 new key
DeDRM v6.8.0: Ultimately failed to decrypt after 8.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 8.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 285, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 0: invalid start byte
Added B0138ZCUWO EBOK to db in: 1.7
Added 1 books in 10.7 seconds

The Surce-Dir looks like:
11.12.2020  23:29               900 amzn1.drm-voucher.v1.b5d236d3-563f-46ce-8590-e7ed10ef43cd.voucher
11.12.2020  23:29           694.352 B0138ZCUWO_EBOK.azw
12.12.2020  00:13               232 B0138ZCUWO_EBOK.mbpV2
11.12.2020  23:29           170.676 CR!JP9P5K72KX2C35WYXHFJEADTK9SK.azw.md
11.12.2020  23:29            22.995 CR!ZT4J5MK2E51VB2S51EEW71P2CYVX.azw.res
Attention: the file *.mbpV2 is hidden (changed the Attriubtes, so we can see it)
Any Ideas?

Thanks,
ProfC13

**Comment by lnxme** [comment]
Have you read the section "Recent Changes to Kindle for PC/Kindle for Mac" at the FAQ URL listed in the error messages? Not  KFX files can be decrypted currently.

What version of Kindle For PC are you using to get the ebook from Amazon?

Also do you have the KFX Input plugin installed in Calibre as you are trying to decrypt a KFX file so need to have software to handle them?

**Comment by ElleKayEm** [comment]
For KFX files, you'll need to install the KFX Input plugin and use Kindle for PC 1.26 or earlier.  Alternatively, disable KFX downloads or use Kindle for PC 1.17 (which doesn't permit KFX downloads.)  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Profc13** [comment]
Thanks!
gone back to kindle 1.17 (version bevor was 1.30, disable render-test.exe won't work), deleted hole contents and started from scratch. For now it works...

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
