### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by Juejo** [apprenticeharper/DeDRM_tools#142]
Everything is installed according to the explanations provided, however I cannot convert an ebook with Calibre and the respective plugin. I bought the book for the Kindle pc reader. I do have the hardcopy of the book as well but i wanted to convert the book to pdf to be able to make notes directly on a tablet pc.
I use an Intel i7 with Win 10 64 bit to do the conversion.
As described in the Issues section of the website I started Calibre in debug mode to obtain the log file, which is posted here. 
Any comments and hints welcome as to why this is not working.
Many thanks
Juejo
[tmp46mnrt.txt](https://github.com/apprenticeharper/DeDRM_tools/files/520491/tmp46mnrt.txt)

**Comment by ElleKayEm** [comment]
The book needs to be downloaded to an installation of Kindle for PC that is on the same computer and user as calibre.

**Comment by Juejo** [comment]
Dear ElleKayEm, that helped. It works. Many thanks! Rgds Juejo
