### ISSUE TITLE
Can't import bulk and remove DRM but can individually

### ISSUE THREAD

**Issue by eldudemeister** [apprenticeharper/DeDRM_tools#1420]
Hi, so I am trying to import 217 kindle ebooks into Calibre. If I bulk import all of them the DRM does not get removed, but if I import each one individually (having downloaded from Kindle Widows App), it removes the DRM. Am I missing something to be able to do it in bulk?

**Comment by ElleKayEm** [comment]
That's going to overwhelm it.  Try it in smaller batches.  Maybe 20 at a time.

**Comment by eldudemeister** [comment]
Think that’s worked, thanks.
