### ISSUE TITLE
None DeDRM versions (>=7.0.0b1) are working on Kindle (1.24.3) file conversion with Calibre 5.7.2

### ISSUE THREAD

**Issue by crobertoc723** [apprenticeharper/DeDRM_tools#1426]
### DeDRM: 7.0.0b1, 7.0.0b2, 7.0.0b3, 7.0.0b4

When I try to convert azw files to pdf, pops up a message box saying this is a Amazon KFX file and it can't be processed.
![image](https://user-images.githubusercontent.com/64986496/102224329-963ca100-3ec4-11eb-9c1e-07511313f8ad.png)

**Comment by ElleKayEm** [comment]
I don't know if DeDRM 7 is working on KFX files yet.  See method 2 at this post to disable kfx downloads:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by crobertoc723** [comment]
Thannnnnnnnnnnnnnnnnnnnnnnk youuuuuu! I worked!!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
