### ISSUE TITLE
Failed De-DRM of Amazon.com rental AZW on Windows 10, 64 bit

### ISSUE THREAD

**Issue by andrasfuchs** [apprenticeharper/DeDRM_tools#143]
I have just rented a book for a month on amazon.com. I downloaded it with Kindle for PC (1.17.1), imported into Calibre (2.70, Windows 64bit), and got an error with the following log.

This is the link to the book: https://www.amazon.com/dp/B00F5TLPHI

calibre Debug log
calibre 2.70 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 2)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 69.6685714286 x 70.3384615385
Starting up...
Started up in 22.43 seconds with 5 books
DeDRM v6.5.2: Trying to decrypt B00F5TLPHI_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Astronomical Spectroscopy for Amateurs (The Patrick Moore Practical Astronomy Series)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.2: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.5.2: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Andras\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Andras\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2697838953' and UserName '416e64726173'
DeDRM v6.5.2: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Astronomical Spectroscopy for Amateurs (The Patrick Moore Practical Astronomy Series)
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.2: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 161, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.3 seconds
Added Astronomical Spectroscopy for Amateurs (The Patrick Moore Practical Astronomy Series) to db in: 0.2
Added 1 books in 1.8 seconds
Worker Launch took: 0.200000047684

**Comment by ElleKayEm** [comment]
As you see in the log:
"Cannot decode library or rented ebooks."
