### ISSUE TITLE
How to decrypt with Kindle and Linux

### ISSUE THREAD

**Issue by merrpink** [apprenticeharper/DeDRM_tools#1432]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

As I don't have Windows and am trying to avoid the whole Wine thing, I downloaded a book (for USB) from my phone kindle app in AZW3 format to my laptop. I then imported it into Calibre but it told me that the book is DRM'd and can't open it. 

According to Apprentice Alf’s Blog, he says DO NOT UNZIP the downloaded tools, so I imported the whole thing into Calibre plugins, but it is not working.

I also tried connecting my Kindle device to my laptop and Calibre read it fine, but when I import books, they are not decrypted. Is it possible to de_DRM directly from my Kindle device connected to Calibre on my laptop? Please help with what I am doing wrong, and thanks for your work.

**Comment by ElleKayEm** [comment]
Books from Android or iOS Kindle apps can't be decrypted.  The other alternative besides Kindle for PC/Mac is to get the books from the website using the "download & transfer via usb" option for an E-ink Kindle (not a Fire).  Add the Kindle's serial number to DeDRM's customization.

**Comment by merrpink** [comment]
@ElleKayEm thanks for your reply. I did "download and transfer via usb" but I selected my Android device in the devices dropdown. I will try it again choosing the kindle device from the dropdown. Does that give me a different file? The file I got the first time was an AZW3. Please tell me how to add the Kindle's serial number to DeDRM's customization. Also, is it possible to De_DRM directly when importing from Kindle device (not fire) to Calibre on laptop?

**Comment by merrpink** [comment]
@ElleKayEm I figured out how to add the Kindle's serial number to the customization. However, there was also a section for "Kindle for Android ebooks." What is that for?

**Comment by merrpink** [comment]
@ElleKayEm It is working now! The solution was my Kindle serial number. Strange how none of the tutorials talk about that. But I am interested if there is a way for Linux users without a Kindle device (as many use the mobile app). So, I am curious, what is the "Kindle for Android ebooks" section in the DeDRM customization? You said that books from Android or iOS apps can't be decrypted, so I am curious what this is.

**Comment by ElleKayEm** [comment]
It was once possible to extract the Kindle for Android key from a backup file.  But Amazon stopped allowing the creation of that backup file.

**Comment by merrpink** [comment]
Ok thanks

**Comment by ElleKayEm** [comment]
As for books directly from an E-ink Kindle, this will only work for non-KFX format books.  For the most part, you'll only get those on the older Kindles which can't handle the newer format.  If you don't have a Kindle device, the only other option right now is Kindle for PC/Mac.

If you're all set, you can close the issue.
