### ISSUE TITLE
Do I need obok for Kobo books?

### ISSUE THREAD

**Issue by merrpink** [apprenticeharper/DeDRM_tools#1433]
Hi, I'm running Calibre 5.7.2 on Ubuntu 20.10 and a Kobo desktop from 2019 in Wine because the current download button for desktop on their site doesn't work. This desktop works and I can read my books in it, but I cannot figure out where the books are to point Calibre to them. They are not where I expected them in:

`.wine/drive_c/users/me/Local Settings/Application Data/Kobo/Kobo Desktop Edition`

 Also, I cannot figure out if I need to separately install the Obok package or not in addition to DeDRM v7.0.0b4. I have also downloaded Adobe Digital Editions 4.5 in Wine but it won't run for now so trying to do this with the Kobo desktop app.

Thank you.

**Comment by ElleKayEm** [comment]
Obok is what you need for books from Kobo Desktop or a Kobo ereader.  I don't think it has been updated to Python 3 yet though.  So you would need calibre 4.23.

You might want to try Adobe 2.0.1, but I'm not familiar with getting that running under Wine.

**Comment by merrpink** [comment]
Ok thanks. Please give me the link to the current obok release. I can only find [this](https://github.com/apprenticeharper/DeDRM_tools/tree/master/Obok_plugin/obok) which I can see is written in Python 3, so should be ok for Calibre latest. However, where is the "official" download link posted? 

Also, how to point Calibre to the Kobo books inside Wine, or does the obok plugin do that automatically? 

Thanks

**Comment by ElleKayEm** [comment]
Same as the latest official (non-beta) release of DeDRM:  https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.1

I don't know if it will find the books automatically on Linux.  If not, you should be able to go into the plugin customization and set the directory.

**Comment by lnxme** [comment]
@merrpink 
If you build the master version of obok from Github, it does remove drm on Kobo books. I've used it successfully for a while. But as ever for an version in development, your mileage may vary.

**Comment by merrpink** [comment]
@ElleKayEm ok, thanks. Do you know the Wine path to the books by any chance? I haven't been successful in finding it.

**Comment by merrpink** [comment]
@lnxme Thanks for the suggestion. Does it work with Calibre 5.7.2?

**Comment by lnxme** [comment]
> @lnxme Thanks for the suggestion. Does it work with Calibre 5.7.2?

Yes, just tested against Calibre V5.7.2. on Windows 10

**Comment by merrpink** [comment]
@lnxme Ok cool, I'll give it a spin. It seems people prefer ADE to the Kobo desktop, I don't know why, and I haven't got it working on Linux yet. Also, in my Wine version of Windows, the books are not in the path you gave, but thanks anyway. I will continue to search....

**Comment by ElleKayEm** [comment]
For myself, I prefer the regular epubs you get from ADE as opposed to Kobo's flavor of epub.  Also, I get Adobe DRM books from other sources besides Kobo.  And Kobo Desktop always checks for updates every time it starts up which can possibly break Obok's ability to decrypt the books.  Hasn't happened in a long time, but that has happened in the past.  If I can download it with Adobe 2.0.1, I know I can decrypt it.

**Comment by merrpink** [comment]
@ElleKayEm Adobe 2.0.1? My ADE is 4.5. Are you referring to a different program here or ADE?

**Comment by ElleKayEm** [comment]
Sorry, I meant Adobe Digital Editions 2.0.1 -- later versions can handle hardened Adobe DRM that DeDRM cannot remove (yet).  As far as I know, Kobo is not using the hardened Adobe DRM at all so far, but other ebookstores might be.  If it can be opened with ADE 2.0.1 (authorized with an Adobe ID), it's definitely the older DRM which DeDRM can remove.

**Comment by merrpink** [comment]
@ElleKayEm Oh wow, that's from 2009. I think I'm just gonna go with the Kobo desktop for now to get my books from there, and them drop them. After that, I'll just stick with Kindle as I have a device and it makes DeDRM quick and easy, and it works on Calibre latest. They also (unfortunately) have exclusivity on many smaller authors whose work I cannot find on other platforms. DeDRM is a great project and I will have a look at the source to see if I can figure out what is going on. Maybe I can find some time to contribute a bit.........
