### ISSUE TITLE
After downloading DeDRM_plugin_7.0.0b4.zip I open the “DeDRM_calibre_plugin” folder but there is no DeDRM_plugin.zip file and I get the error "does not contain a top-level_init_.py file"

### ISSUE THREAD

**Issue by Jenzypenzy** [apprenticeharper/DeDRM_tools#1436]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

**Comment by ElleKayEm** [comment]
DeDRM_plugin_7.0.0b4.zip is the DeDRM plugin only.  Do not unzip it.  Load the entire file as is into calibre 5.

**Comment by Jenzypenzy** [comment]
Thanks. When I click on the link DeDRM_plugin_7.0.0b4.zip on the download page, it downloads a folder to my computer that is already unzipped though?  I just tried to zip it back up & load it into Calibre but I still get a message saying "It does not contain a top-level_init_.py file"

Do you have any other suggestions I could try?
________________________________

**Comment by ElleKayEm** [comment]
First link under Assets on [this page](https://github.com/apprenticeharper/DeDRM_tools/releases/tag/7.0.0b4) is the correct file.

**Comment by franlevy** [comment]
I'm experiencing precisely the same issue as Jenzypenzy. ElleKayEm, I followed the link in your reply to her, but my problem persists. I, too, had to re-zip the file after Mac OS automatically unzipped it during download.

**Comment by Jenzypenzy** [comment]
Yes, still getting "ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Users/Jenna/Downloads/DeDRM_plugin_7.zip' is invalid. It does not contain a top-level __init__.py file" even after downloading the first link under Assets on the page you linked (then having to re-zip in on my Mac since it downloads as an unzipped folder).  Is there a .py file missing from the folder?

**Comment by franlevy** [comment]
My error message states the following:

> **InvalidPlugin:**The plugin in '/Applications/Calibre_Plugins/DeDRM_plygin_7.zip' is invalid. It does not contain a top-level __init__.py file.

Here's the detailed report:

> calibre, version 5.7.2
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Applications/Calibre_Plugins/DeDRM_plugin_7.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.7.2  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && Package KFX (from KFX Input) (1, 31, 0) && Annotations (1, 12, 0) && Embed Comic Metadata (1, 4, 0) && EpubMerge (2, 9, 0) && EpubSplit (2, 9, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && Set KFX metadata (from KFX Output) (1, 41, 1) && KFX Output (1, 41, 1) && KindleUnpack - The Plugin (0, 82, 1) && Manage Series (1, 2, 9) && Prettify Cover 0.9.12
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 284, in load
  File "calibre/customize/zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Applications/Calibre_Plugins/DeDRM_plugin_7.zip' is invalid. It does not contain a top-level __init__.py file

Jenzypenzy's error message apparently refers to a top-level "init.py" file, while mine refers to a top-level "__init__.py" file. The __init__.py file is in the downloaded plugin folder. When my Mac automatically unzipped it during download, I checked each time for that file. It's always there.

**Comment by franlevy** [comment]
Okay, here's something strange: When I published this comment, the name of the init file I was describing was automatically altered. The init file in my Calibre error message is called "__ini__". This is the same python file name found in the downloaded plugin. Could there be an error associated with the underscores in the python file's name?

**Comment by Lxstr** [comment]
Hi guys. I previously ran into this problem. If you rezip the file it will not work 🤷‍♂️ you need to keep the zip file from the download. Sometimes Mac will automatically unzip but you can avoid this by right clicking and selecting 'download as'. When you install the plugin you need to select this entire zipped file as is. How's that go?

**Comment by ElleKayEm** [comment]
Ah, that must be it. It stays zipped for me on Windows/Chrome.  There are zip files inside there too.  So if it unzips everything perhaps that why just zipping up the outer most folder contents doesn't work.

**Comment by Jenzypenzy** [comment]
> My error message states the following:
> 
> > **InvalidPlugin:**The plugin in '/Applications/Calibre_Plugins/DeDRM_plygin_7.zip' is invalid. It does not contain a top-level **init**.py file.
> 
> Here's the detailed report:
> 
> > calibre, version 5.7.2
> > ERROR: Unhandled exception: InvalidPlugin:The plugin in '/Applications/Calibre_Plugins/DeDRM_plugin_7.zip' is invalid. It does not contain a top-level **init**.py file
> > calibre 5.7.2  embedded-python: True is64bit: True
> > macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
> > ('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
> > Python 3.8.5
> > OSX: ('10.16', ('', '', ''), 'x86_64')
> > Interface language: None
> > Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && Package KFX (from KFX Input) (1, 31, 0) && Annotations (1, 12, 0) && Embed Comic Metadata (1, 4, 0) && EpubMerge (2, 9, 0) && EpubSplit (2, 9, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && Set KFX metadata (from KFX Output) (1, 41, 1) && KFX Output (1, 41, 1) && KindleUnpack - The Plugin (0, 82, 1) && Manage Series (1, 2, 9) && Prettify Cover 0.9.12
> > Traceback (most recent call last):
> > File "calibre/gui2/preferences/plugins.py", line 317, in add_plugin
> > File "calibre/customize/ui.py", line 472, in add_plugin
> > File "calibre/customize/ui.py", line 61, in load_plugin
> > File "calibre/customize/zipplugin.py", line 284, in load
> > File "calibre/customize/zipplugin.py", line 379, in _locate_code
> > calibre.customize.InvalidPlugin: The plugin in '/Applications/Calibre_Plugins/DeDRM_plugin_7.zip' is invalid. It does not contain a top-level **init**.py file
> 
> Jenzypenzy's error message apparently refers to a top-level "init.py" file, while mine refers to a top-level "(underscore)(underscore)init(underscore)(underscore).py" file. The (underscore)(underscore)init(underscore)(underscore).py file is in the downloaded plugin folder. When my Mac automatically unzipped it during download, I checked each time for that file. It's always there, and the word "init" is always surrounding by a pair of underscores, without spaces between them.

@franlevy - I think we were receiving the same error with the (_)init(_).py file but there is some automatic formatting which changed it to bold font instead in my posting of the error message above.  And I didn't notice it as I was replying via email & not on the forum page!

@Lxstr comment above worked for me finally - thank you!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by franlevy** [comment]
@Lxstr Eureka! It worked! Thanks a bunch!!!

@ElleKayEm Thank you for your attention to this matter 😊
