### ISSUE TITLE
failed DeDRM of kindle book

### ISSUE THREAD

**Issue by trustingHim** [apprenticeharper/DeDRM_tools#144]
I am trying to use calibre to remove the DRM on my kindle book as explained on [http://lifehacker.com/5954466/how-do-i-get-rid-of-the-drm-on-my-ebooks-and-video](url) which links to the plugin downloaded from [https://github.com/apprenticeharper/DeDRM_tools/releases](url). the plugin to remove the DRM refuses to work, and I can't figure out why. the directions say to load the K3MobiDeDRM_v04.5_plugin.zip plugin file into calibre, but I can't find that in the download link. This is probably a newbie error, but where do i find the correct plugin so I can backup my kindle books?

**Comment by ElleKayEm** [comment]
Ignore outdated directions from elsewhere.  Download the latest release here.  Unzip it, and look in the DeDRM calibre plugin folder.  There's a readme file and the zip you load into calibre.  It handles Kindle books and some other ebook types too.

**Comment by trustingHim** [comment]
Ah, ok. that worked and it (after fighting a bit) it finally converted. thanks!

**Comment by swoodfin** [comment]
Hi ElleKayEm - I appreciate your help with this problem! Your post says to download the latest release "here," but I am not able to access a link to a download site. Could you please repost? Thank you!

**Comment by ElleKayEm** [comment]
The latest release in this repository is at the top of this page:

https://github.com/apprenticeharper/DeDRM_tools/releases
