### ISSUE TITLE
How to find the Mac Kindle Serial Number for Kindle 1.30.0?

### ISSUE THREAD

**Issue by lancejpollard** [apprenticeharper/DeDRM_tools#1442]
I am following [this](https://www.techradar.com/news/software/how-to-remove-ebook-drm-with-calibre-1291960) and [this](https://askubuntu.com/questions/1011989/where-are-amazon-kindle-ebooks-on-my-linux-pc-after-i-download-them-for-offline/1012193#1012193), and have gotten to this point in caliber:

<img width="783" alt="Screen Shot 2020-12-25 at 12 39 17 AM" src="https://user-images.githubusercontent.com/28718/103128303-a59cb680-4649-11eb-9196-62611fd938af.png">

How do I find the serial number for my Mac laptop kindle? I look on [Amazon](https://www.amazon.com/hz/mycd/digital-console/devicedetails?deviceFamily=KINDLE_APP) and see this:

<img width="955" alt="Screen Shot 2020-12-25 at 12 40 22 AM" src="https://user-images.githubusercontent.com/28718/103128339-ca912980-4649-11eb-912b-e3b0ae191c75.png">

I need to convert my kindle book to PDF for a personal project. When I click into the content, and try to download via USB, I get this:

<img width="1076" alt="Screen Shot 2020-12-25 at 12 41 08 AM" src="https://user-images.githubusercontent.com/28718/103128373-ebf21580-4649-11eb-8602-c339700f6c55.png">

Any help would be appreciated.

**Comment by ElleKayEm** [comment]
That's only for E-ink Kindle devices.  You don't need to enter anything for the Kindle for Mac app.  The app just needs to be on the same machine and user as calibre with DeDRM.

Also see this:
https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508
