### ISSUE TITLE
DeDRM v7.0.0b4 Not working on linux

### ISSUE THREAD

**Issue by ujx51** [apprenticeharper/DeDRM_tools#1451]
Running Calibre 5.8.1 on Linux laptop using Arch.

Just converted to Calibre 5 because older versions on Arched to get squirrely due to dependency issues.  Installed DeDRM 7.0.0b4 ok but it doesn't seem to want to decrypt.  One item of note; initially it seemed the problem was a missing dependency (pycryptodome).  Installed that and got past the first error.  Still no luck.  Below are the logs.  Any help would be greatly appreciated.  

[tmpgk2b7nxm.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5747864/tmpgk2b7nxm.txt)

**Comment by ElleKayEm** [comment]
The book is for "download & transfer via usb" to an E-ink Kindle (not a Fire)?  Do you have the Kindle's serial number entered correctly into DeDRM's customization?

**Comment by ujx51** [comment]
Kindle Paperwhite, book downloaded and transfer via usb and the serial number is entered correctly.  Sorry, I should have provided this info right from the start.

**Comment by ElleKayEm** [comment]
Did you mean to close this?

**Comment by ujx51** [comment]
No.  My mistake.  Sorry.

**Comment by ElleKayEm** [comment]
I thought things were working for DeDRM 7 with azw3, but maybe not for Linux.  If you cannot go back to the older versions, you may have to wait for the next release.  Other then that, I'd triple check the serial number and make sure the device chosen when downloading the book was that Paperwhite.

**Comment by ujx51** [comment]
I verified the s/n and just tried another book while making sure that I had the correct device selected.  Still no luck.  Thank you for your help.  I'll wait and see how the next release works out.
