### ISSUE TITLE
Unable to remove DRM from Kindle books

### ISSUE THREAD

**Issue by hubble63** [apprenticeharper/DeDRM_tools#1453]
Hello, I installed successful DeDRM v6.8.0, restarted Calibre and drag and dropped the file to kindle (MacOS 10.13.6).  

---

## Log
<details><summary>Issue</summary>

```
log
DeDRM v6.8.0: Trying to decrypt ebook.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: ebook
Found 0 keys to try after 0.1 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.1 seconds
DeDRM v6.8.0: Finished after 0.1 seconds
Added ebook to db in: 0.1
```
</details>

**Comment by ElleKayEm** [comment]
The book in the log was already DRM-free.

**Comment by hubble63** [comment]
So I don´t unterstand, why I can´t copy/paste Text from this ebook-file as PDF-Document?

**Comment by ElleKayEm** [comment]
If it had DRM, you would not have been able to convert it from azw3 to any other format.

**Comment by hubble63** [comment]
Ah, ok.
So I solved my little Problem with a small workaround: I opened the PDF-File with the Mac-preview. In the print dialog window I used the print2pdf function. So I created a new PDF file without any security settings.

**Comment by ElleKayEm** [comment]
You can close the issue.
