### ISSUE TITLE
REF: failed DeDRM of kindle book #144

### ISSUE THREAD

**Issue by swoodfin** [apprenticeharper/DeDRM_tools#146]
REF: failed DeDRM of kindle book #144

12 days ago, TrustingHim posted: 

I am trying to use calibre to remove the DRM on my kindle book as explained on http://lifehacker.com/5954466/how-do-i-get-rid-of-the-drm-on-my-ebooks-and-video which links to the plugin downloaded from https://github.com/apprenticeharper/DeDRM_tools/releases. the plugin to remove the DRM refuses to work, and I can't figure out why. the directions say to load the K3MobiDeDRM_v04.5_plugin.zip plugin file into calibre, but I can't find that in the download link. This is probably a newbie error, but where do i find the correct plugin so I can backup my kindle books?

ElleKayEm commented:

Ignore outdated directions from elsewhere. Download the latest release here. Unzip it, and look in the DeDRM calibre plugin folder. There's a readme file and the zip you load into calibre. It handles Kindle books and some other ebook types too.
# ElleKayEm - I appreciate your help with this problem! Your post says to download the latest release "here," but I am not able to access a link to a download site on the original post. Could you please repost? Thank you!

**Comment by ElleKayEm** [comment]
Right here in the repository where you're commenting:

https://github.com/apprenticeharper/DeDRM_tools/releases

**Comment by swoodfin** [comment]
Thank you, ElleKayEm. I was hoping it was somewhere else...I've already tried that release, but I've got 30 Kindle books in my library that are still "locked by DRM" when I try to open them in Calibre. I've followed the directions in the Readme file, but no good. Any other ideas or options?

**Comment by ElleKayEm** [comment]
Open calibre in debug mode (under Preferences) and post a log of adding one of the locked books.

**Comment by swoodfin** [comment]
Sure thing. Here it is.

calibre Debug log
calibre 2.70  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 2) && Obok DeDRM (6, 5, 2)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 128.0 x 128.186915888
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 4.31 seconds with 82 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['U\xc0\xf9\x85\x1du\\\xf0n\xe7\xceD\xd9\xbd;\x97;\x05\xd1Sm\xa6\x10r)\xa2u\xa7\\j\xdb9', 'D:\\My Files\\My Documents\\My Kindle Content\\B004CFA9EQ_EBOK.azw']
DeDRM v6.5.2: Trying to decrypt B004CFA9EQ_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 10
Decrypting Mobipocket 6 ebook: The Best Christmas Pageant Ever (Bestâ€¦)
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.2: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.2: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Steve\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Steve\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2647256262' and UserName '5374657665'
DeDRM v6.5.2: Found 1 new key
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 10
Decrypting Mobipocket 6 ebook: The Best Christmas Pageant Ever (Bestâ€¦)
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.2: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 161, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.3 seconds
Added The Best Christmas Pageant Ever (Best…) to db in: 0.1
Added 1 books in 1.5 seconds
Worker Launch took: 0.188999891281

**Comment by ElleKayEm** [comment]
Try deregistering and uninstalling Kindle for PC and removing its folders.  Look at the FAQs for details -- link is in the log.  Then reinstall, re-register, and download the book again.

**Comment by swoodfin** [comment]
Thanks. Do you mean I should also delete the folder with all the book files?

D:\My Documents\My Kindle Content

**Comment by ElleKayEm** [comment]
The books need to be downloaded with the current installation of Kindle for PC which is on the same machine and Windows user as calibre.
