### ISSUE TITLE
DeDRM, Calibre and Python 3 on Ubuntu Linux - help!

### ISSUE THREAD

**Issue by chrisisbd** [apprenticeharper/DeDRM_tools#1469]
Until recently I ran an old version of Calibre that used Python 2 and ran DeDRM successfully with that.

However I have just upgraded my systems to [x]ubuntu 20.10 and that has almost completely pulled the plug on Python 2 now so I need to sort out which DeDRM I need.

The Ubuntu 20.10 repositories give me version 4.99 of Calibre, which would seem to need version 6.8.x of DeDRM but I fear that may be still a Python 2 version of DeDRM and I don't have Python 2 any longer.

So what  should I do??

**Comment by j-howell** [comment]
Version 4.99 of calibre was a beta release for calibre 5 and is very buggy.

You should use the official release available from https://calibre-ebook.com/download_linux

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by chrisisbd** [comment]
Yes, sorry, I meant to before.

**Comment by mndill** [comment]
FWIW, you can use DeDRM 7.1.0 with Calibre 4.99.4 if you change line 132 in the __init__.py file in the plugin from
`minimum_calibre_version = (5, 0, 0)  # Python 3.`
to
`minimum_calibre_version = (4, 9, 9)  # Python 3.`
then rezip and install as usual.

I have only tried this with ADE and epub books, so it may not be a fix, but it has been a workaround for me. I run Linux Mint 20 and like to stick with applications from the repositories, which won't be getting calibre 5+ until the summer of 2022.
