### ISSUE TITLE
Calibre Prefrences does not have Load File option

### ISSUE THREAD

**Issue by Randscom** [apprenticeharper/DeDRM_tools#147]
How can I add DeDRM to Calibre?

**Comment by ElleKayEm** [comment]
Click Preferences > Plugins > Load plugin from file

**Comment by gaelhammer** [comment]
With Calibre 2.71.0, click Preferences > Change Calibre behaviour > Plugins > Load plugin from file. You may need to restart Calibre. DRM ist automatically removed when importing a book to your library.

**Comment by ElleKayEm** [comment]
Yes, you should always restart calibre after installing any plugin.
