### ISSUE TITLE
Unable to unlock DRM from converted KFX: Big Sur, Calibre 5.9, KFM 1.26.1, DeDRM 7.0.3

### ISSUE THREAD

**Issue by krgp21** [apprenticeharper/DeDRM_tools#1470]
Hi, 

After importing books, I could not DeDrm. Got the standard "This file is protected by DRM" after trying to convert to Mobi. 

### What I'm using: 
I'm using Kindle for Mac 1.26.1. 
I used chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test to prevent KFX downloads (note: it does crash my KFM app every time); therefore, I'm importing AZW3 into Calibre. 
I'm using DeDRM 7.0.3. I worked my way up the releases hoping one would work. None did. 

### Notes 1:
I'm unable to sideload from my Kindle because the firmware is too new and I don't want to jailbreak. 
I also have the KFX plugin, but that didn't work—everything remained a KFX-ZIP upon import from KFM. Hence the line of code in terminal.
No I did not open the book inside KFM before trying to import.

### Notes 2: 
I followed all of these instructions from the FAQs:  
Deregister Kindle for PC(Mac) from your Amazon account.
Uninstall Kindle for PC(Mac)
Delete the Kindle for PC(Mac) preferences
PC: Delete the directory [home folder]\AppData\Local\Amazon (it might be hidden) and [home folder]\My Documents\My Kindle Content
Mac: Delete the directory [home folder]/Library/Application Support/Kindle/ and/or [home folder]/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/ (one or both may be present and should be deleted)
Reinstall Kindle for PC(Mac) version 1.17 or earlier (see above for download links).
Re-register Kindle for PC(Mac) with your Amazon account
Download the ebook again. Do not use the files you have downloaded previously.

I'm at a loss. I've tried all the suggested workarounds from Howell and on the forums. 

Thanks. 

### Here's the bug report: 

Traceback (most recent call last):
  File "calibre/gui2/ui.py", line 134, in __init__
  File "calibre/gui2/ui.py", line 152, in init_iaction
  File "calibre/customize/__init__.py", line 614, in load_actual_plugin
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.action", line 24, in <module>
    from calibre_plugins.obok_dedrm.dialogs import (SelectionDialog, DecryptAddProgressDialog,
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.dialogs", line 30, in <module>
    from calibre_plugins.obok_dedrm.utilities import (SizePersistedDialog, ImageTitleLayout,
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.utilities", line 10, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
EpubMerge: DEBUG: 2021-01-08 09:08:09,019: calibre_plugins.epubmerge.epubmerge_plugin(158): macmenuhack file_path:/Users/krgp/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
calibre Debug log
calibre 5.9  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && EpubMerge (2, 11, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Obok DeDRM (6, 5, 4)
calibre 5.9  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && EpubMerge (2, 11, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Obok DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 132.00000198244115 x 132.50000198995036
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[0.86] main UI initialized...
[0.86] Started up in 0.86 seconds with 3445 books
Starting QuickView
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (Blood Heir) finished
Convert book 1 of 1 (Blood Heir)
	DeDRM v7.0.3: Trying to decrypt 0rrcq383.azw
	Using Library AlfCrypto Python
	Using Library AlfCrypto Python
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Blood Heir
	Got DSN key from database default_key_4
	Got DSN key from database default_key_5
	Got DSN key from database default_key_6
	Found 22 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.0.3: Failed to decrypt with error: No key found in 22 PIDs tried.
	DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
	Found k4Mac kinf2018 file: /Users/krgp/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	Found k4Mac kinf2018 file: /Users/krgp/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'krgp'  on file  /Users/krgp/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'0126421d6ee5'
	Decrypted key file using IDString '0126421d6ee5' and UserName 'krgp'
	trying username  b'krgp'  on file  /Users/krgp/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'0126421d6ee5'
	Decrypted key file using IDString '0126421d6ee5' and UserName 'krgp'
	DeDRM v7.0.3: Found 2 new keys
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Blood Heir
	Got SerialNumber from database default_key_1
	Got UsernameHash from database default_key_1
	Got SerialNumber from database default_key_2
	Got UsernameHash from database default_key_2
	Found 8 keys to try after 0.9 seconds
	Crypto Type is: 2
	DeDRM v7.0.3: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  read_metadata_from_opf: '/var/folders/vm/3_7jr3c949q790fq0wc58stc0000gn/C/calibre_5.9.0_tmp_sniqr364/c0et8pa2.opf'
	  cover: '/var/folders/vm/3_7jr3c949q790fq0wc58stc0000gn/C/calibre_5.9.0_tmp_sniqr364/dcpdy5hd.jpeg'
	  verbose: 2
	Resolved conversion options
	calibre version: 5.9.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/var/folders/vm/3_7jr3c949q790fq0wc58stc0000gn/C/calibre_5.9.0_tmp_sniqr364/dcpdy5hd.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x111ebed90>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': 'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x111ebec70>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'personal_doc': '[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/vm/3_7jr3c949q790fq0wc58stc0000gn/C/calibre_5.9.0_tmp_sniqr364/c0et8pa2.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 22 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 630, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	DeDRM v7.0.3: Trying to decrypt 0rrcq383.azw
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Blood Heir
	Got DSN key from database default_key_4
	Got DSN key from database default_key_5
	Got DSN key from database default_key_6
	Found 22 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v7.0.3: Failed to decrypt with error: No key found in 22 PIDs tried.
	DeDRM v7.0.3: Looking for new default Kindle Key after 0.0 seconds
	Found k4Mac kinf2018 file: /Users/krgp/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	Found k4Mac kinf2018 file: /Users/krgp/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'krgp'  on file  /Users/krgp/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'0126421d6ee5'
	Decrypted key file using IDString '0126421d6ee5' and UserName 'krgp'
	trying username  b'krgp'  on file  /Users/krgp/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'0126421d6ee5'
	Decrypted key file using IDString '0126421d6ee5' and UserName 'krgp'
	DeDRM v7.0.3: Found 2 new keys
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Blood Heir
	Got SerialNumber from database default_key_1
	Got UsernameHash from database default_key_1
	Got SerialNumber from database default_key_2
	Got UsernameHash from database default_key_2
	Found 8 keys to try after 0.8 seconds
	Crypto Type is: 2
	DeDRM v7.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 22 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 630, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on /var/folders/vm/3_7jr3c949q790fq0wc58stc0000gn/C/calibre_5.9.0_tmp_sniqr364/0rrcq383.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "runpy.py", line 194, in _run_module_as_main
	  File "runpy.py", line 87, in _run_code
	  File "site.py", line 39, in <module>
	  File "site.py", line 35, in main
	  File "calibre/utils/ipc/worker.py", line 216, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
	  File "calibre/customize/conversion.py", line 245, in __call__
	  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
	  File "calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Blood Heir

**Comment by ElleKayEm** [comment]
If you have an E-ink Kindle (not a Fire), you can get your books from your content and devices page at Amazon.  Select the "download & transfer via USB" and choose the Kindle for the device.  Enter the Kindle's serial number into DeDRM's customization.

If the latest beta version of DeDRM still doesn't work, I recommend going back to calibre 4.23 and DeDRM 6.8.1.  I've seen others say that worked for them with Big Sur.

If you're still having trouble after that, post a log of adding the book (not the conversion attempt):  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by krgp21** [comment]
Thanks for the reply. 

As I noted above, I tried side-loading from my Kindle device, but it failed because the firmware on my Kindle is too new and I don't want to jailbreak. This is what I'm basing this presumption on:

[Here, Howell 11/2020, with updated KFX Input plugin](https://www.mobileread.com/forums/showthread.php?t=291290): "Note: The following import procedures will only work if the software version of the Kindle device or app from which the book is being imported is supported by the DRM removal plugin. DRM removal for KFX format is currently possible only for books downloaded using versions 1.19 through 1.26 of the Kindle for PC/Mac apps and versions 5.6.5 through 5.12.1 of e-ink Kindle device firmware. DRM removal for KFX format will only work for purchased (not borrowed or rented) books."

Given this advice, I downgraded my KFM to the 1.26 version. On import, they were still KFX-ZIP. So I ran the code to block downloads of KFX. And that did what it was supposed to do, BUT the AZW3 files I imported were not de-drm'd so I couldn't convert to MOBI. 

Report: 

Traceback (most recent call last):
  File "calibre/gui2/ui.py", line 134, in __init__
  File "calibre/gui2/ui.py", line 152, in init_iaction
  File "calibre/customize/__init__.py", line 614, in load_actual_plugin
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.action", line 24, in <module>
    from calibre_plugins.obok_dedrm.dialogs import (SelectionDialog, DecryptAddProgressDialog,
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.dialogs", line 30, in <module>
    from calibre_plugins.obok_dedrm.utilities import (SizePersistedDialog, ImageTitleLayout,
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.utilities", line 10, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
EpubMerge: DEBUG: 2021-01-08 20:56:18,435: calibre_plugins.epubmerge.epubmerge_plugin(158): macmenuhack file_path:/Users/krgp/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
calibre Debug log
calibre 5.9  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && EpubMerge (2, 11, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Obok DeDRM (6, 5, 4)
calibre 5.9  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && EpubMerge (2, 11, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Obok DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 132.00000198244115 x 132.50000198995036
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Initializing db...
[0.15] db initialized
[0.15] Constructing main UI...
[0.81] main UI initialized...
[0.81] Started up in 0.81 seconds with 3445 books
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing /Users/krgp/Documents/My Kindle Content/B07J4MMKWP_EBOK/B07J4MMKWP_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.0.3: Trying to decrypt B07J4MMKWP_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Blood Heir
Got SerialNumber from database 20210108 Key
Got UsernameHash from database 20210108 Key
Got DSN key from database default_key_4
Got DSN key from database default_key_5
Got DSN key from database default_key_6
Found 26 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.0.3: Failed to decrypt with error: No key found in 26 PIDs tried.
DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/krgp/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'krgp'  on file  /Users/krgp/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'0126421d6ee5'
Decrypted key file using IDString '0126421d6ee5' and UserName 'krgp'
DeDRM v7.0.3: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Blood Heir
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v7.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 26 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 630, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Blood Heir to db in: 0.0
Added 1 books in 1.1 seconds

**Comment by krgp21** [comment]
Good news: The downgrade you suggested worked, along with KFM 1.26 modified as I described above (not side-loaded from my Kindle).

**If the latest beta version of DeDRM still doesn't work, I recommend going back to calibre 4.23 and DeDRM 6.8.1. I've seen others say that worked for them with Big Sur.**

Thanks.

**Comment by ElleKayEm** [comment]
Glad you found a solution.  FYI, I was not talking about using a book directly from your Kindle.  I know those cannot be decrypted from newer Kindles.  But as I described above, if you have an Eink Kindle on your Amazon account, you can download the book from the website to your computer and add it to calibre.  This is [method 3](https://www.mobileread.com/forums/showthread.php?t=283371) at this post.  If you are all set, you can close the issue.
