### ISSUE TITLE
TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by xxyzz** [apprenticeharper/DeDRM_tools#1479]
#1392 introduces a bug that when adding a kfx book from kindle device will get this error:

```
Error getting PIDs from serial number xxxxx: string argument without an encoding
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 306, in getPidList
    pidlst.extend(map(bytes,getKindlePids(md1, md2, serialnum)))
TypeError: string argument without an encoding
```

`getKindlePids` returns a list of kindle serial number(string) and the lake of encoding parameter causes the error. Add the encoding won't fix the problem because the following code assume the pids are string.

**Comment by ElleKayEm** [comment]
A change to the DRM has meant we haven't been able to decrypt kfx from Kindles for a while now anyway.  Only Kindle for PC/Mac 1.26 and earlier.
