### ISSUE TITLE
Converting using plugin from the command line

### ISSUE THREAD

**Issue by n00b12345** [apprenticeharper/DeDRM_tools#148]
The plugin works great in GUI on Linux. On the terminal though, conversions are problematic and terminate giving errors. Is there plugin meant to be used only in GUI mode of Calibre?

**Comment by ElleKayEm** [comment]
Conversions?  Do you mean DRM removal?  That happens when adding books to calibre, not during conversion.  Or are you saying DRM only gets removed when adding books in the GUI?

**Comment by n00b12345** [comment]
@ElleKayEm I meant DRM removal. Thanks for the clarification. 

My question was, is there any way I can use the plugin in Calibre using the command line? I can remove DRM perfectly issuing the GUI version of Calibre.

**Comment by ElleKayEm** [comment]
I would have thought so, but I only use calibre's GUI interface myself.

**Comment by n00b12345** [comment]
@ElleKayEm Ah. Unfortunately I use Calibre on a headless Raspberry Pi. Hence the need to use the command line. And it gives me a whole lot of errors when trying to convert. Whereas the whole thing works perfectly on GUI. 

At the moment, every time I need to use this plugin, I turn on GUI.

**Comment by apprenticeharper** [comment]
As far as I know, there's nothing in the plugin that should require the GUI when importing books. (But I haven't actually ever tried using command line mode. If doing it on the command line, perhaps decrypting using the command line versions of the tools and then importing would be a work-around.)

However, if you import a book in command-line mode and the DRM isn't removed, please post the import log. Perhaps it's a simple fix.

Any errors during conversion are too late to be of help - DRM only gets removed on import.

**Comment by apprenticeharper** [comment]
If the original poster is still having problems, please re-open and post more info.
