### ISSUE TITLE
KFX DRM not removed

### ISSUE THREAD

**Issue by Ric987** [apprenticeharper/DeDRM_tools#1483]
Hi,

I'm Using Calibre (5.9) with plug-ins DeDRM (7.0.3) and KFX Input (1.32.0) and using Kindle for PC (1.24.3) to access the books which I purchased.
The books do not show on Calibre (Device - Show books in main memory of device).
When a book is dragged into Calibre the format shown is KFX-Zip which I believe indicates that the DRM has not been removed.

Any help most appreciated.
Thanks

**Comment by ElleKayEm** [comment]
The beta DeDRM won't work with KFX files.  Use one of first 3 methods in this post to avoid KFX and get your book in the older format which can be decrypted:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by chillout1974** [comment]
> The beta DeDRM won't work with KFX files. Use one of first 3 methods in this post to avoid KFX and get your book in the older format which can be decrypted: https://www.mobileread.com/forums/showthread.php?t=283371

Easiest is to download the file only, not double clicking the file this will avoid the KFX file to be created. This worked great for me. I also had the execute this command sudo chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test

**Comment by ElleKayEm** [comment]
@chillout1974 
You're talking about method 2 at the link I gave, but for Kindle for Mac.  The OP is on Windows so that method is done differently and also changes for Kindle for PC 1.25 and later.  For PC users, I'd say method 1 is easiest if you can find K4PC 1.17.  If you have an E-ink Kindle, you might find method 3 the easiest.

**Comment by Ric987** [comment]
Thanks very much.

Method 1 worked for me - basically use Kindle for PC ver 1.17

Thanks again and all the best.
