### ISSUE TITLE
Problem installing version 6.5.2 missing file

### ISSUE THREAD

**Issue by morlaine** [apprenticeharper/DeDRM_tools#149]
I have a Toshiba 64-bit laptop, running Windows 10 Home, with 8gb memory and 1Tb hard drive.

I tried to install this latest version of DRM Removal. And got a message saying a file was missing.  The previous version installed with no problem.  I attached a copy of the error message.  Thanks so much for your help.
![error msg on install of version 6 5 2](https://cloud.githubusercontent.com/assets/20029851/20024049/7a3c158c-a2a9-11e6-9151-fd917feeb8b8.jpg)

**Comment by ElleKayEm** [comment]
There are more tools included in the download than just the DeDRM calibre plugin.  You need to unzip that file and look in the DeDRM calibre plugin folder for the zip to load into calibre.
