### ISSUE TITLE
Another error decrypting DeDRM PDFs in calibre

### ISSUE THREAD

**Issue by witcheries** [apprenticeharper/DeDRM_tools#1492]
- [X] `The Title` and The `Log Title` are setted correctly.
- [X] Clarified about `my environment`.
- [X] Code block is used for `the log`.

---

### DeDRM: 7.0.3

---

Running into occasional issues when decrypting PDFs from Adobe Digital Editions into calibre with DeDRM. Most of the time it works fine, but for a few items I've noticed that when the file is imported, instead of showing the cover image it shows a stock image and the title isn't imported. Trying to open the PDF directly from calibre throws up an error. Trying to export the PDF also throws up an error - error code below. Would this be resolved with an earlier version of DeDRM? This doesn't happen for all PDFs that come from an .acsm file and I can't determine what's different about those that fail.

---

## Log

```
calibre, version 5.9.0
WARNING: Error while saving: Failed to update metadata in some books, click "Show details" for more information

Failed to update the metadata in the PDF format of: [BOOK] by Unknown, with error:
    Traceback (most recent call last):
      File "calibre/utils/podofo/__init__.py", line 38, in set_metadata
      File "calibre/utils/ipc/simple_worker.py", line 256, in fork_job
      File "calibre/utils/ipc/simple_worker.py", line 181, in run_job
      File "calibre/utils/ipc/simple_worker.py", line 120, in communicate
    calibre.utils.ipc.simple_worker.WorkerError: Worker failed
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "calibre/customize/ui.py", line 447, in set_file_type_metadata
      File "calibre/customize/builtins.py", line 544, in set_metadata
      File "calibre/ebooks/metadata/pdf.py", line 187, in set_metadata
      File "calibre/utils/podofo/__init__.py", line 42, in set_metadata
    Exception: Failed to set PDF metadata in (Venice): Traceback (most recent call last):
      File "calibre/utils/ipc/simple_worker.py", line 304, in main
      File "calibre/utils/podofo/__init__.py", line 99, in set_metadata_
    podofo.Error: ePdfError_UnsupportedFilter
    File: /private/var/folders/hb/2_22y10x72j2tltq8b0ygzp80000gn/T/t/podofo-avye7kfp/src/base/PdfParser.cpp Line: 272 Unable to load objects from file.
    File: /private/var/folders/hb/2_22y10x72j2tltq8b0ygzp80000gn/T/t/podofo-avye7kfp/src/base/PdfParser.cpp Line: 1070 Error while loading object 1011 0
    
    File: /private/var/folders/hb/2_22y10x72j2tltq8b0ygzp80000gn/T/t/podofo-avye7kfp/src/base/PdfEncrypt.cpp Line: 549 Unsupported encryption filter: EBX_HANDLER
    
```

**Comment by ElleKayEm** [comment]
Give calibre 4.23 and DeDRM 6.8.1 a try.

**Comment by dev31415** [comment]
Sorry. Upon re-reading the log excerpt: This is not an example of #1493

**Comment by witcheries** [comment]
@dev31415 yeah, I tried installing your patched plugin and it didn't solve my issue.

**Comment by witcheries** [comment]
@ElleKayEm YES I finally tried this (I'm a procrastinator) and it worked like a charm. Thank you! Hopefully this issue will be resolved in newer releases.
