### ISSUE TITLE
"At least one signature has problems"

### ISSUE THREAD

**Issue by etrocepad** [apprenticeharper/DeDRM_tools#150]
Hi, 
I use DeDRM tools to create PDF with Calibre from books I obtained on Kindle.
It works but when I open the PDF with Adobe Acrobat, "At least one signature has problems" is written.
It does not hamper the reading of the document, but i would like to know why there is this message.
Does the PDF created contains some Amazon information about me (like hidden watermarks)?
Thanks.

**Comment by ElleKayEm** [comment]
I don't know why you're getting that message or how to fix that.  But if the books are AZW4 files (or even if they're not), you might want to look at the Kindle Unpack plugin.

The DeDRM tools make no attempt to remove any of your personal information.  So if it's in the original file, then it might very well be in the PDF too.

**Comment by apprenticeharper** [comment]
This sounds like a calibre issue. Clearly the DRM is being removed, or the conversion couldn't happen at all.
