### ISSUE TITLE
Calibre/DeDRM fails to decrypt PDF from ADE 2.0.1

### ISSUE THREAD

**Issue by vitaminace33** [apprenticeharper/DeDRM_tools#1503]
### DeDRM: `7.0.3`

I've just bought a book. I initially opened it with ADE 4.5. When I read that DeDRM can only decrypt books from ADE 2.0.1, I went to all the process of uninstalling and cleaning the system of any trace of Adobe files and references (specially the register). I installed ADE 2.0.1 and download the book again (from the .acsm file).

Calibre/DeDRM fails to decrypt the aforementioned PDF. It successfully decrypts an ePUB that I own though. Any suggestion?

PS Although the "Question" template seems to be simple, it is confusing and I didn't know what to check or modify. The English is incorrect. I don't pretend to offend, but to note it.

**Comment by ElleKayEm** [comment]
DeDRM 7.0.3 still has some bugs with pdfs.  Try with calibre 4.23 and DeDRM 6.8.1.

**Comment by vitaminace33** [comment]
It worked! Thx :D
### Calibre: `4.23` (Windows)
### DeDRM: `6.8.1`

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
