### ISSUE TITLE
Error getting PIDs from serial number GXXXXXX: string argument without an encoding

### ISSUE THREAD

**Issue by AUsernameWhichIsNotTaken** [apprenticeharper/DeDRM_tools#1506]
Using a kindle oasis and want to read my eBooks also on a remarkable i tried with no success to DeDRM one of the books I've bought from amazon. (Serial number i set up is copied from my amazon account, e.g. should be right).

Calibre debug output

<pre>
calibre Debug log
calibre 5.10.1  embedded-python: False is64bit: True
Linux-5.4.13-arch1-1-macbook-x86_64-with-glibc2.32 Linux ('64bit', 'ELF')
('Linux', '5.4.13-arch1-1-macbook', '#1 SMP PREEMPT Sun Mar 22 19:23:34 EET 2020')
Python 3.9.1
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 5.10.1  embedded-python: False is64bit: True
Linux-5.4.13-arch1-1-macbook-x86_64-with-glibc2.32 Linux ('64bit', 'ELF')
('Linux', '5.4.13-arch1-1-macbook', '#1 SMP PREEMPT Sun Mar 22 19:23:34 EET 2020')
Python 3.9.1
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.04726735598227 x 96.07565011820331
physicalDpi: 227.35664335664336 x 227.03910614525137
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.05] splash screen shown
[0.05] Initializing db...
[0.05] db initialized
[0.05] Constructing main UI...
[0.54] main UI initialized...
[0.54] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing /media/kindle/documents/Downloads/Items01/Go Programming Blueprints_ Build real-world, production-ready solutions in Go using cutting-edge technology and techniques, 2nd Edition_B01GQCQ8OW.kfx
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /tmp/calibre_5.10.1_tmp_f9xnsw6n/uuwnwmkt.kfx-zip
DeDRM v7.0.3: Trying to decrypt uuwnwmkt.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: uuwnwmkt
Error getting PIDs from serial number G000SA1480170C61: string argument without an encoding
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 306, in getPidList
    pidlst.extend(map(bytes,getKindlePids(md1, md2, serialnum)))
TypeError: string argument without an encoding
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v7.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
DeDRM v7.0.3: Exception when getting default Kindle Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 554, in KindleMobiDecrypt
    defaultkeys = WineGetKeys(scriptpath, ".k4i",dedrmprefs['kindlewineprefix'])
  File "calibre_plugins.dedrm.wineutils", line 74, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "calibre_plugins.dedrm.wineutils", line 37, in __init__
    self.check_call(["-c", self.py3_test])
  File "calibre_plugins.dedrm.wineutils", line 62, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "/usr/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 630, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.36.0: Packaging /tmp/calibre_5.10.1_tmp_f9xnsw6n/uuwnwmkt.kfx-zip
Processing container: CR!HWH275QTVN1B72V1XGFG14Z26N54.kfx
Processing container: Go Programming Blueprints_ Build real-world, production-ready solutions in Go using cutting-edge technology and techniques, 2nd Edition_B01GQCQ8OW.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Go Programming Blueprints_ Build real-world, production-ready solutions in Go using cutting-edge technology and techniques, 2nd Edition_B01GQCQ8OW.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /tmp/calibre_5.10.1_tmp_f9xnsw6n/ddpnv_jm_add_books/0/Go Programming Blueprints_ Build real-world, production-ready solutions in Go using cutting-edge technology and techniques, 2nd Edition_B01GQCQ8OW.kfx-zip

Found device nodes: /dev/sdb None None
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /media/kindle/ documents
DEBUG:    0.0 USBMS: scan from root False /media/kindle/documents
DEBUG:    0.1 USBMS: count found in cache: 227, count of files in metadata: 227, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 227
DeviceJob: set_books_in_library finished: time= 0.018253326416015625
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 1 Set library information finished
No details available.
[9.81] splash screen hidden
[9.81] Started up in 9.81 seconds with 2 books

Found device nodes: /dev/sdc None None
Syncing cover thumbnails to workaround amazon cover bug
Job: 3 Get device information started
DeviceJob: 3 Get device information done, calling callback
DeviceJob: 3 Get device information callback returned
Job: 4 Set library information started
DeviceJob: 4 Set library information done, calling callback
DeviceJob: 4 Set library information callback returned
Job: 5 Get list of books on device started
DEBUG:  314.8 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:  314.8 USBMS: dirs are: /run/media/goedel/Kindle/ documents
DEBUG:  314.9 USBMS: scan from root False /run/media/goedel/Kindle/documents
DEBUG:  315.3 USBMS: count found in cache: 227, count of files in metadata: 227, need_sync: False
DEBUG:  315.3 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:  315.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:  315.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 5 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 227
DeviceJob: set_books_in_library finished: time= 0.0030412673950195312
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 5 Get list of books on device callback returned
Job: 3 Get device information finished
No details available.
Job: 4 Set library information finished
No details available.
Job: 5 Get list of books on device finished
No details available.
Added Go Programming Blueprints: Build real-world, production-ready solutions in Go using cutting-edge technology and techniques, 2nd Edition to db in: 0.3
Added 1 books in 1.1 seconds
Worker Launch took: 0.02 seconds
Job: 6 Convert book 1 of 1 (Go Programming Blueprints: Build real-world, production-ready solutions in Go using cutting-edge technology and techniques, 2nd Edition) finished
Convert book 1 of 1 (Go Programming Blueprints: Build real-world, production-ready solutions in Go using cutting-edge technology and techniques, 2nd Edition)
	DeDRM v7.0.3: Trying to decrypt 4122kzo2.kfx-zip
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	Decrypting KFX-ZIP ebook: 4122kzo2
	Error getting PIDs from serial number G000SA1480170C61: string argument without an encoding
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kgenpids", line 306, in getPidList
	    pidlst.extend(map(bytes,getKindlePids(md1, md2, serialnum)))
	TypeError: string argument without an encoding
	Found 0 keys to try after 0.1 seconds
	Decrypting KFX DRM voucher: voucher
	DeDRM v7.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
	DeDRM v7.0.3: Exception when getting default Kindle Key after 0.1 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
	    self.decrypt_voucher(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
	    raise Exception("Failed to decrypt KFX DRM voucher with any key")
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 554, in KindleMobiDecrypt
	    defaultkeys = WineGetKeys(scriptpath, ".k4i",dedrmprefs['kindlewineprefix'])
	  File "calibre_plugins.dedrm.wineutils", line 74, in WineGetKeys
	    pyexec = WinePythonCLI(wineprefix)
	  File "calibre_plugins.dedrm.wineutils", line 37, in __init__
	    self.check_call(["-c", self.py3_test])
	  File "calibre_plugins.dedrm.wineutils", line 62, in check_call
	    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
	  File "/usr/lib/python3.9/subprocess.py", line 368, in check_call
	    retcode = call(*popenargs, **kwargs)
	  File "/usr/lib/python3.9/subprocess.py", line 349, in call
	    with Popen(*popenargs, **kwargs) as p:
	  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
	    self._execute_child(args, executable, preexec_fn, close_fds,
	  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
	    raise child_exception_type(errno_num, err_msg, err_filename)
	FileNotFoundError: [Errno 2] No such file or directory: 'wine'
	DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
	    self.decrypt_voucher(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
	    raise Exception("Failed to decrypt KFX DRM voucher with any key")
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/lib/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
	    nfp = plugin.run(nfp) or nfp
	  File "calibre_plugins.dedrm.__init__", line 630, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  output_profile: 'kindle'
	  allow_conversion_with_errors: True
	  verbose: 2
	  cover: '/tmp/calibre_5.10.1_tmp_f9xnsw6n/pqxx3yuf.jpeg'
	  flow_size: 2000
	  read_metadata_from_opf: '/tmp/calibre_5.10.1_tmp_f9xnsw6n/s7ci40p9.opf'
	Resolved conversion options
	calibre version: 5.10.1
	{'allow_conversion_with_errors': True,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/tmp/calibre_5.10.1_tmp_f9xnsw6n/pqxx3yuf.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': '2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'flow_size': 2000,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f7a75a8a5e0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x7f7a75a8a0d0>,
	 'page_breaks_before': '/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/tmp/calibre_5.10.1_tmp_f9xnsw6n/s7ci40p9.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	DeDRM v7.0.3: Trying to decrypt 4122kzo2.kfx-zip
	Decrypting KFX-ZIP ebook: 4122kzo2
	Error getting PIDs from serial number GXXXXX: string argument without an encoding
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kgenpids", line 306, in getPidList
	    pidlst.extend(map(bytes,getKindlePids(md1, md2, serialnum)))
	TypeError: string argument without an encoding
	Found 0 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: voucher
	DeDRM v7.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.0.3: Looking for new default Kindle Key after 0.0 seconds
	DeDRM v7.0.3: Exception when getting default Kindle Key after 0.0 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
	    self.decrypt_voucher(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
	    raise Exception("Failed to decrypt KFX DRM voucher with any key")
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 554, in KindleMobiDecrypt
	    defaultkeys = WineGetKeys(scriptpath, ".k4i",dedrmprefs['kindlewineprefix'])
	  File "calibre_plugins.dedrm.wineutils", line 74, in WineGetKeys
	    pyexec = WinePythonCLI(wineprefix)
	  File "calibre_plugins.dedrm.wineutils", line 37, in __init__
	    self.check_call(["-c", self.py3_test])
	  File "calibre_plugins.dedrm.wineutils", line 62, in check_call
	    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
	  File "/usr/lib/python3.9/subprocess.py", line 368, in check_call
	    retcode = call(*popenargs, **kwargs)
	  File "/usr/lib/python3.9/subprocess.py", line 349, in call
	    with Popen(*popenargs, **kwargs) as p:
	  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
	    self._execute_child(args, executable, preexec_fn, close_fds,
	  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
	    raise child_exception_type(errno_num, err_msg, err_filename)
	FileNotFoundError: [Errno 2] No such file or directory: 'wine'
	DeDRM v7.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
	    self.decrypt_voucher(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
	    raise Exception("Failed to decrypt KFX DRM voucher with any key")
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/lib/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
	    nfp = plugin.run(nfp) or nfp
	  File "calibre_plugins.dedrm.__init__", line 630, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: KFX Input running
	on /tmp/calibre_5.10.1_tmp_f9xnsw6n/4122kzo2.kfx-zip
	Software versions: KFX Input 1.36.0, calibre 5.10.1, Linux-5.4.13-arch1-1-macbook-x86_64-with-glibc2.32
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting /tmp/calibre_5.10.1_tmp_f9xnsw6n/4122kzo2.kfx-zip
	Processing container: CR!HWH275QTVN1B72V1XGFG14Z26N54.kfx
	Processing container: Go Programming Blueprints_ Build real-world, production-ready solutions in Go using cutting-edge technology and techniques, 2nd Edition_B01GQCQ8OW.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Go Programming Blueprints_ Build real-world, production-ready solutions in Go using cutting-edge technology and techniques, 2nd Edition_B01GQCQ8OW.kfx has DRM and cannot be converted
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/bin/calibre-parallel", line 20, in <module>
	    sys.exit(main())
	  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 216, in main
	    result = func(*args, **kwargs)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
	    gui_convert(input, output, recommendations, notification=notification,
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	    plumber.run()
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1108, in run
	    self.oeb = self.input_plugin(stream, self.opts,
	  File "/usr/lib/calibre/calibre/customize/conversion.py", line 245, in __call__
	    ret = self.convert(stream, options, file_ext,
	  File "calibre_plugins.kfx_input.__init__", line 123, in convert
	calibre.ebooks.DRMError: This book has DRM!
</pre>

**Comment by ElleKayEm** [comment]
Right now DeDRM cannot decrypt KFX format downloaded directly to Kindle devices.  Go to your content and devices page on the website.  Look for the option to "download & transfer via usb" for that book.  Choose your Oasis for the device.  Import that copy into calibre.

**Comment by AUsernameWhichIsNotTaken** [comment]
That works, thank you!
