### ISSUE TITLE
Obok decryption error

### ISSUE THREAD

**Issue by stil3th** [apprenticeharper/DeDRM_tools#151]
Only 2 books from around 50 wasn't decrypted. I've updated the Kobo app to latest version and also re-downloaded both books.

Here's the debug log:

Obok v3.2.2
Copyright © 2012-2016 Physisticated et al.
c:\users\xxx\appdata\local\temp\tmpjbwk7f
DEBUG: 1183.5 got kobodir C:\Users\xxx\AppData\Local\Kobo\Kobo Desktop Edition
Found 4 possible keys to try.
DEBUG: 1249.4 BookListTableWidget:get_books - book_num: 1
DEBUG: 1249.4 BookListTableWidget:get_books - book: #Self: Taming Your Inner Online Menace
DEBUG: 1249.4 BookListTableWidget:get_books - book_num: 510
DEBUG: 1249.4 BookListTableWidget:get_books - book: The Pirates of Sufiro (Book 1 Old Star New Earth)
DEBUG: 1249.4 InterfacePluginAction::launchObok - number of books to decrypt: 2
Obok DeDRM v6.5.2 - Decrypting #Self: Taming Your Inner Online Menace
Trying key:  907525ba93478af787ea35373227668e
Bad XML: <!DOCTYP
Decryption failed, trying next key.
Trying key:  46418b2b93fa8a7cf6e0aa7ac5846aa7
Decryption failed, trying next key.
Trying key:  33ce413341b9a06e95aa07ae3e871e34
Decryption failed, trying next key.
Trying key:  ba0b7274f0c113f055783080254f9385
Decryption failed, trying next key.
Obok DeDRM v6.5.2 - Couldn't decrypt #Self: Taming Your Inner Online Menace
DEBUG: 1249.4 DecryptAddProgressDialog::do_book_action - book decryption failed: '#Self: Taming Your Inner Online Menace'
Obok DeDRM v6.5.2 - Decrypting The Pirates of Sufiro (Book 1 Old Star New Earth)
Trying key:  907525ba93478af787ea35373227668e
Bad XML: <html xm
Decryption failed, trying next key.
Trying key:  46418b2b93fa8a7cf6e0aa7ac5846aa7
Decryption failed, trying next key.
Trying key:  33ce413341b9a06e95aa07ae3e871e34
Decryption failed, trying next key.
Trying key:  ba0b7274f0c113f055783080254f9385
Decryption failed, trying next key.
Obok DeDRM v6.5.2 - Couldn't decrypt The Pirates of Sufiro (Book 1 Old Star New Earth)
DEBUG: 1249.5 DecryptAddProgressDialog::do_book_action - book decryption failed: 'The Pirates of Sufiro (Book 1 Old Star New Earth)'
Obok DeDRM v6.5.2 - wrapping up results.

**Comment by ElleKayEm** [comment]
Hmm, I have _#Self: Taming Your Inner Online Menace_ too, and I can't decrypt it with Obok either.  Other books are fine though.  I was able to download from the website via ADE and use the regular DeDRM plugin on that book though.

**Comment by apprenticeharper** [comment]
Oh - it's a failure to see that a file has been decrypted.

There's a fix in the works (available in the github repository but not yet in a full release) that should mean that the first one will decrypt successfully, but the second one will still fail. 

(ePub text files should start with <?xml. Some seem to start with <!DOCTYPE. Starting <html xm is wrong, but perhaps we should still decrypt successfully.

I'll see whether something can be done before the next full release.

**Comment by apprenticeharper** [comment]
Please give the latest commit a go. I think it should fix the problem. You can download just the obok plugin from this link:

https://github.com/apprenticeharper/DeDRM_tools/raw/master/Obok_calibre_plugin/obok_plugin.zip

**Comment by ElleKayEm** [comment]
Yes, working for me now.

**Comment by apprenticeharper** [comment]
Thanks for the confirming that the fix works.

**Comment by apprenticeharper** [comment]
Fixed included in the DeDRM 6.5.3 release

**Comment by stil3th** [comment]
Working for me as well.
Thanks for the fix :)
