### ISSUE TITLE
DRM still present

### ISSUE THREAD

**Issue by Alornai** [apprenticeharper/DeDRM_tools#1511]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.10.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 5.10.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.44] db initialized
[0.44] Constructing main UI...
[1.00] main UI initialized...
[1.00] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing C:\Users\rena8\OneDrive\Documents\My Kindle Content\B07H3YTS7Y_EBOK\B07H3YTS7Y_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 7 file(s) as C:\Users\rena8\AppData\Local\Temp\calibre_luer1vaa\nnm7ykmn.kfx-zip
DeDRM v7.0.3: Trying to decrypt nnm7ykmn.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: nnm7ykmn
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7b790ae2-6391-4874-ad33-626ba680789d.voucher
DeDRM v7.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\rena8\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\rena8\AppData\Local\Amazon\Kindle\storage\.kinf2018
[12.11] splash screen hidden
[12.11] Started up in 12.11 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'{\xe3\x0e3kt\xa3\x7f\xbb\x96l\xb89p\x9e\x84\xa4\xc1:\x1a\x94\x044g\x8a\x1125]\xfcz6', b'C:\\Users\\rena8\\OneDrive\\Documents\\My Kindle Content\\B07H3YTS7Y_EBOK\\B07H3YTS7Y_EBOK.azw']
Decrypted key file using IDString '4076675780' and UserName 'rena8'
DeDRM v7.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: nnm7ykmn
Got DSN key from database default_key_1
Found 1 keys to try after 3.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7b790ae2-6391-4874-ad33-626ba680789d.voucher
DeDRM v7.0.3: Ultimately failed to decrypt after 3.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.36.0: Packaging C:\Users\rena8\AppData\Local\Temp\calibre_luer1vaa\nnm7ykmn.kfx-zip
Processing container: B07H3YTS7Y_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\rena8\AppData\Local\Temp\calibre_luer1vaa\ufgmztim_add_books\0\B07H3YTS7Y_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 630, in run
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 3.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B07H3YTS7Y_EBOK.azw has DRM and cannot be converted
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing C:\Users\rena8\OneDrive\Documents\My Kindle Content\B00I60M48W_EBOK\B00I60M48W_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 16 file(s) as C:\Users\rena8\AppData\Local\Temp\calibre_luer1vaa\hhdbpldh.kfx-zip
DeDRM v7.0.3: Trying to decrypt hhdbpldh.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: hhdbpldh
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.81a72a71-a431-4bb4-aebd-002d14f5b94b.voucher
DeDRM v7.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\rena8\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\rena8\AppData\Local\Amazon\Kindle\storage\.kinf2018
Added Processes in Microbial Ecology to db in: 0.1
Added 1 books in 4.0 seconds
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'=H4)\xe4\xd9G\xcb\xf6\xe7\xcd\x17\x88 \x1e\xbcgd\xe7\xca\xf2\xa5VZD\xa3\xbe7O6I\x06', b'C:\\Users\\rena8\\OneDrive\\Documents\\My Kindle Content\\B00I60M48W_EBOK\\B00I60M48W_EBOK.azw']
Decrypted key file using IDString '4076675780' and UserName 'rena8'
DeDRM v7.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: hhdbpldh
Got DSN key from database default_key_1
Found 1 keys to try after 3.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.81a72a71-a431-4bb4-aebd-002d14f5b94b.voucher
DeDRM v7.0.3: Ultimately failed to decrypt after 3.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.36.0: Packaging C:\Users\rena8\AppData\Local\Temp\calibre_luer1vaa\hhdbpldh.kfx-zip
Processing container: B00I60M48W_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\rena8\AppData\Local\Temp\calibre_luer1vaa\r9oq57rx_add_books\0\B00I60M48W_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 630, in run
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 3.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B00I60M48W_EBOK.azwAdded Algae: Anatomy, Biochemistry, and Biotechnology, Second Edition (Routledge Studies in Science, Technology and Society) to db in: 0.2
Added 1 books in 4.1 seconds

```
</details>

Purchased both textbooks on Amazon. Calibre & deDRM won't remove DRM.

**Comment by ElleKayEm** [comment]
Disable KFX format downloads.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Alornai** [comment]
> Disable KFX format downloads. See this post: https://www.mobileread.com/forums/showthread.php?t=283371

I went in and reverted to 1.17, and tried again. They converted without error, but are appearing in gibberish (random symbols). I've tried converting to pdf, htmlz, azw3, and epub. I've also tried opening to view in kindle, calibre, chrome, and adobe. 

I have zero coding experience so any help (with detailed instructions) would be very useful. 

Here is a sample of the gibberish: 
%MOPO „¯jl¯tð× ³L³L2³LÂ³LÂø³MºÏ³Z‰·³r@ ³y`	g³‚Ç É³³˜¡ €³¦!~³±ŸK³¼ê ³Åù³Åù³àŽ³ð“´›®´%IÒ´Bb´[}¥´r"$´†F²´¥ø]´µU P´Õ¥q´í"Mµctµ(×pµFGµ]_êµmINµ†—¶µ¤M×µÂ$ŒµØ°Lµ÷üº¶¶À¶0v³¶P)R¶i{…¶ƒƒ¶ƒÐ¶´SÁ¶ÏV¶éj¶ÿ‰¦·/ 2·&a†·=çƒ·VjŒ·mö! ·–·©šþ·È˜·å²¸¸!¸"Ew¸9¼!‚¸[>c¸s¡!C¸”äó¸´×

**Comment by ElleKayEm** [comment]
You deleted the previous downloads from calibre and the Kindle Content folder, redownloaded, and the added the new copies to calibre?  Let's see a log of adding one of these copies.

**Comment by Alornai** [comment]
Yes. And thanks for the help! Here you go:

'''
calibre Debug log
calibre 5.10.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 5.10.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.64] splash screen shown
[0.64] Initializing db...
[0.64] db initialized
[0.64] Constructing main UI...
[1.45] main UI initialized...
[1.45] Hiding splash screen
Starting QuickView
DeDRM v7.0.3: Trying to decrypt B07H3YTS7Y_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Processes in Microbial Ecology
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
File is encoded with PID ckoM9nn+6D.
Decrypting. Please wait . . . . . . . . . . . . . . . [3.38] splash screen hidden
[3.38] Started up in 3.38 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x10Vw\xd0\xbc\xfc\xcb\xda,w\x80\x8b\xd9\xdf\xf4\xab\xfb\xbb4\x1e\x0e\xf2A\xe1\xb8\x18\xcch\xc9A\x94\xd6', b'C:\\Users\\rena8\\OneDrive\\Documents\\My Kindle Content\\B07H3YTS7Y_EBOK.azw4']
. . . . . . . . . . . . . . . . . . . . . . done
Decryption succeeded after 1.3 seconds
DeDRM v7.0.3: Finished afterAdded Processes in Microbial Ecology to db in: 0.1
Added 1 books in 2.1 seconds
'''

**Comment by jonahanzen** [comment]
Did it work? i think i'm having a similar issue, the kindle i'm trying to convert seems to be written in gibberish, and when i convert, it still is the same gibberish, like:

&lt;‰W&lt;à&lt;&amp;ð
Z&lt;1Jì&lt;96	¬<B_____K__ ____usi_____h_____p___="" k_z__="" e___________="" i____="" _______9_____u___x______________="" ___________="" ____________z____="," __="#'=J" __="$&quot;o=,‘" _="6È" _______="L^" ___="Uô" _k5="v@?=z" __="…" _="‘]Å=™&quot;" ______="«ì=³" __="¼Ô" _____="" __="ÐË" _="ÛF=æ^" __="ð0" __="úÝ7">K&gt;_F&gt;¥
ë&gt;!Ò&gt;*bÖ&gt;/8	K&gt;8ƒŒ&gt;EÁ&gt;LÐ	S&gt;V#O&gt;are&gt;h×
õ&gt;sÌ|&gt;|H£&gt;ƒë&gt;Žò
o&gt;™aæ&gt;¡GÁ&gt;­Ž&gt;´–

**Comment by Alornai** [comment]
No, it didn't. Still having the gibberish. I was just thanking ElleKayEm for trying to help

**Comment by j-howell** [comment]
DRM was successfully removed. AZW4 format is actually a PDF file with a MOBI wrapper. Calibre tries to convert those, but sometimes it will produce gibberish because of the way that PDF files do font subsetting.

Instead of trying to convert AZW4 you can use the kindleunpack plugin to extract the embedded PDF from it. That almost always provides better results.

**Comment by Alornai** [comment]
Thank you so much j-howell! That worked perfectly!
