### ISSUE TITLE
Specific Book Fails DeDRM

### ISSUE THREAD

**Issue by Steveth1951** [apprenticeharper/DeDRM_tools#1514]
Kindle for PC 1.26, Calibre 5.10.1, DeDRM 7.0.3.

Nearly all my books are purchased from Amazon, latterly in KFX format.  All been working fine, until I purchased Recursion.  This appeared in Calibre as a KFX-ZIP, and was still DRM locked.  Reverted to older versions of software, still the same.

Returned to above listed versions of software, purchased a different book which was added to Calibre as a KFX with no problem.  Downloaded Recursion again from Amazon, this time using the "transfer by USB" option.  Appears in Calibre as AZW3 (expected) but still DRM locked.

What am I doing wrong, or has Amazon changed something? Book was published June 2019, so new but not all that recent.

Log file from attempt to add book using current versions of software attached.
[tmp634a2tj6.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5931911/tmp634a2tj6.txt)

**Comment by ElleKayEm** [comment]
When you download from the website, you need to chose an E-ink Kindle for the device (not a Fire) and you need to have the Kindle's serial number entered into DeDRM's customization.

**Comment by Steveth1951** [comment]
Thanks for this, is this specific to certain books?  As I said in my original post I have since purchased, downloaded and added to Calibre another book without a problem.

**Comment by ElleKayEm** [comment]
That's what you need to do for any copy downloaded from the website.

Beta DeDRM still needs some work.  You should be able to decrypt KFX format with calibre 4.23 and DeDRM 6.8.1 as long as the book was downloaded with the current installation of Kindle for PC on the same machine and user and it was version 1.26 or earlier.

**Comment by Steveth1951** [comment]
OK, thanks for all this.  I'm using Kindle for PC v1.26 and it is running on the same machine as Calibre.  I do understand DeDRM 7.03 is a Beta version; the reason I reported this issue was in case it was relevant to improving the code,  I have imported 5 or 6 other books using version 7.x without a problem.

Thanks for your feedback.

**Comment by ElleKayEm** [comment]
In that case, let's see a log of importing the KFX from Kindle for PC into calibre with DeDRM 7.0.3.  And maybe a separate log of a KFX book that worked.  The azw3 file should work with DeDRM 7.0.3 as long as it's for an E-ink Kindle and you have the serial number entered correctly.

**Comment by Steveth1951** [comment]
Before your last post I installed calibre 4.23 with DeDRM 6.8.0 in a virtual machine to see what would happen.  This title (Recursion) still does not decrypt but two other books purchased around the same time are OK.  Just for information.

I'm clearly missing something which should be obvious to me but I can't pick it up.  I've never owned an e-ink Kindle and yet I have 147 books purchased from Amazon in Calibre, 146 of which decrypted OK, 5 or 6 of these very recently using Calibre 5.10.1 and DeDRM 7.0.3.  However this one title, with the same process and same software won't decrypt.

I attached the original debug log to my first post, here it is again.
[tmp634a2tj6.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5932904/tmp634a2tj6.txt)
Here is the log from a successful import run just after the above.
[tmpgpp3kzml.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5932923/tmpgpp3kzml.txt)

Thanks for persevering in trying to help me identify the problem.

**Comment by ElleKayEm** [comment]
The first log is an AZW3 file.  You said you downloaded it with the "transfer via USB" option.  That only works if you have an E-ink Kindle on your account, choose that for the device when downloading, and have its serial number entered correctly in DeDRM.  And an E-ink Kindle is any of the ones with the B&W screen -- any Kindle that's not a Fire tablet.

When you tried with calibre 4.23 and DeDRM 6.8.x in a virtual machine, did you also have Kindle for PC 1.26 installed there and import the book downloaded with that installation? Each app/device uses a unique key even when they are logged into the same account.

**Comment by Steveth1951** [comment]
Ahh, no you are correct I didn't use Kindle for PC in the same virtual machine.  Annoying, because I know that is a requirement.  Will redo it correctly this time.

**Comment by Steveth1951** [comment]
Re-ran test in virtual machine, this time using Kindle for PC v1.26, Calibre 4.23 and DeDRM 6.8 all in the same machine.  As expected, worked OK.  Sorry for the red herring.  Will send debug log showing failing book as imported to Calibre via Kindle for PC, rather than USB, tomorrow.

**Comment by Steveth1951** [comment]
Replaced DeDRM 6.8 with version 7.1 and book now decrypts fine.  Thanks for all your help.
