### ISSUE TITLE
Convert azw impossible

### ISSUE THREAD

**Issue by patricekaratchentzeff** [apprenticeharper/DeDRM_tools#1525]
Hi,

I use a Linux machine with calibre download at version 4.23. DeDRM is 6.8.0.

I download my azw file with on old version of Kindle for PC (1.17) to be sure to have no KFX.

All seems OK ;-)

But when I try to import in calibre when converting, the process fails : 

Here's the log file :

InputFormatPlugin: MOBI Input running
on /tmp/calibre_4.23.0_tmp_zhHMl9/JPXZzq.azw
Found KF8 MOBI of type u'standalone'
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm

Any help is welcome !

Thanks for the job : it is the first time I attempt to convert a DRM File. Note that I have no Kindle, only a Kobo...

**Comment by patricekaratchentzeff** [comment]
Addition. I suspect my Amazon Keys. The procedure to get keys is not clear for me.

I use a Calibre 4.23 in the WM of Win10 (the same where is Kindle for PC). I installed deDRM 6.8.0 and I configured the plugin's by getting "Kindle for MAC and PC keys" then add "Default keys". I export it and use it under my Calibre under Linux.

**Comment by patricekaratchentzeff** [comment]
Last update. Conversion runs good in the Windows VM :-(

Don't close the issue. I would prefer that runs in my linux machine.

Thanks

**Comment by ElleKayEm** [comment]
You should be able to save the working key file from the Windows VM setup of calibre with DeDRM and import it into your Linux setup of calibre/DeDRM.  As long as that installation of Kindle for PC is what you continue to use to download your books, it should work.

**Comment by patricekaratchentzeff** [comment]
Thanks for your response.

Unfortunately, it is what I did...

**Comment by ElleKayEm** [comment]
Let's see the whole import log of adding a book:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by patricekaratchentzeff** [comment]
Here is the log file :

calibre Journal de débogage
calibre 4.23  embedded-python: True is64bit: True
Linux-5.4.0-42-generic-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-42-generic', '#46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020')
Python 2.7.16
Linux: ('debian', 'bullseye/sid', '')
Interface language: fr
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23  embedded-python: True is64bit: True
Linux-5.4.0-42-generic-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-42-generic', '#46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020')
Python 2.7.16
Linux: ('debian', 'bullseye/sid', '')
Interface language: fr
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 157.825242718 x 158.566473988
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.95] main UI initialized...
[0.95] Hiding splash screen
[17.25] splash screen hidden
[17.25] Started up in 17.25 seconds with 9 books
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 960, resource id: 14148778, major code: 40 (TranslateCoords), minor code: 0
['zenity', '--modal', '--file-selection', '--title=Livres s\xc3\xa9lectionn\xc3\xa9s', '--separator=\n', '--attach=77594647', '--filename=/home/pk/T\xc3\xa9l\xc3\xa9chargements/.fgdfg.gdfhjdhf*&^839', '--file-filter=Livres | *.lrf *.rar *.zip *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf', '--file-filter=Livres EPUB | *.epub *.kepub', '--file-filter=Livres Kindle | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=Livres PDF | *.pdf *.azw4', '--file-filter=Livres HTML | *.htm *.html *.xhtm *.xhtml', '--file-filter=Livres LIT | *.lit', '--file-filter=Livres texte | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Bandes Dessin\xc3\xa9es | *.cbz *.cbr *.cbc', '--file-filter=Archives | *.zip *.rar', '--file-filter=Fichiers du traitement de texte | *.odt *.doc *.docx', '--file-filter=Tous les fichiers | *', '--multiple']
DeDRM v6.8.0: Trying to decrypt B08Q8HCZGR_EBOK(1).azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Le Premier Signe d'une vie intelligente extraterrestre (French Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.8.0: Running kindlekey.py under Wine
DeDRM v6.8.0: Command line: 'wine python.exe "/home/pk/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/pk/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
0009:err:module:__wine_process_init L"C:\\windows\\system32\\python.exe" not found
DeDRM v6.8.0: Found and decrypted 0 key files
DeDRM v6.8.0: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Le Premier Signe d'une vie intelligente extraterrestre (French Edition) to db in: 0.3
Added 1 books in 11.8 seconds
Worker Launch took: 0.189940929413

**Comment by ElleKayEm** [comment]
Looks like you haven't imported the keys from your Windows VM setup.

> Found 0 keys to try after 0.1 seconds

**Comment by patricekaratchentzeff** [comment]
The shame on me ! I don't understand why. Calibre (on windows) is OK, because it runs. I exported the keys from deDRM plug-ins, then imported. Is there a special procedure? I did all from the plug-in (that have found automaticity the keys in Windows).

**Comment by patricekaratchentzeff** [comment]
Simple question : is it possible to check the keys by showing them in viewable way in the plug-in? I get only a symbolic name key, not the internal value. Thanks.

**Comment by ElleKayEm** [comment]
No special process -- just save the default_key.k4i from the Window setup and import into the Linux setup.  Be sure to click ok and apply on your way out of the dialog boxes.  Then restart calibre before adding books.

You can see the saved keys by going to Preferences > Miscellaneous > Open calibre's configuration directory.  Then look in the plugins folder for the dedrm.json file.  Both this and the .k4i file are text files.  If you look in the .json file, you should see a section for "kindle keys" which should have the info from the .k4i file.

**Comment by patricekaratchentzeff** [comment]
The shame on me bis! I tried again by reimporting keys and that runs now!

Thanks for all explanation and for your super job!
