### ISSUE TITLE
Adobe DE ebooks from HPE not able to decrype 

### ISSUE THREAD

**Issue by Miles234234** [apprenticeharper/DeDRM_tools#153]
Seems there are some Changes in this Kind of Ebooks, unable to convert them to PDF.

says also something with Unicode Error in Calibre.
Need more Information. Worked till October without Problems. with other Books (they work also still now) Tried also with the latest Calibre Version.

Thanks for this Tool.

----
piped data from file dialog helper: ['-', 'C:\\Users\\*******\\HPE *****.epub']

DeDRM v6.5.2: Trying to decrypt HPE *****.epub

DeDRM v6.5.2: Verifying zip archive integrity

DeDRM v6.5.2: “HPE ******.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub

Running file type plugin DeDRM failed with traceback:

Traceback (most recent call last):

  File "site-packages\calibre\customize\ui.py", line 161, in _run_filetype_plugins

  File "calibre_plugins.dedrm.__init__", line 620, in run

  File "calibre_plugins.dedrm.__init__", line 396, in ePubDecrypt

DeDRMError: DeDRM v6.5.2: Couldn't decrypt after 0.4 seconds. DRM free perhaps?

Added HPE  ******* to db in: 0.4

Added 1 books in 2.1 seconds

stdout+stderr from file dialog helper: ['', '']

piped data from file dialog helper: ["-", 'C:\\Users\\ *******\\HPE  *******.epub']

DeDRM v6.5.2: Trying to decrypt HPE *****.epub

DeDRM v6.5.2: Verifying zip archive integrity

DeDRM v6.5.2: “HPE  ******* *******.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub

Running file type plugin DeDRM failed with traceback:

Traceback (most recent call last):

  File "site-packages\calibre\customize\ui.py", line 161, in _run_filetype_plugins

  File "calibre_plugins.dedrm.__init__", line 620, in run

  File "calibre_plugins.dedrm.__init__", line 396, in ePubDecrypt

DeDRMError: DeDRM v6.5.2: Couldn't decrypt after 0.4 seconds. DRM free perhaps?

**Comment by ElleKayEm** [comment]
That file isn't being recognized as having Adobe Adept DRM.  Did you download this with a more recent version of ADE than 2.0.1?  That book vendor might have switched to the newer DRM that hasn't been figured out.

**Comment by Miles234234** [comment]
hello, have ADE 3.0 and 4.x installed, no 2.x and i was able to open other Ebooks before without Problems.
so something has changed inbetween.

**Comment by ElleKayEm** [comment]
Try downloading it with ADE 2.0.1.

**Comment by Miles234234** [comment]
reinstalled ADE 2.0.1, reautorized it, but it always now says: e_adept_core decrypt license key Problem with License Key server... Don`t understand why some Books have worked with ADE 3.x and now are there Problemes, and can`t download it again with ADE 2.0.1?

**Comment by ElleKayEm** [comment]
ADE 2.0.1 can only handle the older DRM method.  ADE 3 and newer can handle both old and new DRM encryption.  If you're using ADE 3 or newer and an ebook store switches to the new encryption, you won't know until you try to remove DRM and can't.  Once you've downloaded a book which has this new encryption, you won't be able to download another copy of that book with the old encryption.  Some ebook stores have switched exclusively to the new DRM.  These tools cannot remove it, and I haven't heard that it has been figured out at all yet.

**Comment by Miles234234** [comment]
that is really bad.. older bought books still work. and can be downloaded...

**Comment by ElleKayEm** [comment]
I think if a book was originally downloaded with the older DRM, new copies will have still have the old DRM.  Stick with ADE 2.0.1 and you know if it downloads, then you can remove the DRM.

**Comment by apprenticeharper** [comment]
ElleKayEm has it exactly right. From the FAQs:

"Do NOT use Adobe Digital Editions 3.0 or later to download your ePubs. ADE 3.0 and later might use a new encryption scheme that the tools can't handle. While major ebook stores aren't using the new scheme yet, using ADE 2.0.1 will ensure that your ebooks are downloaded using the old scheme. Once a book has been downloaded with the new scheme, it's IMPOSSIBLE to re-download using the old scheme (without buying it again)."
