### ISSUE TITLE
[QUESTION] Build a Python package to download ebooks / Remove kfx encryption

### ISSUE THREAD

**Issue by mkb79** [apprenticeharper/DeDRM_tools#1534]
I've wrote a Python app (which is not finally ready yet) wich let you download Kindle ebooks. The app simulate a iOS Kindle app. How I can add books downloaded with this app to calibre. I tried DeDRM already. But there are some missing keys (pids) I think.

Books downloaded with my app contains a voucher file, some azw9 and azw8 files and a metadata file wich contains "DRMION". One file content starts with "CONT" and contains some words like kfxgen.positionMaps, kfxgen.textBlock, PackageVersion:YJReaderSDK-1.0.x.x GitSHA ...

The app can be found on [Github](https://github.com/mkb79/kindle)

Can someone help me?

**Comment by ElleKayEm** [comment]
I haven't heard that decryption of books from the Kindle iOS app has been figured out.  DeDRM just works with Kindle for PC/Mac and E-ink Kindles.

**Comment by j-howell** [comment]
You are describing KFX format. That is the main format used for books delivered to the Kindle for iOS app, although older formats such as MOBI and KCR are used for some books.

You are likely to have a problem with DRM. All books in KFX format have DRM applied by Amazon. The current DeDRM plugin release cannot handle KFX DRM V4 which is currently in use. A future version may be able to do so. You will need to discover the lock parameters which are different for each registered Kindle app or device. I don't know if anyone has figured out what Kindle for iOS uses. You will probably be on your own for that.

If you manage to remove the DRM then the optional KFX Input plugin for calibre can be used to convert to other formats. Put all of the files associated with the book in the same folder and then import the azw8 file into calibre. The plugin will combine the files and handle conversion.

**Comment by mkb79** [comment]
Thank you for your information. When using my app you have to register a new Kindle device. Registering a new device gives me some additional information like serial, device type, etc. Maybe this is the key to decrypt the books.

PS:
The new Audible aaxc encryption uses a key/iv pair generated from serial, device type, asin and customer id. Maybe this appens for kfx v4 books too?!

**Comment by mkb79** [comment]
After some time of research I found out the following:

I parsed the voucher file which gives me

```python
outer_voucher = {
    "strategy": {
        "lock_parameters": ["CLIENT_ID"],
        "encryption_algorithm": "AES",
        "encryption_transformation": "AES/CBC/PKCS5Padding",
        "hashing_algorithm": "HmacSHA256"
    },
    "mac": b"...",
    # the mac value is a binary with a length of 32
    "voucher": b"..."
    # the voucher value is a ion binary with a length of 741
    # for the parsed voucher see inner_voucher
}


inner_voucher = {
    "id": "amzn1.drm-voucher.v1.4...",
    # the id value is a string with a length of 57
    'cipher_iv': b"...",
    # the cipher_iv value is a binary with a length of 16
    'cipher_text': b"...",
    # the cipher_text value is a binary with a length of 512
    'license': {
        "license_type": "Purchase"
    },
    "categorized_metadata": [
        {
            "category": "client_restrictions",
            "metadata": [
                {
                    "key": "ClippingLimit",
                    "value": "10"
                },
                {
                    "key": "TextToSpeechDisabled",
                    "value": "false"
                }
            ]
        }
    ]
}
```

I tried to decrypt the cipher_text from inner_voucher with the dedrm v7.0.3 plugin. I used the class dedrm.ion.DrmIonVoucher therefore. For the dsn I put my device_serial in and the secret with a empty list. As far as I read the source code, the secret is only used, if the lockparam is ACCOUNT_SECRET. But my is CLIENT_ID, so I only need the dsn.

The decrypt result doesn't give me a valid ion bytes structure which can be parsed (the beginning bytes are not ion typical). I saw that dedrm.ion.DrmIonVoucher.decryptvoucher() uses pkcs7unpadding, but my is padded with pkcs5. But this shouldn't matter at this point.

Maybe my device serial must be prepared in some ways? Can someone help at this point?

Best regards.

**Comment by ElleKayEm** [comment]
This is beyond me.  But device serial numbers are used in decryption of books from E-ink Kindles.  Whereas books from a Kindle Fire can't be decrypted in the same way.  There was a brief period where it was possible to extract information from backup of the Android Kindle app to decrypt books from it, but Amazon shut off the ability to make that backup.

**Comment by mkb79** [comment]
I could successfully decrypt my voucher file now. Thank you all for your help.

**Comment by ElleKayEm** [comment]
Would it be possible with this info to add decryption of iOS Kindle app books to DeDRM?

**Comment by mkb79** [comment]
The solution was [this](https://github.com/apprenticeharper/DeDRM_tools/pull/1490) PR and the device serial. Then I could decrypt my book with dedrm.kfxdrm. KFXZipBook. processBook(["DEVICE_SERIAL"])!

**Comment by mkb79** [comment]
I‘ve found a better solution for now. My package downloads the voucher version V1 only for now. So the Book can be decrypted with current dedrm v7.0.3 and the device_serial.
