### ISSUE TITLE
DeDRM does not work on new Kindle book

### ISSUE THREAD

**Issue by davidwhastings** [apprenticeharper/DeDRM_tools#154]
I have DeDrm'd numerous Kindle books previously but my latest books do not work.  Below is the information for one.
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\david>calibre-debug -g
calibre 2.72  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Qt: Untested Windows version 10.0 detected!
Successfully initialized third party plugins: DeDRM (6, 5, 2)
devicePixelRatio: 1.0
logicalDpi: 144.0 x 144.0
physicalDpi: 160.421052632 x 159.026086957
Starting up...
Started up in 2.51 seconds with 457 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xa6C\xd1\xc0g$$d\x85\xf0az\x19A@'\xbez\x03\xb3m6\x89[\x9b\xd4\n\xd0\x047\xfd\x95", '\\\\DS\\Data\\Scanner\\B00I9CAW6S_EBOK.azw']
DeDRM v6.5.2: Trying to decrypt B00I9CAW6S_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Java EE Architect���s Handbook, Second Edition: How to be a successful application architect for Java EE applications
Found 8 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.5.2: Failed to decrypt with error: No key found in 8 keys tried.
DeDRM v6.5.2: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\david\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\david\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2158650209' and UserName '4461766964'
DeDRM v6.5.2: Found 1 new key
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Java EE Architect���s Handbook, Second Edition: How to be a successful application architect for Java EE applications
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.5.2: Ultimately failed to decrypt after 0.5 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 161, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.5 seconds
Added The Java EE Architect’s Handbook, Second Edition: How to be a successful application architect for Java EE applications to db in: 0.2
Added 1 books in 1.5 seconds
Worker Launch took: 0.110000133514
Job: 1 Convert book 1 of 1 (The Java EE Architect’s Handbook, Second Edition: How to be a successful application architect for Java EE applications) finished
Convert book 1 of 1 (The Java EE Architect’s Handbook, Second Edition: How to be a successful application architect for Java EE applications)
        Resolved conversion options
        calibre version: 2.72.0
        {'asciiize': False,
         'author_sort': None,
         'authors': None,
         'base_font_size': 0.0,
         'book_producer': None,
         'change_justification': u'original',
         'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
         'chapter_mark': u'pagebreak',
         'comments': None,
         'cover': u'C:\\Users\\david\\AppData\\Local\\Temp\\calibre_tgtsfz\\0mcaan.jpeg',
         'debug_pipeline': None,
         'dehyphenate': True,
         'delete_blank_paragraphs': True,
         'disable_font_rescaling': False,
         'dont_split_on_page_breaks': False,
         'duplicate_links_in_toc': False,
         'embed_all_fonts': False,
         'embed_font_family': None,
         'enable_heuristics': False,
         'epub_flatten': False,
         'epub_inline_toc': False,
         'epub_toc_at_end': False,
         'expand_css': False,
         'extra_css': None,
         'extract_to': None,
         'filter_css': u'',
         'fix_indents': True,
         'flow_size': 260,
         'font_size_mapping': None,
         'format_scene_breaks': True,
         'html_unwrap_factor': 0.4,
         'input_encoding': None,
         'input_profile': <calibre.customize.profiles.InputProfile object at 0x046C8F70>,
         'insert_blank_line': False,
         'insert_blank_line_size': 0.5,
         'insert_metadata': False,
         'isbn': None,
         'italicize_common_cases': True,
         'keep_ligatures': False,
         'language': None,
         'level1_toc': None,
         'level2_toc': None,
         'level3_toc': None,
         'line_height': 0.0,
         'linearize_tables': False,
         'margin_bottom': 5.0,
         'margin_left': 5.0,
         'margin_right': 5.0,
         'margin_top': 5.0,
         'markup_chapter_headings': True,
         'max_toc_links': 50,
         'minimum_line_height': 120.0,
         'no_chapters_in_toc': False,
         'no_default_epub_cover': False,
         'no_inline_navbars': False,
         'no_svg_cover': False,
         'output_profile': <calibre.customize.profiles.GenericEink object at 0x045FA190>,
         'page_breaks_before': u"//*[name()='h1' or name()='h2']",
         'prefer_metadata_cover': False,
         'preserve_cover_aspect_ratio': False,
         'pretty_print': True,
         'pubdate': None,
         'publisher': None,
         'rating': None,
         'read_metadata_from_opf': u'C:\\Users\\david\\AppData\\Local\\Temp\\calibre_tgtsfz\\7u2m1a.opf',
         'remove_fake_margins': True,
         'remove_first_image': False,
         'remove_paragraph_spacing': False,
         'remove_paragraph_spacing_indent_size': 1.5,
         'renumber_headings': True,
         'replace_scene_breaks': u'',
         'search_replace': '[]',
         'series': None,
         'series_index': None,
         'smarten_punctuation': False,
         'sr1_replace': None,
         'sr1_search': None,
         'sr2_replace': None,
         'sr2_search': None,
         'sr3_replace': None,
         'sr3_search': None,
         'start_reading_at': None,
         'subset_embedded_fonts': False,
         'tags': None,
         'timestamp': None,
         'title': None,
         'title_sort': None,
         'toc_filter': None,
         'toc_threshold': 6,
         'toc_title': None,
         'transform_css_rules': '[]',
         'unsmarten_punctuation': False,
         'unwrap_lines': True,
         'use_auto_toc': False,
         'verbose': 2}
        InputFormatPlugin: MOBI Input running
        on C:\Users\david\AppData\Local\Temp\calibre_tgtsfz\ahtwm3.azw
        Found KF8 MOBI of type 'standalone'
        Python function terminated unexpectedly
          The Java EE Architect’s Handbook, Second Edition: How to be a successful application architect for Java EE applications (Error Code: 1)
        Traceback (most recent call last):
          File "site.py", line 132, in main
          File "site.py", line 109, in run_entry_point
          File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
          File "site-packages\calibre\ebooks\conversion\plumber.py", line 1064, in run
          File "site-packages\calibre\customize\conversion.py", line 245, in __call__
          File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
          File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
          File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 146, in check_for_drm
        calibre.ebooks.DRMError: The Java EE Architect’s Handbook, Second Edition: How to be a successful application architect for Java EE applications

[B00I9CAW6S_EBOK.zip](https://github.com/apprenticeharper/DeDRM_tools/files/601553/B00I9CAW6S_EBOK.zip)

**Comment by davidwhastings** [comment]
Never mind, I launched the Kindle app on the same computer as Calibre and imported the book directly from its Kindle Content library and it worked.  Previously I copied the book from another computer's Kindle Content library into Calibre which apparently caused it not to work.

**Comment by ElleKayEm** [comment]
Yup, every kindle device/app has its own key even when signed into the same account.
