### ISSUE TITLE
[QUESTION] Key Migration Required From 6.8.1 -> 7.1.0?

### ISSUE THREAD

**Issue by AdmiralAsshat** [apprenticeharper/DeDRM_tools#1543]
## CheckList

- [x] I have read the wiki.
- [x] I have searched for Closed Issues that relate to my question.

---

### DeDRM: `6.6.3`

Hello! I was originally asking this about the DeDRM 7.0.3 Beta, but I see you just released 7.1.0 which I assume is stable.

Nonetheless, my question stands:  I've held back on upgrading Calibre to 5.X until DeDRM had a compatible Python3 version. Now that one appears to be ready, I wanted to clarify whether installing 7.1.0 over 6.8.1 (or 6.6.3, in my case) will pick up all of the previous settings and the existing decryption keys from my Kindle.

I found #1347, where it suggested that one needs to export the keys from DeDRM 6.X and then re-import into 7.X, but this was between two computers, so I'm not sure how installing the new version on the same computer would work.

Thanks in advance! If any "migration" is necessary, I would suggest we add it to the Wiki.

**Comment by ElleKayEm** [comment]
No need to migrate if updating on the same machine.  Just update to the current calibre and load DeDRM 7.1.0.  All your saved keys should still be there.

**Comment by AdmiralAsshat** [comment]
Thanks! Update seemed to work, and I was able to decrypt a test Kindle file afterwards without a problem.
