### ISSUE TITLE
Invalid plugin 7.1.0

### ISSUE THREAD

**Issue by andersberglund** [apprenticeharper/DeDRM_tools#1544]
Calibre 5.11

Error when loading 7.1.0

InvalidPlugin: DeDRM_tools_7.1.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip it and load just the plugin.

**Comment by AdmiralAsshat** [comment]
`DeDRM_tools_7.1.0.zip` that you grab from the Releases section contains five or so files inside it:

- DeDRM_plugin.zip
- DeDRM_plugin_ReadMe.txt
- Obok_plugin.zip
- obok_plugin_ReadMe.txt
- ReadMe_Overview.txt

It's the `DeDRM_plugin.zip` file that you will want to pick when installing the Plugin via Calibre.

**Comment by andersberglund** [comment]
Thanks, that worked, but have not had to do it with previous versions.

**Comment by ElleKayEm** [comment]
The betas were plugin only and this is a full release.

**Comment by ElleKayEm** [comment]
@andersberglund If you're all set, you can close the issue
