### ISSUE TITLE
Calibre 0.7.28 + Plugin + PowerPC Mac = Not recognized

### ISSUE THREAD

**Issue by mrkapqa** [apprenticeharper/DeDRM_tools#155]
Hello ,

i tried these tools DeDRM with Powerpc - it would not get recognized as valid plugin.

Did i do something wrong or has a newer Version of Calibre to be used in order to make them operative?

thanks
richard

**Comment by ElleKayEm** [comment]
I think you're right, but be sure you're loading the actual DeDRM calibre plugin and not the whole tools archive.
