### ISSUE TITLE
DeDRM_plugin.zip cannot be found inside DeDRM_calibre_plugin folder

### ISSUE THREAD

**Issue by Goldenangel3341** [apprenticeharper/DeDRM_tools#1552]
Hello. I'm using Windows 10 and the kindle app. I would like to buy Japanese books and read them on my English Kindle without switching to a created Japanese account.

I'm following the instructions and get stuck on number 7.

"Select the DeDRM_plugin.zip file in that folder"
I cannot find this file. 
thanks.

**Comment by ElleKayEm** [comment]
Sounds like you're following outdated instructions.  If you're using calibre 5.x, then you need [DeDRM 7.1.0](https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v7.1.0).  Download DeDRM_tools_7.1.0.zip
 and unzip it.  You will find DeDRM_plugin.zip directly inside there.
