### ISSUE TITLE
2 questions from this non-tech person. 

### ISSUE THREAD

**Issue by Skye63** [apprenticeharper/DeDRM_tools#1557]

**Comment by ElleKayEm** [comment]
Please close this issue.

**Comment by Skye63** [comment]
BTW, the questions I was unable to type into the box, were:

1.      If I add the new DeDRM, do I need to somehow delete the previous DeDRM version?

2.      If so, after I add the new one, or before; and in either case – how? 

3.      Thanks for any help.

 

Steve

**Comment by ElleKayEm** [comment]
No need to remove previous.  Just load the new.

**Comment by Skye63** [comment]
If I could find a “close issue button” I would be happy to close it. As I said, I cannot find a delete (or “close it”) button. WHERE IS IT???

**Comment by ElleKayEm** [comment]
Follow the link from the email back to GitHub and look near the top of the page.
