### ISSUE TITLE
2 questions on installing deDRM om y Win PC

### ISSUE THREAD

**Issue by Skye63** [apprenticeharper/DeDRM_tools#1558]

**Comment by ElleKayEm** [comment]
Please close this issue.

**Comment by Skye63** [comment]
Sorry for the trouble. As you see I couldn’t even finish the questions I wanted to ask … either time I tried.

I’d be delighted to delete the two. I tried left and right clicking on everything to find a delete somewhere. Couldn’t find it.

I give up. Tell me how to delete the “issue”.

Sorry

**Comment by ElleKayEm** [comment]
As the opening poster, you should see a close issue button.

**Comment by ElleKayEm** [comment]
Don't forget this one.
