### ISSUE TITLE
Single Book DeDRM Failure

### ISSUE THREAD

**Issue by perrinaz** [apprenticeharper/DeDRM_tools#1561]
I have many books that DeDRM'd properly today and 2 books that would not DeDRM properly.  I attempted with Calibre v4 and the latest (6.8) plugin and Calibre v5 and the latest plugin (7.1).  When I put Calibre into debug mode, one of the books DeDRM'd properly.  Here is the log from the book that did not.  Log is from Calibre 5 & 7.1.0 downloaded to Kindle for PC 1.24.3 (Windows 10).  The book is large and I suspect it's a memory issue.  Identifying information has been redacted.

calibre Debug log
calibre 5.12 Portable embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 5.12 Portable embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 141.4020618556701
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[14.59] splash screen shown
[14.59] Initializing db...
[15.14] db initialized
[15.14] Constructing main UI...
[18.61] main UI initialized...
[18.61] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing C:\Users\xxxxxxxx\Documents\My Kindle Content\B084GC1D43_EBOK\B084GC1D43_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.1.0: Trying to decrypt B084GC1D43_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
[78.78] splash screen hidden
[78.78] Started up in 78.78 seconds with 533 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xbb\x92F\x12H\x98\r\xf2\xe42\x08\xc8\x18\t\x01w\x03\x9d`\xf3yg\x9e.\x9b\xc3\xe1\x04\xcd\x87\x9b\xca', b'C:\\Users\\xxxxxxxx\\Documents\\My Kindle Content\\B084GC1D43_EBOK\\B084GC1D43_EBOK.azw']
DeDRM v7.1.0: Failed to decrypt with error: tuple index out of range
DeDRM v7.1.0: Looking for new default Kindle Key after 9.8 seconds
searching for kinfoFiles in C:\Users\xxxxxxxx\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\xxxxxxxx\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString 'xxxxxxxxxx' and UserName 'xxxxxxxx'
DeDRM v7.1.0: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
DeDRM v7.1.0: Ultimately failed to decrypt after 10.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added WONDERLAND Digital Omnibus Vol. 1 to db in: 27.4
Added 1 books in 44.0 seconds
Worker Launch took: 0.05 seconds
Job: 0 Convert book 1 of 1 (WONDERLAND Digital Omnibus Vol. 1) finished
Convert book 1 of 1 (WONDERLAND Digital Omnibus Vol. 1)

	DeDRM v7.1.0: Trying to decrypt ranme1or.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.1.0: Failed to decrypt with error: tuple index out of range
	DeDRM v7.1.0: Looking for new default Kindle Key after 1.0 seconds
	searching for kinfoFiles in C:\Users\xxxxxxxx\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\xxxxxxxx\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString 'xxxxxxxxxx' and UserName 'xxxxxxxx'
	DeDRM v7.1.0: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.1.0: Ultimately failed to decrypt after 1.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  verbose: 2

	  read_metadata_from_opf: 'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\calibre_6o2wi_2x\\cycmv1jr.opf'

	  output_profile: 'tablet'

	  cover: 'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\calibre_6o2wi_2x\\4sz3bd6l.jpeg'

	Resolved conversion options

	calibre version: 5.12.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\calibre_6o2wi_2x\\4sz3bd6l.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_compress': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x07AB8910>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'mobi_file_type': 'old',

	 'mobi_ignore_margins': False,

	 'mobi_keep_original_images': False,

	 'mobi_toc_at_start': False,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'no_inline_toc': False,

	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x07AB8D90>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'personal_doc': '[PDOC]',

	 'prefer_author_sort': False,

	 'prefer_metadata_cover': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\calibre_6o2wi_2x\\cycmv1jr.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'share_not_sync': False,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.mobidedrm", line 319, in __init__

	  File "calibre_plugins.dedrm.mobidedrm", line 377, in patchSection

	  File "calibre_plugins.dedrm.mobidedrm", line 367, in patch

	MemoryError

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 217, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 326, in __init__

	IndexError: tuple index out of range

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 631, in run

	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 1.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	DeDRM v7.1.0: Trying to decrypt ranme1or.azw
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.1.0: Failed to decrypt with error: tuple index out of range
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.9 seconds
	searching for kinfoFiles in C:\Users\xxxxxxxx\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\xxxxxxxx\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString 'xxxxxxxxxx' and UserName 'xxxxxxxx'
	DeDRM v7.1.0: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.1.0: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.mobidedrm", line 319, in __init__

	  File "calibre_plugins.dedrm.mobidedrm", line 377, in patchSection

	  File "calibre_plugins.dedrm.mobidedrm", line 367, in patch

	MemoryError

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 217, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 326, in __init__

	IndexError: tuple index out of range

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 631, in run

	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\xxxxxxxx\AppData\Local\Temp\calibre_6o2wi_2x\ranme1or.azw

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm

	calibre.ebooks.DRMError: WONDERLAND Digital Omn
us Vol. 1

**Comment by ElleKayEm** [comment]
Give 64-bit calibre a try.

**Comment by perrinaz** [comment]
Well, 64bit works.  Sucks to have to have two different versions installed but size matters.

**Comment by ElleKayEm** [comment]
Why not just use 64-bit?  If you're all set, you can close the issue.

**Comment by perrinaz** [comment]
Because I share my libraries across multiple computers, so I use Calibre portable
