### ISSUE TITLE
APPLICATION NOT FOUND KFX-ZIP PROBLEM ADE WORKS FINE

### ISSUE THREAD

**Issue by srlevine1** [apprenticeharper/DeDRM_tools#1563]
WINDOWS VERSION: 10 ( X-64) BUILD 10942 (INDICATED IN SYSTEM DETAILS)
KINDLE VERSION: 1.30.0
CALIBRE VERSION: 5.12.0
DEDRM VERSION: 7.1.0

No import error, on open of kfx-zip file after conversion -- application not found
--------------------------------------------------------------
calibre, version 5.12.0
ERROR: Unhandled exception: <b>OSError</b>:[WinError -2147221003] Application not found: 'C:\\Users\\DEVELOPMENT\\Documents\\Calibre Library\\Edith MacKenzie\\The Wounded Cowboy Billionaire_ A c (9881)\\The Wounded Cowboy Billionaire_ - Edith MacKenzie.kfx-zip'

calibre 5.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 36, 0) && APNX Generator (1, 1, 0) && Count Pages (1, 11, 0) && Find Duplicates (1, 8, 5) && Generate Cover (2, 0, 2) && Job Spy (1, 0, 190) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0) && KindleUnpack - The Plugin (0, 83, 0) && Media File Importer (1, 0, 24) && Obok DeDRM (7, 1, 0) && Prettify Cover (1, 5, 0) && Save To Format (0, 0, 6)
Traceback (most recent call last):
  File "calibre\gui2\actions\view.py", line 295, in view_triggered
  File "calibre\gui2\actions\view.py", line 372, in _view_books
  File "calibre\gui2\actions\view.py", line 324, in _view_calibre_books
  File "calibre\gui2\actions\view.py", line 150, in view_format_by_id
  File "calibre\gui2\actions\view.py", line 206, in _view_file
  File "calibre\gui2\actions\view.py", line 196, in _launch_viewer
  File "calibre\gui2\__init__.py", line 1297, in open_local_file
OSError: [WinError -2147221003] Application not found: 'C:\\Users\\DEVELOPMENT\\Documents\\Calibre Library\\Edith MacKenzie\\The Wounded Cowboy Billionaire_ A c (9881)\\The Wounded Cowboy Billionaire_ - Edith MacKenzie.kfx-zip'

**Comment by srlevine1** [comment]
Fixed the Application Not Found Error by Checking the Use Internal Viewer Box for KFX-ZIP located in Preferences->Behavior.
However, all KFX-ZIP files do not decrypt or open -- showing the "This book is locked by DRM" dialogue on opening with Calibre 5.12 internal viewer. This applies to all newly-imported files AND NOW the older imported files from the older version.

**Comment by ElleKayEm** [comment]
For KFX format, use Kindle for PC 1.26 or earlier.  Alternatively, disable KFX downloads.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by srlevine1** [comment]
Thank you for your kind response... 

I am using Kindle 1.24.3 -- and I noticed something that may or may not be significant. The failure to decrypt and the storage of the kfx-zip in the database appears to ONLY happen when those titles are flagged as "Prime" in the Amazon content and devices list. Everything else works.

**Comment by ElleKayEm** [comment]
If you're talking about borrowed titles from Prime Reading or Kindle Unlimited, that is as intended.  These tools are for purchased books.

**Comment by srlevine1** [comment]
Thank you for the clarification.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by srlevine1** [comment]
Thank you again ElleKayEm.
