### ISSUE TITLE
Sample Amazon Book - Cannot DRM Topaz Format - no metadata record

### ISSUE THREAD

**Issue by ApprenticeDRM** [apprenticeharper/DeDRM_tools#1568]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title

B007IDTLL6 EBSP - Unknown.azw

### DeDRM: `7.1`

I cannot upload the log section because the body becomes too long to be submitted. May I send you an email?

</details>

**Comment by ElleKayEm** [comment]
Attach the text file of the log.  You might try calibre 4.23 and DeDRM 6.8.1.

**Comment by ApprenticeDRM** [comment]
Ok solved. I managed to upload it with the above versions mentioned by you. Thank you. The format turned to be an HTMLZ.

**Comment by ElleKayEm** [comment]
Yes, that's what happens with topaz format when DRM is successfully removed.  DeDRM 7.1.0 apparently needs a little more work in that area.

No, the Apprentices don't accept donations.

If you're all set, you can close the issue.
