### ISSUE TITLE
I am not able to DeDMR this book

### ISSUE THREAD

**Issue by esanjuanp** [apprenticeharper/DeDRM_tools#157]
Hello,

I installed the DeDMR plugging for caliber but I am not able to deDMR this book. I added the serial number for both Kindle devices. I do not know what I am doing wrong. Could you help me?

Thanks in advance.

calibre Registro de depuración
calibre 2.17 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 19.22 seconds with 5 books
DeDRM v6.5.2: Trying to decrypt B009CFOIT8_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: The Lost Art of Common Sense in Chess (Master Chess Book 3)
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.2: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.2: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\esanjuanp\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.2: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.2 seconds
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added The Lost Art of Common Sense in Chess (Master Chess Book 3) to db in: 1.3
Added 1 books in 7.1 seconds
Worker Launch took: 0.461999893188
Worker Launch took: 0.384999990463

**Comment by ElleKayEm** [comment]
The books need to be from an E-ink Kindle or downloaded to Kindle for PC installed on the same machine and user as calibre.   If the book is from one of those Kindle devices (and it's E-ink, not a Fire), then double-check that you've entered the serial number correctly.  Otherwise, install Kindle for PC on this machine, download the book with that installation, and import that copy.

**Comment by esanjuanp** [comment]
Thank you, I will try again downloading from the same machine as Calider is installed. Maybe that is the problem.

Thanks!
