### ISSUE TITLE
Barnes & Noble ePub Keyfile Fetch v1.1 keyfile fetch failed

### ISSUE THREAD

**Issue by mtdew365** [apprenticeharper/DeDRM_tools#158]
Computer is running Fedora 25.  Just downloaded a fresh copy from here.  Run program and returns "Keyfile fetch failed."  I am using the correct e-mail and password.  I try using another family member account and that works.  I have special characters in my pasword i.e. %@#<>!./)*

I have tried to escape them but I am doing it wrong or it still is not correct.  Any help would be appreciated.

**Comment by ElleKayEm** [comment]
I've seen this happen before, and they ended up changing their password to something without special characters.  The only other way I know to retrieve the key is through Nookstudy.

See this closed issue:
https://github.com/apprenticeharper/DeDRM_tools/issues/54

**Comment by apprenticeharper** [comment]
If you discover how to correctly encode the special characters in your password, it would be good to hear. But perhaps it's simpler to temporarily change your password to something without special characters. (The key is account-based, and does not change if you change your password.)
