### ISSUE TITLE
Obok 7.1 not working with Calibre 5.12 - no userkeys found to decrypt books with.

### ISSUE THREAD

**Issue by Reindrelle** [apprenticeharper/DeDRM_tools#1580]
Using the following:
Calibre 5.12 
Obok 7.1
Kobo Desktop 4.26.14705
all installed on same PC (Windows 10), I run in the following error whenever I click on "Obok" icon, "Obok DeDRM v7.1.0: No userkeys found to decrypt books with. No point in proceeding."
I tried to uninstall Obok plugin and install it again, but the error remained.

I then proceeded to install on the same PC a portable version of Calibre (version 4.23) and I installed the "old" 6.8 Obok plugin. In this case, the plugin worked correctly, and I was able to retrieve Kobo Ebooks.

**Comment by ElleKayEm** [comment]
A few other reports here of issues with Obok.  There is currently a pull request which may address it.  I am having no issues with calibre 5.12 and Obok 7.1.0.  Also on Windows 10 with that version of Kobo Desktop.

**Comment by Connor1745** [comment]
I'm having the same problem on my mac macOS 11.1 with Calibre 5.12 and Obok DeDRM v7.1.0.

**Comment by Reindrelle** [comment]
Just wanted to confirm that with the latest version of Obok plugin the issue has been resolved. Thank you all.

**Comment by ElleKayEm** [comment]
Obok 7.1.0 works for me on Windows 10, but 7.2.1 does not.

**Comment by theboomr** [comment]
> Obok 7.1.0 works for me on Windows 10, but 7.2.1 does not.

I just recently finally updated to Calibre 5.x, and downloaded the latest 7.2.1 DeDRM release to go with it. I also was having the "userkeys not found" error after installing 7.2.1 version of Obok, and after reading this comment, I downloaded version 7.1.0, and that is working properly for me. For the record, I'm on Windows 11, running Calibre 5.34 64-bit.

**Comment by ElleKayEm** [comment]
Try noDRM's Obok 10.0.2.  Available here:  https://github.com/noDRM/DeDRM_tools

**Comment by theboomr** [comment]
> Try noDRM's Obok 10.0.2. Available here: https://github.com/noDRM/DeDRM_tools

Thank you! That works great :) Wasn't aware it existed before but now I've got it starred
