### ISSUE TITLE
DRM doesn't work with bought Amazon ebooks using : Windows 10 - Calibre 5.12 - DeDRM_tools_7.1.0

### ISSUE THREAD

**Issue by richardhorus64** [apprenticeharper/DeDRM_tools#1584]
Please let me know what should I do to make the plugin work? Here is the debug mode info:

calibre-debug -g
calibre 5.11  embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Find Duplicates (1, 8, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 91.84180790960451 x 91.7458193979933
Using calibre Qt style: False
[0.00] Starting up...
[0.00] Showing splash screen...
[0.47] splash screen shown
[0.47] Initializing db...
[0.58] db initialized
[0.58] Constructing main UI...
[1.58] main UI initialized...
[1.58] Hiding splash screen
Starting QuickView
[2.05] splash screen hidden
[2.05] Started up in 2.05 seconds with 1612 books
Storage number map:
{(7, 0): [(4, 'C')], (7, 1): [(2, 'I')], (7, 2): [(1, 'D')], (7, 3): [(1, 'E')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\B0241604310709BG&0: StorageDeviceNumber(type=7, number=3, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=10)
{'drive_letters': ['E'],
 'pnp_id_map': {'E': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#b0241604310709bg&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'E': (3, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Restored 0 cover thumbnails that were destroyed by Amazon
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: E:\ documents
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'o\xd5YB76ny\x10$\x90&\xee\xfe\xf4.\r\xcag+:7\xc7]\x802\xa9^\xab\xb1\xaa\xb6', b'I:\\Download\\00 ebooks\\The Doll-Master_ And Other Tales of Terror_B01AGZ8LOK.azw3']
DEBUG:    0.3 USBMS: scan from root False E:\documents
DeDRM v7.1.0: Trying to decrypt The Doll-Master_ And Other Tales of Terror_B01AGZ8LOK.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Doll-Master: And Other Tales of Terror
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Richard\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DEBUG:    0.7 USBMS: count found in cache: 228, count of files in metadata: 228, need_sync: False
DEBUG:    0.7 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.7 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.7 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
Added The Doll-Master: And Other Tales of Terror to db in: 4.0
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 228
Added 1 books in 4.7 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeviceJob: set_books_in_library finished: time= 1.1566588878631592
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
Worker Launch took: 0.02 seconds
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x0cPT\x12\x8d8u\xa8\x0c"\xd6\x11\xc5\xf3m\x8e\xfd\xa2`\xbc\xea\x0f.\xa1\x90\xc3"t\tT\x94]', b'I:\\Download\\The Doll-Master_ And Other Tales of Terror.azw3']
DeDRM v7.1.0: Trying to decrypt The Doll-Master_ And Other Tales of Terror.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Doll-Master: And Other Tales of Terror
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Richard\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.1.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Doll-Master: And Other Tales of Terror to db in: 5.5
Added 1 books in 6.2 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Worker Launch took: 0.00 seconds
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x88\xd4\x16\xcf(\xe4\xb0\xf4\xe8\xef/\xd0\xf4\x92\tcm\x9b\xb9I\xed^\xceg\xedF\xa1\xa7\xcf"\xf2+', b'I:\\Download\\The Doll-Master_ And Other Tales of Terror (1).azw3']
DeDRM v7.1.0: Trying to decrypt The Doll-Master_ And Other Tales of Terror (1).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Doll-Master: And Other Tales of Terror
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Richard\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.1.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Doll-Master: And Other Tales of Terror to db in: 6.5
Added 1 books in 7.1 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Worker Launch took: 0.00 seconds

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then enter the Kindle's serial number in DeDRM's customization.

**Comment by richardhorus64** [comment]
It worked! Thanks ElleKayEm! :-)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
