### ISSUE TITLE
No key found in 4 keys tried. Failed to decrypt.

### ISSUE THREAD

**Issue by LuluSunflowr** [apprenticeharper/DeDRM_tools#159]
Hello Everyone!
I've been trying to figure this out for hours! I installed the new version of everything (calibre, DeDRM tool) and also made sure to deregister and register my amazon account to no success with this issue. It's all on the same machine. Any help is appreciated! Thanks!

My Log:
calibre Debug log
calibre 2.73  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 2) && KindleUnpack - The Plugin (0, 81, 2)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.569275362 x 100.55257732
Starting up...
Started up in 29.23 seconds with 29 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\x83\xe5.\x16}\xd7\x1bKm\xc9\x1bf\xa5\x95\xd7n\xf9\xbe\xcbpE\xcf\x98'\x98\xc8\xd8\xa6\xecq\xccF", 'C:\\Users\\Luiza Lovin\\Documents\\My Kindle Content\\B00MEP9RTO_EBOK.azw4']
DeDRM v6.5.2: Trying to decrypt B00MEP9RTO_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 248
Decrypting Mobipocket 4 ebook: Milady Standard Cosmetology ('013)
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.5.2: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.2: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\Luiza Lovin\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Luiza Lovin\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1425081027' and UserName '4c75697a61204c6f76696e'
DeDRM v6.5.2: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
DeDRM v6.5.2: Ultimately failed to decrypt after 0.6 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 161, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.6 seconds
Added Milady Standard Cosmetology ('013) to db in: 2.0
Added 1 books in 3.1 seconds
isEncrypted = True

**Comment by LuluSunflowr** [comment]
Solution found in post #137 . Installing the 64bit version of calibre and running it on there.

**Comment by apprenticeharper** [comment]
Perhaps I do need to catch the out of memory error separately. Hmmm......

Pull requests welcome!
