### ISSUE TITLE
DeDRM not removing DRM from PDF (OSX)

### ISSUE THREAD

**Issue by csongorb** [apprenticeharper/DeDRM_tools#1593]
Trying to remove Adobe DRM with DeDRM (7.1.0) on Mac OSX (10.14.6) in Calibre (5.11.0), but after the PDF is imported the DRM is still there. Worked before with 2 ePubs without any problems (purchased in the same way). Any recommendations?

calibre Debug log
calibre 5.11  embedded-python: True is64bit: True
macOS-10.14.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
calibre 5.11  embedded-python: True is64bit: True
macOS-10.14.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 128.00000192236715
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Initializing db...
[4.98] db initialized
[4.98] Constructing main UI...
[6.33] main UI initialized...
[6.33] Started up in 6.33 seconds with 1466 books
Starting QuickView
DeDRM v7.1.0: Trying to decrypt 0d5cd9c2-c287-4700-809c-ded7a8fad9d6.pdf
DeDRM v7.1.0: 0d5cd9c2-c287-4700-809c-ded7a8fad9d6.pdf is a PDF ebook
DeDRM v7.1.0: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.1.0: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.1.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.1.0: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.1.0: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 638, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 513, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 347, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Added 0d5cd9c2-c287-4700-809c-ded7a8fad9d6 to db in: 5.9
Added 1 books in 7.5 seconds

**Comment by ElleKayEm** [comment]
Try with calibre 4.23 and DeDRM 6.8.1.

**Comment by csongorb** [comment]
Yesss! Thanks, have worked without any issues!
