### ISSUE TITLE
kindlekey.py doesn't work

### ISSUE THREAD

**Issue by tylerMDDC** [apprenticeharper/DeDRM_tools#1599]
I get an error when trying to run kindlekey.py:

![uVQ5ftm](https://user-images.githubusercontent.com/50341934/110906766-6b52c500-82da-11eb-8a10-975d36963110.png)

----

Resolved this by installing Pycryptodome instead of Pycrypto

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by tylerMDDC** [comment]
Resolved this by installing Pycryptodome instead of Pycrypto
