### ISSUE TITLE
Format of keys in androidkindlekey.py isn't quite right

### ISSUE THREAD

**Issue by ableeker** [apprenticeharper/DeDRM_tools#16]
I believe the keys are calculated correctly, because I've been taken the values that are output, and  have been able to combine them manually into keys that will successfully decrypt my ebooks. However, the format the program uses to form the keys isn't quite right, and as a result the final keys aren’t valid. As it is now, they take the form “(None,)(u’abc’,)” or “(u’abc,)(u’xyz)”. The required format is in fact much simpler: it’s just “abc”, or “abcxyz”. (I found out that one of the values can be missing when combined into the final key.)

**Comment by apprenticeharper** [comment]
Thanks for the report. the android support is still a work in progress.

**Comment by apprenticeharper** [comment]
Fixed in current version.
