### ISSUE TITLE
Converting azw3 to PDF

### ISSUE THREAD

**Issue by eivanhoe** [apprenticeharper/DeDRM_tools#160]
Hi! I'm using the latest version of the deDRM tools. Unfortunately, only epub version is showing for my azw3 file.

Is it possible to convert it to pdf?

**Comment by ElleKayEm** [comment]
These tools remove DRM, but don't convert.  Calibre can convert AZW3 to PDF.  Are you looking at KindleUnpack?

**Comment by eivanhoe** [comment]
Yeah I'm pertaining to kindle unpack. It only shows KF8 to epub.

I was converting azw3 to pdf but it doesn't retain the format.

**Comment by ElleKayEm** [comment]
Extract the EPUB out of KF8 with KindleUnpack.  Then just use calibre to convert the EPUB to PDF.

**Comment by eivanhoe** [comment]
Yeah I already did that too. Format of the pdf looks like this

http://i.imgur.com/iY3ZkXo.jpg

**Comment by ElleKayEm** [comment]
PDF is probably the worst format to try to convert to or from.  You could try asking in the MobileRead calibre forum for advice on how to adjust conversion settings.
