### ISSUE TITLE
Manga not being handled correctly?

### ISSUE THREAD

**Issue by manoelpqueiroz** [apprenticeharper/DeDRM_tools#1604]
## Manga not being handled correctly?
I think #1051 has the same problem, but since he never posted a log, I'll do it properly. Searching for "manga" or "comic" in either Issues or Discussions didn't seem to point to a similar problem. I'm not sure if DeDRM is actually compatible with Kindle comics and manga, but in case the answer is no, would it be relevant to add it to the Wiki?

I'm not sure this is some problem with Calibre or DeDRM itself, but manga specifically (since they are the only ones I have) are imported to Calibre with some rendering issue. The cover imports just fine, but everything from there becomes "squished":

![image](https://user-images.githubusercontent.com/23669137/111240779-a30f8480-85da-11eb-8478-cdad2f203d6b.png)

While I thought it could be some issue related to the reading direction (in Kindle, manga are accordingly read by moving pages from right to left, just like their physical counterparts), but I had a normal book in Japanese that also used right-to-left reading and it imported just fine.

Haven't tried with Calibre 5.x and DeDRM 7.x, will attempt tomorrow to see if the outcome is different.

## Log
<details><summary>Log Title</summary>

```log
calibre Log de Debug
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 110.836363636 x 110.735694823
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[2.20] main UI initialized...
[2.20] Hiding splash screen
[32.53] splash screen hidden
[32.53] Started up in 32.53 seconds with 97 books
DeDRM v6.8.0: Trying to decrypt B00MGI1ZIA_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 生まれる価値のなかった自分がアンナのためにできるいくつかのこと：１
Got DSN key from database default_key
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
File is encoded with PID 6Dh0TwcH5Y.
Decrypting. Please wait . . . done
Decryption succeeded after 0.5 seconds
DeDRM v6.8.0: Finished after 0.9 seconds
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added 生まれる価値のなかった自分がアンナのためにできるいくつかのこと：１ to db in: 2.0
Added 1 books in 4.2 seconds
Worker Launch took: 0.226999998093
```
</details>

**Comment by ElleKayEm** [comment]
I think it may be the calibre ebook viewer that isn't handling it properly.  DRM is successfully removed.

**Comment by manoelpqueiroz** [comment]
True, I hadn't noticed that in the log!
