### ISSUE TITLE
Can't remove AZW3 with Calibre and DeDRM 

### ISSUE THREAD

**Issue by fkeisin** [apprenticeharper/DeDRM_tools#161]
Hi there,

I have a few AZW3 files I am trying to decrypt. I have followed instructions for doing it with Calibre and the Mac DeDRM tool (I have a Mac). Unfortunately it doesn't work both ways.

Attached I am sending the log of the DeDRM file - maybe someone has an idea what the problem is.

Thanks and best from Germany

Freddy

**Comment by ElleKayEm** [comment]
That's not a log from the DeDRM tools.  Take a look at the FAQs page about posting a log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by fkeisin** [comment]
Okay, Sorry - my mistake. Please find the log here:

calibre Fehlerdiagnoseprotokoll
calibre 2.53  embedded-python: True is64bit: True
Darwin-14.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.0.0', 'Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.10', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 4.47 seconds with 21 books
2016-12-04 15:14:01.322 calibre-debug[10162:1972766] Bad cursor rect event, flags = 256
DeDRM v6.5.2: Trying to decrypt Panikherz_B019NVMSU6.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Panikherz (German Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.2: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.2: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.5.2: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 153, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.1 seconds
Added Panikherz (German Edition) to db in: 0.3
Added 1 books in 1.6 seconds
2016-12-04 15:14:19.195 Calibre[10180:1973450] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.523195028305
Job: 1 Buch 1 von 1 (Panikherz (German Edition)) konvertieren finished
Buch 1 von 1 (Panikherz (German Edition)) konvertieren
	Resolved conversion options
	calibre version: 2.53.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/cz/tqldfdkn4yv8nbsrx225ymfm0000gn/C/calibre_2.53.0_tmp_60uLdd/YTnSZF.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x1138e04d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x1138e0c50>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/cz/tqldfdkn4yv8nbsrx225ymfm0000gn/C/calibre_2.53.0_tmp_60uLdd/oMYdNB.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: Panikherz (German Edition)
	InputFormatPlugin: MOBI Input running
	on /var/folders/cz/tqldfdkn4yv8nbsrx225ymfm0000gn/C/calibre_2.53.0_tmp_60uLdd/1tMt7H.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 209, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 190, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 31, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1057, in run
	  File "site-packages/calibre/customize/conversion.py", line 241, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 43, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 81, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 144, in check_for_drm
	calibre.ebooks.DRMError: Panikherz (German Edition)

**Comment by ElleKayEm** [comment]
If the book is from an E-ink Kindle, then you need to enter its serial number into the plugin customization.  Otherwise, install Kindle for Mac and import the book from there.
