### ISSUE TITLE
Unable to convert azw3 into epub

### ISSUE THREAD

**Issue by stephybeg** [apprenticeharper/DeDRM_tools#1610]
I have installed Adobe Digital Editions 4.5, Calibre 4.23 and KindleforPC 1-17. Before this I tried newer versions also without success.  I do not know further. Could anyone help? Thanks in advance

calibre Fehlerdiagnoseprotokoll
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 91.745819398
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
[1.59] main UI initialized...
[1.59] Hiding splash screen
[11.47] splash screen hidden
[11.47] Started up in 11.47 seconds with 5 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['AjQ\xaa\xf8\x1f\x15\xf3N\xbca9Et$\xea\xbcL\xb7\\\x0b~9G\x07\xdez\xda\xd5\x82/W', 'J:\\B\xc3\xbccher\\##MEINS\\amazon\\Die Rachs\xc3\xbcchtige (German Edition).azw3']
DeDRM v6.8.0: Trying to decrypt Die RachsÃ¼chtige (German Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Die RachsÃ¼chtige (German Edition)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\steph\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\steph\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\steph\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2126200815' and UserName '7374657068'
Decrypted key file using IDString '2126200815' and UserName '7374657068'
DeDRM v6.8.0: Found 2 new keys
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Die RachsÃ¼chtige (German Edition)
Got DSN key from database default_key_1
Got DSN key from database default_key_2
Found 4 keys to try after 6.0 seconds
Crypto Type is: 2
DeDRM v6.8.0: Ultimately failed to decrypt after 6.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 6.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files (x86)\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Die Rachsüchtige (German Edition) to db in: 0.1
Added 1 books in 6.4 seconds
Worker Launch took: 0.128999948502
Job: 0 Buch 1 von 1 (Die Rachsüchtige (German Edition)) konvertieren finished
Buch 1 von 1 (Die Rachsüchtige (German Edition)) konvertieren
	C:\Program Files (x86)\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\steph\\AppData\\Local\\Temp\\calibre_wvyl93\\fmx4wq.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\steph\\AppData\\Local\\Temp\\calibre_wvyl93\\gfrmyf.opf'
	  output_profile: u'generic_eink'
	  verbose: 2
	Resolved conversion options
	calibre version: 4.23.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\steph\\AppData\\Local\\Temp\\calibre_wvyl93\\fmx4wq.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x058087F0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x058089F0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\steph\\AppData\\Local\\Temp\\calibre_wvyl93\\gfrmyf.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\steph\AppData\Local\Temp\calibre_wvyl93\grobxa.azw3
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  Die Rachsüchtige (German Edition) (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Die Rachsüchtige (German Edition)

**Comment by ElleKayEm** [comment]
If that book is for an E-ink Kindle (not a Fire), enter the Kindle's serial number in DeDRM's customization.

**Comment by stephybeg** [comment]
Yes, its an kindle and serial number is already added. (configuration elnk kindle ebook) Any other ideas?

**Comment by ElleKayEm** [comment]
Double-check the serial number.  Make sure your E-ink Kindle (it won't work with a Fire) is the device that you chose when you downloaded this copy of the book.

**Comment by stephybeg** [comment]
I entered it with copy&paste from the account and already double-checked with the kindle itself. It is the same I have always used
 used in store.

**Comment by stephybeg** [comment]
Yeah, I tried to download it to my PC and import it from there and this way finally works :-) Thanks for your quick assistance.
