### ISSUE TITLE
failed to remove DRM

### ISSUE THREAD

**Issue by succherone** [apprenticeharper/DeDRM_tools#1619]
Hi thanks for your time, i just bought this book and this is the log

calibre Log di debug
calibre 5.13  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0)
calibre 5.13  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.73578595317724 x 108.85714285714285
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
Loaded cached store plugin for: Smashwords at version: 6
[0.81] main UI initialized...
[0.81] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.37.0: Importing C:\Users\monst\OneDrive\Documenti\My Kindle Content\B088JTKVH6_EBOK\B088JTKVH6_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\monst\AppData\Local\Temp\calibre_64nofgn6\zfprposx.kfx-zip
DeDRM v7.1.0: Trying to decrypt zfprposx.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: zfprposx
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.807f219f-826a-4a9e-9995-4b77a33198ab.voucher
DeDRM v7.1.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\monst\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\monst\AppData\Local\Amazon\Kindle\storage\.kinf2018
[4.81] splash screen hidden
[4.81] Started up in 4.81 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'C\x9f\xa6\x97\x05j\xa7\xdb\xb0\xdcq\xd3\xfb\xb4\xcc\xac\x94\xef)Z\x93\x7f\x1d\x04{\xf81\x1a;\x04@\xc6', b'C:\\Users\\monst\\OneDrive\\Documenti\\My Kindle Content\\B088JTKVH6_EBOK\\B088JTKVH6_EBOK.azw']
Decrypted key file using IDString '3738357994' and UserName 'monst'
DeDRM v7.1.0: Found 1 new key
Decrypting KFX-ZIP ebook: zfprposx
Got DSN key from database default_key_1
Found 1 keys to try after 2.9 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.807f219f-826a-4a9e-9995-4b77a33198ab.voucher
DeDRM v7.1.0: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.37.0: Packaging C:\Users\monst\AppData\Local\Temp\calibre_64nofgn6\zfprposx.kfx-zip
Processing container: B088JTKVH6_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\monst\AppData\Local\Temp\calibre_64nofgn6\4a3jevs__add_books\0\B088JTKVH6_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B088JTKVH6_EBOK.azw has DRM and cannAdded DIRITTO PRIVATO DEI MERCATI DIGITALI - Edizione digitale (Italian Edition) to db in: 0.2
Added 1 books in 3.5 seconds

**Comment by ElleKayEm** [comment]
KFX books need to be downloaded with Kindle for PC 1.26 or earlier.  Alternatively, you can disable KFX downloads.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by succherone** [comment]
Thanks this worked!
