### ISSUE TITLE
Obok plugin doesn't seem to work on Linux

### ISSUE THREAD

**Issue by nmmoldgit** [apprenticeharper/DeDRM_tools#162]
I am getting the following error with both 6.5.2 and 6.5.3 and Calibre 2.5, and the character is the same for several files:

('Linux', '3.16.0-4-amd64', '#1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19)')
Python 2.7.9
Linux: ('debian', '8.6', '')
Successfully initialized third party plugins: Obok DeDRM
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 96, in launchObok
  File "calibre_plugins.obok_dedrm.obok.obok", line 285, in __init__
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 22: ordinal not in range(128)

Restarting Calibre with debug mode fails with:

Successfully initialized third party plugins: Obok DeDRM
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 96, in launchObok
  File "calibre_plugins.obok_dedrm.obok.obok", line 351, in __init__
NameError: global name 'linux_path' is not defined

I am not desperately keen to debug by hacking the source, because the build and reinstall cycle
is tedious, but don't see much option.

**Comment by nmmoldgit** [comment]
In the line  'self.library = KoboLibrary(tmpserials, device_path)' the arguments are [] and None.

**Comment by apprenticeharper** [comment]
Attempts to make obok work on linux with wine seem to have failed. Pull requests to fix this are welcome.

**Comment by norbusan** [comment]
Same as isse isse #156 , these two should be merged if possible.

**Comment by apprenticeharper** [comment]
I have made a version with the two offending lines commented out. So the plugin won't work with Kobo Desktop installed under Wine, but should work otherwise.

Testing encouraged! 

https://github.com/apprenticeharper/DeDRM_tools/tree/master/Obok_calibre_plugin

**Comment by nmmoldgit** [comment]
On Dec 20 2016, Apprentice Harper wrote:

> I have made a version with the two offending lines commented out. So the 
> plugin won't work with Kobo Desktop installed under Wine, but should work 
> otherwise.
>
>Testing encouraged! 
>
>  
> https://github.com/apprenticeharper/DeDRM_tools/tree/master/Obok_calibre_plugin

I am getting the same error as before. It is quite likely that I am using 
it incorrectly, because I have not found any canonical instructions (i.e. 
they are in someone else's how-to). If there are such instructions, I 
should appreciate a pointer.

I have Adobe Digital Editions (2.1, if I recall) installed under wine and
Calibre 2.73 running native under Linux.

Thank you for any help.

Regards,
Nick Maclaren.

**Comment by apprenticeharper** [comment]
If you are getting the same error it's likely that you have not downloaded/installed the new test version.

**Comment by apprenticeharper** [comment]
Fixed included in the DeDRM 6.5.3 release
