### ISSUE TITLE
init.py

### ISSUE THREAD

**Issue by jobardu** [apprenticeharper/DeDRM_tools#1626]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

**Comment by ElleKayEm** [comment]
From the title I guess you're having trouble installing DeDRM.  Unzip the main file and load DeDRM_plugin.zip.

**Comment by jobardu** [comment]
Thanks ElleKayEm. That worked. Much appreciated.
Jobardu

________________________________

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by jobardu** [comment]
OK ElleKayEM. 
I CONSIDER THIS ISSUE CLOSED in a successful manner. 
I want to thank everyone for their help.
