### ISSUE TITLE
[QUESTION] Calibre 4.23 with python3 and DeDRM

### ISSUE THREAD

**Issue by Tokariew** [apprenticeharper/DeDRM_tools#1629]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.

---

### DeDRM: `7.1.0`

</details>

I use Calibre packaged by Fedora distribution, and currently I have Calibre 4.23 which using Python3 as backend…
When trying to install DeDRM 7.1.0 i get error about Calibre version not being 5.0.0 or greater…
DeDRM 6.8.0 don't work either…

What should I edit in packaged zip, to be able to install it, ignoring version check? I would like to stay with version provided by distro…

**Comment by ElleKayEm** [comment]
Edit this line: 
 https://github.com/apprenticeharper/DeDRM_tools/blob/76a47e0dd079e76ff9cf7ba3458d137ead7f8c29/DeDRM_plugin/__init__.py#L132

change (5, 0, 0) to (4, 2, 3)

**Comment by Tokariew** [comment]
Thanks, work beautifully in my case ;)
