### ISSUE TITLE
Virus flag on DeDRM_tools_6.5.2.zip (and other recent releases)

### ISSUE THREAD

**Issue by rog1205** [apprenticeharper/DeDRM_tools#163]
The Mac virus program ClamXav https://www.clamxav.com/ is flagging the downloaded 6.5.2 zip file (and several other recent releases) for Win.Trojan.Toa-5372190-0.  Older releases (eg, tools_v5.6.1.zip) are not flagged.

Maybe a scam to sell somebody's virus removal service?  Anybody know about this?

**Comment by ElleKayEm** [comment]
I'd say it's a false positive.  At any rate, this is the first question I've seen about it, and that version has been available since Oct 11, 2016.

**Comment by rog1205** [comment]
Yes, false positive, with new (today's) ClamXav virus definition, virus no longer flagged.
