### ISSUE TITLE
Obok incorrectly sees books as DRM-free

### ISSUE THREAD

**Issue by erys** [apprenticeharper/DeDRM_tools#1631]
This occurs with both 6.8.1 and 7.1.0. The two books I downloaded most recently after updating Kobo Desktop to 4.26.14705 show up as DRM-free when I import them, but clearly are encrypted if I unzip them or try to read them with the calibre e-book viewer. This also happens if I redownload a book that I previously successfully decrypted with obok and try to import it. If anyone has suggestions for how to work around this by forcing the decryption, that would also be very helpful.

Debug log:
calibre Debug log
calibre 5.9 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Kindle hi-res covers (0, 5, 0) && KindleUnpack - The Plugin (0, 83, 0) && Kobo Books (1, 8, 2) && Obok DeDRM (7, 1, 0)
calibre 5.9 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Kindle hi-res covers (0, 5, 0) && KindleUnpack - The Plugin (0, 83, 0) && Kobo Books (1, 8, 2) && Obok DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 94.14671814671814 x 94.07407407407408
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.09] main UI initialized...
[1.09] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1395, in set_metadata
  File "calibre\db\cache.py", line 1318, in set_cover
  File "calibre\db\backend.py", line 1500, in set_cover
  File "calibre\utils\img.py", line 285, in save_cover_data_to
  File "calibre\utils\img.py", line 197, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
[4.16] splash screen hidden
[4.16] Started up in 4.16 seconds with 1056 books
Running Obok DeDRM v7.1.0
DEBUG:    4.5 didn't find device
Obok v4.0.0
Copyright © 2012-2020 Physisticated et al.
C:\Users\ELIZAB~1\AppData\Local\Temp\tmpp6tpe2x6
DEBUG:    4.5 got kobodir C:\Users\Elizabeth\AppData\Local\Kobo\Kobo Desktop Edition
Found 24 possible keys to try.
DEBUG:   10.7 BookListTableWidget:get_books - book_num: 4
DEBUG:   10.7 BookListTableWidget:get_books - book: So I'm a Spider, So What?, Vol. 11 (light novel)
DEBUG:   10.7 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v7.1.0 - Decrypting So I'm a Spider, So What?, Vol. 11 (light novel)
Trying key:  b'729d1d8c296271b900d9a03d68a9aadd'
Success!
DEBUG:   11.1 DecryptAddProgressDialog::do_book_action - decrypted book: 'So I'm a Spider, So What?, Vol. 11 (light novel)'
Obok DeDRM v7.1.0 - Added So I’m a Spider, So What?, Vol. 11
Obok DeDRM v7.1.0 - wrapping up results.

**Comment by erys** [comment]
Actually, it looks like I was able to fix this by repairing my kobo account in the desktop app (an option I didn't know existed before).

**Comment by ElleKayEm** [comment]
Thanks for reporting that.  I didn't know about the repair option either.
