### ISSUE TITLE
[GNU/Linux] DeDRM plugin won't remove DRM from AZW files

### ISSUE THREAD

**Issue by gnulinuxnovice** [apprenticeharper/DeDRM_tools#164]
**System Specs:**
HP G6-2235us, Linux Mint 17.3 (based on ubuntu 14.04) x86_64, kernel 4.6.4, KDE 4.14

**Software Specs:**
Calibre v. 2.75.1, DeDRM plugin 6.5.2

**Problem:**
I have tried using the DRM removal plugin in the Calibre, however, it didn't work. I tried uninstalling/re-installing Calibre and the DeDRM plugin, and I tried it several times on debug mode. I have included the debug txt files below of the attempts with removing the DRM. However, I noticed a consistent pattern in this bug. It seems only to only occur with AZW files, but with all others (i.e., AZW3, MOBI, EPub) it works. 

If you need more info from me or require anything on my part, please don't hesitate to contact me.

Thank you.

[Calibre_Debug_Info.txt](https://github.com/apprenticeharper/DeDRM_tools/files/678173/Calibre_Debug_Info.txt)
[Debug Info_2.txt](https://github.com/apprenticeharper/DeDRM_tools/files/678174/Debug.Info_2.txt)
[Debug Info_3.txt](https://github.com/apprenticeharper/DeDRM_tools/files/678993/Debug.Info_3.txt)

**Comment by ElleKayEm** [comment]
Looks like the same problem others have had on Linux where the tools can't find Python.  See this part of the log:

> DeDRM v6.5.2: Running kindlekey.py under Wine
> DeDRM v6.5.2: Command line: 'WINEPREFIX="/home/mobile-unit" wine python.exe "/home/mobile-unit/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/mobile-unit/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
> wine: cannot find L"C:\\windows\\system32\\python.exe"
> wine: cannot find L"C:\\windows\\system32\\python.exe"
> DeDRM v6.5.2: Found and decrypted 0 key files

Try running the key retrieval script under Wine manually, and import the key into calibre.

**Comment by apprenticeharper** [comment]
The MOBI and AZW3 files that 'worked' didn't have DRM in the first place.

Ass ElleKayEm says, there's a know problem automatically retrieving the key on :Linux systems. If you can get the key manually and import into the plugin's preferences, you will be fine.
