### ISSUE TITLE
deDRM Adobe Digital Editions Error

### ISSUE THREAD

**Issue by ghostviolet** [apprenticeharper/DeDRM_tools#1642]
DeDRM not removing DRM for .acsm file using newest Calibre/DeDRM. Does work in older versions, but would love to be able to upgrade Calibre. Is this issue with the default_key?

## Log
calibre, version 5.14.0 (darwin, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (The Domestic Revolution)

Convert book 1 of 1 (The Domestic Revolution)
DeDRM v7.1.0: Trying to decrypt l217tzvk.pdf
DeDRM v7.1.0: l217tzvk.pdf is a PDF ebook
DeDRM v7.1.0: Trying Encryption key default_key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 127
bookkey[0] is 91
DeDRM v7.1.0: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 434, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
    doc.initialize(userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
    return self.initialize_ebx(password, docid, param)
  File "calibre_plugins.dedrm.ineptpdf", line 1622, in initialize_ebx
    raise ADEPTError('error decrypting book session key - mismatched length')
calibre_plugins.dedrm.ineptpdf.ADEPTError: error decrypting book session key - mismatched length
DeDRM v7.1.0: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.1.0: Trying Encryption key default_key_2
error writing pdf: max() arg is an empty sequence
DeDRM v7.1.0: Failed to decrypt with key default_key_2 after 0.2 seconds
DeDRM v7.1.0: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v7.1.0: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.1.0: Failed to decrypt with new default key after 0.2 seconds
DeDRM v7.1.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Failed to initialize plugin: '/Users/Roseero/Library/Preferences/calibre/plugins/Barnes & Noble.zip'
Failed to initialize plugin: '/Users/Roseero/Library/Preferences/calibre/plugins/Fantastic Fiction.zip'
Failed to initialize plugin: '/Users/Roseero/Library/Preferences/calibre/plugins/Goodreads.zip'
Conversion options changed from defaults:
  read_metadata_from_opf: '/var/folders/rk/002t4yrx4636nbx7m9w_j60h0000gn/C/calibre_5.14.0_tmp_926vbiud/_1m5x4jd.opf'
  verbose: 2
Resolved conversion options
calibre version: 5.14.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10bbd5580>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_images': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x10bbd5850>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/rk/002t4yrx4636nbx7m9w_j60h0000gn/C/calibre_5.14.0_tmp_926vbiud/_1m5x4jd.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 638, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 513, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.1.0: Trying to decrypt l217tzvk.pdf
DeDRM v7.1.0: l217tzvk.pdf is a PDF ebook
DeDRM v7.1.0: Trying Encryption key default_key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 127
bookkey[0] is 91
DeDRM v7.1.0: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 434, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
    doc.initialize(userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
    return self.initialize_ebx(password, docid, param)
  File "calibre_plugins.dedrm.ineptpdf", line 1622, in initialize_ebx
    raise ADEPTError('error decrypting book session key - mismatched length')
calibre_plugins.dedrm.ineptpdf.ADEPTError: error decrypting book session key - mismatched length
DeDRM v7.1.0: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.1.0: Trying Encryption key default_key_2
error writing pdf: max() arg is an empty sequence
DeDRM v7.1.0: Failed to decrypt with key default_key_2 after 0.1 seconds
DeDRM v7.1.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.1.0: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.1.0: Failed to decrypt with new default key after 0.2 seconds
DeDRM v7.1.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 638, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 513, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: PDF Input running
on /var/folders/rk/002t4yrx4636nbx7m9w_j60h0000gn/C/calibre_5.14.0_tmp_926vbiud/l217tzvk.pdf
Converting file to html...
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 216, in main
  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1105, in run
  File "calibre/customize/conversion.py", line 245, in __call__
  File "calibre/ebooks/conversion/plugins/pdf_input.py", line 54, in convert
  File "calibre/ebooks/pdf/pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

**Comment by ElleKayEm** [comment]
Adobe epubs seem to be good, but pdfs still need some work for DeDRM 7.1.0.  If this book does indeed decrypt with calibre 4.23 and DeDRM 6.8.x, see this note from Apprentice Harper:

>  There may well still be problems with the DeDRM plugin. If you find a book that can be decrypted with calibre 4.23 and DeDRM 6.8.1, but that does not decrypt with DeDRM 7.1.0, please send me to original encrypted book, and your key exported from the DeDRM 6.8.1 preferences. I will try to reproduce the problem and fix the bug. Please send books and keys to apprenticeharper@gmail.com

**Comment by ghostviolet** [comment]
Will do; thanks!

**Comment by Geremia** [comment]
@ElleKayEm I can get 7.2.1 to decrpyt EPUBs and only some PDF. See #1666 .
