### ISSUE TITLE
Calibre 2.75 with tools 6.5.2 won't De-DRM Harry Potter/Cursed Child

### ISSUE THREAD

**Issue by samsam77w** [apprenticeharper/DeDRM_tools#165]
After attempting to convert Harry Potter and the Cursed Child, I just get a message saying something like, "Cannont convert......, This book is locked by DRM...." I have the DeDRM plugin v6.5.2, but still get the same message.

**Comment by rpspringuel** [comment]
DRM removal happens on import, not conversion.  You need to reimport the book to remove the DRM.

**Comment by ElleKayEm** [comment]
Post an import log.  Didn't realize they were putting DRM on these now.  Where did you buy it?  Pretty sure if you get them directly from Pottermore, they just have watermarks.

**Comment by samsam77w** [comment]
per rpspringuel: I Actually did as you suggest, each attempt (I had Calibre and DeDRM updated prior to importing. It imports just fine, but won't convert)

**Comment by apprenticeharper** [comment]
Give details of where you bought it and the format. Post an import log.

**Comment by samsam77w** [comment]
apprenticeharper: I wasn't able to try that right away. Today I was all set to, and updated Calibre from 2.75 to 2.76. Then I re-imported the .epub file (that is, I deleted the book on Calibre and imported it again). This time, the conversion worked - my guess is that the newer version of Calibre addressed an issue with importing.  Thanks to all for your help.
