### ISSUE TITLE
deDRM won't load in Calibre

### ISSUE THREAD

**Issue by hoegmol** [apprenticeharper/DeDRM_tools#1668]
I am running Calibre 5.14 and downloaded the latest deDRM plugin version 7.2.1.  When I try to load the DeDRM_plugin.zip file in Calibre, I get this error message:
ERROR: Unhandled exception
SyntaxError:invalid syntax (calibre_plugins.dedrm._init_, line 167)

There are no other user installed plugins.
What is the problem?

**Comment by lnxme** [comment]
As per the instructions 

> Do remember to unzip the downloaded archive to get the plugin

The actual plugin to be loaded into Calibre is a zip file inside of the downloaded zip file.

**Comment by hoegmol** [comment]
That's exactly what I thought I did.  I unzipped the DeDRM_tools_7.2.1.zip file and loaded DeDRM_plugin.zip file.  Several times.  Just to make sure, I tried again, this time backing out of the autopopulated file name and re-selected the plugin.zip file and it worked.  I imported 3 books converted them and successfully sent them to my kindle.

My apologies.  I'm thrilled it worked this time!   I've been using Calibre for years because I don't finish library books in time to return them in 3 weeks.  Purely personal use, but a great tool for me.

Thank you,
Molly Hoeg

Molly Hoeg, freelance writer
Blog: SuperiorFootprints.org<https://superiorfootprints.org/>
Phone: 218-730-6694

**Comment by lnxme** [comment]
Hi Molly,

Sometimes things happen. Been there, seen that and got the t-shirt.  Glad it worked out okay in the end.

Could you please mark this issue as solved?

Thanks

**Comment by hoegmol** [comment]
Yes, I'll do that right now.  Thanks for your responsiveness!

Molly Hoeg, freelance writer
Blog: SuperiorFootprints.org<https://superiorfootprints.org/>
Phone: 218-730-6694

**Comment by hoegmol** [comment]
I just closed the issue, but I'm wondering if it is possible to edit the comments to remove my contact information (email address and phone number) that were included because it was by email.  I'll know in the future to use the web to reply so that doesn't happen again.

Thanks!


Molly Hoeg, freelance writer
Blog: SuperiorFootprints.org<https://superiorfootprints.org/>
Phone: 218-730-6694

**Comment by ElleKayEm** [comment]
@hoegmol Come to the Github website, click the three dots on the top right of your post, and chose edit.

**Comment by hoegmol** [comment]
The only thing available when I click the three dots is "copy link."  Is this because it is closed?

**Comment by ElleKayEm** [comment]
I can still edit my posts on closed issues.  Make sure you are signed in to GitHub.
