### ISSUE TITLE
Calibre 2.76 with tools 6.5.2 import but don't De-DRM

### ISSUE THREAD

**Issue by riccardoriva** [apprenticeharper/DeDRM_tools#167]
Hello, 
with Calibre 2.76 64 bit and plugin 6.5.2 I can import DRM protected ebook but the DRM remain and I can't read it on my device.
I've just tried an older version of calibre but without results.
The following is the debug log of the ebook import:

calibre Log di debug
calibre 2.76 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 2) && Diaps Editing Toolbag (0, 3, 2) && Biblionet_gr (1, 0, 2) && Kindle Collections (1, 7, 17) && ANOBII (0, 4, 3) && Generate Cover (1, 5, 21)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Starting up...
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
Storage number map:
{(7L, 0L): [(4L, 'C')], (7L, 1L): [(1L, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\9017220144770G81&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=5)
{u'drive_letters': ['D'],
 u'pnp_id_map': {'D': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#9017220144770g81&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'D': (1L, 1L)}}
Job: 1 Recupera informazioni sul dispositivo started
DeviceJob: 1 Recupera informazioni sul dispositivo done, calling callback
DeviceJob: 1 Recupera informazioni sul dispositivo callback returned
Job: 2 Imposta informazioni sulla biblioteca started
DeviceJob: 2 Imposta informazioni sulla biblioteca done, calling callback
DeviceJob: 2 Imposta informazioni sulla biblioteca callback returned
Job: 3 Recupera la lista dei libri del dispositivo started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ documents
DEBUG:    0.1 USBMS: scan from root False D:\documents
DEBUG:    0.1 USBMS: count found in cache: 69, count of files in metadata: 69, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Recupera la lista dei libri del dispositivo done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 69
DeviceJob: set_books_in_library finished: time= 0.0310001373291
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Recupera la lista dei libri del dispositivo callback returned
Job: 4 Invia metadati al dispositivo started
DEBUG:    0.3 USBMS: starting sync_booklists
Job: 1 Recupera informazioni sul dispositivo finished
Nessun dettaglio disponibile.
Job: 2 Imposta informazioni sulla biblioteca finished
Nessun dettaglio disponibile.
Job: 3 Recupera la lista dei libri del dispositivo finished
Nessun dettaglio disponibile.
DEBUG:    0.7 USBMS: finished sync_booklists
DeviceJob: 4 Invia metadati al dispositivo done, calling callback
DeviceJob: 4 Invia metadati al dispositivo callback returned
Job: 4 Invia metadati al dispositivo finished
Nessun dettaglio disponibile.
Started up in 62.42 seconds with 135 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['"\xe8\xa4\xe3\xb1crF{[\x02y\xa7[\xbc$\xf4d[U\xb0\xe7\xb9\x13 \xaf\x813#\x17\xa1\xb4', 'J:\\EBooks\\__nuovi\\Sette minuti dopo la mezzanotte.epub']
DeDRM v6.5.2: Trying to decrypt Sette minuti dopo la mezzanotte.epub
DeDRM v6.5.2: Verifying zip archive integrity
DeDRM v6.5.2: Sette minuti dopo la mezzanotte.epub is a secure Adobe Adept ePub
DeDRM v6.5.2: Trying Encryption key default_key
Could not decrypt 39vqlq.epub. Wrong key
DeDRM v6.5.2: Failed to decrypt with key default_key after 12.9 seconds
DeDRM v6.5.2: Looking for new default Adobe Digital Editions Keys after 12.9 seconds
Found 1 keys
DeDRM v6.5.2: Ultimately failed to decrypt after 13.0 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 391, in ePubDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 13.0 seconds.
Added Sette minuti dopo la mezzanotte to db in: 11.9
Added 1 books in 26.5 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x0000000004A07780>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x0000000004A078D0>> ignored
Worker Launch took: 0.266000032425

Thank you in advance
Regards
Riccardo

**Comment by ElleKayEm** [comment]
The log tells us that there was already a key saved but it was not right for this book.  The plugin then looked at the key for the current installation of Adobe Digital Editions on this machine and it didn't work either.  Was this downloaded with ADE 2.0.1 authorized with your Adobe ID?

**Comment by apprenticeharper** [comment]
I'm assuming that the OP has solved their problem. katdawg9: if you are still having problems, please open a new issue, and post an import log.
