### ISSUE TITLE
Unable to DeDRM eBooks from Sony PRS-300

### ISSUE THREAD

**Issue by rsbrux** [apprenticeharper/DeDRM_tools#1671]
I am trying to migrate my eBooks from an old Sony Pocket Edition to a new Onyx Boox Poke 3.
I am running Calibre under Windows 10 Pro x64 20H2.  I am trying to load the library directly from the PRS-300.
I did not find any "Import" command in the Calibre UI, so I just selected all of the files on the device and picked "Add to library" from the context menu.
I have tried to view a few titles, all of which seem to have failed decryption.  Here is an example log file:

```
calibre, version 5.14.0
ERROR: Loading book failed: Failed to open the book at C:\Users\rbrooks\AppData\Local\Temp\calibre_isdjrbzd\vf3751_f_view_device_book.epub. Click "Show details" for more info.

Failed to convert book: C:\Users\rbrooks\AppData\Local\Temp\calibre_isdjrbzd\vf3751_f_view_device_book.epub with error:
DeDRM v7.2.1: Trying to decrypt vf3751_f_view_device_book.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: vf3751_f_view_device_book.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 358, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 358, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 361, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: EPUB Input running
on C:\Users\rbrooks\AppData\Local\Temp\calibre_isdjrbzd\vf3751_f_view_device_book.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 870, in viewer_main
  File "calibre\srv\render_book.py", line 861, in render_for_viewer
  File "calibre\srv\render_book.py", line 838, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 290, in convert
calibre.ebooks.DRMError: vf3751_f_view_device_book.epub
Exception ignored in: <function NativeFunction.__del__ at 0x000001B8CB40FDC0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001B8CB40FDC0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
```

**Comment by rsbrux** [comment]
P.S.  I also tried to add the books from files, but the only files I have are a backup of my previous Calibre library directory, and the instructions call for "the original downloaded files", so I'm not sure these qualify.  IAC, the results are still the same.  The books were purchased on various bookstore sites, including but not limited to Amazon.  It would be quite difficult for me to reconstruct which books came from which vendors.  Since I can still read the books on the Sony, I was hoping that importing them from the reader would provide whatever key is needed to unencrypt them.  I haven't used it in several years, but my Adobe login still works.  However, I don't find any information about licensed books in my profile there.

**Comment by ElleKayEm** [comment]
Try installing Adobe Digital Editions on the same machine and user as calibre with DeDRM.  Authorize it with your Adobe ID.  See if you can open your books.  If so, DeDRM should be able to extract the necessary key from ADE when you add the books to calibre.

**Comment by rsbrux** [comment]
Thanks for the tips, but I'm too ignorant to understand them.  I have installed ADE 2.0.1 because I have read that older is better and the books I have were bought years ago.  What do you mean by "user as calibre with DeDRM"? What should I authorize with my Adobe ID?   I tried "Authorize computer" with the e-mail address and password I use to log on to the Adobe website, but it identifies this a "Vendor ID", and I am not a vendor.
When you say "See if you can open your books.", do you mean with ADE or with Calibre? When I started ADE, it showed a library containing only a "Getting Started" document.  I don't find an "Open" command in the ADE menus, so I tried "Add to library" for a couple of titles from my Calibre backup and got "Document is licensed for a different user account."  This is entirely possible, since I inherited the Sony PRS-300 from my wife, who now reads eBooks on her iPad Air. Also, the Windows account on my new installation is a domain account, whereas the account on my previous installation was a local account. I could try authorizing the computer with my wife's Adobe login, but ADE seems to expect a "Vendor ID"

**Comment by ElleKayEm** [comment]
I meant that calibre with DeDRM and ADE should both be installed on the same computer and the same Windows user account.  When you first install and open ADE, it should prompt you to authorize it.  If not, this is under Help > Authorize computer.  If the books' DRM is linked to your wife's Adobe ID, then that is what you need to use.  If you can read the books in ADE authorized with that Adobe ID, then you will be able to DeDRM them.

**Comment by rsbrux** [comment]
Thanks again! That certainly sounds like the logical next step, but ISTR that ADE only allows a limited number of devices to be authorized.  I didn't think to deauthorize my PC before scrubbing it to perform the fresh Windows installation and I don't want to exhaust my wife's authorization quota.  Unfortunately, a web search didn't turn up any details on this.  [This article ](https://helpx.adobe.com/digital-editions/using/authorizing-and-de-authorizing-adobe-digital-editions.html) has a link titled "[Deactivating a device from your ADE account.](https://blogs.adobe.com/ebooks/2015/04/30/deactivating-a-device-from-your-ade-account/)" but the link is broken.  If I log in to the Adobe website, I get "Creative Cloud" as described [here](https://community.adobe.com/t5/download-install/deactivate-a-device-from-my-account-page/m-p/10611621).  I don't find anything pertaining to ADE in my Adobe account profile.

**Comment by ElleKayEm** [comment]
You're unlikely to hit the limit.  If you do, you can contact Adobe and have it reset.

**Comment by l-l-l-l-l-l** [comment]
There's a key shortcut to deathorize ADE, which is Ctrl-Shift-D (for Mac, substitute Ctrl for Cmd).

**Comment by ElleKayEm** [comment]
That doesn't remove the device from your allotment.  But as long as you don't activate several apps in a relatively sort period of time, you'll be fine.

**Comment by rsbrux** [comment]
@ElleKayEm 
It took me a while to iron out all the wrinkles, but all now seems to be working.
Your tips about ADE were invaluable: I found no command in ADE 2's menus for deauthorizing or authorizing another account, and the shortcut key combination you revealed was not mentioned in the help.  Many thanks!
