### ISSUE TITLE
DeDRM doesn't work on Kobo book

### ISSUE THREAD

**Issue by 8139david** [apprenticeharper/DeDRM_tools#1678]
I purchased a book on Kobo's website
Then I imported the book on Windows 10, using Kobo Desktop Edition 4.26.14705.
Then, on Calibre 5.16.1, I asked Obok DeDRM v7.2.1 to import it.
The resulting epub contains what looks like a few incomplete images but no text.
The calibre log is attached (with some text anonymized).
Thanks in advance for your help.
[log.txt](https://github.com/apprenticeharper/DeDRM_tools/files/6371569/log.txt)

**Comment by chihweihsu1102** [comment]
Couldnt find the kobo desktop directory and wont work.
 using Kobo Desktop Edition 4.26.14705 and Calibre 5.16.1 with obok dedrm 72.0.

**Comment by ElleKayEm** [comment]
@8139david 
I'm not sure what's going on there.  The log says it successfully decrypted the book.

Obok 7.2.1 is not working for me on Windows 10.  Books didn't import because they couldn't be decrypted.  But I am able to use Obok 7.1.0.
