### ISSUE TITLE
Kindle AZW File Not Having DRM removed

### ISSUE THREAD

**Issue by jmaeshawn** [apprenticeharper/DeDRM_tools#1686]
I downloaded an ebook using Kindle version 1.17.0 (44170), and confirmed it was able to be opened in that program. I then imported it into Calibre v5.16.1 using DeDRM 7.2.1, but when I tried converting it to a zip file, I got a "This book is locked with DRM" error. I'm just guessing, but maybe the plugin can't handle decrypting eBooks with a file size that's this large? (The azw file is 441MB).

Here is the log file from debug mode:

calibre Debug log
calibre 5.16.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.16.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 57.172332942555684 x 57.15
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.83] splash screen shown
[1.83] Initializing db...
Failed to read metadata from font file: c:\windows\fonts\crayon.ttf tuple index out of range
[1.83] db initialized
[1.83] Constructing main UI...
[2.42] main UI initialized...
[2.42] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B093G7LW1Y_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
DeDRM v7.2.1: Failed to decrypt with error: tuple index out of range
DeDRM v7.2.1: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\jmaeshawn\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\jmaeshawn\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1682609808' and UserName 'jmaeshawn'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[4.78] splash screen hidden
[4.78] Started up in 4.78 seconds with 0 books
Added 【電子版】電撃マオウ 2021年6月号 [雑誌] to db in: 1.8
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.mobidedrm", line 319, in __init__
  File "calibre_plugins.dedrm.mobidedrm", line 377, in patchSection
  File "calibre_plugins.dedrm.mobidedrm", line 367, in patch
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 217, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 326, in __init__
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 1 books in 2.9 seconds
Worker Launch took: 0.05 seconds
Job: 0 Convert book 1 of 1 (【電子版】電撃マオウ 2021年6月号 [雑誌]) finished
Convert book 1 of 1 (【電子版】電撃マオウ 2021年6月号 [雑誌])

	DeDRM v7.2.1: Trying to decrypt tpxcdqbt.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.2.1: Failed to decrypt with error: tuple index out of range
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.4 seconds
	searching for kinfoFiles in C:\Users\jmaeshawn\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\jmaeshawn\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '1682609808' and UserName 'jmaeshawn'
	DeDRM v7.2.1: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  read_metadata_from_opf: 'C:\\Users\\jmaeshawn\\AppData\\Local\\Temp\\calibre_3wxik5n5\\nm7_mi4s.opf'

	  cover: 'C:\\Users\\jmaeshawn\\AppData\\Local\\Temp\\calibre_3wxik5n5\\z93ysqu6.jpeg'

	  verbose: 2

	Resolved conversion options

	calibre version: 5.16.1

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\jmaeshawn\\AppData\\Local\\Temp\\calibre_3wxik5n5\\z93ysqu6.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x072C6DC0>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x072C6F28>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'prefer_metadata_cover': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\jmaeshawn\\AppData\\Local\\Temp\\calibre_3wxik5n5\\nm7_mi4s.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'template_css': None,

	 'template_html': None,

	 'template_html_index': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.mobidedrm", line 319, in __init__

	  File "calibre_plugins.dedrm.mobidedrm", line 377, in patchSection

	  File "calibre_plugins.dedrm.mobidedrm", line 367, in patch

	MemoryError

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 217, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 326, in __init__

	IndexError: tuple index out of range

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	DeDRM v7.2.1: Trying to decrypt tpxcdqbt.azw
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.2.1: Failed to decrypt with error: tuple index out of range
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
	searching for kinfoFiles in C:\Users\jmaeshawn\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\jmaeshawn\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '1682609808' and UserName 'jmaeshawn'
	DeDRM v7.2.1: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.mobidedrm", line 319, in __init__

	  File "calibre_plugins.dedrm.mobidedrm", line 377, in patchSection

	  File "calibre_plugins.dedrm.mobidedrm", line 367, in patch

	MemoryError

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 217, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 326, in __init__

	IndexError: tuple index out of range

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\jmaeshawn\AppData\Local\Temp\calibre_3wxik5n5\tpxcdqbt.azw

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1105, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm

	calibre.ebooks.DRMError: 【電子版】電撃マオウ 2021年6月半 [雑誌]

**Comment by j-howell** [comment]
You are running the 32-bit version of calibre. Install the 64-bit version to handle large files.

**Comment by jmaeshawn** [comment]
Thank you, j-howell, for telling me that. I never knew that there would be a difference in functionality between the 32-bit and the 64-bit versions of the Calibre program.

It makes you wonder why they continue to list the 32-bit version as the default when it is crippled compared to the 64-bit version.

Anyway, that solved my problem, and I was successfully able to decrypt my kindle book, so thanks again for the help! 😁
