### ISSUE TITLE
Using Calibre 2.76 with DeDRM_tools_6.5.2 plugin but incorrect key? 

### ISSUE THREAD

**Issue by ckennedy167** [apprenticeharper/DeDRM_tools#169]
I'm guessing the "improper key used" is the problem? I am using right B&N email & password when customizing plugin - any ideas much appreciated!

I can add the book to Calibre but the DRM is still attached...

calibre Debug log
calibre 2.76  embedded-python: True is64bit: True
Darwin-15.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '15.6.0', 'Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.11.6', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM (6, 5, 2)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Starting up...
Started up in 1.32 seconds with 1 books
DeDRM v6.5.2: Trying to decrypt 9780749011994_epub.v2.epub
DeDRM v6.5.2: Verifying zip archive integrity
DeDRM v6.5.2: “9780749011994_epub.v2.epub” is a secure Barnes & Noble ePub
DeDRM v6.5.2: Trying Encryption key XXXXX
Could not decrypt m5JM4d.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 278, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 209, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 158, in __init__
IGNOBLEError: AES improper key used

DeDRM v6.5.2: Failed to decrypt with key XXXX after 0.0 seconds
DeDRM v6.5.2: Looking for new NOOK Study Keys after 0.0 seconds
No nook Study log files have been found.
DeDRM v6.5.2: Ultimately failed to decrypt after 0.0 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 291, in ePubDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.0 seconds.
Added The Cruel Stars of the Night to db in: 0.0
Added 1 books in 0.6 seconds
2017-01-01 16:14:46.921 Calibre[641:12981] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.160141944885
Job: 1 Convert book 1 of 1 (The Cruel Stars of the Night) finished
Convert book 1 of 1 (The Cruel Stars of the Night)
	Resolved conversion options
	calibre version: 2.76.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': u'/Users/caitlin/Calibre Library/Kjell Eriksson/The Cruel Stars of the Night (63)',
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x1119ba550>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x1119bacd0>,
	 'page_breaks_before': u'/',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/dl/wl2ftn0x4l76cws05hj8n2480000gp/C/calibre_2.76.0_tmp_Jzhdw3/JShyih.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: OZvymK.epub
	InputFormatPlugin: EPUB Input running
	on /var/folders/dl/wl2ftn0x4l76cws05hj8n2480000gp/C/calibre_2.76.0_tmp_Jzhdw3/OZvymK.epub
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1064, in run
	  File "site-packages/calibre/customize/conversion.py", line 245, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 268, in convert
	calibre.ebooks.DRMError: OZvymK.epub

**Comment by ElleKayEm** [comment]
Does your password have any special characters in it?  If so, try changing it to one without, at least temporarily.  Once you've retrieved the key, you can change your password again, and your BN key won't change.

**Comment by ckennedy167** [comment]
no special characters in the password unfortunately - any other ideas?

Thanks!

**Comment by ElleKayEm** [comment]
If it's a book you downloaded a while ago, try a fresh copy of the book.

**Comment by yupi2** [comment]
It seems like you're using your password as the B&N key. 
Did you go through the "Create New Barnes & Noble Key" dialogue and had it retrieve your account key?
Also XXXX your password out of the first post and/or change it on your account.

**Comment by ckennedy167** [comment]
Many thanks for your suggestions. 

ElleKayEM - I downloaded this copy of the book in the last 2 days so I don't think that's the problem unfortunately.

yupi2 - I did go through to the "Create New Barnes & Noble Key' dialogue box and retrieved a key using my account details. As for the password, I think you're referring to the Unique Key Name I created in the "Create New Barnes & Noble Key" as no passwords appear in the first post.

**Comment by yupi2** [comment]
Ah, you're right about that.
You could try re-retrieving your key then.

**Comment by ElleKayEm** [comment]
How are you downloading the books?  From what I understand, the key retrieval in the plugin basically pretends to be Nook for PC.  If you've never actually logged in from a Nook for PC app, it might have problems.  And while in most cases a B&N account will have the same key no matter what device/app a book is downloaded to, I have heard the rare report of someone finding a different key on the same account.

**Comment by ckennedy167** [comment]
I wasn't using Nook for PC. But now that I am, it is working.

Thanks very much for all your help and patience!
