### ISSUE TITLE
how to decrypt an unknown type of DRM

### ISSUE THREAD

**Issue by th0mass** [apprenticeharper/DeDRM_tools#17]
There is an online store in Turkey (babil com) which has an unknown type of DRM. and afaik there is no tool to decrypt it. Is there a way to search on it? what would be your advice to deal with it? I can provide an ebook with its registered account if anybody want to try on it.

**Comment by apprenticeharper** [comment]
Reverse engineering the application that currently reads the book is probably the only way. It's necessary to work out how the encryption key(s) are derived, and what decryption operations are used to decrypt the book. So a good knowledge of reverse engineering techniques and of encryption is needed. If anyone produces a tool for this bookstore, I'll happily include it in the archive.
