### ISSUE TITLE
Installed but calibre says they have DRM.

### ISSUE THREAD

**Issue by shiuh** [apprenticeharper/DeDRM_tools#170]
I have installed the lastst version of calibre and calibre plugin, but my books still have DRM. When I try to view or convert my books, here is the log.   

thanks for your time.

calibre Debug log
calibre 2.76  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 2)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9595278246 x 72.0810810811
Starting up...
Started up in 8.07 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xa6\x04T\xa6n\x9d\xdd}\xd3$\xd8\xc6\xddX\\\x90m\xcb\x8dE\xc5<\xa2\x9dY\x1e\xf49&\xb5\x1d\x1c', 'K:\\J drive\\Websites\\My Kindle Content\\B006CT0RHY_EBOK.azw']
DeDRM v6.5.2: Trying to decrypt B006CT0RHY_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Kids and Credibility: An Empirical Examination of Youth, Digital Media Use, and Information Credibility (The John D. and Catherine T. MacArthur Foundation Reports on Digital Media and Learning)
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.2: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.2: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\aaron\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\aaron\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2598224866' and UserName '6161726f6e'
DeDRM v6.5.2: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Kids and Credibility: An Empirical Examination of Youth, Digital Media Use, and Information Credibility (The John D. and Catherine T. MacArthur Foundation Reports on Digital Media and Learning)
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.2: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.3 seconds
Added Kids and Credibility: An Empirical Examination of Youth, Digital Media Use, and Information Credibility (The John D. and Catherine T. MacArthur Foundation Reports on Digital Media and Learning) to db in: 1.3
Added 1 books in 2.1 seconds
Worker Launch took: 0.171999931335
Job: 1 Convert book 1 of 1 (Kids and Credibility: An Empirical Examination of Youth, Digital Media Use, and Information Credibility (The John D. and Catherine T. MacArthur Foundation Reports on Digital Media and Learning)) finished
Convert book 1 of 1 (Kids and Credibility: An Empirical Examination of Youth, Digital Media Use, and Information Credibility (The John D. and Catherine T. MacArthur Foundation Reports on Digital Media and Learning))
	Resolved conversion options
	calibre version: 2.76.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\aaron\\AppData\\Local\\Temp\\calibre_n3kh3f\\9rozww.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x040737D0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleDXOutput object at 0x04073B50>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\aaron\\AppData\\Local\\Temp\\calibre_n3kh3f\\wbbzq9.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\aaron\AppData\Local\Temp\calibre_n3kh3f\6eggzp.azw
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Kids and Credibility: An Empirical Examination of Youth, Digital Media Use, and Information Credibility (The John D. and Catherine T. MacArthur Foundation Reports on Digital Media and Learning) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1064, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 146, in check_for_drm
	calibre.ebooks.DRMError: Kids and Credibility: An Empirical Examination of Youth, Digital Media Use, and Information Credibility (The John D. and Catherine T. MacArthur Foundation Reports on Digital Media and Learning)

**Comment by ElleKayEm** [comment]
Is the book not from the current installation of Kindle for PC?

Oh, wait, you've just closed the issue.  Got it sorted out?

**Comment by shiuh** [comment]
yes got it sorted.    Turns out i have adobe edition installed, just unistalled it.
Download a fresh copy of the ebook, should work fine.

**Comment by ElleKayEm** [comment]
Adobe Digital Editions doesn't matter for a Kindle book.
