### ISSUE TITLE
[QUESTION] How to use installation scripts in Arch?

### ISSUE THREAD

**Issue by hackmalife** [apprenticeharper/DeDRM_tools#1707]
I ran https://github.com/apprenticeharper/DeDRM_tools/wiki/Installing-ADE-on-Arch-Linux-via-WINE script.
I did the first option which installs dependencies, but I can't run second option. It gives me the error as follows:

```log
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.
```

Did I miss someting else? should I have my own adobekey to run second option?  if then, what is adobekey, and how should I get one? should I create my adobe account?
I am a newbie, please understand my ignorance..
Thanks

**Comment by ElleKayEm** [comment]
adobekey.py is the Python script in DeDRM which retrieves the Abobe DRM key from your installation of ADE.

**Comment by hackmalife** [comment]
thanks a lot!
