### ISSUE TITLE
Decrypting a .azw downloaded from a remote PC

### ISSUE THREAD

**Issue by gardavis** [apprenticeharper/DeDRM_tools#1710]
I have Kindle for PC 1.17 and Calibre 5.18 installed on my home server. Downloading a book via Kindle for PC and adding it to Calibre decrypts fine.

I also installed Kindle 1.17 on my laptop, downloaded a book and used the web interface to the Calibre content server to add it. The add works but decryption fails. I read in the FAQ that the Kindle for PC and Calibre need to be on the same server but wonder if what I am trying is possible by adding the laptop's Kindle key to the plug-in? If so, how do I get the key off the laptop's Kindle for PC to import into Calibre's DeDRM plugin?

I also tried coping the working .azw file from the initial successful add from the server to the laptop and tried the Calibre web interface add. This was successful proving the web interface add function does go thru the DeDRM as it should.

Thanks,\
Gary Davis

## Log of decrypt failure (web-add from remote laptop):

    Gather KFX-ZIP (from KFX Input) 1.39.0: Importing C:\Users\gary\AppData\Local\Temp\calibre_p71d8jel\hux20ttg_import_plugin.azw
    Gather KFX-ZIP (from KFX Input): File is not KFX format
    DeDRM v7.2.1: Trying to decrypt hux20ttg_import_plugin.azw
    Using Library AlfCrypto DLL/DYLIB/SO
    Using Library AlfCrypto DLL/DYLIB/SO
    MobiDeDrm v1.0.
    Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
    Decrypting Kindle Format 8 ebook: Think Like a Feminist: The Philosophy Behind the Revolution
    Got DSN key from database default_key
    Got DSN key from database default_key_2
    Got DSN key from database default_key_3
    Found 6 keys to try after 0.1 seconds
    Crypto Type is: 2
    DeDRM v7.2.1: Failed to decrypt with error: No key found in 6 PIDs tried.
    DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
    searching for kinfoFiles in C:\Users\gary\AppData\Local
    Found K4PC 1.25+ kinf2018 file: C:\Users\gary\AppData\Local\Amazon\Kindle\storage\.kinf2018
    Found K4PC 1.9+ kinf2011 file: C:\Users\gary\AppData\Local\Amazon\Kindle\storage\.kinf2011
    Decrypted key file using IDString '1353121189' and UserName 'gary'
    Decrypted key file using IDString '1353121189' and UserName 'gary'
    DeDRM v7.2.1: Ultimately failed to decrypt after 4.9 seconds. Read the FAQs at Harper's repository: 
    https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
    Running file type plugin DeDRM failed with traceback:
    Traceback (most recent call last):
    File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 6 PIDs tried.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
    File "calibre_plugins.dedrm.__init__", line 633, in run
    File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 4.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
    Received server change event: BooksAdded(book_ids=3042) for E:\Data\eBooks\Calibre
    Traceback (most recent call last):
    File "calibre\gui2\jobs.py", line 170, in update
    KeyboardInterrupt

## Log of decrypt success (local add on server itself):

    piped data from file dialog helper: [b'\xd2{\xd1\xd4\x17_fC\xa4eLN\x9a\xc1\xba\x06:\xb6\xca\x16\xedf?%\x1f\xdcQIL\xde$u', b'C:\\Users\\gary\\Documents\\My Kindle Content\\B085RN1328_EBOK.azw']
    Gather KFX-ZIP (from KFX Input) 1.39.0: Importing C:\Users\gary\Documents\My Kindle Content\B085RN1328_EBOK.azw
    Gather KFX-ZIP (from KFX Input): File is not KFX format
    DeDRM v7.2.1: Trying to decrypt B085RN1328_EBOK.azw
    Using Library AlfCrypto DLL/DYLIB/SO
    Using Library AlfCrypto DLL/DYLIB/SO
    MobiDeDrm v1.0.
    Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
    Decrypting Kindle Format 8 ebook: Think Like a Feminist: The Philosophy Behind the Revolution
    Got DSN key from database default_key
    Got DSN key from database default_key_2
    Got DSN key from database default_key_3
    Found 6 keys to try after 0.1 seconds
    Crypto Type is: 2
    File is encoded with PID Vmj1OoW9BH.
    Decrypting. Please wait . . . . done
    Decryption succeeded after 0.2 seconds
    DeDRM v7.2.1: Finished after 0.2 seconds
    Added Think Like a Feminist: The Philosophy Behind the Revolution to db in: 1.2
    Added 1 books in 2.2 seconds

**Comment by ElleKayEm** [comment]
Each installation of Kindle for PC has its own unique key.  To get the key for books downloaded with Kindle for PC currently installed on the laptop, have calibre with DeDRM on the same machine and user.  After successfully adding and decrypting a book there, you could save the key and import into the other setup's DeDRM customization.

**Comment by gardavis** [comment]
Thanks. That worked. It requires installing the Calibre program on the laptop temporarily (with the plugin) to get the key exported, an extra step, but it is a one-time and fairly quick.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
