### ISSUE TITLE
problem with deDRM

### ISSUE THREAD

**Issue by fefeyeah** [apprenticeharper/DeDRM_tools#172]
calibre Log di debug
calibre 2.56  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
Started up in 10.46 seconds with 2 books
DeDRM v6.5.2: Trying to decrypt Il teatro romantico.epub
DeDRM v6.5.2: Verifying zip archive integrity
DeDRM v6.5.2: Il teatro romantico.epub is a secure Adobe Adept ePub
DeDRM v6.5.2: Trying Encryption key default_key
DeDRM v6.5.2: Decrypted with key default_key after 0.6 seconds
DeDRM v6.5.2: Finished after 0.6 seconds
Added Il teatro romantico to db in: 1.7
Added 1 books in 3.1 seconds

**Comment by ElleKayEm** [comment]
This log shows a successful DRM removal.  What's the problem?

**Comment by apprenticeharper** [comment]
No problem that I can see. Closed.
