### ISSUE TITLE
DRM not removed in Calibre 5.19

### ISSUE THREAD

**Issue by giblim** [apprenticeharper/DeDRM_tools#1720]
Ubuntu 20.04 LTS with virtual Windows 10 client 
Calibre 5.19
DeDrm Plugin 
[tmpfhdv0fw7.txt](https://github.com/apprenticeharper/DeDRM_tools/files/6562076/tmpfhdv0fw7.txt)
7.2.1

**Comment by ElleKayEm** [comment]
Looks like you have Windows calibre and Kindle for PC installed in the virtual machine, but this book wasn't downloaded with the app.  If it's from or for an E-ink Kindle (not a Fire), then you need to have the Kindle's serial number entered into DeDRM's customization.

**Comment by giblim** [comment]
It's a White Paper, so I think I'll have to proceed with customization.
Which file in the plugin zip ?
Thanks for your help.

**Comment by giblim** [comment]
I modified the plugin and what a progress - it runs with Calibre 5.19 and
the 7.2.1 DeDRM with Ubuntu 20.04 LTS !
Thanks a lot for your help !

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by giblim** [comment]
Okay,
Calibre 5.19 runs with DeDRM 7.2.1 with Ubuntu 20.04 LTS and Windows 10
Thanks
