### ISSUE TITLE
PDF is not being decrypted

### ISSUE THREAD

**Issue by brenn0** [apprenticeharper/DeDRM_tools#1721]

**Comment by brenn0** [comment]
.

**Comment by ElleKayEm** [comment]
Try calibre 4.23 and DeDRM 6.8.1.

**Comment by brenn0** [comment]
I tried and didn't work

**Comment by ElleKayEm** [comment]
Is Adobe Digital Editions on the same machine and user as calibre with DeDRM?  Was it authorized with your Adobe ID before opening the acsm file?

**Comment by brenn0** [comment]
I don't have adobe account. I bought this ebook 3 years ago on a website like ebay of my country. Is it possible to remove the DRM? I want to read this book in my Kindle, I would even buy it, but it is no longer sold in my language.

**Comment by ElleKayEm** [comment]
Doesn't sound like it has DRM that these tools can decrypt.  What program do you use to read it?
