### ISSUE TITLE
Unable to deDRM azw4

### ISSUE THREAD

**Issue by aurea1300** [apprenticeharper/DeDRM_tools#174]
Hi,
I am having difficulty removing DRM from a purchased kindle book. Thus far I have removed the DRM on several books (azw3, and azw4) up until now. I'm not sure if it has something to do with the file size or not (420 MB). I hope there is a simple fix. The only other difference between this book and the others is that I updated Calibre. 

Your help is greatly appreciated.

calibre, version 2.76.0 (win32, embedded-python: True)
Conversion Error: Failed: Convert book 1 of 1 (Maternal Family)

Convert book 1 of 1 (Maternal Family)
Resolved conversion options
calibre version: 2.76.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\Draco\\AppData\\Local\\Temp\\calibre_pigrkc\\tfzzzc.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x03AB3B70>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'old_pdf_engine': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x03AB3ED0>,
 'override_profile_size': False,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier New',
 'pdf_mono_font_size': 16,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'Times New Roman',
 'pdf_standard_font': u'serif',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Draco\\AppData\\Local\\Temp\\calibre_pigrkc\\z8ff4w.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
Python function terminated unexpectedly
  No embedded PDF found in AZW4 file (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 132, in main
  File "site.py", line 109, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1050, in run
  File "site-packages\calibre\ebooks\azw4\reader.py", line 24, in unwrap
ValueError: No embedded PDF found in AZW4 file

**Comment by ElleKayEm** [comment]
Can't tell from this log that there is an issue with DRM.  Try using the KindleUnpack plugin instead of calibre conversion.  The size could be the problem.  If possible, try 64-bit calibre.

**Comment by apprenticeharper** [comment]
Trying to remove DRM from a 420MB file in 32-bit calibre will fail from lack of memory. It will work in 64-bit calibre if your machine has enough to make 64-bit calibre worthwhile (about 4GB or more).

I have no plans to try to make the tools more memory efficient at present.
