### ISSUE TITLE
PDF DeDRM fails with: error writing pdf: max() arg is an empty sequence

### ISSUE THREAD

**Issue by eugene-sotirescu** [apprenticeharper/DeDRM_tools#1741]
The PDF in question opens fine and can be read using Adobe Digital Editions 4.5.
When imported into Calibre, the PDF cannot be opened as it is still DRMd.
Removed it from Calibre, started Calibre in debug mode and reimported it with same results.
Logs below.
(And yes, I did restart Calibre several times after installing the DeDRM plugin).
Appreciate any help.

## My Environment
###Windows 10
## Log
calibre-debug -g
calibre 5.21  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Extract ISBN (1, 5, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.67567567567568
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.72] splash screen shown
[0.72] Initializing db...
[0.73] db initialized
[0.73] Constructing main UI...
[2.17] main UI initialized...
[2.17] Hiding splash screen
Starting QuickView
[2.53] splash screen hidden
[2.53] Started up in 2.53 seconds with 0 books
DeDRM v7.2.1: Trying to decrypt ZXY.pdf
DeDRM v7.2.1: ZXY.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.7 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.7 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 1.1 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added ZXY.pdf to db in: 0.2
Added 1 books in 2.6 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 433, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 347, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1

**Comment by eugene-sotirescu** [comment]
this has been commented in other posts, closing.

**Comment by ElleKayEm** [comment]
Were you able to do it with calibre 4.23 and DeDRM 6.8.1?
