### ISSUE TITLE
Unable to install DeDRM - Permission denied

### ISSUE THREAD

**Issue by N8AJZ** [apprenticeharper/DeDRM_tools#1744]
I'm getting a permissions error when trying to install the DeDRM plugin.  I've tried running it as Administrator as well as my user.  I downloaded the Tools 7.2.1 and unzipped the file, which I put in a folder called DeDRM_calibre_plugin.  I've fiddled with the parameters to calibre-customize and just can't seem to get it to work for me.  

What am I doing wrong?

## Log

Microsoft Windows [Version 10.0.19041.1052]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd c:\users\connie\desktop\dedrm\

c:\Users\Connie\Desktop\dedrm>dir
 Volume in drive C is Windows
 Volume Serial Number is 58C0-7BA6

 Directory of c:\Users\Connie\Desktop\dedrm

06/22/2021  08:15 PM    <DIR>          .
06/22/2021  08:15 PM    <DIR>          ..
06/22/2021  08:17 PM    <DIR>          DeDRM_calibre_plugin
06/22/2021  07:46 PM           447,790 DeDRM_tools_7.2.1.zip
               1 File(s)        447,790 bytes
               3 Dir(s)  572,486,336,512 bytes free

c:\Users\Connie\Desktop\dedrm>calibre-customize -a DeDRM_calibre_plugin \DeDRM_calibre_plugin\DeDRM_plugin.zip
Integration status: True
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\customize\ui.py", line 830, in main
  File "calibre\customize\ui.py", line 477, in add_plugin
  File "calibre\customize\ui.py", line 65, in load_plugin
  File "calibre\customize\zipplugin.py", line 283, in load
  File "zipfile.py", line 1251, in __init__
PermissionError: [Errno 13] Permission denied: 'DeDRM_calibre_plugin'

c:\Users\Connie\Desktop\dedrm>cd DeDRM_calibre_plugin

c:\Users\Connie\Desktop\dedrm\DeDRM_calibre_plugin>dir
 Volume in drive C is Windows
 Volume Serial Number is 58C0-7BA6

 Directory of c:\Users\Connie\Desktop\dedrm\DeDRM_calibre_plugin

06/22/2021  08:17 PM    <DIR>          .
06/22/2021  08:17 PM    <DIR>          ..
06/22/2021  08:17 PM    <DIR>          DeDRM_plugin
04/11/2021  04:39 PM           379,219 DeDRM_plugin.zip
04/11/2021  04:39 PM             2,198 DeDRM_plugin_ReadMe.txt
04/11/2021  04:39 PM            72,618 Obok_plugin.zip
04/11/2021  04:39 PM             2,220 obok_plugin_ReadMe.txt
04/11/2021  04:39 PM             4,323 ReadMe_Overview.txt
               5 File(s)        460,578 bytes
               3 Dir(s)  572,486,094,848 bytes free

c:\Users\Connie\Desktop\dedrm\DeDRM_calibre_plugin>

```log

```
</details>

**Comment by N8AJZ** [comment]
Oops

DeDRM: Version from Tools 7.2.1

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_7.2.1.zip and load DeDRM_plugin.zip.

**Comment by N8AJZ** [comment]
Hi ElleKayEm,  thanks for the response.  

That's what I did.  I unzipped the DeDRM_tools_7.2.1.zip into a folder called DeDRM_calibre_plugin and tried to load with this command while in the parent folder to the DeDRM_calibre_plugin folder.


 Directory of C:\Users\Connie\Desktop\dedrm

06/22/2021  08:15 PM    <DIR>          .
06/22/2021  08:15 PM    <DIR>          ..
06/22/2021  08:17 PM    <DIR>          DeDRM_calibre_plugin
06/22/2021  07:46 PM           447,790 DeDRM_tools_7.2.1.zip
               1 File(s)        447,790 bytes
               3 Dir(s)  572,739,129,344 bytes free

C:\Users\Connie\Desktop\dedrm>**calibre-customize -a DeDRM_calibre_plugin DeDRM_plugin.zip**
Integration status: True
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\customize\ui.py", line 830, in main
  File "calibre\customize\ui.py", line 477, in add_plugin
  File "calibre\customize\ui.py", line 65, in load_plugin
  File "calibre\customize\zipplugin.py", line 283, in load
  File "zipfile.py", line 1251, in __init__
PermissionError: [Errno 13] Permission denied: 'DeDRM_calibre_plugin'

C:\Users\Connie\Desktop\dedrm>

**Comment by j-howell** [comment]
You are missing a backslash. The command should be:

calibre-customize -a DeDRM_calibre_plugin\DeDRM_plugin.zip

**Comment by N8AJZ** [comment]
LORD I HATE IT when it's something so silly!  thank you j-howell and ElleKayEm!  That loaded.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by N8AJZ** [comment]
ID10T user error.  thanks all.
