### ISSUE TITLE
New Amazon book type?

### ISSUE THREAD

**Issue by bkennelly** [apprenticeharper/DeDRM_tools#175]
I am getting an error importing an AZW file today.  The error is:
  Unknown book type: '\x81\xc4\xde\x02|\x8c"\x08' (Error Code: 1)

calibre, version 2.76.0 (win32, embedded-python: True)
Conversion Error: Failed: Convert book 1 of 1 (B00K27C428 EBOK)

Convert book 1 of 1 (B00K27C428 EBOK)
Resolved conversion options
calibre version: 2.76.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000000055E7A58>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.NookOutput object at 0x00000000055F9278>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\BKENNE~1\\AppData\\Local\\Temp\\calibre_uadinw\\jkvzr1.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\BKENNE~1\AppData\Local\Temp\calibre_uadinw\avivgj.azw
Python function terminated unexpectedly
  Unknown book type: '\x81\xc4\xde\x02|\x8c"\x08' (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 132, in main
  File "site.py", line 109, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1064, in run
  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 34, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 81, in __init__
calibre.ebooks.mobi.MobiError: Unknown book type: '\x81\xc4\xde\x02|\x8c"\x08'

**Comment by ElleKayEm** [comment]
Post an import log.  DRM removal happens when you add the book, not during conversion.

**Comment by bkennelly** [comment]
Sorry about that.  I thought the error dialogue came from the plugin.  Using Calibre-debug, it is a decryption problem. 

Content\\B00K27C428_EBOK\\B00K27C428_EBOK.azw']
DeDRM v6.5.2: Trying to decrypt B00K27C428_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
DeDRM v6.5.2: Failed to decrypt with error: Invalid file format
DeDRM v6.5.2: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\bkennelly\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\bkennelly\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '718477891' and UserName '626b656e6e656c6c79'
DeDRM v6.5.2: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
DeDRM v6.5.2: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.2 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 419, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 283, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 276, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 304, in identity

**Comment by bkennelly** [comment]
Thanks.  It was one of five new books, all downloaded to subdirectories.  The others were all successfully decrypted.

**Comment by ElleKayEm** [comment]
You can still download 1.17.1 right now from Amazon here:
https://s3.amazonaws.com/kindleforpc/44183/KindleForPC-installer-1.17.44183.exe

Go into the Tools > Options > General and uncheck automatically install updates.

**Comment by apprenticeharper** [comment]
New error message included in the DeDRM 6.5.3 release
