### ISSUE TITLE
Can't decrypt kindle e-book

### ISSUE THREAD

**Issue by dtlnor** [apprenticeharper/DeDRM_tools#1755]
System: windows 10 21h1
calibre: 4.23/latest
plugin: 6.8.1/7.2.1
ploblem:
I bought a kindle book from amazon released today(1st July), I cannot decryte the book like what I always do.
I tried latest kindle for PC without KFX, 1.26, 1.29, 1.7, with or without KFX, still cannot decryte the book
I also tried download via usb, I entered the serial number of my paperwhite, that file cannot decryte too.
here is the sample file(azw from kindle for PC 1.7)
edited

**Comment by ElleKayEm** [comment]
Are you using 64-bit calibre?

**Comment by dtlnor** [comment]
> Are you using 64-bit calibre?

32bit calibre 4.23
