### ISSUE TITLE
How to find the Kindle for PC keys?

### ISSUE THREAD

**Issue by JZH19970612** [apprenticeharper/DeDRM_tools#1756]
System: windows 10
calibre: 5.22/latest
plugin: 7.2.1
ploblem: I have bought a book on amazon.co.jp. I download it using the Kindle for PC on my laptop and I cannot deDRM it using this tool. I think it may because I don't have the key for it. So where can I find the key?
Thanks!

**Comment by ElleKayEm** [comment]
DeDRM will retrieve the key as long as Kindle for PC used to download the book is on the same machine and user as calibre with DeDRM.  You'll also want to have KFX downloads disabled or use no later than Kindle for PC 1.26.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by JZH19970612** [comment]
Thank you! I download a Kindle for PC 1.17 and try it again but it still told me the book was locked. Do I need to do something in the customize DeDRM option? or some other way to let the tool find the key? Or maybe it is because the book is too new which is just published on July 1st?

**Comment by ElleKayEm** [comment]
Let's see a log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by JZH19970612** [comment]
Thank you ! I find it. Here it is:

calibre 调试日志
calibre 5.22.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.22.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 94.51162790697674 x 94.51162790697674
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.31] splash screen shown
[0.31] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
Using proxies: {'http': '127.0.0.1:1080', 'https': '127.0.0.1:1080', 'ftp': '127.0.0.1:1080'}
[0.66] main UI initialized...
[0.66] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B097CTTG1T_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
DeDRM v7.2.1: Failed to decrypt with error: tuple index out of range
DeDRM v7.2.1: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\JZH19970612\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\JZH19970612\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2156884211' and UserName 'JZH19970612'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Using proxies: {'http': '127.0.0.1:1080', 'https': '127.0.0.1:1080', 'ftp': '127.0.0.1:1080'}
[8.97] splash screen hidden
[8.97] Started up in 8.97 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"F\x86\xfb\xa6\x9d\xdf\xf3W\x1cl'>\x91\xc2\xb4J\x8a\xfexf\xde\xfe\xf2\xd4\x10\xdc\x92\x95\x88\xccx\x9f", b'C:\\Users\\JZH19970612\\OneDrive\\\xe6\x96\x87\xe6\xa1\xa3\\My Kindle Content\\B097CTTG1T_EBOK.azw']
Added モンスターハンターライズ 公式ガイドブック (カプコンファミ通) to db in: 0.4
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.mobidedrm", line 319, in __init__
  File "calibre_plugins.dedrm.mobidedrm", line 377, in patchSection
  File "calibre_plugins.dedrm.mobidedrm", line 367, in patch
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 217, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 326, in __init__
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/maAdded 1 books in 1.2 seconds

**Comment by ElleKayEm** [comment]
Switch to calibre 64-bit.

**Comment by JZH19970612** [comment]
Oh! Thank you! I will try it now.

**Comment by JZH19970612** [comment]
Thank you so much! It works!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by JZH19970612** [comment]
OK！
