### ISSUE TITLE
DeDRM 7.2.1 + Calibre 5.22.1 Can't decrypt topaz file

### ISSUE THREAD

**Issue by diazbastian** [apprenticeharper/DeDRM_tools#1758]
Hi, I have systematically tried all available methods to decrypt a topaz/awz1 kindle file using Calibre 5.x or DeDRM 7.2.1 unsuccessfully, however, downgrading Calibre to 4.23 with DeDRM version 6.8 there was no problem.

Methods used:
Previously, the plugin had the device's e-ink serial number and Kindle for PC 1.31 and outdated version 1.23. Other AWZ3 and KFX files had been successfully decrypted with the same settings.

- Downloading .tpz file from the web and importing it to Calibre
- Using Kindle for PC to download .azw1 file and import it into Calibre
- Updating Kindle for PC to download .azw1 file and import it into Calibre

None of the above methods worked.

What information do you need to contribute to improving the plugin?

Cheers

**Comment by ElleKayEm** [comment]
You can email ApprenticeHarper@gmail.com and see if they'll take a look.  They would need the encrypted book and the Kindle for PC key (which decrypts it) saved from DeDRM's customization.

**Comment by diazbastian** [comment]
Ok, it was already sent to email
