### ISSUE TITLE
Kindle AZW-format ebooks NOT stripping DRM with Calibre plugin

### ISSUE THREAD

**Issue by Chelle248** [apprenticeharper/DeDRM_tools#176]
Hi. I have the latest version of Calibre and the latest version of the DRM plugin but it will not strip DRM.

I have re-downloaded each book. They open fine in Kindle for PC. Re-loaded into Calibre. No change.. Stays AZW and cannot open.

I downloaded Ultimate Epubsoft DRM removal tool and it came up "Your book is protected by a kind of DRM we do not support"

I opened Calibre in Debug mode and got these results. I do hope someone can help. I have tried everything I can think of. I am not technical in these matters.

calibre Debug log
calibre 2.76  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 2) && Read MP3 AudioBook metadata (1, 0, 79)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9842323651 x 71.9822878229
Starting up...
Started up in 11.90 seconds with 15 books
stdout+stderr from file dialog helper: ['', '']
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['JV\xaf\xb4\x12\x96\xbe\x8f\xb9j\x9d_b\xf4\x88\x073\x8a\xae\xf1\xf6\x16\xb3\xe8\xbc\x1ahH\xd3\xf1(}', 'C:\\Users\\David\\Documents\\My Kindle Content Store\\B01L05ODTW_EBOK\\B01L05ODTW_EBOK.azw']
DeDRM v6.5.2: Trying to decrypt B01L05ODTW_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
DeDRM v6.5.2: Failed to decrypt with error: Invalid file format
DeDRM v6.5.2: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\David\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\David\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2342166968' and UserName '4461766964'
DeDRM v6.5.2: Found 1 new key
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
DeDRM v6.5.2: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.4 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 419, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 283, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 276, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 304, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B01L05ODTW EBOK to db in: 1.2
Added 1 books in 2.2 seconds

![drm](https://cloud.githubusercontent.com/assets/24976808/21742982/21a99846-d502-11e6-8ea6-3254d4fc47e4.JPG)

**Comment by ElleKayEm** [comment]
If you're using Kindle fo PC version 1.19, that is the problem.  Right now you can still download the earlier version 1.17 from Amazon and that will download books you can DeDRM.  When you install 1.17, go to the Tools menu, Options and uncheck "automatically update."

**Comment by Chelle248** [comment]
Thank you SOOOOOO much! I have spent 2 days trying to sort this out. DRM really limits my use of books bought and I would have stopped buying Kindle books. I use TTS software and DRM interferes with this. I cannot tell you how much I appreciate that you took the time to stop by and help me with this.

**Comment by ElleKayEm** [comment]
Eventually, Amazon will force us to update Kindle for PC.  Hopefully, a solution for this new format will have been figured out by then.

**Comment by Chelle248** [comment]
The same thought crossed my mind
