### ISSUE TITLE
Unable to remove DRM from Kindle ebook

### ISSUE THREAD

**Issue by danquick6926** [apprenticeharper/DeDRM_tools#178]
I just purchased a Kindle book that downloaded to my device in kfx format, so I used the Download and Transfer link on the Kindle page and got an azw and added that to Calibre. When I tried to open it, I got the DRM protection notice regardless. Updated Calibre and reinstalled the plugin, but neither worked. Here's the debug log. Any help is appreciated!

DeDRM v6.5.2: Trying to decrypt Reading the Holocaust.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 3
Decrypting Mobipocket 6 ebook: Reading the Holocaust
Found 6 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.5.2: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.5.2: Looking for new default Kindle Key after 0.6 seconds
Found k4Mac kinf2011 file: /Users/danquick/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '99a2f137f0f5' and UserName 'danquick'
DeDRM v6.5.2: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 3
Decrypting Mobipocket 6 ebook: Reading the Holocaust
Found 4 keys to try after 1.8 seconds
Crypto Type is: 2
DeDRM v6.5.2: Ultimately failed to decrypt after 1.8 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 1.8 seconds
DEBUG:    0.2 USBMS: scan from root False /Volumes/Kindle/documents

**Comment by ElleKayEm** [comment]
Was the device you chose for transfer an E-ink Kindle?  If so, you need to add its serial number to the plugin customization.  Otherwise, download Kindle for Mac version 1.17 from Amazon while you still can.  Then turn off automatic updates from the Tools > Options menu.

**Comment by danquick6926** [comment]
Adding the serial number did the trick, thanks! Just got a new Kindle and forgot that step from when I started using deDRM years ago.
