### ISSUE TITLE
DeDRM fails with message: AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by GeekTieGuy** [apprenticeharper/DeDRM_tools#1788]
[BookAndLog.zip](https://github.com/apprenticeharper/DeDRM_tools/files/6897650/BookAndLog.zip)

calibre version 5.22.1 (debug run/book import)
DeDRM v7.2.1

**Comment by ableeker** [comment]
According to the log the key for this Topaz ebook was found, but then an error occurred. To replicate the error, we need not only the book, but the key file too. Could you export the key as an .k4i file, and attach that as well?

**Comment by GeekTieGuy** [comment]
Is there a way to get that key to you privately @ableeker? I'm not sure if I would want everyone to be able to download the zip with the book and then have the key right next to it.

**Comment by ableeker** [comment]
I get it. You can send it to dedrm_tab@outlook.com.

**Comment by GeekTieGuy** [comment]
I sent it some days ago and it might have gone into spam/junk, so I just wanted to check if you saw it come through?

**Comment by ableeker** [comment]
I've received the file, but at the moment I'm unable to check out the issue. I will have a look as soon as I can.

**Comment by GeekTieGuy** [comment]
Great! Thanks for confirming. Take all the time you need.

**Comment by GeekTieGuy** [comment]
100% confirmed - works beautifully. Wonderful job. I SO appreciate your efforts. Thank you! I'm closing this.
