### ISSUE TITLE
Calibre not deDRMing all books

### ISSUE THREAD

**Issue by shizhenni214** [apprenticeharper/DeDRM_tools#179]
Using Calibre 2.49 along with DeDRM_tools_6.5.2. The book was downloaded from the Amazon Kindle PC program as a AZW file format. I have imported another book and it worked just fine. Any help would be appreciated. Thank you.

calibre Debug log
calibre 2.49  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 4.48 seconds with 10 books
DeDRM v6.5.2: Trying to decrypt B00E3BVJ7A_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Last, Long Night (#5 in the Bregdan Chronicles Historical Fiction Romance Series)
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.5.2: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.2: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\Jenna\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Jenna\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '480610304' and UserName '4a656e6e61'
DeDRM v6.5.2: Ultimately failed to decrypt after 0.5 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 152, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.5 seconds
Added The Last, Long Night (#5 in the Bregdan Chronicles Historical Fiction Romance Series) to db in: 0.9
Added 1 books in 2.4 seconds

**Comment by apprenticeharper** [comment]
Was the book downloaded on the same computer/user account as the one you're running calibre on?

**Comment by ElleKayEm** [comment]
Has your installation of Kindle for PC updated to 1.19?  If so, that's likely the problem.  Download version 1.17 from Amazon while you still can.  Then turn off automatic updates under the Tools > Options menu.

**Comment by shizhenni214** [comment]
The book was downloaded on one computer and I am trying to use calibre on another computer.

My Kindle PC version is 1.17.1. I have now disabled automatic updates.

**Comment by ElleKayEm** [comment]
Each installation of Kindle for PC has its own unique key.  Download the book with the one that's on the same machine and user as calibre.

**Comment by shizhenni214** [comment]
Ok. Tried it on the same computer and it worked. Thank you.
