### ISSUE TITLE
[QUESTION] help, kobo, removing drm, kobo device serial number ?

### ISSUE THREAD

**Issue by promeneur** [apprenticeharper/DeDRM_tools#1794]
### obokDeDRM '7.2.1'

1. about: obok DEDRM settings

I don't get any kobo tablet.
I want to buy some kobo books that I don't find at amazon. Furthermore, I want to read them with Fbreader with my smartphone.
In obok DeDRM settings there is "kobo device serials" parameter. I don't get any kobo device serial number. Is it necessary ?

Thanks

**Comment by lnxme** [comment]
I don't have any "Kobo Device serials" and regularly download DRM'ed books from Kobo using the Kobo Desktop without issues. Obok happily removes the DRM for me so I can read them on a Nook reader.

**Comment by l-l-l-l-l-l** [comment]
Or you can just download the books in ADE from your Kobo account, which is what I do. As long as you use an activated ADE 2 to download the book, the plugin will autodetect the key and deDRM it. AFAIK you can later shift to ADE 5 as long as the plugin has already gotten the key.

**Comment by promeneur** [comment]
> Or you can just download the books in ADE from your Kobo account, which is what I do. As long as you use an activated ADE 2 to download the book, the plugin will autodetect the key and deDRM it. AFAIK you can later shift to ADE 5 as long as the plugin has already gotten the key.

Ok, I installed ade with the script for Arch (i modified it according to run it with openSUSE)

I downloaded a book with kobo. This book is in "kepub" folder of kobo.

I open ade
then i use the feature "add to the bookshelves"
i go the "kepub" folder
ade does not see any book in this folder because the name of the book is something as dcf90921-....-d2d139ec7d40

How do you import a book to ade bookshelves ?

**Comment by promeneur** [comment]
> Or you can just download the books in ADE from your Kobo account, which is what I do. As long as you use an activated ADE 2 to download the book, the plugin will autodetect the key and deDRM it. AFAIK you can later shift to ADE 5 as long as the plugin has already gotten the 

Ok i understand we must open an .acsm file to import a book, but there is no .acsm file in any folder of kobo app in my pc.

Do you assume I must connect a kobo ereader then I import from the device the book ?

**Comment by promeneur** [comment]
i created an acsm file for the book using kobo site with my kobo account.

i open this acsm file in ade 2.0.1. The book is imported in ade but the layout is foolish.

i can import the book in calibre. The book is decrypted but the layout is foolish.

i installed a separate ade 4.5.11. i imported the book in ade but the layout is foolish.

Even adobe tools does not understand the layout of the book!

See my report https://github.com/apprenticeharper/DeDRM_tools/issues/1796

**Comment by ElleKayEm** [comment]
This issue can be closed.  DRM issue is resolved.
