### ISSUE TITLE
kobo, import ok,  unreadable epub

### ISSUE THREAD

**Issue by promeneur** [apprenticeharper/DeDRM_tools#1796]
Linux OpenSuse Leap 15.2
Calibre: 5.24.0
Kobo-desktop: 4.28.15823 installed with wine
DeDRM: 7.2.1
obokDeDRM '7.2.1'

## Log
<details><summary>Log Title</summary>

```calibre Journal de débogage
calibre 5.24  embedded-python: True is64bit: True
Linux-5.3.18-lp152.84-preempt-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.3.18-lp152.84-preempt', '#1 SMP PREEMPT Tue Jul 20 23:04:11 UTC 2021 (baaeecf)')
Python 3.8.5
Interface language: fr
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 5.24  embedded-python: True is64bit: True
Linux-5.3.18-lp152.84-preempt-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.3.18-lp152.84-preempt', '#1 SMP PREEMPT Tue Jul 20 23:04:11 UTC 2021 (baaeecf)')
Python 3.8.5
Interface language: fr
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.125
logicalDpi: 96.0 x 96.0
physicalDpi: 81.65310734463276 x 81.55183946488295
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.10] splash screen shown
[0.10] Initializing db...
Failed to read metadata from font file: /usr/share/fonts/truetype/TSCu_Comic.ttf tuple index out of range
Failed to read metadata from font file: /usr/share/fonts/truetype/TSCu_Times.ttf tuple index out of range
[0.12] db initialized
[0.12] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.74] main UI initialized...
[0.74] Hiding splash screen
Starting QuickView
/bin/sh: ipconfig : commande introuvable


```
</details>

Hello

i imported without error message a kobo book.

when i tried to read it with calibre viever, fbreader or okular then i can't  read the book.
the layout of the book is very bad.
this is a pocket book with about 300 pages.
when opening the book it consumes much cpu power during several mns before to display the book.
i  attached some captures.

you see the index. 2657 pages !
many blank pages.

![first_page](https://user-images.githubusercontent.com/240424/128628317-d9403aa0-06d5-4e40-b890-9d8c08e177a3.png)
![page_3](https://user-images.githubusercontent.com/240424/128628319-04461924-0f4f-4224-8e5b-5fd9050fb404.png)
![page_6](https://user-images.githubusercontent.com/240424/128628320-a07198da-5143-4faf-bdf7-5baca52adc9c.png)
![page_9](https://user-images.githubusercontent.com/240424/128628321-a9b05196-625e-4cf3-80c4-13fd620b3b34.png)
![page_135](https://user-images.githubusercontent.com/240424/128628324-3f874bbb-eb21-4718-a48d-47530567a4a9.png)

**Comment by promeneur** [comment]
I explored the book with calibre editor.

All 624 pages (not 300 as iassumed) pages are well there. But they are images, not text.

![page_624_html](https://user-images.githubusercontent.com/240424/128631534-1a7d99e2-c2ae-4d10-b0bd-e2c9e5b0018a.png)
![page_624_jpeg](https://user-images.githubusercontent.com/240424/128631535-15fcafc8-139c-4654-97fa-3ddd1cd3a64d.png)

**Comment by promeneur** [comment]
If I read the book with kobo reader with my Smartphone, then  I can hardly read it. All is tiny. The layout is not adaptable to the size of the screen. There is no way to adjust font size. You can only use the zoom. This confirm that the editor Hachette (?) created not an ebook but a chain of images. Hachette dares to sell this kind of object !

**Comment by promeneur** [comment]
We need some kind of OCR program to convert this kind of epub to true epub

**Comment by promeneur** [comment]
My 3 last comments are false.

I unzipped the EPUB book created by calibre.

Now, I assume the layout of the book is completely erroneous. The text, the images are there, but they are not well combined. There is also a problem with font size.

We can't read the book with fbreader or calibre viewer.

**Comment by promeneur** [comment]
I explored the unzip epub book.
i displayed nav.xhtml (the root web page)with firefox.
we can't access to many pages because there is no link to go to the next page.
anyway in this page there is some sirt of index of all pages. We can indivdually display all pages one by one.
the layout of each one is correct. there is no problem.

My temporary conclusion : the composition of all the pages (to create the EPUB book) is erroneous.

**Comment by promeneur** [comment]
I checked the book with calibre editor. About 15000 errors !

I tried to fix them with calibre editor. Calibre editor used the whole ram (about 14 GB) and the whole swap 8 GB before blocking my pc !

**Comment by promeneur** [comment]
some other experiment

i used calibre 5.25 to import the book

i get some errors

calibre, version 5.25.0
AVERTISSEMENT : Erreurs pendant l'ajout: Il y a eu des problèmes lors de l'ajout de certains fichiers, cliquez "Afficher les détails" pour plus d'information


----------------------------------------------------------------------
Échec à ajouter le fichier /home/roubach/.PlayOnLinux/wineprefix/kobo/drive_c/Program Files/Kobo/kepub/dcf90921-5512-49f1-9319-d2d139ec7d40 au livre : dcf90921-5512-49f1-9319-d2d139ec7d40
Avec l'erreur :
Traceback (most recent call last):
  File "calibre/gui2/add.py", line 488, in add_formats
  File "calibre/db/cache.py", line 1579, in add_format
  File "calibre/db/cache.py", line 1536, in _do_add_format
  File "calibre/db/backend.py", line 1603, in add_format
  File "calibre/db/backend.py", line 1280, in construct_file_name
ValueError: Extension length too long: 98

and a new log

[tmpa9umircu.txt](https://github.com/apprenticeharper/DeDRM_tools/files/6987118/tmpa9umircu.txt)

**Comment by promeneur** [comment]
i bought the book here

https://www.kobo.com/fr/fr/search?query=Guide%20du%20Routard%20Normandie%202021%2F22%20(Collectif)&ac=1&acp=guide%20du%20routard%20normandie&ac.title=Guide%20du%20Routard%20Normandie%202021%2F22&ac.author=Collectif&sort=PublicationDateDesc

It is said : This ebook is a digital version of the paper guide without additional interactivity.
Perhaps this a beginning of an explanation.

**Comment by promeneur** [comment]
I bought another book.

I imported it to calibre. No problem to read it with an ebook reader.

This confirms the book is not a classic epub ebook where each page is composed with text with a layout adjustable to the size of the screen of a smartphone but something raw where each page is a picture.

If i try to read  the book with my smartphone with kobo app, each page is adjusted like a photo to my smartphone. It is unreadable because text is too tiny.

**Comment by promeneur** [comment]
I imported from kobo to ade (2.0.1) the book used acsm file (I created the acsm file of the book using my kobo count at kobo site) 

Ade 2.0.1 decrypts well the book, but the layout is foolish.

So I can't test importing the ade version to calibre using derdrm (not obok).

**Comment by ElleKayEm** [comment]
Neither of your debug logs shows activity from either Obok or DeDRM.

**Comment by promeneur** [comment]
> Neither of your debug logs shows activity from either Obok or DeDRM.

As i explained there is no problem for obok removing the drm.
The problem is that obok produces a book with a foolish layout
ADE importing from kobo the same book, produces also a foolish layout!

I assume that the format of this ebook is a very special one.
At kobo site it is said "This ebook is a digital version of the paper guide without additional interactivity".
Perhaps this a beginning of an explanation.

I bought another book which has a more standard format. There is no problem. drm is removed and we get a good layout thus a readable book.

**Comment by promeneur** [comment]
I can send you the kobo book. You will be able to investigate the problem.

**Comment by ElleKayEm** [comment]
If the DRM is removed, then this is not a DeDRM issue.

**Comment by promeneur** [comment]
Ok but the foolish layout is an issue what ?

**Comment by ElleKayEm** [comment]
I don't know.  MobileRead.com is a good place to ask about non-DRM related ebook issues.

**Comment by promeneur** [comment]
It is not a calibre problem ?

**Comment by ElleKayEm** [comment]
No idea.  There's a calibre sub-forum at MobileRead.

**Comment by promeneur** [comment]
I sent a bug report to calibre team.

thanks

**Comment by ElleKayEm** [comment]
You can close this issue.
