### ISSUE TITLE
The software requires PYTHON

### ISSUE THREAD

**Issue by trollcop** [apprenticeharper/DeDRM_tools#18]
In 2015, this is completely fucking unacceptable.
Stop forcing users to install shit they will never use again.

**Comment by magu** [comment]
On most modern operating systems, Python is installed by default.

**Comment by trollcop** [comment]
I am using Windows 8.1 Pro.

**Comment by magu** [comment]
Yup, I sad *most*, not all, modern operating systems. Blame Microsoft on not including one of the pillars of modern computing in their base install.

**Comment by magu** [comment]
If a specific tool is written in python, it's quite hard to use it without installing Python the program. Also, not requiring Python would both require rewriting the program in question, and providing specialized binaries for every single operating system you wish to target. Much simpler using something like Python for this sort of tool, since it runs on every system under the sun.

**Comment by trollcop** [comment]
So the goal of the project is to shittily run on "every system under the sun" and make it unusable on the only one that everyone actually uses? What's next, you will provide BeOS binaries?

rewriting these hacks in C would probably take less effort than maintaining the read-only garbage that is python.

**Comment by magu** [comment]
Runs fine for me. You're most welcome to rewrite it though, if you're so inclined.

**Comment by memoz** [comment]
Well, why don't you try creating this software yourself if you find it to
be unacceptable?
2015-6-13 下午4:20于 "dongie" <notifications@github.com>写道：

**Comment by ElleKayEm** [comment]
You could use the calibre plug-in.  Or you could buy the software that people have created from this free tool.

**Comment by trollcop** [comment]
calibre plugin is python last I checked.
inside the zip it was all the .py files.

**Comment by ElleKayEm** [comment]
But you only need to install python if you're using the stand alone tool.

**Comment by Lord-Evil** [comment]
Aww.. Looks like someone got his first period! :-D
How much of a brain damage one should have not to respect Python for what it is? It's one of the most powerful and popular tools out there for high level programming. I see no sane reason why would anybody give in easy CROSS-PLATFORM scripting solution(no platform dependant binaries) for C.
Go on, unpack your ASM and show us what you've got! xD

**Comment by trollcop** [comment]
> It's one of the most powerful and popular tools out there for high level programming. 

Not even close.

Its completely unreadable syntax, people writing it usually having no clue and just relying on pre-existing "libraries" to do most of the work so you end up with needing to install retarded dependencies just to run a simple dumb script.

And the read-only nature of the resulting code that nobody wants  to touch or maintain.

C is universal and anyone looking at it can immediately see what's going on.
Anything that takes more than 10 lines of python is probably faster to rewrite in C than try to figure out what the fuck it does.

**Comment by magu** [comment]
Then go right ahead and rewrite it. Put your money where your mouth is ...
