### ISSUE TITLE
Plugin does not install because "does not contain a top-level __init__.py file"

### ISSUE THREAD

**Issue by docaltmed** [apprenticeharper/DeDRM_tools#180]
calibre, version 2.77.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/home/avery/Downloads/DeDRM_tools_6.5.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 2.77  embedded-python: True is64bit: True
Linux-4.8.0-34-generic-x86_64-with-debian-stretch-sid Linux ('64bit', 'ELF')
('Linux', '4.8.0-34-generic', '#36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016')
Running Calibre 2.77.0

Python 2.7.9
Linux: ('debian', 'stretch/sid', '')
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 463, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 58, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 192, in load
  File "site-packages/calibre/customize/zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'/home/Downloads/DeDRM_tools_6.5.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by rpspringuel** [comment]
Looks like you didn't unzip the download.  The plug-in is a zip file inside a folder in the download.

**Comment by docaltmed** [comment]
Thanks!

**Comment by Slowly** [comment]
I unzipped the download, and tried to load the plug-in inside the resulting folder in the download. Got the same error:
![untitled](https://user-images.githubusercontent.com/119132/34124248-65e1478c-e3ef-11e7-9e89-2bcf58589d7f.png)

**Comment by Slowly** [comment]
Then, I unzipped the alfcrypto_src.zip file, added the __init__.py file, rezipped it, and tried to load it into Calibre. It loaded successfully. Then I tried it on a DRM'd file - didn't work.

**Comment by Slowly** [comment]
...to reiterate...i am an it pro with decades of programming and administration experience. I am fluent in python. I looked at both archives of DeDRM modified. I disabled the kpx renderer inside Kindle and redownloaded my purchased books. I added an __init__.py to the inner archive, and it installed into calibre but did not work on the AZW file i tested, and to make sure it was not a kpx i renamed it so as to try it on the kpx input plugin. The kpx input plugin assured me it was not kpx. Like i said, we have to wait until the chinese or north koreans can defeat the new drm scheme.



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by ElleKayEm** [comment]
I don't know where you got DeDRM modified.  It's probably based on some old version of these tools. 
 The DeDRM plugin here works with non-KFX Amazon books.  The new DRM scheme has been figured out, but hasn't been integrated into the tools yet.  The code for it is available here too if you want to take a look at it.

**Comment by Slowly** [comment]
Thank you! I certainly will take a look at it. 😊



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by j-howell** [comment]
> Then, I unzipped the alfcrypto_src.zip file, added the init.py file, rezipped it, and tried to load it into Calibre. It loaded successfully. Then I tried it on a DRM'd file - didn't work.

alfcrypto_src.zip is NOT the calibre plugin. There is no need to modify it. The actual plugin is in the DeDRM_calibre_plugin folder and is named DeDRM_plugin.zip.

> Thank you! I certainly will take a look at it. 😊

If you are interested, see issue #38 for more information on what has been done so far.

**Comment by BahneGork** [comment]
im getting this error today, the dedrm plugin folder does not contain a zip file, but all the plugin files unzipped.

**Comment by BahneGork** [comment]
so i zipped the files and tried to import, "no module named '__version'

**Comment by BahneGork** [comment]
no deDRM_plugin.zip in the unzipped deDRMplugin folder 
![image](https://user-images.githubusercontent.com/32675320/184684178-679be435-352e-421d-8a3b-581dfe8fe9dc.png)

**Comment by ElleKayEm** [comment]
If you're using calibre 6.x, download DeDRM_tools_10.0.3.zip from here:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Unzip that and load DeDRM_plugin.zip.

**Comment by alexetalbott** [comment]
Was getting this error and was able to fix it by using the link above and clicking on the first asset, NOT the "source code" links.

**Comment by Shellshock9001** [comment]
These instructions.... please remake them. on windows unzipping the plugin doesn't anything loadable. It keeps giving a no top.py error.

**Comment by ElleKayEm** [comment]
Unzip only DeDRM_tools_10.0.3.zip.  Leave DeDRM_plugin.zip zipped.

**Comment by Jaycris** [comment]
the DeDRM_plugin is not in zipped, it is still in folder. and when we try to zip the DeDRM_plugin folder and load it from calibre plugin it has an error calibre, version 6.16.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\Jay-ar Cristobal\\Downloads\\DeDRM_tools-master\\DeDRM_plugin.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.16  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 513, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\Jay-ar Cristobal\\Downloads\\DeDRM_tools-master\\DeDRM_plugin.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Download DeDRM_tools_10.0.3.zip here:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

When you unzip that you will see 2 zip files and 3 readme txt files.  Load DeDRM_plugin.zip.

**Comment by kyledehovitz** [comment]
@ElleKayEm thank you for the instructions. I was able to install the plugin, but I'm still unable to convert the AZW3 file. Running Calibre 6.17.0 on an Apple silicon Mac, if that helps.

**Comment by ElleKayEm** [comment]
@kyledehovitz 
From or for an E-ink Kindle?  Be sure you have the Kindle's serial number entered into DeDRM's customization correctly.  Copy and paste from the website.
