### ISSUE TITLE
[SOLVED] Calibre 5.23 & calibre-plugin-dedrm 7.2.1-1 works great but not for a azw4 file

### ISSUE THREAD

**Issue by sagittarius06** [apprenticeharper/DeDRM_tools#1807]
First: my respects and many thanks to the dev.

calibre-debug -g
calibre 5.23  embedded-python: False is64bit: True
Linux-5.13.8-1-MANJARO-x86_64-with-glibc2.33 Linux ('64bit', 'ELF')
('Linux', '5.13.8-1-MANJARO', '#1 SMP PREEMPT Thu Aug 5 09:47:52 UTC 2021')
Python 3.9.6
Interface language: fr
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 135.5328125 x 135.46666666666664
Using calibre Qt style: True
Failed to read metadata from font file: /usr/share/fonts/TTF/TSCu_Comic.ttf tuple index out of range
Failed to read metadata from font file: /usr/share/fonts/TTF/TSCu_Times.ttf tuple index out of range
[0.00] Starting up...
[0.03] Showing splash screen...
[0.13] splash screen shown
[0.13] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[1.78] main UI initialized...
[1.78] Hiding splash screen
Starting QuickView
[2.23] splash screen hidden
[2.24] Started up in 2.23 seconds with 2 books
DeDRM v7.2.1: Trying to decrypt B07HDHLMQJ_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: The ebook I bought (French Edition)
Found 8 keys to try after 2.3 seconds
Crypto Type is: 2
File is encoded with PID 4/NWSUvZR1.
Decrypting. Please wait . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . done
Decryption succeeded after 3.5 seconds
DeDRM v7.2.1: Finished after 3.6 seconds
Added The ebook I bought (French Edition) to db in: 0.3
Added 1 books in 5.3 seconds

The cover displays properly but the text on the following pages is as if it were still encrypted.
On other kindle files, it works perfectly.

Edit SOLVED with Kindle unpack plugin !

**Comment by ElleKayEm** [comment]
If you're all set, then you can close this issue.
