### ISSUE TITLE
PDF bought through Intel Study (formerly KNO)

### ISSUE THREAD

**Issue by bdavis840** [apprenticeharper/DeDRM_tools#181]
My apologies in advance if this has been addressed at another point. I've spent HOURS on this stupid book, just trying to locate it on my drive! Any direction would be unspeakably appreciated! I bought the book through Intel Education for class thinking I could at least Copy text for my guides. WRONG! LOL Absolute worst reading app I've ever used by far. Either way, I'm attaching the debug from calibre. I've only de-drm'd one book before, so if I messed up just let me know and I'll get what I can ASAP! Thanks for everything you've already done and in advance!
[DEBUG LOG 2.txt](https://github.com/apprenticeharper/DeDRM_tools/files/706506/DEBUG.LOG.2.txt)

**Comment by ElleKayEm** [comment]
If it's only possible to download with a special Intel Study app, then these tools won't help.  These tools work with PDFs with Adobe DRM.

**Comment by bdavis840** [comment]
It's a PDF. It can only be read through their ereader program, app etc. Same as kindle book readable only on their reader. Thanks!

**Comment by apprenticeharper** [comment]
If it's a PDF but can't be read using Adobe Digital Editions, then these tools can't help. You'll need to find something written for Intel's DRM scheme.  If you find something, please let me know.
