### ISSUE TITLE
kindle for PC, i can't remove DRM

### ISSUE THREAD

**Issue by promeneur** [apprenticeharper/DeDRM_tools#1810]
Linux OpenSuse Leap 15.2
Calibre: 5.25.0
Kindle: 1.17.1 (44183) installed with wine in WINEPREFIX=/home/<user>/.PlayOnLinux/wineprefix/kindle/
DeDRM: 7.2.1

till this day, no problem to remove DRM.

I made the error to delete at amazon site the device corresponding to kindle app install in  my PC.

When I launched kindle, then i had to resubscribe my app with my amazon id and pwd.

So I assume the app got a new key.

I deleted the default key in dedrm plugin (i saved it before)

Now when i import a book then i get no errors but when i try to convert it to EPUB i get an error message saying the book is protected by DRM.

If i go to derdrm plugin settings, i see there is no key.

I tried to revert to 4.23 because calibre use python 2 and not 3 but calibre site does not supply this version.

See the debug log when importing the book

[tmpiex3wnah.txt](https://github.com/apprenticeharper/DeDRM_tools/files/6987007/tmpiex3wnah.txt)

python 2.7 is installed in /home/<user>/.PlayOnLinux/kindle/drive_c/Python27/

python[w].exe, python[w]2.7.exe, python[w]2.exe are in /home/<user>/.PlayOnLinux/kindle/drive_c/Python27/

pycrypto 2.1.0 for python 2.7 is in /home/<user>/.PlayOnLinux/wineprefix/kindle/drive_c/Python27/Lib/site-packages/Crypto/

If we need to install python 3 then where to get it ? I only find 3.8 and 3.9 at https://www.activestate.com/products/python/downloads/. Is it compliant with the plugin and pycrypto 2.1.0 ?

Thanks

**Comment by ElleKayEm** [comment]
calibre 4.23 is here:
https://download.calibre-ebook.com/4.23.0/

Or you could run the kindlekey Python script from DeDRM 6.8.1.  Then import the retrieved key into DeDRM's customization.

**Comment by promeneur** [comment]
I solved the problem by installing python 3 in  kindle's wine container.

DeDrm extracted the new key.

I got python-3.9.6.exe 32 bits from https://www.python.org/downloads/windows/
