### ISSUE TITLE
EPUBs without rights.xml

### ISSUE THREAD

**Issue by Leseratte10** [apprenticeharper/DeDRM_tools#182]
I have a few epub files with Adobe DRM (Adobe Digital Edititions can read them and Calibre claims it has DRM), but ineptepub.py claims the books don't have DRM - because the file "rights.xml" is missing. In META-INF, there are just encryption.xml, container.xml and com.apple.ibooks.display-options.xml

ADE is still able to read the files. ineptepub.py is not. Is there a way for you to fix that? Do you need a sample file? If yes, I'd rather give that to someone in private as it may contain watermarks.

**Comment by Leseratte10** [comment]
Sorry, please forget this report, the download was corrupt. Redownloading the Epub from the ACSM file using the most recent version of ADE resulted in an EPUB with rights.xml which the script could decrypt.

**Comment by ElleKayEm** [comment]
Stick with ADE 2.0.1 to avoid DRM that you can't decrypt.
