### ISSUE TITLE
Cannot convert to Epub

### ISSUE THREAD

**Issue by Ceroes** [apprenticeharper/DeDRM_tools#1824]
I followed all the steps listed in the read me.
Received file from my kindle keyboard, I also added my kindle keyboard Serial number just in case and it still didn't work.

"calibre Debug log
calibre 5.26 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.26 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.28 x 80.68235294117646
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
[0.78] main UI initialized...
[0.78] Hiding splash screen
Starting QuickView
Failed to check for plugin update: DLL load failed while importing bz2: %1 is not a valid Win32 application.
DeDRM v7.2.1: Trying to decrypt Ethics Within Engineering An Int-asin_B01MCS8O8U-type_EBOK-v_0.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Storage number map:
{(7, 0): [(3, 'C')], (7, 1): [(1, 'D')], (7, 2): [(2, 'E')], (7, 3): [(1, 'G')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\B006D0B113060EAX&0: StorageDeviceNumber(type=7, number=3, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=4)
{'drive_letters': ['G'],
 'pnp_id_map': {'G': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#b006d0b113060eax&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'G': (3, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: G:\ documents
DEBUG:    0.0 USBMS: scan from root False G:\documents
DEBUG:    0.0 USBMS: count found in cache: 36, count of files in metadata: 36, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 36
DeviceJob: set_books_in_library finished: time= 0.0019953250885009766
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 1 Set library information finished
No details available.
[13.67] splash screen hidden
[13.67] Started up in 13.67 seconds with 6 books
Added Ethics Within Engineering to db in: 2.1
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 18, in <module>
  File "zipimport.py", line 259, in load_module
  File "C:\Users\Jonat\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 33, in <module>
  File "bypy-importer.py", line 203, in exec_module
  File "Crypto\Cipher\__init__.py", line 33, in <module>
  File "bypy-importer.py", line 203, in exec_module
  File "Crypto\Cipher\_mode_ccm.py", line 44, in <module>
ImportError: DLL load failed while importing strxor: %1 is not a valid Win32 application.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 527, in KindleMobiDecrypt
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.kfxdedrm", line 20, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.ion", line 33, in <module>
  File "bypy-importer.py", line 203, in exec_module
  File "Crypto\Cipher\__init__.py", line 33, in <module>
  File "bypy-importer.py", line 203, in exec_module
  File "Crypto\Cipher\_mode_ccm.py", line 44, in <module>
ImportError: DLL load failed while importing strxor: %1 is not a valid Win32 applicationAdded 1 books in 2.4 seconds"

**Comment by ElleKayEm** [comment]
Should work if you have your Kindle's serial number entered correctly.  But this log has some strange errors and seems to be missing details about what happened with the DRM removal attempt.  Can we see a log without your Kindle attached?  Move the book to your computer, eject the Kindle, then add to calibre.

**Comment by Ceroes** [comment]
I followed your instructions and it worked. It's also possible I had the sample book when I first tried it instead of the version I bought though it should have been the version I bought because I thought I checked that maybe I still transferred the incorrect one though.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
