### ISSUE TITLE
Calibre 5.3 & plugin 7.2.1 cannot de-drm acsm file

### ISSUE THREAD

**Issue by loremistress** [apprenticeharper/DeDRM_tools#1825]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
Calibre 5.3 and ADE 3.0 worked fine for stripping the DRM from acsm files until I updated to 5.25.  After updating, opening epubs in Calibre gave the 'this book is locked by DRM' error message.  Uninstalling current version and re-installing 5.3 did not fix this issue.

## Log
<details><summary>Log Title</summary>

```log
[calibre error log 2982021.txt](https://github.com/apprenticeharper/DeDRM_tools/files/7071904/calibre.error.log.2982021.txt)
```
</details>

**Comment by Leseratte10** [comment]
This log error looks like you aren't running 7.2.1 but an older (Python-2-only) version of DeDRM. Can you try removing the plugin and reinstalling the most recent version again?

**Comment by loremistress** [comment]
Thank you!  I thought I had the most recent version, but it seems not.  Reinstalling the most recent version fixed the issue.
