### ISSUE TITLE
Current status of Alf dedrm tool KFX encryption and Kindle App version for title [must update to download this title]?

### ISSUE THREAD

**Issue by stillhope** [apprenticeharper/DeDRM_tools#1827]
Hello,  Is there a 7 version of Alfs tool that handle the titles with the lastest KFX encryption, for Mac Catalina or Windows?  I am unclear as by the release notes. I did not know where to see current status of KFX and Alfs tools. Thankyou

**Release Notes 7.2.0**
It also now includes code that should handle the latest KFX encryption used by the latest Kindle for PC and Kindle for Mac.
**Release Notes 7.2.1** (says released April 2021)
I messed up some white space. I still haven’t got KFX to work for me, but I don’t think I’ve actually broken anything this time.

On 1.26, Kindle App returns. message [you must upgrade to the latest version to download this title].

Thankyou

**Comment by j-howell** [comment]
Amazon changed their KFX DRM immediately after the plugin was released so that it no longer works. You need Kindle for PC/Mac version 1.26 or earlier.

**Comment by stillhope** [comment]
thankyou.
