### ISSUE TITLE
Calibre 5.25 + DeDRM 7.2.1 KFX error

### ISSUE THREAD

**Issue by zalaare** [apprenticeharper/DeDRM_tools#1837]
[Debug Log](https://github.com/apprenticeharper/DeDRM_tools/files/7131786/tmpjf3xxn2e.txt)

Unsure of my next step.  The book in this series prior worked correctly (same Kindle for PC, same Calibre, same DeDRM).

Thank you

**Comment by ElleKayEm** [comment]
I'd try switching to 64-bit calibre and updating the KFX Input plugin.  DRM removal was successful.

**Comment by zalaare** [comment]
I just solved this (for now) by https://www.mobileread.com/forums/showthread.php?t=283371 method 2, renaming render-test.exe.

Thanks!
