### ISSUE TITLE
Calibre 4.23 + DeDRM 6.8.1 unable to decrypt azw3 file

### ISSUE THREAD

**Issue by ThinkingMachineYx** [apprenticeharper/DeDRM_tools#1849]
Here's the log output:
```
Decrypting Kindle Format 8 ebook: 西西弗神话(诺奖得主加缪代表作，李玉民教授法语直译，2018全新修订)(果麦经典)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\38208\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\38208\AppData\Local\Amazon\Kindle\storage\.kinf2018
Couldn't decrypt file.
DeDRM v6.8.0: Ultimately failed to decrypt after 5.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 5.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
```

**Comment by ThinkingMachineYx** [comment]
OS: Windows 10

**Comment by ThinkingMachineYx** [comment]
Book downloaded from website "Download & transfer via USB"

**Comment by ElleKayEm** [comment]
For that method, you need to choose an E-ink Kindle (not a Fire) for the device and enter the Kindle's serial number into DeDRM's customization.

**Comment by ThinkingMachineYx** [comment]
> For that method, you need to choose an E-ink Kindle (not a Fire) for the device and enter the Kindle's serial number into DeDRM's customization.

Yes, I've already done that

**Comment by ElleKayEm** [comment]
Try copy and paste of the serial number into DeDRM.  Also try downloading a fresh copy of the book to make sure you have chosen the right device.

**Comment by ThinkingMachineYx** [comment]
> Try copy and paste of the serial number into DeDRM. Also try downloading a fresh copy of the book to make sure you have chosen the right device.

The SN is already copied to the plugin. I've done every step you mentioned.

**Comment by ThinkingMachineYx** [comment]
> Try copy and paste of the serial number into DeDRM. Also try downloading a fresh copy of the book to make sure you have chosen the right device.

Can I send you the azw3 file to see if there's any problem?

**Comment by ElleKayEm** [comment]
I know of no other solution for this method other then what I've suggested.

**Comment by ThinkingMachineYx** [comment]
Is it because that this type of file cannot be decrypted by the current code?

**Comment by ElleKayEm** [comment]
DeDRM has been able to handle AZW3 files for many years.

**Comment by ThinkingMachineYx** [comment]
> DeDRM has been able to handle AZW3 files for many years.

Okay, thanks anyway.
