### ISSUE TITLE
Cannot remove DRM from .azw3 file on Linux, Calibre 5.28.0, DeDRM 7.21

### ISSUE THREAD

**Issue by DFF-fred** [apprenticeharper/DeDRM_tools#1851]
Just bought a book 2 days ago and wanted to share it with my wife. It still says the book belongs to me and she needs to buy a new one. Cannot convert to any other format neither.
I checked other thread and didn't feel it was similar. I don't use any extra software, just buy, download and upload to my Kindle with Calibre. 
Thank you for your help.

**Comment by ElleKayEm** [comment]
If you got the book from the website with the "download and transfer via USB" option, you need to choose an E-ink Kindle (not a Fire) and add its serial number to DeDRM's customization.

**Comment by DFF-fred** [comment]
Excellent, that was the part I was missing. Thank you very much!
