### ISSUE TITLE
Blank book after (apparently) DeDRMing, can't open with Calibre Viewer nor Convert

### ISSUE THREAD

**Issue by mayhewvaults** [apprenticeharper/DeDRM_tools#1859]
After apparently DeDRM I can open my book throught the Reader but it only shows the book cover and the rest is completly blank and don't seem to be able to return to the cover page. If I try to convert the book to other format such as epub or pdf I'm able to navigate throught the pages but they are all covered in odd characters ("&ì9’lVvÔš«¤8Öš£Ð&q§µ×“ÒÚK›»®OZ7@u"), which I believe means that the DeDRMing didn't work properly.

Here's the debug log

> calibre Debug log
calibre 5.7.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.7.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.55183946488295 x 81.64285714285714
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.41] splash screen shown
[0.41] Initializing db...
[0.42] db initialized
[0.42] Constructing main UI...
Loaded cached store plugin for: Библио.бг at version: 2
Loaded cached store plugin for: Project Gutenberg at version: 8
Loaded cached store plugin for: Kobo at version: 8
[0.95] main UI initialized...
[0.95] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B09254JD93_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: A Quem o Assassino Mata? O Serial Killer à Luz da Criminologia e da Psicanálise (eBook)
Got DSN key from database default_key
Found 6 keys to try after 0.2 seconds
Crypto Type is: 2
File is encoded with PID 5G5Gn2mFVF.
Decrypting. Please wait . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . done
Decryption succeeded after 0.6 seconds
DeDRM v7.2.1: Finished after 0.6 seconds
[4.16] splash screen hidden
[4.16] Started up in 4.16 seconds with 36 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xb9q\x9bm\xaelw.J\xa5d\xf9\x86\xdf\xa9\xe3\xd4K\x1ee\x981b\x89h\x19\xc0\xc5:\x16O{', b'E:\\Matheus\\Documents\\My Kindle Content\\B09254JD93_EBOK.azw4']
Added A Quem o Assassino Mata? O Serial Killer à Luz da Criminologia e da Psicanálise (eBook) toAdded 1 books in 1.2 seconds
Worker Launch took: 0.02 seconds

**Comment by ElleKayEm** [comment]
An azw4 is a pdf in an Amazon wrapper.  Try the Kindle Unpack plugin to extract the pdf.

**Comment by mayhewvaults** [comment]
> An azw4 is a pdf in an Amazon wrapper. Try the Kindle Unpack plugin to extract the pdf.

That worked perfectly! Thanks for the help
