### ISSUE TITLE
Calibre 2.77.0 ADE books 

### ISSUE THREAD

**Issue by moosamoo** [apprenticeharper/DeDRM_tools#186]
I have been using the plugin for a while now, but recently the plugin doesn't seem to be working. 
I use adobe digital editions (version 3.0), and usually import the books into calibre. However, recently the DRM hasn't been removed and there is an error message. I would appreciate your help!!

I think this is the log file 
calibre Debug log
calibre 2.77 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 192.0 x 192.0
physicalDpi: 267.286153846 x 267.801156069
Starting up...
Started up in 9.80 seconds with 17 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\\5~\xe3\xc1\xbcd:\xab\xdc9\x08q\xef\xd6\x0f\xae\xf2\xe4\x9bE\x9f\x1d\xbc\xec\xca\xce\x06G\xc6\xcf\xe4', 'C:\\Users\\nslew\\Documents\\My Digital Editions\\My Name is Leon.epub']
DeDRM v6.5.3: Trying to decrypt My Name is Leon.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: My Name is Leon.epub is a secure Adobe Adept ePub
DeDRM v6.5.3: Trying Encryption key default_key
Could not decrypt 9ir0nq.epub. Wrong key
DeDRM v6.5.3: Failed to decrypt with key default_key after 0.3 seconds
DeDRM v6.5.3: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v6.5.3: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 337, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 392, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Added My Name is Leon to db in: 0.4
Added 1 books in 1.8 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x00000000042FD7F0>> ignored

**Comment by moosamoo** [comment]
I have also tried uninstalling digital editions 3.0 and reinstalling version 2.0. This hasn't made a difference.

**Comment by ElleKayEm** [comment]
Can you open the book in ADE 2?

**Comment by moosamoo** [comment]
Yes, that's no problem

**Comment by ElleKayEm** [comment]
Is ADE 2.0.1 (authorized with your Adobe ID) on the same machine and user where calibre is?

**Comment by moosamoo** [comment]
Yes. Previously it was authorised without an ID, but I just created a new one and tried to import the book again. It didn't work :(

**Comment by ElleKayEm** [comment]
If you downloaded a book to ADE before it was authorized with your Adobe ID, then the book is locked to that installation of ADE.

**Comment by moosamoo** [comment]
I have just downloaded a new book to test it, and even with the adobe ID the DRM is not removed.

**Comment by pdurrant** [comment]
If you have been downloading books without an ID registered, I don't know that the tools will be able to help.

You say it's been working for some time. That surprises me.

I'm not sure what is the best thing for you to do. How many non-DRMed ebooks do you have? (If the book displays in the calibre ebook viewer, it doesn't have DRM.)

**Comment by gareth73** [comment]
I had previously had Adobe authorised without an ID and had problems switching. 

To fix the problem I found that I needed to delete the Adobe Adept reg key, HKEY_CURRENT_USER\SOFTWARE\Adobe\Adept then reinstall ADE 2.0.1 and authorize with an Adobe ID. 

Then redownload my books from the bookstore, and import into Calibre. The first book I tried actually failed again, but the logging showed that it had managed to access the key file. So I tried importing it a second time and it worked, and has done since.

**Comment by ElleKayEm** [comment]
Whew -- that was lucky!  I have heard of people not being able to download the book from the bookstore again on a new installation of ADE.  It simply tells them that the book is already licensed to someone else.  If customer service is knowledgeable and willing, they might get them to reset the book.

**Comment by apprenticeharper** [comment]
I don't know what happened, but it seems to be resolved. Issue closed.
