### ISSUE TITLE
[QUESTION] Can an EPUB with audio and video be decrypted?

### ISSUE THREAD

**Issue by Twombs** [apprenticeharper/DeDRM_tools#1861]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
Deliver Us From Evil: Shaw and Katie James 2 (Enhanced Edition) by David Baldacci

https://www.kobo.com/au/en/ebook/deliver-us-from-evil-shaw-and-katie-james-2-enhanced-edition

I can provide the 128 Mb epub file if you wish?

I can view the ebook in Adobe Digital Editions 3.0, though the audio and video don't work in it.
I cannot view the ebook in Calibre, though it adds to it without an error. A DRM error is displayed when attempting to view it or convert.

### DeDRM: `Version` v6.8.0

</details>

**Comment by Leseratte10** [comment]
A logfile from the decryption attempt might be helpful here. 
Try to restart calibre in debug mode, then try to add the EPUB, then close Calibre. A logfile should then open which you can post here.

**Comment by Twombs** [comment]
I ran calibre from a BAT file using the --gui switch, then added the epub, then closed calibre, but alas no Log file appeared.
However, I did catch the console output, which I presume is probably the same (see attached).

[Log.txt](https://github.com/apprenticeharper/DeDRM_tools/files/7270689/Log.txt)

Further to that, I did eventually have some kind of success with Epubor Ultimate yesterday, but only when I eventually used the ebook entry in the Kobo listing. Using its entry with the Adobe Digital Editions failed, even though I had upgraded to v4.5.

Being only the trial version of Epubor, I only got a 20% of the ebook as a text file.

The earlier Adobe Digital Editions method did not fail completely, as I was left with around a 35 Mb file, that contained the MP3 file but no video file, and an almost complete version of the ebook itself (two chapters were missing and some chapter heading images and one other HTML file from the bonus section ... all other content seemed to be present). I'd investigated that by turning the EPUB into a ZIP file and checking content. I then restored the EPUB extension and added to calibre, and could view the ebook, but with those errors.

**Comment by ElleKayEm** [comment]
Are the audio and video files encrypted?  If not, maybe try removing them, DeDRMing, then adding them back.  You might also try 64-bit calibre if possible.

Have you tried Kobo Desktop and Obok?

I don't believe that Epubor can do anything that DeDRM can't do.  It appears to be a different interface based on the code here.

It's recommended to stick with ADE 2.0.1 as later versions can handle a "hardened" DRM that can't be removed.  Shouldn't be an issue with Kobo now, but it could be in future or with other ebookstores.

**Comment by Twombs** [comment]
The whole ebook is encrypted.
One of the first things I did was copy the MP3 and M2V file out, to check them and they like every other file in the EPUB are encrypted. I was also not allowed (able) to delete any of the encrypted content, which was the second thing I tried.
As I said, Epubor was successful when pointed at the entry in the Kobo desktop App listing, but not with the ADE listing.
Epubor might be based on DeDRM code, but clearly it works a bit differently, and going by what I have read it is supposedly superior to using calibre with the DeDRM plugin, especially when dealing with Epub 3 ebooks that contain video and audio.
64 Bit Calibre is not really an option at this point, and I'm not really sure why it would make a difference, unless later versions of DeDRM supported by it would be more capable than the version I am using.
Anyway, my main question hasn't really be answered in regard to whether this type of ebook can be decrypted by DeDRM?
Maybe only an apprentice can tell us the answer to that.
Cheers

**Comment by ElleKayEm** [comment]
Then it seems like Obok may be the answer.  I suggested 64-bit calibre because the 32-bit version can run into memory issues when DeDRM is handling larger files.

**Comment by Twombs** [comment]
Ok, thank you for that.
Never used the Obok plugin before, and it appears to have worked.
I learnt something new. Thanks again.

**Comment by ElleKayEm** [comment]
If you are all set, you can close this issue.
