### ISSUE TITLE
No key found

### ISSUE THREAD

**Issue by Grandez** [apprenticeharper/DeDRM_tools#187]
This ebook was purchased at Amazon and sent to my kindle.
Originally was coded as AZW6, but I downloaded to USB as AZW3.

System: Windows 10 x64
Calibre version 2.67 (x64)

[tmpeuqmlk.txt](https://github.com/apprenticeharper/DeDRM_tools/files/725055/tmpeuqmlk.txt)

**Comment by ElleKayEm** [comment]
First, update to the latest version of the tools (currently 6.5.3, you have 6.0.8).  Then if your Kindle is E-ink, you need to enter its serial number into the plugin customization.  Otherwise, install Kindle for PC (version 1.17 or earlier) to the same machine and user as calibre and import that copy.

**Comment by Grandez** [comment]
Tanks a lot


Enviado desde mi dispositivo Samsung

-------- Mensaje original --------
De: ElleKayEm <notifications@github.com> 
Fecha: 24/1/17  0:30  (GMT+01:00) 
Para: apprenticeharper/DeDRM_tools <DeDRM_tools@noreply.github.com> 
Cc: Javier Gonzalez <javier.gonzalez.grandez@gmail.com>, Author <author@noreply.github.com> 
Asunto: Re: [apprenticeharper/DeDRM_tools] No key found (#187) 

First, update to the latest version of the tools (currently 6.5.3, you have 6.0.8).  Then if your Kindle is E-ink, you need to enter its serial number into the plugin customization.  Otherwise, install Kindle for PC (version 1.17 or earlier) to the same machine and user as calibre and import that copy.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apprenticeharper/DeDRM_tools","title":"apprenticeharper/DeDRM_tools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/apprenticeharper/DeDRM_tools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ElleKayEm in #187: First, update to the latest version of the tools (currently 6.5.3, you have 6.0.8).  Then if your Kindle is E-ink, you need to enter its serial number into the plugin customization.  Otherwise, install Kindle for PC (version 1.17 or earlier) to the same machine and user as calibre and import that copy."}],"action":{"name":"View Issue","url":"https://github.com/apprenticeharper/DeDRM_tools/issues/187#issuecomment-274652139"}}}
