### ISSUE TITLE
Conversion not possible - book locked by DRM

### ISSUE THREAD

**Issue by BitKobold** [apprenticeharper/DeDRM_tools#1886]
Hi there

First, many thanks for your work and your efforts to counter limiting ownership rights by attempting customer lock-in by proprietary empires! Much appreciated.

I bought the book at the amazon.de Kindle store. DL via KindleForPC. Import to Calibre works but conversion pops up the above message.

Versions:
Microsoft Windows 21H1 [Version 10.0.19043.1288]
Calibre 5.29, DeDRM 7.2.1 from Github, KFX input 1.44.0
Kindle for PC 1.33.0 (62002) Note: Tried the suggested older version 1.24.51068 first but this version can not be registered with amazon anymore. The username/password form clears itself every second or two.

Debug excerpt:
Firefox rurl: None None
URLS: ['file://NAS06/_obfuscated_/Documents/Content/My%20Kindle%20Content/B00FDRC0JE_EBOK/B00FDRC0JE_EBOK.azw']
Paths: ['//NAS06/_obfuscated_/Documents/Content/My Kindle Content/B00FDRC0JE_EBOK/B00FDRC0JE_EBOK.azw']
Extensions: frozenset({'azw'})
Decrypted key file using IDString '_obfuscated_' and UserName '_obfuscated_'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: 4abif4rz
Got DSN key from database default_key_1
Found 1 keys to try after 3.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.d8a868e2-a1c9-441e-920e-e71f312df26c.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

I am happy to provide the full debug log but would prefer to encrypt it. Is there a way to send you a key via  a separate channel? Or send it directly?

Again, thanks for any help you can provide.
BitKobold

**Comment by federicorosso1993** [comment]
@ElleKayEm Just one question (not sure where to ask so I'll ask here). Do you have any plans to support KFX drm on updated kindle apps? Right now they need to support it the disable KFX thing because if they don't older kindle will not be able to work but I think they are trying to push drm for every book and they can cut support for older kindle app in the near future.
They even forced the drm in my own ebook published with no drm (I decided to publish it without drm but right now it got it).
It would be great to know that you are still working on a fix for this problem.

**Comment by BitKobold** [comment]
> 
> 
> The KFX format cannot be decrypted from any version later then 1.26 of the Kindle app. Disable KFX downloads to get the older format which can be decrypted. See method 2 at this post: https://www.mobileread.com/forums/showthread.php?t=283371

Thanks for your swift response. The recommended method worked as designed for Kindle for PC 1.33.0 (62002). Thanks to everybody who contributed!
