### ISSUE TITLE
Unable to remove DRM from KFX

### ISSUE THREAD

**Issue by ronchon65** [apprenticeharper/DeDRM_tools#1894]
My environment:
Linux Debian 11
Calibre:
5.29.0
DeDRM:
7.2.1
ebook files:
bought on Amazon and downloaded on my Kindle
[tmp8s_e7216.txt](https://github.com/apprenticeharper/DeDRM_tools/files/7402960/tmp8s_e7216.txt)

**Comment by ronchon65** [comment]
It doesn't work either...
I am currently doing new attemps under a "true" Windows 10.
Is ithe process supposed to work with kindle 1.33 ?

**Comment by ElleKayEm** [comment]
Yes, as long as you disable KFX downloads.

**Comment by ronchon65** [comment]
OK. It works under Kindle 1.29 and Window 10.
There is something wrong with my wine installation under Debian. I shall try to find out what later.
Thanks for your help !
