### ISSUE TITLE
Cannot Convert From Kindle for PC AZW

### ISSUE THREAD

**Issue by Guacanagarix** [apprenticeharper/DeDRM_tools#191]
This book failed to convert in Calibre. Please let me know what to do.

Processor Intel i7
Windows 10
12GB Ram

The log file:

calibre Debug log
calibre 2.74 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 144.0 x 144.0
physicalDpi: 94.1467181467 x 94.0740740741
Starting up...
Started up in 127.99 seconds with 524 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['Y\x82=\x19\x17>\xf6\xc5\xcf,\x93v\xec?\xfe\x80\x1bZ\xd73\xe8\x18.Ii\xf5Im\x8d\xb7\xb5\xb9', 'D:\\Google Drive\\Kindle for PC Content\\B004GNF4VM_EBOK\\B004GNF4VM_EBOK.azw']
DeDRM v6.5.3: Trying to decrypt B004GNF4VM_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\MSI\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\MSI\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2320274476' and UserName '4d5349'
DeDRM v6.5.3: Found 1 new key
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 419, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 283, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 276, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 304, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B004GNF4VM EBOK to db in: 1.6
Added 1 books in 2.4 seconds

**Comment by ElleKayEm** [comment]
From the log: "Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet."

See the FAQs for the answer:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by Guacanagarix** [comment]
Thanks for your reply!
Do you think you will ever develop a workaround for the KFX format?

**Comment by ElleKayEm** [comment]
I believe those with the know-how and the necessary tools are starting to look into this.  However, the older KF8 format will probably still be a better choice for backup and conversion.

**Comment by Guacanagarix** [comment]
Perfect. Thanks very much for sharing your knowldege.

Regards!
