### ISSUE TITLE
DeDRM hanging forever with 100% CPU load when opening ePub

### ISSUE THREAD

**Issue by Elmue** [apprenticeharper/DeDRM_tools#1913]
Hello

I have Calibre 5.31.1 and DeDRM plugin 7.2.1.
I have an ePub file generated by Adobe Digital Editions 2.0.1 (or 4.5.11 does the same) after loading an *.acsm file
This XML file contains a link to an eBub file at http://cdp.pageplace.de/rcdp/files/adrm/......
I can read the book in Adobe Digital Editions correctly on the PC.
But I want to  copy it to my Kindle.
I copied the ePub that ADE has slightly modified from C:\Users\Me\Documents\My Digital Editions\ into Calibre

When I load the ePub into Calibre  with DeDRM installed it shows me correctly the cover of the book.
But when I double click the book I get "Preparing book for first time reading. Please wait" and after a few seconds it hangs forever.
A process calibre-parallel.exe occupies 2 of 4 CPU cores with 100%.
The circle stops after a few seconds and Windows says that Calibre does not respond.

After deinstalling the DeDRM plugin, restarting Calibre and removing and adding the ePub file again I do not see the cover of the book anymore. And after double clicking the book I get "The book  is locked by DRM" and Calibre does not hang.

**Comment by ElleKayEm** [comment]
Is this 64-bit calibre?

**Comment by Elmue** [comment]
calibre.exe and calibre-parallel.exe are both 32 bit

**Comment by Elmue** [comment]
I found a very interesting thing.
Navigating through my folder I found 
C:\Users\Me\Calibre-Bibliothek\Author\Book.epub
the converted book.
If I try to open it in Calibre eBook viewer it hangs.
But I can open it perfectly in Sumatra PDF / ePub Reader
So the book has been converted correctly but the Calibre Book Viewer has a big fat ugly bug.

So  you can close this bugreport.
Where can I report this bug ?

**Comment by ElleKayEm** [comment]
I'd recommend switching to 64-bit calibre.  You can close this issue.  Looks like you can report calibre bugs over here:  https://calibre-ebook.com/bugs.

**Comment by Elmue** [comment]
Its not a DeDrm bug. Its a Calibre eBook Viewer bug.

**Comment by Elmue** [comment]
The Download page https://calibre-ebook.com/download_windows does not offer a 64 bit version. There is only one MSI file

**Comment by ElleKayEm** [comment]
It's here:  https://calibre-ebook.com/download_windows64

**Comment by Elmue** [comment]
I modified the 32 bit URL:
https://calibre-ebook.com/dist/win64
The 64 bit version also can NOT open the book.
It also hangs

I also tried other ePub books which I bought without DRM.
Calibre even hangs with them.

Calibre 5.31.1 has a HUGE UGLY bug !!!
