### ISSUE TITLE
Android Keys For Kindle Not Working

### ISSUE THREAD

**Issue by UPSA007** [apprenticeharper/DeDRM_tools#1916]
I tried to extract keys from my android device using the method mentioned in the help of the plugin. After selecting the backup.ab file no file name is displayed as it was supposed to. Please Help.
Using an android 10 device with Kindle app version 8.48.0.100(1.3.251405.0)

**Comment by ElleKayEm** [comment]
That method does not work any more.  Amazon now prevents a proper backup file from being created.
