### ISSUE TITLE
Failed to remove drm

### ISSUE THREAD

**Issue by sockyou** [apprenticeharper/DeDRM_tools#193]
I downloaded a awz file directly from amazon and it keeps failing to remove the drm.

debug log:
calibre Debug log
calibre 2.76 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Count Pages (1, 6, 9)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.5518394649 x 81.6428571429
Starting up...
Started up in 5.01 seconds with 603 books
DeDRM v6.5.3: Trying to decrypt The Lost and the Found.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Lost and the Found
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Alex\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
Added The Lost and the Found to db in: 0.2
Added 1 books in 1.1 seconds

Any help is much appreciated, thanks.

**Comment by ElleKayEm** [comment]
If that is for an E-ink Kindle, then you haven't got the correct serial number entered into the plugin customization.  Otherwise, install Kindle for PC 1.17 and import that copy.  Be sure to uncheck auto updates.  See the FAQs for info:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by sockyou** [comment]
ElleKayEm, thanks so much for your reply, it made me remember that I've got two kindles registered with amazon but i only had one of their serial numbers entered into calibre. Whoops, problem solved.
