### ISSUE TITLE
[request] kobo / windows

### ISSUE THREAD

**Issue by jschvartz** [apprenticeharper/DeDRM_tools#1930]
Thanks a lot for this DeDrm !
Works like a charm for my KOBO books.
Just one thing:
the new kobo app does load the kepub files under
%LocalAppData%\Kobo\Kobo\Desktop Edition\kepub\
and files have NO extension ...
Is there a way to include this change ?

Many thanks again.
Take care
J.

**Comment by ElleKayEm** [comment]
What's the change?

**Comment by jschvartz** [comment]
Hum ...
I had the feeling that you only checked under "Documents\My Digital Editions".
A second check show i am wrong !
So, my mistake ...
Sorry about that.
Have a nice day !
J.

**Comment by ElleKayEm** [comment]
Those books are decrypted by DeDRM, not Obok.  And they're not imported via the plugin.
