### ISSUE TITLE
Unable to retrieve Adobe key

### ISSUE THREAD

**Issue by ramlet** [apprenticeharper/DeDRM_tools#1945]
I stupidly installed and authorized ADE while calibre was already installed and now I'm not sure how to retrieve my key. I tried uninstalling calibre and deleting all the config files, sadly to no avail. 

Next I tried using the manual method via the python script, but that turned out to be impossible. The script specifies that one should use Python 2, but it simply won't run using it. I'm unable to install PyCrypto and it keeps mentioning something about there being "no module named winreg" and trying to install it via pip also didn't work.

Afterwards I tried using the script with Python 3 instead, but that didn't work out either. The entire script seems to be written for Python2 and seeing as I have no knowledge of either version, I failed at rewriting the syntax.

I'm using ADE 2.0.1 and calibre 4.23 with DeDRM 6.8.1

**Comment by ElleKayEm** [comment]
Did you mean to close this issue?

> I stupidly installed and authorized ADE while calibre was already installed and now I'm not sure how to retrieve my key.

That shouldn't be a problem.  As long as calibre with DeDRM is on the same machine and user as ADE (and ADE is authorized with your Adobe ID), the key should be retrieved when you import an Adobe DRM book.

**Comment by ramlet** [comment]
Sorry for the late response. Yes, I meant to close it. Reinstalling ADE and re-authorizing fixed it.
