### ISSUE TITLE
Unable to download the book file from any version before KPC 1.25

### ISSUE THREAD

**Issue by samuele-bortolato** [apprenticeharper/DeDRM_tools#1948]
In KPC from 1.19 to 1.24 it's apparentrly impossible to login as the loging page seems bugged:
it keeps refreshing every fraction of a second making it impossible to insert the email and password.

In KPC 1.17 I was able to login, but it doesn't let you download the books anymore 

![msg126685486-94763](https://user-images.githubusercontent.com/81489249/143902606-e72399ed-3af2-402e-a833-f69c2564bfc9.jpg)

I tried using the updated version of KPC (I knew I was supposed to use one before 1.25, I just tried) and of course the format was different (azw instead of azw3) and the plugin didn't manage to decript the file.

Any ideas of how to solve?

**Comment by j-howell** [comment]
Others have reported the login problem. It doesn’t seem to happen for everyone.

I am curious whether the problem with 1.17 applies to all books or just some of them. I ask because some Kindle books are only available in KFX format and won’t download using older versions of the app. Perhaps others will post whether that version is still working for them. 

At this point your best option is to install a recent version of the app and disable KFX on it.

**Comment by samuele-bortolato** [comment]
I checked with another book and you were right, it opened it without any problem.
The book I need has been published in 2020, so it's probably as you said.

I'm pretty new and I have no idea how to disable KFX though, I don't see it in the app options

**Comment by ElleKayEm** [comment]
See posts linked under method 2 at this post:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by samuele-bortolato** [comment]
Thanks for the fast replies. 


Disabling KFC before downloading throws:

"This title format is nor compatible with your device. Pleas try another device or dontac Kindle customer support."


Disabling it after the download it throws the error:

"The book could not be opened.
Please remove the book from the device and redownload it."

**Comment by ElleKayEm** [comment]
You definitely want to disable KFX before downloading.  But it sounds like a book that is only available in KFX format.

**Comment by samuele-bortolato** [comment]
Ok, I understand I'm out of luck, I'll just wait and hope someone will manage to deal also with that format one day.
Thanks for the support
