### ISSUE TITLE
Cannot decrypt a number of AZW books

### ISSUE THREAD

**Issue by phillipmcmahon** [apprenticeharper/DeDRM_tools#195]
Attempting to remove the DRM from my personal Kindle library some books work fine and others appear to error.

Here is an example from one AZW attempt that fails.

There is 1 ebook to be decrypted.
Processing file: B003V4ASK4_EBOK.azw
There was an error with 1 ebook:
Macintosh HD:Users:phillipmcmahon:Library:Application Support:Kindle:My Kindle Content:B003V4ASK4_EBOK:B003V4ASK4_EBOK.azw is neither a Kindle not a Mobipocket file.

Any help would be appreciated.

**Comment by ElleKayEm** [comment]
I guess you figured out the problem was this:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by phillipmcmahon** [comment]
Yes I did. Sorry for not checking the debug logs before posting an error. My bad. I simply downgraded my Kindle app to a 2016 older version and all was good.

Thanks for the response.

**Comment by ElleKayEm** [comment]
Don't forget to uncheck auto updates.
