### ISSUE TITLE
Unable to remove DRM from kindle ebook .azw3

### ISSUE THREAD

**Issue by Kartik-Tatiparti** [apprenticeharper/DeDRM_tools#1956]
I bought this book on Amazon and downloaded it to a laptop using the "Download and transfer via USB" option.
-------------------------------------------------------------------------
calibre Debug log
calibre 5.33.2  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.33.2  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 78.9126213592233 x 79.28323699421965
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.94] splash screen shown
[0.94] Initializing db...
[0.95] db initialized
[0.95] Constructing main UI...
[1.88] main UI initialized...
[1.88] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt The Art of Statistics (Pelican Books).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Art of Statistics (Pelican Books)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Kartik Tatiparti\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Kartik Tatiparti\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4199750883' and UserName 'Kartik Tatiparti'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Art of Statistics (Pelican Books)
Got DSN key from database default_key_1
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[5.59] splash screen hidden
[5.61] Started up in 5.61 seconds with 1 books
Storage number map:
{(7, 0): [(3, 'C')], (7, 1): [(1, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0310\6&1815FED6&2: StorageDeviceNumber(type=7, number=1, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x310 devid=usb\vid_1949&pid_0004&rev_0310 devinst=5)
{'drive_letters': ['D'],
 'pnp_id_map': {'D': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0310#6&1815fed6&2#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'D': (1, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ documents
DEBUG:    0.1 USBMS: scan from root False D:\documents
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
DEBUG:    0.8 USBMS: count found in cache: 109, count of files in metadata: 109, need_sync: False
DEBUG:    0.8 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.8 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.8 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 109
DeviceJob: set_books_in_library finished: time= 0.02097177505493164
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'"\\\xff\xf8\xe7#\xd7{\x11\x1fmb\xa0\xad\r\xe2\xbdZ\xdd2\xcd!\xde\x142n\x05R\x88\xb5z%', b'C:\\Users\\Kartik Tatiparti\\Downloads\\The Art of Statistics (Pelican Books).azw3']
Added The Art of Statistics (Pelican Books) to db in: 0.2
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/Added 1 books in 1.1 seconds

**Comment by ElleKayEm** [comment]
Did you choose an E-ink Kindle (not a Fire) for the device?  Then you need to enter the Kindle's serial number into DeDRM's customization.

**Comment by gofilipa** [comment]
This worked for me, as did installing a version 6 of DeDRM with version 4 of Calibre for Mac.

**Comment by Kartik-Tatiparti** [comment]
Thanks a lot! Worked for me as well.
