### ISSUE TITLE
Failed to convert

### ISSUE THREAD

**Issue by sayan31650** [apprenticeharper/DeDRM_tools#196]
Windows 10
Kindle for PC: 1.17.0
Calibre: 2.78 (64 bits)
DRM Plug in 6.4.3 (I also tried with same result with 6.5.3)

Since few days; I cannot any longer remove DRM frdownloaded from Amazon.... 

Thanks for any advice

alibre Journal de débogage
calibre 2.78 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 4, 3) && KoboBooks (1, 0, 0) && Obok DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.6235294118 x 94.5931034483
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Ignoring blacklisted device: The \\?\usb#vid_0fce&pid_01b5#2584c6e9#{6ac27878-a6fa-4155-ba85-f98f491d4f33} device has been blacklisted by the user
Started up in 9.41 seconds with 16500 books
DeDRM v6.4.3: Trying to decrypt B01MTFF3QM_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: De fille coincÃ©e Ã  Escort-Girl : ou lâ€™initiation sexuelle dâ€™une jeune femme mariÃ©e: Version longue et non censurÃ©e (French Edition)
Found 14 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.4.3: Failed to decrypt with error: No key found in 14 keys tried.
DeDRM v6.4.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\arnaud\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\arnaud\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '539876175' and UserName '42e96ee96469637465'
DeDRM v6.4.3: Found 1 new key
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: De fille coincÃ©e Ã  Escort-Girl : ou lâ€™initiation sexuelle dâ€™une jeune femme mariÃ©e: Version longue et non censurÃ©e (French Edition)
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.4.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 604, in run
  File "calibre_plugins.dedrm.__init__", line 554, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.3: Ultimately failed to decrypt after 0.3 seconds
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added De fille coincée à Escort-Girl : ou l’initiation sexuelle d’une jeune femme mariée: Version longue et non censurée (French Edition) to db in: 1.6
Added 1 books in 3.0 seconds

**Comment by ElleKayEm** [comment]
Hard to tell since you posted the log from the old version of the plugin, but I'd guess you've run into the KFX format.  See the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

Uncheck auto updates from the tools > options menu.

**Comment by sayan31650** [comment]
New log with deDRM 6.5.3
Kindle for PC 1.17.1 (44183), Uncheck auto updates from the tools unchecked

Hope you can recommand a solutoion, thanks

calibre Journal de débogage
calibre 2.78 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Obok DeDRM (6, 5, 3) && KoboBooks (1, 0, 0)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.6235294118 x 94.5931034483
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
Ignoring blacklisted device: The \\?\usb#vid_0fce&pid_01b5#2584c6e9#{6ac27878-a6fa-4155-ba85-f98f491d4f33} device has been blacklisted by the user
Started up in 29.07 seconds with 16505 books
DeDRM v6.5.3: Trying to decrypt B01N5VSU4H_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: Le Casting: Je suis le jouet de ces deux hommes... : (Histoire Ã‰rotique, Plan Ã  Trois, Tabou, Exhib, PremiÃ¨re Fois) (French Edition)
Found 14 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 14 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\arnaud\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\arnaud\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '539876175' and UserName '42e96ee96469637465'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: Le Casting: Je suis le jouet de ces deux hommes... : (Histoire Ã‰rotique, Plan Ã  Trois, Tabou, Exhib, PremiÃ¨re Fois) (French Edition)
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Le Casting: Je suis le jouet de ces deux hommes... : (Histoire Érotique, Plan à Trois, Tabou, Exhib, Première Fois) (French Edition) to db in: 1.8
Added 1 books in 2.7 seconds
Worker Launch took: 0.230000019073

**Comment by ElleKayEm** [comment]
Ah, just realized you mentioned using 1.17 in the first post too.  So the problem isn't the new format.  I've just seen so much of that that I jumped to conclusions.

First, was this book from the same machine and user where calibre is?  If so, then do you have any accented letters or other non-ASCII characters in your Windows user name?  If so, try adding a new user with only ASCII characters and then set up Kindle for PC, calibre, and the plugin under that account.

If that's not it, then follow the instructions for uninstalling and reinstalling here:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

Be sure to install 1.17 (current 1.19 version will cause problems the new KFX format).  Link here if you need the installer: https://s3.amazonaws.com/kindleforpc/44183/KindleForPC-installer-1.17.44183.exe

**Comment by sayan31650** [comment]
Yes, same user ' arnaud', and both calibre & Kindle directories are in the same place:

\\BENE\Users\arnaud\Documents\bibliotheque calibre
\\BENE\Users\arnaud\Documents\My Kindle Content

It seems to me that there are no 'non ASCII'

The calibre exe is executed in "C:\Program Files\Calibre2\calibre.exe"

Kindle for PC 1.17.1 (44183), Uncheck auto updates from the tools unchecked
deDRM 6.5.3

I have installed several time Kindle for PC following the complete instructions.... Things were working nicely up to one week ago and then Kindle 4 PC was automacillay upgraded and now I have the problem :=/

**Comment by ElleKayEm** [comment]
You're sure you're using version 1.17, not 1.19?  And you downloaded new copies of your books?  I don't know what else could be the problem.

**Comment by sayan31650** [comment]
Yes it is.... I have uninstalled / reinstalled the Kindle for PC, no change, same error....

Thank for your support

**Comment by ElleKayEm** [comment]
I'm honestly stumped why it's not working for you.  If you followed the instructions for unregistering and deleting all folders, the plugin should pick up the new key for the new copies of your books.

**Comment by sayan31650** [comment]
Yeah, I did all the step of the procedure and still I have these errors

File "calibre_plugins.dedrm.init", line 610, in run
File "calibre_plugins.dedrm.init", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds

I will wait a while ssing if any news arrives

Thanks for everything

**Comment by pdurrant** [comment]
While your Windows username in the path seems to be 'arnaud', the plugin seems to be reading it as '42e96ee96469637465' (in hex) or 'Bénédicte'.

Clearly something in the username is messed up. I suggest creating a new user account (without any accented characters anywhere in the name) and install Kindle for PC and calibre under that and see if that works. Which I think it will

**Comment by sayan31650** [comment]
Yes 

It works perfect 

Thanks so much 

----- Mail original -----

De: "Paul Durrant" <notifications@github.com> 
À: "apprenticeharper/DeDRM_tools" <DeDRM_tools@noreply.github.com> 
Cc: "sayan31650" <arnaud.darbin@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 7 Février 2017 07:39:30 
Objet: Re: [apprenticeharper/DeDRM_tools] Failed to convert (#196) 



While your Windows username in the path seems to be 'arnaud', the plugin seems to be reading it as '42e96ee96469637465' (in hex) or 'Bénédicte'. 

Clearly something in the username is messed up. I suggest creating a new user account (without any accented characters anywhere in the name) and install Kindle for PC and calibre under that and see if that works. Which I think it will
