### ISSUE TITLE
Some kind of regression in Obok

### ISSUE THREAD

**Issue by build6** [apprenticeharper/DeDRM_tools#1960]
Want to report that when using the latest Calibre (5.32) and these DeDRM tools (7.2.1) I ended up with failed decryption output ( .epub is generated but it's gibberish).  When I used an older Calibre (4.23) and Obok (6.7) it works fine.

**Comment by ElleKayEm** [comment]
I believe this is fixed in noDRM's Obok 10.0.2.  Available here:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2

(Maintainance of these tools has moved over there.)

**Comment by build6** [comment]
>

**Comment by build6** [comment]
> 

Hi, thank you, that worked.  I guess this is one of the (rare?) Google failures where it turns up 7.2.1 as the first hit when there's a newer version elsewhere!
