### ISSUE TITLE
Can't remove DRM 

### ISSUE THREAD

**Issue by dido-b** [apprenticeharper/DeDRM_tools#1965]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
DeDRM worked in previous versions. Now, it give the message:

Thanks for having a look, David
[temp.txt](https://github.com/apprenticeharper/DeDRM_tools/files/7735001/temp.txt)

</details>

**Comment by dido-b** [comment]
[temp.txt](https://github.com/apprenticeharper/DeDRM_tools/files/7735028/temp.txt)

**Comment by ElleKayEm** [comment]
You have Adobe Digital Editions authorized with your Adobe ID and on the same machine and user as calibre with DeDRM?  And this is what was used to download this copy of the book?

Either way, give DeDRM 10.0.2 a try:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2

**Comment by dido-b** [comment]
Sorry, did not work either.

I had removed Adobe Digital Editions from my computer before. The book I uploaded to Calibre resides on the Tolino reader.

Regards,
David


Von: ElleKayEm ***@***.***>
Gesendet: Freitag, 17. Dezember 2021 13:43
An: apprenticeharper/DeDRM_tools ***@***.***>
Cc: dido-b ***@***.***>; State change ***@***.***>
Betreff: Re: [apprenticeharper/DeDRM_tools] Can't remove DRM (Issue #1965)


You have Adobe Digital Editions authorized with your Adobe ID and on the same machine and user as calibre with DeDRM? And this is what was used to download this copy of the book?

Either way, give DeDRM 10.0.2 a try: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FnoDRM%2FDeDRM_tools%2Freleases%2Ftag%2Fv10.0.2&data=04%7C01%7C%7Ceb712f65a4e04611ef5208d9c15ab2c7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753417574075619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=beSyfyo%2Fz41U1yzbGWNmSJv89hfrsGrQFHat%2FKEM6ec%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapprenticeharper%2FDeDRM_tools%2Fissues%2F1965%23issuecomment-996693427&data=04%7C01%7C%7Ceb712f65a4e04611ef5208d9c15ab2c7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753417574075619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VeVEfPkY0JiLKZRxkmWAjzzYyqNMOPnP2C70cpWldRM%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ7N5HRDHLKV2ED76TQX3BLURMV3RANCNFSM5KIW3VFQ&data=04%7C01%7C%7Ceb712f65a4e04611ef5208d9c15ab2c7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753417574075619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WVp3CXGeaMU1wS0VzYSjAFpTqOk5Yzx2%2BrRMYYst54k%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ceb712f65a4e04611ef5208d9c15ab2c7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753417574075619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YtQEcUr27JL2%2Bi7q485hstrb0n5Aj5i4YXFTPQAa%2B%2Bg%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ceb712f65a4e04611ef5208d9c15ab2c7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753417574075619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5s5b83lZgE6YglxHe3mBU%2FhTmo9zIA1E2ZRiVZn5%2BWg%3D&reserved=0>.

**Comment by ElleKayEm** [comment]
That's why it's not working then.  No way to retrieve the key.  You could try the ACSM Input plugin:  https://github.com/Leseratte10/acsm-calibre-plugin

**Comment by dido-b** [comment]
Thanks for the quick reply.

I have seen that I cannot authorize on ADE, it give the error E_ADEPT_REQUEST_EXPIRED  and a long http. Anyway, the ACSM plugin does not work either ..

Regards,
David

Von: ElleKayEm ***@***.***>
Gesendet: Freitag, 17. Dezember 2021 14:08
An: apprenticeharper/DeDRM_tools ***@***.***>
Cc: dido-b ***@***.***>; State change ***@***.***>
Betreff: Re: [apprenticeharper/DeDRM_tools] Can't remove DRM (Issue #1965)


That's why it's not working then. No way to retrieve the key. You could try the ACSM Input plugin: https://github.com/Leseratte10/acsm-calibre-plugin<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLeseratte10%2Facsm-calibre-plugin&data=04%7C01%7C%7C64d6b02b3b3440d5444f08d9c15e3782%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753432679114774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CN6uFiQ97NmTKZu3dwEdWbhuyG4Vm8MpgjhDI1HfeQQ%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapprenticeharper%2FDeDRM_tools%2Fissues%2F1965%23issuecomment-996708711&data=04%7C01%7C%7C64d6b02b3b3440d5444f08d9c15e3782%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753432679114774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fqmjlgLFaTPDxRKyZdDGwSrZBZOzecAhRu%2FxoFm7BlY%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ7N5HTK3AN3EXN67UAITYTURMY2BANCNFSM5KIW3VFQ&data=04%7C01%7C%7C64d6b02b3b3440d5444f08d9c15e3782%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753432679114774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WBOg2LKtfbMi%2FoSRor%2BW1A7l4TUzGQHtgVPGA1F55LQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C64d6b02b3b3440d5444f08d9c15e3782%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753432679114774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=83a%2FwBgCOOX7LxCYW9OBr8e7B65hzxmTee%2BwdcYjJ7A%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C64d6b02b3b3440d5444f08d9c15e3782%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753432679114774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=j6AT6oULu553qnJEOBSBRPNgzRe3IOvBWtLO2ypkYas%3D&reserved=0>.

**Comment by ElleKayEm** [comment]
Check the date, time, time zone of your computer.  Adobe says that's what can resolve that error.  See here:  https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html

**Comment by dido-b** [comment]
Thanks, will try, but have to do it later in the evening ...

Von: ElleKayEm ***@***.***>
Gesendet: Freitag, 17. Dezember 2021 14:53
An: apprenticeharper/DeDRM_tools ***@***.***>
Cc: dido-b ***@***.***>; State change ***@***.***>
Betreff: Re: [apprenticeharper/DeDRM_tools] Can't remove DRM (Issue #1965)


Check the date, time, time zone of your computer. Adobe says that's what can resolve that error. See here: https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelpx.adobe.com%2Fdigital-editions%2Fkb%2Factivation-errors-adobe-digital-editions.html&data=04%7C01%7C%7Cab719b22236f4880559b08d9c16487fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753459804094896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5yXkNgkg0hCDieo3h0dODRgEkXI%2F0CB1m5ETG5zsIsQ%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapprenticeharper%2FDeDRM_tools%2Fissues%2F1965%23issuecomment-996738980&data=04%7C01%7C%7Cab719b22236f4880559b08d9c16487fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753459804094896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jyfiR1RAKFQhUb48EU9pa7qCgyf3CEmPGYpH%2BHfxFyM%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ7N5HSKOXAO63QJ2QVTISDURM6DTANCNFSM5KIW3VFQ&data=04%7C01%7C%7Cab719b22236f4880559b08d9c16487fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753459804094896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=n4Sht06nycQ9tOBt0dU9FuipKvbyxuhYh74h%2FPcU5wo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cab719b22236f4880559b08d9c16487fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753459804094896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0UbZMFrPaRkF59QwldgyCC9Vijcok45E832E6kgubKA%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cab719b22236f4880559b08d9c16487fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753459804094896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=V46iXGBhRMJyqL47obqAmcd0WBjyKzwAyVt30o%2Bz984%3D&reserved=0>.

**Comment by dido-b** [comment]
Thank you very much for the help! By enabling "set time zone automatically" in Windows (or similar, I have a German Windows) the authorization in ADE was enabled, now everything is ok.

Best regards,
David


Von: ElleKayEm ***@***.***>
Gesendet: Freitag, 17. Dezember 2021 14:53
An: apprenticeharper/DeDRM_tools ***@***.***>
Cc: dido-b ***@***.***>; State change ***@***.***>
Betreff: Re: [apprenticeharper/DeDRM_tools] Can't remove DRM (Issue #1965)


Check the date, time, time zone of your computer. Adobe says that's what can resolve that error. See here: https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelpx.adobe.com%2Fdigital-editions%2Fkb%2Factivation-errors-adobe-digital-editions.html&data=04%7C01%7C%7Cab719b22236f4880559b08d9c16487fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753459804094896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5yXkNgkg0hCDieo3h0dODRgEkXI%2F0CB1m5ETG5zsIsQ%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapprenticeharper%2FDeDRM_tools%2Fissues%2F1965%23issuecomment-996738980&data=04%7C01%7C%7Cab719b22236f4880559b08d9c16487fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753459804094896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jyfiR1RAKFQhUb48EU9pa7qCgyf3CEmPGYpH%2BHfxFyM%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ7N5HSKOXAO63QJ2QVTISDURM6DTANCNFSM5KIW3VFQ&data=04%7C01%7C%7Cab719b22236f4880559b08d9c16487fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753459804094896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=n4Sht06nycQ9tOBt0dU9FuipKvbyxuhYh74h%2FPcU5wo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cab719b22236f4880559b08d9c16487fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753459804094896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0UbZMFrPaRkF59QwldgyCC9Vijcok45E832E6kgubKA%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cab719b22236f4880559b08d9c16487fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637753459804094896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=V46iXGBhRMJyqL47obqAmcd0WBjyKzwAyVt30o%2Bz984%3D&reserved=0>.

**Comment by ElleKayEm** [comment]
Thanks for reporting back!  If you're all set, you can close the issue.
