### ISSUE TITLE
[QUESTION] Can't convert ACSM epub file

### ISSUE THREAD

**Issue by RadGav** [apprenticeharper/DeDRM_tools#1983]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title

Hi - I purchased and downloaded a book from Google Play. I've tried using an older version of Calibre with an older DeDRM version, plus the latest version of each. I followed the instructions in DeDRM_plugin_ReadMe.txt and here's my log.
Using a Windows 10 laptop - Lenovo Z50.
Thanks,
RadGav

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.34 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.34 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.36] splash screen shown
[1.36] Initializing db...
[1.38] db initialized
[1.38] Constructing main UI...
[2.47] main UI initialized...
[2.47] Hiding splash screen
Starting QuickView
[5.70] splash screen hidden
[5.70] Started up in 5.70 seconds with 19 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xd9R\x98\xef\x86\x97\xe1\xae\x95"1\x9d\xfb\xb4kjn\xe7\x01\xe896\xd0\xb9\xde\r\xe5\x9c\x8aqQ\x11', b'C:\\Users\\Gavin\\Downloads\\How_to_Speak_Dolphin-epub.acsm']
Added How to Speak Dolphin-epub to db in: 4.2
Added 1 books in 4.8 seconds

```
</details>

**Comment by ElleKayEm** [comment]
You not adding the actual book file here.  You'll need to open the acsm file with Adobe Digital Edtions authorized with an Adobe ID to download the epub.  Or look at the [ACSM input plugin](https://www.mobileread.com/forums/showthread.php?t=341975&highlight=acsm+input) .

**Comment by RadGav** [comment]
Ahhhhhhhhhhhhhh - thank you very much! Feel a bit dopey now, but there y'go. Works fine now!
Cheers...
