### ISSUE TITLE
Can't DeDRM B&N ePubs

### ISSUE THREAD

**Issue by Townk** [apprenticeharper/DeDRM_tools#2]
I generate the key with my name and credit card, download the ePub on my Nook App on my Mac and even through the website using the JS helper on Firefox.

Every time I try to remove the DRM I get the following:

imported_9780446567688-ePub.v1.epub is not a secure Adobe Adept ePub.

Where 9780446567688-ePub.v1.epub is the name of my eBook.

Is there any known problem with B&N DRMs?

**Comment by apprenticeharper** [comment]
Read the B&N help in the 6.2.0 plugin.

**Comment by apprenticeharper** [comment]
Closed. Not a bug.

**Comment by Townk** [comment]
The help mention that you have to download NOOK Study from https://yuzu.com/nsdownload but unfortunately the link is not available anymore. So let me try to rephrase my problem:

"How do I generate B&N keys without access to NOOK Study app?"

**Comment by ElleKayEm** [comment]
The FAQs page at Apprentice Alf's Blog has been updated with this info:

https://apprenticealf.wordpress.com/2011/01/17/frequently-asked-questions-about-the-drm-removal-tools/

**Comment by apprenticeharper** [comment]
The FAQs at Alf’s blog now answer this question.


Harper.






Sent from Windows Mail





From: Thiago Alves
Sent: ‎Wednesday‎, ‎25‎ ‎March‎ ‎2015 ‎18‎:‎13
To: apprenticeharper/DeDRM_tools
Cc: apprenticeharper





The help mention that you have to download NOOK Study from https://yuzu.com/nsdownload but unfortunately the link is not available anymore. So let me try to rephrase my problem:

"How do I generate B&N keys without access to NOOK Study app?"

**Comment by apprenticeharper** [comment]
Thanks, ElleKayEm.

**Comment by Townk** [comment]
That fixed my problem! Thanks for the help!
