### ISSUE TITLE
epub DRM removal for Overdrive books does not work

### ISSUE THREAD

**Issue by GuardianMajor** [apprenticeharper/DeDRM_tools#20]
I have installed the latest version of Calibre (2.31) and also installed the latest version of plugin (6.2.1) and yet it doesn't remove the DRM. The log says that it thinks its a DRM Free file. It is not.

Any idea what's going on here? The file is .epub and it comes from Overdrive, according to the XML internals, its using AES128 and Adobe Adept. I am including the XML file for it. Anything else I can provide to help figure out why its not working?

http://www.mediafire.com/download/zbfts1heig7di45/EPUB_File.zip
(contains the actual epub file as well as a folder containing the deconstructed internals)

**Comment by ElleKayEm** [comment]
Overdrive?  The tools are not supposed to work on library books.  On the other hand, the import log shouldn't say it's DRM free either.  Can you post the import log?

**Comment by GuardianMajor** [comment]
@ElleKayEm certainly, give me until I get home from the office and I will post it.

**Comment by GuardianMajor** [comment]
Ok as promised, here is the debug file for this operation:
http://www.mediafire.com/view/033mo3rv66nq0fb/debug.txt

There are some errors I notice right away which seem to be irrelevant to this issue but just the same, here are the highlights:

```
Started up in 136.50 seconds with 0 books
DeDRM v6.2.1: Trying to decrypt The Girl with the Dragon Tattoo-Part01.epub
DeDRM v6.2.1: Verifying zip archive integrity
DeDRM v6.2.1: “The Girl with the Dragon Tattoo-Part01.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 588, in run
  File "calibre_plugins.dedrm.__init__", line 370, in ePubDecrypt
DeDRMError: DeDRM v6.2.1: Couldn't decrypt after 0.2 seconds. DRM free perhaps?
```

**Comment by ElleKayEm** [comment]
The tools work with Adobe Digital Editions epubs.  Take a look at the ReadMe files for more info.  And the tools won't work on library books.

**Comment by GuardianMajor** [comment]
Actually, encryption is encryption and if its using the Adobe Adept and this tool is supposed to decrypt it then it shouldn't matter what source it is. I went ahead and used a different tool and it stripped it pretty well. I was just hoping that this tool integrated with Calibre would do it to save me a step, choosing to do something about it or not is the developers call and no loss to me, but don't make arbitrary excuses about it. Thank you.

Anyway, I will leave the information available if anyone actually want to do look into getting it working properly and if not, then so be it too.

**Comment by apprenticeharper** [comment]
I won't help with library books.
