### ISSUE TITLE
Can't convert ebook from ebook proquest central/ebrary

### ISSUE THREAD

**Issue by kokowang8910** [apprenticeharper/DeDRM_tools#2001]
[tmpsgphcf6e.txt](https://github.com/apprenticeharper/DeDRM_tools/files/7930685/tmpsgphcf6e.txt)

I downloaded ebook from Proquest Central/Ebrary
format downloaded was *acsm then I used Adobe Digital edition 4.5.11 before adding it to calibre.
Previously I used calibre 4xx and DeDRM 6.8, and until last year, it still works.
But then, this new year, I can't convert it to pdf. 
I update to calibre 5xx and DeDRM 7.2.1 but the result still the same.
Please help me

**Comment by kokowang8910** [comment]
I am using windows 10 64bit

**Comment by ElleKayEm** [comment]
ProQuest has switched to the hardened Adobe DRM which cannot be decypted yet.

**Comment by kokowang8910** [comment]
yeah..unfortunately
very sad when I switched to ADE 2.01 all the contents from Proquest can be opened through ADE

**Comment by vikaspsy** [comment]
Having the same issues. Please help.

**Comment by ElleKayEm** [comment]
Development at this repo has ended.

**Comment by kokowang8910** [comment]
so sad. It means that we cannot decrypt the DRM from Proquest again?
TT

**Comment by ElleKayEm** [comment]
Not currently.  At least it isn't an ebookstore.

**Comment by tvphanatic** [comment]
Take a look at [https://github.com/noDRM/DeDRM_tools/pull/48](url) for an update that can decrypt the newer ProQuest files (I tested on two ebooks and it worked).

**Comment by kokowang8910** [comment]
thank you for informing me. but the link doesn't work. it says 'page not found'. would you mind to resend it again?

**Comment by ElleKayEm** [comment]
Copy the link text and paste that into the address bar.  Clicking it takes you to this repo instead of noDRM's.

**Comment by vikaspsy** [comment]
It worked 
Thank you very much

**Comment by kokowang8910** [comment]
> Take a look at [https://github.com/noDRM/DeDRM_tools/pull/48](url) for an update that can decrypt the newer ProQuest files (I tested on two ebooks and it worked).

thank you so much for commenting this to inform me. It works! awesome!

**Comment by thepetition** [comment]
I am looking for someone to do a gig for me to get some data from proquest. I looked on the fiverr site, but i dont find anyone with access.  

I would like some searches and results for the UK parliamentary papers.

The public petitions  1833 - 1918 

Im thinking if anyone can get me that entire database 😅 how big would it be? How many GB ?? 😳

Some basic searches would be good, if not.. would really help three keywords all the results if thats more do able.
kokowang8910? , vikaspsy ? ElleKayEm?
tvphanatic? 🙄 Anyone

Well if you have access could you set a fiver gig up...   "Proquest searches" and i will look for it. 😊
