### ISSUE TITLE
I've tried to upload DeDRM v7.2.1 — Full Release onto Calibre v5.35.0 plugins but Calbre does not take it, see following message "DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file"

### ISSUE THREAD

**Issue by JoBiwo** [apprenticeharper/DeDRM_tools#2003]
### Discussed in https://github.com/apprenticeharper/DeDRM_tools/discussions/1656

<div type='discussions-op-text'>

<sup>Originally posted by **apprenticeharper** April 11, 2021</sup>
I messed up some white space. I still haven't got KFX to work for me, but I don't think I've actually broken anything this time. :)

<hr /><em>This discussion was created from the release <a href='https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v7.2.1'>v7.2.1 — Full Release</a>.</em></div>

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_7.2.1.zip and load DeDRM_plugin.zip.

**Comment by JoBiwo** [comment]
It works! Thank you...:)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
