### ISSUE TITLE
Running adobekey.py results in error

### ISSUE THREAD

**Issue by gomarcus** [apprenticeharper/DeDRM_tools#2007]
## Title
Running "python3 adobekey.py" results in an error and no ".der" file is created. **Would be very happy about quick assistance!**

## Description
I would like to extract the key and create a .der file. But all my attempts so far have failed. The execution of "python3 adobekey.py" results in error listed below. The alternative call with a target (-h) directory does not result in an error, but also does not produce the desired result.

A selection of attempted combinations:

- From script source directory
 `python3 adobekey.py -h ./output`

- From the target directory ( structure: scriptdir[adobekey.py]/output )
 `python3 adobekey.py -h .`
 `python3 adobekey.py -h ./`
 `python3 adobekey.py -h ./output`
 `touch ./out.txt && python3 adobekey.py -h out.txt`

## My Environment
Ubuntu 20.04 in Windows WSL
sudo apt install python3 python3-pip python3-tk
pip install pycryptodome

### DeDRM: `Version`
DeDRM_tools_7.2.1

### ADE
ADE Version 4.5.11.187303

## Log
<details><summary>Error when running "python3 adobekey.py"</summary>

```log
Traceback (most recent call last):
  File "adobekey.py", line 587, in <module>
    sys.exit(gui_main())
  File "adobekey.py", line 554, in gui_main
    root = tkinter.Tk()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```
</details>

<details><summary>Output: "python3 adobekey.py -h ./output"</summary>

```log
adobekey.py v7.0
Copyright © 2009-2020 i♥cabbages, Apprentice Harper et al.
Finds, decrypts and saves the default Adobe Adept encryption key(s).
Keys are saved to the current directory, or a specified output directory.
If a file name is passed instead of a directory, only the first key is saved, in that file.
Usage:
    adobekey.py [-h] [<outpath>]
```
</details>

**Comment by ElleKayEm** [comment]
A workaround would be temporarily installing Windows calibre with the DeDRM plugin where you have ADE (authorized with your Adobe ID) installed.  Save the key from there.  The plugin will use calibre's embedded python.

Development here has ended.  You might try noDRM's DeDRM 10.0.2:  https://github.com/noDRM/DeDRM_tools

Safer to use ADE 2.0.1 or you may end up with DRM that can't be removed.

**Comment by gomarcus** [comment]
Thanks so much for the quick response, I am very new to this. So thanks for the hints. I did manage to get the .der file in the meantime through calibre. I wish it would work with calibre and I wouldn't have to take this detour. But Calibre does not remove the lock at book (pdf) import nor when trying to convert it.

I did not know that I have to get the book through ADE 2 or 3 to be on the save side. Is there still hope to get it work anyway?

**Comment by ElleKayEm** [comment]
It depends on whether or not the ebookstore is actually using the hardened Adobe DRM or not.  Anything beyond ADE 2.0.1 can handle both old and new Adobe DRM.  If you can read the book in ADE 2.0.1 authorized with your Adobe ID, then you're good.  Let's take a look at a log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by gomarcus** [comment]
Thanks you so much! Now I read most of your linked material. Have now made it work.

**For interested subsequent sufferers:**
When installing, uninstalling, and re-setting Calibre and plugins again and again, you may get strange errors in some cases.
1. Just make another clean installation of Calibre
2. Install the latest version of the successor tool mentioned by @ElleKayEm
3. Done.

**Comment by ElleKayEm** [comment]
Great!  Thanks for reporting back on what worked.
