### ISSUE TITLE
Can DeDRM strip e-books downloaded straight from the ACSM file's CDN url?

### ISSUE THREAD

**Issue by Geremia** [apprenticeharper/DeDRM_tools#201]
When opening ACSM files in Android Digital Editions (ADE), I keep running into error \#2038 (cf. [this](https://www.mobileread.com/forums/showthread.php?p=3471345#28)). The error dialog box that ADE gives provides a URL to the EPUB of the following form:
```
13a0790921b0eed053bf-13a0790921b0eed053bfaf9e6b555ccd.ssl.cf2.rackcdn.com
```
<sup>i.e., "(20 hex digits)-(32 hex digits).ssl.cf2.rackcdn.com"</sup>

I am able to use that URL in my browser to download the EPUB and open it in ADE, but DeDRM is not able to strip the EPUB's DRM. Presumably, ADE re-encrypts the EPUBs with it downloads directly, using one's Adobe key.

I had no problems with DeDRM before my ADE started getting these \#2038 errors.

**Comment by ElleKayEm** [comment]
From what I understand, the epub downloaded through the url method has part of the DRM (rights.xml) stored separately from the epub file.  If you could find where that is stored, you might be able to add it back into the epub and DeDRM it.  B&N does something similar with books downloaded through the Windows 8 Nook app.  In that case, the missing piece is stored in a SQLite database in a hidden folder.

Probably far easier to start using ADE 2.0.1.  I assume you ran into this error using ADE 1.7.x.

**Comment by apprenticeharper** [comment]
No response. Issue closed.

**Comment by Geremia** [comment]
@ElleKayEm 
> ADE 2.0.1. I assume you ran into this error using ADE 1.7.x.
Yes, because I couldn't get ADE 1.7.x working in WINE.

**Comment by ElleKayEm** [comment]
Yes.  See the thread linked in the OP.
