### ISSUE TITLE
Cannot De-DRM a purchased textbook from Amazon

### ISSUE THREAD

**Issue by PollyWoIIy** [apprenticeharper/DeDRM_tools#2010]
Hi,
a complete newbie here.

I cannot remove DRM from MOBI book downloaded from Amazon. Calibre says that it ways only 65MB, which is too small of a number for a textbook. When trying to open the book, I get the cover picture and then Calibre just loads forever. 

Kindle: 1.26.0
Calibre 5.35
DeDRM 7.2.1
Windows 11

Thank you for any help!
Polina

Debug log:

calibre Debug log
calibre 5.35  embedded-python: True is64bit: False
Windows-10-10.0.22000 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 5.35  embedded-python: True is64bit: False
Windows-10-10.0.22000 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Loaded cached store plugin for: ebook.de at version: 8
[0.94] main UI initialized...
[0.94] Hiding splash screen
Starting QuickView
[16.81] splash screen hidden
[16.81] Started up in 16.81 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xd0\x8cAZ\x8bOS\x86\x98,E\xf2=\x92K\xff\x8f\xdaE5\xa7\xcb\xc2\x10\xd5\xd8\x90\x1b\xb6\x88\xc6\x14', b'C:\\Users\\Polly\\OneDrive - Troy University\\Documents\\My Kindle Content\\B091V9BVG1_EBOK\\B091V9BVG1_EBOK.azw', b'C:\\Users\\Polly\\OneDrive - Troy University\\Documents\\My Kindle Content\\B091V9BVG1_EBOK\\B091V9BVG1_EBOK.mbp']
DeDRM v7.2.1: Trying to decrypt B091V9BVG1_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Essential Biochemistry, 5th Edition
Got DSN key from database default_key
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
File is encoded with PID 6NwAQOS4PX.
Decrypting. Please wait . . . . . . . . . . . . . . . . . . . . . . . . . . Added B091V9BVG1 EBOK to db in: 0.1
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . done
Decryption succeeded after 3.6 seconds
DeDRM v7.2.1: Finished after Convert book 1 of 1 (Essential Biochemistry, 5th Edition)

DeDRM v7.2.1: Trying to decrypt 56wy5zrd.mobi
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Essential Biochemistry, 5th Edition
Got DSN key from database default_key
Found 4 keys to try after 0.2 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.2 seconds
DeDRM v7.2.1: Finished after 0.4 seconds
Conversion options changed from defaults:

  output_profile: 'generic_eink'

  read_metadata_from_opf: 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_hpxx6dim\\la_e575t.opf'

  pdf_sans_family: 'MS Shell Dlg 2'

  cover: 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_hpxx6dim\\xzvg_4gz.jpeg'

  verbose: 2

  pdf_serif_family: 'MS Shell Dlg 2'

Resolved conversion options

calibre version: 5.35.0

{'asciiize': False,

 'author_sort': None,

 'authors': None,

 'base_font_size': 0.0,

 'book_producer': None,

 'change_justification': 'original',

 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

            "'i')) or @class = 'chapter']",

 'chapter_mark': 'pagebreak',

 'comments': None,

 'cover': 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_hpxx6dim\\xzvg_4gz.jpeg',

 'custom_size': None,

 'debug_pipeline': None,

 'dehyphenate': True,

 'delete_blank_paragraphs': True,

 'disable_font_rescaling': False,

 'duplicate_links_in_toc': False,

 'embed_all_fonts': False,

 'embed_font_family': None,

 'enable_heuristics': False,

 'expand_css': False,

 'extra_css': None,

 'filter_css': '',

 'fix_indents': True,

 'font_size_mapping': None,

 'format_scene_breaks': True,

 'html_unwrap_factor': 0.4,

 'input_encoding': None,

 'input_profile': <calibre.customize.profiles.InputProfile object at 0x07F0E220>,

 'insert_blank_line': False,

 'insert_blank_line_size': 0.5,

 'insert_metadata': False,

 'isbn': None,

 'italicize_common_cases': True,

 'keep_ligatures': False,

 'language': None,

 'level1_toc': None,

 'level2_toc': None,

 'level3_toc': None,

 'line_height': 0.0,

 'linearize_tables': False,

 'margin_bottom': 5.0,

 'margin_left': 5.0,

 'margin_right': 5.0,

 'margin_top': 5.0,

 'markup_chapter_headings': True,

 'max_toc_links': 50,

 'minimum_line_height': 120.0,

 'no_chapters_in_toc': False,

 'no_inline_navbars': False,

 'output_profile': <calibre.customize.profiles.GenericEink object at 0x07F0E3A0>,

 'page_breaks_before': "//*[name()='h1' or name()='h2']",

 'paper_size': 'letter',

 'pdf_add_toc': False,

 'pdf_default_font_size': 20,

 'pdf_footer_template': None,

 'pdf_header_template': None,

 'pdf_hyphenate': False,

 'pdf_mark_links': False,

 'pdf_mono_family': 'Courier',

 'pdf_mono_font_size': 16,

 'pdf_odd_even_offset': 0.0,

 'pdf_page_margin_bottom': 72.0,

 'pdf_page_margin_left': 72.0,

 'pdf_page_margin_right': 72.0,

 'pdf_page_margin_top': 72.0,

 'pdf_page_number_map': None,

 'pdf_page_numbers': False,

 'pdf_sans_family': 'MS Shell Dlg 2',

 'pdf_serif_family': 'MS Shell Dlg 2',

 'pdf_standard_font': 'serif',

 'pdf_use_document_margins': False,

 'prefer_metadata_cover': False,

 'preserve_cover_aspect_ratio': False,

 'pretty_print': False,

 'pubdate': None,

 'publisher': None,

 'rating': None,

 'read_metadata_from_opf': 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_hpxx6dim\\la_e575t.opf',

 'remove_fake_margins': True,

 'remove_first_image': False,

 'remove_paragraph_spacing': False,

 'remove_paragraph_spacing_indent_size': 1.5,

 'renumber_headings': True,

 'replace_scene_breaks': '',

 'search_replace': '[]',

 'series': None,

 'series_index': None,

 'smarten_punctuation': False,

 'sr1_replace': None,

 'sr1_search': None,

 'sr2_replace': None,

 'sr2_search': None,

 'sr3_replace': None,

 'sr3_search': None,

 'start_reading_at': None,

 'subset_embedded_fonts': False,

 'tags': None,

 'timestamp': None,

 'title': None,

 'title_sort': None,

 'toc_filter': None,

 'toc_threshold': 6,

 'toc_title': None,

 'transform_css_rules': '[]',

 'transform_html_rules': '[]',

 'uncompressed_pdf': False,

 'unit': 'inch',

 'unsmarten_punctuation': False,

 'unwrap_lines': True,

 'use_auto_toc': False,

 'use_profile_size': False,

 'verbose': 2}

DeDRM v7.2.1: Trying to decrypt otzacad4.mobi
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Essential Biochemistry, 5th Edition
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.1 seconds
DeDRM v7.2.1: Finished after 0.3 seconds
InputFormatPlugin: MOBI Input running

on C:\Users\Polly\AppData\Local\Temp\calibre_hpxx6dim\o55b182m.mobi

Extracting text...

Adding anchors...

Extracting images...

Cleaning up HTML...

Parsing HTML...

Malformed markup, parsing using html5-parser

Converting style information to CSS...

Creating OPF...

Parsing all content...

Parsing styles.css ...

Parsing index.html ...

Added Essential Biochemistry, 5th Edition to db in: 0.2
Added 2 books in 4.3 seconds
Worker Launch took: 0.05 seconds
Job: 0 Convert book 1 of 1 (Essential Biochemistry, 5th Edition) finished
Convert book 1 of 1 (Essential Biochemistry, 5th Edition)

	DeDRM v7.2.1: Trying to decrypt 56wy5zrd.mobi
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 4 ebook: Essential Biochemistry, 5th Edition
	Got DSN key from database default_key
	Found 4 keys to try after 0.2 seconds
	Crypto Type is: 0
	This book is not encrypted.
	Decryption succeeded after 0.2 seconds
	DeDRM v7.2.1: Finished after 0.4 seconds
	Conversion options changed from defaults:

	  output_profile: 'generic_eink'

	  read_metadata_from_opf: 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_hpxx6dim\\la_e575t.opf'

	  pdf_sans_family: 'MS Shell Dlg 2'

	  cover: 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_hpxx6dim\\xzvg_4gz.jpeg'

	  verbose: 2

	  pdf_serif_family: 'MS Shell Dlg 2'

	Resolved conversion options

	calibre version: 5.35.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_hpxx6dim\\xzvg_4gz.jpeg',

	 'custom_size': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x07F0E220>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x07F0E3A0>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'paper_size': 'letter',

	 'pdf_add_toc': False,

	 'pdf_default_font_size': 20,

	 'pdf_footer_template': None,

	 'pdf_header_template': None,

	 'pdf_hyphenate': False,

	 'pdf_mark_links': False,

	 'pdf_mono_family': 'Courier',

	 'pdf_mono_font_size': 16,

	 'pdf_odd_even_offset': 0.0,

	 'pdf_page_margin_bottom': 72.0,

	 'pdf_page_margin_left': 72.0,

	 'pdf_page_margin_right': 72.0,

	 'pdf_page_margin_top': 72.0,

	 'pdf_page_number_map': None,

	 'pdf_page_numbers': False,

	 'pdf_sans_family': 'MS Shell Dlg 2',

	 'pdf_serif_family': 'MS Shell Dlg 2',

	 'pdf_standard_font': 'serif',

	 'pdf_use_document_margins': False,

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_hpxx6dim\\la_e575t.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'uncompressed_pdf': False,

	 'unit': 'inch',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'use_profile_size': False,

	 'verbose': 2}

	DeDRM v7.2.1: Trying to decrypt otzacad4.mobi
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 4 ebook: Essential Biochemistry, 5th Edition
	Got DSN key from database default_key
	Found 4 keys to try after 0.1 seconds
	Crypto Type is: 0
	This book is not encrypted.
	Decryption succeeded after 0.1 seconds
	DeDRM v7.2.1: Finished after 0.3 seconds
	InputFormatPlugin: MOBI Input running

	on C:\Users\Polly\AppData\Local\Temp\calibre_hpxx6dim\o55b182m.mobi

	Extracting text...

	Adding anchors...

	Extracting images...

	Cleaning up HTML...

	Parsing HTML...

	Malformed markup, parsing using html5-parser

	Converting style information to CSS...

	Creating OPF...

	Parsing all content...

	Parsing styles.css ...

	Parsing index.html ...

**Comment by ElleKayEm** [comment]
DRM is successfully removed.

**Comment by j-howell** [comment]
Your book is a PDF in a MOBI wrapper. Use the [KindleUnpack](https://www.mobileread.com/forums/showthread.php?t=171529) plugin to extract the embedded PDF.

**Comment by PollyWoIIy** [comment]
I have added KindleUnpack plugin and still cannot open the book:(

Here's the converion log:



calibre, version 5.35.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (Essential Biochemistry, 5th Edition)

Convert book 1 of 1 (Essential Biochemistry, 5th Edition)
DeDRM v7.2.1: Trying to decrypt 8s6t64zd.mobi
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Essential Biochemistry, 5th Edition
Got DSN key from database default_key
Found 4 keys to try after 0.2 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.2 seconds
DeDRM v7.2.1: Finished after 0.3 seconds
Conversion options changed from defaults:
  read_metadata_from_opf: 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_z26k2_sh\\4_xwcl1y.opf'
  verbose: 2
  cover: 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_z26k2_sh\\n0sue_lt.jpeg'
  pdf_serif_family: 'MS Shell Dlg 2'
  pdf_sans_family: 'MS Shell Dlg 2'
  output_profile: 'generic_eink'
Resolved conversion options
calibre version: 5.35.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_z26k2_sh\\n0sue_lt.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x07D72F28>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x07D680D0>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'MS Shell Dlg 2',
 'pdf_serif_family': 'MS Shell Dlg 2',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\Polly\\AppData\\Local\\Temp\\calibre_z26k2_sh\\4_xwcl1y.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
DeDRM v7.2.1: Trying to decrypt dzqw11x0.mobi
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Essential Biochemistry, 5th Edition
Got DSN key from database default_key
Found 4 keys to try after 0.2 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.2 seconds
DeDRM v7.2.1: Finished after 0.3 seconds
InputFormatPlugin: MOBI Input running
on C:\Users\Polly\AppData\Local\Temp\calibre_z26k2_sh\tuxknc91.mobi
Extracting text...
Adding anchors...
Extracting images...
Cleaning up HTML...
Parsing HTML...
Malformed markup, parsing using html5-parser
Converting style information to CSS...
Creating OPF...
Parsing all content...
Parsing styles.css ...
Parsing index.html ...

**Comment by j-howell** [comment]
You need to actually use that plugin. Select the imported book then use the menu from KindleUnpack icon to extract the PDF.

**Comment by PollyWoIIy** [comment]
It worked!
Thank you so much for your help. I'm very grateful.

A pdf of the book appeared in "My Kindle Content" folder for some reason. But now I found it!

I hope you guys have a wonderful evening!
