### ISSUE TITLE
Book does not decrypt (Iran: Empire of The Mind, on Kobo)

### ISSUE THREAD

**Issue by stevedundee2** [apprenticeharper/DeDRM_tools#2028]
"Iran: Empire of the Mind" does not decrypt, or at least when I open it after using ebok 7.2.1 it is just unreadable symbols. Also no cover has appeared - just a blue block with the book title and author.

Other books have decrypted at the same time with no problems. All these books were bought from Kobo. I tried restarting Calibre and opening it again, but no help. 

My laptop is running Kubuntu 21.10.
Calibre 5.38
obok 7.2.1 (just upgraded to make sure not the issue)

[tmp2g_eabqn.txt](https://github.com/apprenticeharper/DeDRM_tools/files/8191153/tmp2g_eabqn.txt)

**Comment by ElleKayEm** [comment]
Try noDRM's Obok:  https://github.com/noDRM/DeDRM_tools

**Comment by stevedundee2** [comment]
Hello

Yes that works, thanks! 

Steve

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
