### ISSUE TITLE
DRM not removed on AZW3 using v6.5.3

### ISSUE THREAD

**Issue by louise742** [apprenticeharper/DeDRM_tools#203]
I have installed the latest DeDRM 6.5.3 using the latest version of Calibre 2.78 but the DRM is still not removed.

Here is the log file:
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\nev>calibre-debug -g
calibre 2.78  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && KePub Output (2
, 7, 1) && KindleUnpack - The Plugin (0, 81, 3) && Kobo Utilities (2, 5, 2) && K
oboTouchExtended (2, 8, 2) && KePub Metadata Writer (2, 7, 1)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9292035398 x 72.0567375887
Starting up...
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    1.9 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    1.9 rebuild_menus - self.supports_ratings=None, self.supports_tiles=No
ne
DEBUG:    1.9 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    1.9 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilit
ies to use with Kobo ereaders

Driver: KoboTouchExtended'
Started up in 3.11 seconds with 568 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['Z\xe72\xc5\xb9N\x07\x14\x1d\xa0+\xd6\x94\x
f3oA\xf0S\x04"\xe4f*e\xb0>\xe0\x15\x15\x86\xbf\xa1', 'C:\\_Louise\\eBooks\\MOBI\
\To Import\\Death By The Half Dozen (Tarricone Murder Mystery Book 1).azw3']
DeDRM v6.5.3: Trying to decrypt Death By The Half Dozen (Tarricone Murder Myster
y Book 1).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: Death By The Half Dozen (Tarricone Murder Myst
ery Book 1)
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\nev\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\nev\AppData\Local\Amazon\Kindle\storage\
.kinf2011
Decrypted key file using IDString '1748464764' and UserName '6e6576'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: Death By The Half Dozen (Tarricone Murder Myst
ery Book 1)
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_
tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugi
ns
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds
Added Death By The Half Dozen (Tarricone Murder Mystery Book 1) to db in: 0.3
Added 1 books in 2.9 seconds

**Comment by ElleKayEm** [comment]
If that book is from or for an E-ink Kindle, then you need to enter your serial number into the plugin customization.  Otherwise, download with Kindle for PC (_version 1.17_) and import that copy.  Make sure that you uncheck auto updates in K4PC.

**Comment by apprenticeharper** [comment]
No response. Issue closed.
