### ISSUE TITLE
Notes on DeDRM-ing files from other PC (or Mac might as well)

### ISSUE THREAD

**Issue by runapp** [apprenticeharper/DeDRM_tools#2030]
I'm trying to run DeDRM with files from Kindle PC installed on a VM. After repeating failure and searching, I finally realized that the `k4i` file is actually from `.kinf201?`, rather than `<ISBN>_EBOK.mbpv2`. To grab (and decrypt) critical information from that file, a call to `CryptUnprotectData` is performed, during which the current logging user's credential is used, which means if using `CryptUnprotectData` in Win32API, the code has to be run on the SAME computer with the SAME user with whom installed Kindle PC. Also, the username is stored in `k4i` file, but that can be bypassed by editing the `k4i` file so not a real problem.

It's reasonable that I don't want to install a full set of calibre on my VM. So in case anyone is trapped in the same situation, here's a standalone `kindlekey` to generate `k4i` file. It's compiled with `nuitka` and can (hopefully) run on any Windows. To compile it I suggest removing `alfcrypto.py` first for better compatibility, or compile `kindlekey.py` alone in a seperate folder.

[kindlekey.dist.7z.zip](https://github.com/apprenticeharper/DeDRM_tools/files/8192126/kindlekey.dist.7z.zip)

My suggestion is to add file sanity check on importing `k4i` files. `.mbpv2` files and `k4i` files are all json files, so for now importing a `.mbpv2` file in the "Kindle for Mac/PC ebooks" dialog would succeed without any warnings, which might be extremely confusing for users.

In fact I'm not very satisfied with the solution, and even not sure if it's worth "fixing" it. And even better to post it on reddit or wordpress? So please feel free to close the issue.

**Comment by ElleKayEm** [comment]
Why not just run this:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_plugin/kindlekey.py

Feel free to close the issue yourself.  This repo is no longer maintained.  Work continues here:  https://github.com/noDRM/DeDRM_tools

**Comment by runapp** [comment]
> Why not just run this: https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_plugin/kindlekey.py

 It's exactly what I did in the end, compiling a portable version of kindlekey.py and run it on the target machine.

Thank you for leading me to the new repo. I didn't notice that "noDRM" is a user name lol. I'll check the new version there.

**Comment by noDRM** [comment]
Easiest would probably have been to install Calibre in that VM, dump the keys, then uninstall Calibre again if it's no longer needed. Or just use the Calibre Portable version instead. 

Your suggestion of performing some kind of validation for the K4PC key files does sound like a good idea, I'm going to try to implement that in my fork.
