### ISSUE TITLE
DRM not removed - Voyage and old version of Kindle use KFX

### ISSUE THREAD

**Issue by hstriepe** [apprenticeharper/DeDRM_tools#205]
I reverted to an older version of kindle. 1.17.1 crashed on macOS Sierra even after removing the container and prefs files. 1.12.4 worked, but could not DRM due to KFX format of new downloads.
Voyage also used that format.
Trying and older Kindle, but first have to recharge.

**Comment by ElleKayEm** [comment]
The first version of Kindle for PC/Mac to support the new KFX format is 1.19.  The newest E-ink Kindle that doesn't support KFX is the 1st generation Paperwhite.

**Comment by ElleKayEm** [comment]
You could also download from the website for your Voyage to get the older decryptable formats.

**Comment by hstriepe** [comment]
Odd that 1.12.1 does not work.

**Comment by ElleKayEm** [comment]
I believe that version 1.15 may be the oldest version that works.  Eventually Amazon requires you to update to download your books.

**Comment by hstriepe** [comment]
I am using 1.12.4 one another system with calibr and import works.
I reverted my main system to calibr and cleared all container files and Prefs and started over.
I deleted the custom plugins. then I installed the latest plugin.
But calibr ends up with a DRM protected file. Is there a way to reset the configuration?

**Comment by apprenticeharper** [comment]
I suspect that your installations are being auto-updated to 1.19. Turn off auto-updates. No version before 1.19 can download or read KFX format.

**Comment by apprenticeharper** [comment]
Since you have a Voyage, you can used  'download for transfer via USB' from the Amazon web site. That still downloads AZW/AZW3 files.

**Comment by hstriepe** [comment]
Voyage imports were also seen as KFX. Kindle 4 worked.
The trouble with 1.19 was it crashes on launch.
Where does Kindle keep its secret? Where does deDRM store its decryption preference?
I would like to reset the system or copy it from another config that works. But I am not sure the Containers/com.amazon.kindle and Preferences/calbr are all inclusive.

**Comment by hstriepe** [comment]
Using Time Machine I rolled back my Container/com.amazon.com and calibr preferences to Jan 15, when it worked. On starting Kindle 1.12.4 I got the new authentication dialog from Amazon.
Still get the DRM message after import.

**Comment by hstriepe** [comment]
I can bring up 1.17.1 on another OS X account, but not my current account. The previous update of Kindle sets something that gets in the way causing it to crash. Does anybody know, what it does?

**Comment by hstriepe** [comment]
After several more attempt I was able to launch 1.17.1 and have it log in. I was able to download an older book, which worked fine for import. My latest book was downloaded into a folder and that failed to import altogether.
I launched 1.12.4, which is an App Store version that moved everything to a container. But import of even the newest book worked well. I locked the app and hid it in the App Store, so all should be well until that is disabled for some reason.

**Comment by ElleKayEm** [comment]
If you download **from the website** for your Voyage, you can get the older file type and DeDRM them.

If a book was downloaded into a folder, then Kindle for Mac updated to 1.19.  Version 1.17 doesn't support KFX files.

I have never heard of anyone being able to DeDRM files downloaded with the Mac store Kindle app.

**Comment by apprenticeharper** [comment]
Nothing earlier than 1.19 will download KFX. Either the application is being auto-updated, or you're mistaken in what you're seeing.

If 1.17 is crashing in your user account but not in another, the first step is to try deleting all Amazon folders in ~/Library. There's probably one in Preferences and in Application Support.

However, if what you currently have is working, I'd suggest sticking with it until it stops working.

**Comment by dreki** [comment]
When is KFX support in DeDRM_tools planned?

**Comment by ElleKayEm** [comment]
Currently there is no support for KFX outside of Kindle devices/apps.  Even DRM-free KFX files can't be converted or read on anything else.  Until the format itself is figured out, figuring out the DRM isn't of much use.  Even when it eventually is, the older formats will still probably be better for conversion/backup.  Unless Amazon shuts down workarounds for getting the older formats, there's not a lot of motivation for putting in the effort necessary.

**Comment by j-howell** [comment]
Chicken and egg...

The only KFX books available without DRM are those created by Kindle Previewer 3 in conjunction with a calibre plugin. Developing an ability to convert those books to another format would be a good head start to an effort to convert KFX books from Amazon, but would otherwise be pointless. I doubt that any serious effort will be made in developing a KFX converter unless KFX DRM removal first becomes possible.

**Comment by ElleKayEm** [comment]
Yes, I've seen people report that the only thing you can really do with "DRM-free" KFX files downloaded to an E-ink device is view them on another E-ink device (provided they both support KFX).

So what is the difference between a KFX file which has DRM in other formats and one which doesn't?  Is it just that the DRM-voucher file ties it to a specific device in the first case, but not in the other?  Are they otherwise encrypted in the same way?  Or is it impossible to tell without unlocking the DRM?

**Comment by j-howell** [comment]
The presence of DRM in KFX books delivered by Amazon is what concerns me, not how it functions. It is a barrier to fully understanding the workings of the KFX format.

Based on what I do know about KFX from my investigations using Kindle Previewer 3, I agree with the earlier statement that even without DRM the KFX format is inferior as a source for conversion to other e-book formats as compared with KF8. It is designed for fast rendering and some information from the original e-book source is discarded in the process of creating it.

It is likely that Amazon will eventually discontinue the delivery of books to Kindle for PC versions that do not support KFX. This will take away one method by which KFX can be avoided, but two methods still remain for owners of e-ink Kindle devices. Registered ownership of one of these devices enables the downloading of books in non-KFX format directly from Amazon's website, at least for now.

Even better, there are certain e-ink Kindles, such as the original PaperWhite and the Kindle 3 Keyboard that support KF8, but not KFX. Books can still be copied directly from the storage of these devices and they are likely to continue to be supported by Amazon for years to come. I recommend picking up a cheap, used one.

**Comment by ElleKayEm** [comment]
I'm just curious if there are essentially 2 layers of protection that will have to be worked out for truly DRMed books or only one.

I've actually already picked up a cheap, refurbished Kindle Touch to ensure continued access to the older files.  For those thinking of doing so as well, you should look for 3rd through 5th generation E-ink Kindles:  Kindle Keyboard through 1st generation Paperwhite.  These all support KF8 (AZW3), but not KFX.

(1st and 2nd generations and the Kindle DX don't support KF8 which is the best Kindle format for conversion/archiving.  There was also recently a brief scare where people were unable to register those oldest devices.  It seems like Amazon might have been testing the waters of dropping support for them, but got enough push-back to change their minds.)

**Comment by apprenticeharper** [comment]
Interesting comments, but nothing to be done now. Issue closed.
