### ISSUE TITLE
Can't convert from amazon

### ISSUE THREAD

**Issue by johnnybrit** [apprenticeharper/DeDRM_tools#2056]
[tmpjl_2qp4i.txt](https://github.com/apprenticeharper/DeDRM_tools/files/8497855/tmpjl_2qp4i.txt)

Problem with ebook downloaded from Amazon today. Downloaded to Kindle for PC.

Win 10 on X1 7th Gen. Calibre 5.40 (also failed with 5.34), DeDRM 7.21.

Error message: "Cannot convert..."
"Book is protected by DRM"

[tmpjl_2qp4i.txt](https://github.com/apprenticeharper/DeDRM_tools/files/8497920/tmpjl_2qp4i.txt)
.

**Comment by ElleKayEm** [comment]
This is a KFX format book.  You'll either need to download it with an older version of Kindle for PC or use one of the methods to avoid KFX format and get older formats if possible.  See this post for details: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by johnnybrit** [comment]
Dear ElleKayEm, thank you so much. What superb and rapid support on this GitHub area!

You're right. I was using Kindle for PC 1.34, but didn't have the .bat file to defeat KFX format. Once I installed that everything worked smoothly.

Many thanks.
