### ISSUE TITLE
dedRM_temp.log: No such file or directory - Mac

### ISSUE THREAD

**Issue by timdafweak** [apprenticeharper/DeDRM_tools#206]
Not quite sure if it is something I may be doing wrong - but the last version that actually worked on my 10.12.3 (macOS Sierra) is 6.4.3, before the major rewrite for macOS/OS X. I have tried every version since 6.4.3, on multiple Macs, to the same end result. The log file just states - 

`dedRM_temp.log: No such file or directory`

Any tips/pointers would be highly appreciated.

**Comment by apprenticeharper** [comment]
I'll see if I can reproduce the problem.

**Comment by pdurrant** [comment]
Version 6.5.3 is working fine for me on Mac OS X 10.12.3. I don't know if that helps. I even tried in a new user account, to make sure it worked in a fresh start.

I've opened it up in Script Editor, and DeDRM_temp.log seems to just be a temp file used in ~/Library/Preferences/com.apprenticealf.dedrm

Is there anything peculiar about your user account?

**Comment by timdafweak** [comment]
So, this is interesting - I installed 6.4.3 and DeDRM'd a book or two. That, as I wrote earlier, worked fine after 6.5.3 erred out with the above message. I quickly deleted the app, and downloaded 6.4.3.

Today, I decided to give 6.5.3 another shot, mainly to get a more detailed error message for you guys. However, this time it worked just fine and the DeDRM'd copy got placed on my Desktop, without any errors or warnings. 

I wonder whether the 6.4.3 created the dedRM_temp.log, but somehow, 6.5.3 isn't able to create it on a fresh install?

**Comment by pdurrant** [comment]
How strange. 6.5.3 does work on a fresh install - I went so far as to create a new user account and try it there.

**Comment by apprenticeharper** [comment]
I haven't managed to reproduce the problem. I'm going to assume it was some strange and unusual circumstance that is unlikely to reoccur.

**Comment by jeffbr13** [comment]
I'm encountering this issue too, using 6.5.3 on Mac OS (no previously installed versions).

**Comment by jeffbr13** [comment]
Looks like 6.5.3 doesn't create `~/Library/Preferences/com.apprenticealf.dedrm/` on startup, hence outputting:

```
There is 1 ebook to be decrypted.
Processing file: Capitalist Realism.epub
shellcommand: /usr/local/bin/python '/Applications/DeDRM.app/Contents/Resources/zipfix.py' '/Users/ben/Documents/Digital Editions/<snip>.epub' '/Users/ben/Desktop/<snip>_fixed.epub' > '/Users/ben/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult:  sh: /Users/ben/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log: No such file or directory
There was an error with 1 ebook:
<snip>.epub had a problem with ZipFix:
sh: /Users/ben/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log: No such file or directory
```

The fix is to run `mkdir ~/Library/Preferences/com.apprenticealf.dedrm`.

**Comment by apprenticeharper** [comment]
I shall add some code in the next release to always create that folder if it doesn't already exist. There must be some paths in the code which create the path, and some that don't.

Thanks for the reports.

**Comment by apprenticeharper** [comment]
I found some places to change. A new version of the Mac App is available in the repository and will be included in the next release. Thanks for the reports.
