### ISSUE TITLE
DRM not removed - Python function terminated unexpectedly (AZW3)

### ISSUE THREAD

**Issue by danaalbrecht** [apprenticeharper/DeDRM_tools#207]
calibre Debug log
calibre 2.79 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 135.5328125 x 135.466666667
Starting up...
Started up in 17.69 seconds with 77 books
Worker Launch took: 0.40499997139
Job: 1 Convert book 1 of 1 (Perceiving the Divine through the Human Body: Mystical Sensuality) finished
Convert book 1 of 1 (Perceiving the Divine through the Human Body: Mystical Sensuality)
	Conversion options changed from defaults:
	  filter_css: u''
	  sr3_search: None
	  read_metadata_from_opf: u'C:\\Users\\dwa\\AppData\\Local\\Temp\\calibre_goqk6b\\rstcvs.opf'
	  sr1_search: None
	  sr3_replace: None
	  sr1_replace: None
	  cover: u'C:\\Users\\dwa\\AppData\\Local\\Temp\\calibre_goqk6b\\4auavo.jpeg'
	  search_replace: '[]'
	  output_profile: 'generic_eink'
	  sr2_search: None
	  transform_css_rules: '[]'
	  sr2_replace: None
	  verbose: 2
	Resolved conversion options
	calibre version: 2.79.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\dwa\\AppData\\Local\\Temp\\calibre_goqk6b\\4auavo.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000000000284DA20>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000000000284DDA0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\dwa\\AppData\\Local\\Temp\\calibre_goqk6b\\rstcvs.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\dwa\AppData\Local\Temp\calibre_goqk6b\l1j7dg.azw
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Perceiving the Divine through the Human Body: Mystical Sensuality (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1074, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 152, in check_for_drm
	calibre.ebooks.DRMError: Perceiving the Divine through the Human Body: Mystical Sensuality

Source: https://www.amazon.com/Perceiving-Divine-through-Human-Body/dp/0230119743/
AZW3 file available at: https://www.dropbox.com/s/sy75zxkw45uliep/Perceiving%20the%20Divine%20through%20the%20Human%20Body_%20Mystical%20Sensuality%20-%20T.%20Cattoi%20%26%20J.%20McDaniel.azw?dl=0

**Comment by ElleKayEm** [comment]
DRM removal happens during import, not conversion.  Post an import log.  Although if this is a rental, that's why the DRM wasn't removed.

**Comment by apprenticeharper** [comment]
No response. Issue closed.
