### ISSUE TITLE
Usage of Other_Tools/DRM_Key_Scripts/Kindle_for_Mac_and_PC/kindlekey.pyw

### ISSUE THREAD

**Issue by Jystro** [apprenticeharper/DeDRM_tools#2071]
I'm facing some issues while trying to run kindlekey.pyw on Windows 11.

First, I get errors regarding exceptions such as `raise DecryptNotBlockAlignedError, 'Data not block aligned on decrypt'` `SyntaxError: invalid syntax` and `except getopt.GetoptError, err:` `SyntaxError: multiple exception types must be parenthesized`
I believe this is caused by a different version of Python from 3.10, so I changed to `raise DecryptNotBlockAlignedError('Data not block aligned on decrypt')` and `except getopt.GetoptError as err:`

I then edited the print syntax from Python 2.x to 3.x

But when running `python ./kindlekey.pyw` I get no output in the console whatsoever, nor in the file system

I am probably not using the command in the correct way. However, I have no clues for the correct arguments

Anyone got any suggestion? Thank you

**Comment by ElleKayEm** [comment]
The scripts in Other Tools are really out-of-date.  Try running kindlekey.py from the DeDRM plugin.  For the most up-to-date, look at noDRM's fork.

**Comment by Jystro** [comment]
Thank you, will check and update the issue accordingly
