### ISSUE TITLE
DeDRM_plugin_ReadMe.txt should mention that Kindle for PC needs Windows 7/8.1and 1.17

### ISSUE THREAD

**Issue by oneiros-de** [apprenticeharper/DeDRM_tools#208]
Thanks for your work!

One stumbling block for me was that the Windows version of Wine defaulted to XP which Kindle for PC does not like. The solution was [here](https://www.hiroom2.com/2016/09/26/ubuntu-16-04-run-kindle-for-pc-windows-with-wine/): Make sure that the Windows version is 7 or 8.x.

And the Readme should point to Kindle for PC 1.17 (like the FAQ already does).

**Comment by apprenticeharper** [comment]
Thanks. I've made some updates to the readmes that willl be in the next release.
