### ISSUE TITLE
Issue with DeDRM with Calibre 5.44 converting a epub to a mobi

### ISSUE THREAD

**Issue by davidjgillcrist** [apprenticeharper/DeDRM_tools#2081]
Here is the debug log file. I'm not sure what the fix should be.

[tmpu7vkccig.txt](https://github.com/apprenticeharper/DeDRM_tools/files/8954347/tmpu7vkccig.txt)

**Comment by ElleKayEm** [comment]
Doesn't appear to be an epub which DeDRM can decrypt.  Log says it doesn't have Adobe or B&N DRM.  Where is it from?

**Comment by davidjgillcrist** [comment]
It's a Canadian public library ePub book, they don't offer Kindle compatibility so I'm trying to convert them to MOBI.

**Comment by ElleKayEm** [comment]
You'd need to be able to download it as an Adobe DRM epub.

**Comment by davidjgillcrist** [comment]
Where would I go/look to determine what type of DRM is being used for this/these files?

**Comment by davidjgillcrist** [comment]
There's a XML file named `encryption` in a folder called `META-INF`, but I don't know what fields (if any) would tell me the DRM being used.

**Comment by davidjgillcrist** [comment]
The file is here, I'm link sharing it because XML is not a supported file type on GitHub (I'm not sure if link sharing is okay, so sorry in advance)
https://linksharing.samsungcloud.com/lcwZunMjpU2J

**Comment by ElleKayEm** [comment]
If it were Adobe DRM, you'd download an acsm file which you then open in Adobe Digital Editions to receive the epub.

**Comment by davidjgillcrist** [comment]
> 

It does come with an ACSM file.

**Comment by ElleKayEm** [comment]
DeDRM isn't recognizing it as an Adobe epub.  Did you open the ACSM with ADE authorized with an Adobe ID?

**Comment by davidjgillcrist** [comment]
I tried to open the ACSM in Adobe Digital Editions (of which I setup to authorize without an Adobe ID) and I get the error:
> Error getting License. License Server Communication Problem: E_LIC_ALREADY_FULLFILLED_BY_ANOTHERUSER

**Comment by ElleKayEm** [comment]
DeDRM works by retrieving the key associated with an Adobe ID to unlock the DRM.  Book and key must be tied to the same Adobe ID.

**Comment by davidjgillcrist** [comment]
So in this scenario where I am checking a book out from a public library, is there any work around where I can convert the epub file to a mobi? OverDrive is used on the computer to view and read the books, I assume they have to authenticate the DRM somehow.

**Comment by ElleKayEm** [comment]
No idea.  Maybe if you can use ADE authorized with an Adobe ID on the acsm file instead of Overdrive in the first place.  But DeDRM isn't set up to work with Overdrive.

**Comment by davidjgillcrist** [comment]
I had to use the overdrive website and validate the ASCM file with Adobe Digital Editions, then I can DeDRM it with Calibre and it works.
