### ISSUE TITLE
where do I enter my kindle SN?

### ISSUE THREAD

**Issue by BeccaPrice** [apprenticeharper/DeDRM_tools#2086]
I'm upgrading my tools, and I can't find in which one I enter my new kindle oasis SN. Please help!

**Comment by ElleKayEm** [comment]
Preferences > Plugins > select DeDRM under File Type > Customize plugin > Kindle eInk ebooks > green plus sign

Best to copy and paste serial number from the website. 
 Click ok or apply on your way back out of the dialogue boxes.  Then restart calibre before adding books.

**Comment by BeccaPrice** [comment]
issue solved
