### ISSUE TITLE
I think I did everything right, but still can't convert

### ISSUE THREAD

**Issue by BeccaPrice** [apprenticeharper/DeDRM_tools#2087]
I successfully updated Calibre, and installed the 7.2.21 tools. I entered my kindle sn in the appropriate field, and restarted Calibre.  I use the Kindle app version 1.17.1 to download the book file. I can drag and drop the book file into Calibre, but it still won't remover the DRM to convert the book. What am I doing wrong, or missing?

**Comment by ElleKayEm** [comment]
Having the Kindle serial number in there will work for books downloaded from the website for that Kindle as long as it's an E-ink Kindle (not a Fire).

As for Kindle for PC, are you sure it is still version 1.17 and hasn't updated?  Was the book downloaded with the current installation of Kindle for PC on the same machine and user as calibre with DeDRM?

**Comment by BeccaPrice** [comment]
I double-checked the Kindle for PC app Help/.About, and it is 1.17.1, and
the automatically update box isn't checked.

I downloaded the book before I configured the DeDRM tool - maybe I should
download it again?

**Comment by BeccaPrice** [comment]
I re-downloaded it, and still get the DRM notice.

**Comment by ElleKayEm** [comment]
Are you downloading it from the website or with Kindle for PC?

**Comment by BeccaPrice** [comment]
Not from the web site - I don't know how to get to that. I'm downloading
through the Kindle for PC app

**Comment by BeccaPrice** [comment]
I even tried restarting my computer - still no luck.

**Comment by ElleKayEm** [comment]
You can download from your content & devices page at Amazon.

Let's see a log:  https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by BeccaPrice** [comment]
calibre Debug log
calibre 5.44 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX
Input) (1, 49, 0) && DeDRM (7, 2, 0) && Package KFX (from KFX Input) (1,
49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1,
49, 0) && Set KFX metadata (from KFX Output) (1, 63, 0) && KFX Output (1,
63, 0)
calibre 5.44 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX
Input) (1, 49, 0) && DeDRM (7, 2, 0) && Package KFX (from KFX Input) (1,
49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1,
49, 0) && Set KFX metadata (from KFX Output) (1, 63, 0) && KFX Output (1,
63, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.36363636363636
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.53] splash screen shown
[0.53] Initializing db...
[0.77] db initialized
[0.77] Constructing main UI...
[1.64] main UI initialized...
[1.64] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing
C:\Users\becca\Documents\My Kindle Content\B07NQ33WZ8_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.0: Trying to decrypt B07NQ33WZ8_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
[10.20] splash screen hidden
[10.20] Started up in 10.20 seconds with 4428 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper:
[b"\xd9t\xdd\xba'\x9fe\xbe~3\x84\x08Si\xcc\x107\xae\xa3E\x9d\xd8\x1b\xed\xf5\xb1\xe9P/W\xa2\xa6",
b'C:\\Users\\becca\\Documents\\My Kindle Content\\B07NQ33WZ8_EBOK.azw']
Added The dragon under the hill to db in: 1.7
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 526, in KindleMobiDecrypt
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 191, in exec_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 184, in exec_module
  File "calibre\customize\zipplugin.py", line 180, in get_code
  File "calibre_plugins.dedrm.kfxdedrm", line 85
    traceback.print_exc()
                        ^
TabError: inconsistent use of tabs and spaces in indentatioAdded 1 books in
2.5 seconds

**Comment by ElleKayEm** [comment]
Update to DeDRM 7.2.1 or 10.0.2.  You're running 7.2.0 which has an error.

**Comment by BeccaPrice** [comment]
That worked! Thank you so much for all your help and patience!

**Comment by ElleKayEm** [comment]
If you're all set, you can close your issues.

**Comment by BeccaPrice** [comment]
issue solved

**Comment by BeccaPrice** [comment]
never mind - figured it out.

**Comment by BeccaPrice** [comment]
will do - how do I do that?

**Comment by ElleKayEm** [comment]
You already closed both of them.
