### ISSUE TITLE
DeDrm works but PDF just contains images of the pages. Is this expected?

### ISSUE THREAD

**Issue by justin-jalandoni** [apprenticeharper/DeDRM_tools#2088]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

I am using Calibre on Windows 10. The DeDrm plugin works but it seems
that the PDF without DRM is made up of images. I can't select the text.
Is this normal?

**Comment by ElleKayEm** [comment]
Some pdfs are just page images.  Removing the DRM wouldn't change it.  Are you using different viewers before and after?

**Comment by justin-jalandoni** [comment]
> Some pdfs are just page images. Removing the DRM wouldn't change it. Are you using different viewers before and after?

Hello, it seems that the original pdf is also composed of PDFs. When I use google play books, since I got the book from there, however, I can select the text. It seems exporting produces a PDF of images
