### ISSUE TITLE
Recent problems with conversion on a previously and successfully downloaded book

### ISSUE THREAD

**Issue by nashiraprime** [apprenticeharper/DeDRM_tools#209]
Today, I tried to import some books and convert them with the plugin, but I got an error message (the one you'll see below). I updated the plugin to see if the problem persisted: indeed it persisted. So I decided to see if the problem was the book, the plugin, the import or the conversion. A week ago, I imported and converted successfully this book (let's call it Booky). I downloaded Booky again to Kindle for PC. And I found out this: Kindle format used to be AZW3 and that's how Booky was formatted when I first imported it to Calibre on February 5. Today, when I downloaded Booky on Kindle for PC, its format was now AZW. I imported Booky to Calibre today it gave me the same error message as the other books. So, there's definitely some changes that Kindle for PC has done. I'll now paste the log. The dialog box said "Conversion error".

Convert book 1 of 1 (B01EROMI1S EBOK)
Resolved conversion options
calibre version: 2.71.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': True,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x044FA150>,
 'insert_blank_line': True,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': True,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 75.0,
 'margin_left': 75.0,
 'margin_right': 75.0,
 'margin_top': 75.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': u'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x044FA510>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'personal_doc': u'[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\dnade\\AppData\\Local\\Temp\\calibre_fwck5w\\lytcj5.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': True,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\dnade\AppData\Local\Temp\calibre_fwck5w\1cidui.azw
Python function terminated unexpectedly
  Unknown book type: '\x81\xc4\xde\x02|\x8c"\x08' (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 132, in main
  File "site.py", line 109, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1064, in run
  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 34, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 81, in __init__
calibre.ebooks.mobi.MobiError: Unknown book type: '\x81\xc4\xde\x02|\x8c"\x08'

**Comment by ElleKayEm** [comment]
Sounds like you've run into the new KFX format.  Uncheck auto-updates in Kindle for PC, and downgrade to version 1.17.  See the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by nashiraprime** [comment]
Thanks! It worked perfectly!

**Comment by ElleKayEm** [comment]
Great!  Go ahead and close this issue.
