### ISSUE TITLE
[QUESTION] Calibre crashes when I click "customize plugin"

### ISSUE THREAD

**Issue by lubint** [apprenticeharper/DeDRM_tools#2104]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
[QUESTION] Calibre crashes when I click "customize plugin"

## My Environment
macOS 10.15.7 Catalina
### Calibre: `Version`
Calibre 6.2.1
### DeDRM: `Version`
DeDRM 7.2.1

## Log
<details><summary>Log Title</summary>

```log
Blacklisting the DeDRM plugin as it is too old and causes crashes
Using calibre Qt style: True
calibre Debug log
calibre 6.2.1  embedded-python: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 6.2.1  embedded-python: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.50000170459899 x 113.50000170459901
[0.00] Starting up...
[0.02] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[0.90] main UI initialized...
[0.90] Hiding splash screen
Starting QuickView
```
</details>

**Comment by ElleKayEm** [comment]
Update to calibre 10.0.3:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by lubint** [comment]
Thank  you.

From: ElleKayEm ***@***.***>
Reply-To: apprenticeharper/DeDRM_tools ***@***.***>
Date: Friday, July 29, 2022 at 9:56 AM
To: apprenticeharper/DeDRM_tools ***@***.***>
Cc: "Lubin, Tim" ***@***.***>, Author ***@***.***>
Subject: Re: [apprenticeharper/DeDRM_tools] [QUESTION] Calibre crashes when I click "customize plugin" (Issue #2104)


Update to calibre 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FnoDRM%2FDeDRM_tools%2Freleases%2Ftag%2Fv10.0.3&data=05%7C01%7Clubint%40wlu.edu%7Cd480e3da16ff4ef4a83108da716a2369%7Cd1a80622a99943e58eb67873905e939e%7C1%7C0%7C637946997928984278%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=69%2BjvYY1QG6D3g43I4fGiQNjt1UmOu2ErCq00PGHt%2B8%3D&reserved=0>

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
