### ISSUE TITLE
FAQs wrong about Kindle for Mac 1.19.1

### ISSUE THREAD

**Issue by pdurrant** [apprenticeharper/DeDRM_tools#211]
I just set up a test account on my Mac to take a look at what's happening with the new Kindle for Mac and KFX format files.

On the Mac, Kindle for Mac 1.19.1 is not downloading KFX files for me. It **is** putting the files inside folders in "My Kindle Content", but the files themselves are the same old Mobipocket of KF8 files that I've been getting in previous versions.

The DeDRM Mac application decrypts them just fine.

And it might be worth noting that you can change the location of the My Kindle Content folder in the Kindle for Mac preferences. the default for the current version (~/Library/Application Support/Kindle) isn't very convenient. I'd recommend changing it to be the old default location of ~/Documents/My Kindle Content/ - it's a lot easier to find on a Mac.

**Comment by apprenticeharper** [comment]
Only some books can download as KFX. I suspect that you happened to pick books that always download as KF8.
