### ISSUE TITLE
de_DRM can't remove borrowed book on amazon prime

### ISSUE THREAD

**Issue by danyindrawan** [apprenticeharper/DeDRM_tools#212]
Is it possible to remove DRM from borrowed book from amazon prime?
Thanks

**Comment by ElleKayEm** [comment]
I'd guess no -- just like rented books.  At any rate, I'd say if you want to continue to have that perk, don't abuse it.

**Comment by danyindrawan** [comment]
Thanks for your reply Elle, how about kindle unlimited? I have try to remove drm but it same and useless.

**Comment by ElleKayEm** [comment]
I'd assume the same.  Again if you want publishers to continue to make their books available for the service, then don't abuse it.

**Comment by captn3m0** [comment]
All the Kindle Unlimited books I have seem to be using KFX format: https://github.com/apprenticeharper/DeDRM_tools/issues/38

**Comment by ElleKayEm** [comment]
The tools are intended for books you own.  If you want to remove the DRM, then buy the book.

**Comment by dunesmopy** [comment]
To add to above comment, lets get this closed. I use and contribute changes to these tools so I can read the books I've **bought**. The readme's are pretty clear that is the aim here. Please do not attempt to hold discussions here that attempt to circumvent that.

**Comment by ElleKayEm** [comment]
Yes, @apprenticeharper would you please close this?
