### ISSUE TITLE
Calibre 6.3.0 fails to initialize DeDRM plugin 7.2.1

### ISSUE THREAD

**Issue by Xanderhr** [apprenticeharper/DeDRM_tools#2125]
Hello,

Here is the error message I get from Calibre when I import Kindle books downloaded through Kindle for PC:

Thanks for your help in advance.

Failed to initialize plugin: 'C:\\Users\\User\\AppData\\Roaming\\calibre\\plugins\\K4PC, K4Mac, Kindle Mobi and Topaz DeDRM.zip'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 743, in initialize_plugins
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 309, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 201, in exec_module
  File "calibre\customize\zipplugin.py", line 197, in get_code
  File "calibre_plugins.k4mobidedrm.__init__", line 48
    print "%s is not a valid Kindle serial number or PID." % str(customvalue)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Journal de débogage
calibre 6.3  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 64, 0) && KFX Output (1, 64, 0)
calibre 6.3  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 64, 0) && KFX Output (1, 64, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 100.55257731958763
[0.00] Starting up...
[0.02] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[1.41] main UI initialized...
[1.41] Hiding splash screen
Starting QuickView
[18.70] splash screen hidden
[18.70] Started up in 18.70 seconds with 100 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'R?\xe4l\xf8j\xe1xM\x0e\xf0C\xb2\x17\xd0\xee\x94\xa8d\x13\xdb\xa0\x11\xf7\x0e}\xca\xbd\xb8j\xf7\x16', b'C:\\Users\\User\\Documents\\My Kindle Content\\B07C9H5V68_EBOK.azw4', b'C:\\Users\\User\\Documents\\My Kindle Content\\B08P5Y5LB8_EBOK.azw4']
Failed to initialize plugin: 'C:\\Users\\User\\AppData\\Roaming\\calibre\\plugins\\K4PC, K4Mac, Kindle Mobi and Topaz DeDRM.zip'
DeDRM v7.2.1: Trying to decrypt B07C9H5V68_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Failed to initialize plugin: 'C:\\Users\\User\\AppData\\Roaming\\calibre\\plugins\\K4PC, K4Mac, Kindle Mobi and Topaz DeDRM.zip'
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Topologie générale et espaces normés - 2e éd. : Cours et exercices corrigés (Mathématiques) (French Edition)
Got DSN key from database default_key
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
File is encoded with PID CGn0iEMJE6.
Decrypting. Please wait . . . . . DeDRM v7.2.1: Trying to decrypt B08P5Y5LB8_EBOK.azw4
. Using Library AlfCrypto DLL/DYLIB/SO
. Using Library AlfCrypto DLL/DYLIB/SO
. . . . . . MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
. Decrypting Mobipocket 4 ebook: Arithmétique et cryptologie - 2e édition (Références sciences) (French Edition)
Got DSN key from database default_key
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
. . File is encoded with PID PmNbLlNaEI.
Decrypting. Please wait . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . done
Decryption succeeded after 0.8 seconds
. DeDRM v7.2.1: Finished after 0.9 seconds
done
Decryption succeeded after 0.6 seconds
DeDRM v7.2.1: FiAdded Topologie générale et espaces normés - 2e éd. : Cours et exercices corrigés (Mathématiques) (French Edition) to db in: 1.4
Added Arithmétique et cryptologie - 2e édition (Références sciences) (French Edition) to db in: 1.8
Added 2 books in 4.8 seconds

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by ElleKayEm** [comment]
Also you can remove the really ancient "K4PC, K4Mac, Kindle Mobi and Topaz DeDRM" plugin.  DeDRM replaces all those seperate file type DeDRM plugins.

**Comment by Xanderhr** [comment]
@ElleKayEm Updating to 10.0.3 worked fine. Thank you very much.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
