### ISSUE TITLE
Failed to create new key for NOOK in Calibre

### ISSUE THREAD

**Issue by Shen-1122** [apprenticeharper/DeDRM_tools#2129]
I am using DeDRM plugin in Calibre for NOOK books,which download by NOOK app for Windows
When creating new key,the account and password are certainly correct.As for connection,I using **Global System Proxy**
Then failed to retrieve key,what should I do to make it work?

**Comment by ElleKayEm** [comment]
noDRM's version of DeDRM will extract the key from the Windows app: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

In DeDRM's customization click ADE PassHash (B&N) ebooks > green plus sign > Extract key from Nook Windows application
