### ISSUE TITLE
DeDRM not working on Mac Os 11.6.8 with Calibre 6.4.0 and DeDRM 7.2.1

### ISSUE THREAD

**Issue by Dancoet** [apprenticeharper/DeDRM_tools#2130]
I am unable to send ebook to a Kindle Oasis as it is still locked with DRM.

LOg file:
lacklisting the DeDRM plugin as it is too old and causes crashes
Using calibre Qt style: True
calibre Debug log
calibre 6.4  embedded-python: True
macOS-11.6.8-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('11.6.8', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 6.4  embedded-python: True
macOS-11.6.8-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('11.6.8', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.50000170459899 x 113.50000170459901
[0.00] Starting up...
[0.05] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
[1.12] main UI initialized...
[1.12] Hiding splash screen
Starting QuickView
Blacklisting the DeDRM plugin as it is too old and causes crashes
[7.18] splash screen hidden
[7.18] Started up in 7.18 seconds with 45 books

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by Dancoet** [comment]
Thanks but it still does not work.
Here is the log:
Using calibre Qt style: True
calibre Debug log
calibre 6.4  embedded-python: True
macOS-11.6.8-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('11.6.8', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.4  embedded-python: True
macOS-11.6.8-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('11.6.8', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.50000170459899 x 113.50000170459901
[0.00] Starting up...
[0.03] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.42] db initialized
[0.42] Constructing main UI...
[1.32] main UI initialized...
[1.32] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Livia Lone - Édition française (French Edition).azw3
Using Library AlfCrypto Python
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Livia Lone - Édition française (French Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/danielcoetsier/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/danielcoetsier/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[6.37] splash screen hidden
[6.37] Started up in 6.37 seconds with 44 books
Added Livia Lone - Édition française (French Edition) to db in: 0.0
Added 1 books in 0.9 seconds

**Comment by ElleKayEm** [comment]
Looks like you need to enter your Kindle's serial number into DeDRM's customization.

**Comment by Dancoet** [comment]
I missed this step.
Many thanks. It works fine.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
