### ISSUE TITLE
ADE / DRM removal

### ISSUE THREAD

**Issue by MiguelSchg** [apprenticeharper/DeDRM_tools#2138]
Hi everyone

I have problems to free a pdf book.

I downloaded with ADE 4.5 and then converted it with Calibre (DeDrm 7.1.2) It appears in the list but when I try to open it I get the message:
PDF error: Unsupported security scheme.

With ebooks in other formats I have no problems.

Is there any help?
Thanks a lot.

Miguel

**Comment by ElleKayEm** [comment]
Try DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by MiguelSchg** [comment]
Great. It works.
Thank you very much!!
