### ISSUE TITLE
DeDRM is not working

### ISSUE THREAD

**Issue by carlavc** [apprenticeharper/DeDRM_tools#214]
Hi, i install the tools and i did imported 8 ebooks, but the DeDRM calibre plugin works only whit one of them.
I'm using Ubuntu 16.04 LTS, Calibre 2.55, and the ebooks i did buy them in bajalibros.com/AR site.
Here's the log after run Calibre in debbugin mode:
[tmp8CgXBW.txt](https://github.com/apprenticeharper/DeDRM_tools/files/790807/tmp8CgXBW.txt)
Thanks in advanced. 

calibre Registro de depuración
calibre 2.55  embedded-python: False is64bit: True
Linux-4.4.0-63-generic-x86_64-with-Ubuntu-16.04-xenial Linux ('64bit', 'ELF')
('Linux', '4.4.0-63-generic', '#84-Ubuntu SMP Wed Feb 1 17:20:32 UTC 2017')
Python 2.7.12
Linux: ('Ubuntu', '16.04', 'xenial')
Successfully initialized third party plugins: DeDRM
Starting up...
DeDRM v6.0.8: Trying to decrypt Random.epub
DeDRM v6.0.8: Verifying zip archive integrity
DeDRM v6.0.8: Random.epub is a secure Adobe Adept ePub
DeDRM v6.0.8: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v6.0.8: Running adobekey.py under Wine
DeDRM v6.0.8: Command line: “wine python.exe "/home/usuario/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/usuario/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"”
/bin/sh: 1: wine: not found
DeDRM v6.0.8: Found and decrypted 0 key files
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 226, in ePubDecrypt
IndexError: list index out of range
DeDRM v6.0.8: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 154, in _run_filetype_plugins
    nfp = plugin.run(path_to_file)
  File "calibre_plugins.dedrm.__init__", line 482, in run
  File "calibre_plugins.dedrm.__init__", line 268, in ePubDecrypt
DeDRMError: DeDRM v6.0.8: Ultimately failed to decrypt “Random.epub” after 0.1 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Started up in 17.43 seconds with 11 books
Added Random to db in: 1.1
Added 1 books in 2.2 seconds

**Comment by ElleKayEm** [comment]
The one that "worked" must have already been DRM-free as the tools are not finding your Adobe Digital Editions key at all.  I'm not familiar with getting this working with Linux, but I notice that you're using a really old version of the tools.  You also don't mention your setup for ADE or what version, and I've seen that Linux users have problems with that.

**Comment by carlavc** [comment]
Thanks ElieKayEm, the tool is the last one (6.5.3) and ADE don't run on Linux. 
I guess i must install wine, and then ADE so that's it how keys from Adobe will be find by DeDRM.
Thank you again! you really help me.

**Comment by ElleKayEm** [comment]
Log is showing DeDRM version 6.0.8.

**Comment by carlavc** [comment]
You're right. I just reinstall DeDRM. Thanks.
Now i'll see install wine and ADE.

**Comment by apprenticeharper** [comment]
It seems things are resolved. Issue closed.
