### ISSUE TITLE
[QUESTION] Is it possible to open acsm URL link and download PDF directly using Calibre instead of ADE

### ISSUE THREAD

**Issue by biozzl** [apprenticeharper/DeDRM_tools#2140]
## Title
Is it possible to open acsm URL link and download PDF directly using Calibre instead of ADE？
Or is there any plugin to do that？Tried one plugin DeACSM_0.0.16 but not able to do that

**Comment by ElleKayEm** [comment]
The DeACSM plugin is the only alternative to using ADE that I'm aware of.

**Comment by biozzl** [comment]
> The DeACSM plugin is the only alternative to using ADE that I'm aware of.

Thank you for the reply.
