### ISSUE TITLE
EPUB not possible to open after DRM removed 

### ISSUE THREAD

**Issue by MoraDani95** [apprenticeharper/DeDRM_tools#2147]
Hi

I tried removing the DRM from a book I downloaded from https://www.editions-ellipses.fr/ on my PC(windows 11). I bought it and I wanted to read it on my Kindle. Below is the log I got

Windows 11 : My Environment
Calibre: 6.5.0
Kindle: Basic, 10th generation
DeDRM: v7.2.1
Thanks

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Registro de depuración
calibre 6.5  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
calibre 6.5  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
[0.00] Starting up...
[0.00] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
[1.25] main UI initialized...
[1.25] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Capes Espagnol. Épreuve écrite disciplinaire - La composition. S.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Capes Espagnol. Épreuve écrite disciplinaire - La composition. S.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.5 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.5 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 358, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 393, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Could not locate privateLicenseKey
DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[6.11] splash screen hidden
[6.11] Started up in 6.11 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xaf\xd0\xd2\x95\xdf\x13\xeaV\x10oAY<\xcc\x18\xa6\xf7\xe4E\x0cF?\xee\x93\x10\xb6\xde\x8c\xbb{6K', b'C:\\Users\\Lenovo\\Desktop\\CAPES\\Capes Espagnol. \xc3\x89preuve \xc3\xa9crite disciplinaire - La composition. S.epub']
Exception ignored in: <function NativeFunction.__del__ at 0x00000208ED546DD0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x00000208ED546DD0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
---

**Comment by ElleKayEm** [comment]
Use DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by MoraDani95** [comment]
Hi, thanks for your answer, I just tried that version, it didn't work wither. When I tried to open it, a massage says that the book contains DRM , therefore it is not possible to open it. Here's the log I got. Thanks 

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Registro de depuración
calibre 6.5  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
calibre 6.5  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[0.89] main UI initialized...
[0.89] Hiding splash screen
Starting QuickView

**Comment by MoraDani95** [comment]
Hi, thanks for your answer, I just tried that version, it didn't work wither. When I tried to open it, a massage says that the book contains DRM , therefore it is not possible to open it. Here's the log I got. Thanks

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Registro de depuración
calibre 6.5 embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
calibre 6.5 embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[0.89] main UI initialized...
[0.89] Hiding splash screen
Starting QuickView

**Comment by ElleKayEm** [comment]
No book added in this log so can't tell what the problem is.

**Comment by MoraDani95** [comment]
Hi, I communicate with the web site where I bought the book and they said they unblocked the link so I can download the book and open it with ADE. But, I read about the ADE version that allows to convert the epub. So I erased the last ADE version and I was hoping I couls use the new unlocked link with the ADE 2.0 version that I downloaded. But in fact it wasn't possible, when I tried to get the Epub book by opening it with ADE 2.0 I got the message "ERROR Check activation". 
So I went to a website to tried to get information about the ACSM file by "converting" it into a PDF. 

Here's what I got. 

`<fulfillmentToken fulfillmentType="buy" auth="user" 
xmlns="http://ns.adobe.com/adept">
 <distributor>urn:uuid:f0816700-f2d0-4b0e-b8e8-35ebb7768dee</distributor>
 <operatorURL>http://entrepot2.numilog.com/fulfillment</operatorURL>
 <transaction>Ellipses-58922-2094419-0001</transaction>
 <purchase>2022-09-29T16:31:30+02:00</purchase>
 <expiration>2023-01-07T15:31:30+01:00</expiration>
 <resourceItemInfo>
 <resource>urn:uuid:56426e60-c10f-41e5-a8a3-8b6eb3e8e14d</resource>
 <resourceItem>0</resourceItem>
 <metadata>
 <dc:title xmlns:dc="http://purl.org/dc/elements/1.1/">Capes Espagnol. Épreuve
écrite disciplinaire - La composition. Session 2023. Représentations et satires de 
la société dans le monde hispanique.</dc:title>
 <dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Marigno (sous la 
dir.) Emmanuel, Parisot (sous la dir.) Fabrice</dc:creator>
 <dc:publisher xmlns:dc="http://purl.org/dc/elements/1.1/">Editions 
Ellipses</dc:publisher>
 <dc:identifier 
xmlns:dc="http://purl.org/dc/elements/1.1/">2094419</dc:identifier>
 <dc:format 
xmlns:dc="http://purl.org/dc/elements/1.1/">application/epub+zip</dc:format>
 <dc:language xmlns:dc="http://purl.org/dc/elements/1.1/">FRE</dc:language>
 </metadata>
 <licenseToken>
 <resource>urn:uuid:56426e60-c10f-41e5-a8a3-8b6eb3e8e14d</resource>
 <permissions>
 <display/>
 <print>
 <count initial="488"/>
 </print>
 <play/>
 </permissions>
 </licenseToken>
 </resourceItemInfo>
 <hmac>/kxEZgTm5RVhXz8cfle2v00CgTQ=</hmac>
</fulfillmentToken`

So, what should I do with the acsm file to get the epub file to convert it on Calibre to be able to read it on my Kindle?

**Comment by ElleKayEm** [comment]
You can use the more recent edition of Adobe Digital Editions.  Be sure to authorize ADE with your Adobe ID before using it to open the ACSM file.  Also ADE must be installed on the same machine and user as calibre with DeDRM.

**Comment by MoraDani95** [comment]
But here https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md they said "Do NOT use Adobe Digital Editions 3.0 or later to download your ePubs. ADE 3.0 and later might use a new encryption scheme that the tools can't handle. While major ebook stores aren't using the new scheme yet, using ADE 2.0.1 will ensure that your ebooks are downloaded using the old scheme. Once a book has been downloaded with the new scheme, it's IMPOSSIBLE to re-download using the old scheme (without buying it again)." 

That's why I wouldn't want it to open it with the last version. It seems that then I couldn't convert it on Calibre

**Comment by ElleKayEm** [comment]
DeDRM 10.0.3 can handle this newer encryption.  You are looking at the FAQs for Apprentice Harper's DeDRM which ended with version 7.2.1.  If you were unable to download your book with ADE 2, then it seems likely they aren't providing it with the older encryption anyway.  Just be certain to authorize ADE with your Adobe ID before opening the ACSM file.

**Comment by MoraDani95** [comment]
You were right! It finally worked! In Calibre I did open it and convert it toread to my kindle. Thanks a lot!
