### ISSUE TITLE
Error message installing DeDRM tools (Calibre plugin)

### ISSUE THREAD

**Issue by lmfclcl** [apprenticeharper/DeDRM_tools#215]
I have Calibre 2.79.1 (64 bit) installed on my computer running Windows 7 Pro 64 bit.
I am trying to load the DRM removal Plugin and continue to get an error message that the zip file does not contain the top level "_init_.py" file.

I tried Version 6.5.2 and 6.5.3 of the DeDRM removal tools.  A log of the error is below.  What do I do to correct this?

I did check the contents of both Zip files and they do contain a file called _init_.py so I'm not sure whats going on.

Thank you.

Lisa
___________________________________________________________________________________________________________

calibre, version 2.79.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Programs to install\\DRM Removal Tools\\DeDRM_tools_6.5.2.zip' is invalid. It does not contain a top-level __init__.py file

calibre 2.79.1 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 460, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 59, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 192, in load
  File "site-packages\calibre\customize\zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'C:\\Programs to install\\DRM Removal Tools\\DeDRM_tools_6.5.2.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're trying to install the whole archive.  Unzip that and look in the DeDRM calibre plugin folder for the zip file to load into calibre.
