### ISSUE TITLE
Calibre 6.6.1 crashes when customizing DeDRM

### ISSUE THREAD

**Issue by peterwjsinclair** [apprenticeharper/DeDRM_tools#2150]
I have just installed Calibre 6.6.1 and DeDRM 7.2.1 on a MacBook Pro with macOS 12.6.
I am unable to remove DRM from epub titles loaded into Adobe Digital Editions (as I used to be able)
But also,
Calibre is crashing whenever I try to Customize the DeDRM plugin; other plugin customizations work without crashing.
Key error message in attached crash dump is:
"Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI."
It is hard to see which libcrypto.dylib is being accessed, presumably the one in /Applications/calibre.app/Contents/Frameworks which is libcrypto.1.1.dylib.
Crash dump:
[calibre-6.6.1-crash.txt](https://github.com/apprenticeharper/DeDRM_tools/files/9701566/calibre-6.6.1-crash.txt)

**Comment by ElleKayEm** [comment]
For calibre 6.x, you need DeDRM 10.0.3:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by peterwjsinclair** [comment]
Thank you very much. All working now including customization and conversion :-)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by peterwjsinclair** [comment]
Closing issue
