### ISSUE TITLE
DeDRM crashing with Calibre > 5.44 on Mac OS Monterey

### ISSUE THREAD

**Issue by XorPhyson** [apprenticeharper/DeDRM_tools#2158]
Just upgraded Calibre from 5.44 first to 6.6.1 and then to 6.7.0. In both versions it is not possible to remove drm. 

Preferences > Extensions > DeDRM causes Calibre to crash and quit immediately.

Reported from Mac OS 12.6 Monterey.

**Comment by ElleKayEm** [comment]
For calibre 6.x, you need DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by XorPhyson** [comment]
Great, thanks a lot!
