### ISSUE TITLE
Reports "decryption succeeded" but book still has DRM

### ISSUE THREAD

**Issue by kyle7119** [apprenticeharper/DeDRM_tools#216]
calibre Debug log
calibre 2.38  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && Obok DeDRM && Barnes & Noble
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 59.73 seconds with 12 books
DeDRM v6.5.3: Trying to decrypt B00XIHI6CG_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 264
Decrypting Mobipocket 4 ebook: Human Anatomy & Physiology (Marieb, Human Anatomy & Physiology)
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
File is encoded with PID dJ83bypqEG.
Decrypting. Please wait . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . done
Decryption succeeded after 9.4 seconds
DeDRM v6.5.3: Finished after 10.4 seconds
Added Human Anatomy & Physiology (Marieb, Human Anatomy & Physiology) to db in: 1.7
Added 1 books in 12.7 seconds

The screen capture shows that little has actually changed from the original file.

![capture](https://cloud.githubusercontent.com/assets/1540706/23310383/fe32a77c-fa77-11e6-9b69-12d6ddb3d95e.PNG)

**Comment by ElleKayEm** [comment]
So you're unable to open it?  Or extract the PDF using KindleUnpack?

**Comment by apprenticeharper** [comment]
The log certainly seems to show the decryption working. If KindleUnpack doesn't work on your decrypted file, feel free to send me the original encrypted file (the exact one used to generate the above log) and I'll take a look. My email address is  apprenticeharper@gmail.com

**Comment by kyle7119** [comment]
I was confused. It is working correctly
