### ISSUE TITLE
DeDRM not working

### ISSUE THREAD

**Issue by balz666** [apprenticeharper/DeDRM_tools#2163]
## Title
I am on Linux Mint XFCE.

It doesn't work. When I import an epub book that I could convert from acsm to epub using another script, it says it is protected by DRM.

## Log
<details><summary>Log Title</summary>

```log
DeDRM v7.2.1: Trying to decrypt Méditation d'un condamné.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Méditation d'un condamné.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 363, in ePubDecrypt
    defaultkeys = WineGetKeys(scriptpath, ".der",dedrmprefs['adobewineprefix'])
  File "calibre_plugins.dedrm.wineutils", line 74, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "calibre_plugins.dedrm.wineutils", line 37, in __init__
    self.check_call(["-c", self.py3_test])
  File "calibre_plugins.dedrm.wineutils", line 62, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 644, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Méditation d'un condamné to db in: 0.2
Added 1 books in 1.0 seconds

```
</details>

**Comment by ElleKayEm** [comment]
On Linux, DeDRM looks for an installation of ADE under Wine to find your Adobe key which doesn't seem to be your setup.  Suggest using DeDRM 10.0.3 which can work with the ACSM plugin.  The ACSM plugin allows you to import the ACSM file directly into calibre and download the epub without ADE.

DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3
ACSM plugin: https://www.mobileread.com/forums/showthread.php?t=341975

**Comment by balz666** [comment]
Thanks for helping me!

I downloaded 10.0.3 and now here is the log I get:

`DeDRM v10.0.3: Trying to decrypt Méditation d'un condamné.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Méditation d'un condamné.epub is a secure Adobe Adept ePub for UUID 5c3ef0ff-d3e8-4f45-a3c1-329db26e7392
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
0024:err:module:process_init L"C:\\windows\\system32\\py.exe" not found
DeDRM v10.0.3: wine py.exe -3 does not exist
00fc:err:module:process_init L"C:\\windows\\system32\\python3.exe" not found
DeDRM v10.0.3: wine python3.exe does not exist
0104:err:module:process_init L"C:\\windows\\system32\\python.exe" not found
DeDRM v10.0.3: wine python.exe does not exist
wine: cannot find L"C:\\Python27\\python.exe"
DeDRM v10.0.3: wine C:\Python27\python.exe does not exist
DeDRM v10.0.3: Unable to find python3 executable in WINEPREFIX=""
DeDRM v10.0.3: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Méditation d'un condamné to db in: 0.2
Added 1 books in 2.0 seconds
`

It looks like it wants to use Wine or Python, or there is something missing... 

I tried to remove Wine and see if things worked... They don't:

`DeDRM v10.0.3: Trying to decrypt Méditation d'un condamné.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Méditation d'un condamné.epub is a secure Adobe Adept ePub for UUID 5c3ef0ff-d3e8-4f45-a3c1-329db26e7392
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 596, in ePubDecrypt
    defaultkeys, defaultnames = WineGetKeys(scriptpath, ".der",dedrmprefs['adobewineprefix'])
  File "/home/balz/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 96, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "/home/balz/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 59, in __init__
    self.check_call(["-c", self.py3_test])
  File "/home/balz/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 84, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Méditation d'un condamné to db in: 0.2
Added 1 books in 1.1 seconds`

OK, so I also tried to update Calibre to the latest version (6.7.1), and here is what I get now:

`DeDRM v10.0.3: Trying to decrypt Méditation d'un condamné.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Méditation d'un condamné.epub is a secure Adobe Adept ePub for UUID 5c3ef0ff-d3e8-4f45-a3c1-329db26e7392
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 596, in ePubDecrypt
    defaultkeys, defaultnames = WineGetKeys(scriptpath, ".der",dedrmprefs['adobewineprefix'])
  File "/home/balz/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 96, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "/home/balz/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 59, in __init__
    self.check_call(["-c", self.py3_test])
  File "/home/balz/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 84, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "subprocess.py", line 364, in check_call
  File "subprocess.py", line 345, in call
  File "subprocess.py", line 966, in __init__
  File "subprocess.py", line 1842, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Méditation d'un condamné to db in: 0.6
Added 1 books in 1.6 seconds
`

**Comment by ElleKayEm** [comment]
Needs to get your key somehow.  How are you downloading the epub?  Again I suggest using the ACSM plugin if you don't want to mess with ADE.

**Comment by balz666** [comment]
I download using the libgourou script. I simply add my email and password right in the terminal and it downloads the epub from Adobe... But how can I get the keys?? And where to put them?

**Comment by ElleKayEm** [comment]
Again take a look at the ACSM plugin.

**Comment by balz666** [comment]
Doesn't the ACSM plugin do exactly the same thing? 

http://www.mobileread.mobi/forums/showthread.php?t=341975

> A couple months ago, Grégory Soutadé created an open-source ADE replacement library ([libgourou](http://www.mobileread.mobi/?do=go&to=http%3A%2F%2Findefero.soutade.fr%2Fp%2Flibgourou%2F)) in C++ which can be used to "convert" ACSM files into EPUB or PDF files - see the thread [https://www.mobileread.com/forums/sh...d.php?t=3](https://www.mobileread.com/forums/showthread.php?t=340479)

That's exactly what I used to convert my acsm to epub. From what I understand it does not give the keys either, or maybe I am missing something.

**Comment by ElleKayEm** [comment]
DeDRM can get the key from the ACSM plugin instead of ADE.

**Comment by balz666** [comment]
OK I'll check it. Thanks.

**Comment by balz666** [comment]
The ACSM plugin instructions say:

> Download the plugin and import it into Calibre, then open the plugin settings.

That's the first step and that's where I'm stuck. To import a plugin to Calibre, from what I understand, I need to link to a zip file, but [there are no zip files in the ASCM plugin folder](https://github.com/Leseratte10/acsm-calibre-plugin)... What am I missing? How can I import it to Calibre if there are no zip files?

**Comment by ElleKayEm** [comment]
What you download is a zip.  But you don't have to load it like that.  In calibre, click the drop-down menu for Preferences > Get plugins to enhance calibre.  Then search for DeACSM.

**Comment by balz666** [comment]
OK, nice, thanks, I've been able to install it directly in Calibre. I've linked it to the Adobe ID. I'm testing it right now... Seems a bit complicated and still not have been able to download and de-DRM my book.

**Comment by balz666** [comment]
It doesn't work so far. I've tried to download [a test .ACSM](https://www.adobe.com/ca/solutions/ebook/digital-editions/sample-ebook-library.html) from the Adobe website and I can't open it in Calibre. It says it is locked.

Where exactly should I enter the key in DeDRM? Is it in 'Adobe Digital Editions Ebook'? And if so, is the format starting with 

adobe_uuid_5c......

or does it start with

the key number only: 5c.... 

Thanks again for helping me!

**Comment by balz666** [comment]
Oh wait, I think it works! I tried to reopen my ASCM book and I was able to do it... Thanks a lot!!

I borrowed it from the public library. Will it work for more than 21 days on my ereader? Will it stop working then?

In the tutorial, it says that sometimes Adobe can ban your account. Is it frequent? Is it something I should be worried about?

**Comment by ElleKayEm** [comment]
If you've successfully removed the DRM, there's nothing to stop it from working.

No idea about the possibility of Adobe banning your account.

**Comment by balz666** [comment]
Thanks a lot for helping me! 

I guess if I get banned, I would simply use another email... or I'll see what I'd do then!
