### ISSUE TITLE
Calibre crashing when double clicking on plugin + DRM not removed

### ISSUE THREAD

**Issue by pantofola** [apprenticeharper/DeDRM_tools#2169]
Hi,

I am unable to remove DRM from books downloaded to ADE. This is new, I was able to do it just the other day (15 nov) - the only change was that I downloaded the new version of calibre (6.8).

I tried to double click on the deDRM plugin and calibre crashed. 

I've tried to download a previous version of calibre (6.6.1) - same issue.

I tried to reinstall the plugin, same issue.

I've tried with an older version (6.5), same issue. I've tried with 5.7.2, which I had last time I removed a DRM, no luck. 

I've also used the v10.0.3 of the deDRM, but didn't help. 

I've macOS Monterey 12.3.1. 

Here the full error:[error.txt](https://github.com/apprenticeharper/DeDRM_tools/files/10029816/error.txt)

Please let me know if you need any more info. Thanks!

**Comment by ElleKayEm** [comment]
Make sure to use DeDRM 10.0.3 with calibre 6.x.

**Comment by pantofola** [comment]
Thanks, for the comment. I did try that combination before. 

Just to be sure, I've tried again with Calibre 6.8 and DeDRM 10.0.3 and now it works!

Thanks so much
