### ISSUE TITLE
Error, can't convert

### ISSUE THREAD

**Issue by ron66** [apprenticeharper/DeDRM_tools#217]
Hello and Thanks creating this great program.
I have an error, here is the Debug mode log.
Let me know what to do. I appreciate it.

[Log Debug 2-24.txt](https://github.com/apprenticeharper/DeDRM_tools/files/800933/Log.Debug.2-24.txt)

**Comment by ElleKayEm** [comment]
First, your book is the new KFX format which can't be decrypted yet.  To get it in a format that can be decrypted use Kindle for PC version 1.17 or earlier.  See the FAQs:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

Also, the book needs to be downloaded with Kindle for PC that's on the same machine and user as calibre.  The log shows that Kindle for PC isn't installed here -- I'm guessing it no longer works with Windows XP?  So I think you'll need to install calibre and the plugin on the machine where you currently have Kindle for PC/Mac.

Alternatively, if you have an E-ink Kindle, you can download your books from the website.  To decrypt those books, put the Kindle's serial number into the plugin customization.
