### ISSUE TITLE
deDRM not working

### ISSUE THREAD

**Issue by sososimps** [apprenticeharper/DeDRM_tools#2173]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title

deDRM stopped working
## Log
<details><summary>Failed to initialize plugin: '/Users/_______/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'</summary>
Failed to initialize plugin: '/Users/_______/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 743, in initialize_plugins
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 307, in load
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.kobotouch_extended.__init__", line 7, in <module>
    from calibre_plugins.kobotouch_extended.device.driver import KOBOTOUCHEXTENDED
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.kobotouch_extended.device.driver", line 13, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
Blacklisting the DeDRM plugin as it is too old and causes crashes
Using calibre Qt style: True
calibre Debug log
calibre 6.9  embedded-python: True
macOS-13.0.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.0.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Find Duplicates (1, 9, 4) && Kobo Utilities (2, 16, 6) && Obok DeDRM (10, 0, 3)
calibre 6.9  embedded-python: True
macOS-13.0.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.0.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Find Duplicates (1, 9, 4) && Kobo Utilities (2, 16, 6) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 109.00000163701577
[0.00] Starting up...
[0.06] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Thunderbolt Display',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 505, 'width': 1302, 'x': 168, 'y': 730},
 'full_screened': False,
 'geometry': {'height': 477, 'width': 1302, 'x': 168, 'y': 758},
 'maximized': False,
 'normal_geometry': {'height': 477, 'width': 1302, 'x': 168, 'y': 758},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1440,
                                           'width': 2560,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Thunderbolt Display',
            'serial': '',
            'size_in_logical_pixels': {'height': 1440, 'width': 2560},
            'virtual_geometry': {'height': 1440,
                                 'width': 2560,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Thunderbolt Display',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 477, 'width': 1302, 'x': 168, 'y': 758}
DEBUG:    0.6 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.6 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.6 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.6 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended.device.driver'
DEBUG:    0.6 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouch'
DEBUG:    0.6 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended.device.driver'
/Users/______/Library/Application Support/Kindle/For Calibre is not a valid directory to watch for new ebooks, ignoring
[1.22] main UI initialized...
[1.22] Hiding splash screen
Starting QuickView
Failed to initialize plugin: '/Users/_______/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'
Blacklisting the DeDRM plugin as it is too old and causes crashes
[12.38] splash screen hidden
[12.38] Started up in 12.38 seconds with 2274 books
Added A Terrible Kindness to db in: 0.0
Added 1 books in 0.5 seconds
Failed to initialize plugin: '/Users/_________/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'
Blacklisting the DeDRM plugin as it is too old and causes crashes
Failed to initialize plugin: '/Users/__________/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'
Blacklisting the DeDRM plugin as it is too old and causes crashes

```log

```
</details>

**Comment by ElleKayEm** [comment]
This log clearly shows you have DeDRM 7.2.1 which won't work with calibre 6.x.  Make sure you are loading DeDRM_plugin.zip from 10.0.3 and not mistakenly reloading the file from a previous version.  After loading, close and restart calibre.

**Comment by sososimps** [comment]
Yes, I saw that info too.  But I have downloaded Obok DeDRM and tried installing (and restarting the program) several times, but it's still not working.  When I search my installed plugins for DRM it only shows the old one (7.2.1), but DOESN'T show Obok.  It only shows Obok if I specifically search for Obok, but not for DRM.  If it makes any difference, I'm on Mac Ventura.

![Screenshot 2022-11-30 at 11 22 40 am](https://user-images.githubusercontent.com/119460087/204677435-11f2c519-3b91-4c2f-8244-d7323181e351.png)
![Screenshot 2022-11-30 at 11 23 13 am](https://user-images.githubusercontent.com/119460087/204677530-4c0923b1-49eb-4026-83a4-3e1574377730.png)

**Comment by ElleKayEm** [comment]
Try removing 7.2.1, restart calibre, load 10.0.3, and restart calibre again.

**Comment by sososimps** [comment]
Ok, did that.  Now it's saying:

Failed to initialize plugin: '/Users/_____/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 743, in initialize_plugins
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 307, in load
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.kobotouch_extended.__init__", line 7, in <module>
    from calibre_plugins.kobotouch_extended.device.driver import KOBOTOUCHEXTENDED
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.kobotouch_extended.device.driver", line 13, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
Using calibre Qt style: True
calibre Debug log
calibre 6.9  embedded-python: True
macOS-13.0.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.0.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Find Duplicates (1, 9, 4) && Kobo Utilities (2, 16, 6) && Obok DeDRM (10, 0, 3)
calibre 6.9  embedded-python: True
macOS-13.0.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.0.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Find Duplicates (1, 9, 4) && Kobo Utilities (2, 16, 6) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 109.00000163701577
[0.00] Starting up...
[0.07] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.52] db initialized
[0.52] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Thunderbolt Display',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 505, 'width': 1302, 'x': 167, 'y': 730},
 'full_screened': False,
 'geometry': {'height': 477, 'width': 1302, 'x': 167, 'y': 758},
 'maximized': False,
 'normal_geometry': {'height': 477, 'width': 1302, 'x': 167, 'y': 758},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1440,
                                           'width': 2560,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Thunderbolt Display',
            'serial': '',
            'size_in_logical_pixels': {'height': 1440, 'width': 2560},
            'virtual_geometry': {'height': 1440,
                                 'width': 2560,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Thunderbolt Display',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 477, 'width': 1302, 'x': 167, 'y': 758}
DEBUG:    0.6 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.6 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.6 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.6 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended.device.driver'
DEBUG:    0.6 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouch'
DEBUG:    0.6 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended.device.driver'
/Users/_____/Library/Application Support/Kindle/For Calibre is not a valid directory to watch for new ebooks, ignoring
[1.43] main UI initialized...
[1.43] Hiding splash screen
Starting QuickView
Failed to initialize plugin: '/Users/_____/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'
[4.23] splash screen hidden
[4.23] Started up in 4.23 seconds with 2274 books
Added A Terrible Kindness to db in: 0.0
Added 1 books in 0.4 seconds
Failed to initialize plugin: '/Users/_____/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'
Failed to initialize plugin: '/Users/_____/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'

This problem is happening with library books, which is my main source of books.  Previously deDRM has always worked.

**Comment by ElleKayEm** [comment]
So you still cannot install DeDRM 10.0.3?  What happens when you try?

**Comment by sososimps** [comment]
The second log above says "Successfully initialized third party plugins: Find Duplicates (1, 9, 4) && Kobo Utilities (2, 16, 6) && Obok DeDRM (10, 0, 3)", so it looks like it's installed.  It just doesn't actually remove the DRM.

![image](https://user-images.githubusercontent.com/119460087/204691370-559d7190-e047-46b3-b2ef-1f654f4bdad7.png)

**Comment by ElleKayEm** [comment]
I'm sorry I was confused.  I was thinking you were trying to use the regular DeDRM on Adobe DRM.  You're trying to use Obok DeDRM on a book from a Kobo ereader or Kobo Desktop?

**Comment by sososimps** [comment]
I'm happy to use whatever works!  Until last week it worked fine every time, now all of a sudden it won't deDRM.  I only downloaded obok deDRM today in an attempt to solve this problem.

I've downloaded the book from a library, opened it in Adobe Digital Editions, and then opened the epub file in Calibre.  That process used to automatically remove the DRM, but now it doesn't.  Once the DRM is removed (so I can remove the embedded fonts), I then transfer the book to my Kobo via the Calibre desktop program.

If there is an alternative method that will work, just let me know. Thanks

**Comment by ElleKayEm** [comment]
Install the regular DeDRM 10.0.3 plugin then.  DeDRM 7.2.1 would have stopped working when you updated calibre to 6.x.

**Comment by sososimps** [comment]
Sorry this hasn't been an easy fix.  I have deDRM 10.0.3 installed, as well as the obok one, and it's still not working.  I've tried deleting the obok version and restarting (and deleting both and reloading repeatedly), but that didn't work.  Any more suggestions?

![image](https://user-images.githubusercontent.com/119460087/204711738-a1ffb15d-a459-409e-a87f-9f3a557b9367.png)

![image](https://user-images.githubusercontent.com/119460087/204711781-16e6ed0f-c2dd-451a-8668-dfa21ff6feb6.png)

**Comment by sososimps** [comment]
Could it have something to do with the lines I've put in bold/ the last 2 lines???

**Failed to initialize plugin: '/Users/_____/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'**
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 743, in initialize_plugins
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 307, in load
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.kobotouch_extended.__init__", line 7, in <module>
    from calibre_plugins.kobotouch_extended.device.driver import KOBOTOUCHEXTENDED
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.kobotouch_extended.device.driver", line 13, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
Using calibre Qt style: True
calibre Debug log
calibre 6.9  embedded-python: True
macOS-13.0.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.0.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Find Duplicates (1, 9, 4) && Kobo Utilities (2, 16, 6) && Obok DeDRM (10, 0, 3)
calibre 6.9  embedded-python: True
macOS-13.0.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.0.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Find Duplicates (1, 9, 4) && Kobo Utilities (2, 16, 6) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 109.00000163701577
[0.00] Starting up...
[0.07] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.52] db initialized
[0.52] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Thunderbolt Display',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 505, 'width': 1302, 'x': 167, 'y': 730},
 'full_screened': False,
 'geometry': {'height': 477, 'width': 1302, 'x': 167, 'y': 758},
 'maximized': False,
 'normal_geometry': {'height': 477, 'width': 1302, 'x': 167, 'y': 758},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1440,
                                           'width': 2560,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Thunderbolt Display',
            'serial': '',
            'size_in_logical_pixels': {'height': 1440, 'width': 2560},
            'virtual_geometry': {'height': 1440,
                                 'width': 2560,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Thunderbolt Display',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 477, 'width': 1302, 'x': 167, 'y': 758}
DEBUG:    1.2 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    1.2 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    1.2 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    1.2 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended.device.driver'
DEBUG:    1.2 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouch'
DEBUG:    1.2 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended.device.driver'
/Users/_____/Library/Application Support/Kindle/For Calibre is not a valid directory to watch for new ebooks, ignoring
[1.98] main UI initialized...
[1.99] Hiding splash screen
Starting QuickView
**Failed to initialize plugin: '/Users/_____/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'
Failed to initialize plugin: '/Users/_____/Library/Preferences/calibre/plugins/KoboTouchExtended.zip'**

**Comment by ElleKayEm** [comment]
Now that you have DeDRM 10.0.3 installed, let's see a log of adding an Adobe epub to calibre.

**Comment by sososimps** [comment]
Yay, it's working now!!! Thanks for your help.
