### ISSUE TITLE
DRM not working

### ISSUE THREAD

**Issue by Nickfalso** [apprenticeharper/DeDRM_tools#2174]
Converter livro 1 de 1 (Presente e futuro (Obras completas de Carl Gustav Jung))
DeDRM v10.0.3: Trying to decrypt rhbro7ci.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Presente e futuro (Obras completas de Carl Gustav Jung)
Got DSN key from database default_key_1669846609
Found 5 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 5 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\gabri\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\gabri\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2863948526' and UserName 'gabri'
DeDRM v10.0.3: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\gabri\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\gabri\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 5 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  cover: 'C:\\Users\\gabri\\AppData\\Local\\Temp\\calibre_rh48_7jb\\bfre3_qz.jpeg'
  output_profile: 'kindle_pw3'
  read_metadata_from_opf: 'C:\\Users\\gabri\\AppData\\Local\\Temp\\calibre_rh48_7jb\\47gnd1cu.opf'
  verbose: 2
Resolved conversion options
calibre version: 6.9.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': 'C:\\Users\\gabri\\AppData\\Local\\Temp\\calibre_rh48_7jb\\bfre3_qz.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000027403FE8CD0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': 'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x0000027403FE9180>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'personal_doc': '[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\gabri\\AppData\\Local\\Temp\\calibre_rh48_7jb\\47gnd1cu.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v10.0.3: Trying to decrypt rhbro7ci.azw
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Presente e futuro (Obras completas de Carl Gustav Jung)
Got DSN key from database default_key_1669846609
Found 5 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 5 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\gabri\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\gabri\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2863948526' and UserName 'gabri'
DeDRM v10.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\gabri\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\gabri\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 5 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on C:\Users\gabri\AppData\Local\Temp\calibre_rh48_7jb\rhbro7ci.azw
Found KF8 MOBI of type 'standalone'
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
  File "calibre\ebooks\mobi\reader\mobi8.py", line 85, in __call__
  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm
calibre.ebooks.DRMError: Presente e futuro (Obras completas de Carl Gustav Jung)

**Comment by ElleKayEm** [comment]
How did you download the book?

**Comment by Nickfalso** [comment]
Kindle for pc 1.26, as that site says there. Before I could convert the books normally, but now it stopped. This book I'm trying to convert I had already managed, I put it just to test. Forgive my English, I'm Brazilian.

**Comment by Nickfalso** [comment]
I already tried: Putting the kindle serial number in the drm settings;

Use everything in its older versions;

Use everything in its latest versions;

Reinstalling pluggings several times and caliber itself.

I don't know what else to do, I really need to convert a book

**Comment by Nickfalso** [comment]
I even tried to do the same procedure on other computers, and it gave the same error.

**Comment by ElleKayEm** [comment]
Did you download the book with Kindle for PC on the same computer and user where calibre with DeDRM is installed?

Entering a Kindle serial number is for books from/for an E-ink Kindle.

**Comment by Nickfalso** [comment]
Yes, I did. But I tried it on other computers that didn't have the kindle for the pc.

I tried even without the serial number

I don't understand what the problem is, I need this book urgently :(

**Comment by Nickfalso** [comment]
What I find strange is that I had managed to convert some books a few weeks before...

**Comment by ElleKayEm** [comment]
If the book was downloaded with the Kindle app on a different computer, then DeDRM can't retrieve the key.  Each app installation has a unique key.  Only books from/for an E-ink Kindle can be decrypted using that Kindle's serial number.

Make sure Kindle for PC hasn't updated past 1.26.  Get a fresh download of the book.  Add it to calibre on the same computer and user.

Alternatively, if your Kindle is e-ink (not a Fire), you can download from your content and devices page at Amazon.  Make sure you choose your E-ink kindle for the device.  Make sure you have that Kindle's serial number is entered correctly in DeDRM.

**Comment by Nickfalso** [comment]
Thanks, the problem was the damn file. I tried with another one here and it decrypted normally
