### ISSUE TITLE
DeDRM stuck at 1% of conversion 

### ISSUE THREAD

**Issue by DaveMega** [apprenticeharper/DeDRM_tools#2177]
The file is downloaded from archieve.org 

## Log
<details><summary>Log Title</summary>

```log
Convert book 1 of 1 (Events management copy)
DeDRM v10.0.3: Trying to decrypt a259pzdw.pdf
DeDRM v10.0.3: a259pzdw.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: a259pzdw.pdf is a PDF ebook (EBX) for UUID 606becf3-91fb-456f-a1fd-1cb11c3c5014
DeDRM v10.0.3: Trying UUID-matched encryption key default_ade_key_uuid_606becf3-91fb-456f-a1fd-1cb11c3c5014
DeDRM v10.0.3: Decrypted with key default_ade_key_uuid_606becf3-91fb-456f-a1fd-1cb11c3c5014 after 2.4 seconds
DeDRM v10.0.3: Finished after 2.4 seconds
Conversion options changed from defaults:
  read_metadata_from_opf: '/var/folders/g1/84qyqs5n3jq24c2vv5wjr6m40000gn/C/calibre_6.10.0_tmp_ldbpravx/mi9edade.opf'
  verbose: 2
  output_profile: 'generic_eink'
Resolved conversion options
calibre version: 6.10.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x11d381ff0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_images': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x11d381c90>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'Helvetica',
 'pdf_serif_family': 'Times',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/g1/84qyqs5n3jq24c2vv5wjr6m40000gn/C/calibre_6.10.0_tmp_ldbpravx/mi9edade.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
DeDRM v10.0.3: Trying to decrypt 2b5jr1qw.pdf
DeDRM v10.0.3: 2b5jr1qw.pdf is an unencrypted PDF file - returning as is.
DeDRM v10.0.3: Finished after 0.0 seconds
qt.webenginecontext: 

GL Type: disabled
Surface Type: DefaultRenderableType
Surface Profile: CoreProfile
Surface Version: 4.1
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name calibre 
  *  browser-subprocess-path /Applications/calibre.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess 
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-gpu  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl disabled 

InputFormatPlugin: PDF Input running
on /var/folders/g1/84qyqs5n3jq24c2vv5wjr6m40000gn/C/calibre_6.10.0_tmp_ldbpravx/2b5jr1qw.pdf
Converting file to html...

```
</details>

**Comment by ElleKayEm** [comment]
Log shows DRM is removed.  Was DeDRM not installed when you first added the book?  I suggest deleting and re-adding the book to calibre and leaving it in pdf format.

**Comment by DaveMega** [comment]
Uninstalled everything, removed then added the book. Same result.
By the way do you I have authorise the computer with real Adobe id when downloading the book from URLLink?

Here is the new Log:

Convert book 1 of 1 (Successful event management : a practical handbook)
DeDRM v10.0.3: Trying to decrypt aaziz1kx.pdf
DeDRM v10.0.3: aaziz1kx.pdf is an unencrypted PDF file - returning as is.
DeDRM v10.0.3: Finished after 0.1 seconds
Conversion options changed from defaults:
  cover: '/var/folders/g1/84qyqs5n3jq24c2vv5wjr6m40000gn/C/calibre_6.10.0_tmp_ggxbfvdk/wxw30mi0.jpeg'
  read_metadata_from_opf: '/var/folders/g1/84qyqs5n3jq24c2vv5wjr6m40000gn/C/calibre_6.10.0_tmp_ggxbfvdk/uyjg27py.opf'
  verbose: 2
  output_profile: 'generic_eink'
Resolved conversion options
calibre version: 6.10.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': '/var/folders/g1/84qyqs5n3jq24c2vv5wjr6m40000gn/C/calibre_6.10.0_tmp_ggxbfvdk/wxw30mi0.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x1117c1ff0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_images': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x1117c1c90>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'Helvetica',
 'pdf_serif_family': 'Times',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/g1/84qyqs5n3jq24c2vv5wjr6m40000gn/C/calibre_6.10.0_tmp_ggxbfvdk/uyjg27py.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
DeDRM v10.0.3: Trying to decrypt aaziz1kx.pdf
DeDRM v10.0.3: aaziz1kx.pdf is an unencrypted PDF file - returning as is.
DeDRM v10.0.3: Finished after 0.0 seconds
qt.webenginecontext: 

GL Type: disabled
Surface Type: DefaultRenderableType
Surface Profile: CoreProfile
Surface Version: 4.1
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name calibre 
  *  browser-subprocess-path /private/var/folders/g1/84qyqs5n3jq24c2vv5wjr6m40000gn/T/AppTranslocation/43007733-546D-4D99-A1F6-03FB82AAD750/d/calibre.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess 
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-gpu  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl disabled 

InputFormatPlugin: PDF Input running
on /var/folders/g1/84qyqs5n3jq24c2vv5wjr6m40000gn/C/calibre_6.10.0_tmp_ggxbfvdk/aaziz1kx.pdf
Converting file to html...

**Comment by ElleKayEm** [comment]
DRM was already removed before trying to convert in this log.  Conversion would be a calibre issue.

**Comment by DaveMega** [comment]
ok! How to solve this issue? Any tips?

**Comment by ElleKayEm** [comment]
Ask at the calibre forum over at MobileRead?  Personally I'd leave it in pdf format.

**Comment by DaveMega** [comment]
What I do when using calibre is to drag the file to calibre, click on convert books, convert individually, choose output source as PDF. 

Am I doing it right?

**Comment by ElleKayEm** [comment]
DRM is removed when you add it to calibre.  No need to convert a pdf to pdf.

**Comment by DaveMega** [comment]
Ok :) :) :)
Then how to remove DeDRM without converting the file? Generally speaking of course.

**Comment by DaveMega** [comment]
> DRM is removed when you add it to calibre. No need to convert a pdf to pdf.

One more thing ElleKayEm the conversion is not working for the books downloaded from archive.org. Other URLLink.acsm from other resources are being converted to both PDF and Epub.

**Comment by ElleKayEm** [comment]
Just add the book to calibre.  If DeDRM is working correctly, as it is here, that's all you need to do.

**Comment by ElleKayEm** [comment]
The books from archive.org are probably scanned images.

**Comment by DaveMega** [comment]
Thank you buddy! Understood the whole process now :)
