### ISSUE TITLE
Cannot convert book.

### ISSUE THREAD

**Issue by HairyScot** [apprenticeharper/DeDRM_tools#218]
Received a free book from Amazon.
Installed plugin in Calibre. But conversion fails.
[tmpxdcdtl.txt](https://github.com/apprenticeharper/DeDRM_tools/files/802818/tmpxdcdtl.txt)

**Comment by ElleKayEm** [comment]
This book is in the new KFX format.  See the FAQs:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by HairyScot** [comment]
Thanks for the info
