### ISSUE TITLE
DeDRM no longer working after OS/software "upgrade"

### ISSUE THREAD

**Issue by rebeltaz** [apprenticeharper/DeDRM_tools#2180]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
calibre and the DeDRM plugin worked perfectly under Ubuntu 18.04 LTS. Due to needing to run software for a 3d printer, I reluctantly "upgraded" the OS to 22.04 LTS. Upon doing so, calibre also "updated" and the DeDRM plugin was dropped. I reinstalled the new 7.2.1 plugin and verified that my Kindle serial numbers were still loaded. I download ebooks to be "loaded via USB later" and import them into calibre. They import fine, but I am unable to convert them to any other format or read them. The plugin is not DeDRMing the books anymore. Maybe someone can help? 

## Log
<details><summary>Log Title</summary>

```log```
I have no clue where/how to find this

</details>

**Comment by ElleKayEm** [comment]
Try DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

If that doesn't do it, this is how to get the log: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by rebeltaz** [comment]
> Try DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3
> 
> If that doesn't do it, this is how to get the log: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

That one worked great. Thank you!
