### ISSUE TITLE
DeDRM fork claiming removal of latest Kindle DRM.  Is it valid, safe code?

### ISSUE THREAD

**Issue by rabbitd001f** [apprenticeharper/DeDRM_tools#2189]
This site points to a fork of DeDRM which claims to remove the latest Kindle DRM:
https://auresnotes.com/how-to-remove-amazon-kindles-drm-in-2022-latest-update/

Is this legitimate, safe code?  Does it use an approach which would be appropriate for the main DeDRM fork?

**Comment by ElleKayEm** [comment]
The Apprentices have "retired."   noDRM has taken up DeDRM maintainance.  You will need their 10.0.3 version for calibre 6 (also suppose to work with 4 and 5 too).  But it doesn't remove the latest KFX DRM.  You still need the workarounds here: https://www.mobileread.com/forums/showthread.php?t=283371
