### ISSUE TITLE
Calibre tools don't work - here are logs

### ISSUE THREAD

**Issue by Ferante1** [apprenticeharper/DeDRM_tools#219]
Hi Apprentice Team,

Very grateful for your service!
UPDATE - just saw what  ElleKayEm has said to another user, downloaded the older version of Kindle for Mac and - problem solved! I still would like to know, though, how to (alternatively) download files from the Kindle to the Laptop, and also from The kindle library that opens in Calibre when the kindle is attached to laptop. SEE My original post:

I am on a MAC, just installed the latest version of the tools after I discovered (after not using them for a long while) that my older version was not working anymore. 
The 2 books i was trying to open in Calibre were my own books from my Kindle, bought on Amazon. 
I tried to open them by connecting my Kindle with a USB to my laptop; the Kindle device is then discovered by Calibre; then i went to the tab Device/Show Books in the Main Memory of the Device – and I tried to open them from there.
BY THE WAY, this is the ONLY way I can now open books from Amazon. Can't seem to to figure how to do it from my "Kindle for Mac 2", or by cable-connecting the Kindle to laptop and downloading from the Kindle itself, then opening in Calibre. I used to do it this way but things have changed and files look unrecognizable, both in name and in format. (so I would appreciate a link to how to do that, if you know of any).
So, My Results:
The FIRST book would not open at all.
The SECOND book did open, but with the lock-and-key Amazon “This Book is DRMed” message displayed. 
So I have TWO logs to show what happened with each book. 
BIG Thank you in advance!! 

FIRST LOG – FOR BOOK THAT OPENED BUT SHOWED A LOCKED DRM MESSAGE FROM AMAZON:

calibre Debug log
calibre 2.79.1  embedded-python: True is64bit: True
Darwin-16.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.4.0', 'Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.12.3', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && iOS reader applications (1, 4, 7, 0, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 133.000001997 x 139.000002088
Starting up...
Started up in 2.44 seconds with 28 books
2017-02-27 11:38:59.670 Calibre[26527:9144102] deliverNotificationWithTitle()
* Notification delivered.
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
Job: 1 Get device information finished
No details available.
Job: 2 Set library information finished
No details available.
DEBUG:    0.9 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    2.9 USBMS: count found in cache: 624, count of files in metadata: 624, need_sync: False
DEBUG:    2.9 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    2.9 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    2.9 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 624
DeviceJob: set_books_in_library finished: time= 0.0553350448608
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Job: 4 View book on device started
DeviceJob: 4 View book on device done, calling callback
DeviceJob: 4 View book on device callback returned
Worker Launch took: 0.150635004044
Job: 4 View book on device finished
No details available.

SECOND LOG FOR BOOK THAT WOULD NOT OPN AT ALL:

calibre Debug log
calibre 2.79.1  embedded-python: True is64bit: True
Darwin-16.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.4.0', 'Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.12.3', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && iOS reader applications (1, 4, 7, 0, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 133.000001997 x 139.000002088
Starting up...
Started up in 2.39 seconds with 28 books
2017-02-27 11:34:44.888 Calibre[26466:9140482] deliverNotificationWithTitle()
* Notification delivered.

**Comment by ElleKayEm** [comment]
To get non-KFX files which can be decrypted with the tools, you have 3 possible options:

1. Use Kindle for PC/Mac older than version 1.19.
2. If you have an E-ink Kindle, you can download from the website.
3. If you have an older E-ink Kindle (1st gen Paperwhite or older), you can import books from the device itself into calibre.

Not every book is delivered in the new format.  But if the Amazon listing shows Enhanced Typesetting enabled, then it will be.

**Comment by Ferante1** [comment]
Thank you so much!!
