### ISSUE TITLE
DeDRM 10.0.3 plug in does not show up when trying to load a new plugin in Calibre

### ISSUE THREAD

**Issue by GoldieR2** [apprenticeharper/DeDRM_tools#2192]
Hi! I have downloaded and deleted Calibre a thousand times it seems and have done the same with the DeDRM zip files. Every time I try to load a plugin from file, nothing shows up. The instructions are pretty easy to read and follow, but I don't understand what I am doing wrong.

**Comment by ElleKayEm** [comment]
Should appear under File Type plugins.

**Comment by GoldieR2** [comment]
wait, I found it!! Thank you so much!

**Comment by GoldieR2** [comment]
wait
