### ISSUE TITLE
Problem importing AZW3 Amazon Kindle format

### ISSUE THREAD

**Issue by canarino68** [apprenticeharper/DeDRM_tools#22]
DRM hasn't been removed from the book I have imported directly from the Kindle's folder.
I have opened a debug report as suggested and the result follows:

Microsoft Windows [Versione 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tutti i diritti riservati.

C:\Users\Fabio>calibre-debug -g
calibre 2.33  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM

Nothing happens in the terminal windows when I add the new book.
Do you have any suggestion?

Thank you

**Comment by apprenticeharper** [comment]
Make sure that calibre isn't already running at the time you give the calibre-debug -g command.

**Comment by canarino68** [comment]
Ok, this is the new dubug log:

Microsoft Windows [Versione 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tutti i diritti riservati.

C:\Users\Fabio>calibre-debug -g
calibre 2.33  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi li
bri, ignoring
Started up in 14.65 seconds with 28 books
DeDRM v6.2.2: Trying to decrypt The Bourne Identity - Un nome senza volto_ Jason
 Bourne Vol.1 (BUR NARRATIVA)_B0067E950Y.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Bourne Identity - Un nome senza volto: Jas
on Bourne Vol.1 (BUR NARRATIVA) (Italian Edition)
Found 0 keys to try after 1.1 seconds
Crypto Type is: 2
DeDRM v6.2.2: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.2.2: Looking for new default Kindle Key after 1.1 seconds
searching for kinfoFiles in C:\Users\Fabio\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Fabio\AppData\Local\Amazon\Kindle\storag
e\.kinf2011
DeDRM v6.2.2: Ultimately failed to decrypt after 1.4 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugi
ns
  File "calibre_plugins.dedrm.__init__", line 579, in run
  File "calibre_plugins.dedrm.__init__", line 530, in KindleMobiDecrypt
DeDRMError: DeDRM v6.2.2: Ultimately failed to decrypt after 1.4 seconds
Added The Bourne Identity - Un nome senza volto: Jason Bourne Vol.1 (BUR NARRATI
VA) (Italian Edition) to db in: 6.6
Added 1 books in 16.3 seconds

**Comment by ElleKayEm** [comment]
Judging from the file name, this book is from a kindle?  If it is an E-ink kindle, then enter the serial number into the configuration dialog.  Otherwise, download it with Kindle for PC, and import that copy.

**Comment by canarino68** [comment]
Thank you for the suggestion ElleKayEm... now it works.
