### ISSUE TITLE
Thoughts about KFX decryption. 

### ISSUE THREAD

**Issue by rboatright** [apprenticeharper/DeDRM_tools#220]
I have spent zero time, but wanted to ask the hive mind if someone else has already plowed this road...  

In order to display the text of a KFX book on the screen of my windows PC, Kindle.exe has to decrypt the book at some point, producing an html stream that it then renders using the QT library. 

Is it worth the trouble of attempting to find the decrypted html in memory when the book is open in the Kindle viewer and scraping, at least the text if not the formatting and pictures, out of RAM?  

The way the QT renderer works is pretty well documented, and it seems like one ought to be able to snag the decrypted book text from somewhere as it goes past, but perhaps everything is done with streams and there never is a representation of the book in memory before QT renders it into dots on the screen.  It just seems that someone may have already attempted that, and I'm unwilling to spend the limited time I have if someone has already disproven the idea. 

Thanks for bothering to read.

**Comment by apprenticeharper** [comment]
If Kindle for PC uses QT, that might work to get some version of the text in the book. I don't know if anyone's already tried it.

If you have PC reverse engineering experience, it might be a better use of time to try to work out how to decrypt the KFX format. Then there will be others happy to try to work out how to convert KFX to something more useful.

But I don't want to discourage anyone from spending time on the KFX problem in any way they think fit.

**Comment by IDtheTarget** [comment]
Okay, so I've been buying Amazon books specifically because I was able to strip DRM and read my books on Moon+ on my Android phone. I can't configure the Amazon reader in such a way that I can comfortably read my books, but I *can* configure Moon+ in such a way. I just bought a trilogy on Amazon to read, and after having had no problems for years in buying books and using DeDRM on Calibre, I now cannot read my books. I did the debug, and it's saying that KFX format detected and cannot be decrypted. This is the first time I'd heard about this.

Is there another option? I'm currently doing the Amazon Kindle app on Windows 10, then using DeDRM on Calibre. Should I try Adobe DRM or something? I haven't had much luck with buying books on Google, but is that a better option?  Please note, I *want* to buy my books, but I need a way to read them that works with my eyesight and so far none of the major vendors' apps offer me a way to comfortably read the books I buy.

Thanks!

**Comment by IDtheTarget** [comment]
calibre Debug log
calibre 2.77 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Modify ePub (1, 3, 13)
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Starting up...
Started up in 11.49 seconds with 424 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x86E\xc8\xee\xafT\xd7\x1a\xf88\xbb75]\x9fw*\x9f\x86\xa3\xb15\xa1\x10\x19\xf4"\xb0\nu\\\xbc', 'D:\\Documents\\My Kindle Content\\B0046ECFGI_EBOK\\B0046ECFGI_EBOK.azw']
DeDRM v6.5.3: Trying to decrypt B0046ECFGI_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Benjamin\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Benjamin\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3426415460' and UserName '42656e6a616d696e'
DeDRM v6.5.3: Found 1 new key
DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 419, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 283, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 276, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 304, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B0046ECFGI EBOK to db in: 1.6
Added 1 books in 3.1 seconds

**Comment by IDtheTarget** [comment]
Sorry, found this, which fixed my problem:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by ElleKayEm** [comment]
Glad you figured it out.  If you're all set, go ahead and close this issue.

**Comment by IDtheTarget** [comment]
I don't think I can. I'm not the one who originally opened it.

**Comment by ElleKayEm** [comment]
@IDtheTarget 

Oh, you're right.  I was following via email and missed that there were earlier posts.

**Comment by apprenticeharper** [comment]
Time to close this one, I think.
