### ISSUE TITLE
DeDRM for comics removes the cover

### ISSUE THREAD

**Issue by PaulBrad25** [apprenticeharper/DeDRM_tools#2200]
Calibre stores covers separately, but seems to copy them from most ebooks, so the cover still exists in the book file.

BUG: However when I import a *comic book* from Kindle and convert it, it removes the cover entirely so I have to convert to zip and then add it back manually. with several thousand comic books still to go, as you can imagine this is very time consuming.

Kovid Goyal has assured me that this is due to the de-drm software not Calibre itself.

So, is it possible that the DeDRM plugin is scrapping the front cover of the comic? Oddly it doesn't seem do it when converting text books to .epub or .mobi, just comics to .zip

![Capture](https://user-images.githubusercontent.com/122999941/213927489-e71089fc-8926-46ce-bb9e-31517f3bf3eb.JPG)

**Comment by ElleKayEm** [comment]
The cover is missing when you first add the comic?  Because that is when the DRM is removed.

I'm not seeing this myself.  If I add a comic and open it in the editor, the cover image is still there inside the azw3.

**Comment by PaulBrad25** [comment]
Is that right? I thought the .azw file was under DRM until it was converted.

No the cover is missing when I convert to .zip. If you convert that comic to .zip does it dump the first page? 

I'm struggling to get my head around testing it and as far as Kovid is concerned, comics seem to be beneath him.


Update: huh, you're correct, if I import the .azw file into calibre, then turn off apprentice alf and convert to .zip then it still removed the cover.

Sorry to have troubled you.

**Comment by PaulBrad25** [comment]
@ElleKayEm On much further testing, it appears to be an issue with the .zip, and by extension (if you'll excuse the pun) the .cbz format. 
If I convert the book to .epub in calibre, and then change the file extension to .zip or .cbz, then the cover page disappears still, even more confusing is that when I change it back to .epub then the cover comes back. 

So the .zip format itself is hiding the cover, at this point I have no idea how to resolve it, or even who to ask.

**Comment by ElleKayEm** [comment]
Unlike the ebook formats, a zip file doesn't have a designated cover.  In the azw3 comic I looked at in the calibre editor, the front and back covers were the last 2 images by file name.
