### ISSUE TITLE
DRM Not Removed

### ISSUE THREAD

**Issue by kluzy1** [apprenticeharper/DeDRM_tools#2204]
Calibre with DeDRM could not remove DRM on a Kindle book that is a 'rental'... details below. Thank you in advance...
---------------------------------------
calibre 5.37
Windows 11
Debug log below .....
---
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 47, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0)
calibre 5.37 
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 100.55257731958763
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.77] splash screen shown
[0.77] Initializing db...
[0.77] db initialized
[0.77] Constructing main UI...
[1.52] main UI initialized...
[1.52] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.47.0: Importing C:/Users/XXX/Documents/My Kindle Content/B07NRRHF2J_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B07NRRHF2J_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: AAA
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 12 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\XXX\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\XXX\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3669024110' and UserName 'XXX'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: AAA
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[41.45] splash screen hidden
[41.45] Started up in 41.45 seconds with 47 books
Added AAA to db in: 10.0
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 449, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: Cannot decode library or rented ebooks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 1 books in 10.7 seconds
Worker Launch took: 0.06 seconds
Job: 0 Convert book 1 of 1 (AAA) finished
Convert book 1 of 1 (AAA)
	DeDRM v7.2.1: Trying to decrypt ntm36amw.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: AAA
	Got DSN key from database default_key
	Got DSN key from database default_key_2
	Found 12 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: Cannot decode library or rented ebooks.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\XXX\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\XXX\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '3669024110' and UserName 'XXX'
	DeDRM v7.2.1: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: AAA
	Got DSN key from database default_key_1
	Found 4 keys to try after 0.2 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  read_metadata_from_opf: 'C:\\Users\\XXX\\AppData\\Local\\Temp\\calibre_2972mq_h\\09rt96g_.opf'
	  flow_size: 0
	  verbose: 2
	  cover: 'C:\\Users\\XXX\\AppData\\Local\\Temp\\calibre_2972mq_h\\tc8rvxz7.jpeg'
	  output_profile: 'generic_eink'
	Resolved conversion options
	calibre version: 5.37.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': 'C:\\Users\\XXX\\AppData\\Local\\Temp\\calibre_2972mq_h\\tc8rvxz7.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': '2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'flow_size': 0,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x07099568>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x070996E8>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': 'C:\\Users\\XXX\\AppData\\Local\\Temp\\calibre_2972mq_h\\09rt96g_.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.mobidedrm", line 449, in processBook
	calibre_plugins.dedrm.mobidedrm.DrmException: Cannot decode library or rented ebooks.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	DeDRM v7.2.1: Trying to decrypt ntm36amw.azw
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: AAA
	Got DSN key from database default_key
	Got DSN key from database default_key_2
	Found 12 keys to try after 0.0 seconds
	Crypto Type is: 2
### 	DeDRM v7.2.1: Failed to decrypt with error: Cannot decode library or rented ebooks.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\XXX\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\XXX\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '3669024110' and UserName 'XXX'
	DeDRM v7.2.1: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: AAA
	Got DSN key from database default_key_1
	Found 4 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.mobidedrm", line 449, in processBook
	calibre_plugins.dedrm.mobidedrm.DrmException: Cannot decode library or rented ebooks.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on C:\Users\XXX\AppData\Local\Temp\calibre_2972mq_h\ntm36amw.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "runpy.py", line 194, in _run_module_as_main
	  File "runpy.py", line 87, in _run_code
	  File "site.py", line 82, in <module>
	  File "site.py", line 77, in main
	  File "site.py", line 49, in run_entry_point
	  File "calibre\utils\ipc\worker.py", line 215, in main
	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
	  File "calibre\customize\conversion.py", line 242, in __call__
	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "calibre\ebooks\mobi\reader\mobi8.py", line 85, in __call__
	  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm
	calibre.ebooks.DRMError: AAA

**Comment by ElleKayEm** [comment]
Apprentice Harper's DeDRM intentionally has a block on decrypting rentals.  Use noDRM's version if you want to buy for the price of the rental.

**Comment by kluzy1** [comment]
Thank you very much for your timely response. I can understand why it is blocked. Rentals are technically not 'purchased'. Appreciate your time and hope you have a great day.

**Comment by ElleKayEm** [comment]
Thanks for understanding.  You can close this since it isn't really an issue - working as intended in this case.

**Comment by kluzy1** [comment]
Got it! Will do.
