### ISSUE TITLE
DDR not woking

### ISSUE THREAD

**Issue by 47RAD** [apprenticeharper/DeDRM_tools#2205]
OSX 13.1   Calibre 6.12.0   DDR 7.1.0
---

Blacklisting the DeDRM plugin as it is too old and causes crashes
Using calibre Qt style: True
calibre Debug log
calibre 6.12  embedded-python: True
macOS-13.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.2.0', 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112')
Python 3.10.1
OSX: ('13.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && ACE (1, 1, 5) && Find Duplicates (1, 10, 7) && Overdrive Link (2, 53, 0)
calibre 6.12  embedded-python: True
macOS-13.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.2.0', 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112')
Python 3.10.1
OSX: ('13.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && ACE (1, 1, 5) && Find Duplicates (1, 10, 7) && Overdrive Link (2, 53, 0)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.5000019298764 x 128.5000019298764
[0.00] Starting up...
[0.06] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 956, 'width': 1470, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Built-in Retina Display',
 'serial': '',
 'size_in_logical_pixels': {'height': 956, 'width': 1470},
 'virtual_geometry': {'height': 956, 'width': 1470, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 768, 'width': 1225, 'x': 105, 'y': 57},
 'full_screened': False,
 'geometry': {'height': 740, 'width': 1225, 'x': 105, 'y': 85},
 'maximized': False,
 'normal_geometry': {'height': 740, 'width': 1225, 'x': 105, 'y': 85},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 956,
                                           'width': 1470,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Built-in Retina Display',
            'serial': '',
            'size_in_logical_pixels': {'height': 956, 'width': 1470},
            'virtual_geometry': {'height': 956, 'width': 1470, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 956, 'width': 1470, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Built-in Retina Display',
 'serial': '',
 'size_in_logical_pixels': {'height': 956, 'width': 1470},
 'virtual_geometry': {'height': 956, 'width': 1470, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 740, 'width': 1225, 'x': 105, 'y': 85}
[0.98] main UI initialized...
[0.98] Hiding splash screen
Starting QuickView
SMART_DEV (   0.00:  0.000) _attach_to_port try ip address "" on port 9090
SMART_DEV (   0.89:  0.823) _startup_on_demand listening on port 9090
SMART_DEV (   0.92:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   0.94:  0.000) _startup_on_demand broadcast socket listening on port 54982
2023-02-08 10:19:40.468 calibre-debug[17461:1016473] +[CATransaction synchronize] called within transaction
Blacklisting the DeDRM plugin as it is too old and causes crashes
SMART_DEV (   1.96:  1.006) run All IP addresses {'lo0': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'peer': '127.0.0.1'}], 'en0': [{'addr': '10.0.1.22', 'netmask': '255.255.255.0', 'broadcast': '10.0.1.255'}]}
[37.99] splash screen hidden
[37.99] Started up in 37.99 seconds with 373 books
Added The Bullet Garden: An Earl Swagger Novel to db in: 0.0
Added 1 books in 0.4 seconds

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

**Comment by ElleKayEm** [comment]
For calibre 6, you need DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by 47RAD** [comment]
That fixed it   THANK YOU!!!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
