### ISSUE TITLE
Imported .azw won't convert/open

### ISSUE THREAD

**Issue by dustinhuman** [apprenticeharper/DeDRM_tools#2208]
Will you please take a look at the log below?  This was first try using calibre/dedrm, Mac mini m1, Ventura 13.1.  File was purchased from amazon and found in ~/Library/Application Support/Kindle/My Kindle Content.  Is a .azw file (not .azw3, I'm not sure of the distinction or if this the issue).

`Blacklisting the DeDRM plugin as it is too old and causes crashes
Using calibre Qt style: True
calibre Debug log
calibre 6.12  embedded-python: True
macOS-13.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.2.0', 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kobo Utilities (2, 16, 6)
calibre 6.12  embedded-python: True
macOS-13.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.2.0', 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kobo Utilities (2, 16, 6)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 139.00000208757058 x 137.00000205753358
[0.00] Starting up...
[0.05] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 2160, 'width': 3840, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'LG HDR 4K',
 'serial': '',
 'size_in_logical_pixels': {'height': 2160, 'width': 3840},
 'virtual_geometry': {'height': 2160, 'width': 3840, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 2135, 'width': 2502, 'x': 1338, 'y': 25},
 'full_screened': False,
 'geometry': {'height': 2107, 'width': 2502, 'x': 1338, 'y': 53},
 'maximized': False,
 'normal_geometry': {'height': 2107, 'width': 2502, 'x': 1338, 'y': 53},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 2160,
                                           'width': 3840,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'LG HDR 4K',
            'serial': '',
            'size_in_logical_pixels': {'height': 2160, 'width': 3840},
            'virtual_geometry': {'height': 2160,
                                 'width': 3840,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 2160, 'width': 3840, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'LG HDR 4K',
 'serial': '',
 'size_in_logical_pixels': {'height': 2160, 'width': 3840},
 'virtual_geometry': {'height': 2160, 'width': 3840, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 2107, 'width': 2502, 'x': 1338, 'y': 53}
DEBUG:    0.3 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.3 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.3 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.3 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
DEBUG:    0.3 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouch'
DEBUG:    0.3 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
[0.63] main UI initialized...
[0.63] Hiding splash screen
Starting QuickView
2023-02-10 20:54:56.832 calibre-debug[7320:409394] +[CATransaction synchronize] called within transaction
Blacklisting the DeDRM plugin as it is too old and causes crashes
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 436, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 266, in get_metadata
  File "calibre/ebooks/metadata/mobi.py", line 503, in get_metadata
  File "calibre/ebooks/mobi/reader/headers.py", line 293, in __init__
  File "calibre/ebooks/mobi/reader/headers.py", line 321, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'
[2.78] splash screen hidden
[2.78] Started up in 2.78 seconds with 38 books
Added B0BR79DKNS EBOK to db in: 0.1
Added 1 books in 0.5 seconds

{'bsd_drives': {'main': '/dev/disk4'},
 'drives': {'main': '/Volumes/KOBOeReader'},
 'mount_map': {'/dev/disk1s1': '/System/Volumes/iSCPreboot',
               '/dev/disk1s2': '/System/Volumes/xarts',
               '/dev/disk1s3': '/System/Volumes/Hardware',
               '/dev/disk3s1s1': '/',
               '/dev/disk3s2': '/System/Volumes/Preboot',
               '/dev/disk3s4': '/System/Volumes/Update',
               '/dev/disk3s5': '/System/Volumes/Data',
               '/dev/disk3s6': '/System/Volumes/VM',
               '/dev/disk4': '/Volumes/KOBOeReader',
               'devfs': '/dev',
               'map auto_home': '/System/Volumes/Data/home',
               'msdos://disk4/KOBOeReader': '/Volumes/KOBOeReader'}}
DEBUG:    0.0 KoboTouch::open_osx - mount_map= {'/dev/disk3s1s1': '/', 'devfs': '/dev', '/dev/disk3s6': '/System/Volumes/VM', '/dev/disk3s2': '/System/Volumes/Preboot', '/dev/disk3s4': '/System/Volumes/Update', '/dev/disk1s2': '/System/Volumes/xarts', '/dev/disk1s1': '/System/Volumes/iSCPreboot', '/dev/disk1s3': '/System/Volumes/Hardware', '/dev/disk3s5': '/System/Volumes/Data', 'map auto_home': '/System/Volumes/Data/home', 'msdos://disk4/KOBOeReader': '/Volumes/KOBOeReader'}
DEBUG:    0.0 KoboTouch::open_osx - self._main_prefix= /Volumes/KOBOeReader/
DEBUG:    0.0 KoboTouch::open_osx - self._card_a_prefix= None
DEBUG:    0.0 KoboTouch::open_osx - self._card_b_prefix= None
DEBUG:   14.3 KoboUtilities:_on_device_connection_changed - self.plugin_device_connection_changed.__class__:  <class 'PyQt6.QtCore.pyqtBoundSignal'>
DEBUG:   14.3 Methods for self.plugin_device_connection_changed:  ['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'connect', 'disconnect', 'emit', 'signal']
DEBUG:   14.3 Have a Kobo device connected connected
DEBUG:   14.3 BEGIN Get Device Path
DEBUG:   14.3 Root path of device: /Volumes/KOBOeReader/
DEBUG:   14.3 END Get Device Path
DEBUG:   14.3 KoboUtilities:get_device - self.device_path="/Volumes/KOBOeReader/"
DEBUG:   14.3 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:   14.3 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
DEBUG:   14.3 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouch'
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.1 KoboTouch:books - oncard='None'
DEBUG:    0.1 KoboTouch:books - oncard='None', prefix='/Volumes/KOBOeReader/'
DEBUG:    0.1 device_version_info - start
DEBUG:    0.1 device_version_info - version_file=/Volumes/KOBOeReader/.kobo/version
DEBUG:    0.1 device_version_info - have opened version_file
DEBUG:    0.1 device_version_info - self._device_version_info= ['N50629C045429', '4.1.15', '4.35.20400', '4.1.15', '4.1.15', '00000000-0000-0000-0000-000000000386']
DEBUG:    0.1 Kobo device: Kobo Clara 2E
DEBUG:    0.1 Version of driver: (2, 5, 1) Has kepubs: True
DEBUG:    0.1 Version of firmware: (4, 35, 20400) Has kepubs: True
DEBUG:    0.1 Firmware supports cover image tree: True
DEBUG:    0.1 KoboTouch:books - opts.extra_customization= []
DEBUG:    0.1 KoboTouch:books - driver options= Driver:KoboTouch, Options - format_map: ['kepub', 'epub', 'pdf', 'txt', 'cbz', 'cbr'], use_subdirs: True, read_metadata: True, use_author_sort: False, save_template: {author_sort}/{title} - {authors}, extra_customization: [], manage_collections: True, use_collections_columns: True, collections_columns: , use_collections_template: False, collections_template: , create_collections: False, delete_empty_collections: False, ignore_collections_names: , upload_covers: False, dithered_covers: False, keep_cover_aspect: False, upload_grayscale: False, letterbox_fs_covers: False, letterbox_fs_covers_color: #000000, png_covers: False, show_archived_books: False, show_previews: False, show_recommendations: False, update_series: True, update_core_metadata: False, update_purchased_kepubs: False, update_device_metadata: True, update_subtitle: False, subtitle_template: None, update_bookstats: False, bookstats_wordcount_template: None, bookstats_pagecount_template: None, bookstats_timetoread_upper_template: None, bookstats_timetoread_lower_template: None, modify_css: False, override_kobo_replace_existing: True, support_newer_firmware: False, debugging_title: , driver_version: 
DEBUG:    0.1 KoboTouch:books - prefs['manage_device_metadata']= manual
DEBUG:    0.1 KoboTouch:books - set_debugging_title to ''
DEBUG:    0.1 KoboTouch:books - length bl=0
DEBUG:    0.2 KoboTouch:books - length bl after sync=40
DEBUG:    0.2 KoboTouch:books - reading device database
DEBUG:    0.3 Database Version:  171
DEBUG:    0.3 KoboTouch:books - shelf list: ['ReadingList']
DEBUG:    0.3 KoboTouch:books - query= SELECT Title, Attribution, DateCreated, ContentID, MimeType, ContentType, ImageId, ReadStatus, Description, Publisher , ___ExpirationStatus, FavouritesIndex, Accessibility, Language, IsDownloaded, ISBN, Series, SeriesNumber, ___UserID, ExternalId, Subtitle, SeriesID, SeriesNumberFloat, StorePages, StoreWordCount, StoreTimeToReadLowerEstimate, StoreTimeToReadUpperEstimate FROM content  WHERE BookID IS NULL  AND ((Accessibility = -1 AND IsDownloaded in ('true', 1 ))       OR (Accessibility IN (1,2,8,9) and IsDownloaded in ('true', 1))         )  AND (externalId IS NULL OR externalId = '') AND contentId NOT LIKE 'file:///mnt/sd/%'
DEBUG:    0.4 KoboTouch:books - self.kobo_series_dict= {'Discworld': '9aed23ac-42be-5eac-9fbb-ffe826df84da', 'A Thursday Next Novel': '3083703b-e344-5978-a070-0c98267c33ad'}
DEBUG:    0.4 KoboTouch:books - about to sync_booklists
DEBUG:    0.4 USBMS: starting sync_booklists
DEBUG:    0.4 USBMS: finished sync_booklists
DEBUG:    0.4 KoboTouch:books - have done sync_booklists
DEBUG:    0.4 KoboTouch:books - end - oncard='None'
DEBUG:    0.4 KoboTouch:books - oncard='carda'
DEBUG:    0.4 KoboTouch:books - Asked to process 'carda', but do not have one!
DEBUG:    0.4 KoboTouch:books - oncard='cardb'
DEBUG:    0.4 KoboTouch:books - Asked to process 'cardb', but do not have one!
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 40
DeviceJob: set_books_in_library finished: time= 0.0009438991546630859
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DEBUG:   14.8 KoboUtilites:_on_device_metadata_available - Start
DEBUG:   14.8 Have a Kobo device connected connected
DEBUG:   14.8 BEGIN Get Device Path
DEBUG:   14.8 Root path of device: /Volumes/KOBOeReader/
DEBUG:   14.8 END Get Device Path
DEBUG:   14.8 KoboUtilities:get_device - self.device_path="/Volumes/KOBOeReader/"
DEBUG:   14.8 KoboUtilities:get_device - drive_info: {'main': {'device_store_uuid': 'c97c48de-21d3-4402-ad8e-95ca60c5863a', 'device_name': 'Kobo Clara 2E', 'location_code': 'main', 'last_library_uuid': None, 'calibre_version': '6.12.0', 'date_last_connected': '2023-02-11T04:55:04.835706+00:00', 'prefix': '/Volumes/KOBOeReader/'}}
DEBUG:   14.8 migrate_library_config_if_required - start
DEBUG:   14.8 get_library_config - library_config: `

**Comment by ZolaLa9** [comment]
You are using an old version of the plugin. You need [10.0.3](https://github.com/noDRM/DeDRM_tools) maintained by [noDRM](https://github.com/noDRM/DeDRM_tools).

See also: https://www.mobileread.com/forums/forumdisplay.php?f=166

And Mac specific info here: https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by dustinhuman** [comment]
> You are using an old version of the plugin. You need [10.0.3](https://github.com/noDRM/DeDRM_tools) maintained by [noDRM](https://github.com/noDRM/DeDRM_tools).
> 
> See also: https://www.mobileread.com/forums/forumdisplay.php?f=166
> 
> And Mac specific info here: https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

Thank you

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by dustinhuman** [comment]
Thanks
