### ISSUE TITLE
DeDRM not working for kindle in calibre Windows 10

### ISSUE THREAD

**Issue by bassoon1975** [apprenticeharper/DeDRM_tools#221]
I have been working on this all day.  Have removed Kindle PC registration and folders and then reinstalled and authorized.  Just won't work.  have active python 2.7.13 and pycrypto 2.6 installed.  This used to work like a dream on my windows 7 pc.  wondering if it is a windows 10 problem.

calibre Debug log
calibre 2.80 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.6884422111 x 81.6428571429
Starting up...
Started up in 31.55 seconds with 309 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x83\xc5\r\x8c\t\xcc\xf5e\x1eL\xa3\xdfC\xa0\xeeEDI\xd8n\x05&\xcdO<o\xae\x7f\x94\xdac\x9f', 'C:\\Users\\adrie\\OneDrive\\Documents\\My Kindle Content\\B01HEKF8S2_EBOK\\B01HEKF8S2_EBOK.azw']
DeDRM v6.5.3: Trying to decrypt B01HEKF8S2_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\adrie\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\adrie\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '586648630' and UserName '6164726965'
DeDRM v6.5.3: Found 1 new key
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 416, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 276, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 304, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B01HEKF8S2 EBOK to db in: 1.8
Added 1 books in 2.4 seconds

**Comment by ElleKayEm** [comment]
Kindle for PC version 1.19 downloading the KFX format is the problem, not Windows 10.  See the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

Uncheck auto-update before rolling back, and then double-check it's still unchecked with 1.17.

**Comment by bassoon1975** [comment]
Thank you!!  I had planned on installing all the old software downloads from when it was working on my windows 7 pc today.  It was the only logical choice to try next.  Glad that I only had to redo kindle.It's working now, thanks to you!
 -- Lorraine A. Maillet See "Adrienne's Garden" at http://www.epix.net/~adrienne 

    On Thursday, March 2, 2017 9:13 PM, ElleKayEm <notifications@github.com> wrote:
 

 Kindle for PC version 1.19 downloading the KFX format is the problem, not Windows 10. See the FAQs:https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-macUncheck auto-update before rolling back, and then double-check it's still unchecked with 1.17.—

**Comment by ElleKayEm** [comment]
Great!  Go ahead and close the issue.

**Comment by ajcrossland** [comment]
Fantastic! I had same problem with kindle for PC. Of course it would be great if the geniuses at github could get fix the problem with the KFX format but working fine now I've restored the old version. Thanks for all the hard work.

**Comment by fmw236** [comment]
Unable to use DeDRM to remove drm from .azw3 file. Here's the debug text. Please help.
calibre Debug log
calibre 3.13  embedded-python: True is64bit: False
Windows-10-10.0.17025-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17025')
Python 2.7.12+
Windows: ('10', '10.0.17025', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.13  embedded-python: True is64bit: False
Windows-10-10.0.17025-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17025')
Python 2.7.12+
Windows: ('10', '10.0.17025', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 94.1467181467 x 94.0740740741
Using calibre Qt style: True
Starting up...
Started up in 31.27 seconds with 1 books
DeDRM v6.5.5: Trying to decrypt The Best Songs Ever  Songbook.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Best Songs Ever  Songbook
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\FMW\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.5: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Best Songs Ever Songbook to db in: 2.4
Added 1 books in 5.3 seconds
Worker Launch took: 0.378999948502
Job: 1 Convert book 1 of 1 (The Best Songs Ever Songbook) finished
Convert book 1 of 1 (The Best Songs Ever Songbook)
	Conversion options changed from defaults:
	  input_profile: 'kindle'
	  read_metadata_from_opf: u'C:\\Users\\FMW\\AppData\\Local\\Temp\\calibre_5ecoug\\q4fxq3.opf'
	  verbose: 2
	  output_profile: 'kindle_fire'
	  cover: u'C:\\Users\\FMW\\AppData\\Local\\Temp\\calibre_5ecoug\\e5pzgb.jpeg'
	Resolved conversion options
	calibre version: 3.13.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\FMW\\AppData\\Local\\Temp\\calibre_5ecoug\\e5pzgb.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'docx_custom_page_size': None,
	 'docx_no_cover': False,
	 'docx_no_toc': False,
	 'docx_page_margin_bottom': 72.0,
	 'docx_page_margin_left': 72.0,
	 'docx_page_margin_right': 72.0,
	 'docx_page_margin_top': 72.0,
	 'docx_page_size': u'letter',
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.KindleInput object at 0x04A792D0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x04A795B0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\FMW\\AppData\\Local\\Temp\\calibre_5ecoug\\q4fxq3.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\FMW\AppData\Local\Temp\calibre_5ecoug\3fz_18.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  The Best Songs Ever  Songbook (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: The Best Songs Ever  Songbook

**Comment by ElleKayEm** [comment]
If you downloaded that from the website and chose an E-ink Kindle (not a Fire) for the device, then you need to put the Kindle's serial number into the plugin customization.

Otherwise, download it with Kindle for PC.  See this post for workarounds to avoid KFX format:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by fmw236** [comment]
Well, I'm not sure which machination corrected my issue, but after ensuring that Version 1.17 of Kindle for PC was installed, opening my target book in that application, removing all but one serial number for eInk books, and pointing to the file that opened in Kindle Reader for PC, the entire process worked like a charm. Not going to question anything unless more problems arise.
Thank you very much for your prompt reply. I appreciate it.
FMW
On 12/3/2017 6:03:01 PM, ElleKayEm <notifications@github.com> wrote:
If you downloaded that from the website and chose an E-ink Kindle (not a Fire) for the device, then you need to put the Kindle's serial number into the plugin customization.
Otherwise, download it with Kindle for PC. See this post for workarounds to avoid KFX format:
https://www.mobileread.com/forums/showthread.php?t=283371 [https://www.mobileread.com/forums/showthread.php?t=283371]
