### ISSUE TITLE
DeDRM not removing from PDF from ADE

### ISSUE THREAD

**Issue by ZeroWindows** [apprenticeharper/DeDRM_tools#2212]
My computer is an i7-8700K, GTX 1060, 32GB RAM. I got this ebook from though my university. 

[DRM not working.txt](https://github.com/apprenticeharper/DeDRM_tools/files/10820497/DRM.not.working.txt)

**Comment by ElleKayEm** [comment]
First, update to DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Next, delete your Adobe key and re-add the book letting DeDRM automatically retrieve the key.

**Comment by ZeroWindows** [comment]
> First, update to DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3
> 
> Next, delete your Adobe key and re-add the book letting DeDRM automatically retrieve the key.

Thank you! It works!
