### ISSUE TITLE
another Cannot convert purchased Amazon EBook

### ISSUE THREAD

**Issue by stefanoaltissimo** [apprenticeharper/DeDRM_tools#2218]
Thabnk you,
Stefano Altissimo

calibre Debug log
calibre 5.37  embedded-python: False is64bit: True
Linux-5.15.0-60-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-60-generic', '#66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023')
Python 3.10.6
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0) && KePub Input (3, 6, 3)
calibre 5.37  embedded-python: False is64bit: True
Linux-5.15.0-60-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-60-generic', '#66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023')
Python 3.10.6
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0) && KePub Input (3, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.15759312320917 x 93.06870229007633
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.03] splash screen shown
[0.03] Initializing db...
[0.03] db initialized
[0.03] Constructing main UI...
[0.30] main UI initialized...
[0.30] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.51.0: Importing /home/stefano/Calibre Library/Docker_ Sviluppare e rilasciare software tramite container_B08KJBMRH1.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as /tmp/calibre_5.37.0_tmp_rqjryiad/huwksqqd.kfx-zip
DeDRM v7.2.1: Trying to decrypt huwksqqd.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 18, in <module>
    from ion import DrmIon, DrmIonVoucher
  File "/tmp/calibre_5.37.0_tmp_rqjryiad/44mrv212plugin_unzip/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 527, in KindleMobiDecrypt
    import calibre_plugins.dedrm.k4mobidedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
    from calibre_plugins.dedrm import kfxdedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.kfxdedrm", line 20, in <module>
    from calibre_plugins.dedrm.ion import DrmIon, DrmIonVoucher
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.ion", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
Package KFX (from KFX Input) 1.51.0: Packaging /tmp/calibre_5.37.0_tmp_rqjryiad/huwksqqd.kfx-zip
Processing container: Docker_ Sviluppare e rilasciare software tramite container_B08KJBMRH1.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Docker_ Sviluppare e rilasciare software tramite container_B08KJBMRH1.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /tmp/calibre_5.37.0_tmp_rqjryiad/bq879hp9_add_books/0/Docker_ Sviluppare e rilasciare software tramite container_B08KJBMRH1.kfx-zip
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 432, in get_file_type_metadata
    mi = plugin.get_metadata(stream, ftype.lower().strip())
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
    md = YJ_Book(stream).get_metadata()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
    raise Exception("Failed to locate a KFX container with metadata")
Exception: Failed to locate a KFX container with metadata
[2.34] splash screen hidden
[2.34] Started up in 2.34 seconds with 1 books

Found device nodes: /dev/sdb None None
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /media/stefano/Kindle/ documents
DEBUG:    0.0 USBMS: scan from root False /media/stefano/Kindle/documents
DEBUG:    0.0 USBMS: count found in cache: 3, count of files in metadata: 3, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 3
DeviceJob: set_books_in_library finished: time= 0.013106107711791992
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Added Docker Sviluppare e rilasciare software tramite container B08KJBMRH1 to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by ElleKayEm** [comment]
See this post for getting books you can decrypt: https://www.mobileread.com/forums/showthread.php?t=283371

You may want to switch to the official Linux calibre and update to DeDRM 10.0.3.

**Comment by stefanoaltissimo** [comment]
Thank you very much. Anyway (for other people with the same issue) , it was not clear to me i had to fill the serial number in the plugin configuration. Thank you again.
