### ISSUE TITLE
DMR not being removed in calibre on mac using DeDRM_Tools 6.5.3

### ISSUE THREAD

**Issue by reata100** [apprenticeharper/DeDRM_tools#222]
I installed DeDRM_Tools 6.5.3 for calibre on a mac, linked my kindle serial number and imported .azw3 books I downloaded from the amazon manage your devices/download and transfer via usb feature. However the DRM is not being removed. Is there something I'm doing wrong? 

I was previously using DeDRM_Tools 6.0.8 with no problems until the latest update from kindle.

Cheers

**Comment by ElleKayEm** [comment]
As long as the device is an E-ink Kindle and you're downloading the file for that Kindle, then you should be good.  Double-check you have the serial number entered into calibre correctly.  Try copying it from the Manage Your Devices page -- removing any spaces.

**Comment by vimy100** [comment]
I have had the same problem but not with all books.  I have used DeDRM_Tools 6.5.3 with Calibre 2.80.0 in Windows 10 and have successfully removed DRM from several books but two failed in the attempt.  Here are the job details from one of them (I am assuming this is the import log?)

Convert book 1 of 1 (Our Crime Was Being Jewish: Hundreds of Holocaust Survivors Tell Their Stories)
Conversion options changed from defaults:
  sr3_search: None
  cover: u'C:\\Users\\VDH\\AppData\\Local\\Temp\\calibre_830qys\\ctwyrk.jpeg'
  sr3_replace: None
  sr1_search: None
  output_profile: 'nook_color'
  search_replace: '[]'
  sr1_replace: None
  transform_css_rules: '[]'
  sr2_search: None
  filter_css: u''
  sr2_replace: None
  read_metadata_from_opf: u'C:\\Users\\VDH\\AppData\\Local\\Temp\\calibre_830qys\\oupmqs.opf'
  verbose: 2
Resolved conversion options
calibre version: 2.80.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\VDH\\AppData\\Local\\Temp\\calibre_830qys\\ctwyrk.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x045CFF10>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.NookColorOutput object at 0x0451D3D0>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\VDH\\AppData\\Local\\Temp\\calibre_830qys\\oupmqs.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\VDH\AppData\Local\Temp\calibre_830qys\lxwa6x.azw3
Found KF8 MOBI of type 'standalone'
Python function terminated unexpectedly
  Our Crime Was Being Jewish: Hundreds of Holocaust Survivors Tell Their Stories (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 132, in main
  File "site.py", line 109, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1074, in run
  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
calibre.ebooks.DRMError: Our Crime Was Being Jewish: Hundreds of Holocaust Survivors Tell Their Stories

**Comment by reata100** [comment]
EllyKayEm my kindle is a Kindle Paperwhite 3G - is that different to an E-ink Kindle? The serial number was entered correctly. I have not been able to successfully remove DRM on any books.

**Comment by ElleKayEm** [comment]
@vimy100 
No, we need to see a log from when you first add the book to calibre.  See the [FAQs](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that) and post the log in a new issue.

**Comment by ElleKayEm** [comment]
@reata100 
Yes, that's an E-ink Kindle.  If you tried copying the serial number from the Manage Your Devices page and it still didn't work, then post an import log.

**Comment by reata100** [comment]
OK I figured out what the issue was. I had replaced the latest version of Kindle for the older v1.17.1 but I hadn't deleted the versions of the books that had been downloaded using the newer version. ie those that had a individual folder for each book. Once I deleted those and re-downloaded the books I was able to open them fine in calibre.

**Comment by ElleKayEm** [comment]
Ok, you were originally talking about downloading from the website -- not with Kindle for PC/Mac.  Go ahead and close this issue.
