### ISSUE TITLE
"This book has DRM - Cannot convert"

### ISSUE THREAD

**Issue by darkspark71** [apprenticeharper/DeDRM_tools#2220]
I have followed the instructions given on https://www.youtube.com/watch?v=SK5m3TRTO_Y webpage to the letter but am unable to get the DeDRM to convert a book (from AZM3 to EPUB). My desktop PC OS is Windows 10 and the e-book was downloaded via usb from the list of books in my Amazon account. I have attached the log file that was generated by Calibre in de-bug mode (sorry it's rather lengthy).
Any help/assistance would be greatly appreciated.

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.14  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 6.14  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 89.20975609756097 x 89.296875
[0.00] Starting up...
[0.00] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.88] db initialized
[0.88] Constructing main UI...
[2.53] main UI initialized...
[2.53] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Life Swap.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
[26.84] splash screen hidden
[26.84] Started up in 26.84 seconds with 4997 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xbe\x86C\xbb\xbf\xf3"\xd0\xa7\x86y\xbb\xddD\x90\xddLuU7\xb3jJ\x0f4\xe5\x08!\xc0g\xb8\xbe', b'C:\\Users\\Brian\\Downloads\\Brian Temp\\Kindle Project\\Life Swap.azw3']
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Life Swap
Found 2 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Brian\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Brian\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3738604237' and UserName 'Brian'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Life Swap
Got DSN key from database default_key_1
Found 4 keys to try after 6.4 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 6.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 6.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Life Swap to db in: 1.8
Added 1 books in 9.2 seconds
Worker Launch took: 0.09 seconds
Job: 0 Convert book 1 of 1 (Life Swap) finished
Convert book 1 of 1 (Life Swap)

	DeDRM v7.2.1: Trying to decrypt d9zf0_t4.azw3
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Life Swap
	Found 2 keys to try after 0.2 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
	searching for kinfoFiles in C:\Users\Brian\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Brian\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '3738604237' and UserName 'Brian'
	DeDRM v7.2.1: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Life Swap
	Got DSN key from database default_key_1
	Found 4 keys to try after 6.5 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Ultimately failed to decrypt after 6.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 6.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	Conversion options changed from defaults:

	  read_metadata_from_opf: 'C:\\Users\\Brian\\AppData\\Local\\Temp\\calibre_ssodkeot\\5rm78_eb.opf'

	  input_profile: 'kindle'

	  cover: 'C:\\Users\\Brian\\AppData\\Local\\Temp\\calibre_ssodkeot\\kjewwwxh.jpeg'

	  verbose: 2

	Resolved conversion options

	calibre version: 6.14.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\Brian\\AppData\\Local\\Temp\\calibre_ssodkeot\\kjewwwxh.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.KindleInput object at 0x0000017D96C2A380>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x0000017D96C2A1D0>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Brian\\AppData\\Local\\Temp\\calibre_ssodkeot\\5rm78_eb.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	DeDRM v7.2.1: Trying to decrypt d9zf0_t4.azw3
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Life Swap
	Found 2 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Brian\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Brian\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '3738604237' and UserName 'Brian'
	DeDRM v7.2.1: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Life Swap
	Got DSN key from database default_key_1
	Found 4 keys to try after 6.4 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Ultimately failed to decrypt after 6.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 6.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\Brian\AppData\Local\Temp\calibre_ssodkeot\d9zf0_t4.azw3

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 196, in _run_module_as_main

	  File "runpy.py", line 86, in _run_code

	  File "site.py", line 83, in <module>

	  File "site.py", line 78, in main

	  File "site.py", line 50, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 242, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 85, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm

	calibre.ebooks.DRMError: Life Swap

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by darkspark71** [comment]
That didn't work either. Also I looked to see which plug-ins are installed and it appears there are none?? (see attachment). Unable to send another log file (can't remember where it was located and Search facility doesn't find it either)
![Blank Plugin](https://user-images.githubusercontent.com/128978562/227917081-a21d95b2-9462-4bd6-8e8a-f13edf6b2b14.JPG)

**Comment by ElleKayEm** [comment]
DeDRM won't be listed there since you have to load it from the file.  Here's how to get a log: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by darkspark71** [comment]
Still won't work (I have checked and the DeDRM is definitely in Calibre). Followed your last instructions and generated a log-file:-
 
[tmp11hjwm3e.txt](https://github.com/apprenticeharper/DeDRM_tools/files/11088691/tmp11hjwm3e.txt)

**Comment by ElleKayEm** [comment]
Did you chose an E-ink Kindle (not a Fire) when downloading the book from the website?  Be sure you have the serial number entered into DeDRM correctly.  Copy and paste from the website.

**Comment by darkspark71** [comment]
The e-book was "downloaded via usb from the list of books" from the website and I have used my Fire serial number (didn't know I was not supposed to).  I do have access to another Kindle (8th Gen). What's the best way to proceed now?

**Comment by ElleKayEm** [comment]
That's the problem.  This method does not work for Fires -- only Kindle ereaders.  Download a new copy of the book and this time choose the E-ink Kindle for the device.  Put its serial number into DeDRM and restart calibre before adding the new copy of the book.

**Comment by darkspark71** [comment]
If I use that method, how do I take it from the E-ink Kindle and place it into Calibre?

**Comment by darkspark71** [comment]
Sorry I clicked on the wrong button.

**Comment by ElleKayEm** [comment]
You download the book from the website, but instead of choosing the Fire, you choose the E-ink Kindle when asked which device.

**Comment by darkspark71** [comment]
I followed your instruction :- "Download a new copy of the book and this time choose the E-ink Kindle for the device. Put its serial number into DeDRM and restart calibre before adding the new copy of the book". Now the new book is loaded to a Kindle 8th Gen but if I try to open it in Calibre it shows the book format as B002RUA4IE.kfx and can't open it.

**Comment by ElleKayEm** [comment]
Don't get the book from the Kindle itself.  Download the book from the website to your computer with the "download & transfer" option.

**Comment by darkspark71** [comment]
Now it works, does that mean I can now put the converted book (from AZW to EPUB) on to any of my Kindles because the DRM has been removed?

**Comment by ElleKayEm** [comment]
DRM is removed by DeDRM when you add the book to calibre.  So the AZW3 will work on any Kindle.  The EPUB will work on ereaders or apps that use that format.

**Comment by darkspark71** [comment]
Just loaded it onto an old kindle of mine and it worked a treat.
Just wanted to thank you for your patience/guidance and time that you spent helping a silver surfer.
Thanks again ElleKayEm

**Comment by lockieluke** [comment]
Many books like [this one](https://www.amazon.co.uk/Biology-Complete-Revision-Practice-Online/dp/1782945830) no longer allows downloading onto a Kindle, DRM removal would not work.  I had done this before with this very book but it just doesn’t work anymore.

**if buying isn’t owning, finding ways to circumvent this is not piracy**, I just want to use the book in Goodnotes on my iPad

**Comment by ElleKayEm** [comment]
You should be able to decrypt that downloaded to Kindle for PC.

**Comment by Esco54** [comment]
> E-ink Kindle

Can you please help me with the same problem? I have just downoladed a book into my computer and tried calibre to translate it. But is says DRM is not letting you use this book? Thank you.

**Comment by ElleKayEm** [comment]
@Esco54
If you downloaded it from the website for an E-ink Kindle, then you just need to have that Kindle's serial number entered into DeDRM's customization.

**Comment by Esco54** [comment]
Hello,did manage to fix it but how can we translate the book without the original text as result? Need only the translated content, not the original language. Thank you

Kurt

Van: ElleKayEm ***@***.***>
Verzonden: zaterdag 2 november 2024 20:11
Aan: apprenticeharper/DeDRM_tools ***@***.***>
CC: Esco54 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [apprenticeharper/DeDRM_tools] "This book has DRM - Cannot convert" (Issue #2220)


@Esco54<https://github.com/Esco54>
If you downloaded it from the website for an E-ink Kindle, then you just need to have that Kindle's serial number entered into DeDRM's customization.

**Comment by ElleKayEm** [comment]
I've got no advice for whatever you want to do after the DRM is removed!
