### ISSUE TITLE
not work on both Mac and Win

### ISSUE THREAD

**Issue by nmuser0** [apprenticeharper/DeDRM_tools#223]
I would greatly appreciate your help with DeDRM_tools-6.5.3. 

First I used Kindle 1.19 before reading that DeDRM does not work on 1.19. Then I tried Kindle 1.17 and 1.16, and I tried different Kindle accounts, but the same failure happened:

On Win7, using DeDRM_Drop_Target, it says: "Successes: 0, Failures: 1". 
On Mac OS 10.11.6, DeDRM.app did not work, and DeDRM.log is empty.
On both Win7 and Mac, using plug-in for calibre, the calibre viewer cannot open the imported book because the DRM is still there.

These are the two books I used in my experiment ("eTextbook free 7-day trial"):
https://www.amazon.com/Social-Animal-Elliot-Aronson/dp/1429233419/
https://www.amazon.com/Readings-Social-Animal-Joshua-Aronson/dp/1429233427/

Please help me.  Thanks!

**Comment by ElleKayEm** [comment]
These tools do not work on free trial or rental books.

**Comment by nmuser0** [comment]
Thanks. Are there any tools that work on free trial or rental books? Thanks.

**Comment by ElleKayEm** [comment]
If you want to remove DRM, then you should buy the book.

**Comment by apprenticeharper** [comment]
There are plenty of free to buy but DRMed ebooks on Amazon. Try with one of them.
