### ISSUE TITLE
Unable to decrypt azw files.

### ISSUE THREAD

**Issue by blackcat1313** [apprenticeharper/DeDRM_tools#2232]
Greetings. I'm use calibre with the plugin. I can read the book fine, but it won't decrypt. I have added the serial key for the device. I'm getting the following message.

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.17  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
calibre 6.17  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 94.06726943942132 x 94.08617363344051
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[0.75] main UI initialized...
[0.75] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.51.0: Importing C:/Users/J.R. Pseudonym/Downloads/Travellers Book 1 - The Epsilon Queen.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt Travellers Book 1 - The Epsilon Queen.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Travellers Book 1: - The Epsilon Queen
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\J.R. Pseudonym\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[3.89] splash screen hidden
[3.89] Started up in 3.89 seconds with 87 books
Added Travellers Book 1: - The Epsilon Queen to db in: 0.1
Added 1 books in 0.6 seconds
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (Travellers Book 1: - The Epsilon Queen) finished
Convert book 1 of 1 (Travellers Book 1: - The Epsilon Queen)

	DeDRM v7.2.1: Trying to decrypt x_wsesfa.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 6 ebook: Travellers Book 1: - The Epsilon Queen
	Found 2 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\J.R. Pseudonym\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	Conversion options changed from defaults:

	  cover: 'C:\\Users\\JR570B~1.PSE\\AppData\\Local\\Temp\\calibre__g1e89ph\\w865jse0.jpeg'

	  output_profile: 'kindle_pw3'

	  read_metadata_from_opf: 'C:\\Users\\JR570B~1.PSE\\AppData\\Local\\Temp\\calibre__g1e89ph\\_8vzwcy7.opf'

	  verbose: 2

	Resolved conversion options

	calibre version: 6.17.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\JR570B~1.PSE\\AppData\\Local\\Temp\\calibre__g1e89ph\\w865jse0.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_compress': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000028AFEEFF550>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'mobi_file_type': 'old',

	 'mobi_ignore_margins': False,

	 'mobi_keep_original_images': False,

	 'mobi_toc_at_start': False,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': True,

	 'no_inline_toc': False,

	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x0000028AFEEFFB50>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'personal_doc': '[PDOC]',

	 'prefer_author_sort': False,

	 'prefer_metadata_cover': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\JR570B~1.PSE\\AppData\\Local\\Temp\\calibre__g1e89ph\\_8vzwcy7.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'share_not_sync': False,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	DeDRM v7.2.1: Trying to decrypt x_wsesfa.azw
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 6 ebook: Travellers Book 1: - The Epsilon Queen
	Found 2 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\J.R. Pseudonym\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\JR570B~1.PSE\AppData\Local\Temp\calibre__g1e89ph\x_wsesfa.azw

	Traceback (most recent call last):

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 30, in convert

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 166, in extract_content

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm

	calibre.ebooks.DRMError: Travellers Book 1: - The Epsilon Queen

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "runpy.py", line 196, in _run_module_as_main

	  File "runpy.py", line 86, in _run_code

	  File "site.py", line 83, in <module>

	  File "site.py", line 78, in main

	  File "site.py", line 50, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 242, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 166, in extract_content

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm

	calibre.ebooks.DRMError: Travellers Book 1: - The Epsilon Queen

**Comment by ElleKayEm** [comment]
For calibre 6, update to DeDRM 10.0.3:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by blackcat1313** [comment]
Thank you for your reply, but the problem is still happening.

**Comment by ElleKayEm** [comment]
Make sure you have the serial number entered correctly.  Copy and paste from the website.

**Comment by ElleKayEm** [comment]
Is it an E-ink Kindle, not a Fire?

**Comment by blackcat1313** [comment]
It is a paperwhite model, so yes, it is e-ink. And yes, the serial number is entered correctly.

**Comment by ElleKayEm** [comment]
Let's see the log using DeDRM 10.0.3.

**Comment by blackcat1313** [comment]
Of course, my apologies.

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.17  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0) && Obok DeDRM (10, 0, 3)
calibre 6.17  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 94.06726943942132 x 94.08617363344051
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.81] main UI initialized...
[0.81] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.51.0: Importing C:/Users/J.R. Pseudonym/Desktop/Junk/Travellers Book 1 - The Epsilon Queen.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v10.0.3: Trying to decrypt Travellers Book 1 - The Epsilon Queen.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Travellers Book 1: - The Epsilon Queen
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\J.R. Pseudonym\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\J.R. Pseudonym\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\J.R. Pseudonym\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[5.70] splash screen hidden
[5.70] Started up in 5.70 seconds with 87 books
Added Travellers Book 1: - The Epsilon Queen to db in: 0.1
Added 1 books in 0.6 seconds
Worker Launch took: 0.01 seconds
Job: 0 Convert book 1 of 1 (Travellers Book 1: - The Epsilon Queen) finished
Convert book 1 of 1 (Travellers Book 1: - The Epsilon Queen)

	DeDRM v10.0.3: Trying to decrypt d3nj6h7y.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.1.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 6 ebook: Travellers Book 1: - The Epsilon Queen
	Found 2 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\J.R. Pseudonym\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt

	  File "C:\Users\J.R. Pseudonym\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook

	  File "C:\Users\J.R. Pseudonym\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook

	mobidedrm.DrmException: No key found in 2 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1056, in run

	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	Conversion options changed from defaults:

	  output_profile: 'kindle_pw3'

	  read_metadata_from_opf: 'C:\\Users\\JR570B~1.PSE\\AppData\\Local\\Temp\\calibre_jivfatqc\\f9ema7n7.opf'

	  verbose: 2

	  cover: 'C:\\Users\\JR570B~1.PSE\\AppData\\Local\\Temp\\calibre_jivfatqc\\sswvu14b.jpeg'

	Resolved conversion options

	calibre version: 6.17.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\JR570B~1.PSE\\AppData\\Local\\Temp\\calibre_jivfatqc\\sswvu14b.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_max_image_size': 'none',

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001C4434183A0>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x000001C443419F30>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\JR570B~1.PSE\\AppData\\Local\\Temp\\calibre_jivfatqc\\f9ema7n7.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	DeDRM v10.0.3: Trying to decrypt d3nj6h7y.azw
	MobiDeDrm v1.1.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 6 ebook: Travellers Book 1: - The Epsilon Queen
	Found 2 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\J.R. Pseudonym\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt

	  File "C:\Users\J.R. Pseudonym\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook

	  File "C:\Users\J.R. Pseudonym\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook

	mobidedrm.DrmException: No key found in 2 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1056, in run

	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\JR570B~1.PSE\AppData\Local\Temp\calibre_jivfatqc\d3nj6h7y.azw

	Traceback (most recent call last):

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 30, in convert

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 166, in extract_content

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm

	calibre.ebooks.DRMError: Travellers Book 1: - The Epsilon Queen

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "runpy.py", line 196, in _run_module_as_main

	  File "runpy.py", line 86, in _run_code

	  File "site.py", line 83, in <module>

	  File "site.py", line 78, in main

	  File "site.py", line 50, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 242, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 166, in extract_content

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm

	calibre.ebooks.DRMError: Travellers Book 1: - The Epsilon Queen

**Comment by ElleKayEm** [comment]
The key you have in there doesn't appear to be the right one for this copy of the book.  Did you use download & transfer from the website?  Are you sure you chose your E-ink Kindle?  And did you copy paste the serial number from the website?

**Comment by blackcat1313** [comment]
Bam, THAT solved it. Thank you so much. I had typed in the key from the kindle white itself. Not from the amazon website. Works lovely, again thank you for the help. you can close the issue.

**Comment by ElleKayEm** [comment]
It's easy to mix up 0 for O and other things when trying to read it from the Kindle.  As the person who opened the issue, you're the one who can close it.
