### ISSUE TITLE
On some Kindle for PC books DeDRM won't remove DRM

### ISSUE THREAD

**Issue by vimy100** [apprenticeharper/DeDRM_tools#224]
@ElleKayEm  as per my previous post on #222 

I have used DeDRM_Tools 6.5.3 with Calibre 2.80.0 in Windows 10 and have successfully removed DRM from several books but two failed in the attempt. Here is the import log from one of them:

calibre Debug log
calibre 2.80  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Kindle and Mobipocket DeDRM (0, 4, 19)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.664921466 x 127.590697674
Starting up...
Started up in 96.35 seconds with 4736 books
DeDRM v6.5.3: Trying to decrypt Our Crime Was Being Jewish_ Hundreds of Holocaust Survivors Tell Their Stories.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Our Crime Was Being Jewish: Hundreds of Holocaust Survivors Tell Their Stories
Found 4 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\VDH\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\VDH\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3292484050' and UserName '564448'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Our Crime Was Being Jewish: Hundreds of Holocaust Survivors Tell Their Stories
Found 4 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.7 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.7 seconds
Kindle and Mobipocket DeDRM v0.4.19: Trying to decrypt Our Crime Was Being Jewish_ Hundreds of Holocaust Survivors Tell Their Stories.azw3.
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin Kindle and Mobipocket DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.k4mobidedrm.__init__", line 122, in run
  File "calibre_plugins.k4mobidedrm.__init__", line 255, in config
  File "site-packages\calibre\customize\zipplugin.py", line 183, in load_module
  File "calibre_plugins.k4mobidedrm.config", line 4, in <module>
ImportError: No module named PyQt4.Qt
Added Our Crime Was Being Jewish: Hundreds of Holocaust Survivors Tell Their Stories to db in: 2.0
Added 1 books in 4.5 seconds

**Comment by ElleKayEm** [comment]
First remove the Kindle and Mobipocket DeDRM plugin.  If this book is from or for an E-ink Kindle (not a Fire), then make sure you have the serial number entered correctly.  Otherwise, make sure you have version 1.17 or earlier of Kindle for PC and import a copy from there.

**Comment by vimy100** [comment]
I assume I must uninstall Kindle for PC 1.19 before installing 1.17.  Do I have to deregister Kindle for PC before I uninstall 1.19?

**Comment by vimy100** [comment]
Not to worry @ElleKayEm ~ I found directions in the FAQ.  Thanks for your help.  I'll cose the thread once I get it all working :-).

**Comment by vimy100** [comment]
@ElleKayEm  Sorry, I read those directions on another site, I just realized, and they don't make clear how to actual proceed.  They say uncheck auto-install in 1.19 and then remove and install 1.17 but don't address that idea of de-registering / re-registering.  Is it necessary to address registration at all?

**Comment by ElleKayEm** [comment]
No problem.  Hopefully you're all set, but let us know if you have any other questions.

**Comment by vimy100** [comment]
@ElleKayEm ~ Good, I've used it several times now and all works fine.  

The main reason I want to get my books into Calibre is simply for organizational purposes.  I have more than 3,000 bought and paid for and the Calibre tagging system makes them accessible and easy to browse.  Wonderful.  I also share the concern that others have expressed that my collection is not really safe while it's existence remains subject to Amazon's policies, technical decisions/developments and their business success.  Really appreciate the work done on Calibre and the help folks such as yourself provide.  Thanks, again.

I will close the issue shortly.

**Comment by vimy100** [comment]
P.S. ~ For anyone else looking to do this there are detailed instructions for folks as challenged as I am here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by ElleKayEm** [comment]
That is a good link for info on avoiding the KFX format.  MobileRead is great resource for all kinds of ebook info -- except DRM removal.  It's against their policy to go into detail about that.  They'll just tell you to come here or Alf's blog.
