### ISSUE TITLE
Issues with Kindle import ("KFX format detected")

### ISSUE THREAD

**Issue by letterino** [apprenticeharper/DeDRM_tools#225]
Hi, I've tried importing two Kindle books in Calibre. Here's the error log: 

> calibre Log di debug
> calibre 2.80 [64bit]  embedded-python: True is64bit: True
> Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
> ('Windows', '7', '6.1.7601')
> Python 2.7.9
> Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
> Successfully initialized third party plugins: DeDRM (6, 5, 3)
> devicePixelRatio: 1.0
> logicalDpi: 96.0 x 96.0
> physicalDpi: 72.035450517 x 72.0
> Starting up...
> Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
> Started up in 9.46 seconds with 381 books
> DeDRM v6.5.3: Trying to decrypt B00QFGQFO8_EBOK.azw
> Using Library AlfCrypto DLL/DYLIB/SO
> DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
> DeDRM v6.5.3: Looking for new default Kindle Key after 0.3 seconds
> searching for kinfoFiles in E:\Users\Francesco U\AppData\Local
> Found K4PC 1.9+ kinf2011 file: E:\Users\Francesco U\AppData\Local\Amazon\Kindle\storage\.kinf2011
> Decrypted key file using IDString '337958432' and UserName '4672616e636573636f2055'
> DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds.
> Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
> Running file type plugin DeDRM failed with traceback:
> Traceback (most recent call last):
>   File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
>   File "calibre_plugins.dedrm.__init__", line 610, in run
>   File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
> DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds
> Traceback (most recent call last):
>   File "site-packages\calibre\customize\ui.py", line 416, in get_file_type_metadata
>   File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
>   File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
>   File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 276, in __init__
>   File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 304, in identity
> MobiError: Unknown book type: ÄÞ|Œ"
> Added B00QFGQFO8 EBOK to db in: 1.8
> Added 1 books in 3.9 seconds
> DeDRM v6.5.3: Trying to decrypt B01F759TAO_EBOK.azw
> Using Library AlfCrypto DLL/DYLIB/SO
> DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
> DeDRM v6.5.3: Looking for new default Kindle Key after 0.2 seconds
> searching for kinfoFiles in E:\Users\Francesco U\AppData\Local
> Found K4PC 1.9+ kinf2011 file: E:\Users\Francesco U\AppData\Local\Amazon\Kindle\storage\.kinf2011
> Decrypted key file using IDString '337958432' and UserName '4672616e636573636f2055'
> DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds.
> Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
> Running file type plugin DeDRM failed with traceback:
> Traceback (most recent call last):
>   File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
>   File "calibre_plugins.dedrm.__init__", line 610, in run
>   File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
> DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds
> Traceback (most recent call last):
>   File "site-packages\calibre\customize\ui.py", line 416, in get_file_type_metadata
>   File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
>   File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
>   File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 276, in __init__
>   File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 304, in identity
> MobiError: Unknown book type: ÄÞ|Œ"
> Added B01F759TAO EBOK to db in: 1.4
> Added 1 books in 3.4 seconds

There's also a character encoding issue in the log, here's how I see it:
![image](https://cloud.githubusercontent.com/assets/26205667/23590317/98ed7e60-01dd-11e7-9473-b592994fde27.png)

Thanks!

**Comment by ElleKayEm** [comment]
See the FAQs:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

Be sure to uncheck auto-updates.

**Comment by letterino** [comment]
Thanks a lot. I thought I read thoroughly the faq but apparently I started from the troubleshooting section and missed that bit.

**Comment by ElleKayEm** [comment]
No problem.  Go ahead and close this issue when you know you've got it working.

**Comment by letterino** [comment]
Worked like charm, wonderful! Thanks again!
