### ISSUE TITLE
DeDRM not working

### ISSUE THREAD

**Issue by kanjishinoda** [apprenticeharper/DeDRM_tools#2250]
I bought my ebook from Kobo.

my pc:

Edition	Windows 11 Home
Version	22H2
Installed on	‎3/‎6/‎2023
OS build	22621.1992
Experience	Windows Feature Experience Pack 1000.22644.1000.0

Processor	Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz   2.90 GHz
Installed RAM	8.00 GB (7.83 GB usable)

System type	64-bit operating system, x64-based processor

The following debug comes out:

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.23  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 6.23  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.73814898419865 x 91.80722891566265
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[0.62] main UI initialized...
[0.62] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Introduction to Microcontroller Programming for Power Electronic.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Introduction to Microcontroller Programming for Power Electronic.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.5 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.5 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 358, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 393, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Could not locate privateLicenseKey
DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[11.17] splash screen hidden
[11.17] Started up in 11.17 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x05c\x8b\x8ea\x99\xbcL\xf3\x9e,\x8bwre\xbd\x9c\x16\xb5\xb0\xa3h\xf2\x8endt\xf1Y\xbd\x8a\xdc', b'E:\\Introduction to Microcontroller Programming for Power Electronic.epub']
Added Introduction to Microcontroller Programming for Power Electronics Control Applications: Coding with MATLAB® and Simulink® to db in: 1.4
Exception ignored in: <function NativeFunction.__del__ at 0x0000022C43D6DA20>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x0000022C43D6DA20>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ElleKayEm** [comment]
With calibre 6, use DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by kanjishinoda** [comment]
I redo with 10.0.3, it is same. I will redo remove 7.0.2 and retry

**Comment by ElleKayEm** [comment]
Is ADE used to download this book on the same machine and user as calibre/DeDRM?

**Comment by kanjishinoda** [comment]
> Is ADE used to download this book on the same machine and user as calibre/DeDRM?

Yes. ADE from other device. I just copied epub file to calibre PC.
now it works. I installed kobo desktop app at the same pc as caliber. Then import to calibre from okob plugin. This can dedrm straight to pdf.

**Comment by ElleKayEm** [comment]
> ADE from other device. I just copied epub file to calibre PC.

DeDRM can't retrieve the key in that case.

If you're all set you can close the issue.

**Comment by kanjishinoda** [comment]
thanks
