### ISSUE TITLE
Can't open DRM protected book from BOKUS

### ISSUE THREAD

**Issue by Delli369** [apprenticeharper/DeDRM_tools#2252]
## Log
<details><summary>Log Title</summary>

```log
Using calibre Qt style: True
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
Traceback (most recent call last):
  File "calibre/gui2/ui.py", line 181, in load_store_plugins
  File "calibre/gui2/ui.py", line 193, in init_istore
  File "calibre/customize/__init__.py", line 743, in load_actual_plugin
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.lbschenkel_store_bokus_se.bokus", line 23, in <module>
    from calibre_plugins.lbschenkel_store_bokus_se.lib import GenericStore, xpath, text
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.lbschenkel_store_bokus_se.lib.__init__", line 11, in <module>
    from urlparse import urljoin
ModuleNotFoundError: No module named 'urlparse'
2023-07-23 23:58:51.467 calibre-debug[1646:130036] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2023-07-23 23:58:51.467 calibre-debug[1646:130036] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2023-07-23 23:58:51.467 calibre-debug[1646:130036] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2023-07-23 23:58:51.468 calibre-debug[1646:130036] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2023-07-23 23:58:51.468 calibre-debug[1646:130036] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2023-07-23 23:58:51.468 calibre-debug[1646:130036] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
calibre Debug log
calibre 6.23  embedded-python: True
macOS-13.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: Bokus (0, 1, 0)
calibre 6.23  embedded-python: True
macOS-13.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: Bokus (0, 1, 0)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485792 x 127.50000191485789
[0.00] Starting up...
[0.03] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.51] main UI initialized...
[0.51] Hiding splash screen
Starting QuickView
[27.86] splash screen hidden
[27.86] Started up in 27.86 seconds with 1 books
Added Lenobia's Vow to db in: 0.0
Added 1 books in 0.2 seconds
```
</details>

**Comment by ElleKayEm** [comment]
You don't have DeDRM installed.  Does Bokus use Adobe DRM?

**Comment by Delli369** [comment]
Hey!

I am sorry for the late response! Thank you so much fot taking your time to help me!!! 😁 I truly appreciate it!

Yes Bokus uses Adobe DRM. Are you sure? I did install the plugins, there were even plugins for specifically Bokus.

Best Wishes,
Lejla
________________________________
Från: ElleKayEm ***@***.***>
Skickat: den 24 juli 2023 00:34
Till: apprenticeharper/DeDRM_tools ***@***.***>
Kopia: Delli369 ***@***.***>; Author ***@***.***>
Ämne: Re: [apprenticeharper/DeDRM_tools] Can't open DRM protected book from BOKUS (Issue #2252)


You don't have DeDRM installed. Does Bokus use Adobe DRM?

**Comment by ElleKayEm** [comment]
The log only shows the Bokus plugin which has nothing to do with DRM removal.  For calibre 6, install DeDRM 10.0.3:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by Delli369** [comment]
I can´t find the one according to the instructions.

Best Wishes,
Lejla
________________________________
Från: ElleKayEm ***@***.***>
Skickat: den 29 juli 2023 12:30
Till: apprenticeharper/DeDRM_tools ***@***.***>
Kopia: Delli369 ***@***.***>; Author ***@***.***>
Ämne: Re: [apprenticeharper/DeDRM_tools] Can't open DRM protected book from BOKUS (Issue #2252)


The log only shows the Bokus plugin which has nothing to do with DRM removal. For calibre 6, install DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by ElleKayEm** [comment]
I gave a link to DeDRM 10.0.3.  Download the first file there under Assets.  Unzip it and load DeDRM_plugin.zip into calibre.

**Comment by Delli369** [comment]
Hey again!

It was exactly what I did, and the files I attached in the previous email was the instructions, that DeDRM file does not exist there. Look at the pictures I sent you.

________________________________
Från: ElleKayEm ***@***.***>
Skickat: den 1 augusti 2023 00:26
Till: apprenticeharper/DeDRM_tools ***@***.***>
Kopia: Delli369 ***@***.***>; Author ***@***.***>
Ämne: Re: [apprenticeharper/DeDRM_tools] Can't open DRM protected book from BOKUS (Issue #2252)


I gave a link to DeDRM 10.0.3. Download the first file there under Assets. Unzip it and load DeDRM_plugin.zip into calibre.

**Comment by ElleKayEm** [comment]
No pictures are showing here.  When you unzip DeDRM_tools_10.0.3.zip, you should see 2 zip files and 3 txt files.  Make sure your browser isn't automatically unzipping it.

**Comment by Delli369** [comment]
Can you see the pictures now??

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ElleKayEm** [comment]
No.  You'll have to come back to the website instead of replying by email.

**Comment by Delli369** [comment]
![photo_2023-08-01_20-14-31](https://github.com/apprenticeharper/DeDRM_tools/assets/140352706/502aee65-4772-4bb1-8857-e793de35eaca)
![photo_2023-08-01_20-14-28](https://github.com/apprenticeharper/DeDRM_tools/assets/140352706/76464b69-a946-4684-b1d0-e7951ecc2a1c)

**Comment by Delli369** [comment]
The requested Plug in doesn't exist.

**Comment by ElleKayEm** [comment]
You don't get the plugin from there.  Follow the link I gave above, download the file, and unzip it as I said above.  Then in calibre, click Preferences (not the drop down menu arrow) and look for Plugins at the bottom of that window.  In the Plugins window click the "Load plugin from file" button near the bottom of that window.  Now you can browse to where you have the DeDRM_plugin.zip file on your computer.  Click ok and apply as needed on your way back of the dialog boxes.  Restart calibre before re-adding your book.

**Comment by Delli369** [comment]
Awesome, thank you so much for your patience! 
But now I can't open the book on Calibre or send it as a Epub?
<img width="582" alt="Screenshot 2023-08-01 at 21 20 35" src="https://github.com/apprenticeharper/DeDRM_tools/assets/140352706/8b049f74-b62e-4595-b269-de346578c953">
<img width="563" alt="Screenshot 2023-08-01 at 21 19 26" src="https://github.com/apprenticeharper/DeDRM_tools/assets/140352706/e27bf812-236c-40aa-8f94-84aed4e33108">

**Comment by ElleKayEm** [comment]
Open the acsm file with Adobe Digital Editions authorized with an Adobe ID intstalled on the same computer and user as calibre.  Then it will download the epub that you can add to calibre.

**Comment by Delli369** [comment]
Wow it works!! From the bottom of my heart, a big thank you ElleKayEm!!! You are amazing, truly so grateful! 

Is there anywhere we can have a private chat, I would like to get your Paypal info and send you a small symbolic gift of gratitude <3

**Comment by ElleKayEm** [comment]
Thanks for the thought.  If you're all set, you can close the issue.
