### ISSUE TITLE
Can't DeDRM  - Mac Ventura, Calibre 6.26, DeDRM 10.0.3

### ISSUE THREAD

**Issue by filipinha** [apprenticeharper/DeDRM_tools#2264]
DeDRM doesn't work for me. I upload the file and it never DRMs.
I don't get any error or log. I upload and the DRM is never removed from the book.
I have tried all versions of the DeDRM. I have tried deleting the ADE key from the DRM plugin.
It was bought by myself in a store and I can read it on ADE; I have ADE 4.5

### Kobo. I'm not using any Kobo desktop, I bought from another store

I'd much appreciate some guidance. Thank you

**Comment by ElleKayEm** [comment]
Here's how to get a log: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

Do you have ADE installed on the same computer and user as calibre/DeDRM?

**Comment by filipinha** [comment]
Yes.  

According to this seems to be about the key, even though I have no idea how to fix it

DeDRM v10.0.3: Failed to decrypt with key `((((my key))))`
after 0.1 seconds
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[2.86] splash screen hidden
[2.86] Started up in 2.86 seconds with 0 books
Added (((my book)))  to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by ElleKayEm** [comment]
This isn't the whole log, is it?

**Comment by filipinha** [comment]
no, i was trying to avoid the personal info. I tried again and got a different log:

Using calibre Qt style: True
calibre Registo de depuração
calibre 6.26  embedded-python: True
macOS-13.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.2.0', 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.1', ('', '', ''), 'arm64')
Interface language: pt
Successfully initialized third party plugins: DeDRM (10, 0, 3) && KePub Input (3, 6, 5) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 5) && Obok DeDRM (10, 0, 3)
calibre 6.26  embedded-python: True
macOS-13.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.2.0', 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.1', ('', '', ''), 'arm64')
Interface language: pt
Successfully initialized third party plugins: DeDRM (10, 0, 3) && KePub Input (3, 6, 5) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 5) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.05] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.52] main UI initialized...
[0.52] Hiding splash screen
Starting QuickView
2023-09-18 19:44:51.019 calibre-debug[23755:16767776] +[CATransaction synchronize] called within transaction
DeDRM v10.0.3: Trying to decrypt ((( my book))).epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: (((my book))).epub is a secure Adobe Adept ePub for UUID d1536f8a-315a-455b-bdc9-d18c1b7b1bd2
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v10.0.3: Trying a new default key
1yf5z5pl.epub is a secure Adobe Adept ePub.
Could not decrypt 1yf5z5pl.epub because of an exception:
Traceback (most recent call last):
  File "/Users/(((my user))))/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 327, in decryptBook
    decryptor = Decryptor(bookkey, encryption)
  File "/Users/((( my user )))/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 150, in __init__
    self._aes = AES.new(bookkey, AES.MODE_CBC, b'\x00'*16)
  File "Crypto/Cipher/AES.py", line 232, in new
  File "Crypto/Cipher/__init__.py", line 79, in _create_cipher
  File "Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto/Cipher/AES.py", line 93, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.3: Failed to decrypt with new default key after 0.2 seconds
DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[2.06] splash screen hidden
[2.06] Started up in 2.06 seconds with 0 books
Added ((( my book))) to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by ElleKayEm** [comment]
Searching previous issues, one that seems a close match to this was a problem with the Adobe ID.  Do you have ADE authorized with your Adobe ID?  Here is that issue if you want to take a look: https://github.com/noDRM/DeDRM_tools/issues/274

**Comment by filipinha** [comment]
Thank you for the help, I did the same as the previous user: I deauthorized ADE and authorized it back again and it worked. Thank you once again

**Comment by ElleKayEm** [comment]
Great!  Thanks for letting us know that worked.
