### ISSUE TITLE
for deDRM_tools

### ISSUE THREAD

**Issue by polymath27** [apprenticeharper/DeDRM_tools#2267]
I have tried multiple releases of this tool, from 7.2.1, to 7.2.0 down.  It says "invalid" when I try to load this plug in into Calibre.  I didn't unzip it, b/c it seemed to pull up fine when loading.  Do I need to unzip first?  Or is there another reason for this error?  Is there a known version of Calibre that works better?  I picked the latest, but maybe that's the issue.

Thank you.

**Comment by ElleKayEm** [comment]
If you're using calibre 6.x , you need DeDRM 10.0.3 or even better 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

Unzip DeDRM_tools_10.0.9.zip and load DeDRM_plugin.zip into calibre.

**Comment by polymath27** [comment]
> If you're using calibre 6.x , you need DeDRM 10.0.3 or even better 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
> 
> Unzip DeDRM_tools_10.0.9.zip and load DeDRM_plugin.zip into calibre.

I was so hopeful that was it!  =(   It gave the same error:  "Invalid"lugin..... is invalid.  It does not contain a top-level_init_.py file.

calibre, version 6.27.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\ccarn\\Downloads\\DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.27  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 513, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\ccarn\\Downloads\\DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_10.0.9.zip and load DeDRM_plugin.zip into calibre.

**Comment by polymath27** [comment]
> Unzip DeDRM_tools_10.0.9.zip and load DeDRM_plugin.zip into calibre.

That worked beautifully!!  Thank you for that!!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
