### ISSUE TITLE
10.0.9 and Calibre 6.29.0

### ISSUE THREAD

**Issue by Cate101** [apprenticeharper/DeDRM_tools#2273]
I am trying to add as a plug in to calibre by loading as a plug in from file. but when I try I get this message. How do i fix this to make it upload right?

calibre, version 6.29.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\catti\\Downloads\\DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.29  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 513, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\catti\\Downloads\\DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_10.0.9.zip and load DeDRM_plugin.zip.

**Comment by Cate101** [comment]
Thank you.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
