### ISSUE TITLE
DeDRM failed

### ISSUE THREAD

**Issue by CafedoCampo** [apprenticeharper/DeDRM_tools#2278]
deDRM failed 

## My Environment:

- Python 3.10.1
- macOS-13.5.2-arm64-arm-64bit
- calibre 6.29 
- DeDRM 10.0.3

## Log

Using calibre Qt style: True
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
calibre Debug log
calibre 6.29  embedded-python: True
macOS-13.5.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.36/RELEASE_ARM64_T6020')
Python 3.10.1
OSX: ('13.5.2', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.29  embedded-python: True
macOS-13.5.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020')
Python 3.10.1
OSX: ('13.5.2', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.03] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.58] main UI initialized...
[0.58] Hiding splash screen
Starting QuickView
2023-11-05 05:36:18.619 calibre-debug[53488:5038656] +[CATransaction synchronize] called within transaction
DeDRM v10.0.3: Trying to decrypt O som do rugido da onça.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: O som do rugido da onça.epub is a secure Adobe Adept ePub for UUID 3a138d06-8eed-484c-a738-6eec0b4e38ae
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
    userkey = codecs.decode(userkeyhex, 'hex')
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
[7.20] splash screen hidden
[7.20] Started up in 7.20 seconds with 15 books
Added O som do rugido da onça to db in: 0.0
Added 1 books in 0.3 seconds

**Comment by ElleKayEm** [comment]
Delete the saved Adobe key.  Add the book to calibre letting DeDRM retrieve the key automatically.  This is a known bug which is fixed in DeDRM 10.0.9.

**Comment by CafedoCampo** [comment]
moving comment to the noDRM fork

**Comment by CafedoCampo** [comment]
Thank you ElleKayEm!  Your solution worked.  I will mark as resolved.
