### ISSUE TITLE
DRM calibre plugin can't remove DRM from Kindle File

### ISSUE THREAD

**Issue by MDCBS** [apprenticeharper/DeDRM_tools#228]
calibre Debug log
calibre 2.54  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Loaded cached store plugin for: Woblink at version: 12
Started up in 76.18 seconds with 12 books
DeDRM v6.5.3: Trying to decrypt CÃ³mo curar un corazÃ³n roto (Spanish Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: CÃ³mo curar un corazÃ³n roto (Spanish Edition)
Found 2 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Edna\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds
Added Cómo curar un corazón roto (Spanish Edition) to db in: 2.0
Added 1 books in 3.0 seconds

**Comment by ElleKayEm** [comment]
If that book is from or for an E-ink Kindle (not a Fire), then you need to enter the serial number into the plugin customization.  Otherwise, install Kindle for PC version 1.17 (see the[ FAQs](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac)) and import a copy from there.

**Comment by apprenticeharper** [comment]
The tools don't work on files from a Kindle Fire.
