### ISSUE TITLE
Calibre don't remove DRM from a PDF

### ISSUE THREAD

**Issue by Alf650** [apprenticeharper/DeDRM_tools#2281]
Computer: MacBook Pro mid 2012 with Catalina (10.15.7).
Version Calibre: 6.0 ( I can't install a newer version of Calibre.)
Version of DEDRM_tools plugin: 7.2.1

I bought a PDF with DRM but I want to read it on an Android Tablet and Adobe Digital editions doesn't work because the version is for older Android.

The log on Calibre is:

calibre Log di debug
calibre 6.0  embedded-python: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 6.0  embedded-python: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.00000171210824 x 114.00000171210824
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.21] splash screen shown
[0.21] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[1.09] main UI initialized...
[1.09] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Polizia locale, analisi operativa e soluzione di casi pratici-1.pdf
[12.49] splash screen hidden
[12.49] Started up in 12.49 seconds with 0 books
Added 0 books in 0.6 seconds
 
It's my first time so I hope did it well.
Thanks

**Comment by ElleKayEm** [comment]
For calibre 6, try DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by Alf650** [comment]
You made it! Thanks a lot!
