### ISSUE TITLE
Obok DRM Fails for multiple version combinations

### ISSUE THREAD

**Issue by yagamiaka** [apprenticeharper/DeDRM_tools#2285]
---

## Using Obok when importing from Kobo

Failed versions tried:
 - Calibre 7.1 + DeDRM/Obok 10.0.3
 - Calibre 7.1 + DeDRM/Obok 10.0.9
 - Calibre 6.29 + DeDRM/Obok 10.0.3
 - Calibre 6.29 + DeDRM/Obok 10.0.9

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
calibre 7.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 93.15759312320917 x 93.06870229007633
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.86] main UI initialized...
[0.86] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1859, in set_metadata
  File "calibre\db\cache.py", line 1782, in set_cover
  File "calibre\db\backend.py", line 1769, in set_cover
  File "calibre\utils\img.py", line 301, in save_cover_data_to
  File "calibre\utils\img.py", line 209, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
```
Every failure produced the same error.

**Comment by yagamiaka** [comment]
Source is a book bought off of Kobo Website, and I'm extracting it from the desktop app "Kobo Desktop".

**Comment by ElleKayEm** [comment]
Since this log doesn't really show anything, what happens when you click the Obok button?  Does it not find your Kobo library?  Kobo Desktop is on the same computer and user as calibre/DeDRM?

**Comment by yagamiaka** [comment]
@ElleKayEm When I click the Obok button, it's able to show my Kobo library without issue, the book I'm attempting to import shows there're no DRM for some reason with an unlocked green padlock symbol. After importing, I'm unable to properly view the book within Calibre, images are missing and gibberish text.

**Comment by ElleKayEm** [comment]
I've seen other people report that happening.  Books that do have DRM showing as not so they just get imported as is without Obok even trying to remove the DRM.  I've very rarely seen it myself, but closing and reopening Kobo Desktop and calibre resolved it for me.  Books then show up with red closed locks (if applicable) and get decrypted properly when added.  Some people have said they don't have trouble if they close Kobo Desktop before trying to import.  Others still have the issue.

**Comment by yagamiaka** [comment]
Thanks, seems like the restart worked. Will close this now.

**Comment by ElleKayEm** [comment]
Glad that worked for you!  And thanks for reporting back.  This was with calibre 7.1 and Obok 10.0.9?

**Comment by yagamiaka** [comment]
This is with 7.1 and the unreleased alpha Obok built 2 weeks ago.
