### ISSUE TITLE
Calibre 7.2 (Mac) crashes when I try to customize 7.2.1 DeDRM 

### ISSUE THREAD

**Issue by RealAmyGeek** [apprenticeharper/DeDRM_tools#2286]
FIXED! Downloaded v10.0.3 of the plugin & was able to configure properly.

This Calibre version just shipped a few days ago so I'm guessing it's specific to this build. Every time I click to customize the plugin with my Kindle info, Calibre crashes. I uninstalled & reinstalled but no love. Details:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               calibre [10759]
Path:                  /Users/USER/Desktop/calibre.app/Contents/MacOS/calibre
Identifier:            net.kovidgoyal.calibre
Version:               7.2.0 (7.2.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-18 12:32:52.4730 -0800
OS Version:            macOS 14.2 (23C64)
Report Version:        12
Anonymous UUID:        0B7DB917-564D-AFA1-45C8-B4AFD15E993E

Sleep/Wake UUID:       49CD136E-66E5-452B-AD8F-E0F5403E0DB3

Time Awake Since Boot: 16000 seconds
Time Since Wake:       4144 seconds

System Integrity Protection: enabled

Crashed Thread:        0  AllIpAddressesG  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   calibre [10759]

Application Specific Information:
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.
abort() called

Thread 0 Crashed:: AllIpAddressesG Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18586a0dc __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1858a1cc0 pthread_kill + 288
2   libsystem_c.dylib             	       0x1857ada40 abort + 180
3   libcrypto.dylib               	       0x2259e4950 __report_load.cold.1 + 52
4   libcrypto.dylib               	       0x2259e4640 __report_load + 388
5   dyld                          	       0x18553da24 invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const + 168
6   dyld                          	       0x185583328 invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 340
7   dyld                          	       0x185576668 invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 496
8   dyld                          	       0x18551d2fc dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 300
9   dyld                          	       0x1855756a0 dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 192
10  dyld                          	       0x185582e3c dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 516
11  dyld                          	       0x185539b38 dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const + 524
12  dyld                          	       0x185543928 dyld4::PrebuiltLoader::runInitializers(dyld4::RuntimeState&) const + 44
13  dyld                          	       0x185539f24 dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 220
14  dyld                          	       0x18553dab0 dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const + 112
15  dyld                          	       0x18553a0f0 dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const + 380
16  dyld                          	       0x1855587ac dyld4::APIs::dlopen_from(char const*, int, void*) + 1576
17  _ctypes.so                    	       0x1035dfd10 py_dl_open + 144
18  Python                        	       0x1045c5680 cfunction_call + 100
19  Python                        	       0x104682d40 _PyEval_EvalFrameDefault + 73204
20  Python                        	       0x10466f66c _PyEval_Vector + 464
21  Python                        	       0x1045efb6c slot_tp_init + 200
22  Python                        	       0x1045e60c4 type_call + 144
23  Python                        	       0x104682d40 _PyEval_EvalFrameDefault + 73204
24  Python                        	       0x10466f66c _PyEval_Vector + 464
25  Python                        	       0x10466f428 PyEval_EvalCode + 232
26  Python                        	       0x10466ac04 builtin_exec + 332
27  Python                        	       0x1046852d8 _PyEval_EvalFrameDefault + 82828
28  Python                        	       0x10466f66c _PyEval_Vector + 464
29  Python                        	       0x104562c1c _PyObject_VectorcallTstate.754 + 72
30  Python                        	       0x1045678a8 object_vacall + 268
31  Python                        	       0x104567738 PyObject_CallMethodObjArgs + 92
32  Python                        	       0x1046b6e30 PyImport_ImportModuleLevelObject + 4136
33  Python                        	       0x10467ef24 _PyEval_EvalFrameDefault + 57304
34  Python                        	       0x10466f66c _PyEval_Vector + 464
35  Python                        	       0x10466f428 PyEval_EvalCode + 232
36  Python                        	       0x10466ac04 builtin_exec + 332
37  Python                        	       0x1046852d8 _PyEval_EvalFrameDefault + 82828
38  Python                        	       0x10466f66c _PyEval_Vector + 464
39  Python                        	       0x104562c1c _PyObject_VectorcallTstate.754 + 72
40  Python                        	       0x1045678a8 object_vacall + 268
41  Python                        	       0x104567738 PyObject_CallMethodObjArgs + 92
42  Python                        	       0x1046b6e30 PyImport_ImportModuleLevelObject + 4136
43  Python                        	       0x10467ef24 _PyEval_EvalFrameDefault + 57304
44  Python                        	       0x10466f66c _PyEval_Vector + 464
45  Python                        	       0x10466f428 PyEval_EvalCode + 232
46  Python                        	       0x10466ac04 builtin_exec + 332
47  Python                        	       0x1045c5dec cfunction_vectorcall_FASTCALL_KEYWORDS + 76
48  Python                        	       0x104682bfc _PyEval_EvalFrameDefault + 72880
49  Python                        	       0x10466f66c _PyEval_Vector + 464
50  Python                        	       0x104562c1c _PyObject_VectorcallTstate.754 + 72
51  Python                        	       0x1045678a8 object_vacall + 268
52  Python                        	       0x104567738 PyObject_CallMethodObjArgs + 92
53  Python                        	       0x1046b6e30 PyImport_ImportModuleLevelObject + 4136
54  Python                        	       0x10467ef24 _PyEval_EvalFrameDefault + 57304
55  Python                        	       0x10466f66c _PyEval_Vector + 464
56  Python                        	       0x104568c1c method_vectorcall + 164
57  PyQt6.QtCore.so               	       0x10af9a378 PyQtSlot::call(_object*, _object*) const + 68
58  PyQt6.QtCore.so               	       0x10af9a208 PyQtSlot::invoke(void**, _object*, void*, bool) const + 292
59  PyQt6.QtCore.so               	       0x10af9b194 PyQtSlotProxy::unislot(void**) + 92
60  PyQt6.QtCore.so               	       0x10af9b104 PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) + 68
61  QtCore                        	       0x10a91411c 0x10a820000 + 999708
62  QtWidgets                     	       0x10d85a038 QTreeView::mouseDoubleClickEvent(QMouseEvent*) + 456
63  PyQt6.QtWidgets.so            	       0x10dfcae94 sipQTreeView::mouseDoubleClickEvent(QMouseEvent*) + 136
64  QtWidgets                     	       0x10d56ab94 QWidget::event(QEvent*) + 132
65  QtWidgets                     	       0x10d5f45f4 QAbstractScrollArea::viewportEvent(QEvent*) + 96
66  QtWidgets                     	       0x10d7de844 QAbstractItemView::viewportEvent(QEvent*) + 1084
67  QtWidgets                     	       0x10d8562c4 QTreeView::viewportEvent(QEvent*) + 288
68  PyQt6.QtWidgets.so            	       0x10dfc9a9c sipQTreeView::viewportEvent(QEvent*) + 136
69  QtCore                        	       0x10a8c04a0 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) + 244
70  QtWidgets                     	       0x10d51a6f4 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 288
71  QtWidgets                     	       0x10d51d118 QApplication::notify(QObject*, QEvent*) + 6932
72  PyQt6.QtWidgets.so            	       0x10e179ac8 sipQApplication::notify(QObject*, QEvent*) + 148
73  QtCore                        	       0x10a8c018c QCoreApplication::notifyInternal2(QObject*, QEvent*) + 304
74  QtWidgets                     	       0x10d51adf8 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 824
75  QtWidgets                     	       0x10d5801c4 0x10d4fc000 + 541124
76  QtWidgets                     	       0x10d51a720 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 332
77  QtWidgets                     	       0x10d51b814 QApplication::notify(QObject*, QEvent*) + 528
78  PyQt6.QtWidgets.so            	       0x10e179ac8 sipQApplication::notify(QObject*, QEvent*) + 148
79  QtCore                        	       0x10a8c018c QCoreApplication::notifyInternal2(QObject*, QEvent*) + 304
80  QtGui                         	       0x10f5cf060 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 3244
81  QtGui                         	       0x10f636d64 QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 396
82  libqcocoa.dylib               	       0x10f18419c 0x10f16c000 + 98716
83  CoreFoundation                	       0x18597fa4c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
84  CoreFoundation                	       0x18597f9e0 __CFRunLoopDoSource0 + 176
85  CoreFoundation                	       0x18597f750 __CFRunLoopDoSources0 + 244
86  CoreFoundation                	       0x18597e340 __CFRunLoopRun + 828
87  CoreFoundation                	       0x18597d9ac CFRunLoopRunSpecific + 608
88  HIToolbox                     	       0x18ff2c448 RunCurrentEventLoopInMode + 292
89  HIToolbox                     	       0x18ff2c0d8 ReceiveNextEventCommon + 220
90  HIToolbox                     	       0x18ff2bfdc _BlockUntilNextEventMatchingListInModeWithFilter + 76
91  AppKit                        	       0x18915a8a4 _DPSNextEvent + 660
92  AppKit                        	       0x189934980 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
93  AppKit                        	       0x18938e09c -[NSApplication _doModalLoop:peek:] + 216
94  AppKit                        	       0x189583504 __33-[NSApplication runModalSession:]_block_invoke_2 + 88
95  AppKit                        	       0x189583490 __33-[NSApplication runModalSession:]_block_invoke + 112
96  AppKit                        	       0x18938c81c _NSTryRunModal + 100
97  AppKit                        	       0x189583360 -[NSApplication runModalSession:] + 148
98  libqcocoa.dylib               	       0x10f1828f0 0x10f16c000 + 92400
99  QtCore                        	       0x10a8cba48 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 708
100 QtWidgets                     	       0x10d77dd50 QDialog::exec() + 516
101 PyQt6.QtWidgets.so            	       0x10e1b0804 meth_QDialog_exec(_object*, _object*) + 216
102 Python                        	       0x1045c5680 cfunction_call + 100
103 Python                        	       0x104682d40 _PyEval_EvalFrameDefault + 73204
104 Python                        	       0x10466f66c _PyEval_Vector + 464
105 Python                        	       0x104568c1c method_vectorcall + 164
106 PyQt6.QtCore.so               	       0x10af9a378 PyQtSlot::call(_object*, _object*) const + 68
107 PyQt6.QtCore.so               	       0x10af9a208 PyQtSlot::invoke(void**, _object*, void*, bool) const + 292
108 PyQt6.QtCore.so               	       0x10af9b194 PyQtSlotProxy::unislot(void**) + 92
109 PyQt6.QtCore.so               	       0x10af9b104 PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) + 68
110 QtCore                        	       0x10a91411c 0x10a820000 + 999708
111 QtGui                         	       0x10f901360 QAction::activate(QAction::ActionEvent) + 376
112 QtWidgets                     	       0x10d62b340 0x10d4fc000 + 1241920
113 QtWidgets                     	       0x10d62cb08 QAbstractButton::mouseReleaseEvent(QMouseEvent*) + 204
114 QtWidgets                     	       0x10d75ec30 QToolButton::mouseReleaseEvent(QMouseEvent*) + 20
115 QtWidgets                     	       0x10d56ab94 QWidget::event(QEvent*) + 132
116 QtWidgets                     	       0x10d75f8b0 QToolButton::event(QEvent*) + 212
117 QtWidgets                     	       0x10d51a720 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 332
118 QtWidgets                     	       0x10d51d118 QApplication::notify(QObject*, QEvent*) + 6932
119 PyQt6.QtWidgets.so            	       0x10e179ac8 sipQApplication::notify(QObject*, QEvent*) + 148
120 QtCore                        	       0x10a8c018c QCoreApplication::notifyInternal2(QObject*, QEvent*) + 304
121 QtWidgets                     	       0x10d51adf8 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 824
122 QtWidgets                     	       0x10d5801c4 0x10d4fc000 + 541124
123 QtWidgets                     	       0x10d51a720 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 332
124 QtWidgets                     	       0x10d51b814 QApplication::notify(QObject*, QEvent*) + 528
125 PyQt6.QtWidgets.so            	       0x10e179ac8 sipQApplication::notify(QObject*, QEvent*) + 148
126 QtCore                        	       0x10a8c018c QCoreApplication::notifyInternal2(QObject*, QEvent*) + 304
127 QtGui                         	       0x10f5ced6c QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 2488
128 QtGui                         	       0x10f636d64 QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 396
129 libqcocoa.dylib               	       0x10f18419c 0x10f16c000 + 98716
130 CoreFoundation                	       0x18597fa4c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
131 CoreFoundation                	       0x18597f9e0 __CFRunLoopDoSource0 + 176
132 CoreFoundation                	       0x18597f750 __CFRunLoopDoSources0 + 244
133 CoreFoundation                	       0x18597e340 __CFRunLoopRun + 828
134 CoreFoundation                	       0x18597d9ac CFRunLoopRunSpecific + 608
135 HIToolbox                     	       0x18ff2c448 RunCurrentEventLoopInMode + 292
136 HIToolbox                     	       0x18ff2c0d8 ReceiveNextEventCommon + 220
137 HIToolbox                     	       0x18ff2bfdc _BlockUntilNextEventMatchingListInModeWithFilter + 76
138 AppKit                        	       0x18915a8a4 _DPSNextEvent + 660
139 AppKit                        	       0x189934980 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
140 AppKit                        	       0x18914dd50 -[NSApplication run] + 476
141 libqcocoa.dylib               	       0x10f1829f4 0x10f16c000 + 92660
142 QtCore                        	       0x10a8cba48 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 708
143 QtCore                        	       0x10a8c08e8 QCoreApplication::exec() + 112
144 PyQt6.QtWidgets.so            	       0x10e1bab30 meth_QApplication_exec(_object*, _object*) + 100
145 Python                        	       0x1045c5680 cfunction_call + 100
146 Python                        	       0x104682d40 _PyEval_EvalFrameDefault + 73204
147 Python                        	       0x10466f66c _PyEval_Vector + 464
148 Python                        	       0x10466f428 PyEval_EvalCode + 232
149 Python                        	       0x10466ac04 builtin_exec + 332
150 Python                        	       0x1045c5dec cfunction_vectorcall_FASTCALL_KEYWORDS + 76
151 Python                        	       0x104682bfc _PyEval_EvalFrameDefault + 72880
152 Python                        	       0x10466f66c _PyEval_Vector + 464
153 Python                        	       0x104700754 pymain_run_module + 196
154 Python                        	       0x10470025c Py_RunMain + 1296
155 calibre-launcher.dylib        	       0x1033bdf0c 0x1033b8000 + 24332
156 calibre-launcher.dylib        	       0x1033bdab0 0x1033b8000 + 23216
157 calibre-launcher.dylib        	       0x1033bba80 run + 140
158 calibre                       	       0x102e8fe2c main + 328
159 dyld                          	       0x1855210e0 start + 2360

**Comment by ElleKayEm** [comment]
Use DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by RealAmyGeek** [comment]
Updating now. Thanks for the quick response & your help.
