### ISSUE TITLE
Linux mint calibre dedrm adobe no success

### ISSUE THREAD

**Issue by AbsoluteNewone** [apprenticeharper/DeDRM_tools#229]
Hi there,
I'm more or less an absolute beginner. 
On my computer  I try to import a book with adobe DRM into calibre.
Linux mint 18 cinnamon
ADE 1.7.2 works with wine (books can be read in ADE)
the dedrm_plugin.zip from dedrmtools 6.5.3 is integrated in calibre
the ebook file (pdf) was imported from the ADE under wine

Each time I try to import the book, the DRM stays. Calibre tells me to sign in with a PW for this book.
[tmpfdTCb9.txt](https://github.com/apprenticeharper/DeDRM_tools/files/827574/tmpfdTCb9.txt)

I really hope somebody can help me.

Thank you for your help.
I hope so.

Cheers

**Comment by ElleKayEm** [comment]
Not being a Linux user myself, I can only tell you what I've seen mentioned about this before.  There's an issue for some Linux systems that keeps DeDRM from finding Python.  (You do need to have Python and PyCrypto installed under Wine.)  Try manually running the key retrieval script under Wine, and import the key into calibre:

`wine python.exe "/home/florian/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/florian/winekeysdir"`

(You may need to create /home/florian/winekeysdir first, and then the retrieved key(s) should be put there.)

**Comment by apprenticeharper** [comment]
No response. Closed.
