### ISSUE TITLE
Can't remove DRM

### ISSUE THREAD

**Issue by PawPawTree55** [apprenticeharper/DeDRM_tools#2298]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Can't remove DRM
Hi all, I have followed all of the directions and am clearly missing something here. Can someone please help? information is below. Thanks so much in advance!

## Log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.4  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 8, 1) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1) && Obok DeDRM (10, 0, 3)
calibre 7.4  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 8, 1) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.67567567567568
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.80] GUI main window shown
[0.81] main UI initialized...
[0.81] Hiding splash screen
DeDRM v10.0.3: Trying to decrypt Nature's Best Hope (4).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Nature's Best Hope
Got DSN key from database default_key_1706806521
Found 8 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 8 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\john9\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\john9\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1143941912' and UserName 'john9'
DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\john9\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\john9\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 8 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[13.99] splash screen hidden
[13.99] Started up in 13.99 seconds with 1 books

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 220 b'\x01\x00\x00\x00\x0c\x00\x00\x00H\x00\x00\x00:\x00\x1f\x00\x059\x8e\x08#\x03\x02K\x98&]\x99B\x8e\x11_&\x00\x01\x00&\x00\xef\xbe\x11\x00\x00\x00K\xd8(\x9e\x14g\xd8\x01\x84\x05\xf5x0U\xda\x01c\xc1\xf5x0U\xda\x01\x14\x00\x00\x00\x92\x002\x00\xe8\xd8\xcc\x00AX\x00\x89 \x00Nature\'s Best Hope (4).azw3\x00h\x00\t\x00\x04\x00\xef\xbeAX\xfd\x88AX\x04\x89.\x00\x00\x00\x08"\x03\x00\x00\x00!\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x9eq\x8e\x00N\x00a\x00t\x00u\x00r\x00e\x00\'\x00s\x00 \x00B\x00e\x00s\x00t\x00 \x00H\x00o\x00p\x00e\x00 \x00(\x004\x00)\x00.\x00a\x00z\x00w\x003\x00\x00\x00*\x00\x00\x00' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 36888 b'`\x00\x00\x00`\x00\x00\x000\x00\x00\x00Y\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragContext" 16 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 b'\x01\x00\x00\x00' 

text/uri-list 68 b"file:///C:/Users/john9/Downloads/Nature's%20Best%20Hope%20(4).azw3\r\n" 

application/x-qt-windows-mime;value="FileName" 52 b"C:\\Users\\john9\\DOWNLO~1\\Nature's Best Hope (4).azw3\x00" 

application/x-qt-windows-mime;value="FileContents" 0 b'' 

application/x-qt-windows-mime;value="FileNameW" 106 b"C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00j\x00o\x00h\x00n\x009\x00\\\x00D\x00o\x00w\x00n\x00l\x00o\x00a\x00d\x00s\x00\\\x00N\x00a\x00t\x00u\x00r\x00e\x00'\x00s\x00 \x00B\x00e\x00s\x00t\x00 \x00H\x00o\x00p\x00e\x00 \x00(\x004\x00)\x00.\x00a\x00z\x00w\x003\x00\x00\x00" 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 b"\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\xebK41U\xda\x01\x00\x00\x00\x00\x00\x00\x00\x00b\xa6\xee41U\xda\x01\x00\x00\x00\x00\xe8\xd8\xcc\x00N\x00a\x00t\x00u\x00r\x00e\x00'\x00s\x00 \x00B\x00e\x00s\x00t\x00 \x00H\x00o\x00p\x00e\x00 \x00(\x004\x00)\x00.\x00a\x00z\x00w\x003\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" 

application/x-qt-windows-mime;value="IsShowingLayered" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragWindow" 4 b'\xd4\x0c\x0f\x00' 

application/x-qt-windows-mime;value="IsComputingImage" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DisableDragText" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DropDescription" 1044 b'\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="IsShowingText" 4 b'\x00\x00\x00\x00' 

Firefox rurl: None None
URLS: ["file:///C:/Users/john9/Downloads/Nature's%20Best%20Hope%20(4).azw3"]
Paths: ["C:/Users/john9/Downloads/Nature's Best Hope (4).azw3"]
Extensions: frozenset({'azw3'})
Added Nature's Best Hope to db in: 0.1
Added 1 books in 0.5 seconds

**Comment by ElleKayEm** [comment]
If that copy of the book is for or from an E-ink Kindle (not a Fire), make sure you have that Kindle's serial number correctly entered into DeDRM's customization.

**Comment by PawPawTree55** [comment]
> If that copy of the book is for or from an E-ink Kindle (not a Fire), make sure you have that Kindle's serial number correctly entered into DeDRM's customization.

Thanks for the response. I downloaded this off the amazon website and I input both my kindle and my wife's kindle's serial number (we share an account). I removed her account and tried it and it still did not work, sadly.

**Comment by ElleKayEm** [comment]
Make sure when you download from the website that you choose an E-ink Kindle for the device.  And make sure that particular Kindle's serial number is in DeDRM's customization correctly.  Try copy and pasting the serial number from the website.

**Comment by PawPawTree55** [comment]
I just double checked it and sadly it is still not working :/

**Comment by PawPawTree55** [comment]
Ah that could be something - it is for a Fire. Is that the issue here? Should I remove that device?

**Comment by ElleKayEm** [comment]
For this method, you need to have an E-ink Kindle and choose that when downloading the book from the website.

**Comment by PawPawTree55** [comment]
IT worked! I just used my wife's account with her normal kindle. Thanks so much!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by PawPawTree55** [comment]
Realized the fire was the issue. Kindle fire doesnt work here.
