### ISSUE TITLE
Error: argument should be integer or bytes-like object, not 'str'

### ISSUE THREAD

**Issue by Petya90** [apprenticeharper/DeDRM_tools#2301]
Hi there, i would use inept pdf decrypter 8.4.51 to remove fileopen DRM, but it gives me the above error
I entered the input file (the pdf to be opened) and the location of the output file, and gave it a name
What could be the problem?

Thanks
Pete

**Comment by ElleKayEm** [comment]
noDRM was testing a new script with someone, but they never reported back so I don't know if it works.  See this issue: https://github.com/noDRM/DeDRM_tools/issues/442

**Comment by Petya90** [comment]
thanks, for me, it worked!

**Comment by Petya90** [comment]
Thanks, for me, it worked!

**Comment by ElleKayEm** [comment]
Good to hear!
