### ISSUE TITLE
Failed removal DRM PRC

### ISSUE THREAD

**Issue by BRASPO22** [apprenticeharper/DeDRM_tools#2302]
Hello
Has there been any change in breaking the DRM of the PRC file as of 03/01/2024?

I managed to convert ebooks at 03:00 AM on 01/03 and it was 01:00 PM and out of 17 ebook files that I tried to convert, 10 failed.
Did you notice any changes in the breaking of the PRC format drm?

I live in Brazil.

Thanks in advance.
(If you need a file and the key to test, I'll share it).

**Comment by ElleKayEm** [comment]
Still working for me.  Usually this is all or nothing if they were downloaded the same way.  Are you sure the ones that "worked" had DRM to begin with?

**Comment by BRASPO22** [comment]
One of those that "worked" didn't come with DRM.
I tested the file extracted directly from the Kindle Android here and converted the prc directly into an online file converter.
Probably the 7 didn't have DRM.
Amazon apparently doesn't put DRM on all files.

Thank you very much for responding.

**Comment by ElleKayEm** [comment]
Should be able to get things working.  I can look at a log or try to answer questions.

**Comment by BRASPO22** [comment]
I think I found the problem but I have no idea how to solve it:

I checked where the key generated by Android is registered in Caliber within the DDrm 10.0.3 plugin and the name I gave the key disappeared, that is, apparently the key was removed (I don't know how to even touch that part).
Then I tried to add the key again but it gives the following error:

Unable to open file: C: \Users\ADMINI~1\AppData\Local\Temp\tmpn5opxq.

It is already open in the following programs: The main calibre program: C:\Program Files\Calibre2\calibre.exe

Help, I don't know what to do.
I didn't do anything different for this to happen.


Would the log help figure out why this is occurring?

Thanks in advance.

**Comment by ElleKayEm** [comment]
Try this version of the plugin with the very latest changes: https://github.com/noDRM/DeDRM_tools_autorelease/releases/tag/autorelease_bf2471e65b1f52bb5292caeba70a9aea31bf6653

**Comment by BRASPO22** [comment]
thank you very very very much
It worked
Thank you from the bottom of my heart

**Comment by BRASPO22** [comment]
thank you very very very much
It worked
Thank you from the bottom of my heart

**Comment by 3DRex** [comment]
> Try this version of the plugin with the very latest changes: https://github.com/noDRM/DeDRM_tools_autorelease/releases/tag/autorelease_bf2471e65b1f52bb5292caeba70a9aea31bf6653

Hello, I'm having difficulty removing drm from prc in calibre with dedrm v10.0.09.  Tried your link, but no longer valid?  Would you happen to have another?

**Comment by ElleKayEm** [comment]
Yes, more updates have happened.  Should always be able to find the latest here: https://github.com/noDRM/DeDRM_tools_autorelease/releases
