### ISSUE TITLE
A question about the constant IV

### ISSUE THREAD

**Issue by Gax-c** [apprenticeharper/DeDRM_tools#2307]
I've got a question about the constant initial vector defined in [source code](https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_plugin/adobekey.py#L154). 

The IV for AES in CBC mode should not be constant for security issues. 
So, I wonder if it's a bug.

**Comment by ElleKayEm** [comment]
This version is no longer updated.  See noDRM's version for the latest: https://github.com/noDRM/DeDRM_tools/

**Comment by Gax-c** [comment]
Oh, thank you!
