### ISSUE TITLE
DRM is not working

### ISSUE THREAD

**Issue by Scheitelhengst** [apprenticeharper/DeDRM_tools#2318]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre_plugins.librarything_match.fuzzywuzzy.fuzz:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
calibre Fehlerdiagnoseprotokoll
calibre 7.10  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 10, 0) && ACE (1, 1, 6) && Barnes & Noble (1, 5, 5) && CalibreSpy (1, 0, 92) && Check Books (0, 1, 8) && DNB_DE (3, 2, 4) && Fantastic Fiction Adults (1, 3, 1) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Library Codes (1, 0, 65) && Library Splitter (1, 0, 7) && LibraryThing Match (0, 2, 2) && Obok DeDRM (7, 2, 1)
calibre 7.10  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 10, 0) && ACE (1, 1, 6) && Barnes & Noble (1, 5, 5) && CalibreSpy (1, 0, 92) && Check Books (0, 1, 8) && DNB_DE (3, 2, 4) && Fantastic Fiction Adults (1, 3, 1) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Library Codes (1, 0, 65) && Library Splitter (1, 0, 7) && LibraryThing Match (0, 2, 2) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 106.38743455497382 x 106.32558139534883
[0.00] Starting up...
[0.02] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.78] GUI main window shown
CalibreSpy: initialization_complete
[2.98] main UI initialized...
[2.98] Hiding splash screen
[12.62] splash screen hidden
[12.62] Started up in 12.62 seconds with 0 books
DeDRM v7.2.1: Trying to decrypt Schlacht der Identitäten-1.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Schlacht der Identitäten-1.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 358, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 362, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 342, in CryptUnprotectData
calibre_plugins.dedrm.adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Exception ignored in: <function NativeFunction.__del__ at 0x000001AD84F12F20>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001AD84F12F20>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by Scheitelhengst** [comment]
I have downloaded and installed this update 4 times today. Unfortunately without success. What else can I do?

![drm](https://github.com/apprenticeharper/DeDRM_tools/assets/169598010/907eef5f-a1a1-4b43-b75b-203e6d39d3fd)

**Comment by ElleKayEm** [comment]
Let's see a log from after you updated.  Were the books downloaded with ADE on the same computer and user as calibre/DeDRM?  Or did you use DeASCM?

**Comment by Scheitelhengst** [comment]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre_plugins.librarything_match.fuzzywuzzy.fuzz:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
calibre Fehlerdiagnoseprotokoll
calibre 7.10  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 10, 0) && ACE (1, 1, 6) && Barnes & Noble (1, 5, 5) && CalibreSpy (1, 0, 92) && Check Books (0, 1, 8) && DNB_DE (3, 2, 4) && Fantastic Fiction Adults (1, 3, 1) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && Library Codes (1, 0, 65) && Library Splitter (1, 0, 7) && LibraryThing Match (0, 2, 2) && Obok DeDRM (10, 0, 9)
calibre 7.10  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 10, 0) && ACE (1, 1, 6) && Barnes & Noble (1, 5, 5) && CalibreSpy (1, 0, 92) && Check Books (0, 1, 8) && DNB_DE (3, 2, 4) && Fantastic Fiction Adults (1, 3, 1) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && Library Codes (1, 0, 65) && Library Splitter (1, 0, 7) && LibraryThing Match (0, 2, 2) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 106.38743455497382 x 106.32558139534883
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.39] GUI main window shown
CalibreSpy: initialization_complete
[2.58] main UI initialized...
[2.58] Hiding splash screen




Yes the books were downloaded with ADE on the same computer and user as Kaliber/DeDRM? What is DeACSM?

**Comment by Scheitelhengst** [comment]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre_plugins.librarything_match.fuzzywuzzy.fuzz:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
calibre Fehlerdiagnoseprotokoll
calibre 7.10  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 10, 0) && ACE (1, 1, 6) && Barnes & Noble (1, 5, 5) && CalibreSpy (1, 0, 92) && Check Books (0, 1, 8) && DNB_DE (3, 2, 4) && Fantastic Fiction Adults (1, 3, 1) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && Library Codes (1, 0, 65) && Library Splitter (1, 0, 7) && LibraryThing Match (0, 2, 2) && Obok DeDRM (10, 0, 9)
calibre 7.10  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 10, 0) && ACE (1, 1, 6) && Barnes & Noble (1, 5, 5) && CalibreSpy (1, 0, 92) && Check Books (0, 1, 8) && DNB_DE (3, 2, 4) && Fantastic Fiction Adults (1, 3, 1) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && Library Codes (1, 0, 65) && Library Splitter (1, 0, 7) && LibraryThing Match (0, 2, 2) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 106.38743455497382 x 106.32558139534883
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.39] GUI main window shown
CalibreSpy: initialization_complete
[2.58] main UI initialized...
[2.58] Hiding splash screen



Yes the books were downloaded with ADE on the same computer and user as Kaliber/DeDRM? What is DeACSM?     It is an .acsm file.

**Comment by ElleKayEm** [comment]
This log doesn't show you adding an epub to calibre.  DeACSM is another one of the plugins you have installed.

**Comment by Scheitelhengst** [comment]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre_plugins.librarything_match.fuzzywuzzy.fuzz:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
calibre Fehlerdiagnoseprotokoll
calibre 7.10  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 10, 0) && ACE (1, 1, 6) && Barnes & Noble (1, 5, 5) && CalibreSpy (1, 0, 92) && Check Books (0, 1, 8) && DNB_DE (3, 2, 4) && Fantastic Fiction Adults (1, 3, 1) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && Library Codes (1, 0, 65) && Library Splitter (1, 0, 7) && LibraryThing Match (0, 2, 2) && Obok DeDRM (10, 0, 9)
calibre 7.10  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 10, 0) && ACE (1, 1, 6) && Barnes & Noble (1, 5, 5) && CalibreSpy (1, 0, 92) && Check Books (0, 1, 8) && DNB_DE (3, 2, 4) && Fantastic Fiction Adults (1, 3, 1) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && Library Codes (1, 0, 65) && Library Splitter (1, 0, 7) && LibraryThing Match (0, 2, 2) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 106.38743455497382 x 106.32558139534883
[0.00] Starting up...
[0.00] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.42] GUI main window shown
CalibreSpy: initialization_complete
[2.61] main UI initialized...
[2.61] Hiding splash screen
[4.33] splash screen hidden
[4.33] Started up in 4.33 seconds with 0 books
DeDRM v10.0.9: Trying to decrypt Schlacht der Identitäten-5.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Schlacht der Identitäten-5.epub is a secure Adobe Adept ePub for UUID b68187a7-3e31-4d76-ba1a-128f2335657c
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 565, in ePubDecrypt
  File "C:\Users\marvi\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 293, in adeptkeys
  File "C:\Users\marvi\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 273, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
Was ADE authorized with your Adobe ID before you opened the acsm file and downloaded the epub?

You could try deauthorizing and reauthorizing ADE.

Go to this page: https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html

Scroll down to the instructions under TROUBLESHOOTING REAUTHORIZATION AND DEAUTHORIZATION ISSUES ON WINDOWS.  As it says there, be very careful when modifying the Windows registry.

**Comment by Scheitelhengst** [comment]
I have already done that. Without success.

**Comment by ElleKayEm** [comment]
I don't know then.  Those are all the things which have worked for myself and others.

**Comment by Scheitelhengst** [comment]
Crap. I am desperate.

**Comment by Scheitelhengst** [comment]
It has left me no peace. I did it again exactly as you said and lo and behold, it worked. Sorry, but I love you. Thank you.

**Comment by ElleKayEm** [comment]
:) Glad it finally worked.  If you're all set, you can close the issue.
