### ISSUE TITLE
Windows Calibre 2.81 DeDRM 6.5.3

### ISSUE THREAD

**Issue by viktorce** [apprenticeharper/DeDRM_tools#232]
calibre Debug log
calibre 2.81  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Obok DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 25.41 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['{Ie\xc4\xce\x97r\xda\xc3\xce\xa0\\\xfa\xe9<\xb12\x89\xe2\xbbb?p\xae3N\t\rT e{', 'C:\\Users\\webdev\\Downloads\\Hold on to your kids\\B004LGTS5W_EBOK.azw']
DeDRM v6.5.3: Trying to decrypt B004LGTS5W_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Hold On to Your Kids: Why Parents Need to Matter More Than Peers
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\webdev\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\webdev\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3759408513' and UserName '776562646576'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Hold On to Your Kids: Why Parents Need to Matter More Than Peers
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds
Added Hold On to Your Kids: Why Parents Need to Matter More Than Peers to db in: 0.2
Added 1 books in 1.1 seconds

**Comment by apprenticeharper** [comment]
That ebook is clearly in your downloads folder. For the tools to work, you need to own the ebook and download it using Kindle for PC (1.17 or earlier) on the same machine and user account as calibre and the plugin.
