### ISSUE TITLE
HELPPPPPP

### ISSUE THREAD

**Issue by BRASPO22** [apprenticeharper/DeDRM_tools#2322]
Unable to open file "C:\Users\adm\AppData\Local\Temp\tmp296oloi0". It is now open in the following programs:
Caliber

This message is giving me when I try to add the android key in DDrm 10.0.9

Before, I could easily add the key.
Now it doesn't come in for anything.
It just gives this message.

I formatted the computer thinking it was the problem but I think it's in DDrm.
Before formatting I tried the old plugins and the problem persists.

Now I can't break the DRM of releases from 05/09 because the prc no longer downloads on my Android 6.0 cell phone
And this problem arose: the .prc files that I can download prior to 05/09 cannot break the DRM because the plugin does not accept the key that I have been using since last year.

Is there any solution?

SOS

Thanks in advance.

**Comment by BRASPO22** [comment]
I tried to generate another key and the file size was more than 500mb from the same app I have installed since last year.
The android key I used since last year is 1.83 mb

**Comment by ElleKayEm** [comment]
Use the alpha version of DeDRM: https://github.com/noDRM/DeDRM_tools_autorelease/releases

**Comment by BRASPO22** [comment]
Thank you very much for the new plugin.
It accepted my 1.83 Mb key but the DRM was not broken.
I tried to generate another key in the app that was already on my cell phone and the 1.83 mb key should work since it has been on my cell phone since last year and there was no update.
I tried to generate another key but the key came with 900 Mb.
The command I used was: adb backup com.amazon.kindle

I'm trying to generate keys on my Android 8 and 4.1 cell phone and the key is not generated.

**Comment by ElleKayEm** [comment]
Did you try adding the newly generated key?  The keys occasionally change even without an update.  As long as the file is not ridiculously tiny, it may be a valid key.

Your other phones may have a version of Kindle for Android that is too new...Amazon took away the backup option in later versions.

I've recently used an older version of Kindle for Android in BlueStacks successfully.

You can also decrypt most books from the current Kindle for PC or Kindle Classic for Mac with DeDRM 10.0.9 (or the alpha version) and the KFX Input plugin.
