### ISSUE TITLE
KINDLE PC

### ISSUE THREAD

**Issue by BRASPO22** [apprenticeharper/DeDRM_tools#2323]
Is there a Kindle for PC (Windows) that breaks DRM for ebooks released in 2023?
Or is Kindle for PC only for ebooks released until 2022?
Thanks in advance.

**Comment by ElleKayEm** [comment]
You can decrypt most books from the current Kindle for PC regardless of pub date with DeDRM 10.0.9 and the KFX Input plugin.

**Comment by BRASPO22** [comment]
I spent a while reading your answer in disbelief.
kkkkkkkkk
Then I ran to see.
I can't believe I didn't know that.

Thank you very very very much.
You always saving my life.
