### ISSUE TITLE
Calibre 7.12 DeDRM Problem

### ISSUE THREAD

**Issue by Nooread** [apprenticeharper/DeDRM_tools#2326]
I am receiving this message when trying to install DeDRM into Calibre 7.12 on my Windows 10 PC.

calibre, version 7.12.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'E:\\Users\\Michael\\Downloads\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 7.12  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 12, 0) && Package KFX (from KFX Input) (2, 12, 0) && Barnes & Noble (1, 5, 5) && Extract ISBN (1, 6, 3) && Fantastic Fiction (1, 7, 0) && Fantastic Fiction Adults (1, 3, 1) && FictionDB (1, 4, 2) && Generate Cover (2, 3, 4) && Goodreads (1, 8, 1) && ISFDB3 (1, 4, 0) && Job Spy (1, 0, 239) && K2pdfopt Plugin (0, 5, 4) && KFX metadata reader (from KFX Input) (2, 12, 0) && From KFX (2, 12, 0) && KFX Input (2, 12, 0) && Set KFX metadata (from KFX Output) (2, 8, 0) && KFX Output (2, 8, 0) && Kobo Books (1, 9, 2) && Kobo Metadata (1, 5, 0) && Kobo Utilities (2, 16, 13) && Perrypedia (1, 9, 0) && Search The Internet (1, 11, 2) && Skoob Books (1, 5, 5) && Standard Ebooks (1, 0, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 322, in add_plugin
  File "calibre\customize\ui.py", line 525, in add_plugin
  File "calibre\customize\ui.py", line 76, in load_plugin
  File "calibre\customize\zipplugin.py", line 297, in load
  File "calibre\customize\zipplugin.py", line 392, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'E:\\Users\\Michael\\Downloads\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip the main file and load just DeDRM_plugin.zip.  Recommend using DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by Nooread** [comment]
Perfect. Thanks very much ElleKayEm. Been researching for days on this issue, and you have fixed it immediately.
