### ISSUE TITLE
DeDRM plugin in Calibre fails on a number of Kindle Books.

### ISSUE THREAD

**Issue by nothernneil** [apprenticeharper/DeDRM_tools#233]
Its great work that someone has spent the time to do this and I personally want to create PDF's of my books in case one day I supidly delete my Kindle device or worse. 

I Have tried windows 7 and 10, Calibre and 6.5.3 DeDRM.

Most books convert OK but 3 which I do own fail. Log for one below but all claim that a python function terminated unexpectedly..

calibre Debug log
calibre 2.81 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 192.0 x 192.0
physicalDpi: 267.286153846 x 267.801156069
Starting up...
Started up in 6.03 seconds with 2 books
Worker Launch took: 0.323000192642
Job: 1 Convert book 1 of 1 (Professional Application Lifecycle Management with Visual Studio 2010) finished
Convert book 1 of 1 (Professional Application Lifecycle Management with Visual Studio 2010)
	Conversion options changed from defaults:
	  sr3_replace: None
	  sr1_replace: None
	  verbose: 2
	  search_replace: '[]'
	  read_metadata_from_opf: u'C:\\Users\\neilG\\AppData\\Local\\Temp\\calibre_pajb0w\\smlcb3.opf'
	  filter_css: u''
	  sr2_search: None
	  cover: u'C:\\Users\\neilG\\AppData\\Local\\Temp\\calibre_pajb0w\\ty8pwo.jpeg'
	  sr2_replace: None
	  pdf_sans_family: u'MS Shell Dlg 2'
	  sr3_search: None
	  output_profile: 'tablet'
	  transform_css_rules: '[]'
	  sr1_search: None
	Resolved conversion options
	calibre version: 2.81.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\neilG\\AppData\\Local\\Temp\\calibre_pajb0w\\ty8pwo.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000000056A1C50>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'old_pdf_engine': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x00000000058006D8>,
	 'override_profile_size': False,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier New',
	 'pdf_mono_font_size': 16,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'MS Shell Dlg 2',
	 'pdf_serif_family': u'Times New Roman',
	 'pdf_standard_font': u'serif',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\neilG\\AppData\\Local\\Temp\\calibre_pajb0w\\smlcb3.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\neilG\AppData\Local\Temp\calibre_pajb0w\rzdae9.azw
	**Python function terminated unexpectedly**
	  Professional Application Lifecycle Management with Visual Studio 2010 (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1074, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 161, in extract_content
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Professional Application Lifecycle Management with Visual Studio 2010

Any clues? Suggestions welcome please.

**Comment by ElleKayEm** [comment]
We need to see an import log to find out what's going on with DRM removal.

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by nothernneil** [comment]
Many thanks. Import log below

calibre Debug log
calibre 2.81 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 192.0 x 192.0
physicalDpi: 267.286153846 x 267.801156069
Starting up...
Started up in 3.73 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x8b`*\x10\x08\xaa]V\x07gP[\xf0\xdd\xb8\xaa\xbc\xa0:OH\x82\xc7&\xce)F\x85\xaf\xca\x18\x03', 'C:\\Users\\neilG\\Documents\\My Kindle Content\\B003NX72Z2_EBOK.azw']
DeDRM v6.5.3: Trying to decrypt B003NX72Z2_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 2
Decrypting Mobipocket 6 ebook: Professional Application Lifecycle Management with Visual Studio 2010
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\neilG\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\neilG\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3464232321' and UserName '4e65696c47'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 2
Decrypting Mobipocket 6 ebook: Professional Application Lifecycle Management with Visual Studio 2010
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds
Added Professional Application Lifecycle Management with Visual Studio 2010 to db in: 0.5
Added 1 books in 2.0 seconds

**Comment by ElleKayEm** [comment]
Although your user name in the file path is neilG, the plugin is reading it in hex as 4e65696c47 which is NeilG with the capital N, instead of lowercase n.  For whatever reason, this messes up the key that the plugin gets from Kindle for PC.  The workaround that I've seen work for others is to create a new user account (be sure not to include any accented characters or other non-ascii characters) and install Kindle for PC, calibre, and the DeDRM plugin there.  (See [this comment](https://github.com/apprenticeharper/DeDRM_tools/issues/196#issuecomment-277914636) on a previous issue for reference.)

**Comment by nothernneil** [comment]
Thanks for he feedback and a very accurate observation which I had not noticed. The laptop on which I tried this was setup by IT and the path should have been uppercase N as in the username. I have installed all software on a second machine which I have control over (so its right) and everything works fine. Many thanks for you help.

**Comment by nothernneil** [comment]
Closing this as its now resolved. Again many thanks and keep up the good work. I like you believe that if I have paid for something I have the right to back it up particularly since my wife uses the same account and is by her own admission not so hot on computers so well done for the outstanding work.
