### ISSUE TITLE
Epub conversion 

### ISSUE THREAD

**Issue by KandiiKane** [apprenticeharper/DeDRM_tools#2332]
Hey newbie here,

I bought a book from Kobo and trying to add to my Kindle Paperwhite Signature.

Calibre 7.13 and reinstalled the new DeDRM to make sure I had the up to date one.

I for the life of me have looked everywhere I can to try different options to get this moved over. 
I have Windows 11.

Book downloads as ACSM, I have ADE downloaded, book reads fine on there. Downloaded from Kobo app as well. Use Obok and it comes over as EPUB. Right off the bat if I preview the book on Calibre it reads symbols, I've tried different conversions and it stays the same whether I use the cable, send to Kindle email(which isn't working now for me), or drop it into the files on Amazon.

Not sure if this is exactly the right place to ask but figured I'd give it a try.

**Comment by ElleKayEm** [comment]
Are you using the 10.0.9 versions of DeDRM and Obok?
https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

Sounds like the Kobo Desktop books aren't decrypting.  Try closing the Kobo app before using Obok.  Make sure the book has a closed red lock in Obok.

**Comment by KandiiKane** [comment]
This is going to sound really dumb, but I put the Obok in the plug in but not the DeDrm file. Worked like a charm. Thank you for your time!

**Comment by ElleKayEm** [comment]
Not sure what you're saying.  DeDRM takes care of the Adobe DRM from ADE books.  Obok handles the Kobo app/device books.  Glad it's working either way.
