### ISSUE TITLE
Please help me! 

### ISSUE THREAD

**Issue by Rogier1977** [apprenticeharper/DeDRM_tools#2339]
Dear friend, I tried with Caliber and DeDRM_tools_10.0.3. to unlock the DRM protection, but unfortunately this did not work. Can you please help me?

## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.
<DeDRM_tools_10.0.3>

## Title
<Monadologie. Deutsch mit einer Abhandlung über Leibniz' und Herbarts Theorien des wirklichen Geschehens von Dr. Robert Zimmermann>

## Log
<ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Foutopsporingslog
calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: nl
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: nl
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 132.7020408163265 x 133.00363636363636
[0.00] Starting up...
[0.02] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.64] GUI main window shown
Key 'B' for shortcut Doorblader annotaties is already used by Boeken bijschaven, ignoring
[0.72] main UI initialized...
[0.72] Hiding splash screen
DeDRM v10.0.3: Trying to decrypt Monadologie. Deutsch mit einer Abhandlung ++ber Leibniz und Herba.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Monadologie. Deutsch mit einer Abhandlung ++ber Leibniz und Herba.epub is a secure Adobe Adept ePub for UUID a4dab7eb-b524-40ce-a221-506b2eb2b7e2
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "C:\Users\rgkop\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 343, in adeptkeys
FileNotFoundError: [WinError 2] Het systeem kan het opgegeven bestand niet vinden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\rgkop\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 346, in adeptkeys
adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[7.53] splash screen hidden
[7.53] Started up in 7.53 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xf5\x99\xb6\xd0\xef\x84\xa9\x04\xb7\xb6\x81\x1d\xcf\x1e\xf7\xe6g\xde7\xc0\xd9\xc1+p\xe9\xfap\xf0UELa', b'C:\\Users\\rgkop\\OneDrive\\Bureaublad\\Monadologie. Deutsch mit einer Abhandlung ++ber Leibniz und Herba.epub']
Added Monadologie. Deutsch mit einer Abhandlung über Leibniz' und Herbarts Theorien des wirklichen Geschehens von Dr. Robert Zimmermann to db in: 0.2
Added 1 books in 0.9 seconds
>

**Comment by ElleKayEm** [comment]
Recommend using DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

The issue seems to be DeDRM not being able to get your key.  Do have Adobe Digital Editions on this computer and authorized with your Adobe ID?

**Comment by Rogier1977** [comment]
Thanks for the quick response. That's right. Is there anything I can do
about this? For example, by downloading the epub /acsm file to another
Computer?

Op do 8 aug 2024 om 15:32 schreef ElleKayEm ***@***.***>

**Comment by ElleKayEm** [comment]
Should work if ADE and calibre/DeDRM are on the same computer and user.

**Comment by Rogier1977** [comment]
Thanks, this worked!

Op do 8 aug 2024 om 17:38 schreef ElleKayEm ***@***.***>

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
