### ISSUE TITLE
Can't convert a book.

### ISSUE THREAD

**Issue by sarchmusic** [apprenticeharper/DeDRM_tools#234]
Having problems removing drm from a textbook. I want my phone to read it to me while I drive to work, but can't in the kindle app (that I can find anyways). Downgraded my kindle app to 1.17 (as mentioned above), still can't convert to EPUB (my phone app can read those aloud...). Here's the requested info:

which tool was used
DEDRM 6.5.3

which OS you are using
Windows 10

where the ebook file came from (device or application)
Downloaded to device through Kindle App for PC

any error messages
"Failed: Convert book 1 of 1"

a log of the DRM-removal attempt (see the FAQs on how to get a log).
Convert book 1 of 1 (Becoming Qualitative Researchers: An Introduction, 5/e)
Conversion options changed from defaults:
  transform_css_rules: '[]'
  verbose: 2
  sr2_search: None
  filter_css: u''
  sr2_replace: None
  cover: u'C:\\Users\\Me\\AppData\\Local\\Temp\\calibre_e6nxrk\\hltkg1.jpeg'
  sr3_search: None
  search_replace: '[]'
  read_metadata_from_opf: u'C:\\Users\\Me\\AppData\\Local\\Temp\\calibre_e6nxrk\\6fqfmb.opf'
  sr3_replace: None
  output_profile: 'nook'
  sr1_replace: None
  sr1_search: None
Resolved conversion options
calibre version: 2.81.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\Me\\AppData\\Local\\Temp\\calibre_e6nxrk\\hltkg1.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x046CBC90>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.NookOutput object at 0x046D5130>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Me\\AppData\\Local\\Temp\\calibre_e6nxrk\\6fqfmb.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: AZW4 Input running
on C:\Users\Me\AppData\Local\Temp\calibre_e6nxrk\ndoquy.azw4
Extracting PDF from AZW4 Container...
Converting file to html...
Python function terminated unexpectedly
  pdftohtml failed with return code: 1
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 132, in main
  File "site.py", line 109, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1074, in run
  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\azw4_input.py", line 26, in convert
  File "site-packages\calibre\ebooks\azw4\reader.py", line 57, in extract_content
  File "site-packages\calibre\ebooks\conversion\plugins\pdf_input.py", line 51, in convert
  File "site-packages\calibre\ebooks\pdf\pdftohtml.py", line 92, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

Any help would be greatly appreciated!! The tool has worked perfectly up until now...

**Comment by sarchmusic** [comment]
Saw in another post that this conversion log is likely not what you want. Here is the import log:

calibre Debug log
calibre 2.81  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && KindleUnpack - The Plugin (0, 81, 4)
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Starting up...
Started up in 27.63 seconds with 3 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['1\x16\x0bPX\x0e\x88u\xabno\t&H\xbb\xc8\x1d#\xa3Y-\xde\x8dA\x8e[19\xa7\x17\xbf-', 'C:\\Users\\Me\\Documents\\My Kindle Content\\Becoming Qualitative Researcher - Corrine Glesne.azw4']
DeDRM v6.5.3: Trying to decrypt Becoming Qualitative Researcher - Corrine Glesne.azw4
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 248
Decrypting Mobipocket 4 ebook: Becoming Qualitative Researchers: An Introduction, 5/e
Found 4 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.7 seconds
searching for kinfoFiles in C:\Users\Me\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Me\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1580492398' and UserName '4d65'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 248
Decrypting Mobipocket 4 ebook: Becoming Qualitative Researchers: An Introduction, 5/e
Found 4 keys to try after 0.9 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.9 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.9 seconds
Added Becoming Qualitative Researchers: An Introduction, 5/e to db in: 4.7
Added 1 books in 8.0 seconds

**Comment by ElleKayEm** [comment]
As it says in the log, "Cannot decode library or rented ebooks."

**Comment by sarchmusic** [comment]
A rather obvious answer. Sorry for taking up your time. The weird part is that in the past, I have had no trouble moving borrowed books to my different devices using this method. It worked fine on library books. I wonder why this one is different...? Oh well. Thanks for the help!

**Comment by ElleKayEm** [comment]
I always say that if you want to remove DRM, buy the book.  Go ahead and close this issue.
