### ISSUE TITLE
Unable to decrypt KFX DRM voucher

### ISSUE THREAD

**Issue by NickSaulnier** [apprenticeharper/DeDRM_tools#2343]
This error occurs with DeDRM v10.0.9 and Calibre 7.16 using a purchased kindle ebook (I'm using Kindle for PC v 2.4.1). Any ideas as to why it's failing? I can provide more of that log message if it's helpful.

```log
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
...
DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds
```

**Comment by ElleKayEm** [comment]
DeDRM does not currently work with books from Kindle for PC 2.4.1.  You need no later than Kindle for PC 2.4.0 and also the KFX Input plugin.

**Comment by NickSaulnier** [comment]
Awesome, thank you for the speedy response. I will see if I can downgrade to Kindle for PC 2.4.0.

**Comment by NickSaulnier** [comment]
Thanks again! DeDRM worked like a charm with Kindle for PC 2.35 (downloaded from uptodown https://kindle-for-pc.en.uptodown.com/windows/versions)

**Comment by NickSaulnier** [comment]
Thanks again! DeDRM worked like a charm with Kindle for PC 2.35 (downloaded from uptodown https://kindle-for-pc.en.uptodown.com/windows/versions)

**Comment by NickSaulnier** [comment]
Not sure if it's an easy thing to do, but I'm also willing to look into getting 2.4.1+ to work with DeDRM.
