### ISSUE TITLE
DeDRM crashes in calibre 7.11 when...

### ISSUE THREAD

**Issue by hisarsimanjuntak** [apprenticeharper/DeDRM_tools#2349]
As stated, DeDRM crashes in calibre 7.11 when I try to customise the plug-in with my Kindle serial number.

Running Mac OS X Sonoma 14.4.

**Comment by ElleKayEm** [comment]
Try DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
