### ISSUE TITLE
Calibre plugin unable to convert epub without rights.xml file

### ISSUE THREAD

**Issue by AndreasErne** [apprenticeharper/DeDRM_tools#235]
I have purchased several ebooks where the rights.xml file is missing. According to http://www.idpf.org/epub/31/spec/epub-ocf.html#sec-container-metainf-rights.xml this is valid. It means that there is no encryption present on the container level.

I am trying to modify the plugin code such that it can handle missing rights.xml files. However I am not an epub or decryption expert.

Any ideas?

**Comment by ElleKayEm** [comment]
The link you point to is referring to DRM-free files.  No need for a rights.xml file or these tools on those.  Epubs which are actually "missing" their rights.xml have them stored separately from the epub file itself.  For example, I know the Nook Windows 8/10 app stores this info in a SQLite database.  Restore this info to the epub file, and you can use these tools to remove the DRM.  Code could probably be written to do this.  However, it's easier just to avoid apps and/or sources that do this.  Where are you getting these from or how are you downloading them?

**Comment by apprenticeharper** [comment]
No response. Issue closed.
