### ISSUE TITLE
[QUESTION] Obok doesn't work on limited time free manga from Kobo Japan

### ISSUE THREAD

**Issue by matsumurae** [apprenticeharper/DeDRM_tools#2355]
## CheckList
- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Problem
Imports correctly, shows the cover and metadata. Appears decrypted .epub file but whenever I open it, just gives me a "error loading the book" message.

It doesn't work with any 期間限定無料 manga (Limited time free).  Tried with [青の祓魔師](https://books.rakuten.co.jp/rk/3a8f264567ef322cb4acd6b5f4dc7c6d/).

Did the test:
- It works with a bought manga [キングダム ハーツ FINAL MIX 1巻](https://www.kobo.com/jp/jp/ebook/_FqejVJn4TOqM_YVDWEoXw)
- It works with free book [彼女が生きてる世界線！（１）僕が悪役に転生！？【試し読み】](https://www.kobo.com/jp/jp/ebook/g-UEhwKx-D6lpHTfzwwHUg)

I guess it doesn't work because the format is different from the "normal" vs "limited" version.

## Log
<details><summary>ERROR: Fallo en la carga del libro: No se pudo abrir el libro.</summary>

```log
Failed to convert book with error:
DeDRM v10.0.9: Trying to decrypt Qing noFu Mo Shi [(Qi Jian Xian Ding Wu Li - Jia Teng He Hui.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Post-processing took 0.0 seconds
DeDRM v10.0.9: Finished after 5.7 seconds
InputFormatPlugin: EPUB Input running
on /var/folders/s3/9v3xfnw94hj_m132f858550w0000gn/C/calibre_7.18.0_tmp_hlus1he3/zvxlgq44.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 42, in <module>
  File "site.py", line 38, in main
  File "calibre/utils/ipc/worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre/srv/render_book.py", line 965, in viewer_main
  File "calibre/srv/render_book.py", line 956, in render_for_viewer
  File "calibre/srv/render_book.py", line 934, in render
  File "calibre/srv/render_book.py", line 727, in process_exploded_book
  File "calibre/srv/render_book.py", line 270, in create_cover_page
  File "calibre/srv/render_book.py", line 223, in find_epub_cover
  File "calibre/ebooks/oeb/polish/cover.py", line 286, in find_cover_image_in_page
  File "src/lxml/xpath.pxi", line 415, in lxml.etree.XPath.__call__
  File "src/lxml/apihelpers.pxi", line 48, in lxml.etree._documentOrRaise
TypeError: Invalid input object: bytes
```
</details>

## Calibre debug

<details><summary>Open to see debug message</summary>

```log
Running Obok DeDRM v10.0.9
DEBUG:    7.7 didn't find device
Obok v10.0.9
Copyright © 2012-2023 Physisticated et al.
/var/folders/s3/9v3xfnw94hj_m132f858550w0000gn/T/tmp__nz9g01
DEBUG:    7.7 got kobodir /Users/myuser/Library/Application Support/Kobo/Kobo Desktop Edition
Error parsing Kobo plist: no legacy user key found.
Localizadas 40 posibles claves que probar.
DEBUG:   10.0 BookListTableWidget:get_books - book_num: 1
DEBUG:   10.0 BookListTableWidget:get_books - book: 青の祓魔師【期間限定無料】 6
DEBUG:   10.0 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.9 - Desencriptando 青の祓魔師【期間限定無料】 6
Probando clave: b'82d8cb2614e4654484885ad884bf2a4e'
Bad JPEG: 3c3a4c
La desencriptación falló, probando la clave siguiente.
Probando clave: b'3250c590bbef1decf267ba580c350ff2'
Bad JPEG: 33e54e
La desencriptación falló, probando la clave siguiente.
Probando clave: b'dee70b43d0498a6257b8051b71acf618'
Bad JPEG: d3f0fc
La desencriptación falló, probando la clave siguiente.
Probando clave: b'f7a2da6e31d20ea0acc37815c073b8c4'
Bad JPEG: 47ddaf
La desencriptación falló, probando la clave siguiente.
Probando clave: b'6e7954022240926187c1b160ba44f258'
Bad JPEG: a7a76c
La desencriptación falló, probando la clave siguiente.
Probando clave: b'775852b9d2db6302af60f615f9814e4b'
Bad JPEG: 30b639
La desencriptación falló, probando la clave siguiente.
Probando clave: b'c09f161428211c2102cfd7d96328241d'
Bad JPEG: 1f354c
La desencriptación falló, probando la clave siguiente.
Probando clave: b'4d4d67cff15b336f2428e8058c1571b1'
Bad JPEG: b353fe
La desencriptación falló, probando la clave siguiente.
Probando clave: b'90490b8073fc39184f24bd6860b80229'
Success!
DEBUG:   14.4 DecryptAddProgressDialog::do_book_action - decrypted book: '青の祓魔師【期間限定無料】 6'
Obok DeDRM v10.0.9 - Añadido 青の祓魔師【期間限定無料】 6
Obok DeDRM v10.0.9 - Preparando resultados.
Worker Launch took: 0.03 seconds
```

**Comment by ElleKayEm** [comment]
I've seen other reports of books from Japanese accounts failing.  These books also don't have the option of getting Adobe DRM copies with ADE instead of downloading with Kobo's apps/devices.

**Comment by matsumurae** [comment]
> I've seen other reports of books from Japanese accounts failing. These books also don't have the option of getting Adobe DRM copies with ADE instead of downloading with Kobo's apps/devices.

Kobo removed the option of ADE last year (maybe more) because I've used it before. But now it states on their English FAQ ([here](https://help.kobo.com/hc/en-us/articles/360019527954-Download-books-from-your-Kobo-account-to-export-to-another-device-or-app)) that Japanese store doesn't allow for download anymore.

**Comment by ElleKayEm** [comment]
Yes, so there doesn't seem to be a way to decrypt those at least at the moment.

**Comment by matsumurae** [comment]
> Yes, so there doesn't seem to be a way to decrypt those at least at the moment.

Seems so. It works with paid + free ones, but not the "limited free time" products. I guess it works the same way as Kindle with their own limited free.

**Comment by ElleKayEm** [comment]
Do you mean borrowed with Kobo Plus?  No, those don't work with Obok from what I've seen.

**Comment by matsumurae** [comment]
> Do you mean borrowed with Kobo Plus? No, those don't work with Obok from what I've seen.

I'm not sure if it's Kobo Plus, I don't have any subscription. Those are free for limited time, the same way Amazon Japan does with Kindle ones.

**Comment by ElleKayEm** [comment]
Then, no, I was talking about when books are borrowed through a Kobo Plus subscription.  The same book would work fine if purchased (even for free).  I've never had any issue with limited time free books at either Kobo or Amazon.  They work just like purchased books.

And the book in the earlier log here does seem to be successfully DeDRMed.  It's just not something the calibre ebook viewer or calibre's conversion can handle.
