### ISSUE TITLE
[QUESTION] Fail to remove DRM from ADE 2.0

### ISSUE THREAD

**Issue by ffuentesm** [apprenticeharper/DeDRM_tools#2359]
## Title
Can't remove the DRM

### ADE 2.0.1

I am trying to convert a book I got from ebookcentral.proquest but I keep getting errors. From what I can think of, the website is converting the file for ADE 4.5 while DeAVSM and DeDRM are using 2.0 version

If anyone wants to try to solve this problem of mine. Here is the ASCM file.
[Angelique.zip](https://github.com/user-attachments/files/17264591/Angelique.zip)

**Comment by ElleKayEm** [comment]
DeDRM 10.0.9 can handle the "hardened" Adobe DRM.
