### ISSUE TITLE
Can't convert .azw3 file

### ISSUE THREAD

**Issue by bona88milan** [apprenticeharper/DeDRM_tools#236]
Hi, i can't remove the DRM protection from this file i bought directly from amazon (i'm the owner).
There's the bug list:
calibre Log di debug
calibre 2.74  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 21.59 x 21.6746666667
Starting up...
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
Started up in 6.82 seconds with 167 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['ksY\x9c\xe2v5\x1b\xfc6\xf0\xde\xeei-=7a\xa7\xfe\x120&JMf\xa8\xd8\xc4tg;', 'C:\\Users\\Bona\\Google Drive\\Allenamento e alimentazione\\The Body Solution (Italian Edition).azw3']
DeDRM v6.5.3: Trying to decrypt The Body Solution (Italian Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Body Solution (Italian Edition)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Bona\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
Added The Body Solution (Italian Edition) to db in: 3.3
Added 1 books in 4.0 seconds
Worker Launch took: 0.151000022888
Job: 1 Converti libro 1 di 1 (The Body Solution (Italian Edition)) finished
Converti libro 1 di 1 (The Body Solution (Italian Edition))
	Resolved conversion options
	calibre version: 2.74.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Bona\\AppData\\Local\\Temp\\calibre_zvhqj5\\otqeju.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0381D370>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'old_pdf_engine': False,
	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x0381D550>,
	 'override_profile_size': False,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier New',
	 'pdf_mono_font_size': 16,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'MS Shell Dlg 2',
	 'pdf_serif_family': u'Times New Roman',
	 'pdf_standard_font': u'serif',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Bona\\AppData\\Local\\Temp\\calibre_zvhqj5\\ftwwpi.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Bona\AppData\Local\Temp\calibre_zvhqj5\tfxpyt.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  The Body Solution (Italian Edition) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1064, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 146, in check_for_drm
	calibre.ebooks.DRMError: The Body Solution (Italian Edition)

PC SPEC:
Windows 10 Pro 64bit
Intel Core i7-6700 3.40GHz
16GB RAM

Thank You for the support!!

**Comment by ElleKayEm** [comment]
If that book is from or for an E-ink Kindle (not a Fire), then you need to add its serial number into the plugin customization.  Otherwise, install Kindle for PC version 1.17 ([see the FAQs](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac)) on this machine and import a copy from there.

**Comment by bona88milan** [comment]
It’s works!! Very Thanks!!

 

Da: ElleKayEm [mailto:notifications@github.com] 
Inviato: mercoledì 15 marzo 2017 05:34
A: apprenticeharper/DeDRM_tools <DeDRM_tools@noreply.github.com>
Cc: bona88milan <bona88milan@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [apprenticeharper/DeDRM_tools] Can't convert .azw3 file (#236)

 

If that book is from or for an E-ink Kindle (not a Fire), then you need to add its serial number into the plugin customization. Otherwise, install Kindle for PC version 1.17 (see the FAQs <https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac> ) on this machine and import a copy from there.

**Comment by ElleKayEm** [comment]
Good!  Go ahead and close this issue.
