### ISSUE TITLE
[QUESTION] PDF file converted from kindle for PC ebook is not good

### ISSUE THREAD

**Issue by rwfsantos** [apprenticeharper/DeDRM_tools#2360]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## My Environment
Windows 10
### Calibre: `Version` 
7.19.0
### Kindle: `Version`
Kindle for PC 2.5.0
### DeDRM: `Version`
DeDRM_tools_7.2.1

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Log de Debug
calibre 7.19  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: pt_BR
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
calibre 7.19  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: pt_BR
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 101.07357512953367
[0.00] Starting up...
[0.02] Showing splash screen...
[1.20] splash screen shown
[1.20] Initializing db...
[1.20] db initialized
[1.20] Constructing main UI...
[2.16] GUI main window shown
[2.20] main UI initialized...
[2.20] Hiding splash screen
[2.20] splash screen hidden
[2.20] Started up in 2.20 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'&?q\xed\x18N\xfe\x10\x92\xca\xc9\x15Jv\t-\\\xa9\xc9\xdcoe\xe1R\x89\xe0>D\xff\xd3\xa9[', b'C:\\Users\\anabe\\OneDrive\\Documentos\\My Kindle Content\\B07ZZLYSYM_EBOK\\CR!B5ZHR2Y5HX2678ZSHMFFP3ET5W7G.azw.md']>

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9.  Download your book with Kindle for PC 2.4.0 (70904) aka 2.4.70904.  Also it looks like you added a file that wasn't actually the main book file (azw.md).  Make sure extensions aren't hidden so you add the azw file.

**Comment by rwfsantos** [comment]
Hi LKM
I followed your tips however problem persists. There is no other azx file, only this MD file (please see attachment).
![My kindle files](https://github.com/user-attachments/assets/ca66ee53-b934-42c4-b903-5f904cebb205)

**Comment by ElleKayEm** [comment]
Looks like you have extensions for known file types hidden.  The file you want to add is the one with the blue book icon, second from the top.

**Comment by rwfsantos** [comment]
Perfect my friend, now it is working! Thank you very much!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
