### ISSUE TITLE
BOOKWALKER DRM 

### ISSUE THREAD

**Issue by Walkedharmony** [apprenticeharper/DeDRM_tools#2365]
I wanted to bring this topic back up because no one has been able to solve it as far as I know.

I read the data from XHTML in Bookwalker Windows where there is a Salted_ header. 

That is a file header for AES 256 CBC Encryption that uses openssl and a password to open the Salted. 

After the first 8 bytes then so on is the key for AES 256 and IV but even if we get it we still can't open it because we still need to open Salted with a password.

I don't know here what kind of password is used like abc123#. 

You can refute my research above with your comments.

**Comment by ElleKayEm** [comment]
Might want to start this discussion over at noDRM's DeDRM_tools instead of here at apprenticeharper's which is no longer maintained.

https://github.com/noDRM/DeDRM_tools

**Comment by Walkedharmony** [comment]
Alright

**Comment by Walkedharmony** [comment]
> Alright

Closed
