### ISSUE TITLE
Book still locked by DRM

### ISSUE THREAD

**Issue by leononi** [apprenticeharper/DeDRM_tools#2375]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
I have the most recent version of Calibre and I have installed everything but It still tells me that the books are locked by DRM. I saw a previous comment where it was suggested to download version 10.0.9, which I tried and still got nothing.

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

**Comment by ElleKayEm** [comment]
Are you using "download & transfer via usb" to get your books?  Do you have your E-ink Kindle's serial number entered into DeDRM?

**Comment by leononi** [comment]
The serial number is added to the plugin. I do not see an option anywhere that says "download & transfer via usb". I have tried adding them to the library from the device's memory and it just says it can't transfer a KFX file and to download the AZW3 file and try to add them that way, which I have also tried and had no success.

**Comment by ElleKayEm** [comment]
From the menu on your Content Library at the Amazon website.

**Comment by leononi** [comment]
Oh, yes I did that. I downloaded them that way, but I also downloaded them through the Kindle for PC, so I have them both ways.

**Comment by ElleKayEm** [comment]
If you chose the E-ink Kindle as the device when downloading and have its serial number entered correctly into DeDRM's customization, then you should be able to decrypt those copies.

**Comment by leononi** [comment]
I think I may have figured it out! My daughter was helping me download (because there are a LOT) and when when you click on "download via USB" it lists all the devices and she was selecting my Fire tablet, not my eReader. I have redownloaded several while selecting the proper device and they've converted! Just wanted to let you know in case this may be helpful for someone else in the future!

**Comment by ElleKayEm** [comment]
Yes, that method only works for E-ink Kindles, not Fires.
