### ISSUE TITLE
Can't get this to DEDRM

### ISSUE THREAD

**Issue by VaWineLover** [apprenticeharper/DeDRM_tools#2379]
This book was downloaded manually from my Kindle Content on Amazon. It is in AZW3 format.
Here is the debug data.  My email is dtiblis@yahoo.com.

Failed to initialize plugin: 'C:\\Users\\dtibl\\AppData\\Roaming\\calibre\\plugins\\Barnes & Noble.zip'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 791, in initialize_plugins
  File "calibre\customize\ui.py", line 76, in load_plugin
  File "calibre\customize\zipplugin.py", line 306, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 205, in exec_module
  File "calibre_plugins.barnes_noble.__init__", line 11, in <module>
ImportError: cannot import name 'quote' from 'urllib' (C:\Program Files\Calibre2\app\bin\python-lib.bypy.frozen\urllib\__init__.pyc)
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.22  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 18, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 18, 0) && Amazon.com Multiple Countries (1, 0, 0) && Goodreads (1, 8, 2) && Goodreads Sync (1, 16, 11) && Goodreads_Rating (3, 1, 0) && Job Spy (1, 0, 239) && KFX metadata reader (from KFX Input) (2, 18, 0) && From KFX (2, 18, 0) && KFX Input (2, 18, 0) && Obok DeDRM (7, 2, 1)
calibre 7.22  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 18, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 18, 0) && Amazon.com Multiple Countries (1, 0, 0) && Goodreads (1, 8, 2) && Goodreads Sync (1, 16, 11) && Goodreads_Rating (3, 1, 0) && Job Spy (1, 0, 239) && KFX metadata reader (from KFX Input) (2, 18, 0) && From KFX (2, 18, 0) && KFX Input (2, 18, 0) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.02] Showing splash screen...
[1.20] splash screen shown
[1.20] Initializing db...
[3.52] db initialized
[3.52] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[8.58] GUI main window shown
Job Spy has begun initialization...
Calibre, and hence Job Spy, was gracefully shut down last time?  True
Last time daemon started:  never
Last time daemon failed:  never
Total daemon starts inception_to_date:  0
Total daemon failures inception-to-date:  0
JS: ===>>> change_gui_alternating_row_colors()
Job Spy has finished initialization...
[9.38] main UI initialized...
[9.38] Hiding splash screen
[9.38] splash screen hidden
[9.38] Started up in 9.38 seconds with 15118 books
Failed to initialize plugin: 'C:\\Users\\dtibl\\AppData\\Roaming\\calibre\\plugins\\Barnes & Noble.zip'
DeDRM v7.2.1: Trying to decrypt Love, Cass _ A Brother's Keeper Standalone Companion Novel (Brother's Keeper Security Book 7).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Love, Cass : A Brother's Keeper Standalone Companion Novel (Brother's Keeper Security Book 7)
Found 13 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 13 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\dtibl\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\dtibl\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3223893732' and UserName 'dtibl'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Love, Cass : A Brother's Keeper Standalone Companion Novel (Brother's Keeper Security Book 7)
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 13 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Love, Cass : A Brother's Keeper Standalone Companion Novel (Brother's Keeper Security Book 7) to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by ElleKayEm** [comment]
Did you choose an E-ink Kindle (not a Fire) for the device?  Do you have that Kindle's serial number correctly entered in DeDRM's customization?

**Comment by VaWineLover** [comment]
I downloaded it from My Content on Amazon to my Downloads file to (Supposedly) transfer to my Kindle Paperwhite. I pulled it from there to my Calibre program which has the latest DeDRM plugin.  I cannot open it with the Reader in Calibre because it says it still has DRM. I am going to assume it is because this is a KFX?

**Comment by ElleKayEm** [comment]
No, it isn't KFX.  Just noticed you have an old version of DeDRM.  Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

And make sure your Paperwhite's serial number is in DeDRM's customization.

**Comment by VaWineLover** [comment]
Thanks, I'll try that. 

Denise 
 
  On Tue, Dec 3, 2024 at 3:42 PM, ***@***.***> wrote:   


No, it isn't KFX. Just noticed you have an old version of DeDRM. Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

And make sure your Paperwhite's serial number is in DeDRM's customization.

**Comment by VaWineLover** [comment]
Sheesh, I finally got everything to work.  Thanks so much for your help.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
