### ISSUE TITLE
When importing an .azw book to Calibre, the DRM isn't being removed. 

### ISSUE THREAD

**Issue by Azsendi** [apprenticeharper/DeDRM_tools#238]
I am on ArchLinux with the Windows version of Kindle for PC1.17.
Here's the log:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/calibre/calibre/utils/fonts/scanner.py", line 309, in run
    self.do_scan()
  File "/usr/lib/calibre/calibre/utils/fonts/scanner.py", line 327, in do_scan
    files = tuple(walk(folder))
  File "/usr/lib/calibre/calibre/__init__.py", line 528, in walk
    for record in os.walk(dir):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'utf8' codec can't decode byte 0x93 in position 6: invalid start byte

calibre Debug log
calibre 2.80  embedded-python: False is64bit: True
Linux-4.9.11-1-ARCH-x86_64-with-glibc2.2.5 Linux ('64bit', '')
('Linux', '4.9.11-1-ARCH', '#1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017')
Python 2.7.13
Linux: ('', '', '')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.7381489842 x 91.8072289157
Starting up...
DeDRM v6.5.3: Trying to decrypt B01MSD59SO_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: How a Realist Hero Rebuilt the Kingdom: Volume 1
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.5.3: Running kindlekey.py under Wine
DeDRM v6.5.3: Command line: 'WINEPREFIX="/home/azsendi" wine python.exe "/home/azsendi/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/azsendi/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
wine: cannot find L"C:\\windows\\system32\\python.exe"
DeDRM v6.5.3: Found and decrypted 0 key files
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 170, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
Started up in 9.19 seconds with 2 books
Added How a Realist Hero Rebuilt the Kingdom: Volume 1 to db in: 0.6
Added 1 books in 1.4 seconds
fixme:exec:SHELL_execute flags ignored: 0x00000100

**Comment by ElleKayEm** [comment]
Not being a Linux user myself, I can only tell you what I've seen mentioned about this before. There's an issue for some Linux systems that keeps DeDRM from finding Python. (You do need to have Python and PyCrypto installed under Wine.) Try manually running the key retrieval script under Wine, and import the key into calibre:

wine python.exe "/home/azsendi/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/azsendi/winekeysdir"

(You may need to create /home/azsendi/winekeysdir first, and then the retrieved key(s) should be put there.)

**Comment by apprenticeharper** [comment]
No response. Closed.
