### ISSUE TITLE
Problem with Getting Key for Configuring DeDRM  plugin 

### ISSUE THREAD

**Issue by ichinagam** [apprenticeharper/DeDRM_tools#239]
Back in 2011-2012,  I downloaded about 200 ebooks, mainly Barnes and Noble and Kobo titles, to my PC. I loaded them into Calibre, followed directions for installing the DeDRM plug-in for Calibre.  However, DRM is not being removed from the Barnes and Noble books, I think, because I'm not able to get the Barnes and Noble key using my email address and password.   I thought I might be able to use Nook Study to get the key, but I understand it's been replaced by an app called Yuzu, which is not support on Windows 7. which is the operating system of my computer.  What options do I have?

**Comment by ElleKayEm** [comment]
If you downloaded the B&N books that long ago, then they definitely won't have your current key anyway.  Back then they were keyed to your default credit card at the time of download.  They changed to non-cc based keys a couple years ago.  I suggest downloading fresh copies with Nook for PC.  Here's a direct link to the installation file:

http://images.barnesandnoble.com/PResources/download/eReader2/bndr2_setup_latest.exe

Once you've logged into Nook for PC, then you should be able to retrieve the B&N key in the DeDRM plugin customization.

**Comment by ichinagam** [comment]
Thanks for the advice--I'll give it a try.
Moon Ichinaga  

Sent from Yahoo Mail. Get the app 

    On Sunday, March 19, 2017 7:22 AM, ElleKayEm <notifications@github.com> wrote:
 

 If you downloaded the B&N books that long ago, then they definitely won't have your current key anyway. Back then they were keyed to your default credit card at the time of download. They changed to non-cc based keys a couple years ago. I suggest downloading fresh copies with Nook for PC. Here's a direct link to the installation file:http://images.barnesandnoble.com/PResources/download/eReader2/bndr2_setup_latest.exeOnce you've logged into Nook for PC, then you should be able to retrieve the B&N key in the DeDRM plugin customization.—

**Comment by apprenticeharper** [comment]
If that didn't fix things, start  a new issue. Closed.
