### ISSUE TITLE
Problems Removing DRM From an AZW3 eBook

### ISSUE THREAD

**Issue by dshmidt1** [apprenticeharper/DeDRM_tools#24]
I have version 2.33 of Calibre and installed the latest version of the DeDRM plugin.  However, when I attempted to remove the DRM from an AZW3 ebook, it failed.  Here's what I got as the results:

calibre 2.33  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 3.24 seconds with 50 books
DeDRM v6.2.2: Trying to decrypt The Skull Throne- Book Four of The Demon Cycle (
The Demon Cycle Series 4).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Skull Throne: Book Four of The Demon Cycle
 (The Demon Cycle Series 4)
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.2.2: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.2.2: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Denis\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.2.2: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugi
ns
  File "calibre_plugins.dedrm.__init__", line 579, in run
  File "calibre_plugins.dedrm.__init__", line 530, in KindleMobiDecrypt
DeDRMError: DeDRM v6.2.2: Ultimately failed to decrypt after 0.2 seconds
Added The Skull Throne: Book Four of The Demon Cycle (The Demon Cycle Series 4)
to db in: 0.3
Added 1 books in 1.6 seconds

Please let me know if you have any advice.  Thanks!

**Comment by ElleKayEm** [comment]
If that's from an E-ink Kindle, then you need to enter its serial number into the plug-in's configuration dialog.  Otherwise, install Kindle for PC and import a copy of the book from there.
