### ISSUE TITLE
DRM removal not working 

### ISSUE THREAD

**Issue by jissemalin** [apprenticeharper/DeDRM_tools#240]
Hi, tried everything but tool is not working. Tried 2 different books, both bought at amazon. 
tried adding file from Kindle, from Kindle for PC and as download. Nothing works.

Computer running windows 10 Home
version 1607
64 bit operating system

calibre Debug log
calibre 2.82 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.5518394649 x 81.6428571429
Starting up...
Storage number map:
{(7L, 0L): [(1L, 'C')],
 (7L, 1L): [(1L, 'D')],
 (7L, 2L): [(1L, 'F')],
 (7L, 3L): [(1L, 'G')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\90D422014157046D&0: StorageDeviceNumber(type=7L, number=3L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=16)
{u'drive_letters': ['G'],
 u'pnp_id_map': {'G': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#90d422014157046d&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'G': (3L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: G:\ documents
Job: 2 Set library information finished
No details available.
Job: 1 Get device information finished
No details available.
DEBUG:    0.2 USBMS: scan from root False G:\documents
DEBUG:    0.5 USBMS: count found in cache: 353, count of files in metadata: 353, need_sync: False
DEBUG:    0.5 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.5 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.5 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 353
DeviceJob: set_books_in_library finished: time= 0.010999917984
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Started up in 8.72 seconds with 2249 books
DeDRM v6.5.3: Trying to decrypt The Fast Metabolism Diet- Lose Up to 20 Pounds in 28 Days- Eat More Food & Lose More Weight (1).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Fast Metabolism Diet: Lose Up to 20 Pounds in 28 Days: Eat More Food & Lose More Weight
Found 6 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Gustafsson\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Gustafsson\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4195372943' and UserName '47757374616673736f6e'
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
Added The Fast Metabolism Diet: Lose Up to 20 Pounds in 28 Days: Eat More Food & Lose More Weight to db in: 1.6
Added 1 books in 2.4 seconds

**Comment by ElleKayEm** [comment]
If that book is from or for an E-ink Kindle (not a Fire), then you need to enter its serial number into the plugin customization.  Otherwise, make sure you're using version 1.17 or earlier of Kindle for PC on the same machine and user as calibre, download a fresh copy of the book, and import that.  If you need to roll back to 1.17, see the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by jissemalin** [comment]
Wow, that worked!!! Downloaded version 1.17 of Kindle for PC.
(serial number into plugin was already done).

Thanks,

Ingrid
