### ISSUE TITLE
The DRM for kindles stopped working

### ISSUE THREAD

**Issue by MzPep** [apprenticeharper/DeDRM_tools#241]
I have updated... it just no longer works.  I have tried installing the update again but still no luck

**Comment by ElleKayEm** [comment]
See if this solves your issue:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

If not, post an import log.

**Comment by apprenticeharper** [comment]
No response. Closed.
