### ISSUE TITLE
Add a software License

### ISSUE THREAD

**Issue by saxbophone** [apprenticeharper/DeDRM_tools#244]
Although I assume the software is provided here so others may use it, technically (at least according to United States law on software copyright and possibly equivalent laws of many other jurisdictions) anyone acquiring the source code does not have the right to run it :thinking: 

I can see from having a little dig into the source code that some of the files are individually licensed, so for these such permissions are granted but others are not.

Adding a License for the project as a whole may be a bit tricky as there currently are multiple source files with different licenses, from many different authors (the permission of whom may need to be sought if you wanted to apply a license to their work). Any combination of licenses that results will need to be chosen carefully to ensure that the work as a whole is 'compatible'.

**Comment by saxbophone** [comment]
Hmmm, from taking a closer look, a lot of the source seems to be **GPL v3** - given it's not permissible to re-license GPL'ed stuff under another more permissive license, one option may be to license the project as a whole as **GPL v3** (assuming this is allowed by the other sources which use the more-permissive MIT & BSD licenses, which I think it is but 'tis worth checking for sure).

**Comment by apprenticeharper** [comment]
I'm not sure it's worth the effort. Some commercial companies already take the code and use it in their commercial products anyway, without any kind of licence.

It's also probably impossible. Many of the authors used pseudonyms, and are no longer active.

However, if you feel like tracking down all the authors and getting explicit permission from them, I'll happily add a GPL or less restrive licence for the bits I've done.

**Comment by saxbophone** [comment]
Hmmm, I see your dilemma! 

I may have another dig through the source code some time...

**Comment by saxbophone** [comment]
And hmmm, unless those companies use it in open-source products (unlikely) then they're breaking the GPL :disappointed: — unless they're providing a web service, which the GPL does not protect...

**Comment by haraldkoch** [comment]
Since you mentioned the United States in the issue, I'll mention the DMCA... :)

**Comment by saxbophone** [comment]
@haraldkoch haha, now that you mention it, I can't recall what the DMCA says on 'DRM circumvention tools' but I suspect it may not have a favourable opinion of them...

It would be rather ironic if a DRM-circumvention project tried to use the DMCA to enforce its GPL copyright... :)

**Comment by apprenticeharper** [comment]
I'm going to close this issue, since I don't see any way to apply a licence, given the numerous anonymous authors.

**Comment by saxbophone** [comment]
Sure, guess there's nothing else that can be done.

Note to anonymous authors: License your work! If you're anonymous, public
domain may be best :wink:
