### ISSUE TITLE
DeDRM Calibre plugin doesn't work (Windows 10, purchased Kindle ebook)

### ISSUE THREAD

**Issue by Senjuti** [apprenticeharper/DeDRM_tools#245]
DeDRM Calibre plugin doesn't work for Amazon Kindle ebook. I've attached the relevant details, what am I doing wrong? 
---
Computer: Windows 10
Book obtained: Amazon Canada Kindle Store
---
calibre Debug log
calibre 2.53  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Loaded cached store plugin for: Archive.org at version: 4
Loaded cached store plugin for: Amazon Kindle at version: 14
Loaded cached store plugin for: Amazon UK Kindle at version: 14
Loaded cached store plugin for: Ebookpoint at version: 8
Loaded cached store plugin for: Legimi at version: 8
Loaded cached store plugin for: Virtualo at version: 9
Loaded cached store plugin for: Smashwords at version: 4
Loaded cached store plugin for: Google Books at version: 4
Loaded cached store plugin for: Nexto at version: 4
Loaded cached store plugin for: Kobo at version: 6
Loaded cached store plugin for: Amazon ES Kindle at version: 14
Loaded cached store plugin for: Amazon AU Kindle at version: 4
Loaded cached store plugin for: Amazon IN Kindle at version: 4
Loaded cached store plugin for: Woblink at version: 13
Loaded cached store plugin for: Amazon IT Kindle at version: 14
Loaded cached store plugin for: Amazon CA Kindle at version: 6
Loaded cached store plugin for: Amazon DE Kindle at version: 14
Loaded cached store plugin for: Amazon FR Kindle at version: 14
Loaded cached store plugin for: Publio at version: 7
Started up in 5.85 seconds with 0 books
Storage number map:
{(7L, 0L): [(4L, 'C'), (5L, 'D')], (7L, 1L): [(1L, 'F')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\G090G1056427053Q&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=11)
{u'drive_letters': ['F'],
 u'pnp_id_map': {'F': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#g090g1056427053q&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'F': (1L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
Job: 1 Get device information finished
No details available.
Job: 2 Set library information finished
No details available.
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: F:\ documents
DEBUG:    0.1 USBMS: scan from root False F:\documents
DEBUG:    0.2 USBMS: count found in cache: 153, count of files in metadata: 153, need_sync: False
DEBUG:    0.2 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 153
DeviceJob: set_books_in_library finished: time= 0.00600004196167
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 2 Set library information finished
No details available.
Job: 3 Get list of books on device finished
No details available.
DeDRM v6.5.3: Trying to decrypt B01ER6Z86S_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\Senjuti\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Senjuti\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1578390826' and UserName '53656e6a757469'
DeDRM v6.5.3: Found 1 new key
DeDRM v6.5.3: Ultimately failed to decrypt after 0.5 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 153, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.5 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 358, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 270, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 488, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 273, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 301, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B01ER6Z86S EBOK to db in: 1.6
Added 1 books in 2.9 seconds

**Comment by ElleKayEm** [comment]
From the log:  "Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet."

See the FAQs:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by apprenticeharper** [comment]
Closed.
