### ISSUE TITLE
Some nook ebooks appear to have invalid encryption keys

### ISSUE THREAD

**Issue by seebs** [apprenticeharper/DeDRM_tools#246]
I have a pile of Nook books, and about half of them decrypt. I've been invoking ignoble.py directly to see what's happening, and adding debug logs. The problem is **not** with the user encryption key, so far as I can tell. Rather, it's around here:

            bookkey = aes.decrypt(bookkey.decode('base64'))
            bookkey = bookkey[:-ord(bookkey[-1])]
            encryption = inf.read('META-INF/encryption.xml')
            decryptor = Decryptor(bookkey[-16:], encryption)

In affected books, this produces an empty string.

Dumping the bookkey values here, before and after this:

bookkey: er8mDBvsQZDD+i3Bq59pofU6nt2jjlF+v9Bi62S9EW5aFyvMHFvLnKRNu/wzss3e
decrypted: 59:90:8e:47:c1:9b:79:b4:a5:18:a6:57:b7:12:5a:c5:92:bb:43:8c:bd:9a:12:53:7c:c7:c8:9c:bf:6c:b2:9f:58:d6:e3:9e:bc:8f:35:9a:b4:83:52:3a:91:20:43:49

As you can see, the value :49 at the end doesn't seem likely to work here. A working book looks more like this:

bookkey: osgfcrcb6Nduvpz4EcOh8t1LMHNP6zP5Zu9/ep+2SXaGid/FQRmWYxSsQuK/rZDH
decrypted: 85:06:d9:b7:8c:e2:0e:b2:e1:61:d0:aa:9c:e8:db:bc:8d:96:00:0c:e0:e4:03:9c:ac:9b:a1:0c:b8:ed:ff:ad:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10

In this case, you can see that the last 16 bytes are all :10, or 16, so we strip the last 16 bytes, and then use the 16 bytes before that as the key.

**Comment by seebs** [comment]
Nevermind, I just realized that this is probably happening because the "decrypted" key is decrypted using the provided .b64 key.

So now I'm down to "I have epub files which my nook can read, but which I can't read. Probably they're older files from before the key changed. So I just have to archive them from the nook then redownload them.

**Comment by apprenticeharper** [comment]
Nicely diagnosed. That's PKCS5 padding. Closed.
