### ISSUE TITLE
Kindle DeDRM on linux without wine integration

### ISSUE THREAD

**Issue by andrewbaxter** [apprenticeharper/DeDRM_tools#247]
The usage of wine was not straightforward for me
1. winetricks python26 doesn't put python.exe in system32; you have to edit the registry to modify PATH afaict.  I'm not sure how it's expected to be installed.
2. My wine couldn't access the python script outside the prefix, maybe because it was sandboxed

I worked around it by exporting on the command line.  I just 
1. copied the DeDRM/ directory from the plugin zip/installation folder into `drive_c`
2. ran `wine 'C:\Python26\python.exe' 'C:\DeDRM\libraryfiles\kindlekey.py'`
3. selected the key file via the plugin config in calibre

This is more of an info dump than an issue, maybe.

**Comment by apprenticeharper** [comment]
It's certainly true that the Linux instructions need updating, and possibly some code changes are needed. But that requires someone to take the time to go through it carefully with current software and document the process.

**Comment by apprenticeharper** [comment]
Someone updated the Linux instructions. I haven't checked them, but worth a go?

**Comment by daniexj** [comment]
Are they in the 6.5.4 updated readme?

**Comment by apprenticeharper** [comment]
Yes, somewhere.

**Comment by Iey4iej3** [comment]
Sorry, I need to ask a question: why is `wine` necessary in `DeDRM`? I mean, I only use it during the importation of the DRM azw3 file. Seemingly this is more-or-less algorithmic, I don't see how `Windows` components play some role.

**Comment by ElleKayEm** [comment]
If you're DeDRMing books from programs installed under wine -- Kindle for PC or Adobe Digital Editions.

**Comment by Iey4iej3** [comment]
I am not, at least superficially, that case. I downloaded the `azw3` file from amazon (website), then I import it into `calibre`. I noticed an initialization of `wine` (I manually delete wine configurations after each usage) was triggered.

**Comment by ElleKayEm** [comment]
If you don't have the correct Kindle serial number entered, then DeDRM tries to find a Kindle for PC key.  But other than that, I don't know.

**Comment by Iey4iej3** [comment]
Ah, thanks for clarifications, you are correct. The first time I tried I did not input the serial number. Seemingly it is more intuitive to pop up a message (about the possibility of an incorrect serial number) before invoking `wine`.

**Comment by ElleKayEm** [comment]
DeDRM just sees an Amazon file and if it doesn't have a correct key already saved (either from the Kindle app or a serial number), it tries to get it.
