### ISSUE TITLE
Kobo drm

### ISSUE THREAD

**Issue by Coldman47** [apprenticeharper/DeDRM_tools#248]
I've just recently bought a Kobo book and tried to De-drm it using tools 6.5.3 Using the De-Drm windows program it ran and said success. Looked at the log that was created, it said it wasn't Drm'ed, Tried opening the original file with an added epub ext with ADE it will not open. Loaded file (with epub ext) in calibre, open with view - print is garbage. Obok is added to calibre. What am I doing wrong

**Comment by Coldman47** [comment]
Also, I tried to use the Kobo tool in other tools, when  i opened the py script it doesn't show my new book in the list. Found the file that the list came from, but don't know how to open it to edit the list

**Comment by ElleKayEm** [comment]
Did you download the book with Kobo desktop or with Adobe Digital Editions?

**Comment by Coldman47** [comment]
I downloaded with the Kobo desktop. It is in the new epub3 format with Adobe Drm. I forgot I could download an acsm file from Kobo store. I did that, then downloaded the file with ADE 4.5.4. I was able to use the windows de-drm bat file to remove the DRM. So, everything is ok with what I need from the book.
Other questions still there; why wasn't the obok.py able to find the Kobo book? Why wasn't the Windows De-Drm able to see that the Kobo file was incrypted? Why wasn't Calibre able to decrypt the book with the obok plugin installed? I'll leave those questions to you guys since I got a working copy of the book

**Comment by ElleKayEm** [comment]
I don't know.  I'm having no issue with Obok.  Still not sure what you were doing.  With Obok you don't import books into calibre the normal way (as you do with DeDRM).  You use the Obok interface.  Am I misunderstanding what you were trying to do?

(By the way, stick with ADE 2.0.1 or you could end up with the new Adobe DRM that can't be removed.)

**Comment by apprenticeharper** [comment]
I don't understand the original issue. Closed.
