### ISSUE TITLE
DRM not removed | WIN10 / Calibre 2.82 / Kindle 1.17.1

### ISSUE THREAD

**Issue by Xposhox** [apprenticeharper/DeDRM_tools#249]
Hello,
could you please analyse the diagnostic protocol and maybe help me with this?

`calibre Fehlerdiagnoseprotokoll
calibre 2.82 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Starting up...
Started up in 5.85 seconds with 6 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\ta\x87\x97\x08\xa6zN\x9d\x12\xc1\x16X\x8a\x9f\x0b\xf9o\x98\x11\xc6\x9e\xf1\xdb{\xc9:\xad>\xae\xdaE', 'C:\\Users\\Vorname Lo\xc3\x9fau\\Documents\\My Kindle Content\\B00IZN1S9Q_EBOK.azw']
DeDRM v6.5.3: Trying to decrypt B00IZN1S9Q_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Auf die Masse, fertig, CROWDFUNDING, los!: Was Sie fÃ¼r ein erfolgreiches Crowdfunding-Projekt wissen mÃ¼ssen (German Edition)
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Vorname Loau\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Vorname Loau\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3140483440' and UserName '53746566616e204c6fdf6175'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Auf die Masse, fertig, CROWDFUNDING, los!: Was Sie fÃ¼r ein erfolgreiches Crowdfunding-Projekt wissen mÃ¼ssen (German Edition)
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Auf die Masse, fertig, CROWDFUNDING, los!: Was Sie für ein erfolgreiches Crowdfunding-Projekt wissen müssen (German Edition) to db in: 0.5
Added 1 books in 1.4 seconds
Worker Launch took: 0.230000019073
`

**Comment by ElleKayEm** [comment]
Looks like you have a special character in your Windows user name.  Try creating a new user account without any non-ASCII characters.  Install Kindle for PC, calibre, and the DeDRM plugin there.

**Comment by apprenticeharper** [comment]
No response. Closed.
