### ISSUE TITLE
ADE 2.01 Win 10 Calibre 2.82 epub won't convert but readable in ADE

### ISSUE THREAD

**Issue by symcoxkd** [apprenticeharper/DeDRM_tools#252]
I can see the book fine in ADE 2.01, which is listed in the FAQ as the correct version of ADE to use with the Calibre plugin.  The book is not viewable in Calibre's reader and cannot be converted to mobi.  Attaching the debug.  Any thoughts about what is going wrong here would be appreciated.

calibre Debug log
calibre 2.82  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Kindle and Mobipocket DeDRM (0, 4, 13) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5) && Inept Epub DeDRM (0, 1, 7) && Find Duplicates (1, 6, 2) && Kindle Collections (1, 7, 17) && Quality Check (1, 9, 11) && Save To Format (0, 0, 6) && eReader PDB 2 PML (0, 0, 6) && Inept PDF DeDRM (0, 1, 5) && Webscription (1, 1, 0) && Ignoble Epub DeDRM (0, 1, 6)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 99.2372093023 x 98.7777777778
Starting up...
Started up in 7.79 seconds with 1378 books
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'D')],
 (7L, 1L): [(1L, 'F')],
 (7L, 2L): [(1L, 'E'), (2L, 'A'), (4L, 'B')],
 (7L, 3L): [(1L, 'G')],
 (7L, 4L): [(1L, 'H')],
 (7L, 5L): [(1L, 'I')],
 (7L, 6L): [(1L, 'J')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\B01B15022505039R&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=12)
{u'drive_letters': ['F'],
 u'pnp_id_map': {'F': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#b01b15022505039r&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'F': (1L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: F:\ documents
DEBUG:    0.1 USBMS: scan from root False F:\documents
DEBUG:    0.2 USBMS: count found in cache: 41, count of files in metadata: 41, need_sync: False
DEBUG:    0.2 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 41
DeviceJob: set_books_in_library finished: time= 0.007000207901
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 2 Set library information finished
No details available.
Job: 1 Get device information finished
No details available.
Job: 3 Get list of books on device finished
No details available.
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xb9\\\x05\xf1\x1eC\xff\xd5\xf4\xbd\x826\xd4\xb3\x7fyR\xf6\xeci\xd2\xd8\xba1\x8bS\x94\xe9v\x9e\xcc\xa7', 'C:\\Users\\keith symcox\\Documents\\My Digital Editions\\Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harb.epub']
DeDRM v6.5.3: Trying to decrypt Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harb.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harb.epub is a secure Adobe Adept ePub
DeDRM v6.5.3: Trying Encryption key default_key
Could not decrypt tjbkpa.epub. Wrong key
DeDRM v6.5.3: Failed to decrypt with key default_key after 0.3 seconds
DeDRM v6.5.3: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v6.5.3: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 337, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 392, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
IneptEpub: Using pycrypto.
IneptEpub: Calibre configuration directory = C:\Users\keith symcox\AppData\Roaming\calibre
IneptEpub: Couldn't Retrieve key from ADE install.
Running file type plugin Inept Epub DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.ineptepub.__init__", line 433, in run
ADEPTError: IneptEpub - No keys found. Check keyfile(s)/ADE install
IgnobleEpub: Using PyCrypto.
IgnobleEpub: Calibre configuration directory = C:\Users\keith symcox\AppData\Roaming\calibre
IgnobleEpub: No keyfiles found. Checking plugin customization string.
Running file type plugin Ignoble Epub DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.ignobleepub.__init__", line 319, in run
IGNOBLEError: IgnobleEpub - No keys found. Plugin not configured.
Added Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harbor ; Turbulent Sea ; Hidden Currents to db in: 1.3
Added 1 books in 2.6 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x051BAEF0>> ignored
Worker Launch took: 0.147000074387
Job: 4 Convert book 1 of 1 (Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harbor ; Turbulent Sea ; Hidden Currents) finished
Convert book 1 of 1 (Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harbor ; Turbulent Sea ; Hidden Currents)
	Conversion options changed from defaults:
	  filter_css: u''
	  sr2_replace: None
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\KEITHS~1\\AppData\\Local\\Temp\\calibre_4ir1vi\\iehfyv.opf'
	  sr3_search: None
	  sr3_replace: None
	  sr1_search: None
	  output_profile: 'kindle'
	  search_replace: '[]'
	  sr1_replace: None
	  transform_css_rules: '[]'
	  sr2_search: None
	Resolved conversion options
	calibre version: 2.82.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x04B64D50>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x04B760D0>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\KEITHS~1\\AppData\\Local\\Temp\\calibre_4ir1vi\\iehfyv.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\KEITHS~1\AppData\Local\Temp\calibre_4ir1vi\5rcqll.epub
	WARNING: Header ('OEBPS/components/003_xhtml/feeh_9780515141542_oeb_cover_r1.xhtml') and directory ('OEBPS/components/003_xhtml/feeh_9780515141542_oeb_cover_r!\xc1\xca.\x84\xa9o') filenames do not match inside ZipFile
	Using directory filename 'OEBPS/components/003_xhtml/feeh_9780515141542_oeb_cover_r!\xc1\xca.\x84\xa9o'
	WARNING: Header ('OEBPS/components/002_xhtml/19_oceansoffire_ch09.xhtml') and directory ('OEBPS/components/002_xhtml/19_oceansoM\xf2\xca.`\xbao\x01\xfb\x7f6\t\xfe\x07.\x00') filenames do not match inside ZipFile
	Using directory filename 'OEBPS/components/002_xhtml/19_oceansoM\xf2\xca.`\xbao\x01\xfb\x7f6\t\xfe\x07.\x00'
	WARNING: Header ('OEBPS/components/005_xhtml/feeh_9780515145069_oeb_ack_r1.xhtml') and directory ('OEBPS/components/\x05\xd0\xca.\xa8\x98o\x01\xaf~6\t\x15(.\x00\x00\x10\x00\x00\x10\xce`\t\xa8\x9cO\x08\x0e\x18.\x00PK\x01\x02\n\x00\n\x00\x00\x00\x00\x00}') filenames do not match inside ZipFile
	Using directory filename 'OEBPS/components/\x05\xd0\xca.\xa8\x98o\x01\xaf~6\t\x15(.\x00\x00\x10\x00\x00\x10\xce`\t\xa8\x9cO\x08\x0e\x18.\x00PK\x01\x02\n\x00\n\x00\x00\x00\x00\x00}'
	Python function terminated unexpectedly
	  5rcqll.epub (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1074, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 268, in convert
	calibre.ebooks.DRMError: 5rcqll.epub

**Comment by ElleKayEm** [comment]
You can remove all the old individual file type DeDRM plugins.  Is ADE authorized with your Adobe ID?

**Comment by symcoxkd** [comment]
ADE is authorized with the Adobe ID.

I show that I am using Inept Epub deDRM 0.1.7 in the file type plugins.  Do you mean to say that this is not the correct file?

Do you mean to remove the DeDRM plugins from the 6.5.3 zip file that I just added to Calibre?  Won’t that get rid of the ability to remove DRM from my Kindle files also?

I am confused.  How will removing the possibility of dedrm help remove drm?

**Comment by ElleKayEm** [comment]
No, I'm saying that DeDRM (6, 5, 3) replaces all of these:

Kindle and Mobipocket DeDRM (0, 4, 13)
K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5)
Inept Epub DeDRM (0, 1, 7)
Inept PDF DeDRM (0, 1, 5)
Ignoble Epub DeDRM (0, 1, 6)

So you can remove those old plugins.  I don't know if they would be causing any problem, but they're not needed.

**Comment by symcoxkd** [comment]
Thank you for the information about the clean up.  I removed those plugins, then restarted Calibre and attempted the epub download again.

Unfortunately, it still doesn’t read.  I ran it in debug mode, and this is the debug log.  Any thoughts would be appreciated.

calibre Debug log
calibre 2.82  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Find Duplicates (1, 6, 2) && Webscription (1, 1, 0) && eReader PDB 2 PML (0, 0, 6) && Save To Format (0, 0, 6) && Quality Check (1, 9, 11) && Kindle Collections (1, 7, 17)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 99.2372093023 x 98.7777777778
Starting up...
Started up in 6.15 seconds with 1378 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xa8\x92v\xee\xbe\xa2\xbe\xd1i\xdf\xb4{\r\xcd\xac\xc6\x1d\xb7\xa9Zj\x13\xee\x17n\xb0c\x0b\xd8&\xc7\x14', 'C:\\Users\\keith symcox\\Documents\\My Digital Editions\\Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harb.epub']
DeDRM v6.5.3: Trying to decrypt Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harb.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harb.epub is a secure Adobe Adept ePub
DeDRM v6.5.3: Trying Encryption key default_key
Could not decrypt bp2efr.epub. Wrong key
DeDRM v6.5.3: Failed to decrypt with key default_key after 0.3 seconds
DeDRM v6.5.3: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v6.5.3: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 337, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 392, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Added Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harbor ; Turbulent Sea ; Hidden Currents to db in: 1.1
Added 1 books in 2.2 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x05F45490>> ignored
Worker Launch took: 0.155999898911

**Comment by pdurrant** [comment]
It looks to me like the current Adobe key can't be retrieved. I thought there was something in the FAQs about that, but I can't see it now.

If you have definitely used an Adobe ID to register ADE, then what you need to do is to completely remove ADE from your system, including any preferences or registry entries, and then re-install ADE 2.0.1, and re-register with your Adobe ID (and just one Adobe ID). Then the tools should be able to retrieve your key.

**Comment by symcoxkd** [comment]
I took your advice and went into the registry and deleted the activation folder in the Adobe subfolder after uninstalling version 2.01 of ADE.  I then restarted the system, reloaded the ADE and re downloaded the ascm file.
ADE required a new activation, which I did with my email and password (same as before).
Book visible and readable in ADE.  Still not portable to Calibre.
It appears to not be able to find the registry key.

Details follow…

calibre Debug log
calibre 2.82  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Save To Format (0, 0, 6) && Webscription (1, 1, 0) && Quality Check (1, 9, 11) && Find Duplicates (1, 6, 2) && eReader PDB 2 PML (0, 0, 6) && Kindle Collections (1, 7, 17)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 99.2372093023 x 98.7777777778
Starting up...
Started up in 5.38 seconds with 1378 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['js\x0b\xb2M\xde&\x87\x85\xcf\x95\xe0\xf3\xde_\x8d \xfe\xde\x190Oo\x13Kf\xd5\xa96\xdb\xe3\xe8', 'C:\\Users\\keith symcox\\Documents\\My Digital Editions\\Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harb.epub']
DeDRM v6.5.3: Trying to decrypt Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harb.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harb.epub is a secure Adobe Adept ePub
DeDRM v6.5.3: Trying Encryption key default_key
Could not decrypt dqfdhy.epub. Wrong key
DeDRM v6.5.3: Failed to decrypt with key default_key after 0.4 seconds
DeDRM v6.5.3: Looking for new default Adobe Digital Editions Keys after 0.4 seconds
DeDRM v6.5.3: Exception when getting default Adobe Key after 0.4 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 337, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 392, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds.
Added Magic in the Wind ; Oceans of Fire ; Dangerous Tides ; Safe Harbor ; Turbulent Sea ; Hidden Currents to db in: 1.4
Added 1 books in 2.9 seconds
Worker Launch took: 0.15700006485

**Comment by pdurrant** [comment]
I would suggest trying again and wiping out anything that mentions adobe from preferences and the registry, not just those things that look like they belong to ADE activation.

**Comment by symcoxkd** [comment]
Success!
What ended up working was deleting the entire Adobe entry in the registry, deleting anything that might use Adobe, like Bibliotekia (Cloud reader) and uninstalling all Adobe products.  I then deleted My Digital Editions folder in case there was a hidden file I couldn’t find.

At this point, reinstallation went fine and the file  is now readable in Calibre.

Thanks guys!

**Comment by ElleKayEm** [comment]
Glad to hear it!  Thanks for letting us know what worked.  If you're all set, then you can close this issue.
