### ISSUE TITLE
Hey im having troubles with Barnes and Noble

### ISSUE THREAD

**Issue by saintmichael95** [apprenticeharper/DeDRM_tools#253]
So, I purchased a couple books from B&N not knowing that you couldn't download from there anymore and it's very frustrating. I have followed the instructions in the B_and_N_Download_Helper folder under Other Tools but when I try to install the user script for greasemonkey with this link: http://userscripts.org/scripts/source/152985.user.js
 I get an error:
ERROR
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.187.109.170:80

**Comment by ElleKayEm** [comment]
The script is here: http://userscripts-mirror.org/scripts/source/152985.user.js

Unfortunately that script hasn't been updated to work with the changes to the B&N website.

I recommend downloading your books with Nook for PC which can be found here:

http://images.barnesandnoble.com/PResources/download/eReader2/bndr2_setup_latest.exe

**Comment by apprenticeharper** [comment]
The script is included but unsupported. I don't think it works any more, but perhaps someone can work out whether it can be updated.
