### ISSUE TITLE
Unicode equal comparison failed to convert both arguments to Unicode?

### ISSUE THREAD

**Issue by tonstantincanzt** [apprenticeharper/DeDRM_tools#254]
Any idea?

calibre Fehlerdiagnoseprotokoll
calibre 2.82  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.6235294118 x 94.5931034483
Starting up...
Started up in 7.70 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['&\xcd<\xcb:\x0cb\x1f\xfbd\xf7\x07\xf9\x9a\xddS\x04\x02\x9d\xf8}\x1b\xea`YP4IX\xe5\xe6t', 'C:\\Users\\Constantin Ehrchen\\Documents\\My Digital Editions\\Homo Deus A Brief History of Tomorrow - Kopie.epub']
DeDRM v6.5.3: Trying to decrypt Homo Deus A Brief History of Tomorrow - Kopie.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: Homo Deus A Brief History of Tomorrow - Kopie.epub is a secure Adobe Adept ePub
DeDRM v6.5.3: Trying Encryption key default_key
DeDRM v6.5.3: Decrypted with key default_key after 1.1 seconds
DeDRM v6.5.3: Finished after 1.1 seconds
H:\Program Files (x86)\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
H:\Program Files (x86)\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Homo Deus: A Brief History of Tomorrow to db in: 0.2
Added 1 books in 2.4 seconds

**Comment by ElleKayEm** [comment]
Does there seem to be any issue with the successfully decrypted book?

**Comment by tonstantincanzt** [comment]
This is weird but it works now! Haven't changed anything and yesterday it didnt work.

Can be closed, thank you!

**Comment by ElleKayEm** [comment]
Go ahead and close it then.
