### ISSUE TITLE
epub with DRM for kindle 

### ISSUE THREAD

**Issue by AleexJaqui** [apprenticeharper/DeDRM_tools#256]
calibre Registro de depuración
calibre 2.82  embedded-python: True is64bit: False
Windows-7-6.1.7600 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7600')
Python 2.7.9
Windows: ('7', '6.1.7600', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9842323651 x 71.9822878229
Starting up...
Started up in 54.61 seconds with 1 books
Storage number map:
{(7L, 0L): [(3L, 'C')], (7L, 1L): [(1L, 'F')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\9017220142550BK9&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=3024)
{u'drive_letters': ['F'],
 u'pnp_id_map': {'F': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#9017220142550bk9&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'F': (1L, 1L)}}
Job: 1 Obtener información del dispositivo started
DeviceJob: 1 Obtener información del dispositivo done, calling callback
DeviceJob: 1 Obtener información del dispositivo callback returned
Job: 2 Establecer información de la biblioteca started
DeviceJob: 2 Job: 2 Establecer información de la biblioteca done, calling callback
Establecer información de la biblioteca finished
No hay detalles disponibles.
Job: 1 Obtener información del dispositivo finished
No hay detalles disponibles.
DeviceJob: 2 Establecer información de la biblioteca callback returned
Job: 3 Obtener lista de libros en el dispositivo started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: F:\ documents
DEBUG:    0.7 USBMS: scan from root False F:\documents
Job: 2 Establecer información de la biblioteca finished
No hay detalles disponibles.
DEBUG:    3.0 USBMS: count found in cache: 59, count of files in metadata: 59, need_sync: False
DEBUG:    3.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    3.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    3.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Obtener lista de libros en el dispositivo done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 59
DeviceJob: set_books_in_library finished: time= 0.0650000572205
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Obtener lista de libros en el dispositivo callback returned
Job: 3 Obtener lista de libros en el dispositivo finished
No hay detalles disponibles.
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["m\xa6\xdet\xcc\xe3\x9c\x94\xf2\xab\xe7\xf0!\xeb\xdbO\xd8\xd9\xdb \n|\xe0\xb6\xa4p\x18-\x0e'\x15\x18", 'F:\\EbookDRM\\La costumbre de amar (Flash).epub']
DeDRM v6.5.3: Trying to decrypt La costumbre de amar (Flash).epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: La costumbre de amar (Flash).epub is a secure Adobe Adept ePub
DeDRM v6.5.3: Looking for new default Adobe Digital Editions Keys after 1.4 seconds
Found 1 keys
DeDRM v6.5.3: Trying a new default key
DeDRM v6.5.3: Saving a new default key
DeDRM v6.5.3: Saved a new default key after 1.7 seconds
DeDRM v6.5.3: Ultimately failed to decrypt after 1.7 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 392, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 1.7 seconds.
C:\Program Files (x86)\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added La costumbre de amar (Flash) to db in: 2.5
Added 1 books in 8.4 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x04379630>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x043795D0>> ignored

**Comment by ElleKayEm** [comment]
Looks like that epub was not downloaded with the installation of ADE on the same machine and user as calibre.  And the installation where it was downloaded must be authorized with a different Adobe ID.

**Comment by apprenticeharper** [comment]
That it saved a new default key implies that it thought that the decryption had succeeded.

Looking at the code, it seems that you've hit a bug.

Line  383, reporting a successful decryption, the {3:.1f} should be {2:.1f

It'll be fixed in the next release. Thanks for the report.

**Comment by apprenticeharper** [comment]
Oh, and if you import again, it should work. (Since the new key did get saved.)
