### ISSUE TITLE
DeDRM 6.5.3 did not work with bokk bought at www.casadellibro.com

### ISSUE THREAD

**Issue by forroldo** [apprenticeharper/DeDRM_tools#258]
calibre Registro de depuración
calibre 2.72 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Starting up...
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'E')], (7L, 2L): [(1L, 'G')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\90D4220434570D7M&0: StorageDeviceNumber(type=7L, number=2L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=8)
{u'drive_letters': ['G'],
 u'pnp_id_map': {'G': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#90d4220434570d7m&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'G': (2L, 1L)}}
Job: 1 Obtener información del dispositivo started
DeviceJob: 1 Obtener información del dispositivo done, calling callback
DeviceJob: 1 Obtener información del dispositivo callback returned
Job: 2 Establecer información de la biblioteca started
DeviceJob: 2 Establecer información de la biblioteca done, calling callback
DeviceJob: 2 Establecer información de la biblioteca callback returned
Job: 3 Obtener lista de libros en el dispositivo started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: G:\ documents
DEBUG:    0.0 USBMS: scan from root False G:\documents
Traceback (most recent call last):
  File "site-packages\calibre\devices\kindle\driver.py", line 117, in metadata_from_path
  File "site-packages\calibre\ebooks\metadata\kfx.py", line 275, in read_metadata_kfx
  File "site-packages\calibre\ebooks\metadata\kfx.py", line 254, in extract_metadata
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "site-packages\calibre\devices\usbms\driver.py", line 238, in update_booklist
  File "site-packages\calibre\devices\usbms\driver.py", line 539, in book_from_path
  File "site-packages\calibre\devices\usbms\books.py", line 40, in __init__
  File "site-packages\calibre\ebooks\metadata\book\base.py", line 790, in __nonzero__
  File "site-packages\calibre\ebooks\metadata\book\base.py", line 152, in __getattribute__
AttributeError: Metadata object has no attribute named: 'author'
DEBUG:    0.1 USBMS: count found in cache: 38, count of files in metadata: 38, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Obtener lista de libros en el dispositivo done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 38
Job: 2 Establecer información de la biblioteca finished
No hay detalles disponibles.
Job: 3 Obtener lista de libros en el dispositivo finished
No hay detalles disponibles.
Job: 1 Obtener información del dispositivo finished
No hay detalles disponibles.
DeviceJob: set_books_in_library finished: time= 0.010999917984
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Obtener lista de libros en el dispositivo callback returned
Job: 3 Obtener lista de libros en el dispositivo finished
No hay detalles disponibles.
Started up in 21.98 seconds with 4255 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['_J\xec\xf58\xd9\x95{\x17\xbbIUW\xcfhN\xf5\x84\xa3\xd1\x15\xe34\xaaPO\xc6a?^a\xd7', 'C:\\Users\\rodolfo\\Documents\\My Digital Editions\\Piano para Dummies.epub']
DeDRM v6.5.3: Trying to decrypt Piano para Dummies.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: Piano para Dummies.epub is a secure Adobe Adept ePub
DeDRM v6.5.3: Looking for new default Adobe Digital Editions Keys after 2.7 seconds
Found 1 keys
DeDRM v6.5.3: Trying a new default key
DeDRM v6.5.3: Saving a new default key
DeDRM v6.5.3: Saved a new default key after 3.6 seconds
DeDRM v6.5.3: Ultimately failed to decrypt after 3.6 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 161, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 392, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 3.6 seconds.
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Piano para Dummies to db in: 3.2
Added 1 books in 8.4 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x0000000004E25470>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x0000000004E25320>> ignored

**Comment by ElleKayEm** [comment]
If the book was downloaded with Adobe Digital Editions 3.0 or later, then try opening it with ADE 2.0.1 authorized with the same Adobe ID.  If you can't open it with 2.0.1, then casadellibro.com is probably using the newer Adobe DRM which can't be removed yet.

**Comment by apprenticeharper** [comment]
Assumed solved. Closed.
