### ISSUE TITLE
[Mac] Can't open DeDRM.app

### ISSUE THREAD

**Issue by Gounlaf** [apprenticeharper/DeDRM_tools#259]
Hi,

I'm encoutering a strange problem: If I download the version 6.5.2, I can open DeDRM.app. If it checkout v6.5.2, I can't. Same for master. I don't tried with v6.5.3, 'cause I see your fix ff03c68674250db320356c7ae22adde3eb7a5a64.

With "Finder > Right Click > Open", I got an error: "can't open DeDRM.app"; With cmd, I got this result:

> open DeDRM_Macintosh_Application/DeDRM.app
> LSOpenURLsWithRole() failed with error -10810 for the file /Users/me/DeDRM_tools/DeDRM_Macintosh_Application/DeDRM.app

=> Tried with other tag too. Always the same problem: I can't open app from "a tag / source"

What I'm doing wrong ? I'm on OS X 10.12.4

Thanks.

**Comment by jonpurdy** [comment]
I've got a similar issue, but I get "The application “DeDRM.app” can’t be opened." with v6.5.3.
No issue with v6.5.2 downloaded moments afterwards.
<img width="455" alt="screen shot 2017-04-20 at 07 47 53" src="https://cloud.githubusercontent.com/assets/7793621/25229319/c4cb9a7e-259d-11e7-80bf-c00816a413e0.png">

**Comment by Gounlaf** [comment]
> but I get "The application “DeDRM.app” can’t be opened." with v6.5.3.

Yeap, ff03c68674250db320356c7ae22adde3eb7a5a64 fix it.

**Comment by apprenticeharper** [comment]
I don't know what your issue is with downloading from the repository, but I'll try to do a 6.5.4 release early next week, which should remove the problem.

**Comment by izenn** [comment]
I just tried the latest code available and i'm still getting the -10810 error

**Comment by apprenticeharper** [comment]
I'd be interested in reports of problems with the 6.5.4 app just released.

**Comment by Gounlaf** [comment]
Hi @apprenticeharper,

Unfortunatly, it's still not working

Logs:

When doing **Right Click > Open**

```
spawn_via_launchd() failed, errno=111 label=com.apple.ScriptEditor.id.707CCCD5-0C6C-4BEB-B67C-B6E866ADE85A.20908 path=/Users/myuser/DeDRM_tools_6.5.4/DeDRM_Macintosh_Application/DeDRM.app/Contents/MacOS/droplet flags=1 : LaunchApplicationClient.cp #1204 LaunchApplicationViaLaunchDJobLabel() q=com.apple.root.default-qos
```
When open witch CLI

```
spawn_via_launchd() failed, errno=111 label=com.apple.ScriptEditor.id.707CCCD5-0C6C-4BEB-B67C-B6E866ADE85A.20916 path=/Users/myuser/DeDRM_tools_6.5.4/DeDRM_Macintosh_Application/DeDRM.app/Contents/MacOS/droplet flags=0 : LaunchApplicationClient.cp #1204 LaunchApplicationViaLaunchDJobLabel() q=com.apple.main-thread
```

**Comment by izenn** [comment]
6.5.4 works for me via right click > open on 10.12.5

**Comment by Gounlaf** [comment]
I look quickly about error 111, and found this (for iTerm2 app):

https://gitlab.com/gnachman/iterm2/issues/4446

**Comment by apprenticeharper** [comment]
What happens is you open the DeDRM.app with ScriptEditor and then save as a different name? Does it launch then?

I'm not sure what I can do to fix a problem that seems to be in Apple's launch services.

[quoting from the link you gave]
I fixed it by reloading the LaunchServices database and rebooting the Mac.

/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user

https://discussions.apple.com/thread/3243206?tstart=0

**Comment by Gounlaf** [comment]
Hi @apprenticeharper,

Sorry for the delay; after using [Maintenance](https://www.titanium-software.fr/fr/maintenance.html) for clearing all caches and database, it's working again

**Comment by apprenticeharper** [comment]
Thanks.
