### ISSUE TITLE
Cannot deDRM my downloaded kindle books (on Calibre with deDRM plugin)

### ISSUE THREAD

**Issue by ebara527** [apprenticeharper/DeDRM_tools#263]
Caliber debug log for attempting to upload and convert two books below:

calibre Debug log
calibre 2.83  embedded-python: True is64bit: True
Darwin-16.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.5.0', 'Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.12.4', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Starting up...
Started up in 2.84 seconds with 0 books
DeDRM v6.5.3: Trying to decrypt B00BAXFECK_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Goldfinch: A Novel (Pulitzer Prize for Fiction)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/dimitrybaranov/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '6d8fb1c7f7a2' and UserName 'dimitrybaranov'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Goldfinch: A Novel (Pulitzer Prize for Fiction)
Found 4 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.6 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.6 seconds
2017-04-23 15:27:58.143 Calibre[8028:44690] deliverNotificationWithTitle()
* Notification delivered.
Added The Goldfinch: A Novel (Pulitzer Prize for Fiction) to db in: 0.1
Added 1 books in 1.3 seconds
Worker Launch took: 0.110301017761
Job: 1 Convert book 1 of 1 (The Goldfinch: A Novel (Pulitzer Prize for Fiction)) finished
Convert book 1 of 1 (The Goldfinch: A Novel (Pulitzer Prize for Fiction))
	Conversion options changed from defaults:
	  output_profile: 'kindle_fire'
	  verbose: 2
	  cover: u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/E3KP2D.jpeg'
	  read_metadata_from_opf: u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/fyNLpO.opf'
	Resolved conversion options
	calibre version: 2.83.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/E3KP2D.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x110fcb5d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x110fcbd10>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/fyNLpO.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: The Goldfinch: A Novel (Pulitzer Prize for Fiction)
	InputFormatPlugin: MOBI Input running
	on /var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/U94LF9.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/CoDeDRM v6.5.3: Trying to decrypt B001ANSSDC_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 256
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Silver Linings Playbook: A Novel
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/dimitrybaranov/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '6d8fb1c7f7a2' and UserName 'dimitrybaranov'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 256
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Silver Linings Playbook: A Novel
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds
ntents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1088, in run
	  File "site-packages/calibre/customize/conversion.py", line 245, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: The Goldfinch: A Novel (Pulitzer Prize for Fiction)

Added The Silver Linings Playbook: A Novel to db in: 0.1
Added 1 books in 1.1 seconds
2017-04-23 15:28:36.843 Calibre[8038:45017] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.101966142654
Worker Launch took: 0.158619165421
Job: 3 Convert book 1 of 1 (The Silver Linings Playbook: A Novel) finished
Convert book 1 of 1 (The Silver Linings Playbook: A Novel)
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: 'kindle_fire'
	  read_metadata_from_opf: u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/eF7Ht6.opf'
	  cover: u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/OeDhwN.jpeg'
	Resolved conversion options
	calibre version: 2.83.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/OeDhwN.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x115547550>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x115547c90>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/eF7Ht6.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: The Silver Linings Playbook: A Novel
	InputFormatPlugin: MOBI Input running
	on /var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/sfuSIn.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    DeDRM v6.5.3: Trying to decrypt B001QWDRF6_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Little Bee: A Novel
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/dimitrybaranov/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '6d8fb1c7f7a2' and UserName 'dimitrybaranov'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Little Bee: A Novel
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds
return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1088, in run
	  File "site-packages/calibre/customize/conversion.py", line 245, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: The Silver Linings Playbook: A Novel

Added Little Bee: A Novel to db in: 0.1
Added 1 books in 1.0 seconds
2017-04-23 15:29:12.244 Calibre[8045:45213] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.12214422226
Job: 4 Convert book 1 of 1 (Little Bee: A Novel) finished
Convert book 1 of 1 (Little Bee: A Novel)
	Conversion options changed from defaults:
	  output_profile: 'kindle_fire'
	  verbose: 2
	  read_metadata_from_opf: u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/wi2Rpj.opf'
	  cover: u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/fULhQc.jpeg'
	Resolved conversion options
	calibre version: 2.83.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/fULhQc.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10e699550>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x10e699c90>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/wi2Rpj.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: Little Bee: A Novel
	InputFormatPlugin: MOBI Input running
	on /var/folders/lg/3lq2ys4x2bv2n54ntfdd3gxh0000gn/C/calibre_2.83.0_tmp_U2XJD6/ZIBxKr.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1088, in run
	  File "site-packages/calibre/customize/conversion.py", line 245, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Little Bee: A Novel

**Comment by ebara527** [comment]
I also attempted to deDRM a book with the separate DRM application for Mac rather than through calibre and this also did not work. Below is the script:

There is 1 ebook to be decrypted.
Processing file: B003TU29WU_EBOK.azw
shellcommand: /usr/bin/python '/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py' '/Users/dimitrybaranov/Documents/My Kindle Content/B003TU29WU_EBOK.azw' '/Users/dimitrybaranov/deDRM books/' > '/Users/dimitrybaranov/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.4.
Copyright © 2008-2013 The Dark Reverser et al.
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 256
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Buddha's Brain: The Practical Neuroscience of Happiness, Love, and Wisdom
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 0 keys tried.
 Traceback (most recent call last):
  File "/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 254, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 228, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Applications/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 0 keys tried.
shellcommand: /usr/bin/python '/Applications/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/dimitrybaranov/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/dimitrybaranov/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.2
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/dimitrybaranov/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '6d8fb1c7f7a2' and UserName 'dimitrybaranov'
Saved a key to /Users/dimitrybaranov/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
 
shellcommand: /usr/bin/python '/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/dimitrybaranov/Library/Preferences/com.apprenticealf.dedrm/KindleKey 24.der' '/Users/dimitrybaranov/Documents/My Kindle Content/B003TU29WU_EBOK.azw' '/Users/dimitrybaranov/deDRM books/' > '/Users/dimitrybaranov/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.4.
Copyright © 2008-2013 The Dark Reverser et al.
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 256
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Buddha's Brain: The Practical Neuroscience of Happiness, Love, and Wisdom
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 4 keys tried.
 Traceback (most recent call last):
  File "/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 254, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 228, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Applications/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 4 keys tried.
There was an error with 1 ebook:
B003TU29WU_EBOK.azw couldn't be decrypted.

**Comment by ebara527** [comment]
UPDATE: I was actually able to fix this via an elaborate process. Essentially what I was trying to do in the first place was download my books from my one amazon account and convert them to de-dmr files so that when I delete that amazon account I won't lose all my books. (I have two amazon accounts and want to consolidate). So I initially downloaded the amazon books and saved them in a folder and de-registered my Kindle Mac Reader from the one account with books. Then I tried to use both calibre with plug-in and the de-drm program by themselves in order to convert the .azw files, which did not work as I stated above. 

After reading the apprentice harper deDRM FAQs again, I decided to try re-registering to the one account with books on the Kindle Mac Reader because after having de-registered, my Kindle Mac Reader would not read the files. Then, while still registered, I found the Kindle Content folder and converted all the files to deDRM files using the deDRM program. Finally, I opened calibre and downloaded each deDRM'ed book file and converted all to epub and saved all to disc (harddrive).

Then, after all that I de-registered my Kindle Mac Reader from the account. I cannot directly open the epub files on Kindle Mac Reader, but I can open them on iBook and I'm assuming I can send them to myself through the calibre app.

**Comment by ElleKayEm** [comment]
Yes, the tools use the key tied to your account and app/device.  So if you're not signed into Kindle for Mac, then they can't retrieve the correct key.

**Comment by ElleKayEm** [comment]
If you don't have any more questions, you can close this issue.

**Comment by apprenticeharper** [comment]
I'd think it was worth asking Amazon to consolidate the two accounts. But at least you have your ebooks De-DRMed now.

**Comment by bandtank** [comment]
@ElleKayEm where do you get the key? I'm signed in, but it's still not working.

**Comment by ElleKayEm** [comment]
If the book is from Kindle for PC/Mac (on the same machine and user), then the tools retrieve the key.  If the book is from/for an E-ink Kindle (not a Fire), then you need to enter its serial number into DeDRM's configuration.

**Comment by bandtank** [comment]
That doesn't appear to be working or my book can't be processed by the DeDRM tools. I updated calibre to 3.4.0 and installed this plugin, but it keeps failing to strip the DRM. This is for Kindle on Windows 10.

**Comment by ElleKayEm** [comment]
Start your own issue, and post a log.
