### ISSUE TITLE
All but one Nook books converted fine

### ISSUE THREAD

**Issue by BeteB** [apprenticeharper/DeDRM_tools#264]
Just opened 9 books from Nook (used Nook app for Win10, then grabbed the epub files in the AppData folder).  8 of them worked fine, but one will not De-DRM.  Updated Calibre and DRM plugin, removed and re-added book, no joy.  Log is:

calibre Debug log
calibre 2.83 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 138.231292517 x 137.710843373
Starting up...
Started up in 5.57 seconds with 91 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xca\x81m\xd1\x10Nm\x8e;\xd7#JhF\x90\xd8*\xe1+\xdeQ\x92<p'\x01\xed0d\xea\xb1\xcf", '\\9781439106624.epub']
DeDRM v6.5.3: Trying to decrypt 9781439106624.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: “9781439106624.epub” is a secure Barnes & Noble ePub
DeDRM v6.5.3: Looking for new NOOK Study Keys after 0.9 seconds
No nook Study log files have been found.
DeDRM v6.5.3: Ultimately failed to decrypt after 0.9 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 292, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.9 seconds.
Added Tithe to db in: 7.5
Added 1 books in 10.5 seconds

**Comment by ElleKayEm** [comment]
Have you entered your B&N account email and password into the plugin customization?

**Comment by sriggs1** [comment]
Debug mode: <p>You have started calibre in debug mode. After you quit calibre, the debug log will be available in the file: /var/folders/9t/sl_5zdt950b5n91j760_b3d40000gn/T/tmp4ibr7c.txt<p>The log will be displayed automatically.

**Comment by BeteB** [comment]
No, but the other books I downloaded from B&N were fine.  Why would the other 8 work and not this particular one?  Also, where do you enter the email and password?  I didn’t see that in the instructions.

**Comment by ElleKayEm** [comment]
They must not have had DRM in the first place.  In the plugins area of calibre, highlight DeDRM and click the Customize Plugin button.  Go into the Barnes & Noble section and click the green plus sign.

**Comment by sriggs1** [comment]
I have iBooks, so it is an apple book you log in through iTunes

**Comment by ElleKayEm** [comment]
@sriggs1 
These tools don't work for iBooks DRM removal.  As far as I know there isn't a free tool that does anymore.

**Comment by sriggs1** [comment]
I was wondering if you wanted to log into iBook to use.

**Comment by sriggs1** [comment]
I uploaded pics. Refer to number on pics for the order of book pages in order. I'm sorry. I just took pic of table of contents through the first parts. Let me know if you want prologue or epilogue or anything else you see from the table of contents

**Comment by BeteB** [comment]
Thanks, that worked!

**Comment by ElleKayEm** [comment]
@BeteB 
Great!  Go ahead and close this issue.

@sriggs1 
If you're having problems with DRM these tools actually handle (NOT iBooks), start your own issue.
