### ISSUE TITLE
Can't remove DRM from my epub ebook

### ISSUE THREAD

**Issue by xkhanhs** [apprenticeharper/DeDRM_tools#265]
I download ebook from an android app with an account.

calibre Debug log
calibre 2.83  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 120.712871287 x 120.315789474
Starting up...
Started up in 14.18 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x97(\x13\x89\x9a\xf8\xb8\x02.\xa0\xac\x93\xab\xf4\x8eo\xab\xa7\xa9\xf2\x16g\x98\xda\xe92\xd9\x93\xbf$\xc3\x94', 'D:\\10106_3_drm.epub']
DeDRM v6.5.3: Trying to decrypt 10106_3_drm.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: “10106_3_drm.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 397, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Couldn't decrypt after 0.6 seconds. DRM free perhaps?
Added 10106 3 drm to db in: 1.8
Added 1 books in 3.1 seconds
Worker Launch took: 0.241999864578

**Comment by xkhanhs** [comment]
Link to my file: https://goo.gl/CwHQgk
Please help!

**Comment by ElleKayEm** [comment]
If it's not from B&N or a store that uses Adobe DRM, then these tools can't help.

**Comment by apprenticeharper** [comment]
As ElleKayEm says, I think you'll need to look elsewhere. Closed.
