### ISSUE TITLE
New Type of Kindle Ebook that cannot be decrypted

### ISSUE THREAD

**Issue by msmithee** [apprenticeharper/DeDRM_tools#266]
As of this date 04/25/17 I could no longer back up my Kindle purchase with DeDRM. This is the error message I got:
There is 1 ebook to be decrypted.
Processing file: B00GJ6OAPA_EBOK.azw
There was an error with 1 ebook:
MSmithee_:Kindle:B00GJ6OAPA_EBOK.azw is neither a Kindle not a Mobipocket file

I also noticed that my kindle book appears with a file folder with this new file which was not in the older files: 
amzn1.drm-voucher.v1.e3738f71-21c1-47b3-af3f-1b23fc9e4940.voucher

**Comment by ElleKayEm** [comment]
See the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by msmithee** [comment]
I did as the post suggested but it didn't work. Is it possible that all new downloads now has the KFX file embedded in the .azw file?

**Comment by ElleKayEm** [comment]
After downgrading to 1.17, be sure to uncheck auto-update and download new copies of your books.  If that doesn't work, post an import log.

**Comment by msmithee** [comment]
How do I create an import log?

**Comment by ElleKayEm** [comment]
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by msmithee** [comment]
DeDRM v6.5.3: Processing: B01M4QEXKN_EBOK.azw...
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Director’s Cut: My Life in Film
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
Error decrypting book after 0.1 seconds: No key found in 4 keys tried.
Traceback (most recent call last):
  File "C:\Users\smith\Documents\DeDRM_Windows_Application\DeDRM_App\DeDRM_lib\lib\k4mobidedrm.py", line 254, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "C:\Users\smith\Documents\DeDRM_Windows_Application\DeDRM_App\DeDRM_lib\lib\k4mobidedrm.py", line 228, in GetDecryptedBook
    mb.processBook(totalpids)
  File "C:\Users\smith\Documents\DeDRM_Windows_Application\DeDRM_App\DeDRM_lib\lib\mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 4 keys tried.
DeDRM v6.5.3: Failed

DeDRM v6.5.3: Complete:  Successes: 0, Failures: 1

**Comment by ElleKayEm** [comment]
Ah, didn't realize before that you were using the stand-alone app instead of the plugin.  I'm not familiar with it, but it doesn't seem to be looking for a new key when the old keys fail.  I wonder if you could force it to retrieve the new keys by deleting the old Kindle keys.  Not really sure since I use the plugin myself.

**Comment by msmithee** [comment]
Does anyone know how I can do that?

**Comment by pdurrant** [comment]
Since you've installed python and pycrypto, you could just run the stand-alone key extraction script (in the Other Tools folder, I think) and then point the stand-alone at the key file that generates.

But I'm not really familiar with the Windows stand-alone.

**Comment by msmithee** [comment]
Sorry I'm not Windows literate so I don't know how to do that. On the Mac I've encountered problems with the Kindle Keys before where I can delete it from the Users Library. I wonder if it's the same concept here, and would I find it in the Lib DeDRM Windows folder?

**Comment by ElleKayEm** [comment]
No idea.  I've been using calibre and the plugin for many years.  I can't remember if I ever used the stand-alone or not.

**Comment by apprenticeharper** [comment]
You could try using the latest 6.5.4, but I'm not hopeful. I've paid little attention to the Windows stand-alone because installing the needed Python and PyCrypto is so complex compared to downloading calibre.
