### ISSUE TITLE
DeDRM not working on Kindle

### ISSUE THREAD

**Issue by b-w-moore** [apprenticeharper/DeDRM_tools#267]
Just installed DeDRM_Tools_6.5.3 on Calibre 2.83 using Windows 7 Ultimate.  Tried three Kindle books, all failed.  Reran two of them in debug mode.  Reports follow:

calibre Debug log
calibre 2.83  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9595278246 x 72.0810810811
Starting up...
Started up in 14.82 seconds with 48 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x12\xd1\xca\xe4\xbe\xf5\xddG`\x8d\xd9\x1au\xa1\x7f\xdf\x02\xb2\xae\xe1\x877\x05!\xf9\x87\x85UB-\xb6\xd8', 'K:\\My_Documents\\calibre\\book transition\\convert\\The Holy Bible, English Standard Version (with Cross-References).azw3']
DeDRM v6.5.3: Trying to decrypt The Holy Bible, English Standard Version (with Cross-References).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Holy Bible, English Standard Version (with Cross-References)
Found 0 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.7 seconds
searching for kinfoFiles in C:\Users\student\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\student\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1512246259' and UserName '73747564656e74'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Holy Bible, English Standard Version (with Cross-References)
Found 4 keys to try after 1.0 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 1.0 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 1.0 seconds
Added The Holy Bible, English Standard Version (with Cross-References) to db in: 1.3
Added 1 books in 3.6 seconds
Worker Launch took: 0.266000032425

calibre Debug log
calibre 2.83  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9595278246 x 72.0810810811
Starting up...
Started up in 11.69 seconds with 47 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['Aq\xe0G\xfc\x91\x19\x13O~\x83s\xd4\xec \xd8Tu\xe9\x03Z \xb7e\xcbQs\\\x95\xdc6x', 'K:\\My_Documents\\calibre\\book transition\\convert\\The Holy Bible, English Standard Version (with Cross-References).azw3']
DeDRM v6.5.3: Trying to decrypt The Holy Bible, English Standard Version (with Cross-References).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Holy Bible, English Standard Version (with Cross-References)
Found 0 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.7 seconds
searching for kinfoFiles in C:\Users\student\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\student\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1512246259' and UserName '73747564656e74'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Holy Bible, English Standard Version (with Cross-References)
Found 4 keys to try after 0.9 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.9 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.9 seconds
Added The Holy Bible, English Standard Version (with Cross-References) to db in: 1.7
Added 1 books in 3.9 seconds
Worker Launch took: 0.22000002861

**Comment by ElleKayEm** [comment]
If the books are from or for an E-ink Kindle (not a Fire), then you need to put its serial number into the plugin customization.  Otherwise, download your books with Kindle for PC.  Make sure to use version 1.17 and uncheck auto-updates.  See the FAQs:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by apprenticeharper** [comment]
Assumed Solved. Closed.
