### ISSUE TITLE
BN - IGNOBLEError: AES improper key used

### ISSUE THREAD

**Issue by twmartin** [apprenticeharper/DeDRM_tools#268]
I seem to be having some difficulty importing DRM'd BN epubs into Calibre:

```
calibre Debug log
calibre 2.83  embedded-python: True is64bit: True
Darwin-16.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.5.0', 'Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.12.4', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000166 x 110.50000166
Starting up...
Started up in 1.24 seconds with 0 books
DeDRM v6.5.3: Trying to decrypt 9780307351937.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: “9780307351937.epub” is a secure Barnes & Noble ePub
DeDRM v6.5.3: Trying Encryption key fresh-key
Could not decrypt n_uw_h.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 278, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 209, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 158, in __init__
IGNOBLEError: AES improper key used

DeDRM v6.5.3: Failed to decrypt with key fresh-key after 0.0 seconds
DeDRM v6.5.3: Looking for new NOOK Study Keys after 0.0 seconds
Found nookStudy log file: /Users/twmartin/Library/Application Support/Barnes & Noble/BNDesktopReader/logs/BNClientLog.txt
Found nookStudy log file: /Users/twmartin/Library/Application Support/Barnes & Noble/BNDesktopReader/indices/BNClientLog.txt
DeDRM v6.5.3: Ultimately failed to decrypt after 0.0 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 292, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.0 seconds.
Added World War Z: An Oral History of the Zombie War to db in: 0.0
Added 1 books in 0.6 seconds
```

I referenced #54 and #169 in trying to troubleshoot on my own:
- Changed my pw such that it didn't have special characters
- Logged into the Nook for PC app on a Windows VM with my latest credentials, downloaded my books, and transferred them to my Mac
- Created a new DeDRM plugin BN key with my latest creds
- Confirmed that the `.b64` file is not empty
- Confirmed that the key returned from the `cart4.barnesandnoble.com` url is the same key as what is stored in the `.b64` file

Yet, when I import the epubs into Calibre, they still have DRM and I get the error above.

Any ideas for further troubleshooting that I should try?

**Comment by twmartin** [comment]
Looks like I have a key length of 28, which is bad according to https://github.com/apprenticeharper/DeDRM_tools/blob/53c16c916b3794716b720168e8e104e0662ff154/DeDRM_calibre_plugin/DeDRM_plugin/ignobleepub.py#L157-L158. Any thoughts on the key length discrepancy?

**Comment by apprenticeharper** [comment]
Is it working for you now, or do you still need help?

**Comment by twmartin** [comment]
I still still need help.

**Comment by ElleKayEm** [comment]
Hmm, it really sounds like you've looked at everything.  Fresh copies of the books and the current key should work.  Try retrieving your key again via the plugin, and see whether or not it tells you it's already in there.  Either way, work your way out of the dialogue boxes, restart calibre, and then try importing your books again.

**Comment by twmartin** [comment]
I get the same key when I retrieve it again and DRM still fails to get stripped when I restart and retry uploading books. Gonna take a crack at debugging the issue myself with some code updates. Any other insight would be much appreciated.

My attention is currently focused on https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_calibre_plugin/DeDRM_plugin/ignobleepub.py#L275-L278.

`bookkey[:-ord(bookkey[-1])]` results in an empty string and `-ord(bookkey[-1])` results in `-248`, subsequently the AES class squawks because the blocksize is 0.

**Comment by ElleKayEm** [comment]
I see that it found a Nookstudy log.  Are you able to download books via Nookstudy anymore?  It still works for me, but I know others have had trouble logging into it.

**Comment by twmartin** [comment]
No. I don't think I've ever successfully run Nookstudy before on my Mac. Maybe I tried installing it on this journey to migrate away from Nook.

**Comment by twmartin** [comment]
Figured I should try calibre DeDRM on the windows vm where I originally downloaded the books. Still failed though.

```calibre Debug log
calibre 2.83  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.9028037383 x 95.9134328358
Starting up...
Started up in 3.71 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xa7E"\xdf\xdc\xe4#rU\xd6RzE,5:Nq\x1f\x9f\x14\x94X\xb0Jo\xd8\xda\xf1G\xd17', 'C:\\Users\\tywma\\Desktop\\books\\9780759525771.epub']
DeDRM v6.5.3: Trying to decrypt 9780759525771.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: “9780759525771.epub” is a secure Barnes & Noble ePub
DeDRM v6.5.3: Looking for new NOOK Study Keys after 0.1 seconds
No nook Study log files have been found.
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 292, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Added The Black Echo to db in: 0.1
Added 1 books in 1.0 seconds```

**Comment by ElleKayEm** [comment]
The only reason DeDRM would need to be on the same machine and user for B&N books is if you downloaded them with Nookstudy.  Then the tools automatically retrieve the key from a text log that Nookstudy creates.  It doesn't matter where Nook for PC is installed.  It doesn't create a log like Nookstudy.  So if you don't have Nookstudy working on the same machine/user, you have to retrieve the key by entering your B&N account email and password into the plugin configuration.  The current key should be the same across all B&N devices/apps.  So your issue has me stumped.  If you can retrieve your current key through the plugin, and you have fresh copies of the books from that same account, the books should unlock with that key.  The only exception would be special types of books (comics, magazines, pdfs) which can't be downloaded with Nook for PC.   Obviously from your log, that's not the case here.

**Comment by twmartin** [comment]
Would there happen to be any additional BN decryption documentation available anywhere? As I'm reading through the code, the decryption process feels like some sort of black magic.

**Comment by ElleKayEm** [comment]
I don't know.  All I can say is that it seems that the key you have is not the right one for those books.  In my experience, the reasons for that are old copies of the books, an old key, or they're not from the same account.

**Comment by apprenticeharper** [comment]
The only thing you don't mention trying is retrieving the key under your Windows VM. I didn't think that retrieving it from a Mac browser would make a difference, but it's something to try.

If you can download and read the books using Nook for PC on a Windows VM, then it should be possible to get the key and remove the DRM.

The only documentation is in the python scripts. The algorithms were determined by reverse-engineering the nooks apps to see where the key came from and how it was applied.

**Comment by twmartin** [comment]
If I understand you correctly, I believe I did that. When I tried Calibre DeDRM on the Windows VM five days ago, I did retrieve a fresh key through the plugin from the VM. It was the same as what I've been getting from my Mac.

**Comment by apprenticeharper** [comment]
Try another fresh download of the books?

**Comment by apprenticeharper** [comment]
Please start a fresh issue if you still have problems. B&N keys can be tricky.
