### ISSUE TITLE
ImportError: cannot import name choose_save_file

### ISSUE THREAD

**Issue by Nakel** [apprenticeharper/DeDRM_tools#27]
The latest DeDRM plugin is installed and I have restarted it after installation. When I try to customize the plugin on Calibre, I get the following error;

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 284, in customize_plugin
    self.modify_plugin(op='customize')
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 360, in modify_plugin
    if plugin.do_user_config(self.gui):
  File "/usr/lib/calibre/calibre/customize/__init__.py", line 150, in do_user_config
    config_widget = self.config_widget()
  File "calibre_plugins.dedrm.__init__", line 602, in config_widget
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 150, in load_module
    exec compiled in mod.__dict__
  File "calibre_plugins.dedrm.config", line 28, in <module>
ImportError: cannot import name choose_save_file

**Comment by ElleKayEm** [comment]
Do you have any of the old DRM removal plug-ins for individual file types installed?  Remove all but the current all-in-one DeDRM plugin.

**Comment by Nakel** [comment]
Yes I did had some old DRM plugins installed. but I thought removed them through calibre's "remove plugin" option constantly. In which directory should I check for old DeDRM files and delete them all?

**Comment by Nakel** [comment]
So I deleted all of the files related to DeDRM in /.config/calibre/plugins but when I install it, I still get that hideous error.

**Comment by ElleKayEm** [comment]
Hmmm, have you tried removing and reloading the latest DeDRM plugin?  Then restart calibre before going into the customization dialog.  Also, what version of calibre do you have?  You could try updating or reinstalling calibre.

**Comment by apprenticeharper** [comment]
You don't mention your version of calibre. I'm guessing it's pretty old, and so doesn't have that function available to plugins.

**Comment by apprenticeharper** [comment]
But I suppose we ought to prevent installation in that case, or have some other work-around. What version of calibre are you using?

**Comment by apprenticeharper** [comment]
With no feedback about calibre version, I'm going to close this issue.

**Comment by OskJonsdottir** [comment]
Just for the record: I got the same error with calibre 0.8.38. Issue is not present in calibre 2.47

**Comment by apprenticeharper** [comment]
While I try not to break use with older calibre versions, I'm not surprised it doesn't work with a pre-1.0 version of calibre.
