### ISSUE TITLE
Problem with kindle e book

### ISSUE THREAD

**Issue by kraecke** [apprenticeharper/DeDRM_tools#270]
Hi, on a computer with win 10 with creator update, i´m not able anymore to convert kindle ebooks as i could weeks before. I reinstalled kindle app from amazon hompepage, it is working fine. DeDRM 6.5.3 is installed in calibre. Here is the protokoll:
calibre Fehlerdiagnoseprotokoll
calibre 2.83 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Audit Log (1, 0, 6)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 107.300330033 x 106.947368421
Starting up...
Started up in 14.20 seconds with 19 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xa4\x88\xa5\x8f\xf4\xd1\x1d*\xecS\r\xec^\xa0\x881\xd3\x06W\xca\x8b\xc1\x9f9u\xfe.C\x88\x8dr\xd6', 'D:\\Im Schatten das Licht_B01F6CG9VK.azw3']
DeDRM v6.5.3: Trying to decrypt Im Schatten das Licht_B01F6CG9VK.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Im Schatten das Licht (German Edition)
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\JK\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\JK\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '403334736' and UserName '4a4b'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Im Schatten das Licht (German Edition)
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.5 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.5 seconds
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Im Schatten das Licht (German Edition) to db in: 0.5
Added 1 books in 3.2 seconds

Some ideas? 
Thank you very much!

**Comment by kraecke** [comment]
Sorry guys, i did it. I found the comment to go back to Kindle app version 1.17, i deleted all files in the my kindle content folder, the app downloaded the ebook again, an then i imported this new downloaded ebook to calibre an it worked. Now i can read the book on my tolino too. Thanks a lot for your time and this very helpful plugin!!!!!   :-)

**Comment by ElleKayEm** [comment]
FYI: If the book in the log was from or for an E-ink Kindle (not a Fire), it could be decrypted by entering the serial number into the plugin customization.  Go ahead and close the issue if you're all set.
