### ISSUE TITLE
kindle DRM

### ISSUE THREAD

**Issue by freepopeye** [apprenticeharper/DeDRM_tools#271]
Hi!
...I tried editing an AZW file by Calibre, just for changing the TOC , using DeDRM v6.5.3 plugin and I failed, receiving the following notice:

Found 0 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\Francesco\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.3: Ultimately failed to decrypt after 0.5 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.5 seconds

Does anybody know where is the problem?

**Comment by ElleKayEm** [comment]
That doesn't appear to be the whole log.  If it's a book from Kindle for PC, you need to have it installed on the same machine and user as calibre.

**Comment by apprenticeharper** [comment]
Assumed solved. Closed.
