### ISSUE TITLE
Has Amazon updated their DRM?

### ISSUE THREAD

**Issue by artnking** [apprenticeharper/DeDRM_tools#272]
Sometime between April 4th and today, it appears that Amazon has updated their DRM so that the Calibre plug-in no longer works.  Books I purchased from Amazon and downloaded in AZW3 format before April 4th convert fine.  Newer books fail with the Calibre pop-up "Cannot Convert"... this book is locked by DRM.

I'm using Calibre DeDRM version 6.5.3 with Calibre 2.83 (Windows 64 bit).

I'm attaching two Calibre debug files.  One success with a pre-April 4th AZW3 file, and the second a failure with a more recent AZW3 file.  The errors in here seem to indicate a problem with the decrypt keys.  Both debug files were run using the exact same keys.
[Convert Success - tmp3xnddq.txt](https://github.com/apprenticeharper/DeDRM_tools/files/971633/Convert.Success.-.tmp3xnddq.txt)
[Convert Fail - tmp3xnddq.txt](https://github.com/apprenticeharper/DeDRM_tools/files/971634/Convert.Fail.-.tmp3xnddq.txt)

**Comment by ElleKayEm** [comment]
Is it from or for a different device then you've done before?  If it's for an E-ink Kindle (not a Fire), then you don't seem to have the correct serial number in the plugin customization.  Alternatively, you could install [Kindle for PC v1.17](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac) on this machine and import a copy from there.

**Comment by apprenticeharper** [comment]
I think most likely is that it's from a Kindle that has had a firmware update and now uses the KFX format. Download the book from the Amazon website 'for transfer via USB' to your Kindle, and it should work.

**Comment by ElleKayEm** [comment]
Looking at the import log, it seems that's what they already did.  It's an AZW3 file from the Downloads directory, and I think the naming convention is what you get when you download from the website.  They just choose a different device than the one that worked.

**Comment by artnking** [comment]
Thank you ElleKayEm and apprenticeharper.  You put me on the right track.  I added the key from my new Kindle Voyage to the key list for the plug-in, and downloaded the AZW3 file from Amazon again, specifying that it was for this Kindle Voyage.  It worked.
