### ISSUE TITLE
unable to install DeDRM 6.5.3

### ISSUE THREAD

**Issue by ronvasu** [apprenticeharper/DeDRM_tools#274]
I am running win 10 and calibre 2.84 but I am unable to install DeDRM 6.5.3
it says it to be an "invalid plugin" as "it doesn't contain top-level_init_.py" file

**Comment by ElleKayEm** [comment]
Sounds like you're trying to install the whole archive.  There's more than just the plugin in there.  Unzip it and look inside the DeDRM calibre plugin folder for the zip file to load into calibre.

**Comment by ronvasu** [comment]
Sorry for troubling you.
I got it and it worked. 
Thank you very much
Regards

**Comment by ElleKayEm** [comment]
Go ahead and close the issue.
