### ISSUE TITLE
Can't de-DRM Oxford dictionaries

### ISSUE THREAD

**Issue by zyzyx1** [apprenticeharper/DeDRM_tools#276]
I was able to successfully remove DRM from all my e-ink Kindle books (those that were DRM-ed) with an exception of two Oxford dictionaries that are provided for free by Amazon (Oxford Dictionary of English and The New Oxford American Dictionary). Is it known issue?

I was able to de-DRM Merriam Webster's Advanced Learner's English Dictionary, which is another free dictionary provided by Amazon.

I tried to perform the operation first under Linux + Wine (+ Kindle for PC) and then under Windows 7 with similar results.

**Comment by ElleKayEm** [comment]
Yes, it's a known issue.  The default dictionaries that come free on a Kindle device use some other encryption key than the one that's used for your books.

**Comment by zyzyx1** [comment]
Is de-DRMing these dictionaries a lost cause? Or just that those in the know weren't interested so far?

**Comment by ElleKayEm** [comment]
I don't think any DRM is a lost cause.  But considering these dictionaries have been this way since the original Kindle, no one's been interested for a long time.

**Comment by apprenticeharper** [comment]
Finding the key is more trouble than its worth. Closed.
