### ISSUE TITLE
Kindle for PC and DRM

### ISSUE THREAD

**Issue by Ariele47** [apprenticeharper/DeDRM_tools#277]
I am on Windows10 Home.
I deregistered Kindle for PC from my Amazon account.
I uninstalled Kindle for PC version 1.20 and deleted all the folders 
[home folder]\AppData\Local\Amazon and [home folder]\My Documents\My Kindle Content.
Then I downloaded and installed Kindle for PC 1.17.
The option to automatically install updates is unchecked.
However, in spite of the above, anytime I try to launch Kindle for PC it forces the upgrade to the new version 1.20.1.
Hence I am no longer able to remove DRM from my latest books.

**Comment by ElleKayEm** [comment]
Try method 2 at this link:
https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Ariele47** [comment]
Great. It works just fine. Thanks a lot.
