### ISSUE TITLE
Kobo Desktop Reader update breaks Calibre Obok DeDRM.

### ISSUE THREAD

**Issue by Tenome** [apprenticeharper/DeDRM_tools#28]
Looks like they changed the location of their key.

Kobo Desktop 3.17.0 (white interface), Calibre 2.34, Obok 3.1.3, Windows 7 64-bit, currently inoperable. 

"... could not be added because it could not be decrypted."
"ERROR: Obok DeDRM v3.1.3: No userkeys found to decrypt books with. No point in proceeding"

**Comment by ElleKayEm** [comment]
Just wanted to add that it is Kobo Desktop 3.17.0 for Windows that has the problem.  When I opened the version I already had installed, it only updated to 3.15.0 which still worked.  I had to download a new setup file from the Kobo website to get the latest version.

**Comment by apprenticeharper** [comment]
3.15 can be downloaded through the Wayback Machine, which is the only solution until someone works out how the keys are stored in 3.17

https://web.archive.org/web/20150505234922/https://kbdownload1-a.akamaihd.net/desktop/kobodesktop/kobosetup.exe

**Comment by 13xforever** [comment]
Just to let you know, they added a new salt for master key generation.
In addition to `NoCanLook`, there's now `XzUhGYdFp`.
There's some kind of condition when either of those should be used, but I just try everything.

**Comment by apprenticeharper** [comment]
Many thanks.

**Comment by apprenticeharper** [comment]
This will be fixed in the next release
