### ISSUE TITLE
Can't deDRM with Calibre, using .azw3 file from "Transfer to Kindle via USB" option

### ISSUE THREAD

**Issue by ditchfieldcaleb** [apprenticeharper/DeDRM_tools#280]
I'm sure the serial number I added for the kindle eInk reader is correct in Calibre, and I'm sure that I selected that same kindle for the "Transfer to kindle via USB" option. The file is already on my kindle, but in the new format, so I did the "transfer via USB" option to get the .azw3 format. Here is the log:

calibre Debug log
calibre 2.85.1  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && KindleUnpack - The Plugin (0, 81, 4)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259 x 93.6245733788
Starting up...
Started up in 9.09 seconds with 0 books
DeDRM v6.5.3: Trying to decrypt Vietnam- An American Ordeal.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Vietnam: An American Ordeal
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Caleb\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Caleb\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4094645881' and UserName '43616c6562'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Vietnam: An American Ordeal
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
Added Vietnam: An American Ordeal to db in: 0.2
Added 1 books in 0.6 seconds

**Comment by ElleKayEm** [comment]
From the log: "Cannot decode library or rented ebooks."
