### ISSUE TITLE
Can't de-DRM from epub (ADE) to mobi

### ISSUE THREAD

**Issue by pixietiger** [apprenticeharper/DeDRM_tools#281]
Using ADE 2.0.1. Authorized on same computer as calibre. Says it's locked by DRM.

calibre Debug log
calibre 2.85.1  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 101.6 x 101.6
Starting up...
Started up in 5.68 seconds with 11 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['f\xb7\xb8B\xb4\xc8=Jfw\xdf\xb8Su\x18 U>\xf7jz\x91X\xb7-h\xdb;f\x9adk', 'C:\\Users\\Serenity\\Desktop\\DRM\\DeDRM_calibre_plugin\\DeDRM_plugin.zip']
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xc6\x96qa\xdd)|\xbf\x16\xbc\x19\x98\xf4\xc2\xa2/\xdaRq\xcc\x051]\t{\x88\xca'\xf6\xfdY\xb8", 'C:\\Users\\Serenity\\Documents\\My Digital Editions\\Shimmer and Burn-1.epub']
DeDRM v6.5.3: Trying to decrypt Shimmer and Burn-1.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: Shimmer and Burn-1.epub is a secure Adobe Adept ePub
DeDRM v6.5.3: Trying Encryption key default_key
Could not decrypt zwegiw.epub. Wrong key
DeDRM v6.5.3: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v6.5.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v6.5.3: Trying a new default key
DeDRM v6.5.3: Saving a new default key
DeDRM v6.5.3: Saved a new default key after 0.2 seconds
DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 392, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
Added Shimmer and Burn to db in: 0.1
Added 1 books in 6.8 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x04D36690>> ignored
Worker Launch took: 0.0829999446869
Job: 1 Convert book 1 of 1 (Shimmer and Burn) finished
Convert book 1 of 1 (Shimmer and Burn)
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\Serenity\\AppData\\Local\\Temp\\calibre_dg4dnu\\bso3ii.opf'
	  output_profile: 'kindle_pw'
	Resolved conversion options
	calibre version: 2.85.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x044BF5F0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x044BF9B0>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Serenity\\AppData\\Local\\Temp\\calibre_dg4dnu\\bso3ii.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\Serenity\AppData\Local\Temp\calibre_dg4dnu\xcms8x.epub
	Python function terminated unexpectedly
	  xcms8x.epub (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 268, in convert
	calibre.ebooks.DRMError: xcms8x.epub

**Comment by ElleKayEm** [comment]
Some piece of a previous installation lurking around possibly?  I've seen people solve it by completely removing  ADE 2.0.1 including preferences and registry entries.  Then reinstalling, reauthorizing with the Adobe ID, and trying again.

**Comment by apprenticeharper** [comment]
Assumed solved. Closed.

**Comment by pixietiger** [comment]
It didn't solve the issue, but I fortunately had it on my tablet, so I
didn't worry about it. Just FYI!

**Comment by ElleKayEm** [comment]
If it's working on your tablet with the same Adobe ID, you could export the key from the plugin there and import it to the other.
