### ISSUE TITLE
deDRM not working - Kindle for PC, Amazon purchase, Win10

### ISSUE THREAD

**Issue by juliavaldez** [apprenticeharper/DeDRM_tools#282]
Help please with this issue? Thanks!

calibre Debug log
calibre 2.85.1  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Starting up...
Started up in 55.44 seconds with 2 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x9f\xc3\xee\xc4\x0fE\xabG\x0b7<\xde\x19\x10>\xc8\xc0b\x7f{BO\xf0\xc4\xf3\x1e?\xaa\xda\xb4N\xbd', 'C:\\Users\\acer\\Documents\\My Kindle Content\\B06ZZ4QBPC_EBOK\\B06ZZ4QBPC_EBOK.azw']
DeDRM v6.5.3: Trying to decrypt B06ZZ4QBPC_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\acer\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\acer\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1012942876' and UserName '61636572'
DeDRM v6.5.3: Found 1 new key
DeDRM v6.5.3: Ultimately failed to decrypt after 0.9 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.9 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 416, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B06ZZ4QBPC EBOK to db in: 1.2
Added 1 books in 5.4 seconds
Worker Launch took: 1.95499992371
Job: 1 Convert book 1 of 1 (B06ZZ4QBPC EBOK) finished
Convert book 1 of 1 (B06ZZ4QBPC EBOK)
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\acer\\AppData\\Local\\Temp\\calibre_qaxslf\\d6ldzs.opf'
	  output_profile: 'kindle'
	Resolved conversion options
	calibre version: 2.85.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0420A4F0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x0420A850>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\acer\\AppData\\Local\\Temp\\calibre_qaxslf\\d6ldzs.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\acer\AppData\Local\Temp\calibre_qaxslf\nln1hg.azw
	Python function terminated unexpectedly
	  This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books. (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 34, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 84, in __init__
	calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

**Comment by ElleKayEm** [comment]
As the log says, this is a KFX book which neither calibre or the tools handle.  See the link for info on how to get the book in the older format.

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by prchvs** [comment]
Thank you!!!
