### ISSUE TITLE
DeDRM 6.5.3 and DeDRM 6.3.4a not working for ADE 4.5.4.165157 or ADE 3.0.86137 or ADE 2.0.1.78765

### ISSUE THREAD

**Issue by readzilla** [apprenticeharper/DeDRM_tools#283]
Error message:

"Processing: [FILENAME].epub...Failed
Complete:  Successes: 0, Failures: 1"

Environment in which error keeps happening:

DeDRM_tools_6.5.3
pycrypto-2.6.win32-py2.7
ActivePython-2.7.10.12-win32-x86
Adobe Digital Editions 4.5.4.165157
Windows 7 Pro, Service Pack 1

Which combination of DeDRM tools, PyCrypto, ActivePython, and Adobe Digital Editions should I use instead?

**Comment by ElleKayEm** [comment]
Best to stick with ADE 2.0.1.  See the FAQs here:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-registered-adobe-digital-editions-30-or-later-with-an-adobe-id-before-downloading-but-my-epub-or-pdf-still-has-drm
I believe the rest is fine, but I use the calibre plugin myself.

**Comment by readzilla** [comment]
Thanks for the tip!

I uninstalled pycrypto then uninstalled python then uninstalled ADE.

Next, I installed ADE 2.0.1.78765 then installed ActivePython-2.7.10.12-win32-x86 then _tried_ to install pycrypto-2.6.win-amd64-py2.7 but got the error message "Python version 2.7 ius required, which was not found in the registry."

Which versions of python, pycrypto, and DeDRM Tools do you use with ADE 2.0.1?

Meanwhile, it seems as though some of the versions I tried to uninstall didn't completely uninstall.  Off I go to uninstall everything and reset the computer!...

**Comment by readzilla** [comment]
...and now I'm back.  Apparently installing ActivePython-2.7.10.12-win32-x86 no longer puts Python version 2.7 in the registry like it did earlier today.

???

Now pycrypto-2.1.0.win32-py2.7, _that_ can find the Python 2.7 in the registry

So now I'm working with:

- ADE 2.0.1.78765
- ActivePython-2.7.10.12-win32-x86
- pycrypto-2.1.0.win32-py2.7 (even though the Readme says "Please get the latest (currently 2.6) PyCrypto meant for Windows Python version 2.7.", I know)
- DeDRM_tools_6.3.4a

I got the same "Processing: [FILENAME].epub...Failed
Complete: Successes: 0, Failures: 1" error message.  :/

Then I removed DeDRM_tools_6.3.4a and replaced it with DeDRM_tools_6.5.3, so the configuration is 

- ADE 2.0.1.78765
- ActivePython-2.7.10.12-win32-x86
- pycrypto-2.1.0.win32-py2.7 (even though the Readme says "Please get the latest (currently 2.6) PyCrypto meant for Windows Python version 2.7.", I know)
- DeDRM_tools_6.5.3

If I'm going to replace _one_ of these four with a different version number of the program, then I need to know the version numbers of _all_ of other three that'll go with it...

**Comment by readzilla** [comment]
BTW, on my old Windows XP Pro service Pack 3 machine _this_ combination:

- Adobe Digital Editions 3.0.86137
- ActivePython-2.7.10.12-win32-x86
- pycrypto-2.1.0.win32-py2.7 (even though the Readme says "Please get the latest (currently 2.6) PyCrypto meant for Windows Python version 2.7.", I know)
- DeDRM_tools_6.3.4a

works just fine.  What should I do differently on Win7?

**Comment by readzilla** [comment]
I installed that exact combination on my Windows 7 Pro Service Pack 1 machine:

-     Adobe Digital Editions 3.0.86137
-     ActivePython-2.7.10.12-win32-x86
-     pycrypto-2.1.0.win32-py2.7
-     DeDRM_tools_6.3.4a

...and _still_ got the same error message.

If I really need to be using the Calibre plugin instead then exactly which version number of Calibre, exactly which version number of Python, exactly which version number of PyCrypto, and exactly which version number of DeDRM Tools work with Windows 7 Pro Service Pack 1?

**Comment by readzilla** [comment]
BTW, I don't expect anyone to respond quickly!

I'm posting as I go so that if anyone else is interested, they can retrace the steps, _not_ as some kind of "No one answered?  I'll ask again!!!" thing.

**Comment by ElleKayEm** [comment]
If you use the DeDRM calibre plugin, you don't need to worry about Python or Pycrypto.  Assuming you can open your books in ADE 2.0.1 authorized with you Adobe ID, this setup should be good:

- ADE 2.0.1
- current version of calibre (not sure what it's on, it updates so often.)
- Latest DeDRM plugin (currently 6.5.3)

I'm wondering if there's a way to grab your working key from the DeDRM app on your WinXP machine.  I don't know since I'm not familiar with the standalone app.  I know you can export and import keys from the plugin.  Otherwise, you might need to completely remove ADE including preference folders and registry entries from your Win7 machine.  Then reinstall, reauthorize, and try again.  It could be some lurking piece of a previous ADE install that is causing problems for DeDRM in retrieving your key.

**Comment by apprenticeharper** [comment]
Since you have a working setup on your XP machine, and your Adobe ID is the same, just run Adobekey.pyw on your XP machine and copy the generated key file to your new machine.

Stick to ADE 2.0.1, otherwise one day you'll find yourself with an un-DRMable ePub using Adobe's new encryption scheme.
