### ISSUE TITLE
Can't de-DRM in Calibre, but only some  books 

### ISSUE THREAD

**Issue by cold-n-sour** [apprenticeharper/DeDRM_tools#285]
Never had a problem de-DRM'ing my books before, but recently some of them fail to decrypt. 

Here's a log of one such attempt:

calibre Debug log
calibre 2.85.1  embedded-python: True is64bit: True
Darwin-16.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.6.0', 'Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.12.5', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 125.500001885 x 125.500001885
Starting up...
Started up in 1.84 seconds with 942 books
DeDRM v6.5.3: Trying to decrypt Memory Man (Amos Decker series Book 1).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright В© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Memory Man (Amos Decker series Book 1)
Found 6 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/victor/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Couldn't decrypt file.
DeDRM v6.5.3: Ultimately failed to decrypt after 1.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 1.1 seconds

**Comment by ElleKayEm** [comment]
If it's from or for an E-ink Kindle (not a Fire), then you need to enter its serial number into the plugin customization.  Otherwise, download it with Kindle for Mac version 1.17.  See the FAQs:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by cold-n-sour** [comment]
Thank you, that fixed it!

**Comment by ElleKayEm** [comment]
Go ahead and close the issue.

**Comment by cold-n-sour** [comment]
This issue was opened by mistake, I didn't realize that the key for the newest Kindle was not added to plugin. Thank you for the help, ElleKayEm!
