### ISSUE TITLE
(Android Kindle) Choosing Backup File in Plugin configuration does nothing.

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [apprenticeharper/DeDRM_tools#286]
I am using this guide: https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_calibre_plugin/DeDRM_plugin/DeDRM_Kindle%20for%20Android%20Key_Help.htm

I made the backup file with `adb` from command line:

    adb backup com.amazon.kindle

It creates a `backup.ab` file as it should. Then I try to choose that file in the configuration of the file type plugin DeDRM. However, that does nothing. No key appears next to the button and I cannot progress. I am unsure what I can do now.

# Info

* Phone: MotoG
* OS: Android `5.1` SDK version: `5.1`, API Level: `22`, 
* Kindle version: `7.11.0.115`
* OS: Xubuntu 16.04
* Installed `adb` from repositories `apt-get install android-tools-adb`, version: `1.0.32`

**Comment by j-howell** [comment]
There was some discussion in the comments of Alf's blog back in late 2015 about Amazon changing the Android app so that this process no longer works. Perhaps it will work if you can obtain an old enough version of the app.

**Comment by ZelphirKaltstahl** [comment]
@j-howell I remember being able to create PDFs from ebooks I had in Amazon Cloud Reader, where I chose to download them and then open with Calibre, to prepare to use them in another app than Kindle. That did not involve any key file or backing up. It did not require credentials, if I remember correctly. However, that was most likely in 2016, not so long ago.

Is there another way to get my ebooks as readable PDF or is it simply the current status, that with the current Kindle app there is no way at the moment?

**Comment by j-howell** [comment]
Several other methods of DRM removal still work for Kindle books. See the main FAQ:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by apprenticeharper** [comment]
The  Kindle for Android method stopped working some version ago, when they set the flag to forbid backups. The backup file now contains no useful info.

**Comment by thomaseizinger** [comment]
If the method no longer works, it should probably be removed from the help section? It is kind of hard to debug that it no-longer works when you are just getting started with DeDRM :)
