### ISSUE TITLE
Suddenly stop working on Calibre / Win10-64

### ISSUE THREAD

**Issue by cyberjani** [apprenticeharper/DeDRM_tools#287]
Few days ago I was still happy adding DRM books from Adobe Digital Editions 3.0 to Calibre 2.84... using DeDRM 6.5.2. But not today. I've upgraded Calibre and DeDRM to the latest release and downgraded ADE to version 2.0, but nothing helps. Any suggestion? Log attached.
Best regards,
Jani
[tmp7owael_jr20170601.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1044874/tmp7owael_jr20170601.txt)

**Comment by ElleKayEm** [comment]
The book in the log is not being detected as having Adobe DRM.  How did you download it?

**Comment by cyberjani** [comment]
I downloaded it from a bookstore (biblos.si) as acsm file. I added it (actually 4 of them) to ADE library. After that I picked it up with Calibre from Adobe folder as epub file. As I always do.

**Comment by ElleKayEm** [comment]
We're they originally downloaded with ADE 3?  If so, can you open them in ADE 2 authorized with your Adobe ID?

**Comment by apprenticeharper** [comment]
I suspect that the bookstore turned on the newer DRM scheme. In which case, the books won't work with ADE 2.x
