### ISSUE TITLE
Cannot DeDRM successfully for azw3 in kindle touch.

### ISSUE THREAD

**Issue by lefeudelavie** [apprenticeharper/DeDRM_tools#288]
calibre Debug log
calibre 2.85.1  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Starting up...
Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')],
 (7L, 1L): [(1L, 'G'), (2L, 'H')],
 (7L, 2L): [(1L, 'E'), (2L, 'F')],
 (7L, 3L): [(1L, 'I')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\B00F260714671LER&0: StorageDeviceNumber(type=7L, number=3L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=3228)
{u'drive_letters': ['I'],
 u'pnp_id_map': {'I': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#b00f260714671ler&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'I': (3L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: I:\ documents
DEBUG:    0.2 USBMS: scan from root False I:\documents
Job: 2 Set library information finished
No details available.
Job: 1 Get device information finished
No details available.
DEBUG:    1.3 USBMS: count found in cache: 98, count of files in metadata: 98, need_sync: False
DEBUG:    1.3 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    1.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    1.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 98
DeviceJob: set_books_in_library finished: time= 0.00799989700317
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Started up in 10.95 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x12?\x07\xb1\xb6"\xa0\x90\xbcS\x18n\xa9\x94\xec\xcb\xa0\xd9\x14Q\xe6\xd6-;\xe8\x80)wF\xeb\x0cO', 'I:\\documents\\The Big Book of Health and Fitness_ A Practical Guide to Diet, Exercise, Healthy Aging, Illness Prevent_B008EX1WTS.azw3']
DeDRM v6.5.3: Trying to decrypt The Big Book of Health and Fitness_ A Practical Guide to Diet, Exercise, Healthy Aging, Illness Prevent_B008EX1WTS.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Big Book of Health and Fitness: A Practical Guide to Diet, Exercise, Healthy Aging, Illness Prevention, and Sexual Well-Being
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Alex\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Alex\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '550658700' and UserName '416c6578'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Big Book of Health and Fitness: A Practical Guide to Diet, Exercise, Healthy Aging, Illness Prevention, and Sexual Well-Being
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
Added The Big Book of Health and Fitness: A Practical Guide to Diet, Exercise, Healthy Aging, Illness Prevention, and Sexual Well-Being to db in: 0.2
Added 1 books in 0.7 seconds

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then you need to enter its serial number into the plugin cuatomization.  Otherwise, see method 1 or 2 in this post at MobileRead for getting AZW3 files from Kindle for PC:
https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by apprenticeharper** [comment]
Assumed solved. Closed.
