### ISSUE TITLE
Can't add DRM-ed book to Calibre library from Kobo reader

### ISSUE THREAD

**Issue by ReaderfRik** [apprenticeharper/DeDRM_tools#289]
Windows 7, Kobo Glo, wired connected
calibre Fehlerdiagnoseprotokoll
calibre 2.82  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Annotations (1, 4, 7)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9292035398 x 72.0567375887
Starting up...
Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')],
 (7L, 1L): [(1L, 'F')],
 (7L, 2L): [(1L, 'G')]}
Storage number for USBSTOR\DISK&VEN_KOBO&PROD_EREADER-4.3.8945&REV_0110\613A372040439&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Storage number for USBSTOR\DISK&VEN_KOBO&PROD_EREADER-4.3.8945&REV_0110\613A372040439&1: StorageDeviceNumber(type=7L, number=2L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x2237 product_id=0x4173 bcd=0x110 devid=usb\vid_2237&pid_4173&rev_0110 devinst=3684)
{u'drive_letters': ['F', 'G'],
 u'pnp_id_map': {'F': u'\\\\?\\usbstor#disk&ven_kobo&prod_ereader-4.3.8945&rev_0110#613a372040439&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}',
                 'G': u'\\\\?\\usbstor#disk&ven_kobo&prod_ereader-4.3.8945&rev_0110#613a372040439&1#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'F': (1L, 1L), 'G': (2L, 1L)}}
Job: 1 Geräteinformationen erhalten started
DeviceJob: 1 Geräteinformationen erhalten done, calling callback
DeviceJob: 1 Geräteinformationen erhalten callback returned
Job: 2 Bibliotheksinformationen festlegen started
DeviceJob: 2 Bibliotheksinformationen festlegen done, calling callback
DeviceJob: 2 Bibliotheksinformationen festlegen callback returned
Job: 3 Liste der Bücher auf dem Gerät erhalten started
DEBUG:    0.0 KoboTouch:books - oncard='None'
DEBUG:    0.0 KoboTouch:books - oncard='None', prefix='F:\'
DEBUG:    0.0 Kobo device: Kobo Glo
DEBUG:    0.0 Version of driver: (2, 3, 3) Has kepubs: True
DEBUG:    0.0 Version of firmware: (4, 3, 8945) Has kepubs: True
DEBUG:    0.0 Firmware supports cover image tree: True
DEBUG:    0.1 KoboTouch:books - opts.extra_customization= []
DEBUG:    0.1 KoboTouch:books - driver options= Driver:KoboTouch, Options - format_map: [u'kepub', u'epub', u'pdf', u'txt', u'cbz', u'cbr'], use_subdirs: True, read_metadata: True, use_author_sort: False, save_template: {author_sort}/{title} - {authors}, extra_customization: [], manage_collections: True, collections_columns: , create_collections: True, delete_empty_collections: True, ignore_collections_names: , upload_covers: True, keep_cover_aspect: False, upload_grayscale: False, show_archived_books: True, show_previews: True, show_recommendations: False, update_series: False, update_device_metadata: True, modify_css: False, support_newer_firmware: True, debugging_title: , driver_version: 2.3.1
DEBUG:    0.1 KoboTouch:books - prefs['manage_device_metadata']= manual
DEBUG:    0.1 KoboTouch:books - set_debugging_title to ''
DEBUG:    0.1 KoboTouch:books - length bl=0
DEBUG:    0.2 KoboTouch:books - length bl after sync=38
DEBUG:    0.2 KoboTouch:books - reading device database
DEBUG:    0.2 Database Version:  137
DEBUG:    0.2 KoboTouch:books - shelf list: [u'1', u'Sachb\xfccher - nicht gelesen', u'Fiktion - gelesen', u'Sachb\xfccher - gelesen', u'Fiktion - nicht gelesen', u'ReadingList']
DEBUG:    0.2 KoboTouch:books - query= SELECT Title, Attribution, DateCreated, ContentID, MimeType, ContentType, ImageID, ReadStatus, ___ExpirationStatus, FavouritesIndex, Accessibility, IsDownloaded, Series, SeriesNumber, ___UserID, ExternalId FROM content  WHERE BookID IS NULL  AND ((Accessibility = -1 AND IsDownloaded in ('true', 1 ))       OR (Accessibility IN (1,2,9) )        OR (Accessibility in (6) AND ___UserID <> '')  )  AND (externalId IS NULL OR externalId = '') AND contentId NOT LIKE 'file:///mnt/sd/%'
Job: 1 Geräteinformationen erhalten finished
Keine weiteren Informationen verfügbar.
Job: 2 Bibliotheksinformationen festlegen finished
Keine weiteren Informationen verfügbar.
DEBUG:    0.5 KoboTouch:books - about to sync_booklists
DEBUG:    0.5 USBMS: starting sync_booklists
DEBUG:    0.6 USBMS: finished sync_booklists
DEBUG:    0.6 KoboTouch:books - have done sync_booklists
DEBUG:    0.6 KoboTouch:books - end - oncard='None'
DEBUG:    0.6 KoboTouch:books - oncard='carda'
DEBUG:    0.6 KoboTouch:books - oncard='carda', prefix='G:\'
DEBUG:    0.6 Kobo device: Kobo Glo
DEBUG:    0.6 Version of driver: (2, 3, 3) Has kepubs: True
DEBUG:    0.6 Version of firmware: (4, 3, 8945) Has kepubs: True
DEBUG:    0.6 Firmware supports cover image tree: True
DEBUG:    0.6 KoboTouch:books - opts.extra_customization= []
DEBUG:    0.6 KoboTouch:books - driver options= Driver:KoboTouch, Options - format_map: [u'kepub', u'epub', u'pdf', u'txt', u'cbz', u'cbr'], use_subdirs: True, read_metadata: True, use_author_sort: False, save_template: {author_sort}/{title} - {authors}, extra_customization: [], manage_collections: True, collections_columns: , create_collections: True, delete_empty_collections: True, ignore_collections_names: , upload_covers: True, keep_cover_aspect: False, upload_grayscale: False, show_archived_books: True, show_previews: True, show_recommendations: False, update_series: False, update_device_metadata: True, modify_css: False, support_newer_firmware: True, debugging_title: , driver_version: 2.3.1
DEBUG:    0.6 KoboTouch:books - prefs['manage_device_metadata']= manual
DEBUG:    0.6 KoboTouch:books - set_debugging_title to ''
DEBUG:    0.6 KoboTouch:books - length bl=0
DEBUG:    0.6 KoboTouch:books - length bl after sync=0
DEBUG:    0.6 KoboTouch:books - reading device database
DEBUG:    0.6 Database Version:  137
DEBUG:    0.6 KoboTouch:books - shelf list: [u'1', u'Sachb\xfccher - nicht gelesen', u'Fiktion - gelesen', u'Sachb\xfccher - gelesen', u'Fiktion - nicht gelesen', u'ReadingList']
DEBUG:    0.6 KoboTouch:books - query= SELECT Title, Attribution, DateCreated, ContentID, MimeType, ContentType, ImageID, ReadStatus, ___ExpirationStatus, FavouritesIndex, Accessibility, IsDownloaded, Series, SeriesNumber, ___UserID, ExternalId FROM content  WHERE BookID IS NULL  AND ((Accessibility = -1 AND IsDownloaded in ('true', 1 ))       OR (Accessibility IN (1,2,9) )        OR (Accessibility in (6) AND ___UserID <> '')  )  AND (externalId IS NOT NULL AND externalId <> '' OR contentId LIKE 'file:///mnt/sd/%')
DEBUG:    0.7 KoboTouch:books - about to sync_booklists
DEBUG:    0.7 USBMS: starting sync_booklists
DEBUG:    0.7 USBMS: finished sync_booklists
DEBUG:    0.7 KoboTouch:books - have done sync_booklists
DEBUG:    0.7 KoboTouch:books - end - oncard='carda'
DEBUG:    0.7 KoboTouch:books - oncard='cardb'
DEBUG:    0.7 KoboTouch:books - Asked to process 'cardb', but do not have one!
DeviceJob: 3 Liste der Bücher auf dem Gerät erhalten done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 38
DeviceJob: set_books_in_library finished: time= 0.0110001564026
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Liste der Bücher auf dem Gerät erhalten callback returned
Job: 3 Liste der Bücher auf dem Gerät erhalten finished
Keine weiteren Informationen verfügbar.
Started up in 12.53 seconds with 27 books

**Comment by ElleKayEm** [comment]
You need the Obok plugin for that.

**Comment by ReaderfRik** [comment]
Thanks for your help attempt, but the plugin gives finalliy this message after selecting in Calibre a DRM-ed book on my reader:

calibre, version 2.82.0
FEHLER: Nicht abgefangener Fehler: <b>DatabaseError</b>:file is encrypted or is not a database
calibre 2.82  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Obok DeDRM (3, 1, 1) && Kobo Utilities (2, 5, 2) && Annotations (1, 4, 7)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 85, in launchObok
  File "calibre_plugins.obok_dedrm.action", line 187, in build_book_list
  File "calibre_plugins.obok_dedrm.obok.obok", line 252, in books
DatabaseError: file is encrypted or is not a database

**Comment by ElleKayEm** [comment]
Get the latest version of Obok -- currently 6.5.3 (same as DeDRM).

**Comment by ReaderfRik** [comment]
I can't do so much with your last hint.
 But I stop my attempts, most books I could copy now.
Thanks so far!

Am 06.06.2017 20:55 schrieb "ElleKayEm" <notifications@github.com>:

**Comment by ElleKayEm** [comment]
Your last log showed Obok 3.1.1.  The latest release available here is version 6.5.3.  (Obok's version number was changed to match DeDRM's at some point.)

**Comment by ReaderfRik** [comment]
OK, sorry, I didn't notice that!
Maybe I'll give it then another try. In case of success I'll let you know
:-)


Am 08.06.2017 18:36 schrieb "ElleKayEm" <notifications@github.com>:

**Comment by apprenticeharper** [comment]
Assumed solved. Closed.
