### ISSUE TITLE
Kindle for Android code won't run correctly if userdata_row is empty

### ISSUE THREAD

**Issue by ableeker** [apprenticeharper/DeDRM_tools#29]
If userdata_row is empty, the code won't run because an empty string (or is it NULL even?) can't have encode, or len. Luckily it will just return false if you test it. If I modify the code to use this feature, it runs. That's not to say it does what it's supposed to, but I think it does. I hope so anyway.

    for userdata_row in userdata_keys:
        if userdata_row:
            userdata_row0 = userdata_row[0]
            if userdata_row0:
                userdata_utf8 = userdata_row0.encode('utf8')

**Comment by apprenticeharper** [comment]
Thanks. I haven't encountered this problem, but the next update will take account of it.
