### ISSUE TITLE
kindlekey.pyw update

### ISSUE THREAD

**Issue by jobidon** [apprenticeharper/DeDRM_tools#290]
I was trying to import AWZ3 books into calibre in Arch using the Kindle for PC app in a VM. Ran into a few issues, but in the end, the main setback was the import of the key file from the VM into the plugin config page. To do this, I installed python2 (python3 won't work with this) in the VM to run the pythonkey script. But to make this work, the script had to be modified (see new version below).
HTH
[kindlekey.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1058492/kindlekey.txt)

**Comment by dunesmopy** [comment]
Thanks for creating a ticket and attaching your work. The attached file looks like a very old version. Checking both:
* https://github.com/apprenticeharper/DeDRM_tools/commits/master/Other_Tools/DRM_Key_Scripts/Kindle_for_Mac_and_PC/kindlekey.pyw
* https://github.com/apprenticeharper/DeDRM_tools/commits/master/DeDRM_Windows_Application/DeDRM_App/DeDRM_lib/lib/kindlekey.py

they are documented as being version 2.2 versus the attached version 1.9. There is a high likely hood the changes (or similar ones) you made are already included in the latest version. I'd recommend you pull down the latest version and see if that works, if not it would be good to get a diff figured out to see what you needed to change so it is the best it can be.

**Comment by apprenticeharper** [comment]
Please create a new issue (or a pull request) if you still think your changes are useful once you've updated to the latest version. Closed.
