### ISSUE TITLE
DRM won't remove from ePub

### ISSUE THREAD

**Issue by absolutfragile** [apprenticeharper/DeDRM_tools#291]
All of my books were purchased from Barnes & Noble and the plugin still can't remove the DRM from my books.

calibre Debug log
calibre 2.85.1  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.110344828
Starting up...
Started up in 6.93 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xc1U\x15v6\xd4\x15\xcf\x89\x9f\x0f\x1dV\x80\xc7d\xf9\x10\x83K3\x822\xb3\x15%B[\xf6D<\xbc', 'C:\\Users\\0110BTHOM22\\Desktop\\brittanythoma05@gmail.com\\afterburn_9781459245952.epub']
DeDRM v6.5.3: Trying to decrypt afterburn_9781459245952.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: “afterburn_9781459245952.epub” is a secure Barnes & Noble ePub
DeDRM v6.5.3: Looking for new NOOK Study Keys after 0.3 seconds
No nook Study log files have been found.
DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 292, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Added Afterburn to db in: 1.4
Added 1 books in 2.6 seconds

**Comment by ElleKayEm** [comment]
Have you entered your B&N account email and password into the plugin customization in order to retrieve your key?

**Comment by absolutfragile** [comment]
No, I'm sorry but can you give me the steps for that? I didn't see that step in the guides

**Comment by ElleKayEm** [comment]
From the plugin Readme:  "highlight the plugin (DeDRM under the "File type plugins" category) and click the "Customize Plugin" button.

The buttons in the configuration dialog will open individual configuration dialogs that will allow you to enter the needed information, depending on the type and source of your DRMed eBooks. Additional help on the information required is available in each of the the dialogs vias the [?] help button.

**Comment by apprenticeharper** [comment]
Assumed solved. Closed.
