### ISSUE TITLE
help with azw3 file

### ISSUE THREAD

**Issue by kubera78** [apprenticeharper/DeDRM_tools#292]
Hi.
I have a e-book from a friend of mine. He buy the book from amazon and give it to me. I want to remove drm from the book. I try calibre with drm calibre plugin but didn't work. Any help pls?
thx

calibre Debug log
calibre 2.85.1  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 240.0 x 240.0
physicalDpi: 277.406143345 x 277.090909091
Starting up...
Started up in 9.60 seconds with 0 books
DeDRM v6.5.3: Trying to decrypt Electrical Installation Work_ Level 3_ EAL Edition_B01GVDXZHY.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Electrical Installation Work: Level 3: EAL Edition
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\mahes\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\mahes\AppData\Local\Amazon\Kindle\storage\.kinf2011
Couldn't decrypt file.
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
Added Electrical Installation Work: Level 3: EAL Edition to db in: 0.2
Added 1 books in 1.2 seconds

**Comment by ElleKayEm** [comment]
These tools are for books you have purchased yourself.  They unlock the books with the keys from your own accounts.
