### ISSUE TITLE
UnboundLocalError when trying to remove DRM from an old AZW

### ISSUE THREAD

**Issue by manka3s** [apprenticeharper/DeDRM_tools#293]
Trying to scrape an ebook off an old Windows XP box, using Calibre 1.4.8 with DeDRM 6.5.3 but it doesn't remove the DRM.
(Note that Kindle 1.6.1 for PC on same box still opens that ebook, if I adjust the computer date back a few years.)

calibre Debug log
calibre 1.48  isfrozen: True is64bit: False
Windows-XP-5.1.2600-SP3 Windows ('32bit', 'WindowsPE')
('Windows', 'XP', '5.1.2600')
Python 2.7.5
Windows: ('XP', '5.1.2600', 'SP3', 'Multiprocessor Free')
Starting up...
Failed to check for calibre update: <urlopen error [Errno 11001] getaddrinfo failed>
Failed to check for plugin update: <urlopen error [Errno 11001] getaddrinfo failed>
Started up in 11.03 seconds with 1 books
Worker Launch took: 0.641000032425
Job: 1 Read metadata (0 of 1) finished
Read metadata (0 of 1)
	DeDRM v6.5.3: Trying to decrypt B005xxxxxx_EBOK.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.41.
	Copyright © 2008-2012 The Dark Reverser et al.
	MOBI header version 5, header length 248
	Extra Data Flags: 1
	Decrypting Mobipocket 5 ebook: An Unconventional Guide
	Found 0 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
	DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Documents and Settings\Administrator\Local Settings\Application Data
	Found K4PC 1.6-1.8 kinf file: C:\Documents and Settings\Administrator\Local Settings\Application Data\Amazon\Kindle\storage\rainier.2.1.1.kinf
	DeDRM v6.5.3: Exception when getting default Kindle Key after 0.2 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 529, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.kindlekey", line 1566, in kindlekeys
	  File "calibre_plugins.dedrm.kindlekey", line 1047, in getDBfromFile
	UnboundLocalError: local variable 'added_entropy' referenced before assignment
	DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
	Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 610, in run
	  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
	DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds
	Failed to read MOBI cover

Added An Unconventional Guide to db in: 0.297000169754 seconds

**Comment by ElleKayEm** [comment]
Don't really know what that error means, but maybe an older version of DeDRM would work?  Since that's the only current program in this setup.

I assume there's some reason you can't download a fresh copy of the book to a newer setup?

**Comment by manka3s** [comment]
Good idea, it worked with 6.2.0.

I have tracked it down to the following:
works with Calibre Plugin 6.4.0
works with 6.4.2
doesn't work with 6.4.3 (same error as in debug log above)
doesn't work with 6.5.0 (Note: calibre plugin shows 6.4.4)
doesn't work with 6.5.3, as stated before.

Important:
when replacing plugins for crosschecks especially from working to not working version, do not forget to remove the ...\calibre\plugin\dedrm.json file, as otherwise DeDRM uses the previously extracted key from it.

Thanks

**Comment by ElleKayEm** [comment]
Glad you got it figured out.  Go ahead and close the issue if you're all set.

**Comment by apprenticeharper** [comment]
Note that support for very old versions of Kindle for PC was removed recently. That's why the latest version won't work with Kindle for PC 1.6. Note that Kindle for PC 1.6 won't connect to Amazon.
