### ISSUE TITLE
Cannot convert azw3 library file (via Amazon) using latest DeDRM tools 6.5.3

### ISSUE THREAD

**Issue by fymichaud** [apprenticeharper/DeDRM_tools#294]
I was successful in doing this conversion just a few weeks ago.  I borrow library books to read on my Amazon Paperwhite reader.  The books are downloaded from Amazon as arranged by the library.  These are azw3 files.  As instructed, I have used the debug mode....which I have pasted below.  I use Calibre on a PC using the latest Windows 10.  Can anybody help?

calibre Debug log
calibre 2.85.1 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.7381489842 x 91.8072289157
Starting up...
Started up in 30.75 seconds with 15063 books
DeDRM v6.5.3: Trying to decrypt The Venetian Betrayal_ A Novel (Cotton Malone Book 3).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Venetian Betrayal: A Novel (Cotton Malone Book 3)
Found 2 keys to try after 1.8 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 1.8 seconds
searching for kinfoFiles in C:\Users\fymichaud\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.3: Ultimately failed to decrypt after 1.8 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 1.8 seconds
Added The Venetian Betrayal: A Novel (Cotton Malone Book 3) to db in: 4.2
Added 1 books in 6.7 seconds
Worker Launch took: 0.34700012207
Job: 1 Convert book 1 of 1 (The Venetian Betrayal: A Novel (Cotton Malone Book 3)) finished
Convert book 1 of 1 (The Venetian Betrayal: A Novel (Cotton Malone Book 3))
	Conversion options changed from defaults:
	  output_profile: 'generic_eink'
	  cover: u'C:\\Users\\FYMICH~1\\AppData\\Local\\Temp\\calibre_szayvl\\6qw9rn.jpeg'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\FYMICH~1\\AppData\\Local\\Temp\\calibre_szayvl\\r9daik.opf'
	Resolved conversion options
	calibre version: 2.85.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*

**Comment by ElleKayEm** [comment]
From the FAQs:  "The tools are not designed to remove DRM from rented or library ebooks."

**Comment by khaaan** [comment]
ElleKayEm: Can you elaborate on how that FAQ entry is relevant? The error being reported here is "Ultimately failed to decrypt after # seconds.", whereas the FAQ entry refers to the error "Failed to decrypt with error: Cannot decode library or rented ebooks.".

**Comment by ElleKayEm** [comment]
I think that error actually only appears for rented ebooks.  But I'm not going to help with DRM removal from library books.
