### ISSUE TITLE
What's the missing file?

### ISSUE THREAD

**Issue by marcus5005** [apprenticeharper/DeDRM_tools#295]
Below is from the log file. How do I fix it?

There is 1 ebook to be decrypted.
Processing file: The Sunday Philosophy Club.epub
shellcommand: /usr/bin/python '/Users/marcus/Downloads/DeDRM_tools_6.5.3/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/zipfix.py' '/Users/marcus/Documents/Digital Editions/The Sunday Philosophy Club.epub' '/Users/marcus/Desktop/The Sunday Philosophy Club_fixed.epub' > '/Users/marcus/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult:  sh: /Users/marcus/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log: No such file or directory
There was an error with 1 ebook:
The Sunday Philosophy Club.epub had a problem with ZipFix:
sh: /Users/marcus/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log: No such file or directory

**Comment by ElleKayEm** [comment]
Maybe it's that the folder doesn't exist?  Create the folder:

Users/marcus/Library/Preferences/com.apprenticealf.dedrm/

Then try again.

**Comment by apprenticeharper** [comment]
Or try the latest 6.5.4 version released yesterday, which should fix this bug.
