### ISSUE TITLE
Nook eInk reader

### ISSUE THREAD

**Issue by clayesq** [apprenticeharper/DeDRM_tools#296]
sorry... noob... trying to copy some of my book from a 1st gen Nook, and get this error:Error generating key from this info, error message was: sh:/Users/chummer/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log: No such file or directory

I assume that is what is in the script folder? If not, now what?

Thanks!

**Comment by ElleKayEm** [comment]
Not that familiar with the stand-alone apps.  Try creating the folder
/Users/chummer/Library/Preferences/com.apprenticealf.dedrm/
