### ISSUE TITLE
Calibre 3.0 and DRM file

### ISSUE THREAD

**Issue by clayesq** [apprenticeharper/DeDRM_tools#297]
Just tried again to copy files from 1st gen nook via Calibre. Using macOS Sierra 10.12.5. No luck. Please find attached...
Any assistance would be appreciated!
[tmpL6O7_n.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1081277/tmpL6O7_n.txt)

**Comment by ElleKayEm** [comment]
Try downloading fresh copies of your books.  B&N changed all keys a while back so old books won't unlock with your current key.

**Comment by clayesq** [comment]
Thanks! Ended up de, then re-registering my Nook... the stand alone app worked fine at that point! Thanks for the assistance!

**Comment by ElleKayEm** [comment]
Great!  Close the issue if you're all set.
