### ISSUE TITLE
ActiveState Python 32 bit no longer available For linux calibre plugin install

### ISSUE THREAD

**Issue by fayena** [apprenticeharper/DeDRM_tools#298]
I'm not a programer, I generally just follow instructions to get things working.   However, the 32bit version of activestate python appears to no longer be available.   The newest 64 bit kept giving an install error.   I had an older 64 bit version downloaded so I tried it.   It did install but the dedrm plugin wouldn't find it (wrong install location).   So I finally tried this 32 bit version Windows x86 MSI Installer (2.7.8) from https://www.python.org/download/releases/2.7.8/  and installed with this command "msiexec /i python-2.7.8.msi"

This finally worked so long as you specify the wine prefix.   In my case it was the default  "~/.wine"  but I had to manually specify it before the key was found.   

I hope this helps someone else.   

EDIT:   Forgot to add I'm using Ubuntu 17.04 with wine-2.0.1

**Comment by apprenticeharper** [comment]
Thanks for the comments. The advice for installing Windows python could do with updating. It's jut so much easier to install calibre and use the plugin!
