### ISSUE TITLE
Have a problem with only one book failing to convert

### ISSUE THREAD

**Issue by mertkd** [apprenticeharper/DeDRM_tools#299]
Are all Kindle books DRM'd with the same encryption? Is it possible this one book simply has an error tht prevents it from converting? I have converted hundreds of my books, but have an issue with one specific book. How do I proceed? Here are the conversion error details.

calibre, version 3.0.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (A Woman Rides the Beast: The Roman Catholic Church and the Last Days)
Convert book 1 of 1 (A Woman Rides the Beast: The Roman Catholic Church and the Last Days)
Conversion options changed from defaults:
  cover: u'C:\\Users\\ken\\AppData\\Local\\Temp\\calibre_ddcit_\\fh_al8.jpeg'
  verbose: 2
  read_metadata_from_opf: u'C:\\Users\\ken\\AppData\\Local\\Temp\\calibre_ddcit_\\3nee1g.opf'
  output_profile: 'kindle_pw'
Resolved conversion options
calibre version: 3.0.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\ken\\AppData\\Local\\Temp\\calibre_ddcit_\\fh_al8.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002794FA5FFD0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': u'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x000002794FA616A0>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'personal_doc': u'[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\ken\\AppData\\Local\\Temp\\calibre_ddcit_\\3nee1g.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\ken\AppData\Local\Temp\calibre_ddcit_\83xb8_.azw3
Found KF8 MOBI of type 'standalone'
Extracting text...
Parsing all content...
Parsing text/part0042.html ...
Parsing text/part0024.html ...
Parsing text/part0070.html ...
Parsing text/part0072.html ...
Parsing text/part0043.html ...
Parsing text/part0025.html ...
Parsing text/part0006.html ...
Parsing text/part0067.html ...
Parsing text/part0044.html ...
Parsing text/part0051.html ...
Parsing text/part0026.html ...
Parsing text/part0048.html ...
Parsing text/part0066.html ...
Parsing text/part0064.html ...
Parsing text/part0027.html ...
Parsing text/part0046.html ...
Parsing text/part0007.html ...
Parsing text/part0056.html ...
Parsing text/part0028.html ...
Parsing text/part0053.html ...
Parsing text/part0016.html ...
Parsing text/part0015.html ...
Parsing text/part0068.html ...
Parsing text/part0029.html ...
Parsing text/part0008.html ...
Parsing text/part0057.html ...
Parsing text/part0062.html ...
Parsing text/part0030.html ...
Parsing text/part0018.html ...
Parsing text/part0073.html ...
Parsing styles/0001.css ...
PropertyValue: No match: ('CHAR', u'%', 298, 19)
PropertyValue: Unknown syntax or no value: 1%%
CSSStyleDeclaration: Syntax Error in Property: margin-right:1%%
Parsing text/part0069.html ...
Parsing text/part0031.html ...
Parsing text/part0009.html ...
Parsing styles/0002.css ...
PropertyValue: No match: ('CHAR', u'%', 315, 19)
PropertyValue: Unknown syntax or no value: 1%%
CSSStyleDeclaration: Syntax Error in Property: margin-right:1%%
Parsing text/part0058.html ...
Parsing text/part0032.html ...
Parsing text/part0050.html ...
Parsing text/part0019.html ...
Parsing text/part0001.html ...
Parsing text/part0047.html ...
Parsing text/part0033.html ...
Parsing text/part0010.html ...
Parsing text/part0063.html ...
Parsing text/part0000.html ...
Parsing text/part0059.html ...
Parsing text/part0034.html ...
Parsing text/part0020.html ...
Parsing text/part0074.html ...
Parsing text/part0035.html ...
Parsing text/part0011.html ...
Parsing text/part0002.html ...
Parsing text/part0060.html ...
Parsing text/part0036.html ...
Parsing text/part0021.html ...
Parsing text/part0071.html ...
Parsing text/part0037.html ...
Parsing text/part0012.html ...
Parsing text/part0055.html ...
Parsing text/part0003.html ...
Parsing text/part0061.html ...
Parsing text/part0052.html ...
Parsing text/part0038.html ...
Parsing text/part0022.html ...
Parsing text/part0049.html ...
Parsing text/part0065.html ...
Parsing text/part0039.html ...
Parsing text/part0013.html ...
Parsing text/part0004.html ...
Parsing text/part0045.html ...
Parsing text/part0054.html ...
Parsing text/part0040.html ...
Parsing text/part0023.html ...
Parsing text/part0017.html ...
Parsing text/part0075.html ...
Parsing text/part0041.html ...
Parsing text/part0014.html ...
Parsing text/part0005.html ...
Referenced file u'text/XXXXXXXXXXXXXXXX' not found
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 1 items of level: div_1
Found 5 items of level: p_2
Found 3615 items of level: p_1
Ignoring level p_2
div_1  left margin stats: Counter({u'15%': 1})
div_1  right margin stats: Counter({u'': 1})
Removing level div_1 left margin of: 15%
Negative text indent detected at level  p_1, ignoring this level
Cleaning up manifest...
Trimming unused files from manifest...
Trimming u'images/00006.jpeg' from manifest
Creating MOBI Output...
Serializing resources...
Creating MOBI 6 output
Generating in-line TOC...
Applying case-transforming CSS...
Parsing manglecase.css ...
Parsing tocstyle.css ...
Rasterizing SVG images...
Converting XHTML to Mobipocket markup...
Python function terminated unexpectedly
  Argument must be bytes or unicode, got 'float' (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1252, in run
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_output.py", line 212, in convert
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_output.py", line 244, in write_mobi
  File "site-packages\calibre\ebooks\mobi\mobiml.py", line 125, in __call__
  File "site-packages\calibre\ebooks\mobi\mobiml.py", line 136, in mobimlize_spine
  File "site-packages\calibre\ebooks\mobi\mobiml.py", line 580, in mobimlize_elem
  File "site-packages\calibre\ebooks\mobi\mobiml.py", line 578, in mobimlize_elem
  File "site-packages\calibre\ebooks\mobi\mobiml.py", line 296, in mobimlize_content
  File "src/lxml/lxml.etree.pyx", line 3127, in lxml.etree.SubElement (src\lxml\lxml.etree.c:78512)
  File "src/lxml/apihelpers.pxi", line 203, in lxml.etree._makeSubElement (src\lxml\lxml.etree.c:18851)
  File "src/lxml/apihelpers.pxi", line 198, in lxml.etree._makeSubElement (src\lxml\lxml.etree.c:18777)
  File "src/lxml/apihelpers.pxi", line 302, in lxml.etree._initNodeAttributes (src\lxml\lxml.etree.c:20259)
  File "src/lxml/apihelpers.pxi", line 316, in lxml.etree._addAttributeToNode (src\lxml\lxml.etree.c:20597)
  File "src/lxml/apihelpers.pxi", line 1441, in lxml.etree._utf8 (src\lxml\lxml.etree.c:31851)
TypeError: Argument must be bytes or unicode, got 'float'

**Comment by ElleKayEm** [comment]
I don't see any mention in the log about failing to convert because of DRM.  Although to see what happened with DRM removal, we'd need to look at an import log.

The new KFX format has encryption which the tools can't handle yet.  Also every device and app installation has its own unique key.

If it is just a problem with conversion, then there are a couple things you could try: using the 64-bit version of calibre if possible and/or using the Kindle Unpack plugin instead of calibre's conversion.

**Comment by mertkd** [comment]
Thanks! Interesting that it will unpack to an epub format that I can use in my preferred reader, but I can't still can't convert the epu. to a mobi format. Regardless, it works, and I thank you for pointing me in the right direction!

**Comment by ElleKayEm** [comment]
If it's a large file, it might work with 64-bit calibre.  You could ask over in the MobileRead calibre forum.  Since it doesn't seem to be a DRM issue, you can go ahead and close this issue.
