### ISSUE TITLE
Question re: Calibre PlugIn Not working for Amazon Ebook

### ISSUE THREAD

**Issue by littl3mango** [apprenticeharper/DeDRM_tools#30]
I am running the DeDRM calibre plugin 6.3.3. And Calibre vers. 2.35.0. Windows 7 PC. 

When importing a DRM'ed .azw file, it simply does not remove the DRM and the dialogue box stating so pops up. In the read_me it does not mention much about customizing key files for PC. Is this something I must enter or import? Thank you.

**Comment by ElleKayEm** [comment]
As long as Kindle for PC is on the same PC and Windows user as calibre, then the plugin should automatically find the key.  Post an import log, and we will try to help you figure out what's wrong.

**Comment by littl3mango** [comment]
Thank you ElleKayEm for your help. I am uncertain of the process to obtain an import log. Please advise.

**Comment by ElleKayEm** [comment]
The info is in the DeDRM plugin readme, in the help link in the customization dialog for the plugin, and on the FAQs page at the Apprentice Alf blog.

**Comment by littl3mango** [comment]
![import log](https://cloud.githubusercontent.com/assets/8422506/9341710/5ce0aa08-45ac-11e5-900e-e250e7f588d8.JPG)

**Comment by ElleKayEm** [comment]
The tools do not work on library or rented ebooks.

**Comment by littl3mango** [comment]
Thank you!
