### ISSUE TITLE
GEtting Error when removing DRM

### ISSUE THREAD

**Issue by crakkus** [apprenticeharper/DeDRM_tools#301]
Hello,

I receive the error below when attempting to remove the DRM. I have found out that it is a 128bit RC4 encryption via FileOpen. I was recommended to use this program to help remove the DRM. Any hel would be aprpecaited.

![image](https://user-images.githubusercontent.com/29548413/27295091-5b2485ea-54e1-11e7-81b9-b7d9b576a169.png)

**Comment by ElleKayEm** [comment]
The tools here work on Adobe DRM, Kindle, Nook, and Kobo.

**Comment by crakkus** [comment]
this is an adobe DRM document with Adept DRM. This program does not decrypt that?

**Comment by ElleKayEm** [comment]
It works with Adobe DRMed files downloaded with Adobe Digital Editions (preferably version 2.0.1).  I'm not familiar with FileOpen, and I thought it was different DRM system.

**Comment by crakkus** [comment]
Dang. 

I was looking all morning for 3 hours trying to find something that can remove FileOpen DRM's from pdf.... no luck though.

Thanks for the the info!

**Comment by apprenticeharper** [comment]
If you look in the Other Tools folder, you'll find Tetrachroma_FileOpen_ineptpdf. This is a version of the ineptpdf script that is Windows only but might be able to help you. You'll need to run it manually at the command line, as it's not included in the plugin.

**Comment by apprenticeharper** [comment]
I hope that worked.
