### ISSUE TITLE
Cannot convert azw3 file

### ISSUE THREAD

**Issue by RobanHH** [apprenticeharper/DeDRM_tools#302]
Dears, 
I bought an ebook by Amazon on my kindle and I would like to enhance my reading options.
I did install the plugin for windows, based on read me txt. 
Than I did upload the ebook from my computer to calibre, but it was'nt convertet. 
As advised, I'll add my the lod.dat from the debug mode. 

I would be happy, if anyone could help me. Maybe I forgot to do a stepp.

Thanks!

calibre Fehlerdiagnoseprotokoll
calibre 3.0  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.12+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
calibre 3.0  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.12+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.664921466 x 127.590697674
Using calibre Qt style: True
Starting up...
Started up in 22.24 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['1b\x16m.\x88\x05\xa5\xabT\xca\xfd#\xe0A\x9e\x95%\xa3\x06\xd9\xe29\xbfT\x1b\x15\xdd\x8e\xb70\xac', 'C:\\Users\\Roban\\Downloads\\Das Wunder der Entspannungshocke_ Befreiter R\xc3\xbccken und ein gutes Bauchgef\xc3\xbchl_B01GVNZPMW.azw3']
DeDRM v6.5.3: Trying to decrypt Das Wunder der Entspannungshocke_ Befreiter RÃ¼cken und ein gutes BauchgefÃ¼hl_B01GVNZPMW.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Das Wunder der Entspannungshocke: Befreiter RÃ¼cken und ein gutes BauchgefÃ¼hl (German Edition)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Roban\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Das Wunder der Entspannungshocke: Befreiter Rücken und ein gutes Bauchgefühl (German Edition) to db in: 0.3
Added 1 books in 0.9 seconds

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then you need to add its serial number to the plugin customization.  Otherwise, install Kindle for PC version 1.17 and import the book downloaded from there.

**Comment by apprenticeharper** [comment]
I assume no more help is needed.
