### ISSUE TITLE
Multi file format

### ISSUE THREAD

**Issue by HubGid** [apprenticeharper/DeDRM_tools#305]
This Kindle ebook is an .azw file and a bunch of azw.res files. Total size about 43MB
This original (bought) ebook is downloaded with Kindle for PC.

I also have the same book in Kindle Cloudreader format.
A 776KB and 57.4MB file without an extension.

(My aim is converting to .pdf)

calibre Debug log
calibre 3.1.1 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 3)
calibre 3.1.1 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.0088593577 x 72.0567375887
Using calibre Qt style: True
Starting up...
Started up in 11.07 seconds with 0 books
DeDRM v6.5.3: Trying to decrypt B00A6S4A5W_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Me\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Me\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '278011971' and UserName '4d65'
DeDRM v6.5.3: Found 1 new key
DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 416, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B00A6S4A5W EBOK to db in: 0.1
Added 1 books in 1.0 seconds
Worker Launch took: 0.148000001907

**Comment by ElleKayEm** [comment]
As the log says, this is the KFX format which the tools can't decrypt yet.  See this MobileRead post for workarounds:  https://www.mobileread.com/forums/showthread.php?t=283371
