### ISSUE TITLE
Drm is not auto removed

### ISSUE THREAD

**Issue by leelaram123** [apprenticeharper/DeDRM_tools#307]
hi,
i am using kindle version 1.17
<img width="526" alt="screen shot 2017-07-04 at 9 17 08 am" src="https://user-images.githubusercontent.com/29880028/27814457-2d4d9048-609a-11e7-9e9a-86e72c91cc84.png">
i have installed drm removal plugin 
<img width="858" alt="screen shot 2017-07-04 at 9 17 27 am" src="https://user-images.githubusercontent.com/29880028/27814478-51d5d178-609a-11e7-9c4d-9fdcbccb31f8.png">
but when i add a .azw file to calibre it gets added but getting below error messsage
<img width="433" alt="screen shot 2017-07-04 at 9 16 17 am" src="https://user-images.githubusercontent.com/29880028/27814512-9041db0a-609a-11e7-8ef0-b5eb26285df1.png">
Please let me know if i am doing anything wrong

**Comment by ElleKayEm** [comment]
Remove the old Kindle only DeDRM plugin and install the DeDRM calibre plugin available here, current release 6.5.4.  It replaces all the old individual file type DeDRM plugins.

**Comment by leelaram123** [comment]
calibre, version 3.2.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/Users/tipirnen/Downloads/DeDRM_tools_6.5.4.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.2.1  embedded-python: True is64bit: True
Darwin-16.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.6.0', 'Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: eReader PDB 2 PML (0, 0, 5)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 461, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 60, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 192, in load
  File "site-packages/calibre/customize/zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'/Users/tipirnen/Downloads/DeDRM_tools_6.5.4.zip' is invalid. It does not contain a top-level __init__.py file

i have uninstalled it and downloaded the latest. Getting above exception.

**Comment by ElleKayEm** [comment]
Unzip that file, look in the DeDRM calibre plugin folder, and load that zip file into calibre.

**Comment by PulsarAV1** [comment]
Similar issue here:

calibre Debug log
calibre 3.2.1  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.2.1  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
Starting up...
Started up in 12.36 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x82n\x893L,^x\xcd\xdaJ]S\xa4d\x01_\xa8\xae \xac\xdf\xa9=\x90\xd1\x944\x12\xd1\xa2>', 'Z:\\Downloads\\B0036S0F26_EBOK\\B0036S0F26_EBOK.azw']
DeDRM v6.5.4: Trying to decrypt B0036S0F26_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 10
Decrypting Mobipocket 6 ebook: The Wizard of Seattle
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Mike\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Mike\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '411335349' and UserName '4d696b65'
DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds
Added The Wizard of Seattle to db in: 0.3
Added 1 books in 0.9 seconds
Worker Launch took: 0.112999916077

PulsarAV

**Comment by ElleKayEm** [comment]
@PulsarAV1
OP's issue was old plugin and then not getting the new plugin installed.

Your issue looks like it might be a KFX file, although it didn't detect it as such.  Is that book from the installation of Kindle for PC on the same PC and user as calibre?

**Comment by PulsarAV1** [comment]
Good catch!  I should have realized that the keys would be different on different PC's.  (and I call myself a cyber-security professional...  sigh...).

I installed Calibre and the DeDRM plugin on the other PC and it worked like a charm.

Thanks for your help!

PulsarAV
