### ISSUE TITLE
epub conversion issue

### ISSUE THREAD

**Issue by ppick** [apprenticeharper/DeDRM_tools#308]
I got an epub book and I want to be able to put on my kindle.  This normally works, but this time I got an error:

calibre Debug log
calibre 3.2.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.2.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.8914285714 x 92.3636363636
Using calibre Qt style: True
Starting up...
Started up in 53.81 seconds with 1108 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xf9i\x83\x82\x90N\xe0\x0f\x8f\xa2\xeb\xf0\x96 \xf8DV6\xef\xc3\t\xb8\xb7N\xc3,\xad\xae'\xd6D\x11", 'C:\\Users\\Dave\\Documents\\My Digital Editions\\Into the Water.epub']
DeDRM v6.5.4: Trying to decrypt Into the Water.epub
DeDRM v6.5.4: Verifying zip archive integrity
DeDRM v6.5.4: Into the Water.epub is a secure Adobe Adept ePub
DeDRM v6.5.4: Trying Encryption key default_key
Could not decrypt u4arho.epub. Wrong key
DeDRM v6.5.4: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v6.5.4: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 393, in ePubDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Added Into the Water to db in: 0.3
Added 1 books in 1.0 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x000002499BB5C8D0>> ignored
Worker Launch took: 0.0739998817444
Job: 1 Convert book 1 of 1 (Into the Water) finished
Convert book 1 of 1 (Into the Water)
	Conversion options changed from defaults:
	  output_profile: 'kindle_dx'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\Dave\\AppData\\Local\\Temp\\calibre_bue9xg\\wb1aca.opf'
	Resolved conversion options
	calibre version: 3.2.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000298531CD4A8>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleDXOutput object at 0x00000298531CDAC8>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Dave\\AppData\\Local\\Temp\\calibre_bue9xg\\wb1aca.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\Dave\AppData\Local\Temp\calibre_bue9xg\tpgbcx.epub
	Python function terminated unexpectedly
	  tpgbcx.epub (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 268, in convert
	calibre.ebooks.DRMError: tpgbcx.epub

Can you give any insight into what the issue may be?

**Comment by apprenticeharper** [comment]
It looks like the wrong key.

Is your ADE registered with an Adobe ID? Is it version 2.0.1? Have you changed anything recently?

**Comment by ppick** [comment]
I noticed that this may be different on my phone than on my PC.  I can open it on my phone, but not on the program installed on my PC (which the previous ones that I converted could).  So I am thinking that the phone has different keys on it somehow.

**Comment by ElleKayEm** [comment]
The plugin gets the key from Adobe Digital Editions authorized with your Adobe ID on the same machine as calibre.  If ADE can't open it, then the tools can't find the key needed to remove the DRM.  Sounds like your phone app might be linked to a different Adobe ID?

**Comment by apprenticeharper** [comment]
I hope they got their Adobe IDs sorted.
