### ISSUE TITLE
DRM cannot be removed

### ISSUE THREAD

**Issue by dwarfgiant** [apprenticeharper/DeDRM_tools#309]
I am moving to a new computer. It is not the first time I install the DeDRM tools but now I failed. I installed Calibre; then ActivePython-2.7.13.2716-win64-x64-403203.exe; then pycrypto-2.6.win-amd64-py2.7 (I have already ADE 2.0 ID activated); installed the Plug-in for calibre - exactly the way I should. Nevertheless it didn't work.
Here is the log:
calibre Debug log
calibre 3.2.1  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Obok DeDRM (6, 5, 4)
calibre 3.2.1  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.238993711 x 102.358208955
Using calibre Qt style: True
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 10.64 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['m\x8cGy\xd9<\na2[\xe7\xea7\xc2\x8a\xfan\x8c\xe4-\\\xfb\x01\x17\xe8\x0f>\xa6\xcb\xbd:\xd3', 'C:\\Users\\venci\\Documents\\My Digital Editions\\The Queens Dumbshows-2.pdf']
DeDRM v6.5.4: Trying to decrypt The Queens Dumbshows-2.pdf
DeDRM v6.5.4: The Queens Dumbshows-2.pdf is a PDF ebook
DeDRM v6.5.4: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.5.4: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 439, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 493, in PDFDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 342, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 115, in get_metadata
ValueError: Could not read info dict from PDF
Added The Queens Dumbshows-2 to db in: 0.1
Added 1 books in 1.0 seconds

I would really appreciate any help with my problem.

**Comment by ElleKayEm** [comment]
Do you still have access to the working setup with the same Adobe ID on the old machine?  If so, you could export the ADE key from the DeDRM calibre plugin on the old and import to the new.

(FYI, you don't actually need Python or PyCrypto with the calibre plugin.)

**Comment by dwarfgiant** [comment]
Thank you for the quick answer. How could I export the ADE key from the DeDRM plugin?

**Comment by dwarfgiant** [comment]
My old PC was running on Win XP (and clalibre 1.42.0). The new was is with Win 10 and calibre 3.2.1. Calibre 1.42.0 has no export/import option.

**Comment by ElleKayEm** [comment]
Hmm, no idea what option the old setup might have, but the current DeDRM plugin has a save button and an import keys button in each of the areas where you customize for different file types -- in this case, where you manage the Adobe Digital Editions keys.

I assume the book is opening in ADE 2.0.1 with your Adobe ID on the Win10 machine?

**Comment by dwarfgiant** [comment]
Yes, the book is opening in ADE 2.0.1 on the Win 10 machine. It has also been successfully DeDRM-ed by the old calibre.

**Comment by dwarfgiant** [comment]
I did what you suggested - saved/imported the old DeDRM key - and now calibre works as it should. Thank you so much!

**Comment by ElleKayEm** [comment]
Glad to help!  If you're all set, you can close this issue.
