### ISSUE TITLE
Kindle for Mac 1.20 doesn't deDRM with Calibre + plugins 

### ISSUE THREAD

**Issue by krgp21** [apprenticeharper/DeDRM_tools#310]
Kindle for Mac 1.20 doesn't deDRM with Calibre + plugins. I updated the plugins to the most recent, and the new filetypes (see screenshot) that Kindle now downloads to Mac don't deDRM any more. Not sure what they've changed. See image for how the filetypes look now. Happy to provide more info as needed. Thx.

<img width="531" alt="screen shot 2017-07-07 at 4 40 53 pm" src="https://user-images.githubusercontent.com/29989377/27978050-1a03f27a-6333-11e7-9680-2f5b3079af3a.png">

**Comment by ElleKayEm** [comment]
Yes, you've run into the KFX format.  See this post at MobileRead for workarounds:
https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by krgp21** [comment]
Thanks for the fix. I appreciate it.

**Comment by ElleKayEm** [comment]
No problem.  If you're all set, you can close the issue.
