### ISSUE TITLE
DeDRM doesn't work on Windows 7 in a Virtual Machine

### ISSUE THREAD

**Issue by hollysheep** [apprenticeharper/DeDRM_tools#313]
I'm on Ubuntu 16.04 and have installed all required software in a Virtual Machine (VirtualBox 5.0.4) on Windows 7. I can't decrypt the epub using Calibre or the Batch file for Windows. With Calibre when i open the file there is the error that the epub is encrypted. With the Batch there is only a error that decrypting failed. All software is up to date.

I could decrypt the epub on my Notebook using exactly the same software (Windows 7 and DeDRM). I didn't try decrypt with Calibre plugin on the Notebook. The Calibre plugin also doesnt work on Ubuntu.

**Comment by ElleKayEm** [comment]
For Adobe DRM you could grab the key from the working setup and import it into the other.

**Comment by hollysheep** [comment]
What key do you mean? a key imported with adobe digital? how can i do this?

**Comment by hollysheep** [comment]
ok works now.

do i need to update the key from time to time or can i leave it and it works?

**Comment by ElleKayEm** [comment]
Same key should continue to work as long as it's the same Adobe ID and you're downloading the books with ADE 2.0.1.

**Comment by hollysheep** [comment]
Hm, i've used ADE 4.5.x and the key worked, but ADE doesn't work good with wine. i'll try ADE 2.0

**Comment by ElleKayEm** [comment]
Books downloaded with ADE 3.0 and newer have the potential to have a newer DRM which cannot be removed (yet?).  See the FAQs for more info:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-registered-adobe-digital-editions-30-or-later-with-an-adobe-id-before-downloading-but-my-epub-or-pdf-still-has-drm

**Comment by apprenticeharper** [comment]
It looks like this is resolved. Closed.
