### ISSUE TITLE
DeDRM for Mac not working with Kindle for Mac 1.20.2 files

### ISSUE THREAD

**Issue by knhasan** [apprenticeharper/DeDRM_tools#314]
Getting the following error when trying to open a .azw file using the latest version of DeDRM:

There is 1 ebook to be decrypted.
Processing file: B0010SGR62_EBOK.azw
There was an error with 1 ebook:
Main:Users:knhasan:Documents:Books:Kindle:B0010SGR62_EBOK:B0010SGR62_EBOK.azw is neither a Kindle not a Mobipocket file.

The book was downloaded using Kindle 1.20.2 for Mac. The files from previous version of Kindle for Mac was working fine.

The following is the directory structure of the files downloaded:
/Users/knhasan/Documents/Books/Kindle/B0010SGR62_EBOK/
B0010SGR62_EBOK.azw
B0010SGR62_EBOK.mbpV2
B0010SGR62_EBOK.phl
CR!671QCPB6916M933YHPMY569YW3ZY.azw.res
CR!7Q1DDCGTE95BZ5XZ42QZTHSSZ409.azw.md
amzn1.drm-voucher.v1.984ce1df-16be-43f4-aeb8-352d3f12c2e9.voucher
tmp/

**Comment by ElleKayEm** [comment]
Looks like that's a KFX format.  See this thread:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by knhasan** [comment]
Thanks, changing the execution flag worked!

**Comment by ElleKayEm** [comment]
Glad to hear it!  If you're all set, go ahead and close this issue.
