### ISSUE TITLE
AZW3 will not convert

### ISSUE THREAD

**Issue by roofdeck** [apprenticeharper/DeDRM_tools#315]
I have purchased a new Amazon kindle release which will not convert to Mobi.  I have the latest Calibre installed as well as the latest dedrm plugin 6.5.4. Calibre just reports that the file is protected. Calibre will not generate a debug file either.  I managed to convert older files in my library from azw3 to mobi just to test my setup.  Works just fine.  The kindle serial number is correct in the app customization.  I have just tried to attach the book itself but this is not accepted.

**Comment by ElleKayEm** [comment]
Can't really say what might be wrong without the debug log.  Give it another try:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by roofdeck** [comment]
Thanks for the tip and herewith the debug log.
calibre Debug log


calibre 3.4  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Inept Epub DeDRM (0, 1, 7)
calibre 3.4  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Inept Epub DeDRM (0, 1, 7)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.0567375887 x 71.8867924528
Using calibre Qt style: True
Starting up...
Started up in 29.75 seconds with 1178 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xc6\x83\xe6 #\xafM\x84<\x96\x0c\xd29d`,\xd0%\xd9{\x8fo0c\xc4\r$\x82\xf0\xf7@6', 'C:\\Users\\User\\Desktop\\The Late Show (1997)\\The Late Show - Michael Connelly.azw3']
DeDRM v6.5.4: Trying to decrypt The Late Show - Michael Connelly.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Late Show
Found 12 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 12 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\User\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.4: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.3 seconds
Added 0 books in 6.8 seconds
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['y\x0e\xad\xd1\xf1\xcf\x9a\x1590\x9a/d\x18\r("\x8d\xb1Y3\x84\xcdb>r \x98Rw\xaf\xbe', 'C:\\Users\\User\\Desktop\\The Late Show (1997)\\The Late Show - Michael Connelly.azw3']
DeDRM v6.5.4: Trying to decrypt The Late Show - Michael Connelly.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Late Show
Found 12 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 12 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\User\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds
Added The Late Show to db in: 1.3
Added 1 books in 2.6 seconds
Worker Launch took: 0.233999967575
Job: 1 Convert book 1 of 1 (The Late Show) finished
Convert book 1 of 1 (The Late Show)
	Conversion options changed from defaults:
	  verbose: 2
	  cover: u'C:\\Users\\User\\AppData\\Local\\Temp\\calibre_xyjban\\djewn9.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\User\\AppData\\Local\\Temp\\calibre_xyjban\\wersbg.opf'
	  output_profile: 'kindle_dx'
	Resolved conversion options
	calibre version: 3.4.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\User\\AppData\\Local\\Temp\\calibre_xyjban\\djewn9.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x03218670>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleDXOutput object at 0x032189F0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\User\\AppData\\Local\\Temp\\calibre_xyjban\\wersbg.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\User\AppData\Local\Temp\calibre_xyjban\hx5rzo.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  The Late Show (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: The Late Show

**Comment by ElleKayEm** [comment]
Either the serial number isn't correct or the book was associated with a different Kindle than the one you have  entered into the plugin.

**Comment by roofdeck** [comment]
I feel so stupid. It is a new-ish kindle I had not yet registered on the plugin. All sorted
