### ISSUE TITLE
DeDRM plugin not working on Calibre

### ISSUE THREAD

**Issue by seotony** [apprenticeharper/DeDRM_tools#316]
I downloaded the .azw file from Amazon for my Kindle option to my PC and then added it in Calibre after installing the DeDRM plugin. I had also entered my eink Kindle serial number - though I had to shorten it from B00E 1510 1514 0FC5 to E 1510 1514 0FC5 in order to fit the right number of digits. Not sure if this has anything to do with the failure noted in the Debug log below. Any ideas how I can get this to work? 

calibre Debug log
calibre 3.4  embedded-python: True is64bit: False
Windows-10-10.0.14393-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.4  embedded-python: True is64bit: False
Windows-10-10.0.14393-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.569275362 x 100.55257732
Using calibre Qt style: True
Starting up...
Started up in 23.12 seconds with 8 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['e\xb4p\xa4b\xd1\x85y\xf1YR\xa3\xdd{\x89\x18\x8c\xf69Y\x17\x81\xc5\xe1~\xeb7\xf4\x8a\x85\xc0N', 'C:\\Users\\Tony\\Documents\\Calibre Library\\Bhagavad-gita As It Is.azw']
DeDRM v6.5.4: Trying to decrypt Bhagavad-gita As It Is.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 10
Decrypting Mobipocket 6 ebook: Bhagavad-gita As It Is
Found 6 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Tony\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Tony\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4075813477' and UserName '546f6e79'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 10
Decrypting Mobipocket 6 ebook: Bhagavad-gita As It Is
Found 4 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.6 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.6 seconds
Added Bhagavad-gita As It Is to db in: 2.7
Added 1 books in 6.8 seconds
Worker Launch took: 0.472999811172
Worker Launch took: 0.588999986649
Job: 2 Convert book 1 of 1 (Bhagavad-gita As It Is) finished
Convert book 1 of 1 (Bhagavad-gita As It Is)
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\Tony\\AppData\\Local\\Temp\\calibre_lszgdw\\wu5w3a.jpeg'
	  verbose: 2
	  pdf_sans_family: u'MS Shell Dlg 2'
	  read_metadata_from_opf: u'C:\\Users\\Tony\\AppData\\Local\\Temp\\calibre_lszgdw\\kynmuf.opf'
	Resolved conversion options
	calibre version: 3.4.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Tony\\AppData\\Local\\Temp\\calibre_lszgdw\\wu5w3a.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x02B9D1B0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x02B9D390>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier New',
	 'pdf_mono_font_size': 16,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'MS Shell Dlg 2',
	 'pdf_serif_family': u'Times New Roman',
	 'pdf_standard_font': u'serif',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Tony\\AppData\\Local\\Temp\\calibre_lszgdw\\kynmuf.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Tony\AppData\Local\Temp\calibre_lszgdw\sslkov.azw
	Python function terminated unexpectedly
	  Bhagavad-gita As It Is (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 161, in extract_content
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Bhagavad-gita As It Is

**Comment by ElleKayEm** [comment]
Leave out the spaces when entering the serial number into the plugin.

**Comment by seotony** [comment]
Thanks that worked a treat
