### ISSUE TITLE
Unable to convert AZW3 to PDF

### ISSUE THREAD

**Issue by Knowyourgame** [apprenticeharper/DeDRM_tools#317]
Any help would be greatly appreciated.
[tmpqkpodi.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1150550/tmpqkpodi.txt)

**Comment by ElleKayEm** [comment]
The DRM removal is successful.  You might have better luck with conversion using 64-bit calibre.  You could also try the KindleUnpack plugin instead of calibre's built-in conversion.

**Comment by Knowyourgame** [comment]
Thanks i'll give that a try
