### ISSUE TITLE
Epub conversion failed

### ISSUE THREAD

**Issue by feliarana** [apprenticeharper/DeDRM_tools#318]
My epub was not downloaded with the installation of ADE on the same machine and user as calibre. And the installation where it was downloaded can't be authorized with a different Adobe ID (because I don't have it).
Either way, this is my log which failed to decrypt:

calibre 3.4 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 152.4 x 102.129166667
Using calibre Qt style: True
Starting up...
Started up in 1.99 seconds with 1 books
DeDRM v6.5.5: mybook.epub
DeDRM v6.5.5: Verifying zip archive integrity
DeDRM v6.5.5: mybook.epub is a secure Adobe Adept ePub
DeDRM v6.5.5: Trying Encryption key default_key
Could not decrypt kkdl8w.epub. Wrong key
DeDRM v6.5.5: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v6.5.5: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v6.5.5: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 629, in run
  File "calibre_plugins.dedrm.__init__", line 400, in ePubDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added mybook to db in: 0.1
Added 1 books in 0.7 seconds

**Comment by ElleKayEm** [comment]
The only way I can see to decrypt this is to install calibre and the DeDRM plugin on the machine where the book was downloaded with ADE.

**Comment by feliarana** [comment]
That's a pitty. This book is a Spanish book and it's from my father's friend . I don't think she would like to install it on her pc. I guess I will have to buy it
Thanks for your quick reply!

**Comment by ElleKayEm** [comment]
These tools are intended for ebooks you yourself have purchased.  All the keys for the various types of ebooks are retrieved with info from your own accounts.

**Comment by feliarana** [comment]
Ok. I understand that this tools are intented for ebooks that I have purchased, but is it legit if the owner who bought the book decides to share that book with me, using this tools?

**Comment by ElleKayEm** [comment]
From the wink smiley, I assume you're joking.  But just in case, I'll say no, it's not legit.  Even removing DRM for your own personal use is a legal grey area in most places.

**Comment by feliarana** [comment]
Yeah of course it's a joke hehe. 
In my opinion, removing the DRM from books that you buy it's a similar case  when you buy a movie DVD and you want to have a copy for you just in case it got scratched. So it's ok if that's the limit of making copies
