### ISSUE TITLE
DeDRM does not work

### ISSUE THREAD

**Issue by Safro78** [apprenticeharper/DeDRM_tools#319]
I work with Windows 10.

This is the log-file of the trouble book, can you help?

calibre Fehlerdiagnoseprotokoll
calibre 3.4 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.4 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.110344828
Using calibre Qt style: True
Starting up...
Started up in 12.57 seconds with 6 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x8f\xdb_\x89\xba\xbcD\xfb\xd4Y\x83\xbfPJ\x9dQ\x83\xf1r\xa2x\xd6\xc9]{7[\xdc}\xfe\xc5\x07', 'G:\\ebooks\\Hans Christian Andersen Juergen Schulze\\Andersens Maerchen - Die kleine Seejungfrau Daeumelinchen Die Schneeko\\Hans Christian Andersen Juergen Schulze - Andersens Maerchen - Die kleine Seejungfrau Daeumelinchen Die Schneeko.epub']
DeDRM v6.5.4: Trying to decrypt Hans Christian Andersen Juergen Schulze - Andersens Maerchen - Die kleine Seejungfrau Daeumelinchen Die Schneeko.epub
DeDRM v6.5.4: Verifying zip archive integrity
DeDRM v6.5.4: Hans Christian Andersen Juergen Schulze - Andersens Maerchen - Die kleine Seejungfrau Daeumelinchen Die Schneeko.epub is a secure Adobe Adept ePub
DeDRM v6.5.4: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
Found 1 keys
DeDRM v6.5.4: Trying a new default key
Could not decrypt dbwtxq.epub. Wrong key
DeDRM v6.5.4: Failed to decrypt with new default key after 0.3 seconds
DeDRM v6.5.4: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 393, in ePubDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.3 seconds.
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Andersens Maerchen - Die kleine Seejungfrau Daeumelinchen Die Schneekoenigin Das haessliche junge Entlein Des Kaisers neue Kleider Das kleine Maedchen mit den Schwefelhoelzern Die Prinzessin auf der Erbse und viele mehr - Ueberarbeitete und illustriert to db in: 1.6
Added 1 books in 3.1 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x0000024B5D00F4E0>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x0000024B5D00F630>> ignored
Worker Launch took: 0.213999986649

**Comment by ElleKayEm** [comment]
Was this downloaded with ADE 2.0.1 (authorized with your Adobe ID) on the same machine and user as calibre?

**Comment by Safro78** [comment]
No, I downloaded the books on my tablet and copied them to my laptop (where I used calibre).
Download was via ciando.

**Comment by ElleKayEm** [comment]
DeDRM works by getting the key to unlock your books from ADE on the same machine and user as calibre. 
 Is the installation of Adobe Digital Editions on your laptop authorized with the same Adobe ID as the app on your tablet?  Can you open the books with ADE on your laptop?  And what version is it?  Versions of ADE more recent than 2.0.1 can handle a newer version of DRM that cannot be removed (yet).
