### ISSUE TITLE
De-drm issue similar to others mentioned before. 

### ISSUE THREAD

**Issue by alexhunter27** [apprenticeharper/DeDRM_tools#321]
De-drm is not stripping drm from a book that installs in Calibre as an AZW. Every other book wirks fine just not this one.

Here is the Dedrm log

There is 1 ebook to be decrypted.
Processing file: The Rosary Girls_ A Novel of Suspense (Byrne and Balzano Book 1).azw
shellcommand: /usr/bin/python '/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' '/Users/valuedstate/Downloads/The Rosary Girls_ A Novel of Suspense (Byrne and Balzano Book 1).azw' '/Users/valuedstate/Desktop/' > '/Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.4.
Copyright © 2008-2013 The Dark Reverser et al.
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 3
Decrypting Mobipocket 6 ebook: The Rosary Girls: A Novel of Suspense (Byrne and Balzano Book 1)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 0 keys tried.
 Traceback (most recent call last):
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 254, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 228, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 0 keys tried.
shellcommand: /usr/bin/python '/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.3
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/valuedstate/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '51aa81e39dc2' and UserName 'valuedstate'
Saved a key to /Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
 
shellcommand: /usr/bin/python '/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/KindleKey.der' '/Users/valuedstate/Downloads/The Rosary Girls_ A Novel of Suspense (Byrne and Balzano Book 1).azw' '/Users/valuedstate/Desktop/' > '/Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.4.
Copyright © 2008-2013 The Dark Reverser et al.
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 3
Decrypting Mobipocket 6 ebook: The Rosary Girls: A Novel of Suspense (Byrne and Balzano Book 1)
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 4 keys tried.
 Traceback (most recent call last):
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 254, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 228, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 4 keys tried.
There was an error with 1 ebook:
The Rosary Girls_ A Novel of Suspense (Byrne and Balzano Book 1).azw couldn't be decrypted.

There is 1 ebook to be decrypted.
Processing file: The Rosary Girls_ A Novel of Suspense (Byrne and Balzano Book 1).azw
shellcommand: /usr/bin/python '/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' '/Users/valuedstate/Downloads/The Rosary Girls_ A Novel of Suspense (Byrne and Balzano Book 1).azw' '/Users/valuedstate/Desktop/' > '/Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.4.
Copyright © 2008-2013 The Dark Reverser et al.
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 3
Decrypting Mobipocket 6 ebook: The Rosary Girls: A Novel of Suspense (Byrne and Balzano Book 1)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 0 keys tried.
 Traceback (most recent call last):
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 254, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 228, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 0 keys tried.
shellcommand: /usr/bin/python '/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.3
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/valuedstate/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '51aa81e39dc2' and UserName 'valuedstate'
Saved a key to /Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
 
shellcommand: /usr/bin/python '/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/KindleKey 2.der' '/Users/valuedstate/Downloads/The Rosary Girls_ A Novel of Suspense (Byrne and Balzano Book 1).azw' '/Users/valuedstate/Desktop/' > '/Users/valuedstate/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.4.
Copyright © 2008-2013 The Dark Reverser et al.
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 3
Decrypting Mobipocket 6 ebook: The Rosary Girls: A Novel of Suspense (Byrne and Balzano Book 1)
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 4 keys tried.
 Traceback (most recent call last):
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 254, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 228, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/private/var/folders/34/p4nl4ws12m5b79b37tdpgpch0000gn/T/AppTranslocation/9E646FD3-6023-4187-B0C4-CF2CFEF5F7CF/d/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 4 keys tried.
There was an error with 1 ebook:
The Rosary Girls_ A Novel of Suspense (Byrne and Balzano Book 1).azw couldn't be decrypted.

Any Help is apprecited.

**Comment by ElleKayEm** [comment]
Was that book from or for an E-ink Kindle (not a Fire)?  If so, you need to enter the serial number into the tool's configuration.  If it's from or for a Fire, then download it with Kindle for Mac using method 1 or 2 from the following post:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by alexhunter27** [comment]
the original download was to the Kindle for Mac it was a KFX file format.
I then downloaded it Direct from Amazon and it gave me an AZW file format

**Comment by ElleKayEm** [comment]
When you download a book from the website, it will ask what device it's for.  If that's an E-ink Kindle, then you need to enter its serial number before the tools can remove the book's DRM.  If it's a Fire, then you'll need to download it with Kindle for Mac instead.  Method 1 or 2 at the link will allow you to avoid KFX files.

**Comment by alexhunter27** [comment]
method 1 worked a treat.

thanks again
