### ISSUE TITLE
Kindle AZW ebook (DeDRM 6.5.4 + Calibre 3.4.0 + Kindle PC 1.17.1 + Win10)

### ISSUE THREAD

**Issue by etshy** [apprenticeharper/DeDRM_tools#322]
Hi o/

Saw the same issue several time but the answers I saw ddidn't helped me.

I bought an ebook an amazon.co.jp, downloaded it on Kindle for PC 1.17.1 and imported it on calibre with DeDRM installed.
I didn't set up any key in the plugin preferences, as I have no key to enter.
The kindle app and calibre are on the same PC and Windows user.

After the importation, I got this output on the console

https://pastebin.com/i3MBTVaS

Thanks in advance

**Comment by etshy** [comment]
Okay, I tried to use Calibre 64bits and It worked.
Dunno why exactly, but It worked now.

**Comment by ElleKayEm** [comment]
Oh good!  I was going to suggest reinstalling, but not necessary now.  Sounds like it might have been a memory issue due to a large book if switching to 64-bit calibre solved it.
