### ISSUE TITLE
DeDRM does not remove ProtectedPDF DRM

### ISSUE THREAD

**Issue by fireundubh** [apprenticeharper/DeDRM_tools#323]
[ProtectedPDF](https://www.componentsource.com/product/protectedpdf/about) (developed by Vitrium) uses 128-bit encryption and requires the user to log in from a page in the PDF to unlock the content. ProtectedPDF also sends analytics data to a remote server. DeDRM fails when trying to remove this DRM. ([Vitrium Security Data Sheets](http://www.vitrium.com/category/data-sheets/))

**Comment by apprenticeharper** [comment]
DeDRM doesn't work with that DRM system. I don't know whether anyone has tried to reverse engineer it yet.

**Comment by yulivuviki** [comment]
try to use "A-PDF Password Security" or similar free tool .
