### ISSUE TITLE
Load into Calibre error

### ISSUE THREAD

**Issue by jrleighton** [apprenticeharper/DeDRM_tools#325]
On loading the plugin file into the most recent Calibre on the most recent updated Windows 10, the following error happens: 

calibre, version 3.5.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'E:\\OneDrive\\Software\\Office\\DeDRM_calibre_plugin\\DeDRM_plugin.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.5  embedded-python: True is64bit: False
Windows-10-10.0.14393-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 461, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 60, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 192, in load
  File "site-packages\calibre\customize\zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'E:\\OneDrive\\Software\\Office\\DeDRM_calibre_plugin\\DeDRM_plugin.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
That error usually appears when people try to put the wrong zip into calibre (either the whole archive or one of the zip files inside the actual plugin.)  It looks like you've got the right one though.  Try downloading a fresh copy.

**Comment by sed5354** [comment]
same error shown as above when I try to add to Calibre.  Tried several times and copies.

**Comment by apprenticeharper** [comment]
Download from here. Unzip on your local hard drive. Install the plugin. If you still have problems, give more details, such as the actual error message.

jrleighton: Try from a local copy, not on OneDrive.
