### ISSUE TITLE
Some azw's/ mobi's OK, some not so OK

### ISSUE THREAD

**Issue by John-Wheater** [apprenticeharper/DeDRM_tools#328]
I am in the process of moving to Kobo from Kindle, not liking the current krop of kindles.

I've installed the Calibre plugin 6.5.4, and all is well with many files.  But one mobi is readable but defective.  I cannot attach it here, 'we don't support...', but could send it by email I guess.

It is a big book on programming Perl, and the text gets shifted over to the right more & more as you move along the book. It works OK on my 'Kindle Keyboard', though even in its native form it is defective, having no Table of Contents.

Hoping you might find this interesting...

**Comment by ElleKayEm** [comment]
Sounds like it might just be poor formatting to begin with and not necessarily due to anything during DRM removal.  You could try asking about it over at the MobileRead forums.  They don't allow detailed discussion of DRM removal there, but they might know how to clean up your now DRM-free book.
