### ISSUE TITLE
Caliber doesn't list plug-in

### ISSUE THREAD

**Issue by RobinPaulWilliams** [apprenticeharper/DeDRM_tools#329]
I'm wanting to remove DRM from my ebooks in order to view them on different devices (principally kindle to Kobo). I've downloaded caliber, deDRM Tools, python, PyroCrypt and tried to follow Readme instructions.
I have renamed the deDRM Tools download and think I have unzipped it successfully (?). When I try to add the deDRM plugin to Caliber, it does not appear on the list of available plugins. Can anybody explain possible reasons why and what I need to do?

**Comment by ElleKayEm** [comment]
DeDRM is not in calibre's "add plugins" area.  Go to Preferences, Plugins, and click the "load plugin from file" button.  Navigate to the DeDRM_calibre_plugin folder and select DeDRM_plugin.zip.  Click ok/apply out of the dialog boxes and then restart calibre.  (When using the calibre plugin, you don't need to install Python or PyCrypto.)

**Comment by RobinPaulWilliams** [comment]
Thankyou very much- Ive found the file in Caliber and installed it. Happy
programming!...

:-)

Il 01 Ago 2017 7:08 PM, "ElleKayEm" <notifications@github.com> ha scritto:

**Comment by ElleKayEm** [comment]
If you don't have any other questions, you can close this issue.
