### ISSUE TITLE
Failed to decrypt file

### ISSUE THREAD

**Issue by droidzone** [apprenticeharper/DeDRM_tools#33]
Debug messages:

	Job: 10 Prepare files for transfer from device started
	DeviceJob: 10 Prepare files for transfer from device done, calling callback
	DeviceJob: 10 Prepare files for transfer from device callback returned
	Job: 10 Prepare files for transfer from device finished
	No details available.
	DeDRM v6.3.3: Trying to decrypt Half Girlfriend_B013VO02LS.azw3
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.41.
	Copyright Â© 2008-2012 The Dark Reverser et al.
	MOBI header version 8, header length 264
	Extra Data Flags: 3
	Decrypting Kindle Format 8 ebook: Half Girlfriend
	Found 0 keys to try after 0.5 seconds
	Crypto Type is: 2
	DeDRM v6.3.3: Failed to decrypt with error: No key found in 0 keys tried.
	DeDRM v6.3.3: Looking for new default Kindle Key after 0.5 seconds
	searching for kinfoFiles in C:\Users\Joel\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\Joel\AppData\Local\Amazon\Kindle\storage
	\.kinf2011
	Decrypted key file using IDString '1583170637' and UserName '4a6f656c'
	DeDRM v6.3.3: Found 1 new key
	MobiDeDrm v0.41.
	Copyright Â© 2008-2012 The Dark Reverser et al.
	MOBI header version 8, header length 264
	Extra Data Flags: 3
	Decrypting Kindle Format 8 ebook: Half Girlfriend
	Found 4 keys to try after 0.9 seconds
	Crypto Type is: 2
	DeDRM v6.3.3: Ultimately failed to decrypt after 0.9 seconds.
	Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugi
	ns
	  File "calibre_plugins.dedrm.__init__", line 589, in run
	  File "calibre_plugins.dedrm.__init__", line 539, in KindleMobiDecrypt
	DeDRMError: DeDRM v6.3.3: Ultimately failed to decrypt after 0.9 seconds
	Added Half Girlfriend to db in: 3.3
	Added 1 books in 7.8 seconds
	DeviceJob: set_books_in_library: books to process= 143
	DeviceJob: set_books_in_library finished: time= 0.0539999008179

Used both 6.3.3 and latest github master.
Anything else that I can check?

**Comment by ElleKayEm** [comment]
Encryption for Kindle books is device specific.  If the book is from an E-ink Kindle, than you need to enter its serial number into the configuration settings.  Otherwise, download it through Kindle for PC, and import that copy into calibre.
