### ISSUE TITLE
Decryption error when using Obok

### ISSUE THREAD

**Issue by GalahadThreepwood** [apprenticeharper/DeDRM_tools#330]
Only 4 of the ~20 books I've bought from Kobo have successfully been imported into Calibre with Obok. The rest of the books return with a "decryption error". 
I'm using the latest versions of Calibre, Obok and Kobo Desktop.

Debug log for one of the books that failed to import:

calibre Debug log
calibre 3.5  embedded-python: True is64bit: False
Windows-10-10.0.14393-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Obok DeDRM (6, 5, 4)
calibre 3.5  embedded-python: True is64bit: False
Windows-10-10.0.14393-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 8.87 seconds with 5 books
Running Obok DeDRM v6.5.4
DEBUG:   11.8 didn't find device
Obok v3.2.4
Copyright © 2012-2016 Physisticated et al.
c:\users\gebrui~1\appdata\local\temp\tmpdlirov
DEBUG:   11.8 got kobodir C:\Users\Gebruiker\AppData\Local\Kobo\Kobo Desktop Edition
Found 12 possible keys to try.
DEBUG:   20.8 BookListTableWidget:get_books - book_num: 4
DEBUG:   20.8 BookListTableWidget:get_books - book: East of Eden
DEBUG:   20.8 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v6.5.4 - Decrypting East of Eden
Trying key:  6c3e4cf2bcbcfebc71ef8989dd78a7c2
Decryption failed, trying next key.
Trying key:  7378d4dd7cc82c6c7bf0a47c87efafc1
Decryption failed, trying next key.
Trying key:  6f8c7b279ea2dd4e254f8a230b124d3e
Decryption failed, trying next key.
Trying key:  66fd27eb504c5bb3a5dd48f2f694081c
Decryption failed, trying next key.
Trying key:  16d46619256e3275b74af75da4aaf692
Decryption failed, trying next key.
Trying key:  ccb62a15a32f2f09d2c3f27051633218
Decryption failed, trying next key.
Trying key:  bc345e0a32b7490fec140f0665f730be
Decryption failed, trying next key.
Trying key:  7aae3c2ea88945964bd555f7428d4382
Decryption failed, trying next key.
Trying key:  e4a078703ee86d46c9b4297711320e02
Decryption failed, trying next key.
Trying key:  6ad2b554c198a83755689fd9e317835e
Decryption failed, trying next key.
Trying key:  0a97c761638e3573266de76a1815aabf
Decryption failed, trying next key.
Trying key:  e0345f55f0436372c19ff19641df0e1d
Decryption failed, trying next key.
Obok DeDRM v6.5.4 - Couldn't decrypt East of Eden
DEBUG:   21.2 DecryptAddProgressDialog::do_book_action - book decryption failed: 'East of Eden'
Obok DeDRM v6.5.4 - wrapping up results.

Any idea what causes this error, and how it can be fixed? I can't seem to find any differences between the files that work and the ones that don't.

**Comment by GalahadThreepwood** [comment]
I seem to have resolved the issue by uninstalling and reinstalling the Kobo Desktop app.

**Comment by ElleKayEm** [comment]
Thanks for letting us know how you resolved it.  Doing that probably redownloaded all your books and their compatible key(s).
