### ISSUE TITLE
6.5.4 or DeDRM_plugin_modified?

### ISSUE THREAD

**Issue by Ferante1** [apprenticeharper/DeDRM_tools#331]
I currently have 6.5.3. Had a problem with AZW4, installed KindleUnpack, learned that I have to install DeDRM_plugin_modified from here:
http://www.mediafire.com/file/6jozp2d6si724mp/DeDRM_plugin_modified.zip

But shouldn't I simply upgrade to 6.5.4 instead? Will it work on the AZW4?
Thanks!!!

**Comment by Ferante1** [comment]
I figured 6.5.4 _ KindleUnpack is enough. Thanks!

**Comment by ElleKayEm** [comment]
I would definitely stick with downloading the latest release of DeDRM from here.  This is the "official" supported and maintained source for these tools.  It works fine with AZW4 books that you own.

**Comment by Ferante1** [comment]
Thank you Elle!!!
