### ISSUE TITLE
[OBOK] DRM not recognized on certain books

### ISSUE THREAD

**Issue by FrankDaegas** [apprenticeharper/DeDRM_tools#333]
OBOK tools (calibre plugin, obok.py script) are not recognizing Kobo DRM (presumably social DRM) on some of my kepub books in the %APPDATA%\Local\Kobo\Kobo Desktop Edition\kepub directory. Only the HTML files in these books are encrypted (in each individual HTML file, all possible 0-255 BYTE values occur almost equally as many times), and no header/footer byte pattern is recognizable. DeDRM of 13xforever recognized the Kobo DRM, but cannot find a decryption key. Kobo.sqlite content_keys is empty. Kobo.sqlite content lists the majority of book-contents as unencrypted (isencrypted is false), but has a single entry for each book that is listed as encrypted (but content-type is the same for both unencrypted and encrypted entries). Changing the isencrypted value does not make a difference for Kobo Desktop (so it looks like it is ignoring the isencrypted flag).

**Comment by ElleKayEm** [comment]
Have you tried uninstalling and reinstalling Kobo Desktop?  This will give you fresh copies of all your books.  And make sure you have the latest Obok plugin (currently 6.5.4).

**Comment by FrankDaegas** [comment]
I've done a complete clean install of the OS, and I am using the latest Obok plugin. The debug output of Calibri shows that Obok is decrypting the book successfully (but it really fails). I've used different PC's, same results. Notice that the HTML files (and as it turns out the JPG files also), are encrypted differently based upon the account of the downloader.

**Comment by ElleKayEm** [comment]
Sounds like Apprentice Harper will have to take a look.  At least with Kobo books, you still have the option to download them from the website and use DeDRM instead.

**Comment by FrankDaegas** [comment]
I wish that were the case, but this option isn't available for those books for me. So I can't use my heavily modified SumatraPDF for reading them on my Windows tablet. Worse is that this new schema of theirs breaks their own search in the Kobo Desktop.

**Comment by ElleKayEm** [comment]
Ah, are they emagazines or something?  Everything in my library is available for download as regular epub or pdf, but they have said they will stop providing downloads of PDFs after Nov. 1.

**Comment by apprenticeharper** [comment]
Post an import log.
