### ISSUE TITLE
DeDRM No longer working for me

### ISSUE THREAD

**Issue by poleta1955** [apprenticeharper/DeDRM_tools#335]
I am using Windows 10 and the latest versions of DeDRM, Calibre, but the older 1.17 version if K4PC. I've tried 3 different books so far, all downloaded from my Amazon account. After reading up on this, I have run Calibre in  debug mode getting:

**calibre Debug log
calibre 3.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
Starting up...
Started up in 6.42 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xa5\x95\xddO\xbb\x04\xbb\xec\xd5\\\x08 \xe1R\x80\xd5\xe6}\x84'L\xdf\xb0\x95\x08\x95\x99j\xa8{48", 'L:\\Convert\\Funeral Owl (A Philip Dryden Mystery).azw3']
DeDRM v6.5.4: Trying to decrypt Funeral Owl (A Philip Dryden Mystery).azw3
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Funeral Owl (A Philip Dryden Mystery)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Pete\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Pete\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3375879344' and UserName '50657465'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Funeral Owl (A Philip Dryden Mystery)
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.3 seconds
Added Funeral Owl (A Philip Dryden Mystery) to db in: 2.0
Added 1 books in 3.3 seconds**

I have tried uninstalling K4PC and Calibre, then deleting any files associated with them, and deregistering K4PC. Then I re-installed K4PC (checked updates are off), reregistered K4PC, re-downloaded the book from my account. I then installed the latest versions of Calibre and then added the latest DeDRM plugin. Same error again. I've been through this process several times. Any ideas?

**Comment by ElleKayEm** [comment]
It looks like that book was downloaded from the website for transfer via USB, not with Kindle for PC.  Either import the book from K4PC or enter the serial number of your Eink Kindle (won't work with a Fire) into the plugin customization.

**Comment by poleta1955** [comment]
Well spotted! Thanks for your help. All working fine now.
