### ISSUE TITLE
Kindle in motion

### ISSUE THREAD

**Issue by n00b12345** [apprenticeharper/DeDRM_tools#336]
There's a new Kindle format which shows videos and all. It's called Kindle in motion. I'm guessing this DRM is uncrackable. Am I right?

**Comment by ElleKayEm** [comment]
I believe these are in the KFX format, but they're only available on devices where even regular Kindle books can't be DeDRMed:  Fires and the apps for iOS and Android.  If you download it to Kindle for PC/Mac 1.17 or for an E-ink Kindle, you'll get a version without the extra features which these tools should handle.

**Comment by n00b12345** [comment]
Ah. Thanks for the clarification.
