### ISSUE TITLE
AndroidKindle:  'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Sesselmann** [apprenticeharper/DeDRM_tools#34]
Hi,
I'm experiencing problems dedrm'ing android kindle app files (System information below):
I've successfully installed the adb and I'm backing up the kindle app with the command
"adb backup com.amazon.kindle -f D:\backup.ab" (exporting without setting a specific backup
path will otherwise crash the adb.exe).
However once I've select the ab-file in Calibre 2.35.0/DeDRM 6.3.3 I get the following error
(I don't set up any encryption password for the ab file on my LG G2 phone, after the backup
command promt appears on the phone):

calibre, version 2.35.0
ERROR: Unhandled exception: <b>AttributeError</b>:'NoneType' object has no attribute 'encode'

calibre 2.35  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && Kindle and Mobipocket DeDRM && Inept Epub DeDRM && eReader PDB 2 PML && XRay Generator && KindleUnpack - The Plugin && Ignoble Epub DeDRM && Inept PDF DeDRM
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 934, in get_android_file
  File "calibre_plugins.dedrm.androidkindlekey", line 292, in get_serials
  File "calibre_plugins.dedrm.androidkindlekey", line 224, in get_serials2
<b>AttributeError: 'NoneType' object has no attribute 'encode'<\b>

I've also checked the standalone android decryption tool, which results in the same error.
However I didn't try the "Other_Tools\Kindle_for_Android_Patches", because the version
numbers for the kindle android apps do not match mine (4.16.0.75. I don't know if this is
version number is specific to an app that runs in german).

Thank you for any help!

**Comment by ElleKayEm** [comment]
Probably not related to this problem at all...but you can remove all the individual file type DeDRM plugins (Kindle and Mobipocket DeDRM, Inept Epub DeDRM, Ignoble Epub DeDRM, and Inept PDF DeDRM).

**Comment by apprenticeharper** [comment]
I think this has been fixed by a recent commit, and will be in the next release.

**Comment by Sesselmann** [comment]
Thank you! That's good to know.
