### ISSUE TITLE
decrypt failed

### ISSUE THREAD

**Issue by Connor1745** [apprenticeharper/DeDRM_tools#340]
Decrypt fails loading new book into Calibre.
The only thing that has changed since I last did this (3 days ago) is that Calibre was updated to V3.6.

Mac book pro
os x Sierra 10.12.6
Calibre 3.6
DeDRM v6.5.4
Kindle 1.12.4 (41014)

Debug log
calibre 3.6  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.6  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: Truecalibre
Starting up...
Started up in 2.02 seconds with 1237 books
DeDRM v6.5.4: Trying to decrypt B003DYGNQA_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: title removed
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/??????/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Found k4Mac kinf2011 file: /Users/??????/Library/Application Support/Kindle/storage/.kinf2011
Couldn't decrypt file.
Couldn't decrypt file.
DeDRM v6.5.4: Ultimately failed to decrypt after 3.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 3.3 seconds
Added The Angel of Darkness (Dr. Lazlo Kreizler Book 2) to db in: 0.0

**Comment by ElleKayEm** [comment]
Kindle for Mac where you downloaded this book is located on the same machine and user as calibre?

**Comment by Connor1745** [comment]
Yes, the same machine and another thing that I forgot is that the kindle app asked me to sign in with email address and password when I started the app even though I had never signed out.

**Comment by Connor1745** [comment]
Closing was accidental - if I have to reopen i will.

**Comment by apprenticeharper** [comment]
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

**Comment by ElleKayEm** [comment]
I believe this can be closed.  Issue was resolved in #341.
