### ISSUE TITLE
decrypt failed

### ISSUE THREAD

**Issue by Connor1745** [apprenticeharper/DeDRM_tools#341]
reopen of accidentally closed issue.
#340 
Decrypt fails loading new book into Calibre.
The only thing that has changed since I last did this (3 days ago) is that Calibre was updated to V3.6.

Mac book pro
os x Sierra 10.12.6
Calibre 3.6
DeDRM v6.5.4
Kindle 1.12.4 (41014)

Debug log
calibre 3.6 embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.162/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.6 embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.162/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: Truecalibre
Starting up...
Started up in 2.02 seconds with 1237 books
DeDRM v6.5.4: Trying to decrypt B003DYGNQA_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: title removed
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/??????/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Found k4Mac kinf2011 file: /Users/??????/Library/Application Support/Kindle/storage/.kinf2011
Couldn't decrypt file.
Couldn't decrypt file.
DeDRM v6.5.4: Ultimately failed to decrypt after 3.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
File "calibre_plugins.dedrm.init", line 611, in run
File "calibre_plugins.dedrm.init", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 3.3 seconds
Added The Angel of Darkness (Dr. Lazlo Kreizler Book 2) to db in: 0.0

**Comment by ElleKayEm** [comment]
The fact that Kindle for Mac asked you to sign in again means it is acting like a new installation and has a new key.  Was this book downloaded after the new sign in?  If not, try downloading a fresh copy of the book.  If so, you might need to completely uninstall and reinstall Kindle for Mac.  Take a look at [this section](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book) of the FAQs.  If all else looks okay, then follow the instructions there for reinstalling.

**Comment by Connor1745** [comment]
I followed the FAQ and removed everything and reinstalled V1,17,1 downloaded a new book and have the same problem, here is the log:

calibre Debug log
calibre 3.6  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.6  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: True
Starting up...
Started up in 1.94 seconds with 1237 books
DeDRM v6.5.4: Trying to decrypt B00FN0YJ6S_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: title removed
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/??????/Library/Application Support/Kindle/storage/.kinf2011
Couldn't decrypt file.
DeDRM v6.5.4: Ultimately failed to decrypt after 1.7 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 1.7 seconds
Added title removed to db in: 0.0
Added 1 books in 2.3 seconds
Worker Launch took: 0.0865740776062

**Comment by pdurrant** [comment]
"Found k4Mac kinf2011 file: /Users/??????/Library/Application Support/Kindle/storage/.kinf2011
Couldn't decrypt file."

How strange. Unregister Kindle for Mac, Quit Kindle for Mac, delete Users/??????/Library/Application Support/Kindle/, start Kindle for Mac, re-register it, re-download and try again.

Does your user name have any non-ASCII characters in it? I think that there was a fix for Windows usernames, but I don't know if it affected Macs. (Or whether Macs has that problem at all.)

**Comment by ElleKayEm** [comment]
I wonder if it's the same as whatever was going on in issue #255.

**Comment by Connor1745** [comment]
No strange characters in the user name all lowercase alpha. I did notice that even after removing all of the files recommended in the FAQ there were still some Kindle related files left (~/Library/Containers/com.amazon.Kindle/Data/Library/Preferences/kindle.plist)and a folder ~/Library/Containers/com.amazon.Kindle/Data/Library/Saved Application State/com.amazon.Kindle.savedState, should they go also?  #255 does look very much like my problem. Ill try again tomorrow.

**Comment by pdurrant** [comment]
By the sound of #255 Apprentice Harper might be interested in your problem. But it also sounds like it might be a problem of left-over 'stuff'.

I notice that both you and in #255 the App store version of Kindle for Mac had been used at some point. Perhaps a really thorough clean and restart and reinstall will do the trick.

You could check it's a similar problem by setting up a test user account.

**Comment by Connor1745** [comment]
I went through the process of unregister - remove - reinstall again but this time I was sure to remove any mention of kindle under ~/Library.  As I mentioned above after removing everything mentioned in the FAQ there were still some Kindle related files left, probably because I had indeed had the app store version installed. The problem is now fixed and I thank you all for your help.

**Comment by ElleKayEm** [comment]
Thanks for letting us know.  If you're all set, you can close the issue.

**Comment by ElleKayEm** [comment]
I suspect there's some file sometmes left behind by the Mac store Kindle app that's not removed with the folders mentioned for deletion in the FAQs.
