### ISSUE TITLE
can't install plug in It does not contain a top-level init.py file

### ISSUE THREAD

**Issue by gezn** [apprenticeharper/DeDRM_tools#344]
error when trying to install it from file 
calibre, version 1.25.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/home/gezn/Downloads/DeDRM_tools_6.5.4.zip' is invalid. It does not contain a top-level __init__.py file

calibre 1.25  isfrozen: False is64bit: True
Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty Linux ('64bit', 'ELF')
('Linux', '3.13.0-43-generic', '#72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014')
Python 2.7.6
Linux: ('Ubuntu', '14.04', 'trusty')
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 308, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 375, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 53, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 188, in load
    plugin_name = self._locate_code(zf, path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 282, in _locate_code
    % path_to_zip_file)
InvalidPlugin: The plugin in u'/home/gezn/Downloads/DeDRM_tools_6.5.4.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're trying to install the whole archive, instead of the plugin.  Unzip that file, look in the DeDRM_calibre_plugin folder, and load DeDRM_plugin.zip.

**Comment by gezn** [comment]
thanks, now it's working as espected

**Comment by ElleKayEm** [comment]
If you're all set, close the issue.
