### ISSUE TITLE
Mac OS X Sierra (10.12.6) - The application “DeDRM.app” can’t be opened.

### ISSUE THREAD

**Issue by chrubble** [apprenticeharper/DeDRM_tools#346]
I have previously used DeDRM on my Macbook but, since last successful use, I have updated my OS and also installed the latest version of the DeDRM app and plugin for Calibre. I now get the message "The application “DeDRM.app” can’t be opened" when attempting to open the app and the Calibre plugin appears not to be functioning.

**Comment by ElleKayEm** [comment]
See the FAQs about the Mac app:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#the-macintosh-application

What do you mean about the calibre plugin not working?  Not loading at all?  Not removing DRM?  Post a log if possible, and give us more details.
