### ISSUE TITLE
Failed removal from ADE epub 

### ISSUE THREAD

**Issue by Gaber1992** [apprenticeharper/DeDRM_tools#349]
I tried to remove the DRM from an epub protected with ADE drm many times, and failed.
Here is the debug log from Calibre:
calibre Log di debug
calibre 2.82 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 3, 4)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9842323651 x 71.9822878229
Starting up...
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
Started up in 7.13 seconds with 210 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\x8c\xb1;\xf4Y\x99\xdf\x06)\xb6N\x90\xcf\xc7\x8a\xc7\x82f\xc3'\xe6\x9a\xf1\x11KKw`\xe3\xa6Y%", 'C:\\Users\\Gaber\\Documents\\My Digital Editions\\V. Sackville-West a critical biography.epub']
DeDRM v6.3.4: Trying to decrypt V. Sackville-West a critical biography.epub
DeDRM v6.3.4: Verifying zip archive integrity
DeDRM v6.3.4: V. Sackville-West a critical biography.epub is a secure Adobe Adept ePub
DeDRM v6.3.4: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.3.4: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 318, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.3.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 601, in run
  File "calibre_plugins.dedrm.__init__", line 372, in ePubDecrypt
DeDRMError: DeDRM v6.3.4: Ultimately failed to decrypt after 0.2 seconds.
Added V. Sackville-West: a critical biography to db in: 0.2
Added 1 books in 1.0 seconds

First I used DeDrm 6.5.4. As I saw it was not working, I tried with 6.3.4. Nothing changed.
Can you help me?

**Comment by ElleKayEm** [comment]
Are you using ADE 2.0.1?  Is it authorized with your Adobe ID?  Can you open your book in ADE 2.0.1?

**Comment by Gaber1992** [comment]
Yes, yes, and yes.

**Comment by ElleKayEm** [comment]
Others have reported success with completely uninstalling ADE including related folders and registry entries.  Then re-installing and re-authorizing.

Stick with ADE 2.0.1.  But it won't hurt to update calibre and the DeDRM plugin.  Probably not an issue here, but needed for other file types.

**Comment by Gaber1992** [comment]
I will do that and get back to you asap.

**Comment by ElleKayEm** [comment]
See issue #348 for more about what to remove.
