### ISSUE TITLE
Failed to deDRM Kindle book

### ISSUE THREAD

**Issue by phil-xor31** [apprenticeharper/DeDRM_tools#350]
Imported from Kindle eInk device
Here is the calibre log:
Starting up...
Storage number map:
{(7L, 0L): [(4L, 'C')], (7L, 1L): [(1L, 'D')], (7L, 3L): [(1L, 'E')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\B02317012324044D&0: StorageDeviceNumber(type=7L, number=3L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=5)
{u'drive_letters': ['E'],
 u'pnp_id_map': {'E': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#b02317012324044d&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'E': (3L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: E:\ documents
DEBUG:    0.0 USBMS: scan from root False E:\documents
DEBUG:    0.0 USBMS: count found in cache: 2, count of files in metadata: 2, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 2
DeviceJob: set_books_in_library finished: time= 0.0019998550415
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Job: 1 Get device information finished
No details available.
Job: 2 Set library information finished
No details available.
Started up in 11.85 seconds with 5 books
Job: 4 Prepare files for transfer from device started
DeviceJob: 4 Prepare files for transfer from device done, calling callback
DeviceJob: 4 Prepare files for transfer from device callback returned
Job: 4 Prepare files for transfer from device finished
No details available.
DeDRM v6.5.4: Trying to decrypt Patriots Surviving the Coming Co-asin_B003ODHO8G-type_EBOK-v_0.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 248
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Patriots: Surviving the Coming Collapse
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Phillip\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Phillip\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2889654207' and UserName '5068696c6c6970'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 248
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Patriots: Surviving the Coming Collapse
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds
Added Patriots: Surviving the Coming Collapse to db in: 2.1
Added 1 books in 2.8 seconds
DeviceJob: set_books_in_library: books to process= 2
DeviceJob: set_books_in_library finished: time= 0.00500011444092

**Comment by ElleKayEm** [comment]
Looks like you don't have the correct serial number in the plugin.

**Comment by phil-xor31** [comment]
I saw the note about entering the device serial number, but I could not find the configuration option of where to enter it in Calibre. How do I do this. Thanks!

**Comment by ElleKayEm** [comment]
Preferences > Plugins.  Highlight the DeDRM plugin under File Type Plugins.  Click the Customize Plugin button.  Then E-ink Kindle button.

**Comment by phil-xor31** [comment]
Ok, I did a more specific google search and found where to enter the serial number (Preferences -> Advanced -> Plugins -> File type plugins and double clicking on the entry for DeDRM. ). Now it works!
