### ISSUE TITLE
AZW3 conversion problem

### ISSUE THREAD

**Issue by PaoGi** [apprenticeharper/DeDRM_tools#351]
Hi everybody, 

I have a problem in converting a book with DRM (DeDRM_tools_6.5.4) and Calibre (calibre-64bit-3.7.0). 
I tryed also the KindleUnpack plugin as I saw from other posts but It didn't work. 

Here below the log (hoping to have follow correctly the instruction to get the logs). 

Thanks a lot for your help. 

calibre Log di debug
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (6, 5, 4) && KindleUnpack - The Plugin (0, 81, 5)
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (6, 5, 4) && KindleUnpack - The Plugin (0, 81, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
Starting up...
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
Started up in 42.91 seconds with 94 books
DeDRM v6.5.4: Trying to decrypt Confessioni di un ciclista mascherato (Italian Edition).azw3
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Confessioni di un ciclista mascherato (Italian Edition)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\paolo\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds
Added Confessioni di un ciclista mascherato (Italian Edition) to db in: 1.8
Added 1 books in 2.2 seconds
Worker Launch took: 0.15499997139

**Comment by ElleKayEm** [comment]
If that's from or for an E-ink Kindle (not a Fire), then you need to enter its serial number into the plugin customization.  Otherwise, install Kindle for PC 1.17 (see the FAQs) and import a copy from there.

BTW, KindleUnpack only works on DRM-free books.  Also, you put AZW4 in the issue title, but the book in your log is an AZW3 (KF8) file.  KindleUnpack can be used to "unpack" an epub from azw3 or a pdf from an azw4, but only after any DRM is removed.

**Comment by PaoGi** [comment]
@ElleKayEm thanks a lot! I follow your first advice  "enter its serial number into the plugin customization" and now it works perfectly.

Sorry for the wrong title (I've just corrected it) and thanks for the explanation about KindleUnpack plugin.
