### ISSUE TITLE
lost the picture in EBook .

### ISSUE THREAD

**Issue by TaogenJia** [apprenticeharper/DeDRM_tools#353]
using DeDRM_calibre_plugin_6.5.4  DeDRM .azw3 is successful , but I lost the picture in EBook .

**Comment by apprenticeharper** [comment]
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#my-kindle-book-has-imported-and-the-drm-has-been-removed-but-all-the-pictures-are-gone
