### ISSUE TITLE
Fail to DeDRM this AZW ebook

### ISSUE THREAD

**Issue by twwwy** [apprenticeharper/DeDRM_tools#355]
it is a book I downloaded via PC version Kindle (1.17). The other book I downloaded at the same time was successfully deDRMed. But this one failed. I tried the troubleshooting instruction, and reinstall the kindle app, but the error still occured.

[The Fall of Ottomans.zip](https://github.com/apprenticeharper/DeDRM_tools/files/1273111/The.Fall.of.Ottomans.zip)

Below is the log:

There is 1 ebook to be decrypted.
Processing file: B00PWX7S96_EBOK.azw
shellcommand: /usr/bin/python '/private/var/folders/hm/l_hhry153sz6rj8fjgw5xsvc0000gn/T/AppTranslocation/FDF9C4F3-CE48-4577-8400-B261E356EDEC/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' '/Users/twwwy/Documents/My Kindle Content/B00PWX7S96_EBOK.azw' '/Users/twwwy/Desktop/' > '/Users/twwwy/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.4.
Copyright © 2008-2013 The Dark Reverser et al.
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Fall of the Ottomans: The Great War in the Middle East
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 0 keys tried.
 Traceback (most recent call last):
  File "/private/var/folders/hm/l_hhry153sz6rj8fjgw5xsvc0000gn/T/AppTranslocation/FDF9C4F3-CE48-4577-8400-B261E356EDEC/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 254, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/private/var/folders/hm/l_hhry153sz6rj8fjgw5xsvc0000gn/T/AppTranslocation/FDF9C4F3-CE48-4577-8400-B261E356EDEC/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 228, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/private/var/folders/hm/l_hhry153sz6rj8fjgw5xsvc0000gn/T/AppTranslocation/FDF9C4F3-CE48-4577-8400-B261E356EDEC/d/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 0 keys tried.
shellcommand: /usr/bin/python '/private/var/folders/hm/l_hhry153sz6rj8fjgw5xsvc0000gn/T/AppTranslocation/FDF9C4F3-CE48-4577-8400-B261E356EDEC/d/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/twwwy/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/twwwy/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.3
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/twwwy/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '01fbc58e575c' and UserName 'twwwy'
Saved a key to /Users/twwwy/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
 
shellcommand: /usr/bin/python '/private/var/folders/hm/l_hhry153sz6rj8fjgw5xsvc0000gn/T/AppTranslocation/FDF9C4F3-CE48-4577-8400-B261E356EDEC/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/twwwy/Library/Preferences/com.apprenticealf.dedrm/KindleKey 3.der' '/Users/twwwy/Documents/My Kindle Content/B00PWX7S96_EBOK.azw' '/Users/twwwy/Desktop/' > '/Users/twwwy/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.4.
Copyright © 2008-2013 The Dark Reverser et al.
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Fall of the Ottomans: The Great War in the Middle East
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 4 keys tried.
 Traceback (most recent call last):
  File "/private/var/folders/hm/l_hhry153sz6rj8fjgw5xsvc0000gn/T/AppTranslocation/FDF9C4F3-CE48-4577-8400-B261E356EDEC/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 254, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/private/var/folders/hm/l_hhry153sz6rj8fjgw5xsvc0000gn/T/AppTranslocation/FDF9C4F3-CE48-4577-8400-B261E356EDEC/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 228, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/private/var/folders/hm/l_hhry153sz6rj8fjgw5xsvc0000gn/T/AppTranslocation/FDF9C4F3-CE48-4577-8400-B261E356EDEC/d/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 4 keys tried.
There was an error with 1 ebook:
B00PWX7S96_EBOK.azw couldn't be decrypted.

**Comment by ElleKayEm** [comment]
That's odd.  It should be all or nothing.  Books downloaded to the same installation of Kindle for Mac/PC should unlock with the same key.  Unless the book that worked didn't have DRM to begin with.

**Comment by apprenticeharper** [comment]
It looks like it's picking up a a key from an old App Store version of Kindle for Mac. Try deleting the folder /Users/twwwy/Library/Containers/com.amazon.Kindle and see if that fixes it.
