### ISSUE TITLE
Failed to DeDRM this AZW book (Windows 7, 64-bit)

### ISSUE THREAD

**Issue by andy20** [apprenticeharper/DeDRM_tools#356]
I transfered this book from my amazon kindle via usb. Another book was succesfully DeDRMed but this one still failed.
Log in debug mode:
calibre Fehlerdiagnoseprotokoll
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Obok DeDRM (6, 5, 4)
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 5.42 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xb9$\x05\xfd\x814\xa6\xa7\xa2\x08\xdd\xf8Z)\xdf\xc8\xbc1)L\xa7\x08\xabw7\xb6Y~\x19 c\xe3', 'C:\\Users\\Andr\xc3\xa9\\Desktop\\documents\\The Game Penetrating the Secret-asin_B007MAXHUG-type_EBOK-v_0.azw3']
DeDRM v6.5.4: Trying to decrypt The Game Penetrating the Secret-asin_B007MAXHUG-type_EBOK-v_0.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Game: Penetrating the Secret Society of Pickup Artists
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Andr\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Andr\AppData\Local\Amazon\Kindle\storage\.kinf2011
Couldn't decrypt file.
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added The Game: Penetrating the Secret Society of Pickup Artists to db in: 0.1
Added 1 books in 0.7 seconds

**Comment by ElleKayEm** [comment]
If it's from an E-ink Kindle (not a Fire), then you need to enter its serial number into the plugin customization.
