### ISSUE TITLE
ADE 3.0

### ISSUE THREAD

**Issue by drgumpi** [apprenticeharper/DeDRM_tools#357]
Is there any light on the horisont for ADE 3.0 and later DRM removal? If i try to open ascm file in 2.0.1 I get the Unable to download warning sign with some explanation about error getting license.

**Comment by ElleKayEm** [comment]
Was this the first time you had tried to download them?  If not, was the original download to an installation of ADE that had been authorized with your Adobe ID?  And was that ADE 3.0 or later?

I haven't heard of anyone working on the hardened Adobe DRM.  Until it becomes more crucial (like one of the major booksellers switching exclusively to it), I doubt we will get much progress on it.  ADE 3 and later can handle the new DRM, but books only have it if the bookseller has decided to use it.

**Comment by drgumpi** [comment]
Yes, it was the first time. The ADE 2.0 is authorized. But I must say than first I had ADE 2.0, later I install 3.0 or something like that and than I install ADE 2.0 again. But I downloaded ascm file when ADE 2.0 was installed.

**Comment by ElleKayEm** [comment]
Have you been able to read your Adobe DRM books at all?  Because I'm wondering if this is new DRM or just an issue with your Adobe ID authorization.  Uninstalling and reinstalling on the same machine can cause issues when things from the previous installation don't get completely removed.  It's also possible to run into a number of authorizations limit.

**Comment by drgumpi** [comment]
I was able to read some books from this library under ADE 3.0, but it wont open it with ADE 2.0.

**Comment by ElleKayEm** [comment]
Ok, that sounds like new DRM.  Since you said "this library", I'll point out the fact that there are no plans to ever support DRM removal from borrowed books, rentals, or trials here.

**Comment by drgumpi** [comment]
Sorry, I didn't explain all right. It isn't "regular" library. They first of all sell the books, but they also borrow some of them for some libraries.

**Comment by yulivuviki** [comment]
man try downloading the acsm using ADE_3.0_Installer .. do same steps used on ADE 2 but this time on ADE 3 .. then remove drm .

don't forget to authorize ADE 3.0  .. retrive key then de-drm

**Comment by ElleKayEm** [comment]
As explained in the FAQs, using ADE 3.0 or later might result in DRM that these tools cannot remove.

**Comment by drgumpi** [comment]
Thats mine case I guess.
