### ISSUE TITLE
Calibre DeDRM plug in for Mac OS 10.12.6 not working for Kindle AMZ files

### ISSUE THREAD

**Issue by profjhg** [apprenticeharper/DeDRM_tools#358]
On my new laptop, despite having restored image from my previous laptop via TimeMachine, I can no longer strip the DRM on most AMZ files
I made sure to:

1. Remove Kindle for Mac 1.20 and install 1.17 with no automatic updates
2. Update Calibre to version 3.7
3. Update DeDRM to version 6.5.4
4. Removed and re-downloaded books from Amazon using my Kindle for Mac 1.17.1 app

But I'm still unable to convert. I notice that my file extensions now say .AMZ instead of AMZ3, which seems to indicate the problematic KFX Amazon files, but I didn't think these would be used as long as I have Kindle for Mac 1.17, according to: https://www.mobileread.com/forums/showthread.php?t=283371

Here's the debugging log:

calibre Debug log
calibre 3.7  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Inept Epub DeDRM (0, 1, 7) && Ignoble Epub DeDRM (0, 1, 6) && Inept PDF DeDRM (0, 1, 4) && eReader PDB 2 PML (0, 0, 6)
calibre 3.7  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Inept Epub DeDRM (0, 1, 7) && Ignoble Epub DeDRM (0, 1, 6) && Inept PDF DeDRM (0, 1, 4) && eReader PDB 2 PML (0, 0, 6)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
Starting up...
Started up in 1.44 seconds with 507 books
DeDRM v6.5.4: Trying to decrypt B01K7TJ19Y_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Asymmetric Politics: Ideological Republicans and Group Interest Democrats
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/justinhgross/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Found k4Mac kinf2011 file: /Users/justinhgross/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '790ca18125eb' and UserName 'justinhgross'
Couldn't decrypt file.
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Asymmetric Politics: Ideological Republicans and Group Interest Democrats
Found 4 keys to try after 1.9 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 1.9 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 1.9 seconds

**Comment by ElleKayEm** [comment]
AZW is the generic file extension for Kindle for Mac/PC files.  Once the DRM is removed, it will have the AZW3 extension (or whatever underlying Amazon format it is).

The new installation of Kindle for Mac will have a new key.  The restored image probably left something behind from the old installation which is confusing things for the DeDRM plugin.  See the FAQs about completely uninstalling and reinstalling Kindle for Mac:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

(Also you can remove all the old single file-type DeDRM plugins.)

**Comment by profjhg** [comment]
Thanks! Once I got rid of those old folders and started over, it worked like a charm.
