### ISSUE TITLE
Failed to DeDRM this AZW book (Windows 7, 64-bit)

### ISSUE THREAD

**Issue by schwarznn** [apprenticeharper/DeDRM_tools#359]
I buyed this book in amazon. Another book was succesfully DeDRMed but this one still failed.

calibre Журнал ошибок
calibre 3.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.10240-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.10240')
Python 2.7.12+
Windows: ('10', '10.0.10240', 'SP0', u'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Kindle and Mobipocket DeDRM (0, 4, 13)
calibre 3.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.10240-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.10240')
Python 2.7.12+
Windows: ('10', '10.0.10240', 'SP0', u'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Kindle and Mobipocket DeDRM (0, 4, 13)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 128.0 x 128.186915888
Using calibre Qt style: True
Starting up...
Started up in 11.97 seconds with 130 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['-\xd5\xb5 x\xbf\xd1s\xec2\x1b\x1a{\xbfx\x10\xcdWD@\xc7\xae\xa1\xf8#\x83\xbb\x1eOg\x8d\x84', 'E:\\Skladchik\\Egorov&Co\\\xd0\x95\xd0\xb3\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb2 \xd0\xa1\xd0\xb5\xd1\x80\xd0\xb3\xd0\xb5\xd0\xb9\\B06W2LZ6ZQ_EBOK.azw']
DeDRM v6.5.4: Trying to decrypt B06W2LZ6ZQ_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright В© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Science of Attraction: Flirting, Sex, and How to Engineer Chemistry and Love
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Schwarznn\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Schwarznn\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '578617306' and UserName '5363687761727a6e6e'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright В© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Science of Attraction: Flirting, Sex, and How to Engineer Chemistry and Love
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.5 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.5 seconds
Kindle and Mobipocket DeDRM v0.4.13: Trying to decrypt B06W2LZ6ZQ_EBOK.azw.
Using Library AlfCrypto Python
Running file type plugin Kindle and Mobipocket DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.k4mobidedrm.__init__", line 116, in run
  File "calibre_plugins.k4mobidedrm.__init__", line 249, in config
  File "site-packages\calibre\customize\zipplugin.py", line 183, in load_module
  File "calibre_plugins.k4mobidedrm.config", line 4, in <module>
ImportError: No module named PyQt4.Qt
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added The Science of Attraction: Flirting, Sex, and How to Engineer Chemistry and Love to db in: 0.5
Added 1 books in 4.9 seconds
Worker Launch took: 0.628999948502
Job: 1 Конвертировать книгу 1 из 1 (The Science of Attraction: Flirting, Sex, and How to Engineer Chemistry and Love) finished
Конвертировать книгу 1 из 1 (The Science of Attraction: Flirting, Sex, and How to Engineer Chemistry and Love)
	C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  docx_page_size: u'a4'
	  cover: u'C:\\Users\\SCHWAR~1\\AppData\\Local\\Temp\\calibre_ur5lmz\\cr0dow.jpeg'
	  output_profile: 'generic_eink'
	  read_metadata_from_opf: u'C:\\Users\\SCHWAR~1\\AppData\\Local\\Temp\\calibre_ur5lmz\\jeez8d.opf'
	  verbose: 2
	Resolved conversion options
	calibre version: 3.6.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\SCHWAR~1\\AppData\\Local\\Temp\\calibre_ur5lmz\\cr0dow.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'docx_custom_page_size': None,
	 'docx_no_cover': False,
	 'docx_no_toc': False,
	 'docx_page_margin_bottom': 72.0,
	 'docx_page_margin_left': 72.0,
	 'docx_page_margin_right': 72.0,
	 'docx_page_margin_top': 72.0,
	 'docx_page_size': u'a4',
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000009E198470B8>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000009E19847438>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\SCHWAR~1\\AppData\\Local\\Temp\\calibre_ur5lmz\\jeez8d.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\SCHWAR~1\AppData\Local\Temp\calibre_ur5lmz\rthnn6.azw
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  The Science of Attraction: Flirting, Sex, and How to Engineer Chemistry and Love (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: The Science of Attraction: Flirting, Sex, and How to Engineer Chemistry and Love

Worker Launch took: 0.581000089645
Job: 2 Конвертировать книгу 1 из 1 (The Science of Attraction: Flirting, Sex, and How to Engineer Chemistry and Love) finished
Конвертировать книгу 1 из 1 (The Science of Attraction: Flirting, Sex, and How to Engineer Chemistry and Love)
	C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  verbose: 2
	  cover: u'C:\\Users\\SCHWAR~1\\AppData\\Local\\Temp\\calibre_ur5lmz\\qc9_c7.jpeg'
	  output_profile: 'generic_eink'
	  read_metadata_from_opf: u'C:\\Users\\SCHWAR~1\\AppData\\Local\\Temp\\calibre_ur5lmz\\j0dm2x.opf'
	Resolved conversion options
	calibre version: 3.6.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\SCHWAR~1\\AppData\\Local\\Temp\\calibre_ur5lmz\\qc9_c7.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000000CFDA544F98>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000000CFDA549358>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\SCHWAR~1\\AppData\\Local\\Temp\\calibre_ur5lmz\\j0dm2x.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\SCHWAR~1\AppData\Local\Temp\calibre_ur5lmz\gnasux.azw
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  The Science of Attraction: Flirting, Sex, and How to Engineer Chemistry and Love (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: The Science of Attraction: Flirting, Sex, and How to Engineer Chemistry and Love

**Comment by ElleKayEm** [comment]
The successful book probably didn't have DRM to begin with.  Take a look at this section of the FAQs:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

(You can remove the "Kindle and Mobipocket DeDRM" plugin.)
