### ISSUE TITLE
DeDRM direct from device (and support for linux by this)

### ISSUE THREAD

**Issue by norbusan** [apprenticeharper/DeDRM_tools#36]
Hi all,
I played around with the obok.py script and found out that I can easily decrypt books from my Kobo device when instead of the MAC address of the device, I use the serial number.
In principle I did a bit of hacking to adjust the paths of `self.kobodir` and then added:
`````
@@ -297,6 +308,9 @@
             for m in matches:
                 # print "m:",m[0]
                 macaddrs.append(m[0].upper())
+        elif sys.platform.startswith('linux'):
+            # my Kobo GloHD serial - that does the trick
+           macaddrs.append('SERIAL NUMBER OF YOUR KOBO')
         return macaddrs
 
     def __getuserids (self):
`````

WIth that removal of drm from kepubs on my device worked without a problem. Also, the script started to work on Linux.

I tried a bit to integrate it into the obok calibre plugin and add an interface a la DeDRM plugin with configuration of the device, but didn't succeed, due to limited Python and Calibre-internals knowledge.

I hope that this information allows someone with more insight into the script to add support both for Linux and getting decryption direct from the device.

Thanks

**Comment by apprenticeharper** [comment]
Many thanks for your research and work on this issue. Your fixes are now in a separate branch, with some additions for Unicode support. Once some reports come back, it will be included in the next release.
