### ISSUE TITLE
new Problem kindle 1.17 with DDRM 6.5.4

### ISSUE THREAD

**Issue by kraecke** [apprenticeharper/DeDRM_tools#361]
Sorry, i installed after hd-crash like the last time kindle 1.174418 and made download of the ebooks. Could not open the books. For example, here is the report of one of the books:
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Dr. Jrgen Krcher\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Dr. Jrgen Krcher\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1758370817' and UserName '44722e204afc7267656e204be47263686572'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Aquamarin (German Edition)
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.3 seconds
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Aquamarin (German Edition) to db in: 0.2
Added 1 books in 1.5 seconds
Worker Launch took: 0.320999860764
Any ideas?

**Comment by ElleKayEm** [comment]
Looks like you have a couple vowels with an umlaut in your user name.  There's a known bug which prevents the retrieval of the Kindle for PC key when there are non-ascii characters in your Windows user name.  Create another user name with only ascii characters and install Kindle for PC, calibre, and the DeDRM plugin there.

**Comment by apprenticeharper** [comment]
Please try the new 6.5.5 release on your original user account.

**Comment by apprenticeharper** [comment]
Assumed fixed.
