### ISSUE TITLE
Calibre cannot remove DRM, B&N ePub

### ISSUE THREAD

**Issue by Ocione** [apprenticeharper/DeDRM_tools#362]
calibre Debug log
calibre 3.7  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.7  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
Starting up...
Started up in 60.98 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x16\x9a\xfa\xe3\xbc\xe5g\x17j\xac\xf6\xe5)\x94P\xea\xca\x86E\xa1\x10\xa4\x11\x87J\xc6\x13\xc5\xb2\xde\xc3\x08', 'C:\\Users\\Raymond\\Documents\\My Barnes & Noble eBooks\\raymond.turco93@gmail.com\\lasolitudinedeinumer_9788852014062.epub']
DeDRM v6.5.4: Trying to decrypt lasolitudinedeinumer_9788852014062.epub
DeDRM v6.5.4: Verifying zip archive integrity
DeDRM v6.5.4: “lasolitudinedeinumer_9788852014062.epub” is a secure Barnes & Noble ePub
DeDRM v6.5.4: Looking for new NOOK Study Keys after 0.0 seconds
No nook Study log files have been found.
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 293, in ePubDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Added La solitudine dei numeri primi to db in: 1.8
Added 1 books in 2.4 seconds
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['-\x040\xb0V\xfd\x04*<aq\xa0\xb7q\xb7\xa2\x130\xa9\x95\x0c\x8a\xa5 5z\x1d\xd4\x1fw\xf6\xea', 'C:\\Users\\Raymond\\Downloads\\71TGEQnb8mL.jpg']
Worker Launch took: 0.116000175476
Job: 1 Convert book 1 of 1 (La solitudine dei numeri primi) finished
Convert book 1 of 1 (La solitudine dei numeri primi)
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\Raymond\\AppData\\Local\\Temp\\calibre_zcsbcx\\2lfhuf.opf'
	  output_profile: 'kindle_pw3'
	  cover: u'C:\\Users\\Raymond\\AppData\\Local\\Temp\\calibre_zcsbcx\\3zk8q0.jpeg'
	Resolved conversion options
	calibre version: 3.7.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Raymond\\AppData\\Local\\Temp\\calibre_zcsbcx\\3zk8q0.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x04850430>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x04850810>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Raymond\\AppData\\Local\\Temp\\calibre_zcsbcx\\2lfhuf.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\Raymond\AppData\Local\Temp\calibre_zcsbcx\ke1mq1.epub
	Python function terminated unexpectedly
	  ke1mq1.epub (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 268, in convert
	calibre.ebooks.DRMError: ke1mq1.epub

**Comment by Ocione** [comment]
Attempted to use Calibre to turn this ebook into a Kindle format. Bought it from B&N and downloaded it through an old version of Nook for PC. Plugin is properly downloaded.

**Comment by ElleKayEm** [comment]
You need to enter your B&N account email and password into the plugin customization.

**Comment by Ocione** [comment]
Worked like a charm. Thanks!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
