### ISSUE TITLE
Problem Kindle  1.17  - Calibre 3.7 - DeDRM 6.5.4

### ISSUE THREAD

**Issue by asierra79** [apprenticeharper/DeDRM_tools#363]
This book  was unsuccesfully DeDRMed : 

DeDRM v6.5.4: Trying to decrypt B01MYR3R4T_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: El ciclo del amor marica (No Ficción) (Spanish Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Amo Andrs\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Amo Andrs\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '653187431' and UserName '416d6f20416e6472e973'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: El ciclo del amor marica (No Ficción) (Spanish Edition)
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds
Added El ciclo del amor marica (No Ficción) (Spanish Edition) to db in: 1.5
Added 1 books in 2.3 seconds

Also this other book failed:

DeDRM v6.5.4: Trying to decrypt B019WY00A4_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Quiérete mucho, maricón: Manual de éxito psicoemocional para hombres homosexuales (Spanish Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Amo Andrs\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Amo Andrs\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '653187431' and UserName '416d6f20416e6472e973'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Quiérete mucho, maricón: Manual de éxito psicoemocional para hombres homosexuales (Spanish Edition)
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds
Added Quiérete mucho, maricón: Manual de éxito psicoemocional para hombres homosexuales (Spanish Edition) to db in: 1.6
Added 1 books in 2.4 seconds

Please HELP!!

**Comment by ElleKayEm** [comment]
The problem is the accented character in your Windows user name.  Create a user name with only ASCII characters, and then install Kindle for PC, calibre, and the plugin there.

**Comment by apprenticeharper** [comment]
Please try again on your original user account using the new 6.5.5 release of the plugin.

**Comment by apprenticeharper** [comment]
I'm assuming that fixed it.
