### ISSUE TITLE
azw book conversion with drm that did not work

### ISSUE THREAD

**Issue by ccowelll1965** [apprenticeharper/DeDRM_tools#364]
here is the command prompt output. I hope someone can tell me what i am doing wrong. I am trying to convert to mobi.

C:\Users\Carole>calibre-debug -g
calibre 3.7  embedded-python: True is64bit: False
Windows-10-10.0.14393-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 127.331592689 x 127.590697674
Using calibre Qt style: True
Starting up...
Started up in 2.29 seconds with 1 books
Worker Launch took: 0.28400015831
Job: 1 Convert book 1 of 1 (The Complete Guide to Asperger's Syndrome) finished
Convert book 1 of 1 (The Complete Guide to Asperger's Syndrome)
        Conversion options changed from defaults:
          verbose: 2
          read_metadata_from_opf: u'C:\\Users\\Carole\\AppData\\Local\\Temp\\calibre_nkfmpt\\sskq5y.opf'
          output_profile: 'kindle'
          cover: u'C:\\Users\\Carole\\AppData\\Local\\Temp\\calibre_nkfmpt\\nd7_dw.jpeg'
        Resolved conversion options
        calibre version: 3.7.0
        {'asciiize': False,
         'author_sort': None,
         'authors': None,
         'base_font_size': 0.0,
         'book_producer': None,
         'change_justification': u'original',
         'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
         'chapter_mark': u'pagebreak',
         'comments': None,
         'cover': u'C:\\Users\\Carole\\AppData\\Local\\Temp\\calibre_nkfmpt\\nd7_dw.jpeg',
         'debug_pipeline': None,
         'dehyphenate': True,
         'delete_blank_paragraphs': True,
         'disable_font_rescaling': False,
         'dont_compress': False,
         'duplicate_links_in_toc': False,
         'embed_all_fonts': False,
         'embed_font_family': None,
         'enable_heuristics': False,
         'expand_css': False,
         'extra_css': None,
         'extract_to': None,
         'filter_css': u'',
         'fix_indents': True,
         'font_size_mapping': None,
         'format_scene_breaks': True,
         'html_unwrap_factor': 0.4,
         'input_encoding': None,
         'input_profile': <calibre.customize.profiles.InputProfile object at 0x049804B0>,
         'insert_blank_line': False,
         'insert_blank_line_size': 0.5,
         'insert_metadata': False,
         'isbn': None,
         'italicize_common_cases': True,
         'keep_ligatures': False,
         'language': None,
         'level1_toc': None,
         'level2_toc': None,
         'level3_toc': None,
         'line_height': 0.0,
         'linearize_tables': False,
         'margin_bottom': 5.0,
         'margin_left': 5.0,
         'margin_right': 5.0,
         'margin_top': 5.0,
         'markup_chapter_headings': True,
         'max_toc_links': 50,
         'minimum_line_height': 120.0,
         'mobi_file_type': u'old',
         'mobi_ignore_margins': False,
         'mobi_keep_original_images': False,
         'mobi_toc_at_start': False,
         'no_chapters_in_toc': False,
         'no_inline_navbars': True,
         'no_inline_toc': False,
         'output_profile': <calibre.customize.profiles.KindleOutput object at 0x04980810>,
         'page_breaks_before': u"//*[name()='h1' or name()='h2']",
         'personal_doc': u'[PDOC]',
         'prefer_author_sort': False,
         'prefer_metadata_cover': False,
         'pretty_print': False,
         'pubdate': None,
         'publisher': None,
         'rating': None,
         'read_metadata_from_opf': u'C:\\Users\\Carole\\AppData\\Local\\Temp\\calibre_nkfmpt\\sskq5y.opf',
         'remove_fake_margins': True,
         'remove_first_image': False,
         'remove_paragraph_spacing': False,
         'remove_paragraph_spacing_indent_size': 1.5,
         'renumber_headings': True,
         'replace_scene_breaks': u'',
         'search_replace': '[]',
         'series': None,
         'series_index': None,
         'share_not_sync': False,
         'smarten_punctuation': False,
         'sr1_replace': None,
         'sr1_search': None,
         'sr2_replace': None,
         'sr2_search': None,
         'sr3_replace': None,
         'sr3_search': None,
         'start_reading_at': None,
         'subset_embedded_fonts': False,
         'tags': None,
         'timestamp': None,
         'title': None,
         'title_sort': None,
         'toc_filter': None,
         'toc_threshold': 6,
         'toc_title': None,
         'transform_css_rules': '[]',
         'unsmarten_punctuation': False,
         'unwrap_lines': True,
         'use_auto_toc': False,
         'verbose': 2}
        InputFormatPlugin: MOBI Input running
        on C:\Users\Carole\AppData\Local\Temp\calibre_nkfmpt\u6zooe.azw
        Python function terminated unexpectedly
          The Complete Guide to Asperger's Syndrome (Error Code: 1)
        Traceback (most recent call last):
          File "site.py", line 101, in main
          File "site.py", line 78, in run_entry_point
          File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
          File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
          File "site-packages\calibre\customize\conversion.py", line 245, in __call__
          File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert
          File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 161, in extract_content
          File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
        calibre.ebooks.DRMError: The Complete Guide to Asperger's Syndrome

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add the book, not during conversion.  Post a log of adding the book.

**Comment by ccowelll1965** [comment]
calibre Debug log
calibre 3.7  embedded-python: True is64bit: False
Windows-10-10.0.14393-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.7  embedded-python: True is64bit: False
Windows-10-10.0.14393-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 127.331592689 x 127.590697674
Using calibre Qt style: True
Starting up...
Started up in 23.59 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['[\xa5\x08\xf7\xc3\xc3\xc9\x81\xb2)\xa5\x85t\x864u\xf2J\xd4\xd0J\x82\xe8x"\xe3!e\xf9\x8c\x9b\x13', "C:\\Users\\Carole\\Downloads\\The Complete Guide to Asperger's Syndrome.azw"]
DeDRM v6.5.4: Trying to decrypt The Complete Guide to Asperger's Syndrome.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 7
Decrypting Mobipocket 6 ebook: The Complete Guide to Asperger's Syndrome
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Carole\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Carole\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1608723920' and UserName '4361726f6c65'
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds
Added The Complete Guide to Asperger's Syndrome to db in: 2.5
Added 1 books in 3.3 seconds
Job: 1 Debug device detection started
DeviceJob: 1 Debug device detection done, calling callback
DeviceJob: 1 Debug device detection callback returned
Job: 1 Debug device detection finished
No details available.


hope this helps

**Comment by ElleKayEm** [comment]
If that's from or for an E-ink Kindle (not a Fire), then you need to enter its serial number into the plugin customization.

**Comment by ccowelll1965** [comment]
It is going to be for a kindle app for iPad

**Comment by ElleKayEm** [comment]
How did you download the file?  An E-ink Kindle or downloaded from the website for an E-ink Kindle?  Then enter the serial number into the plugin customization.  Otherwise, download it with Kindle for PC on the same PC and user as calibre.

**Comment by ccowelll1965** [comment]
Hi, 

I have given up.  I un installed calibre, reinstalled the 64 bit version. Added an older version of the deform because when I installed the current version I got a message stating it was missing a file. Sorry, I do not remember what that file was. This is when I got a previous version, installed it, had no troubles. 

Added problem aww book to calibre only to experience same problem. My set up the program for kindle period. I chose plain kindle because it is going to the app on my iPad. The book was a book I got off the internet years ago. Since it did not work with this new setup, I found a new copy an am all set. Hopefully, if I run into another book that needs conversation I will be able to do it. Though I don't have much hope. :(. Any, thanks for trying to help me. I appreciate it.

Carole

**Comment by ElleKayEm** [comment]
DeDRM only works on books from your own account.  As far as not being able to install the current version, it sounds like you were trying to load the whole zip file, instead of the plugin.  If you're all set, then you can close the issue.
