### ISSUE TITLE
AZW4 Conversion Error (Windows 7, 64 Bit)

### ISSUE THREAD

**Issue by dogdaughters** [apprenticeharper/DeDRM_tools#365]
Convert book 1 of 1 (Principles of Life, Second Edition)
Conversion options changed from defaults:
  output_profile: 'kindle'
  cover: u'C:\\Users\\cheet\\AppData\\Local\\Temp\\calibre_2kbmgu\\314mny.jpeg'
  verbose: 2
  read_metadata_from_opf: u'C:\\Users\\cheet\\AppData\\Local\\Temp\\calibre_2kbmgu\\r4ki2c.opf'
Resolved conversion options
calibre version: 3.7.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\cheet\\AppData\\Local\\Temp\\calibre_2kbmgu\\314mny.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001B0088D4EF0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x000001B0088F6518>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Liberation Mono',
 'pdf_mono_font_size': 16,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Liberation Sans',
 'pdf_serif_family': u'Liberation Serif',
 'pdf_standard_font': u'serif',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\cheet\\AppData\\Local\\Temp\\calibre_2kbmgu\\r4ki2c.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Python function terminated unexpectedly
  No embedded PDF found in AZW4 file (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1074, in run
  File "site-packages\calibre\ebooks\azw4\reader.py", line 24, in unwrap
ValueError: No embedded PDF found in AZW4 file

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add the book to calibre, not during conversion.  Post a log of adding the book.

**Comment by dogdaughters** [comment]
Whoops, sorry about that.

calibre Debug log
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.4837092732 x 82.1317365269
Using calibre Qt style: True
Starting up...
Started up in 5.12 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x91\x7f\xe8\xc4\x84\x89\x81\xddO\x1f}\xa8\x8d\xbf\x11.\x0fw\xb7\x87)7\x81\x8bT\xf9\xd1\xd9\xa9y\x85"', 'C:\\Users\\cheet\\Documents\\My Kindle Content\\B00RZQ2F4G_EBOK.azw4']
DeDRM v6.5.4: Trying to decrypt B00RZQ2F4G_EBOK.azw4
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 248
Decrypting Mobipocket 4 ebook: Principles of Life, Second Edition
Found 0 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\cheet\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds
Added Principles of Life, Second Edition to db in: 2.2
Added 1 books in 3.2 seconds

**Comment by ElleKayEm** [comment]
Ok, the book looks like it's from Kindle for PC, but DeDRM isn't finding Kindle for PC on this machine.  Kindle for PC and calibre need to be installed on the same machine and user name.

**Comment by dogdaughters** [comment]
Another simple mistake, sorry about that. I installed Kindle for PC on my computer under the same username, but the issue still persists.

calibre Debug log
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.4837092732 x 82.1317365269
Using calibre Qt style: True
Starting up...
Started up in 17.02 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['z\x83N\xb8\x10\xc5\x8f\xc9\x8eX\xed\xf6\x97\xa6\xcfS\xed\xc6\x944\x92J\xe3;\x1f\xcd\x86\x18\x8eb\xf8\xad', 'C:\\Users\\cheet\\Documents\\My Kindle Content\\B00RZQ2F4G_EBOK.azw4']
DeDRM v6.5.4: Trying to decrypt B00RZQ2F4G_EBOK.azw4
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 248
Decrypting Mobipocket 4 ebook: Principles of Life, Second Edition
Found 0 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\cheet\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\cheet\AppData\Local\Amazon\Kindle\storage\.kinf2011
Couldn't decrypt file.
DeDRM v6.5.4: Ultimately failed to decrypt after 0.5 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.5 seconds
Added Principles of Life, Second Edition to db in: 2.4
Added 1 books in 3.5 seconds

**Comment by ElleKayEm** [comment]
Did you redownload the book with the new installation of Kindle for PC?  Each app installation (or device) has its own unique key even for the same account.

**Comment by dogdaughters** [comment]
Yes I did.

**Comment by ElleKayEm** [comment]
Take a look at this section of the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

If nothing else seems to be the problem, then follow the instructions there for completely uninstalling and reinstalling Kindle for PC.

**Comment by dogdaughters** [comment]
Alright I followed the steps, and it seems the book is stuck on adding. 
"Reading metadata and adding to library (one book).... 0%"

Things aren't looking so good. I'll let it run for ~24h to see if anything happens. Thank you for all your assistance I sincerely appreciate it. If there's anything more you could do for me I would be more than happy to see it.

**Comment by ElleKayEm** [comment]
Glad it worked.  If you were trying to convert to PDF, you might be better off using the KindleUnpack plugin.
