### ISSUE TITLE
AZW book fails to remove DRM

### ISSUE THREAD

**Issue by justinf200** [apprenticeharper/DeDRM_tools#366]
I'm sorry but I'm getting the following error message even though I've read the blogs, and I've done this before. I have the recommended version of Kindle installed on my Mac. I would really appreciate the help, thank you.

**Comment by justinf200** [comment]
calibre Debug log
calibre 3.7  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Obok DeDRM (6, 5, 4)
calibre 3.7  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Obok DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 1.75 seconds with 132 books
DeDRM v6.5.4: Trying to decrypt B009P366PQ_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Understanding Japanese Society (Nissan Institute/Routledge Japanese Studies)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/pasqualalonzo/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '01fbc5b119c8' and UserName 'pasqualalonzo'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Understanding Japanese Society (Nissan Institute/Routledge Japanese Studies)
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.3 seconds

Debugging DND event
text/uri-list 80 'file:///Users/pasqualalonzo/Desktop/WE%20ARE!%20-%20Single/B009P366PQ_EBOK.azw\r\n' 


Firefox rurl: None None
URLS: ['file:///Users/pasqualalonzo/Desktop/WE%20ARE!%20-%20Single/B009P366PQ_EBOK.azw']
Paths: [u'/Users/pasqualalonzo/Desktop/WE ARE! - Single/B009P366PQ_EBOK.azw']
Extensions: frozenset([u'azw'])
Added Understanding Japanese Society (Nissan Institute/Routledge Japanese Studies) to db in: 0.0
Added 1 books in 1.2 seconds

**Comment by ElleKayEm** [comment]
DeDRM does not work on rentals.
