### ISSUE TITLE
Book cannot be opened in Calibre due to DRM

### ISSUE THREAD

**Issue by marypoppins276** [apprenticeharper/DeDRM_tools#367]
The Readme of the plugin suggested to post the logfile here. Can you help?

calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.356521739 x 141.402061856
Using calibre Qt style: True
Starting up...
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\9017220144230ANF&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=9)
{u'drive_letters': ['D'],
 u'pnp_id_map': {'D': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#9017220144230anf&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'D': (1L, 1L)}}
Job: 1 Geräteinformationen erhalten started
DeviceJob: 1 Geräteinformationen erhalten done, calling callback
DeviceJob: 1 Geräteinformationen erhalten callback returned
Job: 2 Bibliotheksinformationen festlegen started
DeviceJob: 2 Bibliotheksinformationen festlegen done, calling callback
DeviceJob: 2 Bibliotheksinformationen festlegen callback returned
Job: 3 Liste der Bücher auf dem Gerät erhalten started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ documents
Started up in 6.80 seconds with 1 books
Job: 2 Bibliotheksinformationen festlegen finished
Keine weiteren Informationen verfügbar.
Job: 1 Geräteinformationen erhalten finished
Keine weiteren Informationen verfügbar.
DEBUG:    0.2 USBMS: scan from root False D:\documents
DEBUG:    0.8 USBMS: count found in cache: 298, count of files in metadata: 298, need_sync: False
DEBUG:    0.8 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.8 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.8 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Liste der Bücher auf dem Gerät erhalten done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 298
DeviceJob: set_books_in_library finished: time= 0.00999999046326
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Liste der Bücher auf dem Gerät erhalten callback returned
Job: 3 Liste der Bücher auf dem Gerät erhalten finished
Keine weiteren Informationen verfügbar.
stdout+stderr from file dialog helper: ['', '']
stdout+stderr from file dialog helper: ['', '']
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xc7\xe2#\x1b\xaeF\xec\xf37\xf5.\xa8V\xed:\x05\xb0\xc5\x9b\x9fc\x957&\xfaz/\x07\xda|\x1e\xd6', 'C:\\Users\\ninap\\Downloads\\DeDRM_tools_6.5.4\\Other_Tools\\DRM_Key_Scripts\\Kindle_for_Mac_and_PC\\Spiel der Zeit_ Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) - Jeffrey Archer.azw3']
DeDRM v6.5.4: Trying to decrypt Spiel der Zeit_ Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) - Jeffrey Archer.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\ninap\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added 1 books in 0.7 seconds
Job: 4 Ein Buch auf das Gerät hochladen: Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) started
Device using plugboard azw3 KINDLE2 None
Setting metadata in: Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) at: C:\Users\ninap\Downloads\DeDRM_tools_6.5.4\Other_Tools\DRM_Key_Scripts\Kindle_for_Mac_and_PC\Spiel der Zeit_ Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) - Jeffrey Archer.azw3
DEBUG:  121.0 USBMS: uploading 1 books
APNX META: guid: 00ff9d13
APNX META: ASIN: B00QZELL0S
APNX META: CDE: EBOK
APNX META: format: MOBI_8
APNX META: Name: CR_7SDSBSFBQH4VKC8A44A934VFSNQD
APNX Content Header: {"contentGuid":"00ff9d13","asin":"B00QZELL0S","cdeType":"EBOK","format":"MOBI_8","fileRevisionId":"1","acr":"CR_7SDSBSFBQH4VKC8A44A934VFSNQD"}
DEBUG:  121.4 USBMS: finished uploading 1 books
DeviceJob: 4 Ein Buch auf das Gerät hochladen: Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) done, calling callback
DEBUG:  121.4 USBMS: adding metadata for 1 books
DEBUG:  121.4 USBMS: finished adding metadata
DeviceJob: set_books_in_library: books to process= 298
DeviceJob: set_books_in_library finished: time= 0.0110001564026
DeviceJob: 4 Ein Buch auf das Gerät hochladen: Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) callback returned
Job: 5 Metadaten zum Gerät senden started
DEBUG:  121.5 USBMS: starting sync_booklists
Job: 4 Ein Buch auf das Gerät hochladen: Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) finished
Keine weiteren Informationen verfügbar.
DEBUG:  124.2 USBMS: finished sync_booklists
DeviceJob: 5 Metadaten zum Gerät senden done, calling callback
DeviceJob: 5 Metadaten zum Gerät senden callback returned
Job: 5 Metadaten zum Gerät senden finished
Keine weiteren Informationen verfügbar.
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xec\xdbQ\xf8\xa9\xa0X\x13\xb1\xe3X\x13k\x9d\xbe\xc5B\xf4{]\x15\xab\x1c\x0fe\x15\xa1c\x12Cj\x90', 'C:\\Users\\ninap\\Downloads\\DeDRM_tools_6.5.4\\Other_Tools\\DRM_Key_Scripts\\Kindle_for_Mac_and_PC\\Spiel der Zeit_ Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) - Jeffrey Archer.azw3']
DeDRM v6.5.4: Trying to decrypt Spiel der Zeit_ Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) - Jeffrey Archer.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\ninap\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) to db in: 0.7
Added 1 books in 1.4 seconds
Worker Launch took: 0.200999975204
Worker Launch took: 0.239000082016
Job: 7 Buch 1 von 1 (Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition)) konvertieren finished
Buch 1 von 1 (Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition)) konvertieren
	C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\ninap\\AppData\\Local\\Temp\\calibre_qmxksz\\ujw9cd.opf'
	  verbose: 2
	  cover: u'C:\\Users\\ninap\\AppData\\Local\\Temp\\calibre_qmxksz\\fjjlts.jpeg'
	Resolved conversion options
	calibre version: 3.7.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\ninap\\AppData\\Local\\Temp\\calibre_qmxksz\\fjjlts.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000022E9BBB2400>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x0000022E9BBB2748>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\ninap\\AppData\\Local\\Temp\\calibre_qmxksz\\ujw9cd.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\ninap\AppData\Local\Temp\calibre_qmxksz\girose.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Spiel der Zeit: Die Clifton Saga 1 - Roman (Die Clifton-Saga) (German Edition)

**Comment by ElleKayEm** [comment]
If that's from an E-ink Kindle or downloaded from the website for an E-ink Kindle (not a Fire), then you need to enter its serial number into the plugin customization.

**Comment by marypoppins276** [comment]
Thank you very much. It can be so easy!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
