### ISSUE TITLE
DeDRM 6.5.4 Will not decode

### ISSUE THREAD

**Issue by Targaryn** [apprenticeharper/DeDRM_tools#368]
Using Calibre 3.70, DeDrm 6.5.4, Tried 6 books to import into Calibre none were successful.  Have used previous  versions of both files with no problem.  Attached is Debug log, Dropping files onto DeDRM app for Mac, decoded fine.
[tmpbwe9_L.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1309740/tmpbwe9_L.txt)

**Comment by ElleKayEm** [comment]
My guess is you have your E-ink Kindle's serial number in the Mac app but not calibre.

**Comment by Targaryn** [comment]
I have more than one serial number Multiple Kindles') and they are in both applications.

**Comment by ElleKayEm** [comment]
Make sure the one that these books are for is entered correctly into the plugin customization.

**Comment by Targaryn** [comment]
I get the message when I Add book into Calibre, "Cannot convert xxx, This book is locked by DRM, etc. At this point I have not moved it to Kindle yet.  I believe that the problem is Calibre plug in is not working correctly, and I have had no problems until upgrading to Calibre 3.70 and the ne DeDRM tool 6.5.4
Thanks for the reply.

**Comment by ElleKayEm** [comment]
When you download a book from the website, you choose the Kindle it is intended for.  This will determine which key the book is locked with.  The log you posted shows that none of the keys already in the plugin are the one for this book.

**Comment by Targaryn** [comment]
Thank you for the reply.  I will check but that Kindle's key has not changed.  When I entered the Kindle keys in Calibre plug-in, I did so as a coma separated string the same as I did with the DeDRM app, which removed the drm with no problem.  I was sure this was the way I have done it in the past with Calibre and plug-in software updates.  Am I missing something here?

**Comment by Targaryn** [comment]
Hello, As an update, I removed all keys, checked the key for the Kindle that downloaded the book, re-entered the key, same result.

**Comment by ElleKayEm** [comment]
Hmm, not familar with adding more than one serial number at a time into the plugin.  I suggest trying to enter just the one that you chose when downloading the book.  Then restart calibre before adding books.  Easiest way to avoid typos is to copy and paste from the website (removing spaces).

**Comment by Targaryn** [comment]
Thanks to all who replied and because of that, I have found  the problem.  It was me.
When I entered the keys in the plug in, I entered them in "Kindle for Mac/PC ebooks"
instead of "elnk Kindle ebooks" I am not sure what the difference is but I am running Calibre on a Mac and having been quite a while since I upgraded Calibre obviously forgot the proper place to enter keys
Thanks again to all.

**Comment by ElleKayEm** [comment]
You usually don't need to manually enter keys when removing DRM from Kindle for PC/Mac books, but you always need to put in the serial number for books from E-ink Kindles.  If you're all set, you can close the issue.

**Comment by Targaryn** [comment]
The books I was trying to  remove drm from were re-downloaded in AZW3 format to my computer than imported into Calibre. Please can you tell me what E-ink actually means?

**Comment by ElleKayEm** [comment]
E-ink Kindles are the black & white screens like the Paperwhite, as opposed to the color screens like the Fire tablets.  When you download a book from the website, you have to choose one of the Kindles on your account.  Then it will have DRM which is keyed to that particular device.  In order to remove that DRM, it must be for an E-ink Kindle, not a Fire.  If someone doesn't have an E-ink Kindle, then they can download their books with Kindle for PC/Mac and the DeDRM tools will automatically look on the computer for the key file.

**Comment by Targaryn** [comment]
Thanks so much ElleKayEm, your help has been very much appreciated.
