### ISSUE TITLE
Got a book. not from amazon or kindle, has DRM and the plugin didn't fix it.

### ISSUE THREAD

**Issue by sasifarah** [apprenticeharper/DeDRM_tools#369]
There's an applicatipn for buying EBooks in Iran which only lets you read the book on your android or windows device with the application itself. i wanted to read the books i bought on my kindle so i uploaded the file on calibre. the cover and information were ok but the text wasn't. i used the DeDRM plugin and it didn't help.
the format is .epub
I have no idea how to fix it.

**Comment by ElleKayEm** [comment]
DeDRM works with EPUBs which have Adobe DRM or Barnes & Noble's DRM.  Since this can only be read in a particular app, it probably has its own unique DRM type.  Unless someone figures out a method for unlocking it and shares it, then these tools won't help.
