### ISSUE TITLE
Epub from Google Play on OpenSUSE (Leap 42.2) + virtual XP machine

### ISSUE THREAD

**Issue by nnnn6** [apprenticeharper/DeDRM_tools#370]
I downloaded the book I purchased from Google Play Books and opened it on a virtual windows xp machine with Digital Editions 2.0. I then copied the epub file to a shared directory on windows, then attempted to open the same file on Linux with Calibre (image below) (DeDRM plugin installed) to no avail (Log below). (Would do it all on the virtual machine but the compatible Calibre version does not support the DeDRM plugin.)

I have been utilizing this system successfully for a few years. This, however, is a different computer with basically the same setup (Leap 42.2 as opposed to OpenSUSE 13.1). Any suggestions or advice would be greatly appreciated. Thanks in advance.

![drm-screenshot](https://user-images.githubusercontent.com/32116062/30624522-96dfe512-9d83-11e7-986b-95cab46a9e6b.png)

QML debugging is enabled. Only use this in a safe environment.
calibre Debug log
calibre 2.81  embedded-python: False is64bit: True
Linux-4.4.79-18.26-default-x86_64-with-SuSE-42.2-x86_64 Linux ('64bit', 'ELF')
('Linux', '4.4.79-18.26-default', '#1 SMP Thu Aug 10 20:30:05 UTC 2017 (fa5a935)')
Python 2.7.13
Linux: ('openSUSE ', '42.2', 'x86_64')
Successfully initialized third party plugins: DeDRM (6, 5, 4)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.2526315789
physicalDpi: 95.6235294118 x 95.5818815331
Starting up...
QML debugging is enabled. Only use this in a safe environment.
DeDRM v6.5.4: Trying to decrypt Complete Works of L. M. Montgomery.epub
DeDRM v6.5.4: Verifying zip archive integrity
DeDRM v6.5.4: Complete Works of L. M. Montgomery.epub is a secure Adobe Adept ePub
DeDRM v6.5.4: Looking for new default Adobe Digital Editions Keys after 0.4 seconds
DeDRM v6.5.4: Running adobekey.py under Wine
DeDRM v6.5.4: Command line: 'WINEPREFIX="/home/garth" wine python.exe "/home/garth/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/garth/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
/bin/sh: wine: command not found
DeDRM v6.5.4: Found and decrypted 0 key files
DeDRM v6.5.4: Exception when getting default Adobe Key after 0.4 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 345, in ePubDecrypt
IndexError: list index out of range
DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 170, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 393, in ePubDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds.
Started up in 26.60 seconds with 7 books
Added Complete Works of L. M. Montgomery to db in: 1.8
Added 1 books in 3.7 seconds

**Comment by ElleKayEm** [comment]
If you have another setup where you are able to remove Adobe DRM and this installation of ADE is authorized to the same Adobe ID, then you could save the Adobe key from the DeDRM plugin in the working setup and import it into the plugin in your Linux calibre.

**Comment by nnnn6** [comment]
First off, thank you for responding. The problem is, I no longer have that setup. I should have indicated that the setup I'm using now, replaces the one previous (upgrade). So that option is not available unfortunately.

**Comment by ElleKayEm** [comment]
Ok, obviously the issue is that the DeDRM plugin can't find the key inside the virtual machine.  There should be some way to retrieve it, save it, and import it into Linux calibre.  I wonder if you could just run the Adobe DRM key script (look in the Other_Tools folder and then DRM_Key_Scripts) inside the virtual machine.  Or the stand-alone Windows DeDRM app.  If neither of those work, you could try temporarily installing the older calibre with an older version of the DeDRM plugin in the virtual machine.  Not sure how far back you'd need to go (or if the older versions have the easy save key button), but you can find all the DeDRM releases here:

https://github.com/apprenticeharper/DeDRM_tools/releases

Fortunately any installation of ADE 2.0.1 authorized with your Adobe ID will have the same key.  So wherever, however you're able to successfully get it working, you can import that key into the setup you actually want to keep using.

**Comment by nnnn6** [comment]
I will try your suggestions when I get a bit of time and report back. Should get the opportunity within 24 hours.

**Comment by ElleKayEm** [comment]
Good.  Thanks for the details on what worked.

**Comment by nnnn6** [comment]
The pleasure is all mine. I would not have doubled back down that path had you not suggested it. Thanks again.

Sent from ProtonMail mobile

-------- Original Message --------
