### ISSUE TITLE
Can't remove DRM with Calibre from a pdf I've just bought

### ISSUE THREAD

**Issue by eargiz** [apprenticeharper/DeDRM_tools#371]
I have a problem with the removal of DRM of a book I've just bought (I just want to work with the book I have paid for, and do some underlining!)
I bought the book in www.casadellibro.com, and the book is:
https://www.casadellibro.com/buscador/busquedaEbooks?lang=es&busqueda=VIVIENDA%20Y%20PROMOCION%20INMOBILIARIA%20EN%20ESPA%C3%91A.%20(EBOOK)&nivel=5&auto=1
I downloaded it with adobe digital editions, and then I added it to my library with Calibre, with the 6.5.4 version of the DeDRM installed (Calibre is instaled in a PC with Windows 10), but it still had DRM. 
I've deleted the book, and added it again to Calibre in "debug mode", and this is the log:

calibre Rexistro de depuración
calibre 3.6  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: gl
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Actualizador Biblioteca Papyrefb2 (2, 3, 0)
calibre 3.6  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: gl
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Actualizador Biblioteca Papyrefb2 (2, 3, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 91.745819398
Using calibre Qt style: True
Starting up...
Started up in 54.68 seconds with 7 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xcc\x81\xb0\xb8\xbf+\x82\x87\xa4\x94qT\x8a\x1fI\xf3\x85\x96\x14\xdar\xbad\xb7\xdf\xa9\xf4t\xff.\xa8\r', 'C:\\E-BOOKS\\Biblioteca pdf con DRM\\Vivienda y promoci\xc3\xb3n inmobiliaria en Espa\xc3\xb1a..pdf']
DeDRM v6.5.4: Trying to decrypt Vivienda y promociÃ³n inmobiliaria en EspaÃ±a..pdf
DeDRM v6.5.4: Vivienda y promociÃ³n inmobiliaria en EspaÃ±a..pdf is a PDF ebook
DeDRM v6.5.4: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.5.4: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 439, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 493, in PDFDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds.
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 342, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 115, in get_metadata
ValueError: Could not read info dict from PDF
Added Vivienda y promoción inmobiliaria en España. to db in: 0.2
Added 1 books in 2.1 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x063AE110>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x063AE170>> ignored

Thanks for any help!

**Comment by ElleKayEm** [comment]
Is Adobe Digital Editions authorized with your Adobe ID?  Is it installed on the same machine and user as calibre?  Is it version 2.0.1?

**Comment by eargiz** [comment]
Solved! You are right: I downloaded the pdf with DRM and tryed to DeDRM it with Calibre in diferent machines. I've just DeDRM  the fill in the same machine where I had downloaded it, and worked properly
Thanks a lot!

**Comment by ElleKayEm** [comment]
Great!  If you're all set, you can close the issue.
