### ISSUE TITLE
Calibre cannot convert an eBook in EPUB-Sifri format to Kindle

### ISSUE THREAD

**Issue by hanashiran** [apprenticeharper/DeDRM_tools#372]
Hi,
I installed the Apprentice Alf plugin for Calibre, but still Calibre cannot convert the eBook, which I purchased, and is in EPUB Sifri format, to Kindle.
Conversion error is below.
Thanks much for your help!
Hana

------------------------------------------------

Convert book 1 of 1 (2FIX sa habiitayanki 4 1702196529)
Conversion options changed from defaults:
  output_profile: 'kindle_voyage'
  read_metadata_from_opf: u'C:\\Users\\MAIN\\AppData\\Local\\Temp\\calibre_0ival4\\b94ei8.opf'
  verbose: 2
Resolved conversion options
calibre version: 3.7.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000178E46C0D30>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindleVoyageOutput object at 0x00000178E46EA470>,
 'page_breaks_before': u'/',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\MAIN\\AppData\\Local\\Temp\\calibre_0ival4\\b94ei8.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: EPUB Input running
on C:\Users\MAIN\AppData\Local\Temp\calibre_0ival4\wb36vg.epub
EPUB appears to be invalid ZIP file, trying a more forgiving ZIP parser
Traceback (most recent call last):
  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 240, in convert
  File "site-packages\calibre\utils\zipfile.py", line 766, in __init__
  File "site-packages\calibre\utils\zipfile.py", line 801, in _GetContents
  File "site-packages\calibre\utils\zipfile.py", line 816, in _RealGetContents
BadZipfile: File is not a zip file

Python function terminated unexpectedly
  Not a ZIP file (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 247, in convert
  File "site-packages\calibre\utils\localunzip.py", line 231, in extractall
  File "site-packages\calibre\utils\localunzip.py", line 218, in _extractall
ValueError: Not a ZIP file

**Comment by ElleKayEm** [comment]
First, DRM removal happens on import, not during conversion.  But more importantly, DeDRM supports removal of Adobe DRM and B&N's DRM from EPUBs.  It appears that these books have their own proprietary DRM which these tools won't be able to remove.
