### ISSUE TITLE
Can't remove DRM from EBook from Old Sony bookstore

### ISSUE THREAD

**Issue by Marc0368** [apprenticeharper/DeDRM_tools#373]
Hi,

I can't remove the Adobe DE DRM from this ebook that I purchased from the then existing Sony ebook store (now Kobo).

Thanks for the help.

Tool: DeDRM plugin for Calibre
OS: Windows 10
Calibre: V3.8 - 64bit
Book Origin: Sony ebook store

Calibre Debug Log:

calibre Debug log
calibre 3.8 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.8 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 94.1467181467 x 94.0740740741
Using calibre Qt style: True
Starting up...
Started up in 22.63 seconds with 1048 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x0c\xceX\x96\xe9\xd0\x88w>\xd8\xc55\xf0\xd8\x17od9\x8b\xfb\xdf\x93\x07\x93\x82\x9d\xa5\x9bN\x108\xc8', '\\\\diskstation\\Downloads\\READY\\Matterhorn-1.epub']
DeDRM v6.5.4: Trying to decrypt Matterhorn-1.epub
DeDRM v6.5.4: Verifying zip archive integrity
DeDRM v6.5.4: Matterhorn-1.epub is a secure Adobe Adept ePub
DeDRM v6.5.4: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
Found 1 keys
DeDRM v6.5.4: Trying a new default key
Could not decrypt g0s6e2.epub. Wrong key
DeDRM v6.5.4: Failed to decrypt with new default key after 0.2 seconds
DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 393, in ePubDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds.
Added Matterhorn to db in: 4.5
Added 1 books in 5.3 seconds

**Comment by ElleKayEm** [comment]
Can you read the book in Adobe Digital Editions?

**Comment by Marc0368** [comment]
Yes i can with the acsm file from kobo.

**Comment by ElleKayEm** [comment]
Forget about the old epub from Sony.  Import the new epub from Kobo that will be in the My Digital Editions folder.

**Comment by Marc0368** [comment]
Bingo. That did it.
Thanks a bunch!
