### ISSUE TITLE
security plugin required was not available

### ISSUE THREAD

**Issue by SJMar** [apprenticeharper/DeDRM_tools#374]
Hi, I am using windows OS and calibre 3.8 with python 2.7.17 and pycrypto 2.6
I am trying to remove DRM from a book I downloaded from class publishing. I would like to use it as a normal pdf instead of within the clunky program that it comes with (KORTEXT).
I am not sure if I have the required plugins. 

Here is the error message I get
calibre, version 3.8.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (UK Ambulance Services Clinical Practice Guidelines 2016)

Convert book 1 of 1 (UK Ambulance Services Clinical Practice Guidelines 2016)
Conversion options changed from defaults:
  output_profile: 'generic_eink'
  verbose: 2
  read_metadata_from_opf: u'C:\\Temp\\calibre_17jop8\\p87uf1.opf'
Resolved conversion options
calibre version: 3.8.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': None,
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000000000273CAC8>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_images': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000000000273CE48>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Liberation Mono',
 'pdf_mono_font_size': 16,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Liberation Sans',
 'pdf_serif_family': u'Liberation Serif',
 'pdf_standard_font': u'serif',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Temp\\calibre_17jop8\\p87uf1.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: PDF Input running
on C:\Temp\calibre_17jop8\vmumh_.pdf
Converting file to html...
Python function terminated unexpectedly
  pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\pdf_input.py", line 51, in convert
  File "site-packages\calibre\ebooks\pdf\pdftohtml.py", line 92, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

Thanks in advance

**Comment by ElleKayEm** [comment]
Are you able to read it in Adobe Digital Editions 2.0.1 authorized with an Adobe ID?

**Comment by SJMar** [comment]
Hi there,
Yes it opens straight away.
Is it still possible to create a normal PDF from there?
Regards
Sonja

**Comment by SJMar** [comment]
If I import an Adobe Digital Edition Key into the calibre DeDRM plugin will it remove the security do you think?

**Comment by ElleKayEm** [comment]
DeDRM should retrieve the key if ADE is located on the same machine and user as calibre.  Post a log from adding the book:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by SJMar** [comment]
calibre Debug log
calibre 3.8 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Obok DeDRM (6, 5, 4)
calibre 3.8 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 11.91 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xcc\x89Dl\xb8~I\xbb\x17\xd2\xca=H@\x9a\xa10f\x86\x9c3\x95w`$\xad\x87\xac\x1d\xd9\xff\xad', 'D:\\Users\\smaria\\Documents\\Kortext Documents\\UK Ambulance Services Clinical Practice Guidelines 2016 - Versio - Copy.pdf']
DeDRM v6.5.4: Trying to decrypt UK Ambulance Services Clinical Practice Guidelines 2016 - Versio - Copy.pdf
DeDRM v6.5.4: UK Ambulance Services Clinical Practice Guidelines 2016 - Versio - Copy.pdf is a PDF ebook
DeDRM v6.5.4: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v6.5.4: Trying a new default key
DeDRM v6.5.4: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 465, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2193, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1999, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1484, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1616, in initialize_ebx
ADEPTError: error decrypting book session key
DeDRM v6.5.4: Failed to decrypt with new default key after 0.1 seconds
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 493, in PDFDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 342, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 115, in get_metadata
ValueError: Could not read info dict from PDF
Added UK Ambulance Services Clinical Practice Guidelines 2016 - Versio to db in: 0.3
Added 1 books in 1.0 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x00000000057AB630>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x00000000057AB780>> ignored

**Comment by ElleKayEm** [comment]
Hmm, doesn't seem to like that key.  Are you sure ADE is the older version 2.0.1?

**Comment by SJMar** [comment]
Maybe not. I will double check when I get back to my computer and let you know.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by SJMar** [comment]
I uninstalled ADE 4.5 and installed Version 2.0.1
Now it doesn't open the document :(

**Comment by ElleKayEm** [comment]
I was afraid of that.  Sounds like they are using the newer version of Adobe DRM which can't be removed yet.  See this section of the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-registered-adobe-digital-editions-30-or-later-with-an-adobe-id-before-downloading-but-my-epub-or-pdf-still-has-drm
