### ISSUE TITLE
DRM Removal Failure on OSX

### ISSUE THREAD

**Issue by TrippOrTreat** [apprenticeharper/DeDRM_tools#375]
Installed calibre and the DeDRM plugin on OSX 10.12.6 and tried to import .AZW files to calibre. The DRM removal failed. I've tried the same with 3 different books, all have the same result. Here is the debug output with personal information removed.

calibre Debug log
calibre 3.8  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.8  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
Starting up...
Started up in 1.55 seconds with 2 books
DeDRM v6.5.4: Trying to decrypt B0716xxxx3_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 264
Decrypting Mobipocket 4 ebook: Text Book Name
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/xxx/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '29xxxxbbb205' and UserName 'xxx'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 264
Decrypting Mobipocket 4 ebook: Text Book Name
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds
Added Text Book Name to db in: 0.1
Added 1 books in 1.0 seconds

**Comment by ElleKayEm** [comment]
As the log says:  Cannot decode library or rented ebooks.

**Comment by ElleKayEm** [comment]
Then download fresh copies.  It should work after you've purchased.
