### ISSUE TITLE
deDRM fails to install on Windows7 32-bit Calibre-3.7. Tried both 6.5.4 and 6.4.3

### ISSUE THREAD

**Issue by Richard092345** [apprenticeharper/DeDRM_tools#376]
The message I get from the Windows is,

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	calibre-file-dialog.exe
  Application Version:	3.7.0.0
  Application Timestamp:	599fa21d
  Fault Module Name:	QuickTime.qts_unloaded
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	4e13ba08
  Exception Code:	c0000005
  Exception Offset:	5c49a9e9
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e37

I have installed deDRM successfully before on that PC, but this time I needed to start from scratch since the SSD failed and I had to reinstall the original hard disk.

**Comment by ElleKayEm** [comment]
Shouldn't be a problem.  Unzip the file.  Look in the DeDRM calibre plugin folder for the zip to load.

**Comment by Richard092345** [comment]
Thanks. That's what I did and I got the above message.  Then I installed Calibre-2.85.1 on another otherwise identical tabletPC and the latest deDRM works fine with 2.85.1.  I will try with Calibre-3.7 again.

**Comment by ElleKayEm** [comment]
Hmmm, I can't duplicate the problem.  Just tried on Windows 7 (64-bit) with calibre 3.8 (32-bit) and DeDRM 6.5.4.

**Comment by Richard092345** [comment]
My tabletPC's are older 32-bit machines running Windows 7 Pro (32-bit). That may be the factor.  I am marking the thread "Closed" since it appears to be an issue specific to an older system and I now have a workaround: use Calibre-2.85.1 instead of 3.8.

Thanks.
