### ISSUE TITLE
Kindle DeDRM (Windows) failed

### ISSUE THREAD

**Issue by omnicaritas** [apprenticeharper/DeDRM_tools#377]
searching for kinfoFiles in C:\Users\Office\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Office\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1828019639' and UserName '4f6666696365'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: A Course in Miracles: Complete and Annotated Edition
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds
Added A Course in Miracles: Complete and Annotated Edition to db in: 2.5
Added 1 books in 3.5 seconds
DeviceJob: set_books_in_library: books to process= 66
DeviceJob: set_books_in_library finished: time= 0.0160000324249
Job: 5 View book on device started
DeviceJob: 5 View book on device done, calling callback
DeviceJob: 5 View book on device callback returned
Worker Launch took: 0.166000127792
Job: 5 View book on device finished
No details available.

**Comment by ElleKayEm** [comment]
The beginning of the log is missing.  Is the book from an E-ink Kindle?  If so, then enter its serial number into the plugin customization.

**Comment by omnicaritas** [comment]
Ah. My bad. Adding the serial sorted it.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
