### ISSUE TITLE
DRM removal failure

### ISSUE THREAD

**Issue by trustingHim** [apprenticeharper/DeDRM_tools#378]
I started using this plugin in calibre when it was the only one that would deDRM my kindle books. It recently stopped working, though. The last 2-3 updates refuse to remove the DRM. Other sites have noted that there's a new DRM in place that other codes can't remove. On the off chance it's a bug in my system, the debug log for calibre is below. I imported the file and tried to convert it before generating the log. I'm not the greatest at reading these logs, though. Can anyone find what's going on besides "the DRM is too strong for this software"? Thanks

calibre Debug log
calibre 2.70  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 4) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 1) && Obok DeDRM (6, 5, 4)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 5.02 seconds with 37 books
DeDRM v6.5.4: Trying to decrypt Mark of Fire (The Endarian Prophecy Book 1).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Mark of Fire (The Endarian Prophecy Book 1)
Found 6 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Whitney\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Whitney\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3966465638' and UserName '576869746e6579'
DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 161, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds
Added Mark of Fire (The Endarian Prophecy Book 1) to db in: 2.1
Added 1 books in 3.0 seconds
Worker Launch took: 0.43499994278
Job: 1 Convert book 1 of 1 (Mark of Fire (The Endarian Prophecy Book 1)) finished
Convert book 1 of 1 (Mark of Fire (The Endarian Prophecy Book 1))
	Resolved conversion options
	calibre version: 2.70.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Whitney\\AppData\\Local\\Temp\\calibre_cknw3m\\rbtjoo.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x04A66FF0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'old_pdf_engine': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x04955210>,
	 'override_profile_size': False,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier New',
	 'pdf_mono_font_size': 16,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'MS Shell Dlg 2',
	 'pdf_serif_family': u'Times New Roman',
	 'pdf_standard_font': u'serif',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Whitney\\AppData\\Local\\Temp\\calibre_cknw3m\\juc5f3.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Whitney\AppData\Local\Temp\calibre_cknw3m\0gde_j.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Mark of Fire (The Endarian Prophecy Book 1) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1064, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 146, in check_for_drm
	calibre.ebooks.DRMError: Mark of Fire (The Endarian Prophecy Book 1)

**Comment by ElleKayEm** [comment]
If the book is from an E-ink Kindle, then you need to put its serial number into the plugin customization.

**Comment by trustingHim** [comment]
it's a Kindle Voyage...
i tried it anyway, and it worked. thank you!

**Comment by ElleKayEm** [comment]
That's an E-ink Kindle.  If you're all set, you can close the issue.

**Comment by ElleKayEm** [comment]
By the way, you can remove the old K4PC, K4Mac, Kindle Mobi and Topaz DeDRM plugin.

**Comment by Slowly** [comment]
...If it's NOT E-ink Kindle - if it's Amazon Kindle 1.19+ for Mac - then unfortunately, yes, the DRM is still too strong for this or any software...until they finally break it...

**Comment by ElleKayEm** [comment]
If you don't have an E-ink Kindle, you can use method 1 or 2 in this post to avoid KFX files:

https://www.mobileread.com/forums/showthread.php?t=283371

The new format and its DRM have been figured out.  The code is here, but hasn't been integrated into the tools yet.  In most cases, you're probably better off sticking with the old format though.

**Comment by Slowly** [comment]
Yes, I'll be waiting until the new code is in the DeDRM tool.


John Bonifas

MS Applied Geospatial Sciences Candidate

Department of Geography, Planning, and Recreation

School of Social and Behavioral Sciences

Northern Arizona University


________________________________
