### ISSUE TITLE
Kindle macOS dedrm removal error

### ISSUE THREAD

**Issue by AndreassaerdnA** [apprenticeharper/DeDRM_tools#379]
Hello!
I used dedrm tools in calibre for a long time, always the same way. Since yesterday this way don´t work anymore and I am wondering about the why?
I of course cheched for updates, but the latest version didn´t change anything. I also tryed the standalone and got the same result:
log from standalone:

There is 1 ebook to be decrypted.
Processing file: B011C6SRV4_EBOK.azw
There was an error with 1 ebook:
#One:Librarys:Kindle:My Kindle Content:B011C6SRV4_EBOK:B011C6SRV4_EBOK.azw is neither a Kindle not a Mobipocket file.

There is 1 ebook to be decrypted.
Processing file: B011C6SRV4_EBOK.azw
There was an error with 1 ebook:
#One:Librarys:Kindle:My Kindle Content:B011C6SRV4_EBOK:B011C6SRV4_EBOK.azw is neither a Kindle not a Mobipocket file.

Thanks for your help!
Andreas

**Comment by ElleKayEm** [comment]
Probably a kfx file.  See the FAQs:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac
