### ISSUE TITLE
DRM Removal Failure: Book Downloaded Via Nook for Windows

### ISSUE THREAD

**Issue by GanbareGinkun** [apprenticeharper/DeDRM_tools#380]
I am unable to decrypt a book that I purchased from Barnes & Noble despite correctly configuring the DeDrm plug-in for Calibre and my Nook Decryption Key and decrypting a number of other books successfully. This is the only book from either B&N or Amazon.com that I have been unable to decrypt thus far. Here is the log that is generated by Calibre whenever I try to do so:

calibre Debug log
calibre 3.9 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.9 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
Starting up...
Started up in 8.72 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x08\xd1\xbc\xd3[q\\\xde\xd6\xa0f\xbd\x90`\xad\xa0QexU\x13\xdf\xeb\xefc@0\xe7O\x1eS\x02', 'C:\\Users\\Retsupurae\\AppData\\Local\\Packages\\BarnesNoble.Nook_ahnzqzva31enc\\LocalState\\9781401236311.epub']
DeDRM v6.5.4: Trying to decrypt 9781401236311.epub
DeDRM v6.5.4: Verifying zip archive integrity
DeDRM v6.5.4: “9781401236311.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 398, in ePubDecrypt
DeDRMError: DeDRM v6.5.4: Couldn't decrypt after 0.7 seconds. DRM free perhaps?
Added V for Vendetta {New Edition} to db in: 0.8
Added 1 books in 2.5 seconds
Worker Launch took: 0.174000024796

Please note that the file in question is *definitely* copy-protected - it cannot be opened with any e-reader outside of Nook for Windows. Possible that it is locked down by another DRM format and then "wrapped up" in an EPUB container?

**Comment by thejarett** [comment]
I'm having this exact same problem.

**Comment by ElleKayEm** [comment]
It's a comic downloaded with the Windows 10 Nook app, right?  A part of the DRM is stored outside the book inside a database.  That's why the tools can't tell it's a Nookbook.  You can find the missing info, put it back in the epub, and remove the DRM.  But even then, it doesn't work in other readers.  Possibly it would with some editing.

**Comment by lopesta** [comment]
man .. the file you are trying to decode is already free-drm so you obiouvsly can read anywhere without the need to decrypt it ..

again .. its free from drm .. came drm free source .. don't decode ..just open it as its on another readers and see .

**Comment by ElleKayEm** [comment]
No, it's not DRM-free.  Just has part of the DRM stored outside the epub.
