### ISSUE TITLE
It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by JimRPh** [apprenticeharper/DeDRM_tools#381]
calibre, version 3.8.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/Users/Jim/Downloads/DeDRM_tools_6.5.4 (2).zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.8  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 461, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 60, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 192, in load
  File "site-packages/calibre/customize/zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'/Users/Jim/Downloads/DeDRM_tools_6.5.4 (2).zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're trying to load the whole archive.  Unzip it and look in the DeDRM calibre plugin folder.

**Comment by Slowly** [comment]
@ElleKayEm ...but it *does* contain the __init__.py file:
<img width="600" alt="untitled" src="https://user-images.githubusercontent.com/119132/34114410-f575b36c-e3cf-11e7-84b0-3ab8af13d990.png">

**Comment by ElleKayEm** [comment]
@Slowly
Not if you're loading the wrong file as the OP was.

**Comment by Slowly** [comment]
...I am a tech with years of experience. I tried disabling the renderer, re-downloading, fixing the latest vrrsion of deDRM...no luck, its just too tough a crack right now. Will have to wait till thr north koreans crack it lol



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by ElleKayEm** [comment]
No idea why you're having a problem.

**Comment by Slowly** [comment]
[shrug]



Sent from my Verizon 4G LTE smartphone


-------- Original message --------
