### ISSUE TITLE
DeDRM v6.5.4: Failed to decrypt with error: No key found in 2 keys tried.(windows10 64bit)

### ISSUE THREAD

**Issue by BOBOKKAA** [apprenticeharper/DeDRM_tools#382]
This plugin worked on my desktop PC successfully，but  failed on my laptop. 
I don't know why. SAD........
The complicated Chinese word in the text is garbled. Never mind that.  

calibre 调试日志
calibre 3.9  embedded-python: True is64bit: False
Windows-10-10.0.14393-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.9  embedded-python: True is64bit: False
Windows-10-10.0.14393-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.684210526 x 133.684210526
Using calibre Qt style: True
Starting up...
Started up in 28.27 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xd6\x1e\x18\xbf\xbc\xa3A\xa82\xd0n#\x1d\xe8\x81\xf1\x0f\x07\xdd\xba\x82C\x16\x0c\xc1\x9db\x0fi\t\x91\xeb', 'C:\\Users\\yang\\Documents\\My Kindle Content\\B00UFDW0HS_EBOK\\B00UFDW0HS_EBOK.azw']
DeDRM v6.5.4: Trying to decrypt B00UFDW0HS_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright 漏 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: 璐у竵閲戣瀺瀛︼紙鍘熶功绗?鐗堬級 (鍗庣珷鏁欐潗缁忓吀璇戜笡)
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\yang\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\yang\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2860546749' and UserName '0be5'
DeDRM v6.5.4: Found 1 new key

MobiDeDrm v0.41.
Copyright 漏 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: 璐у竵閲戣瀺瀛︼紙鍘熶功绗?鐗堬級 (鍗庣珷鏁欐潗缁忓吀璇戜笡)
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added 货币金融学（原书第2版） (华章教材经典译丛) to db in: 0.3
Added 1 books in 1.2 seconds
Worker Launch took: 0.12900018692

**Comment by ElleKayEm** [comment]
Looks like it might be KFX format.  See the FAQs here:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by BOBOKKAA** [comment]
I install kindle for Windows 1.17. Still not work. The same problem, and I find the book's format is AZW, not KFX.

**Comment by ElleKayEm** [comment]
Did you delete and redownload the book after installing K4PC 1.17 and unchecking auto-update?  A book with the AZW extension can still be KFX format.  All book files downloaded by K4PC have that extension regardless of which format.  The fact that it's inside its own folder makes me suspect it is.

**Comment by BOBOKKAA** [comment]
I'm pretty sure i did what you said ,many times. It still not work. Probably not this reason.
calibre 调试日志
calibre 3.9 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.9 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.684210526 x 133.684210526
Using calibre Qt style: True
Starting up...
Using proxies: {'ftp': '127.0.0.1:1080', 'https': '127.0.0.1:1080', 'http': '127.0.0.1:1080'}
Using proxies: {'ftp': '127.0.0.1:1080', 'https': '127.0.0.1:1080', 'http': '127.0.0.1:1080'}
Started up in 5.52 seconds with 0 books
DeDRM v6.5.4: Trying to decrypt B00A72W7PC_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright 漏 2008-2012 The Dark Reverser et al.
MOBI header version 5, header length 248
Extra Data Flags: 1
Decrypting Mobipocket 5 ebook: Symbolic Logic (鍏嶈垂鍏増涔?
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\yang\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\yang\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2860546749' and UserName '0be5'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright 漏 2008-2012 The Dark Reverser et al.
MOBI header version 5, header length 248
Extra Data Flags: 1
Decrypting Mobipocket 5 ebook: Symbolic Logic (鍏嶈垂鍏増涔?
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Symbolic Logic (免费公版书) to db in: 0.3
Added 1 books in 1.2 seconds
Worker Launch took: 0.114000082016

**Comment by ElleKayEm** [comment]
Ok, it looks like it's a problem with your Windows user name.  The file path is showing yang, but the Kindle key was decrypted with a user name which I'm guessing are two Chinese characters.  Did you change your Windows user name?  You could try setting up an entirely new Windows user and setting everything up there.

**Comment by BOBOKKAA** [comment]
I am wondering where you can see the user name. In this sentence？"Decrypted key file using IDString '2860546749' and UserName '0be5'"。0be5 are not  chinese  characters and definitely not my user name. Actually my user name IS in Chinese. I think that is the problem. I am trying to fix it. Thanks a lot.

**Comment by ElleKayEm** [comment]
'0be5' is your user name in hex.

**Comment by BOBOKKAA** [comment]
Problem solved. Chinese user name is the reason. Thank you very much.

**Comment by apprenticeharper** [comment]
Please try again with the just-released v6.5.5 which should fix the error with non-ASCII user names.
