### ISSUE TITLE
No DRM with Kindle

### ISSUE THREAD

**Issue by whttkr** [apprenticeharper/DeDRM_tools#384]
Reinstalled Calibre 3.7 after hardware change. Intalled DeDRM according to instructions and input the Kidnle serial number. No joy. Below is log from Calibre debug mode. Your help will be greatly appreciated.

calibre Debug log
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.5388994307 x 92.3636363636
Using calibre Qt style: True
Starting up...
Started up in 8.57 seconds with 2125 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xa6[r\xc5W\xc8\x16N\xcc \x84j\xc5\x14a\x9e\x0cGVp\x97\xf8\xb5\xfe\xdc%h=\xb1\xbf\xa7O', 'D:\\Kindle files\\Incoming\\The One - John Marrs.azw3']
DeDRM v6.5.4: Trying to decrypt The One - John Marrs.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The One
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\James Whittaker\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.4: Ultimately failed to decrypt after 0.0 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.0 seconds
Added The One to db in: 0.1
Added 1 books in 0.5 seconds

**Comment by ElleKayEm** [comment]
It's an E-ink Kindle?  You entered the serial number in the Eink Kindle section of the plugin?  Make sure you have the serial number correct by copy and pasting it from the website removing spaces.

**Comment by whttkr** [comment]
ElleKayEm commented 

> It's an E-ink Kindle? You entered the serial number in the Eink Kindle section of the plugin? Make sure you have the serial number correct by copy and pasting it from the website removing spaces.

Yes to all of these, except that the Kindle serial numbers were already present when I reinstalled DeDRM . I checked they were correct from the Kindle's own Device Info link. But your suggestion made me think to delete and re-enter the numbers. DeDRM now works. Thank you.

**Comment by ElleKayEm** [comment]
Sounds like you're all set.  Did you mean to reopen this?
