### ISSUE TITLE
Barnes & Noble Retrieve Key No Longer Works

### ISSUE THREAD

**Issue by LeeThompson** [apprenticeharper/DeDRM_tools#385]
I suspect B&N has changed the API that the script uses.

The error "Could not retrieve key. Check username, password and internet connection and try again." pops up.

**Comment by ElleKayEm** [comment]
Still working for me.

**Comment by apprenticeharper** [comment]
Have you ever logged in with Nook for PC? You might need to log in at least once with Nook for PC for the key retrieval to work.

**Comment by LeeThompson** [comment]
Yes, but even it (Nook for PC) won't let me download encrypted books, I get a download error complaining about no payment information on Barnes & Noble's site (even though there is one).    I had assumed it was because the app isn't supported anymore.

**Comment by ElleKayEm** [comment]
Try making sure your credit card is up-to-date and marked as default.  Even though Nook for PC isn't officially supported, it still works.

**Comment by LeeThompson** [comment]
It is, I even removed the card and re-added it.  No change.

**Comment by ElleKayEm** [comment]
Ah, good!  I was going to suggest trying to "buy" a freebie to see if that might do it.  But if all's good, you can close the issue.

**Comment by yulivuviki** [comment]
try downloading the title(s) on all apps  .. i think sometimes some ebooks only download on new editions of BN apps .

**Comment by ElleKayEm** [comment]
As far as I know, if you can't download it with Nook for PC, then you can't remove the DRM.

**Comment by SpareSimian** [comment]
It would be useful to dump the returned web page from the server into a file where it can be examined postmortem. I'm not a Python coder but I'll see if I can figure out how to do that based on the snippets in all the scripts. (I figure it should get dumped into a file under APPDATA, just before the hash is extracted into the found variable.)

**Comment by SpareSimian** [comment]
Based on LeeThompson's comment, I found I had an expired CC in addition to my default one. I removed the expired one from my account and restarted Nook for PC and was able to retrieve the book. I was also able to run the Retrieve Key funtion in the Calibre plugin, but the resulting download was not unlocked.  So the web part can be confused by having a dead CC in one's account.
