### ISSUE TITLE
DeDRM failed for kindle book 

### ISSUE THREAD

**Issue by bucomist** [apprenticeharper/DeDRM_tools#387]
The book was downloaded from Amazon website
calibre Debug log
calibre 2.43  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 6.58 seconds with 14 books
DeDRM v6.5.4: Trying to decrypt Misbehaving- The Making of Behavioral Economics.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Misbehaving: The Making of Behavioral Economics
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Rodman\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Rodman\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4177083684' and UserName '526f646d616e'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Misbehaving: The Making of Behavioral Economics
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds
Added Misbehaving: The Making of Behavioral Economics to db in: 0.4
Added 1 books in 1.5 seconds
Worker Launch took: 0.18499994278

**Comment by ElleKayEm** [comment]
If the Kindle it was associated with was an E-ink Kindle, then you need to put its serial number into the plugin customization.

(Not related to the issue, but you're using a really old version of calibre.  Also, it's the 32-bit on a 64-bit computer.)
