### ISSUE TITLE
Free Drm Ebooks BN Error & another Trouble

### ISSUE THREAD

**Issue by yulivuviki** [apprenticeharper/DeDRM_tools#390]
i am using PC nook-study old version as suggested + (key retrieval using account email and pass) or (key retrieve by keygen noble NAME and CC#) .. decrypt many titles successfully but i have two common issues i think with other people facing them :

(Problem 1):
while decrypting multiple epubs (2 FreeDRM+4 DRMED titles) from nookstudy on "DeDRM_Windows_Application) the Application only decode the encoded files which is the 4 and exit without notifying me there is fail or explanation that there is free drm notice which i feel important .
so after all of this i had to try open the 2 FREEDRM books to see if they are opening . and then copy them by comparing the 6 total ebooks on both folders (the directory of drm BN source ENCODED) with the folder that contains the 4 DECODED .. the application skipp the free which need your recommendation to what to do ?? i think the application should behave like this : 
if it find any title that is free from drm should announce that with failure and which files suspect its free from drm title .. so the user be less picky and saves his time ..

(Problem 2):
still regarding BN .. some rare titles if tried to download using NOOK STUDY the old version which is not recommended by BN .. some titles do not be accepted to download on to it "error 2138 this title is currently not available for download for this application" .. and need to be downloaded by WINDOWS 10 APP newer. and i did so .. to find its PDF but still encrypted .. tried both
Adobe retrieve key and Barnes tools without success ..

any suggestion how to decode the secure PDF which reside in C:\Users\OS\AppData\Local\Packages\BarnesNoble.Nook_ahnzqzva31enc\LocalState
![2138](https://user-images.githubusercontent.com/32941133/31863772-3c37903c-b75b-11e7-8b5b-9f6c60dfc461.jpg)

![secure pdf bn](https://user-images.githubusercontent.com/32941133/31863835-f7217c82-b75b-11e7-9836-ed212ae560b4.jpg)

i think its using some of its own decryption scheme .

Thank you for helping me reading my stuff freely

**Comment by ElleKayEm** [comment]
The tools only work on B&N epubs, not PDFs.

**Comment by yulivuviki** [comment]
so what about the free eoub issue ?? and isn't there a workaround to decode the barnes PDF ?
i was downloading eTextbooks and decrypting them before .. before 3 years .. what happened ?

**Comment by apprenticeharper** [comment]
The tools have never handle B&N PDFs.

I'm surprised that DRM-free ePubs from B&N caused a problem. Post an import log in a new issue.
