### ISSUE TITLE
DRM not removed

### ISSUE THREAD

**Issue by Mesaja** [apprenticeharper/DeDRM_tools#391]
Hi!  I had DeDRM in the past and it worked great.  I installed it again on this PC and it won't remove the DRM from this book.  I downloaded it directly from Amazon's web site.

The target Kindle reader is the Kindle for Android.

Here is the log:

calibre Debug log
calibre 3.10 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && Find Duplicates (1, 6, 3)
calibre 3.10 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && Find Duplicates (1, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 88.6690909091 x 89.6470588235
Using calibre Qt style: True
Starting up...
Started up in 5.17 seconds with 3475 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['u\xf3% \xd2>Z\x1f\xdaJ\xfd\x81\xb2J\xa3\xaaH\xe5~\xae\xcb\xedI\xbf\x90\xae\xe6k\xd0rj\xbd', 'C:\\Users\\vick_\\Desktop\\En as-tu vraiment besoin - (French Edition).azw3']
DeDRM v6.5.5: Trying to decrypt En as-tu vraiment besoin - (French Edition).azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: En as-tu vraiment besoin ? (French Edition)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\vick_\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added En as-tu vraiment besoin ? (French Edition) to db in: 1.6
Added 1 books in 2.3 seconds

**Comment by ElleKayEm** [comment]
You can only decrypt Kindle books downloaded from the website if you associate them with an E-ink Kindle (not a Fire).  And you need to enter its serial number into the plugin customization.  Otherwise, install Kindle for PC 1.17 on this computer and download your books with that.  See the FAQs for a link to the installation file:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by opooyo** [comment]
Ya me too.

Lately I stripped DRM from few files in Marketing Books. I've using DRM removal for 4-5 books and it work perfectly. But the latest e-book i encountered was unsucessfully  DRM-removed. The book was this 

[https://archive.org/details/marketingprincip00assa]

and i've tried download the epub version, pdf (not from Adobe digital Edition) and still failed.
Thank you~


This is the log
==

calibre Debug log
calibre 2.75.1 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 5)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9842323651 x 71.9822878229
Starting up...
Loaded cached store plugin for: Amazon IN Kindle at version: 5
Loaded cached store plugin for: eBook.nl at version: 2
Loaded cached store plugin for: Amazon IT Kindle at version: 15
Loaded cached store plugin for: Amazon ES Kindle at version: 15
Loaded cached store plugin for: Smashwords at version: 5
Loaded cached store plugin for: Amazon CA Kindle at version: 7
Loaded cached store plugin for: Google Books at version: 4
Loaded cached store plugin for: Amazon UK Kindle at version: 15
Loaded cached store plugin for: Publio at version: 7
Loaded cached store plugin for: Kobo at version: 7
Loaded cached store plugin for: Baen Ebooks at version: 2
Loaded cached store plugin for: Amazon Kindle at version: 14
Loaded cached store plugin for: Virtualo at version: 9
Loaded cached store plugin for: Amazon DE Kindle at version: 15
Loaded cached store plugin for: eBooks.com at version: 3
Loaded cached store plugin for: Amazon AU Kindle at version: 5
Loaded cached store plugin for: Amazon FR Kindle at version: 15
Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')]}
Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2416)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x000000000439E438>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 873, in open
  File "site-packages\calibre\devices\usbms\device.py", line 280, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Started up in 15.19 seconds with 3 books
Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')]}
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xb0\xcb\xc9\xdf\xc4s\x82\x94p\xa6\x8b\xe2~\x9c\xdf\xed\x8fL\xc4$\x05\xb3\xec\x80\xd19\x06]pb\xfaw', 'C:\\Users\\ortho\\Downloads\\marketingprincip00assa_encrypted.epub']
DeDRM v6.5.5: Trying to decrypt marketingprincip00assa_encrypted.epub
DeDRM v6.5.5: Verifying zip archive integrity
DeDRM v6.5.5: “marketingprincip00assa_encrypted.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 629, in run
  File "calibre_plugins.dedrm.__init__", line 405, in ePubDecrypt
DeDRMError: DeDRM v6.5.5: Couldn't decrypt after 0.3 seconds. DRM free perhaps?
Added 0 books in 1.5 seconds
Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2416)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x000000000439E438>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 873, in open
  File "site-packages\calibre\devices\usbms\device.py", line 280, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')]}
Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2416)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x000000000439E438>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 873, in open
  File "site-packages\calibre\devices\usbms\device.py", line 280, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')]}
Worker Launch took: 0.174000024796
Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2416)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x000000000439E438>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 873, in open
  File "site-packages\calibre\devices\usbms\device.py", line 280, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Job: 1 Convert book 1 of 1 (Marketing : principles & strategy) finished
Convert book 1 of 1 (Marketing : principles & strategy)
	Resolved conversion options
	calibre version: 2.75.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000000002773FD0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'old_pdf_engine': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000000000277D390>,
	 'override_profile_size': False,
	 'page_breaks_before': u'/',
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier New',
	 'pdf_mono_font_size': 16,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'MS Shell Dlg 2',
	 'pdf_serif_family': u'Times New Roman',
	 'pdf_standard_font': u'serif',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\ortho\\AppData\\Local\\Temp\\calibre_y3ew7z\\cns0eo.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\ortho\AppData\Local\Temp\calibre_y3ew7z\s7nqje.epub
	Python function terminated unexpectedly
	  s7nqje.epub (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1064, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 259, in convert
	calibre.ebooks.DRMError: s7nqje.epub

Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')]}
Storage number map:
{(7L, 0L): [(1L, 'C'), (2L, 'D')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2416)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x000000000439E438>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 873, in open
  File "site-packages\calibre\devices\usbms\device.py", line 280, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...

**Comment by ElleKayEm** [comment]
@opooyo
This is completely unrelated to the original issue.  And these tools are for books you own, not books on loan.

**Comment by opooyo** [comment]
@ElleKayEm

Hallo Elle, good evening..
First I'd like to apologize if my comment before was out of topic. Truthfully, IDK that DRM removal on Calibre just for the books that i own. I must say that my 4-5 previous books were books that i got from loan. Even exactly the same site with my previous comment. So i feel confuse, how can i remove drm for my previous books that all were  loaned.

Thank you.
