### ISSUE TITLE
Unable to remove DRM

### ISSUE THREAD

**Issue by wastedbreath** [apprenticeharper/DeDRM_tools#392]
Hello. Thanks for taking the time to look over this. The ebook that I have was downloaded from Google Books and is in a .acsm format which was obtained by telling Google Books that I wanted to download the file as a .pdf. I am using a Kindle Fire. I even tried adding my Kindle Fire's serial number as a Kindle eInk at one point just to see if that might be the issue, but that didn't work either, so I removed the serial number. Here is my log:

calibre Debug log
calibre 3.10 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.10 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Using calibre Qt style: True
Starting up...
Started up in 5.03 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x0f+I\xf0z\x85 \x8b\x83\x8b\xbb\x11C\x9e\\\x12\xef\xba\xafSM\xf0\x024\xe3e:}F-\xaci', 'C:\\Users\\Zaphod Beeblebrox\\Downloads\\Introduction_to_Leadership-pdf.acsm']
Added Introduction to Leadership-pdf to db in: 1.7
Added 1 books in 2.2 seconds

**Comment by ElleKayEm** [comment]
Download Adobe Digital Editions 2.0.1 (strongly recommended to use that specific version).  Install it on the PC and Windows user where you have calibre.  Authorize it with an Adobe ID (create one if you don't already have one).  Open the .acsm file with Adobe Digital Editions.  A PDF of your book will be downloaded to the Digital Editions folder in your Documents folder.  Add that to calibre.

**Comment by wastedbreath** [comment]
Thank you so much! That did the trick! I was loading the original file instead of the ADE version.
