### ISSUE TITLE
Calibre's doesn't preserve text tables and page format

### ISSUE THREAD

**Issue by fabionar** [apprenticeharper/DeDRM_tools#393]
I've already tried everything, from the 0 margin, disable font scaling, preserve cover aspect ratio, 0% line height, 0 insert between paragraphs, 0 unwrapping. But all I want is to simply remove drm, using calibre or dedrmtools-exe isn't working.

I know this might be a calibre problem, but since this software is all about this, can anyone share a light on the config to keep original pages?

**Comment by ElleKayEm** [comment]
I'd ask about conversion issues over in the calibre forum at MobileRead.
