### ISSUE TITLE
FAQ download links for Kindle for PC and Kindle for mac are broken

### ISSUE THREAD

**Issue by falke100** [apprenticeharper/DeDRM_tools#396]
The links in FAQs.md for the 1.17 versions of the kindle software are broken, "access denied" from s3. 

Maybe add checksums for known-good versions of the installers to the doc, so we can trust alternate downloads if we find them somewhere else?

**Comment by ElleKayEm** [comment]
Checksums are available here:
https://www.mobileread.com/forums/showthread.php?t=283371

Or you can use method 2 at that link with the current version of Kindle for PC/Mac.
