### ISSUE TITLE
DRM not being removed from Nook books

### ISSUE THREAD

**Issue by Hex008** [apprenticeharper/DeDRM_tools#397]
In the past I would use Calibre with the DeDRM plugin and easily remove the DRM from my purchased Nook books but it no longer is working. I have installed the latest version of Calibre (3.12) and DeDRM (6.5.5). I drag the eBook I want to remove the DRM from to Calibre and then try to open it using Calibre but I get  a message that it can't be opened because of DRM. I do not know how to retrieve logs to post so if they are needed I would be happy to do so if I can get instructions.

Thanks.

**Comment by ElleKayEm** [comment]
Have you put your B&N account email and password into the plugin customization?

**Comment by Hex008** [comment]
I am an idiot. That did it. Thanks

**Comment by ElleKayEm** [comment]
No problem.  If you're all set, you can close the issue.
