### ISSUE TITLE
DeDRM Not Working?

### ISSUE THREAD

**Issue by heartxofxmine** [apprenticeharper/DeDRM_tools#398]
Hi there, I went through the instructions of Installing Calibre, and then installing your tool here. I went to my books on amazon.com, selected "Download for Transfer via USB" so I could get a copy of the file onto my computer. It asked which device I would want to send it to, and I selected the device that I added the serial number key to on the DRM preferences - it is an older Kindle Fire. I had added it under eInk Kindle Readers. The file was of the .azw3 format. I open up Calibre, add the file, it properly adds it. But when I try to convert it to .mobi or PDF, it says the book still has the DRM.

Running this on a Windows 10 machine, using deDRM 6.5.5.
Attached is the output code from running it in debug mode

(Went and downloaded Kindle for PC just in case. You say it adds that key automatically? Had a default_key generate when I went to add under the Kindle for PC. Still did not seem to work)

[tmpj3wu5a.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1483345/tmpj3wu5a.txt)

**Comment by ElleKayEm** [comment]
DeDRMing books downloaded "for transfer via USB" only works with E-ink Kindles (like the Paperwhite), not the Fires.

For Kindle for PC, make sure to avoid the newer KFX format using method 1 or 2 in this post:
https://www.mobileread.com/forums/showthread.php?t=283371
