### ISSUE TITLE
Problem importing book

### ISSUE THREAD

**Issue by amf0** [apprenticeharper/DeDRM_tools#399]
I tried to import an .azw file into Calibre, but it didn't work. I am running Calibre on Linux Mint 18 Sarah. The file originally comes from a Kindle Paperwhite. I installed the Calibre plug-in and gave the serial number for the Kindle, but the file still has DRM. Here's the debug log. [tmpANEizx.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1485400/tmpANEizx.txt)

Any help would be greatly appreciated!

**Comment by ElleKayEm** [comment]
Double-check you have the serial number correct and in the E-ink Kindle section.  Easiest way is to copy and paste from the website (removing spaces).

**Comment by amf0** [comment]
Thank you for the reply. I double-checked the serial number, but it's right. Any other ideas?

**Comment by ElleKayEm** [comment]
Is this a built-in dictionary?  Because those can't be DeDRMed.

**Comment by amf0** [comment]
Okay, yes it is. Too bad :(

**Comment by ElleKayEm** [comment]
If that's the only problem, then you can close the issue.
