### ISSUE TITLE
Calibre 2.22 plug-in: install issue - SORTED -

### ISSUE THREAD

**Issue by Tarpal** [apprenticeharper/DeDRM_tools#4]
--- The plug-in got finally installed ---
More .ZIP files found in the DeDRM_tools packet (in itself already a ZIP) than previously expected needed to be un-zipped first. Contributing to the initial failure was the fact that Calibre's plug-ins apparently have the file extension... .ZIP. (...).

Anyway, it's sorted now but I thought it might be worth do leave this (now non-issue) entry published here in case other users run into the same issue. Maybe the ReadMe.txt could add a line to tackle this ZIP-confusion-matter? 

--------- Original entry -----------------------------------
Tried to integrate the DRM plug-in into Calibre 2.22 (64bit), running under Win7, as described in <DeDRM_plugin_ReadMe.txt> and later in various creative ways but keep getting an error message:

calibre, version 2.22.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:/Users/user/Downloads/DRM Tools/calibre plugin/alfcrypto_src.zip' is invalid. It does not contain a top-level __init__.py file

calibre 2.22 [64bit]  isfrozen: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 388, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 53, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 188, in load
  File "site-packages\calibre\customize\zipplugin.py", line 286, in _locate_code
InvalidPlugin: The plugin in u'C:/Users/user/Downloads/DRM Tools/calibre plugin/alfcrypto_src.zip' is invalid. It does not contain a top-level __init__.py file

Any suggestion on how to remedy this? Could I be doing something wrong? Could the ReadMe.txt be somewhere more clear? Any help is appreciated.

**Comment by ElleKayEm** [comment]
I'm confused about your confusion.  You only unzip the outer-most archive.  Then the zip file you load into calibre is the one inside the DeDRM_calibre_plugin folder.

Here is what the Read Me file in that folder says about installation:

> From the Preferences menu, do NOT select "Get plugins to enhance calibre" as this is reserved for 'official' calibre plugins. Instead select "Change calibre behavior" to go to Calibre's Preferences page.  Under "Advanced" click on the Plugins button. Use the "Load plugin from file" button to select the plugin's zip file (DeDRM_plugin.zip) and click the "Add" button. Click "Yes" in the the "Are you sure?" dialog. Click OK in the "Success" dialog.

Do you have a suggestion for how it could be more clear?

**Comment by Tarpal** [comment]
Thank you for your reply.
It must been awhile since I came across ZIP archives zipped within another ZIP archive. Withing "DRM-tools_v6.2.1.zip" and and only related to Calibre, there are in 2 different zipped folders 2 more zip-archives: "DeDRM_plugin.zip" (in the folder "Obok_calibre_plugin") and "DeDRM_plugin.zip" in the folder "DeDRM_calibre_plugin". That is to me already a bit confusing at this time of the night. 

The problem with installing the plug-in also might indeed have come because I initially only un-zipped the "DeDRM_calibre_plugin"-folder from the main archive ("DRM-tools_v6.2.1.zip"). Shortcuts don't always work very well. Not at night.
Lets see how far I get in clarifying (IMO) the installation text....

-----
Installation
------------
Before starting Calibre un-zip "DeDRM_plugin.zip" to your hard drive. This will create a number of sub-folders. Some of these folders contain other ZIP-files. There is NO need to unzip these.

Now open Calibre.
Calibre's plug-ins have the extension .ZIP. This can be bit confusing but don't worry: the rest of the installation instructions will talk you through the actual installation process in Calibre.

From the Preferences menu, do NOT select "Get plugins to enhance calibre" as this is reserved for 'official' calibre plugins. Instead select "Change calibre behavior" to go to Calibre's Preferences page.  Under "Advanced" click on the Plugins button. Use the "Load plug-in from file" button to select the plugin's zip file (DeDRM_plugin.zip) and click the "Add" button. Click "Yes" in the the "Are you sure?" dialog. Click OK in the "Success" dialog.
-----

Hope this is any useful. I zip it now.
Thank you for all your efforts.

**Comment by ElleKayEm** [comment]
You unzip one thing and one thing only and that is tools_v6.2.1.zip.  Yeah, it can be a bit overwhelming to open that up and see all these different folders with different tools.  But you just look at the "Read Me First" text to see which tool you need.  Then look at the "Read Me" in that tool's folder.

Glad you did get it figured out though!
