### ISSUE TITLE
Not working on a Kindle file

### ISSUE THREAD

**Issue by Will-I-Am-V** [apprenticeharper/DeDRM_tools#400]
Have a Kindle book from Amazon.de

DeDRM isn't working on this file included (please rename txt to azw):

There is 1 ebook to be decrypted.
Processing file: B00RAKCDHG_EBOK.azw
There was an error with 1 ebook:
macOS High Sierra:Users:William:Desktop:B00RAKCDHG_EBOK.azw is neither a Kindle not a Mobipocket file.
[B00RAKCDHG_EBOK.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1485414/B00RAKCDHG_EBOK.txt)

**Comment by ElleKayEm** [comment]
It's probably a KFX file.  See this post for workarounds to get the file in a format that the tools can handle:

https://www.mobileread.com/forums/showthread.php?t=283371
