### ISSUE TITLE
BN epub key weirdness

### ISSUE THREAD

**Issue by petep0p** [apprenticeharper/DeDRM_tools#401]
i looked through here, but wasn't able to find any issue that exactly matches what I've encountered. i don't think a log file is necessary, but i can post one if it's deemed so. 

here's the setup: i have several books purchased (and free) from the android nook app. i like to have everything together and to be able to read my books in any app. i like to be able to use just the python scripts directly on my phone, but, as was the case with ADE, generating/retrieving the key can be difficult on the phone, so, after failing at that, i turned to my mac (10.9.5) and installed calibre and the DeDrm plug-in.

long story short, i could never decrypt books using the fetched key from the script. of course, the old CC# version also failed, but i tried that, too. i thought maybe it had something to do with my having downloaded the books on android, so i tried to find a way to dl to my mac. well, the old software didn't seem to work for me: nook for mac crashed with a time server error, and nook study would never successfully log in. However, after that, all my android-downloaded books decrypted successfully in calibre via the plug-in. the log file told me that it succeeded on finding the nook study key-apparently, attempting to log in is good enough to get the key. 

then, on my phone, i used the nook study key generated in calibre to successfully decrypt all the books directly via just the python scripts. so that proves its the right key for my account. 

i looked at all the key files, CC#, fetched, and nook study log, and they're all different. 

so i guess the issue here is that the fetch script is not pulling the correct key, as near as i can tell. 

does nook study fetch the key, or does it generate it? if the latter, maybe someone much smarter than me can reverse engineer the key generation to make a new BN key script that could generate the key from email/password. maybe the android app has clues to this-maybe they're identical in function.

anyway, I'm able to Dedrm my books for now, but if the fetch script pulled the same key as the one nook study gets, i could have saved a few hours. 

any thoughts on this?

**Comment by ElleKayEm** [comment]
Nookstudy fetches your current key and writes it in its log.  On a PC, both Nookstudy and Nook for PC share a database which stores the key and all your other B&N account info.  For me, the key retrieved by entering my email and password is the same as the one from Nookstudy.  And it hasn't changed since they switched from the cc# based keys back in late 2014.

I use Nook for PC to download my books, and the key script is based on the url that Nook for PC uses to fetch the key.  I know that some have reported not being able to retrieve their key if they hadn't ever logged into Nook for PC.  Maybe the url could be adjusted so it's not dependent on that.  Make it generic or like a device/app you have logged into.

We knew how the old keys were generated from your cc# and account name.  The new keys are also a string of 28 characters.  But I don't think anyone's discovered how they're generated now.

**Comment by petep0p** [comment]
its really weird that my fetched key and the nook study fetched key aren't the same. i know the retrieval script thinks it's working correctly, because the key is the same char length and general format as the nook study key. they're just clearly different keys. 

just to be clear, too, I've never been able to download my books anywhere but on android. so i don't think i understand how any download url from another source could factor in, if I've never been able to get that far on the mac.

**Comment by ElleKayEm** [comment]
It's pretty rare, but I have seen someone with more than one key before.  Books downloaded with Nook for PC/Mac wouldn't unlock with the Nookstudy key, only those from Nookstudy itself.

Someone once posted on the blog the url that the android app uses to retrieve the key.  That one would undoubtedly be the right one for you.  For me, this was again the same key.  Maybe that one could be added to the script.

I haven't heard of anyone being able to use either Nook for Mac or the Mac version of Nookstudy for a long time.  Both of the old PC programs are still working for me, but a lot of people have issues logging on to Nookstudy.

**Comment by petep0p** [comment]
thanks a lot for all the further info! 

as a side note, i did try both the PC versions under wine on my mac, but they each had identical (similar?) issues as their mac counterparts. i guess the next step on that road would be VM.

stupid question: where is the blog you're referring to? if i can find that i feel like i might be able to hack the script to work with it...

**Comment by ElleKayEm** [comment]
[Apprentice Alf's blog](https://apprenticealf.wordpress.com/2012/09/10/drm-removal-tools-for-ebooks/)

But I don't know how long ago that was mentioned.  It would have been in one of the thousands of comments.  And those occasionally get purged so who knows if it's even still there.

**Comment by petep0p** [comment]
i couldn't find that url in the comments. 

then i got into packet sniffing to try to capture it from the nook app's traffic, but i couldn't get nook to connect through the VPN. 

you don't happen to know/remember how that person ran across that url, do you?

**Comment by petep0p** [comment]
wait - i looked through ignoblekeyfetch.py, and it looks like it has code to try the android device url. it seems like it only does that if the first one returns a bad key. is that what's going on? 

it's there some way to force that one, and, if not, could the option be added? 

and do you know what changes would be necessary to allow this script to run on an android device?

**Comment by ElleKayEm** [comment]
Ah, good idea to look there!  I think you're right...it seems like it only tries the android url if the Nook for PC url doesn't return a key that's the correct length of 28 characters.

I would imagine that it could be changed to always check both urls and save both keys if they're different.

No idea about running the script on android.

**Comment by petep0p** [comment]
actually, i tried it, and it runs fine on android CLI. i substituted the second url in for the first, but it still pulled the same key for me. only the nook study key seems to be 
different. could the script be changed to pull all possible keys and save multiples if multiples are pulled? could it be made to request the key in the same way nook study does? it may be rare that keys are ever different, but I'm evidence that it does happen.

**Comment by ElleKayEm** [comment]
Huh, weird that the Android url key doesn't work on the books downloaded on your phone.  Are they fresh copies of the books?  Maybe the app has just changed.

I don't know if anyone's looked at how Nookstudy fetches the key since it always puts the key in its plain text log.

**Comment by apprenticeharper** [comment]
If you find out any more info about the best way to retrieve keys, please do start a new issue.
