### ISSUE TITLE
Drm not removed

### ISSUE THREAD

**Issue by Daaneman** [apprenticeharper/DeDRM_tools#403]
I regularly import epubs I bought in calibre to read them on other screens.
My latest purchase keeps showing the message 'Locked by drm', when opening it after import in calibre.
Latest version of the plugin installed.
How can I provide more info if needed?

**Comment by twhite96** [comment]
Yeah I am getting the locked by DRM warning in the latest calibre. Will try to find an older release to see if it is on Kovid's end.

**Comment by twhite96** [comment]
Nope. Installed v. 3.11 of calibre and the DRM removal didn't work. Weird.

**Comment by ElleKayEm** [comment]
@Daaneman 
Post a log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

@twhite96 
Start your own new issue and post a log there.

**Comment by apprenticeharper** [comment]
Closed for lack of response. Start another issue with an import log if you still have a problem.
