### ISSUE TITLE
I’ve tried everything, but can’t get the DRM remover to work.

### ISSUE THREAD

**Issue by NicolePDX** [apprenticeharper/DeDRM_tools#406]
Hi,
I’m running Windows 10 Home on a fairly new 64-bit Inspiron 11 3000 series laptop.
My windows user name contains no special characters (only letters) but my Microsoft password contains letters, numbers, and two asterisks.  I only mention this because there was some mention of ascii characters being a problem and I’m not sure if my password could be causing an issue.

After updating Calebre to the latest version, I very carefully went through the steps outlined in the instructions:

-Deregister Kindle for PC from your Amazon account.
-Uninstall Kindle for PC
-Delete the Kindle for PC preferences
-PC: Delete the directory [home folder]\AppData\Local\Amazon and [home folder]\My Documents\My Kindle Content
-Reinstall Kindle for PC version 1.17
-Re-register Kindle for PC with your Amazon account

 >>Here I downloaded and successfully installed the latest 6.5.5 DRM plugin for Calebre

I shut down and restarted Calibre.

At this point, my caliber library was empty, and I’d deleted all precious Kindle downloads from my download folder.

From the Manage Your Content page in Amazon, I used the “Download and Transfer via USB” on a book I’d purchased, but had never attempted to download before.  I chose a Fire as my device.

I opened my download folder and dragged the fresh kindle book from there to Calibre.

When I tried to convert it from AZW3 to a MOBI, I got the “Cannot convert...this book is locked by DRM” message.  See Log File below.

I’ve used and loved Calibre with your DRM removal plugin for years.  It stopped working about a year ago.  I’d be thrilled if you could help me get it up and running again.  Please advise.

Thanks very much!
Nicole
---------------------------------------------------------------------------------
calibre Debug log
calibre 3.12  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.12  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 135.5328125 x 135.466666667
Using calibre Qt style: True
Starting up...
Started up in 70.43 seconds with 0 books
DeDRM v6.5.5: Trying to decrypt Winston S. Churchill- The Prophet of Truth, 1922â€“1939 (Volume V) (Churchill Biography Book 5).azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Winston S. Churchill: The Prophet of Truth, 1922â€“1939 (Volume V) (Churchill Biography Book 5)
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Portl\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Portl\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2592523400' and UserName '506f72746c'
DeDRM v6.5.5: Found 1 new key
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Winston S. Churchill: The Prophet of Truth, 1922â€“1939 (Volume V) (Churchill Biography Book 5)
Got DSN key from database default_key_1
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.5.5: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Winston S. Churchill: The Prophet of Truth, 1922–1939 (Volume V) (Churchill Biography Book 5) to db in: 2.0
Added 1 books in 4.2 seconds
Worker Launch took: 0.43700003624
Job: 1 Convert book 1 of 1 (Winston S. Churchill: The Prophet of Truth, 1922–1939 (Volume V) (Churchill Biography Book 5)) finished
Convert book 1 of 1 (Winston S. Churchill: The Prophet of Truth, 1922–1939 (Volume V) (Churchill Biography Book 5))
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\Portl\\AppData\\Local\\Temp\\calibre_xpgdre\\dfgfeh.opf'
	  output_profile: 'kindle'
	  cover: u'C:\\Users\\Portl\\AppData\\Local\\Temp\\calibre_xpgdre\\aupaxo.jpeg'
	Resolved conversion options
	calibre version: 3.12.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Portl\\AppData\\Local\\Temp\\calibre_xpgdre\\aupaxo.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x055A5090>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x055A53F0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Portl\\AppData\\Local\\Temp\\calibre_xpgdre\\dfgfeh.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Portl\AppData\Local\Temp\calibre_xpgdre\wz9ezo.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Winston S. Churchill: The Prophet of Truth, 1922–1939 (Volume V) (Churchill Biography Book 5) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Winston S. Churchill: The Prophet of Truth, 1922–1939 (Volume V) (Churchill Biography Book 5)

**Comment by ElleKayEm** [comment]
To remove DRM from a book downloaded from the website, you need to choose an E-ink Kindle, not a Fire, and enter its serial number into the plugin customization.  Otherwise, download the book with Kindle for PC (make sure that you uncheck auto-update so it stays on version 1.17) and import that copy.

**Comment by NicolePDX** [comment]
Ah, thank you.  That worked!  I swear I used to be able to do the USB download choosing a Fire.  Oh well, I’m thrilled to be back in business using my paperwhite.  I super appreciate your help!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
