### ISSUE TITLE
Kindle and Windows 10

### ISSUE THREAD

**Issue by LeeThompson** [apprenticeharper/DeDRM_tools#408]
Kindle Reader for Windows 10 seems to work a little bit differently.    The file has the AZW extension but there's an additional file prefixed with "amzn1.drm-voucher".   Calibre + DeDRM does not seem to be able to open them.    (Clearly this is a variant for AWZ.)

(I have a Windows 7 VM where it all still works fine so this isn't really a problem for me but may be for some folks.)

**Comment by ElleKayEm** [comment]
That would be the KFX format.  The tools don't handle that yet.  See this post for workarounds:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by ElusiveZatchmo** [comment]
Yeah I'm very much experiencing the same problem. I'm excited for the next version; hopefully the next update will help with this.

**Comment by averyfreeman** [comment]
This is great!  To the Developer, thank you SO MUCH for developing this program and thanks for everyone who helped explain this on the thread. 

FIRE AND FURY!!!

**Comment by LeeThompson** [comment]
Hopefully KFX development is moving along (if I can help at all let me know), it's only a matter of time before they phase the older format out.

**Comment by ElleKayEm** [comment]
Basically I think it just needs to be integrated into the tools at this point, but Apprentice Harper hasn't had the time to do so.

**Comment by apprenticeharper** [comment]
Someone worked out how to decrypt on PC, someone else has done an auto-translation to python, but I just haven't had any free time to work on extracting that work into a form suitable for inclusion in the tools. If anyone else does, please post a pull request!. :)

But KFX is actually a worse format for converting to (say) ePub, so even when a KFX fix is available I'll probably stick to the work-arounds.
