### ISSUE TITLE
Question about the ADE error E_ADEPT_CORE_DECRYPT_LICENSE_KEY

### ISSUE THREAD

**Issue by cidy8e** [apprenticeharper/DeDRM_tools#411]
Hi there
I've been reading through the FAQs here and the advice to download my ebooks use ADE 2.0.1. When clicking through on the .acsm fulfillment link for an ebook purchased from Kortext, I'm getting the above error. Does this imply that my publisher is not letting me use ADE 2.0.1 (i.e. are there any other troubleshooting steps I can try) or do I need to try ADE 3.0.
I am currently using 2.0.1. on a Windows PC, authorised under my Adobe username.
Also, that eBook has never been fulfilled previously on ADE3.0 or on any other platform.

Thanks in advance.

**Comment by ElleKayEm** [comment]
If you cannot download the book via ADE 2.0.1, it definitely sounds like they are using DRM that these tools will not be able to remove.

**Comment by cidy8e** [comment]
Thanks for that.

**Comment by apprenticeharper** [comment]
I hope that someone is working on the new Adobe DRM, but I haven't heard anything yet.
