### ISSUE TITLE
Can't DeDRM Kindle ebook

### ISSUE THREAD

**Issue by raffam** [apprenticeharper/DeDRM_tools#413]
I was able to DeDRM a kindle ebook but not another one.
I have Kindle 1.21 and Windows 8.1.
The console that launched the DeDRM_App contains really no error information. Only the app itself says that the conversion failed.
by reading the FAQ, onw possibility is that this other ebook was in KFX format. So I tried running:
`ren %localappdata%\Amazon\Kindle\application\renderer-test.exe renderer-test.xxx`
but the Kindle app did not re-download the book.
The [link](https://s3.amazonaws.com/kindleforpc/44183/KindleForPC-installer-1.17.44183.exe) provided by the FAQ to download Kindle 1.17 returns "Access Denied".
Can you help me?

**Comment by ElleKayEm** [comment]
So you're no longer able to download the book at all with Kindle for PC?  You may have a book that's only available in the KFX format.

**Comment by ElleKayEm** [comment]
For the stand-alone Windows DeDRM app?  In your user folder, according to the FAQs.

**Comment by ElleKayEm** [comment]
Try re-downloading the book to Kindle for PC.  Now that you've run that command, you should get the older format.

**Comment by raffam** [comment]
Yes it worked. Thanks
