### ISSUE TITLE
PDF DRM removal while keeping text

### ISSUE THREAD

**Issue by negmos** [apprenticeharper/DeDRM_tools#415]
Hello All,

I have a DRM protected book where i used your tool to remove the DRM to be able to convert to MOBI for my kindle.
The problem is after removing DRM the PDF is consisting of images instead of the text that was inside, so i can't control the font anymore when it is converted to MOBI.

Is this known for PDF or is there a way around it?

**Comment by ElleKayEm** [comment]
I would think that the pdf started out as only page images.

**Comment by negmos** [comment]
@ElleKayEm That is true, the first three pages are images (cover and some other images) then the text starts.

Is there a work around for this?

**Comment by sidick** [comment]
You may find that even the text pages are just images of the text page. The DeDRM process doesn't change the format of the pages at all.

**Comment by negmos** [comment]
@sidick Hello Simon,

I triend to open it via Adobe Digital Content before i remove the DRM and the book is for sure a text. I can select seperate words, characters, ...etc.
Once DRM is removed it is changed to one picture per page.

I should also note that it is in Arabic language. Could this be the problem? the process consider it as a image not Latin characters?

**Comment by sidick** [comment]
OK, that doesn't sound right, normally the DRM removal doesn't change the book at all but if that's happening then I'll have to leave it to more knowledgable people than me I'm afraid.

**Comment by smurfix** [comment]
On 18.12.2017 16:27, negmos wrote:
> I triend to open it via Adobe Digital Content before i remove the DRM
> and the book is for sure a text. I can select seperate words,
> characters, ...etc.

That, unfortunately, doesn't follow. Modern PDF files can be images but
still make individual words selectable, by way of an overlay. This
method is most often used for OCR'd papers, but apparently your file's
creator has chosen to do this with original content.

Unfortunately there's nothing you can do about this.

-- 
-- Matthias Urlichs

**Comment by negmos** [comment]
@smurfix thanks for details, but if this is true, would the dedrm change this overlay layer and leave only the images below? Or shall it leave everything as it is and just remove the drm?

**Comment by apprenticeharper** [comment]
PDF DRM removal is a bit different to the others because PDF is such a complex format. I've never fully understood the internals, but it's certainly possible that an overlay might get lost. (The last tweak I made to it was to ensure high precision coordinates didn't get accidentally rounded, for instance.)

Sorry I can't be of more help.
