### ISSUE TITLE
Can't strip Kindle DRM

### ISSUE THREAD

**Issue by Ratdale** [apprenticeharper/DeDRM_tools#418]
-Downloaded plug-in, presumably installed it correctly.
-Got a few of my Kindle books via Download & transfer via USB and added to Calibre.  One was for my Paperwhite, two for my Kindle Voyage (I tried both after I couldn't make it work).  Each Kindle has my serial number attached to it in Amazon.  I made sure the books are AZW3.
-Double-clicked on the books to open it and got the "sorry, can't open this, it has DRM, what are you, stupid?" message.

What am I doing wrong?  I tried a couple of times, deleting the books, closing Calibre, reopening and re-importing the books.  I've attached the debug log as a pdf as well as pasting because I can't get rid of the strikethrough lines that show up when when I paste it.  

calibre Debug log
calibre 3.9  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5) && Inept Epub DeDRM (0, 1, 7) && Inept PDF DeDRM (0, 1, 4)
calibre 3.9  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5) && Inept Epub DeDRM (0, 1, 7) && Inept PDF DeDRM (0, 1, 4)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Using calibre Qt style: True
Starting up...
Started up in 1.67 seconds with 379 books
Worker Launch took: 0.0698790550232
Worker Launch took: 0.072979927063
Worker Launch took: 0.377260923386

[Ratdale.pdf](https://github.com/apprenticeharper/DeDRM_tools/files/1594529/Ratdale.pdf)

**Comment by ElleKayEm** [comment]
The debug log doesn't actually show any books being added to calibre.  But you don't mention adding the serial numbers of your Kindles into the E-ink Kindle section of the plugin customization.  (You can remove all the old DeDRM plugins -- DeDRM 6.5.5 replaces all of those.)

**Comment by Ratdale** [comment]
You are absolutely right.  I just did that and it worked beautifully.  I missed that in the instructions.  I'll get rid of the other DRM-strippers.  I have them turned off.  Funny that they turn up.
THANK YOU!!!!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
