### ISSUE TITLE
Can't remove DRM from certain Japanese Kobo Books

### ISSUE THREAD

**Issue by saljuice** [apprenticeharper/DeDRM_tools#423]
I am unable to remove the DRM from a few Japanese ePubs purchased from Kobo. It doesn't matter if the files are downloaded through the Kobo desktop app and Obok used or if they are downloaded via. ADE 2.0.1 and imported that way. Although the latter at least gets the title right while the other way results in a 6 character gibberish code. The standalone Obok code also doesn't seem to work.

Here's an example of a log trying to remove DRM from a book using Calibre and Obok.

calibre Debug log
calibre 3.14  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && Obok DeDRM (6, 5, 4) && Kobo Books (1, 3, 0) && Kobo Utilities (2, 6, 0) && KindleUnpack - The Plugin (0, 81, 5) && KoboTouchExtended (2, 8, 2)
calibre 3.14  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && Obok DeDRM (6, 5, 4) && Kobo Books (1, 3, 0) && Kobo Utilities (2, 6, 0) && KindleUnpack - The Plugin (0, 81, 5) && KoboTouchExtended (2, 8, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.9 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.9 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.9 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.9 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
Started up in 9.52 seconds with 13 books
Running Obok DeDRM v6.5.4
DEBUG:   10.5 didn't find device
Obok v3.2.4
Copyright © 2012-2016 Physisticated et al.
c:\users\jon\appdata\local\temp\tmpcqxkh3
DEBUG:   10.5 got kobodir C:\Users\jon\AppData\Local\Kobo\Kobo Desktop Edition
Found 24 possible keys to try.
DEBUG:   18.4 BookListTableWidget:get_books - book_num: 2
DEBUG:   18.4 BookListTableWidget:get_books - book: きまぐれオレンジ★ロード カラー版 1
DEBUG:   18.4 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v6.5.4 - Decrypting きまぐれオレンジ★ロード カラー版 1
Trying key:  d9e5074bbf2ef1646567b043b112335c
Success!
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 194, in get_metadata
  File "site-packages\calibre\ebooks\metadata\epub.py", line 253, in get_metadata
  File "site-packages\calibre\ebooks\metadata\epub.py", line 156, in read_bytes
  File "site-packages\calibre\utils\zipfile.py", line 995, in read
  File "site-packages\calibre\utils\zipfile.py", line 1023, in open
  File "site-packages\calibre\utils\zipfile.py", line 985, in getinfo
KeyError: "There is no item named u'OPS/advanced.opf' in the archive"
DEBUG:   20.2 DecryptAddProgressDialog::do_book_action - decrypted book: 'きまぐれオレンジ★ロード カラー版 1'
Obok DeDRM v6.5.4 - Added hdetpf
Obok DeDRM v6.5.4 - wrapping up results.

**Comment by ElleKayEm** [comment]
Looks like DRM was removed here.  Is it actually not opening because of DRM or is it just not displaying correctly in the calibre reader?  How does it look in ADE?

**Comment by saljuice** [comment]
Huh, looks like it actually is removed. It works in ADE and on my Kobo but is unusable in Calibre and has useless metadata. It's a manga volume and comparing it to some other volumes I have it seems the publisher left out the xhtml files that explain what images are what pages. Calibre and Edge do not like that I guess.

**Comment by ElleKayEm** [comment]
Might be able to edit it or convert it (even just epub to epub).  Depends on how you want to read it or how much you're willing to mess with it.  Someone over in the MobileRead forums could probably help.

As far as DRM removal goes it looks like you can go ahead and close this issue.
