### ISSUE TITLE
Copying Kindle AZW3 from Calibre(Windows) to Calibre(Linux) - solved

### ISSUE THREAD

**Issue by iainrs** [apprenticeharper/DeDRM_tools#424]
I am running Windows-7 as a VirtualBox on my Xubuntu 17.10 Linux System and have Calibre installed on both.

I installed the DeDrm 6.5.5 plugin on (Windows) Calibre  and have added 2 books quite successfully from the Kindle Content Folder.
I want to read one of these on my Linux Calibre so I copied the book to Disk and then added it to Linux Calibre - apparently successfully. However when I try to read the book it displays everything as HTML in an 'edit' screen.

I then converted the AZW3 copy to 'epub' on Windows Calibre, copied it to disk and added it happily to Linux Calibre and it reads OK.

Am I missing something or should I do this every time I want to copy from Windows to Linux ?
Thanks

**Comment by ElleKayEm** [comment]
Well, clearly the DRM is removed (or they were DRM-free).  Not familiar with the Linux version of calibre, but it sounds like it's opening in the editor instead of the reader.  Is it opening correctly in Windows calibre?

**Comment by iainrs** [comment]
Going back to it this morning, the problem only arises when I double-click the entry. If I open using E-Book Reader it's OK. (I don't think that happened before! - . In windows it opened OK(E-book reader) on double-click or via 'View'. 
Thanks for your response - sorry if I wasted your time)

**Comment by ElleKayEm** [comment]
Hmm, I know there are settings somewhere for what formats calibre will open in its own built in reader.  Maybe the Linux version has different defaults?

**Comment by iainrs** [comment]
Preferences - Change Behaviour - 'click' AZW3 - is now read by E-Book Reader - Thanks - I hadn't looked at that.

(There are a lot of Calibre preferences - must play sometime !)
