### ISSUE TITLE
DeDRM failing for Kindle azw3 downloaded from Amazon.com

### ISSUE THREAD

**Issue by krudebox** [apprenticeharper/DeDRM_tools#425]
calibre 3.14  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 79.1688311688 x 79.2832369942
Using calibre Qt style: True
Starting up...
Started up in 2.75 seconds with 194 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['?P\x8dI\xa1i\xdb\xac\x1f\xf8\xde\xe9\xff\x8d7\x96\x12\xdc\xb7Q\x97\xb4\x95\x1b\xa0\xf2\x19W:\xea\xabg', 'C:\\Users\\karth\\Downloads\\kindle-dl\\Red Sparrow.azw3']
DeDRM v6.5.5: Trying to decrypt Red Sparrow.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Red Sparrow
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\karth\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Red Sparrow to db in: 0.2
Added 1 books in 1.1 seconds
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xc3\xee@_hb\xf4\xc9\x8c\xdf\'\x90^Q\xe6m\xaf/{"\xc4\\\xe81\xc8\t\xc9\xc0;yC\xfa', 'C:\\Users\\karth\\Documents\\My Kindle Content\\B008J4L4KY_EBOK\\B008J4L4KY_EBOK.azw']
DeDRM v6.5.5: Trying to decrypt B008J4L4KY_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.5.5: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\karth\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\karth\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2421993827' and UserName '6b61727468'
DeDRM v6.5.5: Found 1 new key
DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: 
Added B008J4L4KY EBOK to db in: 0.1
Added 1 books in 1.0 seconds

C:\Users\karth>

C:\Users\karth>calibre-debug -g
calibre 3.14  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 79.1688311688 x 79.2832369942
Using calibre Qt style: True
Starting up...
Started up in 2.63 seconds with 193 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x03\xf1\x9b$\xd4[E\xda@\xbd\xdf\xd7\xac\xcb!\xae\x0e\xe9OdL[\xda\x8b\x97\xaaa\x04%]e\xf1', 'C:\\Users\\karth\\Downloads\\kindle-dl\\Red Sparrow.azw3']
DeDRM v6.5.5: Trying to decrypt Red Sparrow.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Red Sparrow
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\karth\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Red Sparrow to db in: 0.2
Added 1 books in 1.0 seconds

**Comment by krudebox** [comment]
It worked by disabling the KFX in Kindle for PC by renaming renderer-test.exe. And the adding the azw file from Kindle into calibre. Thanks for the detailed FAQ page.

**Comment by ElleKayEm** [comment]
When downloading from the website, you must choose an E-ink Kindle (not a Fire) for your device.  Then make sure you have that Kindle's serial number entered into the E-ink Kindle section of the plugin customization.
