### ISSUE TITLE
Drm removal not working in Calibre

### ISSUE THREAD

**Issue by Noirewolf** [apprenticeharper/DeDRM_tools#426]
Running Win10, have two books that I want for my personal library downloaded from archive.org.  Unable to remove drm after downloading/installing plug-in in Calibre.  

calibre Debug log
calibre 3.15  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && EpubMerge (2, 1, 1)
calibre 3.15  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && EpubMerge (2, 1, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.917922948 x 108.857142857
Using calibre Qt style: True
Starting up...
EpubMerge: DEBUG: 2018-01-07 03:39:01,782: calibre_plugins.epubmerge.epubmerge_plugin(152): macmenuhack file_path:C:\Users\darke\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
Started up in 17.98 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xe7\xff\xbb\xbe(\x86W\xc0\xefV\x17\xa5\x08\xbf\x9c\xefy\x0c\xee\x92\x11v\x87N\x1c\x07R~Y\xef\x7f\x99', 'C:\\Users\\darke\\Downloads\\DRM books\\hatari00miln_encrypted (1).epub']
DeDRM v6.5.5: Trying to decrypt hatari00miln_encrypted (1).epub
DeDRM v6.5.5: Verifying zip archive integrity
DeDRM v6.5.5: “hatari00miln_encrypted (1).epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 629, in run
  File "calibre_plugins.dedrm.__init__", line 405, in ePubDecrypt
DeDRMError: DeDRM v6.5.5: Couldn't decrypt after 0.0 seconds. DRM free perhaps?
Added Hatari! to db in: 1.9
Added 1 books in 2.4 seconds
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x86\xeb\x07\xda\x11\xc6\xcb- \x95k\xf3\xa9\xcd$\xdab\x18wt\x08_e\xe4Qwev\x04\x0c:\xc4', 'C:\\Users\\darke\\Downloads\\DRM books\\treasures00king_encrypted.epub']
DeDRM v6.5.5: Trying to decrypt treasures00king_encrypted.epub
DeDRM v6.5.5: Verifying zip archive integrity
DeDRM v6.5.5: “treasures00king_encrypted.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 629, in run
  File "calibre_plugins.dedrm.__init__", line 405, in ePubDecrypt
DeDRMError: DeDRM v6.5.5: Couldn't decrypt after 0.0 seconds. DRM free perhaps?
Added Treasures to db in: 1.6
Added 1 books in 2.0 seconds

**Comment by ElleKayEm** [comment]
Doesn't look like this is a DRM that the tools can handle.  At any rate, the tools are intended for purchased books, not ones on loan.

**Comment by bebblebrox** [comment]
You are right but I have purchased 3 books recently from Amazon and its not working. It’s not working with AZW3 file times it seems

**Comment by foldie** [comment]
I have purchased a book from amazon the day before yesterday and successfully removed drm with the plugin, on osx.

**Comment by ElleKayEm** [comment]
@bebblebrox 

Open a new issue if you're having trouble with purchased Kindle books.  Or leave a comment over at Apprentice Alf's blog.
