### ISSUE TITLE
Images disappear

### ISSUE THREAD

**Issue by markusvdw** [apprenticeharper/DeDRM_tools#428]
When I import an eBook into Calibre all the images disappear from the eBook. The same happened when I did a manual deDRM using the Mac app.

I can see the images on the Kindle app, but some of the tables are still too small to read properly and I don't see an option to zoom into the tables/images in the Kindle app.

**Comment by ElleKayEm** [comment]
See this section of the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#my-kindle-book-has-imported-and-the-drm-has-been-removed-but-all-the-pictures-are-gone
