### ISSUE TITLE
DeDrm 6.6.5 doen't always work

### ISSUE THREAD

**Issue by JohnCenne** [apprenticeharper/DeDRM_tools#429]
I have installed DeDrm 6.5.5 on Calibre 3.14 and it doesn't always strip off th eDRM.
I tried on an older version DeDrm 6.2.1 which was running on Calibre 3.8 on an older PC. There it works.

The details.
I bought 3 books on Amazon (Amazon France to be precise) and specified USB Transfer and then specified to use them with my Kindle  - a Basic 7th generation Kindle. 2 of the ebooks were readable, one wasn't. They are all in azw3 format. 

I actually read them on my Samsung Galaxy A5 (2016) smartphone, but when I couldn't read the eBook, I went and tried to read it by double clicking on the book in Calibre. It said it was DRM protected in the  E-Book viewer.
The eBook in question is one published in Nov 2018. The others were Match 2014 and May 2016.
The reloaded eBook is readable on the smartphone.
It looks like a bug in 6.5.5 which has been introduced since 6.2.1

**Comment by ElleKayEm** [comment]
Did you remember to enter the serial number for your Kindle in your new setup?  The other 2 books were probably already DRM-free.

**Comment by JohnCenne** [comment]
No I didn't remember. So I entered them and it all worked perfectly.
Am I red in the face. Fortunately I am old enough to say it was a senior moment.
Thank you very much & my apologies for this lapse
