### ISSUE TITLE
ignoblekeyfetch fails to fetch B&N key

### ISSUE THREAD

**Issue by SpareSimian** [apprenticeharper/DeDRM_tools#430]
The WIndows 10 Nook app from the app store is able to download a new book. The script and the Calibre plugin are unable to fetch a key. The host in the script is resolvable in Chrome.

**Comment by ElleKayEm** [comment]
Have you tried using Nook for PC?

http://images.barnesandnoble.com/PResources/download/eReader2/bndr2_setup_latest.exe

**Comment by SpareSimian** [comment]
I'd also tried downloading a recent purchase with Nook for PC 2.5.6.9575 and it fails with a dialog reading "Please verify the default payment method on record in your account. (Download: 2080)"

The Nook for PC log file has this line, followed by some XML with details about my account:

2018-01-11 13:35:25.00792000 ERROR [DeliveryService.cpp:110] Category:CLIENTAPI, Action:downloadAsset, Message:error kWebserviceError_CREDIT_CARD_HASH_ISSUE (2080) (original error kWebserviceError_CREDIT_CARD_HASH_ISSUE (2080)) - 

Notable in the XML is this item:

<error errorCode="-1131" errorCategory="-1131" errorDetails="Enter a default credit card in your Account. Download again to unlock." customerCopy=""/>

Again, note that the Nook "app" from the Windows 10 store doesn't have a problem. Nor does my physical Nook reader, which does NOT have a credit card configured. (I buy books from the web browser on my desktop and never buy them from the reader.)

**Comment by SpareSimian** [comment]
I believe this issue is a dup of #385.

**Comment by SpareSimian** [comment]
Looks like this is caused by an expired CC in the account. I removed that and retrieved a key.

**Comment by ElleKayEm** [comment]
So were you able to remove the DRM?

**Comment by SpareSimian** [comment]
No, not using the Calibre plugin. Nook for PC is able to do so, though. As is the Nook app for Windows 10.

**Comment by ElleKayEm** [comment]
Post a log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by SpareSimian** [comment]
The plugin throws this exception from a book downloaded using the Windows 10 app. (Downloads from Nook for PC are already decrypted.)

Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 280, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 211, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 182, in __init__
  File "site-packages\Crypto\Cipher\AES.py", line 95, in new
  File "site-packages\Crypto\Cipher\AES.py", line 59, in __init__
  File "site-packages\Crypto\Cipher\blockalgo.py", line 141, in __init__
ValueError: Key cannot be the null string

**Comment by ElleKayEm** [comment]
If it's a book which can't be downloaded with Nook for PC, then I don't think DeDRM will work on it.

**Comment by SpareSimian** [comment]
It does download work with books downloaded using Nook for PC. But it doesn't when downloaded with the new Nook "app" for WIndows 10. (These are two distinct B&N readers.)

**Comment by SpareSimian** [comment]
At this point, I have a working backup of my book so I no longer see a need to pursue this. The fundamental issue was an expired credit card causing issues in retrieving the key. Remove the bad CC from the account and restart Nook for PC and/or re-fetch the key with the Calibre plugin to recover.

**Comment by frioux** [comment]
Isn't Nook for PC EOL'd?  I couldn't even get it to log in anymore.  Are we unable to decrypt nook books currently?

**Comment by frioux** [comment]
For more info, I uncommented the debug line and got this output:
``` xml
<engineResponse><errors><error id="1135_TaskService">Your account is locked due to repeated sign-in failures. If you know the email address for your account but do not know the password, you may reset the password for your account. To reset the password, either click the "Forgot your password?" link below and follow the instructions, or contact Customer Service at 1-800-THE-BOOK.</error><error id="2313_FEEngine">Payment method required</error></errors><stateData><data name="success">0</data></stateData></engineResponse>
```

I changed my password, just in case.  I have a (working) CC in the account that expires 10/2018.  Pretty sure they have hamstrung this API.

**Comment by frioux** [comment]
For kicks I "updated" the credit card on file to be the same as it was before.  It required me to add my phone number and tweak the address to match the US Postal Service format, but still same output as above.

**Comment by ElleKayEm** [comment]
Nook for PC hasn't been officially supported for years -- last updated in 2011, I believe.  But it is still working for me.  Just checked by getting a freebie, downloading, and DeDRMing it.  Of course, I've had Nook for PC on this computer for ages and never sign out of it, just close it.

**Comment by frioux** [comment]
Yeah.  Bizarrely and thankfully I found that I had a decryption key on my old laptop and that worked.  Furthermore, my wife's Nook account *does* allow using the key download tool, so it is indeed some invisible flag on the account. ¯\_(ツ)_/¯

**Comment by ElleKayEm** [comment]
A couple of things to try if you feel like messing with it... Possibly instead of updating your card you might try deleting and adding it again.  Or with more than one, you could try changing the default, then switching back.

**Comment by frioux** [comment]
Eh now that I got an old key to work I don't intend to mess with this again
for a long while 😉

--
