### ISSUE TITLE
Kindle 1.17 Impossible to get after 1.20?

### ISSUE THREAD

**Issue by itriediswear** [apprenticeharper/DeDRM_tools#432]
I downloaded the newest version first now knowing it would be an issue. After learning I needed the older one, I unchecked the box for automatic updates, deleted the My Kindle Content folder, closing the new kindle program and downloading the 1.17 version as I was told to by many different sources. I even tried the 1.16 version. Yet every time I downloaded the old version there would still be an automatic update reverting the program back the new one despite having unchecked the box and having had closed the program as I was instructed. Please tell me what I am doing wrong.

**Comment by ElleKayEm** [comment]
You can modify the latest version so it won't download KFX files.  See method 2 here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by itriediswear** [comment]
Just wanted to inform that the first method was not functioning

**Comment by garfieldthecat** [comment]
I have disabled automatic updates and it works. The annoying bit is that it doesn't let you download multiple books at once - you have to do it manually, one by one.

If you wanted to be really thorough you could download v 1.17, disable your internet connection, install it, disable automatic updates, then re-enable your internet.
