### ISSUE TITLE
DRM stripping in Calibre seeming to not work

### ISSUE THREAD

**Issue by bebblebrox** [apprenticeharper/DeDRM_tools#433]
I am using the Calibre plugin 6.5.5 in Win 10 with Calibre 3.15.
I am downloading the AZW3 file directly from Amazon to my Win environment rather than grabbing the file from Kindle for PC as under 1.17 I seemingly no longer have access. 

It imports fine but leaves the DRM intact. No error is appearing in Calibre warning me It didn’t work. Not sure if there is a log file somewhere I could post if that helps. I have tried this with 4 different books.
Any help appreciated.

**Comment by ElleKayEm** [comment]
To DeDRM books downloaded from the website, you need to choose an E-ink Kindle for the device (not a Fire) and enter its serial number into the E-ink Kindle section of the plugin customization.
