### ISSUE TITLE
DeDrm purchased kindle books_downloaded via USB as azw3 file not working

### ISSUE THREAD

**Issue by socmang** [apprenticeharper/DeDRM_tools#434]
I am using the Calibre plugin 6.5.5 in Win 10 with Calibre 3.15.
I am downloading the AZW3 files of several purchased books directly from Amazon using download via USB option, as instructed on blogs.

When I bring in the azw3 file to calibre, the DRM remains embedded in the file

Below is the log generated by importing the azw3 in calibre debug mode

any help would be greatly appreciated

calibre Debug log
calibre 3.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 105.216828479 x 105.103448276
Using calibre Qt style: True
Starting up...
Started up in 9.25 seconds with 3 books
DeDRM v6.5.5: Trying to decrypt Cities for People.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Cities for People
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\mango\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\mango\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3322642824' and UserName '6d616e676f'
DeDRM v6.5.5: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Cities for People
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.5: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Cities for People to db in: 0.3
Added 1 books in 1.2 seconds

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) and enter its serial number into the plugin customization.

**Comment by socmang** [comment]
ah, thank you - added the serial and it worked!
    On Wednesday, January 17, 2018, 10:59:51 AM EST, ElleKayEm <notifications@github.com> wrote:  
 
 
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) and enter its serial number into the plugin customization.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
