### ISSUE TITLE
Can't get DeDRM plugin in calibre 3.15 to work on new laptop running Windows 10

### ISSUE THREAD

**Issue by MaddKatt** [apprenticeharper/DeDRM_tools#435]
New laptop running Windows 10 (first experience with it)
Installed ADE 2.0.1.  Authorized with usual email & password.  Downloaded books from Kobo account, which I was able to open & read in Adobe.
Installed Active Python 2.7.x & pycrypto for 2.7.
Installed Calibre 3.15
Successfully installed plugin from tools version 6.5.3.  Restarted Calibre.
Added books from ADE.  Books did not import properly (no covers).  Could not open in viewer because DRM not removed.  Deleted books.
Added DRM-free book.  Imported perfectly.
Checked plugins, which were present
Removed plugin, restarted Calibre,  Very carefully added the plugin again per instructions (Apprentice Alf's blog), again succesfully, & restarted Calibre.
Added book, same result.   Checked plugins, which were present, removed plugin & closed Calibre
Uninstalled python & pycrypto.
Installed Python 2.6.6 & pycrypto 2.1 for Python 2.6 (this is what is running on my Win7 PC--this combination along with a key & script has successfully let me remove DRM for years, before I knew about the tools)
Reopened Calibre & successfully installed plugin from tools version 6.5.3 (also what is on Win7 PC--this setup has been working well through a couple re-installs)
Restarted Calibre, tried adding book from ADE.  Still no cover & unable to op
en in viewer due to DRM.
Uninstalled Calibre, deleted library, then reinstalled.  
Downloaded  tools version 6.5.5, successfully loaded the plugin into Calibre per instructions.  Restarted Calibre.  Tried adding book, same result
Able to decrypt one title using key & script, but not the other...
At my wit's end; either I am doing something wrong & just not seeing it or maybe it is a windows 10 problem?

**Comment by ElleKayEm** [comment]
Post a log:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

Incidentally, you don't need PyCrypto or Python when using the calibre plugin.  Not that it hurts, but you only need those for the stand alone Windows app.
