### ISSUE TITLE
Here's the log for my issue   Can't get DeDRM plugin in calibre 3.15 to work on new laptop running Windows

### ISSUE THREAD

**Issue by MaddKatt** [apprenticeharper/DeDRM_tools#436]
calibre Debug log
calibre 3.15 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.15 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 83.2218430034 x 83.1272727273
Using calibre Qt style: True
Starting up...
Started up in 14.48 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x85\t\xf7+\xf1Ki\x15?\xa8\xec+\xa0\x83.\xb0\xafO\xcd\x81\x9a\xd1#9\xfe\xc0\x8c\xa9\xbb?b\xf6', 'C:\\Users\\katsk\\Documents\\My Digital Editions\\The Twelve Kingdoms The Mark of the Tala.epub']
DeDRM v6.5.5: Trying to decrypt The Twelve Kingdoms The Mark of the Tala.epub
DeDRM v6.5.5: Verifying zip archive integrity
DeDRM v6.5.5: The Twelve Kingdoms The Mark of the Tala.epub is a secure Adobe Adept ePub
DeDRM v6.5.5: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v6.5.5: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 343, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.5.5: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 629, in run
  File "calibre_plugins.dedrm.__init__", line 400, in ePubDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Twelve Kingdoms: The Mark of the Tala to db in: 0.2
Added 1 books in 1.8 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x000001CD287FF518>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x000001CD287FF668>> ignored

**Comment by ElleKayEm** [comment]
Did you download the book with ADE 2.0.1 authorized with your Adobe ID on the same machine and user as calibre?  And can you read the book in ADE 2.0.1?

If all that's true, then try uninstalling ADE and removing the registry entry for the key.  Then reinstalling and reauthorizing ADE.  See issue #348 for details on what worked for someone else.

**Comment by MaddKatt** [comment]
Yes to both.  Check out latest post (#437)...  Tools now working beautifully!  Think something corrupted in either adobe or calibre (calibre not fully uninstalling?)  Also re downloaded books after re install. 
Thanks so much!

⁣Sent from BlueMail ​

**Comment by ElleKayEm** [comment]
I think ADE is probably to blame.  It can be buggy and weird.  Or at least that's been my experience.  As I said in the other issue, you can close all 3 of these now.
