### ISSUE TITLE
re issues 435 & 436

### ISSUE THREAD

**Issue by MaddKatt** [apprenticeharper/DeDRM_tools#437]
Long story, long battles with Windows 10, many corrupted programs.  Uninstalled just about everything.
Uninstalled calibre.  Deleted library.  Removed from AppData, both local & roaming.  Removed all mention of calibre in registry.  
Reinstalled Adobe, Calibre & tools (6.5.5).
Imported books.
Worked like a charm!
Whee!
Taking a break now...
Thanks to everyone

**Comment by ElleKayEm** [comment]
Ahh, good...I was just suggesting this in the other issue.  If you're all set, then you can close all 3 of these issues.
