### ISSUE TITLE
DeDRM tools in general are unable to retrieve nook key

### ISSUE THREAD

**Issue by Rihcus** [apprenticeharper/DeDRM_tools#438]
<img width="519" alt="screen shot 2018-01-27 at 3 54 39 pm" src="https://user-images.githubusercontent.com/30292597/35476381-ef08a364-037c-11e8-8c64-2c55f136fd84.png">
Hi, guys first time on GitHub. So recently I tried the nook obtain key via username and password through calibre and it isn't working. I checked my password and even reset it still no luck. Also nook for pc (not the windows store one the normal exe from here (http://images.barnesandnoble.com/PResources/download/eReader2/bndr2_setup_latest.exe) opens but I cannot sign in and when I click the help link it redirects me to a dead tab. Same applies to nook study. I have tried the apprentice harper mac application and python script version to no avail only to get this error:

shellcommand: /usr/bin/python '/private/var/folders/_8/zr66kcsx6tq86qv0l10wb0980000gn/T/AppTranslocation/44A04BA9-783A-4346-835E-A00ADA8214CA/d/DeDRM.app/Contents/Resources/ignoblekeyfetch.py' '(username)' '(passwor

Please help.
[DeDRM .log](https://github.com/apprenticeharper/DeDRM_tools/files/1670549/DeDRM.log)

**Comment by ElleKayEm** [comment]
Yeah, not being able to log in to Nook for PC is a problem because DeDRM retrieves the key the same way.  Does your password have a non-ascii character?  If so, try resetting it to one without.  (After retrieving your key, you can change the password to whatever you like without effecting the key.)

**Comment by Rihcus** [comment]
Nope, it is an alphanumeric one 13 digits long one caps letter one lowercase letter and 11 numbers long. Sorry if I got this wrong I don't know what is an aci password.

**Comment by ElleKayEm** [comment]
Hmm, I would think that would be fine.  Maybe the length?  I don't know.

**Comment by Rihcus** [comment]
I got nook for pc working I think the issue was that I entered my password to many times causing a temporary account lock out. Do you know where the b64 file is located from this app? Calibre still can't get my key.

**Comment by Rihcus** [comment]
Wait I forgot to update payment method... give me a sec

**Comment by ElleKayEm** [comment]
Nook for PC's key is in a database in a hidden folder.  Nookstudy also has it in a plain text log.  I would need to do some digging to find it again.  But hopefully the key retrieval will work once you get the payment method updated.

**Comment by Rihcus** [comment]
I got calibre to get the key

**Comment by ElleKayEm** [comment]
Now the real test... can you unlock your nook books?  You should be good as long as they're not old copies.

**Comment by Rihcus** [comment]
Sory for the delay works like a charm thanks for the help!
