### ISSUE TITLE
AZW3 DRM not removed on Calibre 32 and 64 for Windows 7 - 64

### ISSUE THREAD

**Issue by pcayuela** [apprenticeharper/DeDRM_tools#441]
After several tries I can't remove AZW3 DRM on Calibre 32 and 64 for Windows 7 - 64.
I bought the book on Amazon for using on my Kindle.
[tmpulb5kt.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1691924/tmpulb5kt.txt)
[tmpzux0xm.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1691925/tmpzux0xm.txt)
[tmpezlski.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1691926/tmpezlski.txt)

Attached logs.

**Comment by ElleKayEm** [comment]
You need to enter your E-ink Kindle serial number into the plugin customization.

**Comment by pcayuela** [comment]
Thank you! Now it works!
