### ISSUE TITLE
Epub to Mobi Failed

### ISSUE THREAD

**Issue by pab-cov** [apprenticeharper/DeDRM_tools#442]
Tried mulitple Epub format books which were downloaded from my local library and want to read on Kindle.

Windows 10, Calibre 3.16 with DeDRM plug-in 6.5.5 installed. Won't convert any books i have.  Here's a log of one:
[tmplwjbc5.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1708908/tmplwjbc5.txt)

**Comment by ElleKayEm** [comment]
These tools are intended for purchased books, not library loans.
