### ISSUE TITLE
Unable to de-DRM Kindle books since November 2017

### ISSUE THREAD

**Issue by RedpointRik** [apprenticeharper/DeDRM_tools#445]
Sometime around the end of October or this past November, importing .azw3 books into Calibre no longer removed the DRM. 
Using DeDRM_tools_6.5.5. 
My work-around was to use the Mac desktop DeDRM app, and that was working until today.
DeDRM log says:
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 4 keys tried.

**Comment by ElleKayEm** [comment]
AZW3?  Are you downloading them from the website?  If so, did you select an E-ink Kindle for your device?  And do you have its serial number entered into DeDRM?

**Comment by RedpointRik** [comment]
The book was borrowed from the library, downloaded through Amazon. Yes, there are 2 Kindle serial numbers entered into DeDRM.

**Comment by ElleKayEm** [comment]
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cant-get-the-tools-to-work-on-my-rented-or-library-ebooks
