### ISSUE TITLE
Had to redownload Calibre and DeDRM software and now not working

### ISSUE THREAD

**Issue by mjschaefer12** [apprenticeharper/DeDRM_tools#449]
DEBUG LOG:

calibre Debug log
calibre 3.17  embedded-python: True is64bit: True
Darwin-17.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.17  embedded-python: True is64bit: True
Darwin-17.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 125.500001885 x 125.500001885
Using calibre Qt style: True
Starting up...
Started up in 1.33 seconds with 698 books
DeDRM v6.5.5: Trying to decrypt After Dark with a Scoundrel_ Lords of Vice.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: After Dark with a Scoundrel: Lords of Vice
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/madisonschaefer/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '292035f2ce16' and UserName 'madisonschaefer'
DeDRM v6.5.5: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: After Dark with a Scoundrel: Lords of Vice
Got DSN key from database default_key_1
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.5.5: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added After Dark with a Scoundrel: Lords of Vice to db in: 0.0
Added 1 books in 1.1 seconds

--> I am using a MacBook 12" and I just downloaded the software after my previous laptop died. I purchased this book on amazon and downloaded it to my kindle in order to add it to the calibre library. When attempting to change the format I discovered that the DRM had not been removed.

**Comment by ElleKayEm** [comment]
Looks like you haven't entered your E-ink Kindle's serial number into the plugin customization.
