### ISSUE TITLE
unable to read a book

### ISSUE THREAD

**Issue by pippo73** [apprenticeharper/DeDRM_tools#45]
Hi,
I'm running calibre 2.45 and kindle 1.13.1 and DeDRM_tools_6.3.4a on a win10 pc
I've just bought a book from amazon. Downloaded the azw file with the kindle for pc on my pc and imported the file into calibre library.
When I try to read the file with calibre I get the message that the file is DRM protected and is not able to read it.

Do I miss something?

**Comment by platonium** [comment]
First of all, many thanks to Apprentices Alf and Harper and everyone else contributing to these tools.  As a noob myself, I ran into a very similar problem as you.  What finally worked - and I'm sorry if I missed it in the documentation - is opening the file in the Kindle app and opening the file again in Calibre after being sure the correct plug-in was installed and calibre restarted.

**Comment by pippo73** [comment]
Hi, 
in the meanwhile, I've found a "solution".. I've reinstalled from scratch all the apps (calibre dedrm kindle  and books) .
now it worked. 

thank anyway
