### ISSUE TITLE
issue removing nook drm

### ISSUE THREAD

**Issue by lindsey1981** [apprenticeharper/DeDRM_tools#453]
I have the latest version of safari, calibre and the drm removal tools. I am getting a message that I can't convert my files due to them being drm protected. I have a first generation nook that I am putting the files on my computer from (no other way for me to access them, nook for Mac does not work on my computer).

calibre Debug log
calibre 3.17  embedded-python: True is64bit: True
Darwin-17.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.17  embedded-python: True is64bit: True
Darwin-17.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 98.0000014718 x 98.0000014718
Using calibre Qt style: True
Starting up...
Started up in 1.82 seconds with 0 books
objc[847]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffb0620b68) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11c965cd8). One of the two will be used. Which one is undefined.
DeDRM v6.5.5: Trying to decrypt 2940000226889.epub
DeDRM v6.5.5: Verifying zip archive integrity
DeDRM v6.5.5: “2940000226889.epub” is a secure Barnes & Noble ePub
DeDRM v6.5.5: Trying Encryption key Lindsey Barnes and Noble
Could not decrypt G_8u9K.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 280, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 211, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 160, in __init__
IGNOBLEError: AES improper key used

DeDRM v6.5.5: Failed to decrypt with key Lindsey Barnes and Noble after 0.0 seconds
DeDRM v6.5.5: Looking for new NOOK Study Keys after 0.0 seconds
Found nookStudy log file: /Users/lindseymallory/Library/Application Support/Barnes & Noble/BNDesktopReader/logs/BNClientLog.txt
Found nookStudy log file: /Users/lindseymallory/Library/Application Support/Barnes & Noble/BNDesktopReader/indices/BNClientLog.txt
DeDRM v6.5.5: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 629, in run
  File "calibre_plugins.dedrm.__init__", line 298, in ePubDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Autism Speaks 100 Day Kit to db in: 0.0
Added 1 books in 0.7 seconds
2018-03-05 11:32:06.980 Calibre[861:22305] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.0957169532776
Job: 1 Convert book 1 of 1 (Autism Speaks 100 Day Kit) finished
Convert book 1 of 1 (Autism Speaks 100 Day Kit)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'/var/folders/6z/_wkv2q054m719d2q5nw_qpmc0000gp/C/calibre_3.17.0_tmp_6_sz0Z/MyhaF0.opf'
	  output_profile: 'nook'
	  verbose: 2
	Resolved conversion options
	calibre version: 3.17.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10bdbf890>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.NookOutput object at 0x10be891d0>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/6z/_wkv2q054m719d2q5nw_qpmc0000gp/C/calibre_3.17.0_tmp_6_sz0Z/MyhaF0.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: 2JodJC.epub
	InputFormatPlugin: EPUB Input running
	on /var/folders/6z/_wkv2q054m719d2q5nw_qpmc0000gp/C/calibre_3.17.0_tmp_6_sz0Z/2JodJC.epub
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1088, in run
	  File "

**Comment by ElleKayEm** [comment]
Were you able to retrieve your key by putting your B&N account email and password into the plugin customization?  If so, try downloading fresh copies of your books to your Nook.

**Comment by lindsey1981** [comment]
Yes I have put my B&N account information in and gotten the key.

**Comment by lindsey1981** [comment]
The book I am starting with is brand new for us and I just downloaded it.

**Comment by ElleKayEm** [comment]
Not sure why it's not working then.  I see from the log that DeDRM found a Nookstudy log.   Is NookStudy no longer installed and/or working either?

**Comment by lindsey1981** [comment]
I am not sure how but the whole nook was corrupted. I reset it back to factory setting and that seems to have done the trick to fix it (now to download my huge library to back it up).

**Comment by ElleKayEm** [comment]
Glad you got it sorted.  Feel free to close the issue whenever you're all set.
