### ISSUE TITLE
macOS: "brew" Python changes break DeDRM

### ISSUE THREAD

**Issue by tadada-o** [apprenticeharper/DeDRM_tools#457]
The Homebrew project this week changed the default Python from 2 to 3.

From what I could figure out, the AppleScript "main.scpt" in DeDRM checks "/usr/local/bin/python" for a Python 2.

After the changes made by Homebrew, this will fail as there is now a Python 3 in that location.

**Comment by ctshh** [comment]
```
$ rm /usr/local/bin/python
$ ln -s /usr/bin/python2.7 /usr/local/bin/python
```

**Comment by apprenticeharper** [comment]
I thought that the official python word was that python would always be python 2. If I'm right, this is a problem with homebrew.

**Comment by apprenticeharper** [comment]
https://www.python.org/dev/peps/pep-0394/

Homebrew bug.
