### ISSUE TITLE
Probable bug in Kindle for Mac caused by Android support

### ISSUE THREAD

**Issue by asphoa** [apprenticeharper/DeDRM_tools#46]
shellcommand: /usr/bin/python '/Volumes/Raumfahrt/Software/Mac/DeDRM_tools_6.3.4a/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/adobekey.py' '/Users/Asphoa/Library/Preferences/com.apprenticealf.dedrm/Local Adept Key.der' > '/Users/Asphoa/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: adobekey.py v6.0
Copyright © 2009-2013 i♥cabbages and Apprentice Alf
 Traceback (most recent call last):
  File "/Volumes/Raumfahrt/Software/Mac/DeDRM_tools_6.3.4a/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/adobekey.py", line 602, in <module>
    sys.exit(cli_main())
  File "/Volumes/Raumfahrt/Software/Mac/DeDRM_tools_6.3.4a/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/adobekey.py", line 525, in cli_main
    keys = adeptkeys()
  File "/Volumes/Raumfahrt/Software/Mac/DeDRM_tools_6.3.4a/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/adobekey.py", line 446, in adeptkeys
    raise ADEPTError("Could not find ADE activation.dat file.")
__main__.ADEPTError: Could not find ADE activation.dat file.
shellcommand: /usr/bin/python '/Volumes/Raumfahrt/Software/Mac/DeDRM_tools_6.3.4a/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/ignoblekey.py' '/Users/Asphoa/Library/Preferences/com.apprenticealf.dedrm/Nook Study Key.b64' > '/Users/Asphoa/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: ignoblekey.py v1.1
Copyright © 2015 Apprentice Alf
No nook Study log files have been found.
Could not retrieve nook Study key.
 
There is 1 ebook to be decrypted.
Processing file: B00MUQULMY_EBOK.prc
An unexpected error occurred. Please report on Apprentice Alf's blog.

Error Message: Erreur dans Finder : Il est impossible d’obtenir document file "backup.ab" of folder "TemporaryItems" of folder "Caches" of folder "Library" of folder "/username/" of folder "Users" of startup disk.
Error Number: -1728

**Comment by apprenticeharper** [comment]
It looks like there's a bug in the latest DeDRM app for Macintosh, from trying to support Kindle for Android. You might be able to work around it by creating an small text file (contents unimportant) called "backup.ab" in the location mentioned.

**Comment by apprenticeharper** [comment]
This will be fixed in 6.4.3
