### ISSUE TITLE
DeDRM failed to decrypt: no keys found

### ISSUE THREAD

**Issue by fossilizedwood** [apprenticeharper/DeDRM_tools#462]
Hello, 

Can someone please assist? I am having trouble removing the DRM on my AZW ebook using Calibre and this plugin.

Here is the debug log:

calibre Debug log
calibre 3.19  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && Obok DeDRM (6, 5, 4)
calibre 3.19  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && Obok DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.29] db initialized
[0.29] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.93] main UI initialized...
[1.93] Hiding splash screen
[1.95] splash screen hidden
[1.96] Started up in 1.96 seconds with 1 books
DeDRM v6.5.5: Trying to decrypt Leap_ Leaving a Job with No Plan B to Find the Career and Life You Really Want.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Leap: Leaving a Job with No Plan B to Find the Career and Life You Really Want
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Leap: Leaving a Job with No Plan B to Find the Career and Life You Really Want to db in: 0.0
Added 1 books in 1.0 seconds

**Comment by fossilizedwood** [comment]
OK, I got it to work. I originally downloaded the book from Amazon website using the "download and transfer by USB" option when I got the above error message.

I got it to work by downloading Kindle for Mac 1.17 and sent the file there. I imported the file downloaded in the folder "My Kindle Content" on my Mac to Calibre and was able to successfully convert to EPUB. Any ideas why this was?

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) for the device and enter its serial number into the plugin customization.
