### ISSUE TITLE
Cannot convert kindle book

### ISSUE THREAD

**Issue by vipson** [apprenticeharper/DeDRM_tools#463]
Please bear with me as this is the first time I am posting...I need help.

I am using:
Calibre: 3.19 latest version on Win 10 Pro 64 bits
Kindle: 1.20.1
Plugin used: DeDRM_tools_6.5.5
I am getting error while converting Kindle for PC ebook:
Error: This book is locked by DRM

It used to work at least 3-4 months back.

**Comment by ElleKayEm** [comment]
You've probably run into KFX files.  DeDRM can't handle them yet.  See this thread for ways to get files in the older format:
https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by apprenticeharper** [comment]
6.6.0 can now handle KFX if you also install the KFX Input plugin.
