### ISSUE TITLE
Unable to convert bought Kindel book (.azw) - imported ebooks still have DRM

### ISSUE THREAD

**Issue by evrardM** [apprenticeharper/DeDRM_tools#469]
## Hi there, I need help to convert a book I've bought in PDF to use it for school (I have the permission of the editor house).

I think I did everything that was described, but at the end I receveid this **error message** : 

calibre, version 2.48.0 (win32, isfrozen: True)
Conversion Error: Failed: Convert book 1 of 1 (B00NHVF30G EBOK)

Convert book 1 of 1 (B00NHVF30G EBOK)
C:\Program Files (x86)\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Resolved conversion options
calibre version: 2.48.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0313C730>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': u'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x0313CAF0>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'personal_doc': u'[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Marion\\AppData\\Local\\Temp\\calibre_pzoria\\2taa9f.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\Marion\AppData\Local\Temp\calibre_pzoria\il96rt.azw
Python function terminated unexpectedly
  Unknown book type: '\x81\xc4\xde\x02|\x8c"\x08' (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 132, in main
  File "site.py", line 109, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 190, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 31, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1051, in run
  File "site-packages\calibre\customize\conversion.py", line 241, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 33, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 79, in __init__
calibre.ebooks.mobi.MobiError: Unknown book type: '\x81\xc4\xde\x02|\x8c"\x08'

## Then I made a log of the import process by deleting the DRMed ebook from calibre and then adding the ebook to calibre when it's running in debug mode. **This log appeared** : 

calibre Debug log
calibre 2.48  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Loaded cached store plugin for: Amazon AU Kindle at version: 3
Loaded cached store plugin for: Amazon IN Kindle at version: 3
Loaded cached store plugin for: Amazon FR Kindle at version: 13
Loaded cached store plugin for: Amazon Kindle at version: 13
Loaded cached store plugin for: Kobo at version: 6
Loaded cached store plugin for: Virtualo at version: 7
Loaded cached store plugin for: Amazon ES Kindle at version: 13
Loaded cached store plugin for: Woblink at version: 13
Loaded cached store plugin for: Google Books at version: 3
Loaded cached store plugin for: Amazon IT Kindle at version: 13
Loaded cached store plugin for: Amazon CA Kindle at version: 5
Loaded cached store plugin for: Amazon DE Kindle at version: 13
Loaded cached store plugin for: Amazon UK Kindle at version: 13
Loaded cached store plugin for: Koobe at version: 5
Loaded cached store plugin for: Archive.org at version: 3
Loaded cached store plugin for: Smashwords at version: 4
Loaded cached store plugin for: Nexto at version: 4
Loaded cached store plugin for: Ebookpoint at version: 8
Loaded cached store plugin for: Publio at version: 6
Loaded cached store plugin for: Cdp.pl at version: 8
Loaded cached store plugin for: Legimi at version: 8
Started up in 40.34 seconds with 0 books
DeDRM v6.5.5: Trying to decrypt B00NHVF30G_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.5.5: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.9 seconds
searching for kinfoFiles in C:\Users\Marion\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Marion\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '180021362' and UserName '4d6172696f6e'
DeDRM v6.5.5: Found 1 new key
DeDRM v6.5.5: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 349, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 273, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 488, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 273, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 301, in identity
MobiError: Unknown book type: ÄÞ |Œ" 
Added B00NHVF30G EBOK to db in: 2.3
Added 1 books in 4.7 seconds

## I hope you have all the information you need, thanks for your help!

**Comment by ElleKayEm** [comment]
See this line in the log:

> DeDRM v6.5.5: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.

Go here to see how to deal with this:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by evrardM** [comment]
It worked ! thanks a lot

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
