### ISSUE TITLE
Cannot remove DRM from kindle book

### ISSUE THREAD

**Issue by leroypimental** [apprenticeharper/DeDRM_tools#470]
using kindle 1.17 (44173)
calibre 3.20 and DeDRM 6.5.5 plugin
and I am trying to remove the DRM from a rented book but I try to open the book in calibre I get an error that the book is locked by DRM. Any ideas?  

calibre Debug log
calibre 3.20  embedded-python: True is64bit: True
Darwin-17.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.20  embedded-python: True is64bit: True
Darwin-17.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000163 x 107.500001614
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[1.13] main UI initialized...
[1.13] Hiding splash screen
[1.18] splash screen hidden
[1.18] Started up in 1.18 seconds with 0 books
DeDRM v6.5.5: Trying to decrypt B00F5UADJI_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Computational Ocean Acoustics (Modern Acoustics and Signal Processing)
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/leroypimental/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '0dc51318ba59' and UserName 'leroypimental'
DeDRM v6.5.5: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Computational Ocean Acoustics (Modern Acoustics and Signal Processing)
Got DSN key from database default_key_1
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.5.5: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Computational Ocean Acoustics (Modern Acoustics and Signal Processing) to db in: 0.1
Added 1 books in 0.8 seconds

**Comment by ElleKayEm** [comment]
You've answered your own question.  See this line from the log:

>DeDRM v6.5.5: Failed to decrypt with error: Cannot decode library or rented ebooks

**Comment by leroypimental** [comment]
Well... yup.  Thanks.
