### ISSUE TITLE
Log says DRM removal succeeded, but the resulting ebook has almost all the images replaced by black blocks

### ISSUE THREAD

**Issue by rincebrain** [apprenticeharper/DeDRM_tools#472]
As I do not own a physical Kindle, I cannot try downloading for USB transfer AFAICT, and the logfile thinks the decryption succeeds, but the resulting book has all but a few pages of images replaced by solid black.

Reading said book in Kindle for PC 1.17, as you might expect, works fine.

[decryption success log.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1874055/decryption.success.log.txt)

**Comment by ElleKayEm** [comment]
Is it the calibre e-book viewer that shows black pages?  How does the DRM-free version look in Kindle for PC?  Have you tried converting it?  Or redownloading?

Alternatively, I see it's a graphic novel that can be read on Comixology.  If you sign in with your Amazon account, you could try using the Comic-Backup chrome extension available here:

https://github.com/Cortys/comic-backup

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by rincebrain** [comment]
...no? Are you trying to convey briefly that the issue is with Calibre's viewer and not the actual content?

**Comment by ElleKayEm** [comment]
Yes, since you said the DRM-free version opens and displays properly in Kindle for PC, then it doesn't seem like there's any issue with DeDRM.

**Comment by j-howell** [comment]
Calibre's e-book viewer does not support Amazon fixed layout, as used in comics and children's books.
