### ISSUE TITLE
No Advanced in Preferences

### ISSUE THREAD

**Issue by simonj4599** [apprenticeharper/DeDRM_tools#474]
Just upgraded Calibre to 3.21.0 and downloaded the DeDRM Tools 6.6.0.
I used to have an "advanced" area/ button in Preferences - now it's gone can,t see where to add plugins...
Help!

**Comment by ElleKayEm** [comment]
Just click the Preferences button itself instead of the drop-down menu.

**Comment by simonj4599** [comment]
There is no Plug in button inside Preferences - I can see no way to add a
plug-in.

**Comment by j-howell** [comment]
Plugins is the first icon in the Advanced category in Preferences:

![prefs](https://user-images.githubusercontent.com/6223054/38472372-0e070ee2-3b4d-11e8-9150-cff3ecb0a274.gif)

**Comment by simonj4599** [comment]
Thank you for your help. What happened was, when I upgraded Calibre the
Prefrences box resized perfectly so that nothing showed below Sharing, as
if the box ended there... I was looking at your reponse and a lightbulb
went off....
What can I say - I'm a dummy :)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by simonj4599** [comment]
Close away - thank you

**Comment by ElleKayEm** [comment]
Only you (or Apprentice Harper) can close your issue.

**Comment by simonj4599** [comment]
Sorry how do I close the thread.

**Comment by ElleKayEm** [comment]
You should be able to see a "close issue" button.
