### ISSUE TITLE
DeDRM_plugin.zip Missing from 6.6.0

### ISSUE THREAD

**Issue by riegelstamm** [apprenticeharper/DeDRM_tools#475]
DeDRM_plugin_ReadMe says to find the file "DeDRM_plugin.zip" in the "DeDRM_calibre_plugin" folder. However, there is no such file.

**Comment by ElleKayEm** [comment]
Download and extract again?  It's not missing for me.

**Comment by riegelstamm** [comment]
I know what happened. I use a download manager, and it automatically extracted not only the main zip, but all the other zip files as well.
