### ISSUE TITLE
View error in Calibre

### ISSUE THREAD

**Issue by AnOrangeCat** [apprenticeharper/DeDRM_tools#476]
Downloaded version of purchased amazon ebook do not open in calibre: i got error in view mode.
Latest version of tools, Calibre 3.21 
As requested this is calibre log file
[tmptslgkh.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1889489/tmptslgkh.txt)

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) for the device and enter its serial number into the plugin customization.
