### ISSUE TITLE
ZIP file infected

### ISSUE THREAD

**Issue by kPshi** [apprenticeharper/DeDRM_tools#48]
When checking for viruses in your archives Dr. Web reports virus infections in the newer ones:

tools_v6.0.8.zip : OK
tools_v6.0.9.zip : OK
tools_v6.1.0.zip : OK
tools_v6.2.0.zip : OK
tools_v6.2.1.zip : OK
tools_v6.2.2.zip : OK
tools_v6.3.1.zip : OK
DeDRM_tools.6.3.2.zip : FOUND Trojan.Siggen6.48102
DeDRM_tools_6.3.3.zip : FOUND Worm.Win32.AutoRun
DeDRM_tools_6.3.4a.zip : FOUND Trojan.Siggen6.48102
DeDRM_tools_6.3.4.zip : FOUND Trojan.Siggen6.48102

Maybe you should check your system and/or fix the (hopefully) false positive.

**Comment by kPshi** [comment]
When you don't have Dr. Web: you can use jotti.org or virustotal.com to scan online.

When asking the latter to rescan, also the older versions seem infected:
6.0.8: clean
6.0.9: clean
6.1.0: clean
6.2.0: Trojan.Siggen6.48102
6.2.1: Trojan.Siggen6.48102
6.2.2: Trojan.Siggen6.48102
6.3.1: Trojan.Siggen6.48102

**Comment by ethus3h** [comment]
The file in the zip that is detected is: >>DeDRM_tools_6.3.4a.zip/Other_Tools/Scuolabook_DRM/Scuolabook_DRM_Remover_1.0.zip/Scuolabook DRM Remover.exe infected with Trojan.Siggen6.48102

According to https://online.drweb.com/result/ http://online5.drweb.com/cache/?i=2146790f757ad68ff766f310a0310877

Also note that Dr.WEB is the only anti-virus tool tested by VirusTotal that identifies that file as dangerous, so it seems possible that it is an incorrect detection.

Here is the result for that file: https://www.virustotal.com/en/file/db001f2907f459fd0e4931bb1fc7c0b4b610bc9582006a30a2b4f5f2510c130a/analysis/1450393330/

**Comment by apprenticeharper** [comment]
That file dates back to at least 2012. This is a false positive that I can do nothing about.

**Comment by kPshi** [comment]
Scuola 1.3 seems to be clean:
https://www.virustotal.com/en/file/ef31f2d6d5e7bdbdcc40ed3d067c7bc79dd1f62103e57e3470f0ade405e76d0d/analysis/1451986275/
https://www.virustotal.com/en/file/c88ba783d72e872acb5dd88142d4a30e29833c3032e8e894d4020a166d771e11/analysis/1451986373/
https://www.virustotal.com/en/file/120ffcc1e2db205d1e08fa620df99937e3dee01827fbc97c0a0843700374749f/analysis/1451986401/

Maybe you want to update?

**Comment by apprenticeharper** [comment]
If there's a new (free, open source) version of the tool, I'll happily include it in the next update.
