### ISSUE TITLE
DeDRM v6.6.0: Failed to decrypt

### ISSUE THREAD

**Issue by RolloRoundbottom** [apprenticeharper/DeDRM_tools#480]
B&N epub that I copied from my Android to my PC.

calibre Debug log
calibre 3.21 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.21 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 92.5388994307 x 92.3636363636
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
[1.44] main UI initialized...
[1.44] Hiding splash screen
[15.89] splash screen hidden
[15.89] Started up in 15.89 seconds with 73 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\\\xe5\xd3\x90\x1a\xd3\x1bYxd\xd3\xbb\x906\xcf\x94\xa9\xa3|\xe7\xd8\xd3\x9c8@\x86\xb2\xc9\x8b\xb5\x01\xcf', 'S:\\Bill\\Documents\\Misc\\9780307795960_epub.v6.epub']
DeDRM v6.6.0: Trying to decrypt 9780307795960_epub.v6.epub
DeDRM v6.6.0: Verifying zip archive integrity
DeDRM v6.6.0: “9780307795960_epub.v6.epub” is a secure Barnes & Noble ePub
DeDRM v6.6.0: Trying Encryption key do.something@cox.net
Could not decrypt a2mmmx.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 280, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 211, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 182, in __init__
  File "site-packages\Crypto\Cipher\AES.py", line 95, in new
  File "site-packages\Crypto\Cipher\AES.py", line 59, in __init__
  File "site-packages\Crypto\Cipher\blockalgo.py", line 141, in __init__
ValueError: Key cannot be the null string
DeDRM v6.6.0: Failed to decrypt with key do.something@cox.net after 0.5 seconds
DeDRM v6.6.0: Looking for new NOOK Study Keys after 0.5 seconds
No nook Study log files have been found.
DeDRM v6.6.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 300, in ePubDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Star Wars: The Clone Wars to db in: 0.5
Added 1 books in 1.7 seconds

Thanks for looking at this.
-Rollo

**Comment by ElleKayEm** [comment]
Were you able to successfully retrieve your key by entering your B&N email account and password into the DeDRM plugin customization?

**Comment by RolloRoundbottom** [comment]
Yes, I was. The plugin removed DRM from about 80 other B&N books I imported into Calibre.

**Comment by ElleKayEm** [comment]
Try downloading fresh copies.  Or downloading with the old Nook for PC program.  Available here:

http://images.barnesandnoble.com/PResources/download/eReader2/bndr2_setup_latest.exe

**Comment by RolloRoundbottom** [comment]
Downloading with the old Nook for PC program solved the issue. All the remaining books imported into Calibre with DRM removed.

Thank you very much for the assistance.
