### ISSUE TITLE
KFX file still has DRM

### ISSUE THREAD

**Issue by mbrenohd** [apprenticeharper/DeDRM_tools#481]
Even after all steps, I couldn't remove DRM.

calibre Log de Debug
calibre 3.21 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.21 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[1.34] main UI initialized...
[1.34] Hiding splash screen
Storage number map:
{(7L, 0L): [(3L, 'C'), (4L, 'D')], (7L, 1L): [(1L, 'E')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\90C60706511201EM&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=10)
{u'drive_letters': ['E'],
 u'pnp_id_map': {'E': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#90c60706511201em&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'E': (1L, 1L)}}
Job: 1 Obter informações do dispositivo started
DeviceJob: 1 Obter informações do dispositivo done, calling callback
DeviceJob: 1 Obter informações do dispositivo callback returned
Job: 2 Definir informações da biblioteca started
DeviceJob: 2 Definir informações da biblioteca done, calling callback
DeviceJob: 2 Definir informações da biblioteca callback returned
Job: 3 Obter listagem de livros do dispositivo started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: E:\ documents
DEBUG:    0.0 USBMS: scan from root False E:\documents
DEBUG:    0.0 USBMS: count found in cache: 38, count of files in metadata: 38, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Obter listagem de livros do dispositivo done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 38
DeviceJob: set_books_in_library finished: time= 0.00399994850159
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Obter listagem de livros do dispositivo callback returned
Job: 3 Obter listagem de livros do dispositivo finished
Nenhum detalhe disponível.
Job: 1 Obter informações do dispositivo finished
Nenhum detalhe disponível.
Job: 2 Definir informações da biblioteca finished
Nenhum detalhe disponível.
[82.61] splash screen hidden
[82.61] Started up in 82.61 seconds with 3 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['O\xcd\xb9\x88w4 2\x1f=\x15\xb2\xe5\x96\t\xb1\xfb\x9d>\xed<\xc6\x1e\xf9\xc4\xd5\x0bY\x8cz\xc3+', 'E:\\documents\\Revis\xc3\xa3o Sistem\xc3\xa1tica da Literatura em Engenharia de Software_ Teoria e Pr\xc3\xa1tica_B0733NCCS8.kfx']
DeDRM v6.6.0: Trying to decrypt RevisÃ£o SistemÃ¡tica da Literatura em Engenharia de Software_ Teoria e PrÃ¡tica_B0733NCCS8.kfx
Unknown booktype kfx. Passing back to calibre unchanged
Added Revisão Sistemática da Literatura em Engenharia de Software Teoria e Prática B0733NCCS8 to db in: 1.7
Added 1 books in 2.3 seconds

**Comment by ElleKayEm** [comment]
For KFX files, you'll also need to install the KFX Input plugin.

**Comment by mbrenohd** [comment]
Many thanks to you!
