### ISSUE TITLE
How to strip images inside .azw.res? (AZW6 Support?)

### ISSUE THREAD

**Issue by choryuidentify** [apprenticeharper/DeDRM_tools#483]
Hi!
I have some Kindle Japanese Light Novel things. so I've convert these books using calibre and this plugin, but strangely book size (1.8M) is diffrent to Amazon's say (8M) and too small, and Image quality is bad.

I'm googling these problem, and finally I have get doubt to '.azw.res' file. This file is very big (6.2M) and someone says that file have encrypted HD-quality image.

I've attach my log below. 
Please told me, It really decrypt or strip .azw.res? if not, How to strip '.azw.res' file?

> calibre 3.21 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: ko
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 99.2372093023 x 102.576923077
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[2.09] main UI initialized...
[2.09] Hiding splash screen
[2.59] splash screen hidden
[2.59] Started up in 2.59 seconds with 1 books
Gather KFX-ZIP File Type (from KFX Input) 1.3.0: Importing C:/Users/sec/Documents/My Kindle Content/B01GE0U4GO_EBOK/B01GE0U4GO_EBOK.azw
KFX Input: File is not KFX format
DeDRM v6.6.0: Trying to decrypt B01GE0U4GO_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: [BOOK NAME MASKED]
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\sec\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\sec\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4108899827' and UserName '736563'
DeDRM v6.6.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: [BOOK NAME MASKED]
Got DSN key from database default_key_1
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
File is encoded with PID GNO83ag+HJ.
Decrypting. Please wait . . . . done
Decryption succeeded after 1.7 seconds
DeDRM v6.6.0: Saving 1 new key
DeDRM v6.6.0: Finished after 1.7 seconds
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added [BOOK NAME MASKED] to db in: 0.9
Added 1 books in 5.2 seconds

**Comment by ElleKayEm** [comment]
Sounds like it's an AZW6 file.  Those will have the book split into two files:  one for the text and AZW6 for the images.  Calibre will only import the main book file.  If you have an E-ink Kindle, you can download the book from the "Manage your content and devices" page for "download & transfer via USB."  This will give you a single AZW3 file.  This can be decrypted if you add the E-ink Kindle's serial number into the plugin customization.

**Comment by choryuidentify** [comment]
Okay... I just bought used Kindle Paperwhite 2. Thanks!

**Comment by ElleKayEm** [comment]
Not that I'm aware of...at least not with these tools right now.

**Comment by choryuidentify** [comment]
That's sad... I'll waiting that always!

**Comment by choryuidentify** [comment]
WOW! Finally! I've found tool from [this post](https://www.mobileread.com/forums/showpost.php?p=3114050&postcount=1145)!
Named 'DumpAZW6', It's works perfectly on .azw.res!

Dump steps like this;

1. Rename .azw.res to .azw6
2. Install python 2 (not 3!)
3. Don't know actually why, but Install PyCharm. cmd.exe dose not work. (It looks UTF-8 failure)
4. Make new project, copy code, and set argument file, and run.
5. Done!

**Comment by ElleKayEm** [comment]
Glad you figured it out.  And thanks for reporting back.

**Comment by apprenticeharper** [comment]
If anyone would like to try integrating DumpAZW6 into the tools, to produce a decrypted KF8 book that uses the high resolution images from the associated AZW6 file, I'd be delighted to receive a pull request.

**Comment by choryuidentify** [comment]
I make the patch for support this. Please test it guys!

**Comment by Darkwolf1515** [comment]
How exactly do I use this part of the plugin? I have no idea what im doing for AZW6

**Comment by choryuidentify** [comment]
@Darkwolf1515 What's your purpose? This issue are depends on image resolutions of Kindle book.

If yes, remove calibre DeDRM plugin and install this.
https://github.com/choryuidentify/DeDRM_tools/releases/tag/v6.6.3-patched

That plugin is based on old DeDRM (6.6.3). so can have bugs.

**Comment by ElleKayEm** [comment]
It isn't part of the official DeDRM plugin.  It's a separate Python script.

**Comment by Darkwolf1515** [comment]
> 
> 
> @Darkwolf1515 What's your purpose? This issue are depends on image resolutions of Kindle book.
> 
> If yes, remove calibre DeDRM plugin and install this.
> https://github.com/choryuidentify/DeDRM_tools/releases/tag/v6.6.3-patched
> 
> That plugin is based on old DeDRM (6.6.3). so can have bugs.

Right, I tried your version, wasn't able to make it work, left the file name as .azw.res, tried renaming to azw and azw6, nothing worked.

**Comment by ElleKayEm** [comment]
@Darkwolf1515 

What OS and how are downloading the book?

**Comment by Darkwolf1515** [comment]
> @Darkwolf1515 
> 
> 
> 
> What OS and how are downloading the book?

Windows 10, kindle, latest version which is probably my issue I'd say.

**Comment by ElleKayEm** [comment]
Yes, I think the older version of DeDRM choryidentify's version is based on will need at least Kindle for PC version 1.24 or earlier.

**Comment by Darkwolf1515** [comment]
> Yes, I think the older version of DeDRM choryuidentify's version is based on will need at least Kindle for PC version 1.24 or earlier.

Is there a safe way to get older versions?

And will they have any effect on quality?

**Comment by ElleKayEm** [comment]
There's info near the bottom of the first post here:  https://www.mobileread.com/forums/showthread.php?t=283371

Try looking for 1.17.

**Comment by ElleKayEm** [comment]
Older version of K4PC won't matter for AZW6 format.  Later versions allow the new KFX format and have a different DRM key.

**Comment by Darkwolf1515** [comment]
> 
> 
> Older version of K4PC won't matter for AZW6 format. Later versions allow the new KFX format and have a different DRM key.

Downgraded, wont download the higher quality version. Gonna try the powershell script.

**Comment by Darkwolf1515** [comment]
> 
> 
> > Older version of K4PC won't matter for AZW6 format. Later versions allow the new KFX format and have a different DRM key.
> 
> Downgraded, wont download the higher quality version. Gonna try the powershell script.

Doing this also refuses to download the higher quality images, guess I just have to hope this plugin gets updated.

**Comment by ElleKayEm** [comment]
Hmm, I guess K4PC 1.17 is too old.  Possibly 1.24 would work, but I don't know the info to find a valid copy of that version.

**Comment by Darkwolf1515** [comment]
> 
> 
> Hmm, I guess K4PC 1.17 is too old. Possibly 1.24 would work, but I don't know the info to find a valid copy of that version.

Nope sadly, .res

**Comment by ElleKayEm** [comment]
Maybe use kindlekey.py from DeDRM 6.8.0.

**Comment by choryuidentify** [comment]
> 
> 
> > Hmm, I guess K4PC 1.17 is too old. Possibly 1.24 would work, but I don't know the info to find a valid copy of that version.
> 
> Nope sadly, .res

I'm using Kindle 1.28 (yeah, pretty recent version) with my patched plugin, installed on Calibre 4.21 64bit. old Kindle for Windows didn't download resource file.
Make sure your book is really download spllited book (Book directory must be contains .azw, .azw.res both). Some books are not spllited. Compare book file size and Kindle store's book size.

and, One directory must has just one .azw.res. more than one, Image merge will be skipped.

My patched plugin is based on old version, so may can't load Kindle decrypt key properly. so I recommand install old Kindle, login, and test decrypting. If decrypted book successfully, upgrade to recent Kindle and test merging.

My working process is this (tested now); 
1. Download book using Kindle
2. Going to books directory, commonly C:\Users\<username>\Documents\My Kindle Content\
3. Going sub-directory, contains downloaded book. commonly latest created directory.
4. Check 2 (or 3) files. Just need .azw and .azw.res
5. Drag n Drop .azw file into Calibre.
6. Books are automatically decrypted and merged. Check books size. Book size of calibre = .azw + .azw.res (can differ 1~2mb. because on merge process, lower resolution images are removed.)

If don't working after this steps, Trying debug mode of Calibre and reporting back the log.

Thank you for interest my patch!
Good luck!

**Comment by Darkwolf1515** [comment]
> 
> 
> > > Hmm, I guess K4PC 1.17 is too old. Possibly 1.24 would work, but I don't know the info to find a valid copy of that version.
> > 
> > 
> > Nope sadly, .res
> 
> I'm using Kindle 1.28 (yeah, pretty recent version) with my patched plugin, installed on Calibre 4.21 64bit. old Kindle for Windows didn't download resource file.
> Make sure your book is really download spllited book (Book directory must be contains .azw, .azw.res both). Some books are not spllited. Compare book file size and Kindle store's book size.
> 
> and, One directory must has just one .azw.res. more than one, Image merge will be skipped.
> 
> My patched plugin is based on old version, so may can't load Kindle decrypt key properly. so I recommand install old Kindle, login, and test decrypting. If decrypted book successfully, upgrade to recent Kindle and test merging.
> 
> My working process is this (tested now);
> 
>     1. Download book using Kindle
> 
>     2. Going to books directory, commonly C:\Users<username>\Documents\My Kindle Content\
> 
>     3. Going sub-directory, contains downloaded book. commonly latest created directory.
> 
>     4. Check 2 (or 3) files. Just need .azw and .azw.res
> 
>     5. Drag n Drop .azw file into Calibre.
> 
>     6. Books are automatically decrypted and merged. Check books size. Book size of calibre = .azw + .azw.res (can differ 1~2mb. because on merge process, lower resolution images are removed.)
> 
> 
> If don't working after this steps, Trying debug mode of Calibre and reporting back the log.
> 
> Thank you for interest my patch!
> Good luck!

Downgraded to 1.28. doesnt work sadly, just imports forever. Thanks for all the help, but I guess im just hoping someday there will be another way to do it.
