### ISSUE TITLE
Not DeDRM

### ISSUE THREAD

**Issue by guram1** [apprenticeharper/DeDRM_tools#487]
I have done everything as described. Also installed  KFX input. Also I installed python.
I have kindle paperwhite. I downloaded book from amazon. I deleted book after install that plugin and I imported again. I also import new book. I also import serial number in plugin configuration. I tried convert or opening book directly  from Calibre but no success. Please help me to DeDRM.
Thank you.

**Comment by ElleKayEm** [comment]
Did you mean to close this issue?

Post a log if you're still having problems:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
