### ISSUE TITLE
was working in old computer... then it stopped

### ISSUE THREAD

**Issue by trehjgf3** [apprenticeharper/DeDRM_tools#488]
Calibre and deDRM plugin were working fine. I got a new computer, moved all my files... I don't know if this was causing the issue. BUT then I re-installed and updated everything. No luck. Then I erased all old files and reinstalled everything again. Error in Calibre still says book has DRM. Log below. Thanks for your help.

calibre Debug log
calibre 3.21  embedded-python: True is64bit: True
Darwin-17.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0)
calibre 3.21  embedded-python: True is64bit: True
Darwin-17.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.21] splash screen shown
[0.21] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[1.17] main UI initialized...
[1.17] Hiding splash screen
[1.23] splash screen hidden
[1.24] Started up in 1.24 seconds with 18 books
objc[77733]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff950bab68) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11eae0cd8). One of the two will be used. Which one is undefined.
Gather KFX-ZIP File Type (from KFX Input) 1.3.0: Importing /Users/mejias/Library/Application Support/Kindle/My Kindle Content/B06XK9CTW3_EBOK.azw
KFX Input: File is not KFX format
DeDRM v6.6.0: Trying to decrypt B06XK9CTW3_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: ******
Found 8 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.0: Failed to decrypt with error: No key found in 8 keys tried.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.6.0: Exception when getting default Kindle Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
  File "site-packages/calibre/customize/zipplugin.py", line 183, in load_module
  File "calibre_plugins.dedrm.kindlekey", line 1238, in <module>
  File "calibre_plugins.dedrm.kindlekey", line 1233, in _load_crypto
  File "calibre_plugins.dedrm.kindlekey", line 1147, in _load_crypto_libcrypto
  File "lib/python2.7/ctypes/__init__.py", line 362, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
	/usr/local/lib/libcrypto.dylib: mach-o, but wrong architecture
	/usr/local/lib/libcrypto.dylib: mach-o, but wrong architecture
DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Global Discontents: Conversations on the Rising Threats to Democracy (American Empire Project) to db in: 0.0
Added 1 books in 0.7 seconds
Worker Launch took: 0.0906119346619

**Comment by ElleKayEm** [comment]
Looks like you're having the same problem as issue #97.  Apprentice Harper advised deleting this file:

/usr/local/lib/libcrypto.dylib

And that solved the problem in that case.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
