### ISSUE TITLE
Kobo Desktop 3.19.3665 support

### ISSUE THREAD

**Issue by 13xforever** [apprenticeharper/DeDRM_tools#49]
Hello.
It looks like Kobo devs are onto us, so they changed the master key generation in version 3.19.
Basically, you can use string `88b3a2e13` as a new salt.

[My version](/13xforever/DeDRM/blob/master/Drm/Format/Epub/KoboMasterKeys.cs)

**Comment by apprenticeharper** [comment]
Many thanks. I hope to have the tools updated shortly.
