### ISSUE TITLE
Thoughts on project directory structure

### ISSUE THREAD

**Issue by wzyboy** [apprenticeharper/DeDRM_tools#491]
Currently there are a lot of identical files in the project, namely files in these three directories:

- `./DeDRM_calibre_plugin/DeDRM_plugin/`
- `./DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/`
- `./DeDRM_Windows_Application/DeDRM_App/DeDRM_lib/lib/`

are mostly the same, except for a few more files in the Macintosh directory.

Every time a contributor wants to make a change, they needs to sync the change among these three directories. This is not good for either writing or reviewing code.

Could we think of a way to re-use the code so that only one file would appear in Git history? I would suggest that we use `Makefile` or `setup.py` or `github_release.sh`, "freezing" the the source code into tarballs / zip files only when releasing a new version.

How do you like it?

**Comment by apprenticeharper** [comment]
I would welcome a nice python script (or similar) that used a single source and generated the plugin, Mac and Windows applications.  If it also bundled them up with the obok plugin and other tools into the distribution zip, that would be splendid.

**Comment by wzyboy** [comment]
I have opened up a pull request to address this issue: https://github.com/apprenticeharper/DeDRM_tools/pull/502

**Comment by apprenticeharper** [comment]
Many thanks. Now integrated, and I'm giving a 6.6.1 release a go, using your fix for the lzma import bug.
