### ISSUE TITLE
How do I install a plugin that contains no .exe file or installer?

### ISSUE THREAD

**Issue by Tarakanza** [apprenticeharper/DeDRM_tools#494]
Hello.
I just downloaded something I cannot get to work.
Where do I stick all those folders in the Calibre root folder?

Thank you.

**Comment by j-howell** [comment]
The main DeDRM plugin is named "DeDRM_plugin.zip" and can be found in the "DeDRM_calibre_plugin" folder of the overall zip file.

For instructions on plugin installation see the topic "How do I install a plugin manually?" in
https://www.mobileread.com/forums/showthread.php?t=118680
