### ISSUE TITLE
dedrm not working when loading azw ebook from amazon on win 10 pc into Calibre

### ISSUE THREAD

**Issue by alwinstardust** [apprenticeharper/DeDRM_tools#496]
OS : win 10 1703
Calibre version 3.22.1
deDRM 6.6.0

azw file downloaded from Website ( amazon account ) 
Please help 

logfile Calibre of conversion attempt 
calibre Debug log
calibre 3.22.1 Portable embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.22.1 Portable embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[2.25] main UI initialized...
[2.25] Hiding splash screen
[2.25] splash screen hidden
[2.25] Started up in 2.25 seconds with 162 books
Storage number map:
{(7L, 0L): [(1L, 'C')],
 (7L, 1L): [(1L, 'D')],
 (7L, 2L): [(1L, 'F')],
 (7L, 3L): [(1L, 'E')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\G090G105711603A0&0: StorageDeviceNumber(type=7L, number=3L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=15)
{u'drive_letters': ['E'],
 u'pnp_id_map': {'E': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#g090g105711603a0&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'E': (3L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: E:\ documents
DEBUG:    0.2 USBMS: scan from root False E:\documents
DEBUG:    0.5 USBMS: count found in cache: 155, count of files in metadata: 155, need_sync: False
DEBUG:    0.5 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.5 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.5 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 155
DeviceJob: set_books_in_library finished: time= 0.00999999046326
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 1 Get device information finished
No details available.
Job: 3 Get list of books on device finished
No details available.
Job: 2 Set library information finished
No details available.
DeDRM v6.6.0: Trying to decrypt Limit_ Roman (German Edition) (1).azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Limit: Roman (German Edition)
Found 6 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.0: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\mattrupp\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\mattrupp\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1323827866' and UserName '6d61747472757070'
DeDRM v6.6.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Limit: Roman (German Edition)
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Limit: Roman (German Edition) to db in: 0.7
Added 1 books in 1.7 seconds

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) and enter its serial number into the plugin customization.

**Comment by alwinstardust** [comment]
Hi ElleKayEm

Txs so much


This helped  I added the Sn of my kindle paperwhite o the plugin and then transferred the downloaded .azw3 files to this kindle device in calibre

From there I could bring it back s a deDRM ed file into the calibre PC library where I could read and convert it to epub

Great job

Thanks for your help

Kind Regards
Matthias

**Comment by ElleKayEm** [comment]
Now that the serial number is in there, you should be able to just add the books to calibre to DeDRM them.  If you're all set, you can close the issue.
