### ISSUE TITLE
macOS, .azw book imported but ... not converted

### ISSUE THREAD

**Issue by rsspdx** [apprenticeharper/DeDRM_tools#497]
I've used DeDRM with Calibre on the Mac for .azw books with no problem. Recently I had to uninstall/reinstall and trash my Calibre Library. 

Now when I import an .azw book, the KFX version appears in the library and I have to use "Convert books" to convert it. Before, it converted on being added to the library, which I think is the normal behavior. 

I cannot find a log (it's not on the Desktop), or I would have pasted it.

**Comment by ElleKayEm** [comment]
No, it doesn't normally convert when added.  Maybe there's a way to get calibre to do that, but I don't know.  If you're adding from Kindle for Mac, the extension will change from the generic AZW to AZW3, MOBI, or whatever the actual format is.

Sounds like it's behaving as expected, but here's how to post a log if needed:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by rsspdx** [comment]
The readme, and my experience three days ago, believe otherwise. From the readme:

Once installed and configured, you can simply add a DRM book to calibre and the DRM-free version will be imported into the calibre database. Note that DRM removal only occurs on IMPORT not on CONVERSION or at any other time. If you have already imported DRM books you'll need to remove them from calibre and re-import them.

**Comment by ElleKayEm** [comment]
You're talking about removing the DRM?  Yes, that happens when adding the book.  I thought you were talking about converting to another format.  If you're unable to remove the DRM, then post a log.

**Comment by j-howell** [comment]
Books normally import in whatever format they happen to be in. If previously books imported in MOBI or AZW3 format and now they import in KFX format that means that the Kindle for Mac program on your system has updated to a newer version with KFX support.

You can read more abut how to handle this here: [Dealing with Kindle for PC/Mac 1.19 and KFX in calibre](https://www.mobileread.com/forums/showthread.php?t=283371)

**Comment by rsspdx** [comment]
Ah, got it. Thank you. Lovely little bit of software. I like paying for books. I don’t like the Kindle app.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
