### ISSUE TITLE
Error removing DRM from within an LXC container

### ISSUE THREAD

**Issue by MikeStromberg** [apprenticeharper/DeDRM_tools#498]
I'm sure this isn't a bug in DeDRM, but I'm hoping you can help. I have an installation of Calibre on my Prosmox file server in an Ubuntu LXC with docker using the aptalca/docker-rdp-calibre docker. This is a change from my former setup of Ubuntu server running docker where everything worked fine. When building this new setup I had to reinstall everything, and while it appears to work, the drm can't be removed. I imported the key from my desktop PC where I download the books to kindle for PC as I've always done.

I'm wondering if the extra  layer of abstraction is causing confusion? Any ideas how to cope with this?
Sorry I couldn't past the error message. Since my view is from inside xrdp, I don't have a  way (or don't know how anyway) to get to the clipboard. 

edit: attachment didn't work. I have to stich  12 screenshots together. to be continued.
![snap 2018-04-28 at 12 32 45](https://user-images.githubusercontent.com/20544113/39399263-5423f7c6-4ae0-11e8-8108-62201d8eae1c.png)

**Comment by ElleKayEm** [comment]
I have no idea why it's not working.  But is there some reason you don't remove the DRM on the desktop PC, and then just add the already DRM-free books to calibre on the file server?

**Comment by apprenticeharper** [comment]
please open a new issue if you still need help.
