### ISSUE TITLE
Failing on import but also saying it found more than 1 key?

### ISSUE THREAD

**Issue by HFC3** [apprenticeharper/DeDRM_tools#499]
I've entered my Kindle (touch g5.3.7.3) s/n into DEDRM plugin (saved restarted).  But when I try to import any DRM's azw3 file, file is not "fixed."  Can't see anything obvious except that it says it found 2 keys - I only tried to import 1 file; can they have multiple keys?

Import file was purchased from Amazon, device is named "HFCKindle" in Amazon, and ebook was manually downloaded and transferred to Kindle (through Calibre).  Why would it say "no key found" when I do (confirmed) have my Kindle S/N defined in plugin (e-Ink Kindle).

Device has NEVER been connected to WiFi (to prevent lock screen commercials and to prevent Amazon indirect access)

Does AMAZON use a different DRM key if the device is named, other than s/n?  I've quadrupled checked s/n on device and I do have it entered correctly (Kindle->Settings->Device Info->Serial Number 801114071457xxxx.  s/n has 2 trailing alpha - tried with and without those, no luck.

I do NOT have Kindle for PC installed on PC (never read on PC, only kindle) - testing DeDRM by attempting to read in Calibre.

Suggestions?

DEBUG LOG
calibre 2.85.1 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 6, 0) && Fantastic Fiction (1, 2, 0) && Kobo Books (1, 3, 0) && Goodreads (1, 1, 13) &&
    Fantastic Fiction Adults (1, 0, 4) && FictionDB (1, 0, 10) && Barnes & Noble (1, 2, 14)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Starting up...
Started up in 5.03 seconds with 672 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xe5y=\xdb\x92\xf5N\xbf\xad\xe2X\xc2t\xa7)x<\xfd\xe8\xe6\x95\xf6!.\xb5%\x93\xf0\xf3\xa58Y',
    'C:\\Users\\Harry\\Downloads\\The Osterman Weekend - Ludlum, Robert.azw3']
 
DeDRM v6.6.0: Trying to decrypt The Osterman Weekend - Ludlum, Robert.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Osterman Weekend: A Novel
Found 2 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Harry\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository:
    https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
Try copy and paste of the serial number from your "Content and Devices" page on Amazon, removing any spaces.  Those things are hard to read off the Kindle itself.  I suspect that first 8 is actually a B.

**Comment by HFC3** [comment]
Brilliant - I didn't even know Amazon had the s/n avail through devices.  And, you're right - it was a "B" not an 8.
Works like a charm now.
Thank you ElleKayEm

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
