### ISSUE TITLE
Found KFX key, but still somehow failed

### ISSUE THREAD

**Issue by p1r473** [apprenticeharper/DeDRM_tools#500]
I have calibre dedrm 6.6.0 installed, and the kfx input plugin 1.3. 
I bought some Amazon books.

When i drag the azw file in, it is still locked by drm (can't convert to epub). However, I think it did find the key.

Here is my Calibre log:

calibre Debug log
calibre 3.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0) && Kobo Utilities (2, 6, 0) && KePub Metadata Writer (2, 7, 1) && Obok DeDRM (6, 5, 3) && KePub Metadata Reader (2, 7, 1) && KoboTouchExtended (3, 0, 2)
calibre 3.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0) && Kobo Utilities (2, 6, 0) && KePub Metadata Writer (2, 7, 1) && Obok DeDRM (6, 5, 3) && KePub Metadata Reader (2, 7, 1) && KoboTouchExtended (3, 0, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 101.44149766 x 101.6
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    0.8 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.8 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.8 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.8 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
[1.17] main UI initialized...
[1.17] Hiding splash screen
[7.62] splash screen hidden
[7.62] Started up in 7.62 seconds with 70 books
Gather KFX-ZIP File Type (from KFX Input) 1.3.0: Importing C:/Users/J/Documents/My Kindle Content/B0074CLJDO_EBOK/B0074CLJDO_EBOK.azw
KFX Input: Gathered 4 files as C:\Temp\calibre_kq1ip3\uyfbsf.kfx-zip
DeDRM v6.6.0: Trying to decrypt uyfbsf.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: uyfbsf
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.ef1ce29a-1039-4383-98c4-bb25d34756ed.voucher
DeDRM v6.6.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\J\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\J\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3796069554' and UserName '4a'
DeDRM v6.6.0: Found 1 new key
Decrypting KFX-ZIP ebook: uyfbsf
Got DSN key from database default_key_1
**Found 1 keys to try after 0.1 seconds**
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.ef1ce29a-1039-4383-98c4-bb25d34756ed.voucher
DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX File Type (from KFX Input) 1.3.0: Packaging C:\Temp\calibre_kq1ip3\uyfbsf.kfx-zip
Processing container: B0074CLJDO_EBOK.azw
Running file type plugin Package KFX File Type (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 52, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 118, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 205, in get_container
KFXDRMError: Book container B0074CLJDO_EBOK.azw has DRM and cannot be converted
KFX metadata reader activated for C:\Temp\calibre_kq1ip3\zhakbf_add_books\0\B0074CLJDO_EBOK.kfx-zip
Added Darksiders: The Abomination Vault: A Novel to db in: 0.4
Added 1 books in 1.3 seconds

**Comment by ElleKayEm** [comment]
This book was downloaded with the current installation of Kindle for PC?  On the same machine and user?

**Comment by p1r473** [comment]
Yes, that is correct
Downloaded it today. Current Kindle installation on this machine and user.

**Comment by ElleKayEm** [comment]
Hmm, I wonder if it's finding a key from an old installation.  I've seen a couple people mention that the latest K4PC was installing in a different location than before.

**Comment by p1r473** [comment]
Ding ding ding!
Yup, we have a winner!

I deleted all the old Amazon files out of appdata and did a full reinstall.
Cheers!
