### ISSUE TITLE
can't deDRM an ebook

### ISSUE THREAD

**Issue by fchaix** [apprenticeharper/DeDRM_tools#504]
I can't remove the DRMs from an ebook I bought in the bookeenstore.

Here is the log from calibre in debug mode, when I try to import the book : 
[tmpJEeryn.txt](https://github.com/apprenticeharper/DeDRM_tools/files/1989463/tmpJEeryn.txt)

**Comment by ElleKayEm** [comment]
It's unable to find your Adobe Digital Editions key.  Where is ADE installed and what version?
