### ISSUE TITLE
DeDrm books from Legimi site.

### ISSUE THREAD

**Issue by the4anoni** [apprenticeharper/DeDRM_tools#508]
Hello
Can you add support for books from there ?
https://www.legimi.pl/
Books that you buy don't have DRM.
However books that you download via subscription have DRM.
Anyone can help ?

**Comment by the4anoni** [comment]
But I only want to remove DRM to read these books in other app than legimi official app.

**Comment by ElleKayEm** [comment]
Sounds like if you buy them, you'll be all set without having to remove DRM.
