### ISSUE TITLE
Barnes&Noble wrong credentials

### ISSUE THREAD

**Issue by Inukinator** [apprenticeharper/DeDRM_tools#510]
I tried logging in to my B&N account, before purchasing anything, just to prep, and got a wrong Password or Username error. Could this be a bug, or is _a_ purchase _needed_ before I can retrieve a key?

Thanks for the great tool!

**Comment by Inukinator** [comment]
Nvm, I'm an international customer, and cannot get digital goods apperently

**Comment by ElleKayEm** [comment]
You can close the issue.
