### ISSUE TITLE
DeDRM remains :-(

### ISSUE THREAD

**Issue by alexdolgin1** [apprenticeharper/DeDRM_tools#511]
calibre Debug log
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0)
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 118.41774744 x 118.225454545
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
[5.66] main UI initialized...
[5.66] Hiding splash screen
[42.39] splash screen hidden
[42.39] Started up in 42.39 seconds with 7 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x0fXu\xad\xbb\xbd\x14Gn\xbc\xa6{\xf1\x1d\x83\x1b\xf9\xae\xe0\xab\x1c,\x1c\xff\x18\xe7\x10\xc2e\xb1W\xbe', 'C:\\Users\\My-Laptop\\Dropbox\\Books\\A Higher Loyalty_ Truth, Lies, and Leadership_B074J6F41V.kfx']
Gather KFX-ZIP File Type (from KFX Input) 1.3.0: Importing C:\Users\My-Laptop\Dropbox\Books\A Higher Loyalty_ Truth, Lies, and Leadership_B074J6F41V.kfx
KFX Input: Ignoring file not in a recognized directory structure
DeDRM v6.6.0: Trying to decrypt A Higher Loyalty_ Truth, Lies, and Leadership_B074J6F41V.kfx
Unknown booktype kfx. Passing back to calibre unchanged
KFX metadata reader activated for C:\Users\My-Laptop\Dropbox\Books\A Higher Loyalty_ Truth, Lies, and Leadership_B074J6F41V.kfx
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 97, in get_metadata
Exception: Failed to locate a KFX container with metadata
Added A Higher Loyalty Truth, Lies, and Leadership B074J6F41V to db in: 0.1
Added 1 books in 1.6 seconds
Worker Launch took: 0.603999853134
Job: 1 Convert book 1 of 1 (A Higher Loyalty Truth, Lies, and Leadership B074J6F41V) finished
Convert book 1 of 1 (A Higher Loyalty Truth, Lies, and Leadership B074J6F41V)
	Conversion options changed from defaults:
	  output_profile: 'kindle_pw'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\MY-LAP~1\\AppData\\Local\\Temp\\calibre_vysl4a\\jxyzdn.opf'
	Resolved conversion options
	calibre version: 3.23.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x070FD130>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x070FD510>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\MY-LAP~1\\AppData\\Local\\Temp\\calibre_vysl4a\\jxyzdn.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\MY-LAP~1\AppData\Local\Temp\calibre_vysl4a\xhr6f1.kfx
	Software versions: KFX Input 1.3.0, calibre 3.23, Windows-10-10.0.16299-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\MY-LAP~1\AppData\Local\Temp\calibre_vysl4a\xhr6f1.kfx
	Processing container: C:\Users\MY-LAP~1\AppData\Local\Temp\calibre_vysl4a\xhr6f1.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 97, in convert
	  File "calibre_plugins.kfx_input.__init__", line 191, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 71, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 118, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 205, in get_container
	KFXDRMError: Book container C:\Users\MY-LAP~1\AppData\Local\Temp\calibre_vysl4a\xhr6f1.kfx has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 100, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
Because KFX books consist of multiple files you need to add the book to calibre from the folder where it was downloaded so the KFX plugin can zip up all necessary files.

**Comment by alexdolgin1** [comment]
I just synced the laptop and the book resides in the Kindle files directory there. Deleted the book from the Calibre, opened from the laptop directory, still no go:
calibre Debug log
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0)
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 118.41774744 x 118.225454545
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.55] splash screen shown
[0.55] Initializing db...
[0.59] db initialized
[0.59] Constructing main UI...
[5.48] main UI initialized...
[5.48] Hiding splash screen
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'E')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\G090G10554160BCW&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=2)
{u'drive_letters': ['E'],
 u'pnp_id_map': {'E': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#g090g10554160bcw&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'E': (1L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: E:\ documents
Job: 1 Get device information finished
No details available.
Job: 2 Set library information finished
No details available.
DEBUG:    0.1 USBMS: scan from root False E:\documents
DEBUG:    0.3 USBMS: count found in cache: 29, count of files in metadata: 29, need_sync: False
DEBUG:    0.3 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 29
DeviceJob: set_books_in_library finished: time= 0.0360000133514
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
[11.22] splash screen hidden
[11.22] Started up in 11.22 seconds with 7 books
Job: 3 Get list of books on device finished
No details available.
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xe6\x93D\xf2\xfa\xf4*\x9a\xf5\xdd\x19\xdb}\xd0\xfc\x04\xd7'\xd7\xc9u\x12\xae\xf8\xab\x881\xc1\xfa\xc0\x0f\x14", 'C:\\Users\\My-Laptop\\Documents\\My Kindle Content\\A Higher Loyalty Truth, Lies, a - Unknown.kfx']
Gather KFX-ZIP File Type (from KFX Input) 1.3.0: Importing C:\Users\My-Laptop\Documents\My Kindle Content\A Higher Loyalty Truth, Lies, a - Unknown.kfx
KFX Input: Ignoring file not in a recognized directory structure
DeDRM v6.6.0: Trying to decrypt A Higher Loyalty Truth, Lies, a - Unknown.kfx
Unknown booktype kfx. Passing back to calibre unchanged
KFX metadata reader activated for C:\Users\My-Laptop\Documents\My Kindle Content\A Higher Loyalty Truth, Lies, a - Unknown.kfx
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 97, in get_metadata
Exception: Failed to locate a KFX container with metadata
Added A Higher Loyalty Truth, Lies, a to db in: 0.2
Added 1 books in 2.5 seconds
Worker Launch took: 0.591000080109
Job: 4 Convert book 1 of 1 (A Higher Loyalty Truth, Lies, a) finished
Convert book 1 of 1 (A Higher Loyalty Truth, Lies, a)
	Conversion options changed from defaults:
	  output_profile: 'kindle_pw'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\MY-LAP~1\\AppData\\Local\\Temp\\calibre_qyasgw\\5s6vcu.opf'
	Resolved conversion options
	calibre version: 3.23.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x06B8B0F0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x06B8B4D0>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\MY-LAP~1\\AppData\\Local\\Temp\\calibre_qyasgw\\5s6vcu.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\MY-LAP~1\AppData\Local\Temp\calibre_qyasgw\zemr6k.kfx
	Software versions: KFX Input 1.3.0, calibre 3.23, Windows-10-10.0.16299-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\MY-LAP~1\AppData\Local\Temp\calibre_qyasgw\zemr6k.kfx
	Processing container: C:\Users\MY-LAP~1\AppData\Local\Temp\calibre_qyasgw\zemr6k.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 97, in convert
	  File "calibre_plugins.kfx_input.__init__", line 191, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 71, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 118, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 205, in get_container
	KFXDRMError: Book container C:\Users\MY-LAP~1\AppData\Local\Temp\calibre_qyasgw\zemr6k.kfx has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 100, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
The file name isn't in the form of a book downloaded with Kindle for PC.  And it still has the error:

>Ignoring file not in a recognized directory structure

**Comment by j-howell** [comment]
> Gather KFX-ZIP File Type (from KFX Input) 1.3.0: Importing C:\Users\My-Laptop\Dropbox\Books\A Higher Loyalty_ Truth, Lies, and Leadership_B074J6F41V.kfx
> KFX Input: Ignoring file not in a recognized directory structure

Books in KFX format are composed of multiple files. As the first step in importing a book in KFX format into calibre, the KFX Input plugin locates all of the files that make up the book and combines them into a .kfx-zip file.

Based on your file name it looks like it came from an e-ink Kindle device. On that device there was also a folder with the same name and the extension ".sdr" containing the rest of the files that make up the book. It doesn't look like you copied the .sdr directory along with the main .kfx file.

**Comment by alexdolgin1** [comment]
Hmm, so I connected my Kindle to the laptop again, copied both the book file and the .sdr folder, deleted the previous version of the book and added the book again. It still opens up ok as the loan is not expired yet (have one day left) but when try to convert, get the same DRM error 
![image](https://user-images.githubusercontent.com/39286239/40058025-eae3c584-581d-11e8-8bc2-b49f5f7a2323.png)

**Comment by ElleKayEm** [comment]
These tools are intended for purchased books, not loans or rentals.

**Comment by WesternGun** [comment]
So, books borrowed for 10 days cannot get rid of DRM protection right? That makes sense..
