### ISSUE TITLE
Not DeDRMing KFX

### ISSUE THREAD

**Issue by dralbright** [apprenticeharper/DeDRM_tools#513]
calibre Debug log
calibre 3.23  embedded-python: True is64bit: True
Darwin-17.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.5.0', 'Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0) && Set KFX metadata (from KFX Output) (1, 18, 0) && KFX Output (1, 18, 0)
calibre 3.23  embedded-python: True is64bit: True
Darwin-17.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.5.0', 'Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0) && Set KFX metadata (from KFX Output) (1, 18, 0) && KFX Output (1, 18, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[2.77] main UI initialized...
[2.77] Hiding splash screen
[2.81] splash screen hidden
[2.81] Started up in 2.81 seconds with 312 books
2018-05-15 21:54:38.715 Calibre[38620:1621033] deliverNotificationWithTitle()
* Notification delivered.
Gather KFX-ZIP File Type (from KFX Input) 1.3.0: Importing /Users/dralbright/Downloads/Revelation Space_B001QL5MAA.kfx
KFX Input: Gathered 4 files as /var/folders/ds/5mgcx0kd2b5c50_glfnld9w00000gn/C/calibre_3.23.0_tmp_D37d7a/bdfR2I.kfx-zip
DeDRM v6.6.0: Trying to decrypt bdfR2I.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: bdfR2I
Found 2 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.0: Failed to decrypt with error: This book is licensed as PublicLibraryLending. These tools are intended for use on purchased books.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/dralbright/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011

{'bsd_drives': {'main': u'/dev/disk2s1'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/Applications/Boom 2.app': '/private/var/folders/ds/5mgcx0kd2b5c50_glfnld9w00000gn/T/AppTranslocation/B93C4DCE-D688-4AD5-BE59-DC3824653B7D',
               '/dev/disk1s1': '/',
               '/dev/disk1s4': '/private/var/vm',
               '/dev/disk2s1': '/Volumes/Kindle',
               'devfs': '/dev',
               'map -hosts': '/net',
               'map auto_home': '/home'}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.3 USBMS: scan from root False /Volumes/Kindle/documents
Job: 2 Set library information finished
No details available.
Job: 1 Get device information finished
No details available.
DEBUG:    1.4 USBMS: count found in cache: 137, count of files in metadata: 137, need_sync: False
DEBUG:    1.4 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    1.4 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    1.4 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 137
DeviceJob: set_books_in_library finished: time= 0.0199780464172
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Decrypted key file using IDString '01fbc5eb7940' and UserName 'dralbright'
DeDRM v6.6.0: Found 1 new key
Decrypting KFX-ZIP ebook: bdfR2I
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.6.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX File Type (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 52, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 118, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 205, in get_container
KFXDRMError: Book container Revelation Space_B001QL5MAA.kfx has DRM and cannot be converted
Package KFX File Type (from KFX Input) 1.3.0: Packaging /var/folders/ds/5mgcx0kd2b5c50_glfnld9w00000gn/C/calibre_3.23.0_tmp_D37d7a/bdfR2I.kfx-zip
Processing container: CR!F608QGEPQS1N59GJ9TRQ50HM8C65.kfx
Processing container: Revelation Space_B001QL5MAA.kfx
KFX metadata reader activated for /var/folders/ds/5mgcx0kd2b5c50_glfnld9w00000gn/C/calibre_3.23.0_tmp_D37d7a/yghIkS_add_books/0/Revelation Space_B001QL5MAA.kfx-zip

Any ideas? The .sdr folder is in the same directory as the .kfx.

**Comment by ElleKayEm** [comment]
As the log says:

>This book is licensed as PublicLibraryLending. These tools are intended for use on purchased books.

**Comment by dralbright** [comment]
Thanks for pointing that out! Turns out that loan expired over a year ago, but the book is still on my Kindle. So I had completely forgotten that it was a loan.

**Comment by ElleKayEm** [comment]
Yeah, it's easy to miss things in these long logs.  Unless you have another question, you can close the issue.
