### ISSUE TITLE
Android Kindle backup import does not work

### ISSUE THREAD

**Issue by schneidewind** [apprenticeharper/DeDRM_tools#514]
I followed the steps, installing ADB and created a backup of com.amazon.kindle as described.
What made me unsure is, that the android device asked, whether I wanted to set a password. I tried with and without, but the generated backup.ab just does not import correctly. 

Can you have a look please?

![error__dedrm_6_6_0_and_dedrm_6_6_0__add_new_kindle_for_android_key_and_dedrm_6_6_0__manage_kindle_for_android_keys_and_customize_dedrm](https://user-images.githubusercontent.com/18747989/40114861-b8ae2a90-590e-11e8-975c-0780349418f0.jpg)

**Comment by ElleKayEm** [comment]
Unfortunately, Amazon stopped allowing the creation of a proper backup file for Kindle for Android quite a while ago.  It may still work if you can install version 4.17 or earlier.

**Comment by schneidewind** [comment]
Thanks for the quick response! I found a kindle version 4.17, however it won't install on my android device. I am probably running the wrong android version for it to work. 

However, I am not yet positive as to how amazon encrypts the kindle books. Are they bound to the first or last device/app the books were downloaded with?

**Comment by schneidewind** [comment]
I found what I needed. 
The original problem was, that I did not use Kindle for Mac 1.17.
Once I did that I was able to convert all of my books. Thanks!

**Comment by ElleKayEm** [comment]
Each Kindle book is keyed to whichever device/app that it is downloaded to.
