### ISSUE TITLE
Also got a problem with the DeDRM-Tool

### ISSUE THREAD

**Issue by ghost** [apprenticeharper/DeDRM_tools#517]
![image](https://user-images.githubusercontent.com/39457752/40278236-b38ec61a-5c2d-11e8-9ab3-d83cb74042f9.png)

calibre Fehlerdiagnoseprotokoll
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 3.0
logicalDpi: 80.0 x 80.0
physicalDpi: 93.9653179191 x 94.2680412371
Using calibre Qt style: True
Starting up...
Loaded cached store plugin for: Legimi at version: 9
Loaded cached store plugin for: Mills and Boon UK at version: 3
Loaded cached store plugin for: Empik at version: 8
Loaded cached store plugin for: ebook.de at version: 5
Loaded cached store plugin for: Beam EBooks DE at version: 3
Loaded cached store plugin for: Publio at version: 9
Loaded cached store plugin for: Woblink at version: 14
Started up in 4.91 seconds with 7 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xd3#\rw:\xa22d\x0c\xe1\xbc\x92\xca\x81\x13\x87\xae\x94\x83^a\x82%\xe5= ^\xed\xb0\x1f\x96\x96', 'C:\\Users\\David Wagstyl\\Documents\\My Kindle Content\\B00STVSH66_EBOK\\B00STVSH66_EBOK.azw']
DeDRM v6.6.0: Trying to decrypt B00STVSH66_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.6.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\David Wagstyl\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\David Wagstyl\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '715957309' and UserName '4461766964205761677374796c'
DeDRM v6.6.0: Found 1 new key
DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B00STVSH66 EBOK to db in: 0.3
Added 1 books in 1.1 seconds

**Comment by ElleKayEm** [comment]
For KFX format you will also need the KFX Input plugin.

**Comment by apprenticeharper** [comment]
added to the FAQs
