### ISSUE TITLE
I updated DeDRM plugin and now not working

### ISSUE THREAD

**Issue by dudtwo** [apprenticeharper/DeDRM_tools#518]
Hi,

I just updated to the latest version of Calibre, ( calibre-3.23.0 ) on a Windows 10 PC, and then downloaded and installed the latest version of the DRM Removal Tools 6.6.0, (specifically the DeDRM_calibre_plugin ), in order to strip the DRM from my purchased Amazon Kindle book files (AZW) and import them into my Calibre Library.

I've done this before a number of times with various update releases over the years, but for some reason this time I am getting no further with my latest book purchase!

I read through the DeDRM_plugin_ReadMe file and followed the troubleshooting instructions within it, restarting Calibre in debug mode and generating the log file when trying to import this book into my Calibre library.

Any help would be much appreciated. 

Many thanks,

Sean.

calibre Debug log
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 68.8813559322 x 68.9246231156
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.08] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[1.75] main UI initialized...
[1.75] Hiding splash screen
[13.09] splash screen hidden
[13.09] Started up in 13.09 seconds with 95 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xf0H\xb4\x1eB\xf32\xf8-7\xf1h\x82\xbcj\x1c\xa4\xf2\xbf\xe6\xf7~\x8fF\xe2\x19\x06\x8a\r\x0b\x08\x84', 'K:\\MY KINDLE CONTENT\\B079WJ5PC8_EBOK.azw']
DeDRM v6.6.0: Trying to decrypt B079WJ5PC8_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Stories from the Messengers: Owls, UFOs and a Deeper Reality
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID CY9R2bXDIY.
Decrypting. Please wait . . . . done
Decryption succeeded after 1.7 seconds
DeDRM v6.6.0: Finished after 1.8 seconds
Added 0 books in 2.3 seconds
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "site-packages\calibre\db\backup.py", line 54, in run
  File "site-packages\calibre\db\backup.py", line 116, in do_one
  File "site-packages\calibre\db\cache.py", line 63, in call_func_with_lock
  File "site-packages\calibre\db\cache.py", line 1154, in clear_dirtied
  File "site-packages\calibre\db\backend.py", line 845, in execute
  File "c:\t\t\apsw-9hooel\apsw-3.13.0-r1\src\cursor.c", line 236, in resetcursor
CantOpenError: CantOpenError: unable to open database file

**Comment by ElleKayEm** [comment]
Hmm, the DRM removal seems to have worked, but then it doesn't add the book to calibre.  Try using 64-bit calibre.

**Comment by dudtwo** [comment]
I think I am already using the 64 bit version. I played around a bit with things and somehow I've got it working anyway, but thanks for the response, cheers!

**Comment by ElleKayEm** [comment]
Log says 32-bit.  Glad it started working.

**Comment by dudtwo** [comment]
My apologies sorry! I assumed 64 bit because my version of windows is 64 bit. And thank you once again for your help.
