### ISSUE TITLE
Suggestion: add "on_preprocess=True" in its __init__.py to make plugin usable in conversion

### ISSUE THREAD

**Issue by fireattack** [apprenticeharper/DeDRM_tools#519]
This is just suggestion, but I was wondering if it's possible to add `on_preprocess=True` in `__init__.py` of the calibre plugin (per [API documentation](https://manual.calibre-ebook.com/plugins.html#filetypeplugin)), so it will also be called when users are converting a book (instead only when adding book to calibre DB).

It will help with the Calibre's CLI tool `ebook-convert.exe`, make it be able to convert encrypted book directly to other formats. I have tried to modify `__init__.py` myself and it does work. It doesn't appear to have side effect (such as when converting a *no-DRM* azw3 book) either. 

You can see previous discussion about it [here](https://www.mobileread.com/forums/showthread.php?t=297100) (on MobileRead).

Thanks!

**Comment by ElleKayEm** [comment]
So does it leave the original format with DRM?

**Comment by fireattack** [comment]
If you mean the CLI tool ebook-convert.exe, it won't modify your input file in anyway.

**Comment by fireattack** [comment]
Just some clarification: I think that scenario will still be the same as now: assuming the plugin would be able to deDRM during both importing and converting, books will still be deDRMed when importing. So, "import DRMed ebooks into calibre" isn't really going to happen under normal usage.

But besides that, I have no strong argument, as I said it's just a suggestion for consideration. I understand supporting additional features will always be troublesome (and I appreciate it).

**Comment by fireattack** [comment]
Fixed by #1241 :+1:
