### ISSUE TITLE
problem with DRM from Kindle Ebook 

### ISSUE THREAD

**Issue by viv91** [apprenticeharper/DeDRM_tools#526]
I'm trying to convert a Kindle ebook in epub. I've legally downloaded the ebook from Amazon in my Amazon Kindle App for Desktop.
I hope you can help me!!

calibre Log di debug
calibre 3.25 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 4, 0) && DeDRM (6, 3, 4) && Package KFX File Type (from KFX Input) (1, 4, 0) && KFX metadata reader (from KFX Input) (1, 4, 0) && KFX Input (1, 4, 0)
calibre 3.25 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 4, 0) && DeDRM (6, 3, 4) && Package KFX File Type (from KFX Input) (1, 4, 0) && KFX metadata reader (from KFX Input) (1, 4, 0) && KFX Input (1, 4, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
[1.27] main UI initialized...
[1.27] Hiding splash screen
[22.94] splash screen hidden
[22.94] Started up in 22.94 seconds with 2 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['Y=7\x0f\n\x7f;\xb6\x91\x96t\x7f_\xda\n\n\xbbu\x84\x95U\xa3$\xd1\xe0}\xe8}\tC\xe6\x8d', 'D:\\Documents\\My Kindle Content\\B004UITPZO_EBOK\\B004UITPZO_EBOK.azw']
Gather KFX-ZIP File Type (from KFX Input) 1.4.0: Importing D:\Documents\My Kindle Content\B004UITPZO_EBOK\B004UITPZO_EBOK.azw
Gather KFX-ZIP File Type (from KFX Input): Gathered 3 files as C:\Users\viviana\AppData\Local\Temp\calibre_r66to8\kvirsu.kfx-zip
DeDRM v6.3.4: Trying to decrypt kvirsu.kfx-zip
Unknown booktype kfx-zip. Passing back to calibre unchanged
Package KFX File Type (from KFX Input) 1.4.0: Packaging C:\Users\viviana\AppData\Local\Temp\calibre_r66to8\kvirsu.kfx-zip
Processing container: B004UITPZO_EBOK.azw
Running file type plugin Package KFX File Type (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 52, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 118, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 205, in get_container
KFXDRMError: Book container B004UITPZO_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\viviana\AppData\Local\Temp\calibre_r66to8\l6z1bi_add_books\0\B004UITPZO_EBOK.kfx-zip
Added Romanzo d'una signorina per bene (Italian Edition) to db in: 2.0
Added 1 books in 2.9 seconds
Worker Launch took: 0.206999778748
Job: 1 Converti libro 1 di 1 (Romanzo d'una signorina per bene (Italian Edition)) finished
Converti libro 1 di 1 (Romanzo d'una signorina per bene (Italian Edition))
	Conversion options changed from defaults:
	  output_profile: 'sony'
	  read_metadata_from_opf: u'C:\\Users\\viviana\\AppData\\Local\\Temp\\calibre_r66to8\\1gr6wo.opf'
	  verbose: 2
	  cover: u'C:\\Users\\viviana\\AppData\\Local\\Temp\\calibre_r66to8\\nmamgv.jpeg'
	Resolved conversion options
	calibre version: 3.25.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\viviana\\AppData\\Local\\Temp\\calibre_r66to8\\nmamgv.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000027CDB5557B8>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.SonyReaderOutput object at 0x0000027CDB6EC160>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\viviana\\AppData\\Local\\Temp\\calibre_r66to8\\1gr6wo.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\viviana\AppData\Local\Temp\calibre_r66to8\oelrjx.kfx-zip
	Software versions: KFX Input 1.4.0, calibre 3.25 [64bit], Windows-10-10.0.17134-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\viviana\AppData\Local\Temp\calibre_r66to8\oelrjx.kfx-zip
	Processing container: B004UITPZO_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 97, in convert
	  File "calibre_plugins.kfx_input.__init__", line 191, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 71, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 118, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 205, in get_container
	KFXDRMError: Book container B004UITPZO_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 100, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by j-howell** [comment]
You need to update your DeDRM plugin. Only the latest version (6.6.0] can handle KFX format.

**Comment by ElleKayEm** [comment]
You need to update the DeDRM plugin to 6.6.0 for KFX books.

**Comment by viv91** [comment]
@j-howell @ElleKayEm thanks a lot for your reply and help! It was actually that! I've downloaded the updated plug-in version and it works now! 
I've found also very useful this post: [https://www.geoffstratton.com/remove-drm-amazon-kindle-books]
