### ISSUE TITLE
Problem - Trying to remove DRM from my Kindle eBook

### ISSUE THREAD

**Issue by djm1234** [apprenticeharper/DeDRM_tools#528]
Hi,

I am having problems  Removing DRM from Kindle Ebook

PC - Win10, same PC and account  being used for Kindle-pc & Calibre

I am trying to use my own legitimate download of 
ITIL Intermediate Certification Companion Study Guide_ Intermediate ITIL Service Lifecycle Exams.azw3 as I have reached the "copy limit" for this Kindle book

I am new to this and just installed Calibre 64 and installed plugin deDRM 6.6.0

Downloaded my Amazon kindle book (from Amazon with “download and transfer via USB” )- 
ITIL Intermediate Certification Companion Study Guide_ Intermediate ITIL Service Lifecycle Exams.azw3

Used Calibre "Add Books" button to upload.

The book uploaded but reports "locked by DRM" when I try to open it

Log indicates:
calibre Debug log
calibre 3.25 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.25 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[4.88] main UI initialized...
[4.88] Hiding splash screen
[16.97] splash screen hidden
[16.97] Started up in 16.97 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['2\xb0Dh\xfc\xc4\xdeGv\xa9\x94\xdeKQ\x05\xce\xcf\xceM\x96k\xc0\x1c\xf2\xc77\xc9\xc0\r\xd1q\x19', 'C:\\Users\\david\\Downloads\\_\\ITIL Intermediate Certification Companion Study Guide_ Intermediate ITIL Service Lifecycle Exams.azw3']
DeDRM v6.6.0: Trying to decrypt ITIL Intermediate Certification Companion Study Guide_ Intermediate ITIL Service Lifecycle Exams.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: ITIL Intermediate Certification Companion Study Guide: Intermediate ITIL Service Lifecycle Exams
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\david\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\david\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3497644429' and UserName '6461766964'
DeDRM v6.6.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: ITIL Intermediate Certification Companion Study Guide: Intermediate ITIL Service Lifecycle Exams
Got DSN key from database default_key_1
Found 4 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v6.6.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added ITIL Intermediate Certification Companion Study Guide: Intermediate ITIL Service Lifecycle Exams to db in: 3.5
Added 1 books in 6.4 seconds
Worker Launch took: 0.430000066757

Any advice?

D

**Comment by ElleKayEm** [comment]
When downloading for transfer via USB, you need to choose an E-ink Kindle (not a Fire) for the device and add its serial number to the E-ink Kindle section of the plugin customization.

**Comment by djm1234** [comment]
Tks
