### ISSUE TITLE
top-level __init__.py file

### ISSUE THREAD

**Issue by TrisaH** [apprenticeharper/DeDRM_tools#529]
When trying to install the plugin, I get the message: Plugin ... is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Then you're trying to install the wrong file.  Unzip DeDRM_tools_6.6.1.zip.  Look in the DeDRM_calibre_plugin folder.  Load DeDRM_plugin.zip.

**Comment by tartley** [comment]
I think we can close this issue.
