### ISSUE TITLE
cannot convert drm file from eink reader

### ISSUE THREAD

**Issue by clark131** [apprenticeharper/DeDRM_tools#530]
calibre Debug log
calibre 3.25  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && EpubSplit (2, 4, 0)
calibre 3.25  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && EpubSplit (2, 4, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[1.84] main UI initialized...
[1.84] Hiding splash screen
[1.84] splash screen hidden
[1.85] Started up in 1.85 seconds with 179 books
2018-06-03 14:44:24.526 Calibre[4996:949384] deliverNotificationWithTitle()
* Notification delivered.
DeDRM v6.6.1: Trying to decrypt The Scientific Revolution in Skin Care_B01N6GJ803.kfx
Unknown booktype kfx. Passing back to calibre unchanged

{'bsd_drives': {'main': u'/dev/disk4s1'},
 'drives': {'main': '/Volumes/Kindle 1'},
 'mount_map': {'/dev/disk1': '/',
               '/dev/disk4s1': '/Volumes/Kindle 1',
               'devfs': '/dev',
               'map -hosts': '/net',
               'map auto_home': '/home'}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle 1/ documents
DEBUG:    0.5 USBMS: scan from root False /Volumes/Kindle 1/documents
Job: 2 Set library information finished
No details available.
Job: 1 Get device information finished
No details available.
DEBUG:    1.4 USBMS: count found in cache: 310, count of files in metadata: 310, need_sync: False
DEBUG:    1.4 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    1.4 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    1.4 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 310
DeviceJob: set_books_in_library finished: time= 0.0134899616241
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Added The Scientific Revolution in Skin Care B01N6GJ803 to db in: 0.0
Added 1 books in 0.9 seconds

**Comment by ElleKayEm** [comment]
For KFX books you'll also need to install the KFX Input plugin.

**Comment by clark131** [comment]
@ElleKayEm It works after I install KFX plugin, thank you a lot!

**Comment by ElleKayEm** [comment]
If you're all set, you can close this issue.
