### ISSUE TITLE
Cannot deDRM a Kindle book

### ISSUE THREAD

**Issue by JPRidgeway** [apprenticeharper/DeDRM_tools#532]
[tmphbyaoa.txt](https://github.com/apprenticeharper/DeDRM_tools/files/2069316/tmphbyaoa.txt)
The following log is generated during an attempt to deDRM a file purchased off amazon.co.jp from my Kindle library. The sample version of the same file is deDRM'ed without any issue. The system is Windows 10.

**Comment by ElleKayEm** [comment]
Was this copy downloaded to the installation of Kindle for PC which is on the same machine and user as calibre with DeDRM?
