### ISSUE TITLE
DeDRM not working with kfx book

### ISSUE THREAD

**Issue by Khris777** [apprenticeharper/DeDRM_tools#533]
I'm on Windows 7 64bit running calibre 64bit latest version.

I have installed the KFX input plugin and the DeDRM plugin.

I'm importing the book directly from my kindle and the drm code is set in the eInk Kindle ebooks section of the DeDRM settings.

The debug output when importing the book is just this:

```
Running file type plugin Package KFX File Type (from KFX Input) failed with trac
eback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugi
ns
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 52, in convert_to_single
_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 118, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 205, in get_container
KFXDRMError: Book container book.kfx has DRM and cannot be converted
```

DeDRM has been successfully loaded on startup though, but this is the only time DeDRM gets ever mentioned in the whole log:

```
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 4, 0) && DeDRM (6, 5, 5) && Package KFX File Type (from KFX Input) (1, 4, 0) && KFX metadata reader (from KFX Input) (1, 4, 0) && KFX Input (1, 4, 0)
```

Why is DeDRM not removing the DRM from this file while importing? Am I missing something vital?

(Of course I did restart calibre several times and added and removed the book several times.)

**Comment by ElleKayEm** [comment]
Looks like you need to update DeDRM.  You have 6.5.5.  First version that can deal with KFX was 6.6.0.  Latest release is 6.6.1.

**Comment by Khris777** [comment]
That's what happens when you don't install from the main site I guess.

Thank you, it works fine now.

**Comment by ElleKayEm** [comment]
If you're all set, you can close this issue.
