### ISSUE TITLE
Can't strip DRM: iMac, Sierra 10.13.4

### ISSUE THREAD

**Issue by Muttley49** [apprenticeharper/DeDRM_tools#535]
Updated Calibre and downloaded 6.6.1. Installed.  Using iMac with Sierra 10.13.4.  Source ebook on Kindle App on iMac. When book placed into Calibre nothing changes and does not even indicate it is a book. Debug file below:
calibre Debug log
calibre 3.25  embedded-python: True is64bit: True
Darwin-17.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.5.0', 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 3)
calibre 3.25  embedded-python: True is64bit: True
Darwin-17.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.5.0', 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.000001637 x 109.000001637
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[1.39] main UI initialized...
[1.39] Hiding splash screen
[1.42] splash screen hidden
[1.43] Started up in 1.43 seconds with 149 books
DeDRM v6.5.3: Trying to decrypt B003XT60E0_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/charlesfrakes/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'cdfe908d2a4b' and UserName 'charlesfrakes'
DeDRM v6.5.3: Found 1 new key
DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 427, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 284, in get_metadata
  File "site-packages/calibre/ebooks/metadata/mobi.py", line 494, in get_metadata
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 284, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 312, in identity
MobiError: Unknown book type: Åƒﬁùå#
Added B003XT60E0 EBOK to db in: 0.0
Added 1 books in 0.8 seconds

**Comment by j-howell** [comment]
You mention that you downloaded version 6.6.1, but do not say anything about installing it.

Your log shows that you have DeDRM 6.5.3 installed. In order to import books in KFX format you need at least DeDRM 6.6.0 and also you need to have the KFX Input plugin for calibre installed.

**Comment by Muttley49** [comment]
Thanks for your quick help.  I had deleted 6.5.3 and installed 6.6.1, but obviously there was an error somewhere.  I have downloaded and installed 6.6.1 CORRECTLY now. Thanks for pointing that out. Where do I find the KFX plugin?—I do not see it in Calibre
Thanks
Chuck

**Comment by j-howell** [comment]
It should be available in the list of plugins that can be installed in calibre under preferences. Aslo in the post above yours, the plugin name is actually a link to the Mobile Read thread for that plugin.

**Comment by Muttley49** [comment]
John, you were absolutely correct.  I was looking in the 'wrong places'.  Installed!   Everything works great.   Greatly appreciate your help.

**Comment by j-howell** [comment]
Glad you got it working.

**Comment by ElleKayEm** [comment]
@Muttley49 
If you're all set, you can close the issue.
