### ISSUE TITLE
AWZ3 works, AWZ doesn't

### ISSUE THREAD

**Issue by Youjair** [apprenticeharper/DeDRM_tools#536]
I've tried a several times and read the FAQ, but the conversion from AWZ still return wrong things.

Debug report:

calibre Registro de depuración
calibre 3.25 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.25 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.453781513 x 102.358208955
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
[1.17] main UI initialized...
[1.17] Hiding splash screen
[23.17] splash screen hidden
[23.17] Started up in 23.17 seconds with 4 books
stdout+stderr from file dialog helper: ['', '']
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xd6)\x83\xa0P\xb7|\xe8\xc4\xd0\xc2d\xf6\xd1\x8d\x81\xbe|\xcc\xc2\x98\xceS\x9aC\xfe\xa8\x16L\x8e \x8d', 'D:\\Users\\Usuario\\Documentos\\Libros\\My Kindle Content']
DeDRM v6.6.1: Trying to decrypt B009WWEPQW_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.6.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Usuario\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Usuario\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3766232123' and UserName '5573756172696f'
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 427, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: ÄÞŒ#
Added CR!F3YKT9RJD51R78Y0KT22X37NEBP2.azw to db in: 4.0
Added B009WWEPQW EBOK to db in: 3.4
Added 2 books in 7.7 seconds

**Comment by ElleKayEm** [comment]
You need to install the [KFX Input](https://www.mobileread.com/forums/showthread.php?t=291290) plugin as well.

**Comment by Youjair** [comment]
I installed the last version, which should include that input too.

**Comment by ElleKayEm** [comment]
The log only shows the DeDRM plugin.  KFX Input is a separate plugin.

**Comment by Youjair** [comment]
The last update in DrDRM should fix the need for another plugin. That or my english ir worse than I thought

> First release using the new directory structure and release script.
Hopefully fixes the problem with KFX and the stand-alone tools.

`https://github.com/apprenticeharper/DeDRM_tools/releases`

**Comment by ElleKayEm** [comment]
That's referring to the stand-alone DeDRM apps.  For calibre, you need the KFX Input plugin.

**Comment by Youjair** [comment]
Okey, I just installed it, restarted calibre and now the book's name is right at least. Now the format is KFX-ZIP and cannot be converted because of DRM.

Log:

calibre Registro de depuración
calibre 3.25 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 4, 0) && DeDRM (6, 6, 1) && Package KFX File Type (from KFX Input) (1, 4, 0) && KFX metadata reader (from KFX Input) (1, 4, 0) && KFX Input (1, 4, 0)
calibre 3.25 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 4, 0) && DeDRM (6, 6, 1) && Package KFX File Type (from KFX Input) (1, 4, 0) && KFX metadata reader (from KFX Input) (1, 4, 0) && KFX Input (1, 4, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.453781513 x 102.358208955
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.06] db initialized
[0.06] Constructing main UI...
[1.25] main UI initialized...
[1.25] Hiding splash screen
[12.05] splash screen hidden
[12.05] Started up in 12.05 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x98\x98\n\x03\x9b\xaa\r\xe4iE\xc4\xb6}\xd0,\x9e9\xc8\xdd\x12\xd6\xd2T\xaf\xed\xbb\xaa\xac\xca\x8a\xa7g', 'D:\\Users\\Usuario\\Documentos\\Libros\\My Kindle Content\\B009WWEPQW_EBOK\\B009WWEPQW_EBOK.azw']
Gather KFX-ZIP File Type (from KFX Input) 1.4.0: Importing D:\Users\Usuario\Documentos\Libros\My Kindle Content\B009WWEPQW_EBOK\B009WWEPQW_EBOK.azw
Gather KFX-ZIP File Type (from KFX Input): Gathered 4 files as C:\Users\Usuario\AppData\Local\Temp\calibre_d6wu2y\0kuazf.kfx-zip
DeDRM v6.6.1: Trying to decrypt 0kuazf.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: 0kuazf
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.8b333b17-15e5-4777-8c22-05ef2075e752.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.1: Failed to decrypt with error: This book is licensed as Prime. These tools are intended for use on purchased books.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Usuario\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Usuario\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3766232123' and UserName '5573756172696f'
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX File Type (from KFX Input) 1.4.0: Packaging C:\Users\Usuario\AppData\Local\Temp\calibre_d6wu2y\0kuazf.kfx-zip
Processing container: B009WWEPQW_EBOK.azw
Running file type plugin Package KFX File Type (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 52, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 118, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 205, in get_container
KFXDRMError: Book container B009WWEPQW_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Usuario\AppData\Local\Temp\calibre_d6wu2y\piij0t_add_books\0\B009WWEPQW_EBOK.kfx-zip
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added American Gods (Rocabolsillo Bestseller) (Spanish Edition) to db in: 1.5
Added 1 books in 2.3 seconds

**Comment by ElleKayEm** [comment]
From the log:

>Failed to decrypt with error: This book is licensed as Prime. These tools are intended for use on purchased books.
