### ISSUE TITLE
IGNOBLEError on B&N epub book, probably due to an empty key file

### ISSUE THREAD

**Issue by ceridwen** [apprenticeharper/DeDRM_tools#54]
I followed these instructions:

"Enter your Barnes & Noble account email address and password into the configuration dialog.  The DeDRM tools v6.2.2 or later will use this information to retrieve the decryption key from the B&N servers.  The email address and password will not be stored."

I didn't get any errors in the GUI or the command line when doing this, and it duly generated a key entry (Phone Appy Key) in the GUI.  However, when I tried it on an epub from B&N, I got the following traceback:

```
DeDRM v6.3.4: “2940045619318_epub.v6.epub” is a secure Barnes & Noble ePub
DeDRM v6.3.4: Trying Encryption key Phone App Key
DeDRM v6.3.4: Exception when trying to decrypt after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 200, in ePubDecrypt
  File "calibre_plugins.dedrm.ignobleepub", line 258, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 158, in __init__
IGNOBLEError: AES improper key used
```

I tried dumping the key to a .b64 file and ended up with an empty file, which may be an indication that it failed to get the key.  I double-checked my username/password and I'm pretty sure they're right---would it silently fail if those were wrong?

The epub came from the Nook Android app, and I'm running Calibre/DeDRM on Ubuntu Linux.

Is there any other information that would help diagnose this?

**Comment by ElleKayEm** [comment]
The fact that the .b64 file was blank indicates that either the email or password you entered were wrong.

**Comment by ceridwen** [comment]
I'm using a password manager, and as I can log into my account with the email/password I'm copying into DeDRM, I don't think my email/password are wrong.  (I've also tried this multiple times now.)  Where is this handled in the code?  I know Python and can probably provide additional diagnostic info if I know where to look.

**Comment by ElleKayEm** [comment]
I don't know why else the exported .b64 would be blank.  Here's a way to see what the plugin is getting from B&N:

Create an URL using the template below by substituting in your B&N account email address and password.  View the source of the returned web page, and the key will be between ccHash tags.  If the email/password is wrong, it will say, "This Email Address and Password is not associated with an existing customer."  If it returns a key, you can try reentering the correct info into the plugin configuration.  Or just copy those 28 characters and save them as plain text in a .b64 file which can then be imported.

https://cart4.barnesandnoble.com/services/service.aspx?Version=2&acctPassword=YOUR_PASSWORD&devID=PC_BN_2.5.6.9575_26595D2569D3F8CB07CA2A89018D1234&emailAddress=YOUR_EMAIL_ADDRESS&outFormat=5&schema=1&service=1&stage=deviceHashB

**Comment by ceridwen** [comment]
I tried this and got a generic 404 error from Microsoft IIS.  Does it work for you?

**Comment by ElleKayEm** [comment]
Aha!  Yes, that's probably it.  Try replacing the non-alphanumerics with their escape codes in that URL.

(Here's a reference:  http://www.december.com/html/spec/esccodes.html)

**Comment by ceridwen** [comment]
Even with all the special characters escaped, I'm still getting the same 404 error.  My only guess here involves User-Agent strings, but if that's the case, what User-Agent strings does the site accept, and what User-Agent string is DeDRM/Calibre using?

**Comment by ElleKayEm** [comment]
That's possible.  The url is actually the one that Nook for PC uses.  It works for me using Chrome on Windows 8.  When I replace a character in my password with the correct percent code, I get my key.  When I put in the wrong password, I get a message about it being an unknown email/password combo.  When I put in an unescaped reserved character, I get the 404 page.

Ok, just tried with the Chrome browser on an Android tablet.  Apparently, I typed my password wrong because I got a message that my account was about to be locked from too many attempts.  So I guess I'll stop messing with that!  But it did respond with something instead of the 404 page.

**Comment by ceridwen** [comment]
I've now tried Chromium and Firefox on Linux and Chrome and Firefox on Android---I'm still getting the 404 error with both the URL above and the URL from the Python code for the Android devices, replacing the string `random` with the random string from the URL you gave above.  I was quite careful with constructing the URLs, but I've still been doing it by hand, so I can't swear I didn't make any mistakes, though I used Perl's URI::Escape to do the substitution for my password.  I don't have any more ideas, though I'm going to try changing my password and redoing the URLs.

How did you find these URLs in the first place?  Is something to do with the random element possibly mucking them up?  Does the URL change when you change your password?

**Comment by ElleKayEm** [comment]
The url was posted at Alf's blog by someone who figured out how Nook for PC retrieved the key.  Then it got incorporated into the tools.

Hopefully changing your password to one without special characters will do the trick.  The url will be the same other than changing your password.  And of course, you can add a new key created with the new password to the plugin and see what happens.

**Comment by ceridwen** [comment]
I don't know what the issue was with the URLs, but changing my password worked.  I looked at the code, and `urllib.quote()` in ignorekeyfetch.py ought to escape special characters in passwords.  I'm not sure if `urllib.quote_plus()` would work better.  There's clearly some kind of insufficient escaping going on, though.  I would add: it would also be nice if the plugin gave an error when it fails to retrieve a valid key, rather than failing silently.

**Comment by apprenticeharper** [comment]
I will see what can be done about adding some more error checking.

**Comment by Algaar** [comment]
I had a similar experience - Non-alpha numeric characters in the B&N password causing the DRM removal process in Calibre to fail.  

A procedural solution that worked ...

1> change the B&N password (to remove non-alpha numeric characters)

2> if downloaded previously (i.e., while using the prior B&N password), clear the downloaded nook ebooks from pc (e.g., the default path being ... C:\...\Documents\My Barnes & Noble eBooks\Your email address)

3> redownload nook books (after the B&N password was changed)

4> 'Add Books' from B&N folder into Calibre

5> Install DeDRM tools [https://apprenticealf.wordpress.com/]

6> Customize the DeDRM plugin with a B&N key (using the new B&N password, sans alpha numeric characters) 

7> Convert Nook Books to the desired format

**Comment by ElleKayEm** [comment]
Put step 4 after step 6.

**Comment by apprenticeharper** [comment]
Improvements to the B&N key dialog in the plugin will be included in 6.4.3. These should stop the empty keyfile problem.

**Comment by apprenticeharper** [comment]
6.4.3 is ready to go, but I'd like to get confirmation that it's all working. Please give this version a go:
[DeDRM_plugin.zip](https://github.com/apprenticeharper/DeDRM_tools/files/235943/DeDRM_plugin.zip)

**Comment by apprenticeharper** [comment]
6.4.3 released
