### ISSUE TITLE
OSX, installed with brew cask doesn't work - ImportError: No module named PyQt4.Qt

### ISSUE THREAD

**Issue by aventizio** [apprenticeharper/DeDRM_tools#540]
Calibre installed on OSX, with `brew cask`:

```
$ calibredb add B313NVG87V7_EBOK.azw
Kindle and Mobipocket DeDRM v0.4.19: Trying to decrypt B313NVG87V7_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin Kindle and Mobipocket DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.k4mobidedrm.__init__", line 122, in run
  File "calibre_plugins.k4mobidedrm.__init__", line 255, in config
  File "site-packages/calibre/customize/zipplugin.py", line 183, in load_module
  File "calibre_plugins.k4mobidedrm.config", line 4, in <module>
ImportError: No module named PyQt4.Qt
Added book ids: 398
```

**Comment by ideologysec** [comment]
Does 
```
brew install PyQt
```
fix the issue?

**Comment by aventizio** [comment]
No, PyQT is PyQT5 in brew:

```
$ brew install PyQT
Warning: pyqt 5.10.1 is already installed and up-to-date
To reinstall 5.10.1, run `brew reinstall pyqt`
$ calibredb add B313NVG87V7_EBOK.azw
Kindle and Mobipocket DeDRM v0.4.19: Trying to decrypt B313NVG87V7_EBOK.azw.
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin Kindle and Mobipocket DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.k4mobidedrm.__init__", line 122, in run
  File "calibre_plugins.k4mobidedrm.__init__", line 255, in config
  File "site-packages/calibre/customize/zipplugin.py", line 183, in load_module
  File "calibre_plugins.k4mobidedrm.config", line 4, in <module>
ImportError: No module named PyQt4.Qt
```

(and no easy/obvious way to install the old version)

**Comment by ideologysec** [comment]
Not the same plugin, but another calibre plugin with a similar issue. Seems like the k4dedrm code might still have PyQT4 references in it?

https://github.com/xchewtoyx/calibre-comicvine/issues/6

**Comment by ideologysec** [comment]
Ah! Reading through some of the newer commits, it seems like you might have an older individual k4MobiDeDRM plugin installed. Can you try going through your plugins to see if there are any DeDRM plugins other than just the single DeDrM 6.6.1, and if so removing them? Seems like there might be a conflict there.

From https://github.com/apprenticeharper/DeDRM_tools/blob/master/contrib/calibre/DeDRM_plugin_ReadMe.txt

"This calibre plugin replaces many previously separate DRM removal plugins. Before you install this plugin, you should uninstall any older individual DRM removal plugins, e.g. K4MobiDeDRM. The exception is the obok plugin, which should not be removed."

ie, you shouldn't have a calibre plugin called K4MobiDeDRM installed at all, but from the traceback it appears that you do.

**Comment by aventizio** [comment]
Ugh. PEBKAC.

Thank you. I downloaded both an old and new version of the zipfile, extracted the old zipfile and thought I was working with the new version.

My apologies, and thank you for the assistance!
