### ISSUE TITLE
Calibre doesn't convert Kfx from Kindle 

### ISSUE THREAD

**Issue by 365Wanda** [apprenticeharper/DeDRM_tools#542]
Hello, 
I have converted all the other formats (AZW, AZW3, MOBI, PRC...) directly from my Kindle Paperwhite but anytime I try to convert a KFX file I get this message (translated from French). I am using Windows 7 Home Premium. 
 
calibre, version 3.25.0
WARNING: Impossible to convert some books. It is impossible to convert this book as no source format was found. 
A Scandal in Battersea B07618X5CM - Formats unsupported (Available formats : kfx)

The file name is: A Scandal in Battersea_B07618X5CM.kfx

Thanks for your help.

**Comment by j-howell** [comment]
In order to successfully import and convert KFX format you need to install the optional [KFX Input](https://www.mobileread.com/forums/showthread.php?t=291290) plugin for calibre.

**Comment by ElleKayEm** [comment]
And you need at least version 6.6.0 of DeDRM.

**Comment by 365Wanda** [comment]
Many thanks to both of you, it works. My 436 e-books and myself are very, very happy right now.  :)
