### ISSUE TITLE
MacOS 6.6.1 app fails

### ISSUE THREAD

**Issue by edglazer** [apprenticeharper/DeDRM_tools#543]
This is on 10.13.5, launched the macos app and receive this message:
The application "DeDRM" can't be opened.

Console logs say:
spawn_via_launchd() failed, errno=111 label=[0x0-0xcb0cb].com.apple.ScriptEditor.id.707CCCD5-0C6C-4BEB-B67C-B6E866ADE85A path=/private/var/folders/sf/jhkzzz9d2ps7lfw_ws1_8p000000gn/T/AppTranslocation/47A6BE26-75F5-47CA-B6D7-CCE2D686DB1D/d/DeDRM.app/Contents/MacOS/droplet flags=1

I looked in the package contents for both 6.6.0 (which works fine for me) and 6.6.1, and on 6.6.0 the "droplet" icon is black in Finder and kind is listed as executable. Whereas on 6.6.1, the "droplet" icon is white and the kind is listed as 'Textedit.' I'm guessing the execute permission wasn't set somehow?

**Comment by ElleKayEm** [comment]
Looks like someone got it working over in this issue:

https://github.com/apprenticeharper/DeDRM_tools/issues/505#issuecomment-396103048

**Comment by edglazer** [comment]
Good deal, thanks for the note!
