### ISSUE TITLE
ImportError: No module named Crypto.Cipher

### ISSUE THREAD

**Issue by jsrichards** [apprenticeharper/DeDRM_tools#545]
Has anyone ran into this issue?

shellcommand: /usr/bin/python '/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/.../Library/Preferences/com.apprenticealf.dedrm/KindleKey 4.der' '/Users/.../Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content/B00BAWQ6E6_EBOK/B00BAWQ6E6_EBOK.azw' '/Users/.../Desktop/' > '/Users/.../Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 93, in <module>
    import kfxdedrm
  File "/Applications/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/Applications/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
There was an error with 1 ebook:
B00BAWQ6E6_EBOK.azw couldn't be decrypted.

**Comment by ElleKayEm** [comment]
It seems like there are a few issues with the Mac app right now.
#505

**Comment by jsrichards** [comment]
I fixed the problem. I have python 3 and python 2 installed. The default version for the OS is python 2 which did not have the proper libraries installed. I had to run python -m pip pycrypto to install the package. For some reason pip when run without the "python -m" option is defaulting to python3 and pip3

**Comment by apprenticeharper** [comment]
Thanks, Added to the FAQs.

**Comment by biocyberman** [comment]
`sudo apt install python3-crypto` might help on linux

**Comment by protist** [comment]
In Arch Linux, the relevant package is `python-pycryptodome`
