### ISSUE TITLE
Installed DRM Removal PlugIns But Still Get Error

### ISSUE THREAD

**Issue by Vienna01** [apprenticeharper/DeDRM_tools#549]
I installed 2 DRM removal plugins
- -DeDRM  6.6.1 in File Type PlugIns
- -Obok DeDRM 6.5.3 in User Interface Action PlugIns . [ This was only installed after repeatedly getting ERRORS when ONLY the File Type PlugIn "DeDRM" had been installed].

**Both plugins installed were accepted.** 
I closed & re-started Calibre after every install.

I removed any earlier copies of the file **"Ipad User Guide for IOS 11.3.epub"**
Then I added a fresh copy of the file to be "VIEW"ed

When I clicked on  Green VIEW icon within Calibre, I received the **error message** that file couldn't be displayed because it had DRM.{not exact words of ERROR text}
I have NOT attached the file ["Ipad User Guide for IOS 11.3.epub"] in question HERE because it is an epub format not accepted by this comment editor.

**What shall I do to find out what is incorrect & causing the error?**
Are there any Calibre tools that can show exactly why the EPUB document is thought by Calibre to have DRM protection?

**Comment by Vienna01** [comment]
Sorry, I don't know if I should leave Comment/Issue OPEN or Closed.
I did **Close** it and after thinking about how it is shown, I **REOPENED** it.

**Comment by ElleKayEm** [comment]
Where was the book purchased?  These tools work on epubs with Adobe DRM, Barnes & Noble's DRM, or Kobo's DRM.  If it's from the Apple iBooks store, then these tools can't help.

If it's one of the DRMs that this should work on, then post a log:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by Vienna01** [comment]
_Thanks for REPLY_ 
That **SOLVES issue**

I **THINK** I got it setting up iPAD. 
**VERY likely it came from Apple**.
Just tried reading it on an iMAC using iBOOKS. 
**IT WAS READABLE on iBOOKS**. 
Yes- probably **came from Apple**. 
I usually don't use iBOOKS.
