### ISSUE TITLE
Headless usage of DeDRM Plugin

### ISSUE THREAD

**Issue by quixony** [apprenticeharper/DeDRM_tools#55]
Hey guys, 

I am trying to use the DeDRM Plugin on my headless server to just copy files to a specific folder and let calibre convert it to a different format. Till now I had to free the files before putting into the folder. 

On Windows dedrm works like charm, on my headless linux I can not add certificates. So it is not able to work. Can you tell me how to import the cert? With calibre-customize customize-plugin=DeDRM I can access plugin-functions. But what is the correct one?

**Comment by apprenticeharper** [comment]
Feel free to examine the code and work it out. It's not something I feel able to support at present.
