### ISSUE TITLE
Unable to decrypt(convert) Kindle Unlimited Book

### ISSUE THREAD

**Issue by chiragshahklc** [apprenticeharper/DeDRM_tools#557]
calibre Debug log
calibre 3.26.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 5, 0) && DeDRM (6, 6, 1) && Package KFX File Type (from KFX Input) (1, 5, 0) && Goodreads (1, 1, 14) && KFX metadata reader (from KFX Input) (1, 5, 0) && KFX Input (1, 5, 0) && Library Splitter (1, 0, 0)
calibre 3.26.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 5, 0) && DeDRM (6, 6, 1) && Package KFX File Type (from KFX Input) (1, 5, 0) && Goodreads (1, 1, 14) && KFX metadata reader (from KFX Input) (1, 5, 0) && KFX Input (1, 5, 0) && Library Splitter (1, 0, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
[1.95] main UI initialized...
[1.95] Hiding splash screen
[13.36] splash screen hidden
[13.36] Started up in 13.36 seconds with 156 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x7f\xdc\x9eV\x10\xff> \x1a9\xe5\xaa\xc4\x85hW0\xdd\x85"\xc7\xcfl\x93\xf3\x0b*\xf3[gA\xf2', 'C:\\Users\\Fury\\Documents\\My Kindle Content\\B077NJWFR3_EBOK\\B077NJWFR3_EBOK.azw']
Gather KFX-ZIP File Type (from KFX Input) 1.5.0: Importing C:\Users\Fury\Documents\My Kindle Content\B077NJWFR3_EBOK\B077NJWFR3_EBOK.azw
Gather KFX-ZIP File Type (from KFX Input): Gathered 4 file(s) as C:\Users\Fury\AppData\Local\Temp\calibre_9lmlk_\fimhrb.kfx-zip
DeDRM v6.6.1: Trying to decrypt fimhrb.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: fimhrb
Got DSN key from database default_key
Found 2 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7fd9591a-fdad-40b6-8f16-277f98a128a4.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.1: **Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books**.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Fury\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Fury\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1255800631' and UserName '46757279'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: fimhrb
Got DSN key from database default_key_1
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7fd9591a-fdad-40b6-8f16-277f98a128a4.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by j-howell** [comment]
That is intentional. From the FAQ:

> You must own the ebook - the tools won't work on library ebooks or rented ebooks or books from a friend.

**Comment by ElleKayEm** [comment]
Yup, as it says in the log:

>This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

**Comment by ElDavoo** [comment]
You can easily edit the source code to remove the limitation though.

**Comment by chiragshahklc** [comment]
If anyone want to use on KindleUnlimited/Rented book, one can try using [Epubor Ultimate](https://www.epubor.com/ultimate.html). Though it is paid application.

**Comment by ElleKayEm** [comment]
If you like a book from Kindle Unlimited enough to want to keep it, then buy it.  Support the author.

**Comment by chiragshahklc** [comment]
@ElleKayEm I agree with you. I do that always. It's just creating collection in calibre is my hobby. To be helpful to those who can't.

**Comment by ElleKayEm** [comment]
Just saying, if you're going to pay for something, pay the author, not those scammers.  Many KU books are pretty reasonably priced anyway.  People keeping books they only paid to borrow/rent instead of buying them will lead to authors/publishers not making them available for subscription/rent.

**Comment by ElDavoo** [comment]
Or you can just remove 2 lines of code from this project...

**Comment by ElleKayEm** [comment]
Or stick to reading KU books with a Kindle app/device so the author actually gets paid _something_.
