### ISSUE TITLE
InvalidPlugin

### ISSUE THREAD

**Issue by mwheeler906** [apprenticeharper/DeDRM_tools#558]
calibre, version 3.26.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'D:\\---------\\Downloads\\DeDRM_tools_6.6.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.26.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 5, 0) && DeDRM (6, 5, 3) && Package KFX File Type (from KFX Input) (1, 5, 0) && KFX metadata reader (from KFX Input) (1, 5, 0) && KFX Input (1, 5, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 471, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 60, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 192, in load
  File "site-packages\calibre\customize\zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'D:\\---------\\Downloads\\DeDRM_tools_6.6.1.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by mwheeler906** [comment]
I was able to resolve the problem. Please close.

**Comment by ElleKayEm** [comment]
For anyone else with this problem, solution is here:

https://github.com/apprenticeharper/DeDRM_tools/issues/554#issuecomment-398701795
