### ISSUE TITLE
DeDRM 6.6.5 and 6.6.1 aren't removing DRM from Kindle books

### ISSUE THREAD

**Issue by bkrchk99** [apprenticeharper/DeDRM_tools#559]
Just added Calibre back after computer upgrade. It was working before the upgrade, but when I reinstalled, it no longer removes DRM. I am using Kindle for PC version 1.17. I also tried downloading file from Amazon. Neither option works.
I also tried the suggestion of deregistering Kindle for PC and deleting the folder on my computer. 

After I reinstalled, I am still getting the same issue. 

Here is the debug file:

calibre Debug log
calibre 3.26.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 5, 0) && DeDRM (6, 5, 5) && Package KFX File Type (from KFX Input) (1, 5, 0) && Set KFX metadata (from KFX Output) (1, 20, 0) && KFX Output (1, 20, 0) && Obok DeDRM (6, 5, 4) && KFX metadata reader (from KFX Input) (1, 5, 0) && KFX Input (1, 5, 0) && Kobo Utilities (2, 6, 0) && KoboTouchExtended (3, 0, 2) && EpubMerge (2, 2, 0) && EpubSplit (2, 4, 0)
calibre 3.26.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 5, 0) && DeDRM (6, 5, 5) && Package KFX File Type (from KFX Input) (1, 5, 0) && Set KFX metadata (from KFX Output) (1, 20, 0) && KFX Output (1, 20, 0) && Obok DeDRM (6, 5, 4) && KFX metadata reader (from KFX Input) (1, 5, 0) && KFX Input (1, 5, 0) && Kobo Utilities (2, 6, 0) && KoboTouchExtended (3, 0, 2) && EpubMerge (2, 2, 0) && EpubSplit (2, 4, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259 x 93.6245733788
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    1.5 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    1.5 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    1.5 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    1.5 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
EpubMerge: DEBUG: 2018-06-27 15:18:36,855: calibre_plugins.epubmerge.epubmerge_plugin(152): macmenuhack file_path:C:\Users\Joy Pihmon\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[1.83] main UI initialized...
[1.83] Hiding splash screen
[80.83] splash screen hidden
[80.83] Started up in 80.83 seconds with 324 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['|Ql\x88\x0b\xbd\xc2\xce310\x03\xb5\x9d\xac\x10\xb7\xae\xc7\xf4T\xb0M\x19#\x0e\xdc6h\x8dm?', 'C:\\Users\\Joy Pihmon\\OneDrive\\Documents\\My Kindle Content\\B07869BSD4_EBOK.azw']
Gather KFX-ZIP File Type (from KFX Input) 1.5.0: Importing C:\Users\Joy Pihmon\OneDrive\Documents\My Kindle Content\B07869BSD4_EBOK.azw
Gather KFX-ZIP File Type (from KFX Input): File is not KFX format
DeDRM v6.5.5: Trying to decrypt B07869BSD4_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Key: The heartwrenching new pageturner from the #1 bestselling author of The Letter
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Joy Pihmon\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Joy Pihmon\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '373086946' and UserName '4a6f79205069686d6f6e'
DeDRM v6.5.5: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Key: The heartwrenching new pageturner from the #1 bestselling author of The Letter
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Key: The heartwrenching new pageturner from the #1 bestselling author of The Letter to db in: 0.2
Added 1 books in 1.3 seconds
Worker Launch took: 0.101999998093

**Comment by ElleKayEm** [comment]
The book you're trying to DeDRM was downloaded with the current installation of Kindle for PC on the same machine and user as calibre?

When downloading from the website, you need to choose an E-ink Kindle and enter its serial number into the plugin customization.

I notice you have the KFX plugin, but an older version of DeDRM that doesn't handle KFX files.  Not that you will get KFX files with K4PC 1.17 or the website.

**Comment by bkrchk99** [comment]
Yes,  the book that is downloaded with Kindle for PC is on the same machine and user as calibre. I guess that I can remove the KFX plugins.

I just tried again and the books from My Kindle Content won't convert. However, after reading your suggestion,  I input my serial number in the DeDRM plugin again and it now works with the books downloaded from the website. I tried the serial number yesterday, but must have made a mistake with the numbers.  Thanks for the info.

Still can't figure out why the Kindle for PC books won't work. They were working before I upgraded my computer. Oh well, as long as one method works, I'm good to go.

Anyway thanks for your help ElleKayEm.

**Comment by ElleKayEm** [comment]
The log shows it finding and decrypting a Kindle for PC key, but it's not working for this book.  Usually that means either the book or the key are left behind from a previous installation of Kindle for PC.  But I know you had already tried deregistering and deleting Kindle folders.  The only thing I can think of is that Kindle for PC is putting something in a different place that isn't listed in [the uninstall instructions](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book).

**Comment by bkrchk99** [comment]
You were spot on about items left behind. There was a second documents folder on my computer after the upgrade and it had another My Kindle Content folder. 

I went through all the steps again but removed the _two_ instances of My Kindle Content, reinstalled Kindle for PC, re-registered, imported the books and it worked perfectly.

Thanks so much for solving my problem.

**Comment by maxbEternauta** [comment]
Can you help me with this? 

calibre, version 5.6.0 (darwin, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (dignidad (Ensayo) (Spanish Edition))

Convert book 1 of 1 (dignidad (Ensayo) (Spanish Edition))
DeDRM v7.0.0: Trying to decrypt 705jdws0.azw3
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: dignidad (Ensayo) (Spanish Edition)
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 10 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID b'7PUMOtXj73'.
Decrypting. Please wait . . . . done
Decryption succeeded after 1.1 seconds
DeDRM v7.0.0: Finished after 1.1 seconds
Conversion options changed from defaults:
  output_profile: 'kindle_pw3'
  read_metadata_from_opf: '/var/folders/x8/rc92y2k918b3bd8w9651vdn40000gn/C/calibre_5.6.0_tmp_g84dr9x3/jcsfd8na.opf'
  verbose: 2
Resolved conversion options
calibre version: 5.6.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x118f14d60>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': 'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x118f23400>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'personal_doc': '[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/x8/rc92y2k918b3bd8w9651vdn40000gn/C/calibre_5.6.0_tmp_g84dr9x3/jcsfd8na.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v7.0.0: Trying to decrypt icduyp8y.azw3
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: dignidad (Ensayo) (Spanish Edition)
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 10 keys to try after 0.0 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.0 seconds
DeDRM v7.0.0: Finished after 0.0 seconds
InputFormatPlugin: MOBI Input running
on /var/folders/x8/rc92y2k918b3bd8w9651vdn40000gn/C/calibre_5.6.0_tmp_g84dr9x3/eacg8pus.azw3
Found KF8 MOBI of type 'standalone'
Extracting text...
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 245, in __call__
  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "calibre/ebooks/mobi/reader/mobi8.py", line 114, in __call__
  File "calibre/ebooks/mobi/reader/mobi8.py", line 467, in expand_text
  File "calibre/ebooks/mobi/reader/markup.py", line 339, in expand_mobi8_markup
  File "calibre/ebooks/mobi/reader/markup.py", line 217, in update_flow_links
TypeError: sequence item 3: expected str instance, bytes found


Thank you!

**Comment by ElleKayEm** [comment]
I don't see anything to help with here -- one successfully deDRMed book and one without DRM to begin with.  DeDRM only deals with DRM removal.
