### ISSUE TITLE
Segfault on Ubuntu 15.10

### ISSUE THREAD

**Issue by sebreit** [apprenticeharper/DeDRM_tools#56]
DeDRM 6.3.4 with Calibre 2.48 segfaults when trying to remove drm while importing epubs into calibre. DRM key and epubs should be ok because it works fine on windows 7 with the same epubs and the same drm key.

This is the result of "calibre-debug -g":
```
calibre 2.48  isfrozen: True is64bit: True
Linux-3.19.0-21-generic-x86_64-with-debian-jessie-sid Linux ('64bit', 'ELF')
('Linux', '3.19.0-21-generic', '#21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015')
Python 2.7.9
Linux: ('debian', 'jessie/sid', '')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 2.31 seconds with 85 books
DeDRM v6.3.4: Trying to decrypt dup_cache.epub
DeDRM v6.3.4: Verifying zip archive integrity
DeDRM v6.3.4: dup_cache.epub is a secure Adobe Adept ePub
DeDRM v6.3.4: Trying Encryption key sebr
Speicherzugriffsfehler (Speicherabzug geschrieben)
```
 
For more information see attached crash dump. 

[crash.zip](https://github.com/apprenticeharper/DeDRM_tools/files/78753/crash.zip)

**Comment by apprenticeharper** [comment]
The crash appears to have happened in the libcrypto library that's supplied with DeDRM. The source is included in the DeDRM_plugin zip, so I suggest you recompile it under Ubuntu 15.10.

I wonder what's changed in Ubuntu 15.10 that's caused the error?

**Comment by sebreit** [comment]
After trying several things (recompile DeDRM, install Calibre from source etc.) I found that in fact it was the key, which I have used at least for two years without problems. After extracting it once more from Adobe Digital editions using the latest DeDRM tools, everything works fine again.

To prevent calibre from crashing with corrupted keys maybe you could add an additional key check in ineptepub.py like so:
```python
    class RSA(object):
        def __init__(self, der):
            buf = create_string_buffer(der)
            pp = c_char_pp(cast(buf, c_char_p))
            rsa = self._rsa = d2i_RSAPrivateKey(None, pp, len(der)) 
            if rsa is None:
                raise ADEPTError('Error parsing ADEPT user key DER')

            # check if pointer is not NULL
            try:
                c = self._rsa.contents
            except ValueError:   
                raise ADEPTError('Error parsing ADEPT user key DER')

        def decrypt(self, from_):
```
