### ISSUE TITLE
I don't know what I'm doing wrong.

### ISSUE THREAD

**Issue by JBaby9783** [apprenticeharper/DeDRM_tools#562]
I'm on the latest version of Calibre, DeDRM tools, and KFX plugins. But I'm at a loss for what to do. I've been using the tools successfully for years. Should I just go track down the old version of Kindle for Mac? All help will be greatly appreciated!

2018-06-30 19:10:16.753 calibre-debug[1564:779145] Can't open input server /Library/InputManagers/CTLoader
libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 3.26.1  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 5, 0) && DeDRM (6, 6, 1) && Package KFX File Type (from KFX Input) (1, 5, 0) && EpubSplit (2, 4, 0) && Open With (1, 5, 10) && KFX metadata reader (from KFX Input) (1, 5, 0) && KFX Input (1, 5, 0) && Manage Series (1, 2, 8) && Modify ePub (1, 3, 13) && Barnes & Noble (1, 2, 15) && Comicvine (0, 10, 6) && Goodreads (1, 1, 14) && Goodreads Sync (1, 12, 0)
calibre 3.26.1  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 5, 0) && DeDRM (6, 6, 1) && Package KFX File Type (from KFX Input) (1, 5, 0) && EpubSplit (2, 4, 0) && Open With (1, 5, 10) && KFX metadata reader (from KFX Input) (1, 5, 0) && KFX Input (1, 5, 0) && Manage Series (1, 2, 8) && Modify ePub (1, 3, 13) && Barnes & Noble (1, 2, 15) && Comicvine (0, 10, 6) && Goodreads (1, 1, 14) && Goodreads Sync (1, 12, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.000001637 x 109.000001637
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
DEBUG:    0.0 HttpHelper::__init__: proxy=None
[1.87] main UI initialized...
[1.87] Hiding splash screen
[1.87] splash screen hidden
[1.88] Started up in 1.88 seconds with 665 books
SMART_DEV (   0.00:  0.001) _attach_to_port try ip address "" on port 9090
SMART_DEV (   0.90:  0.802) _startup_on_demand listening on port 9090
SMART_DEV (   0.93:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   0.95:  0.000) _startup_on_demand broadcast socket listening on port 54982
SMART_DEV (   1.97:  1.006) run All IP addresses {'lo0': [{'netmask': '255.0.0.0', 'peer': '127.0.0.1', 'addr': '127.0.0.1'}], 'ipsec0': [{'netmask': '255.255.255.255', 'peer': '10.6.6.159', 'addr': '10.6.6.159'}], 'en0': [{'netmask': '255.255.255.0', 'broadcast': '192.168.1.255', 'addr': '192.168.1.138'}], 'en1': [{'netmask': '255.255.255.0', 'broadcast': '192.168.1.255', 'addr': '192.168.1.139'}]}
Gather KFX-ZIP File Type (from KFX Input) 1.5.0: Importing /Users/Jessi/Desktop/AutoAddBooks/B075WX4R2R_EBOK.azw
Gather KFX-ZIP File Type (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP File Type (from KFX Input): Gathered 1 file(s) as /var/folders/gf/791bd2rd0xs7c2cpxrvvy6900000gn/C/calibre_3.26.1_tmp_NU6Lkl/h72yk5.kfx-zip
DeDRM v6.6.1: Trying to decrypt h72yk5.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: h72yk5
Got DSN key from database default_key
Found 1 keys to try after 0.0 seconds
DeDRM v6.6.1: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/Jessi/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '1339A1402071' and UserName 'Jessi'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: h72yk5
Got DSN key from database default_key_1
Found 1 keys to try after 1.1 seconds
DeDRM v6.6.1: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX File Type (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 53, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 121, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in get_container
KFXDRMError: Book container B075WX4R2R_EBOK.azw has DRM and cannot be converted
2018-06-30 19:10:53.467 Calibre[1584:782810] Can't open input server /Library/InputManagers/CTLoader
2018-06-30 19:10:53.479 Calibre[1584:782810] deliverNotificationWithTitle()
* Notification delivered.
Package KFX File Type (from KFX Input) 1.5.0: Packaging /var/folders/gf/791bd2rd0xs7c2cpxrvvy6900000gn/C/calibre_3.26.1_tmp_NU6Lkl/h72yk5.kfx-zip
Processing container: B075WX4R2R_EBOK.azw
Worker Launch took: 0.061821937561
Job: 1 Convert book 1 of 1 (B075WX4R2R EBOK) finished
Convert book 1 of 1 (B075WX4R2R EBOK)
	Conversion options changed from defaults:
	  verbose: 2
	  preserve_cover_aspect_ratio: True
	  epub_version: u'3'
	  read_metadata_from_opf: u'/var/folders/gf/791bd2rd0xs7c2cpxrvvy6900000gn/C/calibre_3.26.1_tmp_NU6Lkl/_qvJ0u.opf'
	  output_profile: 'ipad3'
	Resolved conversion options
	calibre version: 3.26.1
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'3',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10eed2dd0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x10eedb3d0>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': True,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/gf/791bd2rd0xs7c2cpxrvvy6900000gn/C/calibre_3.26.1_tmp_NU6Lkl/_qvJ0u.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 98, in convert
	  File "calibre_plugins.kfx_input.__init__", line 197, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 72, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 121, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in get_container
	KFXDRMError: Book container B075WX4R2R_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly: This book has DRM

**Comment by Wisperer** [comment]
Did you pull the KFX file out of it's download directory? It need the DRM voucher file in it to be encrypted.

**Comment by j-howell** [comment]
> Gather KFX-ZIP File Type (from KFX Input) 1.5.0: Importing /Users/Jessi/Desktop/AutoAddBooks/B075WX4R2R_EBOK.azw

The "Automatic adding" function of calibre, which adds any book files placed in a specific directory, cannot be used with books in KFX format because each book in composed of multiple files. You must manually add the main file of the book from its original folder location so that the KFX Input plugin can gather all of the files that make up the book. Alternatively you can create a ZIP file containing all of the files that make up the book, change its extension to ".kfx-zip", and place that into the folder configured for automatic adding to calibre.

**Comment by JBaby9783** [comment]
Thank you so much. I finally got it to work. I was making it harder than it needed to be. Thanks again. I truly appreciate all the effort and work ya'll put into the tools.

**Comment by ElleKayEm** [comment]
If you're all set,you can close the issue.

**Comment by JBaby9783** [comment]
I don’t know how to do that.

**Comment by ElleKayEm** [comment]
As the person who opened the issue you should see a close button ...at the top of the page, I think.

**Comment by ElleKayEm** [comment]
No big deal... if you don't, eventually Apprentice Harper will.
