### ISSUE TITLE
Will not load

### ISSUE THREAD

**Issue by diddoit** [apprenticeharper/DeDRM_tools#564]
I get this error when trying to load this plugin to Calibre ??   I have tried all the versions and get the same error??
InvalidPlugin: The plugin in u'C:\\Users\\drape\\Downloads\\DeDRM_tools-6.6.1.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're trying to load the wrong file.  Unzip that and look in the DeDRM_calibre_plugin folder for DeDRM_plugin.zip.

**Comment by diddoit** [comment]
thank you.
