### ISSUE TITLE
Unable to DeDRM ebook from Kindle for MACOS using standalone

### ISSUE THREAD

**Issue by rufuswilson** [apprenticeharper/DeDRM_tools#567]
I am trying to unlock one of my ebooks from Kindle for MACOS using the standalone app. The app reports an error and the log file contains:

> There is 1 ebook to be decrypted.
> Processing file: B00TK751Z8_EBOK.azw
> There was an error with 1 ebook:
> MacHD:Users:cedric:Library:Application Support:Kindle:My Kindle Content:B00TK751Z8_EBOK:B00TK751Z8_EBOK.azw is neither a Kindle not a Mobipocket file.

Here are some version info:
`DeDRM version: 6.6.1`
`System Version: macOS 10.13.5 (17F77)`
`Kernel Version: Darwin 17.6.0`

How can I help

**Comment by j-howell** [comment]
It is possible that the book is in KFX format. If the folder that holds the .azw file you tried to import also has a file with a name like amzn1.drm-voucher.v1.xxxxxxxx.voucher then it is KFX.

If so then you may be able to remove the DRM with the stand-alone tools if you take some extra steps, but won't be able to do anything useful with the result without the [KFX Input plugin](https://www.mobileread.com/forums/showthread.php?t=291290) for calibre.

**Comment by m3nu** [comment]
Can confirm that. After installing the linked plugin and the DeDRM plugin into Calibre, importing the book worked fine.
