### ISSUE TITLE
Need to update obok_plugin.zip

### ISSUE THREAD

**Issue by lkysow** [apprenticeharper/DeDRM_tools#57]
Hi,

Just an FYI that you've forgotten to update the .zip file of the Obok_calibre_plugin in this directory with the latest changes: https://github.com/apprenticeharper/DeDRM_tools/tree/master/Obok_calibre_plugin

**Comment by apprenticeharper** [comment]
Not so much forgotten as that you were looking at a work in progress. If you go for anything other than the official releases, you're assumed to be able to work out what's going on yourself.

**Comment by lkysow** [comment]
Gotcha, thanks :+1:
