### ISSUE TITLE
Error on DeDRM with KFX disabled

### ISSUE THREAD

**Issue by rufuswilson** [apprenticeharper/DeDRM_tools#570]
As explained in the FAQs, I run that command to force the books not to be in KFX:
`chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test`

Redownloaded the book using Kindle for MAC OSX v1.23.1 (50131)

Tried to DeDRM the book using the stand-alone application 6.6.1 but I have the following error:

> There is 1 ebook to be decrypted.
> Processing file: BOOKNAME.azw
> shellcommand: /usr/bin/python '/Users/USER/Downloads/DeDRM_tools_6.6.1/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/k4mobidedrm.py' '/Users/USER/Library/Application Support/Kindle/My Kindle Content/BOOKNAME/BOOKNAME.azw' '/Users/USER/Desktop/' > '/Users/USER/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
> shellresult: Using Library AlfCrypto DLL/DYLIB/SO
>  Traceback (most recent call last):
>   File "/Users/USER/Downloads/DeDRM_tools_6.6.1/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 93, in <module>
>     import kfxdedrm
>   File "/Users/USER/Downloads/DeDRM_tools_6.6.1/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
>     import ion
>   File "/Users/USER/Downloads/DeDRM_tools_6.6.1/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
>     from Crypto.Cipher import AES
> ImportError: No module named Crypto.Cipher
> shellcommand: /usr/bin/python '/Users/USER/Downloads/DeDRM_tools_6.6.1/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/USER/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/USER/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
> shellresult: kindlekey.py v2.5
> Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
> Found k4Mac kinf2011 file: /Users/USER/Library/Application Support/Kindle/storage/.kinf2011
> Decrypted key file using IDString '3da4022c62a6' and UserName 'USER'
> Saved a key to /Users/USER/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
>  
> shellcommand: /usr/bin/python '/Users/USER/Downloads/DeDRM_tools_6.6.1/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/USER/Library/Preferences/com.apprenticealf.dedrm/KindleKey 2.der' '/Users/USER/Library/Application Support/Kindle/My Kindle Content/BOOKNAME/BOOKNAME.azw' '/Users/USER/Desktop/' > '/Users/USER/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
> shellresult: Using Library AlfCrypto DLL/DYLIB/SO
>  Traceback (most recent call last):
>   File "/Users/USER/Downloads/DeDRM_tools_6.6.1/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 93, in <module>
>     import kfxdedrm
>   File "/Users/USER/Downloads/DeDRM_tools_6.6.1/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
>     import ion
>   File "/Users/USER/Downloads/DeDRM_tools_6.6.1/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
>     from Crypto.Cipher import AES
> ImportError: No module named Crypto.Cipher
> There was an error with 1 ebook:
> BOOKNAME.azw couldn't be decrypted.

Does this mean that we cannot force Kindle to download without KFX?

**Comment by ElleKayEm** [comment]
As far as I know, the method to stop Kindle for Mac from downloading KFX still works.  But the stand-alone DeDRM apps have issues right now.  If you look at other open issues, some people have found workarounds.  Or you could try an earlier version.  (I think 6.5.5 is fine.)  Or use the calibre plugin.

**Comment by rufuswilson** [comment]
OK. Thanks!

I used calibre and both plugins at the end.
