### ISSUE TITLE
Mac app DeDRM 6.6.1 "can't be opened"

### ISSUE THREAD

**Issue by hmahaffey** [apprenticeharper/DeDRM_tools#572]
I have been running DeDRM for quite some time. v6.6.0 works well. When I download and attempt to run DeDRM v6.6.1 by double-clicking the app in the folder "DeDRM_Macintosh_Application/ I get a pop-up that says "The application "DeDRM" can't be opened."  There are no other messages.

It doesn't help to Option+double-click or right-click->Open to open the file either.

I am running macOS 10.13.5.  I was not able to find a similar problem on the blog. I see people had problems trying to install the calibre plugin .zip file into calibre.  I have not attempted to install the calibre plugin yet.

Thanks!

**Comment by ElleKayEm** [comment]
There's a comment here about getting it to open:
https://github.com/apprenticeharper/DeDRM_tools/issues/505#issuecomment-396103048

But there may be other problems.  I think you're fine sticking with 6.6.0.  I believe the only change was a new release script which seems to have caused some issues with both stand-alone apps.

The only problem I've seen people have loading the plugin was trying to load the wrong file.

**Comment by hmahaffey** [comment]
Yay! Thanks for the link to #505!  "chmod" did the trick! You are awesome!
