### ISSUE TITLE
Can't convert to PDF

### ISSUE THREAD

**Issue by 0George0** [apprenticeharper/DeDRM_tools#574]
I'm able to add a KFX book I bought from Amazon using the KFX and DeDRM plugin, but I can't convert it to a PDF. I tried a conversion using another piece of software, but although it seemed to output a PDF, it couldn't be opened - I just got an error that the file was corrupt. I'm using a Mac and just downloaded the latest versions of both Calibre plugins.

This is the Calibre error log:

calibre, version 2.81.0 (darwin, embedded-python: True)
Conversion Error: Failed: Convert book 1 of 1 (Technological Nature: Adaptation and the Future of Human Life (MIT Press))

Convert book 1 of 1 (Technological Nature: Adaptation and the Future of Human Life (MIT Press))
Conversion options changed from defaults:
  output_profile: 'generic_eink'
  filter_css: u''
  sr3_search: None
  sr3_replace: None
  sr1_replace: None
  sr2_search: None
  cover: u'/var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/2uh6m9.jpeg'
  search_replace: '[]'
  transform_css_rules: '[]'
  verbose: 2
  sr2_replace: None
  read_metadata_from_opf: u'/var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/NyDFAA.opf'
  sr1_search: None
Resolved conversion options
calibre version: 2.81.0
{'allow_conversion_with_errors': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/2uh6m9.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10ddec5d0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'old_pdf_engine': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x10ddec9d0>,
 'override_profile_size': False,
 'page_breaks_before': u'/',
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier New',
 'pdf_mono_font_size': 16,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Helvetica',
 'pdf_serif_family': u'Times New Roman',
 'pdf_standard_font': u'serif',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/NyDFAA.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: KFX Input running
on /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/j_7_hf.kfx
Software versions: KFX Input 1.5.0, calibre 2.81, Darwin-17.4.0-x86_64-i386-64bit
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/j_7_hf.kfx
Processing container: /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/j_7_hf.kfx
kfxgen version: 7.149.1.0/PackageVersion:YJReaderSDK-1.6.1034.62 Month-Day:12-21
Features: CanonicalFormat-2, kfxgen.textBlock-1, max_id-716, reflow-style-1
Metadata: ASIN=B00ELW92T8, asset_id=CR!Q5NPF1VYXH5VZ0AP8X3YB97XVH8P, author="Kahn Jr., Peter H.", book_id=P5w07iS7SlyZDTqzN4VagQ1, cde_content_type=EBOK, content_id=B00ELW92T8, cover_image=534x800, creator_version=2.15.0, description=..., file_creator=YJConversionTools, is_sample=False, issue_date=2011-02-25, language=en, publisher="The MIT Press", reading_orders=1, selection=enabled, title="Technological Nature: Adaptation and the Future of Human Life (MIT Press)"
Converting book to EPUB 2.0
Format is EBOK
Successfully converted kfx to EPUB -- running EPUB input plugin
Found HTML cover OEBPS/part0000.xhtml
KFX Input plugin processing complete
Parsing all content...
Parsing OEBPS/part0016.xhtml ...
Parsing OEBPS/part0008.xhtml ...
Parsing OEBPS/part0003.xhtml ...
Parsing OEBPS/part0010.xhtml ...
Parsing OEBPS/part0019.xhtml ...
Parsing OEBPS/part0009.xhtml ...
Parsing OEBPS/part0017.xhtml ...
Parsing OEBPS/part0012.xhtml ...
Parsing OEBPS/part0014.xhtml ...
Parsing OEBPS/part0004.xhtml ...
Parsing OEBPS/part0001.xhtml ...
Parsing OEBPS/part0002.xhtml ...
Parsing OEBPS/stylesheet.css ...
Parsing OEBPS/part0013.xhtml ...
Parsing OEBPS/part0005.xhtml ...
Parsing OEBPS/part0000.xhtml ...
Parsing OEBPS/part0006.xhtml ...
Parsing OEBPS/part0018.xhtml ...
Parsing OEBPS/part0007.xhtml ...
Parsing OEBPS/part0011.xhtml ...
Parsing OEBPS/part0015.xhtml ...
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 1049 items of level: div_1
div_1  left margin stats: Counter()
div_1  right margin stats: Counter()
Cleaning up manifest...
Trimming unused files from manifest...
Trimming u'OEBPS/part0000.xhtml' from manifest
Python function terminated unexpectedly: PDF Output failed, see log for details
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1238, in run
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 156, in convert
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 239, in convert_text
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 265, in write
  File "site-packages/calibre/ebooks/pdf/render/from_html.py", line 255, in dump
Exception: PDF Output failed, see log for details
Creating PDF Output...
Splitting markup on page breaks and flow limits, if any...
Converting input as a text based book...
Serializing oeb input to disk for processing...
Rendering pages to PDF...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0001.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0002.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0003.xhtml...
Loading font: family_name=Times New Roman full_name=Times New Roman postscript_name=TimesNewRomanPSMT subfamily_name=Regular
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0004.xhtml...
Loading font: family_name=Sabon full_name=Sabon-Bold postscript_name=Sabon-Bold subfamily_name=Bold
Loading font: family_name=Times New Roman full_name=Times New Roman Bold postscript_name=TimesNewRomanPS-BoldMT subfamily_name=Bold
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0005.xhtml...
Loading font: family_name=Times New Roman full_name=Times New Roman Italic postscript_name=TimesNewRomanPS-ItalicMT subfamily_name=Italic
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0006.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0007.xhtml...
Loading font: family_name=Sabon full_name=Sabon-Roman postscript_name=Sabon-Roman subfamily_name=Regular
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0008.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0009.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0010.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0011.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0012.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0013.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0014.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0015.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0016.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0017.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0018.xhtml...
Processing /var/folders/lm/x2xxxcyj7s59fmkjvvc38cr00000gn/C/calibre_2.81.0_tmp_7U_A93/qHkcKZ_pdf_out/OEBPS/part0019.xhtml...
Traceback (most recent call last):
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 152, in end
  File "site-packages/calibre/ebooks/pdf/render/serialize.py", line 517, in end
  File "site-packages/calibre/ebooks/pdf/render/fonts.py", line 244, in embed_fonts
  File "site-packages/calibre/ebooks/pdf/render/fonts.py", line 168, in embed
  File "site-packages/calibre/utils/fonts/sfnt/subset.py", line 102, in pdf_subset
  File "site-packages/calibre/utils/fonts/sfnt/subset.py", line 74, in subset_postscript
  File "site-packages/calibre/utils/fonts/sfnt/cff/table.py", line 219, in subset
  File "site-packages/calibre/utils/fonts/sfnt/cff/table.py", line 85, in __init__
  File "site-packages/calibre/utils/fonts/sfnt/cff/table.py", line 148, in __init__
  File "site-packages/calibre/utils/fonts/sfnt/cff/table.py", line 157, in parse_fmt0
  File "site-packages/calibre/utils/fonts/sfnt/cff/table.py", line 156, in <genexpr>
IndexError: list index out of range

**Comment by ElleKayEm** [comment]
DRM removal happens on import, not during conversion.  I'm pretty sure the DRM has been removed, but it's hard to tell without an import log.  I notice you're using a pretty old version of calibre.  I'd update that.  Then if it still won't convert, I'd ask over at the KFX Input plugin thread at MobileRead:

https://www.mobileread.com/forums/showthread.php?t=291290

**Comment by 0George0** [comment]
Thanks for your replies. @ElleKayEm I have updated Calibre, but this made no difference unfortunately. @j-howell I have converted to an epub, but I don't know how to remove the fonts - could you point me to more information on this?

**Comment by ElleKayEm** [comment]
Since the DRM is obviously removed, you can close this issue.
