### ISSUE TITLE
Error: Decryption Unsucessful; No valid pid found DRM Removal Failed.

### ISSUE THREAD

**Issue by mlevin77** [apprenticeharper/DeDRM_tools#575]
On a book I downloaded (bought) from Amazon (Kindle version), tools v5.3.1 say

Error: Decryption Unsucessful; No valid pid found   
DRM Removal Failed.

while tools 6.6.1 don't say anything, but the log has

Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/mlevin/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Couldn't decrypt file.
Could not retrieve Kindle for Mac/PC key. 
There was an error with 1 ebook:
xxxxxxxxxx.azw couldn't be decrypted.

   I'm on Apple OS X High Sierra. What am I missing? what does this error mean?

**Comment by ElleKayEm** [comment]
Wow, v5.3.1!  That's really old -- not too surprising that didn't work.  People are having trouble with this latest release though.  Was the book downloaded with the current installation of Kindle for Mac on this machine and user?

**Comment by mlevin77** [comment]
Yes, latest Kindle was used to download. If 5.31 is too old, and 6.6.1 is troublesome, what's a good version to use (and where to get it)?  Also, I have vague memories that this "no valid pid found" is a generic error that means it doesn't know my Amazon credentials needed to decode, no?

**Comment by ElleKayEm** [comment]
I've seen someone say 6.6.0 of the stand-alone Mac app worked fine.  The current version of the plugin is also fine.  Current and previous releases are all here:

https://github.com/apprenticeharper/DeDRM_tools/releases

It should be able to retrieve your key as long as the book was downloaded with Kindle for Mac that is on the same machine and user as DeDRM.  But here it wasn't able to.  So I wondered if the book had been downloaded with another/previous installation or by another method.

**Comment by mlevin77** [comment]
I just tried 6.6.0 and it doesn't work on all the books either. It worked on some, but there are a couple of books that just don't work. The log shows:

There is 1 ebook to be decrypted.
Processing file: B000TRMGOM_EBOK.azw
shellcommand: /usr/bin/python '/Users/mlevin3/Desktop/DeDRM_tools_6.6.0/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/mlevin3/Library/Preferences/com.apprenticealf.dedrm/Local Kindle Key.k4i' -s 'B009A1A010550607' '/Users/mlevin3/Dropbox/TO WORK from home/to import/B000TRMGOM_EBOK.azw' '/Users/mlevin3/Desktop/' > '/Users/mlevin3/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult:  /usr/bin/python: can't open file '/Users/mlevin3/Desktop/DeDRM_tools_6.6.0/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/k4mobidedrm.py': [Errno 2] No such file or directory
shellcommand: /usr/bin/python '/Users/mlevin3/Desktop/DeDRM_tools_6.6.0/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/mlevin3/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/mlevin3/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult:  /usr/bin/python: can't open file '/Users/mlevin3/Desktop/DeDRM_tools_6.6.0/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/kindlekey.py': [Errno 2] No such file or directory
There was an error with 1 ebook:
B000TRMGOM_EBOK.azw couldn't be decrypted.

   it's kind of weird, it says it can't find kindlekey.py but it I see it there, at the path it's showing.

Also weird is that several of my books, downloaded by the latest Kindle app, are not single files but show up as folders, which contain a small .azw file (too small to be the actual content?) and a bigger .azw.res file). Which of those should DeDRM be pointed at?

I guess I will try the Calibre plug-in next. Or maybe I can find an older version of Apple Kindle app to see if it downloads a better format?

**Comment by ElleKayEm** [comment]
Are they books that were downloaded to a different computer?  Because I see a dropbox file path.  Again, DeDRM and Kindle for Mac need to be on the same machine and user -- each app has its own unique key, even on the same account.  Even reinstalling will change the key.

The books in separate folders would be KFX format.  Here's a post with various methods of working around or dealing with those:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by mlevin77** [comment]
Thanks!! I've gotten an older version of Apple Kindle, and it seems to save files that the Calibre plug-in can decode. So for the time being, all set.

**Comment by ElleKayEm** [comment]
Good.  You can close the issue if you're all set.

**Comment by mlevin77** [comment]
Well, I'm all set but the issue is still an issue with the latest version, so I would hope it gets fixed, but I will close it for now.

**Comment by ElleKayEm** [comment]
There are a few other open issues for the Mac and the Windows stand-alone apps.
