### ISSUE TITLE
Un-DRMed file doesn't go to specified directory

### ISSUE THREAD

**Issue by stark700** [apprenticeharper/DeDRM_tools#576]
Running 6.5.3 on Win 10. The tools have found the appropriate key for Barnes and Noble, but when I drag the epub into the DeDRM bat, the thing says "success" but it does not dump the nodrm file into the folder I specified. Any ideas?

I tried using the calibre plugin, but it doesn't remove the BN DRM for whatever reason, when I drag the epub into calibre

I can't run a later version of the tools because something broke. Idk if it's the changed folder structure, but the app just doesn't run at all.

**Comment by stark700** [comment]
Well this is weird, it doesn't recognize that the epub has DRM

DeDRM v6.5.3: Processing: 2940044448551.epub...
2940044448551 is not DRMed.
DeDRM v6.5.3: Success

DeDRM v6.5.3: Complete:  Successes: 1, Failures: 0

**Comment by stark700** [comment]
I got the 6.6.1 plugin for calibre

calibre Debug log
calibre 2.58 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && Obok DeDRM
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 15.59 seconds with 2 books
DeDRM v6.6.1: Trying to decrypt 2940044448551.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: “2940044448551.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 408, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Couldn't decrypt after 0.7 seconds. DRM free perhaps?
Added Superman Sampler 2013 to db in: 3.1
Added 1 books in 6.6 seconds

**Comment by ElleKayEm** [comment]
Ah, it's a comic.  Part of its DRM is stored in a separate database.  It takes some work to get it DRM-free, and some more work to make it readable outside a nook app.

Here's a comment where I explain how to do it:

https://apprenticealf.wordpress.com/2012/09/10/drm-removal-tools-for-ebooks/comment-page-38/#comment-62274

One additional note...if your rights.xml file has a "permissions" section, just delete everything from the opening to the closing permission tags.
