### ISSUE TITLE
Cant DeDRM with 6.6.1 and Kindle Paperwhite

### ISSUE THREAD

**Issue by m-gorn** [apprenticeharper/DeDRM_tools#577]
What i did on Mac and Calibre

a) installer DeDRM 6.6.1
b) KfX Plugin
c) tryed it with and without Key of my Kindle in the preferences 

with key:

```
Job:

 4 Dateien zur Übertragung vom Gerät vorbereiten started
DeviceJob: 4 Dateien zur Übertragung vom Gerät vorbereiten done, calling callback
DeviceJob: 4 Dateien zur Übertragung vom Gerät vorbereiten callback returned
DeDRM v6.6.1: Trying to decrypt Der Gesprungene Kristall_ Die Legende von Drizzt (DIE VERGESSENEN WELTEN 1)_B006MKWC5I.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Der Gesprungene Kristall: Die Legende von Drizzt (DIE VERGESSENEN WELTEN 1) (German Edition)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Der Gesprungene Kristall: Die Legende von Drizzt (DIE VERGESSENEN WELTEN 1) (German Edition) to db in: 0.0
Added 1 books in 0.7 seconds
DeviceJob: set_books_in_library: books to process= 22
Job: 4 Dateien zur Übertragung vom Gerät vorbereiten finished
Keine Details verfügbar.
DeviceJob: set_books_in_library finished: time= 0.0131890773773
Job: 5 Buch auf Gerät anzeigen started
DeviceJob: 5 Buch auf Gerät anzeigen done, calling callback
DeviceJob: 5 Buch auf Gerät anzeigen callback returned
Worker Launch took: 0.178212881088
Job: 5 Buch auf Gerät anzeigen finished
Keine Details verfügbar.
Worker Launch took: 0.185185909271
```

without key:
```
8 Dateien zur Übertragung vom Gerät vorbereiten started
DeviceJob: 8 Dateien zur Übertragung vom Gerät vorbereiten done, calling callback
DeviceJob: 8 Dateien zur Übertragung vom Gerät vorbereiten callback returned
DeDRM v6.6.1: Trying to decrypt Der Gesprungene Kristall_ Die Legende von Drizzt (DIE VERGESSENEN WELTEN 1)_B006MKWC5I.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Der Gesprungene Kristall: Die Legende von Drizzt (DIE VERGESSENEN WELTEN 1) (German Edition)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Der Gesprungene Kristall: Die Legende von Drizzt (DIE VERGESSENEN WELTEN 1) (German Edition) to db in: 0.0
Added 1 books in 0.6 seconds
DeviceJob: set_books_in_library: books to process= 22
DeviceJob: set_books_in_library finished: time= 0.0103938579559
Job: 8 Dateien zur Übertragung vom Gerät vorbereiten finished
Keine Details verfügbar.
Worker Launch took: 0.174782991409
```

**Comment by ElleKayEm** [comment]
Is the book directly from the Paperwhite?  Or if downloaded from the website, did you choose your Paperwhite as the device?  Then it should work if your Paperwhite's serial number is entered into the E-ink Kindle section of the plugin's customization correctly.  Double-check you have the correct number by copy and paste from the website, removing any spaces.

**Comment by juantorres85** [comment]
Hello good day
Thanks for helping and developing, he tried to convert my books, but the same error is shown as @m-gorn (I leave a copy of the record). I have followed all the instructions in https://www.mobileread.com/forums/showthread.php?t=291290 and also in https://apprenticealf.wordpress.com/ but I have not managed to open or convert them.
I would appreciate if you can help me.
Sincerely, Juan Torres

calibre Registro de depuración
calibre 3.28  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 6, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 6, 1) && KFX metadata reader (from KFX Input) (1, 6, 1) && KFX Input (1, 6, 1) && Set KFX metadata (from KFX Output) (1, 21, 1) && KFX Output (1, 21, 1)
calibre 3.28  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 6, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 6, 1) && KFX metadata reader (from KFX Input) (1, 6, 1) && KFX Input (1, 6, 1) && Set KFX metadata (from KFX Output) (1, 21, 1) && KFX Output (1, 21, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.664921466 x 127.590697674
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
[1.42] main UI initialized...
[1.42] Hiding splash screen
[55.88] splash screen hidden
[55.88] Started up in 55.88 seconds with 1 books
Worker Launch took: 0.139000177383
Worker Launch took: 0.135999917984
Worker Launch took: 0.149000167847
Job: 3 Convertido el libro 1 de 1 (Gente Común Perdidos y Hallados: Encuentros con el Dios viviente (Spanish Edition)) finished
Convertido el libro 1 de 1 (Gente Común Perdidos y Hallados: Encuentros con el Dios viviente (Spanish Edition))
	C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\calibre_ydi0zd\\vbmopl.jpeg'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\calibre_ydi0zd\\a938jq.opf'
	  output_profile: 'generic_eink'
	Resolved conversion options
	calibre version: 3.28.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\calibre_ydi0zd\\vbmopl.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x05564E10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x054A1030>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\calibre_ydi0zd\\a938jq.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\ADMINI~1\AppData\Local\Temp\calibre_ydi0zd\hvi3va.kfx-zip
	Software versions: KFX Input 1.6.1, calibre 3.28, Windows-10-10.0.17134-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\ADMINI~1\AppData\Local\Temp\calibre_ydi0zd\hvi3va.kfx-zip
	Processing container: B00B5JMCEC_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 98, in convert
	  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 95, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
	KFXDRMError: Book container B00B5JMCEC_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 101, in convert
	calibre.ebooks.DRMError: This book has DRM!

stdout+stderr from file dialog helper: ['', 'Qt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\n']
piped data from file dialog helper: ['\x15h@E\xdc\x1d\xaa\x81\x80\x92\n\x81\xa6&%i\xdd\xd6\xa5\xf6\xfd\xf4\xbeM\x93}\xa5\xee\xff\x16\x9dk', 'C:\\Users\\ADMINing\\Documents\\Luisibook\\My Kindle Content\\B00B5JMCEC_EBOK\\B00B5JMCEC_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.6.1: Importing C:\Users\ADMINing\Documents\Luisibook\My Kindle Content\B00B5JMCEC_EBOK\B00B5JMCEC_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\ADMINI~1\AppData\Local\Temp\calibre_ydi0zd\ulpfue.kfx-zip
DeDRM v6.6.1: Trying to decrypt ulpfue.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: ulpfue
Got DSN key from database default_key
Found 2 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7144d55c-a0b6-4d2f-ac3e-b474757bba2c.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\ADMINing\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\ADMINing\AppData\Local\Amazon\Kindle\storage\.kinf2011
Couldn't decrypt file.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.6.1: Packaging C:\Users\ADMINI~1\AppData\Local\Temp\calibre_ydi0zd\ulpfue.kfx-zip
Processing container: B00B5JMCEC_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 76, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
KFXDRMError: Book container B00B5JMCEC_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\ADMINI~1\AppData\Local\Temp\calibre_ydi0zd\ay7iiq_add_books\0\B00B5JMCEC_EBOK.kfx-zip
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Gente Común Perdidos y Hallados: Encuentros con el Dios viviente (Spanish Edition) to db in: 0.1
Added 1 books in 0.6 seconds
Worker Launch took: 0.134999990463

**Comment by ElleKayEm** [comment]
Doesn't look like that book was downloaded with Kindle for PC on the same machine and user as calibre with DeDRM.

**Comment by juantorres85** [comment]
Thank you very much for the help. If it's a PC with Kindle and caliber with dedrm. I will be creating a post for Kindle pc.
