### ISSUE TITLE
Keyfile fetch failed .. plz read

### ISSUE THREAD

**Issue by lopesta** [apprenticeharper/DeDRM_tools#579]
I got the problem Keyfile fetch failed .  when i am using barnes and nobles ePub keyfile fetch v1.1

i entered correct email/pass combination .. plus my password only contains alpha-numeric characters .

i went to the url that apprentice supplied in another thread .. and entered the email/pass .. i got something 
like this
1o0NjK03CRlJfcLbgGEzhjHkDOLM=

i saved it as plain in .b64 file and went to DeDRM_Windows_Application but all ebooks downloaded were failed to decrypt .

whats wrong here ? i think Barnes changed something on their end or that they switched back to old
scheme which then we need the old tools .. but this is guess and try and will take long to pick the correct one.

another question if the returned from the url contains special characters do i need to escape them ? beside email/pass combination as well ??

i entered the password correctly and i log in .. is there a new version of keyfile fetch other than 1.1 ?

**Comment by lopesta** [comment]
Oh Update .. sorry  .. it worked i have to replace the @ in the email with the Escape Code which is : %40

and it worked finally ..

but i had to manually deal with this .. the program itself keyfile fetch 1.1 still fail despite i tried to enter the %40 instead of @ on it . same message keyfile fetch failed .

**Comment by lopesta** [comment]
any news regarding key file fetch program v 1.1 if you can update it to handle the @ or enescaped characters ?

**Comment by ElleKayEm** [comment]
How come you're running the key fetch script on its own?  Are you unable to configure DeDRM with your B&N info within the app itself?

As for the result you got by using the url directly, the "1" at the beginning isn't part of the key.  It should be 28 characters.  If you view the page source in your browser, you can see that the "1" is actually a separate field.

**Comment by lopesta** [comment]
i ran it through version DeDRM_tools-master_v6.5.5 ,, particularly using key fetch file that throw out key file hash which then be used on DeDRM_Windows_Application .. through set then ok .. after that i throw barnes epub on it . i had to do this way because i need to retain same file name from BN .
so i am not using the keyfile fetch alone :)

the 1 or in another words the hash i gave you was just as example (assume it) .. that was given when i entered the @ in url as its .. the one which worked is by me when i had to resolve @ to the percent code
but this happened manually : 
**1-** modify url by entering correct escaped (the @ should be entered as %40 in email variable)
i am wondering why this has happened lately .. as i was entering in the keyfile all the time before and was working untill recently . we need a fix to the program .. some people like doing it without calibre .
**2-** i then save as key file that sent to the windows decrypt program provided within the package
(drop epub to the batch file) .. and then it process succefully .

we need a fix to this problem so we can do it using the program not by manually the url..etc.. and we appreciate all apprentice teamwork .

**Comment by lopesta** [comment]
what app also you referring to ? you mean calibre and the dedrm plugins ?
i don't want to use calibre as it change output decrypted BN file into another names than original .
i need to retain same file name originally given by BN  .

**Comment by ElleKayEm** [comment]
Okay, in some browsers it will show a "1" at the beginning of the key, but you can see it isn't actually part of the key when you look at the page source.  I thought that you'd run into that since your example had 29 instead of 28 characters.

No, I was referring to the stand-alone app.  You're unable to configure it with your B&N info?  You had to find the key with the url and add it manually?

**Comment by lopesta** [comment]
YOU : You're unable to configure it with your B&N info? You had to find the key with the url and add it manually?

ME : yes

**Comment by ElleKayEm** [comment]
Hmmm, all three versions of DeDRM - plugin and both standalone apps -- use the exact same ignoblekeyfetch.py.  I don't use the stand-alone, but it still works in the plugin.

**Comment by lopesta** [comment]
can you still give me the url once again .. i think i lost it from the other thread .. thanks in advance .

**Comment by ElleKayEm** [comment]
You can see it in the [code here](https://github.com/apprenticeharper/DeDRM_tools/blob/master/src/ignoblekeyfetch.py) starting at line 115.

Nook for PC version:
`https://cart4.barnesandnoble.com/services/service.aspx?Version=2&acctPassword=[PASSWORD]&devID=PC_BN_2.5.6.9575_[4 RANDOM NUMBERS]&emailAddress=[EMAIL ADDRESS]&outFormat=5&schema=1&service=1&stage=deviceHashB`

Android devices switch out the "devID" part with:
&devID=hobbes_9.3.50818_

In most cases, you'll get the same key with either one.

**Comment by lopesta** [comment]
thx ElleKayEm , i have finally managed to resolve the issue by running calibre with plugins , then on BN plugin i put my BN credential then fetch the key and save it then manually handle decrypting the eBooks purchased with windows standalone batch dedrming , so i maintain original file names .
