### ISSUE TITLE
Not stripping DRM - Log says "Found 0 keys to try"

### ISSUE THREAD

**Issue by mu2pilot** [apprenticeharper/DeDRM_tools#58]
I'm unable to remove DRM from Kindle books.  Here is a log detailing the importation of one book.  What am I doing wrong?

TIA.

calibre Debug log
calibre 2.48  isfrozen: True is64bit: True
Darwin-14.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.5.0', 'Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64')
Python 2.7.9
OSX: ('10.10.5', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM
Starting up...
Loaded cached store plugin for: Virtualo at version: 6
Loaded cached store plugin for: Cdp.pl at version: 8
Loaded cached store plugin for: Ebookpoint at version: 6
Loaded cached store plugin for: Koobe at version: 5
DeDRM v6.3.4: Trying to decrypt B00AEBEVTQ_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 256
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Eleven Rings: The Soul of Success
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.3.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.3.4: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/**********/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'a59b4407611b' and UserName 'jaygarnett'
DeDRM v6.3.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 256
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Eleven Rings: The Soul of Success
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.3.4: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 590, in run
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
DeDRMError: DeDRM v6.3.4: Ultimately failed to decrypt after 0.3 seconds
Started up in 15.29 seconds with 0 books
Added Eleven Rings: The Soul of Success to db in: 0.1
Added 1 books in 0.8 seconds
InputFormatPlugin: MOBI Input running
on /Users/jaygarnett/Documents/Calibre Library/Phil Jackson/Eleven Rings_ The Soul of Success (106)/Eleven Rings_ The Soul of Success - Phil Jackson.azw
Found KF8 MOBI of type 'standalone'
Worker Launch took: 0.0429649353027

**Comment by ElleKayEm** [comment]
If you look further down the log, it says it found a key, but it didn't work for this book.  Download the book with Kindle for Mac which is installed to the same machine as calibre, and it should work.

**Comment by mu2pilot** [comment]
Thank you, that fixed it.
