### ISSUE TITLE
DeDRM fails on new books

### ISSUE THREAD

**Issue by cheguevilla** [apprenticeharper/DeDRM_tools#584]
Hi,
The tool works for most of the books. For some books that I bought recently, it fails to remove the DRM.
Sample logs attached.
[Riot days log.txt](https://github.com/apprenticeharper/DeDRM_tools/files/2216155/Riot.days.log.txt)

**Comment by ElleKayEm** [comment]
If the book was downloaded from the website, you need to have an E-ink Kindle (not a Fire) and enter its serial number into the plugin customization.

**Comment by cheguevilla** [comment]
Solved, I realised that it stopped working since I reinstalled Win on the PC. The serial number is case sensitive.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
