### ISSUE TITLE
Is there a plugin to use for borrowed azw books?

### ISSUE THREAD

**Issue by lburg801** [apprenticeharper/DeDRM_tools#586]
I use Calibre and have wondered why my kindle books are sometimes scrambled. Mostly I thought the azw3 format was probably fine, as I was reading the coverted epub edition.

Today I stumbled on a problem that also existed in the azw3 and that is when I realized the problem was probably the plugin.

So checked out the book the library and reloaded it in Callibre only to have it turn out worse than the previous, which was probably sent to me by my Kindle-devoted friend.

That is what led me here and I soon read that your plugin does not work on borrowed books (actually, it works fine on borrowed epubs). Do you know of a program that works for borrowed azw? I would appreciate the help. Thanks

**Comment by ElleKayEm** [comment]
Not working on borrowed books is intentional:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#the-drm-wasnt-removed-and-the-log-says-failed-to-decrypt-with-error-cannot-decode-library-or-rented-ebooks-what-now
