### ISSUE TITLE
Cannot deDRM w/6.6.1 on Kindle Voyage

### ISSUE THREAD

**Issue by hphish** [apprenticeharper/DeDRM_tools#588]
I was able to deDRM with my PaperWhite, I no longer can with my new Voyage. See debug log on one particular file:

calibre Debug log
calibre 3.28  embedded-python: True is64bit: True
Darwin-15.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '15.6.0', 'Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.11.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 6, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 6, 1) && KFX metadata reader (from KFX Input) (1, 6, 1) && KFX Input (1, 6, 1)
calibre 3.28  embedded-python: True is64bit: True
Darwin-15.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '15.6.0', 'Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.11.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 6, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 6, 1) && KFX metadata reader (from KFX Input) (1, 6, 1) && KFX Input (1, 6, 1)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 111.000001667 x 110.000001652
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[2.41] main UI initialized...
[2.41] Hiding splash screen
[2.42] splash screen hidden
[2.42] Started up in 2.42 seconds with 375 books
DeDRM v6.6.1: Trying to decrypt A Secret One.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Secret One
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added A Secret One to db in: 0.0
Added 1 books in 0.7 seconds
2018-07-23 15:10:43.254 Calibre[16724:458144] deliverNotificationWithTitle()
* Notification delivered.

**Comment by ElleKayEm** [comment]
Double-check that you've entered your Voyage's serial number correctly.  Try copy and paste from the website (removing spaces).

**Comment by hphish** [comment]
Tried doing that and still:

calibre Debug log
calibre 3.28  embedded-python: True is64bit: True
Darwin-15.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '15.6.0', 'Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT
2018; root:xnu-3248.73.11~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.11.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX
Input) (1, 6, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 6,
1) && KFX metadata reader (from KFX Input) (1, 6, 1) && KFX Input (1, 6, 1)
calibre 3.28  embedded-python: True is64bit: True
Darwin-15.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '15.6.0', 'Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT
2018; root:xnu-3248.73.11~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.11.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX
Input) (1, 6, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 6,
1) && KFX metadata reader (from KFX Input) (1, 6, 1) && KFX Input (1, 6, 1)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 111.000001667 x 110.000001652
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[2.44] main UI initialized...
[2.44] Hiding splash screen
[2.45] splash screen hidden
[2.45] Started up in 2.45 seconds with 375 books
DeDRM v6.6.1: Trying to decrypt A Secret One.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Secret One
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID 4LOprXHdKX.
Decrypting. Please wait . . . done
Decryption succeeded after 0.1 seconds
DeDRM v6.6.1: Finished after 0.1 seconds
Added A Secret One to db in: 0.0
Added 1 books in 0.7 seconds
2018-07-23 15:29:07.064 Calibre[16903:465359] deliverNotificationWithTitle()
* Notification delivered.

**Comment by hphish** [comment]
@ElleKayEm always the easy answer glaring at us because we're idiots :) thanks so much!

**Comment by ElleKayEm** [comment]
:) No problem.  If you're all set, you can close the issue.
