### ISSUE TITLE
DeDRM mac app not working after 6.5.5

### ISSUE THREAD

**Issue by jalavera** [apprenticeharper/DeDRM_tools#590]
I attach an example log from DeDRM 6.61 and from 6.5.5 (last version which works for me). I tested in macOs 10.13.6 and 10.14 beta4. None of both work.

[DeDRM655.log](https://github.com/apprenticeharper/DeDRM_tools/files/2228204/DeDRM655.log)
[DeDRM661.log](https://github.com/apprenticeharper/DeDRM_tools/files/2228205/DeDRM661.log)

Thanks!!

**Comment by ElleKayEm** [comment]
There have been a few reports on this.  Some workarounds are discussed in issues #505 and #545.

**Comment by apprenticeharper** [comment]
It does seem that this is because PyCrypto is missing. Solution added to the FAQs

**Comment by jalavera** [comment]
Finally I need only to use this 2 commands on terminal (tested on Mojave and v.6.6.1):
If your system can't find others libs please check DeDrm log and install what you need.

python -m pip install pylzma --force
python -m pip install pycryto --force

Please add this to FAQ ;-)

**Comment by ElleKayEm** [comment]
You might want to reopen this issue if you can.
