### ISSUE TITLE
KFX files that have been DeDRM'd and transferred to Kindle lack covers.

### ISSUE THREAD

**Issue by Tomifonication** [apprenticeharper/DeDRM_tools#600]
Admittedly I'm not too sure if this is an issue with the DRM plugin or with Calibre, or even the Kindle; I've used the DeDRM tool in Calibre to remove the DRM from a KFX file.

After, I've updated said file with new metadata and saved it as a new KFX file. I've then imported this back to Calibre, and then used Send to Device to load it to my Kindle Oasis. 

This works, and the file is usable, except it has no cover art, despite the cover being included in the metadata.

Any thoughts?

**Comment by ElleKayEm** [comment]
Looks like this might be what you're looking for:

https://www.mobileread.com/forums/showthread.php?t=272407

Scroll down to "Showing Cover Thumbnail Images on E-Ink Kindle Devices"

**Comment by Tomifonication** [comment]
Hmm, that seems interesting, but unfortunately didn't seem to work. It's not detecting the KFX files when running the program.

**Comment by Tomifonication** [comment]
Resolved! Thanks for your assistance.
