### ISSUE TITLE
hello! please help! thank you!

### ISSUE THREAD

**Issue by LIM993** [apprenticeharper/DeDRM_tools#603]
here is the log :

-

calibre Debug log
calibre 3.29 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.29 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[1.50] main UI initialized...
[1.50] Hiding splash screen
[12.62] splash screen hidden
[12.62] Started up in 12.62 seconds with 25 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x07\xa1&\xba\x053\x06\xbdFm\xd0h\x04\xcbM\xcc9e\xec\xc3\xa4g\x04\x93\xd8\r\xbc\xc5\xe5\x8fvI', 'C:\\Users\\LIM99321\\Desktop\\The Hobbit (Lord of the Rings).azw3']
DeDRM v6.6.1: Trying to decrypt The Hobbit (Lord of the Rings).azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Hobbit (Lord of the Rings)
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 6 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\LIM99321\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\LIM99321\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4166462375' and UserName '4c494d3939333231'
DeDRM v6.6.1: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Hobbit (Lord of the Rings)
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Hobbit (Lord of the Rings) to db in: 0.1
Added 1 books in 0.8 seconds
Worker Launch took: 0.133999824524

-

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) and you need to enter its serial number into the plugin customization.

**Comment by LIM993** [comment]
so in order to proceed from here, i need to have an e-ink kindle, is that right?

**Comment by ElleKayEm** [comment]
If you don't have an E-ink Kindle, you can import your books from Kindle for PC.  There are a couple ways to avoid KFX format in this thread:

https://www.mobileread.com/forums/showthread.php?t=283371

Or you can use the KFX Input plugin to gather the files needed to DeDRM those.

**Comment by LIM993** [comment]
thank you so much for your help! :)
