### ISSUE TITLE
Batch-import Kindle library

### ISSUE THREAD

**Issue by christianlupus** [apprenticeharper/DeDRM_tools#604]
I have the habit of buying/ordering/collecting a bunch of kindle files and in the aftermath downloading and importing into calibre. The reason is that I use linux as my main OS and I do not fire up a virtual windows I buy a single ebook. Thus, there are bunches of a few dozen ebbok typically that need to be imported into calibre.
This worked quite easy recently as I only had to sort the kindle library by date and add the newly added files to calibre via drag'n'drop.

Since the new data structure of the kindle library (book in folders), I have to add all book separately. A very time-consuming and tendons work. What are your suggestions in order to get this done within reasonable time? I had the following ideas (although I do not know if all are usable):

- Put the kindle library in some folder accessible from within linux. Then I can search for all files with certain properties (creation date, file extension,...). These files could be either copied or linked to another location. Starting from there I could ...
  - ... install DeDRM under calibre running under linux. (As it is a python script it should be possible?!?) Then I import the clone/links into calibre under linux.
  - ... make the linked/cloned files visible in the virtual machine and import using windows' calibre installation.
  - ... import the files using some CLI magic into calibre.
- Import from calibre using the recursive add function. This might cause trouble with the other files (cover etc.) inside the kindle library.

What is your suggestion to import the files on a batch-level?

**Comment by ElleKayEm** [comment]
You can install the DeDRM plugin in Linux calibre.  It can be tricky to get set up to work with Kindle for PC under Wine.

Everything else seems like something to ask in MobileRead's calibre forum (and/or the KFX Input plugin thread if you're dealing with that format).

**Comment by christianlupus** [comment]
Is it needed to have kindle installed? I mean: Can I use kindle inside the VM and calibre (incl. DeDRM) outside?

**Comment by christianlupus** [comment]
OK, thank you for your information. I will stick to the windows based solution then for now.
