### ISSUE TITLE
Support for newer Adobe DRM

### ISSUE THREAD

**Issue by paul-mesnilgrente** [apprenticeharper/DeDRM_tools#606]
Hello,

I am trying to deDRM my last ebook with the calibre plugin but I just can't open the book in ADE 2.0.1. ADE displays `Error! Check activation.` but I have setup my Adobe ID.

I can open it with ADE 4.5 though. Do you think you will have support for newer Adobe DRM? I can't deDRM the `.epub` from ADE 4.5 as explained in the documentation.

Thank you.

**Comment by apprenticeharper** [comment]
Until someone produces a script to remove the newer Adobe DRM, these tools won't support it.
