### ISSUE TITLE
DeDRM Windows Application will not start Windows 10

### ISSUE THREAD

**Issue by Ironmaidens** [apprenticeharper/DeDRM_tools#607]
Hi,
I was using v6.5.5 and the Windows Application drag and drop worked fine, I upgraded to v6.6.0 and it would not work, so I went back to v6.5.5. I just upgraded to v6.6.1 and still no functionality, the cmd screen briefly appears then vanishes and there is no log file created. 
I upgraded python to v2.7.14.2717_win64 and pycrypto to v2.6.1_win64_py2.7 with no change, V6.5.5 still works ok.
I read a few similar problems but could not see an remedy, has anyone any suggestions.
thanks

**Comment by ElleKayEm** [comment]
Issue #547 has a fix that seems to have worked for a couple people.

**Comment by Ironmaidens** [comment]
Thanks no change still not working.
Anyone know how I can capture the cmd screen that briefly appears to vanishes to see if there is any error preventing the script running.
