### ISSUE TITLE
Kobo DRM not removed

### ISSUE THREAD

**Issue by nixlapi** [apprenticeharper/DeDRM_tools#608]
Tried three KOBO books (downloaded from Kobo to ADE 2.0), DRM not removed on any; Can read in Adobe 2.0; DRM successfully removed on Kindle book. New issue today, updated to latest Calibre and DeDRM plug-ins.
Any help much appreciated! 
----------
calibre Debug log
calibre 3.30 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && KoboTouchExtended (3, 0, 2) && EpubSplit (2, 1, 1) && Obok DeDRM (6, 5, 4)
calibre 3.30 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && KoboTouchExtended (3, 0, 2) && EpubSplit (2, 1, 1) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.75] main UI initialized...
[2.75] Hiding splash screen
[13.08] splash screen hidden
[13.08] Started up in 13.08 seconds with 2961 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['&\xf6\xc8\xe3\xa8|\xafE\xdb?f4p\x16\xec\x90\x9fp\xab\x95\xe7Mj\xd1>)\xda\x8f\xc7\x9f\x8a<', 'C:\\Users\\Eric\\Documents\\My Digital Editions\\West Coast Love.epub']
DeDRM v6.6.1: Trying to decrypt West Coast Love.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: West Coast Love.epub is a secure Adobe Adept ePub
DeDRM v6.6.1: Trying Encryption key default_key
Could not decrypt 3kziav.epub. Wrong key
DeDRM v6.6.1: Failed to decrypt with key default_key after 0.3 seconds
DeDRM v6.6.1: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v6.6.1: Exception when getting default Adobe Key after 0.4 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 346, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 403, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added West Coast Love to db in: 1.9
Added 1 books in 4.7 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x00000184FD8D82B0>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x00000184FD8D8160>> ignored

**Comment by ElleKayEm** [comment]
The installation of Adobe 2.0.1 where you can open your books is authorized with your Adobe ID and on the same machine and user as calibre with DeDRM?

**Comment by nixlapi** [comment]
Yes

**Comment by ElleKayEm** [comment]
Looks like it's picking up the wrong key -- maybe something left over from a previous installation.  I'd try a complete uninstall and reinstall of ADE.  See issue #348 for the details of what worked for someone else.

**Comment by nixlapi** [comment]
No luck, thanks though. Wonder if it's because Windows 10 won't let me delete the adept key?
Also tried uninstalling and reinstalling both ADE and Calibre.

**Comment by ElleKayEm** [comment]
Yeah, I'd say deleting the registry key is probably the most important part.  Did you open regedit as an administator?

**Comment by nixlapi** [comment]
Finally managed to get the reigstry key deleted and that was the lingering issue. So for anyone else stuck with this issue in Win10, I used the program Registry DeleteEx with the option checked to delete all subkeys.
Thanks again for the assistance, much appreciated!
