### ISSUE TITLE
Trouble with Mac AZW4 file

### ISSUE THREAD

**Issue by SpencerAnastasio** [apprenticeharper/DeDRM_tools#609]
I'm on a 2012 macbook pro with mac os 10.12.6. I downloaded an AZW4 file (rented textbook) via Kindle for MAC Version 1.17.1.

I can add the book to Calibre but I'm getting an error when converting the book to any other format. I'd like the pdf format ideally.

This is what I've copied from the error logs... please help.
(if this is not the info you need just let me know and I'll get the right info. I can use the command line pretty well.)

calibre, version 3.5.0 (darwin, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (Functions and Change)

Convert book 1 of 1 (Functions and Change)
Conversion options changed from defaults:
  verbose: 2
  cover: u'/var/folders/ps/0n9ntgcs2lgfvwpxnzj7n72c0000gn/C/calibre_3.5.0_tmp_o1veNc/SLU84k.jpeg'
  output_profile: 'generic_eink'
  read_metadata_from_opf: u'/var/folders/ps/0n9ntgcs2lgfvwpxnzj7n72c0000gn/C/calibre_3.5.0_tmp_o1veNc/EmLGB2.opf'
Resolved conversion options
calibre version: 3.5.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/ps/0n9ntgcs2lgfvwpxnzj7n72c0000gn/C/calibre_3.5.0_tmp_o1veNc/SLU84k.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x1094d6fd0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x1094f6410>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier New',
 'pdf_mono_font_size': 16,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Helvetica',
 'pdf_serif_family': u'Times New Roman',
 'pdf_standard_font': u'serif',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/ps/0n9ntgcs2lgfvwpxnzj7n72c0000gn/C/calibre_3.5.0_tmp_o1veNc/EmLGB2.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Python function terminated unexpectedly: No embedded PDF found in AZW4 file
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1074, in run
  File "site-packages/calibre/ebooks/azw4/reader.py", line 24, in unwrap
ValueError: No embedded PDF found in AZW4 file

**Comment by ElleKayEm** [comment]
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cant-get-the-tools-to-work-on-my-rented-or-library-ebooks

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#the-drm-wasnt-removed-and-the-log-says-failed-to-decrypt-with-error-cannot-decode-library-or-rented-ebooks-what-now
