### ISSUE TITLE
Kindle Book Fails to Convert

### ISSUE THREAD

**Issue by elmoreoocyte** [apprenticeharper/DeDRM_tools#612]
I selected download and transfer via USB, and am trying to convert via the same PC where I downloaded, using the 64 bit Calibre (on a 64 bit Win7 machine).  I have the kindleunpack plugin installed.

This is the log I get when attempting to add the file via debug mode:
calibre Debug log
calibre 3.30 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && KindleUnpack - The Plugin (0, 81, 5)
calibre 3.30 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && KindleUnpack - The Plugin (0, 81, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[2.80] main UI initialized...
[2.80] Hiding splash screen
[106.72] splash screen hidden
[106.72] Started up in 106.72 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xbc\x19\xf2L\xc3\xed\xa8\x8fJ\xcc[\x018L\xd5\xe1\x10\xb1\x94]\xf8+\xe1\xbe-\xd0|\xa1Mka\xa0', 'C:\\Users\\Captain Wilshire\\Downloads\\Systems Analysis and Design, 6th Edition.azw4']
DeDRM v6.6.1: Trying to decrypt Systems Analysis and Design, 6th Edition.azw4
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Systems Analysis and Design, 6th Edition
Found 2 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Captain Wilshire\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Systems Analysis and Design, 6th Edition to db in: 1.2
Added 1 books in 2.3 seconds
Worker Launch took: 0.201000213623
Job: 1 Convert book 1 of 1 (Systems Analysis and Design, 6th Edition) finished
Convert book 1 of 1 (Systems Analysis and Design, 6th Edition)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\CAPTAI~1\\AppData\\Local\\Temp\\calibre_jt_kj6\\kc4ay_.opf'
	  verbose: 2
	  cover: u'C:\\Users\\CAPTAI~1\\AppData\\Local\\Temp\\calibre_jt_kj6\\kzummv.jpeg'
	Resolved conversion options
	calibre version: 3.30.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\CAPTAI~1\\AppData\\Local\\Temp\\calibre_jt_kj6\\kzummv.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000000002642940>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x0000000002642C88>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\CAPTAI~1\\AppData\\Local\\Temp\\calibre_jt_kj6\\kc4ay_.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: AZW4 Input running
	on C:\Users\CAPTAI~1\AppData\Local\Temp\calibre_jt_kj6\6xtbg6.azw4
	Extracting PDF from AZW4 Container...
	Converting file to html...
	Python function terminated unexpectedly
	  pdftohtml failed with return code: 1
	Syntax Warning: May not be a PDF file (continuing anyway)
	Syntax Error: Couldn't find trailer dictionary
	Syntax Error: Couldn't find trailer dictionary
	Syntax Error: Couldn't read xref table (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\azw4_input.py", line 27, in convert
	  File "site-packages\calibre\ebooks\azw4\reader.py", line 57, in extract_content
	  File "site-packages\calibre\ebooks\conversion\plugins\pdf_input.py", line 52, in convert
	  File "site-packages\calibre\ebooks\pdf\pdftohtml.py", line 92, in pdftohtml
	calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
	Syntax Warning: May not be a PDF file (continuing anyway)
	Syntax Error: Couldn't find trailer dictionary
	Syntax Error: Couldn't find trailer dictionary
	Syntax Error: Couldn't read xref table

Convert book 1 of 1 (Systems Analysis and Design, 6th Edition)
Conversion options changed from defaults:
  read_metadata_from_opf: u'C:\\Users\\CAPTAI~1\\AppData\\Local\\Temp\\calibre_jt_kj6\\kc4ay_.opf'
  verbose: 2
  cover: u'C:\\Users\\CAPTAI~1\\AppData\\Local\\Temp\\calibre_jt_kj6\\kzummv.jpeg'
Resolved conversion options
calibre version: 3.30.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\CAPTAI~1\\AppData\\Local\\Temp\\calibre_jt_kj6\\kzummv.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000000002642940>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': u'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x0000000002642C88>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'personal_doc': u'[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\CAPTAI~1\\AppData\\Local\\Temp\\calibre_jt_kj6\\kc4ay_.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: AZW4 Input running
on C:\Users\CAPTAI~1\AppData\Local\Temp\calibre_jt_kj6\6xtbg6.azw4
Extracting PDF from AZW4 Container...
Converting file to html...
Python function terminated unexpectedly
  pdftohtml failed with return code: 1
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\azw4_input.py", line 27, in convert
  File "site-packages\calibre\ebooks\azw4\reader.py", line 57, in extract_content
  File "site-packages\calibre\ebooks\conversion\plugins\pdf_input.py", line 52, in convert
  File "site-packages\calibre\ebooks\pdf\pdftohtml.py", line 92, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) and enter its serial number into the plugin customization.

**Comment by elmoreoocyte** [comment]
So the DRM removal won't work if my only device is a Fire?

**Comment by ElleKayEm** [comment]
You could download it with Kindle for PC.

**Comment by elmoreoocyte** [comment]
This worked perfectly!  Thank you for your quick response and reminding me to try the Kindle for PC app!
