### ISSUE TITLE
Failed to decrypt Adobe Digital Editions book

### ISSUE THREAD

**Issue by raffam** [apprenticeharper/DeDRM_tools#614]
DeDRM 6.6.1 running on Windows with ActiveState Python 2.7 failed to decrypt an Adobe Digital Edition book.

DeDRM version is 6.6.1, running on Windows 10 with ActiveState Python 2.7.
Adobe Digital Edition version is 4.5.8.183423.
The book is [NBA coaches playbook](http://www.humankinetics.com/eproducts/ebooks/nba-coaches-playbook--techniques-tactics-and-teaching-points-ebook-good)

The log is as follows:

> DeDRM v6.6.1: Processing: NBA Coaches Playbook     .epub...
> Could not decrypt NBA Coaches Playbook     _temp.zip because of an exception:
> Traceback (most recent call last):
>   File "D:\data\programmi\DeDRM_tools\src\ineptepub.py", line 420, in decryptBook
>     bookkey = rsa.decrypt(bookkey.decode('base64'))
>   File "D:\data\programmi\DeDRM_tools\src\ineptepub.py", line 329, in decrypt
>     return self._rsa.decrypt(data)
>   File "C:\ActivePython27\lib\site-packages\Crypto\PublicKey\RSA.py", line 375, in decrypt
>     raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")
> NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead
> 
> 
> DeDRM v6.6.1: Failed
> 
> DeDRM v6.6.1: Complete:  Successes: 0, Failures: 1

**Comment by ElleKayEm** [comment]
There's a fix described in issue #547.  Or you can go back to version 6.5.5 or use the 6.6.1 calibre plugin.

Also be aware of possible issues with later versions of ADE:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-registered-adobe-digital-editions-30-or-later-with-an-adobe-id-before-downloading-but-my-epub-or-pdf-still-has-drm

**Comment by raffam** [comment]
I don't think it is related to #547. I did install `pylzma` and the application starts correctly. It just fails to decrypt the file.

It may be related to the new DRM scheme tough. I will investigate in the near future.

**Comment by raffam** [comment]
ok seems to work with calibre plugin
