### ISSUE TITLE
Can't De-DRM books in Calibre

### ISSUE THREAD

**Issue by library-user** [apprenticeharper/DeDRM_tools#617]
I've just had to move from an old PC running Windows XP. I have a Sony PRS350 eReader which uses Sony's Reader Library software - Reader for PC had a lot of problems so I stayed with Reader Library. When I import a book from Reader Library into Calibre, DRM is not removed. This is the original place where purchased books were put i.e. they are not copies. I cannot download another copy because a) I bought from W H Smith and Waterstones and they have moved out of the ebook market, and the one book I bought from KOBO still shows in my history but KOBO says that it is no longer available.
Can anything be done to get rid of DRM, please, otherwise all these books will become unreadable when I set up AdobeID on the new PC.
Thanks

**Comment by ElleKayEm** [comment]
The Sony Reader app used Adobe DRM epubs?  If you know the Adobe ID you used, you should be able to open them in Adobe Digital Editions authorized with that Adobe ID.  Then DeDRM should be able to get the key.

In the future always remove DRM as soon as possible!

**Comment by library-user** [comment]
Sorry - I do not understand your comment. I download books to Reader Library and then transfer them to the eReader. There is obviously DRM around, as, for example, when a library book times out, reading on the eReader is blocked with a 'this book is protected by DRM' - or something like that.
What do you mean that I should be able to open them in Adobe Digital Editions? I can read books either on the eReader or in ReaderLibrary. My point is, that having installed DeDRM v6.6.1 in Calibre, DRM is not removed. The PC on which I tried that broke (19 days old!) so I've had to get a replacement. I've installed Calibre on the new, new PC but when I tried to install the DeDRM tools, it fails with a message "Invalid plugin. It does not contain a top level _init_.py file" so I can't run a debug installation now. I've now got to find out what's wrong with the DeDRM tools.
Library-user

**Comment by library-user** [comment]
Hold on a minute. Just had some success. DeDRM installed, one book DeDRM'd. Have to go out. Will report back.
Library-user

**Comment by ElleKayEm** [comment]
Earlier I was just saying that the Sony Reader app (and devices) used the same type of DRM as Adobe Digital Editions.  ADE authorized with the same Adobe ID would be able to open the DRMed books.  And then the DeDRM plugin could find that key to remove the DRM.

Unless you have another question, you can close this issue.
