### ISSUE TITLE
Standalone OS X Application Will Not Start

### ISSUE THREAD

**Issue by spaz926** [apprenticeharper/DeDRM_tools#62]
When attempting to launch the standalone OS X application results in the following window:
![screen shot 2016-01-15 at 7 22 50 pm](https://cloud.githubusercontent.com/assets/990135/12369486/9f578064-bbbd-11e5-865c-b0b238fea542.png)

The log when launching is as follows: 

> 1/15/16 7:20:37.475 PM	com.apple.xpc.launchd[1]	(net.privatetunnel.ptcore) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
> 1/15/16 7:20:37.824 PM	com.apple.xpc.launchd[1]	(com.apple.ScriptEditor.id.707CCCD5-0C6C-4BEB-B67C-B6E866ADE85A.20832[5787]) Could not find and/or execute program specified by service: 13: Permission denied: /.../DeDRM_tools-master/DeDRM_Macintosh_Application/DeDRM.app/Contents/MacOS/droplet
> 1/15/16 7:20:37.824 PM	com.apple.xpc.launchd[1]	(com.apple.ScriptEditor.id.707CCCD5-0C6C-4BEB-B67C-B6E866ADE85A.20832[5787]) Service setup event to handle failure and will not launch until it fires.
> 1/15/16 7:20:37.824 PM	Finder[699]	spawn_via_launchd() failed, errno=111 label=com.apple.ScriptEditor.id.707CCCD5-0C6C-4BEB-B67C-B6E866ADE85A.20832 path=/.../DeDRM_tools-master/DeDRM_Macintosh_Application/DeDRM.app/Contents/MacOS/droplet flags=1 : LaunchApplicationClient.cp #1136 LaunchApplicationViaLaunchDJobLabel() q=com.apple.root.default-qos
> 1/15/16 7:20:37.824 PM	Finder[699]	spawn_via_launchd() failed, errno=111 label=com.apple.ScriptEditor.id.707CCCD5-0C6C-4BEB-B67C-B6E866ADE85A.20832 path=/.../DeDRM_tools-master/DeDRM_Macintosh_Application/DeDRM.app/Contents/MacOS/droplet flags=1

**Comment by apprenticeharper** [comment]
Check your security settings for unsigned applications. Also check the permissions on the droplet file - perhaps your unzip application hasn't set them right. I'll try to reproduce the problem sometime over the next few days.

**Comment by spaz926** [comment]
I expanded the zip using StuffIt this time and the standalone version worked.
