### ISSUE TITLE
Does not work with *.AZW on Windows

### ISSUE THREAD

**Issue by Sova373** [apprenticeharper/DeDRM_tools#626]
Here is my log file: 

calibre Журнал ошибок
calibre 3.31  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Kindle and Mobipocket DeDRM (0, 4, 13)
calibre 3.31  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Kindle and Mobipocket DeDRM (0, 4, 13)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 101.6 x 101.6
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
[1.55] main UI initialized...
[1.55] Hiding splash screen
[4.05] splash screen hidden
[4.05] Started up in 4.05 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x9fs_\xdb=V\xf9o\xf6:Ot\xa5\x8e\xafL\x82\xa8N9\x8e\x1b\xcd\x05\xbe\xd3\xe5\xc2\x0eS\xf8e', 'C:\\Users\\fly_s\\Downloads\\B000SEGJ5S_EBOK.azw']
DeDRM v6.6.1: Trying to decrypt B000SEGJ5S_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright В© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 7 ebook: Merriam-Webster's Collegiate Dictionary, 11th Edition
Found 2 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\fly_s\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Kindle and Mobipocket DeDRM v0.4.13: Trying to decrypt B000SEGJ5S_EBOK.azw.
Using Library AlfCrypto Python
Running file type plugin Kindle and Mobipocket DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.k4mobidedrm.__init__", line 116, in run
  File "calibre_plugins.k4mobidedrm.__init__", line 249, in config
  File "site-packages\calibre\customize\zipplugin.py", line 183, in load_module
  File "calibre_plugins.k4mobidedrm.config", line 4, in <module>
ImportError: No module named PyQt4.Qt
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Merriam-Webster's Collegiate Dictionary, 11th Edition to db in: 0.3
Added 1 books in 1.5 seconds

**Comment by edlaika** [comment]
I usually restart my pc and it works after!

**Comment by ElleKayEm** [comment]
Kindle for PC and calibre with DeDRM need to be on the same machine and user.

(you can remove the old "Kindle and Mobipocket DeDRM" plugin)

**Comment by Sova373** [comment]
@ElleKayEm 
I rebooted my pc, deleted book, inserted this one again and tried to convert
Program tells now that book format is *.mobi and converting is failed with error:  

calibre, version 3.31.0 (win32, embedded-python: True)
Ошибка конвертации: Неудача: Конвертировать книгу 1 из 1 (Merriam-Webster's Collegiate Dictionary, 11th Edition)

Конвертировать книгу 1 из 1 (Merriam-Webster's Collegiate Dictionary, 11th Edition)
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Conversion options changed from defaults:
  verbose: 2
  read_metadata_from_opf: u'C:\\Users\\08A4~1\\AppData\\Local\\Temp\\calibre__tdoiq\\zpi9od.opf'
  output_profile: 'generic_eink'
  cover: u'C:\\Users\\08A4~1\\AppData\\Local\\Temp\\calibre__tdoiq\\9k59gr.jpeg'
Resolved conversion options
calibre version: 3.31.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\08A4~1\\AppData\\Local\\Temp\\calibre__tdoiq\\9k59gr.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'force_max_line_length': False,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'inline_toc': False,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x039FDD10>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_color': False,
 'keep_image_references': False,
 'keep_ligatures': False,
 'keep_links': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_line_length': 0,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'newline': u'system',
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x039FDF10>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\08A4~1\\AppData\\Local\\Temp\\calibre__tdoiq\\zpi9od.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'transform_css_rules': '[]',
 'txt_output_encoding': u'utf-8',
 'txt_output_formatting': u'plain',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\08A4~1\AppData\Local\Temp\calibre__tdoiq\dh28mg.mobi
Extracting text...
Adding anchors...
Extracting images...
Cleaning up HTML...
Parsing HTML...
Converting style information to CSS...
Creating OPF...
Parsing all content...
Parsing styles.css ...
Parsing index.html ...
Failed to parse content in index.html
Traceback (most recent call last):
  File "site-packages\calibre\ebooks\oeb\reader.py", line 176, in _manifest_prune_invalid
  File "site-packages\calibre\ebooks\oeb\base.py", line 1034, in fget
  File "site-packages\calibre\ebooks\oeb\base.py", line 952, in _parse_xhtml
  File "site-packages\calibre\ebooks\oeb\parse_utils.py", line 211, in parse_html
  File "site-packages\calibre\ebooks\conversion\preprocess.py", line 593, in __call__
MemoryError

Referenced file u'index.html' not in manifest
Parsing index.html ...
Failed to read from manifest entry with id: added, ignoring
Traceback (most recent call last):
  File "site-packages\calibre\ebooks\oeb\reader.py", line 199, in _manifest_add_missing
  File "site-packages\calibre\ebooks\oeb\base.py", line 1034, in fget
  File "site-packages\calibre\ebooks\oeb\base.py", line 952, in _parse_xhtml
  File "site-packages\calibre\ebooks\oeb\parse_utils.py", line 211, in parse_html
  File "site-packages\calibre\ebooks\conversion\preprocess.py", line 593, in __call__
MemoryError

Spine item 'id1' not found
Python function terminated unexpectedly
  Spine is empty (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1117, in run
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1311, in create_oebbook
  File "site-packages\calibre\ebooks\oeb\reader.py", line 72, in __call__
  File "site-packages\calibre\ebooks\oeb\reader.py", line 704, in _all_from_opf
  File "site-packages\calibre\ebooks\oeb\reader.py", line 349, in _spine_from_opf
calibre.ebooks.oeb.base.OEBError: Spine is empty

**Comment by j-howell** [comment]
“Memory error” can occur when trying to convert a very large book using the 32 bit version of calibre. Try the 64 bit version if your system will support it.

**Comment by ElleKayEm** [comment]
If it's showing .mobi format, then DRM is removed.

**Comment by Sova373** [comment]
@j-howell @ElleKayEm 
ty
i reinstalled 64 bit version and it work fine.
