### ISSUE TITLE
Kobo epubs detected as "unencrypted", but pages are individually encrypted

### ISSUE THREAD

**Issue by rendaw** [apprenticeharper/DeDRM_tools#627]
Or at least, that's what's going on as far as I can tell.  I can open them with 7zip and `standard.opf` looks normal, but the file contents of everything in `item/xhtml` and `item/image` is gibberish (file names are fine).

So I bought a bunch of books (comics) on Kobo, all at once, and downloaded them together.  According to the Kobo website, they're all EPUB 3 with Adobe DRM.  Using the Obok plugin it shows the 2nd and 3rd book in one series as not encrypted, the rest of the books (10+) I bought were marked as encrypted as usual and decrypt as normal.  The first book in the series was published Sept 2017, the 2nd and 3rd in 2018.

I tried redownloading the affected books, same thing.  The Kobo desktop app will open them fine, of course.  I ran Calibre with debug mode and the logs just said "Successfully decrypted" when imported via the obok plugin (I assume it writes that for everything imported).

**Comment by rendaw** [comment]
I tried the Adobe DE version too, but no luck (error about DRM when trying to read the book after adding).

**Comment by ElleKayEm** [comment]
What are you using to view the "unencrypted" Kobo desktop epubs?  Can you unzip them and look at the page images?  Or are they still gibberish?

Post a log from adding one of the ADE versions.

**Comment by rendaw** [comment]
I used Calibre (shows random text like `#3)%%%%"` rather than an image), Windows Image viewer (says something like "file size too large or file corrupt"), and one other program which said the magic string at the beginning of the file was different for each file (and none matched the expected jpeg header).

I'll get debug logs in a minute.

**Comment by rendaw** [comment]
Well, I'm not sure what happened.  Since my post earlier the only thing I've done is suspend the computer, but now ADE actually decripts, and the Kobo volume is also properly marked as encrypted (and decrypts).

If the epub was corrupt, how did I manage to extract the gibberish files in the first place?  Is there some strange interaction between ADE and the Kobo desktop app?

Anyway, apologies for the noise!  Closing this now since it resolved itself.

**Comment by ElleKayEm** [comment]
As far as I know, nothing between ADE and Kobo Desktop.  Maybe there was some issue between Obok and calibre.  Sometimes just restarting calibre can help.  I always restart calibre after installing or updating a plugin.

Glad both kepubs and ADE epubs decryption is working for you now.  One of the reasons I like Kobo -- two methods for freeing my books!
