### ISSUE TITLE
How to "Download & transfer via USB" on Amazon?

### ISSUE THREAD

**Issue by CootCraig** [apprenticeharper/DeDRM_tools#636]
I've just started reading ebooks and have purchased a number of kindle
books from Amazon.  I would like to "Download & transfer via USB" from my
Amazon account and then load into Calibre with the DeDRM tools installed.
I am logged into Amazon using Firefox on a Linux workstation.

When I select a purchased book I get a popup windows that shows:
..................
Download & transfer via USB

Select a device from the dropdown

Craig’s Fire TV
Craig’s Android Device
Craig’s Kindle Cloud Reader
Craig’s Kindle for PC

You have selected content that is not compatible with any of your registered devices. Please remove incompatible content from selection for eligible devices to appear.
..................

The devices are correct.  I would like to read the purchased books on
my Android tablet.

What is going on? How can I do this?
The Kindle for PC is version 1.17.0, but I prefer to work on my Linux system.

**Comment by j-howell** [comment]
"Download and Transfer" is only available to owners of e-ink Kindle devices and Fire tablets (and DeDRM only works in the first case).

You will need to download books using the Kindle for PC software.

**Comment by CootCraig** [comment]
Thanks for explanation. I'm frustrated and disappointed with the road blocks for getting my DRM books into Calibre and my readers of choice; but that is the whole point of DeDRM/Calibre. I plan to soldier on. I will do the downloads in "Kindle for PC", copy onto my Linux workstation, import into Calibre and see what happens.
