### ISSUE TITLE
Mac OS app and plug-in does not dedrm kindle book

### ISSUE THREAD

**Issue by barturas** [apprenticeharper/DeDRM_tools#637]
I tried stand-alone app and plugin. I entered s/n of my kindle and tried to dedrm either .kfx (file from paperwhite) or .azw (file from Kindle macos app). no luck

log:
_There is 1 ebook to be decrypted.
Processing file: Stalking the Wild Pendulum_ On the Mechanics of Consciousness.azw
There was an error with 1 ebook:
Macintosh HD:Users:arturas:Desktop:Stalking the Wild Pendulum_ On the Mechanics of Consciousness.azw is neither a Kindle not a Mobipocket file._

**Comment by barturas** [comment]
calibre recognizes two files (kfx and azw) as kfx-zip

**Comment by barturas** [comment]
successful dedrm. I uninstalled all related plugins and reinstalled them again. restarted calible and started in debug mode. This time I followed this instruction https://www.mobileread.com/forums/showthread.php?t=291290
on how to import book.

calibre added book in kfx file and not in kfx-zip (which indicates that import wasn't successful)
then I just tried to convert to mobi and it worked.

Thank you for tools!

**Comment by ElleKayEm** [comment]
> calibre added book in kfx file and not in kfx-zip (which indicates that import wasn't successful)

Actually that indicates that DRM _was_ successfully removed on import.

**Comment by barturas** [comment]
yes, that this time calibre added in kfx file, not in kfx-zip.

The problem was that I located file then copied it to desktop and only then was importing it to calibre.
but in order to successfully import kfx you need to import it from original folder where kindle mac app stores the book
