### ISSUE TITLE
Adobe PDF DRM Failed With Latest Plugin & Calibre!

### ISSUE THREAD

**Issue by syedbilal07** [apprenticeharper/DeDRM_tools#64]
Hi To All GitHub Members & Developers!
Since Past Few Days, I Am Trying To Strip DRM Of Some Of My PDF Books (ADEPT PDF). I Have Used Many Softwares Including All DRM Remover, AzwSoft EPUB DRM Removal, ePUB EPUB DRM Removal, ePUBEE ePUB DRM Removal, EPUBOR Ultimate Pack, EPubsoft Adobe PDF ePub DRM Removal, PDF ePUB DRM Remover. These Softwares Give Me The Error "The Information You Input Is Incorrect" OR "Failed To Remove DRM" Although I Have Read The In Adobe Digital Edition (4.5) Before Removing DRM. I Also Used Python Scripts After Authorizing Adobe Digital Edition With My Account. I Have Generated Keyfile From "adobekey.py" & Also With "ineptkey.py", But When I Tried To Decrypt Book With "ineptpdf.py" , It Says "Error In Book Session Key".
Now As Far As Calibre Is Concerned, I Have Installed The "DeDRM (6.3.6) " Plugin, Loaded My Encrypted PDF Book . But When I Opened It With Calibre, It Says "The Book Is DRM Protected". I Also Tried To Convert My Book With Calibre But It Failed.
Below Are The Pictures Of Calibre & Other Softwares Which I Tried For Better Understanding. I Am Also Uploading A LogCat Which Calibre Produced After It Failed To "Convert" My PDF Book.
Please Help Me As I Am Trying To Decrypt My Legal Books Since 3 Days But Failed To Do So :(

1. (Adobe Digital Edition - Main Window)
http://postimg.org/image/73mbwim7t/
2. (Adobe Digital Edition Authorization Window)
http://postimg.org/image/fhoyp31ph/
3. (Calibre Plugins Window)
http://postimg.org/image/okz5zapxj/
4. (I Have Added "default_key" For ADE In DeDRM Plugin)
http://postimg.org/image/wsmeilzjr/
5. (Calibre Main Window - Book Loaded)
http://postimg.org/image/mv4hn4d8j/
6. (Adobe Acrobat Error After I Loaded Book With Calibre)
http://postimg.org/image/ibidb3pbb/
7. (Calibre Conversion Error)
http://tinypic.com/view.php?pic=24zvs4o&s=9
8. (EPUBOR Ultimate Error)
http://tinypic.com/view.php?pic=qyd4hw&s=9
9. (EPUBSOFT Adobe PDF Error)
http://tinypic.com/view.php?pic=bbk7r&s=9
10 . (AzwSoft EPUB DRM Remover Error)
http://tinypic.com/view.php?pic=2rxxtme&s=9
11. (ePUB DRM Remover Error)
http://tinypic.com/view.php?pic=2e67ngo&s=9
12. (Calibre Failed To Convert Log File)
http://textuploader.com/5z47p

**Comment by ElleKayEm** [comment]
Post an import log.

**Comment by syedbilal07** [comment]
How to capture import log ? Can you guide me!

**Comment by ElleKayEm** [comment]
In calibre, under the Preferences menu, select "Reopen in debug mode."  Import the book.  Then when you close calibre, the log will open.

**Comment by syedbilal07** [comment]
The Import Debug Log For You 

calibre Debug log
calibre 2.49 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && Obok DeDRM
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 7.90 seconds with 0 books
DeDRM v6.3.6: Trying to decrypt eProject Guide - HTML5.pdf
DeDRM v6.3.6: eProject Guide - HTML5.pdf is a PDF ebook
DeDRM v6.3.6: Trying Encryption key default_key
Error serializing pdf eProject Guide - HTML5.pdf. Probably wrong key.
DeDRM v6.3.6: Failed to decrypt with key default_key after 0.6 seconds
DeDRM v6.3.6: Looking for new default Adobe Digital Editions Keys after 0.6 seconds
Found 1 keys
DeDRM v6.3.6: Ultimately failed to decrypt after 0.6 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 152, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 604, in run
  File "calibre_plugins.dedrm.__init__", line 479, in PDFDecrypt
DeDRMError: DeDRM v6.3.6: Ultimately failed to decrypt after 0.6 seconds.
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 357, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 326, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 101, in get_metadata
ValueError: Could not read info dict from PDF
Added eProject Guide to db in: 1.7
Added 1 books in 4.1 seconds

**Comment by ElleKayEm** [comment]
Can you view the book in Adobe Digital Editions 2.0.1?  If not, then you might have a book with the new  Adobe DRM which these tools can't decrypt.

**Comment by syedbilal07** [comment]
I have downloaded ADE 2.0.1 after you said, authorized my Account and tried to download the same book from it but here are the images... 
1. http://postimg.org/image/jc2153ndx/ (Version Information)
2. http://postimg.org/image/e5249fmsr/ (Authorization Information)
3. http://postimg.org/image/yqajz1znn/ (Error Information)

**Comment by syedbilal07** [comment]
So, How To Decrypt Books Of ADE 4.5. Maybe They Have Changed The ADEPT RSA Hashes. Is There Any Way To Break The DRM Because I Have Tried All The Tools Which I Mentioned Above. I Really Need To Break The DRM. Help Required & Thanks @ElleKayEm For Helping Me Out! :+1:

**Comment by ElleKayEm** [comment]
Yes, it looks like you have a book with the new Adobe DRM.  I'm not aware of any way to remove it.  The only thing I can suggest is to stick with ADE 2.0.1 for downloading any future purchases.

**Comment by syedbilal07** [comment]
@ElleKayEm , i am not in a situation to purchase them with ADE 2.0.1, i got these books from my I.T institute so i cannot do anything about it. But, if anyone knows a method to break it. Please post it!

**Comment by apprenticeharper** [comment]
We can only hope that someone with the ability and time will undertake the task.

**Comment by apprenticeharper** [comment]
Known problem that the tools don't handle the new Adobe encryption. Closed.
