### ISSUE TITLE
DeDRM not working

### ISSUE THREAD

**Issue by fatsuki** [apprenticeharper/DeDRM_tools#642]
I updated Calibre today (v. 3.31), installed the newest version of DeDRM (v. 6.6.1), configured my Paperwhite serial number and the DeDRM still doesn't work.  Ran in debug mode; here's the log.  What am I doing wrong?

calibre Debug log
calibre 3.31  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0) && ADLIBRIS_NO (0, 0, 9)
calibre 3.31  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0) && ADLIBRIS_NO (0, 0, 9)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
[1.36] main UI initialized...
[1.36] Hiding splash screen
[1.41] splash screen hidden
[1.41] Started up in 1.41 seconds with 2956 books
objc[1134]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8bbeac90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x130ff7cd8). One of the two will be used. Which one is undefined.
DeDRM v6.6.1: Trying to decrypt Murder at Merisham Lodge_ Miss Hart and Miss Hunter Investigate_ Book 1.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Murder at Merisham Lodge: Miss Hart and Miss Hunter Investigate: Book 1
Found 4 keys to try after 0.0 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.0 seconds
DeDRM v6.6.1: Finished after 0.0 seconds
2018-09-26 12:46:23.531 Calibre[1159:38561] deliverNotificationWithTitle()
* Notification delivered.
DeDRM v6.6.1: Trying to decrypt Locked Rooms_ A novel of suspense featuring Mary Russell and Sherlock Holmes (A Mary Russell & Sherlock Holmes Mystery Book 8).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Locked Rooms: A novel of suspense featuring Mary Russell and Sherlock Holmes (A Mary Russell & Sherlock Holmes Mystery Book 8)
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/fatsuki/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '2d4c5b8922a1' and UserName 'fatsuki'
DeDRM v6.6.1: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Locked Rooms: A novel of suspense featuring Mary Russell and Sherlock Holmes (A Mary Russell & Sherlock Holmes Mystery Book 8)
Got DSN key from database default_key_1
Found 3 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Murder at Merisham Lodge: Miss Hart and Miss Hunter Investigate: Book 1 to db in: 0.0
Added 1 books in 3.9 seconds
Worker Launch took: 0.0708432197571
Job: 1 Convert book 1 of 1 (Murder at Merisham Lodge: Miss Hart and Miss Hunter Investigate: Book 1) finished
Convert book 1 of 1 (Murder at Merisham Lodge: Miss Hart and Miss Hunter Investigate: Book 1)
	Conversion options changed from defaults:
	  cover: u'/var/folders/9b/jnymyq191mb8x89t839_5gg40000gp/C/calibre_3.31.0_tmp_jVNBnK/01Saih.jpeg'
	  verbose: 2
	  output_profile: 'nook'
	  read_metadata_from_opf: u'/var/folders/9b/jnymyq191mb8x89t839_5gg40000gp/C/calibre_3.31.0_tmp_jVNBnK/zoJ7cO.opf'
	Resolved conversion options
	calibre version: 3.31.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/9b/jnymyq191mb8x89t839_5gg40000gp/C/calibre_3.31.0_tmp_jVNBnK/01Saih.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10ccd3f90>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.NookOutput object at 0x10ccda910>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/9b/jnymyq191mb8x89t839_5gg40000gp/C/calibre_3.31.0_tmp_jVNBnK/zoJ7cO.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/9b/jnymyq191mb8x89t839_5gg40000gp/C/calibre_3.31.0_tmp_jVNBnK/3Je3Po.azw3
	Found KF8 MOBI of type 'standalone'
	Extracting text...
	Parsing all content...
	Parsing text/part0001.html ...
	Initial parse failed, using more forgiving parsers
	Parsing text/part0001.html as HTML
	Parsing text/part0000.html ...
	Parsing styles/0001.css ...
	PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): ('CHAR', u'[', 253, 16)
	No content to parse.
	PropertyValue: Unknown syntax or no value:  [Default]
	CSSStyleDeclaration: Syntax Error in Property: font-binding: [Default]
	Reading TOC from NCX...
	Merging user specified metadata...
	Detecting structure...
	Flattening CSS and remapping font sizes...
	Source base font size is 11.00000pt
	Removing fake margins...
	Found 3 items of level: div_1
	Found 269 items of level: div_2
	Found 53 items of level: div_3
	Found 1708 items of level: p_3
	Found 39 items of level: p_2
	Found 1 items of level: p_1
	Ignoring level p_1
	div_1  left margin stats: Counter({u'': 2})
	div_1  right margin stats: Counter({u'': 2})
	div_2  left margin stats: Counter({u'': 196})
	div_2  right margin stats: Counter({u'': 196})
	div_3  left margin stats: Counter({u'': 53})
	div_3  right margin stats: Counter({u'': 53})
	p_3  left margin stats: Counter({u'0': 1708})
	p_3  right margin stats: Counter({u'0': 1708})
	p_2  left margin stats: Counter({u'0': 39})
	p_2  right margin stats: Counter({u'0': 39})
	Cleaning up manifest...
	Trimming unused files from manifest...
	Trimming u'images/00004.jpeg' from manifest
	Trimming u'images/00001.jpeg' from manifest
	Creating EPUB Output...
	Rescaling image from 759x1215 to 441x706 cover.jpeg
	Splitting markup on page breaks and flow limits, if any...
			Splitting on page-break at id=calibre_pb_0
			Splitting on page-break at id=calibre_pb_1
			Splitting on page-break at id=calibre_pb_2
			Splitting on page-break at id=calibre_pb_3
			Splitting on page-break at id=calibre_pb_4
			Splitting on page-break at id=toc-anchor
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_6
			Splitting on page-break at id=toc-anchor-1
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_8
			Splitting on page-break at id=toc-anchor-2
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_10
			Splitting on page-break at id=toc-anchor-3
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_12
			Splitting on page-break at id=toc-anchor-4
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_14
			Splitting on page-break at id=toc-anchor-5
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_16
			Splitting on page-break at id=toc-anchor-6
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_18
			Splitting on page-break at id=toc-anchor-7
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_20
			Splitting on page-break at id=toc-anchor-8
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_22
			Splitting on page-break at id=toc-anchor-9
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_24
			Splitting on page-break at id=toc-anchor-10
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_26
			Splitting on page-break at id=toc-anchor-11
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_28
			Splitting on page-break at id=toc-anchor-12
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_30
			Splitting on page-break at id=toc-anchor-13
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_32
			Splitting on page-break at id=toc-anchor-14
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_34
			Splitting on page-break at id=toc-anchor-15
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_36
			Splitting on page-break at id=toc-anchor-16
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_38
			Splitting on page-break at id=toc-anchor-17
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_40
			Splitting on page-break at id=toc-anchor-18
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_42
			Splitting on page-break at id=toc-anchor-19
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_44
			Splitting on page-break at id=toc-anchor-20
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_46
			Splitting on page-break at id=toc-anchor-21
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_48
			Splitting on page-break at id=toc-anchor-22
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_50
			Splitting on page-break at id=calibre_pb_51
			Splitting on page-break at id=calibre_pb_52
			Splitting on page-break at id=calibre_pb_53
			Splitting on page-break at id=calibre_pb_54
			Splitting on page-break at id=toc-anchor-23
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_56
			Splitting on page-break at id=calibre_pb_57
			Splitting on page-break at id=calibre_pb_58
			Splitting on page-break at id=toc-anchor-24
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_60
			Splitting on page-break at id=calibre_pb_61
			Splitting on page-break at id=calibre_pb_62
			Splitting on page-break at id=toc-anchor-25
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_64
			Splitting on page-break at id=calibre_pb_65
			Splitting on page-break at id=calibre_pb_66
			Splitting on page-break at id=calibre_pb_67
			Splitting on page-break at id=calibre_pb_68
			Splitting on page-break at id=toc-anchor-26
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_70
			Splitting on page-break at id=toc-anchor-27
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_72
			Splitting on page-break at id=calibre_pb_73
			Splitting on page-break at id=calibre_pb_74
			Splitting on page-break at id=toc-anchor-28
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_76
			Splitting on page-break at id=toc-anchor-29
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_78
			Splitting on page-break at id=toc-anchor-30
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_80
			Splitting on page-break at id=toc-anchor-31
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_82
			Splitting on page-break at id=calibre_pb_83
			Splitting on page-break at id=calibre_pb_84
			Splitting on page-break at id=toc-anchor-32
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_86
			Splitting on page-break at id=toc-anchor-33
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_88
			Splitting on page-break at id=calibre_pb_89
			Splitting on page-break at id=calibre_pb_90
			Splitting on page-break at id=toc-anchor-34
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_92
			Splitting on page-break at id=calibre_pb_93
			Splitting on page-break at id=calibre_pb_94
			Splitting on page-break at id=toc-anchor-35
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_96
			Splitting on page-break at id=calibre_pb_97
			Splitting on page-break at id=calibre_pb_98
			Splitting on page-break at id=calibre_pb_99
			Splitting on page-break at id=calibre_pb_100
			Splitting on page-break at id=toc-anchor-36
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_102
			Splitting on page-break at id=toc-anchor-37
	Adjusted split point to ancestor
			Splitting on page-break at id=calibre_pb_104
			Splitting on page-break at id=toc-anchor-38
	Adjusted split point to ancestor
		Looking for large trees in text/part0001.html...
		No large trees found
		Split into 47 parts
			Splitting on page-break at id=calibre_pb_0
			Splitting on page-break at id=calibre_pb_1
		Looking for large trees in text/part0000.html...
		No large trees found
	Removing anchor from TOC href: text/part0001_split_003.html#toc-anchor
	Removing anchor from TOC href: text/part0001_split_004.html#toc-anchor-1
	Removing anchor from TOC href: text/part0001_split_005.html#toc-anchor-2
	Removing anchor from TOC href: text/part0001_split_006.html#toc-anchor-3
	Removing anchor from TOC href: text/part0001_split_007.html#toc-anchor-4
	Removing anchor from TOC href: text/part0001_split_008.html#toc-anchor-5
	Removing anchor from TOC href: text/part0001_split_009.html#toc-anchor-6
	Removing anchor from TOC href: text/part0001_split_010.html#toc-anchor-7
	Removing anchor from TOC href: text/part0001_split_011.html#toc-anchor-8
	Removing anchor from TOC href: text/part0001_split_012.html#toc-anchor-9
	Removing anchor from TOC href: text/part0001_split_013.html#toc-anchor-10
	Removing anchor from TOC href: text/part0001_split_014.html#toc-anchor-11
	Removing anchor from TOC href: text/part0001_split_015.html#toc-anchor-12
	Removing anchor from TOC href: text/part0001_split_016.html#toc-anchor-13
	Removing anchor from TOC href: text/part0001_split_017.html#toc-anchor-14
	Removing anchor from TOC href: text/part0001_split_018.html#toc-anchor-15
	Removing anchor from TOC href: text/part0001_split_019.html#toc-anchor-16
	Removing anchor from TOC href: text/part0001_split_020.html#toc-anchor-17
	Removing anchor from TOC href: text/part0001_split_021.html#toc-anchor-18
	Removing anchor from TOC href: text/part0001_split_022.html#toc-anchor-19
	Removing anchor from TOC href: text/part0001_split_023.html#toc-anchor-20
	Removing anchor from TOC href: text/part0001_split_024.html#toc-anchor-21
	Removing anchor from TOC href: text/part0001_split_025.html#toc-anchor-22
	Removing anchor from TOC href: text/part0001_split_027.html#toc-anchor-23
	Removing anchor from TOC href: text/part0001_split_028.html#toc-anchor-24
	Removing anchor from TOC href: text/part0001_split_029.html#toc-anchor-25
	Removing anchor from TOC href: text/part0001_split_031.html#toc-anchor-26
	Removing anchor from TOC href: text/part0001_split_032.html#toc-anchor-27
	Removing anchor from TOC href: text/part0001_split_034.html#toc-anchor-28
	Removing anchor from TOC href: text/part0001_split_035.html#toc-anchor-29
	Removing anchor from TOC href: text/part0001_split_036.html#toc-anchor-30
	Removing anchor from TOC href: text/part0001_split_037.html#toc-anchor-31
	Removing anchor from TOC href: text/part0001_split_038.html#toc-anchor-32
	Removing anchor from TOC href: text/part0001_split_039.html#toc-anchor-33
	Removing anchor from TOC href: text/part0001_split_040.html#toc-anchor-34
	Removing anchor from TOC href: text/part0001_split_041.html#toc-anchor-35
	Removing anchor from TOC href: text/part0001_split_044.html#toc-anchor-36
	Removing anchor from TOC href: text/part0001_split_045.html#toc-anchor-37
	Removing anchor from TOC href: text/part0001_split_046.html#toc-anchor-38
	EPUB output written to /var/folders/9b/jnymyq191mb8x89t839_5gg40000gp/C/calibre_3.31.0_tmp_jVNBnK/ol14r6.epub

Added Locked Rooms: A novel of suspense featuring Mary Russell and Sherlock Holmes (A Mary Russell & Sherlock Holmes Mystery Book 8) to db in: 0.0
Added 1 books in 0.7 seconds
Worker Launch took: 0.0865950584412
Job: 2 Convert book 1 of 1 (Locked Rooms: A novel of suspense featuring Mary Russell and Sherlock Holmes (A Mary Russell & Sherlock Holmes Mystery Book 8)) finished
Convert book 1 of 1 (Locked Rooms: A novel of suspense featuring Mary Russell and Sherlock Holmes (A Mary Russell & Sherlock Holmes Mystery Book 8))
	Conversion options changed from defaults:
	  cover: u'/var/folders/9b/jnymyq191mb8x89t839_5gg40000gp/C/calibre_3.31.0_tmp_jVNBnK/FwwzqR.jpeg'
	  verbose: 2
	  output_profile: 'nook'
	  read_metadata_from_opf: u'/var/folders/9b/jnymyq191mb8x89t839_5gg40000gp/C/calibre_3.31.0_tmp_jVNBnK/Z5DkSb.opf'
	Resolved conversion options
	calibre version: 3.31.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/9b/jnymyq191mb8x89t839_5gg40000gp/C/calibre_3.31.0_tmp_jVNBnK/FwwzqR.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x112810f90>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.NookOutput object at 0x112817910>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/9b/jnymyq191mb8x89t839_5gg40000gp/C/calibre_3.31.0_tmp_jVNBnK/Z5DkSb.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: Locked Rooms: A novel of suspense featuring Mary Russell and Sherlock Holmes (A Mary Russell & Sherlock Holmes Mystery Book 8)
	InputFormatPlugin: MOBI Input running
	on /var/folders/9b/jnymyq191mb8x89t839_5gg40000gp/C/calibre_3.31.0_tmp_jVNBnK/wyr1Gh.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
	  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 45, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Locked Rooms: A novel of suspense featuring Mary Russell and Sherlock Holmes (A Mary Russell & Sherlock Holmes Mystery Book 8)

**Comment by ElleKayEm** [comment]
If it was downloaded from the website, make sure it was your Paperwhite (or another E-ink Kindle) you chose for the device.  Double-check you have the serial number correct -- copy and paste from the website (deleting any spaces).  Restart calibre after adding your serial number and before adding your book.

**Comment by fatsuki** [comment]
Thanks for the help.  It totally worked!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
