### ISSUE TITLE
DeDRM not decrypting

### ISSUE THREAD

**Issue by obguy** [apprenticeharper/DeDRM_tools#645]
I'm trying to find out why DeDRM fails to decrypt. The plugins, DeDRM and KFX, are installed in Calibre and the Kindle Paperwhite serial number was added to the e-ink section of the plugin. Do I need python and the python scripts installed in wine to use the DeDRM plugin? The book file was downloaded directly from the "manage my devices" page at Amazon with an .azw3 extension.

calibre Debug log
calibre 3.31  embedded-python: False is64bit: True
Linux-4.18.9-arch1-1-ARCH-x86_64-with-glibc2.2.5 Linux ('64bit', '')
('Linux', '4.18.9-arch1-1-ARCH', '#1 SMP PREEMPT Wed Sep 19 21:19:17 UTC 2018')
Python 2.7.15
Linux: ('', '', '')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0)
calibre 3.31  embedded-python: False is64bit: True
Linux-4.18.9-arch1-1-ARCH-x86_64-with-glibc2.2.5 Linux ('64bit', '')
('Linux', '4.18.9-arch1-1-ARCH', '#1 SMP PREEMPT Wed Sep 19 21:19:17 UTC 2018')
Python 2.7.15
Linux: ('', '', '')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259 x 93.6245733788
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.73] db initialized
[0.73] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[1.33] main UI initialized...
[1.33] Hiding splash screen
DeDRM v6.6.1: Trying to decrypt The Foods of the Greek Islands_ Cooking and Culture at the Crossroads of the Mediterranean.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Foods of the Greek Islands: Cooking and Culture at the Crossroads of the Mediterranean
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.6.1: Running kindlekey.py under Wine
DeDRM v6.6.1: Command line: 'WINEPREFIX="/home/clayton" wine python.exe "/home/clayton/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/clayton/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
[6.47] splash screen hidden
[6.47] Started up in 6.47 seconds with 27 books
wine: cannot find L"C:\\windows\\system32\\python.exe"
DeDRM v6.6.1: Found and decrypted 0 key files
DeDRM v6.6.1: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 171, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Foods of the Greek Islands: Cooking and Culture at the Crossroads of the Mediterranean to db in: 2.1
Added 1 books in 4.1 seconds

**Comment by ElleKayEm** [comment]
Yes, you need Python and PyCrypto.  See the readme in the DeDRM calibre plugin folder.  And you may still run into issues.  It seems to be really tricky to get things set up in Linux.  You might find answers in some of the other issues here.

**Comment by obguy** [comment]
I looked into some other posts and see what you mean about the Linux installation issues. Luckily, I'm dual booting and the DeDRM plugin worked perfectly in Windows. Thanks!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
