### ISSUE TITLE
Unable to Remove DRM Suddenly

### ISSUE THREAD

**Issue by Shirezu** [apprenticeharper/DeDRM_tools#648]
Has been working fine for ages. Recent batch are failing. Log below:
calibre Debug log
calibre 3.32  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Obok DeDRM (6, 5, 4)
calibre 3.32  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259 x 93.6245733788
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.16] main UI initialized...
[2.16] Hiding splash screen
[6.98] splash screen hidden
[6.98] Started up in 6.98 seconds with 3081 books
DeDRM v6.6.1: Trying to decrypt Mogworld(1).azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Mogworld
Found 6 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Shirezu\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Shirezu\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1949738866' and UserName '53686972657a75'
DeDRM v6.6.1: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Mogworld
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Mogworld to db in: 1.5
Added 1 books in 2.1 seconds

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) and enter its serial number into the plugin customization.

**Comment by ElleKayEm** [comment]
Have you tried a fresh download of a book?  To make sure it's associated with the correct Kindle.

**Comment by Shirezu** [comment]
Yes. As well as uninstalling and reinstalling the plugin.

**Comment by ElleKayEm** [comment]
When you entered your serial number, did you copy and paste it from the website (removing spaces)?

**Comment by Shirezu** [comment]
...
It had changed download default from 3rd Kindle to 3rd Fire and all I saw was 3rd. Resolving.
