### ISSUE TITLE
DeDRM 6.5.5, Kindle 1.23.1, KFX Input 1.9.0 not working

### ISSUE THREAD

**Issue by xtina** [apprenticeharper/DeDRM_tools#652]
calibre Debug log
calibre 3.32  embedded-python: True is64bit: True
Darwin-18.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.0.0', 'Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && DeDRM (6, 5, 5) && Package KFX (from KFX Input) (1, 9, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0) && Goodreads (1, 1, 16) && Set KFX metadata (from KFX Output) (1, 23, 0) && KFX Output (1, 23, 0)
calibre 3.32  embedded-python: True is64bit: True
Darwin-18.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.0.0', 'Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && DeDRM (6, 5, 5) && Package KFX (from KFX Input) (1, 9, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0) && Goodreads (1, 1, 16) && Set KFX metadata (from KFX Output) (1, 23, 0) && KFX Output (1, 23, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 128.000001922
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.35] db initialized
[0.35] Constructing main UI...
[2.27] main UI initialized...
[2.27] Hiding splash screen
[2.31] splash screen hidden
[2.31] Started up in 2.31 seconds with 386 books
Gather KFX-ZIP (from KFX Input) 1.9.0: Importing /My Kindle Content/B079FFPXFJ_EBOK/B079FFPXFJ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/yg/6y9l90p970nflwqvpc5whcpm0000gn/C/calibre_3.32.0_tmp_esx9O5/d8odbv.kfx-zip
DeDRM v6.5.5: Trying to decrypt d8odbv.kfx-zip
Unknown booktype kfx-zip. Passing back to calibre unchanged
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 76, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
KFXDRMError: Book container B079FFPXFJ_EBOK.azw has DRM and cannot be converted
Package KFX (from KFX Input) 1.9.0: Packaging /var/folders/yg/6y9l90p970nflwqvpc5whcpm0000gn/C/calibre_3.32.0_tmp_esx9O5/d8odbv.kfx-zip
Processing container: B079FFPXFJ_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/yg/6y9l90p970nflwqvpc5whcpm0000gn/C/calibre_3.32.0_tmp_esx9O5/yjaoK9_add_books/0/B079FFPXFJ_EBOK.kfx-zip
Added **** to db in: 0.1
Added 1 books in 1.2 seconds

I am running OSX 10.14 with DeDRM 6.5.5, Kindle 1.23.1, KFX Input 1.9.0, Calibre 3.32.

**Comment by ElleKayEm** [comment]
You using an old version of DeDRM which can't handle KFX format.  Get the latest version here:

https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.6.1

**Comment by xtina** [comment]
🤦‍♀️
