### ISSUE TITLE
DeDRM Not Working - Log

### ISSUE THREAD

**Issue by Andreagiordano69** [apprenticeharper/DeDRM_tools#656]
Hi here is the log of the Calibre debug mode. I was trying to importabook from kindle for pc. Don't kow if I oparate correctly. I tried to import asofromthe kindle device plugged on the laptop with no luck I run win 7 64bit. I have the 1.24 version of Kindle for PC and cannot retrieve the 1.17 from rhe site. Bought the book on Amazon and would like to have them on calibre on my laptopfor a better management (note, copypaste of passages underlined). 
[tmpnftkoo.txt](https://github.com/apprenticeharper/DeDRM_tools/files/2491369/tmpnftkoo.txt)

**Comment by j-howell** [comment]
The [KFX Input plugin](https://www.mobileread.com/forums/showthread.php?t=291290) for calibre is required to import and convert books in KFX format.

**Comment by Andreagiordano69** [comment]
> 
> 
> The [KFX Input plugin](https://www.mobileread.com/forums/showthread.php?t=291290) for calibre is required to import and convert books in KFX format.

I thought I was using the deDRM that convert from awz and thought theplugin wouldwork automaticaly.
Anyway I managed to dowgrade at Kindel 1.17 and it worked perfectly! Thanks!

**Comment by ElleKayEm** [comment]
AZW is the extension used by Kindle for PC for all books.  The copy downloaded with 1.24 was in KFX format.  If you're all set, you can close the issue.
