### ISSUE TITLE
DRM MAC APP tools not working

### ISSUE THREAD

**Issue by alonewoo** [apprenticeharper/DeDRM_tools#657]
I used MAC app to decrypted the doc directly. but it seems not working.
MAC: MAC OS 10.14
DeDRM app:  6.6.1
I have set up the serial number in DeDRM app. but when I open the ebook file, I got this log.
This ebook is download from amazon Australia kindle market and download way is PC sent to kindle. 

There is 1 ebook to be decrypted.
Processing file: Past the Shallows.azw3
shellcommand: /usr/bin/python '/Users/alonewoo/Desktop/DeDRM.app/Contents/Resources/k4mobidedrm.py' -s 'G090G105533208M2' '/Users/alonewoo/Desktop/Past the Shallows.azw3' '/Users/alonewoo/Desktop/' > '/Users/alonewoo/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/Users/alonewoo/Desktop/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 93, in <module>
    import kfxdedrm
  File "/Users/alonewoo/Desktop/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/Users/alonewoo/Desktop/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
shellcommand: /usr/bin/python '/Users/alonewoo/Desktop/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/alonewoo/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/alonewoo/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.5
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
No k4Mac kindle-info/rainier/kinf2011 files have been found.
Could not retrieve Kindle for Mac/PC key.
 
There was an error with 1 ebook:
Past the Shallows.azw3 couldn't be decrypted.

**Comment by ElleKayEm** [comment]
See this from the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#the-application-opens-but-always-gives-an-error-in-the-log-importerror-no-module-named-cryptocipher

**Comment by alonewoo** [comment]
Got it.  I type the command in CLI, but it come back "no PIP". I installed PIP, then it can't install Crypto also. It seems my MAC sython environment is bad. I will see it continually and Pls close this issue at first. thanks.

**Comment by ElleKayEm** [comment]
You could go back to DeDRM 6.5.5 or use the calibre plugin.
