### ISSUE TITLE
k4mobidedrm.py fires "UnicodeEncodeError" at String.format with certain "clean_title" name

### ISSUE THREAD

**Issue by fireattack** [apprenticeharper/DeDRM_tools#658]
I have a kindle file that can't be deDRMed due to some weird UnicodeEncodeError:

```
C:\Users\Administrator\Desktop\DeDRM_tools_6.6.1\DeDRM_Windows_Application\DeDRM_App\DeDRM_lib\lib>py -2 k4mobidedrm.py -k "C:\Users\Administrator\AppData\Local\DeDRMPrefs\kindlekey.k4i" B07HXZBMCQ_EBOK.azw .
Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.5.
Copyright ? 2008-2017 Apprentice Harper et al.
MobiDeDrm v0.42.
Copyright ? 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 君のいる町　妄想２００話　ＳＰＥＣＩＡＬ　ＥＤＩＴＩＯＮ（１） (週刊少年マガジンコミックス)
Got DSN key from database C:\Users\Administrator\AppData\Local\DeDRMPrefs\kindlekey.k4i
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID HZUuoWXrFS.
Decrypting. Please wait . . . done
Decryption succeeded after 0.4 seconds
Traceback (most recent call last):
  File "k4mobidedrm.py", line 353, in <module>
    sys.exit(cli_main())
  File "k4mobidedrm.py", line 347, in cli_main
    return decryptBook(infile, outdir, kDatabaseFiles, androidFiles, serials, pids)
  File "k4mobidedrm.py", line 272, in decryptBook
    outfilename = '{}_{}'.format(orig_fn_root, clean_title)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-30: ordinal not in range(128)
```

The clean title in case is `u'\u541b\u306e\u3044\u308b\u753a\u3000\u5984\u60f3\uff12\uff10\uff10\u8a71\u3000\uff33\uff30\uff25\uff23\uff29\uff21\uff2c\u3000\uff25\uff24\uff29\uff34\uff29\uff2f\uff2e\uff08\uff11\uff09 (\u9031\u520a\u5c11\u5e74\u30de\u30ac\u30b8\u30f3\u30b3\u30df\u30c3\u30af\u30b9)'`

**Comment by fireattack** [comment]
See: https://bugs.python.org/issue7300

A potential solution (from there) is 

>Oh by the way, it's trivial to workaround this issue in Python 2: just use a Unicode format string. For example, replace '{0}'.format(u'\u3042') with u'{0}'.format(u'\u3042').

so, changed it to    `outfilename = u'{}_{}'.format(orig_fn_root, clean_title)`.

**Comment by mvastola** [comment]
I just experienced and fixed this issue separately (the same way you did, @fireattack). Submitting a PR now.

**Comment by fireattack** [comment]
Great, thanks for the PR!
