### ISSUE TITLE
Cannot add Kindle KFX book to library

### ISSUE THREAD

**Issue by jonathanclark** [apprenticeharper/DeDRM_tools#669]
Hi,

I have a brand new install of Calibre 3.33.1 with DeDRM_tools 6.6.1. I have entered my Kindle serial number. When I click on the Kindle icon I get a list of books, when I right mouse click the KFX book and select 'Add to library' I get the pop-up telling me that KFX books can't be handled. I added KFX Input plugin as well - no difference. All I want to do is convert the KFX book to EPUB so I can read it on my Kobo. What am I doing wrong?

Thanks.

Debug log attached.

calibre-debug -g
calibre 3.33.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 9, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[2.23] main UI initialized...
[2.23] Hiding splash screen
[2.84] splash screen hidden
[2.86] Started up in 2.86 seconds with 1 books
Storage number map:
{(7L, 0L): [(4L, 'C'), (6L, 'D')], (7L, 1L): [(1L, 'F')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0310\7&5638464&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x310 devid=usb\vid_1949&pid_0004&rev_0310 devinst=6)
{u'drive_letters': ['F'],
 u'pnp_id_map': {'F': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0310#7&5638464&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'F': (1L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: F:\ documents
DEBUG:    0.0 USBMS: scan from root False F:\documents
DEBUG:    0.1 USBMS: count found in cache: 41, count of files in metadata: 41, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 41
DeviceJob: set_books_in_library finished: time= 0.010999917984
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 2 Set library information finished
No details available.
Job: 1 Get device information finished
No details available.
Job: 3 Get list of books on device finished
No details available.

**Comment by cirrusnine** [comment]
The same here.

Mac HighSierra 10.13.6
APFS (encrypted)
Python 2.7.15
Calibre 3.33.1
DeDRM 6.6.1 & 6.6.0

Makes me wonder if I'm missing a step?
I have pycrypto installed.  Anything else?

Also: DeDRM.app won't open.  It's not a security issue.  

I tried with two objects in this file (6.6.1 log):

```Traceback (most recent call last):
  File "site-packages/calibre/gui2/ui.py", line 157, in __init__
  File "site-packages/calibre/gui2/ui.py", line 171, in init_iaction
  File "site-packages/calibre/customize/__init__.py", line 612, in load_actual_plugin
  File "lib/python2.7/importlib/__init__.py", line 37, in import_module
  File "site-packages/calibre/customize/zipplugin.py", line 184, in load_module
  File "calibre_plugins.similar_stories.action", line 12, in <module>
ImportError: No module named PyQt4.Qt
libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 3.33.1  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Goodreads (1, 2, 0) && BOL_NL (3, 8, 21) && Job Spy (1, 0, 137) && Similar Stories (1, 0, 58) && English Noun Frequency (1, 0, 9) && CalibreSpy (1, 0, 45)
calibre 3.33.1  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Goodreads (1, 2, 0) && BOL_NL (3, 8, 21) && Job Spy (1, 0, 137) && Similar Stories (1, 0, 58) && English Noun Frequency (1, 0, 9) && CalibreSpy (1, 0, 45)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.21] db initialized
[0.21] Constructing main UI...
Job Spy has begun initialization...
Calibre, and hence Job Spy, was gracefully shut down last time?  True
Last time daemon started:  never
Last time daemon failed:  never
Total daemon starts inception_to_date:  0
Total daemon failures inception-to-date:  0
Job Spy has finished initialization...
CalibreSpy: initialization_complete
[1.88] main UI initialized...
[1.88] Hiding splash screen
[1.94] splash screen hidden
[1.96] Started up in 1.96 seconds with 88 books```

**Comment by jonathanclark** [comment]
@ellekayem
I just want to say thanks very much for your answer.

And for anybody else with this problem, I solved mine by installing an old version of Kindle for PC (1.17) which doesn't support KFX files, so now I just have azw files to deal with.

**Comment by ElleKayEm** [comment]
I think the azw3 files are better for converting to epub anyway.  If you're all set, you can close the issue.

**Comment by jdvanisl** [comment]
I just purchased an ebook from Kindle, and can't download from Amazon other than in KFX format (author's choice?). Even though I have installed DeDRM from file, when I import and try to convert the file in Calibre, I get an error message about DRM.  I think I followed all the instructions. My computer is an HP Compaq SFF i5-3470.
-----------------------------------------------
calibre Debug log
calibre 3.46 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 17, 1) && EpubSplit (2, 7, 0) && Set KFX metadata (from KFX Output) (1, 30, 0) && KFX Output (1, 30, 0) && KFX metadata reader (from KFX Input) (1, 17, 1) && KFX Input (1, 17, 1) && EpubMerge (2, 5, 0)
calibre 3.46 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 17, 1) && EpubSplit (2, 7, 0) && Set KFX metadata (from KFX Output) (1, 30, 0) && KFX Output (1, 30, 0) && KFX metadata reader (from KFX Input) (1, 17, 1) && KFX Input (1, 17, 1) && EpubMerge (2, 5, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 90.0253164557 x 90.1013513514
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
EpubMerge: DEBUG: 2019-07-31 16:07:50,798: calibre_plugins.epubmerge.epubmerge_plugin(154): macmenuhack file_path:C:\Users\JenD\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[1.99] main UI initialized...
[1.99] Hiding splash screen
[7.31] splash screen hidden
[7.31] Started up in 7.31 seconds with 1813 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xaf\r\xbc\xb6\x17\xe8\x81n _\x04\x9bC\xa8\xab\xb0\xa0B\xbd\xab\xbd\x9fSB\x05\x97\xd5]]\x0c_.', 'F:\\JenD\\Documents\\My Kindle Content\\B07JPBTT87_EBOK\\B07JPBTT87_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.17.1: Importing F:\JenD\Documents\My Kindle Content\B07JPBTT87_EBOK\B07JPBTT87_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\JenD\AppData\Local\Temp\calibre_8gkvvw\gknsm5.kfx-zip
DeDRM v6.6.1: Trying to decrypt gknsm5.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: gknsm5
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7130d522-e75c-4322-b31a-1915bab0a06d.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\JenD\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.17.1: Packaging C:\Users\JenD\AppData\Local\Temp\calibre_8gkvvw\gknsm5.kfx-zip
Processing container: B07JPBTT87_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B07JPBTT87_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\JenD\AppData\Local\Temp\calibre_8gkvvw\aezbmf_add_books\0\B07JPBTT87_EBOK.kfx-zip
Added A Question of Hats: An Angela Marchmont Short Story (An Angela Marchmont Mystery) to db in: 2.2
Added 1 books in 3.3 seconds
Worker Launch took: 0.129999876022
Job: 0 Convert book 1 of 1 (A Question of Hats: An Angela Marchmont Short Story (An Angela Marchmont Mystery)) finished
Convert book 1 of 1 (A Question of Hats: An Angela Marchmont Short Story (An Angela Marchmont Mystery))
	Conversion options changed from defaults:
	  output_profile: u'tablet'
	  read_metadata_from_opf: u'C:\\Users\\JenD\\AppData\\Local\\Temp\\calibre_8gkvvw\\kgaxw6.opf'
	  allow_conversion_with_errors: True
	  verbose: 2
	  cover: u'C:\\Users\\JenD\\AppData\\Local\\Temp\\calibre_8gkvvw\\bxkxzd.jpeg'
	Resolved conversion options
	calibre version: 3.46.0
	{'allow_conversion_with_errors': True,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\JenD\\AppData\\Local\\Temp\\calibre_8gkvvw\\bxkxzd.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001A883E0DC88>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x000001A883E1C748>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\JenD\\AppData\\Local\\Temp\\calibre_8gkvvw\\kgaxw6.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\JenD\AppData\Local\Temp\calibre_8gkvvw\n7nswj.kfx-zip
	Software versions: KFX Input 1.17.1, calibre 3.46 [64bit], Windows-10-10.0.17763-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\JenD\AppData\Local\Temp\calibre_8gkvvw\n7nswj.kfx-zip
	Processing container: B07JPBTT87_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 98, in convert
	  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
	KFXDRMError: Book container B07JPBTT87_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 200, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 101, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
Kindle for PC which was used to download the book needs to be on the same machine and user as calibre with DeDRM.

**Comment by jdvanisl** [comment]
Thanks for the suggestion. Yes, all on the same machine.

On 2019-07-31 5:09:36 PM, ElleKayEm <notifications@github.com> wrote:
Kindle for PC which was used to download the book needs to be on the same machine and user as calibre with DeDRM.

**Comment by j-howell** [comment]
You must use a Kindle for PC version older then 1.25 for this method to work.

**Comment by jdvanisl** [comment]
Yes, tried that too!

On 2019-07-31 7:32:30 PM, John Howell <notifications@github.com> wrote:
You must use a Kindle for PC version older then 1.25 for this method to work.

**Comment by jdvanisl** [comment]
Thanks ElleKayEm and j-Howell for your suggestions. I decided to go back and uninstall/reinstall both Kindle for PC and DeDRM. Perhaps I did something different, because this time it worked, I was able to download from Kindle in AZW3 format. Back in business!
