### ISSUE TITLE
Adding Support for Yuzu

### ISSUE THREAD

**Issue by spaz926** [apprenticeharper/DeDRM_tools#67]
As far as I can tell [Yuzu](yuzu.com) uses the same encryption as Barnes & Noble Study, but I'm unable to get the encryption keys for my account.

Would it be possible to add support for Yuzu?

**Comment by apprenticeharper** [comment]
If you can tell me how to generate a key for a Yuzu account, I'm sure something could be done.

**Comment by apprenticeharper** [comment]
Closed for now.

**Comment by jaimehrubiks** [comment]
Any news on new ebooks for yuzu?
