### ISSUE TITLE
Cant convert / open book from kindle

### ISSUE THREAD

**Issue by arraart** [apprenticeharper/DeDRM_tools#671]
Hey guys I bought book from kindle store on my kindle, following steps in the read me... and it did not work log file is >>>

calibre Debug log
calibre 3.33.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.33.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.42] db initialized
[0.42] Constructing main UI...
[3.78] main UI initialized...
[3.78] Hiding splash screen
[11.52] splash screen hidden
[11.52] Started up in 11.52 seconds with 1 books
DeDRM v6.6.1: Trying to decrypt Kids'Skills in Action_ A Solution-focused method for coaching children to overcome difficulties_B01LYJI2Y6.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Kids'Skills in Action: A Solution-focused method for coaching children to overcome difficulties
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Stano\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Kids'Skills in Action: A Solution-focused method for coaching children to overcome difficulties to db in: 0.4
Added 1 books in 2.6 seconds
>>>

Thank you for any help

**Comment by arraart** [comment]
you are pure gold hearted being and your advice helped :)

**Comment by ElleKayEm** [comment]
Are you all set?  If so, you can close this issue.
