### ISSUE TITLE
CALIBER problem with KFX with kindle for MAC 

### ISSUE THREAD

**Issue by Potorpan** [apprenticeharper/DeDRM_tools#672]
Hello,
I've installed the latest version of Calibre, as well as the plug in : DeDRM_Tools_6.6.1.zip
But still is unsuccessful. I've tried a few times to open and close, delete books, start again, to no avail.
Can someone help?

This is the message that popped up in the 'debug' mode.
Thanks for your help!!!

calibre Debug log
calibre 3.33.1  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.33.1  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 128.000001922
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.21] splash screen shown
[0.21] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[1.55] main UI initialized...
[1.55] Hiding splash screen
[1.58] splash screen hidden
[1.59] Started up in 1.59 seconds with 0 books
objc[3733]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9e4abc90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11dc6dcd8). One of the two will be used. Which one is undefined.
DeDRM v6.6.1: Trying to decrypt B00KAWW82G_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.6.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/Matthias/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'ed72a0f44324' and UserName 'Matthias'
DeDRM v6.6.1: Found 1 new key
DeDRM v6.6.1: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 284, in get_metadata
  File "site-packages/calibre/ebooks/metadata/mobi.py", line 495, in get_metadata
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 284, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 312, in identity
MobiError: Unknown book type: Åƒﬁúå"
2018-11-02 14:09:20.752 Calibre[3749:450488] deliverNotificationWithTitle()
* Notification delivered.
Added B00KAWW82G EBOK to db in: 0.0
Added 1 books in 1.8 seconds
Worker Launch took: 0.240218877792
Job: 1 Convert book 1 of 1 (B00KAWW82G EBOK) finished
Convert book 1 of 1 (B00KAWW82G EBOK)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'/var/folders/cg/kv2vhyjs5fq2cdb43518fj900000gn/C/calibre_3.33.1_tmp_Rw7ycE/rFpXsF.opf'
	  output_profile: 'kindle'
	  verbose: 2
	Resolved conversion options
	calibre version: 3.33.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10b49c4d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x10b49cb90>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/cg/kv2vhyjs5fq2cdb43518fj900000gn/C/calibre_3.33.1_tmp_Rw7ycE/rFpXsF.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.
	InputFormatPlugin: MOBI Input running
	on /var/folders/cg/kv2vhyjs5fq2cdb43518fj900000gn/C/calibre_3.33.1_tmp_Rw7ycE/FsPQo5.azw
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 199, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
	  File "site-packages/calibre/customize/conversion.py", line 244, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 35, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 84, in __init__
	calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

**Comment by ElleKayEm** [comment]
As it says in the log, this is a KFX book.  You'll need to install the KFX Input plugin.  Or you can follow the link to find out about getting the book in the older format.

Here's the link again:
https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Potorpan** [comment]
Hello ElleKayEm,

Thank you very much for taking time to answer my query. Inserted the KFZ plugin and it worked smoothly!!!

I appreciate that someone is there to keep an eye out, novices like me often get confused with all these 'plugins' and stuff.

Many thanks!!!
