### ISSUE TITLE
DeDRM_tools version 6.6.1 does not work anymore with kf8

### ISSUE THREAD

**Issue by Der-Bauer** [apprenticeharper/DeDRM_tools#673]
Hey Folks cant anymore with your tool decrypt awz3 files which has kf8 to any format i want 

Buch 1 von 1 (Sonnenstein, Band 1 (German Edition)) konverteren
Conversion options changed from defaults:
  cover: u'/tmp/calibre_3.33.1_tmp_7JqFF1/claqRW.jpeg'
  verbose: 2
  output_profile: 'kindle_oasis'
  read_metadata_from_opf: u'/tmp/calibre_3.33.1_tmp_7JqFF1/NWJ6i1.opf'
  input_profile: 'kindle'
Resolved conversion options
calibre version: 3.33.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/tmp/calibre_3.33.1_tmp_7JqFF1/claqRW.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.KindleInput object at 0x7f603178ae50>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': u'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindleOasisOutput object at 0x7f6031777490>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'personal_doc': u'[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/tmp/calibre_3.33.1_tmp_7JqFF1/NWJ6i1.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on /tmp/calibre_3.33.1_tmp_7JqFF1/zCsdSr.azw3
Found KF8 MOBI of type 'standalone'
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 199, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
  File "site-packages/calibre/customize/conversion.py", line 244, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 45, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 157, in check_for_drm
DRMError: Sonnenstein, Band 1 (German Edition)

**Comment by ElleKayEm** [comment]
DRM removal happens when you add the book, not during conversion.  Here's how to get the debug log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by Der-Bauer** [comment]
here´s my log file 
[tmpK84EBA.txt](https://github.com/apprenticeharper/DeDRM_tools/files/2544206/tmpK84EBA.txt)

**Comment by ElleKayEm** [comment]
DeDRM is tricky to get setup with Linux.  You'll see a lot of issues on here with a similar error:

> Command line: 'WINEPREFIX="/home/sven" wine python.exe "/home/sven/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/sven/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
/bin/sh: 1: wine: not found

You could try running kindlekey.py and importing the key yourself.

**Comment by Der-Bauer** [comment]
how can i do that with kindlekey.py

**Comment by ElleKayEm** [comment]
Run it manually under Wine from the command line.  You do need to have Python and PyCrypto installed under Wine.  Something like what it tried to do:

wine python.exe "/home/sven/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/sven/winekeysdir"

You might have to create that directory first.  Then import the retrieved key into the plugin.

**Comment by Der-Bauer** [comment]
i tried to install python  with wine it crashed and  pycrypto seem not to exist anymore

**Comment by ElleKayEm** [comment]
Take a look at the instructions for Linux at the end of the DeDRM_plugin_ReadMe.txt file.  It says that they're out of date, but maybe that will give you a starting point.

**Comment by Der-Bauer** [comment]
seems it does not help either but if i try to convert kfx file to another format it work´s but with awz3 files not

**Comment by ElleKayEm** [comment]
How are you downloading the azw3 file?  If it's from the website, you need to choose an E-ink Kindle (not a Fire) and enter its serial number into the plugin customization.  Same thing if it's directly from an E-ink Kindle.

**Comment by Der-Bauer** [comment]
i download the whole time from amazon directly awz3 files and i allready entered the serial number of my device of my kindle

**Comment by ElleKayEm** [comment]
Where is the KFX from then?

**Comment by Der-Bauer** [comment]
from my kindle oasis

**Comment by ElleKayEm** [comment]
And when you download the AZW3 from the website, you're selecting your Kindle Oasis as the device?

**Comment by ElleKayEm** [comment]
Only for the KFX format.  Older formats like AZW3/KF8 are the same.

**Comment by Der-Bauer** [comment]
it seems it´s working again

**Comment by ElleKayEm** [comment]
Good.  You can close the issue if you're all set.
