### ISSUE TITLE
Calibre DeDRM Windows 10 Some Kindle books not decrypting

### ISSUE THREAD

**Issue by SilventheThrid** [apprenticeharper/DeDRM_tools#675]
Just downloaded two books from Amazon for USB transfer to Kindle, ran them through Calibre with the DeDRM plugin and one DeDRM'd fine while the other does not.

This a log for the one that does not. 

calibre Debug log
calibre 3.30 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.30 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.664921466 x 127.590697674
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
Loaded cached store plugin for: Beam EBooks DE at version: 4
[1.08] main UI initialized...
[1.08] Hiding splash screen
[8.70] splash screen hidden
[8.70] Started up in 8.70 seconds with 29 books
DeDRM v6.6.1: Trying to decrypt Draw More Furries_ How to Create Anthropomorphic Fantasy Creatures.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Draw More Furries: How to Create Anthropomorphic Fantasy Creatures
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\holtk\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\holtk\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '777410942' and UserName '686f6c746b'
DeDRM v6.6.1: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Draw More Furries: How to Create Anthropomorphic Fantasy Creatures
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Draw More Furries: How to Create Anthropomorphic Fantasy Creatures to db in: 0.4
Added 1 books in 1.1 seconds
Worker Launch took: 0.0659999847412

**Comment by ElleKayEm** [comment]
Did you choose an E-ink Kindle for the device?  You need to enter its serial number into the plugin customization.  The log shows that there weren't any keys to try.  Perhaps the one that worked was already DRM-free?

**Comment by SilventheThrid** [comment]
I didn't choose E-Ink, all I have is a Kindle Fire 7, and I am fairly certain when I loaded both books into Calibre before I knew about this whole DRM thing it said both had DRM on them

**Comment by ElleKayEm** [comment]
Unfortunately the tools don't work with books from a Fire.  If you don't have an E-ink Kindle, the other option is to download them with Kindle for PC.

**Comment by SilventheThrid** [comment]
I did download both via the "Download and Transfer via USB" option on Amazon's website

**Comment by SilventheThrid** [comment]
Nvm, it would seem the one I was able to open was in fact without DRM, sorry to have wasted your time.
