### ISSUE TITLE
Failure to decrypt Kindle for PC

### ISSUE THREAD

**Issue by Beater34** [apprenticeharper/DeDRM_tools#678]
I purchased a book from Amazon for use on Kindle for PC on a Windows computer where I can read the book. However, Calibre with Alf's plugin fails to remove the DRM from the azw file (which has worked on previous occasions). I updated Calibre and the Alf plugin to the latest versions, but the DRM is still not removed. The folder My Kindle Content contains two new files( book_asset.db and B0031XYIA6_EBOK.apnx) and a new subfolder containing the files B00P6TZFT6_EBOK.azw, B00P6TZFT6_EBOK.mbpV2, B00P6TZFT6_EBOK.phl and long filenames with the extensions .voucher and .res and .md). I'd greatly appreciate some help, please. 

calibre Debug log
calibre 3.34 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 3, 4)
calibre 3.34 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 3, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
[2.07] main UI initialized...
[2.07] Hiding splash screen
[9.64] splash screen hidden
[9.64] Started up in 9.64 seconds with 207 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x14\xde\x83L\xd9cvV\xb7\x9f\xbc\xban\xe0V\x96\xae\xa7\xee\xc5\xd1\xe7\x97\xcbc\xd5\xacI\x08O\x9c\x9c', 'C:\\Users\\User\\Documents\\My Kindle Content\\B00P6TZFT6_EBOK\\B00P6TZFT6_EBOK.azw']
DeDRM v6.3.4: Trying to decrypt B00P6TZFT6_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
DeDRM v6.3.4: Failed to decrypt with error: Invalid file format
DeDRM v6.3.4: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\User\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\User\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1016542413' and UserName '55736572'
DeDRM v6.3.4: Found 1 new key
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
DeDRM v6.3.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 590, in run
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
DeDRMError: DeDRM v6.3.4: Ultimately failed to decrypt after 0.1 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 495, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: ÄÞŒ#
Added B00P6TZFT6 EBOK to db in: 0.9
Added 1 books in 1.5 seconds
Worker Launch took: 0.0890002250671

**Comment by ElleKayEm** [comment]
Update DeDRM.  Current version is 6.6.1.

**Comment by Beater34** [comment]
Thank you! My apologies for making such an elementary error (I downloaded 6.6.1, but then reinstalled the old version).

**Comment by Beater34** [comment]
Thanks again for your prompt and helpful advice.
