### ISSUE TITLE
DRM removing from azw/azw3 failed with 6.3.6.a

### ISSUE THREAD

**Issue by e-orlov** [apprenticeharper/DeDRM_tools#68]
Hello!
Win7, Calibre 2.50.1.
Debug info is following:

        Microsoft Windows [Version 6.1.7601]
        Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

        C:\Users\admin>calibre-debug -g
        calibre 2.50.1  isfrozen: True is64bit: False
        Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
        32bit process running on 64bit windows
        ('Windows', '7', '6.1.7601')
        Python 2.7.9
        Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
        Successfully initialized third party plugins: DeDRM
        Starting up...
        Started up in 2.75 seconds with 139 books
        DeDRM v6.3.6: Trying to decrypt Facebook-Programmierung_ Entwicklung von Social
        Apps & Websites für die Facebook-Plattform (German Edition).azw3
        Using Library AlfCrypto DLL/DYLIB/SO
        MobiDeDrm v0.41.
        Copyright © 2008-2012 The Dark Reverser et al.
        MOBI header version 8, header length 264
        Extra Data Flags: 3
        Decrypting Kindle Format 8 ebook: Facebook-Programmierung: Entwicklung von Socia
        l Apps & Websites für die Facebook-Plattform (German Edition)
        Found 0 keys to try after 0.4 seconds
        Crypto Type is: 2
        DeDRM v6.3.6: Failed to decrypt with error: No key found in 0 keys tried.
        DeDRM v6.3.6: Looking for new default Kindle Key after 0.4 seconds
        searching for kinfoFiles in C:\Users\admin\AppData\Local
        No K4PC kindle.info/kinf/kinf2011 files have been found.
        DeDRM v6.3.6: Ultimately failed to decrypt after 0.4 seconds.
        Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
        Running file type plugin DeDRM failed with traceback:
        Traceback (most recent call last):
          File "site-packages\calibre\customize\ui.py", line 153, in _run_filetype_plugi
        ns
          File "calibre_plugins.dedrm.__init__", line 597, in run
          File "calibre_plugins.dedrm.__init__", line 547, in KindleMobiDecrypt
        DeDRMError: DeDRM v6.3.6: Ultimately failed to decrypt after 0.4 seconds
        C:\Program Files (x86)\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning
        : Unicode equal comparison failed to convert both arguments to Unicode - interpr
        eting them as being unequal
        Added Non-ASCII text detected. You must set your Console's font to Lucida Consol
        e or Consolas or some other TrueType font to see this text -- Facebook-Programmi
        erung: Entwicklung von Social Apps & Websites fur die Facebook-Plattform (German
         Edition) to db in: 1.9
        Added 1 books in 3.9 seconds
        Worker Launch took: 0.335999965668
        Job: 1 Non-ASCII text detected. You must set your Console's font to Lucida Conso
        le or Consolas or some other TrueType font to see this text -- Buch 1 von 1 (Fac
        ebook-Programmierung: Entwicklung von Social Apps & Websites fur die Facebook-Pl
        attform (German Edition)) konvertieren finished
        Non-ASCII text detected. You must set your Console's font to Lucida Console or C
        onsolas or some other TrueType font to see this text -- Buch 1 von 1 (Facebook-P
        rogrammierung: Entwicklung von Social Apps & Websites fur die Facebook-Plattform
         (German Edition)) konvertieren
                C:\Program Files (x86)\Calibre2\pylib.zip\dateutil\parser.py:339: Unicod
        eWarning: Unicode equal comparison failed to convert both arguments to Unicode -
         interpreting them as being unequal
                Resolved conversion options
                calibre version: 2.50.1
                {'asciiize': False,
                 'author_sort': None,
                 'authors': None,
                 'base_font_size': 0.0,
                 'book_producer': None,
                 'change_justification': u'original',
                 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((ch
        apter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @c
        lass = 'chapter']",
                 'chapter_mark': u'pagebreak',
                 'comments': None,
                 'cover': u'C:\\Users\\admin\\AppData\\Local\\Temp\\calibre_vpjotf\\96
                6yvj.jpeg',
                 'debug_pipeline': None,
                 'dehyphenate': True,
                 'delete_blank_paragraphs': True,
                 'disable_font_rescaling': False,
                 'dont_compress': False,
                 'duplicate_links_in_toc': False,
                 'embed_all_fonts': False,
                 'embed_font_family': None,
                 'enable_heuristics': False,
                 'expand_css': False,
                 'extra_css': None,
                 'extract_to': None,
                 'filter_css': u'',
                 'fix_indents': True,
                 'font_size_mapping': None,
                 'format_scene_breaks': True,
                 'html_unwrap_factor': 0.4,
                 'input_encoding': None,
                 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0
                36B58F0>,
                 'insert_blank_line': False,
                 'insert_blank_line_size': 0.5,
                 'insert_metadata': False,
                 'isbn': None,
                 'italicize_common_cases': True,
                 'keep_ligatures': False,
                 'language': None,
                 'level1_toc': None,
                 'level2_toc': None,
                 'level3_toc': None,
                 'line_height': 0.0,
                 'linearize_tables': False,
                 'margin_bottom': 5.0,
                 'margin_left': 5.0,
                 'margin_right': 5.0,
                 'margin_top': 5.0,
                 'markup_chapter_headings': True,
                 'max_toc_links': 50,
                 'minimum_line_height': 120.0,
                 'mobi_file_type': u'old',
                 'mobi_ignore_margins': False,
                 'mobi_keep_original_images': False,
                 'mobi_toc_at_start': False,
                 'no_chapters_in_toc': False,
                 'no_inline_navbars': True,
                 'no_inline_toc': False,
                 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x
                036B5C50>,
                 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
                 'personal_doc': u'[PDOC]',
                 'prefer_author_sort': False,
                 'prefer_metadata_cover': False,
                 'pretty_print': False,
                 'pubdate': None,
                 'publisher': None,
                 'rating': None,
                 'read_metadata_from_opf': u'C:\\Users\\admin\\AppData\\Local\\Temp\\c
                alibre_vpjotf\\oz8md3.opf',
                 'remove_fake_margins': True,
                 'remove_first_image': False,
                 'remove_paragraph_spacing': False,
                 'remove_paragraph_spacing_indent_size': 1.5,
                 'renumber_headings': True,
                 'replace_scene_breaks': u'',
                 'search_replace': '[]',
                 'series': None,
                 'series_index': None,
                 'share_not_sync': False,
                 'smarten_punctuation': False,
                 'sr1_replace': None,
                 'sr1_search': None,
                 'sr2_replace': None,
                 'sr2_search': None,
                 'sr3_replace': None,
                 'sr3_search': None,
                 'start_reading_at': None,
                 'subset_embedded_fonts': False,
                 'tags': None,
                 'timestamp': None,
                 'title': None,
                 'title_sort': None,
                 'toc_filter': None,
                 'toc_threshold': 6,
                 'toc_title': None,
                 'unsmarten_punctuation': False,
                 'unwrap_lines': True,
                 'use_auto_toc': False,
                 'verbose': 2}
                InputFormatPlugin: MOBI Input running
                on C:\Users\admin\AppData\Local\Temp\calibre_vpjotf\sdsfpw.azw3
                Found KF8 MOBI of type 'standalone'
                Python function terminated unexpectedly
                  Facebook-Programmierung: Entwicklung von Social Apps & Websites fur di
        e Facebook-Plattform (German Edition) (Error Code: 1)
                Traceback (most recent call last):
                  File "site.py", line 132, in main
                  File "site.py", line 109, in run_entry_point
                  File "site-packages\calibre\utils\ipc\worker.py", line 190, in main
                  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 31,
                in gui_convert_override
                  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 25,
                in gui_convert
                  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1051,
                in run
                  File "site-packages\calibre\customize\conversion.py", line 241, in __c
                all__
                  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py",
                line 43, in convert
                  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 81, in
                __call__
                  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 144, in
                 check_for_drm
                calibre.ebooks.DRMError: Facebook-Programmierung: Entwicklung von Social
                 Apps & Websites fur die Facebook-Plattform (German Edition)`

**Comment by ElleKayEm** [comment]
If the book is from an E-ink Kindle, then you need to enter your Kindle's serial number into the plugin customization.  Otherwise, install Kindle for PC, download the book there, and import that copy.
