### ISSUE TITLE
Calibre has stopped converting books

### ISSUE THREAD

**Issue by frostbitesouth** [apprenticeharper/DeDRM_tools#682]
My Calibre has just stopped converting books.  Its says the book is locked by DRM.  When the file was transferred over from Kindle to Calibre it created a KFX-ZIP file in Calibre.  When I try to convert to another file type it says that it can't convert.  Locked by DRM.  When I try to open the book, it doesn't recognize the file type.  It has been working just fine on many many books up until today.

**Comment by j-howell** [comment]
Post an import log. See the FAQ for instructions:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
