### ISSUE TITLE
3 books fail to convert

### ISSUE THREAD

**Issue by RodMyers** [apprenticeharper/DeDRM_tools#687]
I can download and convert 99% of kindle ebooks. right now, I have 3 that fail. here's the logfile for 1 of them;

calibre, version 3.34.0 (linux2, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (The Last Rainmaker)

Convert book 1 of 1 (The Last Rainmaker)
Conversion options changed from defaults:
  preserve_cover_aspect_ratio: True
  cover: u'/tmp/calibre_3.34.0_tmp_7AwZog/wAywpI.jpeg'
  verbose: 2
  output_profile: 'generic_eink'
  read_metadata_from_opf: u'/tmp/calibre_3.34.0_tmp_7AwZog/Iuawf8.opf'
Resolved conversion options
calibre version: 3.34.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/tmp/calibre_3.34.0_tmp_7AwZog/wAywpI.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7fecc767d4d0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x7fecc767d8d0>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': True,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/tmp/calibre_3.34.0_tmp_7AwZog/Iuawf8.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on /tmp/calibre_3.34.0_tmp_7AwZog/cpvCHS.azw
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 199, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
  File "site-packages/calibre/customize/conversion.py", line 244, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 37, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 161, in extract_content
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 157, in check_for_drm
DRMError: The Last Rainmaker (Jack Widow Book 9)

**Comment by ElleKayEm** [comment]
DRM removal happens when you add the book, not during conversion.  Here's how to get the log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by RodMyers** [comment]
My bad.  Here is the output of the debug.log file;

calibre Debug log
calibre 3.34  embedded-python: True is64bit: True
Linux-4.9.0-8-amd64-x86_64-with-debian-9 Linux ('64bit', 'ELF')
('Linux', '4.9.0-8-amd64', '#1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08)')
Python 2.7.12
Linux: ('debian', '9', '')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 0, 8) && Goodreads Sync (1, 12, 1) && Reading List (1, 6, 6) && Manage Series (1, 2, 8)
calibre 3.34  embedded-python: True is64bit: True
Linux-4.9.0-8-amd64-x86_64-with-debian-9 Linux ('64bit', 'ELF')
('Linux', '4.9.0-8-amd64', '#1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08)')
Python 2.7.12
Linux: ('debian', '9', '')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 0, 8) && Goodreads Sync (1, 12, 1) && Reading List (1, 6, 6) && Manage Series (1, 2, 8)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.1119113573 x 96.0945812808
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.10] splash screen shown
[0.10] Initializing db...
[0.21] db initialized
[0.21] Constructing main UI...
DEBUG:    0.0 HttpHelper::__init__: proxy=None
[1.33] main UI initialized...
[1.33] Hiding splash screen
[3.55] splash screen hidden
[3.56] Started up in 3.56 seconds with 1686 books
['zenity', '--modal', '--file-selection', '--title=Select books', '--separator=\n', '--attach=65011726', '--filename=/home/rodney/Documents/My Kindle Content/.fgdfg.gdfhjdhf*&^839', '--file-filter=Books | *.lrf *.rar *.zip *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx', '--file-filter=EPUB books | *.epub *.kepub', '--file-filter=Kindle books | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=PDF books | *.pdf *.azw4', '--file-filter=HTML books | *.htm *.html *.xhtm *.xhtml', '--file-filter=LIT books | *.lit', '--file-filter=Text books | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Comics | *.cbz *.cbr *.cbc', '--file-filter=Archives | *.zip *.rar', '--file-filter=Wordprocessor files | *.odt *.doc *.docx', '--file-filter=All files | *', '--multiple']
DeDRM v6.0.8: Trying to decrypt B00N735A3Y_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Dead Man Walking (Part 1 of 3) (Detective Mark Heckenburg, Book 4)
Found 8 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.0.8: Failed to decrypt with error: No key found in 8 keys tried.
DeDRM v6.0.8: Looking for new default Kindle Key after 0.0 seconds
DeDRM v6.0.8: Running kindlekey.py under Wine
DeDRM v6.0.8: Command line: “wine python.exe "/home/rodney/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/rodney/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"”
/bin/sh: 1: wine: not found
DeDRM v6.0.8: Found and decrypted 0 key files
DeDRM v6.0.8: Ultimately failed to decrypt after 0.0 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 380, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 216, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 469, in processBook
DrmException: No key found in 8 keys tried.
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 471, in run
  File "calibre_plugins.dedrm.__init__", line 422, in KindleMobiDecrypt
DeDRMError: DeDRM v6.0.8: Ultimately failed to decrypt “B00N735A3Y_EBOK.azw” after 0.0 seconds with error: No key found in 8 keys tried.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Added Dead Man Walking (Part 1 of 3) (Detective Mark Heckenburg, Book 4) to db in: 1.3
Added 1 books in 1.8 seconds
Worker Launch took: 0.262341976166
Job: 1 Convert book 1 of 1 (Dead Man Walking (Part 1 of 3) (Detective Mark Heckenburg, Book 4)) finished
Convert book 1 of 1 (Dead Man Walking (Part 1 of 3) (Detective Mark Heckenburg, Book 4))
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: 'generic_eink'
	  cover: u'/tmp/calibre_3.34.0_tmp_bYgRyr/8_qtes.jpeg'
	  preserve_cover_aspect_ratio: True
	  read_metadata_from_opf: u'/tmp/calibre_3.34.0_tmp_bYgRyr/I4xnCI.opf'
	Resolved conversion options
	calibre version: 3.34.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/tmp/calibre_3.34.0_tmp_bYgRyr/8_qtes.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f7374772790>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x7f7374772b90>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': True,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/tmp/calibre_3.34.0_tmp_bYgRyr/I4xnCI.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /tmp/calibre_3.34.0_tmp_bYgRyr/T7CLfH.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "site.py", line 77, in main
	  File "site-packages/calibre/utils/ipc/worker.py", line 199, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
	  File "site-packages/calibre/customize/conversion.py", line 244, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 45, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 157, in check_for_drm
	DRMError: Dead Man Walking (Part 1 of 3) (Detective Mark Heckenburg, Book 4)

Convert book 1 of 1 (Dead Man Walking (Part 1 of 3) (Detective Mark Heckenburg, Book 4))
Conversion options changed from defaults:
  verbose: 2
  output_profile: 'generic_eink'
  cover: u'/tmp/calibre_3.34.0_tmp_bYgRyr/8_qtes.jpeg'
  preserve_cover_aspect_ratio: True
  read_metadata_from_opf: u'/tmp/calibre_3.34.0_tmp_bYgRyr/I4xnCI.opf'
Resolved conversion options
calibre version: 3.34.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/tmp/calibre_3.34.0_tmp_bYgRyr/8_qtes.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f7374772790>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x7f7374772b90>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': True,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/tmp/calibre_3.34.0_tmp_bYgRyr/I4xnCI.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on /tmp/calibre_3.34.0_tmp_bYgRyr/T7CLfH.azw
Found KF8 MOBI of type 'standalone'
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 199, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
  File "site-packages/calibre/customize/conversion.py", line 244, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 45, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 157, in check_for_drm
DRMError: Dead Man Walking (Part 1 of 3) (Detective Mark Heckenburg, Book 4)

**Comment by ElleKayEm** [comment]
Well, you're using a very old version of DeDRM.  Try updating that first.  Could be KFX files -- in which case you'll also need the KFX Input plugin -- or to download it in an older format.  See this post for more info on that:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by RodMyers** [comment]
I thought I had updated the DeDRM, will try again.

As for the link, I am using an older version, as mentioned in the step 1, and also did Step 2 as described

**Comment by ElleKayEm** [comment]
Showing 6.0.8 and the current version is 6.6.1.

If you're using method 1 or 2, then there shouldn't be any worries about KFX files.  What might be different about the way you downloaded these versus the ones that worked?

**Comment by RodMyers** [comment]
they are batch downloaded in vbox/windows. they show the azw format.

in each download, one or more will decrypt. just these 3 will not

**Comment by ElleKayEm** [comment]
That's odd because it's usually all or nothing.  If you retrieve the key for a particular installation of Kindle for PC, then all books downloaded with it should unlock.  But a reinstall or a different app/device will have a different key.  All Kindle books will show the AZW extension when downloaded to K4PC.  Once imported into calibre and DeDRMed, they'll show MOBI, AZW3, or whatever the underlying format actually is.

**Comment by RodMyers** [comment]
very odd. Not sure how t proceed.

if it was just one book, I could live with it. But 3 different books, seems like a trend

**Comment by ElleKayEm** [comment]
Take a look at a log with the current DeDRM of both a book that fails and one that works.  Do it with a fresh download of both books from the same app.

**Comment by RodMyers** [comment]
okay, 2 logs.original.log for already downloaded files.
re-download.log after I deleted the 2set of files, and grabbed them again.

[Original.log](https://github.com/apprenticeharper/DeDRM_tools/files/2601806/Original.log)

[re-download.log](https://github.com/apprenticeharper/DeDRM_tools/files/2601807/re-download.log)

**Comment by RodMyers** [comment]
I did do a reinstall into windows 7 vbox. I thought I copied the directory structure from one session into the new session.

Let me go back to the older session and try then

**Comment by RodMyers** [comment]
Installed calibre inside of vbox, and everything ran good.

will continue to tinker with that.

Thank you and apologies 

Will close issue

**Comment by ElleKayEm** [comment]
You could save the key from the plugin in vbox calibre and import it into the Linux calibre plugin.

**Comment by RodMyers** [comment]
Found. Thank you

**Comment by drneelesh** [comment]
I am a newbie! not able to convert mobi (AZW4) files to pdf, help me. Installed old version of kindle 1.17.0(44170) version but still not able to convert.

**Comment by ElleKayEm** [comment]
Was going to tell you to start your own issue, but I see you already did.

issue #697
