### ISSUE TITLE
Kindle PC detected but unable to dedrm

### ISSUE THREAD

**Issue by ERICHBUHLER** [apprenticeharper/DeDRM_tools#70]
Plug installed in Calibre, kindle PC key is detected but when trying to open a drmed kindle book, a message saying "This book is DRM. To learn more about DRM...."

**Comment by ElleKayEm** [comment]
Post a log of importing a book from Kindle for PC.

**Comment by apprenticeharper** [comment]
Try with DeDRM 6.4.0
