### ISSUE TITLE
Failed to Import With Calibre

### ISSUE THREAD

**Issue by theengineerman** [apprenticeharper/DeDRM_tools#706]
Hi,

Another failed to import property report. Calibre does import but I get a KFX-ZIP file, which Calibre then won't convert.

Here is my log file. 

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 3.35  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14.2', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 11, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 11, 0) && Count Pages (1, 8, 2) && Wikidata (1, 2, 0) && Barnes & Noble (1, 2, 15) && Goodreads (1, 3, 0) && Fantastic Fiction (1, 3, 0) && Resize Cover (1, 0, 2) && Hyphenate This! (0, 0, 8) && NormComment (0, 0, 3) && Kobo Books (1, 4, 0) && Search The Internet (1, 7, 6) && Reading List (1, 6, 6) && KFX metadata reader (from KFX Input) (1, 11, 0) && KFX Input (1, 11, 0)
calibre 3.35  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14.2', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 11, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 11, 0) && Count Pages (1, 8, 2) && Wikidata (1, 2, 0) && Barnes & Noble (1, 2, 15) && Goodreads (1, 3, 0) && Fantastic Fiction (1, 3, 0) && Resize Cover (1, 0, 2) && Hyphenate This! (0, 0, 8) && NormComment (0, 0, 3) && Kobo Books (1, 4, 0) && Search The Internet (1, 7, 6) && Reading List (1, 6, 6) && KFX metadata reader (from KFX Input) (1, 11, 0) && KFX Input (1, 11, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 103.000001547 x 103.000001547
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[1.48] main UI initialized...
[1.48] Started up in 1.48 seconds with 2433 books
2018-12-19 18:56:30.110 Calibre[705:122520] deliverNotificationWithTitle()
* Notification delivered.
Traceback (most recent call last):
  File "site-packages/calibre/devices/kindle/driver.py", line 503, in delete_single_book
  File "site-packages/calibre/devices/kindle/driver.py", line 480, in thumbpath_from_filepath
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 284, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 312, in identity
MobiError: Unknown book type: Åƒﬁùå#
2018-12-19 18:56:44.083 Calibre[710:123616] deliverNotificationWithTitle()
* Notification delivered.
Gather KFX-ZIP (from KFX Input) 1.11.0: Importing /Volumes/Kindle/documents/Good Deeds and Bad Intentions_ A Bunny McGarry Short Story_B07LDX62GB.kfx
Gather KFX-ZIP (from KFX Input): Gathered 5 file(s) as /var/folders/jq/479cscrx4qsgscvd3jccrp500000gn/C/calibre_3.35.0_tmp_GfnYm0/lZS5ZK.kfx-zip
DeDRM v6.6.1: Trying to decrypt lZS5ZK.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: lZS5ZK
Found 2 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container Good Deeds and Bad Intentions_ A Bunny McGarry Short Story_B07LDX62GB.kfx has DRM and cannot be converted

{'bsd_drives': {'main': u'/dev/disk2s1'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/dev/disk1s1': '/',
               '/dev/disk1s4': '/private/var/vm',
               '/dev/disk2s1': '/Volumes/Kindle',
               'devfs': '/dev',
               'map -hosts': '/net',
               'map auto_home': '/home'}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
Job: 1 Get device information finished
No details available.
Job: 2 Set library information finished
No details available.
DEBUG:    2.7 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    2.9 USBMS: count found in cache: 680, count of files in metadata: 680, need_sync: False
DEBUG:    2.9 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    2.9 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    2.9 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 680
DeviceJob: set_books_in_library finished: time= 0.0283839702606
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
READING LIST: Metadata available: {'main': {u'calibre_version': u'3.35.0', u'last_library_uuid': None, u'location_code': 'main', u'device_name': u'Amazon Kindle', u'prefix': '/Volumes/Kindle/', u'device_store_uuid': u'745eb7a8-2bd4-4af0-9ecb-6ef5bb03ece2', u'date_last_connected': u'2018-12-19T18:56:30.031958+00:00'}}
READING LIST: Sync Now - force_sync= False
READING LIST: Device found to sync to: Amazon Kindle 745eb7a8-2bd4-4af0-9ecb-6ef5bb03ece2
READING LIST: Updating automatic column list(s)  [u'To Read']
READING LIST: Auto-populating search list:  To Read
READING LIST: Now 677 ids on automatic list: To Read
Job: 3 Get list of books on device finished
No details available.
READING LIST: No books on 'To Read' list need to be synced
DeviceJob: 3 Get list of books on device callback returned
Job: 4 Delete books from device started
DEBUG:   13.8 USBMS: deleting 1 books
DEBUG:   13.9 USBMS: finished deleting 1 books
DeviceJob: 4 Delete books from device done, calling callback
DEBUG:   13.9 USBMS: removing metadata for 1 books
DEBUG:   13.9 USBMS: finished removing metadata for 1 books
DeviceJob: set_books_in_library: books to process= 679
DeviceJob: set_books_in_library finished: time= 0.1138920784
DeviceJob: 4 Delete books from device callback returned
Job: 5 Send metadata to device started
DEBUG:   14.2 USBMS: starting sync_booklists
Job: 4 Delete books from device finished
No details available.
Job: 3 Get list of books on device finished
No details available.
DEBUG:   27.0 USBMS: finished sync_booklists
DeviceJob: 5 Send metadata to device done, calling callback
DeviceJob: 5 Send metadata to device callback returned
Job: 6 Prepare files for transfer from device started
DeviceJob: 6 Prepare files for transfer from device done, calling callback
DeviceJob: 6 Prepare files for transfer from device callback returned
Added Good Deeds and Bad Intentions: A Bunny McGarry Short Story to db in: 0.0
Added 1 books in 0.9 seconds
DeviceJob: set_books_in_library: books to process= 679
Job: 5 Send metadata to device finished
No details available.
Job: 6 Prepare files for transfer from device finished
No details available.
Package KFX (from KFX Input) 1.11.0: Packaging /var/folders/jq/479cscrx4qsgscvd3jccrp500000gn/C/calibre_3.35.0_tmp_GfnYm0/lZS5ZK.kfx-zip
Processing container: CR!QH6PD4HSFH5F33134ZQH8P48FW4K.kfx
Processing container: CR!VCMPKSZMHH6J7E43SM53F49ZMVNS.kfx
Processing container: Good Deeds and Bad Intentions_ A Bunny McGarry Short Story_B07LDX62GB.kfx
KFX metadata reader (from KFX Input) activated for /var/folders/jq/479cscrx4qsgscvd3jccrp500000gn/C/calibre_3.35.0_tmp_GfnYm0/FcFLvY_add_books/0/Good Deeds and Bad Intentions_ A Bunny McGarry Short Story_B07LDX62GB.kfx-zip
DeviceJob: set_books_in_library finished: time= 0.0757269859314

**Comment by j-howell** [comment]
It looks like you are importing from a Kindle device.

Did you enter the Kindle's serial number into the plugin configuration?

What firmware is your kindle running? DeDRM will not work with firmware version 5.10.2.

**Comment by theengineerman** [comment]
Ha, thank you. Yes, I did enter the Kindle serial number, but my kindle firmware version is 5.10.2  
Do you feel that future versions may work?

**Comment by j-howell** [comment]
If someone comes up with a solution then it will likely be added to these tools. I have no way to tell if or when that might happen.

In the mean time see this thread on MobileRead for ways to avoid or work around KFX: [Dealing with Kindle for PC/Mac 1.19 (and later) and KFX in calibre](https://www.mobileread.com/forums/showthread.php?t=283371)

**Comment by theengineerman** [comment]
Thank you.
