### ISSUE TITLE
DeDrm + Calibre fails to decrypt Kindle DX .azw files

### ISSUE THREAD

**Issue by daveman** [apprenticeharper/DeDRM_tools#709]
I'm totally new to this so I'm probably missing something. Here's as much detail as I can give regarding what seems to be happening. Thanks in advance!

Import into Calibre indicates successful decryption but can't view or convert the "decrypted" file to .mobi without getting the "Cannot convert. This book is locked by DRM." message.
Running Calibre on Ubuntu 16.04 with latest DeDRM plugin.

Exactly the same chain of errors was produced on multiple books regardless of whether the .azw file was obtained by copying it from the Kindle DX or by using the Amazon web-based app's "Manage Your Content and Devices" page to download the Kindle DX .azw file using the "Download and Transfer Via USB" option with the DX as the selected device.

Output of apparently successful initial import:
Gather KFX-ZIP (from KFX Input) 1.12.0: Importing /home/dave/Documents/Calibre_DeDrm_Temp/Beyond The E-Myth_ The Evolution of an Enterprise_ From a Company of One to a Company of 1,000!.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt Beyond The E-Myth_ The Evolution of an Enterprise_ From a Company of One to a Company of 1,000!.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Beyond The E-Myth: The Evolution of an Enterprise: From a Company of One to a Company of 1,000!
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
File is encoded with PID iQZvbscbFN.
Decrypting. Please wait . . . done
Decryption succeeded after 0.0 seconds
DeDRM v6.6.1: Finished after 0.0 seconds
Added Beyond The E-Myth: The Evolution of an Enterprise: From a Company of One to a Company of 1,000! to db in: 1.7
Added 1 books in 2.7 seconds

------------------------------
Output of attempt to convert to .mobi:
Worker Launch took: 0.0938541889191
Job: 6 Convert book 1 of 1 (Beyond The E-Myth: The Evolution of an Enterprise: From a Company of One to a Company of 1,000!) finished
Convert book 1 of 1 (Beyond The E-Myth: The Evolution of an Enterprise: From a Company of One to a Company of 1,000!)
	Resolved conversion options
	calibre version: 2.55.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/tmp/calibre_2.55.0_tmp_ZU0y8z/RzuMh4.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f438324d3d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x7f438324da90>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/tmp/calibre_2.55.0_tmp_ZU0y8z/GxJBBf.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /tmp/calibre_2.55.0_tmp_ZU0y8z/YEf6aS.azw
	Traceback (most recent call last):
	  File "/usr/bin/calibre-parallel", line 20, in <module>
	    sys.exit(main())
	  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 190, in main
	    result = func(*args, **kwargs)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 31, in gui_convert_override
	    override_input_metadata=True)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	    plumber.run()
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1057, in run
	    accelerators, tdir)
	  File "/usr/lib/calibre/calibre/customize/conversion.py", line 241, in __call__
	    log, accelerators)
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/mobi_input.py", line 35, in convert
	    mr.extract_content(u'.', parse_cache)
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 148, in extract_content
	    self.check_for_drm()
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 144, in check_for_drm
	    raise DRMError(name)
	calibre.ebooks.DRMError: Beyond The E-Myth: The Evolution of an Enterprise: From a Company of One to a Company of 1,000!

**Comment by ElleKayEm** [comment]
That definitely looks like DRM is removed successfully.  I would think the file is already in mobi format.  Pretty sure the DX doesn't support anything newer -- even KF8, let alone KFX.  What file extension does it have once it's imported into calibre?

**Comment by daveman** [comment]
The imported file has a .azw extension but Calibre won't view it. If I just try to open it after importing it in Calibre, the Calibre E-book viewer window displays the "Loading ebook..." spinner but then pops up the dialog with "This book is locked by DRM. To learn more about DRM and why you cannot read or convert this book in calibre, click here."
If I start Calibre with "calibre-debug -g" the only output I get in the console when I try to view the file (and get the error above) is "Worker Launch took: 0.0919539928436"

**Comment by daveman** [comment]
Doh! I was using the Calibre 2.55 package from the Ubuntu repos. Checked the Calibre website and saw that the current release is 3.36.0 along with this message "Please do not use your distribution provided calibre package, as those are often buggy/outdated."

Everything's working great after upgrading to 3.36.0! Thank you so much pointing me in the right direction. Sorry to have taken your time.

**Comment by ElleKayEm** [comment]
No problem!  You can close the issue if you're all set.

**Comment by daveman** [comment]
Closing as fixed in newer version.
