### ISSUE TITLE
Impossible to de-DRM Kindle azw3

### ISSUE THREAD

**Issue by infomast** [apprenticeharper/DeDRM_tools#710]
Hi,
I'm trying to de-DRM an ebook someone gave me, with his Kindle ID. I added the Kindle ID in Calibre plugin configuration "eInk Kindle ebooks", but it doesn't work.
Thanks for your help.
[log_calibre.txt](https://github.com/apprenticeharper/DeDRM_tools/files/2702871/log_calibre.txt)

**Comment by ElleKayEm** [comment]
You have the wrong serial number, you haven't entered it correctly, or its not an E-ink Kindle ebook.

**Comment by infomast** [comment]
I double checked the seril number, and it's a azw3 downloaded from Amazon.

**Comment by ElleKayEm** [comment]
Then it's probably not for an E-ink Kindle.

**Comment by infomast** [comment]
Thank you.
