### ISSUE TITLE
DeDRM 6.6.1 not working with Calibre 3.12 on Windows 10 64-bit

### ISSUE THREAD

**Issue by incantata** [apprenticeharper/DeDRM_tools#713]
The DeDRM plugin installs successfully in Calibre 3.12 but when I import an .azw Kindle file from 2015 and try to convert it, I get a message that it is still DRM protected.  It cannot therefore be converted.  Suggestions?

Here is the solution that works:
To convert Kindle KX files in Calibre
1.	 Install Calibre plugin 6.6.1
2.	Uninstall and unregister Kindle for PC
3.	Delete or rename old My Kindle Content
4.	Create new empty folder under Documents\My Kindle Content
5.	Deregister your Kindle for PC or device
6.	Go offline – close internet connection
7.	Install Kindle for PC version 1.24 (you CANNOT USE KINDLE 1.25)
IMMEDIATELY UNCHECK ‘TOOLS’ ‘OPTIONS’ ‘AUTOMATIC UPDATE’
8.	Run cmd and enter:
ren %localappdata%\Amazon\Kindle\application\renderer-test.exe renderer-test.xxx

9.	Download your Kindle library into the new, empty ‘My Kindle Content’
10.	Add the new *.azw files in Calibre and convert them

**Comment by ElleKayEm** [comment]
Make sure you have Kindle for PC version 1.24 or earlier.

**Comment by incantata** [comment]
I installed Kindle for PC 1.24 and downloaded the .azw books on USB as single files.  Then I tried again to convert them, no luck.  still does not work.

**Comment by ElleKayEm** [comment]
Post a log of the attempt with a book downloaded with version 1.24.

**Comment by incantata** [comment]
Here is a successful log after following the above 10 steps.

calibre Debug log
calibre 3.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Using calibre Qt style: True
Starting up...
Loaded cached store plugin for: Publio at version: 9
Loaded cached store plugin for: Mills and Boon UK at version: 4
Loaded cached store plugin for: Beam EBooks DE at version: 4
Loaded cached store plugin for: Woblink at version: 14
Loaded cached store plugin for: Legimi at version: 9
Loaded cached store plugin for: Empik at version: 8
Loaded cached store plugin for: ebook.de at version: 5
Started up in 10.89 seconds with 6 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xdd'p\x10h\x99\xe8\xdc\xd2\x8cbR\x80\xc4\xf6\x98t\xd1\x13\xe0W\xbd\xd0B(\x01o\xaa\xd1\xa4\x95o", 'C:\\Users\\coset\\Documents\\My Kindle Content\\B072L4DSDC_EBOK\\B072L4DSDC_EBOK.azw']
DeDRM v6.6.1: Trying to decrypt B072L4DSDC_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Dirty Genes
Got DSN key from database default_key
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
File is encoded with PID DQpunFUgN2.
Decrypting. Please wait . . . . . . done
Decryption succeeded after 2.9 seconds
DeDRM v6.6.1: Finished after 2.9 seconds
Added Dirty Genes to db in: 0.6
Added 1 books in 5.9 seconds

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
