### ISSUE TITLE
No available solutions for DeDRM 6.6.1 Nook

### ISSUE THREAD

**Issue by alarajrogers** [apprenticeharper/DeDRM_tools#716]
Nook for PC no longer seems to allow the download of files at all; it gives an error message that B+N says means your Nook needs to be upgraded to support TLS 1.2, but of course they are no longer supporting Nook for PC. So I can't get files via that method, and the files acquired with the Windows app do not decrypt. Does anyone have a workaround that can force Nook for PC to download books, or advice for how to get the Greasemonkey script that's supposed to allow you to download your books directly from B+N?

**Comment by ElleKayEm** [comment]
Enable TLS 1.2 in Internet Explorer and Nook for PC should work.

See this post at MobileRead:

https://www.mobileread.com/forums/showpost.php?p=3728361&postcount=1420

**Comment by alarajrogers** [comment]
Thanks. The enabling TLS 1.2 didn't work since mine was already enabled, but the link you provided also gives information on how to get Nook Study to work, and _that_ did the trick. Nook Study seems to be compatible with the DeDRM tools.

**Comment by ElleKayEm** [comment]
I'm still able to use Nook for PC, but I know others have trouble.
