### ISSUE TITLE
Removing DRM from a Kindle Textbook

### ISSUE THREAD

**Issue by Natwii** [apprenticeharper/DeDRM_tools#718]
Hi, I am really hoping that someone can help me out.

I am trying to remove the DRM from a textbook I bought in Amazon Kindle.
I have (I think) installed the deDRM Calibre plugin, it imports the book, but doesn't remove the DRM. 
Here's a log. 

calibre Debug log
calibre 3.36  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.12+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 0) && KindleUnpack - The Plugin (0, 81, 5) && KFX metadata reader (from KFX Input) (1, 12, 0) && KFX Input (1, 12, 0)
calibre 3.36  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.12+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 0) && KindleUnpack - The Plugin (0, 81, 5) && KFX metadata reader (from KFX Input) (1, 12, 0) && KFX Input (1, 12, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.341232227 x 108.085106383
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[3.86] main UI initialized...
[3.86] Hiding splash screen
[39.62] splash screen hidden
[39.62] Started up in 39.62 seconds with 134 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xc6.K\xcb{\x96T2\x86\x88R\xb6\x07/\x92\xf9\xf1T\xd8\xaaR\xdd\x0f\xba\x7fQ\x86\xf2\x18%\x98m', 'C:\\Users\\nkinn\\OneDrive\\Documents\\My Kindle Content\\B00XN47ROM_EBOK\\B00XN47ROM_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.12.0: Importing C:\Users\nkinn\OneDrive\Documents\My Kindle Content\B00XN47ROM_EBOK\B00XN47ROM_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt B00XN47ROM_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Biology: A Global Approach, Global Edition
Found 0 keys to try after 2.8 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 2.8 seconds
searching for kinfoFiles in C:\Users\nkinn\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 3.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 3.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Biology: A Global Approach, Global Edition to db in: 2.3
Added 1 books in 8.5 seconds
Worker Launch took: 0.384000062943

Thanks, Natwii

**Comment by ElleKayEm** [comment]
Use Kindle for PC version 1.24 or earlier.  And it needs to be on the same machine and user as calibre.

**Comment by Natwii** [comment]
> Use Kindle for PC version 1.24 or earlier. And it needs to be on the same machine and user as calibre.

Where can I find 1.24 of earlier? & does it matter how much earlier it is? I found a 1.17 version ...

**Comment by Natwii** [comment]
I’ve installed Kindle 1.17, but now it won’t even upload the book, it’s just stuck on 0% ...


________________________________

**Comment by Natwii** [comment]
Now using 1.24 and 64-bit Calibre but nothing, it's just stuck on 0% :/ Honestly I just want to have the book on my own kindle account rather than my partners (I paid for it) This is so frustrating.

**Comment by Natwii** [comment]
So I ended up using a program called Epubsoft (30 day free trial) to remove the DRM from the kindle textbooks (AZW4) then uploaded them into Calibre and used Kindle Unpack Calibre Plugin to convert to PDF.

**Comment by ElleKayEm** [comment]
Probably just needed more time.  That program is based on these tools.

**Comment by Natwii** [comment]
Fair enough, I’m just not very patient unless I can see things working! Thanks for your help anyway

________________________________

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
