### ISSUE TITLE
kindle.account.tokens Key Not Found in .kinf2011 File from KindlePC 1.14.0

### ISSUE THREAD

**Issue by mvastola** [apprenticeharper/DeDRM_tools#72]
The routine in the `kindlekey.pyw` script to parse my `.kinf2011` file is failing for me because [this](https://github.com/apprenticeharper/DeDRM_tools/blob/e729ae890406c5bd13e3c8f9e36a5edc6c289640/Other_Tools/DRM_Key_Scripts/Kindle_for_Mac_and_PC/kindlekey.pyw#L1163) conditional is always evaluating to false. 

Suggestions welcome.

(I'm also happy to provide my `.kinf2011` file privately to the author for debugging purposes.)

**Comment by apprenticeharper** [comment]
Keep a copy of the .kinf2011, but your quickest solution will be to unregister, wipe (including prefs and the .kinf2011 file) and then reinstall and re-register.

**Comment by mvastola** [comment]
Sorry for the delay, but this worked. No idea why Kindle made it necessary though.
