### ISSUE TITLE
NOT FINDING KEY

### ISSUE THREAD

**Issue by ordchamp** [apprenticeharper/DeDRM_tools#724]
I'm running ver 1.16 od Kindle for PC under playonlinux on Gentoo linux.

I've used calibre and your plugins for years now and usually have been able to figure out my problem but this one has me stumped.

I've un-regestered and reregistered several times to no avail.

Uninstalled and reinstalled, no luck.

Any suggestions?

Here's latest attempt:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 3.26.1  embedded-python: False is64bit: True
Linux-4.14.83-gentoo-x86_64-AMD_FX-tm-8350_Eight-Core_Processor-with-gentoo-2.6 Linux ('64bit', 'ELF')
('Linux', '4.14.83-gentoo', '#1 SMP Sun Dec 30 02:32:07 EST 2018')
Python 2.7.15
Linux: ('Gentoo Base System', '2.6', '')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.26.1  embedded-python: False is64bit: True
Linux-4.14.83-gentoo-x86_64-AMD_FX-tm-8350_Eight-Core_Processor-with-gentoo-2.6 Linux ('64bit', 'ELF')
('Linux', '4.14.83-gentoo', '#1 SMP Sun Dec 30 02:32:07 EST 2018')
Python 2.7.15
Linux: ('Gentoo Base System', '2.6', '')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 100.0 x 100.0
physicalDpi: 63.8628571429 x 64.4769230769
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.10] db initialized
[0.10] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[1.71] main UI initialized...
[1.71] Hiding splash screen
DeDRM v6.6.1: Trying to decrypt B07J9PG9JP_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Cataclysm: V Plague Book 18
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.6.1: Running kindlekey.py under Wine
DeDRM v6.6.1: Command line: 'WINEPREFIX="/home/mike" wine python.exe "/home/mike/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/mike/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
wine: cannot find L"C:\\windows\\system32\\python.exe"
DeDRM v6.6.1: Found and decrypted 0 key files
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 171, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[3.84] splash screen hidden
[3.84] Started up in 3.84 seconds with 685 books
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Added Cataclysm: V Plague Book 18 to db in: 1.1
Added 1 books in 2.3 seconds
Worker Launch took: 0.094691991806
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'

Thanks in advance!

**Comment by ElleKayEm** [comment]
Here's the problem:

wine: cannot find L"C:\windows\system32\python.exe"

Do you have Python and PyCrypto installed under Wine?

Alternatively you could temporarily install Windows calibre with DeDRM, save the key, and import it into Linux calibre.

**Comment by ordchamp** [comment]
I have python and pycrypto installed in linux and python installed under wine config but I find no pycryto to install in wine config.

I do have a working windows setup but I can't find and .k4i files in there but I know it works to decrypt my books, I've been using it for months now since my linux installed started giving me problems. 

Now I have linux working again with a new install and am trying to move back to it fulltime.

So where do I find the files in the windows install to import?

**Comment by ElleKayEm** [comment]
Go into the Kindle for PC section of the plugin customization and hit the save button.

**Comment by ordchamp** [comment]
I saved the key from a working windows install, imported it into the linux/wine install and drm still failing.

Not sure why it's looking for python under wine on the C: drive since I'm running the linux version of the software and python is installed in my system.

Here's the latest:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 3.26.1  embedded-python: False is64bit: True
Linux-4.14.83-gentoo-x86_64-AMD_FX-tm-8350_Eight-Core_Processor-with-gentoo-2.6 Linux ('64bit', 'ELF')
('Linux', '4.14.83-gentoo', '#1 SMP Sun Dec 30 02:32:07 EST 2018')
Python 2.7.15
Linux: ('Gentoo Base System', '2.6', '')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.26.1  embedded-python: False is64bit: True
Linux-4.14.83-gentoo-x86_64-AMD_FX-tm-8350_Eight-Core_Processor-with-gentoo-2.6 Linux ('64bit', 'ELF')
('Linux', '4.14.83-gentoo', '#1 SMP Sun Dec 30 02:32:07 EST 2018')
Python 2.7.15
Linux: ('Gentoo Base System', '2.6', '')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 53.9903381643 x 53.9613733906
physicalDpi: 63.8628571429 x 64.4769230769
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[1.50] main UI initialized...
[1.50] Hiding splash screen
DeDRM v6.6.1: Trying to decrypt B07J9PG9JP_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Cataclysm: V Plague Book 18
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.6.1: Running kindlekey.py under Wine
DeDRM v6.6.1: Command line: 'WINEPREFIX="/home/mike" wine python.exe "/home/mike/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/mike/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
[4.52] splash screen hidden
[4.52] Started up in 4.52 seconds with 685 books
wine: cannot find L"C:\\windows\\system32\\python.exe"
DeDRM v6.6.1: Found and decrypted 0 key files
DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 171, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Added Cataclysm: V Plague Book 18 to db in: 1.4
Added 1 books in 2.9 seconds
Worker Launch took: 0.0830190181732
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mike'

**Comment by ElleKayEm** [comment]
Were the books from the same installation of Kindle for PC?  Each one has its own key, even for the same Amazon account.

If you don't have the right key for the book you're trying to decrypt in the Linux calibre/DeDRM, it tries to run the key script under Wine to get it.  That's why it's looking for Python there.

But if you install calibre under Wine, you should be able to retrieve the key without needing Python and PyCrypto under Wine.  It will use calibre's built-in Python.  Import that key into Linux.  Then you can delete the calibre under Wine if you want.

**Comment by ordchamp** [comment]
So I'm going to have to do this for every book now? I thought the key was to decrypt ALL books.

So basically this is not going to work under the linux version. I sure thought in the past I had done that with no issues.

**Comment by ordchamp** [comment]
I only saw one key in the windows version that I've been using. Default_key

So if what you say is true why were there not many, many keys as I know I have decrypted as many as 200 books this last year as they were brought into calibre.

**Comment by j-howell** [comment]
There is one key per installion of the Kindle for PC software, not one per book. You need to make sure that the key associated with the K4PC installation that downloaded the book is present in the configuration of the DeDRM software you are using to decrypt it.

**Comment by ElleKayEm** [comment]
Oh, sorry, I wasn't clear.  As j-howell said, by "each one", I meant each Kindle app, not each book.  So you'd just need the one key for the app where you plan to download your books.  Same key would work for all the books downloaded to that app.  Unless you reinstall or unregister, the key remains the same.

**Comment by ordchamp** [comment]
So, in that case I just need to remove and redownload the book with the key installed.  Correct?

**Comment by ElleKayEm** [comment]
Yes.  As long as the key is for K4PC where the book was downloaded.

**Comment by ordchamp** [comment]
Do I need to place the key anywhere in kindle or just in calibre drm

**Comment by ElleKayEm** [comment]
Just in the plugin.

**Comment by ordchamp** [comment]
Just tried and same results as last above debug log.

So evidently the kindle version I'm running under wine is not using the same key as the one I installed into calibre. How do I change that?

**Comment by ordchamp** [comment]
How do I get the key out of the installation of Kindle I'm now running? That's the issue I believe.

**Comment by ElleKayEm** [comment]
Easiest way I think is to install calibre with DeDRM under Wine.  Add a book from K4PC under Wine.  If the book is successfully decrypted, you'll have the correct key in the plugin customization.  Save that key and import it into your Linux calibre/DeDRM.  Then you should be able to take books directly from K4PC under Wine to Linux calibre.  If all goes well, then you can uninstall calibre under Wine.

**Comment by ordchamp** [comment]
no luck with calibre under wine either. Even tried importing the default key from my windows install and still failed.

**Comment by ordchamp** [comment]
finally got it... I had to install the caliber into the same wine virtual drive I had kindle installed into so at least it's working under wine.   now I'll try exporting the key and importing it into the linux calibre install.

**Comment by ordchamp** [comment]
Success there too now...Thank you for your help and quick response.

All is working as I intend. Kindle under wine and Calibre directly in linux.

**Comment by ElleKayEm** [comment]
That's what I've been saying, books and key must be from the same installation of Kindle for PC.  If you're all set, you can close the issue.
