### ISSUE TITLE
DRM version Not Working with CAlibre 64bit PC

### ISSUE THREAD

**Issue by mayaxtechnology** [apprenticeharper/DeDRM_tools#726]
I need help on this, I have been up all thorugh the night looking for solution to this.
I have downloaded the previous releases of the versions of DRM and Calibre.

I have tried all combinations but nothing has worked. Kindly check my log

---------------------------------------------------------------------------------------------------------------
calibre Debug log
calibre 3.37 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
calibre 3.37 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[4.70] main UI initialized...
[4.70] Hiding splash screen
[5.84] splash screen hidden
[5.84] Started up in 5.84 seconds with 1 books
Worker Launch took: 1.38999986649
Job: 1 Convert book 1 of 1 (B078T8MWPY_EBOK) finished
Convert book 1 of 1 (B078T8MWPY_EBOK)
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\KUNGFU~1\\AppData\\Local\\Temp\\calibre_h453pu\\gg8xfs.opf'
	  cover: u'C:\\Users\\KUNGFU~1\\AppData\\Local\\Temp\\calibre_h453pu\\ohhrlt.jpeg'
	  output_profile: 'generic_eink'
	Resolved conversion options
	calibre version: 3.37.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\KUNGFU~1\\AppData\\Local\\Temp\\calibre_h453pu\\ohhrlt.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000238F3315470>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x00000238F33157F0>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\KUNGFU~1\\AppData\\Local\\Temp\\calibre_h453pu\\gg8xfs.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\KUNGFU~1\AppData\Local\Temp\calibre_h453pu\nvbnct.kfx-zip
	Software versions: KFX Input 1.12.1, calibre 3.37 [64bit], Windows-10-10.0.14393-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\KUNGFU~1\AppData\Local\Temp\calibre_h453pu\nvbnct.kfx-zip
	Processing container: B078T8MWPY_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 102, in convert
	  File "calibre_plugins.kfx_input.__init__", line 204, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 96, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
	KFXDRMError: Book container B078T8MWPY_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	calibre.ebooks.DRMError: This book has DRM!

------------------------------------------------------------------------------------------------------------

From what I read, I am not sure the DRM plugin worked even if it was intialized

**Comment by j-howell** [comment]
That is a log from conversion. DRM removal happens when the book is first imported into calibre. See "[I cannot solve my problem with the DeDRM plugin, and now I need to ‘post a log’. How do I do that?](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that)" in the FAQ.

For books in KFX format (as yours is) this will only work on books obtained using certain apps/devices: Kindle for PC/Mac versions before 1.25 and e-ink kindle firmware before version 5.10.2. It will not work on books from the Kindle apps on Fire, iOS or Android devices.

**Comment by mayaxtechnology** [comment]
Thank you for the direction. I have gotten the correct log for DRM.
-I used an kindle 1.24 PC
-My files are voucher, awz. awz.md, awz.res, awz.res, .phl

Here is the log 
-----------------------------------------------------------------------------------------------------------------

calibre Debug log
calibre 3.37 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
calibre 3.37 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.31] splash screen shown
[0.31] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[3.99] main UI initialized...
[3.99] Hiding splash screen
[5.91] splash screen hidden
[5.91] Started up in 5.91 seconds with 0 books
Gather KFX-ZIP (from KFX Input) 1.12.1: Importing C:/Users/KUNGFU PANDA/Desktop/B078T8MWPY_EBOK/B078T8MWPY_EBOK/B078T8MWPY_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 5 file(s) as C:\Users\KUNGFU~1\AppData\Local\Temp\calibre_qhgadn\usyewk.kfx-zip
DeDRM v6.6.1: Trying to decrypt usyewk.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: usyewk
Found 0 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.a976dd39-8ba5-4c92-8c86-49cba6beb267.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\KUNGFU PANDA\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.12.1: Packaging C:\Users\KUNGFU~1\AppData\Local\Temp\calibre_qhgadn\usyewk.kfx-zip
Processing container: B078T8MWPY_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container B078T8MWPY_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\KUNGFU~1\AppData\Local\Temp\calibre_qhgadn\lc8eeo_add_books\0\B078T8MWPY_EBOK.kfx-zip
Added Archangels of Magick: Rituals for Prosperity, Healing, Love, Wisdom, Divination and Success to db in: 0.5
Added 1 books in 5.1 seconds

-------------------------------------------------------------------------------------------------------------------


Kindly check again what the problem is.

**Comment by j-howell** [comment]
> No K4PC kindle.info/kinf/kinf2011 files have been found.

It looks like the book you are trying to import was not downloaded by Kindle for PC installed for the current user on that PC. DeDRM needs access to data from that installation.

**Comment by ElleKayEm** [comment]
If Kindle for PC is on the same computer and user, then it must have updated to 1.25.  Be sure to uncheck the setting for auto-updates.

**Comment by j-howell** [comment]
> I transferred the files to to another computer because I could not use Calibre on that system.

That is not going to work.

You could instead run Kindle for PC on the system that is running calibre and use that to download your books.

Or you can try to run the kindle key extraction program (kindlekey) on the system with Kindle for PC. I am not familiar with the details of how to make that work.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by mayaxtechnology** [comment]
Yes thanks the creator of this plugin. I had to use another system to run it. 
Thanks guys again.
