### ISSUE TITLE
cant remove DRM from kindle book

### ISSUE THREAD

**Issue by mepm87** [apprenticeharper/DeDRM_tools#727]
Hi! cant seem to be able to remove my drm. Followed every step, DDRM tools 6.6.1, KFX input, adding my kindle serial number to calibre.

Heres Calibres log
calibre Registro de depuración
calibre 3.37  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.12+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && Kindle Collections (1, 7, 23) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1) && Set KFX metadata (from KFX Output) (1, 26, 0) && KFX Output (1, 26, 0)
calibre 3.37  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.12+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && Kindle Collections (1, 7, 23) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1) && Set KFX metadata (from KFX Output) (1, 26, 0) && KFX Output (1, 26, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[3.17] main UI initialized...
[3.17] Hiding splash screen
[11.67] splash screen hidden
[11.67] Started up in 11.67 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['@\xac\xcd\x9f\xfa\x87>pLO\xd9\x82}6\xfd\xdc\xf3.\x05\x97dU\x1e\xeeIG=$\xf1!4\xee', "C:\\Users\\Euge\\Downloads\\Donal's Meals in Minutes_ 90 suppers from scratch_15 minutes prep (2).azw3"]
DeDRM v6.6.1: Trying to decrypt Donal's Meals in Minutes_ 90 suppers from scratch_15 minutes prep (2).azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Donal's Meals in Minutes: 90 suppers from scratch/15 minutes prep
Found 2 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\Euge\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Donal's Meals in Minutes: 90 suppers from scratch/15 minutes prep to db in: 2.0
Added 1 books in 5.6 seconds
Worker Launch took: 0.651999950409
Job: 1 Convertido el libro 1 de 1 (Donal's Meals in Minutes: 90 suppers from scratch/15 minutes prep) finished
Convertido el libro 1 de 1 (Donal's Meals in Minutes: 90 suppers from scratch/15 minutes prep)
	C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\Euge\\AppData\\Local\\Temp\\calibre_wrc_i6\\wasjbr.opf'
	  cover: u'C:\\Users\\Euge\\AppData\\Local\\Temp\\calibre_wrc_i6\\8hz39_.jpeg'
	  output_profile: 'kindle_fire'
	Resolved conversion options
	calibre version: 3.37.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Euge\\AppData\\Local\\Temp\\calibre_wrc_i6\\8hz39_.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x041F41F0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x041F4590>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Euge\\AppData\\Local\\Temp\\calibre_wrc_i6\\wasjbr.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Euge\AppData\Local\Temp\calibre_wrc_i6\_q4397.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Donal's Meals in Minutes: 90 suppers from scratch/15 minutes prep (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 45, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Donal's Meals in Minutes: 90 suppers from scratch/15 minutes prep

THanks!

**Comment by ElleKayEm** [comment]
Looks like a book downloaded from the website.  You need to choose an E-ink Kindle (not a Fire) for the device and enter its serial number into the plugin customization.

**Comment by mepm87** [comment]
But all I got is a fire. Is there any way around this?

**Comment by ElleKayEm** [comment]
Download it with Kindle for PC.  Be sure to use version 1.24 or earlier.  Here's a post about the various ways to get Kindle files with a link for 1.24 at the bottom.

**Comment by mepm87** [comment]
Thanks, that did the trick! ;)
