### ISSUE TITLE
Can't remove DRM after using suggestions in other threads.

### ISSUE THREAD

**Issue by raroberts36** [apprenticeharper/DeDRM_tools#729]
Good morning. I have tried numerous times to remove DRM from Kindle books in Calibre but it keeps saying I cannot remove DRM. I have tried everything I can find so far on here. I have installed an older version of Kindle for PC, installed the DRM_Plugin and I am logged into my own account on this computer prior to downloading file from Kindle. When adding the book to Calibre it now shows me the name of the book rather than "unknown" but still won't convert. Any help would be appreciated. Thank you.

![capture](https://user-images.githubusercontent.com/46464147/50799399-8fe03a80-1327-11e9-8ae5-a9c0bfad6d28.JPG)

Here is the log:

calibre Debug log
calibre 3.34  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5) && Package KFX (from KFX Input) (1, 12, 1) && Obok DeDRM (6, 5, 4) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
calibre 3.34  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5) && Package KFX (from KFX Input) (1, 12, 1) && Obok DeDRM (6, 5, 4) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.238993711 x 102.358208955
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.58] main UI initialized...
[1.58] Hiding splash screen
[20.91] splash screen hidden
[20.91] Started up in 20.91 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['[\x92\xd7\xd0\x1f\xd1\x08S\x84\x9d\xcf\xcce>\xce\x11/\x9a\xcc\x9b\x16D\xaa\x89*\x16\xb6?\x1a\xb9{\x14', 'C:\\Users\\user\\Documents\\My Kindle Content\\B07CWXXNNW_EBOK\\B07CWXXNNW_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.12.1: Importing C:\Users\user\Documents\My Kindle Content\B07CWXXNNW_EBOK\B07CWXXNNW_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\user\AppData\Local\Temp\calibre_9knyfi\uautrr.kfx-zip
DeDRM v6.6.1: Trying to decrypt uautrr.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: uautrr
Got DSN key from database default_key
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.add9b236-62d7-4196-aee7-4261d1f92c2d.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.1: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\user\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\user\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2282738602' and UserName '75736572'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: uautrr
Got DSN key from database default_key_1
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.add9b236-62d7-4196-aee7-4261d1f92c2d.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
 is not a valid Kindle serial number or PID.
K4MobiDeDRM: Calibre configuration directory = C:\Users\user\AppData\Roaming\calibre
Running file type plugin K4PC, K4Mac, Kindle Mobi and Topaz DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.k4mobidedrm.__init__", line 75, in run
  File "calibre_plugins.k4mobidedrm.mobidedrm", line 170, in __init__
DrmException: invalid file format
Package KFX (from KFX Input) 1.12.1: Packaging C:\Users\user\AppData\Local\Temp\calibre_9knyfi\uautrr.kfx-zip
Processing container: B07CWXXNNW_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container B07CWXXNNW_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\user\AppData\Local\Temp\calibre_9knyfi\clgm82_add_books\0\B07CWXXNNW_EBOK.kfx-zip
Added Bane (Sinners of Saint Book 5) to db in: 2.1
Added 1 books in 3.0 seconds

**Comment by j-howell** [comment]
From the log:

> DeDRM v6.6.1: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

**Comment by raroberts36** [comment]
Fantastic. Thank you for your quick reply. Very much appreciated.

**Comment by j-howell** [comment]
In Kindle Unlimited you are paying for access to a larger set of books that you can borrow. You only have access to those book as long as you continue to be part of KU. Authors in KU are paid by the number oof pages that you read within Kindle apps and devices. If you strip DRM and take the book elsewhere Amazon has you money, but the author doesn’t get paid.

**Comment by raroberts36** [comment]
Thank you. I didn't know that.
