### ISSUE TITLE
Cannot find key file on macOS

### ISSUE THREAD

**Issue by joegnis** [apprenticeharper/DeDRM_tools#732]
OS: macOS 10.14.2
Plugin version: 6.6.1
Kindle version: 1.25.2 (52077)

I downloaded a book from Kindle for Mac, tried importing it to Calibre, and it was unable to decrypt it. I checked plugin's configuration of "Kindle for Mac and PC files", and when I pushed the green plus button, it complained that "The default encryption key for Kindle for Mac/PC could not be found."

I read the debug log and found out the plugin was trying to find file "kindle-info/rainier/kinf2011". Then I tried to find the file by myself and ended up with `/Users/[username]/Library/Application Support/Kindle/storage/.kinf2018` only. Thus, I guess key file has changed in new versions of Kindle for Mac.

Debug log:
```
calibre Debug log
calibre 3.37  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14.2', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.37  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14.2', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000163 x 107.500001614
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.18] db initialized
[0.18] Constructing main UI...
[0.94] main UI initialized...
[0.94] Hiding splash screen
[0.98] splash screen hidden
[1.00] Started up in 1.00 seconds with 7 books
objc[7621]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa2f9d210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x112dfddc8). One of the two will be used. Which one is undefined.
DeDRM v6.6.1: Trying to decrypt B07LBBX8CD_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: MYBOOKNAME
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added MYBOOKNAME to db in: 0.0
Added 1 books in 0.5 seconds
```

**Comment by ElleKayEm** [comment]
Yes, you'll need to go back to a previous version of Kindle for Mac for these tools to work.  There's a link for the last working version at the bottom of the first post here:

https://www.mobileread.com/forums/showthread.php?t=283371

Be sure to uncheck the box for auto-updates even before uninstalling your current version.  Then make sure it is still unchecked when you get the older version installed.

**Comment by joegnis** [comment]
Thanks you for your prompt response. That's kinda what I expected. I installed version 1.17 and it works fine. If I am correct, this change of key file is quite new, because not long time ago I was able to decrypt my books from a latest version at that time. Hope this issue can help someonoe (like me who always wants to try latest version first).

**Comment by Angelo-Mascaro** [comment]
I have MACOs 10.15.7 Catalina and I cannot install version 1.17 of Kindle because it is 32 bit. Is there any other way to use the plugin with the new version of kindle? I can get the AZW3 files also with Kindle 1.30 but I don't know where is the key. 
I also got the serial number of my kindle ebook reader, but the books there are KFX format.

**Comment by ElleKayEm** [comment]
The plugin automatically finds the key for Kindle for Mac if it is on the same machine and user. If your Kindle is E-ink (not a Fire), then you can get azw3 format by going to your content & devices page at Amazon.  Select the "download & transfer via usb" option for the book and choose your Kindle when it asks which device.  Enter the serial number of the Kindle into the eink Kindle ebooks section of DeDRM's customization.

**Comment by auspex** [comment]
This is just so infuriating. I've _never_ had the plugin "automatically find the key". Probably it does when you don't use a specific Wine prefix, but I jump through hoops every time I install on a new system, and it always takes days to find the magic incantation of the month.

I am using 1.16 (the version Winetricks installs -- though I've tried 1.17, 1.30 and a few others) and it simply says "The default encryption key for Kindle for Mac/PC could not be found." whether or not I specify the correct prefix in the config

**Comment by ElleKayEm** [comment]
Yeah, retrieving keys automatically is a lot simpler when the key retrieval scripts can run on calibre's embedded Python as they do with Windows and Mac.
