### ISSUE TITLE
DeDRM app will not open on Mac (OSX 10.11.3 / DeDRM 6.3.6a)

### ISSUE THREAD

**Issue by chrubble** [apprenticeharper/DeDRM_tools#74]
Tried option + double-click, ctrl+click -> 'open', etc.

Error: The application "DeDRM" can't be opened.

(OSX 10.11.3 / DeDRM 6.3.6a)

<img width="630" alt="screen shot 2016-02-25 at 11 43 01" src="https://cloud.githubusercontent.com/assets/13031350/13318832/19663406-dbb5-11e5-8241-f50bf51f8c66.png">

**Comment by apprenticeharper** [comment]
Check your security settings.

**Comment by chrubble** [comment]
Any more details? I am already set to accept installs from unknown sources.

**Comment by motokochan** [comment]
It looks like a file permission issue. I'm not sure what exact files need execute set, but you can run the following command at the terminal to fix this:
`chmod -R u+x DeDRM.app`

**Comment by chrubble** [comment]
That worked perfectly - Thank you @motokochan

**Comment by Moscarda** [comment]
I was having this issue but it wasn't permissions related or security settings, I just had an older release from Mavericks or earlier and after I upgraded it worked fine.
