### ISSUE TITLE
Can't retrieve Nook Key

### ISSUE THREAD

**Issue by Vidioto** [apprenticeharper/DeDRM_tools#745]
When I try to generate a key in the customize plugin window I get an error message saying it could not be retrieved. After it didn't work the first time I tried logging into the barnes and noble site and found out that my old password was expired, so I changed the password and tried again. I've tried with the new password and I get the same error. I'm on calibre 3.38.1 and DeDRM 6.6.1. I also have the Nook Windows 10 app installed if that affects anything. Thanks in advance.
![calibre error](https://user-images.githubusercontent.com/46946152/51576019-9243a800-1e82-11e9-9a16-0b980ef2ad19.PNG)

**Comment by ElleKayEm** [comment]
Try installing Nookstudy.  DeDRM may be able to retrieve your key from its logs.  Here's a link to its setup file:

http://images.barnesandnoble.com/PResources/download/ereader2/sc/BN/pc/bndr_setup_2.1.2.28770.exe

**Comment by Vidioto** [comment]
So I tried downloading that and logging in, but all I get is a message saying "Internal Error: cannot find adobe ID".

**Comment by ElleKayEm** [comment]
Close the app before the login errors out.  Then reopen and you should be logged in anyway.

**Comment by Vidioto** [comment]
I did that and did get logged in. Is there anything I need to do to get the key from its logs (beyond customizing the plugin)?

**Comment by ElleKayEm** [comment]
Just download a book and import it into calibre with DeDRM.  As long as Nookstudy is on the same machine and user, it should retrieve the key.

**Comment by Vidioto** [comment]
That worked! Thank you so much for all the help!
