### ISSUE TITLE
Failed to remove kfx drm from kindle for pc

### ISSUE THREAD

**Issue by tascion** [apprenticeharper/DeDRM_tools#751]
Hello,
I'm hoping to get some help removing the DRM on an ebook I bought from Amazon and downloaded through the Kindle for PC program. I've included the debug log, but I'm not sure what other information might be helpful.

Thanks

calibre Debug log
calibre 3.38.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17242-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17242')
Python 2.7.15+
Windows: ('10', '10.0.17242', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1) && FanFicFare (3, 4, 0)
calibre 3.38.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17242-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17242')
Python 2.7.15+
Windows: ('10', '10.0.17242', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1) && FanFicFare (3, 4, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.7381489842 x 91.8072289157
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
FFF: DEBUG: 2019-01-27 11:30:23,075: calibre_plugins.fanficfare_plugin.fff_plugin(207): Plugin FanFicFare macmenuhack file_path:C:\Users\Primary\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[2.20] main UI initialized...
[2.20] Hiding splash screen
[14.94] splash screen hidden
[14.94] Started up in 14.94 seconds with 596 books

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 3606 '\x01\x00\x00\x00\x0c\x00\x00\x00\xc6\x07\x00\x001\x03\x1f\x00\xe1\x02\xd5\xdf\xa3#\xd3\x02\x04\x00\x00\x00\x00\x00\xcf\x02\x00\x001SPS\x05\xd5\xcd\xd5\x9c.\x1b\x10\x93\x97\x08\x00+,\xf9\xae\xfb\x01\x00\x00\x12\x00\x00\x00\x00A\x00u\x00t\x00o\x00L\x00i\x00s\x00t\x00\x00\x00B\x00\x00\x00\x1e\x00\x00\x00p\x00r\x00o\x00p\x004\x002\x009\x004\x009\x006\x007\x002\x009\x005\x00\x00\x00\x00\x00\xb2\x01\x00\x00\xae\xa5N8\xe1\xad\x8aN\x8a\x9b{\xeax\xff\xf1\xe9\x06\x00\x00\x80\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x80\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\xa2\x00\x14\x00\x1fDG\x1a\x03Yr?\xa7D\x89\xc5U\x95\xfek0\xee \x00\x00\x00\x1a\x00\xee\xbb\xfe#\x00\x00\x10\x00\xd3\xe2.\xf4\x9f\x90\x07I\x88qL"\xfc\x0b\xf7V\x00\x00l\x001\x00\x00\x00\x00\x00;N1x\x10\x00MYKIND~1\x00\x00T\x00\t\x00\x04\x00\xef\xberF\x85\x05;N1x.\x00\x00\x00;M\x01\x00\x00\x00*\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00PD\x9f' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 36888 '`\x00\x00\x00`\x00\x00\x000\x00\x00\x00Y\x00\x00\x00\x80\x0c\x05j\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragContext" 16 '\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 '\x01\x00\x00\x00' 

text/uri-list 94 'file:///C:/Users/Primary/Documents/My%20Kindle%20Content/B00QHMGPXQ_EBOK/B00QHMGPXQ_EBOK.azw\r\n' 

application/x-qt-windows-mime;value="FileName" 57 'C:\\Users\\Primary\\DOCUME~1\\MYKIND~1\\B00QHM~1\\B00QHM~1.AZW\x00' 

application/x-qt-windows-mime;value="FileContents" 0 '' 

application/x-qt-windows-mime;value="FileNameW" 162 'C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00t\x00a\x00s\x00c\x00i\x00o\x00n\x00\\\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00s\x00\\\x00M\x00y\x00 \x00K\x00i\x00n\x00d\x00l\x00e\x00 \x00C\x00o\x00n\x00t\x00e\x00n\x00t\x00\\\x00B\x000\x000\x00Q\x00H\x00M\x00G\x00P\x00X\x00Q\x00_\x00E\x00B\x00O\x00K\x00\\\x00B\x000\x000\x00Q\x00H\x00M\x00G\x00P\x00X\x00Q\x00_\x00E\x00B\x00O\x00K\x00.\x00a\x00z\x00w\x00\x00\x00' 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 '\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

Firefox rurl: None None
URLS: ['file:///C:/Users/Primary/Documents/My%20Kindle%20Content/B00QHMGPXQ_EBOK/B00QHMGPXQ_EBOK.azw']
Paths: [u'C:/Users/Primary/Documents/My Kindle Content/B00QHMGPXQ_EBOK/B00QHMGPXQ_EBOK.azw']
Extensions: frozenset([u'azw'])

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 3606 '\x01\x00\x00\x00\x0c\x00\x00\x00\xc6\x07\x00\x001\x03\x1f\x00\xe1\x02\xd5\xdf\xa3#\xd3\x02\x04\x00\x00\x00\x00\x00\xcf\x02\x00\x001SPS\x05\xd5\xcd\xd5\x9c.\x1b\x10\x93\x97\x08\x00+,\xf9\xae\xfb\x01\x00\x00\x12\x00\x00\x00\x00A\x00u\x00t\x00o\x00L\x00i\x00s\x00t\x00\x00\x00B\x00\x00\x00\x1e\x00\x00\x00p\x00r\x00o\x00p\x004\x002\x009\x004\x009\x006\x007\x002\x009\x005\x00\x00\x00\x00\x00\xb2\x01\x00\x00\xae\xa5N8\xe1\xad\x8aN\x8a\x9b{\xeax\xff\xf1\xe9\x06\x00\x00\x80\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x80\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\xa2\x00\x14\x00\x1fDG\x1a\x03Yr?\xa7D\x89\xc5U\x95\xfek0\xee \x00\x00\x00\x1a\x00\xee\xbb\xfe#\x00\x00\x10\x00\xd3\xe2.\xf4\x9f\x90\x07I\x88qL"\xfc\x0b\xf7V\x00\x00l\x001\x00\x00\x00\x00\x00;N1x\x10\x00MYKIND~1\x00\x00T\x00\t\x00\x04\x00\xef\xberF\x85\x05;N1x.\x00\x00\x00;M\x01\x00\x00\x00*\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00PD\x9f' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 36888 '`\x00\x00\x00`\x00\x00\x000\x00\x00\x00Y\x00\x00\x00\x80\x0c\x05j\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragContext" 16 '\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 '\x01\x00\x00\x00' 

text/uri-list 94 'file:///C:/Users/Primary/Documents/My%20Kindle%20Content/B00QHMGPXQ_EBOK/B00QHMGPXQ_EBOK.azw\r\n' 

application/x-qt-windows-mime;value="FileName" 57 'C:\\Users\\Primary\\DOCUME~1\\MYKIND~1\\B00QHM~1\\B00QHM~1.AZW\x00' 

application/x-qt-windows-mime;value="FileContents" 0 '' 

application/x-qt-windows-mime;value="FileNameW" 162 'C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00t\x00a\x00s\x00c\x00i\x00o\x00n\x00\\\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00s\x00\\\x00M\x00y\x00 \x00K\x00i\x00n\x00d\x00l\x00e\x00 \x00C\x00o\x00n\x00t\x00e\x00n\x00t\x00\\\x00B\x000\x000\x00Q\x00H\x00M\x00G\x00P\x00X\x00Q\x00_\x00E\x00B\x00O\x00K\x00\\\x00B\x000\x000\x00Q\x00H\x00M\x00G\x00P\x00X\x00Q\x00_\x00E\x00B\x00O\x00K\x00.\x00a\x00z\x00w\x00\x00\x00' 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 '\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

Firefox rurl: None None
calibre, version 3.38.1
Debug mode: <p>You have started calibre in debug mode. After you quit calibre, the debug log will be available in the file: c:\users\Primary\appdata\local\temp\tmp3apbkd.txt<p>The log will be displayed automatically.

URLS: ['file:///C:/Users/Primary/Documents/My%20Kindle%20Content/B00QHMGPXQ_EBOK/B00QHMGPXQ_EBOK.azw']
Paths: [u'C:/Users/Primary/Documents/My Kindle Content/B00QHMGPXQ_EBOK/B00QHMGPXQ_EBOK.azw']
Extensions: frozenset([u'azw'])
Gather KFX-ZIP (from KFX Input) 1.12.1: Importing C:/Users/Primary/Documents/My Kindle Content/B00QHMGPXQ_EBOK/B00QHMGPXQ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as C:\Users\Primary\AppData\Local\Temp\calibre_6iui1e\i5nys9.kfx-zip
DeDRM v6.6.1: Trying to decrypt i5nys9.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: i5nys9
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.325b7728-f3b9-4f41-917f-2d0a4af8a32f.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Primary\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.12.1: Packaging C:\Users\Primary\AppData\Local\Temp\calibre_6iui1e\i5nys9.kfx-zip
Processing container: B00QHMGPXQ_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container B00QHMGPXQ_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Primary\AppData\Local\Temp\calibre_6iui1e\9iw5fj_add_books\0\B00QHMGPXQ_EBOK.kfx-zip
Added Apprentice (Lenna's Arc Book 2) to db in: 1.4
Added 1 books in 2.9 seconds

**Comment by ElleKayEm** [comment]
You need to use Kindle for PC version 1.24 or earlier.

**Comment by tascion** [comment]
thank you for your help, that did solve the problem.
:-)
