### ISSUE TITLE
DeDRM not working

### ISSUE THREAD

**Issue by buzzedabe** [apprenticeharper/DeDRM_tools#753]
calibre Debug log
calibre 3.38.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.38.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[1.66] main UI initialized...
[1.66] Hiding splash screen
[67.24] splash screen hidden
[67.24] Started up in 67.24 seconds with 0 books
DeDRM v6.6.1: Trying to decrypt B07CZ6ZJW1_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Guide to Computer Forensics and Investigations
Got DSN key from database default_key
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\abela\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\abela\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2687622320' and UserName '6162656c61'
DeDRM v6.6.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Guide to Computer Forensics and Investigations to db in: 0.6
Added 1 books in 2.8 seconds

**Comment by buzzedabe** [comment]
kindle for pc 1.16 - latest drm tools

**Comment by buzzedabe** [comment]
2019 book

**Comment by j-howell** [comment]
From the log:
> DeDRM v6.6.1: Failed to decrypt with error: Cannot decode library or rented ebooks.

These tools are meant to be used on books that you own.

**Comment by buzzedabe** [comment]
Ooooohhhh thats why ok

**Comment by ElleKayEm** [comment]
You can close the issue.
