### ISSUE TITLE
How the Hell i can maintain original input filename to the calibre output

### ISSUE THREAD

**Issue by stoneasher** [apprenticeharper/DeDRM_tools#755]
How the Hell i can maintain original input filename to the calibre output at least , or with adding
_nodrm at the end of each filename decrypted ..

I am totally disappointed .

and if you want ask me why , because i need that and i don't want to handle it manually by myself .

**Comment by j-howell** [comment]
This question is not DRM related.

Calibre always stores imported book formats under its own folder structure and file naming convention. See [Want to change folder structure or file names in the Calibre library?](https://www.mobileread.com/forums/showthread.php?t=119175) for more information.

You can have calibre preserve the original file name in a custom column using the [GetFileName plugin](https://www.mobileread.com/forums/showthread.php?t=278559).

**Comment by ElleKayEm** [comment]
Is the DRM removed?  If so, then this is a question for the calibre forum at Mobile Read.
