### ISSUE TITLE
Failed to decrypt KFX DRM voucher with any key

### ISSUE THREAD

**Issue by yermasya** [apprenticeharper/DeDRM_tools#756]
Windows 7 32bit
Kindle for PC 1.25.1
Calibre 3.38.1
DeDRM 6.6.1

Hello, please help. When trying to customize the plugin it says "The default encryption key for Kindle for Mac/PC could not be found".

calibre Debug log
calibre 3.38.1  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
calibre 3.38.1  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9842323651 x 71.9822878229
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[2.09] main UI initialized...
[2.09] Hiding splash screen
[4.21] splash screen hidden
[4.21] Started up in 4.21 seconds with 2 books
Storage number map:
{(7L, 0L): [(2L, 'C'), (3L, 'D')], (7L, 1L): [(1L, 'F')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0401\G000PP0884140SQG&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=2600)
{u'drive_letters': ['F'],
 u'pnp_id_map': {'F': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0401#g000pp0884140sqg&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'F': (1L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: F:\ documents
DEBUG:    0.0 USBMS: scan from root False F:\documents
DEBUG:    0.1 USBMS: count found in cache: 13, count of files in metadata: 13, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 13
DeviceJob: set_books_in_library finished: time= 0.00800013542175
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Job: 2 Set library information finished
No details available.
Job: 1 Get device information finished
No details available.
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['j\xf9\x01X^\x85lp\xed\x8b\n\xd0\x97\xbc\x13}\xd4=*\xfb\xaf\xcb)\x90\xd1\xb9\xa7\x02\xcaE\x06\x11', 'C:\\Users\\001\\Documents\\My Kindle Content\\B01N3YVR30_EBOK\\B01N3YVR30_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.12.1: Importing C:\Users\001\Documents\My Kindle Content\B01N3YVR30_EBOK\B01N3YVR30_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 10 file(s) as C:\Users\001\AppData\Local\Temp\calibre_gofvcf\zzpm1v.kfx-zip
DeDRM v6.6.1: Trying to decrypt zzpm1v.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: zzpm1v
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.edaf6b1d-c741-4bb9-8efe-6c2c5d64c526.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\001\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.12.1: Packaging C:\Users\001\AppData\Local\Temp\calibre_gofvcf\zzpm1v.kfx-zip
Processing container: B01N3YVR30_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container B01N3YVR30_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\001\AppData\Local\Temp\calibre_gofvcf\lc_l2u_add_books\0\B01N3YVR30_EBOK.kfx-zip
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added All the Mowgli Stories (Macmillan Collector's Library Book 114) to db in: 0.3
Added 1 books in 2.1 seconds

**Comment by j-howell** [comment]
See issue #752

**Comment by yermasya** [comment]
> See issue #752

thank you! sorry for not finding that myself

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
