### ISSUE TITLE
Unable to DeDRM Adobe Digital book with Calibre

### ISSUE THREAD

**Issue by sbabcock61** [apprenticeharper/DeDRM_tools#759]
using Calibre 3.38.1 / have installed the DeDRM plugin / have confirmed that i's enabled and active
Here is the Log when I open the book in Calibre
It appears to be having trouble finding the Adobe key

calibre Debug log
calibre 3.38.1  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.38.1  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
[1.42] main UI initialized...
[1.42] Hiding splash screen
[13.54] splash screen hidden
[13.54] Started up in 13.54 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xe0\x98\x8a+\xad\xe9\xe6\xc6\xa3\x92\xdb\xb1/\x82q\x18v\xf1\xad3\x17l\xb0\xf2\xd3\x1dH\x14\x1d\\\xb7b', 'C:\\Users\\Cathy\\Documents\\My Digital Editions\\Diagnostic and Statistical Manual of Mental Disorders DSM-IV-TR\xc2\xae.epub']
DeDRM v6.6.1: Trying to decrypt Diagnostic and Statistical Manual of Mental Disorders DSM-IV-TRÂ®.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: Diagnostic and Statistical Manual of Mental Disorders DSM-IV-TRÂ®.epub is a secure Adobe Adept ePub
DeDRM v6.6.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.6.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 346, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 403, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Diagnostic and Statistical Manual of Mental Disorders: DSM-IV-TR® to db in: 1.4
Added 1 books in 2.3 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x03994790>> ignored

**Comment by sbabcock61** [comment]
Adobe Digital Editions 4.5.7
Yes - the computer is authorized

**Comment by ElleKayEm** [comment]
Can you open it in ADE 2.0.1 authorized with the same Adobe ID?

**Comment by sbabcock61** [comment]
I installed 2.01
Help / Authorization show computer is authorized
Am unable to open E-Doc - "Activation Server Error" code : E_ADEPT_INTERNAL

I am still able to open it in 4.5 on the same PC

should I uninstall 4.5 ?

**Comment by ElleKayEm** [comment]
First, try de-authorizing and re-authorizing ADE 2.0.1.  Open it and press Ctrl+Shift+D.  Then authorize with your Adobe ID.  If you can open the book, then try adding it to calibre again.

**Comment by ElleKayEm** [comment]
Good.  Thanks for reporting what worked.  If you're all set, you can close the issue.
