### ISSUE TITLE
[Report] LGTM Analysis Results

### ISSUE THREAD

**Issue by LordNyriox** [apprenticeharper/DeDRM_tools#761]
Running the DeDRM repository through the LGTM analysis tool turned up 8 alerts of severity "error", and 66 alerts of severity "warning". 

Perhaps these could be fixed? 

[<https://lgtm.com/projects/g/apprenticeharper/DeDRM_tools/alerts/?mode=list&lang=&severity=error%2Cwarning>]

**Comment by ideologysec** [comment]
Submit a pull request?

**Comment by LordNyriox** [comment]
@ideologysec: 

>Submit a pull request? 

Unfortunately, I am unfamiliar with Python.  Someone else will have to submit a PR based on these findings.
