### ISSUE TITLE
Plugin not working anymore (DeDRM Calibre Kindle PC OS)

### ISSUE THREAD

**Issue by Michael55plus** [apprenticeharper/DeDRM_tools#765]
I haven't used Calibre for a longer time to deDRM a Kindle ebook and when I tried to import a recently purchased ebook I got "Cannot convert" and "This book is locked by DRM." messages.

I'm using Calibre 3.39 / DeDRM 6.6.1 plugin / Kindle for PC 1.15.0, also have KFX input  plugin installed.

To receive the ebook, I use WindowsXP in VirtualBox with the Kindle reader version 1.15.0. I pick the received ebook and transfer it to outside of VirtualBox into Ubuntu 16.04LTS. There I import the ebook to calibre. After importing the book is shown in calibre with extension AZW. If I try to open this book with the ebook reader of calibre, the ebook reader complains and tells me, that it cannot open the book because it is locked by DRM. 
I tested the procedure with an older ebook, I bought years before by deleting it from calibre and importing it freshly from a backup and this worked fine. The book could be opened as expected.

Here is the info from debug log:

calibre Fehlerdiagnoseprotokoll
calibre 3.39  embedded-python: True is64bit: True
Linux-4.15.0-45-generic-x86_64-with-debian-stretch-sid Linux ('64bit', 'ELF')
('Linux', '4.15.0-45-generic', '#48-16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019')
Python 2.7.15
Linux: ('debian', 'stretch/sid', '')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
calibre 3.39  embedded-python: True is64bit: True
Linux-4.15.0-45-generic-x86_64-with-debian-stretch-sid Linux ('64bit', 'ELF')
('Linux', '4.15.0-45-generic', '#48-16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019')
Python 2.7.15
Linux: ('debian', 'stretch/sid', '')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
Turning on automatic hidpi scaling
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.569275362 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[1.28] main UI initialized...
[1.28] Hiding splash screen
[12.54] splash screen hidden
[12.55] Started up in 12.55 seconds with 838 books
['zenity', '--modal', '--file-selection', '--title=B\xc3\xbccher ausw\xc3\xa4hlen', '--separator=\n', '--attach=81788942', '--filename=/home/michael/Downloads/.fgdfg.gdfhjdhf*&^839', '--file-filter=B\xc3\xbccher | *.lrf *.rar *.zip *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.azw8 *.kfx-zip *.kpf', '--file-filter=EPUB-B\xc3\xbccher | *.epub *.kepub', '--file-filter=Kindle-B\xc3\xbccher | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=PDF-B\xc3\xbccher | *.pdf *.azw4', '--file-filter=HTML-B\xc3\xbccher | *.htm *..azw
Gather KFX-ZIP (frohtml *.xhtm *.xhtml', '--file-filter=LIT-B\xc3\xbccher | *.lit', '--file-filter=Text-B\xc3\xbccher | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Comics | *.cbz *.cbr *.cbc', '--file-filter=Archive .azw
Gather KFX-ZIP (fro.azw
Gather KFX-ZIP (fro| *.zip *.rar', '--file-filter=Textverarbeitungsdateien | *.odt *.doc *.docx', '--file-filter=Alle Dateien | *', '--multiple']
Gather KFX-ZIP (from KFX Input) 1.13.0: Importing /home/<name>/Downloads/XXXXXX_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt XXXX_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: <name of ebook>
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.6.1: Running kindlekey.py under Wine
DeDRM v6.6.1: Command line: 'WINEPREFIX="/home/<name>" wine python.exe "/home/<name>/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/<name>/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
/bin/sh: 1: wine: not found
DeDRM v6.6.1: Found and decrypted 0 key files
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added <name of ebook> to db in: 0.1
Added 1 books in 0.9 seconds
Worker Launch took: 0.187789916992
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

===================================================================

A kindle key is present but I cannot upload a screenshot of the little Window in calibre titled "DeDRM 6.6.1: Manage Kindle for Mac and PC Keys".

**Comment by ElleKayEm** [comment]
Things can be tricky to get set up in Linux.  The readme instructs you to install Kindle for PC as well as particular versions of Python and Pycrypto under Wine.  And to specify the path in the DeDRM plugin customization.  Even then Python sometimes can't be found and the key retrieval script can't run.

In your case, you don't have that setup so we see this error:

> DeDRM v6.6.1: Running kindlekey.py under Wine
DeDRM v6.6.1: Command line: 'WINEPREFIX="/home/michael" wine python.exe "/home/michael/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/michael/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
/bin/sh: 1: wine: not found
DeDRM v6.6.1: Found and decrypted 0 key files

You could try temporarily installing calibre with DeDRM in the VirtualBox.  Add your book.  Then save the key and import it into the Linux calibre's DeDRM plugin.  However, I'm not sure if the old version of calibre you'd have to use in Windows XP would work with the current DeDRM plugin.

If you had Python and Pycrypto installed in the VirtualBox, you might be able to just run the key retrieval script and then import it into Linux calibre's DeDRM.

As for why the older ebook worked, did you really backup a copy that still had DRM?  Because the longer you wait to remove DRM, the less the chances of being able to remove it.

**Comment by Michael55plus** [comment]
Hello and thank you for your detailed advice. But I was aware of all of that. My logfile says:

Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.6.1: Running kindlekey.py under Wine

This I understand so, that the first the trial to find a matching keyfile in DeDRM was not successful. Therefore wine was tried, but was also successless, because I do not use wine. 
Indeed a keyfile "kindlekey1.k4i" is present in calibre plugin, which explains, why my older book was deDRMd successfully. 
But why did the new book not be deDRMd? Your dedailed description gave me the idea, to extract the keyfile from the new book by running the extraction script in XP on the VirtualBox. I copied the new extracted keyfile to Linux and compared it to the old one, which was yet in calibre. Suprise: the files are different! The new book contains another key than the older ones, which are from end of 2015 and begin of 2016.
#### I then renamed the newly extracted keyfile to "kindlekey2.k4i" and imported it to the calibre plugin. Afterwards I imported the new book to calibre and ..... great success. It was deDRMd and could also be converted to epub format, usable on my PocketBook reader. ####

It seems to me, that Amazon changes the keyfile after some time. The logfile line:
_"DeDRM v6.6.1: Looking for **new** default Kindle Key after 0.1 seconds"_
might be a hint to that?
So everybody should extract the keyfile repeatedly, if one buys kindle ebooks seldomly like me.

**Comment by ElleKayEm** [comment]
Every Kindle app/device has its own unique key, even on the same account.  So if the older ebook was from a previous installation, then it would have a different key.  And if you are ever required to log in again when first opening Kindle for PC that would also be an indication that the key had changed.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by Michael55plus** [comment]
Thank you and I am closing now
