### ISSUE TITLE
I still can't convert my book

### ISSUE THREAD

**Issue by 8Ten10** [apprenticeharper/DeDRM_tools#766]
Hi guys, I got this book yerterday and after following every step by step tutorials, I still get the error saying the book is loked by DMR. The book is in .azw format, I unnsuccessfully tried to convert it in many formats. Here is my log : 

calibre Debug log
calibre 2.21 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) && DeDRM && Package KFX (from KFX Input) && KFX metadata reader (from KFX Input) && KFX Input && Obok DeDRM && KindleUnpack - The Plugin
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 9.48 seconds with 0 books
Gather KFX-ZIP (from KFX Input) 1.13.0: Importing C:/Users/Administrator/Documents/My Kindle Content/B06XCHTKIG_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt B06XCHTJBG_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The New Moon
Got DSN key from database default_key
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
File is encoded with PID +NijX29FMY.
Decrypting. Please wait . . . . . . . . . . . . done
Decryption succeeded after 0.4 seconds
DeDRM v6.6.1: Finished after 0.5 seconds
Added The Brief Bedford Reader to db in: 2.8
Added 1 books in 4.3 seconds
Worker Launch took: 0.307000160217
Job: 1 Convert book 1 of 1 (The New Moon) finished
Convert book 1 of 1 (The New Moon)
	Resolved conversion options
	calibre version: 2.21.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\calibre_ihkjcc\\g_ltc5.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000000000546A6D8>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x000000000546AA20>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\calibre_ihkjcc\\brpggh.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\ADMINI~1\AppData\Local\Temp\calibre_ihkjcc\o50py4.azw
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  The New Moon (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 193, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 31, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1041, in run
	  File "site-packages\calibre\customize\conversion.py", line 241, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 43, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 77, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 143, in check_for_drm
	calibre.ebooks.DRMError: The New Moon

Thank you.

**Comment by ElleKayEm** [comment]
If this is a rental, then DeDRM won't work.  If you own the book, try updating calibre.

**Comment by 8Ten10** [comment]
Thanks for your reponse. I own the book. I'm downloading a recent version of calibre.

**Comment by 8Ten10** [comment]
It just worked. I don't really get why it wasn't before. I downloaded the version 3.39 of calibre and also upgraded Kindle to 1.24. Thank you

**Comment by ElleKayEm** [comment]
The log did show the DRM removed:

> Decrypting. Please wait . . . . . . . . . . . . done
Decryption succeeded after 0.4 seconds

But apparently, the older version of calibre didn't recognize that.

Be sure to uncheck auto-update in the Kindle for PC settings because the tools do not work with later versions.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by 8Ten10** [comment]
Thank you again
