### ISSUE TITLE
New computer issues

### ISSUE THREAD

**Issue by imac42** [apprenticeharper/DeDRM_tools#769]
My gf got a new computer and we were trying to recreate the previous setup which worked fine.  Kindle for PC is version 1.17, we download for transfer by USB (to her kindle fire), get an azw3 but it cannot remove the drm.  Any ideas?  Debug below.  I just checked and this book doesn't work on the old computer either.

calibre Debug log
calibre 3.39.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.39.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 78.9126213592 x 78.8275862069
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[2.62] main UI initialized...
[2.62] Hiding splash screen
[18.09] splash screen hidden
[18.09] Started up in 18.09 seconds with 227 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['+d\\\x82\xca\xf1\x1e\xd4yf\x1d\xc2\x80aj[\x8a\x82\xf4Uh\xc7\xeeG\xf4\xfa\xff\x9b\n\xf9\x88*', 'C:\\Users\\beffy\\Downloads\\Before We Were Strangers.azw3']
DeDRM v6.6.1: Trying to decrypt Before We Were Strangers.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Before We Were Strangers
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\beffy\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\beffy\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1592949791' and UserName '6265666679'
DeDRM v6.6.1: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Before We Were Strangers
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 0 books in 4.0 seconds
Worker Launch took: 0.160000085831
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: [" \x1b\xb1{5\x9d\xdf\xea\x10\x05\x86S\xb55|b\x91\xf9\x1a\x14\x88\x98\x03\x96\xb7e'\x95\xf599\xdc", 'C:\\Users\\beffy\\Downloads\\Before We Were Strangers.azw3']
DeDRM v6.6.1: Trying to decrypt Before We Were Strangers.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Before We Were Strangers
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\beffy\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\beffy\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1592949791' and UserName '6265666679'
DeDRM v6.6.1: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Before We Were Strangers
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Before We Were Strangers to db in: 0.1
Added 1 books in 0.6 seconds
Worker Launch took: 0.0889999866486
Job: 2 Convert book 1 of 1 (Before We Were Strangers) finished
Convert book 1 of 1 (Before We Were Strangers)
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\beffy\\AppData\\Local\\Temp\\calibre_bkcna6\\6jguhw.jpeg'
	  output_profile: 'kindle_fire'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\beffy\\AppData\\Local\\Temp\\calibre_bkcna6\\lxhhix.opf'
	Resolved conversion options
	calibre version: 3.39.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\beffy\\AppData\\Local\\Temp\\calibre_bkcna6\\6jguhw.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x049EEC50>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x049EEFF0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\beffy\\AppData\\Local\\Temp\\calibre_bkcna6\\lxhhix.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\beffy\AppData\Local\Temp\calibre_bkcna6\b9jpew.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Before We Were Strangers (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 45, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Before We Were Strangers

**Comment by ElleKayEm** [comment]
Download the book with Kindle for PC installed on the same machine and user as calibre with DeDRM.  You would need an E-ink Kindle, not a Fire, to remove DRM from a book downloaded from the website.

**Comment by imac42** [comment]
Download to Fire is the only option.  This account never had an eInk Kindle and previously worked.  Change in format?

**Comment by ElleKayEm** [comment]
Don't download from the website.  Download with Kindle for PC.

**Comment by imac42** [comment]
Doh.  I feel silly - that worked.  I was importing them from the wrong place.  I got confused as I use an e-Ink Kindle whereas she just has a Fire.
