### ISSUE TITLE
DRM Issue

### ISSUE THREAD

**Issue by Hantoo** [apprenticeharper/DeDRM_tools#770]
I can't open a DRMed book.

Here is the log file created.
[tmpojbgxi.txt](https://github.com/apprenticeharper/DeDRM_tools/files/2849375/tmpojbgxi.txt)

The book was obtained via dawsonera.com and all other books I've been able to access from them.
Computer is a 64Bit windows 10.

Any help would be appreciated.

**Comment by ElleKayEm** [comment]
These tools are intended for books you own.

**Comment by Wannabe99** [comment]
So not for books on loan?

**Comment by ElleKayEm** [comment]
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cant-get-the-tools-to-work-on-my-rented-or-library-ebooks
