### ISSUE TITLE
"Load plugin from file" button doesn't exist

### ISSUE THREAD

**Issue by junkmailreceiverperson** [apprenticeharper/DeDRM_tools#771]
I feel ridiculous, but I don't have a button on the Calibre plugin page for "Load plugin from file". I cannot figure out how to import the unzipped/downloaded file.

What am I missing?

![image](https://user-images.githubusercontent.com/47511000/52543188-623e4500-2d5c-11e9-8f22-1c34f1be4eb1.png)

**Comment by ElleKayEm** [comment]
Wrong area.  Click the Preferences button on the main menu.  Then look for the Plugins button in the last row under Advanced.

**Comment by junkmailreceiverperson** [comment]
Thank you ElleKayEm! I got it!

I'm a long time installer and user. Must a been a brain-fart.
