### ISSUE TITLE
Calibre KFX-Zip isssue

### ISSUE THREAD

**Issue by jamesoooo** [apprenticeharper/DeDRM_tools#773]
I'm sure this has been addressed before but I have spent alot of time reading comments and trying to fix. I would appreciate some help.
In summary, book purchased from Amazon for kindle PC. 
I have installed both KFX input and DeDRM.
Format still comes in as KFX-ZIP. Any help would be appreciated. Log file below.

calibre Debug log
calibre 3.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
calibre 3.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
Starting up...
Loaded cached store plugin for: Beam EBooks DE at version: 4
Loaded cached store plugin for: Legimi at version: 9
Loaded cached store plugin for: Publio at version: 9
Loaded cached store plugin for: Mills and Boon UK at version: 4
Loaded cached store plugin for: Woblink at version: 14
Loaded cached store plugin for: ebook.de at version: 5
Loaded cached store plugin for: Empik at version: 8
Loaded cached store plugin for: Google Books at version: 5
Started up in 16.27 seconds with 16 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xea\xcb\x18q0\xa6D\xce\x1b\x8cS\x9e\xf4\x04\x12\xff\x141!*`\x1e\xb5['\x15\x13\xff~\xf3F\xee", 'C:\\Users\\jolesinski.SGL\\Documents\\My Kindle Content\\B013EUEKUS_EBOK\\B013EUEKUS_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.13.0: Importing C:\Users\jolesinski.SGL\Documents\My Kindle Content\B013EUEKUS_EBOK\B013EUEKUS_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\JOLESI~1.SGL\AppData\Local\Temp\calibre_ptole6\lrfvth.kfx-zip
DeDRM v6.6.1: Trying to decrypt lrfvth.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: lrfvth
Found 0 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.d09d2b29-4646-4984-8567-25826af55ea0.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\jolesinski.SGL\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.13.0: Packaging C:\Users\JOLESI~1.SGL\AppData\Local\Temp\calibre_ptole6\lrfvth.kfx-zip
Processing container: B013EUEKUS_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 152, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 263, in get_container
KFXDRMError: Book container B013EUEKUS_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\JOLESI~1.SGL\AppData\Local\Temp\calibre_ptole6\tqieb0_add_books\0\B013EUEKUS_EBOK.kfx-zip
Added A study guide for Cormac McCarthy's No Country for Old Men (Literary Newsmakers for Students) to db in: 0.8
Added 1 books in 5.8 seconds

**Comment by ElleKayEm** [comment]
You need to use Kindle for PC version 1.24 or earlier.

**Comment by jamesoooo** [comment]
Really thats it? I will try that then. 
I assume i will need the two same plugins?

**Comment by jamesoooo** [comment]
Sorry, just reread. I am trying to open the book in Calibre so I can convert. What does this have to do with the Kindle for PC software?

**Comment by ElleKayEm** [comment]
There is a change in the DRM with starting with version 1.25 which DeDRM can't handle (yet).

**Comment by jamesoooo** [comment]
So I cannot decrypt it then through Calibre at this point?

**Comment by jamesoooo** [comment]
I think I might know what you are saying. If I remove the book data file, remove Kindle, reload the old 1.24 kindle, it will then import the book data in a slightly different format that I can then decrypt?

**Comment by ElleKayEm** [comment]
Yes, the DeDRM plugin can remove DRM from books downloaded with Kindle for PC 1.24 or earlier.  For now, books from 1.25 or later won't work.

**Comment by jamesoooo** [comment]
ElleKayEm, thanks for your help here. I did as you said and still ran into a few issues with KFX. 
For anyone else, I figured it out albiet a slightly different way. I was having an issue with the KFX files still. I did a work around where I renamed the Kindle file renderer-test.exe  to renderer-test.xxx 
This prevents the renderer-test program from executing, blocking the use of KFX. It forces your Kindle to download the book in a different format (hopefully readable)
You can do a search for this file but it is normally in ren %localappdata%\Amazon\Kindle\application\

After restarting the Kindle program any books previously downloaded in KFX format will no longer open. You will need to remove them from your device and re-download them. Pretty easy. All future downloads will use the older Kindle formats instead of KFX although they will continue to be placed in one individual subdirectory per book. You no longer have to worry about the KFX issue. I then opened Calibre and was able to import it in and it came in under a AZW3 format which I could then convert to MOBI. 
It worked!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by tognbee** [comment]
> 
> 
> ElleKayEm, thanks for your help here. I did as you said and still ran into a few issues with KFX.
> For anyone else, I figured it out albiet a slightly different way. I was having an issue with the KFX files still. I did a work around where I renamed the Kindle file renderer-test.exe to renderer-test.xxx
> This prevents the renderer-test program from executing, blocking the use of KFX. It forces your Kindle to download the book in a different format (hopefully readable)
> You can do a search for this file but it is normally in ren %localappdata%\Amazon\Kindle\application\
> 
> After restarting the Kindle program any books previously downloaded in KFX format will no longer open. You will need to remove them from your device and re-download them. Pretty easy. All future downloads will use the older Kindle formats instead of KFX although they will continue to be placed in one individual subdirectory per book. You no longer have to worry about the KFX issue. I then opened Calibre and was able to import it in and it came in under a AZW3 format which I could then convert to MOBI.
> It worked!

Thank you very much. I tried all sorts but this one did the job (Y)

**Comment by ElleKayEm** [comment]
This info is in the FAQs.

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac
