### ISSUE TITLE
Recent Kindle for PC keys are in non-JSON format, even with Kindle 1.17

### ISSUE THREAD

**Issue by saveriomiroddi** [apprenticeharper/DeDRM_tools#774]
Hello!

I use Kindle for PC, version 1.17, for downloading the books I purchase and decrypting/converting them, using DeDRM tools version is 6.6.1.

Everything worked as expected. Recently though, after an operating system reinstall, it seems that the Kindle for PC key format changed, so that I can't use it anymore.

I still have a copy of the old key, whose format is standard JSON. The new key has the same name and location (`AppData/Local/Amazon/Kindle/storage/.kinf2011`), however, it's not JSON anymore. It looks like Base64-ish (alphanumeric and slashes), although it isn't really valid Base64.

Right now, using the old key, I can download and decrypt the beforelast book I bought, but not the last one. They both have `azw` extension.

I can't use the new key at all, since it's not recognized at all by the DeDRM tools.

This seems to be a similar problem as https://github.com/apprenticeharper/DeDRM_tools/issues/443, however, before the reinstall, which happened less than a month ago, I didn't have this issue.

I've tried on a variety of hosts - two Windows 10 machines, and one Wine, and the result is the same.

Any ideas?

**Comment by ElleKayEm** [comment]
Each installation of Kindle for PC will have its own unique key.  Book and key must be from the same installation.  Post a log from one of the Windows machines.

**Comment by saveriomiroddi** [comment]
> Each installation of Kindle for PC will have its own unique key. Book and key must be from the same installation. Post a log from one of the Windows machines.

I've solved the problem - apologies for opening an invalid issue.

The problem was not with the association Kindle application <> downloaded book, instead, it was that I was trying to make Calibre import directly the `.kinf2011` file. This is not possible; one needs to make Calibre find and import the key, then export it to the k4i format - only then it it can be imported in another Calibre installation.

Thanks!
