### ISSUE TITLE
Need help filling out WinePrefix blank 

### ISSUE THREAD

**Issue by hub2git** [apprenticeharper/DeDRM_tools#777]
Dear all, I installed  DeDRM_tools_6.6.1.zip from  https://github.com/apprenticeharper/DeDRM_tools/releases. This is the latest version.

I then followed the 9 steps listed in https://apprenticealf.wordpress.com/2012/09/10/calibre-plugins-the-simplest-option-for-removing-most-ebook-drm/ to install ApprenticeAlf's DeDRM plugin inside my Calibre.

Because I'm on Linux (Linux Mint 19.1, Cinnamon), I need to do additional things, as found in http://will.tip.dhappy.org/lib/calibre/dedrm/DeDRM_Kindle%20for%20Mac%20and%20PC%20Key_Help.htm . The relevant section says:

> 
> Linux Users: WINEPREFIX
> 
> Under the list of keys, Linux users will see a text field labeled "WINEPREFIX". If you are use Kindle for PC under Wine, and your wine installation containing Kindle for PC isn't the default Wine installation, you may enter the full path to the correct Wine installation here. Leave blank if you are unsure.

I need to tell the DeDRM plugin the path to Wine installation. Because I used playonlinux to run/install KindleForPC, the location of my KindleForPC program is different. The main Kindle folder on my Linux is at
/home/hub2git/PlayOnLinux's virtual drives/KindleForPC/drive_c/Program Files (x86)/Amazon/Kindle .

Based on this location, what exactly should I type into the blank?

**Comment by ElleKayEm** [comment]
Linux can be tough to get set up even when you are using Wine in its default location.  One workaround I've seen is to temporarily install Windows calibre with DeDRM.  Then add a Kindle book.  Save the key from the DeDRM customization.  And then import that key into the plugin of your Linux calibre.

**Comment by ideologysec** [comment]
in a terminal:
```echo $WINEPREFIX```

and then post the results

**Comment by hub2git** [comment]
> in a terminal:
> 
> `echo $WINEPREFIX`
> 
> and then post the results
hub2git@desktop ~ $  echo $WINEPREFIX

hub2git@desktop ~ $

**Comment by hub2git** [comment]
> Linux can be tough to get set up even when you are using Wine in its default location. One workaround I've seen is to temporarily install Windows calibre with DeDRM. Then add a Kindle book. Save the key from the DeDRM customization. And then import that key into the plugin of your Linux calibre.

Hi ElleKayEm, 
I tried to carefully follow your instructions. 

1. I downloaded https://download.calibre-ebook.com/3.39.1/calibre-3.39.1.msi.
2. I got playonlinux to install it. I then installed DeDRM_calibre_plugin from DeDRM_tools_6.6.1.zip.
3. I restarted Calibre windows.
4. I clicked "Add book" and double-clicked on an AZW file. I see Calibre adding/importing the book into the Calibre library. 
5. I then go to Preferences>Plug-Ins, then put a check mark in "Show only user installed plugins". 
6. I then select the "DeDRM (6.6.1)  by Apprentice Alf" plugin.
7. I click  "Customize Plugin"
8. Unsure where to go next, I check out both "eInk  Kindle  ebooks" and "Kindle for Mac/PC books". Neither of those two places has a key. 

:crying_cat_face:

**Comment by ideologysec** [comment]
It's under Adobe or ADEPT, I believe.

**Comment by hub2git** [comment]
I'm sorry...I don't understand what you mean when you say it's under Adobe
or Adept

**Comment by ideologysec** [comment]
That was a mistake, I apologize. Forgot we were working with Kindle.

Is Kindle installed in the same Wine bottle as Calibre? Have you succesfully downloaded and activated a book?

**Comment by hub2git** [comment]
I don't know if Kindle and Calibre are in the same wine bottle. I used
playonlinux to install them. And the installation folders are different. So
the answer's probably ”No”.

In Kindle for PC, I have successfully downloaded many of my books. I now
have a folder full of azw files. I don't know what you mean by ”activated”.

**Comment by ideologysec** [comment]
Sorry, I think mostly in Adobe Digital Editions terms, which has a two-stage book download process. As long as you can read books in the Kindle program in Wine, that's all you need.

Unfortunately, Calibre can't see through Wine bottles very easily (hence why your trouble started in the first place). Try installing Calibre in the same Wine bottle as the Kindle app, and importing a book afterwards.

That should put the key into Calibre-Windows-Wine, which you can then export to Calibre-Linux.

**Comment by hub2git** [comment]
Hi @ideologysec (Eric),

Thanks for your help. With PlayOnLinux, I chose the same install location
for CalibreWindows as the KindleForPC(Windows) and it got the
"default_key.k4i". I exported the key, then shut down KindleForPC (Windows).
I then opened Calibre (Linux) and imported the key (in the DeDRM plugin)
and now Calibre (Linux) is able to view the AZW files.

Appreciate it a lot. :)
