### ISSUE TITLE
Cannot Remove DRM from Ebooks on Kindle Fire

### ISSUE THREAD

**Issue by BozoTClown** [apprenticeharper/DeDRM_tools#779]
I want to start by saying thank you for the efforts put into writing this plugin. I am running Calibre on a fresh install of Raspbian Stretch on a Raspberry PI 3+. The book/books I have been trying to convert have been purchased and are not previews or loaner books from Amazon. They have been downloaded to a Fire and can be opened fine on this device, no download is needed. One thing my wife has noticed is if books are saved to an external device they have to be downloaded each time you want to read them. This is why I picked a book that worked without having to be re-downloaded as my test. I have attached the log and an image of the error.

[Calibre_Log.txt](https://github.com/apprenticeharper/DeDRM_tools/files/2886726/Calibre_Log.txt)
![error]

(https://user-images.githubusercontent.com/25624149/53128927-10ec3d80-3534-11e9-8270-2eeb60b4f3f3.JPG)

**Comment by ElleKayEm** [comment]
Books from a Fire cannot be DeDRMed.  You need an E-ink Kindle or books downloaded with Kindle for PC/Mac.

**Comment by BozoTClown** [comment]
Thank you for your quick response.  J
