### ISSUE TITLE
Unable to convert .azw3 kindle download

### ISSUE THREAD

**Issue by tatterjack** [apprenticeharper/DeDRM_tools#781]
W10 Home
Version	10.0.17134 Build 17134
HP 250 G4 Notebook PC
i5-5200U CPU @ 2.20GHz, 8.00 GB

Unable to convert .azw3 kindle download
=======================================

(Please note I eventually converted the books I needed using
version 1.17 of kindle for PC)

Downloaded 2 books from Amazon Manage Contents and Devices
using Download and Transfer using USB

One downloaded as book1.azw and one as book2.azw3 
 
Downloaded and installed Calibre calibre-64bit-3.39.1.msi
Downloaded and installed DRM removal tools plugin in Calibre
Added book1.azw and book2.azw3 to Calibre
Converted book1 to PDF successfully
Converting book2.azw3 failed 'DRM protected'

Downloaded and installed jhowell's KFX Input plugin in calibre
Removed book2 from Calibre
Added book2 again
Retried convert to PDF. Failed again same error 'DRM protected'

Removed book2 from calibre
restarted Calibre in debug mode
added book2 again
closed calibre, copied debug log and posted below

(The reply to this issue https://github.com/apprenticeharper/DeDRM_tools/issues/780 
implies that installing Kindle for PC 1.24 should get round this issue. 
Nope. Same result)

(Option 2 here https://www.mobileread.com/forums/showthread.php?t=283371 says
renaming the renderer should cause new downloads to be in the older formats
Nope. It downloads as .apnx/.azw/.mbpv2/.phl combination and is imported into 
Calibre as .azw3 and once again fails conversion 'DRM protected')

(Option 1 here https://www.mobileread.com/forums/showthread.php?t=283371
installing Kindle 1.17 - I used KindleForPC-installer-1.17.44183 - worked perfectly.
I had avoided this because I didn't want to keep using a backlevel version)

Many thanks for everyone's work on this. I hope the debug log helps future implemetations.

calibre Debug log
calibre 3.39.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
calibre 3.39.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[1.33] main UI initialized...
[1.33] Hiding splash screen
[13.53] splash screen hidden
[13.53] Started up in 13.53 seconds with 3 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['Q\x0f\x85\xf4\xf8\xdd"D\xfd\x0cN\x8a\x90\xfa\r]\xae\xce\xfa4\x93\x02\x01c\xa4\xe1\xee\xec\xc7m\x97\x8e', 'F:\\Graham\\Desktop\\The Kefir Solution.azw3']
DeDRM v6.6.1: Trying to decrypt The Kefir Solution.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Kefir Solution
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Graham\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Kefir Solution to db in: 1.7
Added 1 books in 2.4 seconds

**Comment by ElleKayEm** [comment]
When you downloaded the books from the website, did you choose an E-ink Kindle (not a Fire)?  If so, then you need to enter its serial number into the plugin customization.

**Comment by ElleKayEm** [comment]
Option 2 works for Kindle for PC versions 1.19 to 1.24.  All book files downloaded to Kindle for PC will have the generic AZW extension regardless of underlying format.  If you import it into calibre with DeDRM and the extension changes to AZW3, then DRM has been removed.  AZW3 is the older KF8 format.  No need for the KFX Input plugin with those.

**Comment by tatterjack** [comment]
Hi ElleKayEm, thanks for the speedy reply.
Download from Amazon: I chose Download & transfer via USB. The other options are:
Deliver to Default Device or Others
Clear furthest page read
Read now
Add to collections

I don't see E-ink or Fire but I will re-install the latest Kindle for PC and, make the customisation and report back.

**Comment by tatterjack** [comment]
Option 2: this was using Kindle for PC 1.24. It did download with the generic azw extension and the associated files. After importing into Calibre (with DeDRM installed) it did have an azw3 extension but on trying to convert to PDF it failed with 'Cannot convert _the book_ This book is locked by DRM'.

**Comment by ElleKayEm** [comment]
When you select Download & transfer via USB, the next step is choosing a device.  To be able to DeDRM the file, you need to choose an E-ink Kindle (not a Fire).  If you do not have an E-ink Kindle on your account, then you will need to use Kindle for PC.

Did you remove the AZW3 file downloaded from the website before adding the Kindle for PC file?

**Comment by tatterjack** [comment]
Unfortunately the only device available is 'Tatterjack's Kindle', the others are greyed out. However my device is a third generation Kindle Keyboard not a Fire so I will try the customisation next.

Remove azw3 file: the debug file above is from the first attempt using the file downloaded from the website. In this and subsequent attempts I always removed the existing azw3 file first. I did try using the My Kindle files with versions 1.25 (I know it shouldn't work) and 1.24 (which I tried after reading issue #780) and finally with 1.17 which did work. I'm in the process of trying again with 1.25.

**Comment by tatterjack** [comment]
Kindle for PC 1.25. DeDRM customised with serial number.

Sorry, same result, I've just installed Kindle for PC 1.25 again, customised the DeDRM plugin with my Kindle serial number. Deleted the My Kindle folder contents. Downloaded the book into Kindle for PC. Removed it from Calibre, re-imported it into calibre this time from My Kindle, tried to convert to PDF and once again get 'Cannot convert the book. This book is locked by DRM'

Just to emphasize, I have a PDF conversion of the books I want. I have to go out shortly but will happily continue this later if it is of help. It would certainly be useful to know I had a solution for the future.

Thanks again.

**Comment by ElleKayEm** [comment]
Add your Kindle Keyboard's serial number to the plugin's customization and the files downloaded from the website for it (or directly from the Kindle) will work.

DeDRM will not currently work with books from Kindle for PC 1.25.

Books from version 1.17, as you know, work.  Books from versions 1.19 - 1.24 will work without any modification to K4PC as long as you also have the KFX Input plugin.  If you make the change described in option 2, then you don't have to worry about the KFX format.

As always with books from Kindle for PC, calibre with DeDRM and the installation of K4PC which was used to download the book must be on the same machine and user.

**Comment by tatterjack** [comment]
Issue resolved. Cause: user error but gosh there are many opportunities to make them.
Many thanks for your patience ElleKayEm
> 
> 
> Add your Kindle Keyboard's serial number to the plugin's customization and the files downloaded from the website for it (or directly from the Kindle) will work.
> 
Confirmed. This seems to be the best way to proceed if I wish Kindle for PC to remain current, though who knows what the future may hold.
> DeDRM will not currently work with books from Kindle for PC 1.25.
> 
Confirmed. This is not clear in the [plugin description](https://apprenticealf.wordpress.com/2012/09/10/calibre-plugins-the-simplest-option-for-removing-most-ebook-drm/) but is in [jhowell's post at mobileread](https://www.mobileread.com/forums/showthread.php?t=283371).
> Books from version 1.17, as you know, work. Books from versions 1.19 - 1.24 will work without any modification to K4PC as long as you also have the KFX Input plugin. If you make the change described in option 2, then you don't have to worry about the KFX format.
>
Confirmed. My problem yesterday was I had not customized the plugin properly. If my source is a book downloaded from the Amazon website using 'Download & transfer using USB'  then I need to use 'eInk Kindle ebooks' and fill in the Kindle serial number (without spaces). If my source is the My Kindle Content folder then I need to use 'Kindle for Mac/PC ebooks', press green plus sign and then OK to accept the default_key (renaming it if I want).
>

> As always with books from Kindle for PC, calibre with DeDRM and the installation of K4PC which was used to download the book must be on the same machine and user.

**Comment by ElleKayEm** [comment]
The plugin description you link to was last updated in August 2015 -- well before 1.25 which just came out at the end of last year, I think.  It is mentioned in the [FAQs here](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac) -- that's probably a better place to look for current info.

> If my source is the My Kindle Content folder then I need to use 'Kindle for Mac/PC ebooks', press green plus sign and then OK to accept the default_key (renaming it if I want).

This should happen automatically the first time you add a Kindle for PC book from the current installation of K4PC.  But that is how you can force it to check for a key beforehand.

**Comment by tatterjack** [comment]
> 
> 
> The plugin description you link to was last updated in August 2015 -- well before 1.25 which just came out at the end of last year, I think. It is mentioned in the [FAQs here](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac) -- that's probably a better place to look for current info. And jhowell has kept his post specifically about Kindle books up-to-date too.
> 
I don't see it in the faq. There are two specific mentions of it not working for 'Kindle for Mac 1.25'. Should it say 'PC/Mac'? 
> > If my source is the My Kindle Content folder then I need to use 'Kindle for Mac/PC ebooks', press green plus sign and then OK to accept the default_key (renaming it if I want).
> 
> This should happen automatically the first time you add a Kindle for PC book from the current installation of K4PC. But that is how you can force it to check for a key beforehand.

It probably did. I have a memory of deleting a default_key when it didn't work thinking 'I want my key, not a default.' I was more than a little punch drunk by then.

**Comment by apprenticeharper** [comment]
I'll update the FAQ
