### ISSUE TITLE
Calibre DRM no longer working.

### ISSUE THREAD

**Issue by TMcGee62** [apprenticeharper/DeDRM_tools#783]
Calibre is no longer removing DRM for books I purchase from Amazon.  I purchase and then download the book to my local drive.  Next I import the book into Calibre (Add Book) from its downloaded location.  This process worked seamlessly for years and recently stopped removing the DRM.  The following is the log while trying to Add a purchased book from AZN:
-------------------
calibre Debug log
calibre 3.39.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && Inept Epub DeDRM (0, 1, 7) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
calibre 3.39.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && Inept Epub DeDRM (0, 1, 7) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.32] db initialized
[0.32] Constructing main UI...
[1.77] main UI initialized...
[1.77] Hiding splash screen
[1.82] splash screen hidden
[1.83] Started up in 1.83 seconds with 613 books
objc[4010]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8e627210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11593edc8). One of the two will be used. Which one is undefined.
DeDRM v6.6.1: Trying to decrypt Lethal White (A Cormoran Strike Novel Book 4).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Lethal White (A Cormoran Strike Novel Book 4)
Found 6 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by TMcGee62** [comment]
Issue resolved.  Kindle trade-in and subsequent de-register in Amazon was responsible.  Once I input the new Kindle serial # into the plug-in (and deleted the trade-in) I was back to normal.

**Comment by ElleKayEm** [comment]
You can remove the old Inept Epub DeDRM plugin.
