### ISSUE TITLE
Barnes & Noble PDF supported?

### ISSUE THREAD

**Issue by rmenessec** [apprenticeharper/DeDRM_tools#79]
I found that some Nook books downloaded with the Android appp were in PDF format. They failed to decrypt. All of the files have "real" PDF headers. They did not decrypt with Nook credentials that worked successfully with Nook EPUB files.

I found a few posts with Google saying these are not Adobe DE files. I've also found a few posts saying they may be using some newer DE version that's not recognized by DeDRM.

Is there a special process for these PDFs that's not mentioned in the documentation or are these files not supported yet?

**Comment by ElleKayEm** [comment]
These files are not currently supported.  I would love to see it added.  I just think there hasn't been a lot of interest so no one has bothered.

**Comment by apprenticeharper** [comment]
Closed for now

**Comment by fondfire** [comment]
This should solve the problem. It hasn't been tested much, but has worked for those that tried it.

[ignoblepdf.py.txt](https://github.com/apprenticeharper/DeDRM_tools/files/4632106/ignoblepdf.py.txt)

Rename the file to just 'ignoble.py', make sure it's executable, and then use it just like the ignobleepub.py program.

**Comment by fondfire** [comment]
Added pull request #1095 to make ignoblepdf.py official.
