### ISSUE TITLE
newer drm removal failure for KFX files (most work getting this on newer ones)

### ISSUE THREAD

**Issue by jamosb** [apprenticeharper/DeDRM_tools#793]
calibre Debug log
calibre 3.40.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 14, 0) && DeDRM (6, 6, 2) && Package KFX (from KFX Input) (1, 14, 0) && Set KFX metadata (from KFX Output) (1, 28, 0) && KFX Output (1, 28, 0) && Obok DeDRM (6, 5, 4) && KFX metadata reader (from KFX Input) (1, 14, 0) && KFX Input (1, 14, 0)
calibre 3.40.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 14, 0) && DeDRM (6, 6, 2) && Package KFX (from KFX Input) (1, 14, 0) && Set KFX metadata (from KFX Output) (1, 28, 0) && KFX Output (1, 28, 0) && Obok DeDRM (6, 5, 4) && KFX metadata reader (from KFX Input) (1, 14, 0) && KFX Input (1, 14, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[1.55] main UI initialized...
[1.55] Hiding splash screen
[70.89] splash screen hidden
[70.89] Started up in 70.89 seconds with 234 books
Gather KFX-ZIP (from KFX Input) 1.14.0: Importing C:/Users/Admin/Documents/My Kindle Content/B07HR6456K_EBOK/B07HR6456K_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Admin\AppData\Local\Temp\calibre_cs5rje\sdcqgy.kfx-zip
DeDRM v6.6.2: Trying to decrypt sdcqgy.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: sdcqgy
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7ff02ae6-6e63-4b94-a1b4-638130a012fd.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.2: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
DeDRM v6.6.2: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Admin\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Admin\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3920310702' and UserName '41646d696e'
DeDRM v6.6.2: Found 1 new key
Decrypting KFX-ZIP ebook: sdcqgy
Got DSN key from database default_key_1
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7ff02ae6-6e63-4b94-a1b4-638130a012fd.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.2: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 572, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.2: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.14.0: Packaging C:\Users\Admin\AppData\Local\Temp\calibre_cs5rje\sdcqgy.kfx-zip
Processing container: B07HR6456K_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 152, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 263, in get_container
KFXDRMError: Book container B07HR6456K_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Admin\AppData\Local\Temp\calibre_cs5rje\bnyznw_add_books\0\B07HR6456K_EBOK.kfx-zip
Added Immortality and Chaos: The Complete Epic Pentalogy to db in: 0.3
Added 1 books in 2.0 seconds

Latest version of edrm 6.6.2 and Calibre
https://github.com/apprenticeharper/DeDRM_tools/issues/new

**Comment by ElleKayEm** [comment]
From the log:

>  This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

**Comment by jamosb** [comment]
Some unlimited work they probably do not have protection I am guessing

**Comment by jamosb** [comment]
On a side note it looks like nook study is now blocked by BnN also so no go on those books.

**Comment by ElleKayEm** [comment]
Some have had success with the Windows store Nook app.

**Comment by jamosb** [comment]
I have that installed no go for me.

**Comment by jamosb** [comment]
Closed issue was it doesnt work with amazon unlimited books.
