### ISSUE TITLE
Calibre is not DeDRMing books

### ISSUE THREAD

**Issue by Johaara** [apprenticeharper/DeDRM_tools#795]
This is the first time I'm attempting to DeDRM my kindle books. 

Heres the log:
calibre Debug log
calibre 3.40.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 2)
calibre 3.40.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 2)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[1.23] main UI initialized...
[1.23] Hiding splash screen
[1.23] splash screen hidden
[1.23] Started up in 1.23 seconds with 2 books
DeDRM v6.6.2: Trying to decrypt B076B1QYXK_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Complete Stories and Poems of Edgar Allen Poe
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.2: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.2: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 572, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
2019-03-21 20:05:35.161 Calibre[22667:2372998] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.135537862778
Job: 1 Convert book 1 of 1 (Complete Stories and Poems of Edgar Allen Poe) finished
Convert book 1 of 1 (Complete Stories and Poems of Edgar Allen Poe)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'/var/folders/h3/5x9wpdcx6v5f89507k2d0s9h0000gn/C/calibre_3.40.1_tmp_Bo21bK/oRAwy_.opf'
	  output_profile: 'generic_eink'
	  verbose: 2
	  cover: u'/var/folders/h3/5x9wpdcx6v5f89507k2d0s9h0000gn/C/calibre_3.40.1_tmp_Bo21bK/FXo3fS.jpeg'
	Resolved conversion options
	calibre version: 3.40.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/h3/5x9wpdcx6v5f89507k2d0s9h0000gn/C/calibre_3.40.1_tmp_Bo21bK/FXo3fS.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10f049250>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x10f049650>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/h3/5x9wpdcx6v5f89507k2d0s9h0000gn/C/calibre_3.40.1_tmp_Bo21bK/oRAwy_.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: Complete Stories and Poems of Edgar Allen Poe
	InputFormatPlugin: MOBI Input running
	on /var/folders/h3/5x9wpdcx6v5f89507k2d0s9h0000gn/C/calibre_3.40.1_tmp_Bo21bK/OswrUD.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pm2019-03-21 20:05:41.118 Calibre[22671:2373044] deliverNotificationWithTitle()
* Notification delivered.

**Comment by ElleKayEm** [comment]
Kindle for Mac and calibre with DeDRM need to be on the same machine and user.  If you have Kindle for Mac 1.25 or later, see this post about getting the book in a format that can be DeDRMed:

https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

See this post for more on avoiding or dealing with Amazon's KFX format:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Johaara** [comment]
They are, I also don't own a kindle i actually have a nook, I'm trying to save my books from my kindle for mac app onto my computer to move them to my nook

**Comment by Johaara** [comment]
I also already dealt with the KFX format using the terminal commands

**Comment by ElleKayEm** [comment]
And the link I gave above about using Kindle for Mac **version 1.25** didn't help?

https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by Johaara** [comment]
well i already am using the 1.25.2 version of the kindle app, and thats how I've been downloading the books? Im not entirely sure where else to go from there.

**Comment by ElleKayEm** [comment]
Hmm, well, you could try going back to Kindle for Mac 1.23 or earlier.  There's a link for the download in the other post I mentioned:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Johaara** [comment]
ok so im using kindle version 1.23 now, and i cannot find where its storing my books so now when i download the books theyre not appearing in the same file as before? But i cant find the file theyre being stored in

**Comment by ElleKayEm** [comment]
The FAQs list a couple locations:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#macintosh-1

**Comment by Johaara** [comment]
Either the book doesnt appear there, or when i think ive found the proper file Calibre adds a completely different or random document but never the book. It would download the book perfectly fine on the newest version of the kindle app it just wouldnt strip the DRM.

**Comment by Johaara** [comment]
Here's the log, i know its the correct folder because i checked the prefrences in kindle and it tells me where its being stored. Unless somehow thats incorrect, im not sure where to go from here

calibre Debug log
calibre 3.40.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 2)
calibre 3.40.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 2)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[1.12] main UI initialized...
[1.12] Hiding splash screen
[1.12] splash screen hidden
[1.12] Started up in 1.12 seconds with 1 books
2019-03-22 13:59:09.576 Calibre[24712:2492944] deliverNotificationWithTitle()
* Notification delivered.

**Comment by ElleKayEm** [comment]
You've downloaded new copies with Kindle for Mac 1.23 and it shows them downloaded in the app?  What happens if you try to open and read one in Kindle for Mac?

**Comment by Johaara** [comment]
It doesnt even show them downloaded when i do, i assume because calibre automatically deletes it, ive tried multiple times to have them copied into a different folder and they still don't appear. I can see the book just fine in kindle. But they dont come up as downloaded in the app.

**Comment by ElleKayEm** [comment]
You've lost me.  They don't show as downloaded in Kindle for Mac?  You can't see the files in Finder where they are suppose to be?  But you can open and read them in Kindle for Mac?

As far as I know, the only time calibre automatically deletes books is if you have it set to automatically add books from a folder.

**Comment by Johaara** [comment]
I have it set to automatically convert and add books when theyre downloaded through kindle. In the app they do not appear under downloaded but if i click it the book comes up and i am able to read it.

**Comment by ElleKayEm** [comment]
Ok, then shut off the auto add so you can troubleshoot the DRM removal by manually adding a book with calibre in debug mode.

**Comment by Johaara** [comment]
I can only find these two files and not the actual book, when i try to add it this is what appears in Calibre

calibre Debug log
calibre 3.40.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 2)
calibre 3.40.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 2)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
[1.09] main UI initialized...
[1.09] Hiding splash screen
[1.17] splash screen hidden
[1.17] Started up in 1.17 seconds with 1 books
objc[25693]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa92dd210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11d99cdc8). One of the two will be used. Which one is undefined.
DeDRM v6.6.2: Trying to decrypt B076B1QYXK_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.6.2: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.2: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/crystal/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '51f92c951526' and UserName 'crystal'
DeDRM v6.6.2: Found 1 new key
DeDRM v6.6.2: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 572, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.2: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 284, in get_metadata
  File "site-packages/calibre/ebooks/metadata/mobi.py", line 495, in get_metadata
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 284, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 312, in identity
MobiError: Unknown book type: ¢Åƒﬁùå
Added B076B1QYXK EBOK to db in: 0.0
Added 1 books in 1.1 seconds
Worker Launch took: 0.0961101055145
Added CR!YTTG69D0TN0RB2T6WM2ZEZ3WSW1F.azw to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by ElleKayEm** [comment]
This is a KFX book which you can DeDRM if you also install the KFX Input plugin.  To avoid the KFX format, follow method 2 here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Johaara** [comment]
I already did method 2

**Comment by Johaara** [comment]
Its actually
 working now! thank you very much!!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by davertay** [comment]
FYI as an extra data point, I had the exact same issue with K4Mac v1.25.2 (clean install on a new machine), using method 2 and the extra workaround instructions from odamizu it was still failing, stack trace:
```
Python function terminated unexpectedly: [BOOK TITLE REDACTED]
	InputFormatPlugin: MOBI Input running
	on /var/folders/jb/l1nx7b9959gd5bdcb6cc8p780000gn/C/calibre_3.40.1_tmp_AIio9a/1ytkA7.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 199, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
	  File "site-packages/calibre/customize/conversion.py", line 244, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 45, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 157, in check_for_drm
```
After reverting back to version 1.23.1 and using the exact same procedure it works fine. It seems there is something with v1.25.2 that is being unkind.

**Comment by ElleKayEm** [comment]
Yeah, the workaround let's you download a KF8 (AZW3) format book, but it looks like DeDRM still can't find the key for 1.25.
