### ISSUE TITLE
DeDRM not working

### ISSUE THREAD

**Issue by shimmerr** [apprenticeharper/DeDRM_tools#796]
Hello, 

I downloaded the .azw3 from the amazon content/device page. The device is for Mac. I even downloaded the mac/KFX file/plugin and that didn't work either... please help!

calibre Debug log
calibre 3.40.1  embedded-python: True is64bit: True
Darwin-14.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.5.0', 'Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.10.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 2)
calibre 3.40.1  embedded-python: True is64bit: True
Darwin-14.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.5.0', 'Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.10.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 2)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.29] db initialized
[0.29] Constructing main UI...
[1.53] main UI initialized...
[1.53] Hiding splash screen
[1.58] splash screen hidden
[1.59] Started up in 1.59 seconds with 139 books
DeDRM v6.6.2: Trying to decrypt Marry Him_ The Case for Settling for Mr. Good Enough.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Marry Him: The Case for Settling for Mr. Good Enough
Got DSN key from database default_key
Found 6 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.2: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.6.2: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/samuelshim/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '01fbc5a34088' and UserName 'samuelshim'
DeDRM v6.6.2: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 572, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.2: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) for the device (Kindle for Mac isn't a choice) and enter its serial number into the plugin customization.  If you don't have an E-ink Kindle, then download the book with Kindle for Mac on the same machine and user.  You don't have the KFX plugin installed here.  But you can avoid KFX files by using method 2 here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by shimmerr** [comment]
Thanks but kinda weird. I'm able to download the E-ink Kindle file but in devices, only my kindle for mac shows up. I ended up sharing the book with another amazon kindle account that has a kindle registered. Downloaded it and then input the kindle serial code into the DeDRM plug-in. Thanks again!
