### ISSUE TITLE
FeatureRequest [standalone osx app] -  moving the dialog boxes into OSX notification?

### ISSUE THREAD

**Issue by seasaltseasalt** [apprenticeharper/DeDRM_tools#8]
Standalone mac app- could we please consider moving the dialog boxes into OSX notification. (Then each user can select banner or alert to their preference). 

Currently the app interrupts my workflow as dock icon bounces until I accept the "Thanks" dialog. 
Perhaps even have a preference option, only notify me when there is a problem. 

Thankyou.

**Comment by apprenticeharper** [comment]
I won't be working on this feature request myself, but I'll happily include it if someone else writes it.

**Comment by apprenticeharper** [comment]
The Mac DeDRM application is a plain AppleScript, editable with Script Editor. If anyone wants to contribute to it, please do so.

**Comment by seasaltseasalt** [comment]
hello: Thankyou apprenticeharper. I do not know AppleScript but I know how to edit and follow an existing AppleScript script. However my friend tried to help me out. This works except when the file has no dedrm, you get the old popup that halts the processing. So you must click DRM icon and then click OK. This use-case is rare (file not having drm), so for me its a great solution as now notifications are going thru the OSX notification panel. 

Edit the main.scpt (found by show package resources \DeDRM.app\contents\resources\scripts)
edit the script as below, -- commenting out existing and adding new lines to use the standard OSX notification panel
(sorry I do not know how to give precise where, as there is no line numbers in script editor)

" & ErrorList buttons {"Bother"} with title "DeDRM" default button 1
	end if
	if CompletedCount > 0 then
		set CompletedText to ""
		if CompletedCount is 1 then
			set CompletedText to "Successfully de-drmed 1 ebook:"
		else
			set CompletedText to "Successfully de-drmed " & CompletedCount & " ebooks:"
		end if
		writetolog(CompletedText)
		writetolog(CompletedList)
		
		-- set dialogresult to display dialog CompletedText & "
		
		-- " & CompletedList buttons {"Thanks"} with title "DeDRM"
		-- added a display notification removing any thanks button
		display notification CompletedList with title CompletedText
		
	end if
	return CompletedCount + WarningCount + ErrorCount
	
end ProcessItems

**Comment by apprenticeharper** [comment]
Since the current Kindle for Mac can't run on the older Mac OS X versions, I've switching the messages on completion of drag&drop operations to be notifications rather than dialogs.This will be in 6.4.3

**Comment by apprenticeharper** [comment]
6.4.3 is ready to go, but I'd like to get confirmation that it's all working. Please give this version a go:
[DeDRM_Macintosh_Application.zip](https://github.com/apprenticeharper/DeDRM_tools/files/235950/DeDRM_Macintosh_Application.zip)

**Comment by apprenticeharper** [comment]
6.4.3 released
