### ISSUE TITLE
Kindle for PC decryption fails with version 1.15.0.43061

### ISSUE THREAD

**Issue by apprenticeharper** [apprenticeharper/DeDRM_tools#80]
The decryption key is not recovered for new installations of Kindle for PC 1.15.0.43061. Similar problems with Kindle for Mac.

**Comment by apprenticeharper** [comment]
I think I have found a solution for Kindle for PC. A test solution should be available early in the week of 14th March. Kindle for Mac seems trickier.

**Comment by mazyi** [comment]
Thanks a lot for your work!

**Comment by DB99** [comment]
Seconded.  Thanks for your efforts.  For what it is worth, it appears Amazon has been planning this for a while.  I tried installing older K4PC versions on a new Windows 10 with no luck.  The older versions I tried seemed to support the new key encryption.  My inference is that all versions of K4PC which have not expired have support for the new key encryption.

**Comment by beckolamuffin** [comment]
I am having the same issue with new and some updated installs Kindle for PC 1.15.0.43061 (Windows 7 in my case). Further, it looks like this new version of K4PC will be forced down to all users.  I saw a notice while working on this issue that if I don't update after 30 March 2016, I won't be able to read my books in K4PC until I update it.

**Comment by ElleKayEm** [comment]
I've seen reports on the blog that the key can't be retrieved for any new installation of Kindle for PC/Mac for all non-expired versions -- 1.12 to 1.15, I believe.

**Comment by apprenticeharper** [comment]
First attempt at a fix for Kindle for PC now release as v6.4.0.

**Comment by star-buck** [comment]
still fails here, debug output:

calibre 2.53 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 2.66 seconds with 36 books
DeDRM v6.4.0: Trying to decrypt XYZ.tpz
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting Topaz ebook: XYZ
Found 0 keys to try after 0.1 seconds
DeDRM v6.4.0: Failed to decrypt with error: No key found in 0 keys tried. Read t
he FAQs at Alf's blog: http://apprenticealf.wordpress.com/
DeDRM v6.4.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in ...\AppData\Local
Found K4PC 1.9+ kinf2011 file: ...\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '(obmitted)' and UserName '(obmitted)'
DeDRM v6.4.0: Found 1 new key
Decrypting Topaz ebook: XYZ.tpz
Found 4 keys to try after 0.2 seconds
Trying: (obmitted)
Trying: (obmitted)
Trying: (obmitted)
Trying: (obmitted)
DeDRM v6.4.0: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 153, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 598, in run
  File "calibre_plugins.dedrm.__init__", line 548, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.0: Ultimately failed to decrypt after 0.2 seconds

**Comment by mico1964** [comment]
Thanks for your work, just tried release 6.4.0 (Kindle for PC 1.15.0.43061, calibre 2.53 64, Win 7 64) and deDRMed and converted to EPUB 44 out of 44 .azw files without any problem.

**Comment by DB99** [comment]
Worked fine for me.  Recent install of Windows 10.  Only put Calibre and Kindle4PC on a couple of days ago to test this problem.  To test I installed the updated plugin, uninstalled Kindle4PC, deleted the downloaded books folder, rebooted and reinstalled Kindle4PC.  I also deleted the existing Kindle4PC instances from mu Amazon account.  I downloaded a book with DRM which had consistently failed to decrypt.  I made sure iit was opening okay in K4PC, then imported it into Calibre and DRM was removed.  I can open it in Calibre's viewer and read it with no problems.

It may be worth going to the trouble of ensuring a clean install of Kindle4PC and a fresh download of your books.

**Comment by star-buck** [comment]
@DB99 : Did you import a TPZ book? If so, how exactly did you import it?

**Comment by DB99** [comment]
Sorry.  No.  Just a normal ..azw.  :So far I've never been unfortunate enough to come across a .tpz in the wild.

**Comment by ElleKayEm** [comment]
Was that book downloaded with your current installation of Kindle for PC located on the same machine and user as caliber?

**Comment by apprenticeharper** [comment]
star-buck's installation clearly found the Kindle for PC keys. Any problem decrypting his book is a separate issue.

**Comment by ElleKayEm** [comment]
@apprenticeharper  oh, yes, that's true.

@star-buck Download the book with your current installation of Kindle for PC, and import that copy into calibre.  If it still won't decrypt, open a new issue.

**Comment by star-buck** [comment]
Okay, deleted the whole program, installed and downloaded again, now it appears as awz in the folder, not tpz. Imported just fine, so I wonder what happened with that tpz file before (was installing and doing the same thing just yesterday, and same book was tpz, now aws).
Thanks for all helping and doing the right thing with this software! :100:

**Comment by akadaedalus** [comment]
I confirmed this worked for me too.  By lousy coincidence I made my first Kindle purchase in years yesterday and was "forced" to use the Kindle Android app to read it.  Much appreciated.
