### ISSUE TITLE
DeDRM v6.6.3: Ultimately failed to decrypt

### ISSUE THREAD

**Issue by sekazi** [apprenticeharper/DeDRM_tools#801]
I am using Kindle For PC v1.17.44170 on Windows 10
[tmp45xkc7.txt](https://github.com/apprenticeharper/DeDRM_tools/files/3051991/tmp45xkc7.txt)

**Comment by ElleKayEm** [comment]
This book was downloaded with the current installation of Kindle for PC on the same machine and user as calibre with DeDRM?

**Comment by sekazi** [comment]
Yes everything is on the same computer. I originally had Kindle For PC v1.21.48017 installed which worked fine for me up until this download. I was also on DeDRM v6.6.2 and am on Calibre 3.40.1. After not getting it to work I upgraded to DeDRM v6.6.3. It did not solve the issue so I looked online and found going to Kindle For PC v1.17.44170 would possibly work. I downloaded it and verified the SHA-1 was correct. I uninstalled the newer Kindle For PC and deleted the My Kindle Content folder in Documents and also removed it from my Devices on my Amazon account. I installed v1.17.44170 and signed into my Amazon account and redownloaded the manga. The log file attached is the one from that download. I also tried downloading it directly from the Amazon site with no luck.

**Comment by ElleKayEm** [comment]
There still might be something left behind by the previous installation of Kindle for PC.  Try following these uninstall/reinstall instructions:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

As for the book downloaded from the website, you need to choose an E-ink Kindle for the device and enter its serial number into the plugin configuration.

**Comment by sekazi** [comment]
Still no luck. The folder in the AppData was empty. I still deleted it and reinstalled everything and did not work. I attached a new log which likely will not tell anything different than the first. I also downloaded another manga to see if they still work and they do. The log for that is also attached.
[tmp2f9xta.txt](https://github.com/apprenticeharper/DeDRM_tools/files/3052140/tmp2f9xta.txt)
[tmploghqw.txt](https://github.com/apprenticeharper/DeDRM_tools/files/3052141/tmploghqw.txt)

**Comment by ElleKayEm** [comment]
So it's just the one book?  Others downloaded the same way work?  In that case, it's not that it can't find the key.  You might have better luck using 64-bit calibre.

**Comment by sekazi** [comment]
Well that is just weird. Using 64-bit calibre solved the issue. Thanks for the help.

**Comment by ElleKayEm** [comment]
That can happen with large files.  If you're all set, you can close the issue.
