### ISSUE TITLE
Cannot find the DeDRM_plugin.zip file

### ISSUE THREAD

**Issue by Divine-Knight** [apprenticeharper/DeDRM_tools#803]
I have unzipped the entire DeDRM_tools-master.zip file and have searched the DeDRM_calibre_plugin folder, but the DeDRM_plugin.zip file is nowhere to be seen. I've made sure I'm looking at the unzipped folder and not the zipped file multiple times, and have searched the other folders in the unzipped folder, but the DeDRM_plugin.zip file is nowhere to be seen. I tried checking the actual code on Github here and still couldn't see the file in the DeDRM_calibre_plugin folder.

**Comment by ElleKayEm** [comment]
Go to [this page](https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.6.3).  Click the top link under Assets for DeDRM_tools_6.6.3.zip.

**Comment by Divine-Knight** [comment]
Thank you so much, this solved my problem!
