### ISSUE TITLE
DRM removal not working

### ISSUE THREAD

**Issue by twestheimer** [apprenticeharper/DeDRM_tools#805]
Windows 10 computer
Kindle for PC V 1.17
Calibre 
Book obtained from Amazon.com 
Log:
calibre Debug log
calibre 3.40.1  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.40.1  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.643076923 x 133.900578035
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
[1.36] main UI initialized...
[1.36] Hiding splash screen
[66.58] splash screen hidden
[66.58] Started up in 66.58 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xb7\x8b\xd9\x13"\x17\x0f\xb9\x80g\xa6\xff\xaa1=m"\xee\x1f\xdf\xcd?\x95\xe4@\xb8}\xdf\x18\xf3\x8d\xf8', 'C:\\Users\\tom\\Documents\\My Kindle Content\\Russian Peace Threat B07DYYWM7G_EBOK\\CR!BY1YNKNZS94BD1G9YJ04JVHHG89G.azw.md']
Added CR!BY1YNKNZS94BD1G9YJ04JVHHG89G.azw to db in: 0.3
Added 1 books in 0.7 seconds

**Comment by ElleKayEm** [comment]
Looks like you added a file that wasn't actually the main book file to calibre.  DeDRM didn't even try to decrypt it.  Also, this book must not have been downloaded with version 1.17 because an "azw.md" file is part of the KFX format.  Either K4PC updated or you didn't redownload your books after downgrading from a newer version.  See the bottom of the first post here about preventing unwanted updates:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by twestheimer** [comment]
Thanks so much for your prompt response. I guess I'm feeling pretty stupid
right now that I didn't re-download it :-)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by twestheimer** [comment]
thanks so much
