### ISSUE TITLE
DeDRM does not work on Ubuntu 

### ISSUE THREAD

**Issue by gambr** [apprenticeharper/DeDRM_tools#806]
Hi,
I already used successfully DeDRM with an old PC with Ubuntu and Calibre but now it does not work with the new PC.
Ubuntu 18.10
Calibre 3.31.1
DeDRM Tools 6.6.3 (but also tried with 6.6.2)

First of all I tried to unlock a recent book in KFX format (and I added for that KFX Input plugin 1.14.0). Then I tried a book in azw3 format of 2016, from my Kindle and serial number, but I always get the same message: "This book is locked by DRM".

What should I do then? Is there a known issue? Or is there a library or else missing on my Ubuntu?

Regards,
Gianni

**Comment by ElleKayEm** [comment]
DeDRM isn't working yet with Kindle for PC version 1.25 or newer or with Kindle firmware 5.10.2 or newer.  So try an earlier version of Kindle for PC.

An AZW3 format from or for an E-ink Kindle (not a Fire) should work if you have the serial number entered correctly.

**Comment by gambr** [comment]
I do not use any Kindle for PC, I'm on Linux Ubuntu. An since I tried an AZW3 file that I got from my old Kindle and used my serial that worked a long time ago with an old PC, then the problem must be another one.

**Comment by gambr** [comment]
Anyway, the recent kindle firmware is indeed newer than 5.10 (5.11. ...). But the SN of the old kindle (my device) from which I got the AZW3 file, is correct.

**Comment by gambr** [comment]
Is there a log file to understand what's going wrong in detail?

**Comment by ElleKayEm** [comment]
Ok, some Linux users have Kindle for PC running under Wine or something.  Here's how to get the log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by gambr** [comment]
Here is the log. It seems a python error.
[tmpi5xjd8.txt](https://github.com/apprenticeharper/DeDRM_tools/files/3076763/tmpi5xjd8.txt)

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add  the book to calibre, not during conversion.  I don't see the book being added in that log.

**Comment by gambr** [comment]
OK, I removed the book from library and added again and it worked. We can close the case, thanks.

**Comment by ElleKayEm** [comment]
You can close the issue if you're all set.

**Comment by gambr** [comment]
Since the other problem of this topic is a known issue, I'm closing this case.
