### ISSUE TITLE
Plugin file for calibre is missing

### ISSUE THREAD

**Issue by jcguu95** [apprenticeharper/DeDRM_tools#809]
Seems like there should be "DeDRM_calibre_plugin.zip" in contrib/DeDRM_calibre_plugin. But I only found a .txt file.

**Comment by ElleKayEm** [comment]
You're looking at the source code.  Download DeDRM_tools_6.6.3.zip from the releases page.  Unzip it and you'll find DeDRM_plugin.zip inside the DeDRM_calibre_plugin folder.

**Comment by jcguu95** [comment]
Thank you @ElleKayEm . I tried it... but it still cannot decrypt my kindle dictionary. A similar issue, issue #800 , has been brought up days ago.

**Comment by ElleKayEm** [comment]
If you're referring to the built-in Kindle dictionary, that cannot be decrypted.  It doesn't use the same key as the other books in your account.  If it's one you have purchased, then post a log and we'll see what's going on.

**Comment by jcguu95** [comment]
I see. In fact I am trying to make the other program work (https://github.com/wzyboy/kindle_vocab_anki), which asked me to get rid of DRM from the dictionary. I would let the developer know that somehow this no longer works. Thank you very much again.

**Comment by ElleKayEm** [comment]
This has always been true of the built-in dictionaries.  You must need a purchased dictionary for that other program.

**Comment by jcguu95** [comment]
Thank you very much @ElleKayEm ! I have confirmed with the developer that DeDRM does not work for built-in dictionaries!
