### ISSUE TITLE
Character Encoding Choice Support (Cyrillic) 

### ISSUE THREAD

**Issue by sgloutnikov** [apprenticeharper/DeDRM_tools#81]
Used DeDRM Calibre Plugin to strip an Adobe protected ePub which was in Cyrillic. The resulting file did not convert properly, with most Cyrillic characters throughout the book being mangled up. A few, like the titles did convert however, which leads me to assume that maybe original file from the store was not properly structured, if DeDRM does support Cyrillic characters? 

![Page 1](https://cloud.githubusercontent.com/assets/2321958/13767781/a91cb186-ea2b-11e5-8866-64895f2f3466.jpg)
![Page 2](https://cloud.githubusercontent.com/assets/2321958/13767780/a91b6aba-ea2b-11e5-8c22-d36852e374fa.jpg)

**Comment by apprenticeharper** [comment]
First check that this isn't a problem with the calibre viewer - open the DRM free copy in Adobe Digital Editions.

**Comment by sgloutnikov** [comment]
Indeed. The DRM free copy is fine in Adobe Digital Editions. Also screwed up on the Kindle though, when I converted to .mobi. I'll thinker with Calibre in the future.

**Comment by apprenticeharper** [comment]
I'm sure Kovid would appreciate a bug report at the calibre web site, with the file that doesn't work attached (the DRM-free version, of course).

**Comment by sgloutnikov** [comment]
Yup, I'll move it over to Calibre.
