### ISSUE TITLE
DeDRM produces EPUBs with extra pages

### ISSUE THREAD

**Issue by konomikitten** [apprenticeharper/DeDRM_tools#810]
When I process an epub that came from Adobe Digital Editions the original page count in it 168 pages but when I check the epub that DeDRM produces it has 501 pages, almost 3x the original pages. The extra pages seem to be all blank white pages.

**Comment by ElleKayEm** [comment]
How are you viewing the DRM-free version vs. the DRM version?

**Comment by konomikitten** [comment]
I viewed the drmed version in adobe digital editions and the DRM free one in mupdf and calibre, both showed the extra blank pages.

**Comment by ElleKayEm** [comment]
Try viewing the DRM-free version in ADE.

**Comment by konomikitten** [comment]
The DRM-free version reads correctly in ADE, so I guess not a bug, but that doesn't really help me read it outside of the ADE platform...

**Comment by ElleKayEm** [comment]
Try "converting" it from epub to epub.

**Comment by konomikitten** [comment]
Will try that thanks for your help in advance.

**Comment by konomikitten** [comment]
Unfortunately converting the epub to epub in Calibre didn't fix the issue.

**Comment by konomikitten** [comment]
I think I should stop posting here, after decompressing the epub and looking at it there is definitely not 502 pages, I have a feeling the `volume.opf` has too many entries in it I see multiple item entries in the `<manifest>` node which makes me think that's what is causing issues. Not sure but this is obviously not DeDRMs fault so I feel like it's time to close this issue. Please le me know if it's appropriate to close the issue thanks.

**Comment by ElleKayEm** [comment]
There's probably some way to edit it to get it to work correctly in other readers.  You could look at one that works in calibre's ebook editor and this one to see if there's something obviously wonky.  Someone over at MobileRead's calibre forum might know.

**Comment by ElleKayEm** [comment]
Yes, go ahead and close the issue.  Good luck!

**Comment by konomikitten** [comment]
I managed to fix it so this info is for everyone who had this issue. It turns out there was not extra pages but css issues I went into the css and changed:

````
img {
  margin: 0;
  z-index: 0;
}
````
To:
````
img {
  margin: 0;
  z-index: 0;
  height: 100%;
}
````

It seems the images were overflowing and making the pages larger than they should be. You can change the css in Calibre by right clicking the book -> Edit book.
