### ISSUE TITLE
Question About wineprefix on Linux?

### ISSUE THREAD

**Issue by hhlp** [apprenticeharper/DeDRM_tools#813]
I'm a bit confused/frustrate, what is the parameters that I have to give in the wineprefix in linux 
with python 26 installed for read in calibre books from adobe digital edition 4.5 installed with this plug-in...

echo $WINEPREFIX is blank

![Captura de pantalla de 2019-04-24 19-43-54](https://user-images.githubusercontent.com/2659606/56681305-56aabb00-66c9-11e9-8011-c544c31bb02e.png)

Regards...,

**Comment by ElleKayEm** [comment]
Looks like you have it ~/.wine32.  That said, DeDRM often has trouble finding python under wine.  You may have to run the key script manually and import the key into the plugin.

Also, note that with ADE 4.5, it's possible to get DRM that can't be removed.  Sticking with ADE 2.0.1 is recommended.

**Comment by hhlp** [comment]
> You may have to run the key script manually and import the key into the plugin.

How do I accomplish this task?

**Comment by ElleKayEm** [comment]
Run adobekey.py from the command line.
