### ISSUE TITLE
Can't remove KFX DRM, don't understand

### ISSUE THREAD

**Issue by dxf** [apprenticeharper/DeDRM_tools#818]
I have some KFX books I need to retrieve (long story, relative deleted their Amazon account, recovering Kindle books)

I have the folders with the voucher files inside of them but I don't understand how to make the azws with KFX on them into mobis with the voucher to decrypt it.

Someone help??

**Comment by dxf** [comment]
AAAAnd nevermind. For those wondering, make sure you have the KFX input plugin, and youre dragging the books out of the same folder as the voucher!

**Comment by dxf** [comment]
Never mind once again... https://perfectly-balanced.as-all-things-should.be/i/5n0v.png

Getting this error box, even with Calibre, KFX Input and DeDRM tools plugin installed.

**Comment by ElleKayEm** [comment]
If the account these books are from has been completely deleted, then I think you're probably out of luck.  Post a log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
