### ISSUE TITLE
Cannot open Kindle Paperwhite azw3 file in calibre

### ISSUE THREAD

**Issue by lfmachado1808** [apprenticeharper/DeDRM_tools#819]
Follows log from debug mode:
_________________________________________________________________________________________________________
calibre Debug log
calibre 3.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && KindleUnpack - The Plugin (0, 81, 5) && Kindle Collections (1, 7, 23)
calibre 3.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && KindleUnpack - The Plugin (0, 81, 5) && Kindle Collections (1, 7, 23)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
[1.24] main UI initialized...
[1.24] Hiding splash screen
Storage number map:
{(7L, 0L): [(3L, 'C')], (7L, 1L): [(1L, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\B0241604334201SQ&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=4)
{u'drive_letters': ['D'],
 u'pnp_id_map': {'D': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#b0241604334201sq&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'D': (1L, 1L)}}
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ documents
DEBUG:    0.1 USBMS: scan from root False D:\documents
DEBUG:    0.2 USBMS: count found in cache: 38, count of files in metadata: 38, need_sync: False
DEBUG:    0.2 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 38
DeviceJob: set_books_in_library finished: time= 0.018000125885
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 0 Get device information finished
No details available.
[22.92] splash screen hidden
[22.92] Started up in 22.92 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x8aZ\xe2I\x90\xc3l\xfd\x17S~\xe7y\x15\x99\x83\x08\x062\xcf\xa2bw\x1a\x1c\x9c&"y\x11\x1b\x17', 'D:\\documents\\Sonho grande_ Como Jorge Paulo Lemann, Marcel Telles e Beto Sicupira revolucionaram o capitalismo brasileiro e conquistaram o mundo (Portuguese Edition)_B00C2T1AMO.azw3']
DeDRM v6.6.3: Trying to decrypt Sonho grande_ Como Jorge Paulo Lemann, Marcel Telles e Beto Sicupira revolucionaram o capitalismo brasileiro e conquistaram o mundo (Portuguese Edition)_B00C2T1AMO.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Sonho grande: Como Jorge Paulo Lemann, Marcel Telles e Beto Sicupira  revolucionaram o capitalismo brasileiro e conquistaram o mundo
Found 0 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.7 seconds
searching for kinfoFiles in C:\Users\Fernando\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Sonho grande: Como Jorge Paulo Lemann, Marcel Telles e Beto Sicupira revolucionaram o capitalismo brasileiro e conquistaram o mundo to db in: 3.0
Added 1 books in 5.6 seconds
Worker Launch took: 0.462000131607

_________________________________________________________________________________________________________
Thanks!

Fernando

**Comment by ElleKayEm** [comment]
Looks like you haven't entered your Paperwhite serial number into the plugin customization.

**Comment by lfmachado1808** [comment]
Great. I´ve updated Serial Number and it worked.
Thank you very much!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
