### ISSUE TITLE
Failing to decrpyt : No key found in 2 keys tried

### ISSUE THREAD

**Issue by MTCFrag** [apprenticeharper/DeDRM_tools#821]
calibre Debug log
calibre 3.42  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.42  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 91.745819398
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.05] splash screen shown
[0.05] Initializing db...
[0.05] db initialized
[0.05] Constructing main UI...
[1.19] main UI initialized...
[1.19] Hiding splash screen
[13.86] splash screen hidden
[13.86] Started up in 13.86 seconds with 32 books
DeDRM v6.6.3: Trying to decrypt CompTIA A+ Certification All-in-One Exam Guide, Tenth Edition (Exams 220-1001 & 220-1002).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: CompTIA A+ Certification All-in-One Exam Guide, Tenth Edition (Exams 220-1001 & 220-1002)
Found 2 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Dylan\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added CompTIA A+ Certification All-in-One Exam Guide, Tenth Edition (Exams 220-1001 & 220-1002) to db in: 0.2
Added 1 books in 0.9 seconds

**Comment by ElleKayEm** [comment]
If that's from or for an E-ink Kindle (not a Fire), then make sure you have its serial number entered correctly in the plugin customization.

**Comment by MTCFrag** [comment]
@ElleKayEm  It is for a kindle fire, the serial is correct

**Comment by ElleKayEm** [comment]
If you do not have an E-ink Kindle, then download it with Kindle for PC version 1.24 or earlier.  See this post:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by MTCFrag** [comment]
@ElleKayEm  I already have the book in azw format though not kfx

**Comment by ElleKayEm** [comment]
You cannot remove the DRM from the Kindle Fire book.

**Comment by MTCFrag** [comment]
@ElleKayEm  Any reason?  Or just the plugin does not support kindle fire books?

**Comment by ElleKayEm** [comment]
Unlike the E-ink Kindles, the key isn't connected to the serial number and no method of getting the key from Fire devices has been figured out.

**Comment by MTCFrag** [comment]
If I refund the book and buy it through kindle pc would that work?  Then I could move it over to my kindle?

**Comment by ElleKayEm** [comment]
You don't need to buy it again.  Just download it through Kindle for PC.

**Comment by MTCFrag** [comment]
@ElleKayEm How do I download it through the pc app?  Then what just put it into calibre again?

**Comment by ElleKayEm** [comment]
Once you're logged in, right click the book and choose download.  It will be in My Kindle Content inside your Documents folder.  Add that copy to calibre.  Kindle for PC and calibre need to be on the same machine and user.

**Comment by MTCFrag** [comment]
@ElleKayEm Ok thanks a lot. I did what you said brought it into calibre and converted it to mobi! Thanks.
