### ISSUE TITLE
Obok DeDRM not finding Windows Kobo library

### ISSUE THREAD

**Issue by Shadders78** [apprenticeharper/DeDRM_tools#822]
Using 
Kobo version 5.2.37.0
Windows 10 Pro 64bit
Version 1803
OS build 17134.706

The following error is encountered when trying to use the Obok DeDRM plugin in calibre

> calibre, version 2.85.1
> ERROR: Obok DeDRM v6.5.4: <p>Could not find Kobo Library
> <p>Windows/Mac: do you have Kobo Desktop installed?
> <p>Windows/Mac/Linux: In case you have an Kobo eInk device, connect the device.

The debug text is appended.

[Obok DeDRM error with debug.txt](https://github.com/apprenticeharper/DeDRM_tools/files/3162561/Obok.DeDRM.error.with.debug.txt)

Path for ebook directory for Kobo is 
>C:\Users\...........\AppData\Local\Packages\KoboInc.KoboBooks_vk8qsnw174y90\LocalState\DownloadedBooks

Do you need any more information?

**Comment by ElleKayEm** [comment]
Looks like you're using the Windows 8/10 Kobo app.  You need the [Kobo Desktop app](https://www.kobo.com/us/en/p/desktop).  Latest version with a date of 5/3/2019 is 4.14.10877.  Books are stored in C:\Users\....\AppData\Local\Kobo\Kobo Desktop Edition\kepub.

You also might want to update calibre which is currently on version 3.42.

**Comment by Shadders78** [comment]
Thank you. I followed the link on the email that Kobo sent not realising it's different.
