### ISSUE TITLE
Kindle won't convert; DRM not removed

### ISSUE THREAD

**Issue by Difdrum** [apprenticeharper/DeDRM_tools#826]
Thanks for helping!

calibre Debug log
calibre 3.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 91.8418079096 x 91.8994974874
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[1.92] main UI initialized...
[1.92] Hiding splash screen
[9.45] splash screen hidden
[9.45] Started up in 9.45 seconds with 0 books
DeDRM v6.6.3: Trying to decrypt B07GBRKP32_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Journey of Discovery into Redox Signaling Biology
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\difdr\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\difdr\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\difdr\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2894997141' and UserName '6469666472'
Decrypted key file using IDString '2894997141' and UserName '6469666472'
DeDRM v6.6.3: Found 2 new keys
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Journey of Discovery into Redox Signaling Biology
Got DSN key from database default_key_2
Got DSN key from database default_key_1
Found 7 keys to try after 0.4 seconds
Crypto Type is: 2
File is encoded with PID j78jRFcyYK.
Decrypting. Please wait . . . . done
Decryption succeeded after 0.5 seconds
DeDRM v6.6.3: Saving 2 new keys
DeDRM v6.6.3: Finished after 0.5 seconds
Added A Journey of Discovery into Redox Signaling Biology to db in: 0.3
Added 1 books in 2.7 seconds

**Comment by ElleKayEm** [comment]
You need to use Kindle for PC version 1.24 or earlier.

**Comment by Difdrum** [comment]
ThanksYes, it worked for the 2011 book but not for 2018 one

**Comment by Difdrum** [comment]
I ran it the second time in debug mode and it succeeded.
