### ISSUE TITLE
DRM not removed on .acsm file even with ADE key imported

### ISSUE THREAD

**Issue by makeworld-the-better-one** [apprenticeharper/DeDRM_tools#827]
I'm on Linux, and got my ADE key from running your script on my Mac. I brought the file over to my Linux computer, imported it into the plugin, but when I drag in the ACSM file, it doesn't change the format. Debug mode offers no messages on the subject.

The text of the file is [here](https://pastebin.com/ZNSc32wB).

**Comment by makeworld-the-better-one** [comment]
Update: If I import the .acsm file in ADE on my Mac, then export a DRM .epub file and bring it over to my Linux computer, that will be converted fine by the plugin.

**Comment by ElleKayEm** [comment]
Yes that's how Adobe DRM epubs work.  If you're all set, you can close the issue.

**Comment by makeworld-the-better-one** [comment]
So I can only remove the DRM when I have the ADE program installed? Time to fire up Wine I guess.

**Comment by ElleKayEm** [comment]
Yes, you need ADE to download the actual epub file.

**Comment by makeworld-the-better-one** [comment]
:(

Alright, thanks for explaining everyone. I'll close the issue.
