### ISSUE TITLE
I can no longer add the DeDRM calibre plug-in 6.6.3. to Calibre 3.4.2.0

### ISSUE THREAD

**Issue by serdar0020** [apprenticeharper/DeDRM_tools#828]
I've been using the calibre DeDRM plug-in for quite a while, latest version for the last months 6.6.1. When I recently couldn't open two DRM protected books in a row in calibre 3.4.2.0 64 bit, I removed the plug-in and now I can't re-install it (6.6.3). I get the error message "Exception:File dialog failed (return code - 1073741819)." I've no other DeDRM plug-in installed. I tried to uninstall and re-install calibre, no use. Any ideas? (I used the zip from the "DeDRM_calibre_plugin" folder of the unzipped archive, as usual)

**Comment by ElleKayEm** [comment]
When I google that error message, I find the creator of calibre responding with:

> Something on your computer is blocking the helper process calibre uses
to display file dialogs. Most likely an antivirus/security program. You
can work around it by setting the CALIBRE_NO_NATIVE_FILEDIALOGS
environment variable, as described here: https://manual.calibre-ebook.com/customize.html#environment-variables

So it sounds like a calibre issue rather than something specific to this plugin.

**Comment by serdar0020** [comment]
I'm on windows10. I've deactivated virus&threat protection/real time protection - same error message. And I'm too dumb to understand how to set the "CALIBRE_NO_NATIVE_FILEDIALOGS
environment variable"

**Comment by ElleKayEm** [comment]
I don't know.  I'm also on Windows 10, calibre 3.42, and have no issue loading DeDRM 6.6.3.  Again, seems to be a calibre issue with your system, not specific to DeDRM.  You could try asking about the error message at the MobileRead calibre forums.  You can't discuss DeDRM there, but they might have more info about that error which can occur with other file dialogs as well.

**Comment by serdar0020** [comment]
thanks for your help

**Comment by serdar0020** [comment]
solved with the help from the guys at MobileRead

https://www.mobileread.com/forums/showpost.php?p=3845668&postcount=6

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
