### ISSUE TITLE
Kindle for Mac decryption fails with version 1.15.0.43061

### ISSUE THREAD

**Issue by apprenticeharper** [apprenticeharper/DeDRM_tools#83]
The decryption key is not recovered for new installations of Kindle for Mac 1.15.0.43061

I would like to hear from anyone who still has this problem with DeDRM 6.4.0

**Comment by pdurrant** [comment]
I can't get DeDRM 6.4.0 to fail with a fresh installation of Kindle for Mac 1.15. In fact, I can no longer get it to fail with 6.3.6. I don't understand it - it definitely failed when I first tried a fresh install of 1.15.

**Comment by apprenticeharper** [comment]
I have now had one report of continued problems with 6.4.0. I welcome additional reports to try to get to the root of any problem.

**Comment by apprenticeharper** [comment]
I am still working on the possible Mac problem. Additional reports of success or failure on a Mac Pro would be welcome.

**Comment by cklep** [comment]
If you can walk me through how to give you what you need, I can tell you.  I kindle on macbook pro is failing for me as well.

**Comment by apprenticeharper** [comment]
The Mac problem I'm working on at the moment does not apply to MacBook Pro, only Mac Pro with bonded Ethernet ports. If you are having problems on a MacBook Pro, posting an import log in a new issue is the way to go.

**Comment by apprenticeharper** [comment]
The original problem seemed to be fixed by 6.4.0. The bonded Ethernet ports problem will be fixed in 6.4.3

**Comment by apprenticeharper** [comment]
6.4.3 is ready to go, but I'd like to get confirmation that it's all working. Please give this version a go:
[DeDRM_plugin.zip](https://github.com/apprenticeharper/DeDRM_tools/files/235943/DeDRM_plugin.zip)
[DeDRM_Macintosh_Application.zip](https://github.com/apprenticeharper/DeDRM_tools/files/235950/DeDRM_Macintosh_Application.zip)

**Comment by apprenticeharper** [comment]
6.4.3 released
