### ISSUE TITLE
not working mac

### ISSUE THREAD

**Issue by johnsmith11111111** [apprenticeharper/DeDRM_tools#830]
an epub book wouldn't convert (saying DRM issue) so I installed latest version of calibre & installed the DeDRM_plugin.zip plugin. restarted calibre & loaded the epub book & the drm message still came up. i then tried the DeDRM mac application & when I loaded the book it said error with this book. so i've followed all the procedures & nothing has worked. thanks
![Screen Shot 2019-05-15 at 7 31 34 am](https://user-images.githubusercontent.com/50640944/57733730-8d318f80-76e3-11e9-9733-1f4961013ee2.png)

**Comment by ElleKayEm** [comment]
Post a log.

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by NathanRightnour** [comment]
Same issue here. Just installed Calibre, DeDRM and KFX so all it latest versions. macOS Sierra latest.

calibre Debug log
calibre 3.42  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 16, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 16, 0) && KFX metadata reader (from KFX Input) (1, 16, 0) && KFX Input (1, 16, 0) && Set KFX metadata (from KFX Output) (1, 29, 0) && KFX Output (1, 29, 0)
calibre 3.42  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 16, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 16, 0) && KFX metadata reader (from KFX Input) (1, 16, 0) && KFX Input (1, 16, 0) && Set KFX metadata (from KFX Output) (1, 29, 0) && KFX Output (1, 29, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 102.000001532 x 103.000001547
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.18] db initialized
[0.18] Constructing main UI...
[1.06] main UI initialized...
[1.06] Hiding splash screen
[1.07] splash screen hidden
[1.07] Started up in 1.07 seconds with 1 books
DeDRM v6.6.3: Trying to decrypt As a Man Thinketh.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: As a Man Thinketh
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/~/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'adc7c3692708' and UserName ‘~’
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: As a Man Thinketh
Got DSN key from database default_key_1
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added As a Man Thinketh to db in: 0.0
Added 1 books in 0.8 seconds
2019-05-17 17:51:35.689 Calibre[35486:1111390] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.122419118881
Job: 0 Convert book 1 of 1 (As a Man Thinketh) finished
Convert book 1 of 1 (As a Man Thinketh)
	Conversion options changed from defaults:
	  output_profile: 'kindle_pw3'
	  verbose: 2
	  read_metadata_from_opf: u'/var/folders/m3/7zg15vkx5r91ktgg3z8cgzwc0000gn/C/calibre_3.42.0_tmp_zWLOXy/uP3l1j.opf'
	  cover: u'/var/folders/m3/7zg15vkx5r91ktgg3z8cgzwc0000gn/C/calibre_3.42.0_tmp_zWLOXy/ztUCCx.jpeg'
	Resolved conversion options
	calibre version: 3.42.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/m3/7zg15vkx5r91ktgg3z8cgzwc0000gn/C/calibre_3.42.0_tmp_zWLOXy/ztUCCx.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x11348ca50>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x1134a8290>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/m3/7zg15vkx5r91ktgg3z8cgzwc0000gn/C/calibre_3.42.0_tmp_zWLOXy/uP3l1j.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/m3/7zg15vkx5r91ktgg3z8cgzwc0000gn/C/calibre_3.42.0_tmp_zWLOXy/bw58SN.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly: As a Man Thinketh
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 200, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1107, in run
	  File "site-packages/calibre/customize/conversion.py", line 245, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 46, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 87, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: As a Man Thinketh

**Comment by ElleKayEm** [comment]
When you have a book for "download & transfer via USB", you need to choose an E-ink Kindle (not a Fire) for the device.  And enter the Kindle's serial number into the plugin customization.

If you don't have an E-ink Kindle, then use Kindle for Mac which it appears you have on this machine.

**Comment by NathanR-85** [comment]
Thanks for that info. Unfortunately, amazon doesn’t allow me to choose Kindle for Mac when I download for USB. I can however download it directly to my Kindle for Mac using the amazon interface. 

I have a Paperwhite so I’ll try that. Thanks!

**Comment by ElleKayEm** [comment]
No, it's not possible to download & transfer via USB for Kindle for Mac -- no reason to do so anyway.  As you said, you just download it via the app itself. But it should work for the Paperwhite too.
