### ISSUE TITLE
request: add support to ibooks/ apple books

### ISSUE THREAD

**Issue by hiworld3** [apprenticeharper/DeDRM_tools#831]
some super rare books are only on there as epub, thanks...

**Comment by ElleKayEm** [comment]
There was a free app like this for iBooks called Requiem.  But development on that stopped years ago.  Now I think there might be some apps for purchase, but I would be leery of them.  If it's just a few extremely rare books that are only available there, then it's not likely that anyone will figure it out and share it here.  The tools here are all created and maintained on a completely volunteer basis.  I'm sure Apprentice Harper would be happy to add it if someone shared it.  But there's not a lot of insentive for anyone to do so.

**Comment by apprenticeharper** [comment]
Exactly so.
