### ISSUE TITLE
Cannot open kfx in calibre with last versions of calibre and DeDRM tool

### ISSUE THREAD

**Issue by OscarNewOne** [apprenticeharper/DeDRM_tools#832]
Hi,
Was using Calibre + DeDRM tool succesfully, but didn't work for my last .kfx purchase. Updated calibre to 3.42 and installed DeDRM 6.6.3. But cannot open (and convert, wich is what I need).
Below is the log I get on debug mode. 
Thanks, if anyone can help.

calibre 3.42  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 16, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 16, 0) && Set KFX metadata (from KFX Output) (1, 29, 0) && KFX Output (1, 29, 0) && TTS to MP3 (0, 1, 3) && KFX metadata reader (from KFX Input) (1, 16, 0) && KFX Input (1, 16, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 42.4069565217 x 42.2030769231
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.06] db initialized
[0.06] Constructing main UI...
[1.08] main UI initialized...
[1.08] Hiding splash screen
[1.73] splash screen hidden
[1.73] Started up in 1.73 seconds with 23 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["'\xe2s[\xd2V\xef8&\xe2\xe1\xb6\x9af\xa1\xe0F7\xe0\x8b`\xee\xbf\xab\xc6+\x98t\xb4M\x94X", 'C:\\Users\\Oxxx\\Documents\\My Kindle Content\\B00XXXWRZC_EBOK\\B00XXXWRZC_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.16.0: Importing C:\Users\Oxxx\Documents\My Kindle Content\B00XXXWRZC_EBOK\B00AR2XXXWRZC_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Oxxx\AppData\Local\Temp\calibre_zbuhvw\izsj4w.kfx-zip
DeDRM v6.6.3: Trying to decrypt izsj4w.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: izsj4w
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.8249b5fd-69ab-4d2a-a0df-8ec2acf612bf.voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Oxxx\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\Oxxx\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1646498858' and UserName '4f6c6976696572'
DeDRM v6.6.3: Found 1 new key
Decrypting KFX-ZIP ebook: izsj4w
Got DSN key from database default_key_1
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.8249b5fd-69ab-4d2a-a0df-8ec2acf612bf.voucher
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.16.0: Packaging C:\Users\Olivier\AppData\Local\Temp\calibre_zbuhvw\izsj4w.kfx-zip
Processing container: B00XXXWRZC_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 152, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 263, in get_container
KFXDRMError: Book container B00XXXWRZC_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Oxxx\AppData\Local\Temp\calibre_zbuhvw\mdtcwm_add_books\0\B00XXXWRZC_EBOK.kfx-zip
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Indestructible Truth to db in: 0.1
Added 1 books in 1.1 seconds

**Comment by OscarNewOne** [comment]
I found that I probably should change my Kindle for PC 1.25 for 1.24... 
Is this ok ?
And what will happen to the Ebooks I already downloaded ?
Thx

**Comment by ElleKayEm** [comment]
Yes, go back to K4PC 1.24 or earlier.  Re-download your books.

**Comment by OscarNewOne** [comment]
Thxs
