### ISSUE TITLE
Failed to Add Book error Calibre 3.42.0, DeDRM 6.6.3

### ISSUE THREAD

**Issue by chaosAD99** [apprenticeharper/DeDRM_tools#833]
When I try to add a Adobe Digital Editions File, I'm getting the following error:

calibre, version 3.42.0
ERROR: Errors while adding: Failed to add any books, click "Show details" for more information

----------------------------------------------------------------------
Failed to add the book: The Life-Changing Magic of Tidying Up
	C:\Users\bvicr\AppData\Local\Temp\calibre_nw4enj\yxqwqg_add_books\0\The Life-Changing Magic of Tidying Up.epub
With error:
Traceback (most recent call last):
  File "site-packages\calibre\gui2\add.py", line 415, in add_book
  File "site-packages\calibre\db\legacy.py", line 226, in create_book_entry
  File "site-packages\calibre\db\cache.py", line 63, in call_func_with_lock
  File "site-packages\calibre\db\cache.py", line 1575, in create_book_entry
  File "site-packages\calibre\db\backend.py", line 875, in execute
  File "c:\t\t\apsw-zu_bhl\apsw-3.27.2-r1\src\cursor.c", line 236, in resetcursor
CantOpenError: CantOpenError: unable to open database file

Also, this is what it says in the log file:

Editions\\Descendant of the Crane.epub']
DeDRM v6.6.3: Trying to decrypt Descendant of the Crane.epub
DeDRM v6.6.3: Verifying zip archive integrity
DeDRM v6.6.3: Descendant of the Crane.epub is a secure Adobe Adept ePub
DeDRM v6.6.3: Trying Encryption key default_key
DeDRM v6.6.3: Decrypted with key default_key after 0.3 seconds
DeDRM v6.6.3: Finished after 0.3 seconds
Added 0 books in 1.2 seconds

Please help!

**Comment by ElleKayEm** [comment]
Your book was successfully DeDRMed.  For issues with calibre, try the calibre forum at MobileRead.  Only thing I can think is you've told calibre to save your books somewhere it can't access or doesn't have sufficient space.

**Comment by chaosAD99** [comment]
I figured it out. It was my antivirus blocking it.  Thank you!
