### ISSUE TITLE
May 2019 - can not convert AZW3 file

### ISSUE THREAD

**Issue by dermusensohn** [apprenticeharper/DeDRM_tools#835]
Hello.  Using the most recent DDRM version and updated Calibre on updated Windows 10 computer.  I can not convert an AZW3 file that I downloaded from Amazon.  Log file below.  I hope it helps.  Thanks.  I love your product.  I hope you are able to get it to work on this new level of blockage.  

calibre Debug log
calibre 3.42  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 16, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 16, 0) && KFX metadata reader (from KFX Input) (1, 16, 0) && KFX Input (1, 16, 0) && Set KFX metadata (from KFX Output) (1, 29, 0) && KFX Output (1, 29, 0)
calibre 3.42  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 16, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 16, 0) && KFX metadata reader (from KFX Input) (1, 16, 0) && KFX Input (1, 16, 0) && Set KFX metadata (from KFX Output) (1, 29, 0) && KFX Output (1, 29, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.643076923 x 133.900578035
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[2.09] main UI initialized...
[2.09] Hiding splash screen
[8.70] splash screen hidden
[8.70] Started up in 8.70 seconds with 227 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['#\x95\xf6\x81\xaa\xb2u\xdcFO\xe1\xe1\n\xa95Y\x92\xaa\x046\xccB\xde;\xe2\xe4m\x89\x8an\xe0C', 'C:\\Users\\dhoff\\Downloads\\The Henry Mancini Collection Songbook.azw3']
DeDRM v6.6.3: Trying to decrypt The Henry Mancini Collection Songbook.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Henry Mancini Collection Songbook
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\dhoff\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Henry Mancini Collection Songbook to db in: 5.5
Added 1 books in 7.4 seconds
Worker Launch took: 0.230999946594
Job: 0 Convert book 1 of 1 (The Henry Mancini Collection Songbook) finished
Convert book 1 of 1 (The Henry Mancini Collection Songbook)
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\dhoff\\AppData\\Local\\Temp\\calibre_6gh7fp\\3rscvr.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\dhoff\\AppData\\Local\\Temp\\calibre_6gh7fp\\fxosul.opf'
	  verbose: 2
	  output_profile: 'kindle_pw3'
	Resolved conversion options
	calibre version: 3.42.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\dhoff\\AppData\\Local\\Temp\\calibre_6gh7fp\\3rscvr.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x050216B0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x05021AB0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Liberation Mono',
	 'pdf_mono_font_size': 16,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'Liberation Sans',
	 'pdf_serif_family': u'Liberation Serif',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\dhoff\\AppData\\Local\\Temp\\calibre_6gh7fp\\fxosul.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\dhoff\AppData\Local\Temp\calibre_6gh7fp\lqf_xa.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  The Henry Mancini Collection Songbook (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 200, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1107, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 46, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 87, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: The Henry Mancini Collection Songbook

**Comment by ElleKayEm** [comment]
When you use the website "download & transfer via USB" option, the device must be an E-ink Kindle (not a Fire) and you need to enter its serial number into the DeDRM plugin customization.

**Comment by dermusensohn** [comment]
Thank you.  I had forgotten about the serial number.  That did the trick.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
