### ISSUE TITLE
Cannot remove DRM on downloaded purchased Kindle book in Calibre

### ISSUE THREAD

**Issue by sgweinst** [apprenticeharper/DeDRM_tools#836]
I tried multiple times to remove the DRM from a few books that I purchased and then downloaded to my computer directly from Amazon. I am using updated Windows 10 on a laptop PC.  I have attached the log from Calibre .
calibre Debug log
calibre 3.42  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.42  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[2.00] main UI initialized...
[2.00] Hiding splash screen
[5.62] splash screen hidden
[5.62] Started up in 5.62 seconds with 780 books
DeDRM v6.6.3: Trying to decrypt Witches of New Moon Beach 05 - Sea Dreams - Meriam Wilhelm.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Sea Dreams (The Witches Of New Moon Beach Book 5)
Got DSN key from database default_key
Got DSN key from database kindlekey1
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 3 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Susan\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\Susan\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '611564336' and UserName '537573616e'
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Sea Dreams (The Witches Of New Moon Beach Book 5) to db in: 0.2
Added 1 books in 1.1 seconds

I like to save my books on my computer. It helps me to keep them organized and on hand so I don;t have to be on wifi to get my books.

**Comment by ElleKayEm** [comment]
You need to use Kindle for PC version 1.24 or earlier.  See this post:  

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by ElleKayEm** [comment]
Nevermind my previous answer.  Just realized that book is probably from the website for download & transfer via USB.  The device needs to be an E-ink Kindle and you need to put its serial number into the DeDRM plugin customization.

**Comment by sgweinst** [comment]
I added the Kindle serial number and then added the book and tried to
convert it. It still wouldn't remove the DRM.

**Comment by ElleKayEm** [comment]
Try using 64-bit calibre.  If that still doesn't work, double-check the serial number.  And it does need to be an E-ink Kindle, not a Fire.

**Comment by sgweinst** [comment]
That worked.
Thanks

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by sgweinst** [comment]
I had to go to the earlier version of Kindle for PC
