### ISSUE TITLE
Watermarking Issue?

### ISSUE THREAD

**Issue by Moscarda** [apprenticeharper/DeDRM_tools#84]
I don't know if your DeDRM tools are merely a standalone version of the Calibre scripts by Apprentice Alf and I**♥**Cabbages, but if so, I have heard from multiple sources that their scripts may remove DRM but can leave in "watermarks" to identify you.  Not visible watermarks, but embedded in the metadata.  I was hesitant to believe this myself, because when I compared their scripts and these apps with a "watermark-fixed" version, they were the same.  In fact the "new" one didn't include any of the purported updates at all.  Just wondering if you've heard anything on this front.

**Comment by ElleKayEm** [comment]
Both the DeDRM stand-alones and the calibre plugin here are updates of the "official"  Apprentice Alf tools.  As you heard, no attempt is made to remove personal identifying information.  Since they're intended for your own personal use, there's no need.

**Comment by apprenticeharper** [comment]
Not only 'can leave in "watermarks" to identify you' but deliberately make no effort to remove any such watermarks. Neither Alf nor I have any interest in producing tools that do such a thing.
