### ISSUE TITLE
Cannot Remove DRM from AZW file from Kindle for PC 1.24

### ISSUE THREAD

**Issue by Mesfaro** [apprenticeharper/DeDRM_tools#842]
Bought the book on amazon, brand new just released today.
First time I've been unable to remove the DRM
Tried on a separate computer with fresh installs, with the same result. Here are my logs.

> 
calibre Debug log
calibre 3.44  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 17, 0) && KFX metadata reader (from KFX Input) (1, 17, 0) && KFX Input (1, 17, 0)
calibre 3.44  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 17, 0) && KFX metadata reader (from KFX Input) (1, 17, 0) && KFX Input (1, 17, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
[1.45] main UI initialized...
[1.45] Hiding splash screen
[177.03] splash screen hidden
[177.03] Started up in 177.03 seconds with 6 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x13\xfb\x96f\x82\xb4\x8e\x92\x14lT:E\xdeP \xc5q\x8b}\xab,\x83\x1dg@\xfcg\x087l\xd7', 'D:\\redacted\\Documents\\My Kindle Content\\B07SVL9CM1_EBOK\\B07SVL9CM1_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.17.0: Importing D:\redacted\Documents\My Kindle Content\B07SVL9CM1_EBOK\B07SVL9CM1_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.3: Trying to decrypt B07SVL9CM1_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 【電子版】ドラゴンエイジ 2019年7月号 [雑誌]
Got DSN key from database default_key
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\redacted\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\redacted\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '849235259' and UserName '4c656520416e6e'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 【電子版】ドラゴンエイジ 2019年7月号 [雑誌]
Got DSN key from database default_key_1
Found 4 keys to try after 0.8 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 【電子版】ドラゴンエイジ 2019年7月号 [雑誌] to db in: 3.4
Added 1 books in 5.1 seconds
Worker Launch took: 0.0939998626709

**Comment by j-howell** [comment]
DRM removal sometimes fails for very large books when using the 32-bit version of calibre. I recommend switching to 64-bit calibre and trying again.

**Comment by Mesfaro** [comment]
OMG I can't believe such a simple solution worked Thank you so much
