### ISSUE TITLE
Cannot start ADE 2.0.1

### ISSUE THREAD

**Issue by JPRidgeway** [apprenticeharper/DeDRM_tools#843]
The ADE 2.0.1 installed from https://www.adobe.com/support/digitaleditions/downloads.html does not start. Ever when forced under administrator, its just does nothing when launched. System is Windows 10 1803.

**Comment by ElleKayEm** [comment]
Huh, works for me on Windows 10.

**Comment by JPRidgeway** [comment]
Problem solved by installing Creative Cloud. How come an old app starts working when having a much newer app also installed, what kind of frameworks it installed - who knows?..

**Comment by ElleKayEm** [comment]
Unrelated to DeDRM.  You can close the issue
