### ISSUE TITLE
Can I covert KFX -> PDF If I have Kindle Firmware 5.10.2 ?

### ISSUE THREAD

**Issue by tinker123456** [apprenticeharper/DeDRM_tools#851]
Operating system: Linux Mint 19
Desktop: Cinnamon 3.8.9
Reader: Amazon Kindle Paper White ( about 2 years old )
Calibre: 3.21.0+dfsg-1 build 1
DeDRM plugin 6.63
KFX Input plugin 1.17.1
Kindle Firmware: 5.10.2 

Can I covert KFX -> PDF If I have Kindle Firmware 5.10.2 with the set up above?

**Comment by j-howell** [comment]
Version 5.10.2 of the Kindle firmware uses new DRM for KFX that is not handled by DeDRM.

Since you have an e-ink Kindle you have the option for most books to obtain it in a different format that will work with DeDRM by using the "Download & transfer via USB" option from the Manage Your Content and Devices page on Amazon's website.

**Comment by ElleKayEm** [comment]
You will need Kindle for PC version 1.24 or earlier (running under Wine).  See this post for other possible options:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by tinker123456** [comment]
> Version 5.10.2 of the Kindle firmware uses new DRM for KFX that is not handled by DeDRM.
> 
> Since you have an e-ink Kindle you have the option for most books to obtain it in a different format that will work with DeDRM by using the "Download & transfer via USB" option from the Manage Your Content and Devices page on Amazon's website.

j-howell, thanks for the information.

Amazon rearranged their UI a bit.

I found a list of the content on Kindle Paperwhite at

https://www.amazon.com/hz/mycd/myx#/home/content/deviceContentBooks/dateDsc/yadayadaSomeCode.

There is a list of books at that link that are on my Paperwhite.  There is a menu button next to each that has an option called 

Download & transfer via USB

as you wrote.

However, when I click on it I only get one choice for where to download, my Paperwhite, where it already is :-).

There are two disabled choices for places to download to
1.  The Cloud readder
2.   Audible for Android

Do I need to install "Kindle for PC" ? ( 1.24 or earlier running under WINE as another poster wrote )

If so, would I go find the file from there to convert?

**Comment by j-howell** [comment]
> However, when I click on it I only get one choice for where to download, my Paperwhite, where it already is :-).

That is the choice you should use. It will download the book to your desktop, with the expectation that you will then copy it to your Paperwhite over USB. Instead you can use that copy to import into calibre.

**Comment by tinker123456** [comment]
> That is the choice you should use. It will download the book to your desktop, with the expectation that you will then copy it to your Paperwhite over USB. Instead you can use that copy to import into calibre.

Thanks.  I got it downloaded as an *.azw3 file.  When I try to convert it with calibre I'm still getting the message that it can't do it because of DRM.   Any ideas?

**Comment by ElleKayEm** [comment]
Enter your Paperwhite's serial number into the plugin customization.

**Comment by tinker123456** [comment]
I selected the AZW4 1.0.0 Input plugin and pressed the "customize" button and got message saying it doesn't need customization.  The caption for the plugin labels it as AZW4 -> HTML.

Probably not what I need. :)

Where can I find an AZW3 -> PDF input plugin?  Tried Google and tried Calibre's find plugin feature

**Comment by ElleKayEm** [comment]
This is the DeDRM plugin.

**Comment by tinker123456** [comment]
I got it work.

Thanks much for all of the help.
