### ISSUE TITLE
Can't remove DRM from new Kindle Paperwhite

### ISSUE THREAD

**Issue by lbhatten** [apprenticeharper/DeDRM_tools#857]
I have used a previous version of DeDRM for a number of years to DeDRM files from a Kindle Touch, first version.  I use Calibre.  I recently upgraded to a Kindle Paperwhite.  I attempted to drop a file from my Kindle Paperwhite into Calibre.  The file was Analog Science fiction.  It was labeled Analog Scien~n and Fact_B07LFXGRC3.pobi.  As I used to do, I renamed it to .azw and dropped it into Calibre.  All looked good until I tried to open it. I got the dreaded DRM message.  I read some more and looked at the serial #.  I was of course my old Kindle # so I deledte it and added the serial # for my Paperwhite.  No Joy.  Below is the data:
Calibre 3.44
Tool used:	DeDRM_Tools_6.6.3
OS:		Win 8.1
File came from:	Kindle Paperwhite 4 (2018) WIFI 8 Gig
No error messages during upload
LOG:
calibre 3.44  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.15+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259 x 93.6245733788
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[1.30] main UI initialized...
[1.30] Hiding splash screen
[1.88] splash screen hidden
[1.88] Started up in 1.88 seconds with 105 books
DeDRM v6.6.3: Trying to decrypt Analog Scien~n and Fact_B07LFXGRC3.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Analog Science Fiction and Fact
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Lyle\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\Lyle\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3665809166' and UserName '4c796c65'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Analog Science Fiction and Fact
Got DSN key from database default_key_1
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Analog Science Fiction and Fact to db in: 2.0
Added 1 books in 2.7 seconds

**Comment by ElleKayEm** [comment]
Make sure you have the serial number entered correctly.  Try copy and paste from the website removing any spaces.  And restart calibre after entering it before trying to add the book again.  Incidentally I don't believe you need to worry about changing the extension from pobi to azw anymore.

**Comment by lbhatten** [comment]
That worked!  Thanks!Lyle

    On Wednesday, July 3, 2019, 9:36:04 PM PDT, ElleKayEm <notifications@github.com> wrote:  
 
 
Make sure you have the serial number entered correctly. Try copy and paste from the website removing any spaces. And restart calibre after entering it before trying to add the book again. Incidentally I don't believe you need to worry about changing the extension from pobi to azw anymore.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
