### ISSUE TITLE
Book is locked by DRM

### ISSUE THREAD

**Issue by gordongrams** [apprenticeharper/DeDRM_tools#858]
I have just spent several frustrating hours trying to install and use Alfs DRM removal pluging on my new Windows 10 x64 OS. I used this for many years on Win 7 x32 without any problem. I've tried installing the plugin in various Calibre preferences folders. The plugin zip installs ok and opens but it will not convert AZW to MOBI or any other format - I get a 'This book is locked by DRM' pop-up. I followed the Debug reboot instuctions. I deleted and reinstalled the book but it still will not convert. Please help!

calibre Debug log
calibre 3.44  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.44  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.0 x 95.9160839161
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
Loaded cached store plugin for: Amazon Kindle at version: 17
Loaded cached store plugin for: Google Books at version: 6
[1.94] main UI initialized...
[1.94] Hiding splash screen
[11.81] splash screen hidden
[11.81] Started up in 11.81 seconds with 22 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xc2\xef\x89\xe5\xa9i\x86Z\xfd\x06F\xa4\xf79\x84\x8c\x058V\x9fT?\x9d\x16\xd8\x108\xeb{\xf5\xd1\x95', 'C:\\Users\\PC\\Downloads\\DeDRM_tools_X.X.X.zip archive.zip']
Loaded cached store plugin for: Amazon Kindle at version: 17
Loaded cached store plugin for: Google Books at version: 6

**Comment by ElleKayEm** [comment]
This log doesn't show you adding a book.

**Comment by gordongrams** [comment]
Thanks for your quick response. I added this book to Calibre library from
my Kindle content on my PC drive C: files. I'm reading it on my Android
phone and my Kindle Oasis.
This is all rather complicated for me, and I don't know another log command
to use other than 'Preferences-Miscellaneous-degub device detection' Please
tell me specifically what to do. Many thanks.


[image: image.png]

calibre 3.44  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
USB devices on system:
(USBDevice(vendor_id=0x45e product_id=0x72d bcd=0x100
devid=usb\vid_045e&pid_072d&rev_0100 devinst=2),
 USBDevice(vendor_id=0x480 product_id=0xd011 bcd=0x316
devid=usb\vid_0480&pid_d011&rev_0316 devinst=3),
 USBDevice(vendor_id=0x45e product_id=0x7a5 bcd=0x757
devid=usb\vid_045e&pid_07a5&rev_0757&mi_00 devinst=4),
 USBDevice(vendor_id=0x45e product_id=0x72d bcd=0x100
devid=usb\vid_045e&pid_072d&rev_0100&mi_02 devinst=5),
 USBDevice(vendor_id=0x8087 product_id=0x20 bcd=0x0
devid=usb\vid_8087&pid_0020&rev_0000 devinst=6),
 USBDevice(vendor_id=0x45e product_id=0x7a5 bcd=0x757
devid=usb\vid_045e&pid_07a5&rev_0757 devinst=7),
 USBDevice(vendor_id=0x45e product_id=0x7a5 bcd=0x757
devid=usb\vid_045e&pid_07a5&rev_0757&mi_01 devinst=8),
 USBDevice(vendor_id=0x45e product_id=0x72d bcd=0x100
devid=usb\vid_045e&pid_072d&rev_0100&mi_00 devinst=9),
 USBDevice(vendor_id=0x45e product_id=0x7a5 bcd=0x757
devid=usb\vid_045e&pid_07a5&rev_0757&mi_02 devinst=10),
 USBDevice(vendor_id=0x3f0 product_id=0x4712 bcd=0x100
devid=usb\vid_03f0&pid_4712&rev_0100&mi_02 devinst=11),
 USBDevice(vendor_id=0x3f0 product_id=0x4712 bcd=0x100
devid=usb\vid_03f0&pid_4712&rev_0100&mi_01 devinst=12),
 USBDevice(vendor_id=0x8087 product_id=0x20 bcd=0x0
devid=usb\vid_8087&pid_0020&rev_0000 devinst=13),
 USBDevice(vendor_id=0x3f0 product_id=0x4712 bcd=0x100
devid=usb\vid_03f0&pid_4712&rev_0100&mi_00 devinst=14),
 USBDevice(vendor_id=0x3f0 product_id=0x4712 bcd=0x100
devid=usb\vid_03f0&pid_4712&rev_0100 devinst=15),
 USBDevice(vendor_id=None product_id=None bcd=None
devid=usb\root_hub20&vid8086&pid3b3c&rev0005 devinst=16),
 USBDevice(vendor_id=None product_id=None bcd=None
devid=usb\root_hub20&vid8086&pid3b34&rev0005 devinst=17),
 USBDevice(vendor_id=0x5e3 product_id=0x716 bcd=0x9715
devid=usb\vid_05e3&pid_0716&rev_9715 devinst=18))

No disabled plugins
Looking for devices of type: MTP_DEVICE
List of WPD PNP ids:
[u'\\\\?\\swd#wpdbusenum#{76fc5eee-9c31-11e9-ab66-90e6bace32c5}#0000000006500000#{6ac27878-a6fa-4155-ba85-f98f491d4f33}']
No suitable MTP devices found

Looking for devices of type: SMART_DEVICE_APP
All IP addresses {'{A1117E5F-9825-11E9-AB48-806E6F6E6963}': [{'broadcast':
u'127.0.0.1', 'netmask': u'255.255.255.255', 'addr': u'127.0.0.1'}],
'{50277B28-82E9-4157-A845-E0741601FDDF}': [{'broadcast': u'192.168.1.133',
'netmask': u'255.255.255.255', 'addr': u'192.168.1.133'}]}
No device is connected

Looking for devices...

Devices possibly connected: None

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre.  So that's what we need to see in the debug log.  Here's how:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by gordongrams** [comment]
Thanks. Here is the log:
calibre Debug log
calibre 3.44  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.44  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.0 x 95.9160839161
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
Loaded cached store plugin for: Amazon Kindle at version: 17
Loaded cached store plugin for: Google Books at version: 6
[1.92] main UI initialized...
[1.92] Hiding splash screen
[103.42] splash screen hidden
[103.42] Started up in 103.42 seconds with 22 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper:
[']\xbf\xff>]\xf6\xd12]^c\n\x03\xb2\xad1b\xcc\xdf\xfd\xa0\xcc\xd7v\xf7:\xcb`T\xeb\x98]',
'C:\\Users\\PC\\Documents\\My Kindle
Content\\B004EYT4AK_EBOK\\B004EYT4AK_EBOK.azw']
DeDRM v6.6.3: Trying to decrypt B004EYT4AK_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Measuring the World
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\PC\AppData\Local
Found K4PC 2.25+ kinf2018 file:
C:\Users\PC\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '4076533960' and UserName '5043'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Measuring the World
Got DSN key from database default_key_1
Found 3 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs
at Harper's repository:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in
_run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601:
UnicodeWarning: Unicode equal comparison failed to convert both arguments
to Unicode - interpreting them as being unequal
Added Measuring the World to db in: 0.3
Added 1 books in 1.3 seconds

**Comment by ElleKayEm** [comment]
You need to use Kindle for PC 1.24 or earlier.  Link for that version and info on keeping it from updating at the bottom of the first post here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by gordongrams** [comment]
Wonderful!!! I can't thank you enough. After hours of frustration you
explained and solved my problem with a few clicks. Thanks so much!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
