### ISSUE TITLE
Unable to strip DRM

### ISSUE THREAD

**Issue by mertkd** [apprenticeharper/DeDRM_tools#862]
Finally broke down and bought a new PC. Loaded Calibre 3.45.2 and DeDRM 6.6.3 plugin. Tried to convert my latest Kindle books. Some converted and others errored out indicating they are locked by DRM. These are books I've "downloaded and transferred via USB" directly from Amazon, so nothing unique in the source files. I've attached a log of one of the problem books.

If it was one book, I might think there was something unique about that one book, but this is happening with about 20 new books. I've been using Calibre for years with no problem.

Can anyone point me at what I am missing? 
=============================================
calibre Debug log
calibre 3.45.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 1) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 17, 1) && KindleUnpack - The Plugin (0, 81, 5) && KFX metadata reader (from KFX Input) (1, 17, 1) && KFX Input (1, 17, 1)
calibre 3.45.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 1) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 17, 1) && KindleUnpack - The Plugin (0, 81, 5) && KFX metadata reader (from KFX Input) (1, 17, 1) && KFX Input (1, 17, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 80.2105263158 x 79.5130434783
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[0.69] main UI initialized...
[0.69] Hiding splash screen
[4.44] splash screen hidden
[4.44] Started up in 4.44 seconds with 0 books
DeDRM v6.6.3: Trying to decrypt Robert Mueller - The Mueller Report.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Mueller Report
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\kenme\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\kenme\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1723617033' and UserName '6b656e6d65'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Mueller Report
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Mueller Report to db in: 0.2
Added 1 books in 0.6 seconds

**Comment by ElleKayEm** [comment]
Did you choose an E-ink Kindle (not a Fire) for the device?  Looks like you haven't entered its serial number into DeDRM's customization.

**Comment by mertkd** [comment]
Thanks for the pointer. I don't remember ever manually entering my device's serial number before. But entered it and all appears to be working correctly!

Thanks so much, Elle!
