### ISSUE TITLE
Dedrm for AZW3 to mobi 

### ISSUE THREAD

**Issue by Tarz-an** [apprenticeharper/DeDRM_tools#864]
calibre Debug log
calibre 3.45.2  embedded-python: True is64bit: False
Windows-Vista-6.0.6000-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', 'Vista', '6.0.6000')
Python 2.7.15+
Windows: ('Vista', '6.0.6000', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 17, 1) && KFX metadata reader (from KFX Input) (1, 17, 1) && KFX Input (1, 17, 1) && FanFicFare (3, 9, 0) && Obok DeDRM (6, 5, 4) && KindleUnpack - The Plugin (0, 81, 5) && Goodreads (1, 4, 0) && CalibreSpy (1, 0, 72) && MondoUrania (0, 2, 2) && Count Pages (1, 8, 2) && Set KFX metadata (from KFX Output) (1, 30, 0) && KFX Output (1, 30, 0) && Find Duplicates (1, 6, 3) && Kindle Collections (1, 7, 24)
calibre 3.45.2  embedded-python: True is64bit: False
Windows-Vista-6.0.6000-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', 'Vista', '6.0.6000')
Python 2.7.15+
Windows: ('Vista', '6.0.6000', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 17, 1) && KFX metadata reader (from KFX Input) (1, 17, 1) && KFX Input (1, 17, 1) && FanFicFare (3, 9, 0) && Obok DeDRM (6, 5, 4) && KindleUnpack - The Plugin (0, 81, 5) && Goodreads (1, 4, 0) && CalibreSpy (1, 0, 72) && MondoUrania (0, 2, 2) && Count Pages (1, 8, 2) && Set KFX metadata (from KFX Output) (1, 30, 0) && KFX Output (1, 30, 0) && Find Duplicates (1, 6, 3) && Kindle Collections (1, 7, 24)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 81.5518394649 x 81.6428571429
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.42] db initialized
[0.42] Constructing main UI...
FFF: DEBUG: 2019-07-18 13:04:33,015: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter(41): BS4:4.7.1
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
FFF: INFO: 2019-07-18 13:04:37,403: calibre_plugins.fanficfare_plugin.prefs(206): Attempting to read settings from predecessor--FFDL
FFF: INFO: 2019-07-18 13:04:37,403: calibre_plugins.fanficfare_plugin.prefs(211): Using default settings
FFF: DEBUG: 2019-07-18 13:04:37,408: calibre_plugins.fanficfare_plugin.fff_plugin(207): Plugin FanFicFare macmenuhack file_path:C:\Users\Roy & Tara\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
CalibreSpy: initialization_complete
[5.26] main UI initialized...
[5.26] Hiding splash screen
[65.08] splash screen hidden
[65.08] Started up in 65.08 seconds with 2723 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xb9\xd2\xa9\x9c\xc7r\xad\xfd\x8a|R\x9f\xce\xe9\x1e\xafA\xa5\x1f\x91i2\x12\xff\xdf\xa0\xee@\xaf\x1e\x1e\x9a', 'E:\\B0083ZLVEI_EBOK\\B0083ZLVEI_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.17.1: Importing E:\B0083ZLVEI_EBOK\B0083ZLVEI_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\ROY&TA~1\AppData\Local\Temp\calibre_udkami\jgrpj8.kfx-zip
DeDRM v6.6.1: Trying to decrypt jgrpj8.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: jgrpj8
Got DSN key from database default_key_3
Found 3 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.638da617-c126-4744-9bc3-650ce9c2f39f.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Roy & Tara\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Roy & Tara\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2186573596' and UserName '526f7920262054617261'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: jgrpj8
Got DSN key from database default_key_1
Found 1 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.638da617-c126-4744-9bc3-650ce9c2f39f.voucher
DeDRM v6.6.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.17.1: Packaging C:\Users\ROY&TA~1\AppData\Local\Temp\calibre_udkami\jgrpj8.kfx-zip
Processing container: B0083ZLVEI_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B0083ZLVEI_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\ROY&TA~1\AppData\Local\Temp\calibre_udkami\fb022__add_books\0\B0083ZLVEI_EBOK.kfx-zip
Added The Boy Under the Table to db in: 2.2
Added 1 books in 4.0 seconds

I got the book through Amazon Prime for "free".  I do not have a device for this account.  I have tried to download from kindle cloud and kindle app so that I can load into Calibre, convert to epub & / mobi and load on a kindle paperwhite (again not linked to this account).  Thanks.

**Comment by ElleKayEm** [comment]
The Kindle for PC app which you used to download the book and DeDRM need to be on the same machine and user.  Looks like the book here is imported from E drive while calibre and a different installation of Kindle for PC are on C drive.  So DeDRM can't retrieve the right key.

If the book is "purchased" for free (like Amazon First Reads), you'll be able to remove the DRM.  But if it is borrowed (like Prime Reading books), then you'll get an error.

(Incidentally this isn't AZW3/KF8 format.  It's KFX format)

**Comment by Tarz-an** [comment]
Thank you - I didn't know Prime meant 'borrowed'.

**Comment by ElleKayEm** [comment]
Unless you have more questions, you can close the issue.
