### ISSUE TITLE
Unable to open database file?  Did I install incorrectly??

### ISSUE THREAD

**Issue by innocent92** [apprenticeharper/DeDRM_tools#87]
calibre, version 2.53.0
ERROR: Unhandled exception: <b>OperationalError</b>:unable to open database file

calibre 2.53 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && Obok DeDRM && Find Duplicates
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 82, in launchObok
  File "calibre_plugins.obok_dedrm.obok.obok", line 237, in __init__
OperationalError: unable to open database file

**Comment by ElleKayEm** [comment]
The Obok plugin is looking for Kobo Desktop or an attached Kobo device and not finding anything.

**Comment by googlebot-xx** [comment]
What's error message? In detail.

**Comment by ElleKayEm** [comment]
I'm responding to the error message innocent92 posted.

**Comment by apprenticeharper** [comment]
This doesn't seem to need further response. Please start a new issue if you need further help, innocent92.

**Comment by estherosmo** [comment]
Hi all,

when trying to execute the plug in obok with calibre, I get the following message:

calibre, version 2.71.0
ERROR: Unhandled exception: <b>OperationalError</b>:unable to open database file

calibre 2.71 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: Obok DeDRM (3, 0, 3)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 72, in launchObok
  File "calibre_plugins.obok_dedrm.obok.obok", line 214, in __init__
OperationalError: unable to open database file

What can I do to sort it? Thank you very much for your time.

**Comment by ElleKayEm** [comment]
Install the latest version of Obok and be sure to restart calibre before using.  Log shows an old version, current one is 6.5.2.
