### ISSUE TITLE
Troubleshoot - Kindle for mac 1.23 + De-DRM plugin = No joy

### ISSUE THREAD

**Issue by mlh24490** [apprenticeharper/DeDRM_tools#871]
Using kindle for Mac 1.23

I don't actually have a kindle device so I can't download and transfer via USB as there's no devices listed apart from my kindle for mac. Unless there's a workaround for this?

This is the debug log file:

calibre Debug log
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.6.0', 'Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.5', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.6.0', 'Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.5', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 81.500001224 x 80.500001209
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
/Users/mimihayton/Documents/Kindle books/My Kindle Content is not a valid directory to watch for new ebooks, ignoring
[1.06] main UI initialized...
[1.06] Hiding splash screen
[1.11] splash screen hidden
[1.12] Started up in 1.12 seconds with 1 books
objc[2837]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff992a43d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x118f21f50). One of the two will be used. Which one is undefined.
DeDRM v6.6.3: Trying to decrypt B00JJ9G6QK_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.6.3: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/mimihayton/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'dd9464876fcd' and UserName 'mimihayton'
DeDRM v6.6.3: Found 1 new key
DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 285, in get_metadata
  File "site-packages/calibre/ebooks/metadata/mobi.py", line 498, in get_metadata
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 285, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 313, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
Added B00JJ9G6QK EBOK to db in: 0.0
Added 1 books in 1.0 seconds
Worker Launch took: 0.162003040314
Job: 0 Convert book 1 of 1 (B00JJ9G6QK EBOK) finished
Convert book 1 of 1 (B00JJ9G6QK EBOK)
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: u'tablet'
	  read_metadata_from_opf: u'/var/folders/sh/_d1x766n0g7fjt0n0h_ss__80000gn/C/calibre_3.46.0_tmp_3TxYz7/ryV9yJ.opf'
	Resolved conversion options
	calibre version: 3.46.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10ec91710>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x10eca0350>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/sh/_d1x766n0g7fjt0n0h_ss__80000gn/C/calibre_3.46.0_tmp_3TxYz7/ryV9yJ.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/sh/_d1x766n0g7fjt0n0h_ss__80000gn/C/calibre_3.46.0_tmp_3TxYz7/N3JFpV.azw
	Python function terminated unexpectedly: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 200, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_ove

**Comment by ElleKayEm** [comment]
For the KFX format, you will also need the KFX Input plugin.  Or you can make a modification which prevents Kindle for Mac from downloading books in the KFX format.  See this post for details:

https://www.mobileread.com/forums/showthread.php?t=283371
