### ISSUE TITLE
Failing to Convert .azw3

### ISSUE THREAD

**Issue by rafepilling** [apprenticeharper/DeDRM_tools#876]
Hi,
Below is the log. 
Thanks

Traceback (most recent call last):
  File "site-packages/calibre/gui2/store/loader.py", line 91, in load_cache
  File "site-packages/calibre/gui2/store/loader.py", line 178, in load_object
  File "<string>", line 17, in <module>
ImportError: No module named PyQt4.Qt
Traceback (most recent call last):
  File "site-packages/calibre/gui2/store/loader.py", line 91, in load_cache
  File "site-packages/calibre/gui2/store/loader.py", line 178, in load_object
  File "<string>", line 17, in <module>
ImportError: No module named PyQt4.Qt
calibre Debug log
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.5.0', 'Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.5.0', 'Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
Failed to load cached store: legimi
Failed to load cached store: ebookpoint
[1.33] main UI initialized...
[1.33] Hiding splash screen
[1.37] splash screen hidden
[1.38] Started up in 1.38 seconds with 281 books
DeDRM v6.6.3: Trying to decrypt The Border (Power of the Dog).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Border (Power of the Dog)
Found 6 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/rafepilling/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'c55db8ac0d99' and UserName 'rafepilling'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Border (Power of the Dog)
Got DSN key from database default_key_1
Found 4 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

Debugging DND event
text/uri-list 82 'file:///Users/rafepilling/Downloads/The%20Border%20(Power%20of%20the%20Dog).azw3\r\n' 

Firefox rurl: None None
URLS: [u'file:///Users/rafepilling/Downloads/The%20Border%20(Power%20of%20the%20Dog).azw3']
Paths: [u'/Users/rafepilling/Downloads/The Border (Power of the Dog).azw3']
Extensions: frozenset([u'azw3'])
Added The Border (Power of the Dog) to db in: 0.1
Added 1 books in 1.2 seconds

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) for the device and enter the Kindle's serial number into the DeDRM plugin's customization.

**Comment by rafepilling** [comment]
Thank you!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
