### ISSUE TITLE
Problems to removing DRM azw3 kindle

### ISSUE THREAD

**Issue by HSMln** [apprenticeharper/DeDRM_tools#877]
Hi!
I'm looking for some help.

Some of my books had their DRM removed, but some still say that they have DRM and will not convert. Below is the log.

calibre Log de Debug
calibre 3.42  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 1) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 17, 1) && Set KFX metadata (from KFX Output) (1, 30, 0) && KFX Output (1, 30, 0) && KFX metadata reader (from KFX Input) (1, 17, 1) && KFX Input (1, 17, 1)
calibre 3.42  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 1) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 17, 1) && Set KFX metadata (from KFX Output) (1, 30, 0) && KFX Output (1, 30, 0) && KFX metadata reader (from KFX Input) (1, 17, 1) && KFX Input (1, 17, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[4.95] main UI initialized...
[4.95] Hiding splash screen
[48.16] splash screen hidden
[48.16] Started up in 48.16 seconds with 44 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['}\x03\xd4\x07\x9c\x92?\xe6\x1cR2\xb2^\x97\x8ar\x1c\x17\xef`\x10\xfa\xee\xa96\x81\x13\xb7\xbe\xba9\xc3', 'C:\\Users\\arauj\\Downloads\\P\xc3\xa3o Sem Gl\xc3\xbaten_ Princ\xc3\xadpios, t\xc3\xa9cnicas e truques para fazer p\xc3\xa3o e outras receitas sem gl\xc3\xbaten..azw3']
DeDRM v6.6.3: Trying to decrypt PÃ£o Sem GlÃºten_ PrincÃ­pios, tÃ©cnicas e truques para fazer pÃ£o e outras receitas sem glÃºten..azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: PÃ£o Sem GlÃºten: PrincÃ­pios, tÃ©cnicas e truques para fazer pÃ£o e outras receitas sem glÃºten.
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 7 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 7 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\arauj\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\arauj\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\arauj\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1324771348' and UserName '617261756a'
Decrypted key file using IDString '1324771348' and UserName '617261756a'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: PÃ£o Sem GlÃºten: PrincÃ­pios, tÃ©cnicas e truques para fazer pÃ£o e outras receitas sem glÃºten.
Got DSN key from database default_key_2
Found 4 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Pão Sem Glúten: Princípios, técnicas e truques para fazer pão e outras receitas sem glúten. to db in: 3.0
Added 1 books in 4.9 seconds

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then you need to enter its serial number into the DeDRM plugin's customization.

**Comment by HSMln** [comment]
Yay worked! Tkx so very much!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
