### ISSUE TITLE
Kindle DRM key not found?

### ISSUE THREAD

**Issue by kaestov** [apprenticeharper/DeDRM_tools#88]
I've tried this on two separate computers and had the exact same outcome, here's my debug text.

> calibre Debug log
calibre 2.53  embedded-python: True is64bit: False
Windows-7-6.1.7600 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7600')
Python 2.7.9
Windows: ('7', '6.1.7600', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 4.17 seconds with 2 books
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(1L, 'C')], (7L, 2L): [(1L, 'E')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\B01B15012492051T&0: StorageDeviceNumber(type=7L, number=2L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=3756)
{u'drive_letters': ['E'],
 u'pnp_id_map': {'E': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#b01b15012492051t&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'E': (2L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: E:\ documents
Job: 1 Get device information finished
No details available.
Job: 2 Set library information finished
No details available.
DEBUG:    0.2 USBMS: scan from root False E:\documents
DEBUG:    1.9 USBMS: count found in cache: 75, count of files in metadata: 75, need_sync: False
DEBUG:    1.9 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    1.9 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    1.9 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 75
DeviceJob: set_books_in_library finished: time= 0.00500011444092
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Job: 4 Prepare files for transfer from device started
DeviceJob: 4 Prepare files for transfer from device done, calling callback
DeviceJob: 4 Prepare files for transfer from device callback returned
DeDRM v6.4.0: Trying to decrypt Midnight Riot (PC Peter Grant Book 1)_B004C43F70.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Midnight Riot (PC Peter Grant Book 1)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.4.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.4.0: Looking for new default Kindle Key after 0.1 seconds
Job: 4 Prepare files for transfer from device finished
No details available.
searching for kinfoFiles in C:\Users\Kaest\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.4.0: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 153, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 598, in run
  File "calibre_plugins.dedrm.__init__", line 548, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.0: Ultimately failed to decrypt after 0.1 seconds
Added Midnight Riot (PC Peter Grant Book 1) to db in: 0.1
Added 1 books in 0.7 seconds
DeviceJob: set_books_in_library: books to process= 75
DeviceJob: set_books_in_library finished: time= 0.0110001564026
Worker Launch took: 0.125

**Comment by ElleKayEm** [comment]
If the book is from an E-ink Kindle, then you haven't entered the serial number into the plugin customization.  Otherwise, install Kindle for PC, download the book, and import that copy.

**Comment by kaestov** [comment]
Aha, thank you! Did not realize I needed to enter the serial number.

**Comment by gerardocoppola** [comment]
just tried to remove drm from an azw by 6.40 . Doesnt work.
Help please
Thank you
