### ISSUE TITLE
DeDRM does not seem to remove DRM from my kindle file

### ISSUE THREAD

**Issue by mnemonica2004** [apprenticeharper/DeDRM_tools#886]
calibre Debug log
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 3) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5) && Package KFX (from KFX Input) (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0) && Kindle Collections (1, 7, 21)
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 3) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5) && Package KFX (from KFX Input) (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0) && Kindle Collections (1, 7, 21)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.29] db initialized
[0.29] Constructing main UI...
[1.31] main UI initialized...
[1.31] Hiding splash screen
[1.35] splash screen hidden
[1.36] Started up in 1.36 seconds with 436 books
objc[8015]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffb262f3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x110218f50). One of the two will be used. Which one is undefined.
Gather KFX-ZIP (from KFX Input) 1.8.0: Importing /Users/Fritzie/Library/Application Support/Kindle/My Kindle Content/B0063WKG76_EBOK/B0063WKG76_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.3: Trying to decrypt B0063WKG76_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Our Hero General U. S. Grant, When, Where, and How He Fought
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/Fritzie/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '91939e806c2b' and UserName 'Fritzie'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Our Hero General U. S. Grant, When, Where, and How He Fought
Got DSN key from database default_key_1
Found 3 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin K4PC, K4Mac, Kindle Mobi and Topaz DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.k4mobidedrm.__init__", line 89, in run
ImportError: No module named PyQt4.Qt
K4MobiDeDRM: Calibre configuration directory = /Users/Fritzie/Library/Preferences/calibre
MOBI header version = 4, length = 232
No kindle-info files have been found.
Crypto Type is:  2
Added Our Hero General U. S. Grant, When, Where, and How He Fought to db in: 0.0
Added 1 books in 1.3 seconds

I added the file from my kindle for mac content folder as an awz file, but I am not able to convert it into a mobi file.
What am I doing wrong?
Any help is greatly appreciated.

**Comment by ElleKayEm** [comment]
This book was downloaded with the current installation of Kindle for Mac on the same machine and user as calibre with DeDRM?

(You can remove the old "K4PC, K4Mac, Kindle Mobi and Topaz DeDRM" plugin.  It's replaced by DeDRM.)

**Comment by mnemonica2004** [comment]
I downloaded it with the Kindle for Mac 1.26.1 on the same machine I have calibre installed and the same user.

**Comment by ElleKayEm** [comment]
The key that was found must have been from a previous installation then.  DeDRM isn't able to decrypt keys from Kindle for Mac beyond version 1.23.  See this post for info:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by mnemonica2004** [comment]
Thanks! I downgraded to 1.17, and it worked. Thank you for your help, I really appreciate it!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
