### ISSUE TITLE
6.40 . Doesnt work

### ISSUE THREAD

**Issue by gerardocoppola** [apprenticeharper/DeDRM_tools#90]
just tried to remove drm from an azw by 6.40 . Doesnt work.
Help please
Thank you

**Comment by ElleKayEm** [comment]
Look at the readme files.  If that doesn't help, then post a log.

**Comment by gerardocoppola** [comment]
Hi!
I tried again DeDRM. I think the probel is : my ebook is a Google epub
ebook.
So if I customize the DeDRM in Calibre this option (Google ebooks) is not
available.
I'm right?

Thank u so much for helping !!!

have a nice day

**Comment by ElleKayEm** [comment]
These tools work with Google epubs.  You just need Adobe Digital Editions 2.0.1 authorized with your Adobe ID on the same computer where you have calibre installed.  The key is automatically retrieved.  No need to enter anything into the DeDRM customization.

**Comment by gerardocoppola** [comment]
Thank you again!!!!
