### ISSUE TITLE
Missing default keyfiles for Kindle on Mac

### ISSUE THREAD

**Issue by kn0wsnothing** [apprenticeharper/DeDRM_tools#906]
As the title suggests, I'm unable to convert .azw files to epub. I've installed the KFX Input and DeDRM plugins for Calibre. The files load fine into Calibre, but I keep getting DRM errors from Calibre when trying to convert. Looking into the plugin configuration, I can see there's no default keyfile being generated. I tried loading the keyfile from the DeDRM_Windows_Application folder (kindlekey1.k41) but that doesn't work.

Calibre version 3.48.0
DeDRM version 6.6.3

**Comment by ZolaLa9** [comment]
Keys are specific to each device, so if you're on a Mac, copying the key from a Windows machine won't work. Even copying the key from another Mac won't work. If you got the book from Kindle for Mac, then Calibre needs to be on the same computer as the Kindle for Mac you got the book from. Depending on what version Kindle for Mac you're using, you may also have to do some fiddling (and if you're using anything above v1.23.1, it may not work at all). [More info here](url)

If you got the book from a Kindle device or downloaded it from Amazon by selecting "transfer via USB", you'll need to input the serial number in the DeDRM plugin's customization dialog box.

**Comment by kn0wsnothing** [comment]
I think I figured it out. According to this post on medium (https://medium.com/@angeldan1989/kindle-for-pc-version-1-25-kfx-2-6282ba16462c) dedrm and conversion won’t work with files from later versions of Kindle for Mac. The author recommends 1.23.1, but that didn’t work for me. I’m using 1.17.0 and it works like a charm. Will update if any changes, positive or negative.

**Comment by ZolaLa9** [comment]
> I think I figured it out. According to [this post on medium](https://medium.com/@angeldan1989/kindle-for-pc-version-1-25-kfx-2-6282ba16462c) dedrm and conversion won’t work with files from later versions of Kindle for Mac. The author recommends 1.23.1, but that didn’t work for me. I’m using 1.17.0 and it works like a charm. 

It can work on all versions of Kindle for Mac under the right circumstances. I've gotten it to work with v1.23.1, 1.25 and 1.26 using info from [this post on MobileRead](https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508). But as long as you've got it working, that's what counts.

**Comment by kn0wsnothing** [comment]
Cheers. I’ll check that out now.

Best,

John

**Comment by ElleKayEm** [comment]
If you're all set, you can close this issue.

**Comment by tartley** [comment]
Closing  - user is happy now.
