### ISSUE TITLE
DRM removal not working on azw file

### ISSUE THREAD

**Issue by Audres** [apprenticeharper/DeDRM_tools#907]
I am using Galibre and drm remove plugin, latest versions. Kindle for PC version 1.17. Previous books downloaded with azw3 extension. No problem. This time it didn't work witha abook that downloaded with azw only extension. When I clicked convert tu epub I got the message that it could no covert because it was a DRM protected bok. The log file is:

calibre Debug log
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.643076923 x 133.900578035
Using calibre Qt style: True

Thanks for your assistance

**Comment by zwhitten** [comment]
@Audres if you previously imported the book before installing the plugins then you would need to re-import it to have the plugins remove the DRM

**Comment by Audres** [comment]
Thanks for your attention. I already had the plugins installed.

**Comment by ElleKayEm** [comment]
@Audres 
Did you solve your issue or did you close this by accident?  Your log doesn't show you adding a book so I can't tell what was wrong.

**Comment by reflexwolf** [comment]
I'm having the same problem, I wasn't sure if it was just me and put off
looking into it, here is the log of my loading the book and converting it
to epub from azw brings up the drm error. here is my log if that might
help. thanks !

calibre Debug log
calibre 4.3 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Initialized urlfixer
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX
Input) (1, 23, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1,
23, 0) && Fantastic Fiction (1, 3, 0) && Skoob Books (1, 3, 1) && Goodreads
(1, 4, 0) && Fantastic Fiction Adults (1, 1, 0) && EpubSplit (2, 7, 0) &&
KFX metadata reader (from KFX Input) (1, 23, 0) && KFX Input (1, 23, 0) &&
DOC Input (1, 0, 1) && Kobo Books (1, 7, 0) && Barnes & Noble (1, 2, 15) &&
Ex Libris (1, 0, 19) && Generate Cover (1, 5, 21) && Author Book Count
Hierarchy (1, 2, 0) && Smashwords Metadata (1, 0, 0) && Author Book Count
(2, 1, 7) && Count Pages (1, 9, 0) && Webscription (1, 1, 0) && FictionDB
(1, 2, 0) && Beam Ebooks (1, 0, 0) && Wikidata (1, 3, 0) && Walk Search
History (1, 3, 1) && Amazon.com Multiple Countries (1, 0, 0) && Wikidata
gui (1, 3, 0) && Zotero Metadata Importer (1, 0, 60) && FanFicFare (3, 12,
0) && Kindle hi-res covers (0, 4, 0) && Job Spy (1, 0, 167) && Library
Codes (1, 0, 41)
calibre 4.3 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX
Input) (1, 23, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1,
23, 0) && Fantastic Fiction (1, 3, 0) && Skoob Books (1, 3, 1) && Goodreads
(1, 4, 0) && Fantastic Fiction Adults (1, 1, 0) && EpubSplit (2, 7, 0) &&
KFX metadata reader (from KFX Input) (1, 23, 0) && KFX Input (1, 23, 0) &&
DOC Input (1, 0, 1) && Kobo Books (1, 7, 0) && Barnes & Noble (1, 2, 15) &&
Ex Libris (1, 0, 19) && Generate Cover (1, 5, 21) && Author Book Count
Hierarchy (1, 2, 0) && Smashwords Metadata (1, 0, 0) && Author Book Count
(2, 1, 7) && Count Pages (1, 9, 0) && Webscription (1, 1, 0) && FictionDB
(1, 2, 0) && Beam Ebooks (1, 0, 0) && Wikidata (1, 3, 0) && Walk Search
History (1, 3, 1) && Amazon.com Multiple Countries (1, 0, 0) && Wikidata
gui (1, 3, 0) && Zotero Metadata Importer (1, 0, 60) && FanFicFare (3, 12,
0) && Kindle hi-res covers (0, 4, 0) && Job Spy (1, 0, 167) && Library
Codes (1, 0, 41)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259 x 93.6245733788
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.69] splash screen shown
[0.69] Initializing db...
[18.97] db initialized
[18.97] Constructing main UI...
Initializing wikidata gui preferences
Initialized urlfixer
FFF: INFO: 2019-11-14 08:04:37,476:
calibre_plugins.fanficfare_plugin.prefs(207): Attempting to read settings
from predecessor--FFDL
FFF: INFO: 2019-11-14 08:04:37,476:
calibre_plugins.fanficfare_plugin.prefs(212): Using default settings
FFF: DEBUG: 2019-11-14 08:04:37,489:
calibre_plugins.fanficfare_plugin.fff_plugin(207): Plugin FanFicFare
macmenuhack
file_path:C:\Users\Jamie\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
Job Spy has begun initialization...
Calibre, and hence Job Spy, was gracefully shut down last time?  True
Last time daemon started:  never
Last time daemon failed:  never
Total daemon starts inception_to_date:  0
Total daemon failures inception-to-date:  0
Job Spy has finished initialization...
[27.84] main UI initialized...
[27.84] Hiding splash screen
[115.45] splash screen hidden
[115.45] Started up in 115.45 seconds with 105348 books
Initialized urlfixer
Gather KFX-ZIP (from KFX Input) 1.23.0: Importing
C:/Users/Jamie/Documents/My Kindle Content/B005NSF3ZQ_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.3: Trying to decrypt B005NSF3ZQ_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Chosen: Chosen #1 (The Chosen)
Got DSN key from database default_key
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Jamie\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs
at Harper's repository:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in
_run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.0 seconds.
Read the FAQs at Harper's repository:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Chosen: Chosen #1 (The Chosen) to db in: 1.8
Added 1 books in 2.6 seconds
Worker Launch took: 0.157999992371
Job: 0 Convert book 1 of 1 (Chosen: Chosen #1 (The Chosen)) finished
Convert book 1 of 1 (Chosen: Chosen #1 (The Chosen))
Initialized urlfixer
Conversion options changed from defaults:
 cover:
u'C:\\Users\\Jamie\\AppData\\Local\\Temp\\calibre_2vqpxw\\6ehdso.jpeg'
 read_metadata_from_opf:
u'C:\\Users\\Jamie\\AppData\\Local\\Temp\\calibre_2vqpxw\\crnyzo.opf'
 verbose: 2
 output_profile: u'generic_eink_hd'
Resolved conversion options
calibre version: 4.3.0
{'asciiize': False,
'author_sort': None,
'authors': None,
'base_font_size': 0.0,
'book_producer': None,
'change_justification': u'original',
'chapter': u"//*[((name()='h1' or name()='h2') and re:test(.,
'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))',
'i')) or @class = 'chapter']",
'chapter_mark': u'pagebreak',
'comments': None,
'cover':
u'C:\\Users\\Jamie\\AppData\\Local\\Temp\\calibre_2vqpxw\\6ehdso.jpeg',
'debug_pipeline': None,
'dehyphenate': True,
'delete_blank_paragraphs': True,
'disable_font_rescaling': False,
'dont_split_on_page_breaks': False,
'duplicate_links_in_toc': False,
'embed_all_fonts': False,
'embed_font_family': None,
'enable_heuristics': False,
'epub_flatten': False,
'epub_inline_toc': False,
'epub_toc_at_end': False,
'epub_version': u'2',
'expand_css': False,
'extra_css': None,
'extract_to': None,
'filter_css': u'',
'fix_indents': True,
'flow_size': 260,
'font_size_mapping': None,
'format_scene_breaks': True,
'html_unwrap_factor': 0.4,
'input_encoding': None,
'input_profile': <calibre.customize.profiles.InputProfile object at
0x000001EE657D6108>,
'insert_blank_line': False,
'insert_blank_line_size': 0.5,
'insert_metadata': False,
'isbn': None,
'italicize_common_cases': True,
'keep_ligatures': False,
'language': None,
'level1_toc': None,
'level2_toc': None,
'level3_toc': None,
'line_height': 0.0,
'linearize_tables': False,
'margin_bottom': 5.0,
'margin_left': 5.0,
'margin_right': 5.0,
'margin_top': 5.0,
'markup_chapter_headings': True,
'max_toc_links': 50,
'minimum_line_height': 120.0,
'no_chapters_in_toc': False,
'no_default_epub_cover': False,
'no_inline_navbars': False,
'no_svg_cover': False,
'output_profile': <calibre.customize.profiles.GenericEinkHD object at
0x000001EE657D6DC8>,
'page_breaks_before': u"//*[name()='h1' or name()='h2']",
'prefer_metadata_cover': False,
'preserve_cover_aspect_ratio': False,
'pretty_print': True,
'pubdate': None,
'publisher': None,
'rating': None,
'read_metadata_from_opf':
u'C:\\Users\\Jamie\\AppData\\Local\\Temp\\calibre_2vqpxw\\crnyzo.opf',
'remove_fake_margins': True,
'remove_first_image': False,
'remove_paragraph_spacing': False,
'remove_paragraph_spacing_indent_size': 1.5,
'renumber_headings': True,
'replace_scene_breaks': u'',
'search_replace': '[]',
'series': None,
'series_index': None,
'smarten_punctuation': False,
'sr1_replace': None,
'sr1_search': None,
'sr2_replace': None,
'sr2_search': None,
'sr3_replace': None,
'sr3_search': None,
'start_reading_at': None,
'subset_embedded_fonts': False,
'tags': None,
'timestamp': None,
'title': None,
'title_sort': None,
'toc_filter': None,
'toc_threshold': 6,
'toc_title': None,
'transform_css_rules': '[]',
'unsmarten_punctuation': False,
'unwrap_lines': True,
'use_auto_toc': False,
'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\Jamie\AppData\Local\Temp\calibre_2vqpxw\6lrjom.azw
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly
 Chosen: Chosen #1 (The Chosen) (Error Code: 1)
Traceback (most recent call last):
 File "site.py", line 114, in main
 File "site.py", line 88, in run_entry_point
 File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
 File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in
gui_convert_override
 File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in
gui_convert
 File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in
run
 File "site-packages\calibre\customize\conversion.py", line 246, in __call__
 File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line
47, in convert
 File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in
__call__
 File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in
check_for_drm
calibre.ebooks.DRMError: Chosen: Chosen #1 (The Chosen)

**Comment by ElleKayEm** [comment]
The book needs to be downloaded with Kindle for PC 1.24 or earlier currently installed on the same machine and user as calibre with DeDRM.

**Comment by reflexwolf** [comment]
I did so, the book was downloaded with a fresh install of kindle for pc
1.24 (I have the install file and when done remove with revo each time) I
downloaded it just last week.

**Comment by ElleKayEm** [comment]
You're removing Kindle for PC before adding the book to calibre?  If so, that's why it's not working.  DeDRM can't find the key because it's gone.

**Comment by reflexwolf** [comment]
no, what  I do is to prevet it from auto updating each time I use it to
download  books I have bought I uninstall it, when I need it I install it
again and then go about getting the books, this has worked for several
years now. just this last time its not working.

**Comment by ElleKayEm** [comment]
Okay, DeDRM isn't finding any K4PC key files.

> DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Jamie\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.

**Comment by Laodamas** [comment]
Hello, I have the same problem described above. On Debian 11 KDE, I use Kindle for PC 1.16 and Calibre 5.12 with DeDRM 7.21. The DeDRM tool was working, but it has now failed to work several times with AZW ebooks.

First, I don't know which log to open, to paste it here.

Second, if DeDRM is finding no K4PC key files on my computer, what does that mean? That is, if that is the problem, then how would I fix it?

Really, thank you for your help.

**Comment by ElleKayEm** [comment]
Here's how to get a log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

On Linux, retrieving keys can be tricky and depends on your setup.  On Windows and Mac, it's automatic as long as Kindle for PC/Mac is on the same machine and user as calibre with DeDRM.
