### ISSUE TITLE
6.40 failed on azw format

### ISSUE THREAD

**Issue by Caldwell4560** [apprenticeharper/DeDRM_tools#91]
Here's the debug log from a failed attempt in Calibre.  Any ideas?

calibre 2.13 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.8
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
DeDRM v6.1.0: In __init__
DeDRM v6.1.0: In load_resources
DeDRM v6.1.0: verdir C:\Users\Tom\AppData\Roaming\calibre\plugins\DeDRM\6.1.0
DeDRM v6.1.0: In initialize
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 1.73 seconds with 30 books
DeDRM v6.1.0: In __init__
DeDRM v6.1.0: In load_resources
DeDRM v6.1.0: verdir C:\Users\Tom\AppData\Roaming\calibre\plugins\DeDRM\6.1.0
DeDRM v6.1.0: In initialize
DeDRM v6.1.0: Trying to decrypt B00JFG712A_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: CorelDRAW X7: The Official Guide
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.1.0: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.1.0: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Tom\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Tom\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1882835388' and UserName 'Tom'
DeDRM v6.1.0: Found 1 new key
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: CorelDRAW X7: The Official Guide
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.1.0: Ultimately failed to decrypt after 0.5 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 430, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 216, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 441, in processBook
DrmException: Cannot decode library or rented ebooks.
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 492, in run
  File "calibre_plugins.dedrm.__init__", line 443, in KindleMobiDecrypt
DeDRMError: DeDRM v6.1.0: Ultimately failed to decrypt ���B00JFG712A_EBOK.azw��� after 0.5 seconds with error: Cannot decode library or rented ebooks.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Added CorelDRAW X7: The Official Guide to db in: 4.3
Added 1 books in 5.5 seconds

**Comment by ElleKayEm** [comment]
It's right there in the log:  "Cannot decode library or rented ebooks."
