### ISSUE TITLE
Cannot remove DRM

### ISSUE THREAD

**Issue by KudouUsagi** [apprenticeharper/DeDRM_tools#913]
I can't get this new file I downloaded to remove DRM. This is my debug report

calibre Debug log
calibre 4.1  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 20, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 20, 0) && KFX metadata reader (from KFX Input) (1, 20, 0) && KFX Input (1, 20, 0) && Set KFX metadata (from KFX Output) (1, 31, 0) && KFX Output (1, 31, 0)
calibre 4.1  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 20, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 20, 0) && KFX metadata reader (from KFX Input) (1, 20, 0) && KFX Input (1, 20, 0) && Set KFX metadata (from KFX Output) (1, 31, 0) && KFX Output (1, 31, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 166.443686007 x 166.254545455
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.59] splash screen shown
[0.59] Initializing db...
[0.59] db initialized
[0.59] Constructing main UI...
[1.86] main UI initialized...
[1.86] Hiding splash screen
[9.08] splash screen hidden
[9.08] Started up in 9.08 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['r\xe1\xc7b\xdbs\x17\x15EE\x98N\xf5X{\x8ax\xbf\xd4M\x91\xcf\xd1\xcaX\xf9\xb4\xe9\xb1\x95\xab\xdc', 'C:\\Users\\****\\Desktop\\GUSH 2019-11\\GUSH 2019-11 - Unknown.azw']
Gather KFX-ZIP (from KFX Input) 1.20.0: Importing C:\Users\****\Desktop\GUSH 2019-11\GUSH 2019-11 - Unknown.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.3: Trying to decrypt GUSH 2019-11 - Unknown.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: GUSH 2019-11
Found 0 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\****\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\****\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1008622156' and UserName '436861726c6579'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: GUSH 2019-11
Got DSN key from database default_key_1
Found 4 keys to try after 0.9 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added GUSH 2019-11 to db in: 0.8
Added 1 books in 3.0 seconds
Worker Launch took: 0.164999961853
Job: 0 Convert book 1 of 1 (GUSH 2019-11) finished
Convert book 1 of 1 (GUSH 2019-11)
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\****\\AppData\\Local\\Temp\\calibre_4o9jqv\\picxbj.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\****\\AppData\\Local\\Temp\\calibre_4o9jqv\\2lvean.opf'
	  verbose: 2
	  output_profile: u'generic_eink'
	Resolved conversion options
	calibre version: 4.1.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\****\\AppData\\Local\\Temp\\calibre_4o9jqv\\picxbj.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x05195DD0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x05195FD0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\****\\AppData\\Local\\Temp\\calibre_4o9jqv\\2lvean.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\****\AppData\Local\Temp\calibre_4o9jqv\1gqbgs.azw
	Found KF8 MOBI of type u'standalone'
	P y t h o n   f u n c t i o n   t e r m i n a t e d   u n e x p e c t e d l y 
	 
	     G U S H   2 0 1 9 - 1 1   ( E r r o r   C o d e :   1 ) 
	 
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: GUSH 2019-11

**Comment by ElleKayEm** [comment]
If this is from or for an E-ink Kindle, then you need to enter the Kindle serial number into the DeDRM plugin's customization.  If you don't have an E-ink Kindle, download it with Kindle for PC 1.24 or earlier installed on the same machine and user.

**Comment by KudouUsagi** [comment]
I used kindle for PC 1.17.0

**Comment by ElleKayEm** [comment]
And the book was downloaded with the current installation of Kindle for PC 1.17 on the same machine and user as calibre with DeDRM?  Because while the log shows DeDRM finding and successfully decrypting a key, it's not working for this book.

**Comment by KudouUsagi** [comment]
yes it was.

**Comment by ElleKayEm** [comment]
Try uninstalling and reinstalling Kindle for PC following these instructions:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

**Comment by KudouUsagi** [comment]
It did not work it did the same thing. I did a debug check again 
calibre Debug log
calibre 4.1  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 13, 0) && Set KFX metadata (from KFX Output) (1, 27, 0) && KFX Output (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
calibre 4.1  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 13, 0) && Set KFX metadata (from KFX Output) (1, 27, 0) && KFX Output (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 166.443686007 x 166.254545455
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.59] splash screen shown
[0.59] Initializing db...
[0.59] db initialized
[0.59] Constructing main UI...
[1.83] main UI initialized...
[1.83] Hiding splash screen
[5.73] splash screen hidden
[5.73] Started up in 5.73 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xc0\xb4Fs\xe0T\xf6\xb7\x0f>\xd6s\x88\xedr\xa2A\x17\xf4=1P$<b\xaeO\xd2\xa6\x8fM\xfd', 'C:\\Users\\Charley\\Documents\\My Kindle Content\\B07YWFSV3M_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.13.0: Importing C:\Users\Charley\Documents\My Kindle Content\B07YWFSV3M_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.3: Trying to decrypt B07YWFSV3M_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: GUSH 2019年11月号
Got DSN key from database default_key
Found 4 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\Charley\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Charley\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1008622156' and UserName '436861726c6579'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: GUSH 2019年11月号
Got DSN key from database default_key_1
Found 4 keys to try after 0.9 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added GUSH 2019年11月号 to db in: 1.4
Added 1 books in 3.5 seconds
Worker Launch took: 0.167999982834
Job: 0 Convert book 1 of 1 (GUSH 2019年11月号) finished
Convert book 1 of 1 (GUSH 2019年11月号)
	Conversion options changed from defaults:
	  output_profile: u'tablet'
	  verbose: 2
	  cover: u'C:\\Users\\Charley\\AppData\\Local\\Temp\\calibre_fptg8g\\bdyibl.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\Charley\\AppData\\Local\\Temp\\calibre_fptg8g\\qych4z.opf'
	Resolved conversion options
	calibre version: 4.1.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Charley\\AppData\\Local\\Temp\\calibre_fptg8g\\bdyibl.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x05231D70>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x05241390>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Charley\\AppData\\Local\\Temp\\calibre_fptg8g\\qych4z.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Charley\AppData\Local\Temp\calibre_fptg8g\fzlbp1.azw
	Found KF8 MOBI of type u'standalone'
	P y t h o n   f u n c t i o n   t e r m i n a t e d   u n e x p e c t e d l y 
	 
	     G U S H   2 0 1 9 t^1 1 g�S  ( E r r o r   C o d e :   1 ) 
	 
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: GUSH 2019年11月号

**Comment by ElleKayEm** [comment]
Try using 64-bit calibre.

**Comment by ElleKayEm** [comment]
If it's an AZW4, try the Kindle Unpack plugin.
