### ISSUE TITLE
DeDRM on Windows, BN plugin not working (can't get key)

### ISSUE THREAD

**Issue by mfsteinhour** [apprenticeharper/DeDRM_tools#917]
I tried to retrieve the key based on the instructions in the readme, but every attempt fails. Are there new instructions for getting a key?

Here's the log for the import: 

calibre Debug log
calibre 4.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.0 x 95.9160839161
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.89] splash screen shown
[0.94] Initializing db...
[1.33] db initialized
[1.33] Constructing main UI...
[2.89] main UI initialized...
[2.89] Hiding splash screen
[30.27] splash screen hidden
[30.27] Started up in 30.27 seconds with 2 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xbbvk\xad\xf7\xd6\xdcS\xc1\xbe\xd5\xe8O\xa4nm`\xb62B\x9a\xba\xd5\xfe\x7f'\xad\xd3t\xb8\x1e\x91", 'I:\\eBooks\\Nook epub - Downloaded through WIN Nook app\\DRM\\arcanum101_2940013994034.epub']
DeDRM v6.6.3: Trying to decrypt arcanum101_2940013994034.epub
DeDRM v6.6.3: Verifying zip archive integrity
DeDRM v6.6.3: “arcanum101_2940013994034.epub” is a secure Barnes & Noble ePub
DeDRM v6.6.3: Looking for new NOOK Study Keys after 2.7 seconds
No nook Study log files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 2.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 635, in run
  File "calibre_plugins.dedrm.__init__", line 304, in ePubDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 2.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Arcanum 101: Welcome New Students to db in: 15.6
Added 1 books in 19.1 seconds

**Comment by ElleKayEm** [comment]
Unfortunately the methods for retrieving the B&N keys have been broken for a while now.  There's another thread here discussing getting the key from a rooted Android device, a rooted Nook, or an Android emulator.

https://github.com/apprenticeharper/DeDRM_tools/issues/814

**Comment by mfsteinhour** [comment]
Well, darn. Thanks for the response!
