### ISSUE TITLE
Calibre Plugin Failing on Amazon azw3 book in MacOS 10.14.6

### ISSUE THREAD

**Issue by edcorcoran** [apprenticeharper/DeDRM_tools#923]
Here's teh log

`calibre Debug log
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000163 x 107.500001614
Using calibre Qt style: False
[0.00] Starting up...
[0.02] Initializing db...
[0.03] db initialized
[0.03] Constructing main UI...
[0.94] main UI initialized...
[0.94] Started up in 0.94 seconds with 231 books
DeDRM v6.6.3: Trying to decrypt Capital_ A Critique of Political Economy (Das Kapital series Book 1)_B002XHNMN0.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Capital: A Critique of Political Economy (Das Kapital series Book 1)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

{u'bsd_drives': {u'main': u'/dev/disk4s1'},
 u'drives': {u'main': '/Volumes/Kindle'},
 u'mount_map': {'/dev/disk1s1': '/',
                '/dev/disk1s3': '/Volumes/Recovery',
                '/dev/disk1s4': '/private/var/vm',
                '/dev/disk3s1': '/Volumes/Media',
                '/dev/disk4s1': '/Volumes/Kindle',
                'devfs': '/dev',
                'map -hosts': '/net',
                'map auto_home': '/home'}}
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.1 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.1 USBMS: count found in cache: 129, count of files in metadata: 129, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 129
DeviceJob: set_books_in_library finished: time= 0.0112569332123
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Added Capital: A Critique of Political Economy (Das Kapital series Book 1) to db in: 0.0
Added 1 books in 0.4 seconds
`

**Comment by ElleKayEm** [comment]
Was this downloaded from the website?  Did you choose an E-ink Kindle (not a Fire) for the device?  And did you enter the Kindle's serial number into the DeDRM plugin customization?

**Comment by edcorcoran** [comment]
Not sure what you mean by downloaded from the website. I downloaded the book to my Kindle and moved it to my computer via USB. I did choose e-ink kindle and I did enter the serial number.

The DeDRM used to work but has stopped recently. I don't recall the last time I did this, so I can't tell you what version I would have been on when it last worked.

**Comment by edcorcoran** [comment]
I tried to do it using the standalone app, and it also failed. Here's the log from that:

`There is 1 ebook to be decrypted.
Processing file: Capital_ A Critique of Political Economy (Das Kapital series Book 1)_B002XHNMN0.azw3
shellcommand: /usr/bin/python '/private/var/folders/yg/gj0qttqn15n2lpd3470t6jw00000gn/T/AppTranslocation/DDED58DF-BDE9-4A4D-A252-38FE01DF5A83/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -s 'B00E1510223502NL' '/Users/ed/Downloads/Capital_ A Critique of Political Economy (Das Kapital series Book 1)_B002XHNMN0.azw3' '/Users/ed/Downloads/' > '/Users/ed/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.4.
Copyright © 2008-2013 The Dark Reverser et al.
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Capital: A Critique of Political Economy (Das Kapital series Book 1)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 2 keys tried.
 Traceback (most recent call last):
  File "/private/var/folders/yg/gj0qttqn15n2lpd3470t6jw00000gn/T/AppTranslocation/DDED58DF-BDE9-4A4D-A252-38FE01DF5A83/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 254, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/private/var/folders/yg/gj0qttqn15n2lpd3470t6jw00000gn/T/AppTranslocation/DDED58DF-BDE9-4A4D-A252-38FE01DF5A83/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 228, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/private/var/folders/yg/gj0qttqn15n2lpd3470t6jw00000gn/T/AppTranslocation/DDED58DF-BDE9-4A4D-A252-38FE01DF5A83/d/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 2 keys tried.
shellcommand: /usr/bin/python '/private/var/folders/yg/gj0qttqn15n2lpd3470t6jw00000gn/T/AppTranslocation/DDED58DF-BDE9-4A4D-A252-38FE01DF5A83/d/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/ed/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/ed/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.3
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
No k4Mac kindle-info/rainier/kinf2011 files have been found.
Could not retrieve Kindle for Mac/PC key.
 
There was an error with 1 ebook:
Capital_ A Critique of Political Economy (Das Kapital series Book 1)_B002XHNMN0.azw3 couldn't be decrypted.

There is 1 ebook to be decrypted.
Processing file: Capital_ A Critique of Political Economy (Das Kapital series Book 1)_B002XHNMN0.azw3
shellcommand: /usr/bin/python '/private/var/folders/yg/gj0qttqn15n2lpd3470t6jw00000gn/T/AppTranslocation/DDED58DF-BDE9-4A4D-A252-38FE01DF5A83/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -s 'B00E1510223502NL' '/Users/ed/Downloads/Capital_ A Critique of Political Economy (Das Kapital series Book 1)_B002XHNMN0.azw3' '/Users/ed/Downloads/' > '/Users/ed/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.4.
Copyright © 2008-2013 The Dark Reverser et al.
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Capital: A Critique of Political Economy (Das Kapital series Book 1)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 2 keys tried.
 Traceback (most recent call last):
  File "/private/var/folders/yg/gj0qttqn15n2lpd3470t6jw00000gn/T/AppTranslocation/DDED58DF-BDE9-4A4D-A252-38FE01DF5A83/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 254, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/private/var/folders/yg/gj0qttqn15n2lpd3470t6jw00000gn/T/AppTranslocation/DDED58DF-BDE9-4A4D-A252-38FE01DF5A83/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 228, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/private/var/folders/yg/gj0qttqn15n2lpd3470t6jw00000gn/T/AppTranslocation/DDED58DF-BDE9-4A4D-A252-38FE01DF5A83/d/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 2 keys tried.
shellcommand: /usr/bin/python '/private/var/folders/yg/gj0qttqn15n2lpd3470t6jw00000gn/T/AppTranslocation/DDED58DF-BDE9-4A4D-A252-38FE01DF5A83/d/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/ed/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/ed/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.3
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
No k4Mac kindle-info/rainier/kinf2011 files have been found.
Could not retrieve Kindle for Mac/PC key.
 
There was an error with 1 ebook:
Capital_ A Critique of Political Economy (Das Kapital series Book 1)_B002XHNMN0.azw3 couldn't be decrypted.

`

**Comment by edcorcoran** [comment]
I also tried the steps in this issue (https://github.com/apprenticeharper/DeDRM_tools/issues/800). The Python modules installed, but it didn't seem to make a difference.

**Comment by ElleKayEm** [comment]
The only error I'm seeing is that the key it has is not working for that book.  Make sure you have the serial number correct.  Try copy and paste from the website (removing any spaces).

**Comment by edcorcoran** [comment]
*facepalm* I was using the serial number for my old Kindle. Apologies!
