### ISSUE TITLE
Adobe Digital Editions Adept DRM removal time limit

### ISSUE THREAD

**Issue by jrp13149** [apprenticeharper/DeDRM_tools#926]
Hi,

I'm able to borrow a digital book from a library for 24 hours, and download it using Adobe Digital Editions. After 24 hours ADE advises that the loan has expired and will no longer open the book.

So there is something else going on as well as DRM - there is a time limit being imposed.

I'd like to remove this so i dont have to keep borrowing the same book everyday, and losing my place.

DeDRM fails with an 'error decrypting book session key' message.

I'm dabbling on my laptop at the moment, and will reproduce on my workstation later, and attach some log files. But I am curious. Is this a known issue? Could ADE be using a second key that gets removed after 24 hours, that DeDRM doesn't know about?

Thanks!

**Comment by ElleKayEm** [comment]
These tools aren't intended to work on library books.

**Comment by ZolaLa9** [comment]
Interesting. As ElleKayEm notes, these tools aren't intended for library books. 

However, I'm curious if your library is using Adobe's hardened DRM. 

1) What version ADE are you using? 

2) If you're willing, please open the .acsm file in a text editor:

- Look for something like: <operatorURL>https://something-something.com/fulfillment</operatorURL>
- Add "statuscheck" to the end of the url: <operatorURL>https://something-something.com/fulfillment/statuscheck
- Paste in browser and report back what version comes back in the 3rd item on the results list. It should be something like 4.1, 4.2, 5.0, etc.

This won't help you get past the DRM, but it will let us know if the new hardened DRM is in play.

**Comment by jrp13149** [comment]
It shows version 6.5.0,

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
