### ISSUE TITLE
epub

### ISSUE THREAD

**Issue by alanbsmithee** [apprenticeharper/DeDRM_tools#933]
Since installing OS Catalina, I can no longer open epub books on iBooks that I've backed up from Kindle purchases and converted via Calibre. The error message is "This book is corrupt".

**Comment by ZolaLa9** [comment]
Maybe try deleting the contents of 
~/Library/Containers/com.apple.BKAgentService/Data/Documents/iBooks/Updates

See this Apple Support discussion: https://discussions.apple.com/thread/250735059?answerId=251495630022#251495630022

**Comment by alanbsmithee** [comment]
I was able to resolve this here:
https://discussions.apple.com/thread/250717809?answerId=251397644022#251397644022
if anyone has the same problem
