### ISSUE TITLE
DeDRM Isn't Working

### ISSUE THREAD

**Issue by Jo-Grant** [apprenticeharper/DeDRM_tools#943]
I've bought a ton of books on Amazon over the years, but I don't use a Kindle anymore.  I just want to be able to open those books on my tablet.  I've used Calibre for many years so I didn't have any problem installing your zip file...but it's not working.  Nothing's happening when I import books.  I ran it under safe mode and this is the log file it gave me.  Thank you very much for your help!!

calibre Debug log
calibre 4.3  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.16+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.3  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.16+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 91.745819398
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.52] splash screen shown
[1.52] Initializing db...
[1.56] db initialized
[1.56] Constructing main UI...
[4.22] main UI initialized...
[4.22] Hiding splash screen
[10.16] splash screen hidden
[10.17] Started up in 10.17 seconds with 0 books
DeDRM v6.6.3: Trying to decrypt Last Chance to See.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Last Chance to See
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Jo\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\Jo\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2326554800' and UserName '4a6f'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Last Chance to See
Got DSN key from database default_key_1
Found 3 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Last Chance to See to db in: 1.2
Added 1 books in 3.7 seconds
Worker Launch took: 0.973999977112
Job: 0 Convert book 1 of 1 (Last Chance to See) finished
Convert book 1 of 1 (Last Chance to See)
	Conversion options changed from defaults:
	  output_profile: u'generic_eink'
	  verbose: 2
	  cover: u'C:\\Users\\Jo\\AppData\\Local\\Temp\\calibre_qe6sri\\xzne0e.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\Jo\\AppData\\Local\\Temp\\calibre_qe6sri\\an8bd8.opf'
	Resolved conversion options
	calibre version: 4.3.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Jo\\AppData\\Local\\Temp\\calibre_qe6sri\\xzne0e.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x063FA950>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x063FAB50>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Jo\\AppData\\Local\\Temp\\calibre_qe6sri\\an8bd8.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Jo\AppData\Local\Temp\calibre_qe6sri\3rxqxe.azw3
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  Last Chance to See (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Last Chance to See

Worker Launch took: 1.02400016785
Job: 1 Convert book 1 of 1 (Last Chance to See) finished
Convert book 1 of 1 (Last Chance to See)
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: u'generic_eink'
	  cover: u'C:\\Users\\Jo\\AppData\\Local\\Temp\\calibre_qe6sri\\efnjub.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\Jo\\AppData\\Local\\Temp\\calibre_qe6sri\\nsmwkx.opf'
	Resolved conversion options
	calibre version: 4.3.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Jo\\AppData\\Local\\Temp\\calibre_qe6sri\\efnjub.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x06038950>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x06038B50>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Jo\\AppData\\Local\\Temp\\calibre_qe6sri\\nsmwkx.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Jo\AppData\Local\Temp\calibre_qe6sri\bfijd1.azw3
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  Last Chance to See (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Last Chance to See

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then you need to enter its serial number into the DeDRM plugin customization.

**Comment by Jo-Grant** [comment]
I don't remember whether I downloaded it for my 3rd Generation Kindle or my Fire, but I've never had an E-Ink and I wouldn't have a clue where to find its serial number.

**Comment by ElleKayEm** [comment]
It won't work with the Fire, but will with the Kindle.  Easiest way to find the serial number is on the website here:

amazon.com/mycd

Click the 3-dot button next to your Kindle.  Copy and paste the serial number (removing spaces).

**Comment by Jo-Grant** [comment]
The Calibre popup doesn't give me an option to enter the serial number.  There is no configuration for a standard Kindle device.  There's only eInk Kindle ebooks, Kindle for Android ebooks, B&N ebooks, Mobipocket ebooks, eReader ebooks, Adobe Digital Editions ebooks, and Mindle for Mac/PC ebooks.

**Comment by ElleKayEm** [comment]
Standard Kindle is an E-ink Kindle.  Any Kindle device that's not a Kindle Fire tablet.

**Comment by Jo-Grant** [comment]
I tried that before replying before.  It requires a 16 character string but mine is 18 characters.

**Comment by ElleKayEm** [comment]
If it's a 3rd generation Kindle (with a keyboard), their serial numbers typically start with B006, B008, or B00A.  But that generation doesn't support .azw3 files.  So this book is probably for your Fire and that copy can't be decrypted.  Unless you meant 3rd generation Paperwhite, then those usually start G090 and can handle .azw3 files.  But either way, as you said, it should be 16, not 18 characters.  So I'm not sure what's up with that.

If it is a Kindle Keyboard, then I would recommend downloading the book with Kindle for PC instead (no serial number needed).  But you will need to install version 1.24 or earlier.  Details and a link for that version here:

https://www.mobileread.com/forums/showthread.php?t=283371

For method 4, you will also need the KFX Input plugin.

**Comment by Jo-Grant** [comment]
No, I've never had a paperwhite.  And I think I figured out the problem.  I was stupidly trying to enter in the warranty number, not the serial number.  Doh!

I was going to ask if I could re-download the book to my PC as a fresh copy, but you answered that.  :-)  Thanks for putting up with my obliviot mistake; that should teach me not to work on this in the wee hours when I'm tired.

Quite a few of these books were downloaded to the Fire, so I'll look into the link you sent.  Hopefully it will work for me!

**Comment by Jo-Grant** [comment]
It seems to be working...I've run into a few books that won't convert, but the bulk of them are opening just fine now.  THANK YOU for your help!

**Comment by ElleKayEm** [comment]
For the most part, it should be all or nothing.  Although if you throw too much at it at once, they might not all work.  I'd try adding the ones that didn't work again in smaller batches.  If they still have DRM, post a log for just one of them.

**Comment by Jo-Grant** [comment]
The only two I couldn't convert were Andersen's Fairy Tales, which was a public domain book so I don't know why it was DRM'd to begin with, and Rendezvous With Rama.  Everything else converted to epub, mobi, and azw3 (so all bases were covered on all my devices) without a problem.

**Comment by Jo-Grant** [comment]
This is the conversion error log from Rendezvous With Rama:

Convert book 1 of 1 (Rama 01 - Rendezvous with Rama)
Conversion options changed from defaults:
  output_profile: u'generic_eink'
  verbose: 2
  read_metadata_from_opf: u'C:\\Users\\Jo\\AppData\\Local\\Temp\\calibre_a46du2\\92tzbt.opf'
Resolved conversion options
calibre version: 4.3.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x05C30950>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x05C30B50>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Jo\\AppData\\Local\\Temp\\calibre_a46du2\\92tzbt.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\Jo\AppData\Local\Temp\calibre_a46du2\a7wgjl.mobi
Extracting text...
Extracting text...
Python function terminated unexpectedly
  ord() expected a character, but string of length 0 found (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 39, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 163, in extract_content
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 793, in extract_text
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 787, in text_section
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 777, in sizeof_trailing_entries
TypeError: ord() expected a character, but string of length 0 found

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre, not during conversion.  So I can't tell from this if anything went wrong with DeDRM.  I suspect the DRM was already removed (or not there at all in the case of the PD book) but the conversion attempt just ran out of memory.  I see in the first log that you have 32-bit calibre.  Try 64-bit calibre.  You can have both versions installed so you could just try adding a copy of the book from 32-bit calibre to 64-bit calibre and see if it will convert.

**Comment by Jo-Grant** [comment]
About a dozen wouldn't convert, even when I downloaded brand-new copies directly from my Amazon account.  I noticed that I could drag azw3 files into Calibre and they'd automatically change to a mobi.  When that happened, they converted fine.  When they stayed as an azw3 file, they wouldn't convert.

Tell you what, though, Calibre absolutely hates the new plugin!  It crashes at least 50% of the time now.  Could someone please offer some advice on this?  Because I use Calibre almost daily as part of my job, and this is causing some serious issues.

Thank you!

**Comment by ElleKayEm** [comment]
AZW3 or just AZW?  Are you downloading via Kindle for PC or from the website?  If the website, remember to choose your Kindle Keyboard (not the Fire) for the device.

As for crashing, did you try 64-bit calibre?

**Comment by Jo-Grant** [comment]
AZW3.  And I downloaded from their website to my Kindle for PC.  Then I imported them into Calibre and converted them.

I'm using version 4.6.0, but I can't find anywhere to tell me whether it's 32-bit or 64-bit.  Maybe I'm looking in the wrong place under Preferences?

**Comment by ElleKayEm** [comment]
The books downloaded with Kindle for PC found in the Kindle Content folder will all have the AZW extension.  If they are showing MOBI and AZW3 once imported into calibre, then the DRM is removed.

Look on the lower left corner of calibre.  It will have [64-bit] after the version number if it is.  You had 32-bit when you posted that first log.

**Comment by Jo-Grant** [comment]
It just says calibre 4.6 created by Kovid Goyal.  I didn't even see an option for 64 bit when I upgraded.

**Comment by ElleKayEm** [comment]
https://calibre-ebook.com/download_windows64

**Comment by Jo-Grant** [comment]
Thanks for that url!  I'll give it a try.  Hopefully the crashing problem will stop.

**Comment by Jo-Grant** [comment]
That seems to have fixed the problem...thank you so much for your help!!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by Jo-Grant** [comment]
Looks like it, knock on wood.  ;-)  Thanks again!
