### ISSUE TITLE
DeDRM 6.6.3 failing

### ISSUE THREAD

**Issue by parosio** [apprenticeharper/DeDRM_tools#944]
Hello, 
I've just started using DeDRM tool with Calibre on azw ebook. Initially I had Kindle for PC v1.21, but after reading the faq I installed the 1.17.0.

The log below refers to an ebook downloaded with the old version.

	calibre Log di debug
	calibre 4.5  embedded-python: True is64bit: False
	Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
	32bit process running on 64bit windows
	('Windows', '10', '10.0.17763')
	Python 2.7.16+
	Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
	Interface language: it
	Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 24, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 24, 0) && KFX metadata reader (from KFX Input) (1, 24, 0) && KFX Input (1, 24, 0)
	calibre 4.5  embedded-python: True is64bit: False
	Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
	32bit process running on 64bit windows
	('Windows', '10', '10.0.17763')
	Python 2.7.16+
	Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
	Interface language: it
	Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 24, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 24, 0) && KFX metadata reader (from KFX Input) (1, 24, 0) && KFX Input (1, 24, 0)
	Turning on automatic hidpi scaling
	devicePixelRatio: 1.0
	logicalDpi: 96.0 x 96.0
	physicalDpi: 100.861627907 x 100.55257732
	Using calibre Qt style: True
	[0.00] Starting up...
	[0.00] Showing splash screen...
	[0.53] splash screen shown
	[0.53] Initializing db...
	[0.56] db initialized
	[0.56] Constructing main UI...
	Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
	[2.62] main UI initialized...
	[2.62] Hiding splash screen
	[6.16] splash screen hidden
	[6.16] Started up in 6.16 seconds with 387 books
	Gather KFX-ZIP (from KFX Input) 1.24.0: Importing C:/Users/Paolo/Documents/My Kindle Content/B01A5VHDEY_EBOK.azw
	Gather KFX-ZIP (from KFX Input): File is not KFX format
	DeDRM v6.6.3: Trying to decrypt B01A5VHDEY_EBOK.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.42.
	Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Central Station
	Found 0 keys to try after 0.2 seconds
	Crypto Type is: 2
	DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
	DeDRM v6.6.3: Looking for new default Kindle Key after 0.2 seconds
	searching for kinfoFiles in C:\Users\Paolo\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\Paolo\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '2584045295' and UserName '50616f6c6f'
	DeDRM v6.6.3: Found 1 new key
	MobiDeDrm v0.42.
	Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Central Station
	Got DSN key from database default_key_1
	Found 4 keys to try after 0.3 seconds
	Crypto Type is: 2
	DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 624, in run
	  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
	DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Added Central Station to db in: 0.3
	Added 1 books in 2.3 seconds
	Worker Launch took: 0.286000013351

Is there some configuration I'm missing?

**Comment by ElleKayEm** [comment]
Did you re-download your book with 1.17?

**Comment by parosio** [comment]
Hi, yes:

- I completely deleted the content of My Kindle Library folder, 
- opened Kindle for PC, 
- downloaded that single ebook and 
- dragged it to Calibre UI (started in debug mode).

**Comment by ElleKayEm** [comment]
If Kindle for PC can't open it, then I'm not surprised DeDRM is unable to remove the DRM.  Did you try redownloading it as the error message suggested?

**Comment by parosio** [comment]
Yes, more than once. 
Also tried with other books. They get downloaded, but Kindle PC cannot visualize them.
I can open with Kindle PC only ebooks without DRM, apparently.

Should I unregister Kindle PC or reinstall it, maybe? (the installation over the previous (more recent) version didn't throw any error, apparently); almost all of the files in the KindlPC directory have 08/16/2016 date, except for these:
![image](https://user-images.githubusercontent.com/26117071/69905928-6c990080-13bb-11ea-909e-ba64c1931d01.png)

**Comment by ElleKayEm** [comment]
Yes, I think there's probably something left from that previous install that's causing a conflict.  Try the uninstall/reinstall instructions here:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

**Comment by parosio** [comment]
Just an additional information: 
I just restarted KindlePC as administrator (had to register it to my Amazon account), downloaded and opened two books (which I could not read before within KindlePC with my unpriviledged PC account).

However, the import to Calibre of these two books shows the same result:

	calibre Log di debug
	calibre 4.5  embedded-python: True is64bit: False
	Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
	32bit process running on 64bit windows
	('Windows', '10', '10.0.17763')
	Python 2.7.16+
		[... cut ...]
	[35.75] Started up in 35.75 seconds with 388 books
	Gather KFX-ZIP (from KFX Input) 1.24.0: Importing C:/Users/Paolo/Documents/AdminKindleContent/B00UXKJ1SO_EBOK.azw
	Gather KFX-ZIP (from KFX Input): File is not KFX format
	DeDRM v6.6.3: Trying to decrypt B00UXKJ1SO_EBOK.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.42.
	Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: A Manual for Cleaning Women: Selected Stories
	Found 0 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
	DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Paolo\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\Paolo\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '2584045295' and UserName '50616f6c6f'
	DeDRM v6.6.3: Found 1 new key
	MobiDeDrm v0.42.
	Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: A Manual for Cleaning Women: Selected Stories
	Got DSN key from database default_key_1
	Found 4 keys to try after 0.3 seconds
	Crypto Type is: 2
	DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 624, in run
	  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
	DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Added A Manual for Cleaning Women: Selected Stories to db in: 0.3
	Added 1 books in 2.1 seconds
	Gather KFX-ZIP (from KFX Input) 1.24.0: Importing C:/Users/Paolo/Documents/AdminKindleContent/B01A5VHDEY_EBOK.azw
	Gather KFX-ZIP (from KFX Input): File is not KFX format
	DeDRM v6.6.3: Trying to decrypt B01A5VHDEY_EBOK.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.42.
	Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Central Station
	Found 0 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
	DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Paolo\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\Paolo\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '2584045295' and UserName '50616f6c6f'
	DeDRM v6.6.3: Found 1 new key
	MobiDeDrm v0.42.
	Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Central Station
	Got DSN key from database default_key_1
	Found 4 keys to try after 0.3 seconds
	Crypto Type is: 2
	DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 624, in run
	  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
	DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Added Central Station to db in: 0.3
	Added 1 books in 2.0 seconds

I will try what suggested in the next days, and will come back with the results. 
By then, thank you for your time...

**Comment by parosio** [comment]
Finally found time to remove and reinstall the Kindle application for PC (1.17). Now the plugin works as expected. Thank you @ElleKayEm.

**Comment by ElleKayEm** [comment]
Thanks for reporting back.
