### ISSUE TITLE
Kobo doesn't seem to be in the plugins any more.

### ISSUE THREAD

**Issue by urcminister** [apprenticeharper/DeDRM_tools#95]
![screenshot from 2016-04-18 16-53-46](https://cloud.githubusercontent.com/assets/10630078/14610531/3a5e5184-0586-11e6-8faf-90506e1f0726.png)

I've attached a screenshot.  The same plugin had Kobo as an option on a previously installed Calibre.  This version is Calibre 2.54.  Have you any suggestions please?

**Comment by apprenticeharper** [comment]
DeDRM has never handled Kobo books from the Kobo Desktop app (.kepub). Kobo books downloaded using ADE use the ADE keys.

You might be thinking of the obok plugin, which is also included in the archive.

**Comment by urcminister** [comment]
On 18/04/16 17:52, Apprentice Harper wrote:
>
> DeDRM has never handled Kobo books from the Kobo Desktop app (.kepub). 
> Kobo books downloaded using ADE use the ADE keys.
>
Hi ...   I've found the old version in my archives.  I can't install it, 
as it needs an older version of Python, so I'll have to do a mod later.  
I've put it here:
https://www.dropbox.com/s/du1go770c8gc618/DeDRM_plugin.zip?dl=0

Regards,        Barry.

**Comment by ElleKayEm** [comment]
Kobo ebooks can be downloaded as Adobe Digital Edition epubs.  You can use the current DeDRM plugin to decrypt them.

The DeDRM tools have never been able to decrypt Kobo's kepubs.  You need the Obok plugin for that.

**Comment by apprenticeharper** [comment]
What ElleKayEm said. Not an issue.
