### ISSUE TITLE
UnicodeDecodeError: 'utf8'

### ISSUE THREAD

**Issue by redienhcs** [apprenticeharper/DeDRM_tools#951]
I have a problem removing the Drm from kindle books. I attached the log file from calibre.
Kindle for PC - 1.24
Calibre 4.3
DeDRM 6.6.3

[calibrelog.txt](https://github.com/apprenticeharper/DeDRM_tools/files/3926834/calibrelog.txt)

**Comment by ElleKayEm** [comment]
KFX format - install the KFX Input plugin.  Or modify Kindle for PC so it doesn't download KFX format files and redownload the book.  Details here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by redienhcs** [comment]
Thank you very much, it worked. Appreciated the fast and to the point response.

[]s
