### ISSUE TITLE
No k4Mac kindle-info/rainier/kinf2011 files have been found

### ISSUE THREAD

**Issue by michaeljmuller** [apprenticeharper/DeDRM_tools#953]
I had everything set up and working fine, but then I upgraded my Mac to Catalina (64-bit only) and could no longer run the old version of the Kindle application on my Mac. 

I have a PC that I use for gaming, so I installed version 1.17.0 of Kindle for Windows there.

I took the AZW file from my windows machine, sent it over to the Mac, and added it to Calibre on the Mac.  It failed to De-DRM the file with this error:  

No k4Mac kindle-info/rainier/kinf2011 files have been found

Any ideas what I'm doing wrong?  Log is attached.

  -- Mike

[tmpjLzSGO.txt](https://github.com/apprenticeharper/DeDRM_tools/files/3942320/tmpjLzSGO.txt)

**Comment by ElleKayEm** [comment]
Kindle for PC/Mac and DeDRM must be on the same machine and user in order to retrieve the necessary key.  Each installation of the app/device has its own unique key, even for the same account.  So install calibre and DeDRM on the Windows machine.

**Comment by michaeljmuller** [comment]
Good to know!  I really prefer to have my Calibre library on the Mac.  Worst case, I'll run it both places and sync from one to the other.  But first, I'll look into creating a batch script (instead of Calibre's plugin that strips the DRM from my Kindle books and sends them to my Mac for inclusion in the Calibre library.

Thank you so much for your help!
