### ISSUE TITLE
Trouble removing DRM - Win 10 - Kindle for PC 1.24.3

### ISSUE THREAD

**Issue by tedsears** [apprenticeharper/DeDRM_tools#956]
Having read the readme closely, it appears to me that Kindle for PC 1.24.3 should work now with the KFX input plugin.

I have followed the directions to deregister, uninstall, delete folders, and reinstall, and continue to have this issue.

Book opens fine in Kindle for PC app.

Any idea what I'm doing wrong - the important lines seem to be:

Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds.

Full Log:
C:\Users\USER>calibre-debug -g
calibre 4.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 25, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 25, 0) && KFX metadata reader (from KFX Input) (1, 25, 0) && KFX Input (1, 25, 0) && Set KFX metadata (from KFX Output) (1, 35, 0) && KFX Output (1, 35, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 109.493734336 x 109.182089552
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.47] splash screen shown
[0.47] Initializing db...
[0.47] db initialized
[0.47] Constructing main UI...
[2.05] main UI initialized...
[2.05] Hiding splash screen
[2.17] splash screen hidden
[2.19] Started up in 2.19 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xc1\x1a\xf41\x8f\x03\xe8&\xc9\xf0\x8b\xe7 \x91\x9c\xa3\xcb^\xa1\xedZ\x82\x96s\x83\x1dk\x17\x8br\x83"', 'C:\\Users\\USER\\Documents\\My Kindle Content\\B007TBZ63Y_EBOK\\B007TBZ63Y_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.25.0: Importing C:\Users\USER\Documents\My Kindle Content\B007TBZ63Y_EBOK\B007TBZ63Y_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 5 file(s) as C:\Users\USER~1\AppData\Local\Temp\calibre_aiukmh\utrkpb.kfx-zip
DeDRM v6.6.3: Trying to decrypt utrkpb.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: utrkpb
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.77858398-090f-4d97-bbc9-cb42fc2b5b5c.voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\USER\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\USER\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '985089828' and UserName '546564205365617273'
DeDRM v6.6.3: Found 1 new key
Decrypting KFX-ZIP ebook: utrkpb
Got DSN key from database default_key_1
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.77858398-090f-4d97-bbc9-cb42fc2b5b5c.voucher
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.25.0: Packaging C:\Users\USER~1\AppData\Local\Temp\calibre_aiukmh\utrkpb.kfx-zip
Processing container: B007TBZ63Y_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 88, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 161, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 268, in get_container
KFXDRMError: Book container B007TBZ63Y_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\USER~1\AppData\Local\Temp\calibre_aiukmh\e5al37_add_books\0\B007TBZ63Y_EBOK.kfx-zip
Added The Mark of Athena (The Heroes of Olympus, Book 3) to db in: 0.2
Added 1 books in 1.3 seconds
Worker Launch took: 0.124000072479
Job: 0 Convert book 1 of 1 (The Mark of Athena (The Heroes of Olympus, Book 3)) finished
Convert book 1 of 1 (The Mark of Athena (The Heroes of Olympus, Book 3))
        Conversion options changed from defaults:
          verbose: 2
          cover: u'C:\\Users\\USER~1\\AppData\\Local\\Temp\\calibre_aiukmh\\0nkqsp.jpeg'
          read_metadata_from_opf: u'C:\\Users\\USER~1\\AppData\\Local\\Temp\\calibre_aiukmh\\rlj7ru.opf'
        Resolved conversion options
        calibre version: 4.6.0
        {'allow_conversion_with_errors': False,
         'asciiize': False,
         'author_sort': None,
         'authors': None,
         'base_font_size': 0.0,
         'book_producer': None,
         'change_justification': u'original',
         'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
         'chapter_mark': u'pagebreak',
         'comments': None,
         'cover': u'C:\\Users\\USER~1\\AppData\\Local\\Temp\\calibre_aiukmh\\0nkqsp.jpeg',
         'debug_pipeline': None,
         'dehyphenate': True,
         'delete_blank_paragraphs': True,
         'disable_font_rescaling': False,
         'dont_split_on_page_breaks': False,
         'duplicate_links_in_toc': False,
         'embed_all_fonts': False,
         'embed_font_family': None,
         'enable_heuristics': False,
         'epub_flatten': False,
         'epub_inline_toc': False,
         'epub_toc_at_end': False,
         'epub_version': u'2',
         'expand_css': False,
         'extra_css': None,
         'extract_to': None,
         'filter_css': u'',
         'fix_indents': True,
         'flow_size': 260,
         'font_size_mapping': None,
         'format_scene_breaks': True,
         'html_unwrap_factor': 0.4,
         'input_encoding': None,
         'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001F25F230908>,
         'insert_blank_line': False,
         'insert_blank_line_size': 0.5,
         'insert_metadata': False,
         'isbn': None,
         'italicize_common_cases': True,
         'keep_ligatures': False,
         'language': None,
         'level1_toc': None,
         'level2_toc': None,
         'level3_toc': None,
         'line_height': 0.0,
         'linearize_tables': False,
         'margin_bottom': 5.0,
         'margin_left': 5.0,
         'margin_right': 5.0,
         'margin_top': 5.0,
         'markup_chapter_headings': True,
         'max_toc_links': 50,
         'minimum_line_height': 120.0,
         'no_chapters_in_toc': False,
         'no_default_epub_cover': False,
         'no_inline_navbars': False,
         'no_svg_cover': False,
         'output_profile': <calibre.customize.profiles.OutputProfile object at 0x000001F25F236488>,
         'page_breaks_before': u'/',
         'prefer_metadata_cover': False,
         'preserve_cover_aspect_ratio': False,
         'pretty_print': True,
         'pubdate': None,
         'publisher': None,
         'rating': None,
         'read_metadata_from_opf': u'C:\\Users\\USER~1\\AppData\\Local\\Temp\\calibre_aiukmh\\rlj7ru.opf',
         'remove_fake_margins': True,
         'remove_first_image': False,
         'remove_paragraph_spacing': False,
         'remove_paragraph_spacing_indent_size': 1.5,
         'renumber_headings': True,
         'replace_scene_breaks': u'',
         'search_replace': '[]',
         'series': None,
         'series_index': None,
         'smarten_punctuation': False,
         'sr1_replace': None,
         'sr1_search': None,
         'sr2_replace': None,
         'sr2_search': None,
         'sr3_replace': None,
         'sr3_search': None,
         'start_reading_at': None,
         'subset_embedded_fonts': False,
         'tags': None,
         'timestamp': None,
         'title': None,
         'title_sort': None,
         'toc_filter': None,
         'toc_threshold': 6,
         'toc_title': None,
         'transform_css_rules': '[]',
         'unsmarten_punctuation': False,
         'unwrap_lines': True,
         'use_auto_toc': False,
         'verbose': 2}
        InputFormatPlugin: KFX Input running
        on C:\Users\USER~1\AppData\Local\Temp\calibre_aiukmh\gxwnoa.kfx-zip
        Software versions: KFX Input 1.25.0, calibre 4.6 [64bit], Windows-10-10.0.18362-SP0
        KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
        Converting C:\Users\USER~1\AppData\Local\Temp\calibre_aiukmh\gxwnoa.kfx-zip
        Processing container: B007TBZ63Y_EBOK.azw
        Traceback (most recent call last):
          File "calibre_plugins.kfx_input.__init__", line 100, in convert
          File "calibre_plugins.kfx_input.__init__", line 195, in convert_from_kfx
          File "calibre_plugins.kfx_input.kfxlib.yj_book", line 107, in convert_to_epub
          File "calibre_plugins.kfx_input.kfxlib.yj_book", line 161, in decode_book
          File "calibre_plugins.kfx_input.kfxlib.yj_book", line 268, in get_container
        KFXDRMError: Book container B007TBZ63Y_EBOK.azw has DRM and cannot be converted
        Python function terminated unexpectedly
          This book has DRM! (Error Code: 1)
         Traceback (most recent call last):
          File "site.py", line 114, in main
          File "site.py", line 88, in run_entry_point
          File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
          File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
          File "site-packages\calibre\customize\conversion.py", line 246, in __call__
          File "calibre_plugins.kfx_input.__init__", line 103, in convert
        calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
Nothing's raising any flags for me here.  If you've already tried a fresh install, then the only thing I can think to suggest is shutting off downloads of KFX format.  Maybe you'll have better luck with the older formats.  See method 2 in this post:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by ElleKayEm** [comment]
As reported in another issue, there's a problem between the KFX Input plugin and version 4.6 of calibre.  Go back to the previous version of calibre and you should be ok.

**Comment by tedsears** [comment]
The KFX issue is likely it.  When I disabled KFX, it worked correctly on the az3 file.

**Comment by ElleKayEm** [comment]
Thanks for letting us know.
