### ISSUE TITLE
DeDRM does not work on import; fails on conversion

### ISSUE THREAD

**Issue by sst-76** [apprenticeharper/DeDRM_tools#961]
calibre Debug log
calibre 4.6  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 25, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 25, 0) && Set KFX metadata (from KFX Output) (1, 35, 0) && KFX Output (1, 35, 0) && KFX metadata reader (from KFX Input) (1, 25, 0) && KFX Input (1, 25, 0)
calibre 4.6  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 25, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 25, 0) && Set KFX metadata (from KFX Output) (1, 35, 0) && KFX Output (1, 35, 0) && KFX metadata reader (from KFX Input) (1, 25, 0) && KFX Input (1, 25, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 135.5328125 x 135.466666667
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.05] splash screen shown
[1.05] Initializing db...
[1.11] db initialized
[1.11] Constructing main UI...
Ignoring blacklisted device: The \\?\usb#vid_18d1&pid_4ee1#8c9x1ladw#{6ac27878-a6fa-4155-ba85-f98f491d4f33} device has been blacklisted by the user
[4.19] main UI initialized...
[4.19] Hiding splash screen
[45.31] splash screen hidden
[45.31] Started up in 45.31 seconds with 272 books
Gather KFX-ZIP (from KFX Input) 1.25.0: Importing C:/Users/elliot/Documents/My Kindle Content/B07H18VSWK_EBOK/B07H18VSWK_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as C:\Users\elliot\AppData\Local\Temp\calibre_8zbuyk\th7bdh.kfx-zip
DeDRM v6.6.3: Trying to decrypt th7bdh.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: th7bdh
Got DSN key from database default_key
Found 2 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.72eaf4e8-14df-4465-8554-14b81906ab1e.voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\elliot\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\elliot\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3668832373' and UserName '656c6c696f74'
DeDRM v6.6.3: Found 1 new key
Decrypting KFX-ZIP ebook: th7bdh
Got DSN key from database default_key_1
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.72eaf4e8-14df-4465-8554-14b81906ab1e.voucher
DeDRM v6.6.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.25.0: Packaging C:\Users\elliot\AppData\Local\Temp\calibre_8zbuyk\th7bdh.kfx-zip
Processing container: B07H18VSWK_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 88, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 161, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 268, in get_container
KFXDRMError: Book container B07H18VSWK_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\elliot\AppData\Local\Temp\calibre_8zbuyk\keoo4h_add_books\0\B07H18VSWK_EBOK.kfx-zip
Added A Fall of Moondust (Arthur C. Clarke Collection) to db in: 0.6
Added 1 books in 3.8 seconds
Worker Launch took: 0.43799996376
Job: 0 Convert book 1 of 1 (A Fall of Moondust (Arthur C. Clarke Collection)) finished
Convert book 1 of 1 (A Fall of Moondust (Arthur C. Clarke Collection))
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\elliot\\AppData\\Local\\Temp\\calibre_8zbuyk\\gettkb.opf'
	  output_profile: u'kindle_pw3'
	  verbose: 2
	  cover: u'C:\\Users\\elliot\\AppData\\Local\\Temp\\calibre_8zbuyk\\g0vypo.jpeg'
	Resolved conversion options
	calibre version: 4.6.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\elliot\\AppData\\Local\\Temp\\calibre_8zbuyk\\g0vypo.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0520FC10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x05220030>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\elliot\\AppData\\Local\\Temp\\calibre_8zbuyk\\gettkb.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\elliot\AppData\Local\Temp\calibre_8zbuyk\ru7ehu.kfx-zip
	Software versions: KFX Input 1.25.0, calibre 4.6, Windows-10-10.0.18362-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\elliot\AppData\Local\Temp\calibre_8zbuyk\ru7ehu.kfx-zip
	Processing container: B07H18VSWK_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 100, in convert
	  File "calibre_plugins.kfx_input.__init__", line 195, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 107, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 161, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 268, in get_container
	KFXDRMError: Book container B07H18VSWK_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 103, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
There's a problem between calibre 4.6 and the KFX Input plugin right now.  Go back to calibre 4.5 or disable KFX downloads from K4PC.

**Comment by j-howell** [comment]
> There's a problem between calibre 4.6 and the KFX Input plugin right now.

The KFX Input plugin works fine with the latest calibre. 

As far as I can tell the incompatibility is between calibre version 4.6 and the part of the DeDRM plugin that handles KFX.

**Comment by sst-76** [comment]
I will downgrade to 4.5 and see what happens.

**Comment by sst-76** [comment]
Downgraded all the way to 3.48.0 (4.5.0 had an issue with not finding a python library). Everything worked fine after that.
