### ISSUE TITLE
DRM strip issue - K4PC

### ISSUE THREAD

**Issue by d-salinas** [apprenticeharper/DeDRM_tools#962]
calibre Debug log
calibre 4.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 25, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 25, 0) && KFX metadata reader (from KFX Input) (1, 25, 0) && KFX Input (1, 25, 0) && Set KFX metadata (from KFX Output) (1, 35, 0) && KFX Output (1, 35, 0)
calibre 4.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 25, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 25, 0) && KFX metadata reader (from KFX Input) (1, 25, 0) && KFX Input (1, 25, 0) && Set KFX metadata (from KFX Output) (1, 35, 0) && KFX Output (1, 35, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 157.825242718 x 158.566473988
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
[1.59] main UI initialized...
[1.59] Hiding splash screen
[4.11] splash screen hidden
[4.11] Started up in 4.11 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: [',h\xfdf\xb17\xb7\xa7\xaa\x05\xc0\x8by\xaf}S\x0e5&)\xbe{[\x99Qk\x90\x9f\xcaj\x1d&', 'C:\\Users\\User\\Documents\\My Kindle Content']
Gather KFX-ZIP (from KFX Input) 1.25.0: Importing C:\Users\User\Documents\My Kindle Content\B005CWH8KG_EBOK\B005CWH8KG_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\User\AppData\Local\Temp\calibre_rfg07k\nmzshk.kfx-zip
DeDRM v6.6.3: Trying to decrypt nmzshk.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: nmzshk
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.de657c5b-28e5-472e-9304-dd7f448b82e1.voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\User\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\User\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1750728261' and UserName '4f534350'
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.25.0: Packaging C:\Users\User\AppData\Local\Temp\calibre_rfg07k\nmzshk.kfx-zip
Processing container: B005CWH8KG_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 88, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 161, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 268, in get_container
KFXDRMError: Book container B005CWH8KG_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\User\AppData\Local\Temp\calibre_rfg07k\ytuigu_add_books\0\B005CWH8KG_EBOK.kfx-zip
Added The Shadow Warriors of Nakano: A History of the Imperial Japanese Army's Elite Intelligence School to db in: 0.3
Added 1 books in 2.2 seconds

**Comment by ElleKayEm** [comment]
First, you need to go back to Kindle for PC 1.24 or earlier.  Then either disable the download of KFX files or go back to calibre 4.5.  See this post at MobileRead for details:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by d-salinas** [comment]
Ah! I missed the 1.25 part, thank you for the quick response. Downgrading to 1.24 and disabling the download of KFX files worked without problems.

Thank you again and sorry for missing this on the F.A.Q.
