### ISSUE TITLE
DeDRM no longer removing DRM from Nook

### ISSUE THREAD

**Issue by dbroo20** [apprenticeharper/DeDRM_tools#964]
I just realized today that none of the Nook ebooks that I have imported into Calibre this year have had their DRM removed.  I have been using the DeDRM plug-in to Calibre to successfully remove the DRM from Nook books in the past.  These are all ebooks that I have purchased from Barnes & Noble, and want to read on my Kobo eReader.  I am using the same OS (Windows 10) and PC that I used prior to this year.  I removed one of the ebooks from Calibre, then turned on Restart in Debug Mode, then restarted, then added(imported) the ebook again, then closed Calibre.  Here is the Log:
 
calibre Debug log
calibre 4.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Barnes & Noble (1, 2, 15) && Obok DeDRM (6, 5, 4)
calibre 4.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Barnes & Noble (1, 2, 15) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[1.25] splash screen shown
[1.25] Initializing db...
[1.28] db initialized
[1.28] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[3.86] main UI initialized...
[3.86] Hiding splash screen
[58.08] splash screen hidden
[58.08] Started up in 58.08 seconds with 112 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xdfAY`\xe6\xe9\xab\xd3\x05Z\x9d\xa2C\x9by\x82\x9a\xc7#\xe5`\xe6wjn9\xa8v2R\xdf\xb7', 'C:\\data\\eBooks_uploaded_to_Calibre\\purchased from Barnes & Noble\\9781101635438.epub']
DeDRM v6.6.3: Trying to decrypt 9781101635438.epub
DeDRM v6.6.3: Verifying zip archive integrity
DeDRM v6.6.3: “9781101635438.epub” is a secure Barnes & Noble ePub
DeDRM v6.6.3: Trying Encryption key Nook_DRM_dbXX
Could not decrypt e63zit.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 280, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 211, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 182, in __init__
  File "site-packages\Crypto\Cipher\AES.py", line 95, in new
  File "site-packages\Crypto\Cipher\AES.py", line 59, in __init__
  File "site-packages\Crypto\Cipher\blockalgo.py", line 141, in __init__
ValueError: Key cannot be the null string

DeDRM v6.6.3: Failed to decrypt with key Nook_DRM_dbXX after 0.2 seconds
DeDRM v6.6.3: Looking for new NOOK Study Keys after 0.2 seconds
No nook Study log files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 635, in run
  File "calibre_plugins.dedrm.__init__", line 304, in ePubDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Cell to db in: 1.3
Added 1 books in 3.4 seconds
Worker Launch took: 0.355000019073

**Comment by ElleKayEm** [comment]
If your old key has stopped working, it's not easy to get the current one.  The methods included in DeDRM stopped working at the beginning of this year.  There is a way to extract it from a rooted Android device, a rooted Nook, or an Android emulator.  There is discussion in this issue:

https://github.com/apprenticeharper/DeDRM_tools/issues/814

And here's a blog post of the process:

https://www.aricrenzo.gq/2019-12-13-Liberate-Your-Nook-Ebooks/

**Comment by dbroo20** [comment]
Thank you.  I will try to extract the key.

**Comment by isummer-judy** [comment]
I have tried the software mentioned in this article> https://bestapps.medium.com/switch-nook-to-kindle-why-and-how-to-8dcae8f70c2c and successfully convert my nook books. I only have 1 book. So I use the free trial version to handle it.

**Comment by ElleKayEm** [comment]
Looks like we have a spammer.

**Comment by hellomiakoda** [comment]
> If your old key has stopped working, it's not easy to get the current one. The methods included in DeDRM stopped working at the beginning of this year. There is a way to extract it from a rooted Android device, a rooted Nook, or an Android emulator. There is discussion in this issue:
> 
> #814
> 
> And here's a blog post of the process:
> 
> https://www.aricrenzo.gq/2019-12-13-Liberate-Your-Nook-Ebooks/

Any possibility you can post a new link? It's not working

**Comment by ElleKayEm** [comment]
Now here:  https://www.aricrenzo.com/2019-12-13-Liberate-Your-Nook-Ebooks/

**Comment by jakeisnt** [comment]
Aric updated their TLD - use the link here:  https://www.aricrenzo.com/2019-12-13-Liberate-Your-Nook-Ebooks/

**Comment by ElleKayEm** [comment]
Not seeing any changes from when I posted that link last year.  There's a much easier way to get your B&N key from the Window's app now.  I believe that's been intregated into noDRM's DeDRM fork:  https://github.com/noDRM/DeDRM_tools

**Comment by ElleKayEm** [comment]
See this post:  https://github.com/noDRM/DeDRM_tools/discussions/9
