### ISSUE TITLE
Unable to remove DRM from Kindle book

### ISSUE THREAD

**Issue by mQn9x9ne** [apprenticeharper/DeDRM_tools#967]
I am trying to remove the DRM for a Kindle book using the information in this thread.

Below are the software that I installed:

KindleForPC-installer-1.24.51068.exe
calibre-64bit-4.7.0.msi
DeDRM_tools_6.6.3.zip
KFX Input.zip (latest version 1.26.0 dated December 23, 2019)

The following are the steps I take to remove the DRM:

1. After synchronizing the Kindle For PC software with Amazon's servers, the ebook in question is downloaded to the custom directory.

2. Minimise the Kindle For PC software. Do not shut it down.

3. Launch Calibre software.

4. Install third party plugins such as DeDRM_tools_6.6.3.zip and KFX Input.zip (1.26.0 dated 12-23-2019).

5. Restart Calibre after successful installation of the plugins in (4).

6. Click the button "Add books" --> "Add books from a single directory".

7. Navigate to the custom directory where the Kindle book has been downloaded.

8. The said Kindle book shows up in the list of titles in Calibre.

9. When I double-click on the title, an error message says "This book is locked by DRM. To learn more about DRM and why....."

Your help is much appreciated.

**Comment by ElleKayEm** [comment]
Use calibre 4.5 or disable the download of KFX format.  See method 2 or 4 here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by mQn9x9ne** [comment]
> 
> 
> Use calibre 4.5 or disable the download of KFX format. See method 2 or 4 here:
> 
> https://www.mobileread.com/forums/showthread.php?t=283371

Thanks for your tip.

This time I used Calibre 4.5 and Kindle 1.17 (kindle-for-pc-1-17-44170.exe).

I also installed

DeDRM_tools_6.6.3.zip
KFX Input.zip (latest version 1.26.0 dated December 23, 2019)

I added the Kindle book to Calibre.  The format of the Kindle book is azw4

When I double-clicked said book in Calibre, the following error message appeared:

> calibre, version 4.5.0
> ERROR: Unhandled exception: <b>WindowsError</b>:[Error 1155] No application is associated with the specified file for this operation: u'E:\\Calibre Library\\Judith Rhine\\Clementine (19)\\Clementine - Judith Rhine.azw4'
> 
> calibre 4.5 [64bit]  embedded-python: True is64bit: True
> Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
> ('Windows', '10', '10.0.18362')
> Python 2.7.16+
> Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
> Interface language: None
> Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 26, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 26, 0) && KFX metadata reader (from KFX Input) (1, 26, 0) && KFX Input (1, 26, 0)
> Traceback (most recent call last):
>   File "site-packages\calibre\gui2\actions\view.py", line 108, in view_format_by_id
>   File "site-packages\calibre\gui2\actions\view.py", line 157, in _view_file
>   File "site-packages\calibre\gui2\actions\view.py", line 147, in _launch_viewer
>   File "site-packages\calibre\gui2\__init__.py", line 1237, in open_local_file
> WindowsError: [Error 1155] No application is associated with the specified file for this operation: u'E:\\Calibre Library\\Judith Rhine\\Clementine (19)\\Clementine - Judith Rhine.azw4'

Your help is most appreciated.

**Comment by ElleKayEm** [comment]
The calibre ebook viewer doesn't open AZW4 by default.  You can add it to the file types it opens by going to Preferences > Behavior and then checking the box next to AZW4 in the list on the right (use internal viewer for).  It is actually a PDF in an Amazon wrapper.  You can use the KindleUnpack plugin to extract the PDF.

**Comment by mQn9x9ne** [comment]
> 
> 
>  It is actually a PDF in an Amazon wrapper. You can use the KindleUnpack plugin to extract the PDF.

Thanks for your reply and tip.

**Are ALL Kindle books actually PDFs contained in Amazon's encrypted wrappers?**

**Comment by ElleKayEm** [comment]
No.  Just AZW4.
