### ISSUE TITLE
Error removing DRM from Kindle books

### ISSUE THREAD

**Issue by gianfri54** [apprenticeharper/DeDRM_tools#969]
Hello,

I am trying to remove DRM from some Kindle books using a PC with Windows 10.
I have installed the DRM plugins and entered the serial number of my kindle.
I have downloaded the book from Amazon using the Transfer to USB option, then imported them to Calibre.
When I try to convert the books I get the error that the book is DRM protected and cannot be converted.
Below is the log. I hope someone can help me. Thank you!!!

calibre Debug log
calibre 4.7  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 26, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 26, 0) && Obok DeDRM (6, 5, 4) && KFX metadata reader (from KFX Input) (1, 26, 0) && KFX Input (1, 26, 0)
calibre 4.7  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 26, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 26, 0) && Obok DeDRM (6, 5, 4) && KFX metadata reader (from KFX Input) (1, 26, 0) && KFX Input (1, 26, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 110.836363636 x 110.735694823
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.36] splash screen shown
[0.36] Initializing db...
[0.36] db initialized
[0.36] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.70] main UI initialized...
[1.70] Hiding splash screen
[29.22] splash screen hidden
[29.22] Started up in 29.22 seconds with 189 books
DeDRM v6.6.3: Trying to decrypt The Topeka School.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Topeka School
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\gp195\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\gp195\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3859262843' and UserName '4769616e6672616e636f'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Topeka School
Got DSN key from database default_key_1
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Topeka School to db in: 0.2
Added 1 books in 0.8 seconds
Worker Launch took: 0.0830001831055
Job: 0 Convert book 1 of 1 (The Topeka School) finished
Convert book 1 of 1 (The Topeka School)
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\gp195\\AppData\\Local\\Temp\\calibre_e0llcp\\jzhbjr.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\gp195\\AppData\\Local\\Temp\\calibre_e0llcp\\3qc1wt.opf'
	  output_profile: u'kindle_voyage'
	  verbose: 2
	Resolved conversion options
	calibre version: 4.7.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\gp195\\AppData\\Local\\Temp\\calibre_e0llcp\\jzhbjr.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x051DC9F0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KindleVoyageOutput object at 0x051DCE10>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\gp195\\AppData\\Local\\Temp\\calibre_e0llcp\\3qc1wt.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\gp195\AppData\Local\Temp\calibre_e0llcp\qvvd9s.azw3
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  The Topeka School (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: The Topeka School

**Comment by ElleKayEm** [comment]
Is it an E-ink Kindle, not a Fire?  If so, are you sure you chose the correct device when you downloaded the book?  And double-check that you've entered the serial number correctly into the E-ink Kindle books section of the DeDRM plugin customization.  Easiest way to make sure is to copy and paste from the website removing any spaces.

**Comment by gianfri54** [comment]
Yes, this is for a Kindle Oasis, I also have a Kindle Paperwhite. I copied the SN for both devices from the Amazon web site and pasted them (after removing blank spaces) into the plugin. I then downloaded a book for each of the two devices and tried to remove DRM but neither worked. I was hoping the log would point to some possible ideas (I am not tech savvy enough to make sense of it).

**Comment by ElleKayEm** [comment]
The log tells me that DeDRM tried the keys it had and they didn't work for this book.  It then looked for Kindle for PC keys which, of course, weren't right for this book either.  Did you restart calibre between entering the serial numbers and adding the books?

**Comment by gianfri54** [comment]
Well, problem (partially) solved. One of the two SN I entered had a mistake. After correcting it, books downloaded for that Kindle (Paperwhite) are converted by Caliber. However, books downloaded for the other Kindle (Oasis) are not, even though the SN in the plugin is correct.
Thank you for your help!

**Comment by ElleKayEm** [comment]
Can you sideload the book downloaded for the Oasis to the Oasis and read it?

**Comment by gianfri54** [comment]
I deleted and re-entered the SN for the Oasis and that fixed the problem.

Thank you very much for your help and support!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
