### ISSUE TITLE
Kindle for Mac 1.15.0 (43056): default encryption key not found 

### ISSUE THREAD

**Issue by asukara** [apprenticeharper/DeDRM_tools#97]
I'm using Kindle for Mac v.1.15.0 (43056), Calibre 2.55, DeDRM 6.42/3, OS X El Capitan 10.11.4

I tried uninstalling / deregistering / deleting local content folders / reinstalling the kindle mac app but no dice. Any help is much appreciated. Many thanks!

Here is the import log:

calibre Debug log
calibre 2.55  embedded-python: True is64bit: True
Darwin-15.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '15.4.0', 'Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.11.4', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM && Obok DeDRM
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 2.05 seconds with 315 books
DeDRM v6.4.3: Trying to decrypt B000FC1H2S_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 228
Decrypting Mobipocket 4 ebook: The Bridegroom: Stories
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.4.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.4.3: Looking for new default Kindle Key after 0.0 seconds
DeDRM v6.4.3: Exception when getting default Kindle Key after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 521, in KindleMobiDecrypt
  File "site-packages/calibre/customize/zipplugin.py", line 179, in load_module
  File "calibre_plugins.dedrm.kindlekey", line 1219, in <module>
  File "calibre_plugins.dedrm.kindlekey", line 1214, in _load_crypto
  File "calibre_plugins.dedrm.kindlekey", line 1128, in _load_crypto_libcrypto
  File "lib/python2.7/ctypes/__init__.py", line 365, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
	/usr/local/lib/libcrypto.dylib: mach-o, but wrong architecture
DeDRM v6.4.3: Ultimately failed to decrypt after 0.0 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 604, in run
  File "calibre_plugins.dedrm.__init__", line 554, in KindleMobiDecrypt
DeDRMError: DeDRM v6.4.3: Ultimately failed to decrypt after 0.0 seconds
Added The Bridegroom: Stories to db in: 0.1
Added 1 books in 0.6 seconds

**Comment by apprenticeharper** [comment]
The problem is evident from these lines:

OSError: dlopen(/usr/local/lib/libcrypto.dylib, 6): no suitable image found. Did find:
 /usr/local/lib/libcrypto.dylib: mach-o, but wrong architecture
 
Some bit of software has installed a file, libcrypto.dylib in /usr/local/lib, but it's for PowerPC or perhaps Intel x86 instead of Intel x64. Delete the file /usr/local/lib/libcrypto.dylib and all should be well.

**Comment by asukara** [comment]
Ah! Thanks so much for the heads up. All is indeed well now.

**Comment by apprenticeharper** [comment]
Thanks for confirming.
