### ISSUE TITLE
v. 6.6.3 stoped to decrypt since 27 December

### ISSUE THREAD

**Issue by Ubunter** [apprenticeharper/DeDRM_tools#973]
Hello,
Until 25 December, I had correctly worked, without any issue decrypting files from Adobe and from Kindle in my Calibre. Now, suddenly since December 27 it's stopped working, and say books are encrypted and can't decrypt anymore.
I have updated calibre to v.4.6.8 but no way... and I don't see any new version upper 6.6.3 for DeDRM.
Any advice, please?
Thanks,

**Comment by ElleKayEm** [comment]
Need more info to help.  What OS?  How are you downloading the books?  Post a log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by Ubunter** [comment]
Thank you for your fast prompt ElleKayEm,
It's in a virtual machine (virtual box) Windows 10, Kindle 1.24.3, Calibre 4.6.6 I was purchasing the books from amazon, download it in Kindle, and then import it in Calibre, and convert to pdf. My last working day was 25 December, working perfectly.
Same procedure with ADE 4.5
At December 27 I came to use it, and no way, I couldn't decrypt anymore...

I have updated Calibre to 4.6.8, but no result.

Bellow the trace:

> calibre, version 4.8.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (La médiocratie (Lettres libres) (French Edition))

Convert book 1 of 1 (La médiocratie (Lettres libres) (French Edition))
Conversion options changed from defaults:
  output_profile: u'generic_eink'
  pdf_serif_family: u'MS Shell Dlg 2'
  pdf_sans_family: u'MS Shell Dlg 2'
  cover: u'C:\\Users\\IEUser\\AppData\\Local\\Temp\\calibre_krf6zq\\bfxg22.jpeg'
  verbose: 2
  read_metadata_from_opf: u'C:\\Users\\IEUser\\AppData\\Local\\Temp\\calibre_krf6zq\\ktpow2.opf'
Resolved conversion options
calibre version: 4.8.0
{'allow_conversion_with_errors': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\IEUser\\AppData\\Local\\Temp\\calibre_krf6zq\\bfxg22.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001D1377944C8>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001D13779E108>,
 'page_breaks_before': u'/',
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\IEUser\\AppData\\Local\\Temp\\calibre_krf6zq\\ktpow2.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: KFX Input running
on C:\Users\IEUser\AppData\Local\Temp\calibre_krf6zq\z5ur5q.kfx-zip
Software versions: KFX Input 1.26.0, calibre 4.8 [64bit], Windows-10-10.0.17763-SP0
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\IEUser\AppData\Local\Temp\calibre_krf6zq\z5ur5q.kfx-zip
Processing container: B016WYE2P6_EBOK.azw
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 99, in convert
  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B016WYE2P6_EBOK.azw has DRM and cannot be converted
Python function terminated unexpectedly
  This book has DRM! (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "calibre_plugins.kfx_input.__init__", line 104, in convert
DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
There's a problem right now with KFX files, DeDRM, and the latest versions of calibre.  Workarounds include going back to calibre 4.5 or disabling the download of KFX format in Kindle for PC.

That problem shouldn't be affecting ADE files so I don't know what is happening for you there.

(You didn't really mean to close this issue, did you?)

**Comment by Ubunter** [comment]
Correct, thank you VERY much.
I have removed v. 4.8 clean folders, and reinstall v. 4.5 and the DeDRM and imported the book from kindle to convert it to pdf, work perfectly...
Many thanks again, feel free to close the ticket, or grep whatever needed for the update.
Regards,
