### ISSUE TITLE
DeDRM stopped working with Calibre

### ISSUE THREAD

**Issue by tos070** [apprenticeharper/DeDRM_tools#974]
I have been using the plugin without any problems. Today I bought a DRM protected book and I cannot use it with Calibre. I updated the plugin to the latest version 6.6.3 but still it does not work. Please advise.

**Comment by MacConin** [comment]
same here . OSX 10.15.2, latest calibre plugins and Kindle 1.26.1

**Comment by ZolaLa9** [comment]
@MacConin — You had it working in Catalina at one point, or it never worked in Catalina? 

Either way, post a log: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by ElleKayEm** [comment]
@tos070 
We'll need more info.  Follow the link Zola gave, and post a log.

**Comment by MacConin** [comment]
I updated recently, so my guess is that it never worked for me with the (new) Catalina).
After Catalina I had to update Kindle for OS X to 1.26.1 
Attached is the debug log for a KFX book.
[debug.log.txt](https://github.com/apprenticeharper/DeDRM_tools/files/4029695/debug.log.txt)

I'll check later the Adobe Digital Editions.

**Comment by tos070** [comment]
I updated Calibre to the latest version 4.8, removed the book and when I tried again it worked. I had never experienced problems with the plug in before

**Comment by MacConin** [comment]
OK, it's definitively the KFX files that do not work.
KFX Input is 1.26.0
Calibre 4.8
Kindle for OS X is 1.26.1

**Comment by ElleKayEm** [comment]
For KFX files, you need Kindle for PC/Mac 1.24 or earlier (which, of course, doesn't work on Catalina) and calibre 4.5.

If you've disabled downloads of KFX format, you can use the latest version of calibre (currently 4.8 I believe).  It's possible (with some precautions) to use later versions of Kindle for Mac if you previously had a working setup of K4Mac 1.23 or earlier.  With Kindle for PC, you need 1.24 or earlier.

**Comment by MacConin** [comment]
@ElleKayEm : yepp , seen this issue. Thx.
Had a working 'Kindle for OS X' . 
Guess I have to wait for an upcoming update. fingerscrossed.

**Comment by ElleKayEm** [comment]
@MacConin 
Just for KFX format then, right?  Do you have books that aren't available in the older format?

**Comment by MacConin** [comment]
just for KFX. Had that Kindle unlimited, but will drop that again. Selection and range of offered books are .. uuhm. Will switch to other sources.

**Comment by ElleKayEm** [comment]
DeDRM isn't intended for borrowed books anyway.
