### ISSUE TITLE
Sorry to bother (Kindle AZW Problem)

### ISSUE THREAD

**Issue by naniju** [apprenticeharper/DeDRM_tools#977]
dear wise coding gods,

i am but a mere (obviously useless) user unable to fathom what the code wishes to tell me. i've already read all the previous posts and tried what you suggested, it's still not working (incl. the  mobileread post) - obviously do to the lack of understanding.

i imagine it (the log) wants to tell me i used the wrong kindle code. i'm trying to convert my amazon bought books to a non amazon device that does not support the azw3, the books are not rented but payed for. i tried using the books directly from the kindle and the downloaded version from the amazon page.
i asume the problem can be solved easily, i hope it's just a user error due to the fact i've been trying for days....

thank you in advance for you wise guidance.

i used
calibre (newest and 4.5), also tried the python drag-and-drop-thing
DeDR Tools 6.6.3
KFX Input 1.26.0.

calibre Fehlerdiagnoseprotokoll
calibre 4.8 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 26, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 26, 0) && KFX metadata reader (from KFX Input) (1, 26, 0) && KFX Input (1, 26, 0) && Set KFX metadata (from KFX Output) (1, 36, 0) && KFX Output (1, 36, 0) && Obok DeDRM (6, 5, 4) && KindleUnpack - The Plugin (0, 82, 1)
calibre 4.8 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 26, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 26, 0) && KFX metadata reader (from KFX Input) (1, 26, 0) && KFX Input (1, 26, 0) && Set KFX metadata (from KFX Output) (1, 36, 0) && KFX Output (1, 36, 0) && Obok DeDRM (6, 5, 4) && KindleUnpack - The Plugin (0, 82, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 92.0536912752
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.41] splash screen shown
[0.41] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.48] main UI initialized...
[1.48] Hiding splash screen
[3.75] splash screen hidden
[3.75] Started up in 3.75 seconds with 65 books
Storage number map:
{(7L, 0L): [(3L, 'C')],
 (7L, 1L): [(1L, 'D'), (2L, 'E')],
 (7L, 2L): [(1L, 'F')],
 (7L, 3L): [(1L, 'H')]}
Storage number for USBSTOR\DISK&VEN_LINUX&PROD_FILE-CD_GADGET&REV_0000\6&22487485&0&95231346_8BF4D87F7DDB4850A2B10C17947F8370&0: StorageDeviceNumber(type=7L, number=3L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1f85 product_id=0x6053 bcd=0x9999 devid=usb\vid_1f85&pid_6053&rev_9999 devinst=21)
{u'drive_letters': ['H'],
 u'pnp_id_map': {'H': u'\\\\?\\usbstor#disk&ven_linux&prod_file-cd_gadget&rev_0000#6&22487485&0&95231346_8bf4d87f7ddb4850a2b10c17947f8370&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'H': (3L, 1L)}}
Job: 0 Geräteinformationen abrufen started
DeviceJob: 0 Geräteinformationen abrufen done, calling callback
DeviceJob: 0 Geräteinformationen abrufen callback returned
Job: 1 Bibliotheksinformationen festlegen started
DeviceJob: 1 Bibliotheksinformationen festlegen done, calling callback
DeviceJob: 1 Bibliotheksinformationen festlegen callback returned
Job: 2 Gerätebücherliste abrufen started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= TOLINO oncard= None
DEBUG:    0.0 USBMS: dirs are: H:\ 
DEBUG:    0.0 USBMS: scan from root False H:\
DEBUG:    0.0 USBMS: count found in cache: 81, count of files in metadata: 81, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= TOLINO oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= TOLINO oncard= cardb
DeviceJob: 2 Gerätebücherliste abrufen done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 81
DeviceJob: set_books_in_library finished: time= 0.00300002098083
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Gerätebücherliste abrufen callback returned
Job: 1 Bibliotheksinformationen festlegen finished
Keine Details verfügbar.
Job: 0 Geräteinformationen abrufen finished
Keine Details verfügbar.
Job: 2 Gerätebücherliste abrufen finished
Keine Details verfügbar.
DeDRM v6.6.3: Trying to decrypt A Darker Shade of Magic.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Darker Shade of Magic
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
**DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried.**
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Julia\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added A Darker Shade of Magic to db in: 0.1
Added 1 books in 0.5 seconds

calibre Fehlerdiagnoseprotokoll
calibre 4.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 26, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 26, 0) && Set KFX metadata (from KFX Output) (1, 36, 0) && KFX Output (1, 36, 0) && KindleUnpack - The Plugin (0, 82, 1) && KFX metadata reader (from KFX Input) (1, 26, 0) && KFX Input (1, 26, 0) && Obok DeDRM (6, 5, 4)
calibre 4.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 26, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 26, 0) && Set KFX metadata (from KFX Output) (1, 36, 0) && KFX Output (1, 36, 0) && KindleUnpack - The Plugin (0, 82, 1) && KFX metadata reader (from KFX Input) (1, 26, 0) && KFX Input (1, 26, 0) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 92.0536912752
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.41] splash screen shown
[0.41] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.45] main UI initialized...
[1.45] Hiding splash screen
[4.86] splash screen hidden
[4.88] Started up in 4.88 seconds with 65 books
Storage number map:
{(7L, 0L): [(3L, 'C')],
 (7L, 1L): [(1L, 'D'), (2L, 'E')],
 (7L, 2L): [(1L, 'F')],
 (7L, 3L): [(1L, 'H')]}
Storage number for USBSTOR\DISK&VEN_LINUX&PROD_FILE-CD_GADGET&REV_0000\6&22487485&0&95231346_8BF4D87F7DDB4850A2B10C17947F8370&0: StorageDeviceNumber(type=7L, number=3L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1f85 product_id=0x6053 bcd=0x9999 devid=usb\vid_1f85&pid_6053&rev_9999 devinst=21)
{u'drive_letters': ['H'],
 u'pnp_id_map': {'H': u'\\\\?\\usbstor#disk&ven_linux&prod_file-cd_gadget&rev_0000#6&22487485&0&95231346_8bf4d87f7ddb4850a2b10c17947f8370&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'H': (3L, 1L)}}
Job: 0 Geräteinformationen abrufen started
DeviceJob: 0 Geräteinformationen abrufen done, calling callback
DeviceJob: 0 Geräteinformationen abrufen callback returned
Job: 1 Bibliotheksinformationen festlegen started
DeviceJob: 1 Bibliotheksinformationen festlegen done, calling callback
DeviceJob: 1 Bibliotheksinformationen festlegen callback returned
Job: 2 Gerätebücherliste abrufen started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= TOLINO oncard= None
DEBUG:    0.0 USBMS: dirs are: H:\ 
DEBUG:    0.1 USBMS: scan from root False H:\
DEBUG:    0.2 USBMS: count found in cache: 81, count of files in metadata: 81, need_sync: False
DEBUG:    0.2 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= TOLINO oncard= carda
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= TOLINO oncard= cardb
DeviceJob: 2 Gerätebücherliste abrufen done, calling callback

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 584 '\x01\x00\x00\x00\x0c\x00\x00\x00\xc0\x01\x00\x00:\x00\x1fBf\\\x8d\x013E\x07C\x9bS"M\xe2\xed\x1f\xe6&\x00\x01\x00&\x00\xef\xbe1\x04\x00\x00\xb0\x18\xb2zX\x1e%\x02\xfd\xb0-\x1e\x82\xc7\xd5\x01\xfd\xb0-\x1e\x82\xc7\xd5\x01\x14\x00P\x001\x00\x00\x00\x00\x00)P$;\x10\x04Daten\x00<\x00\t\x00\x04\x00\xef\xbe\xf1N\x81i)P$;.\x00\x00\x00\xa6\x0b\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x1a`\x00\x90\x00\x00\x00\x00\x00\x00\xf1*O\x00D\x00a\x00t\x00e\x00n\x00\x00\x00\x14\x00T\x001\x00\x00\x00\x00\x00)P\x17B0\x04BCHER~1\x00>\x00\t\x00\x04\x00\xef\xbe\x07O/L)P\x17B.\x00\x00\x00\xad\xd4\x01\x00\x00\x00\x05\x00\x00\x00\x00\x00\x1a\xe0\x00\x90\x00\x00\x00\x00\x00\x00ac\xb5\x00B\x00\xfc\x00c\x00h\x00e\x00r\x00\x00\x00\x16\x00d\x001\x00\x00\x00\x00\x00(P/\x800\x04KINDLE~1\x00\x00L\x00\t\x00\x04\x00\xef\xbe(P\xe7|(P/\x80.\x00\x00\x00\xfc\x06\x01\x00\x00\x00]\x00\x00\x00\x00\x00\x1a\xe0\x00\x90\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 36888 '`\x00\x00\x00`\x00\x00\x000\x00\x00\x00Y\x00\x00\x00\x7f\x12\x05\xc2\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragContext" 16 '\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 '\x01\x00\x00\x00' 

text/uri-list 126 'file:///C:/Users/Julia/OneDrive/Daten/B%C3%BCcher/Kindle%20Backup/nicht%20konvertierbar/A%20Darker%20Shade%20of%20Magic.azw3\r\n' 

application/x-qt-windows-mime;value="FileName" 69 'C:\\Users\\Julia\\OneDrive\\Daten\\BCHER~1\\KINDLE~1\\NICHTK~1\\ADARKE~1.AZW\x00' 

application/x-qt-windows-mime;value="FileContents" 0 '' 

application/x-qt-windows-mime;value="FileNameW" 200 'C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00J\x00u\x00l\x00i\x00a\x00\\\x00O\x00n\x00e\x00D\x00r\x00i\x00v\x00e\x00\\\x00D\x00a\x00t\x00e\x00n\x00\\\x00B\x00\xfc\x00c\x00h\x00e\x00r\x00\\\x00K\x00i\x00n\x00d\x00l\x00e\x00 \x00B\x00a\x00c\x00k\x00u\x00p\x00\\\x00n\x00i\x00c\x00h\x00t\x00 \x00k\x00o\x00n\x00v\x00e\x00r\x00t\x00i\x00e\x00r\x00b\x00a\x00r\x00\\\x00A\x00 \x00D\x00a\x00r\x00k\x00e\x00r\x00 \x00S\x00h\x00a\x00d\x00e\x00 \x00o\x00f\x00 \x00M\x00a\x00g\x00i\x00c\x00.\x00a\x00z\x00w\x003\x00\x00\x00' 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 '\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x04\x00\x00\x00Z\xba\xb1\xc3\xc6\xd5\x01\x00\x00\x00\x00\x00\x00\x00\x00D9\x1f\x1b9\xc6\xd5\x01\x00\x00\x00\x00\xa0\xc5\x07\x00A\x00 \x00D\x00a\x00r\x00k\x00e\x00r\x00 \x00S\x00h\x00a\x00d\x00e\x00 \x00o\x00f\x00 \x00M\x00a\x00g\x00i\x00c\x00.\x00a\x00z\x00w\x003\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

Firefox rurl: None None
URLS: [u'file:///C:/Users/Julia/OneDrive/Daten/B%C3%BCcher/Kindle%20Backup/nicht%20konvertierbar/A%20Darker%20Shade%20of%20Magic.azw3']
Paths: [u'C:/Users/Julia/OneDrive/Daten/B\xfccher/Kindle Backup/nicht konvertierbar/A Darker Shade of Magic.azw3']
Extensions: frozenset([u'azw3'])
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 81
DeviceJob: set_books_in_library finished: time= 0.00699996948242
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Gerätebücherliste abrufen callback returned
Job: 0 Geräteinformationen abrufen finished
Keine Details verfügbar.
Job: 1 Bibliotheksinformationen festlegen finished
Keine Details verfügbar.
Job: 2 Gerätebücherliste abrufen finished
Keine Details verfügbar.
DeDRM v6.6.3: Trying to decrypt A Darker Shade of Magic.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Darker Shade of Magic
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Julia\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added A Darker Shade of Magic to db in: 0.1
Added 1 books in 0.5 seconds

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) and then enter its serial number into the DeDRM plugin's customization.

**Comment by naniju** [comment]
I did it - I didn't need to download the files for a specific kindle version (can't choose that option) but for the correct kindle.
thanks for the tipp ElleKayEm, much appreciated
