### ISSUE TITLE
dedrm won't convert kindle books in Calibre

### ISSUE THREAD

**Issue by rnc490** [apprenticeharper/DeDRM_tools#978]
calibre Debug log
calibre 4.8  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.8  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.5388994307 x 92.6756756757
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.47] splash screen shown
[0.47] Initializing db...
[0.48] db initialized
[0.48] Constructing main UI...
[1.95] main UI initialized...
[1.95] Hiding splash screen
[12.45] splash screen hidden
[12.45] Started up in 12.45 seconds with 595 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['r<\xb8\x19j"V!% \xabP\x14v\x17T\xe8B\xf0Qzq\x9f\'\xda7j_)\x90/8', 'C:\\Users\\ronca\\Downloads\\The Theft of America\xe2\x80\x99s Soul.azw3']
DeDRM v6.6.3: Trying to decrypt The Theft of Americaâ€™s Soul.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Theft of Americaâ€™s Soul
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\ronca\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\ronca\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\ronca\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2629814235' and UserName '726f6e6361'
Decrypted key file using IDString '2629814235' and UserName '726f6e6361'
DeDRM v6.6.3: Found 2 new keys
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Theft of Americaâ€™s Soul
Got DSN key from database default_key_1
Got DSN key from database default_key_2
Found 7 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Theft of America’s Soul to db in: 1.8
Added 1 books in 2.6 seconds

Computer: 
OS Name	Microsoft Windows 10 Pro
Version	10.0.18362 Build 18362
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-EH76ET9
System Manufacturer	Dell Inc.
System Model	XPS 8900
System Type	x64-based PC
System SKU	06B8
Processor	Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, 3408 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 2.5.0, 1/10/2019
SMBIOS Version	2.8
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	0XJ8C4
BaseBoard Version	A00
Platform Role	Desktop
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.18362.387"
User Name	DESKTOP-EH76ET9\ronca
Time Zone	Pacific Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	11.9 GB
Total Virtual Memory	18.3 GB
Available Virtual Memory	13.5 GB
Page File Space	2.38 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

Amazon files downloaded to pc from website as "download and transfer via usb"

**Comment by ElleKayEm** [comment]
When downloading from the website, choose an E-ink Kindle (not a Fire) and enter its serial number into the DeDRM plugin customization.

**Comment by rnc490** [comment]
That did it, thank you
