### ISSUE TITLE
DRM removing from azw failed with 6.4.3

### ISSUE THREAD

**Issue by Locmas** [apprenticeharper/DeDRM_tools#98]
Book bought on April 29th 2016, imported with Kindle for PC 1.15.0 on Win7 64 bit. Tried to convert with Calibre 2.56.0 and latest DeDRM_tools_6.4.3.zip.

I have to use ebook-convert.exe because I am blind and my screenreading software does not work with Calibre GUI. I never experienced problems converting my bought books so far. Can you please help?

C:\Program Files (x86)\Calibre2>ebook-convert.exe d:\cal\in\B01BNJ2MYI_EBOK.azw d:\out\ 
Non-ASCII text detected. You must set your Console's font to Lucida Console or Consolas or some other TrueType font to see this text -- 
1% Eingabe wird in HTML konvertiert ... 
InputFormatPlugin: MOBI Input running on d:\cal\in\B01BNJ2MYI_EBOK.azw
Found KF8 MOBI of type 'standalone' 
Python function terminated unexpectedly
Wunschdenken: Europa, WÃ¤hrung, Bildung, Einwanderung - warum Politik so hÃ¤ufig scheitert (German Edition) (Error Code: 1)
Traceback (most recent call last):
File "site.py", line 132, in main
File "site.py", line 109, in run_entry_point File "site-packages\calibre\ebooks\conversion\cli.py", line 380, in main
File "site-packages\calibre\ebooks\conversion\plumber.py", line 1057, in run
File "site-packages\calibre\customize\conversion.py", line 241, in __call__
File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 43,in convert
File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 81, in __call__
File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 144, in check_for_drm
calibre.ebooks.DRMError: Wunschdenken: Europa, WÃ¤hrung, Bildung, Einwanderung -warum Politik so hÃ¤ufig scheitert (German Edition)
C:\Program Files (x86)\Calibre2>

**Comment by pdurrant** [comment]
I can't see any output from the plugin. It seems that calibre never tried to use the plugin to remove DRM.

I suggest using the python scripts directly to remove the DRM, and then convert the DRM-free version. Just unzip the plugin to find the scripts. You may need to also install Python 2.7.x and PyCrypto for 2.7.

First use kindlekey.py to get the key file for your Kindle for PC installation
Then use k4mobidedrm.py to strip the DRM from the ebook.
Then use calibre's ebook-convert.exe on the DRM-free copy.

**Comment by apprenticeharper** [comment]
Closed. pdurrant's suggestion seems good - the command line tools are probably your best bet. If you are still having problems, please open a new issue.
