### ISSUE TITLE
Kindle/Mac Issue

### ISSUE THREAD

**Issue by bijoux3** [apprenticeharper/DeDRM_tools#991]
Hi, I have an Amazon book that I downloaded through the Kindle mac app. I don't have a Kindle, but my Amazon account does have (my father's) android attached. Not sure if that matters. I did the step in terminal to finally have a .azw file, and i downloaded the plugins to calibre. I dragged it over to calibre (could never find it in the little import box) and yet it was not DeDRMed and it won't convert either. I added the KFX plugin as well as the DeDRM. I still have Mojave on my OSX. So Mac version 10.14. Here's the little dialog box I got:

calibre Debug log
calibre 4.9.1  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.191/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 28, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 28, 0) && KFX metadata reader (from KFX Input) (1, 28, 0) && KFX Input (1, 28, 0)
calibre 4.9.1  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 28, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 28, 0) && KFX metadata reader (from KFX Input) (1, 28, 0) && KFX Input (1, 28, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Using calibre Qt style: True
[0.00] Starting up...
[0.06] Showing splash screen...
[0.35] splash screen shown
[0.35] Initializing db...
[0.36] db initialized
[0.36] Constructing main UI...
[1.51] main UI initialized...
[1.51] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 1.28.0: Importing /Users/MYNAME/Library/Application Support/Kindle/My Kindle Content/B07V5SH7L1_EBOK/B07V5SH7L1_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.3: Trying to decrypt B07V5SH7L1_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: THE FITNESS CHEF
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[14.51] splash screen hidden
[14.51] Started up in 14.51 seconds with 1 books
Added THE FITNESS CHEF to db in: 0.2
Added 1 books in 1.1 seconds

Help. I just want to read, man.

**Comment by ElleKayEm** [comment]
You need to use Kindle for Mac version 1.23 or earlier and it needs to be on the same machine and user as calibre with DeDRM.  Here's a post with details and a link for K4Mac 1.23:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by bijoux3** [comment]
How do I keep it from updating on it's own? I did that but it updated

**Comment by ElleKayEm** [comment]
See the info at the bottom of the 1st post at the link I gave.

**Comment by bijoux3** [comment]
...Okay so bless you. Problem solved. I guess I can never update to Catalina?

**Comment by ElleKayEm** [comment]
Now that you have a working setup, you might be okay with some precautions:

https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508
