### ISSUE TITLE
Unable to remove DeDRM

### ISSUE THREAD

**Issue by hyang6039** [apprenticeharper/DeDRM_tools#993]
I am using Window 10 and Calibre 4.10, and Kindle for PC 2, version 1.24.3 (51068). I have installed two plugin, KFX input (1.28.0) and DeDRM (6.6.3).
From Amazon kindle site, I sent the ebook to Kindle for PC 2 (laptop). I then added the Kindle book into Calibre from the Kindle folder. I am trying to change the format to pdf but it seems like the DRM is still there, not sure what goes wrong. Appreciate if someone can help. Thanks.
..........................................................................................................................................................................................................
calibre Debug log
calibre 4.10  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 28, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 28, 0) && KFX metadata reader (from KFX Input) (1, 28, 0) && KFX Input (1, 28, 0)
calibre 4.10  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 28, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 28, 0) && KFX metadata reader (from KFX Input) (1, 28, 0) && KFX Input (1, 28, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 79.1688311688 x 79.2832369942
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.89] splash screen shown
[0.89] Initializing db...
[0.92] db initialized
[0.92] Constructing main UI...
[3.33] main UI initialized...
[3.33] Hiding splash screen
[15.86] splash screen hidden
[15.88] Started up in 15.88 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['rG{\x81\xe8\xeeH(\xa0\xec\xa5J}\x1f\xc9\xcf\x8a&\xa3\xe5\x0f.\xbf\xa4m\xec\x0c\xd1\x1e`\xe4\xd8', 'C:\\Users\\Yang\\Documents\\My Kindle Content\\B078GWN38X_EBOK\\B078GWN38X_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.28.0: Importing C:\Users\Yang\Documents\My Kindle Content\B078GWN38X_EBOK\B078GWN38X_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Yang\AppData\Local\Temp\calibre__ho8wr\j4kcdd.kfx-zip
DeDRM v6.6.3: Trying to decrypt j4kcdd.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: j4kcdd
Found 0 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.bed2dded-3432-46dc-8cf3-1306d3c71883.voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Yang\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Yang\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2532712877' and UserName '59616e67'
DeDRM v6.6.3: Found 1 new key
Decrypting KFX-ZIP ebook: j4kcdd
Got DSN key from database default_key_1
Found 1 keys to try after 0.4 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.bed2dded-3432-46dc-8cf3-1306d3c71883.voucher
DeDRM v6.6.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.28.0: Packaging C:\Users\Yang\AppData\Local\Temp\calibre__ho8wr\j4kcdd.kfx-zip
Processing container: B078GWN38X_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B078GWN38X_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Yang\AppData\Local\Temp\calibre__ho8wr\ffkmwf_add_books\0\B078GWN38X_EBOK.kfx-zip
Added BEWARE THE PAST a gripping crime thriller with a huge twist to db in: 0.3
Added 1 books in 2.6 seconds
Worker Launch took: 0.554000139236
Job: 0 Convert book 1 of 1 (BEWARE THE PAST a gripping crime thriller with a huge twist) finished
Convert book 1 of 1 (BEWARE THE PAST a gripping crime thriller with a huge twist)
	Conversion options changed from defaults:
	  output_profile: u'generic_eink'
	  pdf_sans_family: u'MS Shell Dlg 2'
	  pdf_serif_family: u'MS Shell Dlg 2'
	  verbose: 2
	  cover: u'C:\\Users\\Yang\\AppData\\Local\\Temp\\calibre__ho8wr\\euikjk.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\Yang\\AppData\\Local\\Temp\\calibre__ho8wr\\bh7mhd.opf'
	Resolved conversion options
	calibre version: 4.10.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Yang\\AppData\\Local\\Temp\\calibre__ho8wr\\euikjk.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x061B1B10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x061B1D10>,
	 'page_breaks_before': u'/',
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier',
	 'pdf_mono_font_size': 16,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'MS Shell Dlg 2',
	 'pdf_serif_family': u'MS Shell Dlg 2',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Yang\\AppData\\Local\\Temp\\calibre__ho8wr\\bh7mhd.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\Yang\AppData\Local\Temp\calibre__ho8wr\lfj30x.kfx-zip
	Software versions: KFX Input 1.28.0, calibre 4.10, Windows-10-10.0.18362-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\Yang\AppData\Local\Temp\calibre__ho8wr\lfj30x.kfx-zip
	Processing container: B078GWN38X_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 99, in convert
	  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
	KFXDRMError: Book container B078GWN38X_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 104, in convert
	DRMError: This book has DRM!

Convert book 1 of 1 (BEWARE THE PAST a gripping crime thriller with a huge twist)
Conversion options changed from defaults:
  output_profile: u'generic_eink'
  pdf_sans_family: u'MS Shell Dlg 2'
  pdf_serif_family: u'MS Shell Dlg 2'
  verbose: 2
  cover: u'C:\\Users\\Yang\\AppData\\Local\\Temp\\calibre__ho8wr\\euikjk.jpeg'
  read_metadata_from_opf: u'C:\\Users\\Yang\\AppData\\Local\\Temp\\calibre__ho8wr\\bh7mhd.opf'
Resolved conversion options
calibre version: 4.10.0
{'allow_conversion_with_errors': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\Yang\\AppData\\Local\\Temp\\calibre__ho8wr\\euikjk.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x061B1B10>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x061B1D10>,
 'page_breaks_before': u'/',
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Yang\\AppData\\Local\\Temp\\calibre__ho8wr\\bh7mhd.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: KFX Input running
on C:\Users\Yang\AppData\Local\Temp\calibre__ho8wr\lfj30x.kfx-zip
Software versions: KFX Input 1.28.0, calibre 4.10, Windows-10-10.0.18362-SP0
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\Yang\AppData\Local\Temp\calibre__ho8wr\lfj30x.kfx-zip
Processing container: B078GWN38X_EBOK.azw
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 99, in convert
  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B078GWN38X_EBOK.azw has DRM and cannot be converted
Python function terminated unexpectedly
  This book has DRM! (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "calibre_plugins.kfx_input.__init__", line 104, in convert
DRMError: This book has DRM!

**Comment by nobananasforyou** [comment]
Download and install this: https://filehippo.com/download_kindle_for_pc/1.16.0.44025.0/

See if it works!

**Comment by ElleKayEm** [comment]
Go back to calibre 4.5 if you want to stick with KFX format.  Or prevent the download of KFX format from Kindle for PC to use the latest version of calibre.  See Method 1 or 2 here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by hyang6039** [comment]
> Go back to calibre 4.5 if you want to stick with KFX format. Or prevent the download of KFX format from Kindle for PC to use the latest version of calibre. See Method 1 or 2 here:
> 
> https://www.mobileread.com/forums/showthread.php?t=283371

I delete and reinstall the older version calibre 4.5, and install the two plugins. It's working now. Thank you very much for your help!

**Comment by ElleKayEm** [comment]
If you're all set, you can close this issue.
